### ISSUE TITLE
[P2] Moving a group doesn't move its children's bodies

### ISSUE THREAD

**Issue by pandavigoureux29** [photonstorm/phaser#1065]
Basically, I have a group, to which I add a Sprite with a P2.Body.

So when I move my group, the sprite is actually moving with it, but its body does not budge an inch. 

See my fiddle about it :
http://jsfiddle.net/pandavigoureux29/x8y9x/

**Comment by avdaredevil** [comment]
If that's the case, how do we move (_rotate_) them in relation to their parent group?
