### ISSUE TITLE
Buttons dont't work on CocoonJS next to images

### ISSUE THREAD

**Issue by polyvision** [photonstorm/phaser#1068]
Hi,

using buttons alone (without any other sprite) works on CocoonJS(2.0.1). But if I add an image to the game. The button disappears (although it's still working) from the screen.

I have an example here: https://www.dropbox.com/s/toygn4u4sgd9nnq/cocoon_js_bug.zip

**Comment by photonstorm** [comment]
I'm afraid I have no immediate solution for this. If it's still happening in 2.3 please contact Ludei and see what they can suggest (if they say we need to fix Phaser, that's fine, just get details on how!)
