### ISSUE TITLE
Tinted sprite does not update graphic when changing frame

### ISSUE THREAD

**Issue by AnderbergE** [photonstorm/phaser#1070]
1) This only happens in CANVAS mode!
2) Create a sprite using either a spritesheet or atlas.
3) Tint it.
4) Try to change sprite frame.

Here is a small codepen with the issue:
http://codepen.io/AnderbergE/pen/GpiAe
(notice that it works if we change frame _and_ tint)

Also see this forum post:
http://www.html5gamedevs.com/topic/8141-tween-atlas-frame-on-ipad/

**Comment by fyyyyy** [comment]
thx for the tint -- fix :+1:

**Comment by photonstorm** [comment]
I'm doubtful this will ever be fixed in Pixi 2, but will leave it open for a little longer.

**Comment by AnderbergE** [comment]
Yup, I can understand that. At least this bug report may help someone who stumble upon this bug.

**Comment by photonstorm** [comment]
Ok, I decided to fix it myself :) All done in dev branch.

**Comment by fyyyyy** [comment]
:+1: :trophy:

**Comment by AnderbergE** [comment]
Lovely, I'll try it out pronto :)
