### ISSUE TITLE
IOS/Android - Chrome - Visibility Change not firing

### ISSUE THREAD

**Issue by nickryall** [photonstorm/phaser#1101]
Seen in Chrome on IOS 7.1 and Android 4.42. Minimising the browser does not pause the game. Audio is not muted.

**Comment by B3nac** [comment]
Tested sound muting on minimized Chrome browser on Android 5.0 and it works. Maybe Android 4.42 specific? Android just yesterday updated to 5.0.

**Comment by photonstorm** [comment]
Closing due to OAP status and unable to currently reproduce.
