### ISSUE TITLE
Loaded Sprite Sheet has no frames when its size is a multiple of 32, using WebGL Renderer

### ISSUE THREAD

**Issue by fardog** [photonstorm/phaser#1121]
Using this code:

```
window.onload = function() {
	var game = new Phaser.Game(320, 568, Phaser.AUTO, '', { preload: preload, create: create });

	function preload () {
		game.scale.maxWidth = 640;
		game.scale.maxHeight = 1136;

		game.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
		game.scale.setScreenSize();

		game.stage.smoothed = false;
		game.load.spritesheet('backgrounds', '/assets/img/background_tiles.png', 64, 64);
	}
	function create () {
		var background = game.add.tileSprite(0, 0, 320, 568, 'backgrounds', 1);
	}
};
```

The background file is attached. If I use a spritesheet that is sized as a multiple of 64, I don't get any frames; the whole sheet loads.

See this screenshot for what is happening:
![screenshot 2014-08-20 22 09 34](https://cloud.githubusercontent.com/assets/2207657/3992048/6e9daa08-28f1-11e4-838d-10a3ada4c67e.png)

The background_tile.png is as follows:
![background_tiles](https://cloud.githubusercontent.com/assets/2207657/3992058/7fee2f9e-28f1-11e4-90b2-61b981305e94.png)

However, if I make this a different size, say each tile is 120px, using this code:

```
window.onload = function() {
	var game = new Phaser.Game(320, 568, Phaser.AUTO, '', { preload: preload, create: create });

	function preload () {
		game.scale.maxWidth = 640;
		game.scale.maxHeight = 1136;

		game.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
		game.scale.setScreenSize();

		game.stage.smoothed = false;
		game.load.spritesheet('backgrounds', '/assets/img/background_tiles.png', 120, 120);
	}
	function create () {
		var background = game.add.tileSprite(0, 0, 320, 568, 'backgrounds', 1);
	}
};
```

And this background_tiles.png:
![background_tiles](https://cloud.githubusercontent.com/assets/2207657/3992072/ab1cd102-28f1-11e4-831a-c19a79953559.png)

…then everything works perfectly. If I try the same with a 128px tile size, then I see the same broken behavior as the 64px tile size.

This is with Phaser 2.0.6, and occurs with the latest version of Firefox and of Chrome, on a 15" Retina MacBook Pro (Early 2013 model).

**Comment by photonstorm** [comment]
I'm going to close this issue off due to inactivity. If you would like to test it against the latest build I'm hopeful you'll find it works as expected now, if not feel free to re-open and throw a zip file at me which we can test locally.
