### ISSUE TITLE
p2.convertCollisionObjects on addPolygon 

### ISSUE THREAD

**Issue by sl45sms** [photonstorm/phaser#1122]
at 2.0.7 the addition of array check (on line 79604) breaks the conversion of tiled object polylines
after comment out the check, works again.

addPolygon: function (options, points) {
        options = options || {};
      //  if (!Array.isArray(points)) {
            points = Array.prototype.slice.call(arguments, 1);
      //  }

**Comment by photonstorm** [comment]
Closing this off due to inactivity / approval of resolution.
