### ISSUE TITLE
android webview can not play back the sound effect

### ISSUE THREAD

**Issue by EricShe** [photonstorm/phaser#1138]
i have create  a webview to open the game, i stored the page to android files directory. i can play it but without sound effect. the android logcat  console only mark down 

08-25 13:04:06.005: E/MediaPlayer(8229): error (1, -2147483648)

the code attach at follow.

function preload() {

```
game.load.image('bullet', 'bullet.png');
 ........
game.load.audio('explode', 'sentry_explode.wav');
```

}

function playsound(){
.....
game.sound.play('explode');
}

**Comment by lovebdsobuj** [comment]
My WebView app doesn't play sounds.

It's my JavaScript 
`<script type="text/javascript">
function PlaySound(path) {
  var audioElement = document.createElement('audio');
  audioElement.setAttribute('src', path);
  audioElement.play();
}
</script>`

It works Remote WebView but not Local.
