### ISSUE TITLE
A easier way to create a sprite by cropping from a big spritesheet

### ISSUE THREAD

**Issue by kaelzhang** [photonstorm/phaser#1140]
I have a very big sprite sheet, and want to create many small sprite body of different size by cropping the sprite sheet. It seems it is not that easy by far.

Is there any method that similar to:

```js
game.add.sprite(x, y, key, sprite_x, sprite_y, sprite_width, sprite_height);
```

or something?

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)
