### ISSUE TITLE
Tiled XML (including compressed) support

### ISSUE THREAD

**Issue by englercj** [photonstorm/phaser#1145]
Right now only the Tiled JSON format is supported. I am working with a large game where the maps are quite large and complex. For example, a single map has the following size chart:

| Format | Size (in KB) |
| --- | --- |
| JSON | 1,420 |
| base64 | 1,097 |
| base64-gzip | 144 |
| base64-zlib | 144 |

As you can see there are obvious size benefits, and since I have quite a few of these maps if I converted to use the base64-gzip verions I could be downloading ~3M of map data instead of ~30M.

When I worked on grapefruit I wrote code to load all the versions of Tiled output. You can see the code that will parse the XML into a js object that mimics the result of `JSON.parse()` on the TIled json format, here:

https://github.com/grapefruitjs/grapefruit/blob/master/src/tilemap/Tilemap.js#L364

The above code needs a few things to decode the base64 and decompress the result. It uses TypedArrays, the native `window.atob` function, and (since the library is compiled with browserify) [zlibjs](https://github.com/imaya/zlib.js).

I would be happy to port this over to Phaser and include polyfils to support the browsers that Phaser supports, or even write this in a plugin (possible?), but I wanted to get your opinion before I did the work.

**Comment by kno10** [comment]
Parsing huge JSONs can also become a noticeable performance bottleneck.
Hence it isn't just about size, but supporting some binary format such as Base64 may reduce load time noticeably. Also, compressing in the native form (bytes) tends to be more efficient than compressing the ascii-json-encoded version.
