### ISSUE TITLE
Adding a TilemapLayer to a group and rotating the group results in unexpected rendering / collision detection

### ISSUE THREAD

**Issue by pBun** [photonstorm/phaser#1149]
After adding a TilemapLayer to a group and rotating the group, the layer clips to the width/height of the canvas. In addition, collision detection seems fail after rotating allowing the controlled sprite to pass through walls with specific angles/directions.

I have a simplified version of the issue in a plinker here:
http://plnkr.co/edit/FlMWWeitsW9W4sgeFZDb?p=preview

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)
