### ISSUE TITLE
IE 11 Fullscreen issues

### ISSUE THREAD

**Issue by dgoemans** [photonstorm/phaser#1163]
In IE 11 on 2 separate games from 2 companies:

1) Text rendering in fullscreen causes IE to crash with an Invalid State Error. Seems that there's a call to *renderSession.context.drawImage* with a *HTMLCanvasElement* as the texture and IE doesn't seem to like that. This seems to be happening on Phaser 2.0.7 ( and not 2.0.5 ). I haven't had time to look into this and hunt down the cause.

2) The pointer position is off only for IE in fullscreen. Currently we have added a hack to the end of *Canvas.getOffset*: *point.x += game.scale.margin.x;*

For now, we'll be disabling fullscreen in IE.

**Comment by photonstorm** [comment]
Closing this off due to inactivity and the fact the fullscreen handling was rewritten extensively (as posted above). If you still find it's happening you're welcome to re-open with a test case we can run.

**Comment by boostermedia** [comment]
Thanks. Haven't had time to test against dev, but the moment we update to Phaser 2.2.x we'll test it again. I'm sure it's fine now :)
