### ISSUE TITLE
onComplete on chained tweens firing off after first tween completes, not the last one

### ISSUE THREAD

**Issue by vorrin** [photonstorm/phaser#1171]
Hello! 

I've found what I reckon is a small bug with tween chaining and 'onComplete' calls. 
Basically, when chaining multiple tweens, and adding an 'onComplete' call on the last one, such call will be fired when the FIRST tween ends, not the last.
The code below should demonstrate the problem (I am using typescript myself, so I haven't tested with this exact code, though):

BasicGame.Game.prototype = {

```
preload: function () {
    this.load.image('cursor', 'cursor.png');
},

create: function () {

    // Creating a sprite, and tweening it in 2 steps, with an onComplete call
    this.someSprite = this.add.sprite(0,50, 'cursor');
    this.game.add.tween(this.position).to({ x: 100 }, 100 , Phaser.Easing.Cubic.In, true).
                to({ x: 200 }, 5000, Phaser.Easing.Cubic.Out, true).
                onComplete.add(function () {
                    console.log('TIMER COMPLETE');
                }, this);
}
```

};

So in this case, unexpectedly, the log message will appear after 100ms, not after 5100ms, which I reckon is not how one would want it to behave. I'm sorry I haven't had time to delve deeper to find out why this is happening exactly, but thought I'd report it, feel free to get in touch if needed. 

Browser is vanilla Chrome, latest version, and as I mentioned this is by coding in Typescript, on the unlikely chance that might have something to do with it. 

Have a nice day! 

PS- I've actually toyed a bit and modified an existing jsfiddle to demonstrate. Phaser version on there is a bit older, but the behaviour is the same http://jsfiddle.net/J5fUE/62/

**Comment by jmp909** [comment]
I'd hope for maybe something like

```javascript
chain = tweenA.chain(tweenB);
chain.onComplete.add(doSomethingFinally, this)
```

currently chain just points to tweenA, rather than a managed chain of tweens

thanks
j
