### ISSUE TITLE
onDown, onUp, and onTap all fire at the same time with touch emulation in Chrome, onUp and onTap never fire in iOS

### ISSUE THREAD

**Issue by lazd** [photonstorm/phaser#1193]
## Test case - Desktop

Add the following code to your Phaser 2.x game:

```js
game.input.onUp.add(function() {
  console.log('UP');
});
game.input.onDown.add(function() {
  console.log('DOWN');
});
game.input.onTap.add(function() {
  console.log('TAP');
});
```

In Chrome, open up the **Developer Tools**, select **Emulation**, and select **Emulate touch screen**. Your cursor should change to a round circle.

Press the mouse button down anywhere within the game canvas, wait a second, then release the mouse button. You'll see `DOWN`, `UP`, and `TAP` all appear at the same time -- when you release the mouse button.

Furthermore, try pressing down in one place, moving the mouse, then releasing (simulating a drag event) -- no events fire at all.

## Test case - Mobile

Additionally, you'll find thing behave oddly on mobile as well.

Try the following on your mobile device or the iOS Simulator in debug mode via Safari.

```js
game.input.onUp.add(function() {
  console.log('UP');
});
game.input.onDown.add(function() {
  console.log('DOWN');
});
game.input.onTap.add(function() {
  console.log('TAP');
});
```

Tap within the game canvas, you'll see `DOWN` the second you touch, but will never see `UP` or `TAP`.

**Comment by photonstorm** [comment]
Closing this one off as it's working perfectly in Chrome and Canary touch emulation as tested today (but maybe wasn't back then!) - all signals dispatch in the correct order, across device, tap only firing if the DOWN/UP was within the threshold.

**Comment by jvinhit** [comment]
Phaser input sprite not working on Android. 
Audio not working on Android webview ( .wav + ogg). 
:(

**Comment by pnstickne** [comment]
@jvinhit Make sure to open up a separate issue for each thing. And let old issues stay old/closed unless there is a need to revive them.

**Comment by photonstorm** [comment]
Agreed, this will never be dealt with as a comment on an already solved issue.
