### ISSUE TITLE
TileMap.addTilesetImage should support BitmapData objects as well as Images

### ISSUE THREAD

**Issue by zacharycarter** [photonstorm/phaser#1200]
Currently addTilesetImage only checks in the games cache for images when the addTilesetImage method is called on a TileMap instance. Would be nice if it could somehow check in the cache for BitmapData objects with the key passed in - or even better yet, allow a BitmapData object to be passed in as the key.

In a scenario where someone is generating a tileset image at runtime, this functionality would come in handy.

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)
