### ISSUE TITLE
Add TypeScript definition to borisyankov/DefinitelyTyped

### ISSUE THREAD

**Issue by armetiz** [photonstorm/phaser#1201]
Hi there,

The [borisyankov/DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) repository is used by IntelliJ to automaticaly add librairy definition to IDE.

I guess this is also used by other tools or in an other way.

If someone have free-times, take a look on [Creating a definition file](http://definitelytyped.org/guides/creating.html) guide.

Regards.

**Comment by photonstorm** [comment]
Going to close this off, sorry. I feel I'd prefer to maintain full control over the defs.
