### ISSUE TITLE
IE continues to load files before it is known that an audio file failed to load

### ISSUE THREAD

**Issue by spayton** [photonstorm/phaser#1212]
In IE (10 & 11 tested), a failed audio file load isn't detected until after other files have continued to load.  Once the error has been detected the fileError function is called on the wrong _fileIndex.

The problem is demonstrated here,  http://jsfiddle.net/stupot/84b6x7s4/

The problem was initially presented in the forum here: 

http://www.html5gamedevs.com/topic/9557-failed-audio-file-request-gets-reported-as-failed-image-request-in-ie/

**Comment by speige** [comment]
Related to this, The following line probably doesn't remove the event listener correctly, but I don't know of any adverse behavior caused by the event listener not being removed.
file.data.removeEventListener('canplaythrough', Phaser.GAMES[this.game.id].load.fileComplete);
