### ISSUE TITLE
Overlapping SoundFX get cut off.

### ISSUE THREAD

**Issue by nickryall** [photonstorm/phaser#1220]
In v2.0.7 I could call play() on the same sound instance in quick succession and the sounds would overlap. In v.2.1.1 the previously played sound now gets cut off. I think this is probably the correct behaviour however I'm seeing this also when setting forceRestart = false. e.g. sound.play( 'explode', 0, 1, false, false );

I've tracked it down to the following lines:

v2.0.7

https://github.com/nickryall/phaser/blob/master/src/sound/Sound.js#L409

v.2.1.1

https://github.com/photonstorm/phaser/blob/master/src/sound/Sound.js#L449

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/overlapping-audio-files/11310/1
