### ISSUE TITLE
Removing a group containing a button does not remove the button

### ISSUE THREAD

**Issue by charliemacisaac** [photonstorm/phaser#1227]
A button added to a group is still active and clickable if the group is removed.

You can test using this repo: https://github.com/charliemacisaac/phaser_group_button_issue

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)

**Comment by clark-stevenson** [comment]
Thanks for the tip about just simply disabling input, that was going to be my next move but I was not sure if it was me to blame.
