### ISSUE TITLE
SpriteBatch and sprite bounds.

### ISSUE THREAD

**Issue by j0hnskot** [photonstorm/phaser#1231]
I used SpriteBatch to see the difference between that and  Group in terms of performance and i found out that sprites created with SpriteBatch , as far as i understand, do not update their bounds .

As a result the outOfBoundsKill (and probably other things that use bounds) does not work.

Is this intended?

**Comment by photonstorm** [comment]
Yes I'm afraid this is the correct behaviour - a side-effect of the SpriteBatch. However it's important, so I've updated the docs to reflect this.
