### ISSUE TITLE
Fix: Uncaught TypeError: Cannot read property '2' of undefined phaser.js:63200

### ISSUE THREAD

**Issue by defcronyke** [photonstorm/phaser#1240]
Sometimes when importing a level from Tiled JSON, the level fails to load with the above error.

I have submitted a pull request which shows how I've fixed this error:
https://github.com/photonstorm/phaser/pull/1241

**Comment by leejarvis** [comment]
@photonstorm I can still reproduce this on both branches when adding a second layer to my tilemap. Should it be fixed?

**Comment by AeonFr** [comment]
My tilemap has only one layer and this error is appearing. Where can I find the dev version to test with it?

**Comment by ManzDev** [comment]
I have this problem.

Fixed put `firstgid`, `imagewidth`, `imageheight` and `image` lost properties in tileset JSON.

I supposed that reason is malformed JSON, no embed tileset or custom build tileset.
