### ISSUE TITLE
jsdoc {integer} type-specialization

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser#1252]
This is not a "bug" per-se but, for fields and parameters where such makes sense, I propose annotating the JSDoc type as `{integer}` instead of `{number}` as this imposes additional useful context and type-refinement.

There is no natural distinction in JavaScript itself - but the semantic meta-information added by JSDoc is outside of JavaScript's type-system anyway. Using `{integer}` adds additional and useful information (in some cases a non-integer number just doesn't make sense) and enables a method to correctly, per it's method documentation, treat a "number" as an integer.

**Comment by photonstorm** [comment]
Closing this off as it's something you've been doing bit-by-bit anyway, and will be an on-going effort really.
