### ISSUE TITLE
creating multiple games and deleting them

### ISSUE THREAD

**Issue by hankeypancake** [photonstorm/phaser#1260]
Hi. I probably use phaser in a way it's not meant to be used, but since the 2.1.3 release I've been getting an issue where if I dynamically create more than 4 games, they only render as totally black when I use WebGL. If I use the canvas renderer everything is fine.

here's a (shitty) codepen to illustrate the issue:
http://codepen.io/hankeypancake/pen/oHgxb

Am I not destroying the games properly or is this a totally wrong way of doing this?

Chrome console tells me:
'WARNING: Too many active WebGL contexts. Oldest context will be lost.'

**Comment by photonstorm** [comment]
Thanks for your test case, it really helped me isolate and fix this!
