### ISSUE TITLE
New State Manager draft

### ISSUE THREAD

**Issue by photonstorm** [photonstorm/phaser#1268]
Dumping my thoughts here for discussion.

Note: This is a Phaser 2.2 level change, not part of 2.1.x.

At the moment Phaser states work but are too limited in their nature. There is also one core game loop that is responsible for updating all of the key systems, such as the Tween manager, Sound manager, etc.

The proposal being drafted involves two changes:

1) The State now owns the systems, not the core Game. So a State has its own Tween Manager, Sound Manager, etc that belong exclusively to it. Each Manager is modified to allow multiple instances of it to exist.

2) States will be able to spawn Child States. A Child State is defined in two ways:

2a) It runs in parallel with the parent State and *any other Child States*.
2b) It *optionally* shares the same system managers as its parent, or it has its own.

Child States will be defined in a similar way that States are currently. The difference being that you can stipulate which managers are created for them. Equally a Child State will be able to be timesliced: that is you can define its rate of update. They can also be paused, resumed and destroyed.

To put this into a game context:

A Game State could have several Child States that handle different, but specific tasks, that you may require to happen during your game without closing the Game State itself.

For example an in-game shop, a settings panel, an inventory selection screen, a cut-scene, a level selection screen, a game world map. These are game-level events that need to occur without the Game being destroyed. In some cases the game will need to pause when they are active. In others the game can carry on running in the background.

## Potential Issues

Some managers aren't good at sharing resources/events, for example the Input Manager.

It's a big rewrite.

**Comment by photonstorm** [comment]
I'm closing this off in order to tidy up the issues list. This will form part of Phaser 3 now.

**Comment by noffle** [comment]
Are there docs/proposals somewhere for the new Phaser 3 state manager?

**Comment by photonstorm** [comment]
Not yet, we're still discussing internally - will open up soon, likely on the phaser3 repo.
