### ISSUE TITLE
Nearest-filtered CSS scaling in Chrome is broken

### ISSUE THREAD

**Issue by englercj** [photonstorm/phaser#1293]
Right now if you try to use the scale manager to do scaling for you, but you need nearest filtering it doesn't work in Chrome.

This is a Chrome bug, not a Phaser bug, and is being tracked here:

https://code.google.com/p/chromium/issues/detail?id=134040

I just wanted to raise some awareness here, and open an issue so it can be tracked since it does effect Phaser right now. I am having to manually scale the world instead of using the css auto scaling provided by the scale manager until this is fixed.

**Comment by photonstorm** [comment]
They've also (finally) added proper support for `image-rendering: pixelated` which works beautifully across canvas and webgl. It's in Canary right now, so hopefully will hit Chrome at some point soon. 

Going to close this off as it's technically "resolved", even if most of the public can't see it yet.
