### ISSUE TITLE
Arc() Function broken in Phaser 2.1.3 (Pixi 2.0)

### ISSUE THREAD

**Issue by JakeSiegers** [photonstorm/phaser#1299]
The arc() function crashes when trying to use it in the latest version of Phaser (2.1.3) / Pixi 2.0) - uncompressed for debugging purposes

    [Error] TypeError: null is not an object (evaluating 'this.currentPath.shape')
	arc (phaser.js, line 16026)
	update (game.js, line 610)
	update (phaser.js, line 18036)
	update (phaser.js, line 24522)
	updateRAF (phaser.js, line 42978)
	_onLoop (phaser.js, line 42964)

I'm using this piece of code in game.js at line 610 ("charatcers[n].healthBar" is a Graphic Object & characters[n].health is always between 0-1)

    characters[n].healthBar.arc(0,0,35,Math.PI/4,Math.PI/4-(Math.PI/2)*characters[n].health,true);

I can draw any other shape supported, just not arc().

the arc works fine when using <= phaser 2.1.2 / Pixi 1.6.1, but not the latest release.

Also, here's what it looks like when the arc function is working. The red arc is the first one drawn, and is the code above. (Just in case you need a visual?)
![Image of the arc]
(http://i.imgur.com/aKVP9x7.png)

**Comment by JakeSiegers** [comment]
Well, the function works on the newest versions of Phaser, but it tries to complete the arc (like it's a open shape?), and always draws a straight line from the start and end of the arc. 

Is there a way to stop this? It doesn't appear to be documented anywhere, so I assume it's not supposed to do that and it's a new bug?

**Comment by photonstorm** [comment]
Closing this off as I can confirm it works properly. See the following example:

```
var game = new Phaser.Game(800, 600, Phaser.AUTO, 'phaser-example', { create: create });

function create() {

    var graphics = game.add.graphics(game.world.centerX, game.world.centerY);

    //  Our first arc will be a line only
    graphics.lineStyle(8, 0xffd900);
    graphics.arc(0, 0, 135, game.math.degToRad(0), game.math.degToRad(90), false);
    
    //  As we wish to draw a 2nd arc on the SAME Graphics object, we need to move the drawing operation
    graphics.moveTo(-100, -100);

    //  This will reset the lineStyle
    graphics.lineStyle(0);

    //  And this draws a filled arc
    graphics.beginFill(0xFF3300);

    //  Note the 'true' at the end, this tells it to draw anticlockwise
    graphics.arc(-100, -100, 135, game.math.degToRad(0), game.math.degToRad(90), true);

    graphics.endFill();

}
```
