### ISSUE TITLE
Animation Loops Specified

### ISSUE THREAD

**Issue by austinh** [photonstorm/phaser#1329]
Right now when you use .play() on an animation, loop is only a boolean value. Loop in this case means repeat infinitely. What if we changed this to instead be a number of loops, or repeats. So say I want an animation to play 3 times before ending, so I would set loops = 3. If i wanted an infinite loop I would use -1 in which case the animation will run forever. It would default to 1 loop like it does now.

I think this is a little more flexible and definitely useful.

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)
