### ISSUE TITLE
Loader Async

### ISSUE THREAD

**Issue by austinh** [photonstorm/phaser#1330]
Right now I believe the Loader loads asset synchronously. It waits for .onFileComplete() and then calls .nextFile().

It would be more performant if the loader queued all the files to be loaded asynchronously. This would be great for loading a lot of assets, especially for web servers utilizing SPDY for fast async downloads.

I think this can be done without changing any API or needing to wait for 3.0, yes?

And then for 3.0, as a feature request, loading via XHR2, for file progress support for more accurate loading bars, with a setback to tag loading (I believe this is already on the roadmap)

**Comment by photonstorm** [comment]
Closing as it's now in 2.3 :)
