### ISSUE TITLE
IE 11 

### ISSUE THREAD

**Issue by brejep** [photonstorm/phaser#1348]
Phaser version: v2.1.3 "Ravinda" - Built: Thu Oct 23 2014 12:33:04

Windows 8.1, Internet Explorer 11.0.9600.17416

Graphics: NVIDIA GeForce GT 640M

IE compatibility mode set to Edge.

If I set the game to Phaser.AUTO rendering mode, the screen flickers rapidly and no buttons work. There are no error messages. 

I do get the following warning:
EBGL11135: getContext: Context attribute premultipliedAlpha:false is not currently supported

I know there were previous issues with IE11 and webgl but I thought they were resolved or  automatically fell back to canvas mode. Is this not the case?

Game works fine on IE11 with Phaser.CANVAS renderer.

**Comment by photonstorm** [comment]
I'm afraid I'm going to close this one off for now. I'm not sure it will be addressed in Pixi 2 (if it is, I'll merge the fix for sure). Alternatively if they fix in Pixi 3, and we upgrade to that, it will be covered there. But it won't be fixed directly in the Phaser source, sorry.

**Comment by photonstorm** [comment]
Just for reference however the Pixi issue is https://github.com/GoodBoyDigital/pixi.js/issues/1201 (as the link above points to the phaser repo)

**Comment by tom2strobl** [comment]
FYI: They say it's fixed in v3, so as soon as we have a PIXIv3 build in Phaser it should be fixed here too.  https://github.com/GoodBoyDigital/pixi.js/issues/1201
