### ISSUE TITLE
Phaser.WEBGL doesn't move tilemap (CANVAS works,but slow)

### ISSUE THREAD

**Issue by KurtVanHal** [photonstorm/phaser#1350]
Hi guys, 

I'm having some difficulty getting my map working. When using the Phaser.CANVAS everything works, but when scrolling through the map there is a lot of lag. When using the Phaser.WEBGL the map doesnt render when I move my player. Any thoughts...

This is the basic code (very simple). It uses 1 layer (30_25 (32_32 tile)) 

var game = new Phaser.Game(800, 600, Phaser.WEBGL, 'phaser-example', { preload: preload, create: create, update: update, render: render });

function preload() {

```
game.load.tilemap('map', 'assets/tile.json', null, Phaser.Tilemap.TILED_JSON);
game.load.image('tiles', 'assets/tiles.png');
game.load.spritesheet('player', 'assets/player.png',60,60,5);
```

}

var map;
var layer;

var cursors;
var sprite;

function create() {

```
game.physics.startSystem(Phaser.Physics.ARCADE);
game.stage.backgroundColor = "#000000";
map = game.add.tilemap('map');

map.addTilesetImage('tiles', 'tiles');

layer = map.createLayer('Tilelaag 1');


layer.resizeWorld();

 map.setCollision([48]);

sprite = game.add.sprite(450, 1500, 'player');
sprite.anchor.setTo(0.5, 0.5);
game.physics.enable(sprite);
sprite.body.collideWorldBounds = true;



game.camera.follow(sprite);

cursors = game.input.keyboard.createCursorKeys();
```

}

function update() {

```
game.physics.arcade.collide(sprite,layer);

sprite.body.velocity.x = 0;
sprite.body.velocity.y = 0;


if (cursors.left.isDown)
{
    sprite.body.velocity.x = -200;
}
else if (cursors.right.isDown)
{
    sprite.body.velocity.x = 200;
}

if (cursors.up.isDown)
{
    sprite.body.velocity.y = -200;
}
else if (cursors.down.isDown)
{
    sprite.body.velocity.y = 200;
}
```

}

function render() {

}

Thx in advance

**Comment by Tajnymag** [comment]
Has anything changed since the last post? I am experiencing the same problem. On computer the scrolling is not smooth but the game is playable. Unfortunately I can't say the same about phone experience. When the camera is not moving I get 60fps but at the moment the camera moves, the framerate drops to 4fps.

**Comment by photonstorm** [comment]
The Tilemap updates talked about in this thread have been part of Phaser for over a year now, and haven't updated since then.
