### ISSUE TITLE
Loading JSON textureatlases Cross domain IE9

### ISSUE THREAD

**Issue by winknudge-tomm** [photonstorm/phaser#1361]
When loading JSON files there is an IF statement for the useXDomainResponse variable for IE9 cross domain issues. When loading in JSON files for textureatlases, in the fileComplete function case 'textureatlas' there is only an xhr request.

Quickly fixed by defining "_this = this" at the start of the function and adding the following into the json case within the textureatlas case.

<pre>
if (this.useXDomainRequest && window.XDomainRequest)
                        {
                            this._ajax = new window.XDomainRequest();

                            // XDomainRequest has a few quirks. Occasionally it will abort requests
                            // A way to avoid this is to make sure ALL callbacks are set even if not used
                            // More info here: http://stackoverflow.com/questions/15786966/xdomainrequest-aborts-post-on-ie-9
                            this._ajax.timeout = 3000;

                            this._ajax.onerror = function () {
                                return _this.dataLoadError(_this._fileIndex);
                            };
                               
                            this._ajax.ontimeout = function () {
                                return _this.dataLoadError(_this._fileIndex);
                            };

                            this._ajax.onprogress = function() {};

                            this._ajax.onload = function(){
                                return _this.jsonLoadComplete(_this._fileIndex);
                            };

                            this._ajax.open('GET', this.baseURL + file.atlasURL, true);

                            //  Note: The xdr.send() call is wrapped in a timeout to prevent an issue with the interface where some requests are lost 
                            //  if multiple XDomainRequests are being sent at the same time.
                            setTimeout(function () {
                                _this._ajax.send();
                            }, 0);
                        }
                        else
                        {

                            this.xhrLoad(this._fileIndex, this.baseURL + file.atlasURL, 'text', 'jsonLoadComplete', 'dataLoadError');
                            // this.xhrLoad(this._fileIndex, this.baseURL + file.atlasURL, 'text', 'jsonLoadComplete', 'dataLoadError');
                        }
</pre>

Not sure if this is a correct fix but may aid in future.

**Comment by photonstorm** [comment]
A fix for this was merged tonight into the dev branch, so xdr will be used for everything *if* enabled.
