### ISSUE TITLE
p2 physics -> reset Collision? (improvement/suggestion)

### ISSUE THREAD

**Issue by jpcloud** [photonstorm/phaser#1362]
I ran into the following problem using the p2 physics:

I have a sprite that collides with everything (default state), now an event happens in the game where I want this sprite to temporarily not collide with anything. After a few seconds I want collision again.
 
To disable collision there is 
sprite.body.clearCollision(true);

But to enable default collision again I have to do this:
sprite.body.data.shapes[0].collisionGroup = 1;
sprite.body.data.shapes[0].collisionMask = 1;

(This works fine, assuming the sprite only has one shape.)

I would like a function, that resets collision to the initial state (the state which objects have right after setting them up with p2 physics and a shape) because I don't like to "internal" properties"set it to "magic numbers".

Is the solution maybe to implement a function on the p2 body like "resetCollision" that iterates the shapes and sets collisionGroup & collisionMask to 1?

Thanks

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)
