### ISSUE TITLE
problem with phaser and android 4.4

### ISSUE THREAD

**Issue by steve48911** [photonstorm/phaser#1387]
hello everyone..
hope someone can help me... i create a simple background and loaded it with phonegap on mobile and table.... on table fps is about 30 and on mobile "SAMSUNG GALAXY GT-I9100" works well...but on my mobile "SAMSUNG GALAXY GT-I9504" fps is to 7 with just a background..
how is it possible? the only thing i noticed is that version of android...

anybody else have already had this problem? 

someone knows how can i resolve it?

thanks in advance..

**Comment by photonstorm** [comment]
Just to add to what was said above, please try a more recent version of PhoneGap, or even better Intel XDK / CrossWalk, as performance is (apparently) significantly better. Also definitely try it with Phaser 2.3 (currently in dev branch). If you find consistent errors please open a new issue (or re-open this one) with a test-case.
