### ISSUE TITLE
'right' and 'bottom' issue in Phaser.Ellipse.prototype

### ISSUE THREAD

**Issue by nextht** [photonstorm/phaser#1397]
https://github.com/photonstorm/phaser/blob/dev/src/geom/Ellipse.js#L196
     this.width = this.x + value; 
should be changed to:
    this.width = value - this.x;

https://github.com/photonstorm/phaser/blob/dev/src/geom/Ellipse.js#L238
    this.height = this.y + value;
should be changed to:
    this.height = value - this.y;

**Comment by photonstorm** [comment]
Fixed locally in Phaser :)

**Comment by photonstorm** [comment]
Split to a separate issue please.
