### ISSUE TITLE
wordBreak option for wordWrap in Text style

### ISSUE THREAD

**Issue by dai-shi** [photonstorm/phaser#1403]
How is it difficult to implement work-break feature for wordWarp in Text?
Right now, it seems it doesn't wrap long words nor non-latin words without spaces.

**Comment by soldoutactivist** [comment]
I added a word-breaking PR awhile ago: https://github.com/photonstorm/phaser/pull/1811

It's not the "smart" word-breaking that looks for hyphens, etc. But it's a lot better than what's currently going on.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
