### ISSUE TITLE
canplaythrough event not removed when AudioTag sound used

### ISSUE THREAD

**Issue by jounii** [photonstorm/phaser#1405]
Loader does not remove canplaythrough event from audio tag when loading audio if using AudioTag audio. It tries to remove fileComplete function, but there is no such as it's wrapped when attached. This causes "Phaser.Loader fileComplete invalid index 0" errors when audio is played back.

This with phaser 2.1.3 and latest Chrome.

**Comment by photonstorm** [comment]
I believe this was addressed in the Loader update in 2.3.
