### ISSUE TITLE
Audiosprite: fadeIn doesn't work with it

### ISSUE THREAD

**Issue by vorrin** [photonstorm/phaser#1413]
Hello! 

If playing a sound produced by an audiosprite, if you tell it to fadeIn(), it doesn't fade the right sound in, but the beginning of the audiosprite file. 

That is because Phaser.Sound.fadeIn() doesn't really expect to be started from a marker, and just plays the sound with marker '', so from the start. 

I think this could be fixed simply by changing the fadeIn function to pass in the currentMarker, so:

   Phaser.Sound.prototype.fadeIn =  function (duration, loop, marker) {

                        if (typeof loop === 'undefined') { loop = false; }

                if (this.paused)
                {
                    return;
                }

                this.play(this.currentMarker, 0, 0, loop);

                this.fadeTo(duration, 1);

            },

Not sure if that would create any problem elsewhere, but I reckon not.

Have a nice day!

**Comment by photonstorm** [comment]
Couldn't wait any longer, have merged this in myself :)

**Comment by koraysels** [comment]
SO canb anyone tell me how I can fadein a marker from an audio sprite ? 

I am having touble doing this.. 

this does not work
```
        this.beats = this.game.add.audioSprite('beats');
        this.beats.allowMultiple = true;

        this.randomBeat = this.beats.sounds[this.game.rnd.pick(Object.keys(this.beats.sounds))];
        this.randomBeat.fadeIn(1000);

```
