### ISSUE TITLE
Rotation prop missing on objects loaded from object layer in a tilemap.

### ISSUE THREAD

**Issue by nicroto** [photonstorm/phaser#1433]
Hi,

Thanks for the awesome framework.

I think I've covered the issue pretty well in [this thread](http://www.html5gamedevs.com/topic/10897-rotation-prop-missing-on-objects-loaded-from-object-layer-in-a-tilemap/).

Regards,
Nikolay Tsenkov

**Comment by photonstorm** [comment]
The reason it's missing is that Phaser was built against Tiled 0.9. The `rotation` property is a brand new feature and didn't exist when the TilemapParser was written.

However I've just added it tonight, so please give the dev branch a test.
