### ISSUE TITLE
Setting loop=false to tween, results into infinite repeat

### ISSUE THREAD

**Issue by netgfx** [photonstorm/phaser#1443]
While this is correct: 
var tween = game.add.tween(item).to({width:100}, duration, Phaser.Easing.Linear.None, true, 0, 0);

When writing it like this:
var tween = game.add.tween(item).to(obj, duration, Phaser.Easing.Linear.None, true, 0, false);

results in infinite looping.

**Comment by Firanolfind** [comment]
Hi @photonstorm, what's the difference between loop and repeat params? They behave same way except different callbacks fired.

**Comment by JavoMostro** [comment]
var tween = game.add.tween(item).to(obj, duration, Phaser.Easing.Linear.None, true, 0, true, true);
