### ISSUE TITLE
mouse events fail after sprite removed from parent and added again

### ISSUE THREAD

**Issue by hayesmaker** [photonstorm/phaser#1448]
Hi, I'm making a solitaire card game in Phaseer.  

I have a problem when cards are being dragged and dropped in the game.
I might be over complicating things, but couldn't think of a better way: 

Given I have 3 cards dragged to pile, eg. 7hearts, 6clubs, 5diamonds (7h, 6c, 5d)

I want to be able to drag 6c & 5d together and drop them on another pile.  

To implement this, when the 6c drag start is detected, I add the 5d as a child of the 6c sprite.

When they are dropped on the other pile, I then removeAllChildren from 6c sprite, and re-add the 5c sprite to the game. As it was before. and re-enable drag on it.

The trouble is, after this process the 5c becomes invisible to the mouse, and only the 6c is draggable.

Could this be a bug in the framework, a problem with my code.. or can anyone think of a workaround which might help?

The important code for this functionality is below:

```
        onDragStart: function(sprite) {
            console.log('{Card} onDragStart :: pileCardsLen=', this.pileCards.length);
            var self = this;
            if (this.pileCards.length) {
                this.attachPiledCards();
            }
        sprite.bringToTop();
        self.cardPicked.dispatch(self);
        this.dragInterval = setInterval(function() {
          self.onDragUpdate(sprite);
        }, 100);
       },

      attachPiledCards: function() {
        var i, piledCard, len;
        len = this.pileCards.length;
        for (i = 0; i < len; i++)
        {
          piledCard = this.pileCards[i];
          console.log('{Card} attachPiledCards :: pileCardName= ', piledCard.name);
          //piledCard.disableClick();
          //piledCard.disableDrag();
          var sp = piledCard.sprite;
          this.sprite.addChild(sp);
          this.sprite.tint = 0.2 * 0xff0000;
          sp.x = 0;
          sp.y = 17 + (i * 17);
        }
      },

      deattachPiledCards: function() {
        var i, piledCard, len;
        len = this.pileCards.length;
        this.sprite.removeChildren();
        console.log('{Card} deattachPiledCards :: len', len);
        for (i = 0; i < len; i++)
        {
          piledCard = this.pileCards[i];
          var sp = piledCard.sprite;
          this.game.stage.addChild(sp);
          sp.x = sp.x + this.sprite.position.x;
          sp.y = sp.y + this.sprite.position.y;
          //this.sprite.tint = 0xffffff;
          piledCard.softEnableDrag();
        }
      },
```

**Comment by photonstorm** [comment]
Sorry it's taken a while to respond to this, but it's more the sort of question best suited for the forum or stackoverflow than the issues list. If you can create a small reproducible test case that shows a bug in effect then we'll happily investigate.

I notice you're adding children directly to the stage for some reason, which is outside the boundary of the game world, so it may be that this isn't helping matters. Also you don't need to remove a child from a Group before adding it to another one - just add it immediately to the other Group and it will re-parent itself, stopping it from becoming unparented.
