### ISSUE TITLE
the order of overlap callback seems not working properly

### ISSUE THREAD

**Issue by wayou** [photonstorm/phaser#1453]
i have the following code witch is taken from [this tutorial](http://www.photonstorm.com/phaser/tutorial-making-your-first-phaser-game):

```js
game.physics.arcade.overlap(player,stars,collectStars,null, this);
```

and then in the `collectStars` callback, the code looks like the following:

```js
 function collectStars(p,s){
        s.kill();
    }
```
as expected, the star will be killed.

and then i changed the order passing to the overlap to:

```js
game.physics.arcade.overlap(stars, player,collectStars,null, this);
```

this time, still the star is killed. but according to the [documentation](http://docs.phaser.io/Phaser.Physics.Arcade.html#overlap):

> An optional callback function that is called if the objects overlap. The two objects will be passed to this function in the same order in which you specified them.

so actually, in the second situation the `s.kill();` should kill the player instead of the star.

where am i wrong?

**Comment by wayou** [comment]
I found the answer from the documentation.
> unless you are colliding Group vs. Sprite, in which case Sprite will always be the first parameter

**Comment by mlms13** [comment]
I just ran into the same issue. The collide callback mentions the "Group vs Sprite" part, but there's no mention of it in the overlap callback documentation.

**Comment by photonstorm** [comment]
True, this is now added to the overlap jsdocs in dev branch.
