### ISSUE TITLE
game.world.setBounds doesn't works

### ISSUE THREAD

**Issue by nextht** [photonstorm/phaser#1455]
/phaser-examples-master/examples/camera/basic follow.js

I change the examples to the following code, I change  game.world.setBounds(320, 320, 1000, 680); but the player will not be limit in the bounds, i still can move to outside the bounds.

I found two ways to workaround:

A: Make game.physics.p2.reset(); after game.world.setBounds(320, 320, 1000, 680);
B: Make game.world.setBounds(320, 320, 1000, 680); before game.physics.startSystem(Phaser.Physics.P2JS);

I check the code of game.world.setBounds, i found game.physics.setBoundsToWorld(); already be called, so i think maybe we should use reset to replace setBoundsToWorld?

	var game = new Phaser.Game(800, 600, Phaser.WEBGL, 'phaser-example', { preload: preload, create: create, update: update, render: render });

	function preload() {
		game.load.image('background','assets/tests/debug-grid-1920x1920.png');
		game.load.image('player','assets/sprites/advanced_wars_land.png');
	}

	var player;
	var cursors;

	function create() {
		game.add.tileSprite(0, 0, 1920, 1920, 'background');
	
		game.physics.startSystem(Phaser.Physics.P2JS);
		game.world.setBounds(320, 320, 1000, 680);
		//game.physics.p2.reset();

		player = game.add.sprite(game.world.centerX, game.world.centerY, 'player');
		game.physics.p2.enable(player);

		cursors = game.input.keyboard.createCursorKeys();
		game.camera.follow(player);
	}

	function update() {
		player.body.setZeroVelocity();
		if (cursors.up.isDown)
		{
			player.body.moveUp(300)
		}
		else if (cursors.down.isDown)
		{
			player.body.moveDown(300);
		}
		if (cursors.left.isDown)
		{
			player.body.moveLeft(300);
		}
		else if (cursors.right.isDown)
		{
			player.body.moveRight(300);
		}
	}

	function render() {
		game.debug.cameraInfo(game.camera, 32, 32);
		game.debug.spriteCoords(player, 32, 500);
	}

**Comment by photonstorm** [comment]
This is now fixed in dev.
