### ISSUE TITLE
Audio not working with firefox 35

### ISSUE THREAD

**Issue by elennaro** [photonstorm/phaser#1460]
Steps to reproduce:

1) Download and install [firefox beta](https://www.mozilla.org/en-US/firefox/channel/)
2) Open [play music](http://examples.phaser.io/_site/view_full.html?d=audio&f=play+music.js&t=play%20music) or any other [example](http://examples.phaser.io/index.html)

Error displayed: An unknown error occured while processing decodeAudioData. (view_full.html)

**Comment by Nidre** [comment]
@photonstorm 

Reviving the dead ticket but I've some information about the issue.

This regularly happens with Firefox Developer Edition(47.0a2) (Haven't checked the regular one).

It has a pattern;
if you refresh the game multiple times (not necessarily frequently), every 15-20 times maybe, Firefox starts failing decoding both and audio. I believe this is some sort of issue with Firefox. Restarting Firefox fixes the problem.

**Comment by photonstorm** [comment]
@Nidre  Thanks for the comment, but to be honest that information isn't much use, sorry :) (there's nothing I can actually debug, it sounds like FF just being a dick.. but who knows?)

**Comment by elennaro** [comment]
@Nidre File a ticket to Firefox (https://bugzilla.mozilla.org/), they usually fix such things quite in a decent time.
