### ISSUE TITLE
firefox element.events{onInputDown, onInputUp} are fired twice on firefox os

### ISSUE THREAD

**Issue by elennaro** [photonstorm/phaser#1464]
phaser v2.2.1 "Danabar"
firefox OS >= 1.4

It's easy to reproduce on emulator in WebIDE.

P.S. onInputUp.addOnce is not the solution in case I am makin the trigger button.

**Comment by photonstorm** [comment]
I'm afraid my recommendation for this is going to be to disable the mouse input handler on FirefoxOS - you can do this via `game.input.mouse.enabled = false`. This should stop all duplicate events firing.

In the meantime I've put this down as something to look at in Phaser v3 (Firefox OS specifically)

**Comment by netgfx** [comment]
Sorry to raise the dead, but I'm seeing this on Phaser v3 as well. @photonstorm

**Comment by photonstorm** [comment]
@netgfx this needs opening as a new issue really - although Firefox OS is dead and abandoned, so I'll need to know what device / OS it actually is you're trying this on?

**Comment by netgfx** [comment]
@photonstorm sorry for the confusion, my case is happening on Firefox Browser version `70.0.1` if there is another issue about firefox browser I'm happy to report there as well.

**Comment by photonstorm** [comment]
@netgfx this is was about Firefox OS, so if you're talking about the browser, and there's definitely no plugins or hardware causing it, it needs to be opened in a new issue
