### ISSUE TITLE
tween yoyo delay

### ISSUE THREAD

**Issue by DreadKnight** [photonstorm/phaser#1469]
Delay no longer working between the loops of a yoyo tween, just at start.

In version 2.1.3 I was using this for fading something in and out once in a while, like the WASD keys sprite over the arrow keys sprite in this prototype http://gamejolt.com/games/adventure/frank-in-shirt/40025/

I've included a sample of current behaviour http://jsfiddle.net/DreadKnight/choqtrn5/1/

**Comment by photonstorm** [comment]
This is fixed in the dev branch.
