### ISSUE TITLE
Clipped sound effect playblack

### ISSUE THREAD

**Issue by UglyDuckling2k** [photonstorm/phaser#1471]
I have a problem which affects all browsers (IE a bit more). When i play a sound effect with a short duration (click effects for example) the sound effect sometimes is clipped or does not play at all.

**Comment by UglyDuckling2k** [comment]
Is anyone else experiencing these problems?

**Comment by photonstorm** [comment]
If there is any latency involved in starting playback of the audio (i.e. decoding time, or seeking within a larger audio sprite) then it's entirely possible the timer will assume the sound has finished playing before it has even begun.

I'm not sure of your exact set-up - this can be very specific to the actual audio files being used and the way they're encoded, so we'll need a proper test case to investigate further including the audio causing the problem. Feel free to re-open this if you can provide one.

**Comment by photonstorm** [comment]
Actually I've just pushed up a change to the Sound class that should help with this issue massively.
