### ISSUE TITLE
arcade.moveToPointer with maxTime makes for crazy sprite positions

### ISSUE THREAD

**Issue by AnderbergE** [photonstorm/phaser#1472]
Setup:
* A world that is larger than what the camera is showing (I have a tilemap with 640 x 2000 and a camera with 640 x 640).
* A sprite that is put at the "bottom" of the world (ex position 320 x 1500).
* Call game.physics.arcade.moveToPointer using a maxTime argument (ex 
game.physics.arcade.moveToPointer(sprite, 0, game.input.activePointer, 300)).

Result
The sprite will go berserk and spin around the active pointer.

Possible origin for issue:
The function Phaser.Physics.Arcade.distanceToPointer does not use world coordinates for the supplied pointer, instead it uses camera centric:
        this._dx = displayObject.x - pointer.x;
        this._dy = displayObject.y - pointer.y;

Possible solution:
        this._dx = displayObject.x - pointer.worldX;
        this._dy = displayObject.y - pointer.worldY;

(Note that Phaser.Physics.Arcade.angleToPointer uses world coordinates:
        this._dx = pointer.worldX - displayObject.x;
        this._dy = pointer.worldY - displayObject.y;
)

**Comment by photonstorm** [comment]
Thanks, this is now fixed in the dev branch.

**Comment by AnderbergE** [comment]
That's great!
