### ISSUE TITLE
Tiles with sprites larger than nominal tile width are cropped right/down

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser#1476]
This is a stub issue for the behavior discussed in https://github.com/photonstorm/phaser/issues/1439#issuecomment-67734788

It probably relates to using the nominal (vs. actual) tile size measurement when drawing and/or computing the area to update.

**Comment by photonstorm** [comment]
I wonder if an easy fix for this might be to scan all the tilesets used on a layer and calculate the largest width / height used across all of them. Then use these values to calculate the update area dimensions.

**Comment by photonstorm** [comment]
In order to keep the Github issues clear this feature request has been moved to the [Phaser 3 wishlist](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread/).
