### ISSUE TITLE
sound problem on some devices

### ISSUE THREAD

**Issue by Erik3000** [photonstorm/phaser#1477]
hello, I have problems with sounds on some devices

sound is loaded like this: 
game.load.audio('explodeSoundBomb', ['assets/audio/bomba.wav', 'assets/audio/bomba.mp3']);
this.soundExplosionBomb = game.add.audio('explodeSoundBomb', 1, false);
this sound plays when user hit bomb in game and bomb explodes

and played like this:
this.soundExplosionBomb.play();

I have problem on two devices:
HTC Desire Z running Android 2.3.3 (tested on Dolphin and standard browser)
- when I enter new level on my game, background music is playing, and it is playing all the time
- bomb explosion sound plays normally at begginig, but after I hit bomb several times (this sound plays several times), sound stops playing at all

Samsung Galaxy S running CyanogenMod Android 4.1.1 (tested on standard browser)
- when I enter new level on my game, background music is playing
- then I hit bomb and sound of bomb explosion mentioned earlier plays, but it stops background music; since then I hear only bomb explosion sound

I dont know where could be the problem, whether I am doing something wrong, or there is bug in framework or there is problem in operating system. Do you have any ideas ?

Thank you for your help

**Comment by celisoft** [comment]
I also have the problem on Xbox360 (sounds stop after few times) and on Wii U (no sound).

**Comment by photonstorm** [comment]
Does it throw any kind of error, or just not play? (should be easy enough to debug Android, less so I expect for xbox/wii u)

**Comment by photonstorm** [comment]
Are you using Audio Sprites for this? If not, you probably ought to be - I'm highly doubtful Android 2.x can play multi-channel audio at all, so you're probably running out of sound channels as the previous effects lock onto the old ones. For Android 2.x (and even 4.x in *stock browser*) I would only ever use 1 single audio file personally.

**Comment by photonstorm** [comment]
I've just pushed up some changes to the Sound class which may help in these cases (if the browser can use Web Audio). For legacy audio, see my comment above. I would need actual errors / test cases if the recent changes didn't help.
