### ISSUE TITLE
Incremental search on http://docs.phaser.io/

### ISSUE THREAD

**Issue by ggarek** [photonstorm/phaser#1478]
It would be very helpful to have incremental search in dropdowns on [docs page](http://docs.phaser.io/) (Namespaces, Classes, GameObjects etc).

Example behaviour: 
1. User clicks on Classes dropdown
2. Popup is shown up (new: popup has empty text input element within it)
3. User can scroll down and then select particular item
4. User can enter some text within input (search term: possible with errors, incomplete, only capital letters etc)
5. List items are filtered using text in aforementioned input as filter.

I think it would be very useful timesaving feature for users, because i personally very often use docs page and selecting particular item become tedious thing to do :sweat_smile: 

Thanks! Awesome framework! Keep going, you are doing great good! :+1:

**Comment by pnstickne** [comment]
@ggarek Feel like writing it? :)

Currently this is one of those "missing features" with the standard jsdoc templates. It can be added entirely client side - albeit with a larger download footprint - by dumping the jsdoc structure into JavaScript/JSON and then searching (via JS) with links to the generated pages..

..that being said, the "next" generation jsdoc template (which uses a different approach) should support such.

To start this endeavor, look through https://github.com/photonstorm/phaser/tree/master/resources/docstrap-master

**Comment by photonstorm** [comment]
We're a bit limited until the new jsdoc template lands unless someone wants to recode the current template for us!

**Comment by ggarek** [comment]
I have some thoughts on how search experience could be enhanced on docs site. I will find some time to code my ideas that you could test it. 
I will post here as soon as i get worthy results.

**Comment by photonstorm** [comment]
Going to close this off for now - if someone would like to submit a PR that'd be great, but I won't have time to do this personally, sorry.
