### ISSUE TITLE
extend emitter scaleData Array

### ISSUE THREAD

**Issue by inkfood** [photonstorm/phaser#1481]
I easily extend the scaleData array by adding an other equation at the end/start of it. Seems to work pretty well as long as the live span of a particle is long enough to play trough the scaleData array.

Double checked the Phaser code to make sure it will not cause any errors. Seems good to me, can anyone please let me know if I'm right?? Rich?

P.S.
The emitter docs on the http://docs.phaser.io/Phaser.Emitter.html is broken, please fix. Thanks

**Comment by photonstorm** [comment]
What you are doing sounds fine to me @inkfood
