### ISSUE TITLE
Use of Phaser.Text throws a nasty exception in IE9, IE10 and FF10

### ISSUE THREAD

**Issue by kanecko** [photonstorm/phaser#1482]
Using IE9 or IE10 on Win7 in Standards mode. Tested on Phaser 2.2.1.
**Sample:** http://codepen.io/anon/pen/PwGzgq

**What should happen:** "FPS: N" should appear at the top-left corner and a "test" text in the middle-ish of the green rectangle.
**What happens instead**
*IE9:*
SCRIPT5022: DOM Exception: INDEX_SIZE_ERR (1) 
index.html, line 1 character 1
*IE10:*
SCRIPT5022: IndexSizeError 
phaser.js, line 2495 character 13

**Other info:** The debug text will show normally until I want to show the tooltip text. Then neither debug text nor the other Text instance will show.

**Comment by photonstorm** [comment]
Your codepen above works fine for me in IE10.

I'm not really concerned about FF10 as that's *24 versions ago*! (FF34 is current).

Am happy for you to re-open this if you can show a use-case of it crashing IE consistently (I use Phaser.Text all over the place in our client work, and they all work on IE9/10/11).
