### ISSUE TITLE
MouseMove callback

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#1484]
The api states:
mouseMoveCallback :function
A callback that can be fired when the mouse is moved while pressed down.

But the behavior seems to be whenever the mouse moves, regardless of wether it is pressed down or not.

**Comment by photonstorm** [comment]
The move callback in Input is linked to the Pointer class, so doesn't care if it's coming from the mouse, touch pointer, etc. Which is the method that should be used. The one in the Mouse class is specifically used by the Mouse only and should mostly be ignored. I've flagged it as deprecated, as it shouldn't be used directly.
