### ISSUE TITLE
Input Event Highly Inconsistent

### ISSUE THREAD

**Issue by englercj** [photonstorm/phaser#1486]
I am working with Phaser v2.2.1 and am noticing that much of the event handling is pretty inconsistent:

- Some events (e.g. mouseup, mousedown) use signals off the Phaser.Input class.
- Other events (e.g. mousemove) use a callback list via Phaser.Input#addMoveCallback, which to me just seems like a signal anyway but isn't one?
- Still others (e.g. mousewheel) use a single callback on a specifc pointer (i.e. game.input.mouse.mouseWheelCallback)

Seems a little strange to have so many different methods of listening to mouse events. I kind of get the mouse wheel event since that is mouse specific and not pointer generic, but the others are a little off putting.

Are there plans to unify this api a bit, or is this intentional?

Right now, I need to use all three and it just took some time to find the correct methods since they aren't the same:

```js
game.input.onDown.add(this._onPointerDown, this);
game.input.onUp.add(this._onPointerUp, this);

game.input.addMoveCallback(this._onPointerMove, this);

game.input.mouse.mouseWheelCallback = this._zoomCamera.bind(this);
```

**Comment by pnstickne** [comment]
I've been trying to use or migrate toward just two forms:

- `onFoo` for signal-based events, which can have multiple subscribers, called "relatively infrequently"; and

- `setBarCallback`, wrapping any direct setting of an internal callback property, for a single event only supporting one subscriber (for which a full signal does not apply) and is expected to be called at a much higher rate

It'd definitely be nice to have some "lets eventually work towards this.." direction.

**Comment by photonstorm** [comment]
I consider the Signals a legacy of Phaser v1 to be honest and don't plan to carry them over to Phaser 3. Will be searching for more 'native' event system instead. As much as I prefer Signals to Events (no strings to remember, etc) I'm more interested in performance for Phaser 3 and it would allow for consistency across the board.

**Comment by pnstickne** [comment]
Using a system (like the events found in pixi.js) would not actually be faster, without simply removing some features of signals, as it effectively just inverts what "stores" the event binding information.

The one disadvantage of the signals over per-object events is that they require an object, but that can be managed reasonably well with some conventions.
