### ISSUE TITLE
ScaleManager.RESIZE increases size of parent

### ISSUE THREAD

**Issue by ximop** [photonstorm/phaser#1489]
I'm using RESIZE scaleMode:
game.scale.scaleMode = Phaser.ScaleManager.RESIZE;

I attach the game to a div
(div id="the-game" style="width: 100%")
with:
game = new Phaser.Game(640, 480, Phaser.CANVAS, 'the-game');

If the div has no border it works fine
(div id="the-game" style="width: 100%")

But if I add a border
(div id="the-game" style="width: 100%; border-width: 1px; border-style: solid")
The size of the game canvas increases by 'border-width' pixels every 2 seconds, increasing the parent (div).

It seems that the ScaleManager is taking into a account the complete height of the parent element and not the actual inner space.

edit: the html was not shown. changed to ()

**Comment by pnstickne** [comment]
This falls under the ["parent should not apply padding"](http://docs.phaser.io/Phaser.ScaleManager.html) scenario - I agree that the documentation could be updated to be a bit more clear.

I would recommend adding the border to the _parent_ of Game canvas' parent.

**Comment by photonstorm** [comment]
I've updated the docs.
