### ISSUE TITLE
Sprites can fall through platforms with phaser 2.2 (regression from phaser 2.0)

### ISSUE THREAD

**Issue by nuisanceofcats** [photonstorm/phaser#1490]
With your tutorial: http://www.photonstorm.com/phaser/tutorial-making-your-first-phaser-game

If you run that with phaser 2.2.1 and jump up and down on the middle platform (about 50-100 times)... eventually the player will fall through the platform.

With phaser 2.0 you can jump up and down for hours and never fall through the platform.

This seems to affect/hamper any attempt I make at writing a 2d platformer :(

**Comment by photonstorm** [comment]
Ok dev now contains the latest fix for this. Probably worth testing in normal circumstances first (i.e. not constant tab swapping, but just 'jumping'). If you need to simulate high browser load there are easier ways :)

**Comment by nuisanceofcats** [comment]
Thanks for fixing this so quickly, this one really worried me given I couldn't get a single 2d platformer example to work! I hope you don't mind if I leave this issue open for another day while I do some more testing. Thanks again!

**Comment by nuisanceofcats** [comment]
If you're not too busy, would you mind writing a few sentences about what the problem was and how this fixed it?

**Comment by photonstorm** [comment]
You can follow the relevant discussion here: https://github.com/photonstorm/phaser/pull/1493

**Comment by nuisanceofcats** [comment]
Thanks!
