### ISSUE TITLE
grunt docs -> not found: jsdoc

### ISSUE THREAD

**Issue by flashspys** [photonstorm/phaser#1491]
I just downloaded phaser.io run successfully `npm install` in the directory. Now I want to rebuild the documentation by running `grunt docs`. I got following error:
`Warning: Error: not found: jsdoc Use --force to continue.`
How to solve this ? I didn't change anything on any files.

**Comment by pnstickne** [comment]
`jsdoc` is installed as a developer dependency, install these with:

    npm install -dev

**Comment by pnstickne** [comment]
Make sure the jsdoc module is installed "globally".

**Comment by photonstorm** [comment]
It's listed in the `package.json` so you should be safe to just do an `npm update` first (or an install like above)

**Comment by petarov** [comment]
@photonstorm I was trying to build the docs (dev branch) and faced the issue. It's probably [not a good idea](https://github.com/krampstudio/grunt-jsdoc/issues/125) to have `jsdoc` specified as a dependency in `package.json`.
