### ISSUE TITLE
CSP script-src violations

### ISSUE THREAD

**Issue by elennaro** [photonstorm/phaser#1494]
I try to implement [Content Security Policy](https://w3c.github.io/webappsec/specs/content-security-policy/) on a game written using Phaser.js in Cordova for mobile.

I have my security rules set pretty ok:
```html
Content-Security-Policy: default-src 'self'; 
script-src 'self' *.example.com *.google-analytics.com mc.yandex.ru;
style-src *.example.com;
img-src 'self' *.example.com;
frame-src *.example.com;
connect-src *.example.com ws://api.example.com wss://api.example.com"
```

Where `example.com` is some hosting i use to do some back-end logic and statistics.

However Chrome shows me next errors:

1. **Refused to evaluate a string as JavaScript** because `'unsafe-eval'` is not an allowed source of script in the following Content Security Policy directive: "`script-src` ... 
**phaser.js:34155** ... **phaser.js:70453**
2. **Refused to evaluate a string as JavaScript** because `'unsafe-eval'` is not an allowed source of script in the following Content Security Policy directive: "`script-src` ... 
**phaser.js:34155** ... **phaser.js:70453**

Here's the code:

```javascript
// The accessor creates a new Signal (and so it should only be used from user-code.)
    Object.defineProperty(Phaser.Events.prototype, prop, {
        get: new Function("return "+backing+" || ("+backing+" = new Phaser.Signal())") //line 34155
    });
...
}).call(this); //line 70453 
```
I don't really want to use ` 'unsafe-eval'` for `script-src`, especially since it is not recommended.

Please read [Content Security Policy Specs](https://w3c.github.io/webappsec/specs/content-security-policy/) for more information.

**Comment by pnstickne** [comment]
I'll get a patch in later today - I didn't realize there was a restriction.

The fix is as easy as changing the evals into closures, but that was me trying to be clever and not have the enclosing scope closed over - "don't ask".

**Comment by photonstorm** [comment]
@elennaro would you mind testing the dev branch please? (you'll have to build phaser using grunt, but otherwise it should be good to go).

**Comment by elennaro** [comment]
@photonstorm I've got the build from dev branch. And here I see:

`Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src ...` **phaser.js:34267** **phaser.js:70574**

Here's the code 

```javascript
 // The accessor creates a new Signal (and so it should only be used from user-code.)
    Object.defineProperty(Phaser.Events.prototype, prop, {
        get: new Function("return "+backing+" || ("+backing+" = new Phaser.Signal())") //Here's the error it's line 34267
    });
...
}).call(this); // Line 70574
```

According to [CSP spec 1.1 3.2.5.17 script-src](http://www.w3.org/TR/2014/WD-CSP11-20140211/#script-src):
>   If 'unsafe-eval' is not in allowed script sources:
>   Instead of evaluating their arguments, both operator eval and function eval [ECMA-262](http://www.ecma-international.org/ecma-262/5.1/) MUST throw a SecurityError exception. [DOM4](http://www.w3.org/TR/dom/)

So sorry, no luck with this approach.

**Comment by photonstorm** [comment]
Great stuff, thanks. I'll close this off once I've checked a few more things.
