### ISSUE TITLE
`anchor` on Phaser.BitmapText

### ISSUE THREAD

**Issue by Arcnor** [photonstorm/phaser#1499]
There doesn't seem to be a good reason to not have `anchor` on `BitmapText`, as `Text` have it, unless I'm missing something. Without it, `angle` is a bit limited as it always rotates from the top left corner :).

**Comment by photonstorm** [comment]
Yeah it's a Pixi side effect. The technical reason is that `anchor` is for texture alignment and a BitmapText doesn't have a texture, it's actually a whole bunch of Sprites (one per letter in the text) each of which shares the same texture. You could use `pivot` to achieve the same end result though.

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)
