### ISSUE TITLE
spritesheet margin vs spacing

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser#1501]
http://docs.phaser.io/Phaser.Loader.html#spritesheet
The documentation is a bit unclear. What is the difference between those ?
I couldn't find any examples, would be nice to have some clearer description.
```
margin	number	<optional> 0	
If the frames have been drawn with a margin, specify the amount here.

spacing	number	<optional> 0	
If the frames have been drawn with spacing between them, specify the amount here.

**Comment by hilts-vaughan** [comment]
If I recall, spacing is like CSS padding between sprite images. Margin is
around the entire sheet.

**Comment by photonstorm** [comment]
Correct. Margin is like the x/y offset from the top-left of the image that the sprites start from. Where-as spacing is the space between each frame (if any).

**Comment by pnstickne** [comment]
```
                                        ^
                                  margin_y
                                        v
< margin_x >  A  < spacing_x > B < spacing_x > C
                                        ^
                                  spacing_y
                                        v
< margin_x >  X  < spacing_x > Y < spacing_x > Z

**Comment by fyyyyy** [comment]
Thanks, this makes sense now :+1: 

I have a spritesheet with different horizontal vs vertical spacing, so this won't work with phaser i will have to change it in photoshop.
