### ISSUE TITLE
Wierd focus bug on input[type=range]

### ISSUE THREAD

**Issue by satan6** [photonstorm/phaser#1509]
http://codepen.io/anon/pen/GgNmBO

If you start dragging the slider, you cannot stop dragging it in Chrome and it won't stay where you dragged it in Firefox, unless you focussed the game before by clicking on it.

**Comment by satan6** [comment]
What happens is that the global mouseup handler calls `this.game.input.mousePointer.stop(event);` [here](https://github.com/photonstorm/phaser/blob/master/src/input/Mouse.js#L381), which then might do a event.preventDefault [here](https://github.com/photonstorm/phaser/blob/master/src/input/Pointer.js#L606):
```
if (this._stateReset)
{
    event.preventDefault();
    return;
}
```
Not sure what this code is supposed to do though, so i don't know how to fix it.

**Comment by photonstorm** [comment]
If you comment out that line does it actually work for you though?

**Comment by satan6** [comment]
Yes it does! The problem only occurs after you switch states because it calls .reset() which then sets _stateReset to true.

**Comment by photonstorm** [comment]
Right ok.. so basically if you swap states, then touch the Phaser game and THEN drag the slider it should work fine - because that sequence will set `_stateReset` back to false, stopping the events from being prevented. But if you swap state and then try to drag the slider immediately, it'll fail.

**Comment by photonstorm** [comment]
This is now fixed in dev :)
