### ISSUE TITLE
Arcade Physics allow sprites to push eachother through otherwise impassable objects

### ISSUE THREAD

**Issue by hydrabolt** [photonstorm/phaser#1513]
Hi!
I'm using Arcade Physics, and whenever 2 of my sprites collide, one pushes the other down into the ground until it falls off. I don't want to use P2 Physics just to fix this bug!

![part1](https://cloud.githubusercontent.com/assets/10330923/5606197/b0e7f758-941a-11e4-8853-1db35ef72129.PNG)
![part2](https://cloud.githubusercontent.com/assets/10330923/5606200/b0feb93e-941a-11e4-9343-d12493b24f25.PNG)
![part3](https://cloud.githubusercontent.com/assets/10330923/5606198/b0ebc72a-941a-11e4-909b-8b4a2d2edb99.PNG)
![part4](https://cloud.githubusercontent.com/assets/10330923/5606199/b0f0d7d8-941a-11e4-8d3b-fcc75c4e4443.PNG)
![part5](https://cloud.githubusercontent.com/assets/10330923/5606196/b0e77f62-941a-11e4-9a3f-3fda94c49ac7.PNG)

**Comment by pnstickne** [comment]
Nice images. Unfortunately, I don't think is trivially resolvable with the current Arcade physics.

The collisions of the entire system need to be considered to prevent moved objects from pushing through other objects (immovable or not).

**Comment by hydrabolt** [comment]
My problem with using P2 is that I lose a lot of the nice stuff I get with arcade. For example, it seems like an absolute pain to implement "body.touching.down" with P2.

**Comment by pnstickne** [comment]
@hydrabolt I wonder if it may simply be easiest to make the brick immovable - in that case the Arcade physics won't move it.

Any interaction with the brick would then have to be controlled manually, of course.

**Comment by hydrabolt** [comment]
Thanks, but I face 2 problems with this:

1) The brick seems to fall through the ground when it's body is set to immovable
2) I want it to be affected by hits from missiles, explosions etc.

**Comment by photonstorm** [comment]
What I'd suggest is using a custom separation handler for the brick. Then you can re-position the character sprite accordingly and prevent the brick from tunnelling through the floor. The principal would be identical to the tutorial I wrote for cloud platforms in [Phaser Coding Tips 4](http://www.photonstorm.com/phaser/phaser-coding-tips-4)
