### ISSUE TITLE
"Text Gradient" offset and stepping is incorrect from previous versions

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser#1514]
The ["Text Gradient"](http://examples.phaser.io/_site/view_full.html?d=text&f=text+gradient.js&t=text%20gradient) demo applies a "compressed" gradient to the top of the text instead of a uniform gradient across the entire text height.

The problem appears to have started in 2.1.3 (2.1.2 "looks correct") and was worsened by 2.2.0.

**Comment by photonstorm** [comment]
Well there's a shock.. something else that breaks in 2.1.3!

**Comment by photonstorm** [comment]
Ok have fixed the example. It's because this `text.canvas.height` (which the gradient used to define its height) reports back as 32. Swapped it for `text.height` and it's fine again. Didn't have to touch Phaser itself.
