### ISSUE TITLE
Web Font text is cut out below

### ISSUE THREAD

**Issue by netgfx** [photonstorm/phaser#1518]
A web font with strange layout when used the "p" gets cutout

You can view the issue here also: http://www.html5gamedevs.com/topic/11469-text-cut-out-with-webfont/#entry66513

**Comment by photonstorm** [comment]
There are some fonts Canvas is just unable to accurately measure, so I've added in a `padding` value to the Text object which allows you to specify additional padding added to the calculated dimensions. Using this I was able to get you font working fine:

```
    text.font = 'Fontdiner Swanky';
    text.fontSize = 60;
    text.padding.set(10, 16);
```

**Comment by netgfx** [comment]
Thanks that was exactly what I needed.

**Comment by Afshinbg** [comment]
Thanks for the fonts.
I use it well.

Afshinbg@HTC
Am 19.03.2015 05:26 schrieb "Richard Davey" <notifications@github.com>:
