### ISSUE TITLE
forceOrientation doesn't do what it says on the tin

### ISSUE THREAD

**Issue by photonstorm** [photonstorm/phaser#1520]
This is a small regression from the new ScaleManager (that I've only just spotted as it broke an old client game we're updating):

`ScaleManager.forceOrientation` should allow you to force the orientation of the game itself, regardless of platform or screen size. It was updated to check the screen orientation, not the browser viewport, which leads to incorrect results when using a RESIZE scale mode on desktop, and you resize your browser into the wrong dimensions.

I guess technically the orientation of the display is correct, but the JSDoc says it forces your **game** to adhere to the orientation, which it doesn't in all cases, it just checks the screen.

**Comment by pnstickne** [comment]
The orientation should never change on a desktop and "always" be horizontal - if it does then that's a regression issue, and is an issue I explicitly thought I addressed.

I am likely misunderstanding how orientation is used.

That being said, uhh, hmm .. breaking, mumble .. the behavior can be reverted to what it is before by changing what DOM.getScreenOrientation returns.

**Comment by photonstorm** [comment]
It's the docs that are wrong, it says that your **game** will be kept to that orientation. But this isn't correct, all it does on desktop is check you've a landscape oriented monitor. Your game could have been crushed into a tiny square, or a tall rectangle, but for all Phaser cares it carries on happily ignoring this fact because the orientation API never said otherwise.

This is especially evident if you use a RESIZE scale mode and shrink the browser down.

Technically what it is doing is fine (it *is* a change from how it used to work though, but I don't really mind that so much) but we do need to both update the docs to explain that it doesn't check your game at all, but the monitor, and provide some kind of alternative if you really do want to check your game, not the monitor. `isGameLandscape` perhaps?
