### ISSUE TITLE
webgl retrofont crashing in Internet Explorer

### ISSUE THREAD

**Issue by thinkong** [photonstorm/phaser#1523]
I really don't know if this has come up..

but it seems like retrofont seems to not work in IE.

even the samples don't work.

converting to canvas mode made it work!! so i am guessing it might be something about the webgl stuff in IE.

**Comment by photonstorm** [comment]
You're right. Can't decide if it's a Pixi issue (the preMultipliedAlpha warning certainly is, but that doesn't cause a crash) or something wrong with the retro font textures. Will investigate for 2.3.

**Comment by photonstorm** [comment]
Confirmed as an IE11 WebGL specific edge-case. Yay, my favourite.

**Comment by photonstorm** [comment]
Now fixed in dev.
