### ISSUE TITLE
Phaser.Filter.destroy() doesn't clear out the filter

### ISSUE THREAD

**Issue by P0rnflake** [photonstorm/phaser#1526]
Dear Phaser team,

I have recently discovered, that filters cannot be removed in a proper way.
Please check out the example that I made at http://codepen.io/anon/pen/emgeEp?editors=001 .

As you can see the filters are not destroyed properly, you can only destroy them manually at pixi level (var.filters = null).

Is this a bug or the way it is meant to be done?

Many thanks in advance.

**Comment by pnstickne** [comment]
I don't want to say it's a "bug" - although it may be unexpected.

A valid way to remove the filters is to reassign the `filters` property with the new filters (or null if none) *and* call destroy on any removed filters that are no longer used - so the WebGL resources can be released.

**Comment by photonstorm** [comment]
As the same filter can be potentially added to hundreds of sprites I didn't want the filters themselves responsible for knowing which sprites are using it, as it would just get really messy. Instead you need to remove it from any sprite you know you've assigned it to and *then* destroy it. I will update the docs to make this more clear, but it's definitely not likely to be something that will ever change.
