### ISSUE TITLE
Need documentation on plugins

### ISSUE THREAD

**Issue by alitavector** [photonstorm/phaser#1529]
Despite tried to adding the plugin without documentation, it seem the CPU usage on my project is still running high.

```
<script src="assets/js/phaser.js"></script>
<script src="assets/js/SaveCPU.js"></script>

var game = new Phaser.Game(800, 726, Phaser.AUTO, 'container',{preload: gPreload, create: create});

function create() {
  this.game.plugins.add(new Phaser.Plugin.SaveCPU)
}
```

**Comment by pnstickne** [comment]
It would is best to start with finding out _why_ the CPU usage is high.

SaveCPU won't make code that runs use any less processing, and a CPU that sits idle is just wasting time that it could be doing something (granted it uses less energy) ..

.. anyway, Phaser changed how to computes rendering so SaveCPU might not be updated. Set `game.time.desiredFps` - but do note that this also has a direct relation on physic updates as well.

**Comment by alitavector** [comment]
Yeah, it's the WeGL and memory will keep increasing due to Google Chrome design in atom-shell, all just a line of code
```
var game = new Phaser.Game(1016, 728, Phaser.CANVAS, 'container',{preload: gPreload, create: create});
```

It happen on PixiJS and NodeJS-Webkit which I've been tested extensively.

**Comment by photonstorm** [comment]
I think it's very likely this old plugin no longer works properly with Phaser. I'll be doing a pass on the plugins shortly, so will address it then (or remove it most likely).
