### ISSUE TITLE
Docs scrolling using TOC is a little buggy

### ISSUE THREAD

**Issue by rivertam** [photonstorm/phaser#1530]
When you scroll to an element using the TOC, the element ends up at the top of the browser, so the title of the element usually gets hidden by the navbar. This is fixed using a shim for major elements only.

**Comment by pnstickne** [comment]
Feel like making the appropriate change(s) to the documentation templates?
It would be appreciated - and likely result in this being corrected sooner.

There is [another issue for a filter](https://github.com/photonstorm/phaser/issues/1478) - it may be beneficial to collaborate with that author and/or see where such changes can be made.

**Comment by rivertam** [comment]
I put in a pull request to fix this. At work I'm supposed to create an issue before I submit a change to give context to the change, but I don't seem to be able to link the issue and the pull request, so that's why I made an issue.

I'll also take a look at the filter, though.

**Comment by photonstorm** [comment]
Closing this issue off as the relevant fixes have been merged into dev, thanks :+1:
