### ISSUE TITLE
ym example not working

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser#1532]
Tried with latest chrome && ff, macOs
Tried any version of phaser.

Error message
```js

GET http://examples.phaser.io/plugins/YM.js 404 (Not Found)

SyntaxError: syntax error view_full.html
ReferenceError: YM is not defined jquery-2.0.3.min.js line 4 > eval:143
TypeError: ym is undefined

**Comment by photonstorm** [comment]
Run it locally, and add the plugin first of course, will work fine then.

**Comment by fyyyyy** [comment]
Shouldnt it be working on the website as well ?

**Comment by photonstorm** [comment]
Yes, just a matter of time. Anyway I've updated the examples repo so this is fixed now (but it's not on the site yet until 2.3 goes live)
