### ISSUE TITLE
Fullscreen fails the first time when emulating iOS devices

### ISSUE THREAD

**Issue by belohlavek** [photonstorm/phaser#1533]
**Tested with Chrome Mobile emulation tool.** Using Chrome 39.0.2171.95 m.
All iOS devices fail to lunch fullscreen mode the first time, returning "Uncaught TypeError: undefined is not a function". They do work after a second click/emulated tap.

Try it yourself here: http://examples.phaser.io/_site/view_full.html?d=display&f=fullscreen.js&t=fullscreen

**Comment by pnstickne** [comment]
@belohlavek Thanks for reporting this.

Unfortunately I do have a access to iOS; any further details (ie. the expression / line that causes the exception) would be appreciated.

**Comment by photonstorm** [comment]
iOS doesn't support the full screen API anyway, so this is probably just Chrome emulation messing up: http://caniuse.com/#feat=fullscreen

**Comment by belohlavek** [comment]
As @photonstorm said it's just Chrome emulation messing up, some other devices don't even react to the fullscreen API so this is clearly not a Phaser issue. Closing.

**Comment by pnstickne** [comment]
But the error message _is_ a Phaser issue, per the contracts.

If the API doesn't work the ScaleManager should simply call the the onFullScreenError signal (and not display an exception).

**Comment by photonstorm** [comment]
The behaviour doesn't happen *on device* though, just in Chrome emulation. Feel free to fix it specifically for that if you want, but it feels like wasted time to me.

**Comment by pnstickne** [comment]
Oh, I misread that as "Chrome on iOS".
