### ISSUE TITLE
ScaleMode in config object: Cannot read property 'resize' of null

### ISSUE THREAD

**Issue by Mickawesomesque** [photonstorm/phaser#1534]
The following code results in a TypeError with Phaser 2.2.2:
```javascript
var conf = {
    height: 960,
    scaleMode: Phaser.ScaleManager.SHOW_ALL,
    width: 640
};

var game = new Phaser.Game(conf);
```
http://jsfiddle.net/gwhq9bhj/

**Comment by pnstickne** [comment]
I'm not seeing support for a "config" parameter in dev, which should be past any master release ..

**Comment by pnstickne** [comment]
The problem is because the ScaleManager config is being applied before a renderer has been created by the game.

**Comment by pnstickne** [comment]
This is actually due to circular and semi-circular dependencies between the ScaleManager and a few other components.

I'm working on a corrective update - say tonight or tomorrow.

**Comment by photonstorm** [comment]
This is now fixed in the dev branch.
