### ISSUE TITLE
Reserved index numbers

### ISSUE THREAD

**Issue by proyb2** [photonstorm/phaser#1535]
When each objects is created on game, I wish to tell phaser not to assign those index numbers from e.g. 0-30 to any other objects or spirites. This will be assign for array optimization I've in mind to speed up searching,

**Comment by photonstorm** [comment]
Is this a question?

**Comment by wildfiremedia** [comment]
Yes is a question whether this feature is available? Will be an interesting feature for certain algorithms.

**Comment by wildfiremedia** [comment]
Sorry, was busy at work.

I've in mind to speed up searching most frequently   to least frequently used value in array.

**Comment by pnstickne** [comment]
What "index numbers"?

**Comment by woutercommandeur** [comment]
What you should do is assign the objects returned to an array yourself, and use your own indexes to quickly search for the objects you created. Imho not a phaser problem.
Related forum post I you created that states your problem more clearly: 
http://www.html5gamedevs.com/topic/11653-change-button-frame-by-name/

**Comment by alitavector** [comment]
Woutercommandeur, that's not a related question.

pnstickne, sorry to clarify:
```
var groupobject = game.add.group();
for(...) {
   item = groupobject.create(x, y, 'button', 0)
   item.name="button1"
}

   console.log(groupobject.getAt(0).name)  //I wish if there a way for groupobject to start at 31 instead of 0, this could be related to PixiJS design problem?
```

**Comment by wildfiremedia** [comment]
Woutercommandeur, that's not a related question.

pnstickne, sorry to clarify:

var groupobject = game.add.group();
for(...) {
   item = groupobject.create(x, y, 'button', 0)
   item.name="button1"
}

   console.log(groupobject.getAt(0).name)
//I wish if there a way for groupobject to start adding item at 31 instead of from the
beginning at 0, this could be PixiJS design problem?

**Comment by pnstickne** [comment]
I'm not exactly sure what this would benefit .. and it's not a practical change internally.

However, one could sort of simulate such with adding 30 "dummy" items. I'm not really sure what such would grant though - and the lower-level PIXI functions would need to be used for a direct "replacement", IIRC.

**Comment by photonstorm** [comment]
There's no way I'm going to allow a sparse array internally, sorry. If you need 30 'empty' objects at the head of your Group, then create 30 empty objects and kill them so they don't process or render - and then bring them in as required.
