### ISSUE TITLE
phaser.d.ts Game constructors do not match documentation

### ISSUE THREAD

**Issue by Bilge** [photonstorm/phaser#1537]
According to the [documentation](http://docs.phaser.io/Phaser.Game.html) it is perfectly valid to pass strings to the first two parameters of `Phaser.Game`. However, that is not supported by the TypeScript implementation which only supports numbers:

```typescript
constructor(width?: number, height?: number, renderer?: number, parent?: any, state?: any, transparent?: boolean, antialias?: boolean, physicsConfig?: any);

constructor(config: IGameConfig);
```

**Comment by clark-stevenson** [comment]
Hey @Bilge 

This has been addressed on the dev build:

https://github.com/photonstorm/phaser/blob/dev/typescript/phaser.d.ts

**Comment by Bilge** [comment]
Wouldn't it be more correct to create another constructor definition that accepts strings, rather than just cover it up with an *any* type? Does TypeScript support this sort of overloading?

**Comment by clark-stevenson** [comment]
You are right about overloading. As far as the any goes, I was actually hoping we would get some union types by now.

**Comment by Bilge** [comment]
Maybe in the next version of TypeScript :+1:

**Comment by clark-stevenson** [comment]
@Bilge  that appears to be now with 1.4 :dancer: 

http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx

**Comment by Bilge** [comment]
![](http://img2.wikia.nocookie.net/__cb20100906180732/uncyclopedia/images/7/7d/Stick_Dancer.gif)

**Comment by Bilge** [comment]
Created #1570.
