### ISSUE TITLE
Drag/Scale/Group-bug

### ISSUE THREAD

**Issue by nkholski** [photonstorm/phaser#1542]
Sprites dragged within a scaled group will not follow in the same speed as the pointer that is dragging. It seems like the distance moved by the pointer is multiplied with the scale-value making the sprite go faster than the pointer if scale>1 and slower if scale<1. I've tested dragging both with the mouse and touch.

This fiddle is a modified example from examples.phaser.io demonstrating the bug:
http://jsfiddle.net/niklasberg/xxqad499/10
(I failed to get the images to load correctly and commented out the preload but the example proves it point even with the green boxes.)

Edit: I edited InputHandler.js and got the example to move in the same speed as the pointer, however the position starts a bit off and I haven't tested anything else but my specific case. Maybe it can be of use: http://jsfiddle.net/niklasberg/xxqad499/11/ (changes marked with "change"-comments). If I make any progress I'll post it here, but I'm not sure if I will be able to produce anything that could actually be merged.

**Comment by jf908** [comment]
Can confirm, I ran into the same bug

**Comment by TimvdEijnden** [comment]
You can solve this by creating a CustomInputHandler.

Override the startDrag & updateDrag 

    #inside the dragStart
    this.dragOffset.x *= MyGame.scaleFactor;
    this.dragOffset.y *= MyGame.scaleFactor;

    #inside the updateDrag
    px /= MyGame.scaleFactor
    py /= MyGame.scaleFactor

**Comment by alamboley** [comment]
Same bug here too... :/

**Comment by samalexander** [comment]
Same issue here. Any solutions?

**Comment by 62316e** [comment]
?

**Comment by photonstorm** [comment]
This is an unfortunate limitation of the current implementation. However I'm afraid there are no immediate plans to spend any more time on this trying to resolve it (we get so far, and then hit another wall, which means the whole system needs looking at really, which is beyond the scope for Phaser).

Anyone is welcome to submit a PR if you feel you can resolve it in a clean and relatively API friendly way.
