### ISSUE TITLE
normalMapFilter will make everything white/transparent

### ISSUE THREAD

**Issue by bitplanets** [photonstorm/phaser#1545]
The image is multiple of 2, 512x512px;

    var normalMap = PIXI.Texture.fromImage(require("assets/images/4141-normal.jpg"));
    normalMapFilter = new PIXI.NormalMapFilter(normalMap);
    myGroup.filters = [normalMapFilter]

With other filters works.

I've also put on pixi, but one of you can close this issue. https://github.com/GoodBoyDigital/pixi.js/issues/1355

Phaser 2.2.2; PIXI: 2.2.0; webgl

**Comment by photonstorm** [comment]
Thanks for the report. I'm going to close this as it's unlikely it will ever be fixed in Pixi v2, sorry. If we adopt Pixi 3 in the future hopefully it will be part of that!

Having said that, could the issue be related to the image you're using?
