### ISSUE TITLE
Putting a filter like displacementFilter on a group with many sub groups and sprites renders it white/transparent

### ISSUE THREAD

**Issue by bitplanets** [photonstorm/phaser#1546]
Putting a filter like displacementFilter on a group with many sub groups and sprites renders it white/transparent

    var displacementTexture = PIXI.Texture.fromImage(require("assets/images/displacementMAP.jpg"));
    displacementFilter = new PIXI.DisplacementFilter(displacementTexture);
    rootGroup.filters = [displacementFilter]

I've tried several filters and none works.

I've also put on phaser, but one of you can close this issue. https://github.com/GoodBoyDigital/pixi.js/issues/1356

Phaser 2.2.2; PIXI: 2.2.0; webgl

**Comment by photonstorm** [comment]
I'm going to close this issue as it's a Pixi level bug, and I'm not sure it will ever be fixed in Pixi v2. If that changes we'll integrate the updates to Phaser. Equally we may adopt Pixi v3 in the future once it's had a good amount of time to settle in.
