### ISSUE TITLE
TileSprite mouse click detection issue

### ISSUE THREAD

**Issue by integricho** [photonstorm/phaser#1551]
When detecting mouse clicks on a `TileSprite` like this:

    var ground = game.add.tileSprite(0, 0, 600, 600, "ground");
    ground.inputEnabled = true;
    ground.events.onInputUp.add(mouseUp, this);

mouse clicks are registered only on part of the screen, which is usally close to the resoluion of the image used as tile. For instance on a 256x256 tile-sprite, clicks are detected only in the area from (0, 0) to approximately (256, 256), even though both the world bounds and game resolution are larger.

**Comment by integricho** [comment]
Here is a jsbin to demonstrate the problem: http://jsbin.com/majewefahu/1/

Try clicking on the grass (a js alert will pop up showing the clicked worldX and worldY coordinates). It is supposed to detect clicks everywhere on the ground, but only the upper-left corner works.

**Comment by photonstorm** [comment]
Closing as you fixed it in your PR :)
