### ISSUE TITLE
Alpha fade in/out different in 2.2.3 from 2.1

### ISSUE THREAD

**Issue by kishigo** [photonstorm/phaser#1554]
I am using tween.js from sole to animate.  I animate the creation of sprites with a fade in, alpha running from [0..1] using the tween update function.  In pixi 2.1 the fade in is smooth but in 2.2.3, I get a series of blinks and then it looks as if there is a fade out.  x, y transition is smooth like in 2.1.

Am I doing something wrong here?  I am using a DisplayObjectContainer.  Interestingly, the blinking behavior on the fade transition was something I saw in 2.1 when I tried to use a SpriteBatch.  Now it looks like DisplayObjectContainers also have the same behavior in 2.2.3.

**Comment by photonstorm** [comment]
I suspect the tween.update isn't running in sync with the renderer. Incidentally why are you using tween.js? Given that Phaser has a tween manager built-in that *is* tween.js!

**Comment by kishigo** [comment]
I'm just using pixi.js, not Phaser.  Don't need input for this particular
application, just a renderer.
tween based alpha fades worked with Pixi 2.1 and not at 2.2.3.  Tween is
using RAF to run the tweening engine.  Is that incorrect?

**Comment by photonstorm** [comment]
If you're just using Pixi then report this in the Pixi repo.
