### ISSUE TITLE
Setting world bounds does not update x and y properties.

### ISSUE THREAD

**Issue by Bilge** [photonstorm/phaser#1555]
```javascript

world.setBounds(-200000, -200000, 400000, 400000);

world.x; //-0
world.y; //-0
world.width; //400000
world.height; //400000
```

**Comment by Problematic** [comment]
[The docs](http://docs.phaser.io/Phaser.World.html#setBounds) mention that World#setBounds doesn't modify the world x/y coordinates, which seems contradictory to the method signature (and which seems to mirror what World#resize is already doing). Is this correct behavior? If not, it should be a quick fix; I can open a PR.

**Comment by photonstorm** [comment]
I've enabled this and pushed to dev. It seems to have no adverse effects in my testing, but I'll let the wider community decide and revert if it does.

**Comment by Bilge** [comment]
You have... tests?

**Comment by photonstorm** [comment]
Why do you think there are 500+ examples?
