### ISSUE TITLE
Obsolete classes in the phaser.d.ts file?

### ISSUE THREAD

**Issue by vulvulune** [photonstorm/phaser#1557]
Hello,

With the scripts I wrote to generate the comments.d.ts files, I have now tools to find easily errors in the d.ts file.

I have a couple of questions about these classes, I didn't found it in the src. Are there still useful or can I use delete them from the phaser.d.ts file?
- Phaser.StateCycle
- Phaser.DomSprite

Vulvulune

PS: Is it the good way to create an issue for this kind of question, or is it better to use the forum?

**Comment by clark-stevenson** [comment]
Yeah here is good. 

Phaser.StateCycle should really have been an interface but it is a relic. For sure feel free to get rid of it although keep in mind it is used by "class Plugin" and "class PluginManager" but there is no need for this as the are explicitly defined in those classes so just remove the extends.

I cannot find Phaser.DomSprite anywhere but feel free to remove it. 

I am pretty surprised there is not more orphans.

**Comment by vulvulune** [comment]
Thank you.

No there are not a lot of orphans, the d.ts file has a very good quality. Good job :+1: 

I keep this issue opened while I'm cleaning the file if I have other questions.

**Comment by vulvulune** [comment]
I did the changes in this pull request #1558
