### ISSUE TITLE
Text anchor issue

### ISSUE THREAD

**Issue by yougotashovel** [photonstorm/phaser#1560]
When using a Text object and setting the anchor to 0.5.  The anchor is not doesn't set to the middle of the text, it seems like there is a large padding on the bottom of a Text object.

It's preventing me from animating text from the center point.

Anchors are working fine for sprites.

Using 2.2.2, and this is happening in browsers and in Cocoonjs Canvas+

**Comment by yougotashovel** [comment]
Solved: The problem was with lineSpcing.  Setting to 0 lets the anchor work as expected.

lineSpacing essentially adds a bottom padding that is added to the height of the text.

**Comment by yougotashovel** [comment]
Linked to this:

Setting the anchor to 0.5 on single letters .  Smaller letters like 'i' and 'l' anchor differently to wider letters like 'a' and 'n'.

The image attached demonstrates the point, and this happens with any font:
1. letters have been split into separate objects
2. width of the current letter is added to the X of the next letter
3. red text is with anchor points 0.5
4. blue text has no anchor points set.

![screen shot 2015-01-24 at 11 05 50](https://cloud.githubusercontent.com/assets/523614/5886980/55e90d48-a3b9-11e4-945f-6928aee0d42f.png)

**Comment by TimvdEijnden** [comment]
@photonstorm Is there a issue created for Pixi? Or is this already fixed? I'm also dealing with this issue in all my projects.

**Comment by photonstorm** [comment]
Does anyone have an isolated code example showing this please? (Feel free to open as a new issue if you do, but as this is really old now I'm assuming it's probably long gone)
