### ISSUE TITLE
Android Chrome crash with TileSprites & WebGL (Memory leak?)

### ISSUE THREAD

**Issue by chacal** [photonstorm/phaser#1563]
I'm trying to do a simple parallax scrolling background for my game. On desktop everything seems to work fine, but on my Nexus 7 (2013, Android 4.4.4) Chrome crashes after some playing.

I managed to pinpoint the problem to TileSprites and WebGL rendering and created a very simple project to demonstrate the problem.

Code for the test project is here: https://github.com/chacal/phaser_nexus_test
And you can test it live here: http://chacal.github.io/phaser_nexus_test/

To reproduce the problem, go to the second link with Chrome Mobile and tap on the screen to restart the game until the browser crashes (requires ~20 taps).

If the rendering mode is changed from AUTO to CANVAS, the problems does not seem to occur.

**Comment by chacal** [comment]
Small addition to this..

I tested with smaller power-of-two images (1024 x 512), but the crash still occurs. It does take longer to get there, however, which could indicate some kind of memory leak with the TileSprites.

If TileSprites are completely removed (only bg image drawn), I can't reproduce the problem even with hundreds of taps.

**Comment by pnstickne** [comment]
What happens if `this.game.input.onTap.add(this.restartGame, this)` is put in `preload`? Remember that `create` is called each time so this keeps stacking the onTap handler.

**Comment by chacal** [comment]
On 25 Jan 2015, at 6:01 , pnstickne <notifications@github.com> wrote:
> What happens if this.game.input.onTap.add(this.restartGame, this) is put in preload? Remember that create is called each time so this keeps stacking the onTap handler
> 

I tried this, but the results were the same. It seems, actually, that the preload is called every time the state is started as well.=

**Comment by chacal** [comment]
I checked the adb logs on the device and indeed it seems that the GL engine is running out of memory:

    W/Adreno-GSL(25812): <sharedmem_gpumem_alloc_id:1431>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
    E/Adreno-GSL(25812): <ioctl_kgsl_sharedmem_alloc:1532>: ioctl_kgsl_sharedmem_alloc: FATAL ERROR : (null)

**Comment by pnstickne** [comment]
Is this specific to a TilingSprite? (Does the error occur if a non-TS is used as a background?)

**Comment by chacal** [comment]
It seems to be TileSprite specific problem. I removed all three TileSprites from the example project and couldn't get it crash even with hundreds of taps. 

I also noticed that with only one TileSprite, it took much longer until it crashed. With two a little bit less and with three only those ~20 taps. So it seems to have something to do with the number of TileSprites used (probably because of more memory allocations..).

**Comment by photonstorm** [comment]
This is almost certainly a Pixi bug, and I suspect is linked to the way it clears up the texture after use (or rather *doesn't* clear it). I'll have a look and see if there is anything obvious, but am flagging as Pixi for now (it's probably worth raising over there too so they can patch it)

**Comment by chacal** [comment]
Thanks for your comments!

I created an issue to Pixi's Github repo to let them know about this: https://github.com/GoodBoyDigital/pixi.js/issues/1381

**Comment by englercj** [comment]
Just a heads up, this was an issue in PIXI but a change in Phaser is needed to propagate the fix.

Short version is we didn't properly implement destroy for TilingSprite, and now it is. Phaser needs to call it when destroying a TileSprite so the baseTexture cache is cleaned up.

More details here: https://github.com/GoodBoyDigital/pixi.js/issues/1381#issuecomment-71778886

**Comment by Bilge** [comment]
Also experiencing this in Firefox.

**Comment by photonstorm** [comment]
Fixed in dev.
