### ISSUE TITLE
Reset sprite frame when not overlap

### ISSUE THREAD

**Issue by wildfiremedia** [photonstorm/phaser#1566]
A request for this feature with the ability for sprites itself to reset to original frame state when the overlap is false.

```
game.load.spritesheet('woodenplank', 'w.png', 200, 30);

game.physics.startSystem(Phaser.Physics.ARCADE)	
group = game.add.group()	
group.enableBody = true;
group.physicsBodyType = Phaser.Physics.ARCADE;

for(var i=3;i>0;i--){
	group.create(i*100, 100, 'woodenplank')
}

ccc=game.add.sprite(100, 100, 'dude')
game.physics.arcade.overlap(ccc, group, function(r, s){
	console.log("is overlap")
	s.frame=1
});
```

**Comment by pnstickne** [comment]
This is problematic to make generic and should be handled in game code as it is.

Doing this change requires that the sprite is then aware of its overlapping rules - ie. with whom is it overlapping? - and physics implementation.

**Comment by wildfiremedia** [comment]
Just thought Phaser demo line intersection was similar
http://examples.phaser.io/_site/view_full.html?d=geometry&f=line+intersection.js&t=line%20intersection

The idea to have a characters/sprites aware of its surrounding which is done in 2D or top-view MMORPG when the player move near or overlap them, without having to write generic code that the characters can move around after the player do not approach them.

**Comment by pnstickne** [comment]
Notice how it really isn't "aware", but the check (for a single line-line intersection) is done each update the color updated in both branches. The code proposed above is generic across N sprites in the group - but in both cases it is still _game-specific_ logic.

**Comment by photonstorm** [comment]
Tend to agree this ought to be handled in userland code, sorry.
