### ISSUE TITLE
Mouse "isDown" behaves inconsistently when input moves off canvas

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser#1572]
When in Chrome or IE the `isDown` of the mouse is only sometimes reset when the cursor leaves the canvas - this can be reproduce in Chrome at the URL - http://codepen.io/anon/pen/OPgQWL

To reproduce this, drag the canvas/game around and while the pointer is held, move the mouse off the canvas and release the mouse button. Then move the mouse back over the canvas and it will still be actively dragging. (You may have to repeat the process several times to get it to take effect.)

It is also present in IE, although IE hates codepen. Firefox does not seem to be affected; Safari / OS X / Linux status is unknown.

One solution would be to ensure the pointer isDown flagged is cleared whenever it moves off canvas, if such is possible.

**Comment by photonstorm** [comment]
All that change would do is swap a false positive for a potentially false
negative. It has exactly the same odds as holding an incorrect value as it
does currently.

What it needs is a mouse up listener on window, although we used to do that
too and iirc it didn't catch further edge cases like mouse up outside of
the browser window.




On Sunday, January 25, 2015, pnstickne <notifications@github.com> wrote:

> This can be reproduce in Chrome at the URL -
> http://codepen.io/anon/pen/OPgQWL
>
> To reproduce this, drag the canvas/game around and while the pointer is
> held, move the mouse off the canvas and release the mouse button. Then move
> the mouse back over the canvas and it will still be actively dragging. (You
> may have to repeat the process several times to get it to take effect.)
>
> It is also present in IE, although IE hates codepen. Firefox does not seem
> to be affected; Safari / OS X / Linux status is unknown.
>
> One solution would be to ensure the pointer isDown flagged is cleared
> whenever it moves off canvas, if such is possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/1572>.
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by pnstickne** [comment]
Hmm, I thought such might already be detectable given http://localhost:8001/examples/_site/view_full.html?path=input/out-of-game (this seems to always correctly detect when out-of-game even when pressing the mouse down).

**Comment by photonstorm** [comment]
Sure we can easily detect if the mouse leaves the canvas area, but that doesn't mean you should reset `isDown` just because it happened.

**Comment by pnstickne** [comment]
In that case I wonder if it'd be possible to get `isDown` to behave consistently -

It's always resets when FF leaves the canvas but only "most of the time" in IE or Chrome.

**Comment by photonstorm** [comment]
There's no code in Phaser that resets input just because a pointer leaves the canvas. It does it on visibility change (unless disabled) when the game resumes from a pause. `withinGame` is a simple bounds check against a move event. If the game stops receiving move events, because you've given focus to something else and not returned it to the game properly, then it'll lose sync.

Technically you could mouse down in game, change visibility, return to the game again (which un-pauses, so resets input) yet still have the mouse down - phaser would then be out of sync again - but I really don't think there's much we can do about that.

**Comment by photonstorm** [comment]
Unless you can think of an easy solution I'm going to close this one off for now, sorry.
