### ISSUE TITLE
Docgen Phaser.GameObjectFactory.json "returns" property is null

### ISSUE THREAD

**Issue by et1982** [photonstorm/phaser#1578]
The GameObjectFactory.json file generated by docgen is not generating the "returns" object, else it gets a null value in the case of the methods image(...) and sprite(...).

**Comment by photonstorm** [comment]
Yes this is a known issue I'm afraid since we updated the docs generally across Phaser. For now please use the json file generated by jsdoc itself, or alternatively you're welcome to try and patch it and submit a pull request. Development on docgen is currently on hold as we complete other areas.
