### ISSUE TITLE
ground.body.AddLine Body debug view give wrong graph

### ISSUE THREAD

**Issue by rmxhaha** [photonstorm/phaser#1587]
so I am trying out 
```
    var ground = platforms.create( x1 + dx/2, y1 + dy/2, null, 0);
    game.physics.p2.enable( ground, true );
    ground.body.clearShapes();
    ground.body.addLine( r, 0,0, 0 );
    ground.body.angle = angle;
```

This gives the correct line with the collision body
but swap the last 2 line with

```
    ground.body.addLine( r, 0,0, angle );
    ground.body.angle = 0;
```

then the line would be 0 degree in the canvas but physically the collision is correct

I am using Phaser 2.2.2

**Comment by photonstorm** [comment]
You're definitely specifying `angle` in radians, yes?

**Comment by rmxhaha** [comment]
Off course not, wasn't it mentioned somehwere in the documentation that angle is for degree and rotation is for radian ?

**Comment by photonstorm** [comment]
`Body.angle` is in degrees, yes.

`addLine(length, offsetX, offsetY, rotation)` however is given in radians, but in your code above you use the variable `angle` which makes me wonder if its degrees or radians.

**Comment by rmxhaha** [comment]
I'm very sorry that I've lost that code and haven't got time to rewrite it in a way that I can show the problem. Even if I mixed up the degrees or radians that doesn't make the problem disappear. The main problem is that the polygon rendered is disagreeing with the physics...

**Comment by photonstorm** [comment]
Closing this until a test case is provided.

**Comment by rmxhaha** [comment]
I've tried it again but I couldn't find the bug anymore ...
