### ISSUE TITLE
How to do GUI the right way.

### ISSUE THREAD

**Issue by djmittens** [photonstorm/phaser#1590]
Ive been reading a lot of suggestion on forums and such (like overlaying another canvas with a library like zebkit, or using native html) whatever the technique i have not been able to find good articles or resources for it. These are my requirements for now,
*  Buttons ( there are examples for this thank you).
* TextFields  (blinking cursor, mobile keyboard support etc)
  I havent been able to figure this one out, because overlaying a native form obviously will clash with the pixel nature of my game, so i need to figure something out for this in terms of being able to at least type in stuff and use a bitmap font.

* Panels to combine those things(clearly if all of those didnt use dom components it would be much easier to do it in the engine).

* Work on mobile(cocoon) and desktop(node-webkit), so im not really concerned about doing it inside of the browser, as i would probably want to use app stores to distribute the game.

Thanks in advance.

**Comment by photonstorm** [comment]
I'm going to close this issue off, as it's more a support related question, ideal more useful in the forum where it could be discussed openly, rather than an 'issue' per se with Phaser. I have added it to the Phaser 3 list of things to investigate though.
