### ISSUE TITLE
Make the Loader accept Headers parameters

### ISSUE THREAD

**Issue by Mefteg** [photonstorm/phaser#1591]
Hello,
I want to know if you consider the Loader to accept extra parameters for getting assets.
I need to specify a particular Header to get my assets from GitHub and I can't load them directly with Phaser for the moment.

I've already posted on the forum (http://www.html5gamedevs.com/topic/12093-phaser-loader-contribution-to-add-special-headers/) but I have no reply.

I know how I can modify the Phaser Loader to make it works but I want to know if you want this feature or not.
I see the 2.3 version will update the Loader and if this feature interests you, it can be the right moment to add it.

Thank you for your time, I hope we can work together.

P.S. : sorry for my english :)

**Comment by photonstorm** [comment]
Show me what would be needed to change in the Loader to support this, and we can consider it for sure.

**Comment by photonstorm** [comment]
In order to keep the Github issues clear this feature request has been moved to the [Phaser 3 wishlist](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread/).
