### ISSUE TITLE
Phaser untestable.

### ISSUE THREAD

**Issue by Bilge** [photonstorm/phaser#1592]
I am trying to unit test my code but not only is Phaser itself not unit tested but it also actively prevents testing. This is because Phaser makes the following mistakes:

* Runs code when the library is loaded.
* Assumes it is running inside a browser.

As an example, I get burned very quickly by statements like:
```js
PIXI.Text.fontPropertiesCanvas = document.createElement('canvas');
```
This code runs when the library is loaded and assumes a global `document` object exists.

I do not believe any code should run until Phaser's entry point is invoked, i.e. `new Phaser.Game`. If the Phaser library could be loaded without running any code it would already be a lot easier to test even if it continued to assume browser objects are present. Therefore this ticket can be considered resolved when the library can be loaded without running its own code.

**Comment by photonstorm** [comment]
This ticket will never be resolved for as long as Phaser 2 remains sitting on-top of Pixi (which is basically 'forever'). This can only realistically be addressed in Phaser 3.

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)
