### ISSUE TITLE
`enableDrag` doesn't take `anchor` into account

### ISSUE THREAD

**Issue by unindented** [photonstorm/phaser#1593]
If I have the following:

```js
paddle.anchor.setTo(0.5);

paddle.inputEnabled = true;
paddle.input.setDragLock(false, true);
paddle.input.enableDrag(false, false, false, false, this.game.world.bounds);
```

I can only drag my paddles so far down:

![screen shot 2015-02-01 at 19 09 52](https://cloud.githubusercontent.com/assets/69485/5993358/fa7ced60-aa45-11e4-8dfc-87bc9c8f72c0.png)

The opposite happens when I drag up: the paddles are able to move beyond the world boundaries by half their height.

If I comment out `paddle.anchor.setTo(0.5)` then everything works as expected.

Is this a bug in `enableDrag`, or am I supposed to deal with it in my code?

**Comment by photonstorm** [comment]
Yeah I had been waiting for a new major release to address this one, as it's a bit of an API change. But this is now covered in 2.3.

**Comment by unindented** [comment]
:+1:
