### ISSUE TITLE
Add center zoom feature on camera

### ISSUE THREAD

**Issue by bitplanets** [photonstorm/phaser#1599]
If you just scale on camera and pan like this:

        data.game.camera.x = data.cameraStore.getCurrentX();
        data.game.camera.y = data.cameraStore.getCurrentY();

, everything seems to be shifted too because the scale is applied at 0,0.

That's why scale is not enough. Currently I'm doing this to shift things:

        data.game.world.pivot.x  = data.cameraStore.getCurrentX();
        data.game.world.pivot.y  = data.cameraStore.getCurrentY();

because in this way when you increase the scale you actually zoom in the center.

I need this because when I apply a displacement filter the position of that filter is messed up when the mas is panned.

**Comment by photonstorm** [comment]
While I agree it'd be a great feature I'm going to leave this firmly in user-land code. It's too specific a change to make to the core and would rock a lot of boats. If you really wanted to scale a game world currently, without resorting to using pivot, you could just create the world centered around 0x0 (i.e. set the world bounds to be say `-1000, -1000, 2000, 2000` and position your objects accordingly. Then scaling the camera would do so from the middle of the world automatically.
