### ISSUE TITLE
Setting the font property on a BitmapText instance has no effect - Phaser 2.2.2

### ISSUE THREAD

**Issue by starnut** [photonstorm/phaser#1602]
Setting the *font* property on a BitmapText instance after creating it does not change the font's face as expected:
```javascript
myBitmapText.font = "myNewFontKey"; // Does not update the font's face
```
Apparently, Phaser misses to update the private PIXI property *faceName*, which refers to the font cache key that is actually being used for rendering in the *updateText()* method:
```javascript
// Current workaround:
myBitmapText.fontName = "myNewFontKey"; // Works, but isn't documented anywhere since fontName is used as a private helper within PIXI.BitmapText
```
Maybe updating *fontName* in the *font* setter would do the trick?

**Comment by photonstorm** [comment]
Thanks, fixed in dev.
