### ISSUE TITLE
Tilemap layer camera and collisions broken when scale is changed

### ISSUE THREAD

**Issue by JRogaishio** [photonstorm/phaser#1603]
When changing the tilemap scale, the camera will be stuck to the top-left and the collision detection will not be updated to the new sized tiles.   
Using the below code will resize the layer but cause these issues.
var layer = map.createlayer('myLayer');
layer.scale.set(2,2); //Double the scale
  
Perhaps a "Scale" parameter could be added to the tilemap member of the loader or even the tilemap.createLayer. I haven't looked at the phaser source but in theory if you scale the tiles before it hits the collision detection then it may work and be easier to implement. Something like:

**Comment by mickez** [comment]
I actually implemented proper scaling to tilemap layers today, that makes both rendering and collision work, without having to pre-process any files/textures.

I'll be more than happy to submit a PR of the code if that feature would be appreciated

**Comment by JRogaishio** [comment]
>I'll be more than happy to submit a PR of the code if that feature would be appreciated
Thank you! I just snagged the .min file from your fiddle and it works great in my implementation!  
This issue was a major show-stopper for me because my tile map is 16x16. Without proper scaling it looked terrible. Hopefully this gets merged in to develop soon!

**Comment by mickez** [comment]
We had the same problem (up until today that is!) and we used the naive approach to pre-process all files to a size of 64x64 (which was reaaaaaaally bad for performance). I'm glad I could help! :)

**Comment by photonstorm** [comment]
It's now in the dev branch and will be part of the 2.3 release later this week (or early next week depending how things go)

**Comment by darde** [comment]
Thank you @rehnarama , your PR helped me as well.
