### ISSUE TITLE
TileSprite in Group is not visible when cacheAsBitmap is true

### ISSUE THREAD

**Issue by richpixel** [photonstorm/phaser#1604]
Just as the title suggests...

I create a group, and add objects - Sprites, Images, TileSprites

Then set cacheAsBitmap = true on the group ie. myGroup.cacheAsBitmap = true;

After that TileSprites are no longer visible.

**Comment by photonstorm** [comment]
I would suspect they may no longer be visible if you just set `cacheAsBitmap` on them at all, regardless of being in a Group.

**Comment by richpixel** [comment]
Very true, I would have thought that as well... however I tried it and it's only a problem if part of a Group, and cacheAsBitmap is set on the Group.

Other info: Phaser 2.2.2, Pixi 2.2.0, WebGL (things seemed ok in Canvas, but I had some system wide crashes when switching to Canvas so who knows)
I'm guessing it's a Pixi issue so I'll have to try it without Phaser involved next time.

**Comment by photonstorm** [comment]
Ah wait no that was my mis-reading, you did cache on the Group, not the TileSprite.. in which case yes, almost certainly a Pixi bug, sorry.

**Comment by photonstorm** [comment]
I'm going to close this issue as it's a Pixi level bug, and I'm not sure it will ever be fixed in Pixi v2. If that changes we'll integrate the updates to Phaser. Equally we may adopt Pixi v3 in the future once it's had a good amount of time to settle in.
