### ISSUE TITLE
Add support for Tiled rotated and flipped tiles

### ISSUE THREAD

**Issue by nkholski** [photonstorm/phaser#1607]
Tiled supports rotating and flipping tiles in the editor (press z, x or y when using stamp). This is currently not supported by Phaser.

I got a demo up with a modified version of current phaser-dev:
http://dev.niklasberg.se/phaserRotateTiles/

If I can figure out how I will make a pull request (Tile.js, TilemapLayer.js TilemapParser.js).

**Comment by photonstorm** [comment]
Talk about necro posting! Support for rotated and flipped tiles was made a available in Phaser 3, this post was back in the v2 days.
