### ISSUE TITLE
Tweens with array properties are misbehaving

### ISSUE THREAD

**Issue by FridayMarch26th** [photonstorm/phaser#1619]
I've encountered problems chaining and yoyoing tweens that have array properties.

The cause appears to be the way that TweenData vStarts and vEnds are concatenated to create various effects.

As a(n unfortunately) broad example, a parent property {x: [0,50,50,100]} could end up with a child property {x: [[0, 50, 50, 100], 100, 100, 200]}, which prevents the child property from being read correctly.

**Comment by photonstorm** [comment]
This is now fixed in dev.
