### ISSUE TITLE
Incorporating Pixi's Resolution Parameter

### ISSUE THREAD

**Issue by amadeus** [photonstorm/phaser#1621]
It would be nice to utilize Pixi's resolution parameter. I was able to accomplish this quite easily by subclassing `Phaser.Game`. I will provide an example here, however I think it's a simple enough change that I could make it into a PR if it's something that would be considered for the current `dev` branch.

**Pros**: It enables very easy nearest neighbor scaling for pixel games and retina displays.

**Cons**: There are a couple outstanding PRs I have with Pixi to fix a few bugs with specific features when using the `resolution` parameter. Hopefully they get integrated soon, but it only applies to filters and RenderTextures (at least that I have found thus far). The PRs I have open are https://github.com/GoodBoyDigital/pixi.js/pull/1399 and https://github.com/GoodBoyDigital/pixi.js/pull/1398

I am also not sure if there could be other further reaching implications with a change like this, thus posting here for feedback.

The biggest 'change' is in `setUpRenderer` method, I've added comments where changes need to happen in the function (it's only 2 lines).

```js
var Game = function(width, height, renderer, parent, state, transparent, antialias, physicsConfig){
	Phaser.Game.call(this, width, height, renderer, parent, state, transparent, antialias, physicsConfig);
};

Game.prototype = Object.create(Phaser.Game.prototype);
Game.prototype.resolution = 1;
Game.prototype.setUpRenderer = function(){
	if (this.config.canvasID) {
		this.canvas = Phaser.Canvas.create(
			this.width,
			this.height,
			this.config.canvasID
		);
	} else {
		this.canvas = Phaser.Canvas.create(
			this.width,
			this.height
		);
	}

	if (this.config.canvasStyle) {
		this.canvas.style = this.config.canvasStyle;
	} else {
		this.canvas.style['-webkit-full-screen'] = 'width: 100%; height: 100%';
	}

	if (this.device.cocoonJS) {
		if (this.renderType === Phaser.CANVAS) {
			this.canvas.screencanvas = true;
		} else {
			this.canvas.screencanvas = false;
		}
	}

	if (
		this.renderType  === Phaser.HEADLESS ||
		this.renderType  === Phaser.CANVAS	 ||
		(this.renderType === Phaser.AUTO && this.device.webGL === false)
	) {
		if (this.device.canvas) {
			if (this.renderType === Phaser.AUTO) {
				this.renderType = Phaser.CANVAS;
			}

			this.renderer = new PIXI.CanvasRenderer(
				this.width,
				this.height,
				{
					'view': this.canvas,
					'transparent': this.transparent,
					// Use resolution parameter
					'resolution': this.resolution,
					'clearBeforeRender': true
				}
			);
			this.context = this.renderer.context;
		} else {
			throw new Error('Phaser.Game - cannot create Canvas or WebGL context, aborting.');
		}
	} else {
		//	They requested WebGL and their browser supports it
		this.renderType = Phaser.WEBGL;

		this.renderer = new PIXI.WebGLRenderer(
			this.width,
			this.height,
			{
				'view': this.canvas,
				'transparent': this.transparent,
				// Use resolution parameter
				'resolution': this.resolution,
				'antialias': this.antialias,
				'preserveDrawingBuffer': this.preserveDrawingBuffer
			}
		);
		this.context = null;
	}

	if (this.renderType !== Phaser.HEADLESS) {
		this.stage.smoothed = this.antialias;
		Phaser.Canvas.addToDOM(this.canvas, this.parent, false);
		Phaser.Canvas.setTouchAction(this.canvas);
	}

};
```

Probably to do this right, it would need to be added as an instantiation parameter. I feel it's a pretty simple change that helps unlock some very useful functionality in Pixi. Perhaps we can help pressure them to accept my fixes that I've submitted to get this in :)

**Comment by amadeus** [comment]
I went ahead and created a commit that shows the necessary changes. It's pretty straightforward unless there is something I am missing completely - https://github.com/amadeus/phaser/commit/db710406fdc52050d8ac8b9dd18c78860b94fa4b

**Comment by amadeus** [comment]
It looks like both my fixes for the previous versions of Pixi have been merged in, so adding this functionality along with updating Pixi to the https://github.com/GoodBoyDigital/pixi.js/tree/v2.x branch, should allow this to work great.

**Comment by photonstorm** [comment]
I've merged Pixi 2.2.7 into Phaser now, which includes all of your fixes :)

**Comment by amadeus** [comment]
@photonstorm Thanks for merging those in!

Any thoughts on updating `Game` to include a `resolution` parameter and having it pass onto Pixi? The changes would look something like this: https://github.com/amadeus/phaser/commit/db710406fdc52050d8ac8b9dd18c78860b94fa4b

**Comment by photonstorm** [comment]
I'll add it as an option in the game config object, rather than a parameter.

**Comment by amadeus** [comment]
@photonstorm you're the best, thanks!
