### ISSUE TITLE
Performance issues after upgrading to 2.2.2

### ISSUE THREAD

**Issue by chrispalm** [photonstorm/phaser#1624]
I got performance issues when I switched from version 2.1.3 to version 2.2.2. I decided to step trough each check-in in the repo, build it and test it on the phone until I could pin point the issue and thereby find a solution.
After a couple of hours I was able to find this from 2014-11-08 19:52:
SHA-1: a0cc4c3777f37b51cc77f1051c998ec1b9e76913
 
* A large refactor to how the internal game timers and physics calculations has been made...
 
The hit on my performance between that version and the previous is very noticeable on my phone.
I dont think the code the is 100% same anymore in the latest version but I tried removing everything regarding the "spiralling" management (just about everything in update in Phaser.Game.prototype in Game.js) in the latest phaser version and now my game is back with good performance.

**Comment by photonstorm** [comment]
I bet what is actually happening is that the phone isn't capable of handling 60 fps, which is the default assumed frame rate, so is spending most of its time playing catch-up. What does Phaser.Time.suggestedFps report? My guess is it's significantly lower than Phaser.Time.desiredFps.

**Comment by chrispalm** [comment]
Yes, you are right. Its much lower than desired. It starts around 15 and then goes up to 30.

**Comment by photonstorm** [comment]
What happens if you set desiredFps to 30? Then it should only try to aim for 30fps, so will spend far less time playing catch-up.

**Comment by chrispalm** [comment]
Yes, it looks much much better when I do that. I haven't studied long enough now but it looks like it still goes into "streaks of slowness" like it did before but not as bad. I still think the game runs better when I remove the code though but that's just guesstimating from what I see on the screen now.

**Comment by photonstorm** [comment]
You can enable `Game.forceSingleUpdate` to force it back into the old method. That will force it to do a single logic update + render update every frame. The downside is that this will create different game speeds across different devices (like it did in the old version of Phaser).

**Comment by chrispalm** [comment]
Ok, thanks. Will try that.
