### ISSUE TITLE
BitmapData.alphaMask does not work in IE9

### ISSUE THREAD

**Issue by mxmlbernard** [photonstorm/phaser#1625]
Hi,

I am doing a puzzle game, where I load the image to reproduce & a serie of masks (in black and white) to apply for the pieces' shape.

The following snippet work as intended in all browsers but IE9 : 

var bmd = game.make.bitmapData(330, 250);
var bmdMask = game.add.bitmapData(330, 250).load('mask1');
bmdMask.replaceRGB(255, 255, 255, 255, 0, 0, 0, 0, 255);   // replace white by alpha = 0 for the mask 
bmd.alphaMask('original', bmdMask);

In IE9, it just displays the original image in bmd. IE10 seems to work in my tests.
My investigations lead me that it would be setPixels32 that does not work correctly for IE9 : by displaying bmdMask in a sprite, it shows the white color instead of transparency.

NB : I tried the processPixelRGB API, with the same results.

**Comment by photonstorm** [comment]
Could you please try using the IE9 polyfill found in the Resources folder. Just include it before Phaser in your page and see what happens. My guess is replaceRGB doesn't work because IE9 doesn't support Typed Arrays, so the polyfill should hopefully get around this.

**Comment by mxmlbernard** [comment]
Thank you for your suggestion.
I included dataview-polyfill, and got exact same results...

**Comment by mxmlbernard** [comment]
Still no solution in my sight. Any other suggestion ?

**Comment by photonstorm** [comment]
Going to close this one off, as it's old, and more than likely a browser limitation. All alphaMask does is draw 2 images using blend mode 'source atop': https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation - nothing more I'm afraid, it's literally just a few lines of code. Maybe try another blend mode, to see if you get better / different results?
