### ISSUE TITLE
Support for trackpad multitouch TUIO

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser#1626]
This is a great feature when developing html5 touch apps/games on the desktop, emulating multi touch with your trackpad.
However there seems to be some problem with phaser compatibility. It doesn't register multi-touch events inside the phaser canvas with hammer.js. It works fine on the iPad however. And the tiou demo works also fine in firefox on the mac with the touchpad. Any ideas?
http://www.html5rocks.com/en/mobile/touch/#toc-touchdev
https://www.youtube.com/watch?v=6wL-pLX9Kq0

**Comment by photonstorm** [comment]
Phaser supports multi-touch natively, we just don't enable the extra Pointers because most games don't need them, but it's a single call to do so. I would imagine throwing hammer into the mix would seriously confuse it. Also try this against dev branch, we made a recent change in there that allowed Chrome touch emulation to work, may support this too.

**Comment by fyyyyy** [comment]
Hello Photon,
Thanks for the info, my understanding was that phaser does not recognize multi-touch gestures ?
I was using hammer mainly so it would detect gestures and i wouldnt have to go through the process of doing this myself.
http://www.html5gamedevs.com/topic/8762-zoom-outin-camera-as-seen-in-angry-birds/

Maybe i should strip out the gesture recognition from hammer js, and use it with the phaser inputs?

**Comment by fyyyyy** [comment]
Hello Photon,
Thanks for the info, my understanding was that phaser does not recognize multi-touch gestures ?
I was using hammer mainly so it would detect gestures and i wouldnt have to go through the process of doing this myself.
http://www.html5gamedevs.com/topic/8762-zoom-outin-camera-as-seen-in-angry-birds/

Maybe i should strip out the gesture recognition from hammer js, and use it with the phaser inputs?

**Comment by fyyyyy** [comment]
Ok, i have fixed the integration with Hammer, you can see it working here on iPad / iPhone
http://www.tabloro.com/tables/Testin/play

You can drag 1-4 tiles simultaneously with 1-4 fingers which is handled by phaser.
If you use 2 fingers on the table you can pan/zoom with pinch, which is handled by hammer.js.

**Comment by photonstorm** [comment]
So what do I need to do? :) Is there a PR coming with a fix in it, or did you just manage to get it to work anyway?

**Comment by fyyyyy** [comment]
Was more fyi :)
Hammer js works fine alongside phaser if you let them handle separate events.

The TUIO trackpad multitouch demo from paul still doesn't work in phaser. (It's also outdated so it works only in Firefox at this time.) Maybe i will look into this a bit more to see if this can be made to work with phaser, it would be convenient for testing touch games.
http://www.paulirish.com/demo/multi

**Comment by photonstorm** [comment]
To be honest I'd rather find a way to not need Hammer at all. Gestures plugin anyone? :)
