### ISSUE TITLE
Animation doesn't finish playing when low fps causes a frame skip

### ISSUE THREAD

**Issue by richpixel** [photonstorm/phaser#1628]
I noticed this on devices and firefox (when it's running slow), but I have an easy fix.

If an animation is set to not loop, and not destroy itself onComplete, it's correct behavior is to stop on the final frame. However, if there is an fps drop which causes frames to be skipped, it will stop short of the final frame.

I've implemented a 1-line personal fix in the Phaser.Animation.complete() method:

this._frameIndex = this._frames.length-1;

So now when complete() returns and the frame is set it will be in bounds of the frameData array.

**Comment by martinies** [comment]
```if there is an fps drop which causes frames to be skipped, it will stop short of the final frame.``` can you elaborate on this please?

**Comment by photonstorm** [comment]
I agree, good catch, this is now in dev.

**Comment by joshlory** [comment]
Sorry to comment on a super old issue!  This code is the same in `phaser-ce`: [Animation.js](https://github.com/photonstorm/phaser-ce/blob/cb4bef1154174ead94b1cfec790c7eac4d3ff4f7/src/animation/Animation.js#L658-L659)

I'm seeing `animation.currentFrame.index` correctly move to the last frame, but the rendered sprite still shows the old frame.  Should the fix also have the following line?

```js
this.updateCurrentFrame(false);
```

**Comment by photonstorm** [comment]
@joshlory You'd be better off asking that on the Phaser CE repo to be honest.

**Comment by photonstorm** [comment]
@joshlory (erf, hit reply too fast) - but having had a quick look at it, I agree that the frame needs setting on completion.

**Comment by joshlory** [comment]
Thank you for the quick reply!  I'll file an issue + PR in the Phaser CE repo.
