### ISSUE TITLE
cssWidth and cssHeight not using canvas dimensions and does not account for devicePixelRatio

### ISSUE THREAD

**Issue by DarrenBeukesNEKTAN** [photonstorm/phaser#1630]
When using the 'viewport' meta tag for mobile devices Phaser behaves quite strangely.  I managed to negate the issue as much as possible by managing my own scaling.  However the one issue I found was that the style attributes on the canvas for css width and height were not being calculated correctly.  Additionally because resetCanvas function seems to run on some update loop it's impossible to correct them via DOM manipulation.

In resetCanvas, the issue is that cssWidth and cssHeight are calculated using 'this' which appears to use the window.innerWidth and window.innerHeight when it should be using the height and width of the canvas element.  

Additionally that function does not take account of the pixelRatio which means for devicePixelRatio > 1 the canvas was not properly scaled in CSS.

**Comment by DarrenBeukesNEKTAN** [comment]
After working with this a little more I feel the better solution would be to expose cssWidth and cssHeight via the Scale Manager, it seems the resetCanvas function is already setup to take these parameters (which it never does as far as I can tell).  This way a developer can scale the canvas as they see fit.  You might argue you can do that with media queries in the parent container but that removes the ability to deal with canvas size dynamically since you'd have to give coordinates for each possible set of dimensions ahead of of time.

**Comment by photonstorm** [comment]
As this issue stands now we've actually got nothing we can work with. "behaves quite strangely" is I'm afraid impossible to debug. We need an example.

Simply having a viewport set doesn't trigger issues in itself, all of our games have a viewport meta tag and still use the scale manager. Same for pixel ratio > 1 as well. So it has to be some specific combination of, or just some expectation that isn't being met.

**Comment by DarrenBeukesNEKTAN** [comment]
I'll provide an example later today to highlight the issue.

**Comment by DarrenBeukesNEKTAN** [comment]
Good news and bad news.  The good news is that I can no longer reproduce the issue.  The bad news is that I can no longer reproduce the issue which makes me worried.  It's possible that in my experimentation with the scale manager I'd left in some code which was working against me which I've since cleaned out.  I'll close this issue.
