### ISSUE TITLE
Adding a Graphics child to a Sprite does not update its dimensions

### ISSUE THREAD

**Issue by Bilge** [photonstorm/phaser#1632]
Below I create a Sprite with default dimensions 32x32. Next, I create Graphics with dimensions 123x456. I add the Graphics to the Sprite but the Sprite's dimensions remain at 32x32.

```javascript
var sprite = game.add.sprite(100, 100);
sprite.width; //32
sprite.height; //32

var gfx = game.add.graphics(0, 0);
gfx.drawRect(0, 0, 123, 456);
gfx.width; //123
gfx.height; //456

sprite.addChild(gfx);
sprite.width; //32
sprite.height; //32
```

**Comment by photonstorm** [comment]
Correct, that's just how Pixi does it. If you want dimensions including children you need to use a DisplayObjectContainer (or Group), but even that doesn't include the bounds of Graphics objects, just Sprites.

**Comment by Bilge** [comment]
That's pretty broken.

**Comment by photonstorm** [comment]
Take it up on the Pixi repo.

Even CreateJS isn't capable of giving you the bounds of a Shape object (their equivalent of a Graphics object). *You* have to explicitly tell it what the bounds is yourself!

**Comment by Bilge** [comment]
Explicitly setting the bounds of a Sprite causes it to scale its children, regardless of whether they're set before or after children are added. Therefore, setting bounds of a Sprite manually is not an option.

**Comment by photonstorm** [comment]
I was talking about how CreateJS does it (Shape.setBounds)

In Pixi there is no way to manually set the dimensions of a Sprite without it influencing its children.
