### ISSUE TITLE
Cannot build with grunt - no "build" task?

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser#1633]
Affects dev, `grunt` (or `grunt build`):

> Warning: Task "build" not found. Use --force to continue.

> Aborted due to warnings.

**Comment by pnstickne** [comment]
`grunt clean:build` appears to work..

**Comment by spayton** [comment]
I get the same, it's been doing this for a few days now for one reason or another.  The build tasks are undergoing an overhaul to allow a custom build by components.

**Comment by photonstorm** [comment]
Yeah I'll restore it shortly.

**Comment by photonstorm** [comment]
I've put the task back in.
