### ISSUE TITLE
Tilesets with margin/spacing render incorrectly

### ISSUE THREAD

**Issue by zekoff** [photonstorm/phaser#1641]
A rendering issue occurs when using a tileset with the following properties:

* 432x396 image size
* 32x32 tile size
* 12x11 distinct tiles
* 2px margin on all sides
* 4px spacing between tiles

The important properties for purposes of this issue are margin and spacing. The tileset image is included below, annotated with red for margin pixels and green for spacing pixels.

![bugreport](https://cloud.githubusercontent.com/assets/1486137/6386236/b72fa63e-bd3b-11e4-942a-2be42d044b61.png)

When creating a tilemap based on this tileset, `Phaser.Tileset` warns that "image tile area is not an even multiple of tile size" in the function `updateTileData`. Then, when the tilemap is loaded, it displays the wrong tiles.

Where Tiled renders map as this:

![tiled_rendering](https://cloud.githubusercontent.com/assets/1486137/6386305/5851f0da-bd3c-11e4-925f-3736183840f5.png)

Phaser renders map as this:

![phaser_rendering](https://cloud.githubusercontent.com/assets/1486137/6386306/6109d2ec-bd3c-11e4-8761-8fa778d7b4db.PNG)

**Minimal example to reproduce bug:**
https://github.com/zekoff/phaser-tileset-issue

**Comment by photonstorm** [comment]
Closing this off as you solved it yourself and it's now merged!
