### ISSUE TITLE
setScale and body.width/body.height

### ISSUE THREAD

**Issue by jf908** [photonstorm/phaser#1643]
When the scale of a tilemap layer is 1, the size of physics bodies colliding with the layer can be set using body.width or body.height.

However, when the scale of a tilemap is set to another value, setting body.width/body.height has no effect but using body.setSize() still works.

**Comment by photonstorm** [comment]
To be honest Body.width and height should never be modified directly. It's my fault for not marking them as readonly in the docs - but I've now done so. `setSize` should always be used to adjust a bodies dimensions.
