### ISSUE TITLE
onBeginContact giving null on it's first parameter

### ISSUE THREAD

**Issue by rmxhaha** [photonstorm/phaser#1644]
Though this might not be a bug I want at least documentation if it's not... 

When I tried to add collision group to my code, I stumble upon an error which shouldn't be there then I search then I found out that onBeginContact which should give a p2Body on it's first parameter suddenly gives null. If I add 

if( arguments[0] == null ) return;

inside onBeginContact then the error disappear but now nothing is colliding with each other.

I've asked this question ( http://www.html5gamedevs.com/topic/12649-phaser-p2js-onbegincontact-gives-null-body/ ) but no one is giving me an answer so I asked again here.

**Comment by photonstorm** [comment]
I have improved the documentation for all P2 related signals, including covering this.
