### ISSUE TITLE
Phaser.Sound.fadeIn() never increases the volume beyond 0

### ISSUE THREAD

**Issue by NoiSek** [photonstorm/phaser#1646]
As the title mentions, using Phaser.Utils.Debug on a Phaser.Sound object when triggering fadeIn() will show the sound as eventually 'playing', but the volume will never increase from 0.

I'm using Typescript, and If [this](http://examples.phaser.io/_site/view_full.html?d=audio&f=fade+in.js&t=fade%20in) is anything to go off of, the issue doesn't exist within the default javascript lib. Possibly Typescript specific / an issue with bindings?.

**Comment by photonstorm** [comment]
I can't see why TypeScript would make any difference here, the underlying code is still JavaScript. Will investigate this week.

**Comment by mikaturunen** [comment]
TypeScript is always compiled to given JavaScripts implementation of version X of EcmaScript standard. Currently you should be compiling to ES5 (unless you have Babel /harmony / tools in place). And what @photonstorm said, the TypeScript is only compilation time check, it does not affect the actual implementation of JS.

But you know what.. It's your lucky day and I'm such a freak over TypeScript, I'll rewrite the example provided here in TypeScript today after I get off work, what do you say about that? I'll release it to GitHub for more tinkering and testing so you can see that it actually works.

**Comment by mikaturunen** [comment]
[Link to implementation in TS](https://github.com/mikaturunen/phaser-examples-typescript/blob/master/examples/audio/fade%20in.ts)

There you go. Tested and works. To view it compile it manually or follow the instructions in README.md to get it running through grunt and try it out through the example pages once it's running on your local setup.

Currently the TS test / example code is not available online.

**Comment by NoiSek** [comment]
Seems I just didn't account for the decode time because I was preloading the data, made an assumption. 

Thanks!

**Comment by mikaturunen** [comment]
Happy to help if I can :) 
Main point is that the issue got caught and you can move forward.
