### ISSUE TITLE
Grpoup scale doesn't work

### ISSUE THREAD

**Issue by olkinaYingele** [photonstorm/phaser#1650]
Hi!

I need the group scale functionality but it doesn't work.

Here's my code:

    window.onload = function() {

        var game = new Phaser.Game(800, 600, Phaser.AUTO, 'testDiv', { preload: preload, create: create });

        function preload () {

            game.load.image('logo', 'phaser.png');

        }

        function create () {

            var gr = game.add.group();
            gr.create(0, 0, 'logo');
            gr.scale.setTo(3,3);
 
            /*var logo = game.add.sprite(game.world.centerX, game.world.centerY, 'logo');
            logo.anchor.setTo(0.5, 0.5);
            logo.scale.setTo(3,3);*/

        }

    };

**Comment by photonstorm** [comment]
Your code works fine here. What are you trying to demonstrate?

**Comment by pnstickne** [comment]
@olkinaYingele  Make sure `logo` is a _child/descendant_ of `gr` - or else it won't be affected by the scaling of `gr`. (In the code `logo` is added to work game World, not to the `gr` Group.)

**Comment by olkinaYingele** [comment]
I've downloaded the last version of the phaser.js from the Github, and there's no problem anymore.

Sorry for the noise!

Olga
