### ISSUE TITLE
Phaser.Keyboard.D isn't working in Chrome unless the shift key is held

### ISSUE THREAD

**Issue by Pink401k** [photonstorm/phaser#1651]
Chrome version 40.  Tried on both my OSX machine and Windows.  

If I try to detect the "D" key in chrome, I need to hold down shift to get it to work. However, in Firefox, it does register.

```
rightKey = this.game.input.keyboard.addKey(Phaser.Keyboard.D);
if(this.cursors.right.isDown || rightKey.isDown) {
	this.player.body.velocity.x += 130;
}
```
That is the code in question.

You can see it in action here: http://kyle.pink/games/topdown/

**Comment by B3nac** [comment]
Your example and wasd work fine for me. This seems to be a recurring problem with Chrome and certain keyboards.  Also it looks like Fn+Windows key has solved it for some people. Here are more workarounds https://productforums.google.com/forum/#!topic/chrome/GBuxA5fbFMQ. Hope this helps.

**Comment by Pink401k** [comment]
Thanks! 

For the sake of the bug, I've tried it on a:
* Happy Hacking Keyboard (osx)
* Mac Book Pro native Keyboard (osx)
* Corsair K70 Keyboard (windows 7)

All with the same result.  I'll try what you mentioned though!

**Comment by B3nac** [comment]
No problem! I should have added I'm using Chrome v40 as well. An extension hotkeys could be messing with it as well.

**Comment by photonstorm** [comment]
This is a browser bug (and a local / machine specific one at that, maybe triggered by extensions?), nothing to do with Phaser I'm afraid.

**Comment by davidvgus** [comment]
I'm having this issue today.  It just seems odd that this has been around for a year.  Does anyone have a work around?

**Comment by hilts-vaughan** [comment]
Have you tried using a Javascript Keycode tester and see if that works?

**Comment by davidvgus** [comment]
Yes,  And the code works with both IE and Firefox on the machine in question.  I will try to reboot it today.

**Comment by photonstorm** [comment]
There's no work-around because it's entirely specific to your browser / hardware set-up / browser extension combo. The D key works fine, something you've got set-up locally is blocking it I'm afraid. I would start by exploring Chrome extensions. Maybe running under Canary with all extensions disabled, then put them on one-by-one until you find the culprit.

**Comment by davidvgus** [comment]
I figured it out.  It was vimium.  I thought I had disabled it for the page my game was on but I was wrong.

**Comment by photonstorm** [comment]
Thanks for the heads up. As this has happened to a couple of devs now I
think it's worth adding to our docs.


On Thursday, 31 March 2016, davidvgus <notifications@github.com> wrote:

> I figured it out. It was vimium. I thought I had disabled it for the page
> my game was on but I was wrong.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/1651#issuecomment-204043933>
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27
