### ISSUE TITLE
animations not working on tileSprite

### ISSUE THREAD

**Issue by tcarlsen** [photonstorm/phaser#1653]
From what I can read in the docs and the code the `animationManager` should work on `tileSprite` ([TileSprite.js#L59](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/TileSprite.js#L59)), but for me thats not the case.

In my "test" the animation is working with a `sprite` but not when a `tileSprite`. Am I doing something wrong or does this not work yet?

Working:
```coffeescript
game.load.spritesheet "water", "water.png", 32, 32, 3
water = game.add.sprite 0, 0, "water"
water.animations.add "ani", [0, 1, 2], 2, true
water.animations.play "ani"
```

Not working: 
```coffeescript
game.load.spritesheet "water", "water.png", 32, 32, 3
water = game.add.tileSprite 0, 0, 64, 64, "water", 0
water.animations.add "ani", [0, 1, 2], 2, true
water.animations.play "ani"
```

**Comment by photonstorm** [comment]
This hasn't worked since Pixi updated to 2.2 and I doubt is going to work again any time soon. I'll flag it as a bug, because it used to, but given how it works internally it's massively inefficient anyway, so it's probably no great loss.

**Comment by tcarlsen** [comment]
Is there an alternative workaround?? Not counting adding one sprite at the time to fill out the same area as the tileSprite was covering??

**Comment by photonstorm** [comment]
This has been bugging me for a long time and is now finally fixed in dev.

**Comment by tcarlsen** [comment]
:dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers:
