### ISSUE TITLE
fixedToCamera Seems broken in 2.3.0

### ISSUE THREAD

**Issue by englercj** [photonstorm/phaser#1654]
Is this a known issue? Seems like the `fixedToCamera` functionality isn't working in the latest `dev` branch.

**Comment by photonstorm** [comment]
The `world/fixed to camera` example is working fine here against the current dev branch. I've not tested it against a built version yet though, just source only.

**Comment by englercj** [comment]
Maybe the built version in dev is out-of-date, I didn't even try to rebuild first. Let me try rebuilding!

**Comment by englercj** [comment]
Looks like it is broken for graphics:

http://jsfiddle.net/1hecfdxs/

The line is set to `fixedToCamera` but scrolls with the background.

**Comment by photonstorm** [comment]
Not sure it has *ever* worked for Graphics objects! Will check now.

**Comment by photonstorm** [comment]
Ok yes it did used to work in 2.2 - digging a little deeper it appears to be something wrong with how the mixins are being applied (a recent update I think, was fine the other week).

**Comment by adelciotto** [comment]
For those curious, here are those recent changes: https://github.com/photonstorm/phaser/pull/1647

**Comment by englercj** [comment]
If I create a sprite/graphics object they both have the proper properties for me. It is just that on graphics the `fixedToCamera` flag (although it exists) isn;t honored.

**Comment by adelciotto** [comment]
yeah it looks like the fixedToCamera components postUpdate method is not being called for graphics objects.

**Comment by photonstorm** [comment]
Bloody hell that was a pain in the arse to track down - and yet fundamentally so simple in the end.
