### ISSUE TITLE
Missing preUpdate function for bitmaptext children causes crash

### ISSUE THREAD

**Issue by spayton** [photonstorm/phaser#1655]
At the bottom of Phaser.Component.Core.preUpdate() is a loop to call preUpdate() on the objects' children.

A bitmapText object has PIXI.Sprite children without preUpdate members.

So bitmapText seems broken on the current 'dev' branch.  Verify this by selecting the 'Load Bitmap Font' from the 'Loader' examples and then selecting the 'dev' phaser version.

**Comment by photonstorm** [comment]
I fixed this in dev a few days ago, have pushed it up now. Still not in the build files though.

**Comment by spayton** [comment]
That fixes the problem, but this pull also introduces another break.  In PIXI.DisplayObjectContainer.prototype._renderCanvas() you've removed the 'var' from the loop so it'll use a non-local 'i'.  For me it goes into an infinite loop.  Do you want a PR for this?

**Comment by photonstorm** [comment]
Nah it's already fixed. It doesn't infinite loop though, just raises it globally. But eitherway, 'tis fixed.

**Comment by spayton** [comment]
Possibly conflicted with an 'i' in a higher scope, Chrome through a right wobbler and wouldn't die.
