### ISSUE TITLE
Unable to tint a TileSprite

### ISSUE THREAD

**Issue by FridayMarch26th** [photonstorm/phaser#1658]
Tint is listed as a member of TileSprite in the docs; though changing it doesn't appear to have any effect.

I've been able to tint a PIXI.TilingSprite in a quick test using PIXI alone.

**Comment by photonstorm** [comment]
Hmm I can't get Pixi to tint a TilingSprite when in Canvas mode, only in WebGL mode. Just tested Phaser dev branch and am seeing the same thing (works fine in WebGL, not in Canvas).

Looking at the Pixi source there is nothing at all in `generateTilingTexture` (or anywhere in the TilingSprite class) to actually tint the canvas. The feature literally appears to be missing.

**Comment by FridayMarch26th** [comment]
That's it, isn't it. In fact it's already been raised:

[https://github.com/GoodBoyDigital/pixi.js/issues/1339](GoodBoyDigital/pixi.js#1339)

Cheers,
