### ISSUE TITLE
Example working with non-minified version of phaser only

### ISSUE THREAD

**Issue by hoschiCZ** [photonstorm/phaser#1661]
I took the Hello World script (working even if phaser.min.js present) and replaced the previous code except window.onload with code from one example - thrust.js namely. Getting errors: "Uncaught TypeError: Cannot read property 'style' of null" (from Chrome dev console). When I replace link to phaser.min.js with link to phaser.js, it throws no exceptions (except 404 for images) and it works (when you'll test it, you'll need to replace image sources with working...). Source of index.html:

http://pastebin.com/f7hXUbdt

**Comment by mikaturunen** [comment]
So if I understood you correctly... You are saying the given html file does not work with phaser.min.js? 

What did you test it against? Stable 2.2.2 (Alkindar) or development branch? Stable works, tested.
https://gist.github.com/mikaturunen/1011c60660f33c252976 

Took the phaser.min.js from the last release.

Package.json
    "name": "phaser",
    "version": "2.2.2",
    "release": "Alkindar",

**Comment by hoschiCZ** [comment]
Now it works. No idea how is it possible...
