### ISSUE TITLE
tilemapLayer rendering problem with camera positioning

### ISSUE THREAD

**Issue by KyleBsingh** [photonstorm/phaser#1662]
I have only had this error occur on Apple Devices running iOS8. On Mac w/ Google Chrome I ran into no issues.

Scenario:
Created a tilemaplayer which would be bigger than the camera size.
I allowed the camera to move so that using drag all parts of the tilemap could be seen.
This worked fine on desktop.
However when moving to mobile, parts (not all) of the section which was not in view from the beginning were not being rendered. The parts were not consistent either.

After fiddling around I realized setting layer.renderSettings.enableScrollDelta = false, solved the issue for me. This is because the whole tilemap would be rendered from the beginning rather than when it just came in view. However this will obviously be a performance hit later on.

I recommend taking a look at this.

EDIT: Both Safari and Chrome were tested on the xCode Simulator, along with a physical iPad.

**Comment by photonstorm** [comment]
Sounds like an issue, but without a test case to debug there's nothing more we can do, sorry.
