### ISSUE TITLE
Error destroying TIleSprite before it has been rendered

### ISSUE THREAD

**Issue by englercj** [photonstorm/phaser#1663]
This is a heads up that there was a bug in pixi that made PIXI.TilingSprite throw an exception in v2.2.7 if you tried to destroy a TilingSprite without having rendered it once.

I just released v2.2.8 which includes the fix for this issue. May want to update phaser (my app is hitting this bug :P using latest dev v2.3.0 of Phaser).

Thanks!

**Comment by photonstorm** [comment]
Thanks, done.
