### ISSUE TITLE
Using data for laoding a  pack in v2.3.0 throws an error.

### ISSUE THREAD

**Issue by englercj** [photonstorm/phaser#1664]
In v2.2, I was able to do something like this:

```js
game.load.pack(key, null, data);
```

But in v2.3 that same line throws eventually causes a parsing exception.

Looks like in the loader even when you pass data it still adds the URL to the queue so it tries to load `/null` which fails and causes a `JSON.parse()` to later explode.

During my preload state I load my pack manifest file as just a json file. Then later as specific areas open up I then load the level-specific resources defined in my pack manifest, like so:

```js
this.packData = this.cache.getJSON(Data.Constants.ASSET_TILEMAP_PACKS_KEY);

this.load.pack(this.levelKey, null, this.packData);
```

If there is a different way I should be doing this please let me know, I understand I am on the bleeding edge.

**Comment by pnstickne** [comment]
There was a slight accidental logic change. This should still work per the documentation. I've added a PR patch.

**Comment by photonstorm** [comment]
Now in dev #1668
