### ISSUE TITLE
TilemapLayer does not consider scale when camera is moving.

### ISSUE THREAD

**Issue by KyleBsingh** [photonstorm/phaser#1670]
Condition: Camera is scaled to something other than 1.

When moving the camera via game.camera.x /.y sprites move appropriate, by taking into consideration the scale of the camera. However tilemap does not do this. Instead it only moves by the new x or y unscaled.

EDIT: 

In the dev version of phaser/src/tilemap/TilemapLayer.js

Phaser.TilemapLayer.prototype.postUpdate = function () {

    Phaser.Component.Core.prototype.postUpdate.call(this);

    //  Stops you being able to auto-scroll the camera if it's not following a sprite
    var camera = this.game.camera;

    this.scrollX = camera.x * this.scrollFactorX / this.scale.x;
    this.scrollY = camera.y * this.scrollFactorY / this.scale.y;

    this.render();
};

-----------------------
Could be changed to :
--------------------------

Phaser.TilemapLayer.prototype.postUpdate = function () {

    Phaser.Component.Core.prototype.postUpdate.call(this);

    //  Stops you being able to auto-scroll the camera if it's not following a sprite
    var camera = this.game.camera;

    this.scrollX = camera.x * this.scrollFactorX / this.scale.x;
    this.scrollY = camera.y * this.scrollFactorY / this.scale.y;

    this.render();
    
    if (this.fixedToCamera) {
   
        this.position.x = camera.view.x + this.cameraOffset.x
        this.position.y = camera.view.y + this.cameraOffset.y
    }
};

I've tested this and it works to what I think should be happening. The tilemap moves at the same rate as the camera.

**Comment by photonstorm** [comment]
Closing this one as it was actually fixed a while ago, as a result of something else, and this issue wasn't  properly closed at the time.
