### ISSUE TITLE
Kindle Fire Tablets HD 6, 7 & HDX 8.9 all crash when using Cordova with Phaser

### ISSUE THREAD

**Issue by speige** [photonstorm/phaser#1673]
The code seems to crash in Phaser.Canvas.addToDOM on this line:
target.appendChild(canvas)

It works fine on Kindle Fire Phone.

This was tested using the Kindle Fire emulator at https://developer.amazon.com/tya/dashboard.html using an apk created from build.phonegap.com

The auto-detect chose WebGL mode.

I am not specifying an element when calling new Phaser.Game. The target for the canvas element is document.body

The specific line of code was found through console.log statements. window.onerror also had a console.log, but it was never called.

A console.log on the Canvas & Body variables shows they have valid values. Also, a console.log on appendChild says "native code".

I'm not sure why this statement would cause the game to crash.

**Comment by photonstorm** [comment]
Do they actually support WebGL mode? What happens if you force it to use Canvas?

**Comment by speige** [comment]
Switching it to Canvas fixed the problem! I guess Phaser.AUTO isn't able to correctly identify WebGL functionality on Kindle Fire Tablet with Cordova WebView (or Kindle Fire Cordova WebView claims to support WebGL but it's broken?).

Probably could be fixed by modifying device.webGL function in _checkFeatures

The easy way I can think of is checking UserAgent strings, but that probably isn't a great solution.

I can come up with a workaround in my code, so you can close this issue if you want. However, if you'd like me to test any alternative versions of the device.webGL function so that it can be incorporated back into the library, let me know.

Phaser is an awesome library!
Thanks for your help!

**Comment by photonstorm** [comment]
To be honest I think this might be a PhoneGap issue - the Kindles we've got here *don't* incorrectly report WebGL support when run via Silk.

Am wondering how we might build a more robust "inside PhoneGap WebGL test".

**Comment by speige** [comment]
Good point. I haven't noticed any issues on other devices with PhoneGap, but so I wonder if it's specific to PhoneGap+Kindle.

I did some debugging in the device.webGL function under _checkFeatures.
canvas.screencanvas was undefined, but that didn't matter since you're setting it to false, not reading it. window.WebGLRenderingContext, canvas.getContext('webgl'), & canvas.getContext( 'experimental-webgl' ) all returned valid objects. I might have to enumerate the properties on the context objects to see if there's some property that would notify me that it won't work.

For now I think I'm just going to MonkeyPath Phaser with a Cordova+KindleUserAgent=ForceCanvas. It seems a better approach would have been to use CrossWalk or Cocoon :(

Thanks for your help.

**Comment by photonstorm** [comment]
Here's another thought:

Create a super-simple project. Like just 1 image being loaded and try it in WebGL mode. Does it still crash when it starts-up? If so then I wonder if Pixi might be setting something on the WebGL context that PhoneGap doesn't support (like premultipliedAlpha)

**Comment by speige** [comment]
I didn't try out the super simple project. I think it's a good idea, but haven't had time. However, it makes sense that Kindle Fire shouldn't have WebGL on Cordova/PhoneGap, because it uses the internal WebView (rather than chromium embedded in the apk like Crosswalk/Cocoon). On versions before 5 (Lolipop) the WebView was built into the Android OS and couldn't be modified (As of v5 it's an updateable component through GooglePlay). The WebView didn't start supporting WebGL until Android OS v5, so Kindle Fire's WebView couldn't support it (unless there's been a major Kindle update recently).

**Comment by speige** [comment]
Here's the code I'm using on Cordova to fix this issue (Kindle/Cordova's fault, not Phaser's), in case any one else finds it useful:

//monkey patch Phaser.Device._initialize to override this.webGL on Android versions before 5
var oldPhaserDeviceInitialize = Phaser.Device._initialize;
Phaser.Device._initialize = function () {
    oldPhaserDeviceInitialize.call(this);
    if (this.webGL && window.cordova) {
        if (device.platform.toLowerCase().indexOf('android') != -1) {
            var majorVersion = parseFloat(device.version.split('.')[0]);
            if (majorVersion < 5) {
                this.webGL = false; // some devices incorrectly claim to support WebGL, but Cordova on Android always uses the internal WebView which is built into the OS & never supported WebGL until version 5
            }
        }
    }
};

**Comment by pnstickne** [comment]
The Device type has a useful signal to handle this case, `Phaser.Device.onInitialized`

Use it as so:

```
Phaser.Device.onInitialized.add(function (device) {
  if (this.webGL && window.cordova) {
    var platform = device.platform.toLowerCase();
    if (platform.indexOf('android') != -1 || platform.indexOf('amazon-fireos') != -1) {
    var majorVersion = parseFloat(device.version.split('.')[0]);
    if (majorVersion < 5) {
    this.webGL = false;
});

**Comment by photonstorm** [comment]
Am going to close this one off as a weird-ass PhoneGap issue, because that's a nice clean fix approach above there.
