### ISSUE TITLE
Allow "resolution" to be set in Phaser.Game to be passed to PIXI for hidpi support

### ISSUE THREAD

**Issue by tmaiaroto** [photonstorm/phaser#1676]
PIXI now has better support around retina (hidpi) displays. See: https://github.com/GoodBoyDigital/pixi.js/issues/621

The option is now a ```resolution``` setting, but in Phaser this is always set as ```1``` without the ability to change it. See the following:

https://github.com/photonstorm/phaser/blob/master/src/core/Game.js#L670 (and on line 683)

It would be nice to allow all arguments to be passed through. Or at least those that wouldn't mess other things up (and I'm hoping the resolution change would not).

**Comment by photonstorm** [comment]
This is already done in the dev branch #1621

**Comment by tmaiaroto** [comment]
Sweet! Thanks.
