### ISSUE TITLE
Fixed timestep question

### ISSUE THREAD

**Issue by qdrj** [photonstorm/phaser#1678]
I'm trying to understand how game.update works. And I can't understand this line at all
https://github.com/photonstorm/phaser/blob/dev/src/core/Game.js#L778
```javascript
this.updateRender(this.time.slowMotion * this.time.desiredFps);
```

Why this.time.desiredFps is used? Shouldn't it be (1 / this.time.desiredFps)?

**Comment by photonstorm** [comment]
Look at what time.slowMotion equates to.
