### ISSUE TITLE
Keyboard Events not triggered in IE when game is in iFrame

### ISSUE THREAD

**Issue by webholics** [photonstorm/phaser#1681]
The Phaser examples (e.g. http://phaser.io/examples/v2/input/keyboard ) regarding keyboard events are not working correctly in IE9, IE10. The keyboard events are never triggered.

I currently have the same problem with a game of mine which is running in an iframe. The fix which is stated here does NOT work: 
http://www.html5gamedevs.com/topic/7069-addkeycapture-not-working-in-ie/

**Comment by pnstickne** [comment]
Reproduced locally, IE11/Edge. Unfortunately this issue affects almost all examples..

**Comment by photonstorm** [comment]
In short, the iframe doesn't have focus. You can give it focus by doing `window.focus()` *from within the iframe itself* but only do so once the iframe has fully loaded, i.e. on a document.onReady.

I have added a focus event into Phaser 2.3 to help stop the need to do this manually, but the above definitely works if triggered at the right time. If it doesn't then you've something else in your page stealing focus and need to eliminate for yourself what it is.
