### ISSUE TITLE
checkPixel issue for Not Phaser.Sprite type 

### ISSUE THREAD

**Issue by nextht** [photonstorm/phaser#1684]
In src/input/InputHandler.js checkPixel method, using if (this.sprite.texture.baseTexture.source) for checking Sprite type, but for other type like BitmapText, it has no texture property, we should check BitmapText instance's children for every char Sprite. 

So In phaser-examples-master/examples/text/bitmapfont drag.js, if we set bmpText.input.pixelPerfectClick = true; then when we drag text we will get exception, because bmpText has no texture property.

Hope checkPixel method can be improved for supporting check Not Sprite type.

**Comment by photonstorm** [comment]
I can confirm this *doesn't* throw an error in Phaser 2.3.

Equally it doesn't work, i.e. the pixel click is ignored, but it won't crash. So I'll flag this as a feature request for now.

**Comment by nextht** [comment]
Thanks @photonstorm .
In my project i am doing hittest and checkPixel myself, because i also need to consider cropRect and Text type,  and also i change texture.frame's size NOT using scale, so the customized checkPixel code below work right for me. 
FYR: 

    checkPixel = function (game, sprite, localPoint, pixelPerfect, pixelPerfectAlpha) {
        if(!pixelPerfect){
            return true;
        }
        
        if(pixelPerfectAlpha == NULL){
            pixelPerfectAlpha = 1;
        }
        
        var anchor = sprite.anchor,            
            texture = sprite.texture,
            cropRect = sprite.cropRect,
            x = localPoint.x,
            y = localPoint.y,
            frame = texture.frame,
            trim = texture.trim,
            crop = texture.crop;

        if (anchor.x !== 0)
        {
            x -= -frame.width * anchor.x;
        }

        if (anchor.y !== 0)
        {
            y -= -frame.height * anchor.y;
        }

        x += frame.x;
        y += frame.y;

        if (trim)
        {
            x -= trim.x;
            y -= trim.y;                
            if (x < crop.x || x > crop.right || y < crop.y || y > crop.bottom)
            {
                return false;
            }
        }

        var hitContext = game.input.hitContext;
        hitContext.clearRect(0, 0, 1, 1);
        
        if(sprite instanceof PIXI.Text){
            x *= sprite.canvas.width / frame.width;
            y *= sprite.canvas.height / frame.height;
        }else{
            x *= texture.width / frame.width;
            y *= texture.height / frame.height;
        }
        
        if(cropRect){
            x += cropRect.x;
            y += cropRect.y;
        }        
        
        hitContext.drawImage(texture.baseTexture.source, x, y, 1, 1, 0, 0, 1, 1);        
        var rgb = hitContext.getImageData(0, 0, 1, 1);
        if (rgb.data[3] >= pixelPerfectAlpha)
        {
            return true;
        }
        
        return false;

    };

**Comment by pnstickne** [comment]
I think a good approach would be to move the checkPixel out to the game object types and allow polymorphism/specialization in this case. (BitmapText and Text work a bit differently, for instance.)

**Comment by photonstorm** [comment]
Agreed, although I don't consider this vital enough for the 2.3 release this week. Something for the roadmap perhaps.

**Comment by photonstorm** [comment]
In order to keep the Github issues clear this feature request has been moved to the [Phaser 3 wishlist](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread/).
