### ISSUE TITLE
Loader is catching all kinds of unrelated errors

### ISSUE THREAD

**Issue by photonstorm** [photonstorm/phaser#1689]
cc @pnstickne 

Leaving this here as a reminder to myself, because I think this is going to cause lots of unrelated Github issues. But basically the new Loader is catching errors unrelated to the process of loading assets. For example if *any* error is thrown when adding an asset to the cache, or within the preload or (even worse) in the create function (if called directly after preload), then it's Loader that throws the error in the console. This has caught *me* out lots of times recently, so leaving this here as a reminder to stop it from happening.

**Comment by pnstickne** [comment]
This should .. not be. If the behavior differs radically from previous versions wrt where exceptions are thrown then this is an oversight on my part.

Have an example case to reproduce the issues? (All the `catch` statements funnel through to a handler.)

**Comment by pnstickne** [comment]
This should .. not be. If the behavior differs radically from previous versions wrt where exceptions are thrown then this is an oversight on my part.

Have an example case to reproduce the issues? All the `catch` statements funnel through to a handler and the only known promotion from an event callback I know of is fileComplete for a cached image..

**Comment by photonstorm** [comment]
Here's an example, I'll try and remove what I can from it but it should be clear:

```
    var game = new Phaser.Game(640, 480, Phaser.CANVAS, 'game');

    var PhaserGame = function () {

        this.wasp = null;

    };

    PhaserGame.prototype = {

        preload: function () {

            this.load.atlas('sprites', 'daggers.png', 'daggers.json');

        },

        create: function () {

            this.wasp = this.add.sprite(400, 100, 'sprites', 'wasp1');

            this.add.tween(this.wap).to( { y: 400 }, 2000, "Back.easeInOut", true, 0, 2000, true);

        }

    };

    game.state.add('Game', PhaserGame, true);

    </script>
```

Note that the actual error is the line `this.add.tween(this.wap)` where I put a typo into the sprite name. However this throws an error from the Loader - specifically:

![sshot-2015-03-24- 6](https://cloud.githubusercontent.com/assets/164476/6814595/f61a6202-d277-11e4-90e3-cc55a2431580.png)

**Comment by pnstickne** [comment]
Hmm, the error is caught in an async XHR event which emits the console warning. Instead of always displaying such a warning (as it is the case now) the warning can be removed or guarded with a `debug` flag. At the very least a better error message would be useful.

The error will still be reported through `loader.onFileError` (with or without the explicit console warning).

However this ought _not_ to be related to anything in create.. I think the error shown might be coming from `Phaser.AnimationParser.JSONData` which is called from within `cache.addTextureAtlas` (which is called when the XHR request completes). But as to why/how this is triggered from the tween code, I don't currently know.

**Comment by pnstickne** [comment]
Oh, _unless_ ..

**Comment by photonstorm** [comment]
Just to add - the error being thrown can be *any* JavaScript error. It doesn't have to be a Phaser level error, quite simply any error that would normally be dumped to the console is re-routed to the Loader instead. Don't let the fact that it's a tween in the code above lead you in a false direction.

Equally the fact the error is in 'textureatlas[sprites]' is just because that was the last file loaded. If you add say an audio file into the preload and it loads last, it will be thrown in there instead.

**Comment by photonstorm** [comment]
Have started work on this. Narrowing it down further I see that it *does* matter what file was loaded in the Preloader. Swap the above for a normal image and the error comes from Tween.js as it should. I reckon any loaded file that consists of two files (like a bitmap text, atlas, etc) is the root.

**Comment by photonstorm** [comment]
Phew that took a long time to track down! But I've fixed it.
