### ISSUE TITLE
Phaser.Text gets cut off at bottom if value for lineSpacing is negative

### ISSUE THREAD

**Issue by anthonysapp** [photonstorm/phaser#1690]
If you supply an instance of Phaser.Text with a negative value for lineSpacing, its resulting height causes its text to be cut off at the bottom.

**Phaser.Text line 398**
`var height = (lineHeight + this._lineSpacing) * lines.length;`

**My current fix:** 
`var height = (lineHeight + (Math.max(this._lineSpacing, 0))) * lines.length;`

**Comment by photonstorm** [comment]
This is now fixed in the dev branch. A little differently to your solution above, but definitely inspired as a result of posting this issue.
