### ISSUE TITLE
P2 Contact signals never fire

### ISSUE THREAD

**Issue by englercj** [photonstorm/phaser#1691]
Right now the listeners for the p2 `beginContact` and `endContact` events are removed by the `clear()` method in Phaser.Physics.P2.World:

https://github.com/photonstorm/phaser/blob/dev/src/physics/p2/World.js#L823-L824

This means each state change they are unloaded, which works properly. They are then added back in by the `reset()` method:

https://github.com/photonstorm/phaser/blob/dev/src/physics/p2/World.js#L752-L753

Which the docs say is "called by Phaser.Physics when a State swap occurs". This method is actually never called though, so the event handlers are never called. This makes the signals never fire and I can't actually detect these events in my app without tying directly into the underlying world implementation.

This is using the latest `dev` version (2.3.0). I would've put in a PR, but I wasn't sure what the best way to handle this was.

**Edit**: After some more digging I see that the `startSystem()` method calls `reset()`, but `startSystem()` isn't used in Phaser code anywhere. Is it expected that each of my states needs to call `startSystem(Phaser.Physics.P2JS)` when the state starts up? I can get it to work if I call `this.game.physics.startSystem(Phaser.Physics.P2JS);` from the create method in my states that need physics, is that the proper way to do it?

**Comment by photonstorm** [comment]
Can you have a look at the current dev branch and see if that works for you? You should only ever have to start the physics system once, reset should be handled automatically (and hopefully now is)

**Comment by englercj** [comment]
Looks good, thanks!
