### ISSUE TITLE
Phaser.Component.Core.preUpdate brokes BitmapText

### ISSUE THREAD

**Issue by nextht** [photonstorm/phaser#1692]
In Phaser.Component.Core.preUpdate method this.children[i].preUpdate(); is called, but not all the child is Type of Phaser.*.

Like BitmapText's children is just PIXI.Sprite, so it's child has no preUpdate method.

**Comment by photonstorm** [comment]
Please always pull and *build* the latest version before posting issues here (as you'd see this isn't an issue at all then).

Specifically: https://github.com/photonstorm/phaser/blob/dev/src/pixi/display/DisplayObject.js#L491

**Comment by nextht** [comment]
Sorry @photonstorm  i got latest phaser.js from https://github.com/photonstorm/phaser/blob/master/build/phaser.js

**Comment by photonstorm** [comment]
Ah I thought so - please always build from source. I rarely push up new builds to the dev branch so they are always massively behind what the source is actually doing.
