### ISSUE TITLE
Phaser.Polygon.prototype.contains not working rightly

### ISSUE THREAD

**Issue by nextht** [photonstorm/phaser#1693]
I found in Phaser 2.3.0 PIXI.Polygon = Phaser.Polygon; but when i test hittest for Phaser.Graphics in Phaser.Polygon.prototype.contains, it doesn't work as old version. 

Now i replace Phaser.Polygon.prototype.contains back to PIXI.Polygon's implement, it works. So there must be something wrong in the Phaser.Polygon.prototype.contains implement.

	Phaser.Polygon.prototype.contains = function(x, y)
	{
		var inside = false;

		// use some raycasting to test hits
		// https://github.com/substack/point-in-polygon/blob/master/index.js
		var length = this.points.length / 2;

		for(var i = 0, j = length - 1; i < length; j = i++)
		{
			var xi = this.points[i * 2], yi = this.points[i * 2 + 1],
				xj = this.points[j * 2], yj = this.points[j * 2 + 1],
				intersect = ((yi > y) !== (yj > y)) && (x < (xj - xi) * (y - yi) / (yj - yi) + xi);

			if(intersect) inside = !inside;
		}

		return inside;
	};

**Comment by photonstorm** [comment]
That's not the `contains` method Phaser 2.3-dev is using any more. I'm not sure when you last pulled the repo down, but it often changes multiple times *every day*, so it would be worth always doing that first before checking something.

The Polygon Contains Example in the Examples repo is working fine with the current 2.3-dev. Feel free to re-open this if you can create a valid polygon it doesn't work with though.
