### ISSUE TITLE
Possible to go through solid tiles via one-way-collision tiles

### ISSUE THREAD

**Issue by nkholski** [photonstorm/phaser#1699]
Going from tiles with collision set to true on at least one side (and a least one set to false) will make make collision detection fail on entering adjacent tiles. (as seen here when jumping around the animated arrows, or jumping on a arrow to the right or the left on the ground at http://dev.niklasberg.se/phaser-tiled-extras/example)

I've tested with Phaser 2.2.2 and current 2.3.0-dev. I'm using calculateFaces in the example, but have tried to set all faces to true with the same result.

**Comment by photonstorm** [comment]
Sorry this has been a bug for so long. I'm afraid I'm going to have to close it off as a known limitation of the current system, rather than let it linger any longer (as there is no clean and quick solution for it that I can see)
