### ISSUE TITLE
Phaser.TilemapLayer InputEnabled is deprecated ?（ in dev branches）

### ISSUE THREAD

**Issue by uhe1231** [photonstorm/phaser#1700]
i test my game use dev branches.

but the TilemapLayer can't click, i find 'TilemapLayer.js' file line 264, is not have InputEnabled,

that is deprecated?

**Comment by viliamjr** [comment]
The same happens here with **v2.3.0**.

`InputEnabled` component is required to make `MyEvent` fire:
```javascript
layer = map.createLayer('layerFooBar');
layer.resizeWorld();

layer.inputEnabled = true;
layer.events.onInputDown.add( this.MyEvent, this );
```

**Comment by photonstorm** [comment]
This is now fixed in dev, please test.

**Comment by viliamjr** [comment]
:+1:
