### ISSUE TITLE
Signal addOnce cannot be reset during dispatch

### ISSUE THREAD

**Issue by AlexMouton** [photonstorm/phaser#1701]
Hi folks!

I noticed today that SignalBinding doesn't use its own identity to remove itself from its Signal on dispatch, and instead calls Signal.remove( handler, context ).  If I have received a more general signal that I intend to intercept one instance of, and reregister my handler for a first instance that I wish to ignore, My added, second handler, context pair is removed by the general call, and is not honored.

I worked around this with setTimeout( function() { addOnce; } ) which is unpleasant.

Would you all support a change to a more specific SignalBinding removal?

Thanks
Alex Mouton
@benchun

**Comment by photonstorm** [comment]
That's an interesting requirement - and yes, if you want to submit a PR then please do (be sure it's against the dev branch though)

**Comment by AlexMouton** [comment]
I looked at it a little more closely:
1. addOnce is called with a handler and a context, and adds a binding.
2. Signal.Dispatch is called, which calls the binding and in turn the handler.
3. The handler calls addOnce a second time, before binding.detatch/signal.remove.
4. addOnce finds the existing binding matches the handler/context and returns a reference to it.
5. Binding execution calls binding.detach -> signal.remove which removes the binding from the signal, and actively destroys it.
fin: the signal is left with no bindings.

**Comment by photonstorm** [comment]
So in other words, it works fine? :)

**Comment by AlexMouton** [comment]
Not for my purpose.  The symptom is the same, I'm just working towards potential changes.

**Comment by jdnichollsc** [comment]
This example doesn't work well...

var demoState = {
	create: function(){
                  //code code code...
		  this.btnContinue.onInputDown.addOnce(this.goToInst, this); //works good
	},
	goToInst: function(){
		  this.btnContinue.onInputDown.addOnce(this.goToMenu, this); //This doesn't work on the first click
	},
	goToMenu: function(){
		  this.game.state.start('menu');
	}
}

Regards, Nicholls

**Comment by photonstorm** [comment]
The following works fine for me (Phaser 2.4..7 dev branch version), so I'm going to close this off unless a code sample showing it not working can be provided.

```

var game = new Phaser.Game(800, 600, Phaser.AUTO, 'phaser-example', { preload: preload, create: create });

function preload() {

    game.load.spritesheet('button', 'assets/buttons/button_sprite_sheet.png', 193, 71);

}

var button;

function create() {

    button = game.add.button(200, 200, 'button', null, this, 2, 1, 0);

    button.onInputDown.addOnce(stage2, this);

}

function stage2() {

    console.log('stage2');

    button.onInputDown.addOnce(stage3, this);

}

function stage3() {

    console.log('stage3');

    button.onInputDown.addOnce(stage4, this);

}

function stage4() {

    console.log('stage4');

}
```

**Comment by jdnichollsc** [comment]
Excellent :dancers:
