### ISSUE TITLE
TileSprite not colliding with Sprite 

### ISSUE THREAD

**Issue by numbofathma** [photonstorm/phaser#1702]
After updating to 2.3.0 the main character of my game falls through the ground.

You can see the same issue in the example below: 
http://phaser.io/examples/v2/tile-sprites/colliding-with-tiling-sprite#gv

**Comment by photonstorm** [comment]
Damn it, yes - because TileSprites don't have a physicsType property. You can fix this in 2.3.0 by doing this:

```
yourTileSprite.physicsType = Phaser.SPRITE;
```

I've also uploaded a fix to the dev branch.
