### ISSUE TITLE
disabled state for Button

### ISSUE THREAD

**Issue by cuixiping** [photonstorm/phaser#1703]
If there is a **disabled** state and disabledFrame, the Button will be easier to use.

new Button(game, x, y, key, callback, callbackContext, overFrame, outFrame, downFrame, upFrame, **disabledFrame**)

**disabled** :boolean

**Comment by photonstorm** [comment]
Code it and submit a pull request.

**Comment by cuixiping** [comment]
I will try.

**Comment by nesukun** [comment]
@cuixiping You can use this as a start point:
https://github.com/bernatmv/phaserito/blob/master/src/lib/modules/button.js
Is way behind our current codebase but thought it might help you.
There's also a toggle easily implemented on top of that
https://github.com/bernatmv/phaserito/blob/master/src/lib/modules/toggle.js

**Comment by photonstorm** [comment]
In order to keep the Github issues clear this feature request has been moved to the [Phaser 3 wishlist](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread/).
