### ISSUE TITLE
it seems that scale.forceOrientation is not working

### ISSUE THREAD

**Issue by eugenioclrc** [photonstorm/phaser#1705]
I have use the starter template from;
https://github.com/photonstorm/phaser/tree/master/resources/Project%20Templates/Full%20Screen%20Mobile

It never triggers the scale.enterIncorrectOrientation or scale.leaveIncorrectOrientation callback.

**Comment by photonstorm** [comment]
Have you tested it on device? On a desktop, even under mobile emulation, it will never trigger the event as it uses the Screen Orientation API to determine it.

**Comment by eugenioclrc** [comment]
Yep richard, you are right.
In desktop mobile emulation the "orientationchange" event wont trigger;
window.addEventListener("orientationchange", function() { /* this will never trigger */ })
