### ISSUE TITLE
Sprite/Image/Loader key issue

### ISSUE THREAD

**Issue by alamboley** [photonstorm/phaser#1708]
Hey, I'm a bit confused about the use case of the "key" element for a [Sprite](http://phaser.io/docs/Phaser.Game.html/Phaser.Sprite.html) or an [atlas loader](http://phaser.io/docs/Phaser.Game.html/Phaser.Loader.html#atlas).

Supposing that I'm making a shop inside a game with many elements : weapons, characters accessories, etc. It'll be on *several sprite sheets*. I'm using the TexturePacker magic folder (everything inside the folder is exported as one or more TextureAtlas), and I don't want to bother to know on which sprite sheets does the X texture has been exported too.
At the moment with Phaser, I've to know where each element is due to the key :
```haxe
load.atlasJSONHash('avatar1', 'assets/' + Main.scaleFactor + 'x/avatars1.png', 'assets/' + Main.scaleFactor + 'x/avatars1.json');
load.atlasJSONHash('avatar2', 'assets/' + Main.scaleFactor + 'x/avatars2.png', 'assets/' + Main.scaleFactor + 'x/avatars2.json');

bg = add.image(0, 0, 'avatar2', 'shopBG.png', container);

sword = add.image(0, 0, 'avatar1', 'shopSword.png', container);
```
This is a bit complicated to automate due to key thing (imagine a for loop). Why does each texture isn't just referenced into a **Dictionary**? And we would access them thanks to their strict name (which must be unique)? Or maybe being able to combine key at least.
If you add multiple size assets, which can be combined differently by TexturePacker on the TextureAtlas, it becomes to be real nightmare.
Obviously, I can force the layout etc. but I will lost all those magic things.

**Comment by photonstorm** [comment]
I don't use their filenames as a key because they're just so bloody long-winded to type in! As they have to include the full URL *and* path in order to be fully unique, and in some games I've seen even have to include the query string as well (where server-side scripts are generating pngs)

If you meant something other than file path + name as their 'strict' name, what was it?

**Comment by alamboley** [comment]
Well, I think there are some misunderstood. I wonder why it isn't simply:
```haxe
load.atlasJSONHash('assets/' + Main.scaleFactor + 'x/avatars1.png', 'assets/' + Main.scaleFactor + 'x/avatars1.json');
load.atlasJSONHash('assets/' + Main.scaleFactor + 'x/avatars2.png', 'assets/' + Main.scaleFactor + 'x/avatars2.json');

bg = add.image(0, 0, 'avatar2', 'shopBG.png', container);

sword = add.image(0, 0, 'shopSword.png', container);
```
So without a *key* element. The graphic will be grab from a gobal Dictionary.
But I probably missed several use case!?

**Comment by photonstorm** [comment]
So how would you tell the difference between these:

```
load.atlas('level1/baddies.png');
load.atlas('level2/baddies.png');
load.atlas('http://otherdomain.com/gfx/baddies.png');
load.atlas('baddie_generator.php?file=baddies.png');
```
?

**Comment by alamboley** [comment]
Indeed, we can't, unless we may use: `baddies = add.image(0, 0, 'level2/baddies.png', container);`

Anyway, I think I just need something like:
```haxe
load.atlasJSONHash('avatar', 'assets/' + Main.scaleFactor + 'x/avatars1.png', 'assets/' + Main.scaleFactor + 'x/avatars1.json');
load.atlasJSONHash('avatar2', 'assets/' + Main.scaleFactor + 'x/avatars2.png', 'assets/' + Main.scaleFactor + 'x/avatars2.json');

load.combineKey('avatar', 'avatar2');

bg = add.image(0, 0, 'avatar', 'shopBG.png', container);

sword = add.image(0, 0, 'avatar', 'shopSword.png', container);
```

**Comment by photonstorm** [comment]
Texture Packer has support for splitting an atlas across multiple image files. What is needed is support for that feature (on a Sprite / animation level). This would solve the above without having to add any more methods into the Loader class. I'll keep this flagged as a feature request for now, whether it makes it into Phaser 2 or 3 remains to be seen really.

**Comment by photonstorm** [comment]
In order to keep the Github issues clear this feature request has been moved to the [Phaser 3 wishlist](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread/).
