### ISSUE TITLE
 cocoonjs launcher with phaser 2.2.0+, the sprite movement is jitter

### ISSUE THREAD

**Issue by vanessachem** [photonstorm/phaser#1709]
When I use cocoonjs launcher with phaser 2.2.0+, the sprite movement is jitter. Meaning the movement will randomly suddenly moving back and forth (like a string) then keep moving.
 
Simply create a sprite and give it velocity.x = 500 ( or tween) can reproduce the problem.
 
I googled and found long time ago version 1.1.3 or 1.1.4 has the similar issue. Someone used word "choppy". link:
http://www.html5game...-things-choppy/
 
I also made some effort to change phaser version and found version 2.1.0/2.0.0 is good, or acceptable. The jitter only happen very occasionally. But start from 2.2.0 it is very noticeable. I

I tested on fire phone and samsung tab 2. Both shows same problem.
 
I am guessing something happened between version 2.1 to 2.2 and it is not easy to notice this problem  as it will not show up in the browser.

**Comment by clark-stevenson** [comment]
This is probably not helpful, but just for a test, can you try to add this to the boot up code and try again?

`this.game.forceSingleUpdate = true;`

**Comment by clark-stevenson** [comment]
Hmm, same here. I am completely snowed under this year with work but something still bugs me with performance related to this.

On a desktop gaming PC, forceSingleUpdate simply runs silky smooth.  Perfect, 60fps.

But when false, there is something else at play which causes spikes and the spikes are not relevant to the visual state of the application.  Meaning that any point in the game could either look smooth, or be grinding a bit. 

I updated all games to forceSingleUpdate = true for that reason. 

I know none of this is helpful but I will get around to properly investigating it as soon as I can.
