### ISSUE TITLE
Can not get graphics.generateTexture to work in 2.3

### ISSUE THREAD

**Issue by PaulTodd** [photonstorm/phaser#1712]
This code works in 2.1.1 but I can't get it to work in 2.3.  What should I be doing to get it to work?

var Shape = new Phaser.Polygon();
Shape.setTo([ new Phaser.Point(200, 100), new Phaser.Point(350, 100), new Phaser.Point(375, 200), new Phaser.Point(150, 200) ]);
var graphics = this.game.add.graphics();
graphics.beginFill(0xFF33ff);
graphics.drawPolygon(Shape);
graphics.endFill();
var sprite = this.game.add.sprite(10, 10, graphics.generateTexture());
graphics.destroy();

**Comment by photonstorm** [comment]
This is addressed in 2.3.1-dev, in the meantime you can fix it by passing the points property:

`graphics.drawPolygon(Shape.points);`
