### ISSUE TITLE
Failed to execute 'putImageData' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by Erik3000** [photonstorm/phaser#1714]
Hello, when I try to run my phaser game in Epic Browser, I receive this error:

 Uncaught TypeError: Failed to execute 'putImageData' on 'CanvasRenderingContext2D': parameter 1 is not of type 'ImageData'.                                  (phaser230.js:8163 )
PIXI.CanvasTinter.checkInverseAlpha                    (phaser230.js:8163)
(anonymous function)                                            (phaser230.js:8198)
(anonymous function)                                            (phaser230.js:12437)

I use newest phaser 2.3.0, it happens on line 8163
error occures in this method (line: canvas.context.putImageData(s1, 1, 0);):

    /**
     * Checks if the browser correctly supports putImageData alpha channels.
     * 
     * @method checkInverseAlpha
     * @static
     */
    PIXI.CanvasTinter.checkInverseAlpha = function()
    {
    var canvas = new PIXI.CanvasBuffer(2, 1);

    canvas.context.fillStyle = "rgba(10, 20, 30, 0.5)";

    //  Draw a single pixel
    canvas.context.fillRect(0, 0, 1, 1);

    //  Get the color values
    var s1 = canvas.context.getImageData(0, 0, 1, 1);

    //  Plot them to x2
    canvas.context.putImageData(s1, 1, 0);

    //  Get those values
    var s2 = canvas.context.getImageData(1, 0, 1, 1);

    //  Compare and return
    return (s2.data[0] === s1.data[0] && s2.data[1] === s1.data[1] && s2.data[2] === s1.data[2] && s2.data[3] === s1.data[3]);
    };

Do you have iny idea what to do with that? Thank you

**Comment by photonstorm** [comment]
They have blocked some of the really important Canvas features we need such as `context.getImageData` - which means lots of features break such as Text, BitmapData, Canvas Tinting, etc won't work correctly. However I've just pushed up some fixes so at least basic games will work now.
