### ISSUE TITLE
Rotate and scale an image

### ISSUE THREAD

**Issue by cscott5288** [photonstorm/phaser#1716]
I'm having a problem rotating and scaling an image. It seems if you perform a rotation on an image/sprite object, then scale, the result of the scale is as if it was never rotated.

 I think what's happening is that the scale manager is using the original texture of the sprite/image to rotate, then is also using the original image to scale. Instead of using the original texture to rotate, then using the new rotated image to scale. 

Is there any way to rotate, then scale the newly rotated image?

**Comment by photonstorm** [comment]
You need to provide some example code, because I can't replicate this for the life of me.

**Comment by photonstorm** [comment]
http://phaser.io/sandbox/oyeURgyC

**Comment by cscott5288** [comment]
Thanks so much for getting back to me.

On the left is the image rotated first then sized down in photoshop. On the right is the image sized down first then rotated:
http://i.imgur.com/6JIFxSl.png

That's how the sprite should look when you compare rotation (45 degrees) first vs scale (half of height) first. But it seems in Phaser you can only achieve scale first, even if you specify the rotation first:

function create() {

 var spriteB = game.add.sprite(400, 200, 'phaser');
    
  spriteB.rotation = .78;  // or .angle = 45;
  spriteB.scale.set(1,.5);

 var spriteC = game.add.sprite(500, 200, 'phaser');
 
  spriteC.scale.set(1,.5);
  spriteC.rotation = .78;  // or .angle = 45; 

}

I couldn't quite figure out how to fork your code. I didn't see a button for it. But if you paste the above into your sandbox, you will see that the effects are the same, regardless of the order of rotate/scale.

**Comment by photonstorm** [comment]
Right ok that makes more sense. The reason it doesn't matter which order
you do it in phaser is because it applies a transform to the object at
render time. The transform will both scale and rotate together, not in
sequence, it's a single operation - the underlying texture is never
touched. Photoshop doesn't transform at all, it just manipulates the pixels.

Even if you were to put the sprite inside another and scale the parent and
rotate the child it still won't make a difference as it's just a single
calculated transform.

What you could try is to use cacheAsBitmao, so scale it, cache it, then
rotate as that will then be working from a new texture.



On Friday, April 3, 2015, cscott5288 <notifications@github.com> wrote:

> Thanks so much for getting back to me.
>
> On the left is the image rotated first then sized down in photoshop. On
> the right is the image sized down first then rotated:
> http://i.imgur.com/6JIFxSl.png
>
> That's how the sprite should look when you compare rotation (45 degrees)
> first vs scale (half of height) first. But it seems in Phaser you can only
> achieve scale first, even if you specify the rotation first:
>
> function create() {
>
> var spriteB = game.add.sprite(400, 200, 'phaser');
>
> spriteB.rotation = .78; // or .angle = 45;
> spriteB.scale.set(1,.5);
>
> var spriteC = game.add.sprite(500, 200, 'phaser');
>
> spriteC.scale.set(1,.5);
> spriteC.rotation = .78; // or .angle = 45;
>
> }
>
> I couldn't quite figure out how to fork your code. I didn't see a button
> for it. But if you paste the above into your sandbox, you will see that the
> effects are the same, regardless of the order of rotate/scale.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/1716#issuecomment-89317905>.
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by cscott5288** [comment]
I'm afraid cacheAsBitmap doesn't work no matter what order i put it in (scale, cache, rotate; rotate, cache, scale, etc). :(

var spriteC = game.add.sprite(500, 200, 'phaser');
spriteC.rotation = .78; // or .angle = 45;
spriteC.cacheAsBitmap = true; 
spriteC.scale.set(1,.5);

Any other ideas? I'd like to avoid going a bitmap route because there are A LOT of images. Thanks for the help!

**Comment by cscott5288** [comment]
Well I've hit a complete dead end. Spent the entire weekend trying to do this: tried  it with tweens, bitmaps, scale manager, nope, the result is always the same. You can't size down an image that's been rotated. You can only size down the original image dimensions. This really sucks because I have to rewrite large aspects of the game as a workaround. In the planning stages I really thought I would be able to do this.

**Comment by photonstorm** [comment]
Closing this off because I'm afraid this just isn't how affine transformations work. It has to be done as a 2-step process (one to rotate, create a new texture from that, the another to scale it). It can't be done in a single draw call.

**Comment by clark-stevenson** [comment]
That was cool I never knew that.
