### ISSUE TITLE
Reading Dimensions of Text Resets Resolution on Text  in Phaser 2.3.0

### ISSUE THREAD

**Issue by joelika** [photonstorm/phaser#1717]
If the resolution config option is set for Phaser, reading the dimensions of text will cause Phaser to re-render the text with a resolution of 1 instead of the set value.

See the jsfiddle for examples on a device with window.devicePixelRatio greater than 1.

https://jsfiddle.net/dbw3jbdz/

**Comment by photonstorm** [comment]
This is now fixed in dev.
