### ISSUE TITLE
Weird behaviour with Graphics

### ISSUE THREAD

**Issue by TimvdEijnden** [photonstorm/phaser#1720]
This one uses Phaser 2.3.0:
http://jsfiddle.net/TimvdEijnden/221zh9oy/
Here the red circle cannot be hidden by changing the visible property.

And this one uses Phaser 2.2.2
http://jsfiddle.net/TimvdEijnden/feh1wjvm/1/
Here the red circle is hidden by default.

Both code is identical except the phaser version is different.

**Comment by photonstorm** [comment]
This is now fixed in the dev branch.
