### ISSUE TITLE
Definition files should be pushed to Definitely Typed repo.

### ISSUE THREAD

**Issue by Nimrodxx** [photonstorm/phaser#1724]
It would be great if the TypeScript definition files would be pushed to the global Definitely Typed repo (https://github.com/borisyankov/DefinitelyTyped). It currently contains outdated versions, pixi is for instance at 1.3.

**Comment by photonstorm** [comment]
I agree it would, but this isn't something I've time to look after myself I'm afraid. If someone wants to submit them then please go ahead.
