### ISSUE TITLE
game.physics.p2.getConstraints(); filles an array with "undefined"

### ISSUE THREAD

**Issue by valueerrorx** [photonstorm/phaser#1726]
game.physics.p2.world.constraints.splice(0,game.physics.p2.world.constraints.length);
delivers all constraints but 

    game.physics.p2.getConstraints(); 

delivers an array with "undefined" in it.

**Comment by photonstorm** [comment]
Ah yes, constraints don't have a parent / data property in the same way that Springs do. This is now fixed in dev.

**Comment by valueerrorx** [comment]
great .. thx !
