### ISSUE TITLE
update `State.init` type definition

### ISSUE THREAD

**Issue by ggarek** [photonstorm/phaser#1729]
The ```State.init``` method can be passed additional arguments, but it`s signature in [phaser.d.ts](https://github.com/photonstorm/phaser/blob/master/typescript/phaser.d.ts#L4120) does not allow it.

Although the [StateManager](https://github.com/photonstorm/phaser/blob/master/typescript/phaser.d.ts#L4177)  has correct signature for ```StateManager.start```.

Without it one should think of how to make the typescript compiler "happy" about it.

Suggested edition:

```javascript
class State {
  //...
  init(...args: any[]): void;
  //...
}
```

It would be nice to have this fix,
Thanks!

**Comment by clark-stevenson** [comment]
Thanks mate! Added as PR. Do not hesitate to make PR against the dev branch if you feel anything else is missing.

**Comment by ggarek** [comment]
I will definitely! Thanks =)

**Comment by photonstorm** [comment]
Now merged with dev.
