### ISSUE TITLE
Rope problems with newer Phaser

### ISSUE THREAD

**Issue by vancura** [photonstorm/phaser#1731]
Hey,

The [Rope example](https://github.com/codevinsky/phaser-rope-demo) doesn't compile on recent Phaser due to:

```
TypeError: undefined is not an object (evaluating 'this.texture.baseTexture.scaleMode')
```

This is not caused by the example itself, but more by non-existing texture (AFAIK). The stock phaser.js from the repo works well, I just tried 2.3.0 and it's failing there.

Thanks,
V.

**Comment by nextht** [comment]
I encounter the same problem, i change the Phaser.Component.LoadTexture.prototype.loadTexture implementation to work around, that must be Phaser 2.3.0 bug. /c @photonstorm  

	var smoothed = this.texture.baseTexture ? !this.texture.baseTexture.scaleMode : false;

**Comment by photonstorm** [comment]
This is now properly fixed in the dev branch, including the segments getter and the rope debug not taking the rope scale into account.
