### ISSUE TITLE
isMouse doesn't do what it says

### ISSUE THREAD

**Issue by GregoryAveryWeir** [photonstorm/phaser#1732]
Currently, isMouse is always true for pointer zero, even if pointer zero isn't a mouse (i.e. on an iPhone).

While I recognize this is tricky to accomplish thanks to mobile browser event models, I'd like to be able to have hover effects that do not show up when a touch pointer is being used.

Currently I'm accomplishing this by checking to see if device.touch is false, but that's not ideal as it doesn't allow hover effects for devices that have both mouse and touch.

**Comment by photonstorm** [comment]
Pointer zero is reserved exclusively for the mouse, even on touch devices where a mouse isn't present. It's mapped to `Input.mousePointer` and will have `isMouse` set to true. All other pointers created (i.e. `Input.pointer1`, `Input.pointer2`, etc) will have `isMouse` set to false. If you access the active pointer via Input.activePointer then isMouse will accurately reflect if it was the mouse or not. If you only access Input.pointer1 then isMouse will never be true. If for some reason you are accessing Input.pointers[0] then this is the same as Input.mousePointer, regardless of device.

**Comment by GregoryAveryWeir** [comment]
On an iPhone simulator, I'm pretty sure I'm observing touch events (specifically, a moveCallback) where the pointer passed to the moveCallback has isMouse true. Is this an artifact of using the simulator?

**Comment by photonstorm** [comment]
What about on an actual device?

**Comment by GregoryAveryWeir** [comment]
I'll see if I can set up a test of that.

**Comment by GregoryAveryWeir** [comment]
Okay, this is very weird. I'm testing on an actual device now, and isMouse works in the general case. However, in my game, if I touch a Phaser.Button, the pointer now has isMouse = true.

I'm still investigating to see if it's something I'm doing, but I haven't found anything in my code yet.

**Comment by GregoryAveryWeir** [comment]
Deleted my earlier incorrect guess.

It looks like setting input.touch.preventDefault to false is the root of the problem. I want my users to be able to touch-scroll even with the game, but when I set touch.preventDefault = false, the following happens:

First touch: Pointer 1 is used.
Second touch: Pointer 2 is used.
Third touch: Pointer 0 (isMouse == true) is used.

Is this the intended behavior for preventDefault? Is there a better way for me to allow my users to touch-scroll the parent page when touching the game?

**Comment by photonstorm** [comment]
This doesn't surprise me - the event is bubbling up to the browser and I suspect coming back down again. I'd suspect what is happening is that because the event is propagating you're seeing it fire BOTH a touch and mouse event from a single click. Ideally you ought to catch the event when it hits the top layer (outside the Phaser game) and stop it from going any further, but it might be too late by then anyway (i.e. it may have already triggered a corresponding mouse event)

**Comment by GregoryAveryWeir** [comment]
That makes sense. I will investigate that as an option. Thank you for your patience!
