### ISSUE TITLE
Off-screen tweens seem to cause problems

### ISSUE THREAD

**Issue by hilts-vaughan** [photonstorm/phaser#1733]
When I'm tweening something off the screen and then quickly snap back into the view, it seems like there's some issues. It seems like the sprite 'races' back into the position it should have been in on screen. This on the latest Phaser version, but not development. It has been happening since about a year ago. I've uploaded an AVI below; check between 3s - 4s and observe carefully what happens when I snap back on screen.

 The player character is "Himeragi".

https://mega.co.nz/#!WlJDjKSY!yK4p16FCCCb2pNAUiIMgFUJIKod4r-pCcB64FSonMG0

I'm tweening the X and Y; and it seems like it's not instant. I am firing many tweens behind the scenes, about 95ms in duration each, back to back where possible. It seems like it's taking the initial position and the last possible tween, and tweening to that position in what looks to be 95ms or less? I can't really tell.

Here's two images to show:

![tween001](https://cloud.githubusercontent.com/assets/1079207/7102803/366b2512-e05b-11e4-8e34-341d93133a12.PNG)
![tween002](https://cloud.githubusercontent.com/assets/1079207/7102804/378ea784-e05b-11e4-8013-8fe43d609b2d.PNG)

Note the bottom right snake.

**Comment by hilts-vaughan** [comment]
It seems like the body's x and y do not match with the actual position, which is the cause of the issue for me (you can see the body lagging behind.)

I've worked around it but not sure if a legitimate bug. Let me know.

**Comment by photonstorm** [comment]
Sorry but I really can't tell just from a video - I need to see this happening in code to get an idea what's going on, ideally as minimal a piece of code as possible. Feel free to re-open with such.

**Comment by hilts-vaughan** [comment]
It ended up being fixed in a later rev. Not sure what happened.
