### ISSUE TITLE
Updated tile properties not being displayed (alpha, rotation)

### ISSUE THREAD

**Issue by bigtunacan** [photonstorm/phaser#1737]
I'm checking if a tile has been clicked and then changing properties on the tile to display the interaction, the tiles never change, but the browser tools show that they have been updated.

Here is a link to the affected file in an open github repo https://github.com/bigtunacan/tint/blob/master/index.html

The bulk of the code related to this issue is included here though.

        function update(){
              if(game.input.mousePointer.isDown){
                  downer = {
                      "mouseX": game.input.mousePointer.x,
                      "mouseY": game.input.mousePointer.y,
                      "mouseState": "down",
                      "dirty": "true"
                  }
              }else{
                 if(downer.dirty === "true") {
                     downer.dirty = "false";
                     arr_touched_tiles = bg_map_layer.getTiles( game.input.mousePointer.x, game.input.mousePointer.y, 10, 10); 
                 }
              } 
            }
            
            function render(){
              for(var i = 0; i < arr_touched_tiles.length; i++){
                  arr_touched_tiles[i].alpha = 0.0;
                  arr_touched_tiles[i].rotation = 40;
              }
              if(arr_touched_tiles.length > 0){
                  arr_touched_tiles.splice(0, arr_touched_tiles.length);
              }
            }

**Comment by bigtunacan** [comment]
Upon further exploration I see that the properties are set on the first update and future updates are never reflected.

As an example the following I would expect to show a tile changing rotations, but instead it displays at a random rotation upon page load, but then never changes.

    function update(){
      foobar = bg_map_layer.getTiles( 0,0, 1, 1); 
      foobar[0].alpha = 0.5;
      foobar[0].rotation = Math.random() * 140;
    }

**Comment by hilts-vaughan** [comment]
Have you tried setting the TilemapLayer's to dirty after a change? It might
be an easy to work around this

**Comment by bigtunacan** [comment]
@hilts-vaughan Thanks; that did the trick.
