### ISSUE TITLE
On iOS 8 in landscape mode, if the navigation bar opens, game.height doesn't change

### ISSUE THREAD

**Issue by alamboley** [photonstorm/phaser#1743]
Does Phaser can manage this under the hood and I missed something or I've to do it myself?

Opening the iOS navigation bar dispatch setResizeCallback, then I will have to setGameSize accordingly?

**Comment by alamboley** [comment]
I tried to manage it on my side, but since I use `ScaleManager.RESIZE`, `setGameSize`doesn't have any effect.

So Phaser should definitely handle it on this own.

**Comment by photonstorm** [comment]
If the State.resize function gets called (or the `onSizeChange` Signal gets dispatched) then you can adapt your game size accordingly. If neither of those two things happen then iOS isn't triggering a `window.resize` event, so there's nothing you can actually do directly from Phaser, as it doesn't consider the window as having changed size.
