### ISSUE TITLE
SoundManager throws an error when no audio is supported

### ISSUE THREAD

**Issue by englercj** [photonstorm/phaser#1746]
In the case that no audio is supported (no web audio, no audio tag) then the SoundManager throws on a call of `pauseAll()`.

It is because on this line:

https://github.com/photonstorm/phaser/blob/dev/src/sound/SoundManager.js#L210

Here, context is `null` since webaudio doesn't exist, but also `window.Audio` doesn't exist either. In this case, the code block never runs and `SoundManager#usingWebAudio` continues to be true.

Later when you call `pauseAll()`, an error is thrown on this line:

https://github.com/photonstorm/phaser/blob/dev/src/sound/SoundManager.js#L589

An error is thrown because there is no gain node even though `usingWebAudio` is true. Doesn't seem like this class handles the case of no audio being supported at all (this case can happen in embedded browser scenarios, like CEF implementations).

**Comment by photonstorm** [comment]
This should now be fixed in dev (along with a load of related things). Please give it a test as I don't have a device here without a sound card.

**Comment by englercj** [comment]
:+1: Good to go with the latest `dev` branch. Thanks!
