### ISSUE TITLE
Reusing tween with array properties

### ISSUE THREAD

**Issue by SBCGames** [photonstorm/phaser#1747]
When reusing tween with array properties, these properties are changed (prolonged) with every new call to start().

 If I have tween like this (with target at postion x = 100, y = 150):
tween.to({ x: [500, 500, 100, 100], y: [250, 150, 150, 250] }, 3000, Phaser.Easing.Linear.None);
 If property is array then inside loadValues() in Tweendata.js the array is adjusted to have start position at array position 0, so vEnd["x"] is changed from [500, 500, 100, 100] to [100, 500, 500, 100, 100]. First run is OK.

 When I want to reuse this tween and call tween.start() again, then whole process is repeated, but tween properties are changed again. So, vEnd["x"] becames: [100, 100, 500, 500, 100, 100] as the start position was added on array index 0 again. With every next run you get property array prolonged with start value in the beginning.

 This is minimal example: target sprite is running in rectangle and when Enter is pressed it starts again. As start value is repeatedly added to properties there is longer and longer delay in the beginning:

var spr: Phaser.Sprite = this.add.sprite(100, 250, "ball");

var tween: Phaser.Tween = this.add.tween(spr);
tween.to({ x: [500, 500, 100, 100], y: [250, 150, 150, 250] }, 3000, Phaser.Easing.Linear.None);

tween.start();

this.input.keyboard.addCallbacks(this, null, null, function (aChar: string, aEvent: KeyboardEvent) {
                if (aEvent.charCode === Phaser.Keyboard.ENTER) {
                    if (!tween.isRunning) {
                        spr.position.setTo(100, 250);
                        tween.start();
                    }
                }
});

**Comment by photonstorm** [comment]
Thanks for the clear report - this is now fixed in dev.
