### ISSUE TITLE
Destroying Button dispatch Error

### ISSUE THREAD

**Issue by alamboley** [photonstorm/phaser#1748]
Hey, I'm using Phaser 2.3.0 and I still have a bug concerning destroying a button after ckicking on it. I'm aware of this [forum post](http://www.html5gamedevs.com/topic/9887-destroying-buttons-best-practices/).

```haxe
btn = add.button(0, 0, 'general', _validated, this, 'ValiderOver.png', 'Valider.png', 'ValiderActif.png', 'Valider.png', container);
btn.input.useHandCursor = true;

function _validated() {
     btn.destroy(); => Uncaught TypeError: Cannot read property 'getFrameByName' of null
}
```

An other issue is to use `container.removeAll(true);`. If I don't specify the `true`, no error but I still can see the hand cursor (and I've my callback called). If I specify the `true` arg, I've the same error than previously. The weird thing is it's happening despite I clicked on a button which **is not** in this group!

If I put some `setTimeout`everywhere, no issues.

**Comment by netgfx** [comment]
I noticed this also, maybe it is also related to this post I made: http://www.html5gamedevs.com/topic/13843-events-linger-after-remove-and-destroy/#entry78906

**Comment by georgefrick** [comment]
I am also experiencing this, I've been trying workarounds to get the button off the screen without breaking everything with no luck.

Has anyone had any success with or information about this?

I have tried turning input off first, removing from the world first and even just sending it to the back.

**Comment by photonstorm** [comment]
This is now addressed in the dev branch via the new pendingDestroy property. Here's an example showing use:

```

var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create });

function preload() {

    game.load.spritesheet('button', 'assets/buttons/button_sprite_sheet.png', 193, 71);

}

var button;

function create() {

    game.stage.backgroundColor = '#4b0049';

    button = game.add.button(game.world.centerX - 95, 460, 'button', nukeButton, this, 2, 1, 0);

}

function nukeButton() {

    button.pendingDestroy = true;

    text = game.add.text(game.world.centerX, game.world.centerY, '- button nuked -', { font: '64px Arial', fill: '#ffffff' });

    text.anchor.set(0.5);

}
```
