### ISSUE TITLE
processInteractiveObjects pick up wrong sprite

### ISSUE THREAD

**Issue by nextht** [photonstorm/phaser#1749]
@photonstorm , I found when sprite as parent, its children cannot receive events, Phaser.Pointer.processInteractiveObjects method always pick up parent as targetObject.

I create a online demo http://demo.zuoyouxi.com/core/input/bug.html, in onInputOver he onInputOut events i console.log the target sprite.name, it always print parent.

**Comment by photonstorm** [comment]
You need to set the input priority on the children, otherwise the parent will always get the event as it's more important in terms of the display list: http://phaser.io/examples/v2/input/input-child-priority

**Comment by nextht** [comment]
@photonstorm thanks for your relay, setting children's priorityID does sovle my issue, but i am curious why the children display above don't have higher priority than the parent display below from instinct ?

**Comment by photonstorm** [comment]
It's not about who's on top visually, but about who's on the top of the root display list, and children are second class citizens when it comes to that.

**Comment by nextht** [comment]
Thank you for explanation.
