### ISSUE TITLE
Wrong frame names when loading spritesheet from json

### ISSUE THREAD

**Issue by jpcloud** [photonstorm/phaser#1754]
I had the problem, that all the frames only have numbers as their names after loading an animation from spritesheet like this:

json data:
{"frames": [

{
	"filename": "idle__000.png",
	"frame": {"x":0,"y":0,"w":192,"h":205},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":192,"h":205},
	"sourceSize": {"w":192,"h":205}
}, 

loading code:
this.game.load.atlasJSONHash('monkey', 'assets/monkey.png', 'assets/monkey.json');

problematic phaser code in the function
    JSONDataHash: function (game, json, cacheKey)

the frames are added with "key" as their name:

newFrame = data.addFrame(new Phaser.Frame(
                i,
                frames[key].frame.x,
                frames[key].frame.y,
                frames[key].frame.w,
                frames[key].frame.h,
                key,
                uuid
            ));

 instead of (what I think would be correct):

newFrame = data.addFrame(new Phaser.Frame(
                i,
                frames[key].frame.x,
                frames[key].frame.y,
                frames[key].frame.w,
                frames[key].frame.h,
                frames[key].filename,
                uuid
            ));

With this fix, the frames are found when building an animation referencing the names from the json file. With the code as is this does not work.

**Comment by photonstorm** [comment]
You are loading with `atlasJSONHash` - yet the example json data you've posted above is not a hash, it's an array.

**Comment by jpcloud** [comment]
Oh.
I'm sorry Rich, please chalk this up to ludum dare time pressure.

**Comment by photonstorm** [comment]
No worries, I see this quite often and am going to make sure that all you need in phaser3 is "load.atlas" and once the json is loaded it works out the format for you!
