### ISSUE TITLE
Sprite key issue

### ISSUE THREAD

**Issue by luckylooke** [photonstorm/phaser#1755]
According to doc key parameter of sprite constructor is: "This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture."

The part: " It can be a string which is a reference to the Cache entry" 

I have cache entry with BitmapData, but Sprite checks only IMAGE type of cache entries.

I think because of checkImageKey here:  else if (typeof key === 'string' && !this.game.cache.checkImageKey(key))
in file loadTexture.js (line 78)

Could you fix it somehow to check also for other posible sprite types? Thanks

**Comment by photonstorm** [comment]
You can pass a BitmapTexture to a Sprite too, so just do that.

**Comment by luckylooke** [comment]
I did. But at least docs should be updated. That only cashed images not all
cache entries.

**Comment by L2L2L** [comment]
You would need to find where they store bitmap data at, and than find the method to retrieve/query them.
