### ISSUE TITLE
about physics.arcade.body.velocity handle.

### ISSUE THREAD

**Issue by uhe1231** [photonstorm/phaser#1757]
![bc06a8f5-48b8-44be-8bd8-e5be46462e55](https://cloud.githubusercontent.com/assets/2688145/7218696/2886f494-e6af-11e4-8301-73e890aed7d4.png)

i look for body.velocity handle (physics/arcade/Body.js 435 line) in `this.stage.preUpdate();` function

    this.newVelocity.set(this.velocity.x * this.game.time.physicsElapsed, this.velocity.y * this.game.time.physicsElapsed);

    this.position.x += this.newVelocity.x;
    this.position.y += this.newVelocity.y;

but `processTileSeparationY` function is change `body.velocity`(physics/arcade/TilemapCollision.js 373 line) in `this.state.update()` function

    if (y < 0)
    {
        body.blocked.up = true;
    }
    else if (y > 0)
    {
        body.blocked.down = true;
    }

    body.position.y -= y;

    if (body.bounce.y === 0)
    {
        body.velocity.y = 0;
    }
    else
    {
        body.velocity.y = -body.velocity.y * body.bounce.y;
    }

why? i not found `body.velocity` handle after `this.state.update();`

**Comment by uhe1231** [comment]
i earnest debug code. i think i know it how to work,

i think the `processTileSeparationY` function change `body.velocity` is for next frame. is in updateMotion (physics/arcade/World.js 238 line)

**Comment by photonstorm** [comment]
It's not for the *next* frame, but for the Body.postUpdate function. So at the start of the frame (stage.preUpdate) the physics body is reset, aligned with the sprite and motion applied (computeVelocity). Then in your update function you can collide the sprite, change velocity, all kinds of things which will alter the velocity and / or position of the body. Then in Body.postUpdate (which is called AFTER state.update) all of these changes are applied to the Sprite position itself ready for rendering. After rendering it all starts over again.
