### ISSUE TITLE
Antialias resets to true if you regain focus after losing.

### ISSUE THREAD

**Issue by adamk33n3r** [photonstorm/phaser#1758]
I am passing false for the antialias parameter in Game. If you leave focus of the game and then come back it starts smoothing the sprites. If you run `Phaser.Canvas.getSmoothingEnabled` it will then return true. Am I supposed to be checking `getSmoothingEnabled` and calling `setSmoothingEnabled` in the update loop or is this a bug?

**Comment by photonstorm** [comment]
I can't replicate this at all, please provide a sample. Here is the test case I used to check this against the dev branch:

```

var transparent = false;
var antialias = false;

var game = new Phaser.Game(800, 600, Phaser.AUTO, 'phaser-example', this, transparent, antialias);

function preload() {

    game.load.image('girl', 'assets/pics/manga-girl.png');

}

function create() {

    game.stage.backgroundColor = '#0076a3';

    var sprite = game.add.sprite(32, -100, 'girl');
    sprite.scale.set(4);

}

function render () {

    game.debug.text("Anti-alias: " + game.antialias, 10, 32);

}
```

**Comment by hilts-vaughan** [comment]
Isn't that the wrong flag to test? Shouldn't it be getSmoothingEnabled?

**Comment by photonstorm** [comment]
I don't believe so, no - he said he was using the antialias parameter. `getSmoothingEnabled` will be 'undefined' if you use antialias. `game.renderer.renderSession.smoothProperty` is set correctly to `imageSmoothingEnabled` (on chrome at least). More over though, I cannot make a previously non-aliased game suddenly appear aliased just by swapping to another window and back again, so unless there is a test case that demonstrates the issue exactly I'm not entirely sure there is one.
