### ISSUE TITLE
State.math unnecessary

### ISSUE THREAD

**Issue by JeReT** [photonstorm/phaser#1759]
All methods in the Math class are static.
So there is no need to be a reference anywhere (e.g. in the State class).
The math-member is confusing and not usable anyway for anything.

**Comment by photonstorm** [comment]
You're right there isn't a need for a reference any longer (Phaser.Math used to have a bunch of functions in there and was a proper class, but isn't any more) - however it does actually work perfectly, so there's no harm in keeping it either.

```
this.math.snapTo(345, 16)
```

etc.

**Comment by JeReT** [comment]
Okay, maybe this works with javascript.
It doesn't work with TypeScript, though.

**Comment by photonstorm** [comment]
Issue a PR to remove it from the TS defs for State, it will remain in the actual code though.
