### ISSUE TITLE
[Feature Request] Add Math.distanceSq()

### ISSUE THREAD

**Issue by JeReT** [photonstorm/phaser#1761]
There is a method in the Math class called "distance" and one called "distancePow". Don't know the usecase for the latter one.

However, in many cases you just need the squared distance. For example to check whether two circles are overlapping or not.
To use a distanceSq() method is faster than the distance() method because no sqrt is needed.

**Comment by photonstorm** [comment]
Pull Request? (if you do, do it against dev branch, not master)

**Comment by jeremyosborne** [comment]
Picked a simple one to see if what I did works for your workflow.

**Comment by photonstorm** [comment]
This is now merged in the dev branch.
