### ISSUE TITLE
inconsistent mouse behavior across browsers

### ISSUE THREAD

**Issue by jpcloud** [photonstorm/phaser#1764]
My plan is to recognize right & left clicks on the screen by polling.

First try:
    this.game.input.mouse.isDown
This doesn't work in IE 11 at all.

Next try:
    this.game.input.activePointer.isDown
This works accross IE, Chrome & Firefox.

Now for the buttons:
    this.game.input.activePointer.button
Chrome: works
IE: Works until you move the mouse (button is still pressed, but variable jumps back to -1)
Firefox: works for left button, but completely inconsistently for right button (variable switched to 0 after a few frames, which means left button!)

So I have tried:
    this.game.input.mouse.button
Chrome: works
IE: Doesn't work at all
Firefox: works

Am I missing something?
I think Phaser should (aim to) make this behave equal for all major browsers.

**Comment by jpcloud** [comment]
For now this is my fix:

        var is_firefox = navigator.userAgent.toLowerCase().indexOf('firefox') > -1;

        if (is_firefox) {
            button = this.game.input.mouse.button;
        } else {
            button = this.game.input.activePointer.button;
        }

        if (this.game.input.activePointer.isDown && button == 2) {
                   //do right click stuff
        }

        if (this.game.input.activePointer.isDown && button == 0) {
                   //do left click stuff
        }

**Comment by photonstorm** [comment]
This is now handled properly in dev branch via the new Pointer properties `leftButton` etc.
