### ISSUE TITLE
Phaser.Text: stroke and shadow

### ISSUE THREAD

**Issue by qdrj** [photonstorm/phaser#1766]
Shadow to stroked text applied twice: to text itself and then to stroke.
![clipboard-2](https://cloud.githubusercontent.com/assets/190223/7345780/d2ae7e42-ece0-11e4-8fc6-abc4c9e8c355.png)
When expected behavior (at least for me) should look like this - 
![clipboard-1](https://cloud.githubusercontent.com/assets/190223/7345751/8c76efc2-ece0-11e4-97d8-b1156fbbb319.png)
 (I've prepared this image in graphics editor)

Please take a look at this snippet - http://phaser.io/sandbox/oLIyaQXj

**Comment by photonstorm** [comment]
Thanks for the sandbox example. Personally I really like what it does now :) But I can see why it is unexpected. It's a side-effect from Pixi, but I'll see if we can at least make it a Text shadow option.

**Comment by qdrj** [comment]
Yes, in some cases it gives interesting and nice looking effect. But in most cases I just want to get #2 image.

**Comment by photonstorm** [comment]
Ok this is now possible via 2 new parameters to setShadow.
