### ISSUE TITLE
[Andriod][Stock browser] Sound restarts when calling resume function

### ISSUE THREAD

**Issue by Krummelz** [photonstorm/phaser#1767]
Create a sound object with a piece of music (loading both mp3 and ogg files).
Call the play function.
Tap a button which calls the pause function on the sound object.
Call the resume function for it to carry on from where it left off. 

In the stock Android browser, the audio restarts from the beginning. 
Latest Chrome works as expected; audio resumes playing from where it was paused.

Tested on Android 4.4.4 and 4.1.2

**Comment by photonstorm** [comment]
Pretty sure this is now fixed as part of the fix we applied for #1796

**Comment by photonstorm** [comment]
Closed due to inaction / suspected already fixed.
