### ISSUE TITLE
Missing attributes width and height in phaser.d.ts

### ISSUE THREAD

**Issue by yahiko00** [photonstorm/phaser#1768]
It seems that for classes `Image` and `Sprite` (at least), attributes `width` and `height` are missing in *phaser.d.ts* altough they are mentionned in the documentation and in the JavaScript file phaser.js.

Is it a bug or a feature?

**Comment by clark-stevenson** [comment]
Many of these classes extend PIXI.DisplayObjectContainer in some way and so inherit the width and height of that class.  Phaser.Image extends Pixi.Sprite which extends Pixi.DisplayObjectContainer.  

Is this a problem? I mean, maybe you should always re-list all of the properties inherited but I never have.

**Comment by yahiko00** [comment]
False alert. I just forgotten to retrieve all *.d.ts* files.
