### ISSUE TITLE
Examples on https://phaser.io vs. http://phaser.io 

### ISSUE THREAD

**Issue by jeremyosborne** [photonstorm/phaser#1769]
I don't know if this is the right place to report phaser.io "bugs," but this seemed like a good enough spot.

I recently have been rubber duck coding with phaser to try it out. I love it. I was confused about the 2.3.0 examples on the phaser.io website. It seemed only some of them work, sometimes.

I think what's going on is that whenever I've gone to the plain phaser.io website, I'm getting there over HTTPS, which is fine. But I'm doing it over Chrome, and Chrome seems to be blocking assets which are loaded (apparently?) over HTTP.

Example, the following shows the plain html page, but the embedded example doesn't load:

https://phaser.io/examples/v2/virtualjoystick/buttons

With an error in the console:

> Mixed Content: The page at 'https://phaser.io/examples/v2/virtualjoystick/buttons' was loaded over HTTPS, but requested an insecure resource 'http://examples.phaser.io/embed.php?f=virtualjoystick/buttons.js&v=2.3.1.virtual-joystick'. This request has been blocked; the content must be served over HTTPS.

Whereas the following is fine:

http://phaser.io/examples/v2/virtualjoystick/buttons

The fix seems to be:

* redirect links to examples back to regular http
* move examples.phaser.io to https

Thank you for the great library. I'm having lots of fun with it.

**Comment by jeremyosborne** [comment]
I should have made clear: the examples _are great_ and work just fine. This seems to be merely a browser security thing.

**Comment by photonstorm** [comment]
https://twitter.com/TooOldTooCold/status/592681042923880450

**Comment by jeremyosborne** [comment]
That explains the "how" I got the HTTPS sites: I googled my way there. I had forgotten they were now preferring that in the results. Thanks.

**Comment by photonstorm** [comment]
Yeah, thanks Google. I'll try my best to fix it this week, but we're snowed under with client work at the moment.

**Comment by tobireif** [comment]
When someone googles "phaser", then goes from https://phaser.io/ to https://phaser.io/examples , the examples currently don't work.

Perhaps you could, as a (potentially quick) temporary measure, redirect the incoming https URLs to the existing and valid http URLs?

(Until the real fix, which might be going https for all URLs).

**Comment by tobireif** [comment]
(Just a small note, perhaps it's helpful:)

Perhaps it would be an option to have a bit of JS which, when the page URL starts with "https", changes the iframe src value to also start with "https".

But when I try to load the iframed example page over https I get this:
https://examples.phaser.io/embed.php?f=virtualjoystick/arcade+joystick.js&v=2.3.1.virtual-joystick
"The certificate is only valid for the following names: www.phaser.io, phaser.io, photonstorm.com, www.photonstorm.com "

**Comment by photonstorm** [comment]
This will be fixed shortly when we release the new examples runner.

**Comment by i8ramin** [comment]
I wanted to +1 this as well. Googled phaser examples and landed on the https page. I'm sure this is happening to most people. Wouldn't it be super simple to just replace the iframe src from:

```
http://examples.phaser.io/embed.php?f=tilemaps/csv+map+with+p2.js
```

to

```
//examples.phaser.io/embed.php?f=tilemaps/csv+map+with+p2.js
```

**Comment by photonstorm** [comment]
No because the examples domain doesn't have SSL on it.

**Comment by i8ramin** [comment]
gotcha. well, hope it's fixed soon. I imagine it could potentially be hurting the popularity of the framework. it's one of the best/easiest ones I've found so far. Thanks and good luck.

**Comment by photonstorm** [comment]
Actually it's gone on long enough, so I've just thrown up a quick fix for it until the Examples area is redone properly to not rely on the sub-domain any more. Should work fine now from ssl or not.

**Comment by i8ramin** [comment]
:+1: :+1: :+1:
