### ISSUE TITLE
Method Loader.pack() do not load audio sprites

### ISSUE THREAD

**Issue by boniatillo-com** [photonstorm/phaser#1776]
The method `Loader.pack()` do not load the audio sprites of the asset pack.

I found the problem, in this [line](https://github.com/photonstorm/phaser/blob/dev/src/loader/Loader.js#L1778) it calls the method `Loader.audio` but instead it should call `Loader.audiosprite`, with the right arguments.

Current code:
```
                case "audiosprite":
                    this.audio(file.key, file.urls, file.jsonURL);
                    break;
```

Fixed code:

```
                case "audiosprite":
                    this.audiosprite(file.key, file.urls, file.jsonURL, file.jsonData, file.autoDecode);
                    break;
```

**Comment by photonstorm** [comment]
Closing as it's fixed in your PR.
