### ISSUE TITLE
anchor on graphics object undefined

### ISSUE THREAD

**Issue by ErikAtMapache** [photonstorm/phaser#1787]
Release 2.3.0
I created a sprite group
I created a graphics object (health bar) and added it to the group 
code fails in Phaser.Physics.Arcade.Body#preUpdate 
    can't call "x" on undefined
ran it through th edebugger and found "anchor" is undefined for Graphics object but is for regular sprite
work around is:
        var healthbar = this.add.graphics(0, 10);
        healthbar.beginFill(0xc80000);
        healthbar.drawRect(-50, 0, 100, 10);
        healthbar.anchor = new Phaser.Point(); <------
        healthbar.anchor.setTo(.5, 1);<-------------------
        actor.addChild(healthbar);
This was not a problem in the previous version of Phaser

Hope this helps.
Erik

**Comment by photonstorm** [comment]
A Graphics object has never had an anchor (in any version of Phaser), so this is correct behaviour:

![graphics-anchor](https://cloud.githubusercontent.com/assets/164476/7704716/f11d66d2-fe37-11e4-9f1d-aabe7b6228f5.png)

**Comment by ErikAtMapache** [comment]
...ok
yet it still crashes in the new version where it did not in the old one.

No big deal, just thought I'd let someone know.

**Comment by jacobross85** [comment]
Can this be supported in a newer version? I don't see a reason why this couldn't be applied to graphics.

**Comment by photonstorm** [comment]
Because they don't have a texture. The Pixi anchor is a texture rendering offset (not a registration point / actual anchor), it's a bit of a legacy issue really.

**Comment by smks** [comment]
So this is a definite no? :)

**Comment by photonstorm** [comment]
Afraid so :) Feel free to submit a PR if you can add it in, without breaking everything!

**Comment by iszard** [comment]
I've found that you can play with the pivot of a graphic to gain the same effects as an anchor property would provide.

I have a graphic used as a mask for a sprite. When I change the height I want it to grow not shrink. So I put the pivot on the bottom of the mask (graphic) and move the graphic to the bottom of the sprite in question.

Now when I adjust the mask's (graphics) height (mask.height = .5 * sprite.height) it grows up rather then grows down.
