### ISSUE TITLE
bringToTop() not a method of Phaser.TilemapLayer

### ISSUE THREAD

**Issue by JRogaishio** [photonstorm/phaser#1790]
Branch Master:
Error: Uncaught TypeError: this.world.foregroundLayer.bringToTop is not a function  
  
Code:   
this.foregroundLayer = this.map.createLayer('foregroundLayer');  
this.foregroundLayer.bringToTop();  
  
The layer is being created perfectly fine, however I cannot call bringToTop on it.  
This problem exists on the master branch only. Develop branch works but I hit index issues. Below are the index issues on develop:  
Uncaught TypeError: Cannot read property 'index' of undefined on line 52212

**Comment by photonstorm** [comment]
This is now fixed and working properly in the dev branch.
