### ISSUE TITLE
bringToTop() doesn't work with a sprite's debug

### ISSUE THREAD

**Issue by J4G-** [photonstorm/phaser#1795]
When you enable debug for a sprite, the debug drawing is not brought to the front whenever sprite.bringToTop() is called. Since I've implemented a layering system I'm no longer able to see my sprite bounds or anything like that.

**Comment by photonstorm** [comment]
The P2 BodyDebug is a Phaser.Group linked to the Sprite as the Sprite.body.debugBody property and only updated when the sprites position changes. Any other event that occurs to the sprite (including bringToTop) needs to be handled directly in your own code, as BodyDebug isn't something that should really be used in a production game, so we'd rather not soil the codebase with lots of checks to see if the debug body is there, and if so do x, y and z to it all over the place. I will make this clearer in the docs.
