### ISSUE TITLE
Phaser.Sound.restart() broken in 2.3.0

### ISSUE THREAD

**Issue by eofs** [photonstorm/phaser#1796]
In 2.3.0 `Phaser.Sound.restart()` does not work as excepted. It stops original audio on first call but on second call it plays multiple sounds simultaneously. Same problem in`dev` branch, tested using f78a4cb337ab3b5ae9bd3743ec8d4ed2bfbd6e42.

**Steps to reproduce:**

1. Open http://phaser.io/examples/v2/audio/restart-sound
2. Click on greenie.
3. Audio restarts correctly but audio debug info not updating.
4. Click on greenie again.
5. Hear two sounds playing simultaneously. Audio debug works again.
6. Click on greenie again.
7. Hear three sounds playing simultaneously.
8. etc.

**Workaround:**

Use older 2.2.2 - Alkindar release. You can test it by selecting from "Phaser version" dropdown.

**Comment by Half-Shot** [comment]
Same issue for me by just calling stop and then start. Seems to be creating more contexts without removing or stopping the old ones.

**Comment by photonstorm** [comment]
This is now resolved in dev branch.
