### ISSUE TITLE
Stop render on iOS background WebGL game

### ISSUE THREAD

**Issue by cncolder** [photonstorm/phaser#1800]
[Apple don't allow background app execute commands on graphics](https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/ImplementingaMultitasking-awareOpenGLESApplication/ImplementingaMultitasking-awareOpenGLESApplication.html#//apple_ref/doc/uid/TP40008793-CH5-SW1)

If I build with cordova, run on iPhone5S(8.1.2), then press HOME. App will crash with error .

```
libGPUSupportMercury.dylib`gpus_ReturnNotPermittedKillClient:
    0x18f952180 <+0>:  orr    x8, xzr, #0x1
    0x18f952184 <+4>:  movz   w9, #0xdead, lsl #16
    0x18f952188 <+8>:  movk   w9, #0xbeef
->  0x18f95218c <+12>: str    w9, [x8]
    0x18f952190 <+16>: ret    
```

This issue is only appear on iOS with WebGL. Canvas work fine.

For now, I resolve this issue by set `game.lockRender = true` in cordova pause event.

I think we should prevent any render action in `<internal> game.gamePaused(event)`

**Comment by photonstorm** [comment]
Hmm this is a Cordova specific issue. I'm reluctant to add hacks into the core specific for this case. However it's well worth adding into the docs, so I'll do that now.

**Comment by photonstorm** [comment]
Actually what the heck, it's in there.

**Comment by tony--** [comment]
A note for others that might still be running into this crash with Cordova+Phaser...

The provided fix works, but is not automatically invoked when the app goes to the background.
The app developer needs to add an event listener that pauses the game when the app is sent to the background (and another to unpause it when it returns to the foreground) so that the fix will be invoked to prevent the crash.

Something like:
```
    //pause the game when the app pauses
    function onPause() {
        if(!game.paused) {
            game.gamePaused();
        }
    }
    function onResume() {
        //ios quirk: resume handler needs to be in setTimeout
        setTimeout(function() {
            if(game.paused) {
                game.gameResumed();
            }
        }, 0);
    }
    document.addEventListener('pause', onPause, false);
    document.addEventListener('resume', onResume, false);
```
