### ISSUE TITLE
Colliding With Tiling Sprite doesn't work in 2.3.0

### ISSUE THREAD

**Issue by alexwoll** [photonstorm/phaser#1802]
Seems like the collision with tiling sprites is broken in the latest version. An easy way to see this is via this example http://phaser.io/examples/v2/tile-sprites/colliding-with-tiling-sprite where the ball just passes the tileSprite. It works in 2.2.2.

Is there a workaround or should I stick to the old version in the meantime?

**Comment by photonstorm** [comment]
https://github.com/photonstorm/phaser/issues/1702
