### ISSUE TITLE
TypeScript `fromArray` lacks return-type annotation

### ISSUE THREAD

**Issue by Deathspike** [photonstorm/phaser#1803]
In `class Matrix extends PIXI.Matrix` the `fromArray` function does not have a return type.

Change:

`fromArray(array: number[]);`

To:

`fromArray(array: number[]): any;`

Now compilation with `--noImplicitAny` will be happy.

**Comment by clark-stevenson** [comment]
Are you using an old version of the definition file?

Line 2115:

`fromArray(array: number[]): Phaser.Matrix;`

**Comment by Deathspike** [comment]
I am using the 2.3.0 release, not a dev version.

Seems like you got it. Thanks :+1:
