### ISSUE TITLE
Setting maxWidth on BitmapText throws error

### ISSUE THREAD

**Issue by drhayes** [photonstorm/phaser#1807]
[Here's a link to a minimal test case.](http://cut-downtown.surge.sh/) I'm using Phaser 2.3.0.

Repro:

1. Create a new bitmap text object: `this.text = this.game.add.bitmapText(0, 0, '04b03', 'starting text', 8);`
2. Set the maxWidth: `this.text.maxWidth = 100;`
3. Set new text: `this.text.text = Phaser.RetroFont.TEXT_SET1;` (or otherwise get the BitmapText instance to call `updateText`)
4. No rendered text, error in the console: `Uncaught ReferenceError: lastLineWidth is not defined`

Looks like a PIXI bug. I [saw this](https://github.com/GoodBoyDigital/pixi.js/pull/1370) on their side. Looks like it adjusts [this line of code](https://github.com/GoodBoyDigital/pixi.js/blob/07e4e26f8fd404524a7ebaa73c210de3d8f2cf25/src/extras/BitmapText.js#L275) which Phaser doesn't have, I guess? Anyhoo.

**Comment by drhayes** [comment]
It looks like naively sticking those lines in the `updateText` method doesn't enforce maxWidth. There goes the quick fix for me. :(

**Comment by aendel** [comment]
I have the same problem, but i can't find a solution.... can you explane me better?

**Comment by photonstorm** [comment]
This is now fixed in dev (and then some actually, we completely recoded how Pixi handles maxWidth, which didn't take into account kerning or character widths, or correctly crop the input string).

**Comment by aendel** [comment]
Where can i find the dev or anyway the right way to use it?
Il 03/Giu/2015 17:32, "Richard Davey" <notifications@github.com> ha scritto:

**Comment by photonstorm** [comment]
Just check out the dev branch from github and run grunt to build it.

**Comment by photonstorm** [comment]
Close this one off as it definitely works properly now :) New updated example is in the repo too.
