### ISSUE TITLE
Child sprite texture isn't moved when child sprite is moved.

### ISSUE THREAD

**Issue by samarthwiz** [photonstorm/phaser#1809]
***| i | Applies to dev-branch latest: commit 621e51d949 | i |***
# Description
When a child sprite has its position changed, the texture doesn't move with the sprite; this issue is apparent particularly with buttons, because the button will be clickable in the moved spot, rather than where the texture is.  
# Examples
The following examples illustrate the issue. In both examples white is a regular sprite, while green is the child sprite. In the first example there is a regular sprite, both sprites will be moved in 2 s; in the second example, the green sprite is a button, clicking the button will cause it to be clickable in the moved spot.

http://jsfiddle.net/samarthwiz/q0se2va9/
http://jsfiddle.net/samarthwiz/q0se2va9/2/

**Comment by samarthwiz** [comment]
I've realised this is probably something to do with Pixi's scene graph.

**Comment by photonstorm** [comment]
I can't see anything wrong with the way this works currently, all tests seem fine here:

```

var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create, update: update, render: render });

var parent;
var child;

function preload() {

    game.load.image('mushroom', 'assets/sprites/mushroom2.png');
    game.load.spritesheet('mummy', 'assets/sprites/metalslug_mummy37x45.png', 37, 45, 18);

}

function create() {

    parent = game.add.sprite(100, 100, 'mushroom');

    parent.addChild(game.make.sprite(-50, -50, 'mummy'));
    parent.addChild(game.make.sprite(100, 0, 'mummy'));
    parent.addChild(game.make.sprite(200, 200, 'mummy'));

    //  This child will move faster because its position is updated as well as the parent
    child = parent.addChild(game.make.sprite(0, 100, 'mummy'));

}

function update() {

    parent.x += 0.1;
    child.x += 0.1;

}

function render() {

    game.debug.text(parent.width, 32, 32);
    game.debug.geom(parent.getBounds());

}
```
