### ISSUE TITLE
[IE 11][dev] Loader error: Unable to get property 'substr' of undefined or null reference

### ISSUE THREAD

**Issue by noidexe** [photonstorm/phaser#1813]
I'm getting this error on Internet Explorer 11 for Windows 8.1 when my assets are loading. 

```javascript
 /**
    * Transforms the asset URL.
    * The default implementation prepends the baseURL if the url doesn't being with http or //
    *
    * @method Phaser.Loader#transformUrl
    * @protected
    * @param {string} url - The url to transform
    * @return {string} The transformed url
    */
    transformUrl: function (url) {

        if (url.substr(0, 4) === 'http' || url.substr(0, 2) === '//')
        {
            return url;
        }
        else
        {
            return this.baseURL + url;
```
:x: ERROR: Unable to get property 'substr' of undefined or null reference
```javascript
        }

    },
```
It doesn't happen on any other browser. I'm using phaser-arcadephysics from the dev branch. Evidently url is null or undefined on IE but I don't know why.

**Comment by photonstorm** [comment]
Build it from dev using the grunt script provided and retest. If it still
does it stick a debugger call in the loader source to find out which url is
breaking it.


On Monday, May 25, 2015, Lisandro Lorea <notifications@github.com> wrote:

> I'm getting this error on Internet Explorer 11 for Windows 8.1 when my
> assets are loading.
>
>  /**    * Transforms the asset URL.    * The default implementation prepends the baseURL if the url doesn't being with http or //    *    * @method Phaser.Loader#transformUrl    * @protected    * @param {string} url - The url to transform    * @return {string} The transformed url    */
>     transformUrl: function (url) {
>
>         if (url.substr(0, 4) === 'http' || url.substr(0, 2) === '//')
>         {
>             return url;
>         }
>         else
>         {
>             return this.baseURL + url;
>
> [image: :x:] ERROR: Unable to get property 'substr' of undefined or null
> reference
>
>         }
>
>     },
>
> It doesn't happen on any other browser. I'm using phaser-arcadephysics
> from the dev branch. Evidently url is null or undefined on IE but I don't
> know why.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/1813>.
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by noidexe** [comment]
My bad. I had forgotten to add the mp3 option to one of the audio files. The new build issued a warning showing me the error, instead of crashing.
