### ISSUE TITLE
tile sprite performance 

### ISSUE THREAD

**Issue by Skywalker-gamefu** [photonstorm/phaser#1815]
i made small test for tile sprite performance

1 - i created blank WEBGL game using phaser and tested it on cocoonjs launcher FPS = 60;

2- puting simple tile sprite  " game.add.tileSprit(0,0,gameWidth,gameHeight) " tested it FPS = 30

3- however i tested PIXI tile sprite and the FPS = 60;

so i think you need to work on performance .

**Comment by cscott5288** [comment]
are you sure both were in webgl mode? what was the world width/height?

**Comment by Skywalker-gamefu** [comment]
yes WEBGL  and the world width is 1440 , height 960

**Comment by photonstorm** [comment]
Phaser uses Pixi directly for WebGL rendering of Tiling Sprites, there's no intermediate step, so no "performance" to be worked on. Pixi 3 uses a shader to render tile sprites, Pixi 2 used a canvas generated texture, make sure you're comparing both exactly as is.
