### ISSUE TITLE
TilemapParser - data objects x & y undefined when equal 0

### ISSUE THREAD

**Issue by MaksJS** [photonstorm/phaser#1818]
With a JSON map exported from Tiled, in the Tilemap class when I call this.objects.buildings, x & y properties are undefined whereas they should equal 0 as shown in the JSON below

```json
{
         "color":"#0008a4",
         "height":50,
         "name":"buildings",
         "objects":[
                {
                 "height":512,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":512,
                 "x":0,
                 "y":0
                }, 
                {
                 "height":512,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":512,
                 "x":1536,
                 "y":0
                }
```

Seems like there is a problem with the TilemapParser

**Comment by photonstorm** [comment]
I don't think it's a problem with the parser but it's easy enough for you to confirm - just called TilemapParser.parseTiledJSON() directly and give it the json data of your tilemap. Look at the object that comes back. Are the x/y values set or undefined?

Looking at the snippet of map data above it doesn't look correctly formatted, or an old version of Tiled perhaps? I'm not seeing `gid` properties or anything else you'd usually expect. However only you can tell as you're the one with the full json file - so throw it through the full parser (make sure you test the dev branch to be current) and see what happens.

**Comment by MaksJS** [comment]
My Tiled version is 0.9.1. You're right, I haven't noticed it but it's an old version. I will try to reproduce it with a more recent one.

I've tried to parse data with TilemapParser.parseTiledJSON() and v2.3.0, here's what I get : 

![screenshot](http://img11.hostingpics.net/pics/942057Screenshotfrom20150527160042.png)

As you can see, x and y properties are not in the object when they equal 0. Looks like the parser compact falsy values ? I can give you the full JSON if it can helps.

**Comment by MaksJS** [comment]
Same issue with Tiled v0.12.2 export. I may try with the dev branch

**Comment by photonstorm** [comment]
Yes post the json please.

**Comment by MaksJS** [comment]
The full json here : http://pastebin.com/kCdFAebS

**Comment by photonstorm** [comment]
Thanks for the file. Ok this is now fixed in dev. You'll need to build from grunt to use atm, but we are aiming for official release next week.

**Comment by MaksJS** [comment]
Thanks @photonstorm, keep up the great work :+1:
