### ISSUE TITLE
Sound does not loop after resume in Chrome

### ISSUE THREAD

**Issue by nkovacs** [photonstorm/phaser#1820]
http://jsfiddle.net/nkovacs/dj3sod2v/

Resume calls AudioBufferSourceNode.start with a start offset and a duration. Chrome 42 has a bug (https://code.google.com/p/chromium/issues/detail?id=457099), which means both have to be omitted for the loop to work, but Chrome 43 will fix this, and you only need to omit the duration.

**Comment by photonstorm** [comment]
Thanks for the heads-up, this should now be fixed in dev.
