### ISSUE TITLE
Text not rendered when anchor is set to a text object that has a strokeThickness applied.

### ISSUE THREAD

**Issue by miniversal** [photonstorm/phaser#1821]
When setting the anchor of a text object, you cannot apply a strokeThickness to the text. If you do, the text does not appear.

In the example, I have commented out the line that sets the strokeThickness. When you comment the line in, you will see that the text no longer appears.

```javascript
       var text = this.add.text(this.world.centerX, this.world.centerY, 'START');        
        text.anchor.set(0.5);
        text.inputEnabled = true;
        text.font = 'Impact';
        text.fontSize = 48;
        text.fontWeight = '600';
        text.stroke = '#0066ff';
        text.align = 'center';
        // text.strokeThickness = '5';
        text.fill = '#00ff00';        
        text.events.onInputDown.add(this.startGame, this);
```

**Comment by photonstorm** [comment]
Works fine here in 2.4-dev branch and also here http://phaser.io/examples/v2/text/text-stroke so need more to go on.

**Comment by miniversal** [comment]
Thanks Rich. You are correct. I see my mistake. I was setting strokeThickness = '5' and not strokeThickness = 5. I made that change and it works as expected. Appreciate the help! :)
