### ISSUE TITLE
Phaser.Graphics.drawRoundedRect: radius restrictions

### ISSUE THREAD

**Issue by mpostma** [photonstorm/phaser#1822]
I am running into a strange issue with the drawRoundedRect function (http://phaser.io/docs/PIXI.Graphics.html/Phaser.Graphics.html#drawRoundedRect).

The function works fine with a radius from 0 to 9, but as soon as you give it a radius of 10 or more it crashes if the game is running in WebGL (Canvas is working fine with any radius). Some sample code to reproduce:

```
var button = this.game.add.graphics(100, 100);
button.beginFill(0xAAAAAA, 1);
button.drawRoundedRect(0, 0, 50, 50, 10);
```

The problem is that `var triangles = PIXI.PolyK.Triangulate(recPoints);` inside of PIXI.WebGLGraphics.buildRoundedRectangle returns null, so everything fails as soon as the next loop tries to access `triangles.length`. The only hint PIXI is giving is `window.console.log("PIXI Warning: shape too complex to fill");`, which seems like an odd error for such a simple shape...

I am unclear exactly how the information is passed/translated from Phaser to PIXI, so I am not sure where the issue is (Phaser or PIXI). But, even if it's a PIXI issue, it might be worth mentioning this radius limitation in the Phaser docs (until PIXI fixes it).

**Comment by photonstorm** [comment]
Definitely a strange one - this may well be fixed in Pixi 3 as they no longer use the PolyK library (what do you reckon @englercj ?) but I will update the Phaser docs in the meantime.

**Comment by englercj** [comment]
Yeah not an issue in v3, earcut is much more tolerant of things like this. Doing rounded rects you end up getting some artifacts if your radius is the same or higher than half your width/height, but it definitely doesn't crash.

You can try it on the v3 Graphics example, try changing the rounded rect values and clicking the refresh icon:

http://pixijs.github.io/examples/index.html?s=basics&f=graphics.js&title=Graphics

**Comment by photonstorm** [comment]
Thought so, I've added it to the docs and will close this one off.

**Comment by isoscorp** [comment]
Hi,

I am still using Phaser 2.3.0 and I am not sure that the radius restrictions works in all cases.
For example drawRoundedRect(0, 0, 125, 125, 4) won't work and it seems linked to the height only.

I personnally always set the radius to 20 and have no problem, but as the radius has to be inferior to Math.min(width,height)/2-1, some combinations of width / height can be problematic for small rectangles.

Hope this will help.
