### ISSUE TITLE
Utils.pad() the argument `pad` type should be string.

### ISSUE THREAD

**Issue by muzuiget** [photonstorm/phaser#1823]
In http://phaser.io/docs/2.3.0/Phaser.Utils.html#pad

```
pad     number    The string to pad it out with (defaults to a space).
```

The description says it is a string, but type says it is a number.

and the typescript file https://github.com/photonstorm/phaser/blob/master/typescript/phaser.d.ts#L4740 should be fix too.

**Comment by photonstorm** [comment]
Thanks, both fixed.
