### ISSUE TITLE
Text alignment doesn't work on single lines

### ISSUE THREAD

**Issue by boostermedia** [photonstorm/phaser#1824]
Text alignment relies on having multiple lines of text, whether it's from the input text or by having a long line and a word wrap width. We have an internal tweak for this, but it relies on our internal toolchain sending through the bounding box width to the wordWrapWidth irrespective of whether the text will be wrapped or not. See here:
https://github.com/boostermedia/phaser/commit/c38cd2fc3ba4a7b8ce95eebbec30181e62f93951
This probably wouldn't be suitable as a general fix, but maybe something based on this?

Thanks,
David Goemans

**Comment by photonstorm** [comment]
Text alignment is within the bounds of the texture itself. If it wasn't what would it actually align to? The screen? The world? It's parent container? So many options, none any more correct than each other.

**Comment by boostermedia** [comment]
Indeed, that's also why our internal solution isn't a good general fix. What we do is always define a bounding box in a UI editor, and the alignment is always relative to that, irrespective of whether it's multiline text or not. Phaser, for the most part, supports this by setting the wordWrapWidth, but then the bounding box width is based on the longest line in the text. 

What I think might work, is adding a bounding size to the text, potentially overriding the wordWrapWidth, which will allow for single line and multiline alignment within a box of this width. I also understand if you feel this is not the best idea... having worked on a text implementation in a previous engine, I understand that this adds complexity to the usability. The main reason I feel this is a good feature is the moment you plug text implementations into some form of UI editor and localization systems, you often feel the need for some bounding box definition independent of the initial/visible text sizes.

**Comment by photonstorm** [comment]
That's a much nicer idea (defining the bounds for the Text object itself), as this could map to the underlying canvas dimensions. Then if you specify a wordwrap too long or whatever it's entirely your own problem really :)

**Comment by photonstorm** [comment]
Ok this is all done and in the dev branch. Am quite happy with how it turned out actually!

**Comment by boostermedia** [comment]
Awesome! Looking forward to it!

On Tue, Jul 7, 2015 at 4:17 PM, Richard Davey <notifications@github.com>
wrote:

> Ok this is all done and in the dev branch. Am quite happy with how it
> turned out actually!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/1824#issuecomment-119218741>
> .
>



-- 


*E*:david.goemans@boostermedia.com
*Skype:* booster_dgoemans
