### ISSUE TITLE
Group.bringToTop() has incorrect typescript signature

### ISSUE THREAD

**Issue by sanchopancho13** [photonstorm/phaser#1829]
The Group "bringToTop" method is missing the "child" parameter in the typescript declaration file.  It is declared in the jsdoc comment, however not in the method signature.

**Comment by photonstorm** [comment]
https://github.com/photonstorm/phaser/blob/dev/typescript/phaser.d.ts#L1504

**Comment by tenchugecko** [comment]
2017: bringottop,moveup and movedown still wrong in TS Def, and link is dead.

**Comment by photonstorm** [comment]
The link is 2 years old, things move. More importantly though the defs are correct:

https://github.com/photonstorm/phaser/blob/master/v2/typescript/phaser.d.ts#L1807-L1808
