### ISSUE TITLE
More complex camera follow

### ISSUE THREAD

**Issue by noidexe** [photonstorm/phaser#1830]
Right now you can choose between lock-on mode and differently sized deadzones. The problem with deadzones for platformer games is that since the character pushes against the deadzone, you see more of what's behind her than what's in front of her.  

Itay Keren did a nice analysis of how different games implemented different camera modes and while some are very elaborate and game-specific, others a not too hard to implement and very useful for a big number of games. 

Among the camera features he describes I think "platform-snapping" and "dual-forward-focus" could be very useful for action platformers. 

Article: https://docs.google.com/document/d/1iNSQIyNpVGHeak6isbP6AHdHD50gs8MNXF1GCf08efg/pub?embedded=true
GDC Talk: http://gdcvault.com/play/1022243/Scroll-Back-The-Theory-and

**Comment by photonstorm** [comment]
In order to keep the Github issues clear this feature request has been moved to the [Phaser 3 wishlist](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread/).
