### ISSUE TITLE
getObjectIndex expects an array but is passed an object instead

### ISSUE THREAD

**Issue by sseligma** [photonstorm/phaser#1834]
In Tilemap.js line 710, getObjectIndex is calling this.getIndex(this.objects, name) . The getIndex function expects this.objects to be an array, but in my testing reading from a tilemap.json file, this.objects is an object where each property is an object layer containing an array of objects.

**Comment by photonstorm** [comment]
The TilemapParser extracts each object from the Tiled json and inserts it into an array:

`objects[json.layers[i].name] = [];` (line 439)

`getObjectIndex` searches that local array for the object, not the original json data itself.

Unless you've got a json file that breaks this approach?

**Comment by sseligma** [comment]
I've attached my JSON tilemap created in the Tiled tilemap editor. I also
added  a debug statement to getObjectIndex:

console.log(JSON.stringify(this.objects));

The output is an object, not an array:

{"objectLayer":[{"gid":84,"name":"player","type":"player","x":16,"y":32,"visible":true,"properties":{}}]}

**Comment by photonstorm** [comment]
Your file wasn't attached. I need to see a working example of this please - a minimal test case that shows the json file and the issue, because as it stands I can't reproduce it. Either re-open with a test case or open a new issue, I don't mind which.
