### ISSUE TITLE
Colliding with TilingSprite not working in v2.3.0

### ISSUE THREAD

**Issue by jackycute** [photonstorm/phaser#1835]
As I saw below, it doesn't work anymore.
http://phaser.io/examples/v2/tile-sprites/colliding-with-tiling-sprite

But if you switch it to v2.2.2, it works like a charm

**Comment by photonstorm** [comment]
https://github.com/photonstorm/phaser/issues/1802 https://github.com/photonstorm/phaser/issues/1702
