### ISSUE TITLE
The game is inactive when the window is inactive.

### ISSUE THREAD

**Issue by youssefdetovernickr** [photonstorm/phaser#1843]
This isn't really an issue, pretty good that it does this but there's only one issue with it.. If you split your screen for 2 browsers to test your game, and you want to send over information to the other and want to see it happen (simulating clients on a server), you can't do this as that window is frozen until you actually click on the window to make it active again, however this makes the other browser inactive again..

Is there a possibility to temporary hide this, or some type of debug mode to disable that freezing?

**Comment by photonstorm** [comment]
`game.stage.disableVisibilityChange = false`
