### ISSUE TITLE
Lines on WebGL are offsetted a few pixels to the right/bottom

### ISSUE THREAD

**Issue by youssefdetovernickr** [photonstorm/phaser#1844]
Basically, I got a few "island" made out of the lineTo functions, using lineStyle I have a stroke. When I'm using a canvas it basically outputs what I like: a line that's centered to the points (no offset). However using WebGL I notice that the line is actually offsetted a few pixels to the right. I'm using a scale so it's really easy to spot this.

**Comment by photonstorm** [comment]
Could be anything, sorry - a rounding issue, WebGL issue, the way Pixi handles lines, etc - really need a simple / clear piece of code that demonstrates it (feel free to re-open with that added, or just open a new issue)
