### ISSUE TITLE
Newsletter missing

### ISSUE THREAD

**Issue by luckylooke** [photonstorm/phaser#1846]
Did you stop producing newsletters? Because I didnt get any for long time and even the webpage part with newsletter is not working [http://phaser.io/community/newsletter](http://phaser.io/community/newsletter)

:/

**Comment by photonstorm** [comment]
Yes we've simply been too busy for this or the Coding Tips one either.

I need to consolidate them into one I think, and see if we can't automate some of the content (i.e. pull in latest news from our news feed). They just take up too much time to produce right now.

**Comment by luckylooke** [comment]
Ok
And getting latest news into email would be nice ;)

**Comment by photonstorm** [comment]
Going to close this off as I want repo issues to focus on the library itself really. But rest assured, we'll sort something out in this area soon.
