### ISSUE TITLE
small issue with Phaser.Physics.P2.Body.prototype.destroy

### ISSUE THREAD

**Issue by Weedshaker** [photonstorm/phaser#1850]
Hi,

### Error occurs when calling destroy (game.state.restart())

Some sprites are already null, when calling the destroy function (this.sprite.body = null;). This is the case creating P2 Bodies through the Plugin englercj/phaser-tiled (game.physics.p2.convertTiledCollisionObjects). I first thought the fix may apply to this Plugin, but the fix would be much faster checking the sprite before setting its body to null.

```javascript
// Phaser fix 20150612 / tiled P2.Bodies were null and failed this line [this.sprite.body = null;]
/**
* Destroys this Body and all references it holds to other objects.
*
* @method Phaser.Physics.P2.Body#destroy
*/
Phaser.Physics.P2.Body.prototype.destroy = function () {
    this.removeFromWorld();
    this.clearShapes();
    this._bodyCallbacks = {};
    this._bodyCallbackContext = {};
    this._groupCallbacks = {};
    this._groupCallbackContext = {};
    if (this.debugBody)
    {
        this.debugBody.destroy(true, true);
    }
    this.debugBody = null;
    if(this.sprite){
    	this.sprite.body = null;
    }
    this.sprite = null;
}
```

Thank you! PHASER is fantastic!
Cheers
Silvan

**Comment by photonstorm** [comment]
Thanks for the heads-up but this is already fixed in the dev branch.
