### ISSUE TITLE
Camera view resizing problems

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#1852]
Right now the camera view resizes automatically (i think) when the user changes the window width by dragging the window to a different dimension. But it doesn't auto-size in the following scenarios:
 
* If the browser developer tools is open on page load, the view isn't resized when dev tool is closed
* If a dialog box from the browser, such as the downloads notification area in Chrome, is there on page load and is closed
* when the user zooms out (CTRL +/- in windows)
 
Is there anyway to get resizing in the above scenarios? It's quit a pain to have to reload the browser to get the full camera view in the above scenarios.

**Comment by photonstorm** [comment]
A `window.resize` event has to occur in order for the Camera (or World) size to update like that. It's entirely possible (although worth testing) that this doesn't happen with dialog boxes and the such like, as the window itself didn't technically change size. If using a RESIZE scale mode then you should be able to tell if the State resize function gets called or not in those cases, and if not then that's the reason. If it does get called, then it needs looking in to further, so a code test case will be required.
