### ISSUE TITLE
Improve WebGL on Chrome

### ISSUE THREAD

**Issue by alitavector** [photonstorm/phaser#1855]
When compare IE11 that has been improving WebGL significantly in performance, all that meddling flags in Chrome don't improve at all. I guess it's the OpenGL context switching issue or more optimization can be done on Phaser?

Test: www.phaser.io/examples/v2/demoscene/atari-intro

On Windows 8.1 64-bits
IE11: ~7% cpu
Latest Chrome: ~14% cpu

On Google Chrome - chrome://gpu
Graphics Feature Status
Canvas: Hardware accelerated
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Rasterization: Hardware accelerated
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
WebGL: Hardware accelerated

**Comment by photonstorm** [comment]
Phaser uses Pixi for all WebGL rendering - if you think you've found a specific case where Pixi isn't being properly set for IE11 rendering then please report it in their repo, and if they agree and address it we'll consider merging the change back into Phaser.
