### ISSUE TITLE
Phaser examples should have 3 options

### ISSUE THREAD

**Issue by proyb2** [photonstorm/phaser#1858]
PHASER.AUTO <-- IE11 better than Chrome
PHASER.CANVAS
PHASER.WEBGL

On IE11 with demo that use PHASER.AUTO setting, the example may be render in CANVAS that gives better performance over Goolge Chrome. On other examples in PixieJS, Google WebGL experiment that use WebGL shown both IE11 and Chrome able to achieve the same CPU usage. This will misled any newcomers with the wrong impression.

I suggest the examples could include 3 buttons AUTO, CANVAS, WEBGL for demo.

**Comment by photonstorm** [comment]
There are lots of examples that only work in WebGL mode, or only work in Canvas mode - there are equally a large number that include debug text output, which in WebGL mode really slows things down but should never be used in a live game anyway. So in short, I'm going to keep them as-is, most of them have the optimum setting for what they're trying to show. None should be taken "wholesale" as the only want to do something. Yes it's possible in some of the examples that IE11 will outperform (or under perform) against another browser, but it's just an example - they're meant for taking, tweaking and learning from, not dumping directly into a game.
