### ISSUE TITLE
Line properties can not be tweened on WebGL.

### ISSUE THREAD

**Issue by rbozan** [photonstorm/phaser#1859]
Altering the lineAlpha and lineWidth on the 'graphicsData' object via tween does not do anything on WebGL, while on canvas it just works perfectly.. Just try it yourself... I can see that the property changes, but not that the line actually changes alpha / width.
I guess WebGL just uses the global lineAlpha and lineWidth instead of per line basis, as altering the global line alpha works..

**Comment by photonstorm** [comment]
This is unsupported. Modifying properties directly doesn't inform the parent object that it's now dirty and needs re-rendering, so breaks.
