### ISSUE TITLE
Sprite animation bug

### ISSUE THREAD

**Issue by trpzn** [photonstorm/phaser#1861]
All my sprite animations loop get stuck in the final sprite and jump first
example:
[1,2,3,4,5]
animation do
1,2,3,4,5,5,2,3,4,5,5,2,3,4,5,5,2,3,4,5...

working in phaser 2.3.0
bugged in phaser 2.4 dev

animation code:
this.ship = this.gamePlay.add.sprite(this.positions.ship.x, this.positions.ship.y, 'boardSprites',5);
this.ship.animations.add('normal',[5,11,17,23,29,35],1,true);
this.ship.play('normal',1,true);

**Comment by photonstorm** [comment]
Could you post an actual example please, because I can't replicate this with the animations found in the examples repo.

**Comment by photonstorm** [comment]
I still can't replicate this. Here is an example I tested, the log for me perfectly shows 1,2,3,4,5,1,2,3,4,5 etc without dropping any frames. I always see frame 1 in the list, it doesn't skip it.

```

var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create });

function preload() {

    //  37x45 is the size of each frame

    //  There are 18 frames in the PNG - you can leave this value blank if the frames fill up the entire PNG, but in this case there are some
    //  blank frames at the end, so we tell the loader how many to load

    game.load.spritesheet('mummy', 'assets/sprites/metalslug_mummy37x45.png', 37, 45, 18);
}

function create() {

    var mummy = game.add.sprite(300, 200, 'mummy');

    //  Here we add a new animation called 'walk'
    //  Because we didn't give any other parameters it's going to make an animation from all available frames in the 'mummy' sprite sheet
    var walk = mummy.animations.add('walk', [1,2,3,4,5]);

    walk.enableUpdate = true;
    walk.onUpdate.add(onUpdate, this);

    //  And this starts the animation playing by using its key ("walk")
    //  30 is the frame rate (30fps)
    //  true means it will loop when it finishes
    mummy.animations.play('walk', 10, true);

}

function onUpdate(anim, frame) {

    console.log(frame.index);

}
```

You'll find the assets required for this code in the examples repo. Feel free to re-open this if you have a test case that proves otherwise, or highlights an issue elsewhere.
