### ISSUE TITLE
Lines on WebGL are offsetted a few pixels to the right/bottom

### ISSUE THREAD

**Issue by rbozan** [photonstorm/phaser#1863]
Here's a gif to show you what I mean ->

WebGL: 
http://gyazo.com/012ebdae2e6ff49a7526f186380fe08e

Canvas:
http://gyazo.com/85e2f6fb5577d44d074d162a0c55ef2e

Notice how on WebGL the strokes are offsetted, which makes borders appear offsetted too and just strokes also offsetted (it doesn't follow the tip of the cursor) while on canvas everything works fine, and to prove it's not about the actual cursor I rendered a fake cursor that's tweened, notice how the strokes just don't follow the actual positioning on WebGL.. Also the boxes with the borders, which works properly on canvas but offsetted again on WebGL...

**Comment by youssefdetovernickr** [comment]
It seems this only happens when you are using scales! If you don't use scales it's not offsetted.. How more you scale, how more offsetted it looks

**Comment by photonstorm** [comment]
Scaling on what? The canvas or the Graphics object? If you could post a code sample that would be very handy, although I suspect this is still a Pixi level WebGL bug.

**Comment by rbozan** [comment]
@photonstorm Sorry for the awfully late response... With scales I mean this:

game.scale.scaleMode = Phaser.ScaleManager.RESIZE;

I don't really have a lot of time, but I could try to reproduce it soon.. It still happens on the newest version.

**Comment by rbozan** [comment]
@photonstorm Made a fast CodePen with the bug happening. I guess that it happens when the line pixels is under 2:

http://codepen.io/anon/pen/OyXQPp

**Comment by rbozan** [comment]
I will recreate this issue as I think the main post isn't relevant to the actual error.
