### ISSUE TITLE
Context free tutorials.

### ISSUE THREAD

**Issue by lighterletter** [photonstorm/phaser#1868]
So I had a high level concept of what I wanted to do with phaser but going through the tutorial I found it difficult to follow that. I think it would be useful to also have tutorials that break down components by usability.

**Comment by lighterletter** [comment]
I just want to elaborate. I also mean a more in-depth tutorial. Since following the one on the site tended to lean towards brevity and quick prototyping.

**Comment by Clever-Coding** [comment]
I'm working on that :). The first video will come out soon (a few days after 2.4 release)

YouTube channel : https://www.youtube.com/cleverlycoding 

There's already a video on it, but it's really bad and old, I don't recommend watching it unless you have really nothing to do :)

**Comment by lighterletter** [comment]
Great! Thank you. Some feedback on my part is that at the moment I'm having to learn by trial and error, looking through the docs and kind of trying different things to see what works for what I'd like to build. What I think would make a huge difference in terms of streamlining understanding for others is breaking down the development sequence into different high level concept components based on system context such as: 

Environment set up (I understand there are different ways to do this), 
Adding image properties, 
Working with Input 
and using the different physics components. 

Then moving down the logic tree into the more specific core of things. Keeping things brief and conceptually concise based on how they work, focused on a context free specified subject would do wonders in terms of how people understand how to work with the library and how to find specific information in how to accomplish what they're trying to do. 


By 'context free specified subject' I mean that the examples currently on the site are usually around doing something really specific but somehow still lack info on how it's done and barely touch on how some of the core elements work with each other, (what would break them etc.). 

I think elaborating on that would help other developers understand how to use the library to their own customized needs. 

If you're doing videos, keeping them short and precise would suit things well. 

This is another good resource I found that attempts to concisely display the logic chains in phaser:
http://phaserchains.boniatillo.com/#
Which is good but still lacks general examples of how a line of code in the selected element would look like. Maybe elaborating on that would be good. 

I brought this up because after a day or so I'm still trying to find out how to do certain input things using p2 physics. I think Having better docs would speed up development for lots of people out there thereby bringing in lots of new really cool innovative games. 

These are just suggestions, I hope they help. 

I want to help but at the moment I'm swamped with other projects. When my schedule clears up I would like to contribute with what I can.

**Comment by photonstorm** [comment]
I agree with this feature request, however I want to keep github issues specifically for issues with the framework code, so have labelled it and moved to an internal list for now.

**Comment by lighterletter** [comment]
Perfect. Thank you.
