### ISSUE TITLE
[low priority] Canvas rendering fails with obscure error message when using tile from not loaded tileset image

### ISSUE THREAD

**Issue by Bernhard10** [photonstorm/phaser#1874]
EDIT: Please see comment below.

With phaser 2.3.0:
The Phaser.Tileset.prototype.draw function fails, if I try to draw a tile with an index corresponding to a different layer.
I get the Error message:
"TypeError: Argument 1 of CanvasRenderingContext2D.drawImage could not be converted to any of: HTMLImageElement, HTMLCanvasElement, HTMLVideoElement."
A costum error message would be nice.

Background: The tiled Program allows you to right click on tiles to "copy" them and then left click to place them. This way I accidentally copied a tile from my invisible collision layer to the background layer. It has a high GID and comes from a different png than all the other tiles on my background layer. As soon as this tiles enters into the visible area of the map, I get the above mentioned error.

**Comment by Bernhard10** [comment]
Sorry, I missed the point in my bugreport. Only now I noticed the real reason for the Error.

I accidentally used a tile from a tileset which I didn't load into Phaser. Of course, this has to cause an Error. While an error message like "Error: No tilesetimage loaded for tile $TILE on layer $LAYER" would be nice, this is probably a very low priority issue.,

**Comment by photonstorm** [comment]
Hmm yes I see what you mean (thanks to your second comment!) - I would display an error, but then honestly there are so many things you can do in Tiled that cause errors it feels like plugging a hole in a dam. I'll give it a look when I'm next updating that class.
