### ISSUE TITLE
Maximum drawCircle calls

### ISSUE THREAD

**Issue by matthisk** [photonstorm/phaser#1875]
I'am having problems with drawCircle calls (on Graphics), as soon as I call the function too many times (for me around 700) Pixi start rendering lines between each circle. This is (/was) a known issue in Pixi (https://github.com/GoodBoyDigital/pixi.js/issues/1076) but has been resolved in Pixi 3. Are there any plans to update Phaser's dependency on Pixi to version 3?

**Comment by youssefdetovernickr** [comment]
I'm also hoping that Phaser updates the Pixi dependency.

**Comment by photonstorm** [comment]
There are no plans to integrate Pixi 3 yet, no. I may lift the Graphics section of Pixi 3 out and use that though, as Graphics handling in Pixi 2 is a bit of a mess in places and needs reworking.
