### ISSUE TITLE
Game.renderer has the wrong typescript type

### ISSUE THREAD

**Issue by sanchopancho13** [photonstorm/phaser#1877]
The Game "renderer" property is currently defined as a number type in the typescript definition file, however it is declared like this in the jsdoc:

{PIXI.CanvasRenderer|PIXI.WebGLRenderer}

In typescript 1.4 this can be declared as a union type.  Prior to that, I think the correct way to support that is with the 'any' type.

**Comment by photonstorm** [comment]
@clark-stevenson what do you reckon?

**Comment by clark-stevenson** [comment]
Done! Sorry this one slipped past me.  @sanchopancho13  was correct.
