### ISSUE TITLE
Massive disc usage with phaser in webgl mode 

### ISSUE THREAD

**Issue by cscott5288** [photonstorm/phaser#1878]
I've been struggling to identify a very problematic bug over the past month and I think I may have found the source of the problem. The bug is a HUGE issue for me. It causes the game to be unplayable in certain software environments and this has prevented me from launching a demo of my game. 

Symptoms: 
* In certain software environments, my game and any phaser game in webgl mode is extremely slow. 
* if you open the built-in fps meter in Chrome, you will see random jumps at random intervals when nothing is happening in the game. you might load the game, do nothing (with nothing in update/render debugging, etc), and you will see random spikes in fps. in software environments where the performance isn't slowed down by that mysterious factor, you'll notice that the fps meter flatlines at 60 when nothing is happening in the game. this is how it should work. to assure this wasn't a fluke or some problem with my code, I stripped everything down to just Phaser and booting the game. I tried this going all the way back to phaser v. 1.6 and the problem is in every version. In some software environments, you'll see that random spiking. in others, you won't, but it definitely happens in every version of phaser in webgl mode. 
* In certain software environments, the location of other windows affect the fps of the game. For example, in yosemite on a 2009 imac, you can draw a new browser window over the game window and the fps will spike. it happens in windows as well but my windows machine is a scream machine so it's not as noticeable. at first i thought it was because phaser was processing input events, but no, it still happens when the mouse is entirely outside the window. i've made a video of this fucking weird-ass behavior so you can see for yourself:
http://news-string.com/phaser/phaser_bug.mov
The version of phaser running while this video was taken is completely stripped down. It's just phaser and an empty game world. This behavior alone would not concern me as one could easily write it off as a quirk. But because this behavior occurs only in the software environments with the performance problems, I believe it has significance. Yes, I've tried it in my good working software environment and moving other windows around on top of the phaser window has absolutely no effect on FPS. Here's another weird thing: even if the window is in active and behind the phaser window, it can affect fps. That's right, an inactive window or application behind your game, can causes spikes in fps. wtf?

* In software environments where the performance problem isn't present, it's common to see something like 1-15mb written to the hard drive (activity monitor, disk tab in mac) by the google chrome process. in software environments where the performance problem is present, you could see as much as 1GB of data being written to the hard drive in a single session.  Here you can download the open files and ports while phaser is running, when the problem is present:
http://news-string.com/phaser/open_files_ports_performance_issues.txt
And here you can download a sample of the chrome process when the problem is present:
http://news-string.com/phaser/chrome_sample_w_performance_issues.txt
And when the problem is not:
http://news-string.com/phaser/chrome_sample_working.txt

I'm not 100% sure, but I think this means the problem is not a cpu or memory problem, but a disk reading/writing problem. there's just too much disk activity while phaser/webgl is running and this is causing performance problems. it doesn't just happen in yosemite. it happens randomly in windows 7 as well. i've not seen the behavior in mac osx10 (yet).

**Comment by photonstorm** [comment]
What you're seeing is how the browser deals with a webgl environment and
request animation frame. Phaser has absolutely no control over what or when
chrome writes to disk, literally nothing. You can't even tell from JS when
it happens.

Fps rates changing when the window is obscured is extremely common and
again utterly out of your (or phasers) control. Some browsers like Firefox
for example stop raf entirely if you load your game in an iframe and set
display none from css. There aware many many gotchas like this out there,
and they vary tremendously from browser version to GPU as well. What you
witness from your environment is going to be massively different to what
others see on theirs.

Most importantly though: you have next to no control over any of this. The
browser is doing what the browser is doing, it won't tell you why, or what
or even when. It just does it. Insight into what browsers are actually up
to internally is almost never exposed to JS sadly.



On Saturday, June 27, 2015, cscott5288 <notifications@github.com> wrote:

> I've been struggling to identify a very problematic bug over the past
> month and I think I may have found the source of the problem. The bug is a
> HUGE issue for me. It causes the game to be unplayable in certain software
> environments and this has prevented me from launching a demo of my game.
>
> Symptoms:
>
>    - In certain software environments, my game and any phaser game in
>    webgl mode is extremely slow.
>    - if you open the built-in fps meter in Chrome, you will see random
>    jumps at random intervals when nothing is happening in the game. you might
>    load the game, do nothing (with nothing in update/render debugging, etc),
>    and you will see random spikes in fps. in software environments where the
>    performance isn't slowed down by that mysterious factor, you'll notice that
>    the fps meter flatlines at 60 when nothing is happening in the game. this
>    is how it should work. to assure this wasn't a fluke or some problem with
>    my code, I stripped everything down to just Phaser and booting the game. I
>    tried this going all the way back to phaser v. 1.6 and the problem is in
>    every version. In some software environments, you'll see that random
>    spiking. in others, you won't, but it definitely happens in every version
>    of phaser in webgl mode.
>    -
>
>    In certain software environments, the location of other windows affect
>    the fps of the game. For example, in yosemite on a 2009 imac, you can draw
>    a new browser window over the game window and the fps will spike. it
>    happens in windows as well but my windows machine is a scream machine so
>    it's not as noticeable. at first i thought it was because phaser was
>    processing input events, but no, it still happens when the mouse is
>    entirely outside the window. i've made a video of this fucking weird-ass
>    behavior so you can see for yourself:
>    http://news-string.com/phaser/phaser_bug.mov
>    The version of phaser running while this video was taken is completely
>    stripped down. It's just phaser and an empty game world. This behavior
>    alone would not concern me as one could easily write it off as a quirk. But
>    because this behavior occurs only in the software environments with the
>    performance problems, I believe it has significance. Yes, I've tried it in
>    my good working software environment and moving other windows around on top
>    of the phaser window has absolutely no effect on FPS. Here's another weird
>    thing: even if the window is in active and behind the phaser window, it can
>    affect fps. That's right, an inactive window or application behind your
>    game, can causes spikes in fps. wtf?
>    -
>
>    In software environments where the performance problem isn't present,
>    it's common to see something like 1-15mb written to the hard drive
>    (activity monitor, disk tab in mac) by the google chrome process. in
>    software environments where the performance problem is present, you could
>    see as much as 1GB of data being written to the hard drive in a single
>    session. Here you can download the open files and ports while phaser is
>    running, when the problem is present:
>    http://news-string.com/phaser/open_files_ports_performance_issues.txt
>    And here you can download a sample of the chrome process when the
>    problem is present:
>    http://news-string.com/phaser/chrome_sample_w_performance_issues.txt
>    And when the problem is not:
>    http://news-string.com/phaser/chrome_sample_working.txt
>
> I'm not 100% sure, but I think this means the problem is not a cpu or
> memory problem, but a disk reading/writing problem. there's just too much
> disk activity while phaser/webgl is running and this is causing performance
> problems. it doesn't just happen in yosemite. it happens randomly in
> windows 7 as well. i've not seen the behavior in mac osx10 (yet).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/1878>.
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by cscott5288** [comment]
Yeah, I wasn't sure if the disk space usage had anything to do with it but I thought I should mention it since it was one of the only differences I noticed between the environments that work well with my game and those that don't. I'm honestly at my wit's end here trying to figure this out. As a web developer who does mostly websites, I usually don't see much difference in how front end stuff is interpreted by two different environments (os/cpu/gpu,etc) as long as the browser is the same. I suppose it's different when webgl is involved because the gpu is a big part of the equation. 

Here you can download a zip containing 5 files:
* Chrome js cpu profile, heap snapshot and heap allocations (timeline) in the not working environment
* Chrome heap snapshot and heap allocations (timeline) in the working environment. I couldn't get a cpu profile for the working environment because chrome would crash when i would start the profiler. 

Download link:
http://news-string.com/snapshots.zip

If you do have time, I'd really appreciate it if you took a peek. I have absolutely no clue how to read these things and I suppose it would require a strong understanding of Phaser's core (which I am lacking) to interpret them anyway.

**Comment by cscott5288** [comment]
Also, here is a screenshot of the js profiler for the bad environment. this was taken over the course of maybe 10 seconds and I've ordered it by "self" percentage:
http://i.imgur.com/bKspS8N.png

**Comment by cscott5288** [comment]
P.P.S. I was able to get a js profiler of the working environment:
http://i.imgur.com/so6Puyt.png

If you compare that to the not-working, the not-working uses twice as much cpu % on "textImage2D." Whatever could that mean? I think we might be on to something here.

**Comment by wayfu** [comment]
My experience with large amounts of CPU going to texImage2D (not text-Image btw) was that it happened when I didn't do smart texture upload into the GPU (I had written my own shader that used a bunch of extra textures and those were apparently uploaded for every rendered object instead of once and then used by all of them.)

**Comment by georgiee** [comment]
Hey, 
I don't get your 'bad environment'. Is it a single computer which shows these glitches on every OS ? Or do you have many systems with those symptoms at hand? There are so many things involved. It could go as far as that your gpu, ssd or whatever in the pipeline is a little bit broken. 

You should really get an example online so that other people can try it themselves. Strip your code down even more. Remove Phaser. Try it only with PIXI, try it with other texture uploading engines or even with your very own texture upload in webgl.

Maybe it's worth to ask the folks over at the developer mailing lists of blink, the chrome rendering engine, for insights about the huge data transfer rate you get?

**Comment by cscott5288** [comment]
can you explain what you mean by "smart texture upload"? Is it related to loading images into cache? 
Not loading images into cache seems to have no effect. 

@georgiee I have 3 machines: an imac 2009, windows 7 desktop and a macbook air. I've seen the issue on both the windows machine and the imac. On the windows machine, it happens sporadically. today for example, it's completely fine. But I might boot up my pc tomorrow and I'll see the problem. I might reset the game and the fps will suddenly plummet. The problem is always there with the imac ... i know, it sounds completely absurd that these 3 computers would be performing differently using the same browser on the same codebase at different times. with the imac, the problem is in all browsers including safari and firefox. it's just complete madness.

**Comment by wayfu** [comment]
No, it had nothing to do with the cache, or any Phaser internals really. It was purely a bad shader design that did me in. I did things in such a way that I uploaded too much texture data per frame to the GPU, and performance suffered. IIRC, your project is visually very intense, with huge maps and complex, screenshot-based graphics?

**Comment by cscott5288** [comment]
yeah, I just don't know. i've tested for a few more hours and i actually can get it working on the imac... but when it chooses to work/not work is completely random. I'll refresh the page and cache and it will work. A few minutes later, with that very same codebase, I'll refresh the page and cache and it will cease to  work. I might leave caching out of the equation altogether and it might work for a few page loads. But then randomly it will suddenly stop working after a page load. 

i might strip the game of all core functions, refresh the page and it will suddenly start working again after it hadn't worked for a while. then the stripped version of the game will cease to work after a few page loads. the game might not be working even after 10+ page loads but then I'll replace a file with a copy+paste and it will suddenly start to work. mind you this is happening in scenarios in which the code I'm pasting is identical to the code its replacing ... and somehow that is causing it to start working again. i've honestly never seen anything like it. 

I've tried several times to strip the game down so I can upload it and you guys could check it out. but because there is no single section of the codebase which I can identify as causing the problem, I have no way of creating a stripped-down version which has the bug... and that's assuming the bug is in the codebase. i'm beginning to believe this might be a hardware problem. tonight i'll try testing on other phaser webgl games to assure this isn't something wrong with my imac. i am running yosemite after all.

**Comment by wayfu** [comment]
Before you devote the rest of your life to this, consider that there's nothing you can do about it, that it's completely random, that you're assigning meaning to completely meaningless chance happenings, like the crows that get fed at random times and develop the superstition to continually do what they were doing right before they were fed, in the hopes that that was what made it happen.

**Comment by cscott5288** [comment]
i've figured it out what causes webgl to crash!

creating a bitmap larger than approx. 3000 x 3000 and adding it to the world - some software environments just can't handle that. even if you're not drawing anything to the bitmap. in software environments where this causes a crash, sometimes it will crash, other times it will be perfectly fine (hence it was so difficult to identify as the source of the crash). but it's definitely the size of the bitmap that causes the crash when it does happen. 

that said, i have two options to work around this bug:
A) Tile a bunch of small images in a group and cache that group as a bitmap. then when i want to do bitmap operations, I can simply perform them on the bitmap of the group
B) Create a bunch of small bitmaps and tile them. when i need to do a bitmap operation, I can apply it to the appropriate bitmaps rather than one big bitmap

Is there a way to access the bitmap created by caching a group as a bitmap? If I could access that and perform normal bitmap operations, I could go with option A which would make my life easy. Option B is a bit more complicated. 

I'm not sure if I should close this issue as it's either a genuine bug or a webgl performance limitation.

**Comment by photonstorm** [comment]
A 4000x4000 bitmap would create a 4096x4096 texture on the GPU (and use up the same amount of corresponding memory) - some GPUs will handle this with ease, others will struggle, others won't even do it at all (mobile GPUs especially). It's hardware dependant. The older the hardware, the worse the result will be. If you then update this texture constantly - for example a tile map that draws to a 4096x4096 sized canvas, it then has to push this up to the GPU every frame - which uses up loads of memory bandwidth (which is what @wayfu was talking about re: texture uploading) - on some systems this is enough to crash them entirely.

You've a two options as I see it:

1) Use smaller textures
2) Ignore old hardware and flag your game accordingly
