### ISSUE TITLE
Bitmapdata is pixelated on scaled games

### ISSUE THREAD

**Issue by youssefdetovernickr** [photonstorm/phaser#1880]
Basically what the title says.. Using a basic `game.add.bitmapData(game.width, game.height);` on a scaled game you get a very pixelated bitmapdata when you are about to add it to the world.. Seems logical, however I can't figure out how to make this properly scaled.. When using game.width * game.world.scale.x, game.height * game.world.scale.y it basically takes way too long to render.

**Comment by photonstorm** [comment]
A BitmapData object is just a blank canvas with a load of methods to help draw to it, nothing more really. If you've scaled your game in such a way that it appears pixelated then you need to create a bigger canvas to work from, or set the canvas smoothing options (that *some* browsers support) directly on it.

It's no different to loading an image of a certain size and using that for a Sprite, it will be scaled in the same way as the bmd is. Also depending on how the scaling is being handled that will influence how images and bmds are drawn. Scaling via css for example will 'blur' everything, no matter what you do under the hood.
