### ISSUE TITLE
Phaser.TilemapLayer does not resize when the game world is resized

### ISSUE THREAD

**Issue by hilts-vaughan** [photonstorm/phaser#1881]
It creates an internal `Canvas` inside which still has the old renderWidth and renderHeight on the `this._mc` which causes it not render the difference (bigger, if you start small and resize up). This has the disadvantage of setting the game size not drawing more tilemaplayer's. This includes the canvas width and height. i.e: the game size.

How can I get the tilemap layer to respond? I'm OK with manually letting them know they need to render more. Destroying and recreating them is one option but if the operation is expensive, it's not viable on a window resize.

**Comment by photonstorm** [comment]
Ok this is now done, tested and working in dev.

**Comment by kamikaze1945** [comment]
I tested in phaser 2.4.1 change resize. My script:

function preload() {
	...
	Global.game.scale.scaleMode = Phaser.ScaleManager.RESIZE;              
	Global.game.scale.pageAlignHorizontally = true;                   
	Global.game.scale.pageAlignVertically = true;
	Global.game.scale.forceOrientation(true, false);
	...
}

function resize() {
	Global.game.scale.scaleMode = Phaser.ScaleManager.RESIZE;
	Global.game.scale.pageAlignHorizontally = true;
	Global.game.scale.pageAlignVertically = true;
	Global.game.scale.forceOrientation(true, true);
	Global.game.scale.refresh();
}

Can I ask you to provide the correct code that will correctly gauged the game after obruceniu device?
