### ISSUE TITLE
Inconsistent behavior in updating bitmap sprite 

### ISSUE THREAD

**Issue by luckylooke** [photonstorm/phaser#1883]
Hello, I am using generated bitmap data as sprite in my plugin. I am modifying the data and want to update sprite. In Chromium/ubuntu14.04, Firefox/win7 and IE/win7 sprite is updated automatically. Only in chrome(v42)/win7 I have to workaround it by destroying sprite and creating new one instead. I was trying bitmapdata.update() method, but it didnt help. Chrome does not throw any error.

Live DEMO of the problem is on plugin page [here](http://luckylooke.github.io/phaser-islandjs-plugin/).

Second island with debug = true should react on user clicks and draw additional info. Try it in chrome/win and other browser.

I am using this method to add aditional info into map:
```javascript
Phaser.Plugin.Island.prototype.renderSite = function(index) {
    var cell = this.diagram.cells[index],
        he = cell.halfedges,
        ctx = this.debugLayer.ctx, // debugLayer is Phaser.BitmapData object
        point;
      
      ctx.font="8px";
      ctx.fillStyle = '#ff0';
      
      ctx.beginPath();
      ctx.arc(cell.site.x,cell.site.y,2,0,2*Math.PI);
      ctx.fill();
        
      for (var i = 0; i < he.length; i++) {
        ctx.fillStyle = '#ff0';
        point = he[i].edge.lSite;
        ctx.fillText('L'+i,point.x-8,point.y-8);
        point = he[i].edge.rSite;
        if(point){
            ctx.fillText('R'+i,point.x+8,point.y+8);
        }
        
        ctx.fillStyle = '#0f0';
        point = he[i].getEndpoint();
        ctx.beginPath();
        ctx.arc(point.x,point.y,1,0,2*Math.PI);
        ctx.fill();
        ctx.fillText('E'+i,point.x-8,point.y-8);
        point = he[i].getStartpoint();
        ctx.beginPath();
        ctx.arc(point.x,point.y,1,0,2*Math.PI);
        ctx.fill();
        ctx.fillText('S'+i,point.x+8,point.y+8);
      }
};
```

It is probably bug in chrome, but how should I describe it to google?

Thanks for any hints

**Comment by photonstorm** [comment]
Does this still happen in modern versions of Chrome? If yes, then I'd wager it's a bug in the code. If not, I can close this.

**Comment by luckylooke** [comment]
Yes it is still the issue, I have also updated Phaser to 2.4.4 and it didn't help. Test on Firefox = OK. Test on Chrome = NOT-OK.

**Comment by photonstorm** [comment]
I need a test case really, I can't debug the whole thing. Surely it must boil down to something quite specific?

**Comment by luckylooke** [comment]
Ok.. I will try to extract it tomorrow

**Comment by luckylooke** [comment]
Here is the problem: Sprite is not redrawn on bitmapdata update, so I have to destroy sprite and recreate it with updated bitmadata, but just in Chrome. In Firefox it works correctly. Check [this fiddle](http://jsfiddle.net/luckylooke/ywzmkso3/3/).

I have also find out that Sprite.events seems not to be working if sprite is created from bitmap data, look at [this fiddle](http://jsfiddle.net/luckylooke/ywzmkso3/1/).

**Comment by photonstorm** [comment]
Your first fiddle doesn't work because you're never telling the BitmapData to update its WebGL texture. You can't just modify the underlying context directly and expect that to be reflected in WebGl, it needs to know to create a new texture from it and re-apply it to the Sprite. Do that by setting the 'dirty' flag and then calling render:

```
        bmd.dirty = true;
        bmd.render();
```

And in the 2nd fiddle your sprite events don't work because you've not enabled the sprite for input. Add this: `sprite.inputEnabled = true;` and it works just fine.

Going to close this off as neither are actual issues with Phaser.
