### ISSUE TITLE
Making P2 body on a Rope object fails (no anchor)

### ISSUE THREAD

**Issue by standardgaussian** [photonstorm/phaser#1885]
Rope is supposed to be compatible with the physics systems in Phaser, but the Phaser.Rope object has no "anchor" member variable, which P2 attempts to set when using enableBody.

Either Rope needs to create an anchor for P2 to see, or enableBody needs to check if the anchor exists before attempting to move it.

**Comment by photonstorm** [comment]
Fixed in dev.
