### ISSUE TITLE
debug currentAlpha setting doesn't stick

### ISSUE THREAD

**Issue by wayfu** [photonstorm/phaser#1888]
Apparently, debug.currentAlpha will always be set to game.globalAlpha before anything is drawn—as a workaround, I've been setting debug.sprite.alpha. Is this by design? If so, perhaps it could be clarified in the docs...

**Comment by photonstorm** [comment]
Really not sure what was going on there, it was used as more of a temp. var to hold the context alpha before anything was rendered. But I've now swapped it to set the context globalAlpha to currentAlpha at the start of rendering (it can still be replaced by Debug calls though)
