### ISSUE TITLE
Properties that do not exist in Box2D in the last release version

### ISSUE THREAD

**Issue by jdnichollsc** [photonstorm/phaser#1894]
See in build/box2d-plugin-full.js:

```
Line 35235 => _categoryContactCallbacksContext property doesn't exist. (Solution http://screencast.com/t/4MemHHsm)
```
```
Line 35347 => _categoryPresolveCallbacksContext property doesn't exist. (Solution http://screencast.com/t/mH6X2OWhA45)
```
```
Line 35459 => _categoryPostsolveCallbacksContext property doesn't exist. (Solution REMOVE EXTRA "S" CHARACTER)
```
See other errors http://www.html5gamedevs.com/topic/14181-box2d-phaser-plugin-errors/

Regards, Nicholls

**Comment by photonstorm** [comment]
It's somewhat worrying that jshint never caught any of these at all. Either way they're all fixed in 1.0.3 - the other error in the forum thread was fixed in 1.0.1 (World.reset)
