### ISSUE TITLE
Custom builds from dev fail

### ISSUE THREAD

**Issue by standardgaussian** [photonstorm/phaser#1897]
After doing a merge from dev in order to submit a pull request, Phaser now fails while trying to boot. I did a totally clean checkout and the error still occurs. With the same setup, trying to run v.2.3.0 works just fine.

Both regular builds (run with just "grunt") fail, as well as any custom builds I've tried so far.

I get the following console error:

http://i.imgur.com/O88U8xj.png

The phaser.js line numbers indicated are entirely unrelated to the error.

**Comment by photonstorm** [comment]
Yeah don't worry, I'll sort it out tomorrow when I put up the new release candidate for test.
