### ISSUE TITLE
Groups addMultiple does not add all children

### ISSUE THREAD

**Issue by AnderbergE** [photonstorm/phaser#1898]
https://github.com/photonstorm/phaser/blob/dev/src/core/Group.js#L376

When adding children from another group, only half of them are added. This happens because the children are removed from the group they came from, while added to the other, ie the for loop adds to i while removing from the children.length.

I'm guessing this is quite a normal scenario, but since the array could also be something else than the children of a group, A check for child parent is relevant?

**Comment by photonstorm** [comment]
Hmm first time anyone has ever reported this! So I'm guessing it's not *that* common. However it should work, so the recent changes I've just made to the dev branch should cover it.

**Comment by AnderbergE** [comment]
Haha, yeah, maybe not very common. Thanks for the update :)
