### ISSUE TITLE
2.4 RC1: onMouseDown callback receives pointer that's not down

### ISSUE THREAD

**Issue by wayfu** [photonstorm/phaser#1902]
I have added a handler to an object like this:
```
this.events.onInputDown.add(this.onMouseDown, this);
this.onMouseDown = function(object, pointer) {
    console.log(pointer.isDown);
}
```
logs false.

**Comment by wayfu** [comment]
correction: when I log pointer.isDown, i get "true". when I log pointer and expand it in the console, I get false.

**Comment by photonstorm** [comment]
Pretty sure that's just the way dev tools works. When you expand the object
it shows its current state, not its state at the time it was logged. And by
then it's gone. Json stringify it when you log it to see it exactly as it
was at the time of the log.


On Saturday, July 11, 2015, wayfu <notifications@github.com> wrote:

> correction: when I log pointer.isDown, i get "true". when I log pointer
> and expand it in the console, I get false.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/1902#issuecomment-120627589>
> .
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by clark-stevenson** [comment]
Ahh the Schroeder's cat, its state changes when you observe it! . :+1: for json tip, it took me ages to figure out I had to use toString() because of it.

**Comment by wayfu** [comment]
ah, thanks!

**Comment by photonstorm** [comment]
Have checked this out and it looks fine to me. However I did just update it so that isDown/isUp are now accurate based on the state of ANY button on the device.
