### ISSUE TITLE
Audio does not play on webview. For example: Cordova, Phonegap

### ISSUE THREAD

**Issue by phamtranphu** [photonstorm/phaser#1904]

**Comment by phamtranphu** [comment]
It works when browse with chrome, firefox... and android, iphone simulator but does not work on real device.

**Comment by photonstorm** [comment]
I've seen plenty of Cordova wrapped Phaser games with audio, so whatever is causing this is specific to your implementation rather than Phaser itself. More details needed.

**Comment by phamtranphu** [comment]
I can play my sound, But the problem is that i have to call function sound.play() 2 times to play sound on my phone webview. It seems sound haven't not loaded at the first time. 

On create method:
//Just to force audio loaded
Puzzle.audioItem = this.add.audio('audio'); 
Puzzle.audioItem.mute = true; 
Puzzle.audioItem.play();

Then on update method:
//To play audio
Puzzle.audioItem.mute = false; 
Puzzle.audioItem.play();
