### ISSUE TITLE
Does phaser support transparency info from video?

### ISSUE THREAD

**Issue by darting** [photonstorm/phaser#1910]
Hi all,
Does phaser support transparency info from video?

thanks

**Comment by photonstorm** [comment]
Yes, but it's nothing to do with Phaser. Only webm videos can include alpha and only Chrome supports webm with alpha at the moment.

**Comment by darting** [comment]
hi @photonstorm, I want to implement a custom component to support transparent for video
1, in chrome, I will use webm. 
2, in other browsers, I will use mp4  just like http://jakearchibald.com/scratch/alphavid/ 

do you have any suggest how to do it?

**Comment by photonstorm** [comment]
If you view source on the alphavid page you'll see that they draw the video to a canvas, then process every single pixel of the canvas extracting  a colour value and drawing it out again. This is an incredibly expensive way of supporting alpha - it's also why they use such a tiny video file for the demonstration. 

Even so, to replicate it just use a BitmapData and essentially exactly the same code as they're using, using the BitmapData's context to draw to instead.

**Comment by darting** [comment]
yes, I know how does it work. I just want to have the suggestion from you about how to compatible with Phaser since I will use Phaser to handle all the other things in my games. 

thanks.
