### ISSUE TITLE
[dev] Phaser.Loader failing to load audio

### ISSUE THREAD

**Issue by noidexe** [photonstorm/phaser#1914]
Code:
<code>this.game.load.audio('defaultBounce', ['assets/audio/SFX/default.mp3']);</code>

Console output:
<pre>Phaser.Loader - audio[defaultBounce]: Cannot set property 'defaultBounce' of undefined</pre>

This doesn't happen with 2.4-RC1 only with the latest commits. Still present in a7f17394a465c53217bc58ad7e02e3d29e8c8b84

**Comment by photonstorm** [comment]
Good catch - should be fine now.
