### ISSUE TITLE
[dev] Touch not working

### ISSUE THREAD

**Issue by noidexe** [photonstorm/phaser#1916]
Buttons work fine with a mouse but fail on touch devices or when emulating mobile devices on chrome.  Same for anything dependent on "isDown". 

Tested on 45944d689ceb3483cc57c3ce232b2302ac176dd2
Probably something related to b0a8d3d78c006a3f2e13c3280a10fc77bee8116f or 41d702b4855573c282b14f4865f202b7196b3283

**Comment by photonstorm** [comment]
Thanks - this is now working again, but I'm refactoring it slightly to deal with better button handling.
