### ISSUE TITLE
bitmapData.drawGroup always use smooth

### ISSUE THREAD

**Issue by VitaZheltyakov** [photonstorm/phaser#1917]
var group = this.add.group();
var img = game.add.image(0, 0, 'image');
img.smoothed = false;
img.scale.setTo(10, 1);
group.add(img);
var bmd = game.add.bitmapData(2048, 2048);
bmd.addToWorld();
bmd.drawGroup(group);

Final image always use smooth

**Comment by photonstorm** [comment]
It's not the image that needs smoothing disabled, it's the BitmapData.
