### ISSUE TITLE
Problem with docs url

### ISSUE THREAD

**Issue by pooya72** [photonstorm/phaser#1918]
for example this url only show first page 

http://phaser.io/docs/Phaser.Particles.Arcade.Emitter.html

instead this works 

http://phaser.io/docs/2.3.0/Phaser.Particles.Arcade.Emitter.html

i dont know if this is an issue or you did it by will.

**Comment by photonstorm** [comment]
The first one is an old link, maybe from Google, but it doesn't come from our site. Probably left over from the old docs site structure. I'll add a redirect in for it.

**Comment by pooya72** [comment]
yes its from google and mostly links are like first one.

**Comment by photonstorm** [comment]
Done. The site now redirects accordingly. If the file doesn't exist then you get the index page, otherwise it takes the latest docs version.
