### ISSUE TITLE
Debug canvas context size does not update when using ScaleManager.RESIZE

### ISSUE THREAD

**Issue by francisberesford** [photonstorm/phaser#1919]
Not a critical bug, but still a slightly annoying one.

I'm debugging the mouse pointer with ```this.game.debug.pointer(game.input.mousePointer);``` while using the automatic resize feature provided by ```ScaleManager.RESIZE```.  The problem is the visual output is being cropped because the canvas context being used is still at the original size which was set when instantiating the Game.

See: Phaser.Utils.Debug#boot

This bug would affect all debug output types.

Edit: FYI: I've just instantiated the game at a larger size to work around it...

![debug_cropped](https://cloud.githubusercontent.com/assets/1336422/8765082/3f917bf0-2e26-11e5-9a46-ce786c702115.png)

**Comment by pnstickne** [comment]
This only affects WEBGL; in CANVAS mode the debug information is written directly to the same-same output.

**Comment by nisimjoseph** [comment]
The bug exist in the ScaleManager class getParentBounds function.
I can't push changes to new branch and create pull request to fix it.
i am getting 403 on the push to new branch.

**Comment by photonstorm** [comment]
@nisimjoseph could you just paste the fix up here? I doubt it's that large?

**Comment by photonstorm** [comment]
Closing this one off as it's now (finally) fixed in dev.

**Comment by yeluoqiuzhi** [comment]
I have the save problem in phaser v2.8.2 now

**Comment by yeluoqiuzhi** [comment]
I use EXACT_FIT,  I found it resize debug bitmap to my canvas size in css style, not the width attribute in canvas. My canvas width in css is 667px, but my game and width in canvas is 1334.
Because the will work well in retina.

**Comment by photonstorm** [comment]
@yeluoqiuzhi you need to open the issue on the Phaser CE repo (with a test case)
