### ISSUE TITLE
2.4.0 - Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by StealthC** [photonstorm/phaser#1926]
I have been testing with the new release but the phaser.min.js and phaser.js won't compile in browser:
In Chrome, it gives the error "Uncaught TypeError: Cannot read property 'prototype' of undefined" in line 35790 of phaser.js:
Phaser.TileSprite.prototype = Object.create(PIXI.TilingSprite.prototype);

**Comment by Clever-Coding** [comment]
:+1:

**Comment by IanRamosC** [comment]
The same here. :/

**Comment by DoubleCat** [comment]
same

**Comment by photonstorm** [comment]
Arse, ok will take a look. It works fine 'unbuilt' so it must have been a change to the build script I did earlier.

**Comment by pooya72** [comment]
same

**Comment by rogerluiz** [comment]
same

**Comment by noidexe** [comment]
@pooya72 @rogerluiz Yeah, I'm sure it's happening to everyone using the concatenated versions on master. I've build from 915a757f9672318df1cf50476131202555d9f47f (right before tilesprite and rope being split as custom tasks) and it seems to be working fine, and It's only four commits away from master.

**Comment by Ryuuke** [comment]
It works now, thanks

**Comment by photonstorm** [comment]
Ok the new release up on master (2.4.0a) has this fix in place. It will take a while longer before it hits npm, but just pull from master or download from the new release I posted and all will be fine.

To double check make sure the console outputs 2.4.0a, not 2.4.0.

**Comment by DWboutin** [comment]
Just tried to create a browserify bundler and got this error:

`phaser.js:23083Uncaught ReferenceError: PIXI is not defined`

I got version 2.4.6 from npm.

**Comment by 3rfan** [comment]
@DWboutin have the same problem :(

**Comment by ZakSignal** [comment]
Just installed phaser via npm and have the PIXI is not defined issue.

**Comment by sombriks** [comment]
same here, Phaser 2.4.8

**Comment by photonstorm** [comment]
Read the readme. It explains what to do.
