### ISSUE TITLE
OGV file not recognized as OGG Video

### ISSUE THREAD

**Issue by JB-Tellez** [photonstorm/phaser#1928]
An Ogg video with .ogv extension not recognized. Changing extension to .ogg works. Tested on OSX 10.9.4 in Chrome and Firefox. This may be an issue with browsers themselves but thought I'd point it out as a workaround at least.

**Comment by photonstorm** [comment]
What's an OGV file? Is it just an OGG with a different extension, or something else?

**Comment by JB-Tellez** [comment]
OGV = ogg video. At least that's what the Ogg folks are shooting for though it looks like .ogg is used for both video and audio in the wild. But many video converters output to .ogv not .ogg. Like I mentioned, this may well be an issue in the browsers themselves and there's nothing Phaser can do about it. The workaround is to just change the Ogg video extension to .ogg

Thanks for all the awesomess of Phaser, I've been a fan since FlixelPowerTools ;)

Here's a blurb from the Ogg wiki page...

** Before 2007, the .ogg filename extension was used for all files whose content used the Ogg container format. Since 2007, the Xiph.Org Foundation recommends that .ogg only be used for Ogg Vorbis audio files. The Xiph.Org Foundation decided to create a new set of file extensions and media types to describe different types of content such as .oga for audio only files, .ogv for video with or without sound (including Theora), and .ogx for multiplexed Ogg.[4] **

**Comment by photonstorm** [comment]
Ok thanks for the heads up and kinds words, I'll add ogv as a valid video extension to check for!

**Comment by photonstorm** [comment]
This has now been added to the dev branch - thanks for the suggestion.
