### ISSUE TITLE
Spine plugn

### ISSUE THREAD

**Issue by qdrj** [photonstorm/phaser#1930]
I've noticed that there is a support for Creature but I would say that Spine is "industry standard" now.
More artists are familiar with it.

I would gladly pay for a Spine plugin even without advanced features like meshes or free-form deformations. Just basic set of features which will work on canvas and webgl renderers.

**Comment by photonstorm** [comment]
So would I.

The difference is that the Creature authors were incredibly helpful, provided us with custom libraries, easy integration, listened to our feedback and helped get things working with the minimum of fuss.

Until Spine is fully supported by Pixi 2 (which will never happen imho) I can't see this situation changing in the immediate future. For Phaser 3 we'll revisit it and it's already on the list.
