### ISSUE TITLE
TilemapLayer obcjet can't use Input

### ISSUE THREAD

**Issue by luozan** [photonstorm/phaser#1931]
layer.inputEnabled = true;
        layer.input.onUp.add(function(){},this);

        Chrome error : 'Uncaught TypeError: Cannot read property 'onUp' of undefined'.

        I saw it's no inputEnabled when I print it.

        And,can you help me?
        I have a question about event.

        sprite.events.onInputUp.add(function(){},this);
        game.input.onUp.add(function(){},this);
 
        They are triggering at same time when I click sprite.

        I'm looking forward to your reply,thank you.

        I like Phaser very much :)

**Comment by photonstorm** [comment]
TilemapLayers are essentially Sprites, so you detect input in the same way:

```
layer.inputEnabled = true;
layer.events.onInputDown.add(func, this);
```

**Comment by luozan** [comment]
I tried it,but no trigger

**Comment by luozan** [comment]
sorry,not trigger

**Comment by luozan** [comment]
I tried it, but it didn't trigger

**Comment by photonstorm** [comment]
Try it with the version of Phaser in the _dev_ branch, as it works fine for me now.
