### ISSUE TITLE
cache.hasFrameData ignores cache type

### ISSUE THREAD

**Issue by standardgaussian** [photonstorm/phaser#1935]
Usage of cache.hasFrameData suggests that you can choose your cache type, but the actual function throws away that parameter and always checks Phaser.Cache.IMAGE instead, leading to errors when trying to add animations when using a bitmapdata key.

**Comment by photonstorm** [comment]
`hasFrameData` doesn't have a cache parameter and it says in the docs specifically that it only checks the Image cache, so I don't believe this is an error here - however I do agree it's a useful feature, so I've added it in.
