### ISSUE TITLE
[2.4.1] Uncaught ReferenceError: PIXI is not defined when using Browserify/webpack

### ISSUE THREAD

**Issue by cleverlycoding** [photonstorm/phaser#1937]
When building with browserify/webpack, I get this error `Uncaught ReferenceError: PIXI is not defined`,
but when I load Phaser from a script tag, everything is fine.

**Comment by photonstorm** [comment]
I have a build script specifically for browserify, I'll publish it next week along with the ones I've made for systemjs and requirejs. Until then load it as a global.

**Comment by Clever-Coding** [comment]
thanks :)

**Comment by Substitute59** [comment]
Still the same problem with phaser 2.4.2
Is it supposed to fix it ?

**Comment by photonstorm** [comment]
You need to use the `--split true` option when making a custom build. This will split all of the libs out (phaser, pixi, p2 and creature) to their own independently UMD wrapped files. These should then be required as needed, each allowed to populate the global space. Pixi should come before Phaser.

There is not, and will not, be a 'single' file version of Phaser that works with browserify.

**Comment by lobobabysaurus** [comment]
So in order to use phaser and browserify you have to build it locally? Is there any way to use the phaser npm package with browserify without seeing this PIXI issue? Specifically wonderimg because of use with coffeescript where setting global state is more difficult

**Comment by eignhpants** [comment]
Is there a build script for using browserify? It is referenced in this thread but I have no been able to find it.

**Comment by cleverlycoding** [comment]
@eignhpants `grunt custom --split true` is supposed to work when making a [custom build](http://phaser.io/tutorials/creating-custom-phaser-builds).   
You can always use the [phaser-shim](https://www.npmjs.com/package/phaser-shim) module if you prefer. It's already split for you and you just need to require `phaser-shim`, which is easier to setup :)
