### ISSUE TITLE
Phaser Arcade Collision Issue.

### ISSUE THREAD

**Issue by rsredsq** [photonstorm/phaser#1940]
I noticed that phaser Arcade physics has some collision issues, they are the same as the HaxeFlixel(Flixel) has. Probably that's because functions separateX and separateY are the same. 
![Collision bug](https://cloud.githubusercontent.com/assets/5163918/3930338/a86ac380-243f-11e4-95b5-572ef6338083.gif)
[Here I wrote about it in the HaxeFlixel repository.](https://github.com/HaxeFlixel/flixel/issues/1270)
Problem exactly the same.
Here's a short example of code: https://gist.github.com/rsredsq/626bfb0458a009eddfe7

**Comment by photonstorm** [comment]
Thank you for opening this issue and the video. However this will not be addressed in Phaser, so I'm moving this over to the Lazer feature request list instead. If you wish to submit a PR that isn't massively API breaking and fixes this feature to Phaser then we will consider merging it.
