### ISSUE TITLE
Some polygons do not work as masks in WebGL

### ISSUE THREAD

**Issue by wayfu** [photonstorm/phaser#1941]
This is a weird one. jsFiddle here: http://jsfiddle.net/ofhw1vew/

Only in WebGL, only for certain very specific vertex locations, only when the containing graphics object is used as a mask, some polygons don't work.

**Comment by wayfu** [comment]
This may be due to PolyK having trouble triangulating certain polygon. See also this thread: http://www.html5gamedevs.com/topic/15975-webgl-polygon-with-tiling-texture/

**Comment by wayfu** [comment]
(here's the fiddle with earcut: http://jsfiddle.net/ofhw1vew/2/)

**Comment by photonstorm** [comment]
Putting down as feature-request, because moving to earcut would solve this.

**Comment by photonstorm** [comment]
I've replaced PolyK with EarCut and this now works properly in dev branch.
