### ISSUE TITLE
complex polygons are rendered onto renderTextures with flipped y coordinates in webGL

### ISSUE THREAD

**Issue by wayfu** [photonstorm/phaser#1942]
jsFiddle with minimal repro here: http://jsfiddle.net/fb4vrnzb/

**Comment by photonstorm** [comment]
The first thing `PIXI.RenderTexture.prototype.renderWebGL` does is to flip the display object, because they come in upside down. Evidently Graphics objects don't suffer from this - so instead of renderXY use render instead and provide your own matrix that counters the automatic flip.

**Comment by wayfu** [comment]
That isn't a valid solution because whether or not the poly is complex (ie drawn upside down) can vary from frame to frame (according to which method is used to build the polygon in the graphics renderer, as determined by WebGLGraphics.updateGraphics).

Here's a fiddle where all I've done is removed the second vertex, thereby making the polygon renderable as simple, and the Y flip is now gone: http://jsfiddle.net/v3qdxhq0/

**Comment by photonstorm** [comment]
No idea then, it's a Pixi anomaly and likely to remain one given they don't update v2 any more.

**Comment by jmp909** [comment]
this also happens on your Pixi Render Texture demo at http://phaser.io/examples/v2/display/pixi-render-texture

if you switch the render type to WEBGL and put a bit of code in the update to just let it run once, you'll notice the display actually starts off upside down

thanks
j

**Comment by jmp909** [comment]
actually.. I can now confirm that switching `game.stage` to `game.world` as suggested here
http://www.html5gamedevs.com/topic/10015-phaser-213-and-state-transition-plugin/

`renderTexture2.renderXY(this.game.world, 0,0,true);`
instead of 
`renderTexture2.renderXY(this.game.stage, 0,0,true);`

I've only just started with Phaser so I don't know if this will cause any other side-effects

**Comment by jmp909** [comment]
Hi, 

i've put another example here:
http://phaser.io/sandbox/rQJpJZNi/play

you can see that some of my graphics object is rendered upside down and some isn't

thanks
J

**Comment by jmp909** [comment]
it's any polygon with more than 4 points. I've checked with multiple examples. convex, concave, intersecting etc. the outlines draw ok, the fills don't

```javascript
    var graphics = this.game.add.graphics(0, 0);
		
    // poly with 4 points
    var points = [new Phaser.Point(38,21), new Phaser.Point(83,10), new Phaser.Point(108,48), new Phaser.Point(100,100)]
		
    // a poly with more than 4 points breaks the rendering of the shape
    // comment out the line bewlow line and issue disappears
    points.push(new Phaser.Point(20,50))
		
    // fills break
    graphics.beginFill(0x00FF00)
		
    // outline seems to be ok 
    graphics.lineStyle(1,0xFF0000)
	
    graphics.drawPolygon(points)	
    graphics.endFill()
			
    // create our render texture to the size of the game		
    var renderTexture = new Phaser.RenderTexture(this.game, this.game.width, this.game.height)
		
    // we could use graphics width/height but it reports wrong
    //var renderTexture = new Phaser.RenderTexture(this.game, graphics.width, graphics.height)
		
    // render graphic to the texture	
    // neither of these methods work	
    renderTexture.renderXY(graphics, 0,0,true)
    //this.renderTexture.render(graphics, null, true);
		
    // add the texture to a sprite
    var myRenderedSprite = this.game.add.sprite(0,0,renderTexture)
    myRenderedSprite.x=400;
```

**Comment by wayfu** [comment]
my workaround for the issue has been to raise the number of points a polygon can have before the rendered assumes it's complex (and uses the stencil rendering function), and to swap out the PolyK triangulation for Earcut (which was hella easy), a more robust implementation that will return more valid triangulations (again resulting in less use of the stencil buffer).

**Comment by photonstorm** [comment]
I've swapped to using EarCut internally.

It doesn't solve this problem (with the fills being reversed), but if you cache the Graphics as a Bitmap first it works fine:

```
    graphics.cacheAsBitmap = true;
```

And then the RenderTexture appears as it should do.
