### ISSUE TITLE
[Android] game.input.activePointer.isDown stopped working on 2.4.1

### ISSUE THREAD

**Issue by fariazz** [photonstorm/phaser#1943]
game.input.activePointer.isDown stays false when I touch on Android (version L, Nexus 5). This worked fine in 2.3 and 2.4.0a

Emailed Richard example links.

**Comment by photonstorm** [comment]
Could you all please try the latest build in the dev branch. I've uploaded build files as well for you. But I am pretty sure I've found the cause of it and in my tests in native Cordova apps and on Windows and OSX it's working correctly once again.

**Comment by tgeorge91** [comment]
This fixed my issue on iOS.

**Comment by fariazz** [comment]
Works well on my end using Android Chrome.
