### ISSUE TITLE
[Firefox desktop]  game.input.activePointer.isDown stays true after click release

### ISSUE THREAD

**Issue by fariazz** [photonstorm/phaser#1944]
Also, on Firefox desktop on 2.4.1 , once you click on the screen it's like the "input down" stays there (as you kept on pressing the mouse without releasing it)

Basically on Firefox "this.game.input.activePointer.isDown" stays true even after you release the mouse.

**Comment by photonstorm** [comment]
Pretty sure this is fine now. Firefox on Windows and OSX for me is working with the latest dev build. Here's the test I was using:

```

var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create, render: render });

function preload() {

    game.load.image('mouse', 'assets/sprites/mouse_jim_sachs.png');

}

function create() {

    game.stage.backgroundColor = '#943021';

    game.add.sprite(0, 100, 'mouse');

    game.input.mouse.capture = true;

}

function render() {

    game.debug.text("Left Button: " + game.input.activePointer.leftButton.isDown, 300, 132);
    game.debug.text("Middle Button: " + game.input.activePointer.middleButton.isDown, 300, 196);
    game.debug.text("Right Button: " + game.input.activePointer.rightButton.isDown, 300, 260);

    game.debug.text("Active Pointer: " + game.input.activePointer.isDown, 300, 360);

}
```

**Comment by fariazz** [comment]
Works great on my end now with 2.4.2!

Thanks a lot Richard.

**Comment by fariazz** [comment]
Sorry I was testing it with the wrong Phaser.

Both your example and my game don't work with FF in Ubuntu :(

Screencast: https://www.youtube.com/watch?v=p5_H1Xr_RLE

**Comment by photonstorm** [comment]
Ok this should be good now - please try the new dev branch build

**Comment by fariazz** [comment]
Works like a charm! Thanks a lot Richard.
