### ISSUE TITLE
Event cannot be triggered on Chrome

### ISSUE THREAD

**Issue by phamtranphu** [photonstorm/phaser#1945]
My game works well before upgrade to 2.4.1. After upgrade, the button click event cannot be triggered on Chrome
My code: 

var btnEasy = this.add.button((Puzzle.GAME_WIDTH-350)/2, 500, 'easybtn', this.selectLevel, this, 1, 0, 2);

and callback event:
selectLevel: function(item) {
		alert('1');
		// start the Game state
		Puzzle.LEVEL = item.level;
		
		this.state.start('Categories');
	}

**Comment by photonstorm** [comment]
Could you all please try the latest build in the dev branch. I've uploaded build files as well for you. But I am pretty sure I've found the cause of it and in my tests in native Cordova apps and on Windows and OSX it's working correctly once again.

**Comment by ksidpen** [comment]
same issue. seems to work in dev branch though

**Comment by photonstorm** [comment]
Yes this is fixed fully in 2.4.2 which I'll push to master today.
