### ISSUE TITLE
RemoveSound stuck in an infinite loop

### ISSUE THREAD

**Issue by fzuleta** [photonstorm/phaser#1946]
Hello, 

removeSound is getting stuck in an infinite loop.  it does remove the item from the cache, but then there's an infinite loop logging: WARN "Phaser.Cache.isSoundDecoded: Key "sfx_xxx" not found in Cache."

cheers

**Comment by photonstorm** [comment]
I believe this was caused because you didn't correctly destroy any Phaser.Sound instances that relied on the cached audio file *before* calling removeSound. I've added in a small guard to protect against this in the dev branch, but it should still be dealt with correctly in the game code imho.
