### ISSUE TITLE
Loading BitmapFont from manifest file broken

### ISSUE THREAD

**Issue by danthewolfe** [photonstorm/phaser#1947]
I think loading a bitmapFont from a manifest file is broken.
 
In Phaser 2.3 I was using this example and it worked fine, now it's not in 2.4:
https://github.com/photonstorm/phaser/blob/master/resources/Asset%20Pack%20JSON%20Format/assetPack.json#L122
 
Currently I'm getting the warning and error:
(warning) Phaser.Cache.getBitmapFont: Key "eightbit-32" not found in Cache.
(error) phaser.js:40821 Uncaught TypeError: Cannot read property 'font' of null
 
I saw this in the changelog:
 
LoaderParser.bitmapFont, xmlBitmapFont and jsonBitmapFont all now return the font data rather than write it to the now deprecated PIXI.BitmapText.fonts global array.

I'm assuming it's related to that, but I'm not sure if that's a change I need to make, or if something wasn't updated with the changes to the Loader.

**Comment by photonstorm** [comment]
Ah the json file wasn't updated. Basically replace `xmlURL` and `xmlData` with `atlasURL` and `atlasData`. I've updated the json and example to show this.

**Comment by danthewolfe** [comment]
Excellent. That does the job. Thanks so much! :+1:
