### ISSUE TITLE
Cocoon JS Bitmap Font Bug?

### ISSUE THREAD

**Issue by numbofathma** [photonstorm/phaser#1949]
Hello,

After updating the framework to 2.4.1 my game throws the following errors in Cocoon JS wrapper:

Phaser.Cache.getBitmapFont: Key "gloria_small" not found in Cache.
Phaser.Loader - bitmapfont[font_score]: Cannot read property 'info' of undefined
Phaser.Loader - bitmapfont[gloria_small]: Cannot read property 'info' of undefined
Not implemented createElement: video

Here is a print screen of the stack trace from Cocoon JS: http://prntscr.com/7xnfsr

Before updating I've used the 2.0.7 and 2.3.0 versions with no issues (using DOMish parser hack from here: http://www.html5gamedevs.com/topic/2312-ludei-cocoonjs-xml-bitmap-font-workaround/?p=37140).

Thanks!

**Comment by photonstorm** [comment]
You don't need the DOMish parser hack any more - just convert the XML file to JSON using the links provided in the docs and load it that way. I suspect the dom hack is looking for an old font property (that was updated to make it work properly with json data files)

**Comment by numbofathma** [comment]
It worked with XML file after removing the DOMish Parser hack!

For the sake of testing I also tried converting the font to JSON using the script from: 
http://www.html5gamedevs.com/topic/2312-ludei-cocoonjs-xml-bitmap-font-workaround/?p=37671.
and I got the following error:
http://prntscr.com/7y1y69

I also tried with online tool recommended in the docs, the result was the same.

Thank you!

**Comment by photonstorm** [comment]
Evidently something in the json created invalid xml :) A bit outside the scope of Phaser, sorry. Glad it's working now though. I'll add to the docs to not use this hack any more.
