### ISSUE TITLE
Regression of game.input.onTap from 2.3.0 to 2.4.0a

### ISSUE THREAD

**Issue by stovenator** [photonstorm/phaser#1953]
The game.input.onTap function is not called correctly starting with 2.4.0a . In Chrome 44 on OS X, the event is not fired on a mouse click. If a right-click happens on the screen, further left-click events fire the onTap event.

This can be seen when running the Invaders example from localhost. Unfortunately, choosing a phaser version from the dropdown on the examples page http://phaser.io/examples/v2/games/invaders doesn't actually load versions 2.4 or higher.

**Comment by qdrj** [comment]
I've encountered this issue as well (Chrome, windows)
Temporary solution is to replace onTap for onDown.

**Comment by photonstorm** [comment]
This is fixed in dev.
