### ISSUE TITLE
pointerOver() stays true if sprite was set to visible = false.

### ISSUE THREAD

**Issue by Cristy94** [photonstorm/phaser#1955]
If a sprite is set to `visible =  false` on the `onInputUp` event the `pointerOver` function will always return true.

Demo: http://jsfiddle.net/5qzjjegt/4/
After you click the green placeholder box, `pointerOver()` will always return true.

**Comment by photonstorm** [comment]
Just checked back as far as Phaser v2.0.0 and this issue was even in that version, so it's been around a _long_ time! Will have a look now.

**Comment by photonstorm** [comment]
Ok this is fixed now in the dev branch.
