### ISSUE TITLE
Phaser.ArrayUtils.numberArrayStep(64) returns null

### ISSUE THREAD

**Issue by pooya72** [photonstorm/phaser#1958]
`numarrays=Phaser.ArrayUtils.numberArrayStep(64);
console.log(numarrays);`

![screenshot 2015-07-30 21 27 32](https://cloud.githubusercontent.com/assets/652367/8989495/d9f44fcc-3701-11e5-980a-1c3dec924572.png)

but this works 

`numarrays=Phaser.ArrayUtils.numberArrayStep(0,64)`

**Comment by photonstorm** [comment]
Fixed in dev.
