### ISSUE TITLE
group update-function cancel member sprites' update-function

### ISSUE THREAD

**Issue by nkholski** [photonstorm/phaser#1959]
If a group has a defined update-function the update-functions of the sprites within the group are never called. 

Watch the console log in the attached example. If the group.update function is commented out the sprite.update will be called as expected:

http://phaser.io/sandbox/YyUjmPtM/play 

```javascript
var sprite = game.add.sprite(0, 0, 'phaser');
var group  = game.add.group();
group.add(sprite);
sprite.update = function(){ // Ignored!
    console.log("sprite update"); 
}
group.update = function(){
    console.log("group update");
}
```

(It's easy to work around, but it took a while until i realized what was wrong with my code.)

edit: Tested in Phaser 2.4.1 and 2.4.2

**Comment by photonstorm** [comment]
This is correct behaviour. If you replace an internal _protected_ method like `Group.update`, then you are entirely responsible for ensuring that you still maintain its previous tasks (in this case updating its children). There are lots of other protected methods that would need the same treatment.

**Comment by nkholski** [comment]
Ok. I didn't realize that there was an defined update function already. Thanks for the quick response anyway!

**Comment by photonstorm** [comment]
Yeah because essentially a Group is just a display object, so it has a preUpdate, update and postUpdate too. You can override them, but you must still perform the tasks they currently do.
