### ISSUE TITLE
WP click autorelease problem

### ISSUE THREAD

**Issue by Erik3000** [photonstorm/phaser#1961]
Hello, I found following problem:

running on Nokia Lumia 820 (Windows Phone 8.1 , Internet Explorer)

I created sample program:
```javascript
var game = new Phaser.Game(480, 800, Phaser.CANVAS, '', {create: create});

var txt = null;

function create (){
    game.input.onDown.add(mouseDown, this);
    game.input.onUp.add(mouseUp, this);
    txt = this.game.add.text(100, 100, "hu", {fill: '#FFFFFF'});
}

function mouseDown() {
    txt.setText("mouseDown");
}

function mouseUp () {
    txt.setText("mouseUp");
}
```

it works ok everywhere, so when I touch the screen, "mouseDown" is shown, when I release touch "mouseUp" is shown

but I found problem on mentioned device. When I touch the screen, "mouseDown" is shown - that is OK.
Then I keep finger down, but onUp event is dispatched circa 2 seconds after I touched the screen. So onUp event was dispatched and my finger is still touching the screen.

Do you know where could be problem?

Thanks

**Comment by Cristy94** [comment]
I don't have the device so I can not test, but it seems like this is something your device does: ignore a finger that's on the screen, more like ignoring accidental taps. So, my guess is that your phone's hardware (or software) is actually triggering the end of the touch, thinking that it is a finger accidentally pressing the screen. 

I repeat, I haven't tested/tried it, it's just a guess.

**Comment by Erik3000** [comment]
the same bug happens also on lumia 920,
but the bug happens only in internet explorer, I tested also in UC browser and Project Spartan - there is everything OK

and the problem is also in your example, check the video: https://www.sendspace.com/file/87lqbu

**Comment by pnstickne** [comment]
*May* be related to https://bugs.dojotoolkit.org/ticket/18346

**Comment by photonstorm** [comment]
I'm not sure there is anything we can do about this, sorry - the onUp event comes from the browser, so IE must be sending it at some point. God knows why. Maybe 2 seconds activates an OS gesture? (like touch-hold on iOS does) that triggers it?
