### ISSUE TITLE
every phaser game working in mozilla firefox but not working on Google Crome...

### ISSUE THREAD

**Issue by mvnnn** [photonstorm/phaser#1962]
i use Phaser 2.4.2 "Altara" min.js" links in game. every phaser game working on "Mozilla firefox" but not working on "Google Crome".Google Crome show error (when press "ctrl+shift+j" key) is "YOUR "image/mp3" file is not be loaded"....what should i do ?

**Comment by photonstorm** [comment]
Need to see some code to tell what is going on here. But mp3 files certainly aren't images!

**Comment by mvnnn** [comment]
" THIS SCREENSHOT OF GOOGLE CHROME"...
![screenshot from 2015-08-01 18 01 52](https://cloud.githubusercontent.com/assets/12225578/9021848/80a7749a-3877-11e5-9c13-8becb218cc52.png)

when same code i run on "mozilla firefox"...
![screenshot from 2015-08-01 18 02 03](https://cloud.githubusercontent.com/assets/12225578/9021851/e5684abc-3877-11e5-812e-362d5544a674.png)

**Comment by mvnnn** [comment]
i also download some phaser game from GitHub..i find same issue in every game...the issue is every game working on "mozilla firefox" but not working on "google chrome","Opera".etc...every time i find issue in "phaser.min.js" file.

**Comment by Cristy94** [comment]
This is because you don't have a web server to serve your files. Read this: http://phaser.io/tutorials/getting-started/index
