### ISSUE TITLE
Phaser.Cache.addImage with data parameter not working in Safari

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#1964]
I can't seem to add an image to the cache by creating an image object and setting its src with a base64. It works fine in Chrome but in Safari, the image won't work. Here's my code:

       var key = 'whatever'; 
       var data = new Image();
       data.src = canvasDataURI;
       game.cache.addImage(key, canvasDataURI, data);

        var customizedTile = game.add.image(tileX, tileY, key); // this does not work in safari

I noticed that in game.cache._images, if I look at the image object, it doesn't have a frame data set in safari, though it does in Chrome. I'm not sure if that is a cause of the problem or an effect. And of course if you look at customizedTime.width/height, they are both zero in Safari, but set appropriately in Chrome.

It's pretty rare that you see browsers interpret javascript differently.

**Comment by photonstorm** [comment]
It should only be added to the cache when the image has loaded. In Chrome this is immediately, in Safari it's not. The following from Loader.loadImageTag shows how it should be set-up:

```
        file.data = new Image();
        file.data.name = file.key;

        if (this.crossOrigin)
        {
            file.data.crossOrigin = this.crossOrigin;
        }
        
        file.data.onload = function () {
            if (file.data.onload)
            {
                file.data.onload = null;
                file.data.onerror = null;
                _this.fileComplete(file);
            }
        };

        file.data.onerror = function () {
            if (file.data.onload)
            {
                file.data.onload = null;
                file.data.onerror = null;
                _this.fileError(file);
            }
        };

        file.data.src = this.transformUrl(file.url, file);
        
        // Image is immediately-available/cached
        if (file.data.complete && file.data.width && file.data.height)
        {
            file.data.onload = null;
            file.data.onerror = null;
            this.fileComplete(file);
        }
```
