### ISSUE TITLE
How to access "Object Layer" from Tilemap's json file ?

### ISSUE THREAD

**Issue by mvnnn** [photonstorm/phaser#1970]
i create json file with creating object in Tiled but i don't know how to access object layer in javascript file .

**Comment by Pajamaman** [comment]
Can you be more specific? Maybe post the code?

**Comment by mvnnn** [comment]
please give me link to read...i already create .json file with making object in Tiled but  i don't know how to access object layer in javascript file(in create() function) .

**Comment by mvnnn** [comment]
or give me some code of game in which using above things.

**Comment by Pajamaman** [comment]
Perhaps you mean something like this: http://phaser.io/examples/v2/loader/load-tilemap-json

In that example, the json file is loaded in `preload()` and the TileMap is created is `create()`. Notice line 33:

```javascript
map = game.add.tilemap('mario');
```

In this case, you would access the object properties via `map.propertyName`, replacing "propertyName" with the key you want.
