### ISSUE TITLE
Phaser.ScaleManager#fullScreenChange throws Uncaught TypeError

### ISSUE THREAD

**Issue by mmanlod** [photonstorm/phaser#1972]
The fullScreenChange throws an Uncaught TypeError: Cannot read property 'dispatch' of undefined.

Had looked into the code(2.4.2) and this is still calling the deprecated enterFullScreen and leaveFullScreen.

**Comment by shohan4556** [comment]
you can follow the issue - https://github.com/photonstorm/phaser/issues/1971

**Comment by photonstorm** [comment]
This is fixed in dev.
