### ISSUE TITLE
WebFont Loader

### ISSUE THREAD

**Issue by cloakedninjas** [photonstorm/phaser#1973]
This is feature request. 

After reading http://www.html5gamedevs.com/topic/4225-how-do-you-use-a-webfont-in-phaser-exactly/ and adding my own font loader which looks rather similar I was wondering the feasibility of creating a new Loader helper for WebFonts. I'm happy to develop this but before doing so, I have some questions:

- Would this be a worthwhile addition?
- How would Phaser handle the dependency of [WebFontLoader](https://github.com/typekit/webfontloader)

**Comment by photonstorm** [comment]
I don't really think it's worth merging WebFontLoader into Phaser anywhere. Using it as it stands now is pretty trivial really, and the WebFontLoader code base is massive and frequently updated, almost daily - not something I'd want to have to keep on-top of.

**Comment by cloakedninjas** [comment]
Hmm yeah, ok will close this.
