### ISSUE TITLE
imageData.data from a bitmapData does not contain pixel values

### ISSUE THREAD

**Issue by yahiko00** [photonstorm/phaser#1976]
This issue comes from a [post on the forum](http://www.html5gamedevs.com/topic/16215-cannot-access-imagedatadata-from-a-bitmapdata).

I would like to apply a filter on a picture with a `bitmapData` as a proxy to apply pixel transformations.

The problem comes from the array **`imageData.data`** of a `bitmapData` which is filled with zeros instead of being filled with correct values.

Here is a piece of code to illustrate my issue:

    var originalPic = game.add.sprite(0, 0, 'originalPic');
    var bmd = game.add.bitmapData(originalPic.width, originalPic.height);
    bmd.draw(originalPic);
    
    console.log(bmd.imageData.data); // ==> [0, 0, 0, 0, ...]
    
    var newPic = game.add.image(600, 0, bmd); // Display on screen is okay

Obviously, if I cannot access those data, I would not be able to make any computation on pixels. :/

I came up with a solution by using the **`context`** attribute of a `bitmapData`, instead of using directly the `imageData` attribute.
  
    var originalPic = game.add.sprite(0, 0, 'originalPic');
    var bmd = game.add.bitmapData(originalPic.width, originalPic.height);
    bmd.draw(originalPic);
    var imageData = bmd.context.getImageData(0, 0, originalPic.width, originalPic.height);
    
    console.log(imageData.data); // ==> now contains correct values
    // Here I can call my image processing function
    // ...
    
    var newPic = game.add.image(600, 0, bmd); // Display the processed image

So, `BitmapData.imageData` is quite buggy. I am going to report an issue about this on GitHub.

 Thank you for having read me.

**Comment by photonstorm** [comment]
If you don't call `BitmapData.update` after manipulating it, it won't update the `imageData` property. This isn't done automatically because it's expensive, so you have to call it yourself.

**Comment by yahiko00** [comment]
It works. Thank you for your answer.
The call to `BitmapData.update()` should be mentionned in the documentation so, under the `imageData` entry.
This would have saved me couple of hours understanding where was the problem. ^_^
