### ISSUE TITLE
Phaser with typescript - how to import it as a module?

### ISSUE THREAD

**Issue by markogresak** [photonstorm/phaser#1977]
Hi!
I'm just starting out with Phaser and I'm trying to use with Webpack. I'd like to do something like:

``` js
import * as Phaser from 'phaser';
```
or
``` js
const Phaser = require('phaser');
```

But in definitions, Phaser is not exported as a module. Is it possible to consume Phaser as a module?

**Comment by clark-stevenson** [comment]
This is a bit of a gray zone for me, @photonstorm has been working away on modules last week but I am not sure how it relates to the definitions or if anything needs to change? I have no experience of using modular imports with phaser yet.

**Comment by markogresak** [comment]
The problem was, and still is, with consuming it via webpack's require, which actually expects for phaser to export something and requiring only phaser's file will throw "PIXI is not defined" error.

My current workaround it to just import phaser as usual and assume that it's available on window and don't try to require it.
