### ISSUE TITLE
please add internal json load and parser for phaser 

### ISSUE THREAD

**Issue by pooya72** [photonstorm/phaser#1979]
please add internal json load and parser for phaser .

**Comment by photonstorm** [comment]
Like this you mean?

```
var data = JSON.parse(yourObject);
this.cache.addJSON('yourKey', null, data);
```

**Comment by pooya72** [comment]
or maybe something like this:

`preload:function(){
    
   game.load.json('leveldata','assets/levels/level1.json');
    
},

create:function(){
   leveldata=game.add.json('leveldata');
}`

**Comment by photonstorm** [comment]
Hmm but you can already do this!

What exactly would 'game.add.json' do btw? In your example above it works right now by doing this:

```
game.load.json('leveldata', 'assets/data.json');
..
var data = game.cache.getJSON('leveldata');
```

**Comment by pooya72** [comment]
i never saw 
    game.load.json 
and     game.cache.getJSON but     game.load.text and     JSON.parse(game.cache.getText) this seems better
