### ISSUE TITLE
Scaling the camera breaks checkBounds()

### ISSUE THREAD

**Issue by Adam13531** [photonstorm/phaser#1980]
Phaser version: I took the source from today (8/5/15) and built Phaser.js myself, but this issue has probably existed since [March 6, 2014](https://github.com/photonstorm/phaser/commit/3b2573de9a67eb6e9a066657b617674bd9e4241d).

Repro:
1. [In the "Basic Follow" example](http://phaser.io/examples/v2/camera/basic-follow), simply add `game.camera.scale.set(2);` to the bottom of `create()`.
2. Move the player around with the arrow keys.

Expected result: the camera continues to follow the player.
Actual result: the camera's bounds' `right` and `bottom` properties do not take `scale` into account.

My fix was to compute `boundsRight` and `boundsBottom` based on `scale` in Camera.js:

```javascript
/**
* Method called to ensure the camera doesn't venture outside of the game world.
* @method Phaser.Camera#checkBounds
*/
checkBounds: function () {

    var boundsRight = this.bounds.right * this.scale.x;
    var boundsBottom = this.bounds.bottom * this.scale.y;

    this.atLimit.x = false;
    this.atLimit.y = false;

    //  Make sure we didn't go outside the cameras bounds
    if (this.view.x <= this.bounds.x)
    {
        this.atLimit.x = true;
        this.view.x = this.bounds.x;
    }

    if (this.view.right >= boundsRight)
    {
        this.atLimit.x = true;
        this.view.x = boundsRight - this.width;
    }

    if (this.view.y <= this.bounds.top)
    {
        this.atLimit.y = true;
        this.view.y = this.bounds.top;
    }

    if (this.view.bottom >= boundsBottom)
    {
        this.atLimit.y = true;
        this.view.y = boundsBottom - this.height;
    }

},
```

Other thoughts:
 * This may affect `x` and `y` in addition to the dimensions, but my world starts at (0,0), so I haven't tested that.
 * Perhaps a better fix is to change `this.bounds.right` and `this.bounds.bottom` to reflect `scale`, but I haven't been using Phaser for long enough to determine that (hence why I've filed this bug!).

**Comment by photonstorm** [comment]
This is now fixed in dev.
