### ISSUE TITLE
Make empty tiles load as 'null' instead of as a Tile object with a -1 index

### ISSUE THREAD

**Issue by Preece** [photonstorm/phaser#1982]
My current game has a 300x500 map with 12 layers, leading to almost 2 million possible tiles. After seeing that my game was using nearly 400MB space, I looked into what the cause was. Turns out, empty tiles are actually created as tile objects with a -1 index. After some digging, I found a little evidence that it used to load as null, or some other value, but was changed to actually create a -1 indexed Tile object.

It would reduce memory overhead and loading times significantly if these tiles were not created. I would think for most games, most tile layers are sparse.

I am considering making these changes, but some knowledge first would be helpful. Is there a specific reason that these -1 indexed tiles are created?

Thanks.

**Comment by StealthC** [comment]
I'm interested in that too. :)

**Comment by photonstorm** [comment]
This feature is now available in the dev branch.

**Comment by photonstorm** [comment]
Just to explain - set the value _before_ creating your Tilemap.
