### ISSUE TITLE
Phaser.Text's wordwrap doesn't work with Chinese words

### ISSUE THREAD

**Issue by chaping** [photonstorm/phaser#1986]
There are no spaces between Chinese words,but Phaser splits words by space,so the `wordWrap` and `wordWrapWidth` property have no effect on Chinese.

**Comment by photonstorm** [comment]
Yes sorry about this, I'm not sure of the best way to address it though. How should it wrap words without spaces? I can't pick a number of characters, because that could chop a word entirely in two - what should be done?

**Comment by the-simian** [comment]
I saw this thread while browsing, and I realized I didn't know the answer either. I found this interesting resource though, and i'd like to share : [https://msdn.microsoft.com/en-us/goglobal/bb688158.aspx](https://msdn.microsoft.com/en-us/goglobal/bb688158.aspx)

**Comment by photonstorm** [comment]
Closing as it's a duplicate of #1403
