### ISSUE TITLE
2.4 WebGL problem

### ISSUE THREAD

**Issue by kmilinho** [photonstorm/phaser#1987]
My game was working fine with phaser 2.3 version but now, using 2.4 I have problems with certains spritesheets. That is the console output. I have black squares instead of the spritesheets: 

WebGL: INVALID_VALUE: texImage2D: no canvas
index.html:1 [.WebGLRenderingContext-0BE63D28]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

**Comment by kmilinho** [comment]
I realize that the problem is with adding a new Phaser.Text element, not with spritesheets.

**Comment by kmilinho** [comment]
The error disappeared when I corrected the text style, I was giving
strokeThickness: "4", and the correct way is strokeThickness: 4 (4 as a number, not as string)

**Comment by photonstorm** [comment]
Glad you solved it. Am closing this one off as the docs definitely say to give a number not a string.
