### ISSUE TITLE
scale problem 

### ISSUE THREAD

**Issue by pooya72** [photonstorm/phaser#1988]
http://phaser.io/examples/v2/display/fullscreen-buttons    

      Uncaught TypeError: Cannot read property 'add' of undefined

**Comment by pooya72** [comment]
check here too please.

  http://www.html5gamedevs.com/topic/16266-how-do-i-scale-my-game-in-242/

**Comment by Pajamaman** [comment]
Oops. Ignore 59debd7.

**Comment by pnstickne** [comment]
@Pajamaman For work-in-progress PRs, one good way to cause a changeset to be ignored is to rebase and force push. (Wouldn't want to do this on a finished/merged branch, but it works out pretty well for PR branches.)
