### ISSUE TITLE
Convert TilemapLayer to TileSprite doesn't work in Phaser 2.4.2

### ISSUE THREAD

**Issue by jdnichollsc** [photonstorm/phaser#1989]
Hi guys,

This example worked in earlier versions: http://www.html5gamedevs.com/topic/12994-tilesprite-from-tilemap-and-tilemaplayer/

    this.carreteraMap = this.game.add.tilemap('tileMapName');
    this.carreteraMap.addTilesetImage('tileSetName');
    this.carreteraLayer = this.carreteraMap.createLayer('tileMapLayerName');
    this.carreteraLayer.renderable = false;
		
    this.carretera = this.game.add.tileSprite(this.game.world.centerX, 0, this.carreteraLayer.layer.widthInPixels, this.carreteraLayer.layer.heightInPixels, this.carreteraLayer.texture);
    this.carretera.anchor.x = 0.5;

What is the right way?
Regards

**Comment by Pajamaman** [comment]
Here's a pretty good example: http://phaser.io/examples/v2/box2d/tilemap

If that doesn't help, please post your preload method as well as any error messages from the console.

**Comment by jdnichollsc** [comment]
Hi man, 

This example doesn't help, you're not getting a texture from a TilemapLayer to use with a TileSprite.

The problem is that the console no displays errors, but the TileSprite no shows texture (It appears transparent). 

My example with an old version of Phaser: http://phaser.azurewebsites.net/carrosolar4

Thanks for your response my friend, I stay pending :+1:

**Comment by Pajamaman** [comment]
Looking at menu.js, line 21:

```javascript
this.carreteraLayer.alpha = 0;
this.carreteraIzqLayer.alpha = 0;
this.carreteraDerLayer.alpha = 0;
```

I don't see where you are changing the alpha back to 1 though. Removing these lines, the layers become visible but they're in the wrong position. I guess then it's a matter of figuring out the correct position of each.

btw, I take it you already realized you have to change boot.js to use `scale.updateLayout()` instead of `scale.setScreenSize(true)`?

**Comment by jdnichollsc** [comment]
Ohh man, sorry... that is a very old example.

My last example is the following: http://phaser.azurewebsites.net/carros/

This last example have the code that was placed in my first comment, which does not work on the latest version of Phaser, 2.4.2. (The error to get texture from a layer to a tilesprite)

PD: Sorry for my bad English and yes, I had seen the change setScreenSize by UpdateLayout :dancers: 

Thanks in advance!

**Comment by Pajamaman** [comment]
Dang, I'm not sure. Could it have something to do with this warning?

    Phaser.Tilemap.addTilesetImage: No data found in the JSON matching the tileset name: "street"

**Comment by jdnichollsc** [comment]
No, this isn't related with the error. You can see that load the textures correctly in this old version of Phaser :)

PD: that's my mistake hahaha but it is not a problem, It doesn't affect.

Thanks for your help, is very appreciated. The error can be from Pixi.js, but not sure :/

**Comment by photonstorm** [comment]
There you go - added back in just for you :)

**Comment by jdnichollsc** [comment]
Wowwww amazing! :dancers:
