### ISSUE TITLE
filtered objects with blend mode MULTIPLY are not drawn at all

### ISSUE THREAD

**Issue by wayfu** [photonstorm/phaser#1994]
Here's a repro: http://jsfiddle.net/4o4nxy6n/

**Comment by wayfu** [comment]
Also, I just noticed—it looks as if the sprite becomes slightly transparent when it's blurred and using NORMAL blend mode...

**Comment by photonstorm** [comment]
Interesting. A filtered sprite should completely ignore the blend mode, rather than become invisible.

**Comment by photonstorm** [comment]
Ok this is patched one-way in the dev branch now (i.e. if you set a filter on a sprite that has a blend mode, it will disable the blend mode). However it's still possible to mess it up the other way around (setting a blend mode after enabling a filter). The docs now warn about this though.

**Comment by wayfu** [comment]
Please note that it's really just MULTIPLY that had trouble—ADD and SCREEN worked with filters plus blend mode: http://jsfiddle.net/wvqbachu/

**Comment by photonstorm** [comment]
Fair enough, have updated to remove multiply.
