### ISSUE TITLE
Phaser Js Text tween / yoyo lags only on OSX Safari

### ISSUE THREAD

**Issue by BeFiveINFO** [photonstorm/phaser#1995]
Please try this sample on Chrome, Firefox and Safari. See the difference of how smooth the tweening is done.

http://codepen.io/BeFiveINFO/pen/GJeOmK

For me the tweening with yoyo is not smooth only on Safari though it works okay on Chrome and Firefox.

Is it my code causing the problem or a bug with phaser?

**Comment by pnstickne** [comment]
It is probably simply how WebKit renders the font. There is nothing specific to any browser in the tweening; it merely updates the attribute(s) according to some function and time.

Instead of tweening the font size it may be possible to get better results by changing the object's scale.

**Comment by BeFiveINFO** [comment]
Thank you pnstickne !

>>Instead of tweening the font size it may be possible to get better (or at least more consistent) tweening results by changing the object's scale.
I added the one with scale yo yo tweening as you kindly pointed out.
http://codepen.io/BeFiveINFO/pen/GJeOmK?editors=101

While the fontSize tweening is not smooth, the scale tweening works really well on OSX Safri, even on my old Android.

>>Just one of those darn unpleasant browser differences that arise.
Thank you again for pointing that out. I was not even aware of the "unpleasant browser difference".
