### ISSUE TITLE
Make Phaser.QuadTree independent of physics?

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#1997]
All of the physics systems have their own quad tree implementations built-in for stuff like collision detection. It seems to me that if you were to use the generic implementation, Phaser.QuadTree, it would be in a scenario in which you did not have physics enabled and wanted to take advantage of quad trees without the overhead of physics.

In my case, I am constantly updating the hitArea of each sprite, so I have an easy substitute for sprite.body (i.e. a rectangle which represents the sprite). Since sprite.body is the only physics-related code the quad tree requires, it works just fine if I rewrite all the quad tree methods to use sprite.hitArea instead of body.

If I wasn't auto-updating hitArea, I suppose getBounds would work just as good. If I modified QuadTree to use getBounds instead of body, thereby making it non-physics dependent, would that be something that would be an accepted change? Or maybe add something to detect if the sprite is physics-enabled and if it isn't, use gebounds instead of body? That would probably be optimal. I just want to float this idea before i push anything.

**Comment by photonstorm** [comment]
Thank you for the suggestion. However this will not be implemented in Phaser, so I'm moving this request over to the Lazer feature request list instead. If you wish to submit a PR that isn't massively API breaking and that adds this feature to Phaser then we will consider merging it.
