### ISSUE TITLE
Sprite's onInputUp doesn't fire if off canvas in IE11

### ISSUE THREAD

**Issue by bvargish** [photonstorm/phaser#2000]
I'm sorry to duplicate my post at http://www.html5gamedevs.com/topic/16304-sprites-oninputup-doesnt-fire-if-off-canvas-in-ie11-is-there-a-fix/, but I am getting desperate at this point :(

Essentially, in IE11 if you click on a sprite with onInputDown and onInputUp events, then drag outside of the game and release the mouse, the onInputUp is never fired. I figured out a hack to catch this, but then I have to click on the game once before I can interact with it again. I'm not sure if I can dispatch the onInputDown event with code or whether that would even fix it. Or whether the game is going out of focus and I need to force it back into focus so that first click isn't required.

Is this a Phaser bug? Is there any fix for it?

**Comment by photonstorm** [comment]
Try out the dev branch, you should find this covered now.
