### ISSUE TITLE
switching a p2 body from static or kinematic to dynamic doesn't account for infinite mass

### ISSUE THREAD

**Issue by wayfu** [photonstorm/phaser#2005]
Helping a dude on the forums, I came across this behaviour: static and kinematic bodies automatically get infinite mass. but switching the body to dynamic later doesn't update the mass properties before the next physics update apparently, so if there's gravity on it (for example), the infinite mass leads to infinite force, and that leads to suffering (ie NaN position values).

**Comment by photonstorm** [comment]
It would update the mass and set it to 1, but only if the mass was zero. Anything else would ignore it. It now automatically sets the mass to 1 every time, no matter what value it was before.
