### ISSUE TITLE
isDesktop is false for IE11 on touch screen laptop

### ISSUE THREAD

**Issue by remborg** [photonstorm/phaser#2006]
With Phaser v2.4.2, on Windows8, IE11 on a laptop with touch screen, *game.device.desktop* will return *false*.
The user agent is the following : 
Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; GWX:DOWNLOADED; rv:11.0) like Gecko

I think it comes from the regex in *src/system/Device.js* l.692

**Comment by Cristy94** [comment]
Well, "Tablet PC 2.0;" doesn't sound like desktop :D

**Comment by remborg** [comment]
It's a laptop (asus S551L) not a desktop computer, I just think it should be detected as a desktop computer as it's closer to it than it is to a phone or a tablet.

I think you're right a new category would be nice.

**Comment by photonstorm** [comment]
Hmm yeah it probably should be flagged as a desktop, although it doesn't actually make any different to Phaser internally (the value is there for your use, not Phasers).

**Comment by pnstickne** [comment]
Is this affecting any current functionality?
(If it is, the behavior can be overriden in http://phaser.io/docs/2.4.3/Phaser.Device.html#.onInitialized)

I would personally like to see migration towards less 'categorization' and more features, in part because it avoids .. ambiguity like such.

**Comment by photonstorm** [comment]
Thank you for the suggestion. However this will not be implemented in Phaser, so I'm moving this request over to the Lazer feature request list instead. If you wish to submit a PR that isn't massively API breaking and that adds this feature to Phaser then we will consider merging it.
