### ISSUE TITLE
Game.input - incorrect output (x,y coordinates)

### ISSUE THREAD

**Issue by ParallelUniv3rse** [photonstorm/phaser#2007]
on Phaser 2.4.2 with box2D physics running in Chrome 44.0.2403.130 (64-bit) MAC version I get incorrect x,y coordinates when I log the Input object to console upon clicking a point in game. (Clicking x:320,y:320 yields x:307, y:349, clicking on x:32,y:32 yields x:90, y:351). 

Because of this issue I am unable to drag objects around when I set the world bounds larger than the Game. When i resize the width AND height I am not able to drag at all (I always have a ball on the very bottom left corner of the world). when I keep the height same as Game height I am able to initiate drag, but when I reach around half the width of the game on the x coordinate, the ball starts to lag behind the cursor, the further, the worse. 

When I keep the dimensions of the world same as Game's, I am able to drag just fine, all works well, but logging the Input object still yields the wrong results. 

screenshots below: (points clicked indicated with green dot)
http://i59.tinypic.com/307newo.png
http://i62.tinypic.com/28hk3rm.png

**Comment by photonstorm** [comment]
I need source code really, as I'm not sure if you're reporting a Box2D plugin error or a game scaling error.

**Comment by ParallelUniv3rse** [comment]
Here is the complete source: 
http://pastebin.com/NNB5w1k7
I am not sure how to categorize it either, but when I leave the world to be the same size as the Game (100%, 100%) the issue still persists, so I'd say it is not scale related. 
Thank you!

**Comment by ParallelUniv3rse** [comment]
Is there any progress with this?

**Comment by photonstorm** [comment]
No because the source code is removed. I need a test case, not an entire project. Boil it down to something dead simple, because if it's a proper bug it would manifest even in the most simple of examples. Whereas if the issue is in your game, it will only appear in there.
