### ISSUE TITLE
Hand cursor hovering on button that changes visibility

### ISSUE THREAD

**Issue by ViliX64** [photonstorm/phaser#2011]
I recently noticed that when mouse hovers over a button, the mouse's sprite changes to a hand. That's fine, but when I made the button invisible (whilst still being under the mouse cursor), the hand sprite remained and changed to normal behavior (probably refreshed) only after hovering over other (normal) buttons.

This is particulary annoying when making the button invisible after clicking on it -> the cursor doesnt change back to a normal pointer.

Tested on Chrome and Firefox (both on Ubuntu 15.04, 64bit).

**Comment by Cristy94** [comment]
I think this is the same bug, it got fixed in the dev branch: https://github.com/photonstorm/phaser/issues/1955

**Comment by photonstorm** [comment]
Going to close this issue unless @ViliX64 can confirm it's different to #1955

**Comment by ViliX64** [comment]
Sorry. It's duplicate.
