### ISSUE TITLE
Bug in Tilemap.createFromObjects

### ISSUE THREAD

**Issue by pparke** [photonstorm/phaser#2012]
I think there might be a bug in createFromObjects where it iterates over the objects searching for a matching gid, id, or name.  The variable ```found``` is only set to false once outside of the loop and so if there is a match it will then continue to create a sprite for every object after the match even if those objects don't have a matching gid/id/name.  I've made the changes and tried it out and it seems to work more as expected with ```found``` being set to false at the start of each loop.  

I could make a pull request if this is actually a bug.

**Comment by photonstorm** [comment]
Yup good call - have fixed that method up and optimised it quite a bit now too.

**Comment by pparke** [comment]
Awesome, thanks! :+1:

**Comment by photonstorm** [comment]
Please test it - I've only got a couple of test cases here I can use and there are so many versions of Tiled out there, outputting all kinds of files it would be good to get more coverage.

**Comment by the-simian** [comment]
Thank you, I can confirm this fixes the issue for me as well, I can't wait for you to push this release to npm

**Comment by photonstorm** [comment]
Ok great. I'll be pushing it out this week.

**Comment by pparke** [comment]
Sorry, I didn't see a notification for your last response and Ludum Dare has kept me busy this weekend.  It fixed the issue for me as well.
