### ISSUE TITLE
Not fully implemented Phaser.Cache.addSpriteSheet

### ISSUE THREAD

**Issue by vladkens** [photonstorm/phaser#2017]
Hello, documentation of method `Phaser.Cache.addSpriteSheet` says `frameMax`, `margin`, `spacing` has a default value, but actually values are written as null. For this reason don't draw a sprite created with `addSpriteSheet` method.

See: https://github.com/photonstorm/phaser/blob/master/src/loader/Cache.js#L560

**Comment by photonstorm** [comment]
Fixed in dev.
