### ISSUE TITLE
Errors in Box2D plugin

### ISSUE THREAD

**Issue by jdnichollsc** [photonstorm/phaser#2019]
Hi guys! 

I found errors in the plugin of Box2D...

http://screencast.com/t/4MemHHsm 
http://screencast.com/t/8zCF3FHV11F 
http://screencast.com/t/mH6X2OWhA45
http://screencast.com/t/G8AHnLesJLmT

Thanks

**Comment by photonstorm** [comment]
Closing this as I've checked and they were all fixed in the 1.0.2 release.
