### ISSUE TITLE
DisplayObjects ignore angle attribute

### ISSUE THREAD

**Issue by vladkens** [photonstorm/phaser#2020]
All object which extends `DisplayObject` ignore `angle` attribute after creating object, but `rotation` work done. Example: 

    var game = new Phaser.Game(800, 600, Phaser.AUTO, null, {
        create: function () {
            var text = game.add.text(100, 100, 'TEST', {fill: '#FFFFFF'});
            text.angel = 15; // not work
            // text.rotation = 15 * Math.PI / 180; // work done
        
            var sprite = game.add.sprite(200, 200, 'undefined');
            // sprite.angel = 15; // not work
            sprite.rotation = 15 * Math.PI / 180; // work done
        }
    });

**Comment by vladkens** [comment]
Live demo: http://codepen.io/anon/pen/eNwqYv

**Comment by photonstorm** [comment]
`angle` is a Phaser property. `DisplayObject` is a PIXI level object. You only have access to `rotation` at that level.
