### ISSUE TITLE
Tween can not be restarted after using .stop()

### ISSUE THREAD

**Issue by Cristy94** [photonstorm/phaser#2021]
http://jsfiddle.net/5qzjjegt/9/ - Not working
http://jsfiddle.net/5qzjjegt/10/ - Working

The only difference is that the loop time is longer than the tween time in v10. Am I doing something wrong, or is this a bug?

**Comment by photonstorm** [comment]
From the jsdocs for Tween.stop: `Stops the tween if running and flags it for deletion from the TweenManager.`

Stopping a Tween is the same thing as killing it.

**Comment by Cristy94** [comment]
And how can I stop a tween and restart it afterwards?

If I use the `pause` method I then have to call `resume`, but doing so it makes the tween jump at the end: http://jsfiddle.net/5qzjjegt/11/

A `restart` method would be useful.

**Comment by Cristy94** [comment]
So, a fix, as Tom Atom said in this thread: http://www.html5gamedevs.com/topic/16641-restart-tween/

Is to set `pendingDelete` to false before starting it.
```
scaleTween.pendingDelete = false;
scaleTween.start();
```

This makes the tween re-playable but still jumps to end or has some unexpected behavior: http://jsfiddle.net/5qzjjegt/15/

Notice how the top-left square doesn't go as big as the bottom right one. What other values should be reset?

So, shouldn't be a `Tween.restart()` method be available? If yes, then how would you stop it before without deleting it? (I assume the already implemented `.pause()` will do the job)

If you think that what I'm asking makes no sense please close this issue :)

**Comment by photonstorm** [comment]
It makes sense, but it's still a feature request rather than a bug :)

**Comment by AnderbergE** [comment]
:+1:
I'd be a really nice feature :)

**Comment by photonstorm** [comment]
Thank you for the suggestion. However this will not be implemented in Phaser, so I'm moving this request over to the Lazer feature request list instead. If you wish to submit a PR that isn't massively API breaking and that adds this feature to Phaser then we will consider merging it.

**Comment by BrentStrandy** [comment]
I +1 this feature request if that means anything :)
