### ISSUE TITLE
Reversed Tween.onLoop and Tween.onRepeat events

### ISSUE THREAD

**Issue by vladkens** [photonstorm/phaser#2024]
If create looped tween and subscribe to `onLoop` event then the event will never happen, but tween send `onRepeat` event. Similarly for repeated tween: `onRepeat` event not happen, `onLoop` was dispatched.

Demo: http://codepen.io/anon/pen/aOeyrR
Code:

    function make_tween() {
        var text = game.add.text(100, 100, 'TEST', {fill: '#FFFFFF'});    
        var tween = game.add.tween(text).to({ y: '+50' }, 1000, Phaser.Easing.Bounce.Out);
        tween.onLoop.add(function() { text.text = 'onLoop'; });
        tween.onRepeat.add(function() { text.text = 'onRepeat'; });
        return tween;
    }

    var game = new Phaser.Game(800, 600, Phaser.AUTO, null, {
        create: function () {
            //make_tween().loop().start(); // set text "onRepeat"
            make_tween().repeat(10).start(); // set text "onLoop"
       }
    });

**Comment by photonstorm** [comment]
This is now fixed in dev.
