### ISSUE TITLE
Rope.events bug

### ISSUE THREAD

**Issue by Tarasiuk** [photonstorm/phaser#2030]
I'm trying to bind onInputDown event to the rope object. But it seems like binding works only for sprites, not ropes. You can see my example on github:
https://github.com/Tarasiuk/phaser-issue.git
Orange fish are rope, blue ones are sprites. Ropes don't react on input handler. Input enabled for both. No errors in console. Pretty strange. 
Thank you for attention.

**Comment by photonstorm** [comment]
Going to put this down as a long term feature request, because we don't support input events on ropes (and to be honest aren't likely to anytime soon, sorry).

**Comment by Tarasiuk** [comment]
So, please, at least remove it from your current documentation :-)

**Comment by photonstorm** [comment]
Rope no longer has the InputEnabled component.
