### ISSUE TITLE
Put the keyboard constants in the documentation

### ISSUE THREAD

**Issue by drhayes** [photonstorm/phaser#2031]
To get at them currently, you have to dig in the source. Not the most pressing issue, but inconvenient.

**Comment by beagleknight** [comment]
I have added a PR with your suggestion. The only problem I have detected is now is hard to check the `Phaser.Keyboard` documentation. I could be useful if jsdoc have an option to include a separate section for them.

**Comment by photonstorm** [comment]
Thanks for the PR. This is now resolved with the new KeyCode file.
