### ISSUE TITLE
Phaser 2.4.3 breaks in Safari for Windows

### ISSUE THREAD

**Issue by bvargish** [photonstorm/phaser#2037]
In upgrading to the latest version of Phaser my game breaks in Safari for Windows. I get the following errors:

TypeError: setting a property that has only a getter     phaser.min.js:13

And I get this error every time I click on the console, then back on the game

TypeError: 'null' is not an object (evaluating 'this.mousePointer.reset')     phaser.min.js:13

I did not test on Safari for Mac or other Apple devices, where this problem might also occur.

**Comment by photonstorm** [comment]
Sorry but Safari for Windows is unsupported. This browser hasn't been updated by Apple for years and years, they no longer officially support it, and nor should you. Safari on OSX is fine, as Apple keep it up to date (relatively speaking).
