### ISSUE TITLE
Audio fallback for sounds that fail to completely load [feature request]

### ISSUE THREAD

**Issue by bvargish** [photonstorm/phaser#2038]
Hello!

I'd like to request a feature where if a sound file is found but fails to load (as described here http://www.html5gamedevs.com/topic/16706-ie11-audio-loading-issues/) that a key will still be generated and the audio will be loaded on the fly rather than from memory. This would prevent any Key "sound" not found in Cache errors.

**Comment by photonstorm** [comment]
You mean have a default sound, like there is the __default and __missing images stored as binary data?

**Comment by bvargish** [comment]
Hmmm... I'm not sure how your audio loading mechanism works so I'm not sure how to answer that. What I'm encountering in IE11 is that some sounds start loading, fail for some unknown reason (they aren't always the same sounds or format but larger sounds fail more often) and so a key is never generated. So when I go to play the sound later I get an error. I thought maybe there would be some way to still generate the key so that the sound is loaded on the fly rather than the key not being found. Does that make sense? Another idea would be to add a "try again" mechanism to the preloader for sounds that abort prematurely.

**Comment by bvargish** [comment]
This is curious. Using the Fiddler web debugger it appears that there are multiple requests for the failed sounds already?
![capture](https://cloud.githubusercontent.com/assets/8495905/9523299/50fd19ae-4ca7-11e5-9ba5-de89f4c6ebf1.JPG)

**Comment by photonstorm** [comment]
All file loading is done by the browser, not Phaser. If multiple requests are made for a single file that is under the browsers control, not ours - it also makes a lot of sense, as by default it will download the file header and first few bits of the audio file to inspect it, check the size etc and then probably chunk load the rest of it. Again, this is all out of your control, the browser is doing what the browser wants to do.

If the audio file doesn't load then we can't create a cache entry, so there's no point storing the key. I don't like the idea of trying to download the file again should you try and play a sound with an invalid key because if it didn't download the first time then it's usually pointless trying to download it again.

**Comment by bvargish** [comment]
Understood. Thank you for explaining this to me.

**Comment by bvargish** [comment]
I'm reopening this as bug, because if I use createjs (preloadjs and soundjs) to play my sounds instead of Phaser, I do not have any issues in IE11.

**Comment by photonstorm** [comment]
And if I use Phaser and IE11 all sounds load and play fine in our games. It's not a bug unless you can demonstrably prove it with a test case.

**Comment by bvargish** [comment]
Once the game launches I will provide the test case. Hopefully that will be soon.

**Comment by bvargish** [comment]
I stand corrected! Once I added more sounds the file load errors started showing up. Such a fool was I to think that it wasn't the ever craptacular IE's fault! Sorry for jumping the gun!

If I devise a strategy to deal with this issue and provide some sort of fallback (if even possible) I will post my findings to the other forum. Already I think I minimized the issue by loading the largest sounds first. Sounds aren't failing until 95% of my game is loaded now. Sometimes they all load. If I load all my sounds with listeners first then I should have to worry about issues there so the issue will be minimized.

Thanks again for your time!

**Comment by photonstorm** [comment]
It still shouldn't do it though - what file format are you loading? And are the files super large at all?

**Comment by bvargish** [comment]
I'm loading 26 MP3s with a total file size of 2.8MB.

bump.mp3	28,433
chew.mp3	46,511
click.mp3	11,784
crash.mp3	24,683
end_music.mp3	209,431
hit_ball.mp3	46,220
hit_curb.mp3	32,577
hit_person.mp3	16,171
level_1_music_v2.mp3	416,206
level_1_music_v2_01.mp3	416,206
level_2_music_v2.mp3	416,206
pling.mp3	19,753
siren.mp3	32,273
song1.mp3	313,624
song2.mp3	314,041
song3.mp3	314,041
static_end.mp3	21,724
static_start.mp3	21,307
stop.mp3	21,319
take_another.mp3	61,338
take_a_fry.mp3	37,932
wannafry.mp3	25,939
wannanugget.mp3	23,635
wantsomecandy.mp3	25,363

I moved the most unimportant sounds to the bottom of the loading queue since the load errors are happening there. In changing the order of the sounds, it changes the sounds that bomb, so it doesn't seem specific to certain sounds.

To play sounds I'm now calling a function that checks game.cache.checkSoundKey(key). If that fails, I'm using howler.js to play the sound on the fly. This works most of the time, but not all of the time. Maybe it's an issue with that library, maybe it's yet another issue with IE.
