### ISSUE TITLE
Phaser.Math.midpoint(x1,y1,x2,y2)

### ISSUE THREAD

**Issue by cscott5288** [photonstorm/phaser#2040]
Thought it would be useful to have a function for determining the midpoint between two coordinates. It's a pretty simple formula and has tons of applications for game logic:

function getMidpoint(x1, y1, x2, y2) {

    var midX = (x1 + x2) / 2;
    var midY = (y1 + y2) / 2;

    return [midX, midY];

}

**Comment by pnstickne** [comment]
I personally prefer to do 'less' in the Math util (I had a whack at throwing \@deprecated all over a year ago), especially when such is not complicated to do locally ..

**Comment by photonstorm** [comment]
This exact function is already available in `Line.midPoint`, but I can see it could be useful for Point objects too, and just generally. So I don't mind adding it, because it's already in the code base, but it needs to be added once, in one single place, and then all the other functions can use that one single implementation.

**Comment by qdrj** [comment]
Also there are Phaser.Point.interpolate() and Phaser.Math.linear()
I don't think we need 4th implementation of same thing.

**Comment by photonstorm** [comment]
Yes those two could be merged into one single call, but they don't do the same thing as `midPoint` does.

**Comment by photonstorm** [comment]
Ok I'm going to close this one off. The feature is available already in the Line class and I'm trying to minimise changes to the API.

**Comment by lewster32** [comment]
Just to add, this is also what [Point.centroid](http://phaser.io/docs/2.4.4/Phaser.Point.html#.centroid) returns when passed two points.
