### ISSUE TITLE
game.stage.smoothed = false; not working

### ISSUE THREAD

**Issue by go717franciswang** [photonstorm/phaser#2041]
In this example: http://phaser.io/examples/v2/display/render-crisp#gv, 
uncommenting `//  game.stage.smoothed = false;` didn't pixelate the melon, but `melon.smoothed = false` does pixelate the melon.

**Comment by beagleknight** [comment]
I tried the `antialias` param of the Game constructor and it doesn't work as well.

**Comment by beagleknight** [comment]
Sorry I was mistaken. If you initialize the `antialias` param with value `false` it works well. This param is initializing the `game.stage.smoothed` so it may be related to modifying the param when the game is booted.

**Comment by go717franciswang** [comment]
Thanks man! You are right. When I move `game.stage.smoothed = false` to the preload function, it works fine.
