### ISSUE TITLE
Button sounds ReadOnly, if though you have to set them? (doc bug)

### ISSUE THREAD

**Issue by Cristy94** [photonstorm/phaser#2048]
Why is the **onDownSound** ( http://phaser.io/docs/2.4.2/Phaser.Button.html#onDownSound ) **readOnly** (as well as the rest of the on..Sound) when you have to set it like `button.onDownSound = mySound` ? This confused me.
 Am I missing something?

**Comment by beagleknight** [comment]
I think this is intentional. You need to use the `setSounds` method to set the button's sounds I guess :)

**Comment by photonstorm** [comment]
You should use `setSounds` or if you just want to set one type use `setOverSound` etc.
