### ISSUE TITLE
Queuing multiple identical items in the loader can cause CRC2D TypeError

### ISSUE THREAD

**Issue by tennysonholloway** [photonstorm/phaser#2053]
Error Message: `TypeError: Argument 1 of CanvasRenderingContext2D.drawImage could not be converted to any of: HTMLImageElement, HTMLCanvasElement, HTMLVideoElement, ImageBitmap.`
@ phaser.js:15492  using phaser 2.4.3 at  486c15f 
I am receiving image URLs from a web socket at a very high speed, this was the code that was producing errors:

```javascript
var url = data from websocket //can come in very fast
game.load.image(url, url);
game.load.onFileComplete.addOnce(function (prog, key, success) {
    // function call that eventually did game.add.image(.... key)
});
game.load.start()
```
I think the intended behavior should not be to error out if queuing multiple similar items, or raise an error if you attempt to add to the loader something that is in the load queue. This was my code that mitigated the error (prevents image from being loaded if load.checkKeyExists or cache.checkKeyExists)
```javascript
var url = data from websocket //can come in very fast
if (game.cache.checkImageKey(url) {
    // function call to game.add.image
} else if (game.load.checkKeyExists('image', url) {
    // do nothing (image is loading already)
} else {
    game.load.image(url, url);
    game.load.onFileComplete.addOnce(function (prog, key, success) {
        // function call that eventually did game.add.image(.... key)
    });
    game.load.start()
}
```

**Comment by photonstorm** [comment]
Does the websocket data come in asynchronously? The speed the data arrives is irrelevant, the issue here is almost certainly abusing the way the loader is designed to work.

**Comment by tennysonholloway** [comment]
The error seemingly comes up when 2+ messages from the websocket are received together. I'm not too sure about web socket async - I'm not using web workers or anything, just doing an event callback:
```javascript
socket.onmessage = function (event) {
    //code above
}
```
I guess the error probably happens because I'm doing a game.load.image with the same key and URL as one that's currently being downloaded, and it corrupts somehow?

**Comment by pnstickne** [comment]
Is the same url ever loaded multiple times?
