### ISSUE TITLE
Build/grunt: JSHint code-style features are deprecated

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser#2057]
JSHint is getting out of the code-style business; but I do think it's good to keep with set of generally formatting rules in addition to error/warning detection rules.

> Warning This option has been deprecated and will be removed in the next major release of JSHint. JSHint is limiting its scope to issues of code correctness. 

The JSHint documentation points to JSCS (so it would be JSHint *and* [JSCS](https://github.com/jscs-dev/node-jscs)) although there are other solutions like [ESLint](https://github.com/eslint/eslint) available.

**Comment by photonstorm** [comment]
Going to leave this in place. From what I can tell as long as we stick to a fixed version of JSHint then we should be fine. There's no "modern" JavaScript in Phaser, and Lazer uses ESLint, so all good there.
