### ISSUE TITLE
d.ts inconsistency for GameObjectFactory.js > bitmapText

### ISSUE THREAD

**Issue by ggarek** [photonstorm/phaser#2059]
branch: v2.4.3

[GameObjectFactory.js:423](https://github.com/photonstorm/phaser/blob/v2.4.3/src/gameobjects/GameObjectFactory.js#L423)

has this signature for bitmapText method:
```
 bitmapText: function (x, y, font, text, size, group)
```

But there is different one in typings:
```
bitmapText(x: number, y: number, font: string, text?: string, size?: number, align?: string, group?: Phaser.Group): Phaser.BitmapText;
```

I dont mind to make a PR, but it is not obvious. Since there is new arguments `align: string` in BitmapText constructor, should it be added to factory method in GameObjectFactory?

**Comment by ggarek** [comment]
as for now i just commented it out in phaser typings

**Comment by clark-stevenson** [comment]
Good catch and for some reason it is blowing my mind! 

As you said the BitmapText does appear to accept an alignment property here. 

https://github.com/photonstorm/phaser/blob/dev/src/gameobjects/BitmapText.js#L54

`Phaser.BitmapText = function (game, x, y, font, text, size, align)`

But not here

https://github.com/photonstorm/phaser/blob/dev/src/gameobjects/GameObjectFactory.js#L423

`bitmapText: function (x, y, font, text, size, group)`

@photonstorm  should the `GameObjectFactory` above accept the align param?

**Comment by pnstickne** [comment]
The parameters are already out of sync (due to `group`) so some finagling would have to be done or inconsistency introduced; FWIW, I'm not a big fan of many arguments either ..

**Comment by photonstorm** [comment]
Leave it out of the Factory. It's easy enough to change alignment after the BitmapText has been created - and if you desperately need to align it in the constructor then you can just create an instance yourself outside of the Factory. The Factory method arguments don't need to fully map to the object constructors in all cases, they're just a convenience really.
