### ISSUE TITLE
Text: hitArea and buttonMode - Example 

### ISSUE THREAD

**Issue by ThomasDeutsch** [photonstorm/phaser#2061]
i would like to use a text with a hitArea as a button.

Two issues i have with my code:
- no buttonMode behavior visible
- hitArea coordinates are not the debug-visible hitArea coordinates.
  how can i make the actual hitArea visible?

[see my fiddle example](https://jsfiddle.net/J5fUE/199/)
```js
var clickfn = function() {
    console.log("click!");
}

var create = function (game) {
    var text = game.add.text(20, 20, "click me, i am a button");
    var hitRect = new Phaser.Rectangle(15, 10, 300, 50);
  	text.hitArea = hitRect;
    text.inputEnabled = true; 
    text.buttonMode = true;
    text.events.onInputDown.add(clickfn);
    
    // hitArea debugging
    game.debug.geom(hitRect, "rgba(100,50,20,0.2)");
}

var game = new Phaser.Game(400, 490, Phaser.AUTO, 'game_div', {create: create}, true);
```

**Comment by photonstorm** [comment]
There is no `buttonMode` property, so you'll need to create your own Button wrapper that does what you need. You can debug the hitArea by rendering it as you're doing, just remember to apply the parent coordinates as well.
