### ISSUE TITLE
button.events.onInputOver doesn't fire for a short while after clicking on canvas.

### ISSUE THREAD

**Issue by VincentMeier** [photonstorm/phaser#2062]
After you click anywhere on the game canvas for short while you can move the mouse over a button and onInputOver won't fire and the button won't change to the 'over' frame.

This is even the case with very simple code, with nothing special coded into the buttons. 
For example I used this demo http://phaser.io/examples/v2/buttons/action-on-click and made a short video with clicking audio cues to demonstrate the problem.
https://youtu.be/F_L6-UkeX0A

**Comment by pnstickne** [comment]
Verified Chrome and Firefox in Phase 2.4.3

**Comment by VincentMeier** [comment]
Judging by the comment next to j27cai's fix
```
//  If the Pointer was only just released then we don't fire an over event
```
This functionality was implemented intentionally? If so, why?
Feel free to correct me, if I'm missing something. I'm pretty new to github, and how all these commits, fixes and other features are a bit confusing to me atm.

**Comment by pnstickne** [comment]
AFAIK there was a fix for/relating to this a year ago or so .. but the details as to what the ultimate issue at the time was.

I do believe that investigating *why* the just-pressed check is in there needs to be done as a cursory check. It is a 'back-off guard', but as to what or why, I don't know.

**Comment by pnstickne** [comment]
I haven't been able to find out *why* this would be needed. It was added in a "JSDoc fixes" (being not too helpful a category), https://github.com/photonstorm/phaser/commit/96fd0ade

**Comment by VincentMeier** [comment]
So any ideas what's the next course of action? ATM this issue makes the UI of my game feel buggy. I have a system that shows what a menu button does when the player moves the mouse over it. Also the player doesn't have to move the mouse between buttons very quickly, like I demonstrated in the video. Just casual clicks and movement still fall in this .justReleased range.

The game is still in development, but would be nice to know if I have to consider some other UI library or if this issue will be addressed some time in the future.

**Comment by pnstickne** [comment]
@VictorBjelkholm If it were me I'd monkey-patch the method to remove the check and move on.

 Most every framework/library has issues and edge-cases that need a little love. Thankfully this scenario - aided by the fact it's JavaScript and object properties are used - is easy to work around until when (if) a more universal change is committed.

**Comment by VincentMeier** [comment]
Dunno who this VictorBjelkholm character is, but thanks for the advice. Never have tried tinkering with other peoples code, but I guess it's never too late to start.

Will keep the issue open for now since it's still present in phaser and we might get some more info down the line.

**Comment by pnstickne** [comment]
@VincentMeier Auto-complete fail :}

**Comment by photonstorm** [comment]
With this fix now merged are we good to close this issue off?

**Comment by VincentMeier** [comment]
I guess so. Thanks for all the help.
