### ISSUE TITLE
One physics body shared by multiple sprites

### ISSUE THREAD

**Issue by zukkun** [photonstorm/phaser#2063]
I want to let multiple sprites to share ONE physics body.
But, Phaser.Group does not have that feature.
I think that creating Phaser.Sprite without texture is wrong way.

Thank you.

**Comment by Cristy94** [comment]
You can add multiple sprites as children of Phaser.Sprite and apply the body to the parent sprite. Is this what you want?

**Comment by zukkun** [comment]
@Cristy94
Thank you for your reply.
I can resolve my problem by its way.
But, Creating Phaser.Sprite without texture as parent that called "Sprite" I feel bad knowhow and last resort.
If it only way, I have no choice.

**Comment by pnstickne** [comment]
@zukkun Currently creating a Sprite (without a texture) is the best way to create a 'full featured game object', including support for collisions.

**Comment by zukkun** [comment]
@pnstickne Thank you for your reply.
I will try create a Sprite (without a texture).

But, I feel a sense of discomfort.
That is referred to as the "drink" the cup that does not contain drink.
