### ISSUE TITLE
Reverse graphic.arc drawn incorrectly

### ISSUE THREAD

**Issue by Chockyegg** [photonstorm/phaser#2064]
Not possible to draw a full circle (0-360º) when reverse=true

Forum thread here:
http://www.html5gamedevs.com/topic/16947-reversed-graphicarc-bug/

Also visible in this official example:
http://phaser.io/examples/v2/display/arc-details

**Comment by photonstorm** [comment]
Yup it's a bug in Pixi 2. I'm not convinced there's an "easy" fix for it, but haven't had time to look properly yet.

**Comment by photonstorm** [comment]
Fixed in dev via new segments argument.
