### ISSUE TITLE
Memory leak in Phaser.Sound using WebAudio

### ISSUE THREAD

**Issue by Pappa** [photonstorm/phaser#2066]
There is a memory leak caused by a reference to AudioBufferSourceNode not being freed after a sound is played. This results in the listener count increasing over time and not being cleaned up. I've reproduced this on Chrome in Windows 7 and Chrome on OSX.

I've been able to fix the issue using the following modification to Phaser.Sound:

    onEndedHandler: function () {
        
        this._sound.onended = null;
        this.isPlaying = false;
        this.stop();

    },

**Comment by pnstickne** [comment]
I'm not quite sure I see how this can lead to a 'growing' memory leak..

**Comment by pnstickne** [comment]
Merge pull #2069

**Comment by photonstorm** [comment]
Closing this as it's covered by your merged PR from yesterday.
