### ISSUE TITLE
Broken Example 

### ISSUE THREAD

**Issue by Mourtz** [photonstorm/phaser#2067]
It just doesn't seem to work for me.
Check it [here](http://phaser.io/examples/v2/filters/pixelate)

**Comment by pnstickne** [comment]
Throws "Uncaught TypeError: c.Filter[a] is not a function" on Phaser 2.4.3

**Comment by pnstickne** [comment]
@Mourtz Make sure to include as many details as possible, including the example name as part of the title.

**Comment by Mourtz** [comment]
Didn't know that there was a different repo for the examples on the site. However, it doesn't seem like a big deal. Btw, it works if you use the given cdn link to the shader code instead of loading the file locally.:laughing:

**Comment by pnstickne** [comment]
Hmm. I've run into that problem on another example.
It might be a more widespread .. issue :}

**Comment by photonstorm** [comment]
Yup it's on the (very long and tedious) list of things to sort out on the web site.
