### ISSUE TITLE
multiple text strokes feature request

### ISSUE THREAD

**Issue by bvargish** [photonstorm/phaser#2074]
It would be cool to be able to apply multiple strokes to text. Something like:

text.multiStroke(['#ff0000', 6], ['#ffff00', 12]);

It would automatically sort the layers by thickness so they are rendered in the correct order.

I'm wondering if this can be done already, but didn't see anything in the text examples.

**Comment by pnstickne** [comment]
This seems too specialized..

..but a little example of such an a effect be neat.

**Comment by bvargish** [comment]
Hi pnstickne,

This is actually a common text treatment for my client. I am using it for level names in my game. Currently I have to cut this as a graphic, but if I had this capability I could use text.
![capture](https://cloud.githubusercontent.com/assets/8495905/9773581/1c22662a-5711-11e5-8fa4-5587517d39a4.JPG)

Here is the client using the technique:
![5 reasons tiger banner](https://cloud.githubusercontent.com/assets/8495905/9773598/384f32a6-5711-11e5-8cf2-c6d60911ca7d.png)

Here are some examples from a Google image search.
![three-strokes](https://cloud.githubusercontent.com/assets/8495905/9773608/4546fe6c-5711-11e5-90f2-4aa225211bae.gif)
![freebie](https://cloud.githubusercontent.com/assets/8495905/9773611/49a87878-5711-11e5-9d84-4fb4ec536450.jpg)
![step12](https://cloud.githubusercontent.com/assets/8495905/9773618/505fb9f6-5711-11e5-9a57-a3de5706aa00.jpg)
![outlineb4](https://cloud.githubusercontent.com/assets/8495905/9773620/52276108-5711-11e5-9c99-dc418a39d76b.png)

Anyway, I think it would be a cool feature that I'm guessing wouldn't be too difficult to implement.

**Comment by photonstorm** [comment]
Actually I don't think it's possible to implement at all. Strokes on Text elements are handled by the Canvas API itself, and they certainly have no support for multi-strokes in there. Which means it would need coding specifically, and is never going to look as good as Photoshop can manage it.

**Comment by bvargish** [comment]
Bummer. Yeah, I had just edited my comment after scrutinizing the images more closely. Many of them require touching up in Photoshop to get the final effect.

**Comment by photonstorm** [comment]
You can use a drop shadow and a stroke together, which with the right settings allows for a double layer outline at least - but it's never as precise or smooth as the images posted above.

**Comment by nickryall** [comment]
@bvargish I've got around this in the past by having two text objects layered on top of one another. The text object at the back has a larger stroke which shows around the sides. It's not perfect but can work in some cases.

**Comment by bvargish** [comment]
That works pretty well actually! I had to re-align the text layers based on the stroke thickness, but due to the fraction pixel issue the layers are slightly off unless using all odd or even numbers. So instead of 14, 9 here I'd have to use 14, 10 or 15, 9 to make it perfect. It doesn't exactly match my original graphic, but pretty darn close.

var myText = multistroke('ANTSY ANTICS', '20px bpreplaybold', '#FFF', ['#000', '#a8bf38'], [14, 9]);
myText.x = 100;
myText.y = 100;
levelSelect.add(myText);

function multistroke(chars, font, fill, stroke, strokeThickness) {
	var multistroked = game.add.group();
	for (var i = 0; i < stroke.length; i++) {
		var text = game.add.text(-strokeThickness[i] / 2, -strokeThickness[i] / 2, chars, {
			font: font,
			fill: fill
		});
		text.stroke = stroke[i];
		text.strokeThickness = strokeThickness[i];
		multistroked.add(text);
	}
	return multistroked;
}

**Comment by bvargish** [comment]
Oh duh, nevermind. I forgot that I was rounding pixels by doing this:
game.renderer.renderSession.roundPixels = true;

**Comment by photonstorm** [comment]
I'm going to close this off. It's not a feature I think is vital enough to include in the core, and looks like it can be resolved with a little creative coding re: above.

**Comment by bvargish** [comment]
See http://www.html5gamedevs.com/topic/17730-multistroked-text-function/ for my final function.
