### ISSUE TITLE
Re-hovering over a pressed button goes to 'Hover' state; expecting 'Down'

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser#2077]
Per http://phaser.io/examples/v2/buttons/action-on-click - Phaser 2.4.x

- Click on the button and keep the mouse button pressed.
  - The button shows 'down' - GOOD
- Move the mouse off the button
  - The button image shows 'out' - OKAY, but confusing if `isOver` not checked in click-action/onUp callback. (But I think this is a separate issue.)
- Move the mouse back on the button.
  - The button image changes to 'over' - NOT EXPECTED. The button should go back to the 'down' state as the mouse/pointer is still down.

**Comment by pnstickne** [comment]
Hr, hr. The UI is a bit different on most Touch UIs; in these cases moving off the button in the native browser UI appears to be the same as considering the pointer to be released.

**Comment by pnstickne** [comment]
Okay, the latest PR adds and option that defaults to 'mouse like behavior' or 'touch like behavior', depending on pointer.

It now works as expected for a mouse input; and arguably works as expected for a touch input, mirroring 'native' browser button types.

**Comment by photonstorm** [comment]
Closing (as fixed in your own PR)
