### ISSUE TITLE
Button "action" should only fire by default is the pointer is Over the button

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser#2079]
The Button exposes an `onUp` event with an `isOver` parameter. The user must manually check `isOver` to determine if the "click was real". This is confusing at least.

Proposal:

- Add an `onClick` event that will only fire when the "up" occurs over the button. The `onUp` would still be fired to avoid breaking changes.

- A minor breaking change would be the callback/context supplied to the constructor as these would be wired to the `onClick` event. (I am not a fan of their usage to begin with..)

**Comment by pnstickne** [comment]
FWIW, the use of checking `isOver` will also produce false-positives as the pointer may be released over the button even though the button was never pressed (ie. it is only 'overed').

**Comment by photonstorm** [comment]
Closing off (as you fixed it in your PR).
