### ISSUE TITLE
Button.onOverMouseOnly should default to true for more consistency

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser#2083]
Touch input (periodic) does not work like continuous mouse input - and touch devices are only become more popular.

Having this default to true (it is currently false) makes for a more 'native' default feel, as expressed in native UI buttons on such devices.

It would be a minor breaking change, but I can't imagine very many buttons on touch devices relying on an Over state..

**Comment by photonstorm** [comment]
Done.
