### ISSUE TITLE
forceSetTimeOut broken in 2.4

### ISSUE THREAD

**Issue by satan6** [photonstorm/phaser#2087]
Example: http://codepen.io/anon/pen/epJdbo?editors=101

When using forceSetTimeOut the game basically runs in slow motion, like the 1000ms tween in the example taking ~3000ms for me in Chrome. In Firefox it jerks around and takes ~1500ms.

When going back in versions it still worked fine in 2.3.0.

**Comment by photonstorm** [comment]
True - fixed in dev.
