### ISSUE TITLE
Bug in Phaser.Timer w/r/t game.time.slowMotion

### ISSUE THREAD

**Issue by drhayes** [photonstorm/phaser#2088]
Here's a test-case: http://jsbin.com/nutavu/edit?js,output

There's an effect in my game where the player can make the game run in slow motion. I just recently added gargoyles that fire a number of fireballs after a delay.

When the game is running in slow motion the timer doesn't take it into effect, so my fireballs stack up a lot closer than they did without it.

**Comment by photonstorm** [comment]
Hmm this is an interesting one. Part of me thinks that if you ask a Timer to last 4 seconds, it should last 4 seconds regardless. But at the same time it makes sense it should honour `slowMotion` too. I can see cases where both are equally desired outcomes, one neither better than the other.

**Comment by drhayes** [comment]
It's why I hesitated posting this as a bug, yeah. Like tweens, maybe, four seconds is four seconds. But it is kinda annoying. :)

**Comment by photonstorm** [comment]
It's like say you got an in game power-up that gave you slow motion for 3 seconds. You'd need a non Phaser Timer to calculate the expiration of the power-up (especially if you tweened the slowMotion value to make the game ease into and out of slow motion). Like I said, I half agree with you and can equally see the need to not 'fix' it. At the very least it should be in the docs though.

**Comment by pnstickne** [comment]
This is 'correct' behavior because time.event is real-world (wallclock) time, not physics time.

The documentation isn't always the best at the making the delineation.

**Comment by pnstickne** [comment]
Example: http://jsbin.com/ditecudewi/edit?js,output

**Comment by drhayes** [comment]
Works for me. :+1:

**Comment by pnstickne** [comment]
Alternatively, because tweens run in *physics time*, a tween (with a 'dummy object') could be created and the event can be handled.

**Comment by photonstorm** [comment]
Forgot to close this one, docs update has been merged. Bingo.
