### ISSUE TITLE
TypeError: Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by brenolf** [photonstorm/phaser#2092]
When I am in a state where a create a TileSprite and immediately sets is visibility to false and then I try to call `game.state.start('game', true, false, this.data);` I get the title error.

Interestingly, if I toggle the visibility of the TileSprite, the error is not thrown. I'm using Phaser v2.4.3, and this didn't happen on v2.4.2.

**Comment by pnstickne** [comment]
If possible, please create a minimum (runnable) demonstration case on jsbin or via the Phaser sandbox.

**Comment by brenolf** [comment]
[Here](https://jsbin.com/jurewipoho/edit?html,js,output) is an example of the bug. Note that if you change the CDN version for 2.4.2 the bug doesn't happen anymore.

**Comment by pnstickne** [comment]
Thanks for the example case.

'cause' is PIXI.TilingSprite.prototype.destroy does not check it's canvasBuffer .. was introduced in 50516e3d342e7faeb86ddf936f60a63ebb1ca7e1

**Comment by photonstorm** [comment]
Thanks for the report. Now fixed in dev branch.
