### ISSUE TITLE
Game isBooted as event

### ISSUE THREAD

**Issue by katywings** [photonstorm/phaser#2094]
Hey there ^.^

I'm currently fighting with this problem:
Trying to show a enable-fullscreen Button (in a gui outside of the game) only, when the Browser has compatibility for fullscreen. Now after instantiating the game, `game.scale` is still undefined. How can I head of the moment when the ScaleManager (`.scale`) is available without using `setTimeout`? Is there any event? I could only find `isBooted` which isnt an event :D...

In advance, thx a lot for your advice!

Cheers :D

**Comment by pnstickne** [comment]
It's a little bit obscure, but I added in support a while back - see [Device.onInitialized](http://phaser.io/docs/2.4.3/Phaser.Device.html#.onInitialized).

**Comment by katywings** [comment]
Haha okay :) fair enough, thats a solution :), i will try it out! Thank you for the fast and detailed answer!

When I think about it,

**Comment by katywings** [comment]
Sry i am on mobile:

Answer part 2:
Your info should be added to the fullscreen examples :)

And oh well this should be a new issue but:
The example does not work:
http://phaser.io/examples/v2/display/fullscreen-buttons

(will add this to a new issue later)

**Comment by pnstickne** [comment]
Yes, the demo uses old signal handlers have been deprecated and since removed.

It will against older versions of Phaser such as 2.3.1.

There was an issue/pr open for it somewhere (I think on https://github.com/photonstorm/phaser-examples) but I cannot find it.

**Comment by katywings** [comment]
Okay okay :), `device.fullscreen` helped!

Thank you!
