### ISSUE TITLE
No sound on ios 9

### ISSUE THREAD

**Issue by MyCatCarlos** [photonstorm/phaser#2095]
No sound on ios 9 (safari and chrome). Tested with phaser audio examples (2.4.3) and own game (2.3.0).

**Comment by Cristy94** [comment]
What format of audio files do you use? Does it work in iOS 8?

**Comment by MyCatCarlos** [comment]
mp3-files, it worked on ios 8.4.1

**Comment by photonstorm** [comment]
Any errors in the console when it tries to play them? (You can see this if you hook an iOS device to a Mac and run Safari in debug mode). If it's trying to hit a Web Audio API that no longer exists then we'll need to fix this of course.

**Comment by MyCatCarlos** [comment]
No errors in console while remote debugging (tested with audio demo's 'fade in' and 'loop')

**Comment by photonstorm** [comment]
Hmm - how about using something other than an mp3? An m4a perhaps (proper Apple native format). Would rule that out at least.

**Comment by photonstorm** [comment]
This is now fixed in dev. Sodding Apple.

**Comment by MyCatCarlos** [comment]
Thanks !

**Comment by Cristy94** [comment]
So I guess this is because of 3D Touch/force touch? Now the touchstart won't trigger events as before? Won't this affect/break other things too in Phaser?

**Comment by photonstorm** [comment]
According to the issue in the webkit bug tracker it looks like a regression rather than done on purpose.
