### ISSUE TITLE
Phaser.ScaleManager#getParentBounds not return the correct Parent size/bounds value (See my solution please)

### ISSUE THREAD

**Issue by jdnichollsc** [photonstorm/phaser#2098]
Hi guys,

**See my explanation:** http://www.html5gamedevs.com/topic/17270-phaserscalemanagergetparentbounds-not-return-the-correct-parent-sizebounds-value/

You need change 

```
var clientRect = parentNode.getBoundingClientRect();
bounds.setTo(clientRect.left, clientRect.top, clientRect.width, clientRect.height);
```

for
```
var clientRect = parentNode.getBoundingClientRect();
var parentRect = parentNode.offsetParent.getBoundingClientRect();
bounds.setTo(clientRect.left - parentRect.left, clientRect.top - parentRect.top, clientRect.width, clientRect.height);
```

Because if the parent have any transforms you wanted to get it relative to it's parent.
Please see the link: http://stackoverflow.com/questions/23891892/how-do-i-get-the-actual-values-for-left-right-top-bottom-of-an-absolutely-positi 

**What do you think?**

**Regards, Nicholls**

**Comment by pnstickne** [comment]
http://stackoverflow.com/a/23891934/2864740 - the answer seems to indicate getBoundingClientRect already takes the bounds into account.

**Comment by jdnichollsc** [comment]
You can run my example from this codepen: http://codepen.io/jdnichollsc/pen/yYJOOx

When you open the side menu, the canvas has a different width of the parent element

Thanks in advance :)

**Comment by photonstorm** [comment]
Closing as this was merged ages ago.
