### ISSUE TITLE
Webfonts italic styling not working

### ISSUE THREAD

**Issue by katywings** [photonstorm/phaser#2100]
Problem:
Italic styling does not work.

Example: 
- Go to http://phaser.io/examples/v2/text/google-webfonts#gv
- Change to webfonts loader to:

        google: {
          families: ['Open Sans:n,b,i,bi']
        }

- Change `font` to `Open Sans`
- Add `text.fontStyle = 'italic';`

**Comment by katywings** [comment]
Got it working:
For italic styling there needs to be some italic text with the wished font family in the body (before the Phaser script).

**Comment by photonstorm** [comment]
Yeah that's the same for nearly all web fonts. They are temperamental as hell.

**Comment by lukaMis** [comment]
Hi

Is there any working example of this hack in action? I tried to put Open Sans in body with italic and it still does not work inside Phaser game.

**Comment by katywings** [comment]
Can you please send your Javascript Code for webfonts?

(The object with the families)

**Comment by lukaMis** [comment]
Hi

We generated our own version of webfont from Open Sans using webfont-generator from http://www.fontsquirrel.com/tools/.

We are using it in css with no problem (code below):
```
@font-face { font-family: "Open Sans"; src: url("../fonts/Open_Sans/OpenSans-Italic.eot"); src: url("../fonts/Open_Sans/OpenSans-Italic.eot?#iefix") format("embedded-opentype"); src: url("../fonts/Open_Sans/OpenSans-Italic.woff") format("woff"), url("../fonts/Open_Sans/OpenSans-Italic.ttf") format("truetype"), url("../fonts/Open_Sans/OpenSans-Italic.svg") format("svg"); font-style: italic; font-weight: 400; }

@font-face { font-family: "Open Sans"; src: url("../fonts/Open_Sans/OpenSans-Regular.eot"); src: url("../fonts/Open_Sans/OpenSans-Regular.eot?#iefix") format("embedded-opentype"); src: url("../fonts/Open_Sans/OpenSans-Regular.woff") format("woff"), url("../fonts/Open_Sans/OpenSans-Regular.ttf") format("truetype"), url("../fonts/Open_Sans/OpenSans-Regular.svg") format("svg"); font-style: normal; font-weight: 400; }

@font-face { font-family: "Open Sans"; src: url("../fonts/Open_Sans/OpenSans-BoldItalic.eot"); src: url("../fonts/Open_Sans/OpenSans-BoldItalic.eot?#iefix") format("embedded-opentype"); src: url("../fonts/Open_Sans/OpenSans-BoldItalic.woff") format("woff"), url("../fonts/Open_Sans/OpenSans-BoldItalic.ttf") format("truetype"), url("../fonts/Open_Sans/OpenSans-BoldItalic.svg") format("svg"); font-style: italic; font-weight: 700; }

@font-face { font-family: "Open Sans"; src: url("../fonts/Open_Sans/OpenSans-Bold.eot"); src: url("../fonts/Open_Sans/OpenSans-Bold.eot?#iefix") format("embedded-opentype"); src: url("../fonts/Open_Sans/OpenSans-Bold.woff") format("woff"), url("../fonts/Open_Sans/OpenSans-Bold.ttf") format("truetype"), url("../fonts/Open_Sans/OpenSans-Bold.svg") format("svg"); font-style: normal; font-weight: 700; }

@font-face { font-family: "Open Sans"; src: url("../fonts/Open_Sans/OpenSans-LightItalic.eot"); src: url("../fonts/Open_Sans/OpenSans-LightItalic.eot?#iefix") format("embedded-opentype"); src: url("../fonts/Open_Sans/OpenSans-LightItalic.woff") format("woff"), url("../fonts/Open_Sans/OpenSans-LightItalic.ttf") format("truetype"), url("../fonts/Open_Sans/OpenSans-LightItalic.svg") format("svg"); font-style: italic; font-weight: 300; }

@font-face { font-family: "Open Sans"; src: url("../fonts/Open_Sans/OpenSans-Light.eot"); src: url("../fonts/Open_Sans/OpenSans-Light.eot?#iefix") format("embedded-opentype"); src: url("../fonts/Open_Sans/OpenSans-Light.woff") format("woff"), url("../fonts/Open_Sans/OpenSans-Light.ttf") format("truetype"), url("../fonts/Open_Sans/OpenSans-Light.svg") format("svg"); font-style: normal; font-weight: 300; }
```

**Comment by katywings** [comment]
I will do some tests, when i'm at the computer ;)

**Comment by katywings** [comment]
Okay I tried some things and maybe I found the problem:
Can you please try using the following:

    var textStyleItalic = {
        font: 'Open Sans',
        fill: '#000000', 
        align: 'center',
        fontStyle : 'italic',
        fontSize : 40,
        fontWeight : 'normal'
    };

**Comment by pnstickne** [comment]
Only 0 is allowed in CSS without a unit.

**Comment by katywings** [comment]
Yeah with css you are right but that is javascript - phaser.io code and not css ;)

Von meinem Sony Xperia™-Smartphone gesendet

---- pnstickne schrieb ----

**Comment by lukaMis** [comment]
There is no difference between these: 
Italic does not work:
```
 var textStyleItalic = {
    font: '40px Open Sans',
    fill: '#000000', 
    align: 'center',
    fontStyle : 'italic',
    fontWeight : 'normal'
  };
```
```
 var textStyleItalic = {
    font: 'Open Sans',
    fill: '#000000', 
    align: 'center',
    fontStyle : 'italic',
    fontSize : '40',
    fontWeight : 'normal'
  };
```
```
 var textStyleItalic = {
    font: 'Open Sans',
    fill: '#000000', 
    align: 'center',
    fontStyle : 'italic',
    fontSize : '40px',
    fontWeight : 'normal'
  };
```

**Comment by katywings** [comment]
That's very very strange :), in my "test environment" I could fix the problem with the explained solution.

Hmm... Maybe I can't solve the problem directly for you, but give a tip:

We need to decrease the range of the problem, that said, does your Phaser font code work when you use Google Webfonts and Open Sans from there?
When that works we know that the problem lies in the css...

And a second tipp: when you browse your site and open the console, does inspecting the hidden italics text really show you the Open Sans font in the active css?

And a third tipp: Where is your Phaser App defined? It's should be at the end of the file. Can you also please try, wrapping the Phaser set text / style code in a SetTimeout with 5000ms or so?

---- Luka Mis schrieb ----

**Comment by lukaMis** [comment]
@katywings 
I got it working. I edited my previous post with solution.

**Comment by katywings** [comment]
No problem, you're welcome! :)
