### ISSUE TITLE
Quadtree Collision Infos example fails to load

### ISSUE THREAD

**Issue by ekulabuhov** [photonstorm/phaser#2101]
Hi guys,

Tried to open this example:
http://phaser.io/examples/v2/arcade-physics/quadtree---collision-infos

But all it shows isL "// Opps - Failed to load js file" and a black screen.

**Comment by pnstickne** [comment]
This is an issue with reverse name-mappings in the example site that occurs (sometimes) when there is a dash in the name.

Ref. https://github.com/photonstorm/phaser-examples/issues/117

**Comment by photonstorm** [comment]
Closing as this is handled in the phaser-examples repo.
