### ISSUE TITLE
Warning "Not implemented createElement: video" in Phaser 2.4.X

### ISSUE THREAD

**Issue by CastellviElsAltres** [photonstorm/phaser#2104]
I posted this on html5gamedevs, but no one seems to be able to help me so I will post it here.

Original post:
Hello, I just updated my project to the brand new Phaser 2.4.3, and as soon as I execute my game, even before it finishes loading my main menu, it throws me this warning: "Not implemented createElement: video" (See attached image).
 
What does this mean? Is it some bug of this version or do I have a probem with my code? I don't have any element named "video" in my code.
 
My game is rendered using Phaser.CANVAS.

![](http://www.html5gamedevs.com/uploads/monthly_09_2015/post-11634-0-09574100-1441703838.png)

Update:
I tried with versions from 2.4.0 to 2.4.3 and all of them gave me the same warning.
I am using phaser by loading the phaser.min.js and phaser.map files.

Thanks.

**Comment by photonstorm** [comment]
Are you loading a video? The only reason that message could appear is if the Phaser Loader tries to load a video file.

**Comment by CastellviElsAltres** [comment]
Nope, not a single video, the only assets I have are ".png" sprites and some ".ogg" aufio files. Nothing more.

In my preload and load files, a just load the following resources:
game.load.image()
game.load.spritesheet()
game.load.audio()
game.load.atlasJSONHash()

Thank you.

**Comment by photonstorm** [comment]
One of your files, I have no idea which as I can't see them, is being treated as a video. There is only one place in the Loader that `createElement('video')` is called and that's in `loadVideoTag`. I need to see your code running somewhere to debug this any further.

**Comment by photonstorm** [comment]
Either that, or you're running under some kind of special wrapper (Cocoon?) or browser that scans the Phaser source and throws a warning about things it doesn't support.

You won't see this in 2.3 because we didn't support videos at all in 2.3.

**Comment by CastellviElsAltres** [comment]
Yes I'm running under cocoonjs, is that the issue?

**Comment by photonstorm** [comment]
I reckon this is just Cocoon mis-diagnosing the Device class. If you're not using Video, then don't worry.
