### ISSUE TITLE
Follow on children of a group where the group position isn't [0, 0]

### ISSUE THREAD

**Issue by rbozan** [photonstorm/phaser#2106]
When you game.camera.follow on a child of a group where the group position does not start at [0, 0], the camera follows the wrong position, because the child x and y are just offsets relative to the group.

**Comment by pnstickne** [comment]
Probably also wrong for other kinds of transformations. Probably just need to normalize around world space transforms.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
