### ISSUE TITLE
Sprite.getBounds innacurate when sprite is scaled with negative values

### ISSUE THREAD

**Issue by DavidAPC** [photonstorm/phaser#2108]
Say you've an image loaded, then:

    var testSprite = game.add.sprite(200,0,"test")
    testSprite.getBounds()
    ---> Object { x: 200, y: 0, width: 300, height: 300, type: 22 }
    testSprite.scale.x = -1;
    testSprite.getBounds()
    ---> Object { x: 200, y: 0, width: 300, height: 300, type: 22 }

The getBounds() should be returning the x as being -100, since being scaled negatively should make 200 be the rightmost boundary of the sprite, not the leftmost boundary.

Fortunately, I found out how to fix this problem (I know I should be submitting a pull request but for now this works easier for me).

At the PIXI.Sprite.prototype.getBounds line at 15277, replace:

        if (a < 0) a *= -1;

with:

        if (a < 0) {
            a *= -1;
            var temp = w0;
            w0 = -w1;
            w1 = -temp; 
        }

This updates the boundaries of sprite when the scaling flips the sprite horizontally so the correct bounds are calculated.

You'll also need to do the same for the vertical flipping. On the next line down from the above, replace:

        if (d < 0) d *= -1;

with:

        if (d < 0) {
            d *= -1;
            var temp = h0;
            h0 = -h1;
            h1 = -temp; 
        }
 
I found this bug because generateTexture was generating textures with sides cut off because this bug meant it didn't have the correct area to crop from.

This is my first reported Phaser bug, thank you very much for creating an excellent HTML5 game engine!

**Comment by pnstickne** [comment]
Sure you don't want to learn some gitfu? Pull requests are fun!

I wonder if there was any edge case that relied on not-flipping.. since this appears to be a pixi issue, make sure they get notification as well.

**Comment by photonstorm** [comment]
Hmm let me check this with Mat first. It's a tiny change, but one of those things that could have catastrophic effects elsewhere :)

**Comment by photonstorm** [comment]
Discussed it over with him and we feel it should be a relatively safe change, so have made it and will test for 2.4.4 RC1.
