### ISSUE TITLE
InputHandler.justPressed pointer parameter documentation is incorrect

### ISSUE THREAD

**Issue by sonelliot** [photonstorm/phaser#2110]
The `InputHandler.justPressed` and other `just` methods accept a pointer object and a delay in ms. In the parameter documentation it says that it accepts a `Phaser.Pointer` object but what it actually wants is the `id` of the pointer so that it can lookup a value from its internal `_pointerCache` property.

I say we either update the documentation for these methods or change them to use `pointer.id` when looking up the cached value.

**Comment by pnstickne** [comment]
https://github.com/photonstorm/phaser/pull/2081

**Comment by photonstorm** [comment]
Closing this issue as the fix is merged into dev.
