### ISSUE TITLE
Map collisions stoped working

### ISSUE THREAD

**Issue by hugoeustaquio** [photonstorm/phaser#2112]
A lot of versions ago map collisions stopped working. Entirely.

Some of official examples that uses map collisions and are not working (I tested on both firefox and chrome on linux 64 bits):

http://phaser.io/examples/v2/tilemaps/tileset-from-bitmapdata
http://phaser.io/examples/v2/tilemaps/map-bounce
http://phaser.io/examples/v2/tilemaps/map-collide
http://phaser.io/examples/v2/tilemaps/tile-callbacks
http://phaser.io/examples/v2/tilemaps/create-from-objects
http://phaser.io/examples/v2/tilemaps/features-test

If something changed and all those examples are not working for some reason, I think the examples need to change too... There's some way I can "workaround" this problem? Are those examples working on another browsers and OS's?

Any suggestion?

Thanks

**Comment by pnstickne** [comment]
Do you know which Phaser version caused the regression?

**Comment by hugoeustaquio** [comment]
Until 2.3.0 it was working. On 2.4.x it stopped. I tried all 2.4.x versions tagged on github as 2.4.x versions (2.4.3, 2.4.2, 2.4.1 and 2.4.0a).
I think something has changed and someone forgot to inform us about how to handle map collisions on 2.4.x. But it's just my guess.

**Comment by photonstorm** [comment]
I tried all of those that you listed against 2.4.1 and 2.4.4 and they all collided just fine, with the exception of the bitmapdata one, and the collision in that works, it's the put tile part that is broken in the example. So more information needed.

**Comment by hugoeustaquio** [comment]
![phaser_err](https://cloud.githubusercontent.com/assets/8718536/10120265/34cb4a40-6489-11e5-9744-4a0476d46cfc.png)

![phaser_err2](https://cloud.githubusercontent.com/assets/8718536/10120274/7f5aae02-6489-11e5-93ad-a842f53a4745.png)


I tried to run those examples on windows, and it didn't work on both windows or linux. Same error. I can't say for sure where the problem are. I guessed based on log, that says "collideSpriteVsTilemapLayer is not a function".

**Comment by photonstorm** [comment]
Ah that's because the version of 2.4.3 on the examples site is a dev build and hasn't been replaced yet. Equally the version switched doesn't work (you'll notice it never actually loads the previous versions, it just tries again with 2.4.3-dev).

Run the examples locally and it works fine in all versions. I appreciate it's not great that they are broken on the examples site, but the actual Phaser builds are solid, as is the example code. I'll sort the site out when we release 2.4.4.
