### ISSUE TITLE
Pixi Render Texture example not working with 2.4.3/WebGL

### ISSUE THREAD

**Issue by jmp909** [photonstorm/phaser#2114]
Hi, 

I was trying out some rendering effect and I had some issues so I tried taking the example here http://phaser.io/examples/v2/display/pixi-render-texture but using 2.4.3 locally, instead of the 2.2.2 on the site.

one buffer seems not to work (the display flickers), and there's some graphical corruption. 
http://oi58.tinypic.com/245n60z.jpg

i thought it was my code at first but swapping 2.4.3 back to 2.2.2 works fine

on the demo site it appears that
WebGL uses Phaser v2.2.2 | Pixi.js v2.2.0 | WebGL | WebAudio 
Canvas uses  Phaser v2.4.3-dev | Pixi.js v2.2.8 | Canvas | WebAudio 

i've just checked and the last version that worked for this demo was 2.3.0.with Pixi v2.2.8 so it doesn't necessarily seem to be Pixi that's the issue.

2.4.0 gives an error Uncaught TypeError: Cannot read property 'prototype' of undefined (on PIXI.TilingSprite i believe)
2.4.0a gives a blank screen 
2.4.1 has the same issue as 2.4.2

thanks.
J

**Comment by pnstickne** [comment]
Does this still occur on the device branch?

**Comment by jmp909** [comment]
I'm just manually getting the minified build from the github tags and putting it into the example locally. doesn't work after 2.3.0

also I'm having the same Y-flipping issue as here with any version but that's a separate issue
https://github.com/photonstorm/phaser/issues/1942

**Comment by jmp909** [comment]
as per the fix on the other issue (1942) rendering `game.world` instead of `game.stage` also fixes this issue

`renderTexture2.renderXY(this.game.world, 0,0,true);`
instead of 
`renderTexture2.renderXY(this.game.stage, 0,0,true);`

strangely an entirely different issue fixed by the same thing.

**Comment by pnstickne** [comment]
My guess is there is some 'residual state' in the transformations that was being cycled.

**Comment by photonstorm** [comment]
This example runs fine under 2.4.4-dev in WebGL (as do the other Render Texture examples) so I'm going to close this one off. I'll upload a new 2.4.4 build file later on today, so feel free to check your own code against that when it's uploaded.
