### ISSUE TITLE
Question: Local Pixi patching policy

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser#2115]
I know you probably don't want to touch this, but.. 

Is the Pixi bundled with Phaser *the* reference for a Phaser? In particular,  is there a clean(er)  method to add local patches/updates to it? Such that they will not be lost on a 'sync'..

**Comment by photonstorm** [comment]
The version of Pixi included in Phaser should be patched directly. It is so modified from the official Pixi build that you can no longer merge from any Pixi version directly into Phaser. The more I work through the Pixi source the more I will be changing it in the months to come as well.
