### ISSUE TITLE
Possible issue with recent fix for iOS 9 audio unlocking

### ISSUE THREAD

**Issue by jesse-k** [photonstorm/phaser#2119]
Apologies if this is the wrong place to post this or if I haven't followed the right protocol here.

I was trying the recent fix for the iOS 9 'audio unlock' problem discussed here:

https://github.com/photonstorm/phaser/issues/2095

And may have found a case where it doesn't work correctly. I'm seeing this problem in my own code as well.

It seems that if the 'touch end' event comes at the end of a held touch or drag (rather than a brief tap), iOS will not unlock Web Audio inside that event. Since Phaser considers audio to be unlocked after the first 'touch end' event, if the first user interaction is a drag or held touch, audio will never be unlocked (or at least that seems to be the case).

Here's a self-contained test program:

```javascript
var sound, playSound = false;
var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'unlock-test', {
  preload: function() { game.load.audio("sound", "sound.m4a"); },
  create: function() {
    sound = game.add.audio("sound");
    game.input.onDown.add(function() { playSound = true; });
  },
  update: function() {
    if (playSound) {
      sound.play();
      playSound = false;
    }
  }
});
```

If the first interaction is a tap, it works and audio is unlocked, but if the first interaction is a drag or held touch, audio never unlocks. (I'm pretty sure the test program is implemented correctly, but it's possible I've made an error somewhere.)

I realize this is really more of an iOS issue than a Phaser issue, but I thought it might be worth mentioning.

**Comment by photonstorm** [comment]
Hmm if that's the case I'm not sure of any fix for it.

**Comment by jesse-k** [comment]
One thing I've tried is waiting for the 'onended' event of the Web Audio source to fire, indicating that audio has actually been unlocked, and only then removing the listeners. That seems a little circuitous though, and it still doesn't guarantee an unlock if the user never makes a 'tap' gesture at all.

Anyway, it seemed like it might be worth asking about, but maybe as you said it's just a limitation in iOS that there's no easy fix for at the moment.

**Comment by mattdesl** [comment]
I've been exploring bugs related to mobile WebAudio in this repo. It's truly a pain:
https://github.com/Jam3/web-audio-player#webaudio-gotchas

I'm also working on a variety of modules to ease these pains and wrap up the boilerplate into a single function.

I noticed the same `'touchend'` issue in a recent demo. To fix, I'm listening for `'touchstart'`, storing the time and position, and then checking that in the `'touchend'` event to see whether it's less than a certain threshold. 
https://github.com/mattdesl/codevember/blob/25512f80a0aea27131b959a9ebd99f85456dfd03/src/30.js#L110-L115

**Comment by photonstorm** [comment]
Given the fix for this is now [merged](https://bugs.webkit.org/show_bug.cgi?id=149367) with webkit I'm wondering what the next best course of action is.

They may well revert to 'touchend' again at a later date, but assuming the fix lands in iOS shortly we're in the wonderful grey area of "all versions of iOS can use touchstart, except these two specific versions of iOS9", which is a hell of a mess. Or I guess you could just update all code to work on `touchend` only, and then do the timing trick and pray it wasn't actually a drag event, even if the timer threshold thinks it was.

**Comment by photonstorm** [comment]
This has now landed in iOS, so I'm going to keep an eye on it, but otherwise it'll go down as one of those lovely Apple legacy issues.
