### ISSUE TITLE
DeviceButton is not present on Type definitions for Phaser 2.4.3

### ISSUE THREAD

**Issue by diegogonzalez** [photonstorm/phaser#2126]
The type definitions doesn't match with the lib

**Comment by photonstorm** [comment]
DeviceButton is in the defs in the dev branch, unless you mean there is something wrong with the def itself?

**Comment by diegogonzalez** [comment]
I´m sorry. I mean in the definition for TypeScript (phaser.d.ts)

**Comment by photonstorm** [comment]
I understand, I meant did you check the defs in the dev branch? That is where we work on them when preparing the new build, and I can see DeviceButton in there.

**Comment by diegogonzalez** [comment]
Ahh ok, that´s rigth! I check´d the last release. Thank´s!
