### ISSUE TITLE
making an Array with Random entries out of an original Array 

### ISSUE THREAD

**Issue by pooya72** [photonstorm/phaser#2127]
Like This 

`var originalArray =[0,1,2,3,4,5,6,7,7,7,7,8,9,54];`

`var randArray = Phaser.ArrayUtils.randArrayGenerator(originalArray,5);`

`///  ==> randArray = [1,4,7,9,7];`

**Comment by photonstorm** [comment]
Is this a question or a feature request?!

You can do it with ArrayUtils.shuffle though. Just clone the array then shuffle it. Voila.

**Comment by pooya72** [comment]
shuffle returns a full length shuffled array, but any way combining it with Array slice solves the problem.
Thx for respond.
