### ISSUE TITLE
Does not work with browserify out of the box

### ISSUE THREAD

**Issue by cybrown** [photonstorm/phaser#2131]
I've installed phaser with npm, and used require in my app file, then browserified it.

In the browser I get this error:

Uncaught ReferenceError: PIXI is not defined

**Comment by photonstorm** [comment]
Yes it needs setting as a global, here's a package.json you can adapt:

```
{
  "main": "./main.js",

  "browser": {
    "phaser": "../../phaser/dist/phaser-test.js"
  },

  "browserify-shim": {
    "phaser": "global:Phaser",
    "pixi": "global:PIXI"
  },

  "browserify": {
    "transform": [ "browserify-shim" ]
  },

  "devDependencies": {
    "browserify": "^11.0.0",
    "browserify-shim": "^3.8.10"
  }
}
```

**Comment by cybrown** [comment]
Thank you :+1:

**Comment by benwiley4000** [comment]
I'm experiencing a similar problem (I'm running browserify using gulp).

Here's my package.json (with irrelevant entries removed):

```
{
  "dependencies": {
    "phaser": "^2.4.4",
    "pixi": "^0.3.1"
  },
  "browserify-shim": {
    "phaser": "global:Phaser",
    "pixi": "global:PIXI"
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "devDependencies": {
    "browserify": "^12.0.1",
    "browserify-shim": "^3.8.11",
    "gulp": "^3.9.0",
    "vinyl-source-stream": "^1.1.0"
  }
}
```

Here's my gulpfile:

```
var gulp = require('gulp');
var browserify = require('browserify');
var source = require('vinyl-source-stream');
 
gulp.task('browserify', function() {
    return browserify('./src/js/main.js')
      .bundle()
      .pipe(source('bundle.js'))
      .pipe(gulp.dest('./dist/js/'));
});

gulp.task('default', ['browserify']);
```

Here's my main.js:

```
var PIXI = require('pixi');
var Phaser = require('phaser');

window.onload = function() {

  console.log('hey');

  var game = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: preload,
    create: create
  });

  function preload () {

    game.load.image('logo', 'phaser.png');

  }

  function create () {

    var logo = game.add.sprite(game.world.centerX, game.world.centerY, 'logo');
    logo.anchor.setTo(0.5, 0.5);

  }

};
```

The console tells me that `Phaser` is `undefined`. What am I doing wrong?

**Comment by mattstyles** [comment]
@benwiley4000 you're including [pixi](https://www.npmjs.com/package/pixi), it should be *pixi.js*

**Comment by AlexGoico** [comment]
@benwiley4000 I think your problem is you have no alias for phaser in your package.json: https://github.com/thlorenz/browserify-shim#b-use-aliases. You also don't need to include pixi like mattstyles says. I'm currently trying to find out why I keep getting a call function property undefined involving Phaser.Device.__readyCheck after bundling. Unlike the original response though, I am not using globals since that would require including the required js files into your main html file.

**Comment by AlexGoico** [comment]
I take that back my problem, I forgot to instantiate Phaser.Game as new Phaser.Game.
