### ISSUE TITLE
onInputOver issue

### ISSUE THREAD

**Issue by McFarts** [photonstorm/phaser#2133]
For example:

```
	tempSprite.events.onInputOver.add(MonsterHover);
```

If you hover over that tempSprite and keep your mouse hovering it and click on it (let's say to attack the monster), the MonsterHover get's FIRED after you let go of your mouse (if your mouse is still over that sprite)

Is that intended? Because it should only fire when the mouse enters and hovers it, not when the mouse is already hovering it and when you release. Hence the 'OnInputOver'.

**Comment by McFarts** [comment]
Here is the issue I'm talking about:

Go here: http://phaser.io/examples/v2/buttons/action-on-click#gv


And replace the code with:

```
var game = new Phaser.Game(800, 600, Phaser.AUTO, 'phaser-example', { preload: preload, create: create });

function preload() {

    game.load.spritesheet('button', 'assets/buttons/button_sprite_sheet.png', 193, 71);
    game.load.image('background','assets/misc/starfield.jpg');

}

var button;
var background;

function create() {

    game.stage.backgroundColor = '#182d3b';

    background = game.add.sprite(25, 25, 'background');
 
    background.inputEnabled=true;
    background.events.onInputOver.add(over, this);
    background.events.onInputOut.add(out, this);
    background.events.onInputUp.add(up, this);

}

function up() {
    console.log('button up', arguments);
}

function over() {
    console.log('button over');
}

function out() {
    console.log('button out');
}

function actionOnClick () {

    //background.visible =! background.visible;

}
```

You see, how the hover function gets called when you release the mouse? Even though it's still ontop of the sprite?

**Comment by photonstorm** [comment]
And against 2.4.4-dev?

**Comment by McFarts** [comment]
@photonstorm  Sorry for the late reply. Had to rebuild 2.4.4 since both cdn's on the github page don't work for it. Looks like it was removed from their servers.

It [still](https://i.gyazo.com/55c8411bad5709459e453df69b0f3b99.gif) is happening on 2.4.4 as well.

Screenshot gif is bad, but it's doing the same thing as the above code. onInputHover is being fired even when mouse is still over the sprite after the user clicks.

What's funny is, it works fine when you use `game.add.button` as prevalent [here](http://phaser.io/examples/v2/buttons/action-on-click#gv)

**Comment by McFarts** [comment]
Boom! @photonstorm I fixed it! Took me a while to grasp through the source, it's huge :)

But, it's on line 44321:


It needs to be:

```
        if (this.sprite === null || pointer.justReleased()) // Or if the pointer is released above the sprite
        {
            //  Abort. We've been destroyed.
            return;
        }
```

I added `|| pointer.justReleased()` to the if condition.

It's used the same exact way on Line 51931:
```
Phaser.Button.prototype.onInputOverHandler = function (sprite, pointer) {

    //  If the Pointer was only just released then we don't fire an over event
 
    if (pointer.justReleased())
    {
        return;
    }
```

**Comment by McFarts** [comment]
Okay, sorry about my other post, there was an issue.

New code:

```
		if(this.sprite && data.isOver === true && pointer.justReleased()){ // Don't fire the hover event when the mouse is already released over a sprite
			return;
		}
```

Line: 44329

This seems to work fine now with other events, sorry my old code, we need to make sure it's a sprite, and it's over is truthy and if pointer released :)

**Comment by photonstorm** [comment]
This is now fixed in the dev branch.

**Comment by McFarts** [comment]
Haha, cannot believe this was actually fixed.  It's been forever rich, I totally forgot about it, lol thank you

**Comment by photonstorm** [comment]
It was super low priority really, nothing was 'broken' as such.
