### ISSUE TITLE
parentRect needs a terny [2.4.4 dev]

### ISSUE THREAD

**Issue by McFarts** [photonstorm/phaser#2134]
Latest build inside the `getParentBounds` function, at line **74917**

`
           var parentRect = parentNode.offsetParent.getBoundingClientRect();
`

If there is no offsetParent, you will receive a fatal:
![](https://i.gyazo.com/db128ab2d1096764df906ca98519f410.png)

Fix:

```
var parentRect = parentNode.offsetParent ? parentNode.offsetParent.getBoundingClientRect() : parentNode.getBoundingClientRect();
```

Or, however Rich and the other devs want to fix it :)

**Comment by photonstorm** [comment]
Thanks - added :)
