### ISSUE TITLE
Rope is missing the tilePosition property

### ISSUE THREAD

**Issue by spayton** [photonstorm/phaser#2135]
The Rope class uses acts upon a tilePosition property, probably for the advertised 'texture scrolling', but it isn't defined, so calling Rope.reset() which references it will crash.

Is this a feature awaiting implementation or pending removal?

If it's to stay, then probably best to hide all references to tilePosition in the interim to stop crashes.

**Comment by photonstorm** [comment]
Hmm it was used in several places. I have removed it for now, the demos still work, so I'll leave it "left out" for the time being.

**Comment by wayfu** [comment]
Correct me if I'm wrong, but that property was only there because the Rope class was created from the Tilesprite class template

**Comment by photonstorm** [comment]
Quite possibly, although it did mention it in the jsdocs. Right now I don't have time to go back through earlier builds to figure out why, so am happy to leave it as-is (as it works and doesn't break now).
