### ISSUE TITLE
Apply lineSpacing to last row of Phaser.Text

### ISSUE THREAD

**Issue by Lopdo** [photonstorm/phaser#2137]
Currently, line spacing works fine for calculating distance between lines, but it keeps original "padding" on the bottom.

For example, if my text has line height of 20, but I want it more clustered, I set lineSpacing to -5, making it effectively 15, however last line remains at 20, so if I get height of 2 line text, I get 35 instead of 30 which causes complications when I want to position something right underneath this text. Same problem is apparent when there is only one line

**Comment by photonstorm** [comment]
This is now fixed in dev.
