### ISSUE TITLE
Phaser full game destruction and possible memory leak

### ISSUE THREAD

**Issue by i-dimitrov** [photonstorm/phaser#2138]
I am making a multiplayer game with AngularJS and Phaser. When the game ends or the user leaves I call my Game instance destroy() method which should "Nuke the entire game from orbit.". However, as I follow the phaser.js source code, it seems that everything is destroyed except the "world" group and the "cache". When Game's destroy() calls "this.state.destroy()", then "this.clearCurrentState();" should call "this.game.world.shutdown();" and "this.game.cache.destroy();" but only if _clearWorld and _clearCache are set to true when switching states. But they are not, when nuking the game. So according to Chome Profiler this causes memory leak. However, manually calling cache.destroy() and world.destroy() seems to fix that issue, but I think it should be automatic.

**Comment by McFarts** [comment]
When you are calling destroy, are you sure you're not just calling it on a specific object?

**Comment by i-dimitrov** [comment]
```javascript
/// <reference path="phaser.d.ts"/>

class GameApp extends Phaser.Game {
    constructor() {
        super(800, 600, Phaser.AUTO, "game-content");

        this.state.add('boot', Boot);
        this.state.add('preload', Preload);
        this.state.add('main', Main);

        this.state.start('boot');
    }
}


window.onload = function () {
        var gameApp = null;
        Phaser.Device.whenReady(function () {
            gameApp = new GameApp();
        });
}
```
Generally, that's the case. On some point later "gameApp.destroy()" is called so it is not on a specific object. It really nukes the whole game but phaser's cache seems to stay. 
I placed some console.logs in phaser.js and tried again but cache.destroy() doesn't appear to be called.

**Comment by photonstorm** [comment]
Agreed, fixed in dev.
