### ISSUE TITLE
Playing legacy audio does not respect mute value of SoundManager

### ISSUE THREAD

**Issue by brianbunch** [photonstorm/phaser#2139]
When playing a sound for the first time using e.g.
```javascript
this.game.sound.play('sfx'); 
```
after muting the SoundManager using 
```javascript
this.game.sound.mute = true;
```
the sound plays anyway when using legacy audio.

It seems to be because only previously added sounds are muted when calling mute on the SoundManager.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
