### ISSUE TITLE
TypeScript problem accessing BitmapFont Data

### ISSUE THREAD

**Issue by Darky-Lucera** [photonstorm/phaser#2140]
Hi!
 
I tryed to access BitmapFont data through 'game.cache.getBitmapFont()' but seems that typeScript file 'phaser.d.ts' does not define any class 'BitmapFont' and indicates that the function 'game.cache.getBitmapFont()' returns 'RetroFont' that is not correct because the function returns other thing.
 
I added this to 'phaser.d.ts':
```typescript
class BMChar {
    x: number;
    y: number;
    width: number;
    height: number;
    xOffset: number;
    yOffset: number;
    xAdvance: number;
    kerning: any[];
    texture: PIXI.Texture;
}
class BMFontData {
    chars: any[];
    font: string;
    lineHeight: number;
    size: number;
}
class BMFont {
    base: PIXI.BaseTexture;
    data: HTMLImageElement;
    font: BMFontData;
    url: string;
}
```
and changed 'game.cache.getBitmapFont()' to return a BMFont.

Could you please add something like this to 'phaser.d.ts' file.

Thanks!

**Comment by clark-stevenson** [comment]
Thanks for this!

Do you want to make a PR on the dev branch? To be honest, what confuses me is that I cannot find the "BitmapFont" class.  Does anyone where it lives?

**Comment by Darky-Lucera** [comment]
Could you do it? 
I'm not a regular user of GIT and is a bit uncomfortable for me, and I do not need the authorship of this change, hehe

Furthermore, I put provisional names to the classes (BM*) precisely because I was surprised that no BitmapData class exists already.

if finally you update TypeScript defs for phaser, remember to put right names to the classes.

PD: I didn't know what info is on kerning data.

**Comment by clark-stevenson** [comment]
No problem :dancer:  I went over to the phaser examples (awesome work on live editing sandbox @photonstorm !) and console logged out the return object. You were pretty much spot on.  I do not know what kerning is either but it seems to be an array of numbers.  

Hopefully it should fix the problem.

**Comment by Darky-Lucera** [comment]
Kerning is the space between each pair of letters. ^_^

**Comment by clark-stevenson** [comment]
I always thought it was some kind of Skewing..... Old Flash misunderstanding.  You learn something new everyday!
