### ISSUE TITLE
iFrame on iOS Chrome Browser Pausing Game

### ISSUE THREAD

**Issue by dturney** [photonstorm/phaser#2142]
Hello,

We just recently had an issue with Chrome browser on iOS with Phaser 2.4.4.  It seems Phaser touch events were not being active inside an iFrame with Chrome.

The iFrame seems to pause the game or Phaser pauses the game while in the iFrame.  We had to use this.game.stage.disableVisibilityChange = true to disable the pause and the touch events came back.

Found the fix according to this post:
http://www.html5gamedevs.com/topic/16096-touch-events-inside-iframe-on-chrome-for-ios-not-firing/

I did some some testing with older versions and found that anything less than 2.4.4 still works for us without having to change or set stage.disableVisibilityChange.

It wasn't a concern with Safari on iOS and Firefox on iOS.  Or Chrome on Android.

**Comment by photonstorm** [comment]
Which version of iOS? Nothing actually changed in 2.4.4 with regard to how the visibility events are handled, so it has to be a side-effect of something else (possibly even unrelated).

**Comment by dturney** [comment]
iOS 9.0.1 and 9.0.2
Chrome 45.0.2454.89

I think I still have a 8.0 device floating around.  I can see if that issue is happening as well.

The Chrome browser app for iOS did update in September 15, 2015.

**Comment by dturney** [comment]
You are correct that it is not just 2.4.4.

I did a test with 2.4.3 and ran into the same pause issue.  So, not just 2.4.4.  We have older games using different versions, but all those games are using the disableVisibilityChange = true.  So, they are working in the iFrame.

The oldest version looks to be Phaser 2.2.2 that we use and have that disableVisibilityChange set to true.

**Comment by dturney** [comment]
Did some tracing on out on a local phaser.js file.  As soon as you click the page containing the iframe or the game inside the iframe.  The window looks to fire a blur event.  Which causes the game to call focusLoss if disableVisibilityChange is not set to true.

None of the other browsers on iOS(safari and firefox) seem to fire that trace out.

**Comment by photonstorm** [comment]
Closing due to several months of inactivity. A stand-alone running code example is needed to investigate this further.
