### ISSUE TITLE
Documentation: Animation has 2x loop parameters

### ISSUE THREAD

**Issue by Cristy94** [photonstorm/phaser#2143]
http://phaser.io/docs/2.4.4/Phaser.Animation.html

`new Animation(game, parent, name, frameData, frames, frameRate, loop, loop)`

Line 21 or should be removed: https://github.com/photonstorm/phaser/blob/v2.4.4/src/animation/Animation.js#L21

**Comment by photonstorm** [comment]
Fixed in dev.
