### ISSUE TITLE
loader for audio sprites should be camel-case

### ISSUE THREAD

**Issue by epaezrubio** [photonstorm/phaser#2145]
https://github.com/photonstorm/phaser/blob/c9c85330ab60547b39ba4c9400c258ed7fb2a317/src/loader/Loader.js#L1035

I find really disturbing loading audio sprites with `game.load.audiosprite` and creating them with `game.add.audioSprite` (note the capital *s*).

I suggest using *audioSprite* for both.

**Comment by photonstorm** [comment]
Agreed. Updated in dev.
