### ISSUE TITLE
Reported text width when resolution is high

### ISSUE THREAD

**Issue by mattahj** [photonstorm/phaser#2146]
Hi,

I found that setting text resolution to `game.renderer.resolution * window.devicePixelRatio` makes text look much nicer on devices which have a pixel ratio that is greater than 1. However this seems to screw up the text width that you get when checking `text.width`. 

I created a sandbox which should show this issue: http://phaser.io/sandbox/edit/LxNJwfBq 

The output I get when running this is:
```
[Log] really high DPI width: 342
[Log] High DPI width: 171
[Log] Low DPI width: 171
```

**Comment by hayesmaker** [comment]
They all look the same on my imac :dancer:

**Comment by zodern** [comment]
I also had this issue when setting `resolution: window.devicePixelRatio` when creating a new Phaser.Game.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
