### ISSUE TITLE
Box2D plugin removeBodyContactCallback function request

### ISSUE THREAD

**Issue by bvargish** [photonstorm/phaser#2147]
Unless I'm missing something in the API for the Body class, it doesn't seem like there is a way to remove callbacks from a body that are set with setBodyContactCallback. A removeBodyContactCallback would be helpful.

Here's a use case and the hack I'm currently using to deal with this: http://www.html5gamedevs.com/topic/16078-setbodycontactcallback-box2d-excutes-callback-twicehelp/

**Comment by photonstorm** [comment]
You can call the function again and pass in 'null' as the callback and it will clear it.
