### ISSUE TITLE
ReferenceError: VERSION is not defined

### ISSUE THREAD

**Issue by McFarts** [photonstorm/phaser#2148]
![](https://i.gyazo.com/69d926b72f644a4c821df4149ab6ab64.png)

Every time we click on the rocket icon, we get uncaught version errors ~ Not sure if it's already been reported but it's been happening for several days now so I'd thought I'd make a issue.

Happens on any example page

**Comment by staff0rd** [comment]
Same for me on Chrome/IE

**Comment by photonstorm** [comment]
Finally got around to fixing this one. Also fixed not being able to change the Themes too.

**Comment by McFarts** [comment]
Awesome!!! This was one a annoying little bugger messing with the examples, glad it's fixed thank you rich!!
