### ISSUE TITLE
Problem when pausing looped sounds

### ISSUE THREAD

**Issue by haden** [photonstorm/phaser#215]
If you pause then resume a looped sound, you will stop hearing it when it loops. When the sound's time reaches it's total duration, it will stop instead of looping, but the debug.renderSoundInfo says it's still playing.

You can test the bug by yourself here:

https://dl.dropboxusercontent.com/u/36169647/AudioBug/index.html

It's a combination of "loop" and "pause and resume" Phaser examples. At first the sounds loops fine, but if you pause it and resume it (by tapping in the upper part then lower part of the canvas) it will not loop correctly.

**Comment by NeoHoffa** [comment]
This seems to be an issue again.

https://github.com/photonstorm/phaser-ce/issues/316
