### ISSUE TITLE
Memory leak in Phaser.Utils.Debug

### ISSUE THREAD

**Issue by bdaenen** [photonstorm/phaser#2150]
### Issue
Since updating to 2.4.4 I noticed my page was crashing a lot in Chrome. I tested this on: 
* Windows 7 Chrome stable "46.0.2490.71 m"
* Windows 7 Firefox Nightly "44.0a1 (2015-10-21)"
* OSX 10.10.5 Chrome stable "46.0.2490.71 (64-bit)"

After some debugging I found out that memory usage keeps rising for a couple of seconds, then drops back to a lower number. This pattern keeps repeating itself, going higher and higher in memory usage until eventually my PC runs out of memory.

Initially I thought this was a problem with my game-specific code, but after checking some of the examples I could easily notice the same problem occuring. As soon as I loaded 2.4.3 this problem disappeared completely.

In the end, the culprit turned out to be my Phaser debug calls. Unfortunately I could not find the exact cause.

### Steps to reproduce:
 * Go to http://phaser.io/examples/v2/arcade-physics/body-debug in Chrome or Firefox
 * Open Windows Task Manager
 * Find the ``` chrome.exe ``` (Chrome) or ``` plugin-container.exe ``` (Firefox) process with heavily changing memory usage and click it for easy tracking.
 * Click in the example frame to disable the debug info, memory usage should become way more stable
 * Change the Phaser version to 2.4.3 in the dropdown underneath the editor and notice that it is now lower and much more stable with the debug info on.

#### Extra info
* See https://i.imgur.com/y4VD0Qk.gifv to see it in action on my PC in another example with debug info.
* I tried debugging this in Chrome. Turning on heap snapshots greatly reduced the spiking for some reason and gave me data that didn't seem very usable.

**Comment by nexiuhm** [comment]
I second this. Memory spikes when using debug.text.

**Comment by nexiuhm** [comment]
So i looked into this abit more and I think i found that the change that is causing it: https://github.com/photonstorm/phaser/commit/8899eddd9a52d60b94377e3a28ee5e3b92293701

Maybe there is actually a memory leak happening in BitMapData.update() ? Either that or its just very expensive using it during every clear().  But then again I'm just a beginner programmer and the whole inner workings of phaser is not something I'm familiar with!

**Comment by nexiuhm** [comment]
Its worth nothing that this only seems to happen with some setups. I tried it on another computer and was not able to reproduce the problem.

**Comment by photonstorm** [comment]
The fix implemented for #2208 will resolve this too. The reason it doesn't appear on some set-ups is because it's a WebGL only bug.
