### ISSUE TITLE
Events dispatched to wrong sprite when multiple sprites with input handlers overlap

### ISSUE THREAD

**Issue by Taschenschieber** [photonstorm/phaser#2153]
When multiple sprites with input handlers overlap, events are apparently dispatched to the newest of them, not to the one that's last in rendering order. This does not match the documentation at http://phaser.io/docs/2.2.2/Phaser.InputHandler.html#priorityID.

**Comment by photonstorm** [comment]
Have you set a priorityID? By default they all have an ID of zero, meaning the display list dictates which one gets the event. Only if you set the ID do the docs in the above link come into effect.

**Comment by Taschenschieber** [comment]
Oh, so the display list is not actually in the order in which the sprites are rendered? I misunderstood the documentation, then, because I assumed the sprite painted last would get the event (which also seems a lot more intuitive to me).

With a priority ID set, everything behaves like I would have expected.
