### ISSUE TITLE
Can we removed phaser-comments.d.ts?

### ISSUE THREAD

**Issue by clark-stevenson** [photonstorm/phaser#2157]
See http://www.html5gamedevs.com/topic/17833-phaserdts-vs-phasercommentsdts/?hl=typescript

I know I cannot fix it personally, and I seen people are confused so I say lets remove it until someone knows how to fix this script?

https://github.com/photonstorm/phaser/blob/master/tasks/buildtsdoc.js

**Comment by photonstorm** [comment]
Yes I agree. I'll remove it for 2.4.5.

**Comment by vulvulune** [comment]
Hello,
I found a workaround to execute the script:
https://github.com/photonstorm/phaser/pull/2198

**Comment by photonstorm** [comment]
Closing as this is now fixed. Glad to have it back again!
