### ISSUE TITLE
Gamepad buttons not reported as in "down" state when onDownCallback invoked.

### ISSUE THREAD

**Issue by suicidepills** [photonstorm/phaser#2159]
To reproduce:

- Obtain a SinglePad instance reference.
- Set up a listener for the SinglePad instance's onDownCallback method.
- In your listener, use the console to print out the pressed buttons "isDown" property.

Expected behavior: The button's "isDown" property would be set to TRUE.
Actual behavior: The button's isDown is set to FALSE.

The apparent cause of this can be found in SinglePad.js : Line 360.  I think the fix is simply to move the last "if" clause to the top of the function so the button's state is set prior to calling the rest of the "down" callbacks.

Is that safe to do?  I'm happy to make the change and submit a pull request if this is an acceptable fix but I wanted to check to see if the existing order of the "if" statements was intentional.

Thanks for your help!

Edit: It may be worth noting that manually getting a reference to the pressed button (via SinglePad.getButton()) and setting the value (via DeviceButton.start(null, value)) before checking the value of DeviceButton.isDown seems to fix the issue.

Example code.
```
game.input.gamepad.start();
pad1 = game.input.gamepad.pad1;
pad1.onDownCallback = function (buttonCode, value) {
    switch (buttonCode) {
        case Phaser.Gamepad.XBOX360_A:
            console.log(pad1.getButton(buttonCode).isDown); // returns false;

            // Manually set button state.
            pad1.getButton(buttonCode).start(null, value);
            
            console.log(pad1.getButton(buttonCode).isDown); // returns true;
            break;
    }
};
```

**Comment by photonstorm** [comment]
Agreed, this is now fixed in dev.
