### ISSUE TITLE
Blurry Text with anchor.set

### ISSUE THREAD

**Issue by McFarts** [photonstorm/phaser#2162]
Okay, I finally found what was causing this issue. (If it's a bug, or maybe my fault for not positioning text correctly, not entirely sure)

Here is the jsfiddle:

http://jsfiddle.net/Dillybob/u3mGL/23/

With `anchor.set(0.5, 0.5)`
![](https://i.gyazo.com/78aeec80646d6e2a0e81a158f2910afe.png)

Without it:
![](https://i.gyazo.com/fbdc203beac8f37a14629c6d15ff543b.png)

Just curious, as pertinent to this topic:
http://www.html5gamedevs.com/topic/15162-phasertext-smoothness-issue-text-appears-blurred/?p=85859

I am curious if this is a bug and if maybe the text should not be blurred like that regardless of the position?

**Comment by shohan4556** [comment]
I have faced same problem, may be its a bug hope it will fix soon.

**Comment by carst3n** [comment]
Did you try setting game.renderer.renderSession.roundPixels to 'true'? For me that fixes the problem in your fiddle.

**Comment by McFarts** [comment]
wow carst3n...

That is awesome, thank you for this. I would of never found out lol

**Comment by carst3n** [comment]
No problem. And yeah, I've also spend quite a bit of time on this. Now I just drop it into the init/create function of every project. The flag just needs to be set once and then you can completely forget about it.

**So my vote for this issue is:** make roundPixels default to 'true'. Having roundPixels set to 'false' causes all kinds of strange blurriness in both WebGL and Canvas.

**Comment by photonstorm** [comment]
Nah I can't default those, sorry. Changes too much.

Also this issue isn't a result of using anchor 0.5, it's because of the resulting sub-pixel rounding. You could easily have a Text object with anchor 0.5 that renders just fine, because it's width is divisible by 2 evenly.

**Comment by d3lm** [comment]
@carst3n Just had the same issue. You saved my day. I was working on a Retina Mac Book before and it looked fine. Then I switched to a Windows and everything was broken in terms of fonts that seem blurry. With that option enabled everything looks super nice again. Thank you so much!
