### ISSUE TITLE
Sound Off for all previous and future sounds

### ISSUE THREAD

**Issue by pooya72** [photonstorm/phaser#2163]
Please add ability to make sound off for all sounds (including sounds not created yet), this is a very helpful feature for sound off/on settings in games, if there be a way to separate music and audio in some ways(by id for example) that would be much much better.

**Comment by Cristy94** [comment]
Have you tried `game.sound.mute = true` ?

**Comment by photonstorm** [comment]
Mute the SoundManager itself to achieve this. As for splitting between FX and Music, that's the responsibility of the developer.
