### ISSUE TITLE
Kerning information in BitmapText is ignored

### ISSUE THREAD

**Issue by veu** [photonstorm/phaser#2165]
In Phaser 2.4.4 the kerning information in BitmapText fonts is parsed correctly and used for calculating line breaks but appears to be ignored for rendering.

Debugging this a bit, changing [three lines](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/BitmapText.js#L290-L294) in BitmapText.js to the following appears to fix it.

```
w += (charData.xAdvance + kerning) * scale;
chars.push(x + (charData.xOffset + kerning) * scale);
x += (charData.xAdvance + kerning) * scale;
```

I haven't tested it enough for a full pull request though.

PS: I don't see a difference in the dev branch either.

**Comment by photonstorm** [comment]
This is now fixed in dev.
