### ISSUE TITLE
Group.sort doesn't work with integers

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2166]
After quite a lot of debugging I've figured out that Group.sort isn't able to sort integers. It sorts alphabetically so you don't see the problem until you have a data set with numbers having varying decimal places (e.g. [10,900,1000]).  

I would expect that 'z', the default sorting property, would be an integer since sorting with letters seems absurd. And if you've got a zelda-like game, you're going to sort on the y vector which is an integer... really I can't imagine a scenario in which sorting alphabetically would be practical. 

That said, I had to create my own function for depth sorting with a property that is an integer. Phaser.Group#ascendingSortHandler should only really work with strings.
    
    function manualSort() {
        gameObjects.children.sort(function(a, b) {
            return a.z - b.z;
        });
    }

I think ascendingSortHandler and descendingSortHandler should operate the same way. After some testing you'll discover that they are only really suited for strings or integer data sets without varying decimal places.

**Comment by McFarts** [comment]
If approved, I think Richard would add it to the core, good idea

**Comment by photonstorm** [comment]
I assume you mean it can't sort _floats_ ? Either way, I need an example showing how you think it can't sort floats (or integers), because this Group.sort test handles both just fine: http://phaser.io/sandbox/edit/OzbGZCRc

View the console output to see the raw y coordinates. Array.sort only sorts by Unicode string if no comparison function is provided, but Group uses one.

Internally `z` is an integer, set by the render loop, never a string and never a float (unless it was replaced by something, which it shouldn't have been, as it's a protected property).

**Comment by cscott5288** [comment]
Once again, the error was not in Phaser but in my code. The property I created to sort with had numbers mixed in with strings. Group.sort does work with numbers as well as integers... my bad. You can close this issue.

**Comment by photonstorm** [comment]
Ok cool. Leave it open for now as it will be a good reminder for me to
mention this in the docs.

On Tuesday, 27 October 2015, cscott5288 <notifications@github.com> wrote:

> Once again, the error was not in Phaser but in my code. The property I
> created to sort with had numbers mixed in with strings. Group.sort does
> work with numbers as well as integers... my bad. You can close this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2166#issuecomment-151649512>
> .
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by photonstorm** [comment]
Docs updated, so closing.
