### ISSUE TITLE
Click and control key

### ISSUE THREAD

**Issue by yuvalsv** [photonstorm/phaser#2167]
When the user tries to select an sprite using "ctrl + left click" the click event will get fire a first time, after that the sprite freeze and you won't be able to click on it again. It is happening on Chrome and IE11. You can test this behaviour here

http://phaser.io/examples/v2/basics/02-click-on-an-image

This also occurs on buttons. I have also find out that if you click using the right button you will be able to click on the sprite again.

Some of the users are using the control key to try to select multiple sprites.

Thanks in advance for your help.

**Comment by yuvalsv** [comment]
After some research I have noticed that if I comment these lines on Phaser

        //  On OS X (and other devices with trackpads) you have to press CTRL + the pad
        //  to initiate a right-click event, so we'll check for that here

        if (event.ctrlKey && this.leftButton.isDown)
        {
            this.rightButton.start(event);
        }

It will work as expected. I don't have a Mac but I am guessing it won't work for these devices if I do this.

**Comment by photonstorm** [comment]
Honestly I can't think of an easy way to avoid this. We either don't allow ctrl + click on Windows, or we don't allow right-clicks on OS X. I'm not sure either is better than the other.

Suggestions?!

**Comment by photonstorm** [comment]
Figured out a nice way to resolve this. Fix now in dev.
