### ISSUE TITLE
cannot add blank sprite (uses previous sprite texture)

### ISSUE THREAD

**Issue by jmp909** [photonstorm/phaser#2173]
it does not seem possible to add a blank sprite unless it is the first sprite created
http://phaser.io/sandbox/vXVjSgyw/play

if `game.add.sprite (0,0)` is the first call, then the sprite will be blank (so you can add Phaser.Graphics to it etc)

however if it is called with no texture supplied, *after* another sprite has been used with a texture previously, it uses that texture (although not at the same dimensions)

**Comment by jmp909** [comment]
for anyone reading. you can currently use
`mySprite.texture.baseTexture.skipRender = false`
and no texture will be shown

**Comment by photonstorm** [comment]
Closing as this is fixed in the dev branch.
