### ISSUE TITLE
createFromTiles does not accept spritesheet/frame, whereas createFromObjects does

### ISSUE THREAD

**Issue by jmp909** [photonstorm/phaser#2175]
since createFromTiles and createFromObjects both create Sprites, it would make sense that I should be able to pull the replacement image from a spritesheet frame

createFromObjects lets you do it
createFromTiles doesn't

thanks
j

**Comment by photonstorm** [comment]
I agree, but am not willing to change the API in order to add this argument in, sorry, as it would have to be inserted into the middle of the method call :(

The easiest solution is simply to set the frame on the Sprite that is returned.
