### ISSUE TITLE
2.4.4 Regression: Null Sprites Using Last Created Texture in WebGL

### ISSUE THREAD

**Issue by joelika** [photonstorm/phaser#2176]
I ran into this issue when I upgraded from Phaser 2.4.3 to 2.4.4. I use null sprites quite a bit to define hit areas over text, and in Phaser 2.4.4 I noticed that Phaser was using whatever the last created texture and displaying it on the null sprite instead of no texture.

Here's a test case with both a text sprite and some bitmap data:

https://jsfiddle.net/tanptet2/5/

Once the jsFiddle loads, you may have to hit "run" to see the duplicated textures.

In Phaser 2.4.3 and below, the null sprite would not have a visible texture of any kind.

**Comment by photonstorm** [comment]
This is fixed in the dev branch already. In the meantime you can resolve it by setting the `skipRender` parameter of the `__default` BaseTexture to `false`. You only need do this once.

**Comment by jmp909** [comment]
Duplicate issue https://github.com/photonstorm/phaser/issues/2173

**Comment by Tdnshah** [comment]
Hi all,
I am developing a game for a educational social cause using phaser.js. In this game i wanted to use a pop up after the player click on the submit button. The pop up will contain the correct answer if the student(i.e. player plays the game wrong) and if the player plays it right the a congratulations message to to be displayed in the pop up.

While searching for how to make popups in phaser i found this modals library i am trying to embedde this in myy game to show popup but i am unable to create and embed this.

This are things i tried till now :-

I had added the modal.js script in index.html

I used the function given at the usage section on this page but it dosen't work.

You can find my code at:- 
https://github.com/Tdnshah/Phaser-Pattern-Games/blob/a0f86ade77bdda8da2f69cca767e694a6befe974/src/game1.js

**Comment by jmp909** [comment]
Not a phaser framework issue @Tdnshah 

Please post on the html5gamedev forum
http://www.html5gamedevs.com/forum/14-phaser/

**Comment by Tdnshah** [comment]
Thanks for such a prompt reply
Opps sorry can i know any simple way to create popups in phaser @jmp909
