### ISSUE TITLE
No 'var' keyword before some variables in 'Making your first Phaser game' tutorial

### ISSUE THREAD

**Issue by mattiasahlsen** [photonstorm/phaser#2177]
There is no 'var' keyword for example in part4.html in the 'Making your first Phaser game' tutorial:

    //  The platforms group contains the ground and the 2 ledges we can jump on
    platforms = game.add.group();

I don't think this is intentional (creates global variable). This is also in the part5.html, on multiple places in the tutorial on the home page (http://phaser.io/tutorials/making-your-first-phaser-game/part3, http://phaser.io/tutorials/making-your-first-phaser-game/part4) and probably at more places).

**Comment by photonstorm** [comment]
If you look in the source you'll see it's already been declared as a global var before the `create` statement, so it's correct to not locally scope it within the function itself.

**Comment by mattiasahlsen** [comment]
Well, first of all, it hasn't been declared in part1.html. Second of all,
in part5.html, the player variable is never declared using var.

2015-10-29 14:08 GMT+01:00 Richard Davey <notifications@github.com>:

**Comment by photonstorm** [comment]
It's not used in part1, so doesn't need declaring there. It should be in part5 however (I can see it appears in part6 so is correct from that point on). Functionally the addition of it changes nothing because they are globally scoped variables anyway, but for consistency it should be in part 5.
