### ISSUE TITLE
Gamepad callbacks disabled when game is paused

### ISSUE THREAD

**Issue by ldurback** [photonstorm/phaser#2179]
When game.paused = true, all other input callbacks are still enabled, but the gamepad callbacks get disabled.

**Comment by photonstorm** [comment]
The Gamepads need to use a poll timer value in order to update themselves, and this won't update if the game is paused (so none of their callbacks can fire, because they are unable to determine the difference between now and their previous update).

**Comment by chrmitchell** [comment]
Is there any current workaround for a way to unpause a game with a gamepad?
