### ISSUE TITLE
Add typescript definitions to package.json for `tsd link`

### ISSUE THREAD

**Issue by mjohnsonengr** [photonstorm/phaser#2180]
I would suggest DefinitelyTyped definitions, but I would hardly be the first;
 * https://github.com/photonstorm/phaser/issues/1201 - you said you prefer to maintain your own type definitions.
 * https://github.com/borisyankov/DefinitelyTyped/pull/5214 - more recently it was attempted and abandoned due to sheer work required to meet DefinitelyTyped requirements.

Instead, I'd like to suggest something else that will let developers use tsd to get the type definitions from the npm package.  See here: https://github.com/DefinitelyTyped/tsd#link-to-bundled-definitions

I believe all that would be needed is a couple of extra lines in package.json.

With the go-ahead, I'd be willing to make this change myself!  I would link the "*.commends.d.ts" ones.

**Comment by mjohnsonengr** [comment]
An identical component could also be added to bower.json since Phaser also supports bower. :relaxed:

**Comment by iamfreee** [comment]
+1

**Comment by photonstorm** [comment]
Fixed in dev.
