### ISSUE TITLE
p2 - all world bounds break & collisions/collisiongroups need to be recreated after resizing game world

### ISSUE THREAD

**Issue by jmp909** [photonstorm/phaser#2183]
it appears all collision groups need to be recreated after resizing game world in order for world bounds to work again.. (including coming back from full screen) you can see here (instructions in code):

http://phaser.io/sandbox/SXKpakhM/play

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by sauthrully** [comment]
Hi,

I've read spmething worthy on the web and I think this is a very good idea for your business, take a look <http://trijipuba.jobsmastersinc.com/lnfeow>

Best Wishes, malaikat_benar@rocketmail.com
