### ISSUE TITLE
alphaMask with atlas image doesn't work in Chrome (but works Firefox/Edge)

### ISSUE THREAD

**Issue by jmp909** [photonstorm/phaser#2184]
code comment is the easiest way to explain it
single sprite: http://phaser.io/sandbox/tQdvKSjE/play
sprite generator function: http://phaser.io/sandbox/ovODiVRK/play

but in brief..
* load atlas sprite texture into bitmapdata
* create a bitmap fill
* mask fill with bitmapdata

doesn't work in Chrome on Windows. (if it's not an atlas frame it does work). 

the only way i've managed to get it to work is to set the maskedBMD to the stage size, but then the bitmapdata is much too large (it should just be the size of the sprite), and is therefore anchored incorrectly

thanks
j

**Comment by jmp909** [comment]
this can be resolved in Chrome for that example by setting height of the masked bitmap data to h*2, 

```javascript
maskedBMD = game.make.bitmapData(w,h*2); // fix for chrome: h*2, not h
var srcRect = {x:0, y:h/2, width:w , height:h};
maskedBMD.alphaMask(fillBMD,maskBMD, srcRect);
```

if anyone can explain why though, that'd be great thanks!

**Comment by photonstorm** [comment]
This must have been Chrome version specific, because it works fine now (thanks Google).

**Comment by jmp909** [comment]
confirmed... working for me in latest Chrome. thanks
