### ISSUE TITLE
BitmapData.copy blendMode is wrong type on Typescript definition file

### ISSUE THREAD

**Issue by brinca** [photonstorm/phaser#2188]
The parameter type for the blendMode argument of the copy(), copyRect(), draw() and drawGroup() methods of BitmapData are set to type "number" on the Typescript definition file, while the expected (and working) values are of type "string".

This is probably because it used to expect values from the PIXI.blendModes enumeration (which is number based), and now is using HTML5's globalCompositeOperation (a string value), but the type remains "number" in the definition file (the documentation states the type as "string" though).

It is easily fixed by updating the definition file (phaser.d.ts or phaser.comments.d.ts), replacing all instances where "blendMode" is "number" to either "string" or "any".

**Comment by milkey-mouse** [comment]
I just made a PR to fix this, thanks

**Comment by photonstorm** [comment]
Fixed via PR merge.
