### ISSUE TITLE
Phaser.Camera.setBoundsToWorld() does not work if camera bounds set to null

### ISSUE THREAD

**Issue by jounii** [photonstorm/phaser#2191]
As per documentation you can free camera movement out of bounds by setting camera bounds to null. This causes ScaleManager activated World.resize to fail when it calls Camera.setBoundsToWorld() which doesn't check validity when doing this.bounds.copyFrom(...).

**Comment by photonstorm** [comment]
Should be fine in dev branch:

```
        if (this.bounds)
        {
            this.bounds.copyFrom(this.game.world.bounds);
        }
```
