### ISSUE TITLE
.collide doesn't take in effect rotated sprites

### ISSUE THREAD

**Issue by McFarts** [photonstorm/phaser#2193]
Just noticed this. If you have 2 sprites in arcade body physics and change the rotation of 1 sprite, and then make it collide with the other sprite. (Even although, the rotated sprite visually isn't colliding with the sprite), it still collides since collide doesn't take in account of rotated sprites.

Would this be classified as a bug, suggested feature, or something intended? Just wondering, thx

**Comment by McFarts** [comment]
http://www.html5gamedevs.com/topic/6772-how-do-i-detect-a-collision-on-a-rotating-rect-sprite/

Sorry about this thread

**Comment by photonstorm** [comment]
Yeah use P2 physics for this.
