### ISSUE TITLE
How to propagate click event to parent of sprite?

### ISSUE THREAD

**Issue by yeluoqiuzhi** [photonstorm/phaser#2194]
when I click on spriteTop,can event of spriteBottom  be triggered too,how to do?this is my code: [sample](http://phaser.io/sandbox/FnJAJjLf).thank you

**Comment by McFarts** [comment]
priorityID I believe?

Check:

http://phaser.io/examples/v2/input/input-priority

**Comment by yeluoqiuzhi** [comment]
@McFarts set higher priorityID,only change the priority,and only one sprite dragging can be triggered.I want it can drag two sprite simultaneously.

**Comment by photonstorm** [comment]
Sorry but this isn't currently possible. It assumes one drag target at once only, you'd have to write custom code to move the other sprite as one moves.
