### ISSUE TITLE
Add way to control context.textBaseline in Phaser.Text

### ISSUE THREAD

**Issue by cloakedninjas** [photonstorm/phaser#2200]
It's hardcoded to `'alphabetic'` right now - any thoughts on leaving that as a default but allowing a `textStyle` property to override it?

**Comment by photonstorm** [comment]
Thank you for the suggestion. However this will not be implemented in Phaser, so I'm moving this request over to the Lazer feature request list instead. If you wish to submit a PR that isn't massively API breaking and that adds this feature to Phaser then we will consider merging it.
