### ISSUE TITLE
Sprite.right, .left, .top, .bottom properties change meaning when 'scale' is negative

### ISSUE THREAD

**Issue by carst3n** [photonstorm/phaser#2201]
The Sprite properties right, left, top, and bottom exchange meaning when 'scale' becomes negative. So, for example, Sprite.right will actually be the leftmost coordinate when scale.x is negative.

I'm aware that this might be intentional, but it sure was completely unexpected and had me stumped for a few minutes...

**EDIT:** Curiously, Sprite.width also becomes negative with a negative scale. I think I'll avoid a negative scale for now. But is this really the intended behavior?

**Comment by photonstorm** [comment]
The negative width is a Pixi trait I'm afraid. As for the properties you're right, but I'm reluctant to change it (as it's been like it for years) so will add a documentation comment instead.
