### ISSUE TITLE
motionState description confusion

### ISSUE THREAD

**Issue by McFarts** [photonstorm/phaser#2202]
```
motionState : number
The type of motion this body has. Should be one of: Body.STATIC (the body does not move), Body.DYNAMIC (body can move and respond to collisions) and Body.KINEMATIC (only moves according to its .velocity).
```

It says it should be a number, but in the description it's saying it should be `Body.STATIC` which is a string?

http://phaser.io/docs/2.4.4/Phaser.Physics.P2.Body.html#motionState

Do the numbers represent an index for the different Body's?
https://github.com/photonstorm/phaser/issues/563#issuecomment-37685681

**Comment by Cristy94** [comment]
`Body.STATIC` is a number. It is actually a variable. Defined something like `Body.STATIC = 2`, think like a C++ define or a static variable.

So, the `motionState` can be equal to `Body.STATIC` (define) but not with `"Body.STATIC"` (string).

**Comment by photonstorm** [comment]
Yeah it's a standard const (or as close to them as JS has)
