### ISSUE TITLE
Loader deleting waiting file from queue if asset pack is added after load has started

### ISSUE THREAD

**Issue by tfelix** [photonstorm/phaser#2203]
I tried to implement a "on-demand" load based around phasers loader when encountering this bug. Asset Packs should be loaded before other assets. The problem occures when I add lets say 2 image assets (bottle.png and apple.png) and afterwards an asset pack. The first image is marked as loading in this._fileList, the second one is waiting. When I add an asset pack right in this moment Loader searches for the first asset not yet loaded which is apple.png. This code is executed:

```
if (!file || (!file.loaded && !file.loading && file.type !== 'packfile'))
            {
                this._fileList.splice(i, 1, pack);
                this._totalPackCount++;
                break;
            }
```

The problem lies in  this._fileList.splice(i, 1, pack); according to JS API doc: http://www.w3schools.com/jsref/jsref_splice.asp the second parameter means how many items to be removed. This call will essentially replace the apple.png with the packfile array. I think it should be rather inserted. The correct call would be:

```
if (!file || (!file.loaded && !file.loading && file.type !== 'packfile'))
            {
                this._fileList.splice(i, 0, pack);
                this._totalPackCount++;
                break;
            }
```
Which wont delete any file from this array but rather put the asset pack stuff in between. Pushing my apple.png to the last position. An pull request is incoming.

**Comment by photonstorm** [comment]
Thanks for the PR. Merged.
