### ISSUE TITLE
Don't try to unlock audio on iOS when set to `disableAudio`

### ISSUE THREAD

**Issue by bcjordan** [photonstorm/phaser#2206]
When `window['PhaserGlobal'].disableAudio` or `SoundManager.prototype.noAudio`, we should avoid trying to unlock audio, as there may not be a `SoundManager.prototype.context` initialized.

*Temp. workaround*: set `window['PhaserGlobal'].disableWebAudio`.

(Low-impact issue since throwing from the touch handler doesn't stop any important code from running.)

**Comment by photonstorm** [comment]
This is now fixed in dev.
