### ISSUE TITLE
“No Physics” custom build lacks Tilemaps

### ISSUE THREAD

**Issue by rblopes** [photonstorm/phaser#2212]
The custom build configured with no physics engines included still lacks Tilemap and its related classes. I'm sure Arcade Physics were required to have Tilemaps working in the past, but physics support for Tilemaps is now split into its own module.

Is there any reason not to include Tilemaps in that build option yet?

**Comment by photonstorm** [comment]
I guess I could include Tilemaps even if you don't have any physics engines included, although to what end I'm not sure as it could only ever be used purely visually, which feels like a bit of an edge case to me.

**Comment by rblopes** [comment]
Yes, I get the point. I filed this issue because at the time I was asked why Tilemaps are missing in Phaser's "no physics build", but I don't know what he was trying to do. Thanks anyway.
