### ISSUE TITLE
PIXI pushMask: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by geros** [photonstorm/phaser#2213]
Phaser  2.4.4
I apply a rectangle mask out of graphic and i get this error when i use WEBGL  :

 ```javascript
Uncaught TypeError: Cannot read property 'data' of undefined
```
At 
```javascript
/**
* Applies the Mask and adds it to the current filter stack.
* 
* @method pushMask
* @param maskData {Array}
* @param renderSession {Object}
*/
PIXI.WebGLMaskManager.prototype.pushMask = function(maskData, renderSession)
{
    var gl = renderSession.gl;

    if(maskData.dirty)
    {
        PIXI.WebGLGraphics.updateGraphics(maskData, gl);
    }

    if(!maskData._webGL[gl.id].data.length)return;

    renderSession.stencilManager.pushStencil(maskData, maskData._webGL[gl.id].data[0], renderSession);
};
```

**Comment by stoneman1** [comment]
Have the same problem. Here is some data : 

![screen shot 2015-12-01 at 00 00 19](https://cloud.githubusercontent.com/assets/4244526/11487705/d3a5dedc-97c9-11e5-9730-f3ff79955030.png)
![screen shot 2015-12-01 at 00 04 59](https://cloud.githubusercontent.com/assets/4244526/11487712/e101cd2a-97c9-11e5-87c8-b29228438cb9.png)
![screen shot 2015-12-01 at 00 05 52](https://cloud.githubusercontent.com/assets/4244526/11487720/ed23d2b0-97c9-11e5-883e-97da38718d1e.png)
![screen shot 2015-12-01 at 00 02 26](https://cloud.githubusercontent.com/assets/4244526/11487747/2a0e001a-97ca-11e5-859f-de5131b5ecd3.png)

**Comment by geros** [comment]
I just made a terrible and unexplainable hack that made my code working. 
Similar situation as the one i opened the issue for same error.
So 
I had to mask a group of sprites so i gave :
```
var mask = this.game.add.graphics(0, 0);
mask.beginFill(0x000);
mask.drawPolygon(points);
mask.endFill();

this.add(mask); 
this.diceGroup.mask = mask;
```
The above resulted to the same error as initially reported when render is WEBGL (it works on CANVAS). 
When i give:
```
var mask = this.game.add.graphics(0, 0);
mask.beginFill(0x000);
mask.drawPolygon(points);
mask.endFill();
this.add(mask);

var sprite = new Phaser.Sprite(this.game, 0, 0);
sprite.addChild(mask);
sprite.visible = true;
this.add(sprite);

this.diceGroup.mask = mask;
```
it works like a charm on both CANVAS and WEBGL.

**Comment by photonstorm** [comment]
This is now fixed in the dev branch.
