### ISSUE TITLE
Marker stop loop with disableVisibilityChange when browser tab lose focus

### ISSUE THREAD

**Issue by lucap86** [photonstorm/phaser#2220]
with 
``stage.disableVisibilityChange = true;``

if i've an audioSprite's marker that is playing in loop and focus another browser tab the 
sound stop when the marker reach the end, 
it return to play when tab get focus again.

this happen also when browser winindow is minimized

Example:
https://www.dropbox.com/s/ujzh2nyy19xo6ar/soundTest.zip?dl=0

**Comment by imleyenda** [comment]
Maybe you need to force setTimeOut.

**Comment by lucap86** [comment]
Can u provide an example?

**Comment by imleyenda** [comment]
var config = {
	forceSetTimeOut: true,
	renderer: Phaser.AUTO,
	width: 1200,
	height: 800,
};

var game = new Phaser.Game(config);

**Comment by photonstorm** [comment]
It's entirely possible that the RAF callback that Phaser needs to update has been paused by the browser. When you swap tab you are at its mercy if / when it decides to pause RAF anyway. I have updated the documentation to mention this.
