### ISSUE TITLE
Filters don't work in Phaser.CANVAS mode. Intended behavior?

### ISSUE THREAD

**Issue by bvargish** [photonstorm/phaser#2223]
After countless hours trying to figure out why I couldn't get the ColorMatrixFilter to work I tried the Gray filter to find that it didn't work for me either. Examining the Phaser Gray filter example code I noticed that you used Phaser.WEBGL rather than Phaser.CANVAS which I was using in my game. Sure enough, I changed it and both filters worked. 

Is this intended behavior? If so, it would be nice to put a note at the top of the filters examples page stating that the filters will not work in Phaser.CANVAS mode so that others can avoid this pitfall. It would also be cool to have an example with the ColorMatrixFilter as it might be helpful to others. Thanks! :)

**Comment by drhayes** [comment]
Although it's frustrating to lose time on something like that, the Sprite#filters documentation says this first thing: "Sets the filters for the displayObject. IMPORTANT: This is a webGL only feature and will be ignored by the Canvas renderer."

**Comment by bvargish** [comment]
Doh! Of course it does!

I was looking at http://phaser.io/docs/2.4.4/Phaser.Filter.html (which does mention Phaser.CANVAS_FILTER) and http://phaser.io/examples/v2/category/filters only!

**Comment by photonstorm** [comment]
Filters are basically Shaders, and shaders are WebGL only I'm afraid. I have updated the docs to reflect this.

**Comment by lebronchin** [comment]
however, it does work for the Canvas on android system, why is that?
