### ISSUE TITLE
Modularising p2 usage

### ISSUE THREAD

**Issue by deiga** [photonstorm/phaser#2228]
Hey,

I just spent most of a day trying to get phaser to recognize an actual installatin of p2, which simply didn't work.
Why is p2 just sneaked into the source and not required like a proper module?

I suggest building in the require for p2 to make phaser more module friendly

**Comment by photonstorm** [comment]
Because Phaser 2 doesn't use modules at all, anywhere, and v2 of it never will. This is the main reason for the v3 rewrite.

**Comment by McFarts** [comment]
Not sure what the issue is.

using 
```
    //  Enable P2
    game.physics.startSystem(Phaser.Physics.P2JS);
```

We can enable P2, no need for modules.

**Comment by deiga** [comment]
@photonstorm Okay, that's something  I do understand. Is there somekind of timetable and documentation on the v3 rewrite? How could one chip in with that?

**Comment by photonstorm** [comment]
You can follow Phaser 3 (Lazer) development in its repo here: https://github.com/photonstorm/lazer
