### ISSUE TITLE
Webcam example does not work

### ISSUE THREAD

**Issue by ruslandzhumaev** [photonstorm/phaser#2229]
Hello!
I checked this example - http://phaser.io/examples/v2/misc/webcam - using Chrome and Firefox (Win7) and it seems that this example does not work.
Can you also check it?

**Comment by milkey-mouse** [comment]
Just went and looked, seems like the WebCam.js plugin that Phaser needs to do webcam stuff is missing and returning a 404 when Phaser tries to load it.

**Comment by ruslandzhumaev** [comment]
The problem was in the wrong path to the plugin. I solved it in this pull request: https://github.com/photonstorm/phaser-examples/pull/136
And btw sorry, I had to open this issue in phaser-examples, not here :)
