### ISSUE TITLE
Game Scale Example not working

### ISSUE THREAD

**Issue by JB-Tellez** [photonstorm/phaser#2230]
Hi Phaser folks,

I get blank screen and error at http://phaser.io/examples/v2/input/game-scale using Phaser 2.4.4

Here is the error in Chrome...
Uncaught TypeError: game.scale.setScreenSize is not a function

**Comment by luigimannoni** [comment]
`.setScreenSize()` is a deprecated method, try to replace it with `.updateLayout()`.

Small note for Phaser devs: please, please, please, do add warnings for deprecated methods instead of taking them out. There are lots of Phaser examples out in the web which still uses the < 2.0 methods.
