### ISSUE TITLE
New revive 2.4.4 multiplies health

### ISSUE THREAD

**Issue by netgfx** [photonstorm/phaser#2231]
Hello,

I had a Sprite with health 3 and not alive, when I call revive(3) the Sprite now has health = 9
I have no maxHealth defined, so I expected for this to leave the health as is, since it was not 0

Or is this supposed to work like this now that the "heal" function is taking place? If yes, then I will have to check whether or not the Sprite has 0 health before I revive it with the health argument, or to define a maxHealth property. Correct?

Thanks.

**Comment by bsparks** [comment]
The maxHealth is defaulted at 100. I can't imagine why it would multiply to 9. Maybe 6 as heal adds health, so if it already had 3, and the max is 100 then it will keep adding. Perhaps it got called twice to get to that 9.

**Comment by photonstorm** [comment]
Fixed in dev.
