### ISSUE TITLE
Multiple Tiled layers not loaded correctly due to loop variable reuse

### ISSUE THREAD

**Issue by ttencate** [photonstorm/phaser#2233]
Loop variable `i` is used for the outer loop:
https://github.com/photonstorm/phaser/blob/c9c85330ab60547b39ba4c9400c258ed7fb2a317/src/tilemap/TilemapParser.js#L227
and for the inner loop:
https://github.com/photonstorm/phaser/blob/c9c85330ab60547b39ba4c9400c258ed7fb2a317/src/tilemap/TilemapParser.js#L244
In the middle of a game jam right now, no time for a PR, but should be easy to fix :)

**Comment by photonstorm** [comment]
Fixed via merge.
