### ISSUE TITLE
Should pointerOver() stay true if touch is released over sprite?

### ISSUE THREAD

**Issue by bvargish** [photonstorm/phaser#2240]
Using the example at http://phaser.io/examples/v2/input/pointer-over, if I roll over the bunny on my iPad and lift my finger off of the screen shouldn't the bunny dim? I'm guessing this is not happening because activePointer refers to the most recently active Pointer object which still exists even after release. For my issue I was able to use game.input.totalActivePointers to create a workaround, but just wondering if this is intended behavior or not.

**Comment by photonstorm** [comment]
You could make it dim by listening for `sprite.events.onInputOver` and `onInputOut` instead of the way that example does it, which is to poll the `pointerOver` function, which isn't ideal for touch screens, but is fine for mouse.
