### ISSUE TITLE
Animation onUpdate callback skips frames

### ISSUE THREAD

**Issue by jeppester** [photonstorm/phaser#2243]
When using an onUpdate-listener it is unreliable to make the callback dependant on the current frame number, since frames might be skipped (based on animation and game FPS).

I know that this might not be considered a bug, but I think it's an issue that developers might easily face. In my case my game worked flawlessly until I ran it on a slow device with a poor FPS. From that point it was difficult to find out what the issue was.

I think the docs should flag this, so developers don't get caught off guard.

**Comment by photonstorm** [comment]
Docs updated.
