### ISSUE TITLE
deleteMoveCallback(moveIndex) in phaser 2.4.4

### ISSUE THREAD

**Issue by jalalimehdi** [photonstorm/phaser#2246]
hi
nice job
in phaser 2.4.4,
 game.input.deleteMoveCallback(moveIndex);
not working
but with phaser 2.3 is working

**Comment by photonstorm** [comment]
The correct method signature is: `deleteMoveCallback(callback, context)`

**Comment by klarafall** [comment]
Am Mittwoch, 3. Februar 2016 schrieb Richard Davey :

> Closed #2246 <https://github.com/photonstorm/phaser/issues/2246>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2246#event-536734550>.
>


-- 
Von Gmail Mobile gesendet
