### ISSUE TITLE
Numerical instability in Arcade Physics

### ISSUE THREAD

**Issue by rogual** [photonstorm/phaser#2254]
Hi, I came across this issue when colliding a sprite with a tilemap using Arcade Physics, with gravity. Sometimes, when the sprite is resting on a solid tile, the Y position of its physics body will not be constant but will oscillate between two close values every frame.

For instance, instead of coming to rest at Y=16, the value would oscillate between Y=15.99999999 and Y=16.00000003 each frame.

**Why is this a problem?**

I'm using the roundPixels option for that old-school look, but if the two values the body oscillates between are either side of an integer (as they often will be with integer-sized tiles), the jitter becomes magnified and the sprite is drawn at a different pixel position each frame, giving a blurred or flickering look.

**Steps to Reproduce**

The underlying numerical problem can be seen in the example: http://phaser.io/examples/v2/tilemaps/map-collide#gv although the default readout doesn't show enough decimal places. If you change the debug call in the render method to:

```game.debug.text(p.body.position.y, 32, 320);```

and jump about a bit you'll see the issue crop up. Although that example doesn't use scaling or roundPixels, you can imagine what the display would look like if it did.

**Workaround**

I did find one workaround which was to make sure the physics body had a Y offset ending in .5, meaning the common case of landing on a solid tile would not produce the effect. But, even with this workaround, the effect would probably still show up when colliding with other objects. (though I haven't tested this).

**Comment by photonstorm** [comment]
Almost certainly a result of floating point math (I'd suspect as a result of gravity applying a force to an object already settled.)

Feel free to submit a PR if you've got a bullet proof solution, otherwise it is what it is I'm afraid.

**Comment by thomasmolby** [comment]
Thanks for posting the workaround! I had the exact same problem and offsetting the collider box 0.01 keeps my sprite on the right side of the floor(), without noticeably affecting gameplay  :)
