### ISSUE TITLE
Typescript Emitter makeParticles definition

### ISSUE THREAD

**Issue by iamfreee** [photonstorm/phaser#2257]
Hi,

The currently version of the definition 2.4.4 in the repo of phaser.d.ts don't allow to call Phaser.Particles.Arcade.Emitter.makeParticles() without args but in the examples this works.

http://phaser.io/examples/v2/particles/particle-class

Also the particleClass property has a type of Phaser.Sprite when it should be any.

Thanks

**Comment by photonstorm** [comment]
This is now correct in the TS defs in the dev branch.
