### ISSUE TITLE
Question about Cache getImage

### ISSUE THREAD

**Issue by iamfreee** [photonstorm/phaser#2259]
Hi,

What is the concrete return type of game.cache.getImage("key")?

Phaser.CachedImage or Phaser.Image?

Because in typescript using the 2.4.4 definitions i cant cast this.game.cache.getImage("key") to Phaser.Image;

In definition it says CachedImage but in the website docs it says Image.

Thanks

**Comment by photonstorm** [comment]
It's an HTML Image object, or `null` if not found.
