### ISSUE TITLE
Add repeat param to Image/Texture

### ISSUE THREAD

**Issue by Lopdo** [photonstorm/phaser#2260]
It would be nice to be able to create image with tiled texture with just one param (boolean). When the width/height of the image is larger than the underlying texture, the texture would wrap around instead of scaling up.

I know there is TiledSprite, but it does not accept sprite sheet and seems to be targeted more towards infinite scrolling backgrounds than, for example progress bars

**Comment by photonstorm** [comment]
Thank you for the suggestion. However this will not be implemented in Phaser, so I'm moving this request over to the Lazer feature request list instead. If you wish to submit a PR that isn't massively API breaking and that adds this feature to Phaser then we will consider merging it.
