### ISSUE TITLE
getBounds() returns incorrect value for flipped images (scale.x = -1)

### ISSUE THREAD

**Issue by Lopdo** [photonstorm/phaser#2264]
I have a Phaser.Group object which contains image let's say 100x100. I want this image to be flipped horizontally so I set scale.x = -1. This however causes the group object to report width of 200 instead of 100, becaue bounds of the flipped image are returned as {0, 100, 100, 100}. Shouldn't getBounds() take negative scale into consideration when returning bounds of object?

**Comment by photonstorm** [comment]
I've tested this out tonight and I can't see an issue. The following code:

```
    var bob = game.add.group();

    bob.x = 0;

    var s = game.add.sprite(400, 0, 'einstein');
    // s.scale.x = -1;

    bob.add(s);

    console.log(bob.getBounds());
    console.log(bob.getLocalBounds());
```

It reports a bounds width of 640 (the size of the image) regardless of the scale.x or not on the sprite The only difference the scale makes is in the x coordinate of the local bounds.

Happy to re-investigate if you can provide a code sample demonstrating.
