### ISSUE TITLE
"Free" Lynda course requires a subscription

### ISSUE THREAD

**Issue by j127** [photonstorm/phaser#2266]
The [README](https://github.com/photonstorm/phaser/blob/master/README.md) says that Lynda has a free video course, but when I try to watch it, it looks like it needs a credit card for a subscription trial. If there is a way to watch it for free, maybe add specific instructions on how to do that, or indicate that it requires a credit card that will be charged if you don't cancel within 10 days? Even logging in with my LinkedIn account doesn't work.

**Comment by photonstorm** [comment]
True (they used to be free, part of a promotion I think) but I've removed the wording anyway.
