### ISSUE TITLE
Emitter quantity increases each time start is called

### ISSUE THREAD

**Issue by alexh00** [photonstorm/phaser#2268]
Within the start method of Phaser.Emitter, the quantity argument is added to the internal this._quantity property.

https://github.com/photonstorm/phaser/blob/master/src/particles/arcade/Emitter.js#L531

The value of this._quantity is otherwise never modified. This means that each time I call start I am further increasing the value of this._quantity. Surely the required functionality should be that the value of the argument I pass in is assigned directly to this._quantity rather than being added to it?

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
