### ISSUE TITLE
Emitter emitParticle could return the particle reference rather than a boolean

### ISSUE THREAD

**Issue by alexh00** [photonstorm/phaser#2269]
I guess this is a feature request not a bug.
If Phaser.emitter.emitParticle returned a reference to the particle that was created it would make it easier to extend the functionality of the emitter and particles which would be quite useful.
Currently it returns a boolean which is true if a particle was emitted, otherwise false. If emitParticle just returned the particle if it was emitted otherwise null, then all the conditional checks that are evaluating the boolean currently would continue to work.

**Comment by photonstorm** [comment]
Thank you for the suggestion. However this will not be implemented in Phaser, so I'm moving this request over to the Lazer feature request list instead. If you wish to submit a PR that isn't massively API breaking and that adds this feature to Phaser then we will consider merging it.
