### ISSUE TITLE
inputEnabled=false doesn't affect hitArea property

### ISSUE THREAD

**Issue by bymafmaf** [photonstorm/phaser#2270]
Hi,
I've been struggling with hitArea property because my game is mobile I need it for convenience. The problem was when player drags a sprite to somewhere in screen, game makes that sprite's inputEnabled property false. But, still its hitArea property overlaps with others and others' hitArea gets covered so that overlapping area cannot be used at all.

So, inputEnabled=false should make hitArea null or some other mechanic that would fix this problem.

and that took me 2 weeks and I couldn't send the game to App Store before Christmas, cost was a bit too much :(

**Comment by photonstorm** [comment]
I need to see a test case demonstrating this. If a Sprite has its input disabled, then it doesn't matter if it has a hitArea set or not, it's never actually used by Phaser.

**Comment by photonstorm** [comment]
Closing due to several months of inactivity. A stand-alone running code example is needed to investigate this further.
