### ISSUE TITLE
Documentation error in Tilemap.addTilesetImage

### ISSUE THREAD

**Issue by tsphillips** [photonstorm/phaser#2271]
There is a documentation error in Tilemap.js, for Tilemap.addTilesetImage.

Lines https://github.com/photonstorm/phaser/blob/master/src/tilemap/Tilemap.js#L256 and https://github.com/photonstorm/phaser/blob/master/src/tilemap/Tilemap.js#L257 are incorrect.  Both arguments (tileMargin and tileSpacing) default to zero and are not the width and height as indicated in the comments.

    * @param {number} [tileMargin=0] - The width of the tiles in the Tileset Image. If not given it will default to the map.tileWidth value.
    * @param {number} [tileSpacing=0] - The height of the tiles in the Tileset Image. If not given it will default to the map.tileHeight value.

**Comment by photonstorm** [comment]
Fixed in dev.

**Comment by gregkleintv** [comment]
PLEASE STOP EMAILING ME/INCLUDING ME IN THIS CRAP.


________________________________

**Comment by photonstorm** [comment]
@gregkleintv you're receiving notifications because _you_ chose to 'Watch' this repo. We cannot remove you because it's a setting in _your_ user account. Just un-watch the repo and it'll stop. Beginners guide to GitHub has more details about it.
