### ISSUE TITLE
Lag on tilemap when camera move

### ISSUE THREAD

**Issue by aurys123** [photonstorm/phaser#2273]
I have same lag on camera move like this one http://examples.phaser.io/_site/view_full.html?d=tilemaps&f=sci%20fly.js&t=sci%20fly&phaser_version=dev&

**Comment by MrDallOca** [comment]
I've had a simlar problem when running it in android (lollipop). I don't know why, but with tiledmap the camera totally stops working (I was using camera follow). If it's continues like this, there's no way to make my project with phaser (but I'm really loving work with).

**Comment by Teelord** [comment]
I'm having the same issue. My map is 92x92 and ran at ~60fps on 2.2.2. In 2.4.4, the fps drops to 5-15 when the map is scrolling. I'm using 2 layers on my tilemap, Arcade physics and auto render on Chrome.

**Comment by photonstorm** [comment]
We've made a number of optimisations to the way TIlemaps render and are updated in 2.4.9 (currently in the dev branch), and a lot of fixes to how Sprites are followed by the Camera.

We're also working on a new WebGL shader for rendering Tilemaps, which you can find in its own branch on the main repo. I'll leave this one open for now, until the new WebGL renderer lands, but it should be a lot better than before with 2.4.9.

**Comment by photonstorm** [comment]
Ok I'm closing this one off (finally, yay!) as the new WebGL Tilemap renderer is now included in Phaser 2.7.0 in the dev branch, and I would like that build to be tested against this.
