### ISSUE TITLE
convertTilemap function needs to be baptized

### ISSUE THREAD

**Issue by McFarts** [photonstorm/phaser#2278]
```
    * The slopeMap parameter is an array that controls how the indexes of the tiles in your tilemap data will map to the Ninja Tile IDs.
    * For example if you had 6 tiles in your tileset: Imagine the first 4 should be converted into fully solid Tiles and the other 2 are 45-degree slopes.
    * Your slopeMap array would look like this: `[ 1, 1, 1, 1, 2, 3 ]`.
    * Where each element of the array is a tile in your tilemap and the resulting Ninja Tile it should create.
```

Holy cow batman, so if we have a map with over 5,000+ tiles, we have to use 5,000 more integer's to apply a slopeMap? Why not just supply the specific tile id's in your map through an object with the slope id as a property instead?

For example I want to map the 45 degree slope to tile index's 4, 10, 220.

```
slopeMap = {
4: 3,
10: 3,
220: 3
}
```

But instead, we have to do this:
```
[0,0,0,3,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...to 220 integers].
```

**Comment by McFarts** [comment]
It's because I think we're using hasOwnProperty which grabs the index from an array since we're not using an object for `slopeMap` (the function is accepting an array).

**Comment by photonstorm** [comment]
PR or it doesn't happen, sorry :)

**Comment by klarafall** [comment]
Am Mittwoch, 3. Februar 2016 schrieb Richard Davey :

> PR or it doesn't happen, sorry :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2278#issuecomment-178893225>
> .
>


-- 
Von Gmail Mobile gesendet
