### ISSUE TITLE
Building Phaser without tweens throws an error in StateManager

### ISSUE THREAD

**Issue by RetrocadeNet** [photonstorm/phaser#2283]
I tried to custom build phaser with the following settings:

    grunt custom --exclude tweens,flexgrid,arcade,ninja,p2,particles,creature,video

And phaser would report an error on the following line in `StateManager.js`:

    this.game.tweens.removeAll();

The error was `undefined is not a function`.

**Comment by photonstorm** [comment]
Fixed via PR merge, thank you.
