### ISSUE TITLE
Right click in Chrome prevents future mouse events.

### ISSUE THREAD

**Issue by KyleU** [photonstorm/phaser#2286]
Steps to reproduce:
- Open http://phaser.io/examples/v2/input/drag in Chrome.
- Right click anywhere on the canvas.
- Attempt to drag sprite.

The sprite will follow the mouse forever, as no inputUp is generated.

This demonstrates the issue with enableDragDrop, but the issue appears with raw event handling as well. You will receive a single mouse down event after the right-click's onInputUp, but no further inputUp or inputDown events anywhere in the canvas.

I've tried to repro this in a few other frameworks and couldn't reproduce it, but if it turns out to be a general Chrome issue, I'd be glad to submit it there.

**Comment by KyleU** [comment]
The following code will demonstrate this issue (can't figure out how to save/share Phaser Sandbox projects):

```
var lastGlobalUpdate = 'No global input yet.';
var lastSpriteUpdate = 'No sprite input yet.';

function preload() {
  game.load.baseURL = 'http://examples.phaser.io/assets/';
  game.load.crossOrigin = 'anonymous';
  game.load.image('logo', 'sprites/phaser-dude.png');
}

function create() {
  game.input.onDown.add(function(e, p) {
    lastGlobalUpdate = 'Global Input Down: ' + p.button;
  });  
  game.input.onUp.add(function(e, p) {
    lastGlobalUpdate = 'Global Input Up: ' + p.button;
  });

  var sprite = game.add.sprite(300, 300, 'logo');
  sprite.inputEnabled = true;
  sprite.anchor.set(0.5);
  sprite.events.onInputDown.add(function(e, p) {
    lastSpriteUpdate = 'Sprite Input Down: ' + p.button;
  });  
  sprite.events.onInputUp.add(function(e, p) {
    lastSpriteUpdate = 'Sprite Input Up: ' + p.button;
  });
}

function render() {
  game.debug.inputInfo(32, 32);
  game.debug.text(lastGlobalUpdate, 32, 120);
  game.debug.text(lastSpriteUpdate, 32, 150);
}
```

You can left-click the sprite and see up/down event, but once you right-click the canvas, a single mouseDown will register, then no further sprite events will be generated (though global events still work).

**Comment by KyleU** [comment]
Looks like this doesn't affect Phaser 2.2: http://output.jsbin.com/vufiqanari

**Comment by nexiuhm** [comment]
Not able to reproduce it, neither in the phaser example or your jsbin. Hmm, chrome version?

**Comment by KyleU** [comment]
47.0.2526.106 (64-bit) on OS X.

It might be Mac-specific? It's not just me, I've gotten hundreds of bugs reports. If it helps, I just found out that the issue "repairs" itself once the browser loses focus. In other words, after right-clicking, the sprite will stick to your mouse and no mouse events are handled. If you then Cmd-Tab to another application and come back, mouse events work normally.

**Comment by KyleU** [comment]
Oh, and yes, the JSBin is supposed to work, it uses some ancient version of Phaser. But if you replace it with 2.4.2 or higher, the JSBin stops working.

**Comment by nexiuhm** [comment]
Weird stuff, especially if it's mac specific. I should note that whenever I do i right click I will get the chrome dropdown menu (save picture as... etc ) But it does register the click still. Tried all version of phaser from 2.0.0 to 2.4.4 and I have not noticed it even once.

**Comment by KyleU** [comment]
Yeah, I just checked on a Ubuntu Chrome, and it worked fine, must be Mac
specific then. Couldn't find anything in Chrome's bug tracker... no real
pressure, I've downgraded to 2.4.1 and everything seems to be working.

**Comment by dchernokur** [comment]
I can confirm this bug with Mac osx 10.11.2 and Chrome Version 47.0.2526.111 (64-bit)
All versions of phaser after 2.4.1

**Comment by photonstorm** [comment]
Confirmed this is OS X only.

**Comment by enriqueto** [comment]
I used phaser 2.4.0 on my latest game (a solitaire) because of this

**Comment by photonstorm** [comment]
This was a super-nasty one to fix, but fix it I have. Chrome OS X doesn't fire any mouseup events if the context-menu is open. In fact the only event it fires is 'mouseout' on the window object. So I now hijack that and use it to do what's needed here. Seems to be working fine now for me on OS X and is pushed to dev branch.

**Comment by TolgaND** [comment]
The problem is back with the newest update!
