### ISSUE TITLE
Bitmap Draw Doesn't include Destination Parameters

### ISSUE THREAD

**Issue by McFarts** [photonstorm/phaser#2288]
Go here:

http://phaser.io/docs/2.4.4/Phaser.BitmapData.html#draw

`draw(source, x, y, width, height, blendMode, roundPx)`

You forgot to include the most important parameter's that are used to clip bitmapdata (Health Orbs for example):

![](https://i.gyazo.com/bf92f880d1202821d8aea721389ea234.png)

We need support for the other 4 parameter's for `drawImage`
```
x	The x coordinate where to place the image on the canvas 
y	The y coordinate where to place the image on the canvas 
width	Optional. The width of the image to use (stretch or reduce the image)	 
height	Optional. The height of the image to use (stretch or reduce the image)
```

**Comment by nexiuhm** [comment]
The x, y, width, height, parameters in Phaser actually is the destination parameters. No parameters are set for the source since this is automatically found in the source displayObject. 

So to clarify :

```
draw(source, x, y, width, height, blendMode, roundPx)
```

Could be thought as the same as:

```
draw(source, dx, dy, dw, dh, blendMode, roundPx)
````

**Comment by photonstorm** [comment]
It automatically works this out for you based on the object given.

If you need more fine-grained control then use `BitmapData.copy` instead.
