### ISSUE TITLE
What is Group.z supposed to do?

### ISSUE THREAD

**Issue by staff0rd** [photonstorm/phaser#2290]
In the following code, the `z` values have no affect on the order the sprites are rendered.

    var group1 = this.add.group();
    group1.z = 0;
    group1.add(new Phaser.Sprite(this,0,0, 'mysprite'));

    var group2 = this.add.group();
    group2.z = 1;
    group2.add(new Phaser.Sprite(this,50,50, 'mysprite'));

The only thing that affects the order is by switching the order the above groups are `add`ed in.  As such, what is the purpose of `z` if not to change the rendering order?

**Comment by nexiuhm** [comment]
Group.z is a read-only property that has no side effects.  If you want to swap the order of groups you will have to use it's parent object ( which would be game.world if nothing else is specified ):

```
var group1 = this.add.group();
this.world.bringToTop(group1);
group1.add(new Phaser.Sprite(this,0,0, 'mysprite'));

var group2 = this.add.group();
this.world.bringToTop(group1); // group 2 is now rendered ontop
group2.add(new Phaser.Sprite(this,50,50, 'mysprite'));
```

**Comment by staff0rd** [comment]
Ah I see.  The [example](http://phaser.io/examples/v2/groups/group-as-layer) implies it should be used -   Is setting it achieving anything, or is the example just old?  The way Group.cs is structured it looks like it just exposes all its variables, when rather it looks like z should be hidden and just exposed via a function getter or similar.

**Comment by nexiuhm** [comment]
It achives nothing and setting it might even lead to errors. This is true for Sprites, text etc aswell, so its a consistant thing. The parent is the "manager" of children z values using functions like ``` bringToTop(c) ```
That example is either old or just a bad example to begin with : p

**Comment by photonstorm** [comment]
The example was incorrect originally, and remains so. I'll nuke it (I never actually created it, was just a PR I accepted and should have checked more carefully).

The `z` property is used internally for ordering, but isn't meant for 'public' use.
