### ISSUE TITLE
Add API for _totalFileCount

### ISSUE THREAD

**Issue by McFarts** [photonstorm/phaser#2294]
Just spent about 2 hours trying to figure out how to get the total amount of queued files.

http://phaser.io/docs/2.4.4/Phaser.Loader.html#totalLoadedFiles

None of these methods give us the _totalFileCount, they either change dynamically or give us the 'loaded' amount.

I suggest we add the  _totalFileCount method to the api page, which we can already call using `game.load._totalFileCount`.

 

Thanks!!

**Comment by photonstorm** [comment]
The total amount of _queued_ files is `Loader.totalQueuedFiles`, which of course will change if the load has been started (as will the total held in `totalLoadedFiles`. Add the two together, at any point, and you've got the total number of files in the Loader, regardless of their state.

**Comment by McFarts** [comment]
Yeah good idea. I guess I need to expand my brain a bit more and utilize what I already have.
