### ISSUE TITLE
Add method on Group for getting object with max/min of a key (i.e. health)

### ISSUE THREAD

**Issue by nickcarenza** [photonstorm/phaser#2295]
Usage example:
`group.getMax('health')`
Maybe to make it clear what the user wants returned we could use a second param like other methods do:
`group.getMax('health', RETURN_CHILD)`
`group.getMax('health', RETURN_VALUE)`

**Comment by photonstorm** [comment]
Thank you for the suggestion. However this will not be implemented in Phaser, so I'm moving this request over to the Lazer feature request list instead. If you wish to submit a PR that isn't massively API breaking and that adds this feature to Phaser then we will consider merging it.
