### ISSUE TITLE
**Warning** .progress false positive's

### ISSUE THREAD

**Issue by McFarts** [photonstorm/phaser#2296]
Okay Rich. I've been stuck on trying to isolate this bug for about 3 hours now, I finally got it and created a jsfiddle:

http://jsfiddle.net/Dillybob/J5fUE/227/

Check the console.

For some odd reason when you use `game.load.image` Phaser doesn't send a signal to `loadUpdate` thus, the progress it receives is only 50% and not 100%.

**Comment by stoneman1** [comment]
Not really a bug.. The thing is when its done loading it does not perform loadUpdate but it does perform loadCompleted. So the last % and so on can be read on the loadCompleted function

**Comment by nexiuhm** [comment]
But isnt this weird though ? I'm thinking its logical for loadUpdate to be updated for every "tick" , it going to 100 is also a update so to say.

**Comment by photonstorm** [comment]
Yeah I agree it makes sense to call `loadUpdate` one final time here, so will merge this in.

**Comment by McFarts** [comment]
Oh wow, thanks Rich.
