### ISSUE TITLE
AnimationManager#stop(name) does not work as described

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#2299]
> If a name is given that specific animation is stopped […]

In fact if you pass the name of any existing animation, the function [stops the current animation (no matter which it is) and then loads the named animation](https://github.com/photonstorm/phaser/blob/db641ca82e608470bd7902de3447d048d9715ab5/src/animation/AnimationManager.js#L311).

**Comment by nexiuhm** [comment]
Nice catch. You should do a PR :+1:

**Comment by photonstorm** [comment]
Fixed via the PR, thank you.
