### ISSUE TITLE
Config Object + Antialias

### ISSUE THREAD

**Issue by amadeus** [photonstorm/phaser#2302]
It appears that the antialias property can never be set to `false` if a config object is provided on `Phaser.Game` instantiation because only a truthy value of `config.antialias` is checked and therefore `false` will always be ignored.

https://github.com/photonstorm/phaser/blob/master/src/core/Game.js#L480-L483

**Comment by photonstorm** [comment]
True, same happened for transparent as well. Fixed in dev.

**Comment by amadeus** [comment]
Thanks!
