### ISSUE TITLE
Where did the custom build with Ninja physics enabled go?

### ISSUE THREAD

**Issue by rlenders** [photonstorm/phaser#2306]
I understand the physics engine is not included by default, but it seems somewhere during Phaser 2.3 the custom build folder no longer contains a build with ninja physics. Is it gone now, not coming back? And why?

**Comment by McFarts** [comment]
Not sure, but I was using Ninja Physics and found so many bugs in there  I just switched to `p2` and never looked back :)  I think it might have been removed or forgotten about from the compiling process based on it's poor performance

**Comment by clark-stevenson** [comment]
I am pretty sure I read that the original authors kind of gave up on it and so it was removed for the above reason. Although do not quote me.

**Comment by rlenders** [comment]
So I guess you could say the ninja physics implementation was by no means a viable engine to use for game development?

**Comment by photonstorm** [comment]
I don't intend to include a pre-built version of it any more, no. It's easy enough to use the custom build option to make one with it in imho.
