### ISSUE TITLE
Tweening listener's w/ HTML 5 Page Visibility

### ISSUE THREAD

**Issue by McFarts** [photonstorm/phaser#2309]
I'm not sure if this was intended or not because I have no idea how the page visibility API works.

But, when you tween something for like 2 seconds, then right when you start, go to a different tab, then come back and if that tween had any `onUpdateCallback` or `onComplete` callbacks assigned to it, they don't fire.

Any work around to this? 

Basically, is it possible to have the game render (or keep tweens running) when that browser tab is not active.

You can see this effect when you set a tween and assign it a `onUpdateCallback` and press F12 and then when the tween starts click on the dev console (or anywhere outside of the game canvas) and the tween stops.

Weird or is just how it's supposed to work? I'm trying to find a way to keep the tween's running even if not active

**Comment by McFarts** [comment]
The problem is not really a problem, but well sorta.

Pixi's rendering engine is based upon requestAnimationFrame, thus, when leaving the browser or tab this cancels the requestAnimationFrame signal. Thus, if you have callback handler's assigned to your tween, those will fire, but at the wrong times (when you alt tab back), thus this is what is happening.

My solution is to switch to setInterval / setTimeout tweening functions, I am trying http://jeremyckahn.github.io/shifty/dist/doc/classes/Tweenable.html#method_setScheduleFunction this one for now.  If anyone else had this problem hope this helps.

Also, I just WISH, JUST WISH that we could somehow keep requestAnimationFrame running 100% of the time.  There is no way though :(  Anyways, all I got for this

**Comment by drhayes** [comment]
The thing you are asking for is the exact thing requestAnimationFrame was implemented to solve:

  1. stop animations when the browser tab is not in focus.
  2. give the browser a chance to tell us when the best time to animate things is.

Even setTimeout and setInterval, in Chrome, drop to around 1 fps in the background anyway. Not all browsers do this, though, so that's not reliable.

I'm not sure why you want to tween something smoothly in the background when the user can't see it. What problem are you trying to solve here?

**Comment by McFarts** [comment]
@drhayes  I just posted this here: https://github.com/atom/electron/issues/4179#issuecomment-173633113

Since I was trying to get this enabled in electron, maybe a custom V8 build or something. But my problem is in that post, 3rd paragraph.

**Comment by drhayes** [comment]
Ah, a game in electron. This is relevant to my interests. :)

> My game receives ticks from the server to update the user's hp accordingly. The tick they receive is every 1 second with the new hp regeneration amount. This values get's SENT to a tween function in Phaser that then uses drawImage to render my HP orb graphic to make it feel like it has that 'regeneration' effect of gaining health.

When you get a tick from the server, what receives it? Does it *have* to be the tween function? I'm pretty sure the event loop is still running in that background tab so if it were implemented as an XHR/fetch callback or an `onmessage` callback I bet the value would still update.

As for the graphics being messed up... I got nothin'.

**Comment by McFarts** [comment]
Yeah, I didn't really explain my problem. I'm just pretty heated atm that's all.  Yeah, the thing is, I mean,  I could set my gameserver on node to run every 16ms and update the hp values so it makes it seem like it's animated.  But that's just silly.  I figured just send the hp reg amount every 1 second and make it tween client side so it seems like you're actually regenerating health.

So yeah, I have to have it be tweened. I think what would fix it if the tween method signal'd a callback that the tween has died or something.  That way, I can just use a callback on that and set the HP amount to whatever  (when the user alt-tabs back to the browser).  I'm going to make a suggestion now

**Comment by McFarts** [comment]
Bad design by me.

Because if there is game lag with requestAnimationFrame, it will cause the same issues. I need to store the REAL amount of the total amount of HP in a temporary object, and then use that to update the player's HP when they come back in focus (clicking on the tab). I can use this https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API 

Then, when that player has came back (all the tween's have failed, etc) use the temporary object with their real hp amount in there and restore their HP! 

Boom!

**Comment by McFarts** [comment]
@drhayes 

I switched to a setInterval Web-worker tween. Get's run in  another thread even though you're not active in the tab, works fine.   Just a heads up

**Comment by drhayes** [comment]
That's very good to know; thanks for circling back around. :smile_cat:
