### ISSUE TITLE
Line.rotateAround mistake in documentation.

### ISSUE THREAD

**Issue by Alaxe** [photonstorm/phaser#2310]
In the [Docs](http://phaser.io/docs/2.4.4/Phaser.Line.html#rotateAround) `Line.rotateAround` is missing some parameters (the coordinates `(x, y)` of the point to rotate around) . It should be `rotateAround(x, y, angle, asDegrees)`, but it's documented as `rotateAround(angle, asDegrees)`. These parameters are apparent in the source code of both the [dev](https://github.com/photonstorm/phaser/blob/dev/src/geom/Line.js#L130) and the [mater](https://github.com/photonstorm/phaser/blob/v2.4.4/src/geom/Line.js#L130) branches.

If someone explains to me how the docs are generated, I'll create a Pull Request, fixing the issue. (I guess it has something to do with the `/** ... */` comments before the function definition, but then how you turn them into HTML?).

**Comment by photonstorm** [comment]
Fixed in dev.

And for future, all you need do is change the js source. The docs html is auto-generated at build time (you don't need to do it)
