### ISSUE TITLE
bug in the arcade physics engine

### ISSUE THREAD

**Issue by flashspys** [photonstorm/phaser#2312]
We discovered a bug in the arcade physics engine, specifically in the `updateMotion` function. When gravity is disabled, the fact that the velocity is calculated separately for each axis causes the sprite to decelerate incorrectly if the velocities along the two axes are different.
You use the following code:
```
body.velocity.x = this.computeVelocity(1, body, body.velocity.x, body.acceleration.x, body.drag.x, body.maxVelocity.x);
body.velocity.y = this.computeVelocity(2, body, body.velocity.y, body.acceleration.y, body.drag.y, body.maxVelocity.y);
```
if velocity.x is 10 and velocity.y = 1000 then velocity.x is reaches 0 much faster than velocity.y causing the sprite to decelerate in an arc.

The common way to decelerate is to multiply the vector with something < 1. E.g.:
`body.velocity.multiply(0.9, 0.9);`
If you execute this if acceleration is 0, the deceleration will be correct (in a zero gravity environment).

I only work in a zero gravity environment (spaceship shooter 8-) ) so someone with "gravity experience" should fix this.

**Comment by photonstorm** [comment]
While I agree with this, I cannot change it. It has worked like this for years, i.e. devs are used to it and it would fundamentally change games if it was implemented.

It's trivial for you to replace the `computeVelocity` method your own should you require an alternative approach.
