### ISSUE TITLE
Unwanted smoothing (sprite.smoothed = false)

### ISSUE THREAD

**Issue by sergey7c4** [photonstorm/phaser#2317]
I used Chrome 48, IE 11, and Edge.
Example: [phaser pixel art example.zip](https://github.com/photonstorm/phaser/files/115351/phaser.pixel.art.example.zip)

**Comment by photonstorm** [comment]
Sorry but I need an example uploaded somewhere I can run.

**Comment by sergey7c4** [comment]
https://jsbin.com/quqakonuqo/edit?html,output

**Comment by djmittens** [comment]
I have also been running into this issue for a while, but i decided that this approach works the best to turn the smoothing off globally 
```
Phaser.Canvas.setImageRenderingCrisp(game.canvas)
```
Works in the latest stable chrome.

from #1586

**Comment by ForgeableSum** [comment]
I've also run into this issue quite often. It seems Chrome does not want to respect smoothing regardless of what you have the property set. Sometimes it works, sometimes it doesn't. It's odd! I think it must be a Chrome bug.

**Comment by photonstorm** [comment]
The fix for this is now merged into dev.
