### ISSUE TITLE
Unoptimizable code using arguments

### ISSUE THREAD

**Issue by tsphillips** [photonstorm/phaser#2319]
The below expressions cannot be optimized by the V8 engine.

```
./core/PluginManager.js:55:        var args = Array.prototype.slice.call(arguments, 1);
./gameobjects/GameObjectCreator.js:417:        var args = Array.prototype.slice.call(arguments, 1);
./gameobjects/GameObjectFactory.js:534:        var args = Array.prototype.slice.call(arguments, 1);
./utils/ArraySet.js:171:        var args = Array.prototype.slice.call(arguments, 1);
```

I do not think the engine is able to optimize because the arguments variable is leaked out of the function.

Is the below code a suitable replacement?

```
var args = new Array(arguments.length-1);
for(var i = 1; i <= args.length; i++) {
     args[i-1] = arguments[i];
} // for i
```

**Comment by photonstorm** [comment]
Given how this doesn't happen in any 'hot' areas I'm dubious it really matters at all. Obviously it would be great if V8 could optimize everything, but if it can't handle a couple of functions that are called quite rarely anyway then I really don't mind too much. Submit a PR if you disagree strongly.
