### ISSUE TITLE
Phaser & browserify dont work !

### ISSUE THREAD

**Issue by Flotruche** [photonstorm/phaser#2322]
Hello, I've tried to use Phaser with NPM/Browserify, but when I require Pixi, p2 and Phaser on global variable, I have this error: 

`TypeError: PIXI.CanvasPool is undefined`

Yet, I've used the same version of Pixi and p2 as Phaser build.

**Comment by drhayes** [comment]
Check out #2131.

**Comment by photonstorm** [comment]
You cannot use Pixi and P2 from npm along with Phaser. You have to use the version of Pixi that Phaser includes with it, as it's heavily customised. Also, see the issue linked above.
