### ISSUE TITLE
Sprite width and height is different if the image is in .gif format

### ISSUE THREAD

**Issue by SVasilev** [photonstorm/phaser#2324]
Hello,
I noticed that if you create two sprites, where one has .png image in the constructor and the other has a .gif image in the constructor the width is different. No matter you set pngSprite.width = 200, and gifSprite.width = 200, the result in the width is still different.
I don't know if this is intended to be that way. The .gif image is transparent if that makes any difference.
Notice: I had to conclude that formula:
pngSprite.width = gifSprite.width * 0.65;
pngSprite.height = gifSprite.height* 0.47;
Here is an example:
[gifBug.zip](https://github.com/photonstorm/phaser/files/119816/gifBug.zip)
Regards,
Stefan

**Comment by photonstorm** [comment]
Your images are not the same size.

Open the PNG into Photoshop and it's 239x159.
Open the GIF into Photoshop and it's 360x324.

Screen shot of Photoshop showing this: https://www.dropbox.com/s/zta2luf5cswd4tg/Screenshot%202016-02-07%2012.17.05.png?dl=0
