### ISSUE TITLE
Phaser.Color formats mismatch

### ISSUE THREAD

**Issue by mainpsyhos** [photonstorm/phaser#2327]
Some functions use alpha-chanel as 0-1 float number. Other functions use alpha-chanel  as 0-255 integer.
Example   Phaser.Color.hexToRGB:
step 1: prsing string via Phaser.Color.hexToColor
step 2: creating object via Phaser.Color.createColor with default alpha = 1(float) end extending rgb
step 3: converting to packed integer via Phaser.Color.getColor32
Function getColor32 recives alpha=1, but it requires integer value = 255.

**Comment by photonstorm** [comment]
Fixed in dev.
