### ISSUE TITLE
Using strings as game width/height throws error ( 2.4.5 RC1 )

### ISSUE THREAD

**Issue by nexiuhm** [photonstorm/phaser#2329]
Not entirely sure if this feature was removed for 2.4.5 , if thats the case docs should be updated to reflect this! : )

----

**Error:**
``` Argument 3 of CanvasRenderingContext2D.getImageData is not a finite floating-point value. ```

**Stack:**
c.BitmapData (phaser.js:47748)
c.GameObjectCreator.bitmapData (phaser.js:46800)
c.Utils.Debug.boot (phaser.js:77205)
c.Game.boot (phaser.js:34435)
c.Device._readyCheck (phaser.js:58179)

**Comment by photonstorm** [comment]
Fixed in dev.
