### ISSUE TITLE
[pixi 3] this.texture.frame.resize is not a function

### ISSUE THREAD

**Issue by noidexe** [photonstorm/phaser#2330]
I was testing the pixi 3 branch and this is the error I got when trying to resize a tilemap. Built from 3bb918bdba868c0f15e923cc378a8231b1aba82b using ```grunt arcadephysics```
```Javascript
Phaser.TilemapLayer.prototype.resize = function (width, height) {

    this.canvas.width = width;
    this.canvas.height = height;

    this.texture.frame.resize(width, height);  // <--- Uncaught TypeError: this.texture.frame.resize is not a function
```

**Comment by photonstorm** [comment]
Thanks for this. I'm going to close it off as I don't intend to continue the Pixi v3 branch any longer (I will instead use Pixi v4)
