### ISSUE TITLE
Quite laggy tween

### ISSUE THREAD

**Issue by Deshtructioner** [photonstorm/phaser#2332]
Hey there,

I have huge problem with making tweens smooth in my game. I've already made about 10 games with Phaser and had zero problems with tweens there.

Anyhow, I'm trying to make a game, where clouds move up/down/left/right a bit in the sky but (I think) the problem is that I want them to move for about 75px in 10.000ms (10s), which is really slow movement but that might be the problem there. 
On the other hand, I've already made first version of that game (almost the same) and tweens work there normally (same distance, same duration!). Don't know what the problem could be here, I've more or less copy&pasted code from v1 to this version. 

I've already tried 
- FPS is always 60

CREATE:
- `game.camera.roundPx = false;` -> no improvement
- tweens are created that way:

`var xPos = originalCloudPositions[i][0] + Math.random() * (-150) + 75;
var yPos = originalCloudPositions[i][1] + Math.random() * 50;
tweens[i] = game.add.tween(clouds[i]).to({x: xPos, y: yPos}, cloudTweenTime, "Linear", true).onComplete.add(setNewTween, clouds[i]);
...
function setNewTween()` -> does the same thing (calculates xPos, yPos and triggers tween).

It's quite urgent and it should be resolved fast so please for any help? 

Greetings,
Blaž

**Comment by nexiuhm** [comment]
Easiest way to solve this if it's urgent would be to just downgrade Phaser to the version where you didn't have any issues with smooth tweens, there are so many factors at play here that it's very hard to even start debugging it. I suggest you make simple demo that demonstrates this specific issue you're having :)

**Comment by Deshtructioner** [comment]
I've already solved the problems. Don't know why but differences in projects A and B (both now work!):
- antialiasing (in one false, in one true) 
- `game.camera.roundPx` = false; in proj B
- A: `game.add.tween(sprite).to({x: 100, y: 100, "Linear"...`, B: `... y: 100, Phaser.Easing.Linear.None`

Really weird that both projects work as they are almost duplicates of each other.

**Comment by nexiuhm** [comment]
Glad to hear :+1:
