### ISSUE TITLE
Documentation of Phaser.Math for version 2.4.4 inconsistency

### ISSUE THREAD

**Issue by SVasilev** [photonstorm/phaser#2333]
Hello,
I am looking at the documentation of [Phaser.Math](http://phaser.io/docs/2.4.4/Phaser.Math.html#chanceRoll) for version 2.4.4. It says there is a method called chanceRoll, but I saw that it is moved to Phaser.Util and no longer can be called as Phaser.Math.chanceRoll.
Regards,
Stefan

**Comment by photonstorm** [comment]
Fixed in dev.
