### ISSUE TITLE
loadTexture TypeError: this.game is null

### ISSUE THREAD

**Issue by Nidre** [photonstorm/phaser#2334]
Below error occurs after I switch back from another state to my main state. The code is called with a button press after the state is fully loaded. So I don't think it is some sort of racing condition.

A few details;

1- gameUI is not null or undefined.
2- gameUI.newFlipCoinPieceKey is not null, undefined or invalid value.
3- This issue does not happen if I change states without clearing the world. But I believe this results in previous state not to be cleaned?
```javascript
 game.state.start("stateName", false, false);
```

I would be glad if any has an explanation for this.game is being null in phaser.js.

Phaser version: * v2.4.4 "Amador" - Built: Thu Oct 15 2015 11:52:26

**Error**
TypeError: this.game is null
Phaser.Component.LoadTexture.prototype.loadTexture()
 phaser.js:45038
GameUI.prototype.flipCoin/<()
 index.html:257

**Code**

```javascript
        if (gameUI.coinSymbol) {
            game.add.tween(gameUI.coinSymbol.scale).to({ y: 0 }, 300, Phaser.Easing.Linear.In, true, 105);
        }
        gameUI.coinFlipStartAnim.play(15);
        gameUI.coinFlipStartAnim.onComplete.addOnce(function () {
            //Switch Sprite
            if (gameUI.coinSymbol) {
                gameUI.coinSymbol.loadTexture(gameUI.newFlipCoinPieceKey); //This is line 257
                gameUI.coinSymbol.position = { x: gameUI.goldCoinSprite.position.x, y: gameUI.goldCoinSprite.position.y };
                gameUI.coinSymbol.width = 100;
                gameUI.coinSymbol.height = 100;
                game.world.bringToTop(gameUI.coinSymbol);
            } else {
                gameUI.coinSymbol = game.add.sprite(
                    gameUI.goldCoinSprite.position.x,
                    gameUI.goldCoinSprite.position.y,
                    gameUI.newFlipCoinPieceKey);
            }
            gameUI.coinSymbol.anchor.set(0.5);
            gameUI.coinSymbol.scale = { x: 0.8, y: 0 };
            gameUI.coinFlipEndAnim.play(15);
            gameUI.coinFlipEndAnim.onComplete.addOnce(gameUI.onSpinCompleted, gameUI);
            game.add.tween(gameUI.coinSymbol.scale).to({ y: 0.8 }, 350, Phaser.Easing.Linear.In, true, 105);
        }, gameUI);
```

**Comment by photonstorm** [comment]
Almost certainly a context issue. When it gets to the next state it's in the wrong context (as a result of the context provided to the button callback), so none of the things it needs exist. Usually the context of a callback should be the State itself, not the object on which it was invoked.

**Comment by Nidre** [comment]
Will be checking and updating here.

**Comment by Nidre** [comment]
@photonstorm 

I have made some checks and updated my callbacks with Phaser Signals which solved some of the callback context issues that I was previously having.

But still could not manage to fix the above issue. 
I am relatively new to Phaser and JavaScript, mostly coming from .NET, Java and C++.

Below is the pdated method. "gameUI" ref was used before due to incorrect usage of callbacks. I have changed them back to "this" since I have updated my callbacks to use Phaser.Signal instead. 

this reference is defined and seems to be correctly referencing to my current state. But this.game is still null. Also this does not happen if I use game.add.sprite instead.

**Another detail (Might be a bit far fetched)**
I am switching from state "A" to state "B" without clearing the world.
When I switch back from state "B" to state "A", I only have the issue if I send clearWorld parameter true. I am wondering, if the clearworld parameter is clearing both previously not cleared "A" and current state "B" before switching to "A" and thus resulting in null ref with "this.game".

flipCoin method is called from gameUI with "this" context in below code. Which I believe should have the correct context.

Both of the below examples are prototype methods of gameUI(A), that is my state.

**Event which calls flipCoin**
```javascript
spinTween.onStart.addOnce(function () { game.time.events.add(500, gameUI.flipCoin, this); }, this);
```

**flipCoin method**
```javascript
  flipCoin: function () {
        if (this.coinSymbol) {
            game.add.tween(this.coinSymbol.scale).to({ y: 0 }, 300, Phaser.Easing.Linear.In, true, 105);
        }
        this.coinFlipStartAnim.play(15);
        this.coinFlipStartAnim.onComplete.addOnce(function () {
            //Switch Sprite
            if (this.coinSymbol) {
                this.coinSymbol.loadTexture(this.newFlipCoinPieceKey);
                this.coinSymbol.position = { x: this.goldCoinSprite.position.x, y: this.goldCoinSprite.position.y };
                this.coinSymbol.width = 100;
                this.coinSymbol.height = 100;
                game.world.bringToTop(this.coinSymbol);
            } else {
                this.coinSymbol = game.add.sprite(
                    this.goldCoinSprite.position.x,
                    this.goldCoinSprite.position.y,
                    this.newFlipCoinPieceKey);
            }
            this.coinSymbol.anchor.set(0.5);
            this.coinSymbol.scale = { x: 0.8, y: 0 };
            this.coinFlipEndAnim.play(15);
            this.coinFlipEndAnim.onComplete.addOnce(this.onSpinCompleted, this);
            game.add.tween(this.coinSymbol.scale).to({ y: 0.8 }, 350, Phaser.Easing.Linear.In, true, 105);
        }, this);

    },
```

**Comment by Nidre** [comment]
OK, I have moved below code to my create function instead of event callback. I believe calling it in event callback was causing sprite to be created in a different game context somehow and moving it to, start function solved issue. 

```javascript
 this.coinSymbol = game.add.sprite(
                    this.goldCoinSprite.position.x,
                    this.goldCoinSprite.position.y,
                    this.newFlipCoinPieceKey);
```
