### ISSUE TITLE
Game not scaling properly

### ISSUE THREAD

**Issue by sharmad** [photonstorm/phaser#2335]
Its a tiny game code which I have uploaded on http://scaleissue.site44.com/ so pls use browser dev tools to have a look. 

As you will notice when u go to dev tools and choose mobile emulation (iphone 4, 5, 6 - landscape orientation only), the screen only shows the top-left corner of the actual game with scroll bars when in fact it should have scaled the game such that all of the game was being shown on the screen since I used            

`            this.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
`
 (you might have to reload page to notice this issue when in dev tools). I tried the game on real mobile and still the same issue. 

All relevant scaling code is under boot.js

 

Please help as I cant quite nail the issue having tried several scaling modes.

**Comment by sharmad** [comment]
I would really appreciate if Rich or a fellow dev can confirm whether this could be a bug in the framework itself or not?

**Comment by ForgeableSum** [comment]
Your link doesn't work, but it sounds like a DOM issue.

**Comment by photonstorm** [comment]
Your link 404s. Please re-post somewhere and we'll take a look. We're closing this issue in the meantime (I will re-open it once code is provided and we can conclude it's an actual error, not a CSS issue)
