### ISSUE TITLE
Several problems with audio loading

### ISSUE THREAD

**Issue by maxkfranz** [photonstorm/phaser#2336]
Usecase : A Cordova app

Issue (1) : The mechanism used in Phaser to pull audio files doesn't work in Cordova.

Issue (2) : Trying to work around (1), I created my own request using XHR to grab the audio file.  This succeeds, leading me to believe there is a bug in Phaser with respect to (1).  I convert this data into a base 64 data URI and send this to Phaser instead -- so that Phaser doesn't have to do its own XHR -- but this doesn't work either.

Issue (3) : When debugging this and stepping through Phaser's code, I suspected that there was an issue with (2) due to it loading the data asynchronously.  This is indeed the case, as doing a simple `game.load.audio()` in a timeout doesn't work either.  I confirmed that (2) is still an issue by hardcoding the data URI into the the call.

For reference, take a look at the `example` directory of [my fork].  My fork only adds the example.  I planned on making a PR with a fix, but I didn't find where the loader is failing.  I confirmed these issues in the dev branch and in 2.4.4.

To reproduce (1) : Take the example I put in the `example` directory of [my fork](https://github.com/maxkfranz/phaser/tree/dev) and put it into a simple Cordova app for iOS.

Create the Cordova project:
```
npm install -g cordova
cordova create app
cd app
cordova platform add ios
```

Copy the example to the Cordova `www` directory:
```
cp <phaser-repo>/example/* app/www
```

Run on your iPhone:
```
cordova run --debug --device
```

Or you can open up `app/platforms/ios/app.xcodeproj` and run the simulator in Xcode.  You can use the debugger in Safari in tandem with the Xcode simulator.

To reproduce (2) and (3), you can just open up the example directory behind an HTTP server in your browser.  It doesn't work in Chrome, for example. You can uncomment different cases in the example code to try them out.

I'm mostly concerned with (1), because I wouldn't have even tried (2) or (3) if (1) were working.  However, (2) and (3) provide useful general workaround cases -- so they'd be valuable even if it's difficult to fix (1). 

Other than this problem, Phaser has been a joy to use!

Thanks for your help

**Comment by gaelenh** [comment]
@maxkfranz I do not think the problem is in phaser.  I downloaded your example and it didn't work for me. However, I simplified your example file ```sound-complete.js``` and it works fine within a Cordova project.  I attached a copy: 
[sound-complete.js.zip](https://github.com/photonstorm/phaser/files/157813/sound-complete.js.zip)

I have written a large-ish audio-heavy Cordova + Phaser game for Android, iOS, and browser.  If you are planning to release this game as a product, I would use the Cordova Media plugin instead of Phaser's audio implementation (web audio).  I ran into many other significant and tricky problems and eventually switched all my audio over to the Cordova plugin (which is also a buggy in it's own way).

**Comment by JTronLabs** [comment]
I also had this issue on Android devices with API < 21. I think it is because they do not support the 'new Audio' command 

[My StackOverflow question with more information about the problem, and what worked for me](http://stackoverflow.com/questions/36783554/mediaplayer-error-1-2147483648-in-cordova-6-1-1-with-phaser-2-4-6/36792899#36792899)

**Comment by JTronLabs** [comment]
I was wrong, 'new Audio' is supported in old Android versions. The issue ended up being due to file access permissions in Android+Cordova, nothing to do with Phaser.

**Comment by photonstorm** [comment]
Anything you could summarise so we could add it to the docs?


On Saturday, 30 April 2016, James <notifications@github.com> wrote:

> I was wrong, 'new Audio' is supported in old Android versions. The issue
> ended up being due to file access permissions in Android+Cordova, nothing
> to do with Phaser.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2336#issuecomment-215940771>
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by maxkfranz** [comment]
Thanks for the responses.

With the latest Cordova (6.1.1) and the latest iOS (9.3.1), both Phaser 2.4.4 and 2.4.7 work with the example in the OP.  I suspect the issue may have been on the Cordova side (maybe the whitelist plugin?).

In the meanwhile, I ended up using plain XHR and AudioContext -- which worked regardless of the version of Cordova.

**Comment by maxkfranz** [comment]
@photonstorm The [`wkwebview-engine-localhost`](https://github.com/apache/cordova-plugins/tree/master/wkwebview-engine-localhost) plugin should make this issue moot.  It adds a background http server, so resources like audio should load properly regardless of Cordova `file://` loading issues.  It also brings with it the `cordova-plugin-wkwebview-engine` plugin, which is great for rendering performance.  It would be great if a note could be added to the docs with this information.

**Comment by maxkfranz** [comment]
There's also [`cordova-httpd`](https://github.com/floatinghotpot/cordova-httpd)
