### ISSUE TITLE
iOS sound fades on app minimize

### ISSUE THREAD

**Issue by RyuMaster** [photonstorm/phaser#2337]
I am using the latest stable phaser build 2.4.5. When I minimize the app, sound fades out, but it keeps on 'playing', because when I get back, I can see sound position updated further way in sound debug info. But, the actual sound is played from the position I left. Can anyone confirm, that it is a bug? The should not be any fade in/out at all, sound should just continue playing.

this.stage.disableVisibilityChange = true;

this is set. I tested on iphone 4 and iphone 6; 

It can be reproduced with this simple example: http://phaser.io/examples/v2/audio/play-music (just need to add this.stage.disableVisibilityChange = true);

Also, forceSetTimeOut: true makes no difference. So I am not even sure where to start looking for the potential bug.

**Comment by photonstorm** [comment]
Phaser does _not_ fade the sound out for you when it loses visibility, that is iOS doing that (and to my knowledge there is nothing you can do about it)

**Comment by RyuMaster** [comment]
I just integrated jPlayer with Phaser,and it does not fade the sound. My guess was that both Phaser and jjPlayer are using html5 to play audio, so I though this is a bug.

**Comment by photonstorm** [comment]
Regardless, I guarantee there is no code anywhere in Phaser that will fade the sound out when visibility is lost.
