### ISSUE TITLE
TypeError: Cannot read property 'removeFromHash' of null(…)

### ISSUE THREAD

**Issue by noidexe** [photonstorm/phaser#2338]
I'm getting this error when adding a sprite to a group: 
TypeError: Cannot read property 'removeFromHash' of null(…)   phaser:js:71866

It's started happening with commit a0eb44ec091c5da15d36736dff0d91012329517c  up to 2.4.5

**Comment by brianbunch** [comment]
I have the same problem. There is missing a check on whether child.parent is defined.

**Comment by photonstorm** [comment]
This is fixed in dev.
