### ISSUE TITLE
[2.4.5] changing Game State problem

### ISSUE THREAD

**Issue by civet** [photonstorm/phaser#2339]
I just try phaser 2.4.5 and notice that something like Text on screen is gone when switching game states. but it works correctly on 2.4.4
Here is my code for testing:

    var hello = {
        create: function() {
            this.add.text(0, 0, 'Hello World', {fill: '#ffffff'});
        }
    };
    var goodbye = {
        create: function() {
            this.add.text(0, 0, 'Good bye', {fill: '#ffffff'});
        }
    };
    var game = new Phaser.Game(640, 480, Phaser.AUTO, 'stage', null);
    game.state.add('hello', hello, false);
    game.state.add('goodbye', goodbye, false);

    setTimeout(function() {
        game.state.start('hello');
    }, 1000);

    setTimeout(function() {
        game.state.start('goodbye');
    }, 2000);

**Comment by photonstorm** [comment]
Fixed in dev. Sodding CanvasPool issue!
