### ISSUE TITLE
Phaser 2.4.5 CANVAS render drawImage error

### ISSUE THREAD

**Issue by fzuleta** [photonstorm/phaser#2341]
Hi, 
Phaser 2.4.4 is fine, the issue is when running Phaser 2.4.5 with Phaser.CANVAS on Android chrome it's :

`Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'`

![image](https://cloud.githubusercontent.com/assets/3056157/13144557/6088f6a8-d619-11e5-9ec1-b9eed8112ce1.png)

**Comment by photonstorm** [comment]
This is fixed in dev branch as of this morning.
