### ISSUE TITLE
In pointer.js stop function gets called after game.destroy

### ISSUE THREAD

**Issue by stoneman1** [photonstorm/phaser#2342]
So I have this single page situation with angular. I call game.destroy() when its out of the game view. But it still somehow gives errors like this : 
Uncaught TypeError: Cannot read property 'time' of null
Which points to this in pointer.js :         
this.timeUp = this.game.time.time;

Trying to make a fix for this at this moment just put this up here if someone else is wondering same.

**Comment by soumak77** [comment]
This is the same error I'm seeing.  The fix is described in #2344.

**Comment by photonstorm** [comment]
Merged into dev.
