### ISSUE TITLE
_onMouseOutGlobal event not unregistered

### ISSUE THREAD

**Issue by soumak77** [photonstorm/phaser#2344]
When attempting to destroy a Phaser game instance (v2.4.6), I am seeing errors appear due to the **_onMouseOutGlobal** event being called after the game is destroyed.  Looking at the source code I see the `Phaser.Mouse.start` method adds the following event listeners:
```
window.addEventListener('mouseup', this._onMouseUpGlobal, true);
window.addEventListener('mouseout', this._onMouseOutGlobal, true);
```
Looking at the `Phaser.Mouse.stop` method, I see that only **_onMouseUpGlobal** is unregistered:
```
window.removeEventListener('mouseup', this._onMouseUpGlobal, true);
```
The following line must also be added:
```
window.removeEventListener('mouseout', this._onMouseOutGlobal, true);
```

**Comment by stoneman1** [comment]
Thanks for this :) Did not have the time to figure it out yet :)

**Comment by photonstorm** [comment]
Merged into dev.
