### ISSUE TITLE
The Phaser API pages needs to be re-designed

### ISSUE THREAD

**Issue by WebGLisTheFuture** [photonstorm/phaser#2352]
The Phaser API page is a total mess.

I was searching a keyboard event issue and found this:
http://www.html5gamedevs.com/topic/11715-help-with-phaser-stealing-keypress-focus/?do=findComment&comment=67758

So, I go to the Phaser API page here:

http://phaser.io/docs/2.4.4/Phaser.Game.html#onFocus

And it has no representation or example of how to utilize this onBlur signal whatsoever. This is not only for the onBlur signal but for every single thing listed. 

_______________________________________________

Now, for example if I were using the ImpactJS engine and wanted to find out how to add an image, this is what their API shows:

http://impactjs.com/documentation/class-reference/image#synopsis

For Phaser, this is what their API shows:

http://phaser.io/docs/2.4.4/Phaser.Image.html

See the difference?

Also, what's up with the [huge background image](https://i.gyazo.com/98315d60c90ebc0d91f38fd7de2b2d3a.png) almost taking up half of the docs page? Remove that, it's highly annoying when scrolling through the docs.

The documentation about how the methods work is good, but the layout and usages are lacking immensely and it's an extreme turn off.

**Comment by WebGLisTheFuture** [comment]
Wow. Very sad.

So after a while of searching, you actually are supposed to do:

```
game.onFocus.add(function(e){
console.log('Game was in focus');
});
```

To utilize the onFocus method/signal.

Mind telling me why in the world this was not explained here?
http://phaser.io/docs/2.4.4/Phaser.Game.html#onFocus

No where on that page is it telling the user that you need to utilize the `add` method. Just another round of hoops you need to go through to finally get something working from the API page.  Why isn't there just a simple example code block of what I have posted above? There is absolutely NO reason whatsoever to make the API documentation this confusing.

**Comment by photonstorm** [comment]
Give me one reason why I should put up with the attitude and hostility in this post?

There are myriad ways to request or suggest something politely. This isn't one.

**Comment by WebGLisTheFuture** [comment]
I shouldn't NEED to request a proper documentation in the first place. I'm fed up with wasting my time sifting through a poorly API just to find out how to use some methods within the game engine. It's silly.

**Comment by Leekao** [comment]
Yeah, they should totally refund you back the money you paid.

**Comment by WebGLisTheFuture** [comment]
Yeah they should, since I thought moving from ImpactJS to Phaser would be a good idea, huh?

**Comment by clark-stevenson** [comment]
Feel free not to use it?

**Comment by photonstorm** [comment]
What you're requesting is code examples in the API docs. I purposely don't do that because I like to give much longer form examples in the Phaser Examples instead. Which is why there are hundreds and hundreds of them. Far more than you could ever fit into the API docs themselves.

**Comment by netgfx** [comment]
And I wonder if impactJS has so great documentation why did you feel the need to move from them?
Could it be because they focus on documentation layout and page setup and not actually for the underlying engine?
Also did you give Phaser the same amount of time that you have been using ImpactJS and compared them? After a while you don't need the docs any more.

**Comment by dariusk** [comment]
@WebGLisTheFuture I agree that Impact has nicer documentation than Phaser; inline example code is great. (Impact is also a paid project and so the people who work on that get compensated for their time working on docs.) One of the things that I do when evaluating a new library or framework is do a thorough documentation review. It's standard due diligence and I highly recommend that if underdocumented code is a turnoff to you, you should base your decisions in using a framework *primarily* on the state of the documentation.

I also agree that the way you put your request could've been much nicer. You're not a customer. You're not entitled to anything. You're taking advantage of volunteer time and labor here. The ideal response would have been a pull request with some example code that could be merged directly into the documentation. That way, the maintainers would have a framework they could use in the future for adding similar documentation to other functions.

**Comment by WebGLisTheFuture** [comment]
The problem PhotonStorm is that not every method / function on the API page has an example for it. So what you are saying is fine, but a user will end up just looking at the doc's then go to the examples page and then end up not finding what they want. Then they end up at square one. I am suggesting a better documentation page and for each method/function on the doc's page, there is a link to the examples page. (Since you said the code blocks would fill up the docs, which is fair).  

You guys have not addressed any of my concerns in my original post which are fair and valid but resort to not doing anything about it because of my tone.  That's not right.

**Comment by Leekao** [comment]
That should teach you something about the proper tone to use on such occasions.

**Comment by photonstorm** [comment]
Your tone is the reason this is closed. Feel free to re-open a better constructed one. As I said, I absolutely do not have to put up with attitude here. At all. I don't really care if you disagree with that, it's just how it is.

**Comment by WebGLisTheFuture** [comment]
Just to clarify, you guys also should note Impact was developed by one person more than 5 years ago and their documentation has been like that for years. Doesn't take much to add code examples.

> You're not a customer. You're not entitled to anything

But, how do you know I am not a Patreron supporter? So now you guys are saying if I was a 'customer' and used this tone It would be okay?

**Comment by hilts-vaughan** [comment]
No, you'd still be a jerk. But then tolerance would be required to get your
money. :)

**Comment by dariusk** [comment]
Just want to clarify that I'm not a Phaser contributor in any way! But I've used Phaser and Impact and I run a lot of open source projects myself and I care about good documentation and good PRs.

And asking for proper documentation is 100% okay! You just asked for it in a really mean way, and that's not okay.

**Comment by hilts-vaughan** [comment]
In this case, it makes it clear it returns a Phaser.Signal. Is the Signal
API not clear or the return value?

I don't think adding a code example for every signal is the right thing to
do.. they are all more or less the same, after all.

**Comment by WebGLisTheFuture** [comment]
@hilts-vaughan 

Yeah, it says it returns a `Phaser.Signal`, and so I clicked on that:

http://phaser.io/docs/2.4.4/Phaser.Signal.html

Then when I get here, there is still no documentation on how to even use this Signal Syntaxically in the game engine itself. That's what I am suggestion, I shouldn't (or any dev) have to run through all these hoops to just find out how to utilize the method/function. This is true not only for Phaser.Signal but everything in the docs.  The documentation for the functions are actually really well done, but the lack of showing how to actually implement those methods in-game are non-existence (in the API docs).

So I am suggesting to add a link in the doc's next to each method / description that goes to a page showing how to use it (or atleast a code block).

**Comment by hilts-vaughan** [comment]
I don't know; isn't add and remove clear? I think it's fine -- but if you
could explain your exact issues I don't mind putting a PR through (or you
can, too)

I wouldn't call this hoop jumping -- it's two clicks. Now, if it's not
immediately obvious how to use the signal then there is an issue.

**Comment by netgfx** [comment]
http://phaser.io/docs/2.4.4/Phaser.Signal.html

Contains the ```add``` function just at the middle of the page.

Also if you thing a developer shouldn't have/need to read the framework to get accustomed to it and learn to use it, then this tells me you haven't read many documentations before...
And FYI Phaser has a great and friendly community and it would benefit you if you got engaged and asked away whatever troubles you.

**Comment by WebGLisTheFuture** [comment]
@netgfx  Yes, I saw that method but how would I know that `add` method belonged to the main `game` class? ( `game = new Phaser.Game()`) That's what I am trying to get at, there is no documentation noting that.  All I read was:

> Constructor new Signal()
A Signal is an event dispatch mechanism that supports broadcasting to multiple listeners.
Event listeners are uniquely identified by the listener/callback function and the context.

**Comment by hilts-vaughan** [comment]
`add` doesn't belong to the game class. It belongs to the signal.

**Comment by WebGLisTheFuture** [comment]
Oops, I meant signal belonged to main
```
	game.onFocus.add(function(){
		 
	})
```
But how would you find out that the onFocus has to use the `add` method in the docs

**Comment by hilts-vaughan** [comment]
Because "onFocus" in the document you linked returns a Phaser.Signal ... :)
Of course, it can't return a void (that would make no sense, no)? So, the
next obvious thing to do is figure out how to "attach" the event.

The Signal is the answer to that.

**Comment by hilts-vaughan** [comment]
This smells like a case of not reading  an introduction to Phaser and
understanding the signal dispatch system (or even rationalizing  how this
could fire)

**Comment by WebGLisTheFuture** [comment]
> This smells like a case of not reading  an introduction to Phaser and
understanding the signal dispatch system (or even rationalizing  how this
could fire)

Which is not explained in the docs whatsoever.

**Comment by hilts-vaughan** [comment]
If only someone had posted a guide on them... ;)

http://phaser.io/news/2016/01/using-phaser-signals

**Comment by hilts-vaughan** [comment]
Once again, disagree about inlining it on every signal. If you know how the
signals work, it's gloss. The page will be twice as long if you have to
include an example on how to "reuse the signal API" on every page.

You see it returns a Phaser.Signal; the API is straight forward -- add and
remove. If you need more help, there's tons of pages to get you started.

I don't see a convincing case except you insisting it's not spelled out
inline. I insist if you spend 5 minutes reading it's easy to find.


Disclaimer: I'm a developer that uses Phaser; not a Phaser developer.

**Comment by northducks** [comment]
I always thought that every good programmer, really good programmer-not-a-coder, is also a hacker -- the man who has a “mind" to dig into some code, nevermind how bad or good or difficult or stupid or super-cool. The man who has the human-ability to read and investigate code, like a painter can find the hidden meaning in someone other picture (yes, a hacker - not a cracker). And if that man doesn’t understand something, doesn’t see the sense or the point of a line of code.. so i would say that he is not a good programmer. It’s normal, it’s ok. And it’s real. But when someone, not a good programmer, trying to teach the stuff that he doesn’t know - it only shows his stupidity. And I don't see the point in having to pay attention to him and wasting my time. In short - if you don’t understand the code and, you think that the documentation is bad, but you what to know that codes.. but you cannot.. that’s mean only one - probably you are not such good as you think.

@WebGLisTheFuture, please stop showing your stupid mind. If you cannon understand the code - go ahead and read the code again and again, with or without debugger, which you like to use to maintain your courage. If you don't like the documentation - don't read it. It's simple.

Don't teach others when you yourself are still a student.

**Comment by hilts-vaughan** [comment]
We should keep this constructive. If we can do something as a community to
make it more clear, we should.

**Comment by noidexe** [comment]
> Hilarious how someone like me has to be shunned down like this just for you guys to acknowledge that the API / docs is poorly written.
@WebGLisTheFuture the API and the docs are two different things. Just because you don't like the docs doesn't mean the API needs to be redesigned. Try the old docs. Open docs/index.html inside the phaser repo. I find them easier to navigate.

**Comment by cloakedninjas** [comment]
@WebGLisTheFuture It's an open source project - don't like something, submit a pull request. Acting like an entitled douche nozzle completely overshadows and salient points you might have raised.

And as for being a Patreon supporter, even if you were a top-tier funder, that doesn't give you the power to demand work to be done.

**Comment by JakeCake** [comment]
When you guys are done lecturing about proper manners, maybe we can return to the fact that the header on the docs does in fact, as pointed out by mr. Douche himself, take up half the screen. This means I have to go into html and edit the header smaller each time I visit the docs.

Should I open a new request or can someone do it for me? I'm not a git-shark yet, but working on it.

**Comment by netgfx** [comment]
@JakeCake In my 1920x1200 27'' it looks fine... as you see it all depends. But yeah maybe a small X could be put in-place to reduce the height of the header or remove it altogether.
