### ISSUE TITLE
AudioContext should not close if PhaserGlobal is used to reuse it.

### ISSUE THREAD

**Issue by brianbunch** [photonstorm/phaser#2356]
If the AudioContext is reused by being stored in PhaserGlobal it should not be closed, since the call to createGain fails when performed on a closed context.

A possible fix would be to check if PhaserGlobal has been set and only close the AudioContext if it has not. This code extends the suggested fix to issue #2355:

`if (this.context.close  && !window['PhaserGlobal']) {
this.context.close();
}`

**Comment by photonstorm** [comment]
Thanks, now fixed in dev.
