### ISSUE TITLE
SoundManager destroy not working with edge

### ISSUE THREAD

**Issue by stoneman1** [photonstorm/phaser#2361]
Well it turns out that Microsoft Edge does not know context.close(). Which is bad, because I have no idea how to close the context which edge is creating now and it is actually now making the destroy crash on trying to close the context. 

Tried to make a check if the browser is edge and then not closing it and it partly works. The context will be there and not closed which causes another issue after having more than 6 contexts (which is the maxium)

**Comment by photonstorm** [comment]
I already check if 'close' is supported before calling it, so Edge should
be fine now. Repeat game instances will still run it out of contexts
though, but for that you should really use the PhaserGlobal object to store
it in anyway.


On Saturday, 27 February 2016, stoneman1 <notifications@github.com> wrote:

> Well it turns out that Microsoft Edge does not know context.close(). Which
> is bad, because I have no idea how to close the context which edge is
> creating now and it is actually now making the destroy crash on trying to
> close the context.
>
> Tried to make a check if the browser is edge and then not closing it and
> it partly works. The context will be there and not closed which causes
> another issue after having more than 6 contexts (which is the maxium)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2361>.
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by stoneman1** [comment]
Yeah its not a real bad problem. But without closing the context there is a problem with using webcam and/or microphone, because the whatever icon indicating that the webpage is using your mic and/or webcam does not go away so fast. People might not like it. Anyway we can probably close this issue.

**Comment by photonstorm** [comment]
This is really strange though, maybe Edge just does it 'differently' - there is no `close` method available in their documentation: https://msdn.microsoft.com/en-us/library/dn954795(v=vs.85).aspx

But I can't believe it's not possible.
