### ISSUE TITLE
Tween Accept Array as Target

### ISSUE THREAD

**Issue by webcaetano** [photonstorm/phaser#2362]
Hello everyone.

I was thinking that tween should be able to accept array of objects as target.
E.g. :

**Currently**
```javascript
game.add.tween(obj1).to({x:'-100'});
game.add.tween(obj2).to({x:'-100'});
game.add.tween(obj3).to({x:'-100'});
```

**If accept Array of objects**
```javascript
game.add.tween([obj1,obj2,obj3]).to({x:'-100'});
```

I know laser are in developing, but tween was not write there yet.

Should i create a PR with this feature?

**Comment by photonstorm** [comment]
I like the idea, but I don't want to implement it into the API, sorry. No more sweeping changes like this really.

**Comment by webcaetano** [comment]
np.
