### ISSUE TITLE
website issue: broken laravel routes or something

### ISSUE THREAD

**Issue by verybigelephants** [photonstorm/phaser#2363]
http://phaser.io/download/official-tutorials
http://phaser.io/download/community-tutorials

> Whoops, looks like something went wrong.

**Comment by photonstorm** [comment]
Where did you get those links from? They should be:

http://phaser.io/learn/official-tutorials
http://phaser.io/learn/community-tutorials

As those are the links we use on the site.

**Comment by verybigelephants** [comment]
oh, then the links provided on the left side here are wrong it seems :)

http://phaser.io/download/stable

**Comment by photonstorm** [comment]
Alrighty, now that I can fix. And have done so. Cheers for pointing it out.
