### ISSUE TITLE
Can't create render texture from particle storm emitter 

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2365]
For normal particle emitters, I have no problem rendering them to a render texture with renderXY. But for emitters created with particle storm, I get this error:

Uncaught TypeError: displayObject.updateTransform is not a function (phaser-2.4.6.js:53644)

Why wouldn't a particle emitter created by the Particle Storm plugin not have the updateTransform function? Is it not an extension of normal Phaser particle emitters? This is the particle emitter I used (but I assume this problem is for all particle emitters in PS): http://phaser.io/examples/v2/particlestorm/firelight

Also, if I comment out line 53644, I get another error, presumably because updateTransform is a necessary step. 

Code: 
```
function createBurner(burnerX, burnerY, parent, scale) {
    if (burnerRenderTexture == undefined) {
        //  A burning torch
        var flame = {
            lifespan: 3000,
            image: 'white',
            bringToTop: true,
            blendMode: 'ADD',
            hsv: {
                initial: 0,
                value: 70,
                control: 'linear'
            },
            alpha: {
                initial: 0,
                value: 1,
                control: [{
                    x: 0,
                    y: 1
                }, {
                    x: 0.5,
                    y: 0.8
                }, {
                    x: 1,
                    y: 0
                }]
            },
            scale: {
                min: 0.5,
                max: 1.5
            },
            vx: {
                min: -0.2,
                max: 0.2
            },
            vy: {
                min: -1,
                max: -2
            }
        };

        var spark = {
            lifespan: 3500,
            image: 'white',
            bringToTop: true,
            blendMode: 'ADD',
            alpha: {
                initial: 0,
                value: 1,
                control: [{
                    x: 0,
                    y: 1
                }, {
                    x: 0.5,
                    y: 0.9
                }, {
                    x: 1,
                    y: 0
                }]
            },
            scale: {
                initial: 0,
                value: 1,
                control: 'linear'
            },
            vx: {
                min: -0.2,
                max: 0.2
            },
            vy: {
                min: -1,
                max: -2
            }
        };

        var smoke = {
            lifespan: 3000,
            image: 'smoke',
            sendToBack: true,
            alpha: {
                initial: 0,
                value: 1,
                control: [{
                    x: 0,
                    y: 0
                }, {
                    x: 0.2,
                    y: 1
                }, {
                    x: 0.5,
                    y: 0.5
                }, {
                    x: 1,
                    y: 0
                }]
            },
            scale: {
                min: 1,
                max: 1.5
            },
            vx: {
                min: -0.2,
                max: 0.2
            },
            vy: {
                min: -1,
                max: -2
            }
        };

        manager.addData('flame', flame);
        manager.addData('spark', spark);
        manager.addData('smoke', smoke);

        burnerSmokeEmitter = manager.createEmitter();
        flameEmitter = manager.createEmitter();

        burnerSmokeEmitter.addToWorld();
        flameEmitter.addToWorld();

        burnerSmokeEmitter.emit('smoke', 400, 300, {
            delay: 3000,
            repeat: -1,
            frequency: 360
        });

        flameEmitter.emit('spark', 400, 450, {
            repeat: -1,
            frequency: 140
        });
        flameEmitter.emit('flame', 400, 450, {
            repeat: -1,
            frequency: 40,

        });
        burnerRenderTexture = game.add.renderTexture(600, 600);
    }

    var burner = game.add.sprite(burnerX, burnerY, burnerRenderTexture);
    parent.addChild(burner);
    burner.scale.set(scale);
    burner.anchor.set(.5);
    if (parent != undefined) {
        if (parent.burners == undefined) {
            parent.burners = [];
        }

        parent.burners.push(burner);
    }

    return burner;

}
```

**Comment by photonstorm** [comment]
The Emitter itself doesn't extend anything, and doesn't have any display properties (so therefore doesn't have an updateTransform method) because it's not a display list object.

We provide a RenderTexture specific renderer with Particle Storm if you need to render the particles to a RT, but you can't render the Emitter _itself_ to anything because it has no visual properties.

**Comment by ForgeableSum** [comment]
I'm having trouble understanding what "A RenderTexture based renderer" is. Say I want to create a rendertexture of a photon storm particle emitter. How do I do that? It was pretty straightforward in vanilla Phaser and I could directly render the emitter objects to the render texture, e.g.:
```
burnerRenderTexture.renderXY(burnerSmokeEmitter, 0, 0, true);
burnerRenderTexture.renderXY(flameEmitter, 0, 0, false);
```
Just trying to figure out how to do that in PS with Phaser.ParticleStorm.Renderer.RenderTexture. Any code examples would be helpful. Thanks!

**Comment by photonstorm** [comment]
There are 5 different examples included with the plugin showing how to use the RenderTexture  renderer (rendertexture 01 through to 05),all of them are in the examples folder.

**Comment by ForgeableSum** [comment]
I studied those examples and couldn't seem to make heads or tails. What I want to do essentially is create a single particle emitter, render it to a rendertexture and use that rendertexture as the texture on many different sprites. I've used this trick before on normal particle emitters and it works like a charm. Having 100 render textures of a single particle emitter is much better on performance than having 100 particle emitters... in the case of PS emitters, having  a single particle emitting from several different locations is really bad on performance. I'd like to use my old trick of giving a bunch of sprites a render texture as their texture and rendering the particle emitter to that render texture. I can still have variety by rotating and scaling the sprites.. Just not sure how to do that with Particle Storm.

**Comment by photonstorm** [comment]
The RenderTexture Renderer has a property called `renderTexture` which is a reference to the RenderTexture that is created. So to use it for another Sprite you'd just do:

`game.add.sprite(0, 0, flameEmitter.renderer.renderTexture)`

It also creates a single Image object that is added to the display list, which you'd likely want to hide in your case.

**Comment by ForgeableSum** [comment]
Works! Thanks Rich! Now I can have my thousands of particle emitters with little impact on performance. 

and yeah, I do hide the emtter. What I do in the paste is add it to an invisible group.
