### ISSUE TITLE
Error on drag when sprite is fixed to the camera

### ISSUE THREAD

**Issue by solusipse** [photonstorm/phaser#2367]
When sprite is fixed to the camera (`testsprite.fixedToCamera = true`) and `enableDrag` method is ran with `true` as a first argument (`testsprite.input.enableDrag(true)` - so it sets dragpoint to the center of the sprite) I get `Uncaught TypeError: this.sprite.centerOn is not a function` everytime I try to drag that sprite. I guess that's a bug. There's a live example: https://solusipse.net/misc/phaser-drag-error/

```javascript
<script src="https://cdnjs.cloudflare.com/ajax/libs/phaser/2.4.4/phaser.min.js"></script>
<script>
var game = new Phaser.Game(800, 600, Phaser.AUTO, "gameContainer", { preload: preload, create: create, update: update });

function preload()  {
    game.load.image('test', "test.png", 50, 50);
}

function create() {
    var testsprite = testsprite = game.add.sprite(200, 200, "test");
    testsprite.fixedToCamera = true;
    testsprite.inputEnabled = true;
    testsprite.input.enableDrag(true);
}
function update() {}
</script>
```

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
