### ISSUE TITLE
BitmapText is blurry if anchor set to 0.5 and width is odd number

### ISSUE THREAD

**Issue by Lopdo** [photonstorm/phaser#2370]
Whenever resulting position of text resolves to non-integer, the text gets blurry, easiest example is setting anchor to 0.5 and writing text with odd width. Same probably goes for height. If the position is integer, text is crisp again
Proposed solution: round ax/ay down in updateText method?

**Comment by photonstorm** [comment]
There are cases where the anti-aliasing is required, so this won't be enabled by default. If you need it we provide the `roundPixels` flag in the renderer:

`game.renderer.renderSession.roundPixels = true`.

**Comment by Lopdo** [comment]
I understand the need for andti-aliasing, but wouldn't it make sense to make this default for the text? The roundPixels is global, isn't it? Perhaps consider adding this property to display object so it can be turned on/off for each object separately?

**Comment by photonstorm** [comment]
Yes it would be useful on a per-case basis, but that's a significant change touching every type of Game Object and both renderers, so it's not happening this late in the day.

If you need it, extend the BitmapText class and override the offending method, or replace it directly on the prototype if you want it globally.
