### ISSUE TITLE
phaser is loaded "choppy" on random refresh

### ISSUE THREAD

**Issue by verybigelephants** [photonstorm/phaser#2372]
i have decided to test phaser out and have this basic scene here
http://phaser_test.vomit.me/

you can move with left/right keys 

the issue is that when you refresh the page, at random times, the whole scene is **noticably** choppier than other times at other random refresh times. what is going on? 

does phaser use some kind of profiling to determine whether to use requestAnimationFrame or setTimeout or something like that?

can i disable it?

update: the issue is truly strange. when enabling game.time.advancedTiming and console.logging the the game.time.fps, the values are actually lower for when the game behaves not choppy

**Comment by hocuspucus** [comment]
If you switch Phaser version to 2.4.5, does the chopiness increase?

**Comment by verybigelephants** [comment]
yep. just updated the link to include 2.4.5 version of phaser and it still happens http://phaser_test.vomit.me/

**Comment by photonstorm** [comment]
Try setting `game.forceSingleUpdate = true` at the start of your code and see if that helps (I suspect it will)

**Comment by photonstorm** [comment]
Actually in light of this issue, and lots of others, this is now enabled by default.

**Comment by verybigelephants** [comment]
it did help, thanks! it works smooth across all solid desktops
unfortunately, i am afraid that with experience with slower machines or mobile phones is much less consistent when running with forceSingleUpdate set to true :(
