### ISSUE TITLE
Text cropped when using negative lineSpacing

### ISSUE THREAD

**Issue by gaelenh** [photonstorm/phaser#2374]
In 2.4.6, a change was introduced to the Text spacing code that reduced the height of the drawn text.  https://github.com/photonstorm/phaser/commit/0c52b9316a774aa88d08b3e824934f8d5da0563f.  This change causes text to be cropped at the bottom for larger lineSpacing values.  Given that this is a regression to how this was previously displayed, I am submitting it as a bug.

Example image: 
![screen shot 2016-03-03 at 6 08 00 pm](https://cloud.githubusercontent.com/assets/325937/13512852/43783efe-e16b-11e5-9d59-afa492a26488.png)

Code to reproduce: [cropped-text.zip](https://github.com/photonstorm/phaser/files/157837/cropped-text.zip)

**Comment by gaelenh** [comment]
I created pull request https://github.com/photonstorm/phaser/pull/2379 to address this.

**Comment by photonstorm** [comment]
Merged, thanks!
