### ISSUE TITLE
Bouncing too fast & collideWorldBounds makes the sprite stick to the wall

### ISSUE THREAD

**Issue by taylankasap** [photonstorm/phaser#2378]
The sprite just stops moving in the direction which has the 3000 velocity after it hits the wall. But keeps moving in the direction which has 500 velocity.

Here you can just clone the repo & run the index.html
https://github.com/taylankasap/phaserjs-bounce-issue

I tested on Chrome, Firefox, IE, Windows & Ubuntu. All same.

**Comment by photonstorm** [comment]
This is known as 'tunneling', when a physic body is moving so fast it tunnels into (or sometimes even right through) another body. Arcade Physics has no checks in place to handle this, and no form of CCD, so you'll need to either keep your velocities in check, or move to a full body physics system.
