### ISSUE TITLE
tileSprite using bitmapData as texture

### ISSUE THREAD

**Issue by mzamateo** [photonstorm/phaser#2380]
this worked on 2.3.0 but not on versions > 2.3.0

bmd = game.add.bitmapData(400, 100);
bmd.fill(0, 0, 0, 1);
text = game.make.text(0, 0, "hello!" );
bmd.draw(text, 0, 0);
ts=game.add.tileSprite(10, 10, 400, 100, bmd);//<-this throws a message to console (WIP?)

**Comment by lucap86** [comment]
try to add bitmap data to cache
---

var bmd = game.add.bitmapData(400, 100);
game.cache.addBitmapData('myBmd', bmd);
bmd.fill(255, 255, 255, 1);
var text = game.make.text(0, 0, "hello!" );
bmd.draw(text, 0, 0);
var ts=game.add.tileSprite(10, 10, 400, 100, bmd);

---

console message is a leave behind console.log

**Comment by mzamateo** [comment]
it works this way, THANKYOU!!!

but about key parameter docs say:

> This is the image or texture used by the TileSprite during rendering. It can be a string which is a reference to the Phaser Image Cache entry, or an instance of a RenderTexture, PIXI.Texture or BitmapData.

Should it work without game.cache.addBitmapData(...)?

thankyou again

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
