### ISSUE TITLE
SoundManager does not always respect muting

### ISSUE THREAD

**Issue by Afowler2k** [photonstorm/phaser#2382]
My game has a mute button in another window. When the mute button is clicked, Phaser loses focus and mutes the sound. My event handler triggers for the mute button, which then calls this.game.sound.mute=true. However, when Phaser gets focus back, the game gets unpaused and the sound continues playing.
This is happening because in SoundManager L770, this._codeMuted = true;  doesn't get executed if the audio is already muted (which it is when Phaser loses focus)
https://github.com/photonstorm/phaser/blob/v2.4.6/src/sound/SoundManager.js#L770

_codeMuted should be set/unset everytime regardless, so that the muting works when the game needs to control the sound externally.

**Comment by lewispollard** [comment]
Same problem here - in this case the sound mute is toggled via an overlay in an iframe (not by choice may I add but a client requirement), and setting game.sound.mute while the iframe is active doesn't mute sound, though the variable is toggled. For now I've just set a separate variable for muting that is toggled when the iframe is active, and the game.sound.mute value is set in the update function afterwards if the variable changes.

**Comment by photonstorm** [comment]
This can now be handled via the new `SoundManager.muteOnPause` boolean (in your cases, set it to `false` and toggle it as needed yourself, externally).

**Comment by SBCGames** [comment]
Sorry for reopening

Currently muteOnPause is checked in gamePaused() and gameResumed() methods, which are called by Stage visibility hadler.

 I have client that displays overlay with menu over game. If disableVisibilityChange is set to true or overlay does not steal focus, then game runs under it (unfortunately both is possible). For this, client's framework sends his own onPause() and onResume() events when it shows or hides overlay. Inside handlers of these events I set paused to true or false. Overlay has menu with sound on/off button on it, which sends events onMute() / onUnmute(). If game is paused with call to paused = true/false in onPause()/onResume(), then setting game.sound.mute = true/false inside event handlers for onMute()/onUnmute() events does not have effect.

 Reason is, that in paused property of Phaser.Game, setMute and unsetMute are called without muteOnPuase check. Adding checks resovles issue.

```javascript
Object.defineProperty(Phaser.Game.prototype, "paused", {

    get: function () {
        return this._paused;
    },

    set: function (value) {

        if (value === true)
        {
            if (this._paused === false)
            {
                this._paused = true;
                if (this.sound.muteOnPause) {            // added check
                    this.sound.setMute();
                }
                this.time.gamePaused();
                this.onPause.dispatch(this);
            }
            this._codePaused = true;
        }
        else
        {
            if (this._paused)
            {
                this._paused = false;
                this.input.reset();
                if (this.sound.muteOnPause) {            // added check
                    this.sound.unsetMute();
                }
                this.time.gameResumed();
                this.onResume.dispatch(this);
            }
            this._codePaused = false;
        }

    }

});
```
