### ISSUE TITLE
renderTexture and TileSprite issues

### ISSUE THREAD

**Issue by lucap86** [photonstorm/phaser#2384]
issues#1
if set Phaser.AUTO as renderer PIXI throw error in PIXI.TilingSprite.prototype.generateTilingTexture
when try to drawImage because texture.baseTexture.source is undefined
I think that the problem is related to this pixi issue https://github.com/pixijs/pixi.js/issues/1393

issue#2
if set Phaser.CANVAS as renderer no error thrown but nothing will be shown

All works correctly instead with bitmapData

Here it is an example
[tilespriteError.zip](https://github.com/photonstorm/phaser/files/169792/tilespriteError.zip)

**Comment by lucap86** [comment]
same error is trow when call

myTileSprite.texture.destroy(true);

on a tileSprite that has been create with bitmapData as key

**Comment by photonstorm** [comment]
First up, you cannot use a RenderTexture as a texture for a TileSprite. I have updated the jsdocs to reflect this.

Secondly, I can destroy a TileSprite created from a BitmapData fine, using current dev branch, code here:

```
    var bmd = game.add.bitmapData(400, 100);
    bmd.fill(255, 255, 0, 1);

    var text = game.make.text(0, 0, "hello!" );
    bmd.draw(text, 0, 0);

    var ts = game.add.tileSprite(10, 10, 400, 100, bmd);

    game.input.onDown.addOnce(function() { ts.destroy(true, true); });
```

**Comment by lucap86** [comment]
You should also remove string|Phaser.RenderTexture from {string|Phaser.RenderTexture|Phaser.BitmapData|Phaser.Video|PIXI.Texture} in:

* @param {string|Phaser.RenderTexture|Phaser.BitmapData|Phaser.Video|PIXI.Texture} key - This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache Image entry, or an instance of a RenderTexture, BitmapData, Video or PIXI.Texture.

**Comment by photonstorm** [comment]
No because the LoadTexture component is shared by all Game Objects, and
most of them can use it fine. The warning in the docs will have to do.


On Wednesday, 6 April 2016, lucap86 <notifications@github.com> wrote:

> You should also remove string|Phaser.RenderTexture from
> {string|Phaser.RenderTexture|Phaser.BitmapData|Phaser.Video|PIXI.Texture}
> in:
>
>    - @param <https://github.com/param>
>    {string|Phaser.RenderTexture|Phaser.BitmapData|Phaser.Video|PIXI.Texture}
>    key - This is the image or texture used by the Sprite during rendering. It
>    can be a string which is a reference to the Cache Image entry, or an
>    instance of a RenderTexture, BitmapData, Video or PIXI.Texture.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2384#issuecomment-206181510>
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27
