### ISSUE TITLE
How to store data locally by phaser?

### ISSUE THREAD

**Issue by zhanll** [photonstorm/phaser#2386]
If i want to make a dynamic map, which need to store the new generated map data into local files, then which api should i use? I looked through the whole phaser code, but didn't get it.Could you please add some apis like these?

**Comment by hilts-vaughan** [comment]
Use local storage.

**Comment by photonstorm** [comment]
I agree, use LocalStorage. There's no Phaser interface to it because it's so easy to use on its own:

https://developer.mozilla.org/en-US/docs/Web/API/Storage
