### ISSUE TITLE
Unity-style components

### ISSUE THREAD

**Issue by Domiii** [photonstorm/phaser#2389]
I see that there already is a sort of component-like concept in Phaser (in [src/gameobjects/components](https://github.com/photonstorm/phaser/tree/master/src/gameobjects/components)), where you can add components to a GameObject to add extra functionality to it. However, for some reason, those components do not provide default "message functions", such as `create`, `update`, `render` etc.

Is there any reason, why we cannot just have "Unity-style components" (sorry, don't know how else to call this, but if you are familiar with Unity, this should be pretty self-explanatory), to do things like the following?

```javascript
Phaser.defineComponent('Player', {
  // ...
  create: function() {
    // my player initializer
  },
  update: function() {
    // my player update...

    // get a reference to the actual Player GO
    var go = this.gameObject;
    // ...
  }
});

Phaser.defineComponent('MeleeAttacker', {
  // ...
  update: function() {
    // my attacker update...
    var target = this.findTarget();
    if (this.canAttack(target)) {
      this.attack(target);
      // ...
    }
  }
  // ...
});

var player = game.add.sprite(400, 300, 'player');
player.addComponent('Health');
player.addComponent('Player');
player.addComponent('MeleeAttacker');
// ...
```

In Unity, there is also message sending where all components that defined the method of given name will get executed, and a lot more. E.g.:

```javascript
Phaser.defineComponent('Unit', {
  // ...
  damage: function(attackInfo) {
    // ...
    if (this.isVulnerable()) {
      var health = this.GetComponent('Health'):
      health.value -= attackInfo.amount;
    }
  }
});

// ...

Phaser.defineComponent('Attacker', {
  dealDamage: function(amount, target) {
    var attackInfo = {
      attacker: this.gameObject,
      target: target,
      amount: amount
    };
    target.sendMessage('damage', attackInfo);
    this.sendMessage('onDealtDamage', attackInfo);
  }
});
```

Of course, all of those features can be added slowly over time. But I'm just wondering if there is something that speaks against it in general, because some of this stuff can be implemented very quickly, and it does give a great deal of flexibility to the engine! :)

**Comment by MrDallOca** [comment]
I don't think that is a bad idea. But phaser uses a different approach. Instead of defining a component, you can create a 'class' (object returning function) and store it into Phaser game object.
You can even modify game objects prototypes to allow adding components.

Phaser is open source. Just go ahead and make some customisations and test them. You can share the results with the community too!

**Comment by Domiii** [comment]
Well, the current approach is less flexible and not as high-level. Instead of being able to attach behavior in form of multiple components (each component basically being a class with its own set of `start`, `update`, etc events overrible) to objects, you have to define one fixed class for each game object.

Simple example of where components take the upper hand: Imagine, you have a tower defense game with fixed towers and moving units. Units and towers share some behaviors (attacking and maybe health, maybe more). But they also have their own unique set of behaviors (e.g. towers can be upgraded in place, while units can move etc...). 

And most importantly: You already have a simplified version of this idea in [gameobjects/components](https://github.com/photonstorm/phaser/tree/master/src/gameobjects/components). But for some reason, you did not generalize them. Why did you hard-code some behavior components, but did not allow for a generalized version of the same concept, where everyone can define, attach and remove components to any game object? Is there a reason for this, other than (minor) performance considerations?

**Comment by MrDallOca** [comment]
Well, I think that maybe you could use a kind of **aggregation**, inserting your components into the prototype of your constructors functions. Remember that _"classes" in javascript are not classes_, so they are very flexible. Here's a sketch:


```javascript

function Tower(args)
{
    //Constructor
    
    this.doWhatTowersDo = function()
    {
        
    }
}

function addComponent(funcConstructor, funcBehavior, name)
{
    funcConstructor.prototype[name] = funcBehavior;
}

function defend()
{
    //bla bla bla   
}

addComponent(Tower, defend, "defend");

```

Are you talking about something like this but controlled by the game object or even by the Phaser object?

```javascript

Phaser.defineComponent(name, componet)
{
    //do boring verifications
    
    Phaser.Components[name] = function() //construtor function
    {
        (componet.create()).bind(this);
        update = componet.update;
        
        //etc...
    }
}

```

**Comment by Domiii** [comment]
That's exactly what I have already started implementing! Check my "`PhaserExtensions`" out [here](https://github.com/Domiii/MeteorGame1/blob/master/packages/meteor-phaser/).

[Here](https://github.com/Domiii/MeteorGame1/blob/master/packages/meteor-phaser/PhaserExtensions.Components.js) is the code for components. You can define them like this:

```javascript
/**
   * Define new component class of given name with given instance methods and static members.
   * @param {Object} [instanceMethods]
   * @param {Object} [staticMembers]
   * @param {Object} [staticMembers.defaultValues] Assigned initially (and on reset) to each component instance.
   * @param {Array.String} [staticMembers.requiredComponents] Make sure, each object having this component also has the given set of components.
   */
  PhaserExtensions.defineComponent = function(name, instanceMethods, staticMembers) {
    // create new Component class
    var ComponentClass = function(name, gameObject, initialValues) {
      Object.defineProperty(this, 'name', {
        value: name
      });
      this.gameObject = gameObject;
      this.game = gameObject.game;
      this._initialValues = initialValues;
      this.enabled = true;
    };
    ComponentClass.prototype = Object.create(PhaserExtensions.ComponentPrototypeBase);
    ComponentClass.prototype.constructor = ComponentClass;
    _.assign(ComponentClass.prototype, instanceMethods);

    // set of static members, shared between all components
    if (!!staticMembers) {
      _.assign(ComponentClass, staticMembers);
    }

    // register class
    PhaserExtensions.AllComponents[name] = ComponentClass;
  };
```

However, it would not work, if it was not for a [customized `GameObject` class](https://github.com/Domiii/MeteorGame1/blob/master/packages/meteor-phaser/PhaserExtensions.GameObject.js), inheriting from `Sprite` for now, with `getComponents`, `getComponent`, `addComponent`, `sendMessage`, `start`, `update`, `stop`, `reset` and `requireComponent` methods (again: for now).

I also added some prefab utilities to easily define objects in data form and apply the data to any object required, including something that Unity does not have that is prefabs for groups (since groups are a pretty cool and more unique feature of Phaser that Unity does not have (yet)).

[Here](https://github.com/Domiii/MeteorGame1/blob/master/client/game/core/create.js) are some applications with my first set of components defined [here](https://github.com/Domiii/MeteorGame1/tree/master/client/game/components):

```javascript
// TODO: Convert the whole thing to a prefab
function createCurrentPlayerCharacter() {
  //var group = game.world;
  var group = GameStatus.groups.units;
  var character = GameStatus.currentPlayerCharacter = group.create(0, 0, 'octacat');

  // TODO: Get or create player object
  character.addComponent('PlayerCharacter', { player: null });
  character.addComponent('CurrentPlayerCharacter', { speed: 300 });
  character.addComponent('Shooter', {
    bulletsGroup: GameStatus.groups.bullets,
    bulletSprite: 'bullet1',
    bulletSpeed: 300,
    shootDelay: 1
  });
  
  game.camera.follow(character);
}
```

```javascript
function createGroups() {
  GameStatus.groups = {
    units: PhaserExtensions.GroupPrefabs.createGroup(game, {}),

    bullets1: PhaserExtensions.GroupPrefabs.createGroup(game, {
      objectPrefab: {
        sprite: 'bullet1'
      }
    })
  };
}
```

I will share once I got a fully working sample and the whole thing cleaned up and debugged. :)

**Comment by MrDallOca** [comment]
Cool, man! It's getting more interesting!
I hope it get fully developed!

**Comment by MrDallOca** [comment]
Check out [this](https://github.com/luizbills/phaser-plugin-behavior)

**Comment by photonstorm** [comment]
Phaser doesn't use components at all actually, not in the sense you are talking about them. Phaser components are JavaScript mixins, used internally during base class creation only. What you're describing is more like an ECS really, which isn't something we'll add into the core I'm afraid.

I can see you've already been playing with it as an extension, so if you take it further please tell me (email / twitter) and I'll feature it on the web site and newsletter, as there have been other ECS's in the past and readers seem to like them.
