### ISSUE TITLE
Found  a nasty bug w/ p2 physics

### ISSUE THREAD

**Issue by Dillybob92** [photonstorm/phaser#2392]
If you are using p2 physics and do:

```
	   sprite.body.setCircle(20, 0, 25); 
	   sprite.body.fixedRotation=true;
```

You will not collide with left and right **world** bounds, but you do collide with **top and bottom world bounds**.

I just spent an hour or so trying to figure out why my character wasn't colliding left and right bounds but he was with top and bottom.. until I found this lol. Not sure if this is a bug or intended

**Comment by photonstorm** [comment]
The result you're seeing is because you've adjusted the Circles mass offset by quite a large value (25). The offset values are given in unit lengths, from the body center of mass, along the local x/y axis. Providing them re-calculates the bodies center of mass and bounding radius.
