### ISSUE TITLE
No destroy method on State class

### ISSUE THREAD

**Issue by jessefreeman** [photonstorm/phaser#24]
There should be a destroy method you can override in order to better organize state tear down when moving from state to state. Also the Game class will need to automatically call this when switching to the next state.

**Comment by jmdjr** [comment]
Old thread I know, but I have an issue directly related to this...

I am trying to implement a state agnostic development tool, how would I configure it so that its own game.input.onDown events are not wiped away when transitioning between two states?

**Comment by photonstorm** [comment]
I would set the InputManager to be `resetLocked`. Then it won't get cleared on a State change. It's up to you to manually manage the Input Handler as a result though.
