### ISSUE TITLE
this.sprite.anchor is undefined

### ISSUE THREAD

**Issue by NLilley** [photonstorm/phaser#2400]
Using Phaser.Physics.ARCADE:

When adding a graphics object to a sprite as a child, if you do so before enabling physics on the object, you get a this.sprite.anchor is undefined error in the game.update function.

If you move the graphics creation until after turning on physics, this error doesn't occur.

Stub:
This will cause an error:
player = game.add.sprite(constants.GAME_WIDTH / 2, constants.GAME_HEIGHT / 2);
var playerGraphic = game.add.graphics();
playerGraphic.drawCircle(0, 0, 64);
player.addChild(playerGraphic);
game.physics.enable(player);

This will not:
player = game.add.sprite(constants.GAME_WIDTH / 2, constants.GAME_HEIGHT / 2);
game.physics.enable(player);
var playerGraphic = game.add.graphics();
playerGraphic.drawCircle(0, 0, 64);
player.addChild(playerGraphic);

Stack trace:
Phaser.Physics.Arcade.Body.prototype.preUpdate()
 phaser.js:83858
Phaser.Component.PhysicsBody.preUpdate()
 phaser.js:45493
Phaser.Graphics.prototype.preUpdate()
 phaser.js:53441
Phaser.Component.Core.preUpdate()
 phaser.js:43817
Phaser.Sprite.prototype.preUpdate()
 phaser.js:46998
Phaser.Group.prototype.preUpdate()
 phaser.js:32550
Phaser.Stage.prototype.preUpdate()
 phaser.js:30910
Phaser.Game.prototype.updateLogic()
 phaser.js:34761
Phaser.Game.prototype.update()
 phaser.js:34703
Phaser.RequestAnimationFrame.prototype.updateRAF()
 phaser.js:59420
Phaser.RequestAnimationFrame.prototype.start/this._onLoop()
 phaser.js:59404

**Comment by ForgeableSum** [comment]
You cannot add a Phaser.Graphic as a child of a sprite because it is not an extended DisplayObject (like a sprite or image). You should only use addChild on things like groups, sprite and images.

**Comment by NLilley** [comment]
Is it something that should be avoided all together then?  Because as I say, if you reverse the ordering of the assignments then Phaser appears to do what I want.  What would the preferred approach of building sprites out of graphics be?

**Comment by ForgeableSum** [comment]
Not sure what you mean by "building sprites out of graphics". What is your ultimate goal here - why does the graphic need to be a child of the sprite? If you need to reference the graphic from the sprite, simply create your own manually (there is no need to add it as a child).

**Comment by photonstorm** [comment]
When you enable a Sprite for physics it will scan all of its children, and give them their own physics bodies as well. I suspect this isn't what you actually want (i.e. you just want a single Sprite and to use the Graphics object almost as a texture for it?) - not for each of them to have their own independent bodies.

I think what this issue has highlighted though is a problem with enabling a Graphics object to have a physics body. Looking over the code I can see it has the component for it, but its preUpdate isn't set up for it. I'll have a play and see, but I suspect Graphics objects shouldn't have a physics body at all. Eitherway this is definitely a bug, but not quite as clear cut as you'd expect.

**Comment by NLilley** [comment]
Okay cool,

I wanted to use a sprite game object to the units in a game I was making, but didn't want to actually create the assets for them, and so thought it would be easier to just create them dynamically.

I think I may have gotten the idea to do so from examples like:
http://phaser.io/examples/v2/display/graphics-child

I have uploaded the game I was toying with to
http://www.nlilley.io:8003/

The player and enemy ships are all graphics objects, as are the bullets, planets, stars and enemy indicators.

**Comment by photonstorm** [comment]
For that the best approach is to create a Graphics object, then `generateTexture` on it, and assign that texture to all the Sprites that need it. This is the most optimal way of using Graphics objects as Sprite textures (and also will get around the bug you've found re: physics body)

**Comment by NLilley** [comment]
Thanks Richard, will have to try that.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
