### ISSUE TITLE
Using addChild add's to the draw calls

### ISSUE THREAD

**Issue by Dillybob92** [photonstorm/phaser#2401]
I just noticed if I create a sprite and then another one using `addChild` to that sprite's parent, it actually accumulates extra draw calls. 

I am not sure if this is intended or how Pixi / Phaser work internally? But, I could let's say just add that sprite to the game world wherever and not add it to the parent using `addChild` and then just reposition it seperately (since it's not bound to the parent), and it would result in hundred's of saved drawn calls. 

My suggestion is, shouldn't sprites that be added to their parent not add those extra drawn calls or is that just how the group system is set up?

**Comment by Dillybob92** [comment]
For example:


```
MONSTER_SPRITE_LAYER = game.add.group();
var temp_monster = game.add.sprite(0, 0, 'Bat');  
var monsterShadow = game.add.sprite(temp_monster.x, temp_monster.y, 'GameSprite', 'MonsterShadow', temp_monster);										
```

I can add thousand's of these, and the draw call will not be increased at all. I can lately just reposition the monsterShadow separately later since it's not added to a group (parent positioning).

Now, take a look here:


```
MONSTER_SPRITE_LAYER = game.add.group();
var temp_monster = game.add.sprite(0, 0, 'Bat');  
var monsterShadow = game.add.sprite(temp_monster.x, temp_monster.y, 'GameSprite', 'MonsterShadow', temp_monster);											temp_monster.addChild(monsterShadow);
```

If I do this 1000 times, I get 1000 more drawn calls, doesn't seem right. The trade-off is that now I don't have to reposition monsterShadow, but I don't think that's worth the 1000 extra drawn calls? Not sure, just trying to show an example here

**Comment by photonstorm** [comment]
Draw calls are based on the texture being rendered, not the display
hierarchy. You gain 1000 draws because you're ping ponging between two
textures, so it can't batch them.

Use a texture atlas, then as long as parent and child use frames from the
same atlas it will batch the draws.



On Monday, 28 March 2016, Dillybob92 <notifications@github.com> wrote:

> For example:
>
> MONSTER_SPRITE_LAYER = game.add.group();
> var temp_monster = game.add.sprite(0, 0, 'Bat');
> var monsterShadow = game.add.sprite(temp_monster.x, temp_monster.y, 'GameSprite', 'MonsterShadow', temp_monster);
>
> I can add thousand's of these, and the draw call will not be increased at
> all. I can lately just reposition the monsterShadow separately later since
> it's not added to a group (parent positioning).
>
> Now, take a look here:
>
> MONSTER_SPRITE_LAYER = game.add.group();
> var temp_monster = game.add.sprite(0, 0, 'Bat');
> var monsterShadow = game.add.sprite(temp_monster.x, temp_monster.y, 'GameSprite', 'MonsterShadow', temp_monster);                                           temp_monster.addChild(monsterShadow);
>
> If I do this 1000 times, I get 1000 more drawn calls, doesn't seem right.
> The trade-off is that now I don't have to reposition monsterShadow, but I
> don't think that's worth the 1000 extra drawn calls? Not sure, just trying
> to show an example here
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2401#issuecomment-202216089>
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by Dillybob92** [comment]
Oh so both texture's need to be on the same atlas. Because my GameSprite is my atlas, but Bat isn't on there because that monster has animations. But if I stick Bat on my GameSprite atlas it should be fine then?  I see now. Thank you for explaining this, I got really confused

**Comment by Dillybob92** [comment]
I am going to give this a good read too. If anyone else is wondering about animations inside texture atlas's :) 

http://www.joshmorony.com/how-to-create-animations-in-phaser-with-a-texture-atlas/

Thanks again @photonstorm
