### ISSUE TITLE
bitmapData won't correct drawing sprite if his texture in atlas have indent

### ISSUE THREAD

**Issue by PhaserDebugger** [photonstorm/phaser#2405]
My atlas {"frames":[{"filename":"sprite1","frame":{"x":0,"y":0,"w":53,"h":53},"rotated":false,"trimmed":false,"spriteSourceSize":{"x":0,"y":0,"w":53,"h":53},"sourceSize":{"w":53,"h":53}},{"filename":"sprite2","frame":{"x":54,"y":0,"w":113,"h":105},"rotated":false,"trimmed":false,"spriteSourceSize":{"x":0,"y":0,"w":113,"h":105},"sourceSize":{"w":113,"h":105}},{"filename":"sprite3","frame":{"x":0,"y":54,"w":53,"h":53},"rotated":false,"trimmed":false,"spriteSourceSize":{"x":0,"y":0,"w":53,"h":53},"sourceSize":{"w":53,"h":53}}]}.
![image](https://cloud.githubusercontent.com/assets/18153479/14126649/ffc9bdba-f62b-11e5-91c3-e0ef56f7cb5e.png)

Following code get bad result
```
function create() {
	game.stage.backgroundColor = "#4488AA";
	var decorations = ["sprite1", "sprite2", "sprite3"];
	shadowTexture = game.add.bitmapData(game.width, game.height);
	shadowSprite = game.add.image(0, 0, shadowTexture);
	for (var i in decorations)
	{
		var obj = game.add.sprite(i * 300, 300, 'atlas', decorations[i]);
		var p = new Phaser.Sprite(game, i * 300 + 100, 400, 'atlas', decorations[i]);
		p.tint = 0;
		shadowTexture.draw(p);
	}
	shadowTexture.dirty = true;
}
```

![bug](https://cloud.githubusercontent.com/assets/18153479/14126467/a30dd59e-f62a-11e5-992e-642e69659043.png)

but without tint all are good
![image](https://cloud.githubusercontent.com/assets/18153479/14126589/7fb62d70-f62b-11e5-856d-e9cecdf1045d.png)

**Comment by photonstorm** [comment]
Thanks, this is now fixed in dev.
