### ISSUE TITLE
Cannot get accurate `width` and `height` of child sprites

### ISSUE THREAD

**Issue by Domiii** [photonstorm/phaser#2406]
[Sample fiddle here](http://jsfiddle.net/ywzmkso3/21/).

Turns out, `width` and `height` (as defined in [src/pixi/display/Sprite.js](https://github.com/photonstorm/phaser/blob/master/src/pixi/display/Sprite.js#L126)) ignores parent scaling. I am guessing that this is by design (so setting it works as expected), but it should at least be properly documented.

On the other hand, since [`getBounds`](https://github.com/photonstorm/phaser/blob/master/src/pixi/display/Sprite.js#L200) does take `worldTransform` into consideration, this should be the way to go. Sadly, the numbers don't make sense to me.

[In this sample fiddle](http://jsfiddle.net/ywzmkso3/21/), parent's and child bounds' `width` and `height` should be identical (Shouldn't it?). But for some reason, the numbers don't match.

**Comment by photonstorm** [comment]
The problem with PIXI `getBounds` is that it's deferred. For example say you have a Parent with Child A, and that child has Child B. So a simple 3 depth hierarchy. If you modify any properties of 'Parent' such as scale, position, rotation, then do `getBounds` on either child, none of them will take the parent changes into account. Equally if you change Parent and Child A, then Child B will be missing out on both sets of updated data _until the next render pass has processed_.

You can mitigate this to a degree by calling `updateTransform` on the top-most layer of your hierarchy, as it will flood down and update all objects as it goes. Then `getBounds` will be accurate, at that point in time anyway (although possibly then invalidated in the very next call).

This is the core problem of deferred updates, but as it's how Pixi works we're bound to it with Phaser. Ideally it would use immediate updates, but it trades that for speed instead (as this way you only ever process the transform update stack once per loop). The downside is the loss of accuracy and blatantly incorrect values between frames.

**Comment by photonstorm** [comment]
Docs updated to reflect how this works.
