### ISSUE TITLE
Tween onLoop not firing in v. 2.4.6

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2407]
onLoop event isn't firing in 2.4.6. Works in 2.3.0 when I tested. Leg is a sprite whose parent is a Phaser.Group whose parent is a Phaser.Group whose parent is the game world (Game World -> Group -> Group -> Sprite) - not sure if that has anything to do with it but worth testing if you can't recreate the problem with just the code below (I've noticed other odd behaviors with this setup, but could be separate issues). 

Note that yoyo and repeat are set. The event doesn't fire if yoyo is turned off as well. leg is the sprite I'm tweening in the code below. 

```
function tweenLeg(leg) {

    var pauseTime = 110;

    var legTween = game.add.tween(leg).to({
        x: 5,
    }, 100, Phaser.Easing.Default, false, 0, -1, true);

    legTween.onLoop.add(function() {
    console.log('this never fires in phaser 2.4.6 but does fire in 2.3.0!'); 
        legTween.pause();
        setTimeout(function() {

            legTween.resume();

        }, pauseTime);

    });


    legTween.start();

}
```

**Comment by photonstorm** [comment]
`onLoop`
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
