### ISSUE TITLE
small question about tween's being destroyed

### ISSUE THREAD

**Issue by PokemonAshLovesMyTurkeyAndILikeYouTwo** [photonstorm/phaser#2408]
Let's say if I make a group.

Let's say if I add a sprite to that group via `add`.

Let's say I attach a repeating yoyo tween to that sprite

Let's say I run `mygroup.destroy()`, it removes all the sprites from my game, but do the tween's still run in the background or do I have to manually destroy those as well? 

I'm just getting anxiety because I don't want to create memory leaks as my maps are getting kind of large, that's all :)

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
I did some digging

the destroy actually doesn't check for tweens because I checked `game.tweens._tweens`

But, you can do:

`game.tweens.removeFrom(mygroup);`

before running destroy, and since everything inside removefrom is synchronous, we should be fine.

Maybe if Richard agree's... maybe add a if condition inside the destroy method to check if that object has any tween's associated with it and remove them too? I think it will help with memory leaks as I didn't even know and had 14 tween's running from looking at `game.tweens._tweens` :8ball: even after destroying my group, haha.

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
And I'm back!

I added this:

```
	    // Does this object have any tween's attached?
		this.game.tweens.removeFrom(this)
```

Inside `    destroy: function (destroyChildren) { `

 Works great!

**Comment by photonstorm** [comment]
Yeah there is no harm in doing this, so I've added it :) Also tightened up Tween.update.

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
Oh sweet! Thank you Photonstorm, this is awesome
