### ISSUE TITLE
Phaser odd error

### ISSUE THREAD

**Issue by jdnichollsc** [photonstorm/phaser#2411]
Hi guys,

I'm loading image dynamically but the following errors appear sometimes.

http://screencast.com/t/0HHc3x4bYM
http://screencast.com/t/O6iNloELaH

Errors:
`phaser.js:38548Uncaught TypeError: Cannot read property 'time' of null`
`phaser.js:35015Uncaught TypeError: Cannot read property 'reset' of null`
`phaser.js:35004Uncaught TypeError: Cannot read property 'setMute' of null`
`phaser.js:35015Uncaught TypeError: Cannot read property 'reset' of null`

Thanks in advance, Nicholls

**Comment by hilts-vaughan** [comment]
I'm pretty sure sprites need to be preloaded in Phaser.

**Comment by jdnichollsc** [comment]
:o testing mmm

**Comment by jdnichollsc** [comment]
I'm loading new images with my following code:

`var loader = new Phaser.Loader(this.game);`
`loader.image('photo', imageData);`
`loader.onLoadComplete.addOnce(this.loadPhoto, this);`
`loader.start();`

I do not know what is happening :/

**Comment by photonstorm** [comment]
Do not create a new instance of the Loader. Use the preload function and
make the sprites in the 'create' function, as only then are they actually
processed and in the cache ready for use.

On Sunday, 3 April 2016, Juan David Nicholls Cardona <
notifications@github.com> wrote:

> I'm loading new images with my following code:
>
> var loader = new Phaser.Loader(this.game);
> loader.image('photo', imageData);
> loader.onLoadComplete.addOnce(this.loadPhoto, this);
> loader.start();
>
> I do not know what is happening :/
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2411#issuecomment-205068595>
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by jdnichollsc** [comment]
Other eventListener was the error, Phaser works perfect :dancers: 

Thanks @photonstorm

**Comment by okaybenji** [comment]
@jdnichollsc Hey, would you mind elaborating on what was causing this issue (if you recall)? Some of our users are getting this error in our Phaser game and I can't tell why.

**Comment by jdnichollsc** [comment]
@okaybenji ohhh I don't remember, can you share your code? what version of Phaser are you using? 👍

**Comment by okaybenji** [comment]
@jdnichollsc Unfortunately, I don't think I can. We're on Phaser CE 2.10.0. That's okay, thanks for being willing to help. :)

**Comment by jdnichollsc** [comment]
@okaybenji not share all the code, only the way you are using to load the images 👍

**Comment by okaybenji** [comment]
@jdnichollsc Ah, I can actually do that quite easily because we open sourced it :) https://github.com/goldfire/phaser-webpack-loader/blob/master/src/index.js
Though, I don't see what a `setMute` method could have to do with loading images. I assume it must be related to sound. The breadcrumb trail leading up to the error is GET requests for `webm` files.
