### ISSUE TITLE
Phaser text positioning bug with high resolution

### ISSUE THREAD

**Issue by mattcolman** [photonstorm/phaser#2416]
Please see this code pen, it's just a modified example from the Phaser website to include devicePixelRatio resolution.

This means that the example will work fine on screens with window.devicePixelRatio == 1, but will incorrectly center and right justify the text on higher pixel density screens.

http://codepen.io/mattcolman/pen/BKmQMZ/

**Comment by mattcolman** [comment]
Just some further info on this:
1. set the Phaser resolution to be window.devicePixelRatio.
2. create a new text object. Let's say the text takes up 100 pixels on the Phaser Stage. The text will always take up 100 pixels on the stage no matter what resolution you have, however, text.width returns 100 * resolution which is not my expected result. I would expect it to always return 100.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by mattcolman** [comment]
Nice! Thanks Rich!

**Comment by TolgaND** [comment]
I still have this problem with the newest release!
