### ISSUE TITLE
Physics.Arcade.Body's speed property is only set when the body moves

### ISSUE THREAD

**Issue by mark-henry** [photonstorm/phaser#2417]
[This if guard](https://github.com/photonstorm/phaser/blob/v2.4.4/src/physics/arcade/Body.js#L468) erroneously guarantees that the body's `speed` property is not set to zero when the body stops.

`if (this.position.x !== this.prev.x || this.position.y !== this.prev.y)`

guards the setting of the `speed` and `angle` properties. This was probably intended to avoid bugs when setting the `angle` property but should not guard the speed-setting line.

Suggest that the speed-setting line be moved out of the if statement.

**Comment by photonstorm** [comment]
Agreed, Fixed in dev.
