### ISSUE TITLE
[suggestion] Prevent kill() from being called on sprites that are already dead

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2419]
I run into this error a lot when attempting to call kill on an already dead object - "maximum call size exceeded". I suggest preventing kill from being called on dead objects in Phaser (so I don't have to add a boolean check in every place I use kill).

**Comment by photonstorm** [comment]
This is literally all the kill function does:

```
    kill: function () {

        this.alive = false;
        this.exists = false;
        this.visible = false;

        if (this.events)
        {
            this.events.onKilled$dispatch(this);
        }

        return this;

    }
```

There is no way calling this repeatedly would cause a call size error. Something else is doing it.

**Comment by Dillybob92** [comment]
Give us the stack trace for that call size error (or post it on the HTML 5 forums) we can help.

**Comment by photonstorm** [comment]
Just to add that I need a code example showing this happening, or I'll have to close it off, sorry.

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

If it's easier you can use the [Phaser Sandbox](http://phaser.io/sandbox/) to create a code sample (as this is now running the latest build of Phaser). Enter your code, click the 'save icon' in any of the editor tabs, and paste the URL here.
