### ISSUE TITLE
Unit Testing with Karma/ jasmine

### ISSUE THREAD

**Issue by karneaud** [photonstorm/phaser#2421]
Can unit testing be done with Karma and Jasmine?

Been developing with phaser and unit testing some of the simplest of tasks are become such a pain that I seem to spend more time debuggin unit tests than the actual project code

**Comment by photonstorm** [comment]
There aren't any Phaser unit tests, so make them in whatever you want, it doesn't really matter. There are no plans to add any either, the API is just too broad to do it justice. It's something we'll address in Lazer, but not here.

**Comment by karneaud** [comment]
"Lazer"???

**Comment by clark-stevenson** [comment]
https://github.com/photonstorm/lazer
