### ISSUE TITLE
generateTilingTexture console.log left in Phaser 2.4.6 release JS

### ISSUE THREAD

**Issue by JamesSkemp** [photonstorm/phaser#2422]
I was following [Emanule Feronato's character selection tutorial](http://www.emanueleferonato.com/2016/01/20/phaser-tutorial-creation-of-a-html5-character-selection-screen-like-the-one-in-crossy-road-ios-smash-hit/) and noticed during my implementation that a message was being logged in Chrome's console from line 22487 in phaser.js (2.4.6):

> console.log('generateTilingTexture', texture, frame);

I assume this was supposed to be commented out and just got missed? Testing against 2.4.4's JS doesn't log this message.

Simple example:

```
<!DOCTYPE html>
<html>
<head>
    <title></title>
	<meta charset="utf-8" />
</head>
<body>
	<script src="lib/phaser.min.js"></script>
	<script>
		var game = new Phaser.Game(400, 300, Phaser.AUTO, 'phaser-example', { preload: preload, create: create });

		function preload() {
			game.load.image('button', 'assets/block.png');
		}

		function create() {
			var scrollingMap = game.add.tileSprite(0, 0, game.width, game.height, 'button');
		}
	</script>
</body>
</html>
```

**Comment by photonstorm** [comment]
This is fixed in the dev branch (and was some time ago). Will be part of 2.4.7 next week.
