### ISSUE TITLE
Offset on "sprite.body" doesn't work.

### ISSUE THREAD

**Issue by Mourtz** [photonstorm/phaser#2430]
Hi,

Noticed while working on a project with Phaser that "sprite.body.offset" doesn't work when the pivot point of the sprite has been changed.

Looking forward to patching this.

Thanks.

Example Code:
```js
function preload() {
	game.load.image('foo', 'foo.png');
    game.load.physics('foo-coll', 'foo.json');
}

function create(){       
    //	Enable p2 physics
    game.physics.startSystem(Phaser.Physics.P2JS);
    game.physics.p2.gravity.y = 0;
    game.physics.p2.restitution = 1;

    var bar = game.add.sprite(game.world.centerX, game.world.centerY, 'foo');
    bar.anchor.setTo(0.5);
    bar.pivot.x = -200;
    bar.pivot.y = 300;

    game.physics.p2.enable(bar, true);
    bar.body.kinematic = true;

    bar.body.clearShapes();
    bar.body.loadPolygon('foo-coll', 'foo');

    bar.body.offset.setTo(this.game.width / 3);
}
```

**Comment by Mourtz** [comment]
By looking at the code I found out that "body.offset" is never being used.  Apparently, this is a feature request instead of bug fix.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by Mourtz** [comment]
The thing still seems broken. Currently offset changes the position of the sprite along colliders position.

@photonstorm
