### ISSUE TITLE
Feature implementation

### ISSUE THREAD

**Issue by SVasilev** [photonstorm/phaser#2431]
Hello,
I've looked for a implemented game menu feature in Phaser. I did not find one siutable for my needs so I've implemented it. See the zip file for example. There is a lot of work to be done yet, but for now it is kind of stable. Do you have interest to have such a feature in Phaser? I can adapt the utility to be one of the Phaser objects and make a pull request.
[GameMenu.zip](https://github.com/photonstorm/phaser/files/217821/GameMenu.zip)

**Comment by photonstorm** [comment]
Thanks for this, but I would say it's best suited as a plugin published in your own repo. Everyone likes to do their menus slightly differently, but this could serve as a good template to offer them. If you release it on GitHub (or similar) then email me and I'll mention it on the Phaser site.
