### ISSUE TITLE
Polygon hole

### ISSUE THREAD

**Issue by pokatomnik** [photonstorm/phaser#2432]
Is there any way to make a hole in Polygon graphics?

**Comment by Weedshaker** [comment]
I made a donut and worked around this by using the https://www.codeandweb.com/physicseditor drawing a horseshoe shape with a 1px gap.

**Comment by photonstorm** [comment]
The short answer is 'no', but you can definitely do as Weedshaker suggested and create a polygon that almost closes, but doesn't quite (so the final points don't get eliminated during decomposition)
