### ISSUE TITLE
Video loaded as blob on Chrome Android

### ISSUE THREAD

**Issue by JuCarr** [photonstorm/phaser#2433]
Hi there,

I ran into this issue lately and even if I pretty sure this is not a Phaser bug, I report it here in case you'd like to add a special case to fix the issue.

**The issue:**
Loading a video as a blob and playing it does not work on Chrome Android. The video loads but then silently fails to play (but it works perfectly on Firefox Android and on Chrome and Firefox desktop).

This issue shows up with the 2 devices I tried:
- Asus Tablet running Android 4.4.2 and Chrome 49
- Nexus Phone running Android 5.1.1 and Chrome 49

I have no idea about the why but after testing many things, I found out that setting "blob" instead of "arraybuffer" as the xhr responseType and saving the file data directly as the response makes it work on Chrome Mobile.

````
// Phaser Loader L2118
this.xhrLoad(file, this.transformUrl(file.url, file), 'blob', this.fileComplete);
// instead of
this.xhrLoad(file, this.transformUrl(file.url, file), 'arraybuffer', this.fileComplete);
````
````
//Phaser Loader L2705
file.data = xhr.response; 
// instead of
file.data = new Blob([new Uint8Array(xhr.response)]);
````

**Comment by photonstorm** [comment]
Thanks. If you change the Loader like above, does it still work in other browsers for you? Or does it fix it for Chrome, but break it everywhere else?

**Comment by JuCarr** [comment]
It works fine for Chrome and Firefox, both on Android and desktop. I didn't check on IE but I'll try tomorrow and let you know.
Unfortunately I can't check on Safari  iOS / MacOS, I don't own any Apple device.

**Comment by JuCarr** [comment]
So, setting the responseType as blob does works with IE11 on Windows 8.1

Furthermore, IE11 doesn't like to have a blob set as a video source like this:
```
//Phaser Loader L2705
file.data = new Blob([new Uint8Array(xhr.response)]);
```

It wants the mime type to work:
```
//Phaser Loader L2705
file.data = new Blob([new Uint8Array(xhr.response)], , {type : "video/mp4"}); // for example
```

Surprisingly, it doesn't complain about a mime type when the responseType is directly set to 'blob'

**Comment by photonstorm** [comment]
Thanks for the details. I'll test on iOS here and then either make the change, or conditionally patch it based on browser.

**Comment by photonstorm** [comment]
Tested in Microsoft Edge (Win10) and iOS and works fine, so will make the change.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
