### ISSUE TITLE
Typescript + Group extends, `prototype.x` and `prototype.y` changed to `0` after construct

### ISSUE THREAD

**Issue by WhaleWatching** [photonstorm/phaser#2434]
In definition:

    constructor(game: Phaser.Game, x: number, y: number) {
      super(game, game.world, 'ComicWindow')
      this.x = x
      this.y = y
    }

In construction:

    this.game.world.add(new ComicWindow(this.game))

Then, comic window position changed to (0, 0)

**Comment by photonstorm** [comment]
In the code above you don't specify the x and y arguments when you do `new ComicWindow`, so surely they are bound to be 0x0? Unless you can demonstrate a bug in Phaser I think this needs asking in the forum really.

**Comment by WhaleWatching** [comment]
Sorry it's a mistake by me.
