### ISSUE TITLE
loadAudioTag calling different loader instance

### ISSUE THREAD

**Issue by SBCGames** [photonstorm/phaser#2435]
In Loader.js file in function loadAudioTag (https://github.com/photonstorm/phaser/blob/dev/src/loader/Loader.js#L2280) there is this line:
```javascript
// Why does this cycle through games?
Phaser.GAMES[_this.game.id].load.fileComplete(file);
```
Problem is, that this piece of code takes default loader created for game even in case that loadAudioTag was called within different loader instance.

Situation in which I encountered it: Android Chromium has bug where decoding music file takes ages (it was corrected after more than year short time ago) - like 15 seconds. So, Instead of loading all assets in the start of game I am loading all except music (I am in fact loading only short initial one). Rest of the music files are loaded in the background during game with separate Phaser.Loader instance. This works OK on FF and Chrome when WebAudio is used. On IE 11 where audioTag is used it does not work, because it comes across above maentioned line. It calls fileComplete on different instance of loader (default one), which throws warning: 'Phaser.Loader - active loading canceled / reset' and stops loader from correct work.

 Wider surrounding of that piece of code is:
```javascript
            var playThroughEvent = function () {
                file.data.removeEventListener('canplaythrough', playThroughEvent, false);
                file.data.onerror = null;
                // Why does this cycle through games?
                Phaser.GAMES[_this.game.id].load.fileComplete(file);
            };
            file.data.onerror = function () {
                file.data.removeEventListener('canplaythrough', playThroughEvent, false);
                file.data.onerror = null;
                _this.fileError(file);
            };
```

I think, that change like this would correct it (at least it works in IE11):
```javascript
                //Phaser.GAMES[_this.game.id].load.fileComplete(file);
                _this.fileComplete(file);
```

There is one more place in loader where I noticed similar construct - loadVideoTag

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
