### ISSUE TITLE
Naming convention with Point.Angle

### ISSUE THREAD

**Issue by ShawnHymel** [photonstorm/phaser#2436]
Minor issue: In every instance (that I found), "angle" means degrees and "rotation" means radians, except for the Point.angle() function (http://phaser.io/docs/2.3.0/Phaser.Point.html#angle), which returns radians.

**Comment by photonstorm** [comment]
I agree it's weird (it's not the only instance of this inconsistency either) but we sort of climbed in to bed with this devil, and now must lay with it. It's too entrenched to change at this point.

**Comment by ShawnHymel** [comment]
Hahahaha....fair enough. Figured I would point it out. Maybe an optional inDegrees argument to have angle() return degrees vs radians. That way you could at least get both? Call it a feature request, so I'll leave the issue closed.

**Comment by photonstorm** [comment]
`Point.angle` already has an `asDegrees` argument for this very reason. It just should be consistent in the first place though.

**Comment by ShawnHymel** [comment]
Ah! So it does. I was looking at the wrong version in the docs. Thanks!
