### ISSUE TITLE
Phaser v2.4.7 RC1 - running slow

### ISSUE THREAD

**Issue by Weedshaker** [photonstorm/phaser#2437]
Hi,

I haven't yet looked deeper into it, but just wanted to throw this into the round. The game shows the same or even slightly higher framerate with the newest update. Though, the character moves significantly slower. It seems as the p2.js physics run in slow motion.

Has anyone had the same or a similar issue?

I am using Phaser v2.4.7 RC1, phaser-tiled (latest release) and p2.js.

**Comment by photonstorm** [comment]
If you do _nothing but_ swap 2.4.7 RC1 for 2.4.6 does it speed-up again?

**Comment by Weedshaker** [comment]
yes, I did this couple times back and forth but couldn't figure why it should be slower eventhough the fps is equal...

**Comment by photonstorm** [comment]
Try this: set `game.forceSingleUpdate = false` somewhere when your game first starts. That's the only thing that I think would make any difference (in 2.4.7 this is now true by default)

**Comment by Weedshaker** [comment]
Yes, it is the forceSingleUpdate parameter which caused the slow down. Sorry, for stealing your time here, I should have figured this after I have had the same issue couple of month's ago when I started using particle storm, which also has this parameter to true in the examples.

I am just wondering, what is the big advantage of this being "true", that the phaser default changed at this version? Maybe I should adjust my game to run well with forceSingleUpdate?

Thank you in advance for your answer!
Cheers

**Comment by photonstorm** [comment]
That's interesting. I'm not seeing any difference in the apps we've got that use p2, but it's not exactly an exhaustive study. All the flag does is insist that there is at least one call to 'update' per loop (plus as many extra are needed to catch-up), and one call to 'render'.

Without it the loop will determine for itself if it should call 'update' or not based on elapsed time, and other things. The problem is a bit two-folded. On slow systems and generally low powered devices, having it `false` causes all kinds of jerky movement and inconsistent display, even if it's rendering at 60 fps. On high-end kit you don't really notice it either way.

**Comment by Weedshaker** [comment]
I will update our tech demo and send you the link asap, so you can see the effect for yourself.

**Comment by Weedshaker** [comment]
You can see what switching "game.forceSingleUpdate = " does to the tech demo here: http://tarutarolegends.com/shoga9team/ , if you want. (and controls, when needed: http://tarutarolegends.com/demo-controls/)

You can close this issue... Thank you very much for your quick support/help!

**Comment by photonstorm** [comment]
Yeah I toggled it from the console and everything remains at the same speed other than the character movement (which is obviously done in p2), like it's running twice as slow, but the menus etc were all fine. Sadly I can't see any source to know what you're doing though in your update.

**Comment by Weedshaker** [comment]
I do have an update object managing "characters", etc being hooked into the update cycle or spliced out. Then cycling through it on update:

```javascript
    update(){
        this.updateArray.forEach((func) => {func();});
    }
```

on the character level, the controls are handled the same way as it is common in the examples. So, there is nothing extraordinary, despite this forEach.
