### ISSUE TITLE
Phaser tilemap collision not taking into account movement?

### ISSUE THREAD

**Issue by hihihih565** [photonstorm/phaser#2438]
Hello,

I'm trying to move tilemaps around but the collision doesn't seem to follow with them. You can clearly see in the debug that they have moved but the collision is still staying in its main place. I have tried changing all sorts of values but have come to no luck. I also tried switching to P2 physics and converting the map but still not luck.

Link to game: [http://googledrive.com/host/0B9hdQxQYYzvWbWpmVjZneVBSVkE](http://googledrive.com/host/0B9hdQxQYYzvWbWpmVjZneVBSVkE)

`	createMap: function() {
	    this.layers = {};
	    this.map = this.game.add.tilemap('east');
		this.map.addTilesetImage('dungeon_tiles', 'tiles');
		//var rnd = this.game.rnd.integerInRange(0, 1);
		var rnd = 1;
		console.log("rolled a ", rnd);
		
        this.map.layers.forEach(function (layer) {
            this.layers[layer.name] = this.map.createLayer(layer.name);
            this.layers[layer.name].fixedToCamera = false;
            
            if(layer.properties.collision) {
                this.map.setCollision(291, true, this.layers[layer.name]);
                collision = this.map.getLayer(layer).name;
            }
            
            if(layer.properties.ignore) {
                return;
            } else if(layer.properties.group == rnd) {
                this.layers[layer.name].visible = true;
            } else {
                this.layers[layer.name].visible = false;
            }
        }, this);
        
        this.layers2 = {};
        this.map2 = this.game.add.tilemap('map');
		this.map2.addTilesetImage('dungeon_tiles', 'tiles');
		
		this.map2.layers.forEach(function (layer) {
		    this.layers2[layer.name] = this.map2.createLayer(layer.name);
            this.layers2[layer.name].fixedToCamera = false;
            this.layers2[layer.name].position.set(256, 0);
            
            if(layer.properties.collision) {
                this.map2.setCollision(291, true, this.layers2[layer.name]);
                collision2 = this.map2.getLayer(layer).name;
            }
        }, this);
        
        this.layers[collision].debug = true;
        this.layers2[collision2].debug = true;
	},`

**Comment by photonstorm** [comment]
You aren't supposed to move the tilemap layers via `position`, they're locked to the camera and it's the camera that moves around them. If you adjust them in the way you're doing then all of the physics collisions will be out (by whatever amount they've been moved) as they're no longer at that position in the world any more.

**Comment by hihihih565** [comment]
Would you be able to tell me how to move them, I have been stuck on this for around 2 weeks now. I have tried so many things.

**Comment by photonstorm** [comment]
You move the camera, then the layers will follow. Look at any of the Tilemap examples, as they all do it (either directly by changing the camera position, or by following a sprite that moves around the map)

**Comment by hihihih565** [comment]
Yes but they're all 1 Tilemap, this is offsetting different tile maps :/

**Comment by photonstorm** [comment]
Look at the example called `blank tilemap`, it has 3 layers all scrolling at different speeds.

**Comment by hihihih565** [comment]
Ahhhh right I set the scrollFactorX to 256(size of tilemap) Probs why it didn't work! 😂

**Comment by hihihih565** [comment]
I don't think I explained this well enough, I'm trying to have multiple tilemaps makeup a dungeon and I want to offset them. Just looked into blank tilemap example and its not really what I'm trying to achieve.

https://gyazo.com/53cd0d5c1c1064944d17693ecd6d689a

I have 2 tilemaps and I want to offset them by 256 in whatever direction to create prefabbed roomed generated dungeon. This will obviously lead to around 25-40 tilemaps in the end, just haven't finish off the rooms.

**Comment by photonstorm** [comment]
It can't be done.

Hey @obiot can MelonJS do this? If so I suggest you use that instead @hihihih565

**Comment by hihihih565** [comment]
http://www.html5gamedevs.com/topic/13158-advanced-tutorial-building-composite-maps-in-phaser-using-tiled/#comment-75434 I look into how this guy did it and he turned the collision layer into a sprite and did the collision that way. Do you think that is more plausible?

**Comment by photonstorm** [comment]
I still think you're trying to fit a round peg through a square hole.

**Comment by hihihih565** [comment]
Hmmm okay, thanks for all the help! Any chance phaser will support moving tilemaps in the near future :P?

**Comment by obiot** [comment]
LOL, Should be pretty the same actually, as the collision layer in Tiled is "translated" into Shape objects that we then use for the collision, so if you move the Tile Layer itself it won't move these objects. 

what i would do though, is to get a list of all the collision objects, and then just offset them together with the tile layer when needed (could be somehow automatic using some signal/event function)

**Comment by xxzzrr6000000** [comment]
Hello world

**Comment by xxzzrr6000000** [comment]
![_ -animation](https://user-images.githubusercontent.com/38167040/38464351-064c867e-3afc-11e8-9722-2a6f6dda0b3e.gif)

**Comment by xxzzrr6000000** [comment]
SOS
