### ISSUE TITLE
2.4.6: PIXI not defined when require('phaser') after npm install

### ISSUE THREAD

**Issue by ZakSignal** [photonstorm/phaser#2440]
Steps to repro:
1. npm install --save phaser
2. copied phaser.min.js into source file directory
3. coffeescript file has line Phaser = require('phaser') at beginning

Result:
Console error in browser: phaser.js:23083 Uncaught ReferenceError: PIXI is not defined

Expected:
PIXI is automagically included in minified phaser (or PIXI is an npm dependency and auto-installed into my node_modules for easy minified PIXI copying).

**Comment by photonstorm** [comment]
PIXI _is_ included in the phaser.min file. But if 'required' like this is still need exposing globally. See https://github.com/photonstorm/phaser#browserify--cjs

**Comment by ZakSignal** [comment]
Thanks for the RTFM link! We are using browserify, so I'll attack it like the text says.

**Comment by photonstorm** [comment]
I wish we didn't have to do it like this, but without an expensive and time
consuming refactor it's the best we can do for now. Rest assured we won't
have the same issue in Lazer.

On Monday, 25 April 2016, ZakSignal <notifications@github.com> wrote:

> Thanks for the RTFM link! We are using browserify, so I'll attack it like
> the text says.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2440#issuecomment-214428120>
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27
