### ISSUE TITLE
2.4.7: Arcade Physics overlap acting much different?

### ISSUE THREAD

**Issue by rgk** [photonstorm/phaser#2441]
In 2.4.6 I had this.bullets.forEachAlive(this.bulletLogic, this);
and inside bulletLogic I had a physics overlap function. The overlap function would constantly loop correctly with game, allowing me to stack values.

In 2.4.7, the bullet logic runs the correct amount of times, constantly looping, but the overlap function seems to only run once (or twice). Aka it only triggers once it starts overlapping, and not constantly while its overlapping. The problem is I had stacking damage so the constant overlap was something I was taking advantage of. The overlap function also doesn't seem to trigger if the sprite is spawned overlapping the group.

Is this a bug or new functionality?
Also, thank you for the great Phaser release!

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

If it's easier you can use the [Phaser Sandbox](http://phaser.io/sandbox/) to create a code sample (as this is now running the latest build of Phaser). Enter your code, click the 'save icon' in any of the editor tabs, and paste the URL here.

**Comment by rgk** [comment]
Thanks for the response, hopefully this code example explains my issue.
http://phaser.io/sandbox/edit/tRtNjhEm
As you can see the overlay doesn't get called at all since it spawns on it. In 2.4.6 this worked.

**Comment by photonstorm** [comment]
Yes I can see what's going on now. I've created a simpler test case demonstrating this: http://phaser.io/sandbox/FAjSAqtP

I agree this is a bug and will address it in 2.4.8. Thanks for the report!

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
