### ISSUE TITLE
Expose Camera._shake.intensity as public property for tweening purposes

### ISSUE THREAD

**Issue by drhayes** [photonstorm/phaser#2442]
Loving the new Camera functionality in 2.4.7. The shake plugin I wrote that I'd love to get rid of gradually lowers the intensity over the life of the shake. With the way this functionality is written in `Phaser.Camera`, looks like exposing the `_shake.intensity` private-looking property with some kind of getter/setter would be enough for me to duplicate this functionality in my project.

If you're game, that's a simple patch and I can do it.

**Comment by photonstorm** [comment]
Yeah makes sense. Let me get the dev branch sorted out first before I merge this though. I'm thinking I may do a 2.4.8 release, as I'm worried if I merge this to 2.5.0 it'll be ages before it surfaces.

**Comment by photonstorm** [comment]
Ok all done and merged with the `dev` branch.
