### ISSUE TITLE
Issue with typescript definition changes

### ISSUE THREAD

**Issue by Dreaded-Gnu** [photonstorm/phaser#2445]
Hello,
within the typescript definition changes seems to be a small issue with version 2.4.7.

I use `tsd link` to get the typescript definitions for my grunt build process. At the file "phaser.comments.d.ts" within the previous version 2.4.6 there was "pixi.comments.d.ts" set as reference instead of "pixi.d.ts", as it is currently in 2.4.7.

When you try to link phaser via `tsd link` now, and use it for typescript compilation, you'll get a huge amount of duplicate errors. Changing the reference within "phaser.comments.d.ts" back to "pixi.comments.d.ts" solves these duplicate errors.

So either it can be changed back to "phaser.comments.d.ts" or the package.json needs to be changed, so that instead of "pixi.comments.d.ts" "pixi.d.ts" will be considered, when using `tsd link`.

When you tell me the correct way to do, I can create a pull request tomorrow.

**Comment by photonstorm** [comment]
Hmm this wasn't purposely changed our end. Change it to whatever makes most sense and submit a PR and I'll merge it (I suspect change it back to whatever it used to be). Try running `grunt tsdocs` as well just to see if that was the cause of it changing.

**Comment by Dreaded-Gnu** [comment]
Humm...
Checked out project, installed package dependencies, updated global installations and ran `grunt tsdocs`. It changed automatically `pixi.d.ts` to `pixi.comments.d.ts` at file `phaser.comments.d.ts`.

I'll need to take a look into github manual on how to do a pull request... :)

**Comment by Dreaded-Gnu** [comment]
Set this ticket to closed as of the pull request has been added.
