### ISSUE TITLE
Can't switch to 2.4.7 in examples

### ISSUE THREAD

**Issue by hlfcoding** [photonstorm/phaser#2447]
This issue is about:

* An error on the web site

To reproduce: go to http://phaser.io/examples/v2/camera/basic-follow, try to switch to version 2.4.7, this error gets thrown: `Uncaught ReferenceError: Phaser is not defined` (`VM712 embed.php?f=camera/basic+follow.js&v=2.4.7:33`).

Other versions work fine afaict.

**Comment by photonstorm** [comment]
Yes 2.4.7 Examples are not yet uploaded. Download the repo and use it locally if you need them before we get them on the site.

**Comment by photonstorm** [comment]
Both 2.4.7 and 2.4.8 are now available in the Examples.
