### ISSUE TITLE
NPM error in 2.4.7

### ISSUE THREAD

**Issue by mattcolman** [photonstorm/phaser#2448]
Hi, I'm getting an error when running `npm install phaser` -> `npm ERR! cb() never called!`
There is no error when I npm install phaser 2.4.6.

**Comment by Dreaded-Gnu** [comment]
Also struggled with this issue when trying to upgrade from 2.4.6 to 2.4.7. A node update to the latest version fixed this issue. There has been at least a security update to node LTS and stable:
https://nodejs.org/en/blog/vulnerability/npm-tokens-leak-march-2016/

**Comment by photonstorm** [comment]
Just to confirm @Dreaded-Gnu you fixed this by updating node locally, yes?

**Comment by Dreaded-Gnu** [comment]
I updated to latest stable version as of the installed stable was a bit outdated, and that fixed it.

**Comment by photonstorm** [comment]
Thanks for confirming. I'm closing this as it's obviously just a local out-dated version of node causing it.
