### ISSUE TITLE
addMoveCallback either passing incorrect parameter or documentation is misleading

### ISSUE THREAD

**Issue by dedoubleyou1** [photonstorm/phaser#2449]
This Issue is about
* A bug in the API
* An error in the documentation

`
    game.input.addMoveCallback(function(pointer, pointX, pointY, isDown) {
        console.log(isDown, pointer.isDown);
    }, this);
`

Documentation:
> The callback will be sent 4 parameters: The Pointer that moved, the x position of the pointer, the y position and the down state.

If I understand the documentation correctly the fourth parameter (the down state) should be the same as pointer.isDown. Instead it is true only on the first call after a given press. I'm guessing it's probably the documentation that is misleading in this case but not sure what the intended behavior was.

**Comment by photonstorm** [comment]
Yes I've had a look into this and the 4th parameter is actually "was this movement the result of a click event?", not "is the pointer down". I'll update the docs now.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
