### ISSUE TITLE
Frame doesn't change with tint on - in canvas mode only

### ISSUE THREAD

**Issue by spayton** [photonstorm/phaser#2453]
This Issue is about

* A bug in the API

When in canvas mode, with a sprites tint set to something other than 0xFFFFFF, if the frame is changed the sprite display doesn't update, it does remember the required fram but won't display it until the tint is removed by setting to 0xFFFFFF.

This is demonstrated in this Phaser sandbox example [here](http://phaser.io/sandbox/edit/gNjUZKQE).  Two game instances are created, the top one is with the default sandbox canvas mode of AUTO (should be labelled WEBGL unless your browser doesn't support it), the bottom one is fixed to CANVAS (will be labelled CANVAS).

The following keyboard keys are setup:
1 - change to frame 1
2 - change to frame 2
3 - change to frame 3
T - toggle tint

To show the problem, press T, then change the frames with 1,2,3.  You'll see that the top mummy changes frame when red, the bottom mummy doesn't.  Hit T again and you'll see the bottom mummy switch to it's correct frame.

I can see why this is happening, the requiresReTint flag appears to be getting cleared in the preUpdate before rendering (note that this doesn't happen if the frame is being changed by the animation manager).  I think there's a choice here on how to fix this, a quick fix to address this issue or a more thorough fix to also cache the tinted frame reference to be able to detect exactly when a tinted canvas needs regenerating.

**Comment by photonstorm** [comment]
A better question to me is why on earth is `preUpdate` clearing the flag, and not the tinting process itself. Will have a play with this and see what can be done, thanks for opening the issue.

**Comment by spayton** [comment]
Yup, that's a better question.  It's not clear looking at the commit history what area you were working in that might explain why this was added, so suspecting the fix wouldn't be as trivial as it seemed I left it.

The flag clearing was initialy added here on 8/5/2015: a1102d4d4d7b5d6ad268514625f86e11b6131e7c

And then beefed up a few days later with a texture check here: 4aa22e22a1e45a5f990b8b40fe1fe00a5b5b8950

**Comment by photonstorm** [comment]
Ok I can't see any reason at all why the tint process shouldn't be responsible for it, so I've made that change and your test case now works (as do the old examples), so I'm happy this is resolved.

Until the reason I added it in the first place comes back to bite my ass :)
