### ISSUE TITLE
version 2.4.7 have a bug in  method game.physics.arcade.overlap

### ISSUE THREAD

**Issue by LibiChai** [photonstorm/phaser#2454]
we code a game with the version 2.4.7 phaser method game.physics.arcade ,but when use overlap() and collide() , only when from top collide can callback,  
version 2.4.6 have not this problem.
please check this problem

**Comment by photonstorm** [comment]
https://github.com/photonstorm/phaser/commit/f494c867c798835f0819cc71077d1914bd3aed36
