### ISSUE TITLE
postUpdate is called twice per update

### ISSUE THREAD

**Issue by Yozer** [photonstorm/phaser#2455]
I have overridden postUpdate method on my class which is deriving from Phaser.Sprite:

```
Player.prototype.postUpdate = function () {
        _super.prototype.postUpdate.call(this);
       // some code
    };
```

I have noticed that my code is not working as it should. After some debugging I saw that my postUpdate is firing more than it should. My call stacks:

![2](https://cloud.githubusercontent.com/assets/9254709/14857513/d7500772-0c9c-11e6-8c14-aaf0a4c27254.PNG)
![3](https://cloud.githubusercontent.com/assets/9254709/14857514/d7513930-0c9c-11e6-8cea-784fa6c329de.PNG)

I don't think that it should work that way.

**Comment by photonstorm** [comment]
This is normal behaviour if the browser is running fast enough to be able to do more than one update per frame. You'll find the part that controls it in core/Game.js, in the update method (and updateLogic).

**Comment by Yozer** [comment]
I understand but check this example:
http://ideone.com/ryGF1D

You will see following output
![ss](https://cloud.githubusercontent.com/assets/9254709/14883394/3cdc2926-0d3e-11e6-8f34-181abd6034ae.PNG)

I think that postUpdate should be called once after every update. Not twice.

**Comment by photonstorm** [comment]
The problem somewhere in your code. Phaser will not 'natively' call `postUpdate` twice in a single update step. This is easily confirmed by adding a few simple logs to the Game and Core files (attached here if you want to put them into your own build). Then just create a Sprite and give it a name of 'debug' and it'll dump out its postUpdate for 60 frames and then call the debugger:

```

var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create });

function preload() {

    game.load.image('pic', 'assets/pics/dr_death-e605-endpart.png');

}

function create() {

    game._dd = 0;

    var sprite = game.add.sprite(0, 0, 'pic');

    sprite.name = 'debug';

}
```
[test.zip](https://github.com/photonstorm/phaser/files/240470/test.zip)
