### ISSUE TITLE
Input propagation.

### ISSUE THREAD

**Issue by namark** [photonstorm/phaser#2456]
I'm currently working on a quite ambitious game, that involves implementing lots of, let's say, non trivial GUI, so I ran across this "problem", that there is no way to propagate input events in Phaser, and I don't see any easy workarounds for that. The priority thing doesn't help, as far as I understand, cause I need several overlapping elements to respond to the same input event, not just one of them, that has the higher priority. So I was thinking, is it worth trying to implement something like multiple target objects for the Pointer class, or would it be easier to just make a custom build with PIXI's interaction manager resurrected?

**Comment by hilts-vaughan** [comment]
Sounds like you should use the DOM

**Comment by namark** [comment]
Noooo... not DOOOM... I much rather just do the hit tests manually :D
... And it seems that's what I'm actually going to do, for some custom objects, as a temporary solution, but it doesn't feel good at all.

**Comment by Dillybob92** [comment]
Have you looked at http://phaser.io/examples/v2/input/input-priority?

**Comment by namark** [comment]
Yep, I'm currently implementing a scrollable container with some clickable elements inside, and that doesn't really help :/

**Comment by Dillybob92** [comment]
You should try to post the code on the html 5 forums with a jsfiddle or something. We can try to help you there more maybe? Not sure

**Comment by namark** [comment]
Maybe, I'll do that when I'm completely stuck. Thanks.
But my question here actually was more general, anticipating some future complications, that might arise with various workarounds. I'll rephrase, just in case:
Does it make sense to add some logic for multiple target objects in Phaser.Pointer? Cause I'm looking at it, and really want to do that, but would like some green light and advice from someone who understands it better. 
Also is it possible to somehow enable PIXI's interaction manager in Phaser? Cause, even though more primitive, it also seems more capable to me... no offense :D ... just seems, alright?

**Comment by namark** [comment]
> Are you saying the input propagation is too laggy, not responsive enough?

Nooo... Maybe "propagate" is not the right word? As far as I understand the input does not propagate. A single object just receives it, and no one else in notified. Ideally there should be propagation through it to other object under it, and also propagation up the display object hierarchy, I think.

**Comment by photonstorm** [comment]
This is a very non-trivial feature request. The Pixi input manager isn't included in our build, and even if it was it wouldn't work anyway.

If you want to try implementing this for yourself then I would start in the Pointer class, in the `processInteractiveObjects` method. When it does the double-sweep you could add valid objects into a collective array, then at the end dispatch whatever events you want them to dispatch.

I'm closing this because it's not something I'll implement in Phaser, but feel free to reply if you want to ask questions about adding it to your own build.

**Comment by namark** [comment]
Yep, I wanted to implement this myself, so asking to make sure that I'm thinking in the right direction,
and I was actually looking exactly at the method you mentioned, so I'll try and see how it goes :)
Thanks.

**Comment by Dillybob92** [comment]
I am sorry @namark I believe you used the correct word. I just am getting confused and what exactly you are wanting to do that's all

**Comment by namark** [comment]
ummm... A question. Why does the Phaser.Group update its children in reverse order?
https://github.com/photonstorm/phaser/blob/master/src/core/Group.js#L1389
All the other display objects do otherwise. Makes renderOrderIds inconsistent.

**Comment by Nuuf** [comment]
https://pixijs.github.io/docs/core_display_Container.js.html#line110

PIXI's Container.addChild, adds new objects at the end of the list.

`this.addChildAt(child, this.children.length);`

**Comment by namark** [comment]
@Nuuf Ummm... Yes... That is certainly correct... But I can't see how is that relevant... ???

**Comment by Nuuf** [comment]
Nvm, I had a brain malfunction.

**Comment by namark** [comment]
sure, not a problem... I'll borrow that excuse though :D

**Comment by photonstorm** [comment]
Traditionally because it's extremely common for Group children to delete themselves during their `update` cycle, which screws with the Group array length if you're iterating through it at the time. However we moved to using a destroy phase a while back, which may mitigate this requirement. Will have a look into it.

**Comment by photonstorm** [comment]
Just had a further look at this - `preUpdate` is where the `renderOrderID` is set, and that loops through in bottom-to-top order in Stage, but Group was doing it in reverse (hence the order ID issue), so have swapped that around. `update` and `postUpdate` will loop in reverse though, for the reason stated above, but that won't impact the order IDs.

**Comment by namark** [comment]
Great. I did the same thing, so good to know there are not going to be any dire consequences.
