### ISSUE TITLE
Not recognizing Cocoon.io (compiled) developer app

### ISSUE THREAD

**Issue by tidelake** [photonstorm/phaser#2459]
This may be an issue. I'm getting `false` for all values on iPhone cocoon.io dev app, including Phaser.Device.iOS.  I think I understand that I need the `document.deviceready` event before Cocoon is available.  I've access the variables before, after getting this event.  Their documentation is shoddy, imho, but I don't believe I can use Canvas+ w/o loading the app after the deviceready event.  Though I did load using Webview+ and it shows the page background, so maybe it was using canvas+.  

Since I don't have access to any Cordova/Cocoon instances before the event fires, I'm using Phaser.Device.  I'm not sure if this is relevant to Phaser, but I'm quite puzzled why it won't even say I'm using iOS or iPhone.  I haven't checked all the options, maybe I'm missing something.  Thank you.

```
window.onload = function() {
  window.console.log("Phaser.Device.cordova     " + Phaser.Device.cordova);
  window.console.log("Phaser.Device.cocoonJS    " + Phaser.Device.cocoonJS);
  window.console.log("Phaser.Device.cocoonJSApp " + Phaser.Device.cocoonJSApp);
  window.console.log("Phaser.Device.iPhone      " + Phaser.Device.iPhone);
  window.console.log("Phaser.Device.desktop     " + Phaser.Device.desktop);
  window.console.log("typeof(Cordova)           " + typeof(Cordova));
  window.console.log("typeof(Cocoon)            " + typeof(Cocoon));

  // this crashes app in Canvas+
  if (!Phaser.Device.desktop) {
      document.addEventListener("deviceready", deviceReady, false);
      window.console.log('deviceready listening #' + load_order++);
  } else {
      deviceReady();
      window.console.log('deviceReady w/o listening #' + load_order++);
  }
}
```

**Comment by tidelake** [comment]
I am getting these properties to work on desktop inside the preload() and create() methods.

**Comment by photonstorm** [comment]
`Phaser.Device` is a singleton class, it needs instantiating before it, or any of its properties, can be used. None of those properties are set until the class has booted, which happens when Phaser.Game is instantiated, so I fully expect it to log `false` for everything in the code above.
