### ISSUE TITLE
angleToPointer exclusive to Arcade Physics

### ISSUE THREAD

**Issue by typedeph** [photonstorm/phaser#2461]
This function seems misplaced as it has nothing in it that should keep it from being used in any other physics engine that Phaser supports. Is there any particular reason for this?

**Comment by Dillybob92** [comment]
My hypothesis is when grabbing the angle, you're most likely already using physics. It's a helper method I believe and without a physics engine enabled I don't know if an angle is going to help much

**Comment by typedeph** [comment]
Just realized your edit. On the other hand, it seems it would be more appropriate to put it under another object (namespace?).

**Comment by ForgeableSum** [comment]
Yes, Phaser.Math.angleBetween or angleBetweenPoints can accomplish angleToPointer as well. I say rip it out of arcade physics and put it in Phaser.Math, with the rest of the angle between functions.

**Comment by photonstorm** [comment]
It's there for legacy reasons. It's also widely used, so will remain there for legacy reasons too. If I wasn't about to retire Phaser I'd probably deprecate it and move it, but it can live out its life with the rest of its similarly misplaced functions in there.
