### ISSUE TITLE
Camera following partially broken after 2.4.7

### ISSUE THREAD

**Issue by hlfcoding** [photonstorm/phaser#2462]
This issue is about a bug in the API.

In fixing #2106 with aee0212, I believe a regression was introduced that would break `Camera#follow` calls on game objects not in groups. Sample code can be found in the project and is clonable and runnable at hlfcoding/morning-stroll@c2143c2. I've applied a work-around [here](https://github.com/hlfcoding/morning-stroll/blob/c2143c2/src/state-play.coffee#L258), and the `follow` call is [here](https://github.com/hlfcoding/morning-stroll/blob/master/src/state-play.coffee#L308). My camera setup is the basic camera following setup from the [example](http://phaser.io/examples/v2/camera/basic-follow), which I believe would fail if it actually can load 2.4.7 instead of 2.4.6 (#2447).

In more detail: camera following doesn't happen beyond the initial follow, at least when `world` is the game world. So my sprite added using `game.add` always has the same seed position, but using that to calculate camera position doesn't make sense. Only the sprite's `position` changes. See screenshots.

2.4.7:

![image](https://cloud.githubusercontent.com/assets/100884/14844108/e34d345c-0c09-11e6-87ab-299c7348e87b.png)

2.4.6:

![image](https://cloud.githubusercontent.com/assets/100884/14844697/202149f0-0c0e-11e6-8371-101554ef6c55.png)

**Comment by photonstorm** [comment]
Sorry I don't have time to debug CoffeeScript. I need this boiled down to a simple runnable JS example really.

Also I'm curious, but it's impossible to have a Sprite in the World that isn't in a Group (as the World is in itself a Group), so how do you have your code structured that makes the Sprite not appear in a Group?

**Comment by hlfcoding** [comment]
Re. adding a sprite, there's no special code structure, I'm just using [`Game#add`](http://phaser.io/docs/2.4.7/Phaser.Game.html#add) [here](https://github.com/hlfcoding/morning-stroll/blob/c2143c2/src/player.coffee#L40), just like the [example](http://phaser.io/examples/v2/camera/basic-follow), which doesn't work for 2.4.7, but if it did I'm sure it'd fail in the same way. Sorry I don't have time to keep convincing you to fix this. There's always future bug reports from others. Thanks tho.

**Comment by photonstorm** [comment]
The example cited (basic-follow) works exactly as expected for me in 2.4.7 and 2.4.8-dev. The sprite remains in the middle, and the camera tracks it until it hits the world bounds.

So whatever local modifications you made to it specifically in your game is the cause of the issue, or alternatively you weren't expecting the example to do this? I'm not really sure which. Your screen grabs seem to indicate some kind of property error, but it doesn't happen in the example, so my request for a proper code example remains I'm afraid (unless anyone else reading this has the time to translate the CoffeeScript into normal code for me)
