### ISSUE TITLE
Headless mode not working 

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2464]
This Issue is about:

* A bug in the API

I suspect headless mode may not be working in the latest version of Phaser. Someone else on the forum was experiencing the same problem:
http://www.html5gamedevs.com/topic/21425-headless-mode-multiplayer-game/#comment-121863

What I see when I run headless mode appears to be the same thing I see in canvas mode:

`var game = new Phaser.Game('100','100',Phaser.HEADLESS,'game',null,true,false); `

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
