### ISSUE TITLE
Masking broken in Chrome v50

### ISSUE THREAD

**Issue by staff0rd** [photonstorm/phaser#2467]
This Issue is about
* A bug in the API/Chrome 64bit

Browse to http://phaser.io/examples/v2/sprites/mask and run your mouse over the black background.  In firefox/ie and Chrome 32bit, the expected masked circle appears at the mouse position and displays the sprite behind.

In Chrome 64bit however (tested 50.0.2661.94), at first no background is seen (game area remains black).  After switching in and out of the tab, or popping open developer tools, the round area that represents the mask starts to flicker/strobe in and out.  Clicking the game component then switches between this flickering effect, or just a black background with no mask visible.

I've tested this against masks in Phaser v2.4.6 and v2.4.4 and saw the same result.  Tests are against the WebGL renderer.

**Comment by staff0rd** [comment]
I've isolated this to one machine (Win10) and both Chrome 32bit and 64bit have the masking issue.

**Comment by staff0rd** [comment]
Downgrading to Chrome v49 (Discontinued) or updating to Chrome v51 (Beta) fixes the issue, so it's specific to the current stable Chrome v50.

However, I have both a desktop machine and a Surface Pro 3 running Windows 10 v1511 (10586.218), and the symptoms only occur on the desktop.

Will be interesting to see what happens once Crosswalk updates to Chromium 50.

**Comment by photonstorm** [comment]
I've tried this in Chrome 50 (stable channel release, 32-bit version) on Win10 and on Chrome 52 (Canary, dev channel, 64-bit) and it works fine with them both.

I'll try Chrome 50, 64-bit and see what happens there, and a few other PCs, but I'm not sure this is _just_ Chrome version related, but involves another factor as well (GPU perhaps)

**Comment by photonstorm** [comment]
Tried this on a really low-spec laptop, with terrible integrated GPU, and I can see the error in WebGL mode (Canvas is fine). This is 32-bit Chrome. So my money is on this being a Chrome + GPU specific error, rather than 32 or 64 bit (it's possible maybe the 64-bit version uses different GPU drivers, which is why it only happens that way around for you).

There's no errors, nothing in the stack, and WebGL inspector doesn't show me any errors either. Which is just great, as honestly I can't see any way to fix this now.

**Comment by enriko-riba** [comment]
yep a mix of GPU and browser related issue.
My home laptop displays the mask correctly on both integrated HD4600 and Nvidia 850 while my work laptop is having the issue in Chrome with a Radeon GPU (but not with same GPU in other browsers).

**Comment by staff0rd** [comment]
Possibly Radeon (+ Chrome v50) specific?  I only saw symptoms with Radeon 5800.

**Comment by photonstorm** [comment]
Good call. My integrated GPU is a Radeon. On my Nvidia it was fine.

Which sadly makes this even less fixable!

On Tuesday, 17 May 2016, Stafford Williams <notifications@github.com> wrote:

> Possibly Radeon (+ Chrome v50) specific? I only saw symptoms with Radeon
> 5800.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2467#issuecomment-219634464>
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by photonstorm** [comment]
Masks in WebGL use the stencil buffer, so this is definitely a WebGL  + GPU + Chrome specific bug, and as it's fixed in Chrome 51 I think it's best if we just close this off, rather than try to fight it, and leave it here so it's a search result for anyone else coming across it.
