### ISSUE TITLE
Arcade Physics bug - incorrect physics body position when using body.setSize and sprite anchor

### ISSUE THREAD

**Issue by SBCGames** [photonstorm/phaser#2470]
This Issue is about: 
* A bug in the API

 There is problem in arcade physics when setting body size and offset and using sprite anchors in the same time.

 In test case, there is one sprite with size 64x64. Its anchor is set to 0.5, 0.5, so it is centered at position. Body size is set to 32x32 and offsets are both set to 32. Expected result is placing body in right bottom corner with size of 1/4 of whole sprite (on right side on image below).
 Current result is on left side.

![arcade](https://cloud.githubusercontent.com/assets/8962889/15091905/0bc55caa-1459-11e6-9fc2-b7e3f04c4b41.png)

 Reason for this is that in physics/arcade/Body.js (https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/Body.js#L447) there are these two lines:
```javascript
        this.position.x = (this.sprite.world.x - (this.sprite.anchor.x * this.width)) + this.offset.x;
        this.position.y = (this.sprite.world.y - (this.sprite.anchor.y * this.height)) + this.offset.y;
```
 Its purpose is to find top left of sprite, so it should use this.sprite.width and this.sprite.height instead of this.width and this.height. Currently, it applies anchors on body size, not sprite size. If body size is different from sprite size, it may result in incorrect body position.

 So, purposed change is:
```javascript
        this.position.x = (this.sprite.world.x - (this.sprite.anchor.x * this.sprite.width)) + this.offset.x;
        this.position.y = (this.sprite.world.y - (this.sprite.anchor.y * this.sprite.height)) + this.offset.y;
```

 For completness, here is test code:
```typescript
            this.physics.startSystem(Phaser.Physics.ARCADE);

            let sprite = this.add.sprite(150, 150, "Sprites", "Block1M");

            this.physics.arcade.enableBody(sprite);

            sprite.anchor.set(0.5, 0.5);

            let body = <Phaser.Physics.Arcade.Body>sprite.body;
            body.setSize(32, 32, 32, 32);
```

**Comment by VitaZheltyakov** [comment]
It not bug. 
_setSize_ reassigns anchor and scale

**Comment by SBCGames** [comment]
@VitaZheltyakov problem is not with setSize method, but with preUpdate method - it mixes data from sprite and body to calculate top left position of body. It applies Sprite anchors on Body size and I am pretty sure it was not intended. Everything works as far as body size is the same as sprite size or anchor is 0,0 (default top left).
 See image on top of this issue (images are not fakes, but were taken from screen before and after change in code). If requested offset is 32x32 (and size 32x32), then expected result is on right (regardless of anchor!) ... and it also works well with zero anchor - result is offset 32x32 from top left of sprite regardless of anchor setting. But result, when changing anchor in the same time is shown on left - it has no meaningfull interpretation for 32x32 offset: body is 48x48 from top left of sprite, 16x16 from sprite position, ...

**Comment by photonstorm** [comment]
I agree, this is a bug.

Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by SBCGames** [comment]
Sorry for reopening. There is one more place where this bug occurs - I came across it a while ago.

In reset method of body (https://github.com/photonstorm/phaser/blob/dev/src/physics/arcade/Body.js#L716): 
```javascript
        this.position.x = (x - (this.sprite.anchor.x * this.width)) + this.offset.x;
        this.position.y = (y - (this.sprite.anchor.y * this.height)) + this.offset.y;
```

**Comment by photonstorm** [comment]
Done

**Comment by andiCR** [comment]
I am using an animation with an anchor set to (0.5, 1). The animation is based on an atlas and the frames change their width. The position of the body is moving when changing from frame to frame.

**Comment by photonstorm** [comment]
@andiCR this issue is closed, if you've a reproducible test case then it needs opening as a new issue, with that test code + assets included, or it will just remain a comment on a long thread that was long closed I'm afraid

**Comment by andiCR** [comment]
Thanks @photonstorm, I'll create a new issue with test code + asets
