### ISSUE TITLE
Pausing, resuming, losing and regaining focus when using HTML audio results in stopped audio and other audio from the audiosprite

### ISSUE THREAD

**Issue by rroylance** [photonstorm/phaser#2473]
This Issue is about A bug in the API.

Pausing audio when using HTML audio causes the audio to be stopped and not resumed, also losing focus (which pauses all audio) and regaining focus should play the audio but it doesn't. I also get other audio from the audiosprite being played after both scenarios in some cases.

You can see the the behavior in a provided example (http://phaser.io/examples/v2/audio/pause-and-resume) when running in IE 11, although the behavior is present when forcefully disabling WebAudio in other browsers as well;

- Pause and resume causes the audio to be restarted not resumed
- Click away from the window and back while the audio is playing and it never comes back

I know that HTML Audio supports this functionality as Howler.js doesn't suffer from these issues so I believe it to be an issue with how Phaser is handling HTML Audio.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by rroylance** [comment]
Thanks for the quick update; however it doesn't seem to be completely fixed yet, one step closer in that it actually resumes now. 

I'm noticing that when I lose focus the audio stops as it should, however the position of the audio when resuming seems tied to how long I leave the game unfocused. 

So for example with the background music that loops I get the following behavior;
1. Play music
2. Click out of window pausing the music
3.1. Quickly click back in the window and the music plays just about where it was left off
3.2. Wait to click back and the music will either resume later in the track or if I wait long enough for the music to end it will start at the beginning when I click back

Same for VO except it just wont come back if it gets to the end while unfocused.

It seems as though when the game is paused the audio is just muted and not paused ? Thinking this I tried calling game.sound.pauseAll() and game.sound.reusmeAll() in game.onPause and game.onResume respectively and I end up with more or less the same behavior I had in the initial issue.

So it seems there are more issues in the pause and resume logic for HTML Audio.

**Comment by photonstorm** [comment]
When `SoundManager.pauseAll` is called, Audio tags are literally stopped. They don't have their volume changed. When `resumeAll` is called, they are played again and their `currentTime` properties are set back to whatever they were when `pause` was triggered.

I just tried the Example you linked to originally again, forcing Audio tags, and left the browser paused for several minutes before returning to it, and it carried on exactly where it was.

So I'm going to need a working test case to debug this further.

**Comment by photonstorm** [comment]
Just to clarify - my test was to pause the audio in the example (by clicking the top region of the demo), which calls `music.pause()`, then making the browser lose focus for several minutes, then return to the example again and click the bottom half (calling `music.resume()`) and that carried on correctly.

If you leave audio playing and just click away from the browser, then yes it will mute the volume (unless `SoundManager.muteOnPause` is `false`), and the sound itself doesn't actually stop playing.

**Comment by rroylance** [comment]
OK. So the behavior I described after testing the update is intended as the audio isn't actually paused with the game (although the looped audio not continuing a loop still seems wrong to me); which is why in my game's case I used the onPause and onResume method to actually pause my audio when the game pauses (I do not have a pause button, only way to pause is to lose focus).

[CodePen Link to test case](http://codepen.io/rroylance/pen/BKejQW); When run in IE give it a few seconds to load and play the music then click out of the browser window and when you click back in the music is restarted, not resumed, as described in the original issue. I have not setup an audiosprite version as I imagine it is suffering from the same issue, once this is resolved if the audiosprite issue still exists I'll setup a test case for that as well.

**Comment by photonstorm** [comment]
Your CodePen example is using 2.4.7. This fix is applied to 2.4.8-dev only, which is what I would expect to see in the console had it been built against that version. When fixes are pushed to dev I don't then release a new build file (unless it's flagged as a Release Candidate), so you have to run 'grunt build' on the repo to build a phaser.js to test with. RC1 will be out later this week though (maybe even tomorrow) if you'd rather wait for that.

**Comment by rroylance** [comment]
Oh, whoops. My bad. I'll build and test it out.

**Comment by rroylance** [comment]
New test case [here](http://codepen.io/rroylance/pen/aNrLLZ?editors=0010).

**Comment by photonstorm** [comment]
Try the latest version.

There was definitely an issue with Audio tags set to loop, that were not ... well, looping. This now works as I'd expect in Chrome and IE, Audio and WebAudio.

AudioSprites pause and resume properly now as well based on your test case above. Although that may be related to the fix applied for the looping issue.
