### ISSUE TITLE
PIXI.defaultRenderer become invalid and cannot be updated after calling Phaser.Game.destroy

### ISSUE THREAD

**Issue by xtforgame** [photonstorm/phaser#2474]
This Issue is about PIXI.defaultRenderer

* A bug in the API

I have not took a look into source code, but according the built code, it seems that ```PIXI.defaultRenderer``` can be updated only once. After I called ```Phaser.Game.destroy``` and created a new one, the ```PIXI.defaultRenderer``` became invalid (for example, render.gl was set to null) but cannot be updated.

I have tried to add a line ```PIXI.defaultRenderer = null``` after calling ```Phaser.Game.destroy```, and everything works well.

Should this line be  added in the ```destroy``` method of ```Phaser.Game.Destroy```?

**Comment by photonstorm** [comment]
Maybe. What's the actual error it causes when you create a new game
instance?


On Wednesday, 11 May 2016, RickChen <notifications@github.com> wrote:

> This Issue is about PIXI.defaultRenderer
>
>    - A bug in the API
>
> I have not took a look into source code, but according the built code, it
> seems that PIXI.defaultRenderer can be updated only once. After I called
> Phaser.Game.destroy and created a new one, the PIXI.defaultRenderer
> became invalid (for example, render.gl was set to null) but cannot be
> updated.
>
> I have tried to add a line PIXI.defaultRenderer = null after calling
> Phaser.Game.destroy, and everything works well.
>
> Should this line be added in the destroy method of Phaser.Game.Destroy?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2474>
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by xtforgame** [comment]
It will cause a error while calling ```PIXI.RenderTexture```
at line ```this.baseTexture._dirty[gl.id] = false;```

this.renderer.gl here is null

**Comment by photonstorm** [comment]
I'm happy to null out the default in destroy, but a bigger question is why is RenderTexture being sent a null `renderer` value in the first place.

```
this.renderer = renderer || PIXI.defaultRenderer;
```

Because it surely shouldn't be.

**Comment by photonstorm** [comment]
Actually looking at the code there is no reason for `defaultRenderer` to exist at all, may as well remove it.

**Comment by xtforgame** [comment]
Oh, this.renderer is not null, ```this.renderer = renderer || PIXI.defaultRenderer;``` works well.
but this.renderer.gl was set to null, I also use the EZGUI, I'm not sure it is caused by EZGUI.

**Comment by xtforgame** [comment]
For more information, I use [this example](https://github.com/Ezelia/EZGUI/tree/master/examples/game) of EZGUI with some patch for EZGUI.

When EZGUI use its ```Compatibility.createRenderTexture``` function to load resources, it will call the PIXI.RenderTexture with an undefined renderer. In this case, ```PIXI.RenderTexture``` will choose ```PIXI.defaultRenderer```.

**Comment by photonstorm** [comment]
Hmmm, it really shouldn't do that. Guess I'll keep `defaultRenderer` around then. Anyway this is now fixed in dev, thanks for reporting it!
