### ISSUE TITLE
Typescript definition files has incorrect function signature

### ISSUE THREAD

**Issue by galen-manuel** [photonstorm/phaser#2475]
This Issue is about

* An error in the TypeScript defs

Line 8847 in the comments file and line 1638 in the defs file for Group.callAllExists has an incorrect function signature causing a compile error and breaking intellisense when using Typescript.

The callback parameter is of type `Function` when it should be of type `string`.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
