### ISSUE TITLE
Collision issue with Arcade and Google Chrome?

### ISSUE THREAD

**Issue by lessmilk** [photonstorm/phaser#2477]
I built a tiny platformer with Phaser 2.4.7 and Arcade Physics. If you jump against a wall while pressing an arrow key, you will get stuck in the walls instead of falling. You can [play the game here](http://www.lessmilk.com/content/tmp/).

I have this issue only on Google Chrome (Mac). On Safari and Firefox it works fine.

Here's how the level is created:

```
var level = [
    "x                    x",
    "x                    x",
    "x                    x",
    "x                    x",
    "xxxxxxxxxxxxxxxxxxxxxx",
];

this.walls = game.add.group();
this.walls.enableBody = true; 

for (var i = 0; i < level.length; i++) {
	for (var j = 0; j < level[i].length; j++) {
		if (level[i][j] == 'x') {
			var wall = game.add.sprite(70+20*j, 50+20*i, 'wall');
			this.walls.add(wall);
			wall.body.immovable = true;
		}
	}
}
```

**Comment by halilcakarr** [comment]
There is a problem with the left wall.
go touch on the left wall and try to jump you will see that

**Comment by Dillybob92** [comment]
@halilcakarr There is though. When you hold down left and up next to a wall the character gets stuck.

**Comment by photonstorm** [comment]
Using one large sprite, instead of multiple tiles, is exactly how it should be fixed. Or convert it to a Tilemap, and then it'll create one large edge for the side of the wall.

I suspect it only happens in Chrome because it's polling at a different rate to FF, and causing more updates, so it's finding the edges more precisely.

**Comment by photonstorm** [comment]
Going to close this one off, it's just a limitation of Arcade Physics, and there's no easy fix for it.
