### ISSUE TITLE
Get next alive unit in group

### ISSUE THREAD

**Issue by SVasilev** [photonstorm/phaser#2479]
This Issue is about
* A feature suggestion

Hello,
I am making a game which has batlles just like Final Fantasy.
Picture: 
![image](https://cloud.githubusercontent.com/assets/3826465/15305706/6da92d5e-1bcd-11e6-9251-f209c380e3ec.png)
As you can see, the second character is on turn. After his turn is done I should move to the next alive character, which is character four, because the third character is not alive. So I am using a group to handle this units set. I cant just use the next() function so I have implemented a Phaser.Group.getNextAlive (and Phaser.Group.getPreviousAlive). Do you see point in adding such functionallity to the Phaser.Group class? If you like the idea, I can make a pull request.
Best regards,
Stefan

**Comment by photonstorm** [comment]
Thanks for the suggestion. I can see why this would be useful, but it's quite easy to achieve already using `Group.iterate`, so I think honestly if someone needs it I'll just let them add it (like you've done) for now. This is definitely something good to add to the Lazer wish list though, so I'll do so.

**Comment by SVasilev** [comment]
Hello,
Thanks for the response. I looked the wish list and did not see this. Maybe you forgot it or did not update it yey :) . Nevermind, I want to ask how will the features from the wishlist be implemented. Will they be assigned to exact people or everyone from the community (like me) can take a feature and make a pull request.
Another thing I think might be usefull. As you said getNextAlive can be achieved by using Group.iterate. But what about getPreviousAlive. In this way of thinking maybe there should be a way to iterate a group backwards. Do you see a point in this?
Best regards,
Stefan
