### ISSUE TITLE
Error destroying a game shortly after its creation

### ISSUE THREAD

**Issue by ferrao** [photonstorm/phaser#2480]
I am trying to fire a callback when my Phaser.Game has been fully loaded. I am doing it from inside the create method of my main game state. 

If i call game.destroy() immediately after such callback, i get:

`TypeError: Cannot read property 'preUpdate' of null`

A simple delay of a few ms in destroying will make this go away.
Is there a proper/better way to fire callback when game is ready and can be safely destroyed?

**Comment by Dillybob92** [comment]
Try `kill()` instead

**Comment by hilts-vaughan** [comment]
If you're using lodash or underscore, a `_.defer` will probably due to the trick. It probably needs to do a full cycle.

**Comment by ferrao** [comment]
Just to confirm that a `_.defer` or a `setTimeout(destroy, 0)` does the trick.

**Comment by photonstorm** [comment]
It needs to render once before you can destroy it. So you can either use a timeout, or you could probably just do it in the `State.render` function instead, because that is called as the very last thing in the game cycle (well, `plugins.postRender` is the truly last thing, but is empty by default)
