### ISSUE TITLE
Arcade Physics Overlap Issue

### ISSUE THREAD

**Issue by DuncanPriebe** [photonstorm/phaser#2481]
Hey, everyone!

I'm working on a 2D scrolling shooter, and I just spend a number of hours troubleshooting an issue with Phaser's Arcade physics overlap. I'm not 100% sure that the error is in Phaser, but I do know that downloading a new version of Phaser caused my code to break.

Okay, so I have a bunch of collision detectors like this one:
`GameSystem.game.physics.arcade.overlap(obstacles, player, playerObstacleCollisionHandler, null, this);`

The playerObstacleCollisionHandler function will deal damage to the both player and the obstacle, but I found that it was only firing for a fraction of a second during the collision, then stopping.

A link to a version of my game that's having the issue can be found [here](http://duncanpriebe.com/pages/zyrian/).

To see the problem in action, do the following:
1. Use the arrow keys on the keyboard to select NEW GAME;
2. Press ENTER;
3. Select MISSIONS;
4. Select Foolishness;
5. Wait for Obstacles to spawn;
6. Crash into them and/or shoot them.

(FYI: The tan bar is ship health, the blue bar is shield health.)

After a bunch of testing, here's what was able to confirm:
- The overlap was being checked every update;
- The collision function would fire a few times after initial contact, then stop;
- Projectiles fired while the player is on top of an entity will cause the projectiles not to collide with the entity;
- Checking for overlap without physics (as seen [here](http://phaser.io/examples/v2/sprites/overlap-without-physics)) worked properly;
- The issue occurred in both Chrome FireFox;
- **Reverting to an older version of Phaser (2.4.0 from 2.4.7) fixed the problem (without changing anything else);**
- **Reverting all of my files to an older version fixed the problem (without changing Phaser).**

I actually just figured the last point out while I was writing this, and I considered deleting the post. I apologize if this is actually an issue with my code and I've wasted your time, but it might be something worth investigating.

Thank you for your time, and thanks for making Phaser!

**Comment by photonstorm** [comment]
Have you tried against 2.4.8-dev? Because I think you'll find it will fix it. There was a bug in `overlap` in 2.4.7 but that has been fixed, and is part of 2.4.8. I'm releasing RC1 today, so if you get that file and test against it later, I think you'll find it's ok again. Please re-open / re-comment on this issue if that isn't the case, and if you're able to boil it down to a smaller test case, thank you.
