### ISSUE TITLE
Button.onInputOver and onInputOut events do not seem to be triggering anymore in 2.4.8.

### ISSUE THREAD

**Issue by pengchuan** [photonstorm/phaser#2486]
As described, the Phaser.Button's onInputOver and onInputOut events used to trigger pre 2.4.8. But doesn't seem to anymore. Am I missing something?

Thanks

**Comment by kevinleedrum** [comment]
Phaser._Sprite_'s onInputOver and onInputOut events also aren't triggering for me after after upgrading to 2.4.8.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
