### ISSUE TITLE
Group.js removeAll(true)

### ISSUE THREAD

**Issue by stoneman1** [photonstorm/phaser#2487]
This Issue is about 

* A bug in the API (maybe?) or then feature request

In the group.js removeAll there is a param to invoke destroy on each children. However the recent changes in api to the objects destroy has a possibility to destroy the base texture. In case you use removeAll(true) it does not destroy the base texture and I think it should or it should be an option somewhere. Perhaps an option would be a better idea.

```
Phaser.Group.prototype.removeAll = function (destroy, silent) {

    if (destroy === undefined) { destroy = false; }
    if (silent === undefined) { silent = false; }

    if (this.children.length === 0)
    {
        return;
    }

    do
    {
        if (!silent && this.children[0].events)
        {
            this.children[0].events.onRemovedFromGroup$dispatch(this.children[0], this);
        }

        var removed = this.removeChild(this.children[0]);

        this.removeFromHash(removed);

        if (destroy && removed)
        {
        //here we could do true,true?  destroy: function (destroyChildren, destroyTexture) {
            removed.destroy(true);
        }
    }
    while (this.children.length > 0);

    this.hash = [];

    this.cursor = null;

};
```

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have added this feature, and it has been pushed to the `dev` branch.
