### ISSUE TITLE
Arcade physics body and scale.x

### ISSUE THREAD

**Issue by icameron** [photonstorm/phaser#2488]
This Issue is about

* A bug in the API

arcade physics .body.setSize not playing well with sprite.scale.x (maybe sprite.scale.y as well havent tested) tested using http://phaser.io/examples/v2/arcade-physics/offset-bounding-box

line 21 + sprite1.scale.x=-1; sprite1.anchor.x=0.5;

line 30 * sprite1.body.setSize(100, 50, 0, 25);

2.4.7 shows sprite flip and bounding box in the correct place based off the anchor
2.4.8 has the bounding box on the edge of the sprite

Note: i tried the 2.4.8 dev with the same result

**Comment by Nuuf** [comment]
I have the same issue.

with anchor 0.5

negative scale x: flips the body to the right side of the sprite
negative scale y: flips the body under the sprite

with anchor 0.0

body remains while sprite is flipped.

**Comment by SBCGames** [comment]
Read this forum post: http://www.html5gamedevs.com/topic/22695-247-248-body-anchoring-any-migration-tips/ - there you will find evolution of body position calculation, current problems and possible solution.

**Comment by icameron** [comment]
looks like the suggested fix is  
this.position.x = (this.sprite.world.x - (this.sprite.anchor.x * this.sprite.width)) + this.sprite.scale.x * this.offset.x;
        this.position.x -= this.sprite.scale.x < 0 ? this.width : 0;
        this.position.y = (this.sprite.world.y - (this.sprite.anchor.y * this.sprite.height)) + this.sprite.scale.y * this.offset.y;
        this.position.y -= this.sprite.scale.y < 0 ? this.height : 0;****

**Comment by VitaZheltyakov** [comment]
I have this problem. Body Scale is less than 1.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
