### ISSUE TITLE
Phaser 2.4.8: problem with physics

### ISSUE THREAD

**Issue by EvolViper** [photonstorm/phaser#2490]
Hello. I've got a problem with my game after updating to Phaser 2.4.8. Player falls through platforms and stucks in air. Here you can see it on the video: https://youtu.be/V4Z8LIkw-g4
I use Arcade physics. Phaser 2.4.7 works fine.

**Comment by SBCGames** [comment]
There is change in Arcade Physics in 2.4.8. Check visual debug for bodies if it is correctly positioned and also read this forum post if you find information on your issue: http://www.html5gamedevs.com/topic/22695-247-248-body-anchoring-any-migration-tips/

**Comment by EvolViper** [comment]
It seems that problem is related to body positioning after flipping sprite with scale.x *= -1. Is it a bug or sprite.scale is supposed to work this way now?

![6](https://cloud.githubusercontent.com/assets/17985873/15452885/c8732874-2006-11e6-9c96-0d2ebfd80983.JPG)

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
