### ISSUE TITLE
BitmapText align "center" does not align properly

### ISSUE THREAD

**Issue by crippledcactus** [photonstorm/phaser#2496]
I am experiencing an odd problem aligning the text of a BitmapText to the center. I am able to successfully wrap the text by using the "maxWidth" property, but the alignment of the text is uneven / jagged (see attached screenshot). It doesn't align to the center, some words are more to the left, and some are more to the right.

This is the code I'm using (typescript):
`let hintText:Phaser.BitmapText = this.game.make.bitmapText(0, 100, "MSR", "", 25, "center");`
`hintText.maxWidth = 310;`
`this.add(hintText);`
`hintText.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut mattis velit. Cras placerat fermentum dictum. Donec at semper enim. Donec euismod pulvinar volutpat."`

![ss](https://cloud.githubusercontent.com/assets/19533413/15473219/968b9112-2131-11e6-9f61-99859ed94da5.png)

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
