### ISSUE TITLE
Video - iOS - Safari -  detecting when user hits done on video player

### ISSUE THREAD

**Issue by kelu-smiley** [photonstorm/phaser#2498]
When playing a video on mobile device, I needed to detect when the 'done' button was hit on iphone video player for an intro video, which would trigger the main menu to come up.

There is no done button handler, but was able to use the 'webkitendfullscreen' event as follows :

introVideo.video.addEventListener('webkitendfullscreen', function () { videoDoneHandler() }, true);

adding as issue with workaround per Rich on slack.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
