### ISSUE TITLE
Sound effect loop refreshes too early

### ISSUE THREAD

**Issue by MaxMcCool** [photonstorm/phaser#2500]
I'm new to Phaser, and was wondering if anyone could answer my question about an issue I'm having. I have set a sound effect to play for a keyDown event, but the full audio file doesn't play until the key is released. I have loop set to true, and forceRestart set to false. If this is any help, it's an .ogg file and I'm using chrome to run it. Here is a sample of my code:

function playerWalk()
	{
		this.leafWalk.play();
	}

update: function()
{   
if (aKey.isDown)
    {
		sprite.body.moveLeft(150);
		play: playerWalk(game, 'leafWalk', .25, true, false);
		facing = "left";
		playerRun();
    }
}

Any insight would be greatly appreciated. Many thanks.

**Comment by rroylance** [comment]
The provided code doesn't make any sense and is not valid javascript... however what you can do for that control style is something along the lines of;

```
var walkLeft = game.input.keyboard.addKey(Phaser.Keyboard.A);
walkLeft.onDown.add(function () {
    this.walkLoop.play();
    this.isMovingLeft = true;
}, this);
walkLeft.onUp.add(function () {
    this.walkLoop.stop();
    this.isMovingLeft = false;
}, this);
```

and do similar for each of the other directions, and then in your update check the flags isMovingLeft, isMovingRight, etc and do your movement logic.

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

If it's easier you can use the [Phaser Sandbox](http://phaser.io/sandbox/) to create a code sample (as this is now running the latest build of Phaser). Enter your code, click the 'save icon' in any of the editor tabs, and paste the URL here.

**Comment by MaxMcCool** [comment]
I figured it out. Thanks.


________________________________
