### ISSUE TITLE
Phaser 2.4.8 does not register onInputOver or onInputOut correctly

### ISSUE THREAD

**Issue by tuxagon** [photonstorm/phaser#2501]
This Issue is about

* A bug in the API

Using the code found [here](https://github.com/codemwnci/PhaserJS-Pairs), you can easily see that changing the phaser version to 2.4.8 (using [this](http://cdn.jsdelivr.net/phaser/2.4.7/phaser.min.js)) causes the `onInputOver` and `onInputOut` events to not be triggered as expected. Instead of `onInputOver`, it registers what seems to be a click event. Hovering over the cards should render a change in opacity. This was attempted in both Microsoft Edge and Google Chrome.

**Comment by photonstorm** [comment]
Yes, this has been fixed in the dev branch already, and will be part of the 2.4.9 release which will hit RC1 later this week.
