### ISSUE TITLE
GenerateTexture return type fix from the past couple of commits, cause problems for Typescript Definition files.

### ISSUE THREAD

**Issue by Astridax** [photonstorm/phaser#2502]
I wrote about this issue in a comment on this file, so to keep it brief, the fact that both PIXI.Graphics.prototype.generateTexture and PIXI.DisplayObject.prototype.generateTexture have different argument types and or return types causes problems for Typescript definitions.

You can overload on arguments or return type, but not both as far as I'm aware.

Please see my original comment:
https://github.com/photonstorm/phaser/commit/e6b9ca4e22285500862e7c7a8a72d76c74d4d703

and these:
https://visualstudiomagazine.com/articles/2015/11/01/overloading-typescript-functions.aspx
http://stackoverflow.com/questions/25022331/overloads-cannot-differ-only-by-return-type

**Comment by photonstorm** [comment]
We've reverted to it returning `RenderTexture`. It's incorrect, but it stops the compilation error.
