### ISSUE TITLE
v 2.4.8 - onInputOver never fires

### ISSUE THREAD

**Issue by nickryall** [photonstorm/phaser#2503]
This issue can be reproduced by switching between 2.7 /  2.8 on the demo here:

http://phaser.io/examples/v2/buttons/action-on-click#gv

I tracked the issue down to this commit:

https://github.com/photonstorm/phaser/commit/9649f714bb6837b13b98590449e041c2785f5937

The `checkPointerOver` method is returning early if  `!pointer.isDown` .

Removing this check from line 726 of InputHandler.js fixes the issue. 

I didn't create a PR for this as I'm not sure if `!pointer.isDown` should be replaced with a different check and I couldn't see a  `pointer.isOver` property set anywhere.

**Comment by photonstorm** [comment]
Thanks for opening the issue and spending time on research, but this is already fixed in the dev branch!

**Comment by nickryall** [comment]
Oh man... Ha ha
