### ISSUE TITLE
Button onInputOver not working in v.2.4.8

### ISSUE THREAD

**Issue by riaan** [photonstorm/phaser#2507]
When hovering a button/sprite/image on a desktop browser the inputOver doesn't trigger. When clicking inside the canvas and hovering the button it does trigger the 'Over' button event.

Tested in Firefox, Chrome and Safari on iMac 5K / OS X
Demo: http://phaser.io/examples/v2/buttons/action-on-click

The hover effect works fine when selecting v2.4.7

**Comment by photonstorm** [comment]
Thanks for reporting this, but it's already fixed in the dev branch.
