### ISSUE TITLE
"InvalidStateError" When playing an audio with markers on Safari

### ISSUE THREAD

**Issue by mari8i** [photonstorm/phaser#2508]
This issue is about a bug I discovered today, that only shows on Safari (tested on safari 9.1.1, could not reproduce on chrome and Firefox, both on Linux and OS X El Captain, NOT tested with IE or Edge)

Using the latest Phaser release (2.4.8) with Pixi.js 2.2.9, but could also reproduce using Phaser 2.4.6.

I have the following:

```
preload: {
            this.load.audio('audio', ['audio.ogg','audio.m4a', 'audio.mp3'], true);
}
create: {
            var audio = this.add.audio('audio');
            audio.allowMultiple = true;
            audio.addMarker(0, 0.62, 0.62);
            audio.addMarker(1, 0, 0.61);
            audio.addMarker(2, 2.05, 0.82);
            audio.addMarker(3, 2.06, 0.8);
            audio.addMarker(4,  4.11, 1.22);
            audio.addMarker(5, 2.89, 1.2);
            audio.addMarker(6, 5.4, 1.3);
            audio.addMarker(7, 6.7);
            audio.play(7);
}
```

Running this code crashes when executing audio.play(7) with the following error:
`"InvalidStateError: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable." phaser.js 74271`

The nice thing is that I also found a solution:
By specifying the length (any length..) of the last audio segment (the one with key 7), the bug does not show.

Working code:

```
preload: {
            this.load.audio('audio', ['audio.ogg','audio.m4a', 'audio.mp4'], true);
}
create: {
            var audio = this.add.audio('audio');
            audio.allowMultiple = true;
            audio.addMarker(0, 0.62, 0.62);
            audio.addMarker(1, 0, 0.61);
            audio.addMarker(2, 2.05, 0.82);
            audio.addMarker(3, 2.06, 0.8);
            audio.addMarker(4,  4.11, 1.22);
            audio.addMarker(5, 2.89, 1.2);
            audio.addMarker(6, 5.4, 1.3);
            audio.addMarker(7, 6.7, 100);
            audio.play(7);
}
```

Hope this helps somebody, I struggled with this bug for a whole day.

Bye and thanks for creating Phaser :-)

**Comment by photonstorm** [comment]
Thanks for posting this! The duration argument _isn't_ optional, so should never have been left out. Even so, that's such a weird error message that I've added in an extra guard to protect against it.
