### ISSUE TITLE
pixi definition file errors

### ISSUE THREAD

**Issue by TheFirstLairron** [photonstorm/phaser#2513]
This Issue is about

* An error in the TypeScript defs

I'm using phaser with typescript in visual studio 2015 and this is the error i am getting(just copied down from master):

_Error TS2415	Class 'Graphics' incorrectly extends base class 'DisplayObjectContainer'.
  Types of property 'generateTexture' are incompatible.
    Type '(resolution?: number, scaleMode?: number) => Texture' is not assignable to type '(resolution?: number, scaleMode?: number, renderer?: PixiRenderer) => RenderTexture'.
      Type 'Texture' is not assignable to type 'RenderTexture'.
        Property 'renderer' is missing in type 'Texture'._

Is there any fix for this? Also, if you need more info, just let me know.

**Comment by clark-stevenson** [comment]
See #2492

**Comment by TheFirstLairron** [comment]
Thank you very much clark

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by DenisVuyka** [comment]
I'm using version 2.4.8 and getting the following error:

```
node_modules/phaser/typescript/pixi.d.ts(605,18): error TS2415: Class 'Graphics' incorrectly extends base class 'DisplayObjectContainer'.
  Types of property 'generateTexture' are incompatible.
    Type '(resolution?: number, scaleMode?: number) => Texture' is not assignable to type '(resolution?: number, scaleMode?: number, renderer?: PixiRenderer) => RenderTexture'.
      Type 'Texture' is not assignable to type 'RenderTexture'.
        Property 'renderer' is missing in type 'Texture'.
```

**Comment by photonstorm** [comment]
@DenisVuyka  This is fixed in both the dev branch and the current stable release.
