### ISSUE TITLE
Chaining Animation doesn't trigger killOnComplete

### ISSUE THREAD

**Issue by Dillybob92** [photonstorm/phaser#2515]
Not sure if this intended, but just noticed this when doing some chaining :)

for example:
```
				var tempbolt = game.add.sprite(0, 0, 'lightningbolt');
				    tempbolt.animations.add('walk');
				     tempbolt.play('walk', 30, false, true)
```

The [`killOnComplete`](http://phaser.io/docs/2.4.6/Phaser.AnimationManager.html#play) parameter triggers perfectly

But, if you do this:
```
				var tempbolt = game.add.sprite(0, 0, 'lightningbolt');
				    tempbolt.animations.add('walk').play('walk', 30, false, true)
```

Animation works fine and does stop, but the `killOnComplete` doesn't get called. Not sure if this is a bug, or if it's intended to keep us away from chaining (if it's bad practice). I love to chain whenever I can because my codebase is so big, but I can understand if it's intended. Thought i'd report anyways

Thx

**Comment by photonstorm** [comment]
It's because the method signatures are different. In the first example you're calling `AnimationManager.play`, so the arguments are correct. In the second one you're calling `Animation.play` which has a different signature. The following should work fine:

```
var tempbolt = game.add.sprite(0, 0, 'lightningbolt');
tempbolt.animations.add('walk').play(30, false, true)
```

**Comment by Dillybob92** [comment]
I see, thanks Rich.
