### ISSUE TITLE
hand cursor only appears when mouse is down, even when useHandCursor is set to true

### ISSUE THREAD

**Issue by crippledcactus** [photonstorm/phaser#2516]
I've updated to version 2.4.8 and am experiencing an issue with the hand cursor not appearing as it should. It only appears when the mouse is down but returns back to a normal pointer when the mouse is up. I'm using the same code I was in 2.4.7:
`let testSprite:Phaser.Sprite = this.game.add.sprite(0, 0, "ss_1", "button_bg");
        testSprite.inputEnabled = true;
        testSprite.input.useHandCursor = true;`

**Comment by photonstorm** [comment]
Thanks for submitting this issue. This has been fixed already. You can find the fix in the `dev` branch if you want to test it prior to 2.4.9 release.
