### ISSUE TITLE
getOverlapX and getOverlapY / typescript VS 

### ISSUE THREAD

**Issue by obamor** [photonstorm/phaser#2517]
Hallo, 
in my Project, Intellisense don´t find the following methodes:
VS 2015 Enterprise (up-to-date) Phaser: 2.4.8

```
- getOverlapX(body1, body2, overlapOnly) → {float}
- getOverlapY(body1, body2, overlapOnly) → {float}
```

i need them to check if my car is on the parking place.

maybe i use it false? that should be the correct syntax? (both are bodies)
`this.game.physics.arcade.getOverlapX(this.carPlayer, this.sprite1);`
The part with `getOverlapX()` Visual Studio underline red. With this Codeline that don´t compile.

Sorry for the bad english

Best regards
obamor

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by obamor** [comment]
Thanks guys :+1: :
