### ISSUE TITLE
Error on Game.destroy()

### ISSUE THREAD

**Issue by flogvit** [photonstorm/phaser#2521]
I'm using Phaser 2.4.8.

When doing Game.destroy(), i get the message

TypeError: Cannot read property 'update' of null
    at Phaser.Game.update (phaser.js:34615)
    at Phaser.RequestAnimationFrame.updateRAF (phaser.js:58581)

Which points to

```javascript
update: function (time) {

      this.time.update(time);
// ..
}
```

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

If it's easier you can use the [Phaser Sandbox](http://phaser.io/sandbox/) to create a code sample (as this is now running the latest build of Phaser). Enter your code, click the 'save icon' in any of the editor tabs, and paste the URL here.

**Comment by flogvit** [comment]
Well, I run it inside Angular 2, which would be hard to provide. But here is a skeleton for a component which get the error. I have all the phaser files in the ../phaser/ directory.

```typescript
/// <reference path="../phaser/phaser.d.ts" />
/// <reference path="../phaser/pixi.d.ts" />

import { Component, OnInit, OnDestroy } from '@angular/core';
import '../phaser/phaser';

@Component({
  moduleId: module.id,
  selector: 'phaser',
  templateUrl: 'phaser.component.html',
  styleUrls: ['phaser.component.css'],
})
export class PhaserComponent implements OnInit, OnDestroy {
  game: Phaser.Game;

  constructor() {}
  create() {}
  preload() {}
  update() {}

  ngOnInit() {
    this.game = new Phaser.Game(800, 600, Phaser.AUTO, 'content', { preload: this.preload, create: this.create, update: this.update });
  }

  ngOnDestroy() {
      // This fails
      this.game.destroy();
  }

}
```

**Comment by flogvit** [comment]
It seems the code in the Phaser.RequestAnimationFrame.stop()

```javascript
  window.cancelAnimationFrame(this._timeOutID);
```

do it asynchrony. I fixed it temporary with:

```javascript
   updateRAF: function (rafTime) {

      if (!this.isRunning) return;  // Added this to avoid update on empty time property

      // floor the rafTime to make it equivalent to the Date.now() provided by updateSetTimeout (just below)
      this.game.update(Math.floor(rafTime));

      this._timeOutID = window.requestAnimationFrame(this._onLoop);

    }
```

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
