### ISSUE TITLE
[2.4.8] Pointer "over" check in InputHandler not working correctly anymore

### ISSUE THREAD

**Issue by Garbanas** [photonstorm/phaser#2523]
This is a bug due to a copy&paste error from `InputHandler.checkPointerDown()`.

The "over" check (`InputHandler.checkPointerOver()`, line ~724) also checks for `!pointer.isDown` which is wrong for an "over" check.

This results in the hand cursor not showing and the "`isOver`" boolean in the Phaser.Button callback being "false" when it should be "true".

**Comment by photonstorm** [comment]
Thanks for spending time opening this issue, but it has already been fixed in the `dev` branch.
