### ISSUE TITLE
getJSON(true, 'key') adds a bunch of extra properties to the cloned object

### ISSUE THREAD

**Issue by drhayes** [photonstorm/phaser#2524]
This Issue is about (delete as applicable)

* A bug in the API

From: http://www.html5gamedevs.com/topic/22910-getjson-clone/

Here's the recreation (thanks to super_frog for that): https://jsfiddle.net/1ypcnre5/

Expected: Call `Phaser.Cache.getJSON(true, 'key')` with my JSON and get a clone of my object back with no extra properties.

Actual: Call `Phaser.Cache.getJSON(true, 'key')` with my JSON and get an extension of Phaser.Util back.

The Phaser.Utils.extend call in Phaser.Cache.getJSON is making it extend Phaser.Utils in the process... I think. The methods that are added are all Phaser.Util methods, at least.

**Comment by photonstorm** [comment]
Nice one. Merging.
