### ISSUE TITLE
fixedToCamera Text

### ISSUE THREAD

**Issue by Upperfoot** [photonstorm/phaser#2527]
This Issue is about (delete as applicable)

* A bug in the API

It looks like https://github.com/photonstorm/phaser/commit/68c29470cf07591222d2267006c16158d480728f seems to have affected the way text that is fixedToCamera is positioned when the camera moves.

Here is an example.

http://imgur.com/Z2krRHS

Here is the code I'm using to add the text.
    
    var help = game.add.text(10, 10, 'Arrows to move, click and drag to cast a ray', { font: '16px Arial', fill: '#ffffff' });
    help.fixedToCamera = true;

And the camera is set to follow my sprite that is tweening using the following.

    game.camera.follow(sprite, Phaser.Camera.FOLLOW_LOCKON);

Seems that this https://github.com/photonstorm/phaser/blob/dev/src/core/Stage.js#L176-L193 is causing.

Swapping the position of https://github.com/photonstorm/phaser/blob/dev/src/core/Stage.js#L181-L184 with https://github.com/photonstorm/phaser/blob/dev/src/core/Stage.js#L186 fixes the issue in regards to the text, but swaps the issue from it being on the text to the sprite.

**Comment by photonstorm** [comment]
Yes, I'm not going to swap the order around though as it just breaks in a different (more obvious!) way.

I think what is needed is a new approach entirely to anything that uses the camera for positioning. Will have a think about how best to do this. But right now I'm thinking that any object with 'fixedToCamera' on it does some kind of preRender position update.

**Comment by photonstorm** [comment]
Closing this as all the examples now work as expected in RC4 and above.
