### ISSUE TITLE
Looping audio not able to stop after 2nd loop

### ISSUE THREAD

**Issue by TheJasonReynolds** [photonstorm/phaser#2528]
This Issue is about
* A bug in the API

Looping sounds do not always stop with sndInstance.stop() after looping. This problem isn't present in 2.4.7. It appears a line was added in Phaser.Sound:
//  Gets reset by the play function
this.isPlaying = false;

I'm not 100% (sorry I can't post my project) but it seems either after the 2nd loop (but only when multiple looping sound) this.isPlaying is not being set back to true. This makes the check in stop() for isPlaying just bail.

**Comment by lewispollard** [comment]
I have the same issue in 2.4.8, but seems to only happen on mobile for me?

**Comment by TheJasonReynolds** [comment]
I saw it on all browsers, but there's a fix in the dev branch now -- and has solved the issue for me completely. If you're not seeing your issue in 2.4.7 it's probably the same thing.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
