### ISSUE TITLE
BUG catching video stop

### ISSUE THREAD

**Issue by jaraiza** [photonstorm/phaser#2543]
This Issue is about

* A bug in the API

There is a bug with phaser.signal detecting when a video has ended when using changeSource function. The times the video is reporting as "ended" is equal to the times changeSource was changed.

To reproduce the issue, please change both videos and the image button with some media you have. 

Once you run the demo, check your **developer console** each time button is pressed.

- The first time the video is stopped, it says "Played 1 times"
- The second time it says "Played 2 times" AND "Played 3 times"
- The third time it says "Played 4 times", "Played 5 times" AND "Played 6 times"

and so on...

It's like it is reporting when each video has stopped, not just the video that has just been "source changed".

Here's the code:

```javascript
window.played = 0;
var game = new Phaser.Game(1280, 720, Phaser.AUTO, 'gameCanvas', { preload: preload, create: create});

function preload() {
	game.load.video('Blank', 'vids/somevideo.mp4');
	game.load.image('btn','gfx/btn_play.png');
}

function create() {
	button = game.add.button(100, 400, 'btn', btnClick);
	
	video = game.add.video('Blank');
	video.addToWorld(0, 0, 0, 0, 0, 0);
	
	videoOnStop = new Phaser.Signal();
	video.onComplete = videoOnStop;
	
	game.world.bringToTop(button);
	
	videoOnStop.add(function() {
		played++;
		console.log("Video Stopped: Played " + played + " times");
	});
}

function btnClick() {
	video.changeSource('vids/anothervideo.mp4');
	video.play(false);
}
```

Thank you in advance!!

**Comment by photonstorm** [comment]
I haven't tested the above yet, but is there a good reason why you're erasing the `onComplete` Signal that Video has, and replacing it with your own? Why not just: `video.onComplete.add(functionHere)` ?

**Comment by jaraiza** [comment]
Hi! To be brutally honest... A month ago when I first met and learned Phaser, I tried to learn from API docs, but since it lacks examples for each function, I went to Google and I found an example doing this, so I assumed it was the right way to do it.

Today, I know I should have used video.onComplete :) But this still seems a Signal() bug someway.

Greets!!

**Comment by photonstorm** [comment]
I know this is old, but it's also now fixed. The issue was that calling `changeSource` would queue the video to be played, so calling `video.play` right away after it, would add another entry into the `onComplete` handler. The dev build now protects against this.
