### ISSUE TITLE
[dev brunch] TilemapLayer rendering and collision detection are not consistent?

### ISSUE THREAD

**Issue by SergeyFromHell** [photonstorm/phaser#2544]
This Issue is about

* A bug in the API

(dev brunch)
TilemapLayer render uses scroll(_scrollX,_scrollY) to determine tiles that need to be rendered, but TilemapLayer collision system uses tilemapLayer.position and does not take into account scroll. I try to use the following configuration:

- tilemapLayer.fixedToCamera = false (so it is fixed in the "world")
- tilemapLayer.position = (0,0) (and it is fixed\constant)
- tilemapLayer.scrollFactorX = 1
- tilemapLayer.scrollFactorY = 1

Now, when camera position changes (for example, when camera follows moving sprite), tile collision gets broken: character falls through the map or "stands" in the middle of tiles.

I tried every possible combination of described parameters(scrollFactor = 0, fixedToCamera = true, etc), but it gave wrong results. The best was:
- tilemapLayer.fixedToCamera = false
- tilemapLayer.scrollFactorX = 0
- tilemapLayer.scrollFactorY = 0

But with these values rendering is broken: it renders only top left part of the tilemap (I think it is because scrollX,scrollY do not change so render method thinks there is nothing to rerender. But actually camera position changes!

What is a supposed way now to get a fixed in world tilemap with camera following character so that collisions work too?
In 2.4.7 version I used default configuration and it worked:
- tilemapLayer.fixedToCamera = true (default)
- tilemapLayer.position = (0,0) (and it is fixed\constant)
- tilemapLayer.scrollFactorX = 1 (default)
- tilemapLayer.scrollFactorY = 1 (default)

Dispite of fixedToCamera = true, tileLayer really was scrolling when camera moves because of scrollFactor, and tilemapLayer collision system did not use tileLayer.position. Now it uses tileLayer.position [https://github.com/photonstorm/phaser/commit/4a3e8f2b4aaa6975e4b3ada8151785e29b3728b1](url) and maybe that is a cause of inconsistency? 
Also maybe tilemapLayer rendered should use camera position (not scrollX,scollY) to determine renderable tiles?

**Comment by photonstorm** [comment]
This is almost certainly a result of the recent commits by @Upperfoot to try and get tilemaps rendering when 'stitched' together, rather than how they should be by default (i.e. `fixedToCamera`). I'll probably revert back to the original code today, and then reintroduce the changes bit by bit until I find out what's breaking it.

**Comment by Upperfoot** [comment]
@SergeyFromHell Just doing some digging, can you post a demo at all? TilemapLayer.position is only used if it's off from default 0, 0 it doesn't replace what scrollX and scrollY does, it just incorporates it into the calculation for collision and in fixX and fixY only if it's the following.

Collision:

https://github.com/photonstorm/phaser/blob/dev/src/physics/arcade/TilemapCollision.js#L133

If the TilemapLayer.position is 0,0 it wouldn't affect that line, and it wouldn't affect any of the others that use TilemapLayer.position. 

(number - 0 = number)


Render:

https://github.com/photonstorm/phaser/blob/dev/src/tilemap/TilemapLayer.js#L424-L433

Again ifor the TilemapLayer.position is off from standard then it isn't used.

Something else is going on I believe, perhaps I need to include the TilemapLayer.position in the calculation for fixX here https://github.com/photonstorm/phaser/blob/dev/src/tilemap/TilemapLayer.js#L435 and fixY here https://github.com/photonstorm/phaser/blob/dev/src/tilemap/TilemapLayer.js#L479

But you stated that your scrollFactorX and scrollFactorY where either 0 or 1 which means it would never have hit that line.

Thoughts?

**Comment by photonstorm** [comment]
The code in the repo, as it stands now, doesn't work in any of the Tilemap examples in the Phaser Examples repo either. It starts off fine, but as soon as it scrolls the collision is gone. So @SergeyFromHell is right, there's definitely something up, and I don't think it's `fixedToCamera` related, but something else. I'll have a dig into this as soon as I can, but to see it happening @Upperfoot just try out any of the Phaser examples like `map collide` or `sci-fly`.

**Comment by Upperfoot** [comment]
@SergeyFromHell Can you try this out? https://github.com/photonstorm/phaser/pull/2546

Basically what was happening was that if fixedToCamera is set to true, it was changing the tilemapLayer position to follow the camera, which interacted with collision. 

What I've done is added a conditional check to only incorporate the tilemapLayer.position in the collision if fixedToCamera is set to false, otherwise it doesn't need to incorporate the tilemapLayer.position in the collision calculations as they are already accounted for.

**Comment by SergeyFromHell** [comment]
@Upperfoot It works after the last commit. Thank you. But...
I think there is some rendering issue left. And maybe it is related to the discussed stuff.
It is only a slightly visible offset of tilemap(a few pixels) in the direction of camera movement. When camera movement stops, offset is decaying back to zero. It is visible when, for example, some things are rendered on top of tilemap(in my case that is a path lines from player to some point). I tried 2.4.7 and there is no such a thing. So it is only in the dev brunch. Maybe I should capture some video or screenshots? I'll try to give more info later...

**Comment by Upperfoot** [comment]
@SergeyFromHell Could you try 2.4.8 and compare against this https://github.com/photonstorm/phaser/blob/1b7dcd9cbb85f803de35cf9b13f78c692b7f5632/build/phaser.min.js

**Comment by SergeyFromHell** [comment]
@Upperfoot I've tested it.
2.4.8: no rendering bug.
[https://github.com/photonstorm/phaser/blob/1b7dcd9cbb85f803de35cf9b13f78c692b7f5632/build/phaser.min.js](url): has rendering bug.

**Comment by photonstorm** [comment]
You should really test it by building a release, the pre-built files are
always out of date.

I have tested every Tilemap example last night and they all work fine, with
no rendering bugs at all. So I'm happy this is fixed unless someone can
show me a test case proving otherwise.


On Friday, 10 June 2016, SergeyFromHell <notifications@github.com> wrote:

> @Upperfoot <https://github.com/Upperfoot> I've tested it.
> 2.4.8: no rendering bug.
>
> https://github.com/photonstorm/phaser/blob/1b7dcd9cbb85f803de35cf9b13f78c692b7f5632/build/phaser.min.js
> <http://url>: has rendering bug.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2544#issuecomment-225111994>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKCfN6o6z_NIDok6CX9_6P8QyH9wY5Kks5qKRGUgaJpZM4Iwuoc>
> .
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by SergeyFromHell** [comment]
@photonstorm Sure, I have built git versions. I thought however that npm-hosted releases (2.4.7, 2.4.8 ...) do not need to be rebuilded.
Anyway, I think this issue is finished.

**Comment by photonstorm** [comment]
npm releases don't need to be rebuilt, but it was the dev branch that needed testing - and that definitely does need building each time.

**Comment by SergeyFromHell** [comment]
I found the commit that fixed rendering bug.
[https://github.com/photonstorm/phaser/commit/5415d9b603112e7d74863510d86d07d50ae6838a](url)

**Comment by photonstorm** [comment]
Yeah. Just need to fix camera shake now though :)
