### ISSUE TITLE
Phaser.Sound.stop() and Phaser.Sound.destroy() doesn't works after audio loop

### ISSUE THREAD

**Issue by FlacorLopes** [photonstorm/phaser#2548]
This Issue is about:

* A bug in the API

If a mp3 or wav audio plays a loop, it won't stop when game.music.stop() or game.music.destroy() 
is called.
**I have tested it in the version 2.4.7 and works fine**, with both mp3 and wav audio.

However, the 2.4.7 version causes a strange bug in my game so I can't use it.

Note that it only happens when the audio completes a loop. Then, the create function will 
create another instance of the audio and plays it simultaneously.

The bug occurs in IE, Chrome and Firefox.

```javascript
window.onload = function(){


playState = {
    preload: function () {
        game.load.audio('music', 'assets/music 2.wav');
        
        game.physics.startSystem(Phaser.Physics.ARCADE);
    },
    create: function () {
        game.music = game.add.audio('music', 0.2, true);
        game.music.play();
    },
    gameOver: function () {
        game.music.destroy();

        game.state.start('over');
    },
    update: function () {
        if(game.input.keyboard.isDown(Phaser.Keyboard.SPACEBAR))
            playState.gameOver();

    }
};
overState = {
    create: function () {
        console.log('GAME OVER');

    },
    update: function () {
        if(game.input.keyboard.isDown(Phaser.Keyboard.SPACEBAR))
            game.state.start('play');
    }
};

var game = new Phaser.Game(600, 400, Phaser.CANVAS, '', {preload: playState.preload, 
    create: playState.create, update: playState.update});

game.state.add('play', playState);
game.state.add('over', overState);
};
```

Thanks for the attention =D

**Comment by photonstorm** [comment]
This is fixed in the `dev` branch. Please grab the latest dev build (RC3) and try that, you should find it's fine.

**Comment by FlacorLopes** [comment]
Thanks @photonstorm! The RC3 fix the problem. But now it is throwing an uncaught exception error when **game.input.keyboard.isDown(Phaser.Keyboard.SPACEBAR)** is called.

phaser.js

> phaser.js:44021 Uncaught TypeError: Cannot read property 'key' of undefined
> getKeyCode @ phaser.js:44021
> processKeyDown @ phaser.js:44056
> _onKeyDown @ phaser.js:43889

phaser.min.js
> phaser.min.js:14 Uncaught TypeError: Cannot read property 'key' of undefined
> getKeyCode @ phaser.min.js:14
> processKeyUp @ phaser.min.js:14
> _onKeyUp @ phaser.min.js:14

**Comment by photonstorm** [comment]
Yeah sorry about that, it's fixed in the dev branch already! Glad the original one is sorted though.
