### ISSUE TITLE
[Dev Branch]  Keyboard Keys

### ISSUE THREAD

**Issue by ltngames** [photonstorm/phaser#2549]
This Issue is about 
* A bug in the API

I tried out the new 2.9 RC3, tilemaps are working now but I receive errors with my keyboard keys now.
The problem is with all the keys, currently I have cursor keys, shift key and space key that I have tested and all throw this error. 
![screenshot_1](https://cloud.githubusercontent.com/assets/14813394/15943445/779ef204-2e5f-11e6-9a30-5a7fd44ca577.png)

The problem seems to be with the getKeyCode: function, but I am new to Phaser and have not really looks at the code to know for sure lol.

I have also reverted back to 2.7 to make sure it was not my code and everything works fine in 2.7.

**Comment by drhayes** [comment]
Yup, looks like the event isn't getting passed to getKeyCode [here](https://github.com/photonstorm/phaser/blob/28c1a26780c5ee734161cd8331305aa749adbbe0/src/input/Keyboard.js#L410) and [here](https://github.com/photonstorm/phaser/blob/28c1a26780c5ee734161cd8331305aa749adbbe0/src/input/Keyboard.js#L473).

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
