### ISSUE TITLE
getJSON('key', true) doesn't work for Arrays

### ISSUE THREAD

**Issue by drhayes** [photonstorm/phaser#2551]
This Issue is about (delete as applicable)

* A bug in the API

When you put an Array into the cache and then get it out like this: `cache.getJSON('key', true);` it comes out as an object instead of an array.

Here's a JSBin with a repro: http://jsbin.com/gahomu/edit?html,js,console

Notice that `thing` should've come back as an Array because that's what we put in. But it came out an object with properties 0, and 1. I'm guessing it's because my fix on [this line](https://github.com/photonstorm/phaser/blob/1daf897b2368cbfef2d7996497d164757d93e057/src/loader/Cache.js#L1315) should be checking whether to pass in a `{}` of a `[]` based on what `data` is, but I'm only guessing.

**Comment by Nuuf** [comment]
When you set clone to true Phaser uses Phaser.Utils.extend which returns an object.
My suggestion is that you either wrap your array inside an object or handle the cloning on your own.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. Your fix has been merged to the `dev` branch.
