### ISSUE TITLE
Tile map loader does not load all relevant data for object layers

### ISSUE THREAD

**Issue by gotenxds** [photonstorm/phaser#2554]
This Issue is about (delete as applicable)

* A bug in the API

Hi, Tilemap loader does not load some data when the object is an image, 
missing data that I found is width and height, you can can stretch the images in tiled but we cannot get this data since phaser only load it for polygons.

**Comment by photonstorm** [comment]
Please post a sample Tiled export so we can see exactly the properties missing.

**Comment by photonstorm** [comment]
Thanks for the PR. Merged.
