### ISSUE TITLE
setting tint for bitmap text causing IndexSize error in ie

### ISSUE THREAD

**Issue by vikramarka** [photonstorm/phaser#2555]
Hi,

I am using latest version of phaser. I use lot of bitmap textfields in my app. I usually create them with white color and apply tint to color them differently. However I have observed an issue in ie. After updating the text for a while, it is throwing index size error in ie on this line:
`renderSession.context.drawImage(this.tintedTexture, 0, 0, cw, ch, dx, dy, cw / resolution, ch / resolution);`

I tried to debug the text that is being passed to texfield, but there is nothing wrong in it.

For now, I am precoloring various fonts instead of applying a tint.

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so (and which version of IE does it happen in?). Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

If it's easier you can use the [Phaser Sandbox](http://phaser.io/sandbox/) to create a code sample (as this is now running the latest build of Phaser). Enter your code, click the 'save icon' in any of the editor tabs, and paste the URL here.
