### ISSUE TITLE
Bug with looping audio pause and resume controls

### ISSUE THREAD

**Issue by DemonicEgg** [photonstorm/phaser#2565]
This Issue is about (delete as applicable)

* A bug in the API

If this is an API error please provide example code showing what happens, and why you don't believe this is the expected behavior. Issues posted without code take _far_ longer to get resolved, sometimes not ever.

There is an issue in 2.4.8 with a looping sound not being able to pause and resume. isPlaying is not reset to true if the currentMarker is empty.

    //Gets reset by the play function
    this.isPlaying = false;
    if (this.currentMarker === '')
    {
        this.currentTime = 0;
        this.startTime = this.game.time.time;
    }
    else
    {
        this.onMarkerComplete.dispatch(this.currentMarker, this);
        this.play(this.currentMarker, 0, this.volume, true, true);
    }

Fixed it by moving this.isPlaying = false into the else statement

    if (this.currentMarker === '')
    {
        this.currentTime = 0;
        this.startTime = this.game.time.time;
    }
    else
    {
        //Gets reset by the play function
        this.isPlaying = false;
        this.onMarkerComplete.dispatch(this.currentMarker, this);
        this.play(this.currentMarker, 0, this.volume, true, true);
    }

**Comment by photonstorm** [comment]
Thanks for spending time reporting this issue. However we've already fixed this in the `dev` branch of Phaser, and it will be part of the next official release. You can track what's already been fixed by looking at the Change Log part of the [dev README](https://github.com/photonstorm/phaser/tree/dev#change-log) file.
