### ISSUE TITLE
onInputOver and onInputOut do not fire unless pointer is down

### ISSUE THREAD

**Issue by jbattersby-bb** [photonstorm/phaser#2567]
This Issue is about (delete as applicable)

* A bug in the API

Taken from the Phaser examples Text Events page:

```javascript    
var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { create: create });
var clicks = 0;
function create() {
    var text = game.add.text(game.world.centerX, game.world.centerY, "click and drag me", { font: "65px Arial", fill: "#ff0044", align: "center" });

    text.anchor.set(0.5);

    text.inputEnabled = true;

    text.input.enableDrag();

    text.events.onInputOver.add(over, this);
    text.events.onInputOut.add(out, this);

    text.events.onInputDown.add(down, this);
    text.events.onInputUp.add(up, this);
}

function over(item) {
    item.fill = "#ffff44";
    item.text = "clicked " + clicks + " times";
}

function out(item) {
    item.fill = "#ff0044";
    item.text = "click and drag me";
}

function down(item) {
    clicks++;
    item.text = "clicked " + clicks + " times";
}

function up(item) {
    item.text = "thanks for clicking!";
}
 ```

Prior to 2.4.8 the over function would be called when the mouse pointer was over the object and the out function was called on the pointer exiting the object **without** pressing the pointer down. Now, in 2.4.8, these functions are **only** called when the pointer is down.

**Comment by photonstorm** [comment]
Thanks for spending time reporting this issue. However we've already fixed this in the `dev` branch of Phaser, and it will be part of the next official release. You can track what's already been fixed by looking at the Change Log part of the [dev README](https://github.com/photonstorm/phaser/tree/dev#change-log) file.
