### ISSUE TITLE
2.4.9 - Typescript defs issues

### ISSUE THREAD

**Issue by SBCGames** [photonstorm/phaser#2568]
This Issue is about an error in the TypeScript defs

 In new typescript defs, there are some small issues, that prevent compilation of any game:

1) in phaser.d.ts new Bullet class is added, that extends Phser.Sprite class. It has kill method defined like this (https://github.com/photonstorm/phaser/blob/master/typescript/phaser.d.ts#L442):
```javascript
 kill(): void;
```
 As it returns void, it throws error during compilation. Suggested change is to:
```javascript
 kill(): Phaser.Bullet;
```

</br>
2) in pixi.d.ts there is error with generateTexture method in class Graphics. Graphics class extends DisplayObject, where generateTexture is defined with different signature.

- generateTexture in DisplayObject (https://github.com/photonstorm/phaser/blob/master/src/pixi/display/DisplayObject.js#L551):
```javascript
generateTexture(resolution?: number, scaleMode?: number, renderer?: PixiRenderer): RenderTexture;
```
- generateTexture in Graphics (https://github.com/photonstorm/phaser/blob/master/src/pixi/primitives/Graphics.js#L646):
```javascript
generateTexture(resolution?: number, scaleMode?: number, padding?: number): RenderTexture;
```
Suggested solution is kind of workaround, as you can not change method signature in derived class. Change of def for method in DisplayObject to this helps:
```javascript
generateTexture(resolution?: number, scaleMode?: number, renderer?: PixiRenderer | number): RenderTexture;
```

</br>
3) in readme.md file https://github.com/photonstorm/phaser/blob/master/typescript/readme.md there is written, that box2D / Creature defs are not created yet. Some time ago I created it for box2D - it is here at GitHub (https://github.com/SBCGames/Phaser-Box2D-Typescript-defs). It is possible to reference it in readmd.md. I am not making preassure on you, but I am proud of the defs :smile:

**Comment by photonstorm** [comment]
Damn it, I actually spent hours using `tslint` on the defs as well, making sure they were all correct - and it didn't even pick these things up! Useless.

**Comment by photonstorm** [comment]
Ok I've fixed all of those, and included your defs into the repo :)

Could you please test and let me know if it works?

**Comment by SBCGames** [comment]
Thanks! Tested on small tutorial game and it works (in fact, size of the project should not matter here as compiler reported these errors regardless of features use previously).

**Comment by photonstorm** [comment]
Awesome, thanks for letting me know before too many people got 2.4.9.

**Comment by photonstorm** [comment]
Although thinking about it, these changes won't get reflected in npm now. Arse.
