### ISSUE TITLE
Graphics shape returning incorrect width/height values while tweening

### ISSUE THREAD

**Issue by kelu-smiley** [photonstorm/phaser#2573]
I've checked this with 2.5 and it's still present.

You can reproduce the bug with this code : 

```
function bugTest()
    {
        var duration = 1000
        var interval = 200
        var blastRing = game.add.graphics(100,100)
        blastRing.lineStyle(2, 0xff0000, 1);
        blastRing.drawCircle(0, 0, 100);
        //console.log(blastRing.width + " : " + blastRing.height)
        blastRing.scale.setTo(0,0)

        var scaleTween = game.add.tween(blastRing.scale).to({x:1,y:1},duration, Phaser.Easing.Linear.None, true)
        game.time.events.repeat(interval, duration / interval, blastRingCheck, this, blastRing)
    }

    function blastRingCheck(blastRing)
    {
        console.log(blastRing.width + " : " + blastRing.height)
    }
```

Executing this code will log out what incorrect width/height values for the blastRing. The values 0-1 decimal values that seem to be the scale.x/scale.y values.

If you uncomment the console.log line in bugTest, the width/height values will log out correctly.

**Comment by photonstorm** [comment]
There's something wrong here, but it's nothing to do with tweens. Graphics objects simply don't return the correct width and height, at all, if you adjust their scale before first calling `getLocalBounds`.

**Comment by kelu-smiley** [comment]
Makes sense. So by logging out width/height, getLocalBounds was being called internally?

**Comment by photonstorm** [comment]
Yes, exactly that.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
