### ISSUE TITLE
World Bounds Disappear when changing states with p2.

### ISSUE THREAD

**Issue by ewpolly1** [photonstorm/phaser#2574]
When the game state is changed, or simply restarted using p2, the objects immediately ignore world bounds and fall directly through. The first time the state is loaded, the objects behave correctly. On subsequent state runs, the world borders are ignored, and objects move through.

Example Code:(Modified one of the p2 examples to show this bug, as my own code is needlessly complex. Every 10 seconds the state will restart. Use arrow keys to control the box. After the first 10 seconds, box will move through world bounds, due to this bug)
https://jsfiddle.net/mppvr2wj/

Tested on: Chrome 51.0.2704.103 (64-bit), with Macbook Air(Mid 2012) Running OSX Yosemite 10.10.5.

**Comment by codermua** [comment]
i have same problem. It can seems in that example [http://phaser.io/examples/v2/p2-physics/state-reset](url)

and my codes:
`var game = new Phaser.Game(W, H, Phaser.CANVAS,'', "cyclo");

    game.state.add("play",playState);
    game.state.add("boot",bootState);
    game.state.add("menu",menuState);
    game.state.start("boot");`

if bootstate include physics code, occurs error when starts other state.
`var bootState={
    create:function(){
        game.physics.startSystem(Phaser.Physics.P2JS);
        game.state.start("play",true,false);
        //there's error
    }
};`

`var bootState={
    create:function(){
        //game.physics.startSystem(Phaser.Physics.P2JS);
        game.state.start("play",true,false);
        //there's not error
    }
};`

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by codermua** [comment]
thanks rich
