### ISSUE TITLE
Button click location changing when resizing canvas for responsiveness

### ISSUE THREAD

**Issue by TolgaND** [photonstorm/phaser#2575]
Phaser seems to have an issue with relocating the click field to the same location as the sprite button I am using. When I resize the browser window, I change the width of the canvas using jQuery and Phaser.Game to fix the flicker issue (this doesn't happen when using PIXI JS), because it seems that Phaser.Game doesn't resize automatically with the canvas itself. So this is my resize method in ES6:

`

    onResize() {
        this.ratio = this.getMinRatio();

        this.positionY  = window.innerHeight / 2 - (this.dimensions.h * this.ratio) / 2;
        this.positionX  = window.innerWidth / 2 - (this.dimensions.w * this.ratio) / 2;

        $('#container').children().first().css({
            'width'             : Math.ceil(this.dimensions.w * this.ratio),
            'height'            : Math.ceil(this.dimensions.h * this.ratio),
            "-webkit-transform" : "translate("+ this.positionX + "px," + this.positionY + "px)",
            "-ms-transform"     : "translate("+ this.positionX + "px," + this.positionY + "px)",
            "transform"         : "translate("+ this.positionX + "px," + this.positionY + "px)"
        });

        this.game.width   = Math.ceil(this.dimensions.w * this.ratio);
        this.game.height  = Math.ceil(this.dimensions.h * this.ratio);
    }

    getMinRatio() {
        var sx = window.innerWidth / this.dimensions.min;
        var sy = window.innerHeight / this.dimensions.h;

        return Math.min( sx, sy );
    }
`

I didn't had the same issue when using PIXI JS, so what do I do wrong? Did I forget something? Please explain if possible, thank you.

[http://www.html5gamedevs.com/uploads/monthly_2016_06/outside-click.thumb.jpg.416b6770ca8fe882998f4473b0999855.jpg](http://www.html5gamedevs.com/uploads/monthly_2016_06/outside-click.thumb.jpg.416b6770ca8fe882998f4473b0999855.jpg)

**Comment by stoneman1** [comment]
You are setting this.game.width and height directly.

In the docs it says :

Do not modify this property directly: use Phaser.ScaleManager#setGameSize - eg. game.scale.setGameSize(width, height) - instead.

**Comment by photonstorm** [comment]
Closing this one off as it's been answered above, plus also I believe you've solved this already judging by your post to the forum re: Scale Manager guide.
