### ISSUE TITLE
Weapon.onFire documentation lists arguments in wrong order.

### ISSUE THREAD

**Issue by drhayes** [photonstorm/phaser#2578]
This Issue is about (delete as applicable)

* An error in the documentation

Docs say weapon first, then bullet instance. Actual order from code is reversed.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `dev` branch, and attributed the work to you in the README. If you need to tweak the code for whatever reason, please submit a new PR.
