### ISSUE TITLE
Mobile device - Input Events

### ISSUE THREAD

**Issue by robsontenorio** [photonstorm/phaser#2582]
Hi,

The "onInputOver" event is called just the first time when the sprite is clicked. The next "clicks" are ignored.

**How to reproduce:**
NOTE: Run on Chrome debuger to emulate a mobile device 

- Click and release the sprite. Console: over > down > up 
- The next clicks. Console: down > up 

Is that an expected behavior or could be a bug?

```
var MainState = {

    preload: function() {

        this.load.image('box', 'assets/sprites/block.png');

    },

    create: function() {

        var sprite = game.add.sprite(0,0, 'box');

        sprite.inputEnabled = true;

        sprite.events.onInputDown.add(icon_click, this);
        sprite.events.onInputOver.add(icon_over, this);
        sprite.events.onInputOut.add(icon_out, this);
        sprite.events.onInputUp.add(icon_up, this);
     
    }

};

function icon_click() { 

    console.log('down');

}

function icon_over() {        
    console.log('over');

}


function icon_out() { 
        console.log('out');
}

function icon_up() { 
        console.log('up');
        
}

var game = new Phaser.Game(800, 600, Phaser.AUTO, 'phaser-example', MainState);
```

**Comment by photonstorm** [comment]
Unless you touch somewhere else on the game, outside of the Sprite, it's going to keep thinking you're over it, because that is where the last touch event occurred. As obviously there is no concept at all of 'over' or 'out' on touch devices, those events are of dubious value on mobile.

**Comment by robsontenorio** [comment]
My card game: emulate "mouse over card".  While finger is kept pressed and sliding over each card it would be enlarged/reduced.

Yes, i would like the "over" were trigged again, on the next click, and next, and next... 
Because, the current behavior affects my purpose.

```
Click1 : Console: over > down > up (yes! )
Click2: Console: down > up   (no! over not triggered)
Click3: Console: down > up   (no! over not triggered)
...

```

So, its an expected behavior? Or "over" is not applied for mobile devices?
