### ISSUE TITLE
Phaser 2.5.0 - Phaser.Text Changing text dynamically causes game to lag

### ISSUE THREAD

**Issue by bomzj** [photonstorm/phaser#2584]
Changing text in global update method causes game to lag in Phaser 2.5.0, while it works smooth in 2.4.8.

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

If it's easier you can use the [Phaser Sandbox](http://phaser.io/sandbox/) to create a code sample (as this is now running the latest build of Phaser). Enter your code, click the 'save icon' in any of the editor tabs, and paste the URL here.
