### ISSUE TITLE
Graphics objects can't be interactive

### ISSUE THREAD

**Issue by symbiane** [photonstorm/phaser#2591]
Graphics objects can't be interactive.

In the version of 2.1.3, Pixi v2 Specific New Features contain "Graphics objects can now be interactive." , this is amazing, and it last stable in 2.2.0, 2.2.1, 2.2.2. But after that, from 2.3.0 till 2.5.0 this feature is missing.

Please fix it. Thank you!

[testgraphics.txt](https://github.com/photonstorm/phaser/files/331531/testgraphics.txt)

**Comment by photonstorm** [comment]
Your testgraphics.txt file is empty for me. Please can you upload it as a gist, or just paste it into a comment here.

**Comment by symbiane** [comment]
<html>
<head><title>test</title></head>
<body>
<div id="test"></div>
</body>
<script src="phaser250.min.js"></script>




<script>
var game = new Phaser.Game(1280,800, Phaser.CANVAS, 'test', {create:create});
function create() {
   this._graphicsHat = game.add.graphics(0, 0);
   var createCanvas = drawHat(this._graphicsHat, 0, 0);
   this._canvasHat = game.add.sprite(0, 0);
   this._canvasHat.addChild( createCanvas );
   // click:
   this._canvasHat.inputEnabled = true;
   this._canvasHat.input.useHandCursor = true;
   this._canvasHat.events.onInputDown.add(clickHat, this);
}

function drawHat(ctx, xoff, yoff) {
   ctx.beginFill(0xff0000);
   // ctx.beginPath() en Pixie.js
   ctx.lineStyle(4, 0x00ffff, 1);
   ctx.moveTo(279 + xoff, 301 + yoff);
   ctx.bezierCurveTo(263 + xoff, 296 + yoff, 262 + xoff, 269 + yoff, 273 + xoff, 253 + yoff);
   ctx.bezierCurveTo(276 + xoff, 224 + yoff, 302 + xoff, 159 + yoff, 310 + xoff, 147 + yoff);
   ctx.bezierCurveTo(346 + xoff, 93 + yoff, 405 + xoff, 75 + yoff, 420 + xoff, 74 + yoff);
   // a lot of more ctx.
   return ctx;
}
   
function clickHat() {
	console.log('click...');
}
</script>
</html>

**Comment by symbiane** [comment]
<script>
var game = new Phaser.Game(1280,800, Phaser.CANVAS, 'test', {create:create});
function create() {
   this._graphicsHat = game.add.graphics(0, 0);
   var createCanvas = drawHat(this._graphicsHat, 0, 0);
   this._canvasHat = game.add.sprite(0, 0);
   this._canvasHat.addChild( createCanvas );
   // click:
   this._canvasHat.inputEnabled = true;
   this._canvasHat.input.useHandCursor = true;
   this._canvasHat.events.onInputDown.add(clickHat, this);
}

function drawHat(ctx, xoff, yoff) {
   ctx.beginFill(0xff0000);
   // ctx.beginPath() en Pixie.js
   ctx.lineStyle(4, 0x00ffff, 1);
   ctx.moveTo(279 + xoff, 301 + yoff);
   ctx.bezierCurveTo(263 + xoff, 296 + yoff, 262 + xoff, 269 + yoff, 273 + xoff, 253 + yoff);
   ctx.bezierCurveTo(276 + xoff, 224 + yoff, 302 + xoff, 159 + yoff, 310 + xoff, 147 + yoff);
   ctx.bezierCurveTo(346 + xoff, 93 + yoff, 405 + xoff, 75 + yoff, 420 + xoff, 74 + yoff);
   // a lot of more ctx.
   return ctx;
}
   
function clickHat() {
	console.log('click...');
}

**Comment by symbiane** [comment]
function create() {
   this._graphicsHat = game.add.graphics(0, 0);
   var createCanvas = drawHat(this._graphicsHat, 0, 0);
   this._canvasHat = game.add.sprite(0, 0);
   this._canvasHat.addChild( createCanvas );
   // click:
   this._canvasHat.inputEnabled = true;
   this._canvasHat.input.useHandCursor = true;
   this._canvasHat.events.onInputDown.add(clickHat, this);
}

function drawHat(ctx, xoff, yoff) {
   ctx.beginFill(0xff0000);
   // ctx.beginPath() en Pixie.js
   ctx.lineStyle(4, 0x00ffff, 1);
   ctx.moveTo(279 + xoff, 301 + yoff);
   ctx.bezierCurveTo(263 + xoff, 296 + yoff, 262 + xoff, 269 + yoff, 273 + xoff, 253 + yoff);
   ctx.bezierCurveTo(276 + xoff, 224 + yoff, 302 + xoff, 159 + yoff, 310 + xoff, 147 + yoff);
   ctx.bezierCurveTo(346 + xoff, 93 + yoff, 405 + xoff, 75 + yoff, 420 + xoff, 74 + yoff);
   // a lot of more ctx.
   return ctx;
}
   
function clickHat() {
	console.log('click...');
}

**Comment by symbiane** [comment]
Hi photonstorm, thank you for reply, I had test from every version from 2.0.6 to 2.5.0, only 2.1.3, 2.2.0, 2.2.1, 2.2.2 can enabled "inputEnabled", "useHandCursor", "events" on graphics, other versions still remain default cursor when mouse over, and no click event can be added on it.

**Comment by symbiane** [comment]
![testgraphics](https://cloud.githubusercontent.com/assets/18189938/16366683/59dad0de-3c4d-11e6-8ccb-989a9c37cfa8.png)

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
