### ISSUE TITLE
Phaser Text (alignment)

### ISSUE THREAD

**Issue by Scraft** [photonstorm/phaser#2594]
When setting up Phaser text to be right aligned, when the text is changed, for a single frame the text is positioned correctly (it looks like it is probably using left alignment), and then a frame later it snaps to the right position.

![Image](https://s31.postimg.org/u0u8afgbf/phaser_text_alignment_bug.png)

In the above image, the left hand side is what happens for the first frame (after setting the new text), and the right hand side is what it looks like a frame later (and from then onward). The code used to create the text:

```javascript
score = this.game.add.text(275, 200 + i * 32, "", {  
    font: "bold 24px Arial",  
    fill: "#fff",  
    boundsAlignH: "right"  
});  
score.setTextBounds(-50, 0, 100, 100);
```

And the code used to update (this is done when the score is returned from the server):

```javascript
score.text = scoreValue;
```

I have noticed this issue in multiple places in my project, if it turns out this is a mistake on my part, and not a bug, please accept my apologies (although my usage feels like a common sense attempt of doing the right thing, so it may be of interest anyway).

**Comment by photonstorm** [comment]
I wonder if the issue is related to _when_ the text is updated? I.e. if the text is set after the game `update` loop has run, but before `render` is called, then I can full-well imagine it would do what you outline above, as it's only half been processed. One way to check this would be to try updating the text in response to a key press, or mouse click, something internal and handled by Phaser, and observing if the same pattern emerges. Then you could try swapping the text update for a setTimeout, which is async and out of the core game loop, so should highlight the problem you're seeing most of the time (depending when it fires of course).

**Comment by Scraft** [comment]
Okay, I have followed your suggestion, and put the code that changes the text into a block:

```javascript
setTimeout(function (scoreValue) {
    score.text = scoreValue;
}, null, scoreValue);
```

The problem remains, specifically, if I put a break point inside the setTimeout callback (where I set score.text to ScoreValue), and then once that has been hit, put a break point in the update function for the class, the next time the update function is hit the text hasn't updated, the following time it has updated but has the wrong position, and the next time (and from then onward) it appears in the right position.

I am happy to run further tests based on your feedback if that helps.

**Comment by Scraft** [comment]
Okay, so with that it fixes the issue, or more precisely, the break point in the text update gets hit, then the break point in the update (the text on screen hasn't changed yet), on the next update the screen has updated at the alignment and position is correct.

I'm happy to place these extra calls in my code where I change text with alignment for the time being; if ultimately a better fix can be worked out on the API side so this 'just works' I'll be happy to remove these changes to confirm the fix.

Thanks for your help (and continue to let me know if I can do more to help). Finally, for what it is worth, I am using typescript for this project (this is my first little test project for HTML5, Javascript, Phaser, TypeScript, it is all new to me), and from a bit of fiddling, I found I needed to add this to the top of my file in order to access the update/dirty stuff you mentioned:

```javascript
declare module Phaser {
    interface Text {
        dirty: boolean;
        updateText(): void;
    }
}
```
It is nice to see my Facebook leaderboard now working correctly with out any text pinging around the screen!

**Comment by photonstorm** [comment]
Yeah those are private methods, we don't add those to the TS defs as you don't _normally_ need to call them directly! I've an idea about the API, give me a few minutes.

**Comment by photonstorm** [comment]
There you go - that should do it (see latest commit) :)

**Comment by Scraft** [comment]
Nice; thanks. Once the next release is made I'll grab and try it out (I'm just using the phaser.min.js/phaser.d.ts files, as previously stated, just getting started with this, so haven't experimented with attempting to work directly off the github individual source files).
