### ISSUE TITLE
Phaser doesn't comply typings standards.

### ISSUE THREAD

**Issue by ulitiy** [photonstorm/phaser#2595]
This Issue is about

* An error in the TypeScript defs

It seems that phaser doesn't comply typings standards.
See https://github.com/typings/typings/blob/master/docs/faq.md#should-i-use-the-typings-field-in-packagejson

Please consider adding support, it will enhance a ts experience a lot.

**Comment by photonstorm** [comment]
Is that not what this PR does? (I don't use TS, but I'm sure it does)

https://github.com/photonstorm/phaser/pull/2576

**Comment by ulitiy** [comment]
Yes, I think so. It's not in package.json though but it's your decision whether to include it there or not, it makes just `typings install phaser` to install definitions, not `typings install github:photonstorm/phaser/typescript/typings.json -GD`
You can close the issue if you're fine with that.

**Comment by photonstorm** [comment]
@monagames any thoughts on the above? (as it was your PR)

**Comment by monagames** [comment]
The entry in package.json can be adde without a problem. I hesitated at the beginning since I did not know if it might cause any trouble with the typescrit/definitions entries in that file. I can prepare a PR and run some tests.

However, mind that the effect of that change is that you could use 'typings install github:photonstorm/phaser -GD'. In order to use the short command we need to add an entry in the typings registry

**Comment by photonstorm** [comment]
Add it in and we can ask people to test it. If no-one helps test it, we'll just remove it again.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by letmaik** [comment]
Why is the `"typings"` field pointing to a json file? Have a look at http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html This should point to the main `.d.ts` file, and in fact Visual Studio Code doesn't recognize the typings of phaser when I use it via npm.

**Comment by monagames** [comment]
There is some work to do after the new approach in typescript 2.0 related to npm packages. I made a quick attempt to fix it, but the dependencies with the type definitions for pixi gave me some trouble. I suggest you try to use typings as described in https://github.com/photonstorm/phaser/blob/master/typescript/readme.md
