### ISSUE TITLE
Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.

### ISSUE THREAD

**Issue by fzuleta** [photonstorm/phaser#2597]
Hi, after updating to Phaser 2.5.0 Im getting this message

Im triggering like this
`
if (audio.isDecoded == true) {
 audio.play("",position,1,loop,true);
}
`

![image](https://cloud.githubusercontent.com/assets/3056157/16385322/eff4637e-3c51-11e6-953b-b1197b4aa373.png)

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible. Having said that, I have added in a guard to stop disconnections from a gainNode that no longer exists.

If it's easier you can use the [Phaser Sandbox](http://phaser.io/sandbox/) to create a code sample (as this is now running the latest build of Phaser). Enter your code, click the 'save icon' in any of the editor tabs, and paste the URL here.
