### ISSUE TITLE
Bitmaptext with "maxWidth" defined sometimes truncates last word in line without adding line break

### ISSUE THREAD

**Issue by WVI** [photonstorm/phaser#2601]
This only happens if the last word just barely doesn't fit within the maxWidth area:

![image](https://cloud.githubusercontent.com/assets/1386475/16527586/aede9d28-3f85-11e6-9e5e-435ad87dea20.png)

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

If it's easier you can use the [Phaser Sandbox](http://phaser.io/sandbox/) to create a code sample (as this is now running the latest build of Phaser). Enter your code, click the 'save icon' in any of the editor tabs, and paste the URL here.

**Comment by WVI** [comment]
http://phaser.io/sandbox/edit/xCjioTqo
