### ISSUE TITLE
Suggestion: It would be nice if there was an easier way to create bitmapfonts using a shared texture atlas

### ISSUE THREAD

**Issue by crippledcactus** [photonstorm/phaser#2614]
I wish there was an easier way to create a bitmapfont using a shared texture atlas. Yes I know its possible to do this as seen here: http://phaser.io/news/2016/03/merging-font-into-atlas-tutorial but it still feels very hacky. :)

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
