### ISSUE TITLE
Sprite unscaled width and height

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2615]
Phaser gives us the `scale`, `width` and `height` properties. But it doesn't give us access to the original dimensions of the Sprite/Button, etc.

If I have a 30x30 Sprite and I'm currently animating its scale (let's say it's `0.5` at the moment), its width and height are 15. If I want to position a second element below it in this moment, after the first element's animation is finished, the second one is not below it. It's 15px above its bottom since it was put there while the animation was going.

To avoid that, I need to do the following
```
var s = firstElem.scale;
firstElem.scale.setTo(1);
var w = firstElem.width,
    h = firstElem.height;
firstElem.scale = s;

secondElem.x = firstElem.x + w;
secondElem.y = firstElem.y + h;
```

That is pretty annoying. It would be nice if visible objects with `scale` had `originalWidth` and `originalHeight` or maybe `unscaledWidth` and `unscaledHeight` properties.

Thanks for your attention!

**Comment by photonstorm** [comment]
The the way width / height / scale works is directly influenced by Pixi. However, you can get the values you need from the texture, which will always return the original dimensions, regardless of the transforms: `sprite.texture.width` and `sprite.texture.height`.
