### ISSUE TITLE
Arcade Physics bug - Not updating arcade body correctly when using animation with atlas and an anchor

### ISSUE THREAD

**Issue by andiCR** [photonstorm/phaser#2616]
I am using the following code:

http://codepen.io/andiCR/pen/BzmyKL

As you can see, the bounding box for Ken jumps from one place to the other even though it's just changing the sprite frame. This happens because I have a sprite animation with different widths per frame (animation based on atlas) and an anchor set to (0.5, 1). It's not doing the correct alignment calculation and moves the collision rectangle on some frames.

**Comment by SBCGames** [comment]
This is not bug as description of setSize method in Body.js in Arcade physics says (https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/Body.js#L1038):
``` javascript
    * @method Phaser.Physics.Arcade.Body#setSize
    * @param {number} width - The width of the Body.
    * @param {number} height - The height of the Body.
    * @param {number} [offsetX] - The X offset of the Body from the top-left of the Sprites texture.
    * @param {number} [offsetY] - The Y offset of the Body from the top-left of the Sprites texture.
    */
    setSize: function (width, height, offsetX, offsetY) {
```
Offset is measured from top left of the sprite. I put nontransparent background under your sprite and these are results:

![ken](https://cloud.githubusercontent.com/assets/8962889/16746233/afe3b58c-47b9-11e6-823e-af97b3ff39e2.png)

Box is still the same size and is always requested 10px from left.

In your case, I would make all frames of the seme size - then you have to set body only once. As second possibility, I would make all frames of the same size at least within every animation. then you have to set size only when changing animation. Mixing frames of different size in one animation can bring problems similar to yours. For example animating sprite with anchor set to [0.5, 0.5] with different frames will center all of them, which may not be desired.
 Second, I would switch trimmed ON in TexturePacker - it will save you lot of space in your atlas (all the free space you have between characters), while information on original size (with empty space) is still preserved in export.

**Comment by andiCR** [comment]
While I agree the setSize description takes into account the top-left of the Sprite image and not the anchor, I think it is very inconvenient to leave this as is. The animation's anchor is at the bottom center of the sprite (feet) precisely to both save unnecesary frame space as well as be able to place any object, any height or size, and have it placed at the exact same position. Think of having this coordinate set to either a big character like Zangief or small one like Sakura (all Street Fighter) set to the same position on screen, all of them with different image sizes. This is a very common practice for games, so I'd like to keep my anchors on the middle-bottom.
I think this should be labeled as a suggested feature, if not a bug. I don't think the way it's working now is consistent.

**Comment by SBCGames** [comment]
I would not call it inconsistent, as it is consistent (will show later), but you are right, that more convenient would be to offset body from anchored point instead from top left.

This forum post summarizes history in last few months: http://www.html5gamedevs.com/topic/22695-247-248-body-anchoring-any-migration-tips/#comment-129375

- Phaser 2.4.7 - yes, there was inconsistency (see first picture). Changing anchor changed body position within sprite in unpredictable way (issue https://github.com/photonstorm/phaser/issues/2470). Bugfix fixed this bug, so body stays on fixed position, but original idea of code - offset from top-left of sprite - was preserved,
- Phaser. 2.4.8 - fixed bug when flipping along x or y axis (second picture),
- last picture is current state.

During all changes the idea of body from top-left corner is preserved. What you want is to offset it from anchored point. In fact it is very easy fix. It even makes code more simple. Locate in code this lines (https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/Body.js#L587):
``` javascript
        this.position.x = (this.sprite.world.x - (this.sprite.anchor.x * this.sprite.width)) + this.sprite.scale.x * this.offset.x;
        this.position.x -= this.sprite.scale.x < 0 ? this.width : 0;

        this.position.y = (this.sprite.world.y - (this.sprite.anchor.y * this.sprite.height)) + this.sprite.scale.y * this.offset.y;
        this.position.y -= this.sprite.scale.y < 0 ? this.height : 0;
```
and change it to this (jus comment out part of line):
```javascript
        this.position.x = (this.sprite.world.x /*- (this.sprite.anchor.x * this.sprite.width)*/) + this.sprite.scale.x * this.offset.x;
        this.position.x -= this.sprite.scale.x < 0 ? this.width : 0;

        this.position.y = (this.sprite.world.y /*- (this.sprite.anchor.y * this.sprite.height)*/) + this.sprite.scale.y * this.offset.y;
        this.position.y -= this.sprite.scale.y < 0 ? this.height : 0;
```
Then do similar in reset method (https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/Body.js#L1144)

What I am afraid is, how many people will find their games broken, if this change is implemented. Those changes described above broke some people's games (on the other side it is true, that most problems was with temporary flipping bug in 2.4.8 not with original bugfix). I think this is crucial point Rich will consider if he decides to chage it. 

Saving frame space, you wrote about, has nothing to do with this problem - just switch tirmming in Texture packer to get rid of all empty spaces around characters (in your atlas .json all characters have set "trimmed": false).

For now, to get what you want quickly, you can make custom build with changes above.

**Comment by andiCR** [comment]
Thanks @SBCGames , really appreciate the effort on your responses. I'll copy this to my phaser lib and use it. Great work man.

**Comment by photonstorm** [comment]
Hmmm, this is exactly how it _used_ to work (based off the anchor), but then it was changed a few versions ago, and now everyone is used to what it is now. But this suggests changing it back again. I'm not entirely sure. So many people confuse the anchor with a registration point, and that really is not what it is, it's nothing more than a texture offset.

I'll have a think about it, but I'm not exactly thrilled about the idea of reverting it back again, put it that way.

**Comment by SBCGames** [comment]
@photonstorm are you sure, that 2.4.7 was based off anchor? Code was looking for top lef corner of sprite and then offseting from it:
``` javascript
        this.position.x = (this.sprite.world.x - (this.sprite.anchor.x * this.width)) + this.offset.x;
        this.position.y = (this.sprite.world.y - (this.sprite.anchor.y * this.height)) + this.offset.y;
```
 problem was, it was not using width and height of sprite, but body and it was giving hardly predictable results, because anchor applied to sprite, was here applied to body size. On second row of imaga at: http://www.html5gamedevs.com/topic/22695-247-248-body-anchoring-any-migration-tips/#comment-129375 you want body offset 15,15, but on pictures it is 15,15 from both anchor and top left of the sprite only on first image. On others it is not 15,15 from anchor nither top left of sprite.

 So, change to 2.4.8 was this - taking width and height of sprite:
``` javascript
        this.position.x = (this.sprite.world.x - (this.sprite.anchor.x * this.sprite.width)) + this.offset.x;
        this.position.y = (this.sprite.world.y - (this.sprite.anchor.y * this.sprite.height)) + this.offset.y;
```
It kept body on fixed position relative to top left of sprite. But problem with negative scales was still there. I believe, that lot of people never encountered it, because by chance in 2.4.7 negative x with anchor 0.5 (most common) resulted in the same result as positive x with anchor 0.5.

 Change in 2.4.9 corrected this:
``` javascript
        this.position.x = (this.sprite.world.x - (this.sprite.anchor.x * this.sprite.width)) + this.sprite.scale.x * this.offset.x;
        this.position.x -= this.sprite.scale.x < 0 ? this.width : 0;
        this.position.y = (this.sprite.world.y - (this.sprite.anchor.y * this.sprite.height)) + this.sprite.scale.y * this.offset.y;
        this.position.y -= this.sprite.scale.y < 0 ? this.height : 0;
```

 Now, the discussed change, regargless it will be implemented or not, is in fact anchor independent:
``` javascript
        this.position.x = this.sprite.world.x + this.sprite.scale.x * this.offset.x;
        this.position.x -= this.sprite.scale.x < 0 ? this.width : 0;
        this.position.y = this.sprite.world.y + this.sprite.scale.y * this.offset.y;
        this.position.y -= this.sprite.scale.y < 0 ? this.height : 0;
```
 It is not interested in anchor (texture offset) anymore. It completely splits from visual representation of sprite (texture, width, height) - sprite is anchored relative to sprite positon and body is independently offseted from sprite position. It is fun, that this code is also most simple in whole code evolution (while including negative scale handling). Only one things is in my mind: whether width and height of body here should be also multiplied with sprite scale if it is different from 1/-1, so it scales correctly with sprite (will have to make some tests, but I think it should).

**Comment by Nuuf** [comment]
This is not an issue as far as I can tell.
If you want it centered just use setSize(bodyWidth, bodyHeight, spriteWidth * 0.5 - bodyWidth * 0.5, spriteHeight * 0.5 - bodyHeight * 0.5);

**Comment by photonstorm** [comment]
@SBCGames taking you 2 revised versions of this, both fail the [Body Scale](http://phaser.io/examples/v2/arcade-physics/body-scale) test.

The first:

```
        this.position.x = this.sprite.world.x + this.sprite.scale.x * this.offset.x;
        this.position.x -= this.sprite.scale.x < 0 ? this.width : 0;

        this.position.y = this.sprite.world.y + this.sprite.scale.y * this.offset.y;
        this.position.y -= this.sprite.scale.y < 0 ? this.height : 0;
```

Causes the bodies to collide at what looks like an offset value. The final one:

```
        this.position.x = this.sprite.world.x + this.sprite.scale.x * (this.offset.x - this.sprite.scale.x < 0 ? this.width : 0);
        this.position.y = this.sprite.world.y + this.sprite.scale.y * (this.offset.y - this.sprite.scale.y < 0 ? this.height : 0);
```

Causes the two bodies to just pass right through each other.

**Comment by SBCGames** [comment]
@photonstorm 
 The final one is crap. I am sorry for that...

 The first one works, but you need to call setSize for every new body... which is not too friendly. It is appropriate to what @andiCR needed to solve, but probably not for majority of users who need quickly set their sprites with bodies. I would stick to custom changes when someone has similar needs like andiCR. So, sorry once more...

**Comment by photonstorm** [comment]
Ok thanks for the clarification @SBCGames - going to close this one off, the solution has been given.
