### ISSUE TITLE
Camera.shake

### ISSUE THREAD

**Issue by VitaZheltyakov** [photonstorm/phaser#2617]
This Issue is about (delete as applicable)

* A bug in the API
--
camera.shake - shake all sprites in the view.
We need a parameter, which forbade sprite shake. For example, sprite.noShake = true;

**Comment by photonstorm** [comment]
This is a feature request, not a bug.

**Comment by photonstorm** [comment]
I'm closing this off as a "won't do". Camera shake is implemented (in WebGL) by changing the projection offset at the start of the render, not by adjusting sprite coordinates or similar. It would need refactoring to provide this feature, which I don't want to do at this stage.
