### ISSUE TITLE
Big drop in Graphics performance with introduction of updateLocalBounds() after internal drawing functions.

### ISSUE THREAD

**Issue by pengchuan** [photonstorm/phaser#2618]
I understand that the inclusion of this function is necessary for checking bounds of graphics objects (fix for #2573 - commit 4066a8d on 29 Jun 2016). However, since its inclusion, my application (which involves drawing charts with lots of lineTo() calls on full browser dimensions) performance has dropped significantly such that the entire application lags for almost 1s just to get a full redraw, which did not happen in 2.5.0.

Is it possible to have a flag that disables this bounds update for applications that do not need it?

Appreciate any help with this. Thanks!

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch. Let me know if it works better for you.
