### ISSUE TITLE
Phaser.Stage has no parent.

### ISSUE THREAD

**Issue by Arcanorum** [photonstorm/phaser#2620]
So I was about to do some debugging using https://github.com/englercj/phaser-debug and got an error when trying to inspect the Scene Tree.

> Uncaught TypeError: Cannot read property 'visible' of null

Which I traced back to this code.
```
/**
    * Indicates if this DisplayObject is visible, based on it, and all of its parents, `visible` property values.
    * @name PIXI.DisplayObject#worldVisible
    * @property {boolean} worldVisible - Indicates if this DisplayObject is visible, based on it, and all of its parents, `visible` property values.
    */
    'worldVisible': {

        get: function () {

            if (!this.visible)
            {
                return false;
            }
            else
            {
                var item = this.parent; // <---- Error line. No parent exists on 'this' when 'this' is the stage.

                do
                {
                    if (!item.visible)
                    {
                        return false;
                    }

                    item = item.parent;
                }
                while (item);

                return true;
            }

        }

    },
```

I'm using 2.6.1. According to the docs, as of 2.6.0 Phaser.Stage no longer has a parent property.

**Comment by photonstorm** [comment]
I'm not sure I get this issue, because Phaser.Stage has a `parent` property (and always has), it's just set to `null` by default, and always has been because it's the root level display object.

Do you have a working piece of code that can demonstrate this?

**Comment by Arcanorum** [comment]
I only noticed this screwing up since 2.6.0.

Check the console after trying to open the Scene Tree panel. Minimal demos:
- Working fine with 2.5.0: http://waywardworlds.com/games/demo/2.5.0/
- Not working with 2.6.1: http://waywardworlds.com/games/demo/2.6.1/

**Comment by AleBles** [comment]
Stage always had parent, but it's only since e39cd584bf086d8f4817bc16f4209010ae049ba8 that we're checking the parent of an item in the DisplayObject. A simple fix would be that we change the while loop to a regular while, therefor also checking if the parent condition is null before looping.

**Comment by photonstorm** [comment]
The `worldVisible` loop was updated in the previous version, so it checks the parent first, so am closing this off as fixed.
