### ISSUE TITLE
Uncaught TypeError: Cannot set property 'y' of undefinedBasicGame.Game.gameResized

### ISSUE THREAD

**Issue by elviscristiano** [photonstorm/phaser#2622]
Hi,

I'm using:
- Intel XDK with Phaser template (structured in 2 files Game.js and app.js) + Cordova
- Phaser 2.6.1

Error
Uncaught TypeError: Cannot set property 'y' of undefinedBasicGame.Game.gameResized @ Game.js:66c.ScaleManager.preUpdate @ phaser.min.js:21c.Game.updateLogic @ phaser.min.js:12c.Game.update @ phaser.min.js:12c.RequestAnimationFrame.updateRAF @ phaser.min.js:18c.RequestAnimationFrame.start.window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:18

How to reproduce the error
This error occurs when I try to work with the gameResized function.
And, in my case, I could see that it is related with the size of my preload function. 
When I try to load 1 or 2 sprites, the system doesn't launch this error.
When I try to populate the preload function with 3 or more sprites, the error occurs.  

src/Game.js

/* globals Phaser:false */
// create BasicGame Class
BasicGame = {
};

// create Game function in BasicGame
BasicGame.Game = function (game) {
    this.ground;
};

// set Game function prototype
BasicGame.Game.prototype = {

    init: function () {
        this.input.maxPointers = 1;
        this.stage.disableVisibilityChange = true;
        this.scale.scaleMode = Phaser.ScaleManager.RESIZE;
        this.scale.pageAlignHorizontally = true;
        this.scale.pageAlignVertically = true;
        this.scale.forceOrientation(true, false);
        this.scale.setResizeCallback(this.gameResized, this);
        this.scale.updateLayout(true);
        this.scale.refresh();

    },

    preload: function () {
        this.load.image('ground', 'asset/ground.png');   
    },

    create: function () {
        //starting physics effects
        this.physics.startSystem = Phaser.Physics.ARCADE;

        //set gravity
        this.physics.arcade.gravity.y = 100;

        //ground
        this.ground = this.add.sprite(0, this.game.world.bounds.bottom,'ground'); 
        this.ground.anchor.y = 1;
    },

    gameResized: function (width, height) {
        this.ground.y = height;
    }

};

src/app.js
(function () {
    var game = new Phaser.Game(720,480, Phaser.CANVAS, 'game');
    game.state.add('Game', BasicGame.Game);
    game.state.start('Game');
})();

**Comment by photonstorm** [comment]
What you've created for yourself is a race condition. You're setting a resize callback in `init`, that modifies the y position of an object that doesn't yet exist, because it isn't created until `create`. It's perfectly possible for a game to resize during the boot / load process, so you need to either not use an asset in your callback that isn't yet ready, or don't set-up the callback until in your `create` function.

**Comment by elviscristiano** [comment]
Thank you!
