### ISSUE TITLE
Phaser.RenderTexture documentation error

### ISSUE THREAD

**Issue by Owumaro** [photonstorm/phaser#2624]
In the `Phaser.RenderTexture` class documentation, the `key` parameter is defined 2 times.

See code (L15 & L18) :
https://github.com/photonstorm/phaser/blob/dev/src/gameobjects/RenderTexture.js#L15
L15 should be deleted.

And website documentation :
http://phaser.io/docs/2.6.1/Phaser.RenderTexture.html

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
