### ISSUE TITLE
Sound.js#volume doc inconsistency

### ISSUE THREAD

**Issue by rroylance** [photonstorm/phaser#2629]
This Issue is about
* An error in the documentation

[src/sound/Sound.js#L1155-L1156](https://github.com/photonstorm/phaser/blob/dev/src/sound/Sound.js#L1155-L1156)

Line 1156 should be removed and line 1155 should be changed to say "Gets or sets the volume of this Sound, a value between 0 and 1. The value given is clamped to the range 0 to 1." to match the SoundManager volume property.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
