### ISSUE TITLE
TileSprites don't collide

### ISSUE THREAD

**Issue by RafaelOliveira** [photonstorm/phaser#263]
game.physics.collide don't work with TileSprites. The collide function don't have tilesprites in the valid objects.

**Comment by Mutinix** [comment]
TileSprite and Sprite collision stopped working with Phaser 2.3.0. Still works with 2.2.2. Tried with the example on the website as well.

**Comment by photonstorm** [comment]
Already fixed in dev, please search gh issues for options.

**Comment by chaping** [comment]
In the version 2.3.0 it seems that TileSprite doesn't have the property `physicsType`,so I think we can do that to fix it temporarily:
```
someTileSprite.physicsType = Phaser.SPRITE; //add this property manually
someGame.physics.arcade.collide(someSprite, someTileSprite); //and collide will now work
```

**Comment by alexandresgf** [comment]
Still the same! I can't collide TileSprite and Sprite. I've try every tutorial that I found in the internet and still doesn't work. I'm using Phaser 2.4.4

```
Game.prototype.update = function () {
    this.game.physics.arcade.collide(this._player, this._ground);
};
```

`this._ground` is the TileSprite and `this._player` is the Sprite. Does anyone know if it has fixed and the solution?

Thanks!

**Comment by photonstorm** [comment]
Yes it's fixed: http://phaser.io/examples/v2/tile-sprites/colliding-with-tiling-sprite
