### ISSUE TITLE
Phaser.Circle methods not working on circular physics bodies

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2630]
* A bug in the API

When the physics body is a circle (created with setCircle in arcade physics body), at least with an offset (and non-zero parent sprite anchor), some standard Circle methods don't work. For example, Phaser.Circle.intersectsRectangle:

`isSelected = Phaser.Circle.intersectsRectangle(sprite.body,someRectangle);
`

isSelected should return true in the above but doesn't. And if I create a new circle, based on the x/y center (with the radius added) and radius of the circle physics body (the sprite.body above), isSelected returns true. By adding the radius to the x/y, the method is 100% accurate as I've determined through testing. 

```
var circleArea = new Phaser.Circle(sprite.body.x + (sprite.body.radius), sprite.body.y + (sprite.body.radius), sprite.body.radius * 2);
isSelected = (Phaser.Circle.intersectsRectangle(circleArea, someRectangle));
```

So it seems intersectsRectangle is seeing incorrect x/y center on the circle is the circle is a physics body. This might be because it's not taking into consideration the anchor on the sprite or the offset. Could be either one really, as my sprite.body has an offset equivalent to half the sprite's width (which is also what the circle radius is based on). I'm encountering this same problem with Phaser.Circle.Contains.

**Comment by ForgeableSum** [comment]
hmm, I did a quick test with the sprite anchor set to 0 and no offset. Yet still the method does not work as it should.

**Comment by VitaZheltyakov** [comment]
Phaser.Circle work with geometry, no physics.
See Phaser.Physics.Arcade.intersects

**Comment by photonstorm** [comment]
I agree, this is trying to compare apples with oranges.

**Comment by ForgeableSum** [comment]
I thought the circular physics body created by arcade physics was en extension of Phaser.Circle. Why else would it have the intersectsRectangle, contains, and such methods on them? 

Is there any way to check for intersections between a physics body and non-physics body? For example, check if a circular physics body intersects with a normal Phaser.Rectangle. Or, check if an x/y coordinate lies within a circular physics body.

**Comment by samme** [comment]
@ForgeableSum you can copy a circular body into a Circle with

```javascript
var circ = new Phaser.Circle(body.center.x, body.center.y, body.halfWidth);
```

then check for intersections with it.
