### ISSUE TITLE
[02 Making your first game] Jump issue

### ISSUE THREAD

**Issue by RompePC** [photonstorm/phaser#2633]
I suposse this one isn't fixed (from what I searched in the log), but it isn't a big problem (even a little one).

In "02 Making your first game", the player's jump has an issue: you only check if it is touching something below it (```player.body.touching.down```). It isn't good, as it lets the player to jump when the below object touched is a star (for example in this project). A little hacking for it would be setting that property manually to false inside the ```collectStar``` function.

**Comment by photonstorm** [comment]
I would do it like this in the update function:

```
var hitPlatform = game.physics.arcade.collide(player, platforms);

...

if (cursors.up.isDown && player.body.touching.down && hitPlatform)
{
    player.body.velocity.y = -350;
}
```
