### ISSUE TITLE
[Meta / Suggestion] - Fixed Timestep

### ISSUE THREAD

**Issue by Dillybob92** [photonstorm/phaser#2635]
Hey folks,

I found this thread:

http://www.html5gamedevs.com/topic/5860-fixed-timestep/

And I saw:

> I haven't looked too deep into it, but as far as I know the **_update function is not running on a fixed timestep_**.  Even if the physics engine does use a fixed time-step

I'm using arcade physics. And if I have some movement code like this inside the `update` function:

```
var pMoveSpeedVelocity = 350;
if (Movement_Keys.a == 1) {
    playersprite.body.velocity.x = -pMoveSpeedVelocity;
}
```

and if a players FPS drops to 20, 30, or below 45 some problems start. It's not a fixed timestep and the player doesn't move the appropriate amount of pixels. Do you know if it's possible to add some type of `accumulator` to Phaser so we can run a fixed timestep similar to: http://gafferongames.com/game-physics/fix-your-timestep/? 

Just some thoughts. I think this feature could help with multiplayer games in the future. Especially when Lazer starts to evolve / come to fruition.

**Comment by Dillybob92** [comment]
```
            while (this._deltaTime >= slowStep)
            {
                this._deltaTime -= slowStep;
                this.currentUpdateID = count;

                this.updateLogic(1.0 / this.time.desiredFps);

                //  Sync the scene graph after _every_ logic update to account for moved game objects
                this.stage.updateTransform();

                count++;

                if (this.forceSingleUpdate && count === 1)
                {
                    break;
                }
            }
```

I found a solution. `this.forceSingleUpdate` was set to true. This basically disables the fixed timestep I think. I disabled it and tested the movement from 20FPS with forceSingleUpdate set to true / false, and if set to false, it acts as a fixed timestep and my character moves the same duration of my input (that sets the velocity) I'll close this, but maybe we can reference somewhere if people need a fixed timestep, forceSingleUpdate has to be disabled. Although, I'm not entirely sure but from what I'm testing it now works so I'll close this :)

**Comment by GGAlanSmithee** [comment]
Just to add as a reference, [here is a JS library](https://github.com/IceCreamYou/MainLoop.js) that does what you are asking for. I am using it myself, and as far as being a "mainloop" it works well, but I cannot vouch for the correctness of the fixed timestep implementation as I haven't used it extensively.

**Comment by photonstorm** [comment]
Yes a variation of this is already being used in Lazer, and is being back-ported to Phaser (see the mainloop branch) but isn't yet finished.
