### ISSUE TITLE
[2.7.0] Tilesets of by one pixel after resizing

### ISSUE THREAD

**Issue by noidexe** [photonstorm/phaser#2644]
![Imgur](http://i.imgur.com/8J3yOVj.png)

The red, yellow and green horizontal lines belong to adjacent tiles in the tileset. If I scale the browser window slowly I can see the glitch flicker on an off as I resize the window. I can stop resizing at a point where the glitch is present or at a point where it is not. 
This happens to every tile. I'm just showing you the ones where it's easy to see. 

Some rounding error maybe?

**Comment by photonstorm** [comment]
Far more likely the same issue as you get with texture atlases when frames are packed too tightly.

How are you scaling the game though? because just changing the browser window won't do that automatically.

**Comment by noidexe** [comment]
```javascript
this.game.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
this.game.scale.setResizeCallback(this.reflow,this);
```
this.reflow() keeps the same native width and adapts the height to match the window aspect ratio like this:
```javascript
this.game.scale.setGameSize(this.game.width,this.game.width*window.screen.height/window.screen.width);
```
This is the tileset image: 
![tieset](http://orig11.deviantart.net/65e2/f/2015/272/b/6/bgtiles_by_noidexe-d9bca9k.png)

There is no padding as you can see, though it never caused any bleeding before.

**Comment by photonstorm** [comment]
That's because it never rendered it with WebGL before! What do you reckon @pjbaron ?

**Comment by pjbaron** [comment]
I have seen this effect when developing the Beam renderer for Lazer but only when using point sprites (GL_POINT with a texture applied).  It is visible in the 'point tile' demo for instance.  I was not able to track it down in that, but will give it another go for this new tile renderer (which uses GL_TRIANGLE_STRIP so I am surprised to encounter it again).

@noidexe I have grabbed a copy of your tileset to experiment with from your message, can you please confirm that your tilesize is 42x42 (e.g. you didn't share a rescaled or modified version of your original tiles)?

**Comment by noidexe** [comment]
@pjbaron It is indeed 42x42. Here's the exact file that is on master right now https://www.dropbox.com/s/lk7v3cbwvil4q61/bgtiles.png?dl=0

**Comment by pjbaron** [comment]
Hi @noidexe I have just tried to recreate this in a very simple example but can't get the lines to appear.
Could you please try the attached example (it's in the standard Phaser "examples" format, though I used your code mentioned above to resize dynamically as the window changes size) and let me know if you are able to cause it to happen?
cheers,
Pete
[tiles bug test.zip](https://github.com/photonstorm/phaser/files/375685/tiles.bug.test.zip)

**Comment by photonstorm** [comment]
This is surely a result of texture bleeding, it's the exact same symptoms: http://rotorz.com/tilesystem/guide?ref=e3d107d9-e4cc-4c08-aa2b-2b555abac30a

**Comment by pjbaron** [comment]
Could be, but strange that I cannot recreate in a simple example.

**Comment by pjbaron** [comment]
Rich found the magic numbers, in my example use:

function reflow() {
    game.scale.setGameSize(800, 334.883);
}

generates lines on my system.
I'll play around with rounding and the shader but it probably is bleeding.

**Comment by pjbaron** [comment]
Ok, so I tried both round and floor on source texture (UV) coordinates but neither fixed the lines.  However turning off anti-aliasing for the game did fix them (at that scale factor anyhow):

var game = new Phaser.Game(800, 600, Phaser.WEBGL, 'phaser-example', { preload: preload, create: create, update: update, render: render }, false, false);

With pixel art like this you probably want that turned off anyhow.  Let me know if it works for you!

**Comment by noidexe** [comment]
![Imgur](http://i.imgur.com/iTfxMIb.png)

This is using freshly a freshly built phaser.js from the latest dev and the lines stay no matter how I resize the window. Sure enough disabling antialias fixes it here and on my game. 

I found [this](http://gamedev.stackexchange.com/questions/46963/how-to-avoid-texture-bleeding-in-a-texture-atlas) before creating the issue, while I googling to see if there was some error on how I created my image assets. Not sure if it'll be of any help.

**Comment by pjbaron** [comment]
Thanks for the reference, I did try applying the half-pixel correction they talk about there however with this code:
        var uvl = (t.sx + 0.5) * iTextureWide;
        var uvt = (t.sy + 0.5) * iTextureHigh; 
We get this output:
![bleed](https://cloud.githubusercontent.com/assets/614817/17041493/7e7a7d70-4ffa-11e6-992b-010ebf8a512e.png)
As you can see, it fixes the lines on top, but adds lines underneath instead.

**Comment by pjbaron** [comment]
Ok, that appears to work for this example, but for others with flipped tiles it causes problems (vertical lines at the edges when the tile is horizontally flipped).
I need to experiment with the code, applying the correction at the last stage is not the best way to handle this, it should go into the glBatch buffer much earlier in the process.
Thanks for the link!

**Comment by pjbaron** [comment]
Ok, that change is now in dev branch.  Please report any other effects it might have - I've skimmed through the example projects and they look ok.

**Comment by noidexe** [comment]
The visual glith is gone, but the game freezes when I try to switch to a different game state. It only happens when switching from the game state with the tilemap to any other. 
![Imgur](http://i.imgur.com/Ja9Rmyl.png)

**Comment by pjbaron** [comment]
I believe Rich is _currently_ working in the dev branch.  Please raise a new issue for this new bug if it continues after today.  It's great to hear the image is clean now, thanks for your help in finding the cause of that problem!

**Comment by photonstorm** [comment]
Yeah I'm changing things like mad at the moment. Give it time to settle down before trying again.

**Comment by noidexe** [comment]
Yeah I imagined it could've been that. I cherry picked your last commit(@pjbaron) ignoring the three added by Rich and everything worked fine. Thanks for the amazing work you're doing :)
