### ISSUE TITLE
[2.7.0] Tilemap layers do not respond to camera shake

### ISSUE THREAD

**Issue by noidexe** [photonstorm/phaser#2645]
Is camera shake implemented with the new tilemap renderer? It doesn't seem to be shaking anymore(the rest of the visual elements do).

**Comment by photonstorm** [comment]
True, no shaders do. But we will add support for this in.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
