### ISSUE TITLE
Phaser.Weapon.autofire not working

### ISSUE THREAD

**Issue by alverLopez** [photonstorm/phaser#2647]
Hello, i'm having a problem using autofire method in Phaser.Weapon, i set that attribute to true, but nothing happens, i tried it into this code http://phaser.io/examples/v2/weapon/fire-rate#gv.

Am i missing something? 

Thanks.

**Comment by photonstorm** [comment]
Have you actually called `fire`? It needs to be started off, and then will continue after that.

**Comment by alverLopez** [comment]
Yes, as soon as the weapon and its bullets are created, i set its autofire to true, then i fire but i doesn't keep firing, unless i keep the fire button pressed.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by JTronLabs** [comment]
Any idea when this will be published into stable? Thanks!
