### ISSUE TITLE
bitmapText.cacheAsBitmap doesn't work properly 

### ISSUE THREAD

**Issue by kamilsobieszuk** [photonstorm/phaser#2650]
Hello,

with update to 2.6 (from 2.5) I've noticed, that caching bitmapText object doesn't work properly anymore. In best case you only get few bottom pixels of text.

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

If it's easier you can use the [Phaser Sandbox](http://phaser.io/sandbox/) to create a code sample (as this is now running the latest build of Phaser). Enter your code, click the 'save icon' in any of the editor tabs, and paste the URL here.
