### ISSUE TITLE
KeyCode class not listed in docs

### ISSUE THREAD

**Issue by boniatillo-com** [photonstorm/phaser#2653]
This Issue is about

* An error in the documentation

I do not find the `KeyCode` class in the Input namespace docs:

http://phaser.io/docs/2.6.1/index#input

Maybe it does not appear because the `KeyCode` definition is tagged as `@namespace` but not as `@class`. I can do a pull request with the change.

**Comment by photonstorm** [comment]
It's here http://phaser.io/docs/2.6.1/Phaser.KeyCode.html which is linked from the Key class: http://phaser.io/docs/2.6.1/Phaser.Key.html

It doesn't appear on the index page though. I could add it I guess? That page is generated manually, not from a script.

**Comment by boniatillo-com** [comment]
Yes sure, you can add it to the index manually.

Looking into the local docs (I guess those are generated by a script), in the namespace menu there is the items `Phaser`, `KeyCode` and `PIXI` (I think `KeyCode` should not appear there, out of `Phaser.Input` namespace). And in looking in the `Input` namespace menu, the `KeyCode` does not appear. So I guess to declare it as a class  still a good solution.

**Comment by photonstorm** [comment]
KeyCode shouldn't appear in the namespace list, that is true. But the Input menu is manually created.

**Comment by boniatillo-com** [comment]
Manually added even in the local docs? Anyway... what's the options here then?

- To change the docs of the phaser site manually (you only has access to that).
- And change the local docs index manually too (I can do this).

**Comment by photonstorm** [comment]
Yes there are no automatic drop-downs generated in the local docs other than 'global' (and 'namespace' iirc), they are all hard-coded into the html template which is in the resources folder in the repo.

**Comment by boniatillo-com** [comment]
Ok thanks, let's go manually then.

**Comment by photonstorm** [comment]
We can change it to avoid it appearing in the namespace list. But it still needs manually correcting to solve those other 2 places too.

**Comment by boniatillo-com** [comment]
I see, well, I think there is some tooling behind it, docstrap or something like that. I can setup the environment or maybe it is more easy for you just to fix it next time you need to update the templates.  I just do not want to take more of your time.

**Comment by photonstorm** [comment]
Ok I've updated it so it no longer appears in the Namespace list, and now appears in the Input drop-down in the generated docs.
