### ISSUE TITLE
IOS 10 transparency issue

### ISSUE THREAD

**Issue by RyuMaster** [photonstorm/phaser#2655]
Hi! This is what I get for IOS 10 png images, transparency seems broken. Is that known issue? 

![7b22e1ed5b5315d8310b9eb1b1cb5a550df663476c14d0260f pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11544855/17006143/62dd707c-4ee7-11e6-9246-0f66d4221a9c.jpg)
![d066da77f136cf7a13207054d2904458b617076745a8a80a3d pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11544855/17006144/62e17b0e-4ee7-11e6-9381-804ad937f887.jpg)

Phaser version is 2.4.7

**Comment by photonstorm** [comment]
Yes this is an iOS10 bug. As it's still in beta and not yet released I'll be amazed if they don't fix it.

It manifests in all versions of Pixi too (see upstream issue here https://github.com/pixijs/pixi.js/issues/2726)

**Comment by photonstorm** [comment]
This appears to be fixed in the latest iOS10 beta. Closing off.
