### ISSUE TITLE
Body is offset from sprites when using parenting

### ISSUE THREAD

**Issue by deedeekaka** [photonstorm/phaser#2657]
I am working on a 2D basketball game. I am using 2 small sprites (with circular physics bodies) on each side of the basket rim for collision detection with the ball. I parented the 2 sprites to the backboard so I could move them all together (as shown in the child sprite example). I turned on the debug draw for the physics bodies and found the 2 bodies were not in the same position as the sprites.

```
//Load net sprite
this.net = this.game.add.sprite(this.game.world.centerX, 200, 'net');
this.net.anchor.setTo(0.5);

//Add hoop children markers
this.leftMarker = this.net.addChild(this.game.make.sprite(-66, 60, 'marker'));
this.leftMarker.anchor.setTo(0.5);
this.rightMarker = this.net.addChild(this.game.make.sprite(66, 60, 'marker'));
this.rightMarker.anchor.setTo(0.5);
```

I parent them like so.. but my physics bodies don't act as if they are parented. They should be at the same position as the sprite, but instead they are (-66, 60) and (66, 60) from the **top left** corner (0, 0) instead of (-66, 60) and (66, 60) from the **parents position** (world center x, 200). You can see the attached image as an example.

![offsetbody](https://cloud.githubusercontent.com/assets/6290930/17025371/7fbbf3ca-4f29-11e6-87b1-94c04f03989e.jpg)

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

If it's easier you can use the [Phaser Sandbox](http://phaser.io/sandbox/) to create a code sample (as this is now running the latest build of Phaser). Enter your code, click the 'save icon' in any of the editor tabs, and paste the URL here.
