### ISSUE TITLE
body.checkCollision.none, body.checkCollision.any do not prevent collisions

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#2661]
http://phaser.io/sandbox/CDdkxjgV

> Set the `checkCollision` properties to control which directions collision is processed for this Body. …

`checkCollision` includes `any` and `none`, but setting `any = false` or `none = true` doesn't prevent collisions.

This issue is about

* A bug in the API (or)
* An error in the documentation

**Comment by photonstorm** [comment]
To be honest I can't think of a reason why `checkCollision.none` is even in there. I'm thinking it may be a copy-paste left over from the `Body.touching` object. If you want to disable collision on a Body you should use `Body.enable = false`. I'm going to remove it, thanks for spotting it.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by photonstorm** [comment]
Actually I'm changing my mind :) I can think of reasons while you'd want a Body updating but not checking for collision.

**Comment by photonstorm** [comment]
There - much better. You can now set it, and it'll be checked inside of `separate` and skip the check if either of them has it set to `true`.
