### ISSUE TITLE
Particles made with makeParticles(collide = false) can collide

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#2662]
http://phaser.io/sandbox/wqnaJikP

> [collide=false] - If you want the particles to be able to collide with other Arcade Physics bodies then set this to true.

    makeParticles(…, collide = false)
    // …
    arcade.collide(particles, …)

The particles will still collide (bounce).

This issue is about

* A bug in the API

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
