### ISSUE TITLE
device.desktop is false on windows 10 and IE 11

### ISSUE THREAD

**Issue by fzuleta** [photonstorm/phaser#2666]
Hello! 😄 

* A bug in the API

tested on 2.5.0

to trigger: open IE 11 on windows 10  (on edge on the ... and "Open with Internet Explorer" then:

`console.log(game.device.desktop)`

it will output false

**Comment by photonstorm** [comment]
Logs out fine to me on Win 10 + IE11 and Edge:

![image](https://cloud.githubusercontent.com/assets/164476/17138475/6103cd28-5338-11e6-9ecb-4c043f1d6588.png)

This is Phaser 2.6.1 but I know the device class hasn't changed for a while, so I doubt 2.5 is much different.

**Comment by hilts-vaughan** [comment]
Is he on a surface or something maybe? We had this problem.

**Comment by photonstorm** [comment]
By default `desktop` is `false`. These are the only 2 checks that change that:

```
        if (device.windows || device.macOS || (device.linux && !silk) || device.chromeOS)
        {
            device.desktop = true;
        }

        //  Windows Phone / Table reset
        if (device.windowsPhone || ((/Windows NT/i.test(ua)) && (/Touch/i.test(ua))))
        {
            device.desktop = false;
        }
```

**Comment by hilts-vaughan** [comment]
Yeah, that last one. :( I'm pretty sure the surface has touch in the user
agent (and any touch screen monitor) but also would have Windows.

**Comment by photonstorm** [comment]
You could argue it's not a _true_ desktop then.

Either way it's easily remedied, use the `Phaser.Device.onInitialized` signal, and modify whatever properties you need to in there, if you need more fine-grained control.

**Comment by fzuleta** [comment]
I am on a surface yes, 
thanks @photonstorm I'll take a look at the signal
