### ISSUE TITLE
Error when loading xml files: Error 406 (Not Acceptable)

### ISSUE THREAD

**Issue by istvan89** [photonstorm/phaser#2670]
Since Phaser 2.6.0 the loading of .xml files gives an error: 406 (Not Acceptable). Versions affected: **2.6.0, 2.6.1 and 2.7.0 Beta 3**
The code in the preload function:
`this.game.load.xml('my_xml_file', 'assets/my_file.xml');`
This worked up to the version 2.5.0.

**Comment by photonstorm** [comment]
I just put together this simple test and it loaded an XML file fine for me. A 404 error is surely a server based error, Phaser itself can't generate that.

```
var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create });

function preload() {

    //  Phaser can load XML files.

    game.load.xml('octopus', 'assets/sprites/octopus.xml');

}

var text;

function create() {

    game.stage.backgroundColor = '#0072bc';

    var xml = game.cache.getXML('octopus');

    console.log(xml);

}
```

**Comment by istvan89** [comment]
Hi,
Thank you for the fast reply. It's a Visual Studio typescript project. The strange thing is that it does not produce the error with Phaser 2.5.0 and below, that's why I thought it could be Phaser related.

**Comment by photonstorm** [comment]
From the docs:

```
    /**
    * Used to map the application mime-types to to the Accept header in XHR requests.
    * If you don't require these mappings, or they cause problems on your server, then
    * remove them from the headers object and the XHR request will not try to use them.
    *
    * This object can also be used to set the `X-Requested-With` header to 
    * `XMLHttpRequest` (or any other value you need). To enable this do:
    *
    * `this.load.headers.requestedWith = 'XMLHttpRequest'`
    *
    * before adding anything to the Loader. The XHR loader will then call:
    *
    * `setRequestHeader('X-Requested-With', this.headers['requestedWith'])`
    * 
    * @property {object} headers
    * @default
    */
    this.headers = {
        "requestedWith": false,
        "json": "application/json",
        "xml": "application/xml"
    };
```

**Comment by istvan89** [comment]
Sorry, I have missed that, because it was working until now. Thank you again!
I guess this issue can be deleted, because it's not an issue actually!:)

**Comment by photonstorm** [comment]
Ok will do. Glad you got it sorted out. I was reluctant about adding in the header support, because I knew it would cause problems like you had, but leaving it out was causing equal problems in other areas too :)
