### ISSUE TITLE
Texture AtlasJSON not working on Chrome on iOS

### ISSUE THREAD

**Issue by Cristy94** [photonstorm/phaser#2678]
I tried bundling all my images into a sprite-sheet, while it works fine on PC and Safari on iOS, opening the game with Chrome on iOS doesn't select the correct sprite from the spritesheet. Everywhere a frame from the atlas is used the **entire atlas** appears.

I load the sprite sheet like this:
`this.load.atlasJSONHash('blocks', 'res/img/blocks/spritesheet.png', 'res/img/blocks/atlas.json');`

It occurs both using the Canvas and the WebGl renderer.
I'm testing on an iPhone 5C, latest iOS (9.3.3).

**Comment by photonstorm** [comment]
The error is with either your texture atlas, or the way it is being served to Phaser. Post it here, or to the forum, and we can probably figure out what it is quite quickly. Texture atlases work fine on iOS, so this isn't a Phaser level issue. Trust me, GitHub would be absolutely brimming with hundreds of issues about this if it was. Plus my own projects would fail on Chrome / iOS, and they don't.

**Comment by Cristy94** [comment]
I tested today and it's working fine, that's odd. I guess there might have been some issues with Chrome on iOS caching stuff even after multiple refreshes or stuff like that.
