### ISSUE TITLE
game.load.setPreloadSprite Issue

### ISSUE THREAD

**Issue by thexbasic** [photonstorm/phaser#2682]
Hi, This Issue is about A bug in the API.

In my Preloader im setting the preloadbar like this (image was loaded before):
`this.loadingBar = Core.PhaserGame.add.sprite(this.world.centerX - 100, this.world.centerY, "preloaderBar");
this.loadingBar.anchor.set(0, 0);
Core.PhaserGame.load.setPreloadSprite(this.loadingBar);`

Afterwards stuff gets loaded and everything is fine. But now I'm in my Login scene and want to load a captcha so I do:
`Core.PhaserGame.load.image("captcha", "http://localhost:63342/PHP/captcha.php?id=" + response.captchaid);
Core.PhaserGame.load.start();`
And in an instant I get the following error: 

`phaser.min.js:14 Uncaught TypeError: Cannot read property 'x' of nullupdateCrop @ phaser.min.js:14updateProgress @ phaser.min.js:20start @ phaser.min.js:20(anonymous function) @ register.js:36xhttp.onreadystatechange @ proto.js:227`

Which is probably due to that the preloadbar is still set to the one of the preloader state (which got destroyed). So the preload image has to be cleaned up after each state change and there should be a manual way setting it to 'null' which wont cause a crash: 

`phaser.min.js:20 Uncaught TypeError: Cannot read property 'width' of nullsetPreloadSprite @ phaser.min.js:20(anonymous function) @ register.js:33xhttp.onreadystatechange @ proto.js:227`

Please excuse my bad english (I'm from germany and just wanna help since this was bugging me for 2 hours now)
I fixxed it temporarily by simply creating a little sprite out of bonds and setting it as preload sprite before I `load.start()` again.

**Comment by photonstorm** [comment]
When Phaser changes State, it calls `Loader.reset`, which definitely removes any preload sprites that have been set, as long as the State it moves in to has a `preload` function. If it doesn't, then it doesn't reset the Loader, as it assumes it isn't required. So if you're creating a manual Loader, and starting it manually (which it sounds like from above), then you need to call `Loader.reset(true)` yourself in your new State, and that will drop any previously set preloader sprites for you.
