### ISSUE TITLE
Options on the separation function in arcade physics collision

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2683]
[feature request]

Please make parameters available to the separation function used in the arcade physics collide method. e.g. how quickly the separation should take place and I'm sure there are other options a separation function might have. I find myself needing to write my own separation function because I can't control basic things like the amount separation on each game loop.

**Comment by hexus** [comment]
Separating a collision over time sounds like quite a specific use case to me. In most cases you'd expect collision solving to completely separate bodies completely as soon as they overlap, right?

Why do you need to separate bodies slowly over a set amount of time, or by a percentage of the overlap each game loop iteration?

**Comment by drhayes** [comment]
Also, have you checked the `customSeparateX` and `customSeparateY` properties? From the docs:

> This flag allows you to disable the custom x separation that takes place by Physics.Arcade.separate. Used in combination with your own collision processHandler you can create whatever type of collision response you need.

**Comment by photonstorm** [comment]
I'm struggling to think of a reason why you'd ever want to not fully separate two objects, but you can already define your own as @drhayes has pointed out above, so I'm happy to close this one off as a feature request already implemented.
