### ISSUE TITLE
crop cannot work with tint in canvas mode

### ISSUE THREAD

**Issue by phoenixyjll** [photonstorm/phaser#2688]
This Issue is about (delete as applicable)

* A bug in the API

For example:

```
    pic = game.add.sprite(0, 0, 'trsi');
    pic.tint = 0x8CA7E9;
    cropRect = new Phaser.Rectangle(100, 100, 128, 128);
    pic.crop(cropRect);
```

The code has different behaviors under CANVAS mode and WEBGL mode. In CANVAS mode, the rectangle's (x, y) doesn't work, and pic is always cropped from its top-left.

As for the Phaser source code,
`renderSession.context.drawImage(this.tintedTexture, 0, 0, cw, ch, dx, dy, cw / resolution, ch / resolution);`
(https://github.com/photonstorm/phaser/blob/dev/src/pixi/display/Sprite.js#L495)

it seems that the crop's cx, cy are always 0.

So should I always not use a tint when I need to crop in canvas mode, or it can be fixed so that it has the same behavior as the WEBGL mode?

Thank you.

**Comment by AleBles** [comment]
Using your example I'm not getting the results you're seeing.

the following code:
```javascript
var sprite = game.add.sprite(20, 20, 'phaser-dude');
sprite.tint = 0x33cc00;
var rect = new Phaser.Rectangle(8, 10, 11, 30);
sprite.crop(rect);
```

Gives me this for WebGL:
![crop_webgl](https://cloud.githubusercontent.com/assets/3883477/17554631/192298ec-5f0c-11e6-8a62-77a0e8619ac9.png)

And this for Canvas:
![crop_canvas](https://cloud.githubusercontent.com/assets/3883477/17554642/1f7e0636-5f0c-11e6-96b1-e65e70643132.png)

**Comment by phoenixyjll** [comment]
Using the Phaser Examples: http://phaser.io/examples/v2/sprites/dynamic-crop#gv, and adding a tint to `pic`:

```
function create() {

    pic = game.add.sprite(0, 0, 'trsi');

    w = pic.width;
    h = pic.height;
    
    pic.tint = 0x33cc00;

    cropRect = new Phaser.Rectangle(0, 0, 128, 128);

    pic.crop(cropRect);

}
```

Under CANVAS mode:

![image](https://cloud.githubusercontent.com/assets/16497885/17611245/2404b746-6078-11e6-9a76-119462fc0b85.png)

And under WEBGL mode:

![image](https://cloud.githubusercontent.com/assets/16497885/17611322/d6eb00d6-6078-11e6-8b9f-72983cedf245.png)

**Comment by phoenixyjll** [comment]
BTW, I'm using Google Chrome 49.0.2623.110 m

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
