### ISSUE TITLE
forceSetTimeOut missing from phaser.d.ts IGameConfig

### ISSUE THREAD

**Issue by AlvaroBarua** [photonstorm/phaser#2689]
The forceSetTimeOut boolean is missing from the IGameConfig definition. 
I'm opening this issue because while working for a client we had to disable the request animation frame and using the raf property of the game class didn't work. I added the boolean into the IGameConfig and everything worked perfectly, so this is either a bug with the raf property or just a simple slip.

Bests 
Alvaro.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by McBits** [comment]
Hi, I stumbled upon this while looking for a description of what forceSetTimeOut does, since it's the only IGameConfig property that's not marked optional. Should it be optional? It looks like the only place it's used would work the same when it's undefined.

**Comment by AlvaroBarua** [comment]
It should be optional, as before the commit with the fix it was undefined by default, it should not affect functionallity.
