### ISSUE TITLE
How do I install Ubuntu?

### ISSUE THREAD

**Issue by kholyphoenix1** [photonstorm/phaser#2690]
Hello, 

How do I download and install on Ubuntu?

Thank you!

**Comment by Cristy94** [comment]
You can install through Node.js, which runs on Ubuntu:
https://github.com/photonstorm/phaser#bower--npm

Or you could simply download the phaser.js file from the [cdn](https://cdnjs.com/libraries/phaser).

**Comment by kholyphoenix1** [comment]
I compiled it.
How do I open the application?

**Comment by Cristy94** [comment]
See this tutorial: http://phaser.io/tutorials/getting-started

**Comment by kholyphoenix1** [comment]
Ahhh, thanks !!
