### ISSUE TITLE
Adding a Phaser.ProgressBar Plugin

### ISSUE THREAD

**Issue by JTronLabs** [photonstorm/phaser#2695]
I think that a Progress Bar/Health Bar is an integral part of most games. I would say even more so than the current Plugin, Phaser.Weapon (as it would be useful in loading screens, timer countdowns, health display, etc).  Currently, if someone wants a health bar they might do some googling and come across this [repo](https://github.com/bmarwane/phaser.healthbar). I did this, and in the course of developing my game have had to [greatly expand this bar to fit my needs](https://github.com/JTronLabs/Space-Shooter-Phaser/blob/master/src/objects/UI/ProgressBar.js). 

I've added an outline, centered text, the ability to modify colors, ability to use thresholds for color changes, updated to ES6, etc. I'm not finished though. Some other potential changes include: making it possible to set an arbitrary image as the bar (tried this but had issues with cropping), making it a Phaser.Group instead of a generic class, adding Plugin integration, etc.

If I finish improving and documenting it, would it be a good idea to add it in as a default Plugin in Phaser's src via a Pull Request?

Or perhaps add to the [plugin repo](https://github.com/photonstorm/phaser-plugins/blob/master/ScreenShake/ScreenShake.js)

**Comment by JTronLabs** [comment]
What the bars currently look like

![14037962_10210498642927277_668556910_o](https://cloud.githubusercontent.com/assets/7429786/17738674/e996fea0-6457-11e6-8a64-3f19396d2a78.png)

**Comment by Cristy94** [comment]
I think health bars are really easy to implement, simply draw two sprites on top of each other and crop one of them. I don't know if having a plugin for health bars would reduce the amount of code you have to write, considering that you also have to customize the look of your health bar.

**Comment by JTronLabs** [comment]
True it's not the most difficult thing ever, but I think that would make it a perfect candidate for a default plugin. It would provide a well-coded example for beginners to learn from, and a more feature rich bar than what the average person would make on their own. It would make it so everyone can do things like having colors that change upon the progress, using an outline sprite, shrinking the bar in different directions, using rounded rectangles or images, text overlay, etc. 

Also, Math.sign and Math.abs are very simple functions, but JS provides these for free to improve code readability and to preemptively squish bugs for its users. If millions of people code in JS, some of them will mess up these simple things if they had to implement it themselves. Same goes for a progress bar. I've spent an embarrassing amount of time trying to get this one right, and I'm still not finished with it. I believe there's twice as much need for it, as the current most widely used solution, [this repo](https://github.com/bmarwane/phaser.healthbar), does not extend Phaser.Group. This makes the code overly complicated: it re-implements a lot of stuff like setPosition or isFixedToCamera, that Phaser.Group gives you for free (and I don't think it is maintained any more). I think Phaser users want to make games, not health bars. And I think there would be more demand for it than the current included plugin, Phaser.Weapon (which is an awesome BTW).

**Comment by JTronLabs** [comment]
Since this hasn't gotten much interest, I think I'll submit a request to a plugin repo, or perhaps work on a UI related repo
