### ISSUE TITLE
Don't understand how world works

### ISSUE THREAD

**Issue by Jerkoco** [photonstorm/phaser#2698]
Hi ! 
I don't understand how stage, camera and world works (I tried to read the doc and the code).

How Phaser process entities in the game. If I decide an entity is somewhere in the world, and the camera can't see it, how phaser decide what entities are going to be updated and rendered, and what entities shouldn't ?

Thanks a lot.

**Comment by photonstorm** [comment]
All entities are updated and rendered, every frame, no matter where in the world they are.

You can tell an entity to stop rendering if out of the camera bounds by setting `autoCull = true` on a Sprite (or anything with the InWorld component). You can tell it to kill itself if out of the camera bounds with `outOfCameraBoundsKill = true`, or out of the world bounds with `checkWorldBounds = true` combined with `outOfBoundsKill = true`.

For any follow-up questions please use the forum. I prefer to keep GitHub issues for actual issues.
