### ISSUE TITLE
alphaMask removes transparency from the texture being masked

### ISSUE THREAD

**Issue by ulitiy** [photonstorm/phaser#2707]
* A bug in the API

https://gist.github.com/ulitiy/a82ba7e966544893cbbd3222b113a1b4

1. When I create a first gradient - it works good - transparent-blue-transparent.
https://www.dropbox.com/s/k0xxaum8v489gh1/Screenshot%202016-08-20%2003.59.30.png?dl=0
2. But when I apply mask on it - transparent from the first step becomes white
https://www.dropbox.com/s/dldgix5sa5ffs68/Screenshot%202016-08-20%2003.58.23.png?dl=0

Is it an expected behaviour? Can I mask the semitransparent image somehow?
Thanks.

**Comment by photonstorm** [comment]
The mask is drawn over the BitmapData canvas using the blend mode `source atop`, this is responsible for what is happening - although it doesn't remove alpha:

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

If you need a different result (via a different blend mode), then I'd recommend taking a quick look at the `alphaMask` method. You'll see it's just a couple lines of code, and creating your own variation shouldn't take long at all.
