### ISSUE TITLE
Arcade.Body#rotation, #preRotation should be initialized from Sprite#angle, not Sprite#rotation

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#2708]
[Arcade.Body copies these from `sprite.rotation`](https://github.com/photonstorm/phaser/blob/dev/src/physics/arcade/Body.js#L85), but that's incorrect.

They should be copied from `sprite.angle`, [as in Arcade.Body#preUpdate](https://github.com/photonstorm/phaser/blob/dev/src/physics/arcade/Body.js#L595).

This Issue is about

* A bug in the API

**Comment by photonstorm** [comment]
It doesn't functionally make any difference, as it's replaced immediately via `preUpdate` anyway, but you're right, it should use that value instead, so I've fixed it in dev.

**Comment by samme** [comment]
I figured as much, but thanks. :)
