### ISSUE TITLE
[Docs Error] Phaser.Group's width and height

### ISSUE THREAD

**Issue by JTronLabs** [photonstorm/phaser#2709]
This Issue is about (delete as applicable)

* An error in the documentation

 If you try to set Phaser.Group's width or height, you'll fail, google it, and come across this [thread](http://www.html5gamedevs.com/topic/10540-can-i-set-the-group-width/). As far as I know, it is a variable that can only be set internally, based upon the farthest separated items inside of it. Despite that, the docs read

> The width of the displayObjectContainer, setting this will actually modify the scale to achieve the value set

I propose setting it to something like:

> Read-only variable derived from what is inside of this Phaser.Group. Width is the difference of the right most child's right and the left most child's left.

> Read-only variable derived from what is inside of this Phaser.Group. Height is the difference of the bottom most child's bottom and the top most child's top.

I believe the file to change is [DisplayObjectContainer](https://github.com/photonstorm/phaser/blob/v2.6.1/src/pixi/display/DisplayObjectContainer.js), as that is refenced in Group's [width](http://phaser.io/docs/2.6.1/Phaser.Group.html#width). Since it is inherited though, I don't know if it will mess up any other docs.

**Comment by JTronLabs** [comment]
bump

**Comment by photonstorm** [comment]
`Group.width` is the calculated width, in pixels, is read. If you set it, it adjusts the scale (like the docs say). Here's a little test case to show what I mean:

```

var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create, render: render });

var group;

function preload() {

    game.load.image('block', 'assets/sprites/32x32.png');
    
}

function create() {

    group = game.add.group();

    //  Create a 200x100 sized Group, with 2 sprites in the top-left and bottom-right corner
    group.create(0, 0, 'block');
    group.create(168, 68, 'block');

    //  Set Group dimensions x2
    group.width = 400;
    group.height = 200;

}

function render() {

    game.debug.text('width: ' + group.width, 0, 400);
    game.debug.text('height: ' + group.height, 0, 432);

}
```

**Comment by JTronLabs** [comment]
Yeah IDK what I was thinking. Must've been a bug I was running into. Sorry for the issue, thank you for the code snippet!
