### ISSUE TITLE
[Feature Request] - Phaser.Group - add a sprite in a group during his construct

### ISSUE THREAD

**Issue by TokiDEV** [photonstorm/phaser#2711]
Well, I am actually developping a game with Phaser.js framework. Due to optimisation issues, I decided to use Arcade instead of P2 physics. However, in P2 I used collision groups, which are not available in Arcade.

My idea was to use simple groups, but when I want to add a sprite in these, this doesn't go well ; when I do a console.log of the group children, I've got this return, given that each console.log is made by another entity of my class.

![issue](https://cloud.githubusercontent.com/assets/18354939/17857620/b8364094-6882-11e6-8247-923f93a46b2d.png)

Short example code : 
```
var Dude = function (gameState) {
    Phaser.Sprite.call(this, gameState, Math.random()*1500, Math.random()*200, 'dude');
    gameState.physics.enable(this, Phaser.Physics.ARCADE);
    gameState.dudeGroup.add(this);
    console.log(gameState.dudeGroup.children);
};

Dude.prototype = Object.create(Phaser.Sprite.prototype);
Dude.prototype.constructor = Dude;


var GameState = function(){
    this.game = new Phaser.Game("100%", "100%", Phaser.AUTO, 'mainContainer');
    this.game.state.add("Game", this, true);
};

GameState.prototype.preload = function() {
    this.load.image('dude', 'http://examples.phaser.io/assets/sprites/phaser-dude.png');
};

GameState.prototype.create = function() {
    this.dudeGroup = this.add.group();

    for (var i = 0; i < 10; i++) {
        this.add.existing(new Dude(this));
    }
};

var game = new GameState();
```

Is there any way to include this possibility or may be a collision group for arcade ?

**Comment by photonstorm** [comment]
I'm not going to add collision flags to Arcade Physics I'm afraid.

As to your second point, I'm not entirely sure I understand. You want a Sprite to be a child of a Group as soon as it's created? In that case use `group.create()` instead, or if you need the group to create a specific class type, you can do `group.classType = Dude`, then any calls to `group.create` will create `Dude` objects instead.

**Comment by TokiDEV** [comment]
Thank you, I will try the group.classType. After the issue open I used a setTimeOut of 50ms to the .add expression and was quite confused that it actually worked.
