### ISSUE TITLE
Rendering tilemap layer to textures, unable to apply translation / camera offset

### ISSUE THREAD

**Issue by Refeuh** [photonstorm/phaser#2713]
Hi !

This Issue is about :
- Possibly a bug if this is supposed to work
- Possibly a feature request if this is currently unsupported

I am rendering tilemap layers to textures, but I have issues applying a "camera" offset to get the correct area of the layer to appear in the texture.

Tested on the latest release v2.6.1 ; I haven't seen any relevant changes in the dev-branch log.

If the context is important :
The goal is to do some post-processing using the rendertexture, including custom shader up-scaling. The rendering pipeline is fairly typical : render everything to textures, and draw a simple sprite with the effects for the final display.
The actual world/scene is only made of 1 single sprite covering the entire game window and displaying the content of the rendertexture. All display objects (sprites, tile layers, etc.) are rendered into the render texture and are not added to world/scene. The game/world camera is static (0, 0). Only the content of the rendertexture is updated to reflect the player moving around. (, etc.)

My problem is that I can't seem to find the right combination of layer/rendering parameters to get the correct area of layer to render into the texture. Since my game camera isn't actually moving, I am setting the layer cameraoffset attribute manually, but this has no effect.

I've created a minimal test scene that demonstrates the problem in the Phaser Sandbox :
[code sample](http://phaser.io/sandbox/edit/weeeaLZy)

Either I'm using it correctly, and there's a bug somewhere when rendering tile layers to textures, or I'm not using things right and this could use some extra documentation.

The only relevant topic/example I found is this demo : http://phaser.io/examples/v2/display/render-texture-tilemap , doing a manual layer render by processing all the tiles one at a time. Which I'd really like to avoid, because of massive drawcalls overhead.

I've tried lots of things, cropping, render offset, etc. so far nothing gave the expected result :-?

Any help to get this working and/or setup properly would be greatly appreciated :)

Regards

**Comment by hexus** [comment]
When rendering to a render texture, you need to provide a matrix object that determines the transformation of the display object to render, even if this is just translation. While I've had less luck with the scaling values, the translation values worked fine for tilemaps (nested in groups) for me.

**Comment by Refeuh** [comment]
Thanks for the input, I'll try that next ! So I guess using the rendertexture.render(displayobject, matrix, ...) function instead of renderXY, AND leaving the layer.cameraoffset to (0, 0). That sounds promising ! At least it's one combination I haven't tried yet :D

**Comment by hexus** [comment]
Yeah, though I'm doing this with the layers added to the world, and an active camera. I use the camera coordinates to govern the translation values for the matrix for `renderTexture.render(object, matrix)`.

**Comment by Refeuh** [comment]
Well as you guess it doesn't fully work - though it seems to be a step in the right direction ! I've updated the code sample to use a translation matrix for the render() parameter

http://phaser.io/sandbox/edit/bhjtPcPh

But it seems the translation happens AFTER the display/crop, therefore it shows black" all around the initial layer screen, instead of the correct content of the layer.

I understand why tile layers need to be more complicated than other simpler display objects, but surely there's a way to render to texture without having to rewrite a full renderer :-?

**Comment by hexus** [comment]
Yeah, I've been slowly building up my understanding of all of this but my knowledge stops short when it comes to how exactly tilemap layers work and why they need to be a part of the world.

It would be nice if more of this behaviour could be potentially controlled by the developer.

**Comment by Refeuh** [comment]
Quick update -

In the absence of a functional solution and/or work-around, I have re-classified this issue as a "bug" or "feature request" (if currently unsupported)

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
