### ISSUE TITLE
setTileIndexCallback Makes Tile passable

### ISSUE THREAD

**Issue by anthkris** [photonstorm/phaser#2714]
This Issue is about (delete as applicable)

* A bug in the API

I've checked the dev log and the HTML5 Game forum. There were several folks with questions about this but no answers that I could find. The setTileIndexCallback works but makes the tile passed in pass-through. It's unclear whether or not this is working as designed.

To reproduce, create a tileset with collision and then use setTileIndexCallback on a tile. A player sprite that overlaps with that (previously solid) tile will now fall through.

The current workaround is to create a physics.arcade.collide statement in update instead.

(Love Phaser!!)

**Comment by hexus** [comment]
Try returning `true`.

https://github.com/photonstorm/phaser/blob/v2.6.1/src/physics/arcade/TilemapCollision.js#L155

**Comment by anthkris** [comment]
Thanks so much @hexus ! That worked brilliantly! I see that you linked to the code. Is this need to return true in the docs? Did I miss something?

**Comment by hexus** [comment]
Hmm, if it's not specified in the documentation then perhaps it should be. Process callbacks, like tile callbacks, need to return `true` to allow separation to continue. They return `false` if they handled the collision themselves or don't separation to continue.
