### ISSUE TITLE
Phaser.Weapon#fireRateVariance without effect

### ISSUE THREAD

**Issue by noseglid** [photonstorm/phaser#2715]
First off, thanks for an awesome game engine. I've just recently started using it and made so much progress in so short time due to the great examples and documentation as well as the very flexible but extensive framework!

This Issue is about (delete as applicable)

* A bug in the API

Setting `fireRateVariance` does not have any effect.

I've tracked the error to when [_nextFire in the weapon plugin is set](https://github.com/photonstorm/phaser/blob/v2.6.1/src/plugins/weapon/WeaponPlugin.js#L872). I'm guessing this needs some similar treatment as with the [bulletSpeedVariance](https://github.com/photonstorm/phaser/blob/v2.6.1/src/plugins/weapon/WeaponPlugin.js#L716).

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by noseglid** [comment]
Wow, quick turnaround!
👍
