### ISSUE TITLE
UX/SEO improvement to the documentation

### ISSUE THREAD

**Issue by JTronLabs** [photonstorm/phaser#2721]
This Issue is about (delete as applicable)

* An error in the documentation

Let's say you are a total Phaser beginner, and want to learn what a Group can do, so you turn to Google.

![selection_023](https://cloud.githubusercontent.com/assets/7429786/18028676/d19fb30a-6c4a-11e6-97c1-b86b6fa5f1d3.png)

All of the links lead to old documentation! That's okay you think, as there are options in the top left to view the newest docs. But you're a noob and don't know that, so you use the old docs. Maybe you click around, get lucky, and find a newer version.

![selection_025](https://cloud.githubusercontent.com/assets/7429786/18028705/1e66d8b2-6c4b-11e6-8fd9-16c4daca4b11.png)

Nowhere on the screen does it say it's outdated. In fact, it looks quite the opposite with the official looking 2.4.4 on the left-hand side. Even for more experienced devs it can be difficult. Usually when I am searching I go straight to Ctrl-F or check props/methods before I look at the version #. Part of that is I need to change my workflow, part of that is a UX experience that could be improved. The extra clicking to get to the most recent version from Google is also annoying.

I think it would be really nice if there could be a working http://phaser.io/docs/current/Phaser.Group.html, and I believe such a link might improve SEO and make it rise to the top of results(after it gets a ton of links/clicks). At the present time, http://phaser.io/docs/current works and takes you to the docs for the most recent version.

On top of/in place of that, I think there really needs to be something that alerts the user to a more updated version. Preferably something clickable to take you to docs/current/$MY_PAGE. Or at least an indicator of some sort.

![selection_025](https://cloud.githubusercontent.com/assets/7429786/18028759/1859edc8-6c4c-11e6-834d-117a911d6fe5.png)

**Comment by JTronLabs** [comment]
Cordova is a good example of what I'm talking about

![cordova-old](https://cloud.githubusercontent.com/assets/7429786/18514051/9e3a2464-7a55-11e6-816c-a6046292b4b6.PNG)


![new](https://cloud.githubusercontent.com/assets/7429786/18514029/88726fba-7a55-11e6-9478-32cf5daaa485.PNG)

**Comment by JTronLabs** [comment]
Looks awesome, great job! Was the docs/latest/... implemented too?

![selection_002](https://cloud.githubusercontent.com/assets/7429786/19023219/7fd98e76-88ae-11e6-95c6-e20845b7c1d2.png)

**Comment by photonstorm** [comment]
Not yet, but I think the warning will do for now, cheers.
