### ISSUE TITLE
Switching states while Phaser.autofire is on causes a crash

### ISSUE THREAD

**Issue by JTronLabs** [photonstorm/phaser#2725]
This Issue is about (delete as applicable)

* A bug in the API

Example
```
      var weapon = this.game.add.weapon(30);
      weapon.autofire = true;
      this.game.state.start('GameOver' ); //ERROR!
```

Trace
```
//error occurs here in Phaser.Group.add
this.game.physics.enable(child, this.physicsBodyType);
```
![selection_028](https://cloud.githubusercontent.com/assets/7429786/18030208/aed42eea-6c73-11e6-995e-5512ed584d92.png)

My hypothesized source:

```javascript
Phaser.Weapon.prototype.update = function () {

    //...stuff...

    if (this.autofire)
    {
        this.fire();
    }

};
```

I suspect the update function continues to run even after the state has changed. Autofire is set to true, fire() is called, eventually down the stack something breaks.

**Comment by samme** [comment]
The trace suggests `this.game` is undefined, but that's weird; `game` should always be defined even when changing states.

**Comment by JTronLabs** [comment]
I know right? Hopefully it's not my code that is messing it up. Anyone want to corroborate this?

**Comment by JTronLabs** [comment]
Attempting to create a [non-biased example shows that it is working fine](http://jsfiddle.net/hnLthack/14/). IDK what is going on with my code. I'll try to figure it out and update later.

**Comment by JTronLabs** [comment]
Still haven't found the answer, will update/re-open when I do.

**Comment by samme** [comment]
I think you also need `weapon.autoExpandBulletsGroup: true` to see this error.

**Comment by JTronLabs** [comment]
[Wow nice!! Thanks man, good find!](http://jsfiddle.net/hnLthack/16/)

**Comment by photonstorm** [comment]
You are responsible for tidying-up plugins, and any of the other countless things that you could have done in a game state, during the states `shutdown` method. It's there for last-minute house-keeping, object nulling, reference clearing, etc. And that's definitely what this falls in to.

Calling `destroy` on any Weapon instance you've created will be enough. If it isn't, then feel free to re-open as a bug that needs fixing. But looking quickly at the destroy code, I'm pretty sure it will work fine.

**Comment by JTronLabs** [comment]
Thanks Rich! Since weapon is a default plugin, is there any way we could include this behavior by default for future users?

**Comment by photonstorm** [comment]
Hmm, sort of, it would require a new plugin level property along the lines of `ignoreDestroy`, so for cases where you want a single Weapon plugin shared across states, it didn't nuke it as soon as the state changed (which is how I tend to use it). Plugins never automatically destroy themselves on state change, so if Weapon did it, it'd be specific to that one alone. Definitely worth adding to the docs though.

**Comment by JTronLabs** [comment]
I can update weapon's docs in PR https://github.com/photonstorm/phaser/pull/2730. 

Side question. My commit https://github.com/photonstorm/phaser/pull/2730/commits/f1a7976d83c92843c10dfaaaf6db42d976439640 in that PR got kinda borked somehow, Git things code changed that didn't actually change. Should I redo the PR or is that alright?

**Comment by photonstorm** [comment]
Yeah I use the Weapon plugin in a shmup where I have a single instance, in a global (non-State) location, and just clear-down the bullets group on each state change, but keep everything else the same (bullet count, last shot timer, etc). This will be even more important when we add parallel state / non-destructive states. For now though, let's update the docs for `autoFire`, and maybe in the class description too. That's an easy to merge change.

**Comment by JTronLabs** [comment]
I think what happened is the JS file was [Beautified](https://atom.io/packages/atom-beautify)

**Comment by photonstorm** [comment]
Makes sense. And, please don't :)

**Comment by JTronLabs** [comment]
Can I ask what you mean by this? 

>  I have a single instance, in a global (non-State) location, and just **clear-down** the bullets group on each state change...

Also, how do you manage having a ton of guns? Where each enemy has a gun, and the player could have a dual, tri, quad, and so one shot weapon? I can imagine setting up a class specifically to manage Weapon pooling, and then just assigning multiple guns where a dual shot is needed?

**Comment by JTronLabs** [comment]
I appreciate you taking my issue seriously and deprecating [Phaser3](https://github.com/photonstorm/phaser3) by the way! It's nice to have an impact on these big projects.
