### ISSUE TITLE
Yoyo not supported for scale

### ISSUE THREAD

**Issue by smks** [photonstorm/phaser#2726]
This Issue is about yoyo not being applied when targeting the scale object of a sprite. I can see setting position on sprite is not an issue for yoyo.

* A bug in the API

        this.circle = this.game.add.sprite(0, 0, 'sprites', 'blue-sphere.png');
        this.circle.anchor.set(0.5, 0);
        this.circle.inputEnabled = true;
        this.circle.input.enableDrag(false, false, true, 1, new Phaser.Rectangle(419, 190, 257, 0));
        
        this.pulseScaleTween = this.game.add
            .tween(this.circle.scale)
            .to( { x: 1.2, y:1.2 }, 50, 'Linear', true, 0, -1);

        this.pulseScaleTween.yoyo(true, 10);

**Comment by samme** [comment]
It seems to work correctly: http://codepen.io/anon/pen/dpPrjv

**Comment by JTronLabs** [comment]
Was your circle already at scale 1.2?

**Comment by photonstorm** [comment]
The codepen from @samme shows this working, so unless you can share a fully running code sample that demonstrates otherwise, I'm going to close this one off.
