### ISSUE TITLE
Raycasting demo still doesn't work

### ISSUE THREAD

**Issue by darkf** [photonstorm/phaser#2733]
[This official demo](http://phaser.io/examples/v2/box2d/raycasting) is broken (the line is never detected as intersecting), despite it being a paid, commercial plugin.

This issue went ignored on the forums, so let's try the actual issue tracker and maybe something can get done about it, huh?

**Comment by photonstorm** [comment]
This works fine with Phaser 2.6.2 (and various versions prior to that), it just doesn't work in the js-scrambled version of Phaser with Box2D built-in that is used on the site (which is pretty old now)

Nothing needs fixing in the plugin itself, or the example, just use a recent version of Phaser and it'll work fine. I'll update the site when I get a chance, but it's not important enough to have an Issue lingering open for.
