### ISSUE TITLE
Bug - Wrong sprite picking in scrollable area

### ISSUE THREAD

**Issue by rfatkullin** [photonstorm/phaser#2734]
I have problem with sprite picking. If put phaser canvas in scrollable div and click on different parts of canvas, Phaser picks wrong sprite.
Here are my code: http://codepen.io/anon/pen/RGwBKZ
Steps to reproduce:
     1. Click on the first sprite.
     2. Quick scroll to the middle or the bottom of scrollable area.
     3. Click on the sprite.
     4. Phaser pick wrong sprite.

**Comment by photonstorm** [comment]
It can't calculate the offset needed to accurately map it to the canvas, and it's not something that will be added in either. So you'll need to figure out some way of doing it, and overriding the internal methods to compensate for that. Or just don't put it in a scrollable div of course.
