### ISSUE TITLE
phaser-minimum.js games fail to start (error evaluating `this.fx.clear`) 

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#2738]
http://codepen.io/anon/pen/vXYooK

`camera.reset` or `camera.resetFX` should probably check `camera.fx != null` (as when Phaser.Graphics is excluded).

This Issue is about

* A bug in the API

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `dev` branch, and attributed the work to you in the README. If you need to tweak the code for whatever reason, please submit a new PR.

**Comment by djom20** [comment]
Is solved this error?

**Comment by photonstorm** [comment]
Like it says above, it's fixed in the dev branch.
