### ISSUE TITLE
Error when trying to destroy video.

### ISSUE THREAD

**Issue by Tetley** [photonstorm/phaser#2740]
This Issue is about (delete as applicable)

* A bug in the API

API errors must include example code showing what happens, and why you don't believe this is the expected behavior. Issues posted without code take _far_ longer to get resolved, sometimes not ever.

Here is a slightly modified version of this example http://phaser.io/examples/v2/video/dolby-digital-plus#gv

I'm getting this error when I try to destroy the video.

Uncaught TypeError: Cannot read property 'paused' of null

```
var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create });

function preload() {
    game.add.text(100, 100, "Loading videos ...", { font: "65px Arial", fill: "#ff0044" });

    game.load.video('dolby', 'assets/video/MP4_HPL40_30fps_channel_id_51.mp4');
}

var video;

function create() {

    video = game.add.video('dolby');
    video.play(true);
    //  x, y, anchor x, anchor y, scale x, scale y
    video.addToWorld(400, 300, 0.5, 0.5, 0.5, 0.5);
    setTimeout(function(){
        video.destroy();
    },5000);
}
```

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
