### ISSUE TITLE
Uncaught ReferenceError: begin is not defined when using removeChildren

### ISSUE THREAD

**Issue by alex-espinoza** [photonstorm/phaser#2741]
This Issue is about

* A bug in the API

I am upgrading from Phaser 2.4.8 to 2.6.2, using Chrome 52.

When attempting to use the `removeChildren` method, an `Uncaught ReferenceError: begin is not defined error` is being thrown.

Example: http://phaser.io/sandbox/LGcoNJob

**Comment by alex-espinoza** [comment]
It looks like this bug was introduced in commit  https://github.com/photonstorm/phaser/commit/b69cae420642ad9c5fb05a64e09175425670755f on line 264 to 270.

The `begin` variable was changed to `beginIndex` and an old reference to `begin` still exists on line 270. Changing the variable name fixes the bug. I've included a pull request with the fix. :)

**Comment by suranyami** [comment]
👍

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `dev` branch, and attributed the work to you in the README. If you need to tweak the code for whatever reason, please submit a new PR.

**Comment by iamchristopher** [comment]
@photonstorm When do you think this will be released?

**Comment by photonstorm** [comment]
You can find a 2.7 release with the fix in here: https://github.com/photonstorm/phaser/tree/2.7

**Comment by iamchristopher** [comment]
@photonstorm Thank you! I'm currently running a CDN version of 2.6.2 (https://cdnjs.cloudflare.com/ajax/libs/phaser/2.6.2/phaser.js) and didn't realize 2.7 was floating around.

**Comment by photonstorm** [comment]
It's not really, it's a special build for a select few devs who needed it, which is why it's not on the CDN or web site.

I ran a survey in the last issue of the newsletter if I should release 2.7 or just carry on with 3.0, and 72% said to carry on with 3.0, so I am, but the 2.7 build is there for anyone who wants it.
