### ISSUE TITLE
Phaser.Math.getShortestAngle is not on typings definitions

### ISSUE THREAD

**Issue by StealthC** [photonstorm/phaser#2747]
The function works well but is not present in the updated typings definitions, giving the error: 

'TS2339: Property 'getShortestAngle' does not exist on type 'typeof Math'.'

**Comment by JTronLabs** [comment]
I think these are the TS defs. https://github.com/photonstorm/phaser/blob/dev/typescript/phaser.d.ts#L2559

**Comment by StealthC** [comment]
Yes, exactly the file I am using, it doesn't have the definition of "getShortestAngle" in the Phaser.Math class, maybe it was missed on the last update.

The other new feature of version 2.6.2 "rotateToAngle" have its definition on line 2604.
[https://github.com/photonstorm/phaser/blob/dev/typescript/phaser.d.ts#L2604](https://github.com/photonstorm/phaser/blob/dev/typescript/phaser.d.ts#L2604)

It's only a minor issue, does not break any functionality.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
