### ISSUE TITLE
Adding audio once and attempting to use onStop >1 times causes a crash

### ISSUE THREAD

**Issue by JTronLabs** [photonstorm/phaser#2748]
This Issue is about (delete as applicable)

* A bug in the API
* A problem with my own code

This is probably intended behavior, but I wanted to bring it up in case it is not known. [The HTML5 post here explains it well. ](http://www.html5gamedevs.com/topic/9650-sound-signal-onstop/#comment-143169)

**Comment by photonstorm** [comment]
You're creating an anonymous function, and passing it to a Signal via `add` which means "call this function _every single time_ this Signal is dispatched", and it never gets cleared up. So it's an accumulative snowball. Ideally you don't bind an anonymous function, or if you must, use `addOnce` instead, so at least it gets removed internally once invoked.

If you think the error is something else, post a full code sample showing it please.
