### ISSUE TITLE
Arcade Physics setCircle is bugged when using a scale on the Sprite

### ISSUE THREAD

**Issue by ColaColin** [photonstorm/phaser#2752]
This Issue is about
- A bug in the API

So [before](https://github.com/photonstorm/phaser/issues/2750)  I was confused about how the scaling works, and I have fixed that now in my code. Rectangles work fine now. The circles however do not.

After fiddeling a bit I think that there is a problem with how the radius is handled. Some parts of the code assume it is scaled, some don't. The result is something like this:
- The size of the circle is correct if you don't scale the passed in radius
- The offsets are better (not sure if correct) if the passed in radius is scaled.
- I found that the best result I can get, that works reasonably well as long as the involved sprites are not too big is this:
  
  ```
          part.body.setCircle(hitbox.size.radius * part.scale.x,
                  hitbox.size.offsetX / part.scale.x,
                  hitbox.size.offsetY / part.scale.x);
          part.body.radius = hitbox.size.radius;
  ```
  
  That looks somehow wrong to me, something has to be amiss.

Looking at the code I think I have some idea what the problem is.

In [setCircle](https://github.com/photonstorm/phaser/blob/v2.6.2/src/physics/arcade/Body.js#L1108) the radius is directly copied over from the parameters. However a few lines down you can see that this.center is set based on the position and the halfwidth. Halfwidth is based on width, which is based on the scaled radius. So center is in scaled coordinates.

But I can find at least two places where the center position and the radius value are added together:

https://github.com/photonstorm/phaser/blob/v2.6.2/src/physics/arcade/Body.js#L814

https://github.com/photonstorm/phaser/blob/v2.6.2/src/physics/arcade/Body.js#L1178

Debug drawing also mixes the center position and the radius value when drawing:
https://github.com/photonstorm/phaser/blob/v2.6.2/src/physics/arcade/Body.js#L1445

Since these two values basically are in different coordinate systems the results are erratic.
The issue seems to still exist in the dev tree as well, at least the code looks the same there.

Here is a new sandbox example. The rectangle works fine after dividing by the scale, the circle not. Can you get the circle to be correct somehow there?

http://phaser.io/sandbox/qAbuKdDO/play

**Comment by Arcanorum** [comment]
Definitely broken. I modified http://phaser.io/examples/v2/arcade-physics/circle-body where you can see this more clearly.

```javascript
var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create, update: update, render: render });

function preload() {

    game.load.image('wizball', 'assets/sprites/wizball.png');
    game.load.image('disk', 'assets/sprites/copy-that-floppy.png');

}

var ball1;
var ball2;
var disk;

function create() {

    game.physics.startSystem(Phaser.Physics.ARCADE);

    disk = game.add.sprite(80, 0, 'disk');
    ball1 = game.add.sprite(100, 240, 'wizball');
    ball2 = game.add.sprite(700, 240, 'wizball');
    
    ball1.scale.setTo(2);
    ball2.scale.setTo(0.5);
    disk.scale.setTo(2);

    //  rect corners collide, but circles don't
    // ball2.x = 280;
    // ball2.y = 220;

    //  circles collide
    // ball2.x = 260;
    // ball2.y = 140;

    //  disk rect NOT collide with ball1, and is out of its bounds
    // disk.x = 320;
    // disk.y = 380;

    //  disk rect NOT collide with ball1, but is within its bounds
    // disk.x = 280;
    // disk.y = 380;

    //  disk rect WILL collide with ball1
    // disk.x = 270;
    // disk.y = 370;


    // game.physics.arcade.enable([ball1, ball2]);
    game.physics.arcade.enable([disk, ball1, ball2]);

    //  By default the Body is a rectangle. Let's turn it into a Circle with a radius of 45 pixels

    ball1.body.setCircle(45);
    ball2.body.setCircle(45);

    // ball1.body.immovable = true;
    // ball2.body.mass = 3;

    //  Set the ball to collide with the world, have gravity, bounce, and move.
    ball1.body.collideWorldBounds = true;
    ball2.body.collideWorldBounds = true;
    disk.body.collideWorldBounds = true;

    ball1.body.bounce.set(1);
    ball2.body.bounce.set(1);
    disk.body.bounce.set(1);

    ball1.body.gravity.y = 100;
    ball2.body.gravity.y = 100;
    disk.body.gravity.y = 100;

    // ball1.body.velocity.x = 50;
    // ball2.body.velocity.x = -50;

    ball1.body.velocity.set(150);
    ball2.body.velocity.set(-200, 60);
    disk.body.velocity.set(50);

    // game.input.onDown.add(function() { console.log(game.physics.arcade.intersects(ball1.body, ball2.body)); });
    // game.input.onDown.add(function() { console.log(game.physics.arcade.intersects(ball1.body, disk.body)); });

}

function update () {

    game.physics.arcade.collide(ball1, ball2);
    game.physics.arcade.collide(ball1, disk);
    game.physics.arcade.collide(ball2, disk);
    
}

function render () {

    game.debug.body(disk);
    game.debug.body(ball1);
    game.debug.body(ball2);

}
```

**Comment by samme** [comment]
<http://codepen.io/anon/pen/ORpvjd?editors=0010>

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
