### ISSUE TITLE
UUID should be of type string in the typedefs

### ISSUE THREAD

**Issue by nickdbush** [photonstorm/phaser#2754]
In the RandomDataGenerator class the return type for the ```uuid()``` function is ```number```. However, as per the JSDoc, it returns a string:

```
/**
* Returns a valid RFC4122 version4 ID hex string from https://gist.github.com/1308368
* @return A valid RFC4122 version4 ID hex string
*/
uuid(): number;
```
should be
```
/**
* Returns a valid RFC4122 version4 ID hex string from https://gist.github.com/1308368
* @return A valid RFC4122 version4 ID hex string
*/
uuid(): string;
```

I'm in the middle of creating a pull request to fix this definition.

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
