### ISSUE TITLE
Phaser.Math minor docs error & potential improvements

### ISSUE THREAD

**Issue by JTronLabs** [photonstorm/phaser#2758]
This Issue is about (delete as applicable)

* An error in the documentation
![selection_037](https://cloud.githubusercontent.com/assets/7429786/18498905/fd701390-79ff-11e6-9535-7ef126710d54.png)

http://phaser.io/docs/2.6.2/Phaser.Math.html#between

**Comment by JTronLabs** [comment]
probably should add the keyword 'Random' in there too

**Comment by JTronLabs** [comment]
I recommend `Returns a random integer between min and max values (inclusive)`

**Comment by JTronLabs** [comment]
It looks like there's not a function to get a random float between 2 values???

**Comment by photonstorm** [comment]
I've already merged your PR, however there are functions for this already: `RandomDataGenerator.interger` and `RandomDataGenerator.frac`, also `integerInRange` and `realInRange`.

**Comment by JTronLabs** [comment]
I did not know this was a thing. Maybe we should add a link/reference to it in Phaser.Math?
