### ISSUE TITLE
Updating New Issues to include a link to Phaser Sandbox

### ISSUE THREAD

**Issue by JTronLabs** [photonstorm/phaser#2759]
Current new Issue text

> Before opening this issue _please_ check we haven't already fixed it! Development always takes place in the Phaser `dev` branch. The easiest way to check is to read the [Dev Change Log](https://github.com/photonstorm/phaser/tree/dev#change-log).

> This Issue is about (delete as applicable)

> * A bug in the API
> * An error in the documentation
> * An error in the TypeScript defs
> * An error on the web site
> * A problem with my own code

> API errors must include example code showing what happens, and why you don't believe this is the expected behavior. Issues posted without code take _far_ longer to get resolved, sometimes not ever.

> If your Issue contains _any_ form of hostility it will be instantly closed.
> **Be nice.**

**Comment by JTronLabs** [comment]
Proposed new Issue text

> Before opening this issue _please_ check we haven't already fixed it! Development always takes place in the Phaser `dev` branch. The easiest way to check is to read the [Dev Change Log](https://github.com/photonstorm/phaser/tree/dev#change-log).

> This Issue is about (delete as applicable)

> * A bug in the API
> * An error in the documentation
> * An error in the TypeScript defs
> * An error on the web site
> * A problem with my own code

> API errors must include example code showing what happens, and why you don't believe this is the expected behavior. Issues posted without code take _far_ longer to get resolved, sometimes not ever. `You should include a link to Phaser Sandbox (http://phaser.io/sandbox) or somehow showcase your code.`

> If your Issue contains _any_ form of hostility it will be instantly closed.
> **Be nice.**

**Comment by photonstorm** [comment]
Fair enough. Done.
