### ISSUE TITLE
Phaser.SoundManager() mute Propertie doesn't work

### ISSUE THREAD

**Issue by halilcakarr** [photonstorm/phaser#2761]
Hello,

I got 2 problem with SoundManager.
First im creating that SoundManager like this: `this.soundManager = new Phaser.SoundManager(game);`
inside **init** function.
Then i called a function named **arrangeSounds()** and adding sounds like this.
```
this.soundManager.add('correntSound', .8, false, true);
this.soundManager.add('waiting', .8, true);
this.soundManager.add('falseSound, .8, false);
```
After all this my first problem is: When user select one of question options im playing **waiting** sound
on the onInputDown function. But when user change the selection, sound start a new one. And sounds getting mixed. How can i check for this ?

////////////////////////////////////////////////
Update: 
After i just update this i figured out how can i check.

```
if(this.waiting == null)
		this.waiting = this.soundManager.play('waiting', .7, true, false);
//this if statement handle my problem :)
```

/////////////////////////////////////////////////

And the second problem with SoundManager is the mute option. I have a button named **soundButton**
and when user click this im calling this function :
```
if(this.enableSound) {
	this.sound.frame = 1;
} else {
	this.sound.frame = 0;
}
this.soundManager.mute = !this.soundManager.mute;
this.enableSound = !this.enableSound;
```
this should mute all the sounds but it doesn't. 

Thanks for advance.

**Comment by photonstorm** [comment]
Hi - Is there a reason you've created your own SoundManager instance, and not used the one Phaser creates by default? (which you can access via `game.sound` or just `sound` from within any Phaser State).

Things like muting on game pause, etc, won't work with your own instance, it'll only mute the one Phaser creates.

**Comment by halilcakarr** [comment]
The reason i create one is i have lots of sound but ill try to use one Phaser's. Hope it will Work Thanks

**Comment by photonstorm** [comment]
If you find this still happens when you use the built-in (global) Phaser Sound Manager, then please leave a comment with example code, and I'll re-open this and look at it. Otherwise I'm going to close it for now.
