### ISSUE TITLE
tween manager removeFrom does not work on groups

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2769]
If you're tweening a group directly (not the children of the group mind you, I mean the literal group) you cannot use the tween manager to remove all tweens, e.g. game.tweens.removeFrom(group). Therefore, it's impossible to stop tweens on a group unless you've created your own reference. The docs also specify that removeFrom accepts Phaser.Group as a paramater, so this should work in theory.

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

If it's easier you can use the [Phaser Sandbox](http://phaser.io/sandbox/) to create a code sample (as this is now running the latest build of Phaser). Enter your code, click the 'save icon' in any of the editor tabs, and paste the URL here.
