### ISSUE TITLE
Sprite.kill() does not halt the update loop

### ISSUE THREAD

**Issue by JTronLabs** [photonstorm/phaser#2776]
This Issue is about (delete as applicable)
- A bug in the API

Add a console function to a sprite's update. kill the sprite. The console will be logged indefinitely. Why was this design decision made? I doubt it's a bug, as it seems like a really basic behavior, but sprite pooling is a super common paradigm and needlessly running the update loop seems wasteful.

http://phaser.io/sandbox/edit/kKQXcliI

(note for the sandbox, you have to click on the game in the 'play' tab for the game to have focus & do the logging)

[Discussion here](http://www.html5gamedevs.com/topic/25510-why-does-spritekill-not-halt-the-update-loop/#comment-145826)

**Comment by JTronLabs** [comment]
Same thing happens for Phaser.Group.  I updated the sandbox.

**Comment by photonstorm** [comment]
Yes this is by design, there are plenty of reasons why a Sprite that has been killed may still need its update function running. It's not something that will be changed in Phaser 2, but if you all want to change it in Phaser CE then go ahead. Just be sure to document it _clearly_.
