### ISSUE TITLE
Phaser.Group.prototype.addAt is missing 'return'

### ISSUE THREAD

**Issue by Pr0fil3** [photonstorm/phaser#2784]
This Issue is about (delete as applicable)
- A bug in the API

Both the 2.6.2 and dev branches are missing the return in Group.addAt.

https://github.com/photonstorm/phaser/blob/dev/src/core/Group.js#L435

It should be changed to 

`return this.add(child, silent, index);`

**Comment by hilts-vaughan** [comment]
This is fixed now in `dev` it seems.
