### ISSUE TITLE
Phaser 2.6.2 - Typescript definition issue with functions like "getRayCastTiles" at Tilemap and TilemapLayer

### ISSUE THREAD

**Issue by fsrojash** [photonstorm/phaser#2792]
I notice that the typescript definition for **getRayCastTiles** function is different from what you see at phaser.min.js. At typescript definition file this function is part of Tilemap class but on the phaser.min.js is part of TilemapLayer class...

**Comment by photonstorm** [comment]
I fixed this this morning, so is now ok in Phaser CE.
