### ISSUE TITLE
Graphics.alpha not in documentation.

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2798]
In the latest version of Phaser, the <a href="http://phaser.io/docs/2.6.2/Phaser.Graphics.html">Phaser.Graphics documentation</a> lacks the `alpha` property. I was wondering if a Graphics object can have its opacity modified and I checked there, but found nothing. When I went in the Javascript console to test, though, the `alpha` property was there and I was able to set it with no problem. It worked too.

**Comment by photonstorm** [comment]
Yeah this was related to #2837 which is now fixed in Phaser CE.
