### ISSUE TITLE
Phaser build using grunt throws an error

### ISSUE THREAD

**Issue by trueicecold** [photonstorm/phaser#2803]
when using grunt to builkd phaser (either excluding or full build) I get the following error:

`Loading "eslint.js" tasks...ERROR

> > SyntaxError: C:\Work\Phaser\node_modules\grunt-eslint\tasks\eslint.js:2
> > const chalk = require('chalk');
> > ^^^^^
> > Use of const in strict mode.`

However, the grunt process works fine, and finished without errors. Afraid to face the outcomes at a later stage :)

**Comment by photonstorm** [comment]
This should be fine since the split to Phaser CE, as I removed all the eslint files I was using :) I noticed a few left over that I've now removed too, but they weren't being used.
