### ISSUE TITLE
What is up with rotation from Sprite being in radians and rotation from Arcade Physics bodies being in degrees? Opposite issue with angle

### ISSUE THREAD

**Issue by Cazadorro** [photonstorm/phaser#2810]
I didn't see this issue, though maybe I missed it, it appears that Sprite (and probably other display object types) rotation is in radians while .angle property is in radians  Arcade physics bodies on the other hand use degrees for the rotation property and radians for the angle property!   Can any one else confirm this is the case?  The documentation for phaser 2.6.2 appears to corroborate this.   

I imagine a fix now would cause issues for many people who relied on the conversion for either but this really needs to be fixed.

**Comment by photonstorm** [comment]
You're right, it's too late in the day to be changed now.

If someone wants to change it for Phaser CE then go ahead though. Just be sure to document the change clearly, as it'll confuse a _lot_ of people.
