### ISSUE TITLE
Chrome on macOS Sierra renders blank screen

### ISSUE THREAD

**Issue by ChennyBaBy** [photonstorm/phaser#2813]
This Issue is about :
- Chrome on macOS Sierra renders blank screen

I have recently updated to the new **macOS Sierra version 10.12**. And I have a problem that any of the phaser tutorials or games won't load in **Chrome (Version 54.0.2840.71 64-bit)** it just shows a blank screen:

![phaser_-_making_your_first_game__part_2_and_about_this_mac](https://cloud.githubusercontent.com/assets/1523107/19622527/f875e9ec-98a3-11e6-90c3-08cc313f8a11.jpg)

There isn't any error message in the console either. I have tried loading the page in safari and it works fine. 

I then jumped on my other mac which has Yosemite version 10.10.5 and got the same chrome version and it still works fine so my only guess it's down the to OS.

I would love to know if there's anyone out there who also has Sierra to see if they see the same thing.

**Comment by photonstorm** [comment]
I use Chrome on OS X Sierra daily, and Phaser works fine. However I've never tested such an old version (you've got 2.0.1 there, which is really old). Try swapping it for the phaser.js from the latest release? (2.6.2) and see what happens. I'd suspect that might be enough.

**Comment by ChennyBaBy** [comment]
Yeah i'm still getting the same thing after updating the phaser.js Maybe it's down to the iMac I have doesn't work well with sierra.

**Comment by photonstorm** [comment]
That's a shame :( It's possible Safari black-listed your GPU? True forcing the code to use CANVAS. Most examples online use `Phaser.AUTO` which will try and use WebGL, but if you force `Phaser.CANVAS` then at least you can narrow down the cause. If that works, but AUTO doesn't, the issue is between Safari and your GPU sadly.

**Comment by ChennyBaBy** [comment]
Thank for your help man 😋 ! Yeah it's not an issue here, my iMac is like 7 years old I will give that a try to see if it works. Thank you~!
