### ISSUE TITLE
Phaser Group forEach not passing i to callback

### ISSUE THREAD

**Issue by Marak** [photonstorm/phaser#2815]
This Issue is about: 
- A missing feature in the API

**Phaser Group forEach not passing i to callback**

`/src/core/Group.js`
`Phaser.Group.prototype.forEach`
https://github.com/photonstorm/phaser/blob/v2.6.2/src/core/Group.js#L1734

In JavaScript forEach, callback is invoked with three arguments:
- the element value
- the element index
- the array being traversed

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

In Phaser Group forEach, we are missing the element index i in callback. This is useful to have and is also the standard JavaScript API.

Can we add the `i` value to the callback arguments in Phaser?

**Comment by monkeyWzr** [comment]
Currently we can use `Group.getChildIndex(item)` in ` Group.forEach` callback to get the index. But it's not elegant at all :D.

[http://phaser.io/docs/2.6.2/Phaser.Group.html#getChildIndex](http://phaser.io/docs/2.6.2/Phaser.Group.html#getChildIndex)

**Comment by hilts-vaughan** [comment]
@monkeyWzr See the PR above, it was merged and implemented so that you don't need to a linear search each time.

@photonstorm This was fixed when you merged it -- can we close this issue?

**Comment by photonstorm** [comment]
True, closing.
