### ISSUE TITLE
API docs unclear / incomplete on starting animation at specific frame

### ISSUE THREAD

**Issue by letmaik** [photonstorm/phaser#2823]
I just spent one hour trying to figure out how to start an animation at a given frame which was not the first frame of the animation.
What I tried was:

``` js
animation.frame = 5
animation.play()
```

However, `play()` resets the frame and starts at 0, which is not documented, at least I didn't find anything. So, the solution is to start playing and then set the frame:

``` js
animation.play()
animation.frame = 5
```

This is counter-intuitive to me. If you think about casette players, you first seek to your playing position, and then press play, not the other way around. Would be great if this is documented so that others don't stumble upon the same issue.

**Comment by Cristy94** [comment]
I think the correct solution would be to actually have your `animation` frames only from 5 to the end.

**Comment by letmaik** [comment]
The frames I start with are dynamic, so I would have to create a lot of animation objects for all different cases. But since the animation class supports setting the frame, why not use it?
