### ISSUE TITLE
Default value to frequency parameter of Phaser.Particles.Arcade.Emitter.flow is never set

### ISSUE THREAD

**Issue by brianbunch** [photonstorm/phaser#2824]
This Issue is about (delete as applicable)
- A bug in the API

The default value of 250 to frequency parameter of Phaser.Particles.Arcade.Emitter.flow is never set.

**Comment by photonstorm** [comment]
It is, because the argument value is passed directly to `Emitter.start`, and if that value is undefined or null then it defaults to 250 in that method, so it doesn't need to do it in the flow method as well.

**Comment by photonstorm** [comment]
Having said that, if you set the `immediate` argument to `true` then it'd fail, so I'll default it anyway.
