### ISSUE TITLE
Sprite ID

### ISSUE THREAD

**Issue by Gurigraphics** [photonstorm/phaser#2829]
Implementation:

```
var SpriteId = 0;

PIXI.Sprite = function (texture) {

    PIXI.DisplayObjectContainer.call(this);

    /**
     * The id that the sprite is using
     *
     * @property id
     * @type Number
     */
    this.id = SpriteId;
    SpriteId++;  
(...)

```

Use:

```
image.events.onDragStart.add(onDragStart, this);


      function onDragStart(sprite, pointer) {

          console.log("Dragging " + sprite.id); //Dragging 1      

      }
```

Any better suggestions to implement sprite id?

**Comment by photonstorm** [comment]
Why not use `Sprite.name` which already exists? Or store a property in `Sprite.data` ?

**Comment by Gurigraphics** [comment]
> Why not use Sprite.name which already exists? Or store a property in Sprite.data ?

Truth.
I need to use the same image repeatedly. 
And confuse "image name" with "sprite name". 
```
image.property = 'define id';
image.name = 'define id';
(...)
```
Thank you.

**Comment by hilts-vaughan** [comment]
@photonstorm This is addressed with `name`, should we close this?

**Comment by photonstorm** [comment]
Yup.
