### ISSUE TITLE
Variable/event missing in .min file of latest Phaser

### ISSUE THREAD

**Issue by branislav-brujic** [photonstorm/phaser#2833]
Hi everyone,
We used latest phaser.min.js file and notice that it dont have some variables/functions like normal.
First: Phaser.AUTO variable is missing
Second: Event onDragUpdate also missing.

**Comment by photonstorm** [comment]
Hi - Neither of these are missing from the min file. You can search for them here: https://github.com/photonstorm/phaser/blob/master/build/phaser.min.js and it'll find them both.

It's easier to find AUTO by searching for `{VERSION:"2.6.2",GAMES:[],AUTO:0`, but onDragUpdate appears right away.

**Comment by branislav-brujic** [comment]
Hi,
But then why i getting undefined for onDragUpdate when I using min, and same code just with regular phaser.js working fine?

**Comment by photonstorm** [comment]
This example uses Phaser 2.6.2 _min_ and drag update works: http://phaser.io/examples/v2/input/drag-update

Whatever the problem is, it's local to your set-up / browser / cache / environment I'm afraid.
