### ISSUE TITLE
P2 Physics ApplyImpulse breaks Collisions

### ISSUE THREAD

**Issue by DevinPentecost** [photonstorm/phaser#2842]
This Issue is about:

* A bug in the API
* A problem with my own code

Hello,

I am running into issues using ApplyImpulse and ApplyForce with P2 Physics.
I am seeing two problems:

1. Using ApplyImpulse removes any collisions with bodies in a single PhysicsGroup.
2. Using ApplyImpulse causes collisions to result in bodies getting destroyed.

I have been unable to find any examples that use ApplyImpulse, but I hope I am using it correctly. If there are examples that I have missed that show I am using it incorrectly, I would love to correct my code and fix the issue.

However, I believe that there is an issue in the code base. I took one of the examples from the website and made a very small change:
[https://phaser.io/examples/v2/p2-physics/collision-groups](https://phaser.io/examples/v2/p2-physics/collision-groups)

I took this example and removed any references to the sprites so we don't run into those issues, and set all of the bodies to use debug = true.

The only major change is I changed the logic of a left keypress from MoveLeft(200) to simply applyImpulse([10, 0]). If you run the example with this change, it behaves perfectly normally **until** you hit the left key and therefore applies the impulse.

Collisions before hitting left -> consistent with the example.
Collisions after hitting left -> objects are destroyed.

Is there something I am missing? I am not completely familiar with P2 physics, especially when it comes to Physics Groups, Collision Groups, and their relationship with one another. I checked the dev branch change log and could not see anything related to this - in fact all of my searches have pretty much come up empty regarding applyImpulse and applyForce...

I will be happy to provide more example code but I believe what I have posted below shows it cleanly.

/**
**/
var game = new Phaser.Game(800, 600, Phaser.AUTO, 'phaser-example', { preload: preload, create: create, update: update, render: render });

function preload() {

}

var ship;
var cursors;

function create() {

    //  Enable P2
    game.physics.startSystem(Phaser.Physics.P2JS);

    //  Turn on impact events for the world, without this we get no collision callbacks
    game.physics.p2.setImpactEvents(true);

    game.physics.p2.restitution = 0.8;

    //  Create our collision groups. One for the player, one for the pandas
    var playerCollisionGroup = game.physics.p2.createCollisionGroup();
    var pandaCollisionGroup = game.physics.p2.createCollisionGroup();

    //  This part is vital if you want the objects with their own collision groups to still collide with the world bounds
    //  (which we do) - what this does is adjust the bounds to use its own collision group.
    game.physics.p2.updateBoundsCollisionGroup();

    var pandas = game.add.group();
    pandas.enableBody = true;
    pandas.physicsBodyType = Phaser.Physics.P2JS;

    for (var i = 0; i < 4; i++) {
        var panda = pandas.create(game.world.randomX, game.world.randomY);
		
        panda.body.setRectangle(40, 40);

        //  Tell the panda to use the pandaCollisionGroup 
        panda.body.setCollisionGroup(pandaCollisionGroup);

        //  Pandas will collide against themselves and the player
        //  If you don't set this they'll not collide with anything.
        //  The first parameter is either an array or a single collision group.
        panda.body.collides([pandaCollisionGroup, playerCollisionGroup]);
		panda.body.debug = true;
    }

    //  Create our ship sprite
    ship = game.add.sprite(200, 200);
	
    ship.scale.set(2);
    ship.smoothed = false;

    game.physics.p2.enable(ship, false);
    ship.body.setCircle(28);
    ship.body.fixedRotation = true;
	ship.body.debug = true;

    //  Set the ships collision group
    ship.body.setCollisionGroup(playerCollisionGroup);

    //  The ship will collide with the pandas, and when it strikes one the hitPanda callback will fire, causing it to alpha out a bit
    //  When pandas collide with each other, nothing happens to them.
    ship.body.collides(pandaCollisionGroup, hitPanda, this);

    game.camera.follow(ship);

    cursors = game.input.keyboard.createCursorKeys();

}

function hitPanda(body1, body2) {

    //  body1 is the space ship (as it's the body that owns the callback)
    //  body2 is the body it impacted with, in this case our panda
    //  As body2 is a Phaser.Physics.P2.Body object, you access its own (the sprite) via the sprite property:
    body2.sprite.alpha -= 0.1;

}

function update() {

    ship.body.setZeroVelocity();

    if (cursors.left.isDown) {
		//////////
		//This is where the problems happen!
        ship.body.applyImpulse([10, 0]);
		//////////
    }
    else if (cursors.right.isDown) {
        ship.body.moveRight(200);
    }

    if (cursors.up.isDown) {
        ship.body.moveUp(200);
    }
    else if (cursors.down.isDown) {
        ship.body.moveDown(200);
    }
}

function render() {

    game.debug.text('Collide with the Pandas!', 32, 32);

}

/****/
`

**Comment by DevinPentecost** [comment]
I am having difficulty with formatting the code in the issue, I'll try to fix it but if someone can help me there I'd appreciate that as well!

Thanks

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
