### ISSUE TITLE
Certain velocity speed will create jitterness when a sprite is moving

### ISSUE THREAD

**Issue by Dillybob92** [photonstorm/phaser#2844]
> The jitter may be due to the camera setting the follow position a frame late or something similar. If that is happening, it would cause what you are seeing here.

Thanks for taking a look! Yeah, that's what I thought initially. Again, sorry for this cesspool of a bug issue. I've just been trying to isolate this bug because its been throwing me in every direction.

Except even if we disable the camera: http://jsfiddle.net/Dillybob/7LLqnxw1/30/

The jitterness is still there? I'm really not sure what else to test. If we decrease the velocity it seems like the jitterness actually is less. I have a feeling the velocity of arcade physics is making it jitter. Except, if the renderer is set to CANVAS, the jitterness doesn't happen at all. Only under WebGL. I'm really stumped here

**Comment by Dillybob92** [comment]
Isolated this a bit more.

Jitterness only starts to happen when the camera is panning.

**Comment by Dillybob92** [comment]
**Update:**

Isolated this issue more.

  
I added ` game.renderer.renderSession.roundPixels = true` to the `render` function and it seems to stop the jitter. Great! But when you apply a rotation to your sprite (`sprite.angle=31`), example:
http://liveweave.com/r55DO9

The jitter is back... Lol

**Comment by Dillybob92** [comment]
**Another Update:**

This seems like a WebGL issue.

Look here:
http://jsfiddle.net/Dillybob/7LLqnxw1/19/

There is no jitter whatsoever. But if you do: `Phaser.WEBGL` instead of CANVAS, the jitterness happens... What in the world?

**Comment by nexiuhm** [comment]
Hey. Looked at your last example and I'm only able to recreate the jitterness if roundPixels is set to True.  It also seem to happen regardless of camera movement, but less noticeable. Otherwise it works here. Probably some kind of rounding issue in WEBGL ?

**Comment by Dillybob92** [comment]
@nexiuhm Oops I posted the wrong one. I meant http://jsfiddle.net/Dillybob/7LLqnxw1/26/

@nexiuhm Yep, can confirm about camera. I just disabled `game.camera.follow` and the jitterness is still there.

To further isolate this:

- Happens only in WEBGL
- Camera panning is irrelevant
- if `game.renderer.renderSession.roundPixels` is true and the sprite **IS NOT rotated**, **no jitternes**s.
- if `game.renderer.renderSession.roundPixels` is true and the sprite **IS rotated**, **jitterness occurs**

**Comment by nexiuhm** [comment]
@Dillybob92  Indeed. Seems like the pixels dosnt get rounded properly when the sprite is rotated. Edited your example abit to further demonstrate this: https://jsfiddle.net/7LLqnxw1/28/

**Comment by Dillybob92** [comment]
@nexiuhm Thanks.

Check this out:

http://jsfiddle.net/Dillybob/7LLqnxw1/29/

Disabled the `arcade` physics, and moving with x, y positions only, no velocity.  And rotated. No jitterness?

Seems like, a body.velocity issues with physics inside `WebGL`. Weird....

**Comment by englercj** [comment]
The jitter may be due to the camera setting the follow position a frame late or something similar. If that is happening, it would cause what you are seeing here.

**Comment by Dillybob92** [comment]
> The jitter may be due to the camera setting the follow position a frame late or something similar. If that is happening, it would cause what you are seeing here.

Yeah, that's what I thought initially. Again, sorry for this cesspool of a bug issue. I've just been trying to isolate this bug because its been throwing me in every direction.

Except even if we disable the camera: http://jsfiddle.net/Dillybob/7LLqnxw1/30/

The jitterness is still there? I'm really not sure what else to test. If we change the velocity it seems like the jitterness actually is less. I have a feeling the velocity of arcade physics is making it jitter. Except, if the renderer is a CANVAS, the jitterness doesn't happen at all.

**Comment by nexiuhm** [comment]
@Dillybob92 I think what we are seeing here is that when using 'roundPixels = true' , the verticies are just stripped of fractions not caring on how approximate it is to it's closest integer.  Which means that the verticies are not coordinated in finding the right pixel to snap to. Changing this behavoir might be a huge performance hit to the rendering part. 

My suggestion is have roundPixels always be false in WEBGL and just make sure the data supplied to the renderer is not a float number. Maybe the physics engine should take this into account ? Idk. This is far beyond my abilites to even suggest.

**Comment by Dillybob92** [comment]
Created a new, more professional issue:
https://github.com/photonstorm/phaser/issues/2885
