### ISSUE TITLE
[Feature request] Ability to chain tweens with negative delays

### ISSUE THREAD

**Issue by adrian-gray** [photonstorm/phaser#2848]
One of the main things we miss from TweenJS is the ability to 'chain' tweens with a negative delay. This allows for things like 'a' tweens for 1 second, then half a second into that tween 'b' starts it's tween, as does 'c'.

In our old engine we used this frequently through TimelineMax. We'll probably end up importing TweenJS, but we'd prefer to stick with Phaser/Lazer if possible.

**Comment by photonstorm** [comment]
Why not just use GSAP? Yes Phaser has a Tween system built in, but you don't _have_ to use it. Lots of devs use GSAP in their games instead. We just can't include it because of licensing issues.

**Comment by adrian-gray** [comment]
Done. Cheers.
