### ISSUE TITLE
Minor error in docs

### ISSUE THREAD

**Issue by sbijoshj** [photonstorm/phaser#2858]
This Issue is about (delete as applicable)
* An error in the documentation

Right here:
https://github.com/photonstorm/phaser/blob/dev/docs/Phaser.GameObjectFactory.html#L3335
I think it is supposed to say Creature instead of Sprite?

**Comment by stoneman1** [comment]
Link does not work anymore. Is it fixed or what is the status?

**Comment by sbijoshj** [comment]
Alternative links that may be useful/helpful:
http://phaser.io/docs/2.6.2/Phaser.GameObjectFactory.html#creature
https://github.com/photonstorm/phaser/blob/v2.6.2/src/gameobjects/GameObjectFactory.js#L144
https://github.com/photonstorm/phaser/blob/master/v2/src/gameobjects/GameObjectFactory.js#L144

I see in v3 on master it's been refactored heavily so this may not be an issue.
