### ISSUE TITLE
AnimationParser.spriteSheet() arguments are all required

### ISSUE THREAD

**Issue by qarlosh** [photonstorm/phaser#2860]
This Issue is about

* A bug in the API
* (or maybe An error in the documentation)

Documentation says that `frameMax`, `margin` and `spacing` arguments are optional, but if no value is specified, the method implementation doesn't assign default values (-1, 0 and 0), and the `FrameData` object returned is not correct.

Example:
`bitmapdata.frameData = Phaser.AnimationParser.spriteSheet(game, bitmapdata.canvas, width, height)`

the above code always fails, it must be:

`bitmapdata.frameData = Phaser.AnimationParser.spriteSheet(game, bitmapdata.canvas, width, height, -1, 0, 0)`

**Comment by stoneman1** [comment]
Could you give example where you use this?

**Comment by qarlosh** [comment]
Hello,
I was using it in a function that dynamically creates a BimapData with some frames for an animated sprite, but I have changed my code since then... now I create the frames by using bitmapdata.frameData.addFrame() because I need named frames, and Phaser.AnimationParser.spriteSheet() doesn't allow this.

**Comment by hilts-vaughan** [comment]
This PR was fixed -- so we should close it. @photonstorm
