### ISSUE TITLE
AUTO mode doesnt work on chrome

### ISSUE THREAD

**Issue by NodeJoSe** [photonstorm/phaser#2867]
Chrome always picks Webgl, even when my graphic card does not support it. Firefox works fine.

I cant play games wich are on AUTO mode, its very laggy because its always picking Webgl mode

**Comment by photonstorm** [comment]
This is an issue with Chrome and your GPU. We have no control over if the browser thinks it can support WebGL or not: we ask it, and it replies. And if it replies that it can, we have to assume it is telling the truth and carry on. You should report this as an issue to the Chrome team.

**Comment by NodeJoSe** [comment]
Thx for the reply! you were right, it happens on the lastest updates on chrome and firefox, my graphic card was soposed to be on blacklist on those browsers but now webgl is enabled by default, i just had to disable webgl on every browser this way:

Firefox:

    Type into the URL bar “about:config” and click the “I’ll be careful” button
    Find the setting “webgl.disabled” and set it to true

Google Chrome: To disable WebGL in Google Chrome you will need to:

    Right-click your Google Chrome shortcut or from your Windows menu on your desktop, click ‘properties’ and add “-disable-webgl” to the Target Shortcut box

**Comment by photonstorm** [comment]
You really should report it to them - they _do_ fix stuff like this, and pretty fast. Although I guess "bad performance" is very different to "doesn't work" - one is just a symptom, the other a bug.
