### ISSUE TITLE
Where is Richard?

### ISSUE THREAD

**Issue by GodotIsAMess** [photonstorm/phaser#2881]
He's been gone for a while and haven't seen any posts by him on github. I am getting pretty worried to be honest, is he ok?  I really hope nothing happened to him.. :(

**Comment by hilts-vaughan** [comment]
Huh? He closed a bunch of pull requests and announced Phaser v2 not long ago.

Also, not to speak for him but he has posted in his newsletter and in a few other places that he has been ill. :)

**Comment by dongyukang** [comment]
He pushed some commits about an hour ago...

**Comment by GodotIsAMess** [comment]
Thanks for the fast responses. I was just getting worried because I usually see more activity from his profile. What is the Phaser v2 CE edition? For the people who don't want to switch to V3, but stay in V2? Will he still be head of the oversight committee (PR's, issues, for V2)? So many questions!

**Comment by hilts-vaughan** [comment]
https://github.com/photonstorm/phaser/blob/master/v2-community/README.md

**Comment by GodotIsAMess** [comment]
@hilts-vaughan Thanks.

> We'll give GitHub permissions to a select few individuals to help with this process.

Not sure what this means though, how the hell does GitHub know who to select? The people who have contributed adjacently next to Richard? (the most)?

**Comment by GodotIsAMess** [comment]
Also, what if I want to convert my game over to Lazer 3.0? Will there a script readily available for this? My game is around 15k + lines of code. There is no way on God's green earth I'm re-writing, however, if there is is a huuuuge performance advantage I might. There is so many questions that need to be addressed. I really hope Richard talks about these in his next presentation.  Really looking forward to it!

**Comment by photonstorm** [comment]
Happy to discuss things like this on Slack or Discord (as it's not an 'issue', so isn't worth adding to the total here, especially as people are trying to get that total down with PRs, etc)
