### ISSUE TITLE
Inconsistent cache handling of texture atlas breaking cache.removeTextureAtlas()

### ISSUE THREAD

**Issue by tfelix** [photonstorm/phaser#2893]
Version Phaser 2.6.2

I wanted to check if a certain texture atlas key was loaded (actually there is no method for this on the cache object) diving into code I found a inconsistent handling for the atlas cache.

In the addTextureAtlas Method the generated object is added to this._cache.image (see https://github.com/photonstorm/phaser/blob/v2.6.2/src/loader/Cache.js#L656) in the method removeTextureAtlas(key) it wants to delete from this._cache.atlas (https://github.com/photonstorm/phaser/blob/v2.6.2/src/loader/Cache.js#L1893) which is not defined and thus fails. I think this forum post is related: http://www.html5gamedevs.com/topic/18907-remove-cache-from-atlasjsonhash/. As you can see at the initialization of Cache.js no such cache is defined:

```
/**
    * The main cache object into which all resources are placed.
    * @property {object} _cache
    * @private
    */
    this._cache = {
        canvas: {},
        image: {},
        texture: {},
        sound: {},
        video: {},
        text: {},
        json: {},
        xml: {},
        physics: {},
        tilemap: {},
        binary: {},
        bitmapData: {},
        bitmapFont: {},
        shader: {},
        renderTexture: {}
    };
```

This will reproduce the error:

```
function create() {
    game.cache.removeTextureAtlas('test');
}
```

I would create a patch, but I am not certain how to adress this issue. Arguably one can change the removeTextureAtlas method to use the image cache or one could re-introduce the atlas cache object again. Any thoughts?

P.S.: Love this framework!

**Comment by photonstorm** [comment]
Good catch. `_cache.atlas` is a legacy object, and no longer used, but used to exist in the past.

If you just remove it from `_cache.image` it'll be fine. Which is the same thing as `removeImage` does already. For consistency it makes sense to include it though.

Feel free to submit it as a PR, but be sure to do so against the Phaser CE version (in the `v2-community` folder), thanks.

**Comment by photonstorm** [comment]
Closing, as it's now fixed in Phaser CE.
