### ISSUE TITLE
TypeScript error in pixi.d.ts because of missing SpriteBatch class

### ISSUE THREAD

**Issue by nyohan** [photonstorm/phaser#2899]
* An error in the TypeScript defs

In pixi.d.ts it looks like the SpriteBatch class was removed on purpose.  

Update Notes: "Phaser.SpriteBatch was incorrectly applying the prototypes, causing the Sprite Batch render methods to be replaced by the normal DisplayObjectContainer ones, meaning nothing was really batched at all. This has now been fixed, and PIXI.SpriteBatch removed, as it's no longer required."

Without it in visual studio I get an error on the following code in the WebGLFastSpriteBatch class.  

Here:  begin(spriteBatch: SpriteBatch, renderSession: RenderSession): void;
and Here: render(spriteBatch: SpriteBatch): void;

Adding it back in fixes the error.

 export class SpriteBatch extends DisplayObjectContainer {

        constructor(texture?: Texture);

        ready: boolean;
        textureThing: Texture;

        initWebGL(gl: WebGLRenderingContext): void;

    }

**Comment by elraro** [comment]
Hello, i have this problem.

Where can i add this to fix it?

**Comment by nyohan** [comment]
Add the SpriteBatch class to the pixi.d.ts file.  I added it right after the Sprite class like this...

    export class Sprite extends DisplayObjectContainer {

        constructor(texture: Texture);

        anchor: Point;
        blendMode: blendModes;
        exists: boolean;
        shader: IPixiShader;
        texture: Texture;
        tint: number;

        setTexture(texture: Texture, destroyBase?: boolean): void;

    }

    export class SpriteBatch extends DisplayObjectContainer {

        constructor(texture?: Texture);

        ready: boolean;
        textureThing: Texture;

        initWebGL(gl: WebGLRenderingContext): void;

    }

**Comment by jeremyBass** [comment]
@photonstorm hello, this is still missing in `pixi.comments.d.ts` and throws the same error when using the default `typings.json`
