### ISSUE TITLE
Particle Storm needs an update to work with phaser-CE

### ISSUE THREAD

**Issue by hayesmaker** [photonstorm/phaser#2909]
Particle Storm doesn't work with phaser-ce 2.7.2

* A bug in the API (phaser-ce 2.7.2)

<img width="555" alt="screen shot 2016-12-09 at 15 40 55" src="https://cloud.githubusercontent.com/assets/593429/21054506/ee3820c4-be25-11e6-80fc-618cdb2e1fd2.png">

**Comment by photonstorm** [comment]
I'm unlikely to update Particle Storm to support CE, so I'd recommend adding in a method reference into CE. I.e. map PIXI.canUseNewCanvasBlendModes to the Phaser.Device equivalent.

**Comment by hayesmaker** [comment]
` to the Phaser.Device equivalent.`

which is what?

**Comment by photonstorm** [comment]
#2863
