### ISSUE TITLE
`phaser_box2d.d.ts` calls `phaser.d.ts` and can't find it

### ISSUE THREAD

**Issue by jeremyBass** [photonstorm/phaser#2911]
Hello,
I have checked the issues, and change log and didn't see anything on this.  As I pull in the npm through visual studio 2015 update 3, and it auto builds the typescript, the typings here

https://github.com/photonstorm/phaser/blob/master/v2-community/typescript/phaser_box2d.d.ts#L1

fail to line up with the others which is the comments versions that are defined in the the `typings.json`.  That starts the path for use of the comments version but if you don't do any file alterations, the  `phaser_box2d.d.ts` calls `phaser.d.ts` which then complains about doubling.   Removing the  `phaser.d.ts` fixes the doubling, but then `phaser_box2d.d.ts` can't find it.  It would be nice to have `phaser_box2d.d.ts`  use 

```js
/// <reference path="phaser.comments.d.ts" />
```

So it lines up with that `typings.json`.

**Comment by photonstorm** [comment]
Please submit a PR for this (if you feel it'll sufficiently fix it for everyone, which on the surface it appears it would!)
