### ISSUE TITLE
Phaser CE documentation missing?

### ISSUE THREAD

**Issue by JTronLabs** [photonstorm/phaser#2922]
This Issue is about (delete as applicable)

* An error in the documentation

Not sure if I'm missing something, but the most up-to-date documentation visible on the site is [2.6.2](https://phaser.io/docs/2.6.2/index). Where is CE documentation supposed to live? Thanks!

**Comment by photonstorm** [comment]
For now it lives in the docs folder of the repo (or npm package if you get it that way). I've yet to decide where on the site it will live, or how, as I don't want it to be confused with an official release.

**Comment by JTronLabs** [comment]
Can we make the docs on the repo [GitHub projects pages?](https://pages.github.com/)

**Comment by JTronLabs** [comment]
You might be able to set the dev branch as the published branch, and then people could navigate to https://photonstorm.github.io/phaser/v2-community/docs/index.html to have to browser render it online. Or they can always download the source and open it on a local browser window

**Comment by JTronLabs** [comment]
Looks like someone did it - Thanks!! 

https://photonstorm.github.io/phaser-ce/
