### ISSUE TITLE
Phaser CE versions not on jsDelivr or cdnjs

### ISSUE THREAD

**Issue by triptych** [photonstorm/phaser#2925]
I noticed when going to jsDelivr to get the hosted version of Phaser that it only goes up to 2.6.2. Will CE versions get hosted there as well? 

https://www.jsdelivr.com/?query=phaser

**Comment by triptych** [comment]
Just an update - I see now that phaser-ce does not show up in the search results for phaser on the jsDelivr site, so it looks as if there's only up to 2.6.2. Perhaps add something in the description to help folks find the -ce version?

**Comment by triptych** [comment]
cdnjs.com link also does not work...

**Comment by photonstorm** [comment]
I'm not going to update the CDN links until I know where CE will live, as it will almost certainly move to its own repo in the New Year, so changing the links now would cause all kinds of grief.

**Comment by photonstorm** [comment]
Phaser CE now has its own repo: https://github.com/photonstorm/phaser-ce and has been submitted today to both jsDelivr and cdnjs.
