### ISSUE TITLE
removeChildren error

### ISSUE THREAD

**Issue by sharbelfs** [photonstorm/phaser#2929]
There is an error in the removeChildren function.

https://github.com/photonstorm/phaser/blob/v2.6.2/src/pixi/display/DisplayObjectContainer.js#L229

`var removed = this.children.splice(begin, range);`
begin is undefined

I believe that the correct should be:
`var removed = this.children.splice(beginIndex, range);`

**Comment by RedPanduzer** [comment]
I can confirm this, changing begin to beginIndex fixes issue. There is no variable named begin in removeChildren function.

**Comment by photonstorm** [comment]
This was fixed in Phaser CE several months ago. Please upgrade to that version, or fork and patch locally, as there will be no more changes to Phaser v2 I'm afraid.
