### ISSUE TITLE
Missing cdn on Gray Filter Example

### ISSUE THREAD

**Issue by halilcakarr** [photonstorm/phaser#2936]
Hi,
I was checking about filter effects. and on this example : phaser-examples/examples/filters/gray.js
gray.js script can not find.

:) hope you can fix that

**Comment by cjke** [comment]
Probably worth filing over on the examples repo: https://github.com/photonstorm/phaser-examples
Might be easier/better for visibility?

**Comment by photonstorm** [comment]
All of the filter examples have been updated and now work on the Phaser web site.
