### ISSUE TITLE
Feature Request - Quality adjust

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2946]
Display resolution plays a huge part in FPS values. For example, my game works at 60fps on my 1440x900 monitor, but at 30-35 on my 1920x1080. I noticed that if I zoom the page, the canvas gets a bit blurry, but there's less stuff to render and the FPS raises all the way up to 60.
I successfully made it possible to change quality for better performance:
```
function create() {
    ...
    gameResize.call(game);
    game.input.scale.setTo = function () {};
}

function gameResize(){
    var scale = 0.5; // or some other number greater than 0. Normal quality is 1.

    this.world.scale.setTo(scale);
    this.scale.setGameSize(window.innerWidth * scale, window.innerHeight * scale);
    setTransform(this.canvas, "scale(" + (1 / scale) + ")", "left top");

    this.input.scale.x = scale;
    this.input.scale.y = scale;
}

function setTransform(elem, value, origin){
	elem.style.webkitTransform = value;
	elem.style.MozTransform = value;
	elem.style.msTransform = value;
	elem.style.OTransform = value;
	elem.style.transform = value;

	elem.style.webkitTransformOrigin = origin;
	elem.style.MozTransformOrigin = origin;
	elem.style.msTransformOrigin = origin;
	elem.style.transformOrigin = origin;
}
```
By decreasing the game size and world scale, the whole game shrinks, lowering render pixels. Then, the CSS transform forces the canvas to stretch, filling the empty space made by the shrinkage.

I've erased the `input.scale.setTo` method because the engine internally modifies the input scale so that the pointers in the game are at the same place as the cursor. However, the CSS transform is a change that Phaser doesn't take into account and the pointers are no longer accurate.
For example, if the window is 1000px wide and we decrease the quality in half, the canvas becomes 500px wide, so does the game world. When the cursor is at (100, 100), we are at (100, 100) in the game world too. However, after transform is applied, the canvas is stretched and is twice as big. Now, for each screen pixel, we have two game pixels, meaning that (100, 100) on the screen is now (200, 200) in the game. Therefore the input multiplier must be equal to the factor by which we downscale the game.

I've tested this on my game and I like it a lot. About 20-30% quality decrease bumps my FPS (on the big monitor) up to 60, while the quality is still not bad. I actually like it a bit more that way, to be honest. The blur gives it a smooth look.

It would be nice if this was a simple modifiable number in Phaser. This gives flexibility to people with slow machines. Leaving that number's value to `1` makes absolutely no difference - game world and scale are not affected, transform is not applied, so people who don't want to use this functionality have no problem doing so. 

Thanks for reading!

**Comment by bladeSk** [comment]
This is already implemented, but without an official API. You can set the scale when creating a Phaser instance via a mostly undocumented `resolution` parameter:

    var game = new Phaser.Game({
        ...
        resolution: 0.5,
    });

There's no API to change it during runtime, but it's easily doable with a bit of messing with internals:

    game.renderer.resolution = 0.5
    game.renderer.renderSession.resolution = 0.5
    window.dispatchEvent(new Event('resize'));

The code above halves the resolution and works with WebGL as well as Canvas renderer. I wouldn't recommend changing it too often (like every frame), as the functions that are called on resize aren't necessarily optimized for realtime performance.

However, this doesn't solve the _real_ problem, which is poor performance on higher resolutions. WebGL itself can handle high resolutions just fine, but Phaser's old version of PIXI struggles with them for some reason - see https://github.com/photonstorm/phaser/issues/2908

**Comment by hdodov** [comment]
I didn't know about that, but I tried it now. It's not the same. I don't know _exactly_ what it does, but it totally breaks my game elements' positioning and overall size. Although, yes, it does reduce the resolution, but in a way that messes everything up. Perhaps that's why this functionality doesn't have official API?

Anyways, what I proposed changes only the world scale, meaning that everything _inside_ the world is alright. The camera can be a bit clunky because of that (since they share the same scaling), but it's easily manageable once you include `camera.scale` in all your interactions with the camera.

**Comment by bladeSk** [comment]
Huh, it worked for me, but there's yet another thing you could do: use a custom scaler, tell Phaser to use a smaller resolution and then stretch the canvas using CSS. The canvas element should look like this: `<canvas width="640" height="360" style="width: 1280px; height: 720px;">`. This shouldn't mess anything up (in theory).

**Comment by hdodov** [comment]
I remember trying to do it with CSS. Something was going wrong. I tried it now and Phaser just resizes the CSS width and height to the canvas' attribute width and height. I don't think that was the problem when I was doing that last week, though. I just remember it wouldn't work.

The canvas' attributes _are_ downsized. `game.scale.setGameSize()` does it. I simply upscale it back with transform, instead of CSS width and height.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
