### ISSUE TITLE
Feature Request - Phaser.Math.mapValue()

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2952]
If you have a slider in your game (music or sound, for example), the values are 0 at minimum, or 1 at maximum. That's just how a slider works. However, what if that slider's value represents something a bit more complicated? Something that ranges from `-100` to `100` for example. You'll be needing some sort of way to map the value of the slider in the `0` to `1` range to the `-100` to `100` range.

I made a method like that. It takes a value, current range (*cr*) and new range (*nr*):
```
function mapValue(val, cr, nr) {
    if (val < cr[0]) { val = cr[0]; }
    if (val > cr[1]) { val = cr[1]; }

    var rat = (cr[1] - val) / (cr[1] - cr[0]);
    return (rat * nr[0]) + ((1 - rat) * nr[1]);
}

mapValue(200, [100, 300], [0, 1]);     // 0.5
mapValue(0.451, [0, 1], [-100, 100]);  // -9.79
mapValue(10, [0, 15], [1, 0]);         // 0.33
```

**Comment by riebschlager** [comment]
What you've described already exits at Phaser.Math#mapLinear:

https://github.com/photonstorm/phaser/blob/master/v2/src/math/Math.js#L1086

**Comment by hdodov** [comment]
Oh, didn't saw that.
