### ISSUE TITLE
Feature Implementation Request - findTopElement()

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2954]
Finding the topmost Sprite in the game can be quite tricky. Finding the topmost Sprite that meets a certain condition is even trickier. I made a method that makes these things possible and I think it would be great if Phaser had it as a helper function.
```
function findTopSprite(object, fn, ctx, sprite) {
    if (fn.call(ctx, object) === true) {
        sprite = object;
    }

    for (var i = 0; i < object.children.length; i++) {
        sprite = findTopSprite(object.children[i], fn, ctx, sprite);
    }

    return sprite;
}

function check(sprite) {
    if (sprite instanceof Phaser.Group === false) {
        return sprite.getBounds().contains(
            this.input.activePointer.x,
            this.input.activePointer.y
        );
    }
}

// Returns the topmost Sprite under the active input pointer.
findTopSprite(game.world, check, game);
```
If the first argument is a Group or a Sprite, the result will be the topmost Sprite in that certain object. The second argument can be a function that checks anything in a Sprite. If the desired condition is met, it should simply return `true`. The third argument is the context in which the given checker function should run. The fourth argument can be a default Sprite in case there aren't any valid Sprites found.

The function uses recursion which can be dangerous, but I tested it and it's working fine. I suppose it can cause problems or performance issues if the checked Sprite tree is too large, but despite that, this can be very useful in my opinion.

Thanks for reading!

**Comment by hdodov** [comment]
I found an even better solution:
```
function findTopSprite(object, fn, ctx, sprite) {
    if (fn.call(ctx, object) === true) {
        return object;
    }

    for (var i = (object.children.length - 1); i >= 0; i--) {
        sprite = findTopSprite(object.children[i], fn, ctx, sprite);
        if (sprite) {
            return sprite;
        }
    }

    return sprite;
}
```
It doesn't have to iterate through the whole world tree because it works backwards and returns the first Sprite that meets the condition. If it starts from the topmost Sprite and goes down, the first Sprite to meet the condition is guaranteed to also be the _topmost_ that does.

The downside is that the fourth argument can no longer be used as a default Sprite if no match is found, but I don't think that's a big deal, though.

**Comment by phreaknation** [comment]
Think you can add some comments to this and make it a bit more formal?

**Comment by hdodov** [comment]
Well, I don't know what I could comment, really. Recursions are confusing in my opinion and comments can't help much until you dive into it and check what happens for yourself. I'll try, though.
```
/**
* Gets the topmost child of an element with the option to check for a condition.
*
* @method
* @param {object} - Element inside of which to search.
* @param {function} - Optional checker function that is called for each child in the recursion. It should return true or false depending on whether we want the child to be a possible match.
* @param {array} - Optional array of arguments to be passed to the checker function.
*/

function findTopElement(object, checker, args) {
    return (function search(object, match) {
        var c = object.children;

        if (Array.isArray(c)) {
            var i = c.length;

            while (i--) {
                // If the current child matched the checker function condition or
                // no such function was given, return the child to the parent caller.
                if (typeof checker !== "function" || checker.apply(c[i], args) === true) {
                    return c[i];
                }

                // Save any matches that the child might find inside itself.
                match = search(c[i], match);

                // If a match was found in the current child, break the recursion and proceed
                // to return the match to the parent caller.
                if (match) {
                    return match;
                }
            }
        }
        
        // Return any match found to the parent caller.
        return match;
    })(object, null);
}

function findTopElement(object, checker, args, match) {
     var c = object.children;

     if (Array.isArray(c)) {
         var i = c.length;

         while (i--) {
             // If the current child matched the checker function condition or
             // no such function was given, return the child to the parent caller.
             if (typeof checker !== "function" || checker.apply(c[i], args) === true) {
                 return c[i];
             }

             // Save any matches that the child might find inside itself.
             match = findTopElement(c[i], checker, args, match);

             // If a match was found in the current child, break the recursion and proceed
             // to return the match to the parent caller.
             if (match) {
                 return match;
             }
         }
     }
     
     // Return any match found to the parent caller.
     return match;
}
```
The first method uses a nested function. That's because the `match` variable is used internally by the recursion to pass data to child calls. This way, the user can't specify this argument because he doesn't have to.
The second method doesn't use a nested function and `match` can be specified. If it's not falsy, the method would return `match` after the first child has been checked and none of the child's children have been matched.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
