### ISSUE TITLE
 Phaser is not rendering inside time callback nested in a tween

### ISSUE THREAD

**Issue by jjppof** [photonstorm/phaser#2963]
**Phaser:** 2.6.2

I have a function `fire_event()` outside `update()`. Inside this function, I do these things:

```
function fire_event(){
    my_flag = false;
    do_stuff_1();
    game.add.tween(sprite).to( { alpha: 1.0 }, Phaser.Timer.HALF, Phaser.Easing.Linear.None, true).onComplete.addOnce(function(){
        game.time.events.add(Phaser.Timer.HALF, function(){
            do_stuff_2();
            game.add.tween(sprite).to( { alpha: 0.0 }, Phaser.Timer.HALF, Phaser.Easing.Linear.None, true).onComplete.addOnce(function(){
                my_flag = true;
            }, this);
        }, this);
    }, this);
}

function update(){
    if(my_flag){
        do_update_stuff();
    } else {
        //do nothing
    }
}
```

Everything that need to be rendered on function `do_stuff_2()`, is not rendering... only when the most inner tween finishes things got rendered. Everything go rendered, till the code reaches `do_stuff_2()`.

In short words: `do_stuff_2()` removes sprites from groups, then add new layers to them, and change some sprites position.
The thing is, **everything inside `do_stuff_2()` only happens when the tween under `do_stuff_2()` finishes.**
The inner tween makes alpha channel goes from 1 to 0 immediately.

**The problem happens always in the fade out. Fade in works.**

**QUESTION:**

Does a time event inside a tween, like the example above, make things do not render excepting when everything is finished? Don`t things get rendered when I nest callbacks?

-----------------------------

Instead of using a timer, I also tried using tween delay. Also didn't work:

```
function fire_event(){
    my_flag = false;
    do_stuff_1();
    game.add.tween(sprite).to( { alpha: 1.0 }, Phaser.Timer.HALF, Phaser.Easing.Linear.None, true).onComplete.addOnce(function(){
        do_stuff_2();
        game.add.tween(sprite).to( { alpha: 0.0 }, Phaser.Timer.HALF, Phaser.Easing.Linear.None, true, Phaser.Timer.HALF).onComplete.addOnce(function(){
            my_flag = true;
        }, this);
    }, this);
}
```

-----------------------------

Detailed info about functions if needed:

**`do_stuff_2()`:**
```
underlayer_group.removeAll(); //clear group
overlayer_group.removeAll(); //clear group
map_name = current_event.target; //thats just a string
maps[map_name].setLayers(underlayer_group, overlayer_group); //I'll provide a more details on it, but it basically add new layers to these groups
hero.body.x = current_event.x_target * maps[map_name].sprite.tileWidth; //hero is a sprite. Changing it x position
hero.body.y = current_event.y_target * maps[map_name].sprite.tileHeight; //hero is a sprite. Changing it y position
shadow.x = hero.x;  //shadow is a sprite. Changing it x position
shadow.y = hero.y;  //shadow is a sprite. Changing it y position

//reconfig world physics
game.physics.p2.resume();		    			
map_collider.body.clearShapes();
map_collider.body.loadPolygon(maps[map_name].key_name, maps[map_name].key_name);
mapCollisionGroup = game.physics.p2.createCollisionGroup();
map_collider.body.setCollisionGroup(mapCollisionGroup);
map_collider.body.setZeroDamping();
map_collider.body.setZeroRotation();
hero.body.collides(mapCollisionGroup);
map_collider.body.collides(heroCollisionGroup);
game.physics.p2.updateBoundsCollisionGroup();
```

**`setLayers()`:**
```
setLayers(underlayer_group, overlayer_group){
    this.map_sprite = game.add.tilemap(this.key_name); //set map sprite
    this.map_sprite.addTilesetImage(this.tileset_name, this.key_name); //set tilemap image

    for(var i = 0; i < layers.length; i++){
        var layer = this.map_sprite.createLayer(layers[i].name); //create a layer
        layer.resizeWorld();
        if(layers[i].properties.over != 0) //just test a property to determine which group this layer is going to make part
            overlayer_group.add(layer);
        else
            underlayer_group.add(layer);
    }
}
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
