### ISSUE TITLE
Typescript errors for typings.json under node_modules

### ISSUE THREAD

**Issue by appsolutegeek** [photonstorm/phaser#2975]
Hi,

I am uisng at-loader (awsome typescript loader) for webpack and I was constantly getting an issue like so

```
[at-loader] Checking finished with 4 errors
 95% emitting[at-loader] node_modules/phaser/typescript/typings.json:2:11
    ';' expected.

[at-loader] node_modules/phaser/typescript/typings.json:3:11
    ';' expected.

[at-loader] node_modules/phaser/typescript/typings.json:4:12
    ';' expected.
```

I tried ignoring the file under tsconfig.json and exclude but nothing. So I decided to remove the typescript directory and now everything works ok.

I have another file under typings that is the following

```
{
  "resolution": "main",
  "tree": {
    "src": "https://raw.githubusercontent.com/photonstorm/phaser/master/typescript/typings.json",
    "raw": "github:photonstorm/phaser/typescript/typings.json",
    "main": "phaser.comments.d.ts",
    "files": [
      "pixi.comments.d.ts",
      "p2.d.ts"
    ],
    "global": true,
    "name": "phaser",
    "type": "typings"
  }
}
```

little confused here, and I hate to throw another typescript issue. Right now it seems to be fixed as I removed the typings from the node_modules and everything seems to continue be found.

Anyone have any experience with at-loader and the errors that I was getting ?

thanks

**Comment by rpascal** [comment]
Did you ever find a solution to this problem?

**Comment by appsolutegeek** [comment]
Well its fixed, but I am afraid I can't be of much help as I was going round in circles so I eventually pulled my tsconfig and restarted again. Everything just started working. Here is my current TSCONFIG if its helpful.

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  }
```
