### ISSUE TITLE
Box2D Plugin - renderBody seems to incorrectly render x-direction on camera move

### ISSUE THREAD

**Issue by jcharry** [photonstorm/phaser#2981]
It seems that the Box2D debug render body function incorrectly moves the x coordinate when the camera moves.  
![box2d-renderbody-issue](https://cloud.githubusercontent.com/assets/4093008/22609360/e3f40c92-ea2e-11e6-9daa-57d28957fa83.gif)
In this gif, only the camera is moving, the body is completely static.

[This forum post](http://www.html5gamedevs.com/topic/23728-phaser-box2d-sprite-and-physic-body-at-different-location-when-following-player/) suggests the solution is in Box2D, in the ```renderBody``` method, changing
```
    xf.p.x += -body.game.camera.x / world.ptmRatio;
    xf.p.y -= -body.game.camera.y / world.ptmRatio;
```
to
```
    xf.p.x -= -body.game.camera.x / world.ptmRatio;
    xf.p.y -= -body.game.camera.y / world.ptmRatio;
```
Seems to fix things.

**Comment by Cristy94** [comment]
Wouldn't the fix be better like this:
```
    xf.p.x += body.game.camera.x / world.ptmRatio;
    xf.p.y += body.game.camera.y / world.ptmRatio;
```

I think there's no reason for the double minus sign.
