### ISSUE TITLE
Image.generateTexture always generates 32x32 texture

### ISSUE THREAD

**Issue by and3rson** [photonstorm/phaser#2983]
This Issue is about:

* A possible bug in the API v2.6.2
* A possible problem with my own code

I'm using a GLSL fragment shader to generate lighting for my scene.
Because all of the raytracing is an expensive operation, I do this:
- I set my filter to a smaller `Image` (called `originalImage`)
- I call `originalImage.generateTexture` to get the texture
- I put the result into another, biger image.

The problem is that `Image.generateTexture` **always** returns texture of size 32x32. The texture is very blurry when used in other images.

STR:
1. Create `Image`: `var originalImage = new Image()`
2. Draw something onto `originalImage`
3. Call `originalImage.getTexture()`
4. Resulting texture is always sized 32x32 despite resolution and other settings.

You can see the demo of the problem here: http://public.dun.ai/public/misc/light.html
Left side is original image, right side is `originalImage.generateTexture.`

AFAIKT, Phaser internally uses 32x32 textures and resizes them with `scale` factor - I guess that's where the `32` kicks in from. But isn't it possible to generate higher-resolution texture?

Thanks in advance! Phaser totally rocks, we're going to publish our first game written in Phaser+Electron to Steam Greenlight soon.

**Comment by and3rson** [comment]
I managed to solve this by using the intermediate `RenderTexture` and calling `RenderTexture.renderXY`. To anyone looking for the solution to this problem, here's how I did it:

1. I create `texture`, `sourceImage` and `targetImage`. `targetImage` has texture tet to `texture`.
2. I render my shader onto `sourceImage` and call `texture.renderXY(sourceImage, 0, 0, true)` and thus get the texture display at `sourceImage`.

This way I get proper size of the texture.

Hope it helps.

**Comment by and3rson** [comment]
This issue can be closed. Here's my final solution: public.dun.ai/public/misc/light4.html

**Comment by hexus** [comment]
Nice lighting effect! Lots of branching in that shader though. :grin:

**Comment by and3rson** [comment]
Thanks!

Yeah, it can still be optimized - some of the loops can be replaced by code duplication.

I was trying to implement proper shadow blurring, but it requires some extra trigonometry stuff, so I simply did multiple raycasting - simplier, but requires extra passes. Gonna try the proper way later. Probably gonna make a lib or something.

**Comment by hexus** [comment]
The GPU unrolls your loops anyway! I'm doing something similar, but it's an implementation of this:

https://github.com/mattdesl/lwjgl-basics/wiki/2D-Pixel-Perfect-Shadows

I'm having trouble working out the best way to do a smooth distance-based blur too. The method presented in that tutorial isn't great for huge-radius lights.

My implementation for rendering the lights uses a lightmap and shadowmap texture, and instancing to render quads to the lightmap with a light shader.

**Comment by and3rson** [comment]
@hexus That looks cool!

In case anyone is interested I've just published & cleaned up my code a bit [here](https://github.com/and3rson/enlightenment).

**Comment by hexus** [comment]
Awesome! I'm pretty new to it too, I feel the same way.
