### ISSUE TITLE
Setting up a video auto flips on Y coord in Mozilla firefox 51.0.1, while it works correctly in Chrome/edge

### ISSUE THREAD

**Issue by koenvancrombrugge** [photonstorm/phaser#2984]
This Issue is about: when setting up a video, the video flips the y coord for no reason in Mozilla firefox 51.0.1 using phaserJS 2.6.2, I tested this with chrome & edge and it works perfectly. I'm pretty sure the problem isn't inside my code, can you guys take a look at this issue?

* A bug in the API (2.6.2)
* A problem with my own code

Please take a look in the pictures below.

Thank you!
![code](https://cloud.githubusercontent.com/assets/9421086/22824672/247c0b20-ef89-11e6-974a-15e07bf6fc16.PNG)
![untitled-1](https://cloud.githubusercontent.com/assets/9421086/22824675/28c5b780-ef89-11e6-922a-b2a4a9fedd42.png)

**Comment by adrian-gray** [comment]
Small note, looks flipped on Y, not rotated, to me... I don't suppose it's related to only setting an anchor for X? Or it being scaled somewhere?

**Comment by koenvancrombrugge** [comment]
@adrian-gray I got exact the same issue using this line: introVideo.addToWorld(0, 0);

I want my video full screen starting from x = 0 & y = 0 without scaling, I did test with other formats aswell, it doesn't seem to work with firefox. Do you know about this bug?

Im pretty sure I'm using the right code, since my example perfectly works in other browsers beside firefox..

**Comment by adrian-gray** [comment]
@koenvancrombrugge Tested using FF 51.0.1 PhaserJS 2.6.2 on OSX with an mp4. Looks fine here, shows with the correct orientation.

Maybe it's something funky with your video's encoding? If you want to put a link up to an example with a flipped video, I'd be happy to try it.

**Comment by koenvancrombrugge** [comment]
@adrian-gray I sended you an email with my example. You can switch between *mp4, *webm, both don't seem to work. Thanks for helping me out.

**Comment by adrian-gray** [comment]
@koenvancrombrugge strange, this looks fine here – the vids (both webm and mp4) play the right way up in FF 51.0.1 (64 bit, OSX). I'd try it in a new private window in Firefox, to isolate the effects of any plugins, and if it's still happening for you. Then get someone using the same OS as you to give it a try.

The bright side is, it looks like you're doing things right with the code.

**Comment by koenvancrombrugge** [comment]
@adrian-gray I did just refresh my Firefox, still doesn't seem to work. Gonna try that one out, thanks mate for helping me out! 🥇
