### ISSUE TITLE
Docs search is unresponsive.

### ISSUE THREAD

**Issue by israelg99** [photonstorm/phaser#2986]
This Issue is about (delete as applicable):
* An error in the documentation

The docs search button unresponsive.
Go here: https://phaser.io/docs/2.6.2/index, and click the last item in the left menu.

**Comment by Arpit-24** [comment]
Solved :
Cut and Paste : <li class="dochead"><a href="https://phaser.io/learn/chains">Docs Search</a></li>
from its own ul list to the previous ul

<ul class="js-slide-hidden">
<li class="dochead"><a href="/docs/2.6.2/index#tweens" data-slug="tweens">Tweens</a></li>
<li class="dochead"><a href="/docs/2.6.2/index#sound" data-slug="sound">Sound</a></li>
<li class="dochead"><a href="/docs/2.6.2/index#system" data-slug="system">System</a></li>
<li class="dochead"><a href="/docs/2.6.2/index#utils" data-slug="utils">Utils</a></li>
<li class="dochead"><a href="https://phaser.io/learn/chains">Docs Search</a></li>
</ul>

**Comment by photonstorm** [comment]
About to redo the whole docs area, so closing off this old issue.
