### ISSUE TITLE
Phaser.Sprite does not have a rotation field in the TypeScript defs

### ISSUE THREAD

**Issue by israelg99** [photonstorm/phaser#2987]
This Issue is about (delete as applicable)"
* An error in the TypeScript defs

Phaser.Sprite does not have a rotation field in the TypeScript defs, I fixed it by adding `rotation: number;`.
This example uses Phaser.Sprite.rotation: https://github.com/photonstorm/phaser-examples/blob/master/examples/arcade%20physics/angle%20to%20pointer.js#L25

**Comment by israelg99** [comment]
I think it is located in the `pixi.d.ts` file, I'll check and update.

**Comment by ChrisMcNulty91** [comment]
@israelg99 Is this still an issue if so I could take a look?

**Comment by israelg99** [comment]
The rotation field was not found because it was located in `pixi.d.ts` and not `phaser.d.ts`, I didn't have the former file thus TypeScript complained about not finding the field, I fixed the issue by adding `pixi.d.ts` into typings.
