### ISSUE TITLE
game.add.text with fontSize greater than 2000 gets displaced in Firefox

### ISSUE THREAD

**Issue by creole** [photonstorm/phaser#2993]
I don't know if this is an issue with Phaser or with Firefox, but if I do:

var style = { font: a, fontStyle: b, fontWeight: c, fontSize: d, align: 'center' };
var text = game.add.text(x, y, s, style);

and d (fontSize) > 2000

then the rendered text gets displaced in Firefox (compared to Chrome and Edge). If the fontSize is smaller than 2000, then there is no displacement.

Using Phaser 2.6.2 and latest Firefox on Windows.

**Comment by nimohe** [comment]
hi @creole  I tested on my computer ,it can show text content(font-size=2050px) in my FireFox.

you can click this demo link:[demo link](https://nimohe.github.io/test-fontSize-phaser/)

> demo tip:the text can drag

Phaser ver : 2.6.2
Firefox ver : 51.0.1 (x86) 

so you can check your code again.Maybe something is wrong.Hope can help you.

**Comment by creole** [comment]
hi @nimohe, thanks for making that demo.  It demonstrates the issue I described: in Firefox the cross of the "t" is situated lower than in Chrome. The displacement would show more clearly if you added another text (under 2000px) to the scene as a reference point. Also, the bigger the fontSize, the larger the displacement.

Chrome 56.0.2924.87
Firefox 51.0.1 (32-bit)

**Comment by photonstorm** [comment]
There's nothing you can do about this I'm afraid, the issue is the way Firefox and Chrome differ in their implementation of the Canvas FillText method when you use insanely large font sizes (and yes, 2000px is insanely large). For Text objects all Phaser does is create an internal canvas, draw text to it using the canvas API and then render it. You're at the mercy of the browser as to how that text is drawn.

**Comment by creole** [comment]
@photonstorm Good to know, thanks.

**Comment by creole** [comment]
@photonstorm Would using BitmapText be a way around this issue (if I insisted on using insanely large fonts)?

**Comment by photonstorm** [comment]
Depends on the font as to how that would look. If it's a smooth font, with lots of curves, then at that resolution it would look extremely chunky. Try it and see though.

For text genuinely that large, the only way of not blowing all your GPU RAM would be to use the DOM instead.

**Comment by creole** [comment]
OK, thanks.
