### ISSUE TITLE
NS_ERROR_OUT_OF_MEMORY in Firefox with Phaser.Text and fontSize = 2000

### ISSUE THREAD

**Issue by creole** [photonstorm/phaser#2994]
Trying to display unicode symbol ◉ at a fontSize of 2000 (or thereabouts) leads to the following error in FF 51.0.1 (32-bit):

NS_ERROR_OUT_OF_MEMORY

The error references the following line in phaser-no-physics.js (2.6.2):

if (!context.getImageData(0, 0, width, height))

There is no error in Chrome.

**Comment by photonstorm** [comment]
The problem is right there, you've run FF out of memory by trying to create a canvas too large for it to handle on whatever device you tested it on.

**Comment by creole** [comment]
Right, okay.
