### ISSUE TITLE
Sprites flicker for 1 frame after call to reset() (v2.6.2)

### ISSUE THREAD

**Issue by kylepaulsen** [photonstorm/phaser#2995]
This Issue is about:
* A bug in the API (Version 2.6.2)
* A problem with my own code ??

If I use an old version, the last working one appears to be v2.4.8

This might also have to do with the fact that I'm using generators or async await.

I read that I should call preUpdate() so I have that everywhere. It seems to make it a little better?? Now only the emitters flicker sometimes.

When running the code, it seems random if the flicker happens so press the reset button 3-5 times.

jsbin: https://jsbin.com/yebizajeke/1/edit?html,js,output

code (just in case):
```
/*
HTML:
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
<body>
  <script>window.module = {};</script>
  <script src="https://raw.githack.com/tj/co/master/index.js"></script>
  <script src="https://raw.githack.com/photonstorm/phaser/v2.6.2/build/phaser.min.js"></script>
  <!-- last working version? -->
  <!-- <script src="https://raw.githack.com/photonstorm/phaser/v2.4.8/build/phaser.min.js"></script> -->
</body>
</html>
*/
// noprotect
var co = window.module.exports.co;
var width = 500;
var height = 400;
var game = new Phaser.Game(width, height, Phaser.AUTO, 'phaser-example', { preload: preload, create: create, update: update });

function preload() {
    game.load.baseURL = 'http://examples.phaser.io/assets/';
    game.load.crossOrigin = 'anonymous';
    game.load.image('phaser', 'sprites/phaser-dude.png');
}

var rockets;
var text;
var numRockets = 20;

function sleep(ms) {
    return new Promise(function(res) {
        setTimeout(res, ms);
    });
}

//async function reset() {
var reset = co.wrap(function*() {
    var rocket;
    while (rocket = rockets.getFirstExists(true)) {
        rocket.kill();
        rocket.preUpdate();
        rocket.fireTail.preUpdate();
    }
    // await sleep(1000);
    yield sleep(1000);
    for (var x = 0; x < numRockets; x++) {
        fireRocket();
    }
});

function create() {
    text = game.add.text(200, 250, 'Reset');
    text.fill = '#ffffff';
    text.inputEnabled = true;
    text.events.onInputDown.add(reset, this);
  
    rockets = game.add.group();
    rockets.enableBody = true;
    rockets.physicsBodyType = Phaser.Physics.ARCADE;
    rockets.createMultiple(numRockets, 'phaser');
    rockets.setAll('anchor.x', 0.5);
    rockets.setAll('anchor.y', 1);
    rockets.forEach(function(rocket) {
        var emitter = game.add.emitter(0, -40, 20);
        emitter.makeParticles('phaser');
        emitter.gravity = 0;
        emitter.maxParticleScale = 0.5;
        emitter.minParticleScale = 0.5;
        emitter.setXSpeed(-20, 20);
        emitter.setYSpeed(-50, -30);
        emitter.start(false, 500, 50);
        rocket.fireTail = emitter;
        rocket.addChild(emitter);
    }, this);
  
    for (var x = 0; x < numRockets; x++) {
        fireRocket();
    }
}

function update() {
  //console.log(game.time.fps);
}

var rad2ang = 180 / Math.PI;
function fireRocket() {
    var rocket = rockets.getFirstExists(false);
    if (rocket) {
        var xPos = Math.floor(Math.random() * width + 20) - 10;
        rocket.preUpdate();
        rocket.fireTail.preUpdate();
        rocket.reset(xPos, -10);
        rocket.preUpdate();
        rocket.fireTail.preUpdate();
        var xMidDiff = width / 2 - xPos;
        if (!xMidDiff) {
            xMidDiff = 1;
        }
        var angle = Math.atan((height - rocket.body.y) / xMidDiff) * rad2ang + 90;
        if (angle > 90) {
            angle += 180;
        }
        rocket.angle = angle;
        game.physics.arcade.velocityFromAngle(rocket.angle + 90, 100, rocket.body.velocity);
    }
}
```

**Comment by kylepaulsen** [comment]
I noticed that jsbin broke my example of the bug with its "protect" stuff, so I updated the link.

**Comment by kylepaulsen** [comment]
I think I figured something out!! This doesn't happen on a screen with a 60Hz refresh rate. I run my monitors at 144Hz and I noticed that when I switch them back to 60, the flicker is gone! I also noticed it happens at 85Hz.

So something crazy is going on when the canvas tries to render at something higher than 60Hz. I wonder how many games have this flicker effect in the wild.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.

**Comment by photonstorm** [comment]
Sorry, just to add that I bet this is linked with an issue with Hz other than 60 + requestAnimationFrame. I'll look into it for v3 carefully.
