### ISSUE TITLE
Uncaught ReferenceError: PIXI is not defined

### ISSUE THREAD

**Issue by tuiqu** [photonstorm/phaser#2998]
hello, I use npm+webpack+es6  to manege my project. 
It wii be error '**Uncaught ReferenceError: PIXI is not defined**' when I user <pre>import Phaser from "Phaser" </pre>

**Comment by tuiqu** [comment]
![qq 20170310174150](https://cloud.githubusercontent.com/assets/20797357/23790219/364431d4-05b9-11e7-8094-707b73758926.jpg)
![qq 20170310174324](https://cloud.githubusercontent.com/assets/20797357/23790221/368be182-05b9-11e7-9a9c-50089bbe9877.jpg)
![qq 20170310174353](https://cloud.githubusercontent.com/assets/20797357/23790223/36d6e736-05b9-11e7-91af-341bfd482bf6.jpg)

**Comment by tuiqu** [comment]
This usage  wii be ok ;
![qq 20170310174524](https://cloud.githubusercontent.com/assets/20797357/23790324/92364a40-05b9-11e7-81c5-6ce7483c5315.jpg)
cloud you tell me why ,and how to do.

**Comment by lucasjohnson** [comment]
You need to locate the pixi.js file and include that as well

**Comment by samme** [comment]
https://github.com/photonstorm/phaser/blob/master/README.md#browserify--cjs

**Comment by webcaetano** [comment]
@tuiqu config a your `webpack`.
```
"externals": {
    "Phaser": "Phaser",
}
```

Not a phaser bug.
This can be closed.

**Comment by GAumala** [comment]
Hello everyone, I'm new to phaser. I had this exact issue today with Webpack 3. The config posted in the README didn't work. Maybe it targets an older version of Webpack? Anyway, here is the config that worked for me:

``` javascript
// webpack.config.js
const path = require('path');
const webpack = require('webpack');

const phaserModule = path.join(__dirname, '/node_modules/phaser/');
const phaser = path.join(phaserModule, 'build/custom/phaser-split.js'),
  pixi = path.join(phaserModule, 'build/custom/pixi.js'),
  p2 = path.join(phaserModule, 'build/custom/p2.js');


module.exports = { 
  ...
  module: {
    rules: [
      {
        test: /(phaser-split|p2|pixi).js$/,
        use: 'script-loader'
      }
    ]
  },
  resolve: {
    alias: {
        'phaser': phaser,
        'pixi.js': pixi,
        'p2': p2,
    }
  }
  ...
}
```
Maybe the README should be updated? I could send a PR.
