### ISSUE TITLE
tween loop or no ?!?

### ISSUE THREAD

**Issue by kPlusPlus** [photonstorm/phaser#3000]
function moveBal(n) {
            if (n < baloni.children.length) {
                var balonX = gWidth * Math.round();
                var balonY = gHeight * Math.round();
                var timeFor = moveTime * Math.round();
                game.add.tween(baloni.children[n]).to({ x: balonX, y: balonY }, timeFor, Phaser.Easing.Quadratic.InOut, true,5,-1,true);
            }
        }

once move and stop, why ?

**Comment by halilcakarr** [comment]
if i understand this correctly that baloni is a phaser group and you are checking if n inside of range of childrens array. First please make sure that if condition is passed correctly, maybe console something inside, and your tween seem's to be okey for loop and yoyo.

**Comment by kPlusPlus** [comment]
* v2.6.2 "Kore Springs"

**Comment by halilcakarr** [comment]
Okey then, if there anything can stop tween and did you check that moveBal() functions if condition? Is it pass ?

**Comment by kPlusPlus** [comment]
game.tweens.removeAll();
game.tweens.removeFrom(baloni.children[i]);

**Comment by kPlusPlus** [comment]
http://kplusplus-001-site1.atempurl.com/babalon.html

**Comment by samme** [comment]
This doesn't look like a Phaser bug. Can you post on <http://www.html5gamedevs.com/forum/14-phaser/> and close this?

**Comment by kPlusPlus** [comment]
Phaser have tween collection in tween manager.
Some test operation dont work, I know that's problem in core of phaser.
I need it, if I must create new phaser rootines for this ...

**Comment by photonstorm** [comment]
In your code you are giving the Sprites both P2 physics and tweens. You can't have both, pick one or the other. Either physics or a tween moves the sprite, it's up to you which.
