### ISSUE TITLE
Phaser Tween or deep sh...t

### ISSUE THREAD

**Issue by kPlusPlus** [photonstorm/phaser#3004]
http://kplusplus-001-site1.atempurl.com/babalon.html

I need just all of this balloons move it non stop (NO STOP).
I cant how to do, tween manager, list, collection, disflection, desirecton, who is kill Kenedy ?
Phaser support -1, CE -10.
I have dead line for this simple application and now is droped.

**Comment by photonstorm** [comment]
This isn't a Phaser bug report. Please open questions related to errors / problems in your own code in the Phaser Forum, or ask on the Phaser Slack channel (which is probably better if you're on a deadline).
