### ISSUE TITLE
Blur Filter example not working

### ISSUE THREAD

**Issue by JarLowrey** [photonstorm/phaser#3005]
This Issue is about (delete as applicable)

* An error in the documentation

[This example](https://phaser.io/examples/v2/filters/blur) has 404 errors on the Blur filters. Actually it seems like multiple filters are missing their files - https://phaser.io/examples/v2/category/filters

**Comment by hdodov** [comment]
The code itself is also wrong:
```
game.load.script('filterX', 'https://cdn.rawgit.com/photonstorm/phaser/master/filters/BlurX.js');
...
var blurX = game.add.filter('BlurX');
```
It's saved in the cache with key `filterX`, but used as `BlurX`.

**Comment by damienleroux** [comment]
+1

**Comment by photonstorm** [comment]
All of the filter examples have been updated and now work on the Phaser site.

**Comment by manorius** [comment]
The blur example is not working again

**Comment by SxcretGit** [comment]
The blur exemple is not working again !! Help please
