### ISSUE TITLE
Phaser.Keyboard lastChar

### ISSUE THREAD

**Issue by digitsensitive** [photonstorm/phaser#3006]
Hello there!

I'm having the issue, that I can not access lastChar before any key has been pressed. I always get the following error:

`phaser.js:44758 Uncaught TypeError: Cannot read property 'charCode' of null`

If I press a key very quick before the game starts it works because lastChar seems not to be undefined.

I guess in this part lies the error:

```
Object.defineProperty(Phaser.Keyboard.prototype, "lastChar", {

    get: function () {

        if (this.event.charCode === '32')
        {
            return '';
        }
        else
        {
            return String.fromCharCode(this.pressEvent.charCode);
        }

    }

});
```

**Comment by photonstorm** [comment]
You can either raise it as an issue over on the Phaser CE repo, where I'm sure someone will patch it. Or if you need a local fix then I'd suggest just populating `pressEvent` with a dummy object that contains a `charCode` property set to some value (32 perhaps).

**Comment by digitsensitive** [comment]
Thank you! I have moved it to Phaser CE.
