### ISSUE TITLE
 Vector.js  has bug

### ISSUE THREAD

**Issue by GStones** [photonstorm/phaser#3009]
path:phaser/v3/src/physics/matter-js/geometry/Vector.js

error:
    Vector.angle = function(vectorA, vectorB) {
        return Math.atan2(vectorB.y - vectorA.y, vectorB.x - vectorA.x);
    };
right：
 Vector.angle = function(vectorA, vectorB) {
       let a = Vector.normalise(vectorA);
       let b = Vector.normalise(vectorB);
       return Math.atan2(Vector.cross(a,b), Vector.dot(a,b));
    };

no thanks!  just tell me 雷锋！

**Comment by photonstorm** [comment]
This file is part of https://github.com/liabru/matter-js - although I'd be genuinely surprised if something so fundamental hadn't yet been noticed by @liabru !

**Comment by liabru** [comment]
Thanks for reporting but this isn't an error, see the first answer in this [thread](https://gamedev.stackexchange.com/questions/69649/using-atan2-to-calculate-angle-between-two-vectors). The angle returned by `Vector.angle` is the one drawn in red in the diagram, which is the definition as used by one or two functions inside Matter.js.

**Comment by photonstorm** [comment]
Yeah I didn't think it was, thanks for responding @liabru - am closing this off.
