### ISSUE TITLE
More accurate line/rect intersection.

### ISSUE THREAD

**Issue by cursorial** [photonstorm/phaser#3019]
Apologies if this is already done or *being* done but I couldn't see any evidence of it.

I've been working on an interesting issue where I wanted to do some raycasting, where sprites would block the rays from continuing, after searching high and low I couldn't find anything, the closest I got was the Line.intersects(line) function and the Line.intersectsRectangle(line, rect) function. I needed something in the middle, I needed to find out what the closest intersection point was between the line and the rectangle.

I wrote a function to do this, there's a couple of images here to demo what I mean:
Before:
![lightshow](https://user-images.githubusercontent.com/2265262/27078789-ffe10b3a-502c-11e7-9d7f-8cb7f88d3996.gif)

After:
![screen shot 2017-06-13 at 11 31 10](https://user-images.githubusercontent.com/2265262/27078795-03555924-502d-11e7-8aae-f9d0e9157cdf.png)

Essentially when the rays hit a sprite it culls the ray short at the closest intersection point.

(I'm also looking to do this with the Tilemap at some point but I'm not sure if this should be a separate issue all together, if I understand the code for raycasting and tilemaps is a whole different area, possibly an area to be improved here?)

Should I submit a pull request with my new function in it or is this deviating too far from the functionality we're looking at or even if it's going to be in the right place in the Line class? Also, not sure what to call this function, intersectsRectAt?

Pastebin so you can see the (still not tidied up) code: https://pastebin.com/FSHZppaG

**Comment by photonstorm** [comment]
Looks very useful! I would ask on the [Phaser CE](https://github.com/photonstorm/phaser-ce) repo if they want it merged there (I would imagine so if it's a simple addition) as we can't merge it into v2 here I'm afraid.
