### ISSUE TITLE
duplicate identifier errors

### ISSUE THREAD

**Issue by marzsocks** [photonstorm/phaser#3023]
Lots of  duplicate identifier errors due to conflict between phaser and pixi. E.g.
phaser.comments.d.ts and pixi.comments.d.ts etc.

Steps to Reproduce

Install latest version of TS (2.3+)
Create an empty asp.net visual studio project in VS2017
Add the collection of latest Phaser typescript definitions to project
errors... lots of them

**Comment by photonstorm** [comment]
Thank you for taking the time to work on this and open your pull request. However, Phaser 2 is now maintained in the [Phaser CE GitHub repo](https://github.com/photonstorm/phaser-ce). If the issue still exists in Phaser CE then please submit your issue there and I'm sure the community will be able to help out or offer guidance.
