### ISSUE TITLE
Accidental global variable `game`

### ISSUE THREAD

**Issue by rblopes** [photonstorm/phaser#3030]
This Issue is about a bug in the API.

Somehow, a `game` variable is being accidentally declared in the global scope. I could not determine what module is leaking that variable.

![spectacle tt9109](https://user-images.githubusercontent.com/61425/27834858-04363b28-60af-11e7-8091-c4b6b304c6f3.png)

The screenshot is from the Labs examples, but I can confirm the problem is still present in the latest HEAD as well (f79db37cdafd63c799fddb4c31dfab55592541c4 as of this post).

**Comment by photonstorm** [comment]
This is done on purpose and will remain in place until we hit release.

**Comment by rblopes** [comment]
Good to know, thanks.

**Comment by photonstorm** [comment]
If you want to disable it, it's done in Game.js at the end of the constructor.
