### ISSUE TITLE
TriangleToCircle containment bug

### ISSUE THREAD

**Issue by Antriel** [photonstorm/phaser#3033]
This Issue is about: A bug in the API

`Phaser.Geom.Intersects.TriangleToCircle(triangle, circle)` doesn't work for containment test (i.e. when not intersecting any edges).
I would create a PR but I'm not sure which option you like better, we need to either change:
`if (Contains(triangle, circle))` to either:
- `if (ContainsPoint(triangle, circle))` 
- `if (Contains(triangle, circle.x, circle.y))`.

**Comment by photonstorm** [comment]
I would use 'Contains' as it keeps it clear you're checking the circles mid point.
