### ISSUE TITLE
npm: @3.0.0-alpha.2 is under a different dist-tag

### ISSUE THREAD

**Issue by rblopes** [photonstorm/phaser#3036]
Hi again.

It seems the Alpha 2 package published earlier today is under a dist-tag other than the `alpha` one. Issuing `npm install phaser@alpha` still fetches the 1st alpha at the moment.

Using `npm dist-tag ls phaser` to show available dist-tags shows the following:

```
alpha: 3.0.0-alpha
latest: 2.6.2
phaser@3.0.0-alpha.2: 3.0.0-alpha.2
```

I believe you can fix this using [`npm dist-tag`](https://docs.npmjs.com/cli/dist-tag) as explained in its documentation. This is a minor issue, but it may confuse users trying Phaser 3 alphas via npm later.

Of course, `phaser@3.0.0-alpha.2` can be installed using its full version tag.

**Comment by photonstorm** [comment]
I'll see if it's an easy change and if so make it, although the newsletter specifically said to use the full tag, not the short form so it shouldn't cause any issues there.

**Comment by photonstorm** [comment]
Ok all done in npm too.
