### ISSUE TITLE
Animation is slow in mobile devices (Specially in Android devices), any suggestion or fix?

### ISSUE THREAD

**Issue by mamallana** [photonstorm/phaser#3037]
Code Eg:
`sprite.animations.add('congrats', Phaser.Animation.generateFrameNames('Congratulations', 1, 140, "", 4), 20, true);
 sprite.animations.play('congrats', 20, false,true);`

**Comment by photonstorm** [comment]
Thank you for taking the time to open your issue. However, Phaser 2 is now maintained in the [Phaser CE GitHub repo](https://github.com/photonstorm/phaser-ce). If the issue still exists in Phaser CE then please submit your PR there and I'm sure the community will be only too happy to merge it.
