### ISSUE TITLE
Need normal tutorial "Hello world" (Phaser 3)

### ISSUE THREAD

**Issue by gerchicov-bp** [photonstorm/phaser#3038]
Tried to learn how to create a game with phaser from zero...
http://phaser.io/tutorials/getting-started
Describes how to setup webserver, download the phaser sources and how to run semiprecompiled "helloworld" which links to "minimal" remote phaser. Missing middle part:
1)how the phaser sources become minimal?
2)difference between sources and minimal?
3)do I need phaser sources at all or I could download the minimal version from somewhere else and place it locally?
4)a lot of examples are good but blow up the phaser size and of course most of them are extra. How to delete them?

Look likes the following picture:
![how-to-draw-a-horse](https://user-images.githubusercontent.com/11498205/28964871-4f4056f0-7917-11e7-997e-bc4dc9849fc2.jpg)

**Comment by photonstorm** [comment]
This isn't a Phaser 3 issue, but to cover it:

The tutorial linked is how get started making a Phaser game. You don't need to build Phaser to do this, but that is a pretty deep topic in itself and is linked directly from the GitHub README: https://github.com/photonstorm/phaser#building-phaser as well as on the Phaser site. There is no point throwing this at someone in a getting started guide, it's too much, too fast, and is about web development, not game development.

I don't understand what question 4 is asking.

**Comment by gerchicov-bp** [comment]
@photonstorm 
In general I downloaded phaser 3 and "helloworld". How to link this phaser 3 with "helloworld" and how to remove all the extra files from result? As I see I should at least remove "dev-guide" folder

**Comment by rblopes** [comment]
@gerchicov-bp are you having trouble setting up a project with Phaser 3?

You could just download an alpha build from the [releases page](https://github.com/photonstorm/phaser/releases) and start a bare minimum "Hello World" with some code like this:

```js
const game = new Phaser.Game({
    width: 640,
    height: 480,
    scene: {
        create() {
            const x = this.cameras.main.width / 2;
            const y = this.cameras.main.height / 2;

            const text = this.add.text(x, y, 'Hello, World!', {
                font: '64px Arial',
                fill: '#00ff00'
            });
            text.setOrigin(0.5);
        }
    }
});
```

Or you could clone the [example project](https://github.com/photonstorm/phaser3-project-template) for a more advanced project setup. Is that what you're looking for?

**Comment by gerchicov-bp** [comment]
@rblopes thanks. It is enough for me

**Comment by photonstorm** [comment]
Ok, that makes more sense. There is no "hello world" for Phaser 3 yet, as it hasn't been written. The one you linked is for v2 and I know won't work properly with v3. Keep an eye on the newsletter / dev logs, as we release more things like this over the coming months.
