### ISSUE TITLE
[Question] Isometric support?

### ISSUE THREAD

**Issue by DylanC** [photonstorm/phaser#3043]
Will Phaser 3 have built in Isometric support or maybe a plugin?  I'm holding off development on my project until Phaser 3 is released as I read somewhere it worked when you tried a simple test with some new code.

Another option would be to use Phaser 2 with the isometric plugin but I think it may be buggy at this point and I would prefer to use Phaser 3 as the platform for our game.

Thanks for this awesome project.

**Comment by photonstorm** [comment]
Hi,

We worked hard on making z-depth sorting really easy in Phaser 3, specifically for isometric and 2.5D game support. We won't have time to include isometric map import in the first release, but it will definitely be coming, and more importantly, the renderer is already set-up to handle it easily (if you wanted to roll your own in the meantime).

**Comment by DylanC** [comment]
@photonstorm - That sounds amazing. Thanks for getting back to me! I think I will wait it out. I have much backend programming to do before I get to the frontend.
