### ISSUE TITLE
Object jumping issue when player and object body touch/hit

### ISSUE THREAD

**Issue by mamallana** [photonstorm/phaser#3044]
I have sprite/object image placed using Revolute join and it will be in a kind of osculation, when we hook the player and the player reach the object/ hit that object, object is jumping. 

If keep that sprite body as static (this.sprite.body.static = true ) it will not jump but the osculation will not work.

Please some suggest me on this.

**Comment by photonstorm** [comment]
Questions like this are best asked on the forum, as they're not an actual issue with the framework itself.

http://www.html5gamedevs.com/forum/14-phaser/
