### ISSUE TITLE
Audio not audible on iPads 

### ISSUE THREAD

**Issue by mansa-dev** [photonstorm/phaser#3064]
HI,

I am using Caemlyn version.

I have an very strange sound issue on iPads(Chrome, Safari 11). Audio plays very smooth while playing game but once going on another tab or minimising tab on MAC(Inactivate game tab) for few seconds, and starts playing game after making tab activate, None audios are audible. audio.isPlaying returns true, audio.mute returns false. 
Will be great if someone can help......

Thanks
Mansa Dev

**Comment by photonstorm** [comment]
Sorry but Caemlyn is version 2.6.1 of Phaser, which was released in July 2016 - so is pretty old now and iOS has changed a lot since then. I would strongly recommend upgrading to a more recent version of Phaser CE.

**Comment by mansa-dev** [comment]
Hi

Thanks for your reply, we upgrade our Phaser version to CE but no luck. Audios are still inaudible. We are using Chrome 61.0 on iOS 11.0 (15A372).

Please suggest .

Thanks
Mansa Dev
