### ISSUE TITLE
None of the hitArea examples are working

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3067]
In Firefox 56, I get the same error with all hitArea examples ([ellipse](http://labs.phaser.io/view.html?src=src\input\mouse\ellipse%20hit%20area.js), [triangle](http://labs.phaser.io/view.html?src=src\input\mouse\triangle%20hit%20area.js), [polygon](http://labs.phaser.io/view.html?src=src\input\mouse\polygon%20hit%20area.js) and [shape](http://labs.phaser.io/view.html?src=src\input\mouse\shape%20hit%20tests.js)): in all cases, the error is `sprite.setHitArea is not a function`. The examples do not work as a result of this.

**Comment by photonstorm** [comment]
Yes, good point. I removed that method but obviously didn't update the examples. The correct method is `setInteractive`. I've updated the input examples and pushed them up, so they should all work now.
