### ISSUE TITLE
Text origin values are not calculated correctly causing it to not be displayed v3.0.0-beta.6

### ISSUE THREAD

**Issue by pavle-goloskokovic** [photonstorm/phaser#3068]
This Issue is about:
* A bug in the API v3.0.0-beta.6

I've created a repo for purposes of testing Phaser 3 here: [https://github.com/pavle-goloskokovic/phaser3-test](https://github.com/pavle-goloskokovic/phaser3-test).

I used code from this example [http://labs.phaser.io/view.html?src=src\game%20config\game%20title.js](http://labs.phaser.io/view.html?src=src\game%20config\game%20title.js) with addition of mr doob stats.js and some minor changes to the example code.

If you run code from the repo it should display an image and text like in the example but instead the text is not being displayed. 
I found that there is an issue with calculation of values for `originX`, `displayOriginX`, `displayOriginY`, and `originY` as they all have the value of `NaN`.

If you uncomment this block of code https://github.com/pavle-goloskokovic/phaser3-test/blob/master/src/js/game.js#L38-L41 to set values to 2 (same as the image) then the text is being displayed correctly.

**Comment by msickle** [comment]
I also saw this issue.  The example I was using was http://labs.phaser.io/edit.html?src=src\components\data\after callback.js

When I replaced beta 6 with beta 5 the text displayed fine.

**Comment by photonstorm** [comment]
Thanks, missed a spot where origin was set. Fixed now.
