### ISSUE TITLE
Phaser breaks for browsers that don't support URL API v3.0.0-beta.6

### ISSUE THREAD

**Issue by pavle-goloskokovic** [photonstorm/phaser#3069]
This Issue is about:

* A bug in the API v3.0.0-beta.6

I've created a repo for purposes of testing Phaser 3 here: 
[https://github.com/pavle-goloskokovic/phaser3-test](https://github.com/pavle-goloskokovic/phaser3-test)

If you try to run code from this repo in any browser that does not support [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL) it breaks on this line:
[https://github.com/photonstorm/phaser/blob/master/v3/src/loader/filetypes/ImageFile.js#L75](https://github.com/photonstorm/phaser/blob/master/v3/src/loader/filetypes/ImageFile.js#L75)
with `URL` being `undefined` and this error message:
> Unhandled Error: Cannot convert 'URL' to object

Here is a table of browser support for URL API: 
[https://developer.mozilla.org/en-US/docs/Web/API/URL#Browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/API/URL#Browser_compatibility)

**Comment by photonstorm** [comment]
Have added a window.URL polyfill that should sort this out.
