### ISSUE TITLE
Mouse position is offset with absolute positioning of canvas

### ISSUE THREAD

**Issue by msickle** [photonstorm/phaser#3070]
In Phaser2 I used a standard page template that used absolute positioning to center the canvas.  No issues.

I was pulling in Phaser3 examples to try out and ran into an issue with absolutely positioning canvases.  The mouse position is offset by as much as the absolute positioning is applied.  

I am just spitballing here but Phaser seems to read the mouse coordinates from the position of the parent container now instead of the canvas actual position.

The sample code I used was: http://labs.phaser.io/view.html?src=src\geom\intersects\rectangle%20to%20triangle.js

Specifically:
    document.addEventListener('mousemove', function (event) {
        Phaser.Geom.Triangle.CenterOn(triangle, event.clientX, event.clientY);
    });

I tried 3 different geometry intersects examples and they all behaved the same.  I changed out phaser3 for betas 4, 5 and 6 and behavior was the same.  Again, the following CSS setup works fine in Phaser 2, multiple versions.

This CSS will show the issue on a page with just one div, #phaser-example and a phaser game at 800x600 on an average sized page.

```
#phaser-example {
    background-color: #888;
    height: 100vh;
    width: 100vw;
    position: relative;
}
canvas {
    position: absolute;

    /* Simplest version to show pointer offset.  By increasing the top offset 
        the mouse position will move further and further */
    top: 120px;

    /* Original CSS also shows issue - shows offset to right and down
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
    */
}
```

**Comment by photonstorm** [comment]
That example just uses the DOM mouse move event, as it was written before I had completed the new Input classes. What about the actual input examples? Like input/game object/on down event, and so on?

**Comment by msickle** [comment]
Oh great call, I did not realize that.  I tried now with an input example "circle hit area" and the mouse position does read properly.  Thanks!

**Comment by photonstorm** [comment]
Sorry, going to re-open this as it's a good reminder to fix the example! (if you spot any more, please tell me so I can fix them)

**Comment by photonstorm** [comment]
Ok, all examples now use proper phaser input API, not dom events.
