### ISSUE TITLE
Using modern JavaScript conventions on Phaser 3

### ISSUE THREAD

**Issue by anaibol** [photonstorm/phaser#3074]
The JavaScript community have been developing some conventions like using 2 spaces, using functional programming (forEach => map, for example), using arrow functions.. Do you think I could contribute doing that on the examples or the webpack boilerplate maybe? We could also add an ".editorconfig" and eslint.

**Comment by photonstorm** [comment]
Hi,

We have an `editorconfig` and `eslint` config on the main repo, which we adhere to quite strictly. They're configured to match the way we work and I don't want to change them at this point. However, adding them to the examples repo feels a little heavy-handed. I'm not sure I like the idea of enforcing anything there, as it's just an examples repo. A lot of the code is for quick tests or demonstrations and it really doesn't matter too much if it conforms to any standard or not.

The template repos though would be a perfect candidate for it. So you're welcome to update those to add in both features.

Cheers,

Rich

**Comment by anaibol** [comment]
Cool!
