### ISSUE TITLE
Group.add() doesn't add children to display list

### ISSUE THREAD

**Issue by iamchristopher** [photonstorm/phaser#3080]
This Issue is about (delete as applicable)

* A bug in the API (always say which version you're using!)
3.0.0-beta.7

Much like #3052, I'm not sure if this is a bug but it definitely seems counter-intuitive to me..

It is possible to use the following snippet to add a `Sprite` to a `Group` and have it shown on-screen:

```js
const group = this.add.group();
group.create(0, 0, 'player');
```

However, using the following snippet to add a custom `Sprite` does not show the results on-screen:

```js
const playerSprite = new PlayerSprite(/* .. */); // extends Phaser.GameObjects.Sprite
const group = this.add.group();
group.add(playerSprite);
```

From what I can tell this is because `Group.add()` and `Group.addMultiple()` don't include this line:

```js
this.scene.sys.displayList.add(child);
```

If this behaviour is intentional, please let me know if I should be using another method. Otherwise, I'd be happy to submit a PR to fix.

**Comment by photonstorm** [comment]
It is intentional because Groups aren't Display Objects in v3. They're just buckets of objects and non-exclusive ones at that (a single Sprite can exist in multiple Groups now).

If you use `Group.create` then it'll create the object and add it to the lists for you, but `Group.add` assume the object already exists and has been added where it was needed in advance. Sprites don't need to be in Groups anymore (in order to render or update), so I'm not sure if `add` should assume you always want it on the list or not. I guess it could be a method argument though?

**Comment by iamchristopher** [comment]
@photonstorm Thanks for the response! Just to clarify: are you suggesting that I call `this.sys.displayList.add(playerSprite)` (`this` being the current scene) before adding it to the Group?

Also, I [started a thread on the forums](http://www.html5gamedevs.com/topic/33705-groupadd-doesnt-add-children-to-display-list/) if you'd prefer to move discussion there.

**Comment by photonstorm** [comment]
You can just do `this.children.add(playerSprite)` from your Scene. `children` is a mapping to the Display List for the Scene.

I don't mind having it as an argument for `Group.add` though, I just want to avoid situations like this:

```
var sprite = this.add.sprite(x, y, key);
groupA.add(sprite);
groupB.add(sprite);
```

The above is perfectly valid in V3. The sprite is already on the display list, but would then be added a further 2 times as it's added to a Group. The end result won't hurt anything, I mean it won't render 3 times for example or anything like this, it's just a bit superfluous.

Happy to have people comment on it though. 1) Should `Group.add` have an argument that adds it to the display (and update) lists too? Or 2) Should `Group.add` just do it automatically anyway?

**Comment by iamchristopher** [comment]
That's a great point for a scenario I hadn't considered. Throwing my hat in the ring for option 1, with an example call being:
```js
group.add(sprite, {
    addToScene: true
});
```

**Comment by netgfx** [comment]
Agreed to add a property to add it to the display list, I like the way groups work in v3, sometimes you don't want everything added on the display list automatically.

**Comment by photonstorm** [comment]
This is now available in master branch.
