### ISSUE TITLE
Input events buggy with multiple active scenes

### ISSUE THREAD

**Issue by Twilrom** [photonstorm/phaser#3085]
If you register for an input event you'll get one event for every active scene, rather than just the scene that registered for the event.
Example:
```
new Phaser.Game({
    parent: 'phaser-example',
    width: 100,
    height: 100,
    scene: [{
        key: 'Scene 1',
        create: function() {
            this.input.events.on('POINTER_DOWN_EVENT', function (event) {
                console.log(event.camera.scene.sys.config.key);
            });
        }
    },
    {
        key: 'Scene 2',
        active: true
    }]
});
```

This will log "Scene 1" and "Scene 2" every time you click.

**Comment by photonstorm** [comment]
Yes. there's even a comment in SceneInputManager saying literally: "//  Should use Scene event dispatcher?" - which I've now swapped over, so the above situation won't happen anymore, as it will use the Scene event dispatcher instead.
