### ISSUE TITLE
phaser 3 game.destroy

### ISSUE THREAD

**Issue by nickaversano** [photonstorm/phaser#3092]
I'm trying to completely remove the Phaser.Game used by rolling my own `game.destroy` function:

```javascript
game.destroy = function() {
   this.renderer.destroy()
   this.loop.stop()
   this.canvas.remove()
}
```
It doesn't seem to completely clean up the game state, even after doing `window.game = null`. If I try to then re-create a new instance of `Phaser.Game` it doesn't run.

Is there a plan to include a function like this in the v3 release? Also what am I missing here to get this to work properly?

**Comment by netgfx** [comment]
trying to do the same, any update on this?

**Comment by nickaversano** [comment]
Seems like it's not yet implemented but is [planned to be](https://groups.google.com/forum/#!topic/phaser3-dev/1lUmy42HpAg).

**Comment by photonstorm** [comment]
Took a while, but all implemented now + an example added showing it off too.
