### ISSUE TITLE
graphics.strokeRect corners are slanted

### ISSUE THREAD

**Issue by nickaversano** [photonstorm/phaser#3093]
The following code produces an outline of the correct thickness but the corners are slanted:

```javascript
var g = this.add.graphics()
g.clear()
g.lineStyle(20, 0x2ECC40)
g.strokeRect(20, 20, 40, 40)
```

Produces
![screen shot 2017-11-16 at 6 38 08 pm](https://user-images.githubusercontent.com/5448363/32921899-8ca45eaa-cafd-11e7-8588-e7f6b866c5bc.png)

Will there be an option to set borderRadius before drawing? Either way this doesn't seem like what you would want

**Comment by Twilrom** [comment]
It's specifically a problem with the WebGL renderer. If you use the Canvas renderer you'll get hard corners. I just draw my own lines with fillRect instead.

**Comment by photonstorm** [comment]
Just to say that we applied a fix for this to the WebGL renderer, so rectangles will close off properly now:

![image](https://user-images.githubusercontent.com/164476/33405461-5f73aa7c-d560-11e7-90eb-bf96fc65ede3.png)

It's not as flexible as a line caps option, which is what is really needed, but it gives more predictable results now.
