### ISSUE TITLE
Multi line text example not behaving as expected

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3094]
The [multi line text example](http://labs.phaser.io/view.html?src=src\game%20objects\text\static\multi%20line%20text%20with%20alignment.js) doesn't seem to be working as intended. I guess the goal is to have text text written, well, in multiple lines, whereas in the current example in only displays in one line.

I have observed this in both Firefox Quantum and Chrome 62.0.3202.94.

Edit: this is the case for both multi line text examples, with or without alignment.

**Comment by photonstorm** [comment]
You're right. The problem was an array passed in the constructor failed, but via `setText` worked. Both now work :)
