### ISSUE TITLE
Text Rtl example not working

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3095]
The [text rtl example](http://labs.phaser.io/view.html?src=src\game%20objects\text\static\rtl.js) is crashing for me (in both Firefox Quantum and Chrome 62). The error is the following in both: `ReferenceError: ctx is not defined` at `rtl.js:18:5`.

**Comment by photonstorm** [comment]
Yes this was just a test file to try out a few approaches, none of which worked due to browser limitations / implementation issues :( will remove the example
