### ISSUE TITLE
The container example moves its content in the wrong direction

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3097]
This issue pertains to the [container](http://labs.phaser.io/view.html?src=src\game%20objects\container\create%20container.js) example.

A ball is added at position (0,0), within the container, and the container is moved 100 pixels to the right and towards the bottom. Normally the coordinates of the ball should become (100,100). Nothing is visible on the screen. Upon inspecting the console, you can see that the coordinates of the ball are instead (-100,-100), which is why the ball is not visible. The coordinates of the container are however correct.

I haven't looked into the code but apparently the offset of +100,+100 became -100,-100.

**Comment by photonstorm** [comment]
The Container is just a WIP and hasn't been planned out yet, so this example isn't worth exploring yet. Wait for some activity on the Container object itself and then you should see examples follow through.
