### ISSUE TITLE
Dragging sprites doesn't work

### ISSUE THREAD

**Issue by CodestarGames** [photonstorm/phaser#3100]
http://labs.phaser.io/view.html?src=src\input\mouse\drag%20sprite.js

In the example on phaser labs as well as in my own code, the "DRAG_EVENT" never fires and the sprite doesn't drag. I've tested this on sprites with physics bodies and without.

**Comment by photonstorm** [comment]
Here are the drag examples that use the correct API calls / events:

http://labs.phaser.io/index.html?dir=input/dragging/
