### ISSUE TITLE
Mobile bug on flood game example

### ISSUE THREAD

**Issue by robgraeber** [photonstorm/phaser#3102]
Hey Phaser team,

I noticed a bug with the Flood game on my iPad running iOS 11. After clicking the monsters they seem to get stuck in the corner. Screenshot attached.

![ceb516c0-6cb0-439d-ae32-ee0dbecf1a34](https://user-images.githubusercontent.com/2387719/33192243-dbf69cac-d075-11e7-855d-f28f26b5fd84.png)

**Comment by photonstorm** [comment]
Yes, it said in the newsletter this game was desktop only (for this reason, I ran out of time to debug it.)

Pretty sure it's just the issue with double pointer events firing on mobile. Will have a look when there's time.

**Comment by photonstorm** [comment]
Linked to #3127

**Comment by photonstorm** [comment]
This game now works properly on mobile.
