### ISSUE TITLE
Errors in 'bullets' example

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3106]
I encounter an error when running the [bullets example](http://labs.phaser.io/view.html?src=src\pools\bullets.js) of sprite pools:  `this.pool` on line 62 is undefined. Nevermind if this is still "wip".

**Comment by photonstorm** [comment]
You're right, we removed the Pool object as Groups can now be Pools. I'll fix the examples.

**Comment by photonstorm** [comment]
These examples are now fixed.
