### ISSUE TITLE
programmatically drawing sprites

### ISSUE THREAD

**Issue by nickaversano** [photonstorm/phaser#3107]
Rather than creating a sprite and adding it the the running scene, is there a way to programmatically draw sprites on the fly? For example, if I wanted to create a trail effect on a GameObject it would be much easier to do this with a direct draw rather than updating 10 different GameObjects. What would be the best way of doing this for both WebGL and canvas targets? (Phaser 3)

Thanks,
Nick

**Comment by Twilrom** [comment]
Perhaps you could use particles?

**Comment by nickaversano** [comment]
I guess that's one option but then I'd need to maintain a map of different particle objects for each kind of sprite I would want to draw. Ideally I want a call like canvas's `ctx.drawImage` perhaps on the graphics library like `graphics.drawImage` or `graphics.drawSprite`

**Comment by acz13** [comment]
maybe do some stuff pixi?

**Comment by photonstorm** [comment]
There's no ability to dump gl draw calls direct onto any kind of object. We have got RenderTexturess on the roadmap but even those would abstract the calls away.

**Comment by nickaversano** [comment]
That's fine, I really just want some kind of call from the graphics library or something. Looks like RenderTextures can do what I want -- thanks!
