### ISSUE TITLE
Particle emmiter example error

### ISSUE THREAD

**Issue by AngelMunoz** [photonstorm/phaser#3111]
This Issue is about (delete as applicable)
* An error on the web site

Hello I was just passing by and saw an error in one of the examples for Phaser3
specifically this
http://labs.phaser.io/view.html?src=src\game%20objects\particle%20emitter\electric.js

`"this.add.emitter" is not a function`

![screenshot_20171129_190053](https://user-images.githubusercontent.com/8684875/33407592-b003fe2a-d537-11e7-9f8d-4f44ed40b511.png)

**Comment by photonstorm** [comment]
This is now fixed in the repo.
