### ISSUE TITLE
Errors in values of two properties of zone object

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3112]
This error can be seen in the [basic zones example](http://labs.phaser.io/edit.html?src=src\input\zones\basic%20input%20zone.js). In Chrome 62, if I print one of the zone objects to the console, the field `displayHeight` has a value of `TypeError: Cannot read property 'realHeight' of undefined`, while the field `displayWidth` has a value of `TypeError: Cannot read property 'realWidth' of undefined`.

The example works perfectly well, however!
`

**Comment by photonstorm** [comment]
Hmm yes because they don't have textures, so no frame to calculate the display dimensions from. Will override this for Zone so it doesn't get exposed.

**Comment by photonstorm** [comment]
Zones have been updated and this is now fixed in master.
