### ISSUE TITLE
v3 Sound looping (repeating doesn't work)

### ISSUE THREAD

**Issue by alperakgun** [photonstorm/phaser#3114]
* A bug  in the API  v3 beta 13

```javascript
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create
    },
    pixelArt: true
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.audio('sfx',    'assets/SOME.mp3');

}

function create () {
  
    var sound = this.game.sound.add('sfx');
    sound.play( {loop: true} );
// sound.loop = true  // doesn't work neither 
}


```

**Comment by pavle-goloskokovic** [comment]
v3 Sound API is still work in progress and looping is not implemented yet, but it should be available in next few weeks.
you can follow progress in our weekly dev logs https://phaser.io/phaser3/devlog

**Comment by alperakgun** [comment]
As far as I tested this seems to work - so you may close this if needed.

**Comment by pavle-goloskokovic** [comment]
There's still some work left to be done for looping, I'll close this issue when that is finished.

**Comment by pavle-goloskokovic** [comment]
http://labs.phaser.io/view.html?src=src\audio\Web%20Audio\Loop%20Delay.js
