### ISSUE TITLE
Swipe down on phaser 3 canvas scrolls down on iOS Safari 10.3 and 11  

### ISSUE THREAD

**Issue by alperakgun** [photonstorm/phaser#3115]
* An issue/missing thing in the phaser3

ON ipad/iphone ios 10.3/11, on any game, when I need to swipe down Safari scrolls down making it impossible to play the game. On phaser2 the issue doesn't exist. 

CSS styling on the Canvas for the following didnt help.

```
canvas {
    display: block;
    touch-action: none;
    user-select: none;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```

**Comment by photonstorm** [comment]
Correct, it doesn't prevent default on the events yet and it should, or at least optionally should like V2. Have flagged for next beta.

**Comment by photonstorm** [comment]
This is now fixed in the master branch, you can specify in your game config if input events should capture input or not (default is to capture it).

**Comment by woodydeck** [comment]
Do you have an example of doing this? I'm spending way too much time trying to figure out how to do this going through the docs.

**Comment by michaltrzcinka** [comment]
@woodydeck the following fix worked for me.
I added this snippet:
```js
  input: {
    touch: {
      capture: false
    }
  }
```
to my `config` object which is passed to `new Phaser.Game`. Full code:

```js
const config = {
  type: Phaser.AUTO,
  parent: "game",
  // other config elements...
  input: {
    touch: {
      capture: false
    }
  }
}

const game = new Phaser.Game(config)
```
