### ISSUE TITLE
v3 input events: Canvas (or parents) with a padding in  percentages results in event.x and event.y to be offset wrong.

### ISSUE THREAD

**Issue by alperakgun** [photonstorm/phaser#3116]
* A bug in the API v3 Beta 13

-  Click on top, left around 0,0 on canvas.  event.x and event.y will not be 0,0 as padding won't be taken into account.

```javascript
//  canvas or any container parent  style="padding: 10%";

  this.input.events.on('POINTER_DOWN_EVENT', function (event) {
console.log(event.x, event.y);
  });
```

**Comment by photonstorm** [comment]
Wonderful, it obviously isn't taken into consideration when the DOM calculates `canvas.offsetLeft`, which is insane really as it's supposed to return a pixel value. Mind you, it returns `null` on iOS if the canvas is hidden or fixed.

**Comment by alperakgun** [comment]
I think offsetLeft gives relative to the parent only and  the only way is to use .getBoundingClientRect();

**Comment by photonstorm** [comment]
This is now fixed in Beta 14. Please let me know if it still happens though!

**Comment by alperakgun** [comment]
That works fine now - thanks a lot !
