### ISSUE TITLE
Frame's setCut doesn't take into account x (cutX) and y (cutY) attributes

### ISSUE THREAD

**Issue by alperakgun** [photonstorm/phaser#3119]
// Phaser v3 Beta 13

When I set a sprites crop the x  & y params don't have any effect. Maybe not the right method?

sprite.frame.setCut(10, 10, 30, 30)

```

// textures/Frame.js
    setCut: function (x, y, width, height)
    {
        this.cutX = x;
        this.cutY = y;

        this.cutWidth = width;
        this.cutHeight = height;

        return this.updateUVs();
    },

```

**Comment by photonstorm** [comment]
Yes, this is a bit of a legacy method actually. Will have a chat with the team and see if it's worth keeping (and fixing), or just removing.

**Comment by alperakgun** [comment]
What's the best way to crop a sprite texture it in v3?

**Comment by photonstorm** [comment]
Ideally using a mask, but for a simple crop that may be overkill, so I've added this to the list to look at soon.

**Comment by photonstorm** [comment]
I've removed `Frame.setCut` because it was misleading and didn't work. I also removed the TextureCrop.js file too. I have added 'crop support' to a list of features to consider for a post 3.0 release, but it won't make it in for 3.0 I'm afraid.
