### ISSUE TITLE
Use of reserved keyword in function argument

### ISSUE THREAD

**Issue by rblopes** [photonstorm/phaser#3123]
This issue is about a problem in one of Phaser modules.

An attempt to minify Phaser code, using a recent uglifyjs-webpack-plugin, will fail. While investigating the issue, I found that the `src/physics/matter-js/components/Friction.js` module contains a function argument named `static`.

At first, running the `dist` script will complete without fail, but the Webpack plugin included in the Phaser 3 package is outdated. Prefixing the module with a `"use strict";` line yields the following exception, though:

```
ERROR in ./physics/matter-js/components/Friction.js
Module parse failed: The keyword 'static' is reserved (5:39)
You may need an appropriate loader to handle this file type.
| var Friction = {
| 
|     setFriction: function (value, air, static)
|     {
|         this.body.friction = value;
 @ ./physics/matter-js/components/index.js 8:14-35
 @ ./physics/matter-js/MatterSprite.js
 @ ./physics/matter-js/Factory.js
 @ ./physics/matter-js/Matter.js
 @ ./scene/plugins/PhysicsManager.js
 @ ./scene/local/Systems.js
 @ ./scene/local/Scene.js
 @ ./phaser.js
```

Recent versions of the UglifyJS plugin are more sensitive, and will fail regardless the absence of `"use strict";`.

This issue will likely affect users trying dev-kits containing recent releases of UglifyJS, including the Webpack plugin.

**Comment by photonstorm** [comment]
Yeah, this was fixed in #3117 and is now merged
