### ISSUE TITLE
Resizing input zones?

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3124]
I have been playing around with the [Basic input zone](http://labs.phaser.io/view.html?src=src\input\zones\basic%20input%20zone.js) example. It seems to me that it is not possible to resize the input zones. 

For example, if we have at the beginning `var plainZone = this.add.zone(0, 0, 345, 300).setName('Plain').setInteractive();`, the label will display the text "plain" whenever I click in the rectangle (0,0,345,300). So far so good.

But if at the bottom of the file I try to change the dimensions of one of the zones, for example by adding `plainZone.setSize(100,100);`, the behavior of the example doesn't change: clicking inside the (0,0,345,300) rectangle will still trigger the event, even if I click outside the new 100*100 area. In other words, only the initial specification of the size of the input zone is taken into account.

I have tried with `setW()` and `setH()` as well, and I also tried calling `setInteractive()` after the dimension change because previous fiddling around seemed to indicate it was necessary. To no avail.

I'm not sure I'm approaching this the right way though, so the issue could be one of two possibilities:
- Either it's supposed to work that way, and apparently it doesn't;
- Either it's supposed to work differently, and then it would be great to have an example to show how to do it properly.

Thanks for considering this!

**Comment by photonstorm** [comment]
It makes sense to me that Zone should override `setSize` and push those changes through to its hit zone, as long as a custom zone hasn't been specified for it. So I'll definitely have a look at how this is implemented because it shouldn't be this confusing.

**Comment by photonstorm** [comment]
Ok, calling `setSize` now updates the input hit area, as long as the hit area has been set and is a Rectangle. Any other shape won't get set.
