### ISSUE TITLE
VertexBuffer.js:61 WebGL: INVALID_VALUE: enableVertexAttribArray: index out of range

### ISSUE THREAD

**Issue by roxydoggy** [photonstorm/phaser#3126]
The code in the following Phaser3 example:

http://dan-nuc/ph/view.html?src=src\animation\add%20animation%20event.js

throws the following warning in VertexBuffer.js

                if (element !== undefined && element !== null)
                {
                    gl.enableVertexAttribArray(element.index);
                    gl.vertexAttribPointer(
                        element.index,
                        element.size,
                        element.type,
                        element.normalized,
                        element.stride,
                        element.offset
                    );
                }

![screenshot_20171219_115022](https://user-images.githubusercontent.com/8267608/34176041-5fdd8d18-e4b3-11e7-98e7-88ebce7f4947.png)

![screenshot_20171219_114851](https://user-images.githubusercontent.com/8267608/34176038-5cdbf30c-e4b3-11e7-89f6-e5422d40dd88.png)

* A bug in the API (always say which version you're using!)

**Comment by photonstorm** [comment]
This may have been specific to the build at the time, but this example is working correctly now (against master branch), please re-open if you can reproduce it though.

**Comment by MHarris021** [comment]
@photonstorm I just opened the example and I'm still seeing the issue reported. Running on Chrome. I care, because I'm seeing this issue in my own code. My code logs it over 100 times. The example just seems to log each warning once.

**Comment by MHarris021** [comment]
@photonstorm I apologize build 14 resolves this issue. I hadn't realized that you just pushed a new build

**Comment by rblopes** [comment]
Sorry, but I can still see this warning in that and a few other examples too. I just tested the example "Add Animation Event" example, for comparison, from the Labs and also from a local copy I keep. Neither using the current build or a fresh build from `master` solves the issue.

Tested on Chrome 63 and Firefox 57. The warning on Firefox has some additional information:

```
Error: WebGL warning: enableVertexAttribArray: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program.
```
