### ISSUE TITLE
GAME_OBJECT_DOWN_EVENT event is triggered twice for mouseup and touchstart 

### ISSUE THREAD

**Issue by alperakgun** [photonstorm/phaser#3127]
GAME_OBJECT_DOWN_EVENT event is triggered twice for mouseup and touchstart.
In mobile mode in Chrome developer tools. (Maybe a feature and not a bug). 

I will test in mobile mode too.

* A bug in the API  - phaser 3 master beta 13

```javascript

      this.input.events.on('GAME_OBJECT_DOWN_EVENT', function (event) {
        console.log(event);
  }

```

**Comment by photonstorm** [comment]
Pretty sure it shouldn't do this. Will debug on Android tablet to check. Does anyone reading this have a Mac and iOS device to see if it happens on that too? (as my Mac died and I've not replaced it yet)

**Comment by pavle-goloskokovic** [comment]
@photonstorm 
I've tested it on an iPad with this example: [Markers - Pause, Resume](http://labs.phaser.io/view.html?src=src\audio\Markers%20-%20Pause,%20Resume.js) which uses `GAME_OBJECT_DOWN_EVENT` and it fires event handler twice on every touch

**Comment by photonstorm** [comment]
@pavle-goloskokovic I don't suppose you know if it fires once for mouse and once for touch, do you?

**Comment by photonstorm** [comment]
@pavle-goloskokovic also, please try master branch build, as I fixed some related issues which might stop it

**Comment by photonstorm** [comment]
Actually, I'm sure this is fixed in master now, I can't get it on Android or under emulation in Chrome after the recent changes, so I'm happy it's working as expected. What is still a problem though is the OVER_EVENT fires just before the DOWN_EVENT, which I don't think it should.

**Comment by pavle-goloskokovic** [comment]
@photonstorm I can confirm that it is fixed on iPad as well
