### ISSUE TITLE
Phaser3 - Examples/Animation/callback%20parameters.js triggers two warnings from TouchManager.js

### ISSUE THREAD

**Issue by roxydoggy** [photonstorm/phaser#3128]
Phaser3 - Examples/Animation/callback%20parameters.js triggers two warnings from TouchManager.js

See lines 69-70 in TouchManager.js:

        this.target.addEventListener('touchstart', handler, false);
        this.target.addEventListener('touchmove', handler, false);

[dan-nuc-1513804155667.log](https://github.com/photonstorm/phaser/files/1577057/dan-nuc-1513804155667.log)
![screenshot_20171220_131534](https://user-images.githubusercontent.com/8267608/34229105-ec9c72ee-e587-11e7-8d03-ee126b1e6a69.png)

**Comment by photonstorm** [comment]
Hiya - which browser is this in? As I don't see the error in Chrome or FF.

**Comment by roxydoggy** [comment]
It's in Chrome. In the Developer Tools' JavaScript console, the default filter hides warnings. If you change it to show 'All levels' I think you'll  see the warning.

**Comment by photonstorm** [comment]
Thanks, this is now covered in the master branch version. I can't mark listeners as passive because we actually need to preventDefault on them, but it appears having a `passive` object in there is enough to stop the warning.
