### ISSUE TITLE
Phaser3 - Examples/Animation/gif%20to%20animation.js triggers TypeError

### ISSUE THREAD

**Issue by roxydoggy** [photonstorm/phaser#3129]
See line 63 in http://dan-nuc/ph/src/animation/gif%20to%20animation.js:
function update ()
{
    group.rotate(data.r, data.s); // <-- Exception here...
    group.setScale(data.sx, data.sx, data.s, data.s);
    group.setXY(data.x, data.y, data.s, data.s);
}

Uncaught TypeError: group.rotate is not a function
    at Scene.update (/ph/src/animation/gif%20to%20animation.js:63)
    at Systems.step (/ph/build/dev.js:29945)
    at Game.step (/ph/build/dev.js:50580)
    at TimeStep.step (/ph/build/dev.js:78778)
    at step (/ph/build/dev.js:27543)

[dan-nuc-1513805202300.log](https://github.com/photonstorm/phaser/files/1577076/dan-nuc-1513805202300.log)
![screenshot_20171220_132630](https://user-images.githubusercontent.com/8267608/34229527-771c3b7e-e589-11e7-9cb8-bf117b01d692.png)

**Comment by photonstorm** [comment]
Thanks for reporting this. It has been fixed.
