### ISSUE TITLE
Phaser3 - Example camera\3D%20camera\fixed%20scale.js has undefined type error

### ISSUE THREAD

**Issue by roxydoggy** [photonstorm/phaser#3132]
See http://dan-nuc/ph/src/camera/3D%20camera/fixed%20scale.js, line 55:
    for (var i = 0; i < road.length; i++) // Length is undefined

/ph/src/camera/3D%20camera/fixed%20scale.js:55 Uncaught TypeError: Cannot read property 'length' of undefined
    at Scene.update (/ph/src/camera/3D%20camera/fixed%20scale.js:55)
    at Systems.step (/ph/build/dev.js:29945)
    at Game.step (/ph/build/dev.js:50580)
    at TimeStep.step (/ph/build/dev.js:78778)
    at step (/ph/build/dev.js:27543)
[dan-nuc-1513814786951.log](https://github.com/photonstorm/phaser/files/1577416/dan-nuc-1513814786951.log)
![screenshot_20171220_160959](https://user-images.githubusercontent.com/8267608/34234501-484c2bee-e5a0-11e7-8809-cfd60e48ea03.png)

**Comment by photonstorm** [comment]
This one is running properly now, maybe as a result of the last fix I just pushed.
