### ISSUE TITLE
Phaser 3 build 14 2D Camera does not respect setBounds(x, y, width, height)

### ISSUE THREAD

**Issue by MHarris021** [photonstorm/phaser#3133]
**This repo is for Phaser 3 related issues only**

Official support for Phaser 2 has now ended. We urge you to visit the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) for continued development of v2.

* A bug in the API  build 14
2d Camera will continue to scroll outside of the setbounds' rectangle's width and height if these are smaller than the scene's width and height when using the startFollow() method.

Examining the PreRender.js code reveals that the evaluation of the useBounds property sets the values for boundR and boundB using the camera's width and height instead of the _bounds.width and _bounds.height.

Assuming this behavior is in error changing the code to use the _bounds properties should fix this behavior

API errors must include example code showing what happens, and why you don't believe this is the expected behavior. Issues posted without code take _far_ longer to get resolved, _if ever_. Feel free to use a site such as jsbin to demo the problem. If we can run it, and see the error, we can usually fix it.

If your Issue contains _any_ form of hostility it will be instantly closed.

**Be nice. We do this for free.**

**Comment by photonstorm** [comment]
This is now resolved in master and I made some new examples to test it.
