### ISSUE TITLE
Phaser v3 build 14 does not implement CollideSpritevsTilemap

### ISSUE THREAD

**Issue by MHarris021** [photonstorm/phaser#3134]
**This repo is for Phaser 3 related issues only**

Official support for Phaser 2 has now ended. We urge you to visit the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) for continued development of v2.

This Issue is about (delete as applicable)

* A bug in the API (build 14)

Not certain if the feature to have sprites collide with the tilemap is simply not implemented yet or if there is an issue. Cannot detect a collide event for the Arcade Physics Engine. I believe it is unimplemented due to no class with the name in the title, as the other CollideSpritevs .... exist

Not certain if there is a roadmap with implemented features for Phaser 3. It would be handy not to bug the devs if there was such a reference.

API errors must include example code showing what happens, and why you don't believe this is the expected behavior. Issues posted without code take _far_ longer to get resolved, _if ever_. Feel free to use a site such as jsbin to demo the problem. If we can run it, and see the error, we can usually fix it.

If your Issue contains _any_ form of hostility it will be instantly closed.

**Be nice. We do this for free.**

**Comment by photonstorm** [comment]
It's not yet implemented but will be shortly. I'll leave this issue here as a notification for those who want an update when it is.

**Comment by ZaDarkSide** [comment]
This is now implemented in beta 18

https://phaser.io/phaser3/devlog/112
