### ISSUE TITLE
Phaser 3:    this.physics.add.mouseSpring()   how to remove it

### ISSUE THREAD

**Issue by alperakgun** [photonstorm/phaser#3145]
A problem with Phaser v3:

How to I remove mouseSpring() which I have added with this.physics.add.mouseSpring()?

Maybe not a bug.

**Comment by vulcanoidlogic** [comment]
Phaser version: 3.0.0-beta.18

I don't know if this is the correct or recommended way to remove mouseSpring, but this worked for me:
    const ms = this.matter.add.mouseSpring();
    console.log('Before destroy', this.matter.world);
    ms.destroy();
    console.log('After destroy', this.matter.world);

Note, however, to make this work, I first had to make the following modifications on my local copy.

**In physics/matter-js/PointerConstraint.js**
initialize method (this.world.events is undefined so ...):
        // this.world.events.on('BEFORE_UPDATE_EVENT', this.update, 0, this);
        this.world.on('BEFORE_UPDATE_EVENT', this.update, 0, this);

destroy method  (this.world.events is undefined so ...):
        // this.world.events.off('BEFORE_UPDATE_EVENT', this.update);
        this.world.off('BEFORE_UPDATE_EVENT', this.update);

**In physics/matter-js/World.js**
destroy method (it seems mouseSpring is a PointerConstraint, not a Body):
        // Composite.removeBody(this.localWorld, body, deep);
        Composite.remove(this.localWorld, body, deep);
