### ISSUE TITLE
Allow for directly passing an object instead of a path as the atlasURL

### ISSUE THREAD

**Issue by mcfarljw** [photonstorm/phaser#3147]
Right now the atlasURL can only be loaded via `xhr`, but lots of bundlers import json in to the js bundle. It would be helpful if it could check to see if the atlasURL is a string or object and handle it accordingly

**Reference:**
https://github.com/photonstorm/phaser/blob/822b3a9d0c7285331414fcaa49de0b089471d039/v3/src/loader/filetypes/AtlasJSONFile.js

**Comment by dev-zetta** [comment]
Agreed. This should be implemented, as it would help to save half of the HTTP requests thus speeding up the scene preloading.
