### ISSUE TITLE
Being able to resize the canvas dynamically

### ISSUE THREAD

**Issue by netgfx** [photonstorm/phaser#3148]
* A bug in the API latest V3

I'm trying to create multiple game objects on a single page or re-use the same game object but with new dimensions, so I have

```
 var config = {
       width: window.innerWidth,
       height: window.innerHeight,
       type: Phaser.AUTO,
       parent: "trigons",
       scene: {
           create: create,
           update: update
       }
};

var game = new Phaser.Game(config);
```

And I would like to be able to either destroy it and re-create it with different dimensions, or change dimensions dynamically (through properties or function call).

The reason for this is to use the `snapshot` functionality with a correct canvas size.

I tried resizing the canvas DOM element but it didn't produce the desired outcome.

**Comment by photonstorm** [comment]
This won't be supported until the ScaleManager lands.

**Comment by photonstorm** [comment]
Just to say that `renderer.resize` has been implemented and is working properly, and can be called by your own code whenever you need to.
