### ISSUE TITLE
Phaser CE v2.9.4 [Deprecation] GainNode.gain.value setter smoothing is deprecated.

### ISSUE THREAD

**Issue by halilcakarr** [photonstorm/phaser#3149]
I'm having the same warning on Chrome v63.0.3239.132. Firefox doesn't give any deprecation warning. I don't know what to do but all warning is like this:

[Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

![screenshot_1](https://user-images.githubusercontent.com/18047554/34674946-e4537112-f498-11e7-9b61-95c1fc205b30.png)

Is this gonna be a problem in future or what to do ? :)

**Comment by photonstorm** [comment]
Hi - This is a Phaser CE issue, please report it on the [Phaser CE repo](https://github.com/photonstorm/phaser-ce) :)

**Comment by halilcakarr** [comment]
I see, Thanks Ricard :)

**Comment by prizky** [comment]
Bodo amat

Pada tanggal 8 Jan 2018 22.07, "Halil CAKAR" <notifications@github.com>
menulis:

**Comment by serenoandrea** [comment]
Any news about this issue? Sorry but i cannot understand if this issue will be resolved on the next release of Phaser or not. Thank you.
