### ISSUE TITLE
Setting renderer type to Phaser.AUTO not working as expected

### ISSUE THREAD

**Issue by pavle-goloskokovic** [photonstorm/phaser#3159]
This Issue is about

* A bug in the API (always say which version you're using!)

If you set renderer type in game config to `Phaser.AUTO` and WebGL is not supported Phaser throws an error 
```
Uncaught exception: Error: This browser does not support WebGL. Try using the Canvas renderer.
```
instead of using Canvas renderer.
When you explicitly set type to `Phaser.CANVAS` then it works as expected.

**Comment by photonstorm** [comment]
Closed as per discussion on slack and your recent commit.
