### ISSUE TITLE
Quads ignore their this.frame when rendering spritesheet textures

### ISSUE THREAD

**Issue by halgorithm** [photonstorm/phaser#3161]
This Issue is about a bug in the API for 3.0.0-beta.20

When given a spritesheet key as their texture to render, Quads seem to ignore their this.frame property for rendering. Instead, they render an image whose width and height are the size of a single frame from their spritesheet, but the image displayed is the full texture instead of just one frame.

Here's a JSFiddle of the bug in question:
https://jsfiddle.net/wmjhy17f/

I was trying to debug this and my best guess is it's something that's happening in SpriteBatch.addMesh, possibly with it not passing uv values for the frame? But I could be wrong about this as I don't have a great idea what that code does.

**Comment by photonstorm** [comment]
Yes, Quads use a single text. Have added it as a feature request for now.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
