### ISSUE TITLE
Request: Support custom props in JSONHash & JSONArray

### ISSUE THREAD

**Issue by dev-zetta** [photonstorm/phaser#3165]
Hello everyone,

could you please add support for loading of custom properies in JSONHash & JSONArray?

For example:

`{
    "frames": {
        "test.png": {
            "customData": {
                "delta": {
                    "x": 39,
                    "y": 39
                },
               "etc.": "etc"
            },
            "frame": {
                "h": 40,
                "w": 78,
                "x": 0,
                "y": 0
            }
        }
    }
}`

So we can access them like sprite.frame.customData.delta or sprite.frame.data.delta?

**Comment by photonstorm** [comment]
What would it be used for?

**Comment by dev-zetta** [comment]
Postprocessing, for example? In my example, I use delta property to change sprite's position on screen, after the sprite is added. Once could specify there also rotation and other frame-specific stuff. Or does it sound like stupid idea?

**Comment by dev-zetta** [comment]
Or it would be great, if one could specify a callback function to atlas loader for the postprocessing purposes.

For example:
`this.load.atlas('level1', 'assets/level1/items.png', 'assets/level1/items.json', (frame, jsonFrame) => {
    frame.mydata = jsonFrame.customData
});
`
