### ISSUE TITLE
[Feature Request] Allow asset loader parameters in Game, Scene configuration.

### ISSUE THREAD

**Issue by rblopes** [photonstorm/phaser#3168]
In the current Phaser implementation, it is not possible to declare which parameters asset loaders should use _before_ their initialization.

Ideally, the Phaser `Game` configuration object should accept an option to tweak parameters and control asset loading behavior, which could occasionally be overridden should it be needed. This could be especially beneficial for file assets declared using the scene asset payload feature (a.k.a. the scene `files` field), where some of these parameters must be known before the asset payload is processed in the scene initialization.

For example, if assets are kept in a given directory in the server (e.g.: `./assets/`), files should either be prefixed with their respective paths (as most Labs examples do) or fall back to regular API methods and properties, such as setting the `Loader#path` to avoid verbosity. However, if the user need more control over the asset loader, modifying certain parameters is only possible using the loader API.

So, my suggestion is to provide a configuration key (`loader` or other appropriate name) that should be consumed by all game scenes during their initialization, setting the default URL, path, parallel loading and other parameters. Perhaps the same could be done in scenes too, merging the root configuration.

```javascript
const game = new Phaser.Game({
    width: 800,
    height: 600,
    scene: [ /* ... */ ],

    //  Example: Default parameters for all scene asset loaders.
    loader: {
        baseURL: 'http://example.com/',
        path: 'assets/',
        crossorigin: true,
        xhr: {
            timeout: 30
        }
    }
});

const exampleState = {
    key: 'example',
    
    //  Example: parameters used for this scene only (overrides root parameters)
    loader: {
        path: 'assets/example-scene/'
    },
    
    files: [ /* ... */ ],
    
    create: function () { /* ... */ }
};
```

**Comment by photonstorm** [comment]
Agreed, this makes sense.
