### ISSUE TITLE
tile.resetCollision()-related bug

### ISSUE THREAD

**Issue by nkholski** [photonstorm/phaser#3169]
Resetting collision on a previously collidable tile allows bodies to slip through conjoined tiles.

I've attached a failing example. The green sprites are constantly trying to get through to the other side of the screen. After six seconds I remove a block in their way which causes them to fall through the floor instead of running into the next block in their way as expected.

My guess it has something to do with calculating faces.

[resetCollision-bug.zip](https://github.com/photonstorm/phaser/files/1640700/resetCollision-bug.zip)

**Comment by nkholski** [comment]
Couldn't resist trying to find a solution:
`this.map.calculateFacesWithin(0,0,9,9, this.layer);`
My whole tilemap in the example is 10x10 tiles and adding this to the code after resetting collision fixes the problem, so I guess adding something like this for the surrounding tiles to the resetCollision-method would fix it.

**Comment by mikewesthad** [comment]
Thanks for submitting this!

So to summarize, the issue has to do with how AP physics works with tilemaps. There is an optimization step where "interesting" faces are calculated. When you change the collision state of tile (via `tile.setCollision(...)`, `tile.resetCollision()`), that interesting faces calculation isn't updated.

For this situation where you want to remove a colliding tile from the world, I'd recommend using `Tilemap.removeTileAt(...)` which will update the interesting faces appropriately. Regardless, I'll look into tweaking the Tile API.

**Comment by mikewesthad** [comment]
This should be fixed now. Thanks for the bug report!
