### ISSUE TITLE
[Suggestions] integration with WebWorkers and more

### ISSUE THREAD

**Issue by r-Sulfar** [photonstorm/phaser#3170]
1- It would be cool if physics computations could be run in separate threads (assuming the physics are run in the CPU instead of the GPU) via Web Workers, this way the main thread responsible for rendering would be able to handle more physics enabled game objects.

2- In my games as they grow more complex I always end up creating some kind of AI management system that also uses Web Workers to manage game objects behaviour, perhaps something like this could be implemented natively in the engine or as a plugin.

3- Support for unit testing outside the browser environment.

4- Leverage mature UI frameworks such as vue/react to provide basic UI widgets.

**Comment by bradharms** [comment]
It's worth mentioning that any time you have to work with web workers, you have to worry about serializing/deserializing all of the data to be communicated between the main thread and the workers.  Results of physics calculations have to be transmitted at least 60 times per second. This could become a bottle neck, unless you want to get REALLY fancy with data buffer sharing.

Also, web workers require code to be executed from a totally separate JavaScript file, which may put constraints on your project structure. However I know Webpack has some magic to ease support of this scenario.

**Comment by photonstorm** [comment]
The physics library would have to be written in a specific way to take advantage of WW. If one of the libs we use is upgraded to do that, we'll incorporate those changes, although due to the locality of the data with WW I'm not sure it will happen imho. We'll keep an eye on it though and also the WASM space.
