### ISSUE TITLE
"gameobjectmove" doesn't set "event.gameObject" anymore.

### ISSUE THREAD

**Issue by alperakgun** [photonstorm/phaser#3177]
Is event.gameObject not supported anymore in beta 18? or maybe a bug for Move, and maybe other events, after the new event mechanism?

```
      myScene.input.on('gameobjectmove', function (event) {
console.log(event.gameObject); //   this used to give me the gameObject

...


```
// src/input/InputPlugin.js ..  

            this.emit('gameobjectmove', pointer, gameObject);

```

**Comment by photonstorm** [comment]
The event signatures have all changed, there are no 'event' objects anymore, it always sends arguments now.

**Comment by alperakgun** [comment]
Sorry I have missed the dev logs. For other people this works now as an additional argument to event handler.

```
      myScene.input.on('gameobjectmove', function (event, gameObject) {
console.log(gameObject); //   this used to give me the gameObject

...
```
