### ISSUE TITLE
tilemap zoom, change the canvas size

### ISSUE THREAD

**Issue by RiCoTeRoX** [photonstorm/phaser#3178]
Phaser v3@latest

Showable in [here](http://labs.phaser.io/view.html?src=src%5Cgame%20objects%5Ctilemap%5Ccollision%5Cmatter.js&v=113)

Steps:
.- Fill at least half of the map with balls
.- Zoom all in
.- Zoom default
.- Canvas size changed (bug)

**Comment by photonstorm** [comment]
No matter how hard I try I cannot re-create this. I filled the entire map with balls, hit ctrl + until I couldn't zoom any further in Chrome, hit ctrl + 0 and it was still just an 800x600 canvas.

Can anyone else replicate this?

**Comment by RiCoTeRoX** [comment]
i forgot to say...
I am on macbook (touchbar) and zooming with the (big) trackpack

my bad.

**Comment by mikewesthad** [comment]
I can't replicate it either (in Chrome or FF on windows). Any chance you've got a bunch of chrome extensions installed?

**Comment by RiCoTeRoX** [comment]
yes i have some extensions but i tested without them, with the same result.
Maybe this video help. Maybe is not a bug and is only a weird behavior.
[video](https://youtu.be/ZlP0t4q0Xqo)

in the video you can see when i zoom in, the top, apparently, is of the screen is the top of the canvas.

**Comment by mikewesthad** [comment]
I'm not sure what I'm looking at here. The canvas looks to be the same size at the start of the video as it is at the end of the video.

**Comment by photonstorm** [comment]
I've watched this video several times now and I don't really get what I'm meant to be seeing either, sorry! Maybe a 'before' and 'after' screen shot would be better? or run Chrome inspector on the canvas and tell us what the size was at the start vs. the end.

**Comment by RiCoTeRoX** [comment]
the title "canvas size" maybe is not very clear.
_There are many maybe in this publication. sorry._
the behavior I want to show you is when I zoom in-out, all the balls seem to be pushed down and I think it's because the zooming.
video: 0:10 - 0:20 seconds

**Comment by photonstorm** [comment]
Ahhh ok!! It don't think it's anything to do with the zooming actually. If you just leave the simulation running they will be pushed down eventually, because matter can't cope with that many non-static, non-sleeping bodies crammed on-top of each other.

**Comment by RiCoTeRoX** [comment]
ok 👍 
feel free to close this issue 🚀

**Comment by mikewesthad** [comment]
Ditto to that - yeah, at a certain point Matter can't resolve all those tiny collisions. Thanks for pointing it out @RiCoTeRoX.
