### ISSUE TITLE
Missing DataStore

### ISSUE THREAD

**Issue by Antriel** [photonstorm/phaser#3187]
[This commit](https://github.com/photonstorm/phaser/commit/8e0732059646884ee8f4b6c8d5545e5bc201c371#diff-3d16cf5bb1d48ea5748caacc8504653bL83) broke [Html5 Audio/No Audio/Web Audio]/Markers - Play.js examples because of `gameObject.setData` usage, which accesses DataProxy (which still exists and is initialized), which internally uses `scene.sys.dataStore`, which was removed.

Not sure if the DataStore is supposed to be manually enabled (i.e. examples are bugged) or it's issue with Phaser.

**Comment by Antriel** [comment]
Checking further, 21 examples use the DataProxy.

**Comment by photonstorm** [comment]
Haven’t decided what to do with this plugin yet. Ignore for now.

**Comment by pavle-goloskokovic** [comment]
I'll update audio examples not to use it

**Comment by photonstorm** [comment]
Don't spend any time doing that mate, I'll likely add it back in, just haven't decided how yet.

**Comment by photonstorm** [comment]
Ok, the Data plugin is back and working properly. I updated the examples too.
