### ISSUE TITLE
Blitter Alpha is ignored in WEBGL rendering

### ISSUE THREAD

**Issue by Antriel** [photonstorm/phaser#3189]
See [example](http://labs.phaser.io/edit.html?src=src\game%20objects\blitter\blitter%20alpha.js).

**Comment by photonstorm** [comment]
Yup, wait for @bitnenfer to merge in the new pipeline code and then we can re-test. Blitter also ignores camera scroll and scrollFactor in canvas mode I think.

**Comment by photonstorm** [comment]
Fixed now the new pipeline code is in.
