### ISSUE TITLE
[Suggestion] phaser3-examples - External Source Maps

### ISSUE THREAD

**Issue by jrasm91** [photonstorm/phaser#3191]
This Issue is about 
* An error on the web site

I noticed the examples at [labs.phaser.io](http://labs.phaser.io) can often take a long time to load. Most of the time seems to be spent loading the **phaser build**

![image](https://user-images.githubusercontent.com/4334196/35403273-74ab66b8-01bc-11e8-8060-a3e99528dd9d.png)

There are a lot of things that can be done to optimize the build, but one suggestion I have is to use **external** source maps, instead of embedded ones. This would immediately cut the build size in at least half. 

**Example:** http://labs.phaser.io/build/113.js
- Embedded Maps: 6829 KB
- External Maps: 2442KB

**Comment by photonstorm** [comment]
I'm happy for them to remain inlined until we finish development. We build and dev locally, and run labs locally too, so the filesize isn't an issue for us, but the inlined source map is a _massive_ boost to our productivity and keeps things easy when we publish new builds to go with the dev logs (as we just have to upload one build file)

When we hit final and move from labs to examples we'll make the sourcemap external, but for now, it really doesn't matter too much, as it's not for general consumption - we only really made the labs public for those interested in poking around during this dev period (admittedly, that's quite a lot of you though!). Once we're live, we'll likely close them off again.

**Comment by jrasm91** [comment]
Awesome, sounds good. Thanks!
