### ISSUE TITLE
[Bug] `load.audio()` does not respect `load.path`

### ISSUE THREAD

**Issue by halgorithm** [photonstorm/phaser#3194]
* A bug in the API for v3.0.0.beta19

This a regression from the behavior in earlier betas before the loader API was changed.

https://jsfiddle.net/g7pg5L4p/

Open the console and check the urls for the network requests it tries to make. It prepends the path for the first two, but not for the audio.

**Comment by pavle-goloskokovic** [comment]
This is a duplicate of #3182 
It should be fixed on master and available in next beta version.
