### ISSUE TITLE
Renderer resolution is blurry for devices with devicePixelRatio > 1

### ISSUE THREAD

**Issue by kronion** [photonstorm/phaser#3198]
This issue is about several apparent bugs in the renderer API and source in Phaser 3.0.0-beta.18.

When viewed on a high DPR device (a MBP with retina display, in my case), the results of drawing text in Phaser 3 appear blurry, both in `CANVAS` and `WEBGL` modes. It seems that Phaser isn't scaling the canvas context (or webgl equivalent) to take advantage of the true pixel density of devices. I suspect this is an issue for rendering images/sprites as well as text, but I've only tested text rendering.

I have the following app, which manually renders two canvases (one "naively", and the other taking into account the device DPR), and then draws an equivalent canvas with Phaser.

`app.js` (I use webpack to bundle it with Phaser 3, no other dependencies):
```
'use strict';

import 'phaser';

// First, two comparisons via direct canvas control
const blurryCanvas = document.getElementById('canvas1');
const blurryCtx = blurryCanvas.getContext('2d');

const crispCanvas = document.getElementById('canvas2');
const crispCtx = crispCanvas.getContext('2d');

const size = 200;
blurryCanvas.style.width = blurryCanvas.style.height = size + 'px';
crispCanvas.style.width = crispCanvas.style.height = size + 'px';

// Set different canvas scales (i.e., account for extra device pixel density or not)
const loScale = 1;
const hiScale = window.devicePixelRatio;  // 2 for me on a retina display
blurryCanvas.width = blurryCanvas.height = size * loScale;
crispCanvas.width = crispCanvas.height = size * hiScale;

blurryCtx.scale(loScale, loScale);
crispCtx.scale(hiScale, hiScale);

blurryCtx.fillStyle = crispCtx.fillStyle = '#000';
blurryCtx.fillRect(0, 0, blurryCanvas.width, blurryCanvas.height);
crispCtx.fillRect(0, 0, crispCanvas.width, crispCanvas.height);
blurryCtx.fillStyle = crispCtx.fillStyle = '#fff';
blurryCtx.font = crispCtx.font = '28px Arial';
blurryCtx.textAlign = crispCtx.textAlign = 'center';
blurryCtx.textBaseline = crispCtx.textBaseline = 'middle';

const x = size / 2;
const y = size / 2;

// textString = 'I love Po'
blurryCtx.fillText('This is blurry', x, y);
crispCtx.fillText('This is crisp', x, y);


// Now onto Phaser

function preload() {};

function create() {
  let game = this.cache.game;
  let half = game.config.width / 2;
  let third = game.config.width / 3;
  var text = this.add.text(half, half, 'This is blurry', {
    font: '28px Arial',
    fill: '#fff',
  }).setOrigin(0.5,0.5);
  var text2 = this.add.text(third, 2 * third, 'Can\'t use all of canvas', {
    font: '18px Arial',
    fill: '#fff',
  });
};

function update() {};

var config = {
  type: Phaser.CANVAS,  // Same problem in webgl
  width: 200,
  height: 200,
  scene: {
    preload: preload,
    create: create,
    update: update
  }
};

var game = new Phaser.Game(config);
```

`index.html`:
```
<!DOCTYPE HTML>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Test</title>
  </head>
  <body>
    <canvas id="canvas1"></canvas>
    <canvas id="canvas2"></canvas>
    <script src="bundle.js"></script>
  </body>
</html>
```

As you can see, the Phaser canvas looks as blurry as the naive canvas.
<img width="618" alt="screen shot 2018-01-28 at 1 49 58 pm" src="https://user-images.githubusercontent.com/2781682/35485773-39597ece-0432-11e8-82eb-258254162e64.png">

In Phaser 2 you could use the `resolution` game config attribute to allow the Pixi renderer to take advantage of screen DPR. So I thought it would do the same in Phaser 3:

```
var config = {
  type: Phaser.CANVAS,  // Same problem in webgl
  width: 200,
  height: 200,
  resolution: window.devicePixelRatio,  // 2 for me on a retina display
  scene: {
    preload: preload,
    create: create,
    update: update
  }
};

var game = new Phaser.Game(config);
```
Expectation: The canvas would stay 200x200 CSS pixels, but its context would be 400x400. Additionally the canvas context would be scaled 2x in both dimensions so that its coordinate system would correspond to CSS coordinates. Text would look crisp.

Reality: The canvas CSS and context _both_ scale 4x to 800x800. Text is still blurry. For some reason, Phaser only uses 200x200 of the canvas.

<img width="1215" alt="screen shot 2018-01-28 at 2 11 09 pm" src="https://user-images.githubusercontent.com/2781682/35485967-239d3708-0435-11e8-90eb-db2d7c871021.png">

I started making changes to the `CanvasRenderer`, and I've been able to address some of the issues. Changes for the webgl renderer would be similar.

```
var CanvasRenderer = new Class({

    initialize:
    function CanvasRenderer (game)
    {
        ...
        //  Read all the following from game config (or Scene config?)
        // this.clearBeforeRender = true;
        // this.transparent = false;
        this.autoResize = true; // TODO: this is a hack for debugging resolution issues
        // this.roundPixels = false;

        this.width = game.config.width * game.config.resolution;
        this.height = game.config.height * game.config.resolution;
        this.resolution = game.config.resolution;
        ...
        this.gameCanvas = game.canvas;
        this.gameContext = this.gameCanvas.getContext('2d');
        this.currentContext = this.gameContext;
        ...
        this.init();
    },

    init: function ()
    {
        // this.width and this.height were just scaled up in initialize(), but they get 
        // scaled up again in this.resize(). So I just scaled down the parameters.
        this.resize(this.width / this.resolution, this.height / this.resolution);
    },

    //  Resize the main game canvas
    resize: function (width, height)
    {
        var res = this.game.config.resolution;

        // This is why I had to scale the width and height arguments to this.resize() down again
        this.width = width * res;
        this.height = height * res;

        this.gameCanvas.width = this.width;
        this.gameCanvas.height = this.height;

        if (this.autoResize)
        {
            // I set this.autoResize = true just to take advantage of these two lines below
            this.gameCanvas.style.width = width + 'px';
            this.gameCanvas.style.height = height + 'px';
        }
        ...
    },
```

This causes the canvas context to be 2x the resolution (rather than 4x), and also keeps the canvas 200x200 in the DOM as expected. However, the full canvas still isn't used.

<img width="615" alt="screen shot 2018-01-28 at 2 34 02 pm" src="https://user-images.githubusercontent.com/2781682/35486178-5828cf8e-0438-11e8-9a1b-ea815032215b.png">

I think there needs to be a line like `this.gameContext.scale(this.resolution, this.resolution);` somewhere in the renderer, but I haven't been able to figure out where. I've experimented with putting it in the `if (this.autoResize)` block, but AFAICT it quickly gets reset by subsequent calls like `this.currentContext.setTransform(1, 0, 0, 1, 0, 0);`? At this point I'm pretty lost.

**Comment by kronion** [comment]
This is still an issue in Phaser 3.0.0-beta.20.

**Comment by photonstorm** [comment]
Multi-resolution text (and game canvases) was added in the 3.0.0 release version, so please re-test against that.

**Comment by kronion** [comment]
This is still an issue in Phaser 3.1.2, though the behavior has changed. Here's the latest screenshot:
<img width="824" alt="screen shot 2018-02-23 at 11 27 42 pm" src="https://user-images.githubusercontent.com/2781682/36625649-a04df65e-18f1-11e8-8e15-d41cbf018222.png">
Phaser is still scaling the canvas element's width and height unnecessarily (now 2x instead of 4x), and text is blurry. The entire canvas is useable, though. Same results with WebGL.

**Comment by Sunqinying** [comment]
I get this problem too, when I only want scale canvas context,  the config of resolution will also scale css width and context. I find a hack method to solve it

```javascript
 let clientWidth = document.documentElement.clientWidth
 let clientHeight = document.documentElement.clientHeight

 const gameConfig = {
     width: clientWidth,
     height: clientHeight,
     resolution: PIXEL_RATIO,
     "callbacks.postBoot": function() {
         document.getElementsByTagName("canvas")[0].style.width = clientWidth + "px"
         document.getElementsByTagName("canvas")[0].style.height = clientHeight + "px"
     }
 };
```

PIXEL_RATIO is a function like:
``` javascript
export const PIXEL_RATIO = (function() {
    var ctx = document.createElement("canvas").getContext("2d"),
        dpr = window.devicePixelRatio || 1,

        // The backing store size in relation to the canvas element
        bsr = ctx.webkitBackingStorePixelRatio ||
        ctx.mozBackingStorePixelRatio ||
        ctx.msBackingStorePixelRatio ||
        ctx.oBackingStorePixelRatio ||
        ctx.backingStorePixelRatio || 1

    return dpr / bsr
})();
```

**Comment by sonzqn** [comment]
It can be fix by modify Text class
- Scale the font size to target resolution
- Reverse scale the text to original resolution
```javascript
function Text (scene, x, y, text, style)
{
    if(style && style.font)
    {
        var fontInfo = style.font.split('px');
        style.font = fontInfo[0]*scene.sys.game.config.resolution + 'px' + fontInfo[1];
        this.setScale(1/scene.sys.game.config.resolution);
    }
    //original code below
}
```
Result:
- Before
![capture old](https://user-images.githubusercontent.com/10859950/44305004-1905cd80-a397-11e8-871c-a03992a3b449.PNG)
- After
![capture](https://user-images.githubusercontent.com/10859950/44305005-1905cd80-a397-11e8-8e32-348554a8ade5.PNG)

Issue: this is a hack, and it create scale bug for any children of text object.
@photonstorm : Can you take a look and fix this issue?

**Comment by alexandernst** [comment]
This hasn't been fixed.

**Comment by photonstorm** [comment]
It was, but then the Scale Manager was added and resolution is _always_ fixed at 1 now and cannot be changed, so it's a valid issue again. However, this isn't going to change soon and needs a different issue to be opened for it.

**Comment by ChrisP83** [comment]
make sure u have `<meta name="viewport"
          content="width=device-width, initial-scale=0.5, maximum-scale=1.0, minimum-scale=0.5, user-scalable=no, minimal-ui">` in your html header

**Comment by giorgi-shippo** [comment]
> 

This solution doesn't work on fullscreen mode.
