### ISSUE TITLE
[Bug] Exception when destroy()ing a GameObject with a body

### ISSUE THREAD

**Issue by halgorithm** [photonstorm/phaser#3199]
This Issue is about a bug in the API for v 3.0.0.beta19

https://jsfiddle.net/p6v3ky7y/

In the console you should see the following error: `Uncaught TypeError: Cannot read property 'remove' of undefined`

This is being raised in GameObject.js on this line: `sys.physicsManager.remove(this);`

**Comment by nkholski** [comment]
A temporary fix is to add this to your create-method:
`this.sys.physicsManager = this.physics.world;`

**Comment by halgorithm** [comment]
Looks like this was fixed in beta 20.
