### ISSUE TITLE
Errors in Input Mouse Events examples

### ISSUE THREAD

**Issue by partnano** [photonstorm/phaser#3200]
So I'm playing around with Phaser 3 and noticed that the input/mouse circle and ellipse hit area examples don't work. They are probably not yet updated, but the huge "Open Github Issue" button tempted me ;)

It seems like `this.input.events.on()` is undefined.
Through a little bit of guesswork and reading newer syntax somewhere, I managed to get it working via
```
this.input.on('pointerover', function (pointer, gameObject) 
{
        gameObject[0].setTint(0x7878ff);
});
```

2 questions though:
- Are the events documented somewhere? The examples still have (I guess old?) other events in them, like POINTER_OVER_EVENT
- Why exactly does the second parameter deliver an array? I'm probably missing some important point, but it doesn't make much sense to me in this case.

Hope I didn't miss an overlapping issue.
Cheers! :)

**Comment by photonstorm** [comment]
These examples have been fixed now.

`pointerover` delivers the pointer and an array of game objects, because it can be over more than one at once. `gameobjectover` delivers the pointer + one game object.
