### ISSUE TITLE
Beta 20 - Broken due require() on shader files

### ISSUE THREAD

**Issue by dev-zetta** [photonstorm/phaser#3202]
I'm unable to start Phaser after update to Beta 20. Running in Node.js.

Uncaught (in promise) SyntaxError: Invalid 'shaders/TextureTint.vert:1' or unexpected token
    at createScript (vm.js:74)
    at Object.runInThisContext (vm.js:116)
    at Module._compile (module.js:533)
    at Object.Module._extensions..js (module.js:580)
    at Module.load (module.js:503)

Caused by this line:
var ShaderSourceVS = require('../shaders/TextureTint.vert'); 

because you're calling require on non-js file, which results in wrongly generated module stub function:

`(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { #define SHADER_NAME PHASER_TEXTURE_TINT_VS

precision mediump float;

uniform mat4 uProjectionMatrix;
uniform mat4 uViewMatrix;
uniform mat4 uModelMatrix;

attribute vec2 inPosition;
attribute vec2 inTexCoord;
attribute vec4 inTint;

varying vec2 outTexCoord;
varying vec4 outTint;

void main () 
{
    gl_Position = uProjectionMatrix * uViewMatrix * uModelMatrix * vec4(inPosition, 1.0, 1.0);
    outTexCoord = inTexCoord;
    outTint = inTint;
}

}.call(this, exports, require, module, __filename, __dirname); });`

**Comment by photonstorm** [comment]
In our webpack config we use raw-loader to handle the vert and frag files. If you're pulling into your own webpack set-up, you'll need to copy this block as well in order for it to build.

**Comment by dev-zetta** [comment]
I'm not using webpack in my app, but Babel. I cannot switch to webpack. I just fixed it by wrapping those shader files into export.
