### ISSUE TITLE
[Feature request] Add indices on Mesh

### ISSUE THREAD

**Issue by TheTrope** [photonstorm/phaser#3203]
If I'm not wrong, the Mesh gameobject only have a vertices property.
It would be nice to have the possibility to **set indices**.

(The possibility of adding a custom shader on a Mesh could be really usefull too !)
Thank you,

**Comment by Arthur3DLHC** [comment]
We can understand that implementing hardware indices is complex and it will break the current inner vertex buffer structure of Pipelines, but is it possible to add a simple software indices implementation? It seems like that you only need to select the vertex and uv and so on from corresponding arrays by the indices before pending them to the vertex buffer of WebGLPipeline, in MeshWebGLRenderer.
Although it is not as fast as hardware indicing, but with this feature, we can begin to use some character skin mesh animation APIs, such as DragonBones. So it will be very nice.

**Comment by photonstorm** [comment]
There's no time to look at this right now, realistically probably not this year, but I'd be happy to accept a PR from someone adding the feature in.

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
