### ISSUE TITLE
Porting my open source project to V3, but missing things

### ISSUE THREAD

**Issue by prsolucoes** [photonstorm/phaser#3205]
This Issue is about migrations things.

Im trying port my open source multiplayer game to phaser v3:
https://github.com/prsolucoes/golandy-web

But something is too hard to find, and im reading near full source code.

Can anyone point me where is:

- sprite.anchor.setTo
- game.world.centerX
- game.world.width
- game.scale.scaleMode = Phaser.ScaleManager.EXACT_FIT;
- game.scale.fullScreenScaleMode = Phaser.ScaleManager.EXACT_FIT;
- game.scale.pageAlignHorizontally = true;
- game.scale.pageAlignVertically = true;
- game.scale.setScreenSize = true;
- game.scale.refresh();

The way to go to a new scene is:  

```game.scene.start('main_menu', true, false, otherThing, this.nextState);```

And the MainMenu is something like this?

```
var MainMenuScene = new Phaser.Class({

    Extends: Phaser.Scene,

    initialize: function LoadingScene(assetsName, assetsFile, nextState) {
        Phaser.Scene.call(this, { key: 'main_menu', active: true });

        this.assetsName = assetsName;
        this.assetsFile = assetsFile;
        this.nextState = nextState;
    },
....
});
```

?

**Comment by nkholski** [comment]
There is no scale manager yet and there is no world in that sense. Phaser 3 is still being developed. I suggest slack or the forums for questions like this.

**Comment by prsolucoes** [comment]
I posted. But no answers.

**Comment by photonstorm** [comment]
V3 doesn't use texture anchors in the way Pixi does, so to achieve the same effect you should use `setOrigin(x,y)` instead.

Equally, there is no "world" in v3 either. You're free to implement the bounds however you wish (if at all) - you may wish to use the camera bounds as the world boundary (there are a few examples showing how to do this), or perhaps the physics world bounds. Or you could just use a plain old Rectangle, it's really up to you :) But once you know what you're using, finding the center is easy enough.

The rest are Scale Manager related, so can't be covered yet. Keep an eye on the examples repo for when examples for that land.
