### ISSUE TITLE
WebGL Tilemap rendering is blurry

### ISSUE THREAD

**Issue by etienne** [photonstorm/phaser#3207]
This Issue is about

* A bug in the API (3.0.0-beta.20)

When `pixelArt` is set to `false`, Tilemap tiles are rendered with a slight blur when using WebGL. The same image, when rendered as an `Image` GameObject, displays correctly.

Here is a comparison of both renderers (magnified 300%):

![comparison](https://user-images.githubusercontent.com/9656/35828786-cf36a1a8-0a8e-11e8-8223-fb021e64fe86.png)

* **[Live test case](https://etienne.github.io/phaser3-test-cases/)**
* [Source code](https://github.com/etienne/phaser3-test-cases/blob/master/src/index.js)

Tested in the latest versions of Chrome, Safari, and Firefox (all on the Mac).

**Comment by photonstorm** [comment]
This was addressed in the 3.0.0 release. Please can you re-test against that.

**Comment by etienne** [comment]
Fixed indeed! Thanks!
