### ISSUE TITLE
TileSprite examples don't tile the image correctly

### ISSUE THREAD

**Issue by halgorithm** [photonstorm/phaser#3208]
http://labs.phaser.io/view.html?src=src\game%20objects\tile%20sprite\Example.js
The image isn't repeated, there's just the one image with lines stretching out in each direction.

**Comment by bradharms** [comment]
I can confirm this started in beta 20. Before that I had a background tiling horizontally, after upgrading to 20 it only tiles rightmost column of pixels.

**Comment by photonstorm** [comment]
It's being fixed literally at the moment.

**Comment by bradharms** [comment]
Thanks as always, Rich!
