### ISSUE TITLE
RenderPass game object removed from V3?

### ISSUE THREAD

**Issue by dev-zetta** [photonstorm/phaser#3210]
Howdy guys,

I wanted to use custom shaders within my game and according to Phaser 3 API overview (https://phaser.io/phaser3/api), it's possible thu Phaser.GameObjects.RenderPass.

However, there is no such class. That's quite strange that such helpful class was removed before the release and the docs were not updated accordingly.

How do I use custom shaders in Phaser 3? Thank you in advance.

**Comment by photonstorm** [comment]
It was removed along with EffectLayer when we put the new WebGL pipeline code in place. They will both return but not in the same manner as we felt being display list items made no sense. We understand the need for custom shaders and @bitnenfer will make it possible, just not for 3.0.0.
