### ISSUE TITLE
_lineSpacing does not seem to be taken

### ISSUE THREAD

**Issue by sftsk** [photonstorm/phaser#3215]
* A bug in the API (always say which version you're using!) v3.0

https://github.com/photonstorm/phaser/blob/8afeafd66b3767e2ae7aad19a9766939be312f6d/src/gameobjects/text/static/Text.js#L988

In here it's taking the line-height but it seems to never actually be parsed from the text config.
If I do something like this I expect it to change the line-height of the text:

```
var textConfig = {
    x: 450,
    y: 190,
    text: "this is some text\nhere it flows to the next line",
    style: {
      fill: '#111'
    },
    lineSpacing: 50
  };
```

I hope this is not me misunderstanding the docs.
Thank you for your great work!

Lukas

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
