### ISSUE TITLE
Circular object references

### ISSUE THREAD

**Issue by vpmedia** [photonstorm/phaser#3217]
Hi!

Thanks for all the effort you've put into the new framework.

I've tried to learn about the new Phaser 3 API, logging game main game object.
While doing this I've noticed a few circular object references:
``
    console.log(game.scene.game.scene.game.scene.game);
    console.log(game.add.group().scene.sys.scene.sys.scene);
``
Is this intentional by design and you want to keep it this way?
I'm not sure how well the browser garbage collection handles this, also this makes extending and debugging applications a bit harder, maybe.

--

Some slightly related observation would be - I don't want to create a new issue - that I've noticed that game.input.config object contains all the game configuration properties.
Maybe it would worth the effort to try to group these properties, like inputConfig, sceneConfig, renderConfig so the intention of these settings would be more clear and separated by system scope.

**Comment by photonstorm** [comment]
Unlike in v2 the `game` object is no longer the main entry point into Phaser. It contains only a handful of global managers and very rarely should be interacted with directly, instead everything through be done via the Scene. So the fact it's possible to jump from Game to the SceneManager, back to Game again, is fine, as under normal circumstances you'd never actually do this anyway.

I'll have a look at the Input config. It doesn't actually need it once it has booted, so the property could be removed entirely.

**Comment by vpmedia** [comment]
Thanks for the clarifications!
