### ISSUE TITLE
Number of WebGL calls to render texts compared to v2.6.2

### ISSUE THREAD

**Issue by vpmedia** [photonstorm/phaser#3218]
Hi!

I've tried to compare text rendering using the legacy and new framework.
It looks like v3 uses double amount of webgl calls (render calls are matching) to render the same amount of texts.

*Phaser 2.6.2*
``
Object.bindTexture(TEXTURE_2D, Object)
Object.drawElements(TRIANGLES, 6, UNSIGNED_SHORT, N(0|12|24|..))
..
Object.bindTexture(TEXTURE_2D, Object)
Object.drawElements(TRIANGLES, 6, UNSIGNED_SHORT, N(0|12|24|..))
..
``

*Phaser 3.0.0*
``
Object.activeTexture(TEXTURE0)
Object.bindTexture(TEXTURE_2D, Object)
Object.bufferSubData(ARRAY_BUFFER, NONE, Object)
Object.drawArrays(TRIANGLES, 0, 6)
..
Object.activeTexture(TEXTURE0)
Object.bindTexture(TEXTURE_2D, Object)
Object.bufferSubData(ARRAY_BUFFER, NONE, Object)
Object.drawArrays(TRIANGLES, 0, 6)
``

Test repo: 
https://github.com/vpmedia/PhaserPerfTest/tree/master/phaser-perf-test

--

Maybe a short migration doc with tips would be help the adoption, at least for me.

Thanks!

**Comment by bitnenfer** [comment]
Hi @vpmedia 

I am currently working on a simple batch optimization that reduces substantially the number of webgl commands emitted. It's on par with v2.6.2 and even gets to shave off some redundant calls.

Here is a comparison of the summary of commands emitted by your example. The left one is v 2.6.2 and the right one is 3.0.0 + the fix I am working on.

![commands](https://user-images.githubusercontent.com/843198/36186023-22885f44-111b-11e8-8663-794c45b8b75c.jpg)

On the current version is pushing around 408 commands. This fix will affect all textured elements and should also reduce the overhead of calling `gl.bufferSubData` for each texture change on the renderer state.

Cheers,
Felipe

**Comment by vpmedia** [comment]
Hi!

Since you are aware and working on it, I'm closing this issue.

Thank you!
