### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by pipeserrano** [photonstorm/phaser#3220]
![image](https://user-images.githubusercontent.com/17888034/36171334-3e5cfca2-10d0-11e8-9ef4-cefe9c7dc66d.png)

All versions of Safari iOS 9, 10, 11 and MacOSX 10.10, 10.11, 10.12, 10.13

![image](https://user-images.githubusercontent.com/17888034/36171266-f4362a86-10cf-11e8-9b1c-e8a82c2458c0.png)

![image](https://user-images.githubusercontent.com/17888034/36171093-57547204-10cf-11e8-88be-bea49f0a9010.png)

![image](https://user-images.githubusercontent.com/17888034/36171114-6709d95a-10cf-11e8-88c5-41df6e015884.png)

**Comment by samme** [comment]
#3221

**Comment by pipeserrano** [comment]
I replaced all let with var and it loads but now I'm getting this in iOS when I try to load an image, MacOSX is working ok.

![image](https://user-images.githubusercontent.com/17888034/36175046-30e73fa4-10dc-11e8-9225-c782e0afb2d9.png)

**Comment by photonstorm** [comment]
Hi, I just built a new version direct from the current master branch, and ran it on my iPad (iOS 11) and tried out a few of the examples and they all worked. Specifically I tried the animation / cubes, demoscene / chunky rasters and physics / arcade / static body. I also ran the particles / electric demo and although it was quite hard to drag the markers around, they did respond once I hit them.

I've pushed the build I just made up to the labs site, so feel free to grab it from there to test with.

**Comment by pipeserrano** [comment]
Thank you it works from Safari but when I try to use it with Ionic it doesn't work at all and it doesn't destroy the instance so everytime I load the controller 6 times it gives me:

![image](https://user-images.githubusercontent.com/17888034/36177106-aa310f4c-10e2-11e8-880c-045b50affb4c.png)

Phaser 2.x has work very well with this code

$scope.$on('$ionicView.beforeLeave', function() 
{
        game.destroy();
});

**Comment by pavle-goloskokovic** [comment]
You'll need to instantiate `AudioContext` yourself and reuse it by passing it to the game config every time you create a new Game instance.
Here's an example showing how to accomplish that http://labs.phaser.io/edit.html?src=src\game%20config\game%20destroy.js

Or if you are not planning to use sounds you can set `noAudio` setting to `true` in the game config, take a look at any of the examples in this folder: http://labs.phaser.io/index.html?dir=audio/No%20Audio/

**Comment by photonstorm** [comment]
Yes, this (Ionic) is a separate issue so I'm closing this one off.
