### ISSUE TITLE
[BUG][Tweens] TypeError: this.emit is not a function

### ISSUE THREAD

**Issue by ZaDarkSide** [photonstorm/phaser#3222]
Sometimes when using tweens I get this error:

```TypeError: this.emit is not a function```

https://github.com/photonstorm/phaser/blob/c1eb443c1f0a209eb939f253f61041451d857c27/src/tweens/tween/Tween.js#L730

It seems the error can be triggered by calling ```resume()```

https://github.com/photonstorm/phaser/blob/c1eb443c1f0a209eb939f253f61041451d857c27/src/tweens/tween/Tween.js#L721

Sadly I do not have a test case ready.

**Comment by photonstorm** [comment]
Thanks. Copy pasta strikes again (copied from TweenManager class, where it can emit events)
