### ISSUE TITLE
Support Lua scripting

### ISSUE THREAD

**Issue by daurnimator** [photonstorm/phaser#3225]
Phaser could support lua scripting via the [fengari](https://fengari.io/) project.

There are a few subsets of functionality that would be good:
  - Use lua as main development language (this should be easy/can be done today; just need some support + examples in docs)
  - Support lua for running untrusted code
    Fengari allows distinct lua states: this means that in a game, entities could send code to each other that gets to run in a sandbox

**Comment by PythonFanboy** [comment]
Please no. JavaScript is already a scripting language. Do we really want layers of scripting languages one over another?

**Comment by ZaDarkSide** [comment]
@PythonFanboy Why do we use TypeScript then?

**Comment by pavle-goloskokovic** [comment]
@ZaDarkSide type checking and pseudo OO paradigm?

**Comment by ZaDarkSide** [comment]
So I guess every scripting language has it's use then. Anyway my question was kind of rhetorical for @PythonFanboy who apparently doesn't likes LUA for some reason.

**Comment by rexrainbow** [comment]
It could be implemented in (3rd-party) plugin.
Here is another useful feature :
`Lua in the browser means you can use coroutines to write beautiful asynchronous code`

**Comment by photonstorm** [comment]
I'm going to close this issue. Not because I don't agree with the idea, but just because there is no way we're going to implement it ourselves, so if the wider community want to do it then please go ahead - and we'll feature it in the newsletter and on the site if you do, we just won't put any of our resources into it I'm afraid.

**Comment by daurnimator** [comment]
FYI I ported the tutorial to lua: https://github.com/daurnimator/fengari-phaser-tutorial-02
