### ISSUE TITLE
custom blend mode with graphics.js:79 Uncaught TypeError: renderer.addBlendMode is not a function

### ISSUE THREAD

**Issue by jeffallen6767** [photonstorm/phaser#3226]
This Issue is about an error I got in the console when viewing the phaser 3 examples:

custom blend mode with graphics.js:79 
Uncaught TypeError: renderer.addBlendMode is not a function

http://127.0.0.1:8080/view.html?src=src\display\blend%20modes\custom%20blend%20mode%20with%20graphics.js

I'm new to phaser, and I apologize if this reported problem has already been addressed, I tried searching through the known issues and didn't see anything related. ( but maybe I did it wrong ... ? )

Any chance I could help develop phaser ( even though I have zero experience with it ? ) I'm a fairly decent developer with quite a bit of JavaScript experience.

Thanks,
Jeff
![phaser-error-001](https://user-images.githubusercontent.com/1063272/36187293-1056f3b6-10f9-11e8-8b9d-b64eee7a2e67.png)

**Comment by photonstorm** [comment]
Yes, this method was left out of the new renderer by mistake. Have flagged it to be added in for 3.0.2 - thank you!

**Comment by photonstorm** [comment]
This is now fixed in the master branch and will be part of the 3.0.1 release.
