### ISSUE TITLE
Feature: Plugins via import

### ISSUE THREAD

**Issue by nkholski** [photonstorm/phaser#3228]
It would be nice to add plugins in the package.json and import them into the scenes. Like this:

`import BasePlugin from 'base-plugin;`

```
preload(){
    this.load.plugin('BasePlugin', BasePlugin); // Object instead of url
}
```

Actually the above works if this is added to PluginFile in PluginFile.js but will throw a 404 in the console:
```
        if(typeof url !== "function"){
            this.key = key;
            window[key] = url;
            window[key].register(PluginManager);
        }
```

**Comment by photonstorm** [comment]
Agreed, have marked for 3.0.2. If you want to submit a PR I'd merge it too, but we'll do this regardless :)

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
