### ISSUE TITLE
[BUG][Loader] Strange behavior with loader

### ISSUE THREAD

**Issue by ZaDarkSide** [photonstorm/phaser#3230]
I have observed some strange behavior with sounds.

```js
sound = this.sound.add('some sound 1');
sound = this.sound.add('other sound 2');
sound.play();
```

In this case both ```'some sound 1'``` and ```'other sound 2'``` will play at the same time.

**Comment by pavle-goloskokovic** [comment]
I'm unable to replicate it.
Can you provide an example demonstrating this behavior?

**Comment by ZaDarkSide** [comment]
I will try to create a test case.

**Comment by ZaDarkSide** [comment]
@pavle-goloskokovic So did you replicated it?

**Comment by pavle-goloskokovic** [comment]
@ZaDarkSide I'll look into it

**Comment by pavle-goloskokovic** [comment]
Ok, I figured it out, it's not a bug with Sound API but with Loader.
When you load the second file, `complete` event callback is called twice, for both files, even if you call `self.load.reset();` before loading audio file.

I've updated fiddle to log message when on complete callback is called: https://jsfiddle.net/L4gkttkx/48/

**Comment by ZaDarkSide** [comment]
Great news, well we should fix that somehow.

**Comment by photonstorm** [comment]
Yes, because Loader.reset doesn't remove any previously bound event listeners, because people were complaining that when the Scene finished loading (and reset the Loader) their event listeners were lost too. Can't have both :)

**Comment by ZaDarkSide** [comment]
I have managed to fix it my code.

https://jsfiddle.net/L4gkttkx/51/

**Comment by pavle-goloskokovic** [comment]
@ZaDarkSide or you could just add `self.load.removeAllListeners();` below `self.load.reset();`

**Comment by ZaDarkSide** [comment]
OK, thanks for the hint.
