### ISSUE TITLE
Phaser.CANVAS doesn't rotate tilesprites

### ISSUE THREAD

**Issue by amkazan** [photonstorm/phaser#3231]
* A bug in the API (always say which version you're using!)
Phaser 3.0.0

http://jsbin.com/mevarapizu/edit?html,js,output

In Canvas mode tilesprites are not rotated. They are if we change CANVAS to WEBGL

**Comment by photonstorm** [comment]
Well, that's embarrassing :) We're on it, will be fixed in 3.0.1.

**Comment by photonstorm** [comment]
Extra note - it doesn't scale them either.

**Comment by amkazan** [comment]
cool! Found it accidentally while trying to understand fast fan spinning when 100 sprites are added (half rotated)

(p.s. By the way: Thanks for the great framework!!! 👍 )

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
