### ISSUE TITLE
setFrame() doesn't work on TileSprite

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3232]
Apparently attempting to change the frame of a `TileSprite` using `setFrame()` doesn't work. 

I have reproduced it in the [atlas tilesprite example](http://labs.phaser.io/view.html?src=src\game%20objects\tile%20sprite\Atlas.js). I added `images[0].setFrame('hotdog');` at the end of `create()`. This should have the effect of displaying two "hotdog" columns, one to the left and one to the right. Instead, nothing changes. `setFrame()` works perfectly well on ordinary `Sprite` objects however.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
