### ISSUE TITLE
Pointer Buttons example throws an error

### ISSUE THREAD

**Issue by ansimuz** [photonstorm/phaser#3235]
pointer buttons.js:59 Uncaught TypeError: Cannot read property 'on' of undefined
    at Scene.create (pointer buttons.js:59)

Link:  https://labs.phaser.io/view.html?src=src\input\pointer\pointer%20buttons.js&v=dev

**Comment by DillonHemphill** [comment]
Changing  this.input.events.on to this.inputs.on. Solves this

**Comment by ansimuz** [comment]
THanks

**Comment by photonstorm** [comment]
Yeah, sorry, we're going through and fixing these as fast as we can (there are quite a lot!)

**Comment by photonstorm** [comment]
This example is now fixed.
