### ISSUE TITLE
Feature: add plugin instance with name parameter

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3236]
The 3rd parameter `Mapping` in `PluginManager.register` function is the member name in scene. (`Mapping is what the plugin is injected into the Scene.Systems`)
It might restrict only 1 instance could be created in the `PluginManager.installLocal` function.
How about place 3rd parameter into `PluginManager.installLocal` function to assign member name instead of `Mapping` property, to create multiple instances of that plugin?

**Comment by pixelpicosean** [comment]
What is your purpose of adding multiple plugin instances? Plugins suppose to be system like, consider the `system` concept of ECS.

**Comment by rexrainbow** [comment]
I tried to create instances like game object with or without display/updating. 
It seems that PluginManager was not designed for this kind of object, thanks for reply.
