### ISSUE TITLE
Phaser3 not loading images in Safari

### ISSUE THREAD

**Issue by pipeserrano** [photonstorm/phaser#3237]
![image](https://user-images.githubusercontent.com/17888034/36171334-3e5cfca2-10d0-11e8-9ef4-cefe9c7dc66d.png)

CODE
![image](https://user-images.githubusercontent.com/17888034/36282191-622e8b06-126e-11e8-9402-885ac24a8c59.png)

All versions of Safari iOS 9, 10, 11 and MacOSX 10.10, 10.11, 10.12, 10.13
![image](https://user-images.githubusercontent.com/17888034/36281804-0037cc9c-126d-11e8-8d1d-029218042381.png)

WEBGL Safari
![image](https://user-images.githubusercontent.com/17888034/36281912-628b1ff2-126d-11e8-92ee-084022f9e8f3.png)

CANVAS Safari
![image](https://user-images.githubusercontent.com/17888034/36281942-7720caca-126d-11e8-9ae4-58ff0078a1d4.png)

All versions of Chrome MacOSX and Windows
![image](https://user-images.githubusercontent.com/17888034/36282029-be1b058a-126d-11e8-86ae-61f37001f44c.png)

WEBGL and CANVAS Chrome
![image](https://user-images.githubusercontent.com/17888034/36282104-0d8579f2-126e-11e8-9b5d-aad393e66d7c.png)

**Comment by photonstorm** [comment]
Hi - This is fixed in the master branch already, and will be pushed to npm today with the 3.1.0 release.
