### ISSUE TITLE
`Key#duration` not behaving as documented

### ISSUE THREAD

**Issue by rblopes** [photonstorm/phaser#3239]
Using the keyboard input manager API, it is not possible to evaluate how long a given key is being pressed down.

<details>
<summary>Sample code (<a href="https://jsfiddle.net/rblopes/hmtxj5hb/">live</a>) (Tested with Phaser 3.1.0.)</summary>

```js
const game = new Phaser.Game({
  type: Phaser.CANVAS,
  width: 400,
  height: 300,
  backgroundColor: '#222288',
  scene: {
    create() {
    	this.keys = this.input.keyboard.addKeys({
      	leftKey: Phaser.Input.Keyboard.KeyCodes.LEFT,
        rightKey: Phaser.Input.Keyboard.KeyCodes.RIGHT
      });

      this.t1 = this.add.text(16, 16);
      this.t2 = this.add.text(16, 64);
    },
    
    update() {
      const {leftKey, rightKey} = this.keys;
      this.t1.setText([
        `leftKey.isDown = ${leftKey.isDown}`,
        `leftKey.duration = ${leftKey.duration}`
      ].join('\n'));
      this.t2.setText([
        `rightKey.isDown = ${rightKey.isDown}`,
        `rightKey.duration = ${rightKey.duration}`
      ].join('\n'));
    }
  }
});
```
</details>

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/61425/36316254-f81c3da4-1320-11e8-9c52-aeb8d72f15c0.png)
![image](https://user-images.githubusercontent.com/61425/36316316-27c278a2-1321-11e8-9cf5-af1da663e9d6.png)
</details>

#### Expected behaviour
The `duration` property should update while a key is held down, preserve the last value when that key is held up, as documented.

#### Actual result
While a key is held down, `duration` is always zero. When that key is released, `duration` yields a random value.

**Comment by agilul** [comment]
Seems like it's firing `ProcessKeyDown` continously after ~500ms, updating `key.timeDown` in the meanwhile.
I guess it's the default Operating System behaviour with input management, like when you keep a key pressed to type it many times.

Could check in `ProcessKeyDown` if the key was already pressed and prevent overwriting `key.timeDown`.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
