### ISSUE TITLE
graphics.generateTexture always generates same Graphics object.

### ISSUE THREAD

**Issue by driescroons** [photonstorm/phaser#3241]
Since the 3.1.0 update I wanted to test out the generateTexture feature that got fixed but I don't the result returned is expected behaviour.

```
var config = { width: 800, height: 600, scene: { update }};
var game = new Phaser.Game(config);

function update() {
    graphics = this.add.graphics();
    
    var color = 0xffff00;
    var thickness = 2;
    var alpha = 1;

    graphics.lineStyle(thickness, color, alpha);

    graphics.strokeRect(32, 32, 256, 256);

    sprite = this.add.sprite(100,100, graphics.generateTexture());
}
```

I would expect the texture to be the same rectangle as the graphic we've created but no matter what graphic object I create, it keeps returning a green square.

Result: [Imgur](https://i.imgur.com/KWVC3gD.png)

I wanted to create a Phaser 3 Sandbox snippet but wasn't able to save the snippet.

**Comment by photonstorm** [comment]
`generateTexture` returns the Graphics instance itself, so you'd need to do:

```
graphics.generateTexture('someUniqueKey', width, height);
this.add.sprite(100, 100, 'someUniqueKey');
```

**Comment by driescroons** [comment]
Oh alright, my bad. Should've just checked out code reference instead. I was referencing to an old example on the website.

**Comment by photonstorm** [comment]
No worries, glad you got it working.
