### ISSUE TITLE
Problem with game.renderer.resize and canvas, global stage not resized (Phaser 3.1.0)

### ISSUE THREAD

**Issue by JimZeeKing** [photonstorm/phaser#3242]
Hi, i made a simple test here : [https://tim.cgmatane.qc.ca/phaser/v3/](https://tim.cgmatane.qc.ca/phaser/v3/)

It seems to show a problem with `game.renderer.resize()`.

To see the problem, start with your browser small and expand it, the canvas element will receive new dimensions, but the background color set in the config object wont stretch with it.

Unless i am doping somenthing wrong, i think this is not the intended behaviour.

Here is a direct link to the script : [https://tim.cgmatane.qc.ca/phaser/v3/assets/js/main.js](https://tim.cgmatane.qc.ca/phaser/v3/assets/js/main.js)

_See resizeGame function_

**Edit :** It seems that the Phaser main stage is not resized at all, but the canvas element is

**Edit 2:** It seems that the [official example](http://labs.phaser.io/edit.html?src=src\game%20config\game%20resize.js) is having the trouble too

**Comment by photonstorm** [comment]
Please see the new `Game.resize` function that is ready for testing in the `master` branch. This will resize the renderer, input system and game config values accordingly. If you find errors with it please open a new issue specific to them, thank you.
