### ISSUE TITLE
Camera Jitter

### ISSUE THREAD

**Issue by bradharms** [photonstorm/phaser#3245]
After updating to 3.0.0 release or above, camera follow now seems to have a random 1-pixel jitter that affects everything on the screen, like some kind of off-by-one or rounding error. This was never an issue in beta 20 or earlier.

This is my game config:
```javascript
{
      parent,
      type: Phaser.WEBGL,
      width: 400,
      height: 225,
      pixelArt: true,
      physics: {
        // @todo: Switch to 'matter' so we can use sloped tiles
        default: 'arcade',
        arcade: {
          // debug: true,
          gravity: {
            y: 450
          }
        }
      },
      scene: new RootScene(projectPath)
    }
```

In my create() function I have this call:
```javascript
this.cameras.main.setRoundPixels(true);
```

It may be worth noting that the jitter happens on both the X and the Y axis even though the camera boundary height is the same as the screen resolution height.

If I call setRoundPixels(false) instead then the issue goes away, BUT I get slight corruption in the edges of tiles being rendered plus a warbling/underwater effect due to pixel columns being slightly different sizes.

**Comment by bradharms** [comment]
The issue apparently started in commit 7b1ad0b307401bbd44921215228432b09a5a0513. The commit immediately before that doesn't have the issue.

**Comment by bradharms** [comment]
You can see the problem in action in the [follow sprite example](https://labs.phaser.io/view.html?src=src\camera\follow%20sprite.js) if you add the following line after `startFollow()` on line 35:

```javascript
this.cameras.main.setRoundPixels(true);
```

**Comment by bradharms** [comment]
I attempted to provide a fix for this by removing the lines from the preciously mentioned commit which were causing the rounding problems that lead to the jittering. Please let me know if this in an acceptable way to fix the problem, or else please provide more insight into why those changes were made in the first place so I can figure out another way to remedy this.

**Comment by photonstorm** [comment]
Hiya - thanks for your work on this and your PR. We have independently fixed this as part of a different batch of work on the renderer and this has now been pushed to the master branch. If you've time it would be great if you could build a version to test, but the fix will be part of the next official release too.

**Comment by bradharms** [comment]
Yes, the issue does appear to be fixed now. Thank you!
