### ISSUE TITLE
3.1.0 Phaser.Physics.Arcade.Sprite Resizing Doesn't Work

### ISSUE THREAD

**Issue by yigitozdemir** [photonstorm/phaser#3247]
Hi Everyone,

I am trying to move into Phaser 3.1.0, this is my very first step into Phaser 3. I initialized a scene using Arcade Physics, everything is working great but i can not resize Sprites.

`    create: function(){
        this.physics.world.setBounds(0, 0, 400, 400);
        var star = this.physics.add.sprite(128, 128, 'star');
        star.width = 20;
        star.height = 20;
        star.setGravity(40, 100);
        star.setBounce(1).setCollideWorldBounds(true);
    },`

According to documentation width is defined as:

> The native (un-scaled) width of this Game Object.

I think it is an issue about scaling game objecs.

Thanks every greate one in this great community!

**Comment by agilul** [comment]
Use `.displayWidth` and `.displayHeight` (or the function `.setDisplaySize(w,h)`) to resize, as these will also adjust the sprite scale.

**Comment by yigitozdemir** [comment]
Oh thank you that worked.

But now, image and body moves seperately, https://i.hizliresim.com/bBLPdb.png
Modified code to this, but it didn't work:

`    create: function(){
        this.physics.world.setBounds(0, 0, 400, 400);
        var star = this.physics.add.sprite(128, 128, 'star');
        star.displayWidth = 20;
        star.displayHeight = 20;
        star.x = star.body.position.x;
        star.y = star.body.position.y;
        star.setGravity(40, 100);
        star.setBounce(1).setCollideWorldBounds(true);
    },`

**Comment by agilul** [comment]
Yeah it seems like the physics body doesn't correctly update after modifying the sprite scale.
Needs some checking on the calculations there.

**Comment by yigitozdemir** [comment]
I discovered that, we need to set display origin 0 before resizing: 

`create: function(){
        this.physics.world.setBounds(0, 0, 400, 400);
        var star = this.physics.add.sprite(128, 128, 'star');
        star.displayOriginX = 0;
        star.displayOriginY = 0;
        star.displayWidth = 20;
        star.displayHeight = 20;
        star.x = 0;
        star.y = 0;
        star.setGravity(40, 100);
        star.setBounce(1).setCollideWorldBounds(true);
    },`

I used to scale everything mathematically on my previous games, that will be hard to get used to for me.

**Comment by pixelpicosean** [comment]
The physics body align issue has been solved in PR #3300

**Comment by photonstorm** [comment]
Sweet, thanks @pixelpicosean
