### ISSUE TITLE
Setting Origin seem to have no effect on bitmapText...

### ISSUE THREAD

**Issue by amkazan** [photonstorm/phaser#3249]
Phsaser 3.1
Setting Origin seem to have no effect on bitmapText...

text=scene.add.bitmapText(0, 0, 'font',"noice" ,30);
text.setOrigin(0.5)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
