### ISSUE TITLE
tint and alpha corners are incorrect

### ISSUE THREAD

**Issue by Rybar** [photonstorm/phaser#3252]
It appears that tintTopRight, tintTopLeft, etc. and alphaTopRight.. etc are not pointing at the correct corners visually.

![screenshot 2018-02-18 00 48 51](https://user-images.githubusercontent.com/145812/36349127-91d2d3e8-1445-11e8-93f4-dbe90cd55470.png)
  
I've got a live example here:
https://jsfiddle.net/02sdm0tc/5/

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch and will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by Rybar** [comment]
built and tested, works as expected.  👍
