### ISSUE TITLE
Phaser.Event missed

### ISSUE THREAD

**Issue by atrancaburras** [photonstorm/phaser#3253]
In 3.0 and 3.1 Phaser.Event not exist:
Uncaught TypeError: Phaser.Event is not a constructor

This issue  can be checked in the examples:
[http://labs.phaser.io/view.html?src=src\events\078%20event%20dispatcher.js](http://labs.phaser.io/view.html?src=src\events\078%20event%20dispatcher.js)

**Comment by photonstorm** [comment]
Sorry, yes, there's no such thing as a Phaser.Event class. We are tidying up all the examples this week to avoid confusions like this, sorry for wasting your time.
