### ISSUE TITLE
phaser3 headless not working?

### ISSUE THREAD

**Issue by rgk** [photonstorm/phaser#3256]
* A bug in the API.

I was trying to put phaser on the server, mostly because of my want for arcade physics. Phaser 3 is more modular then phaser 2 so I was hoping I could strip out what is not needed on the server. When I set the renderer to headless this is what echos back:
     Phaser v3.1.0 (WebGL | Web Audio)  https://aerialdrop.com/

I also seem to have tons and tons of calls to canvas which breaks a lot.

Should this show Headless instead of WebGL?

**Comment by photonstorm** [comment]
Right now there are only two valid renderers: Canvas and WebGL. We will add a headless mode shortly and have flagged this as a feature request until we complete that work.

**Comment by rgk** [comment]
@bamsutler I have also see use of http://phantomjs.org/

My general issue here is performance though, I ended up going with matter.js on the server and I'm also using it with phaser v3 client side.

**Comment by photonstorm** [comment]
Headless mode is now supported in the master branch. Please test.

**Comment by rosancoderian** [comment]
can i do the headless mode in node.js environment?

**Comment by rgk** [comment]
@rosancoderian yes, you will need canvas on node though, something like this: https://github.com/Automattic/node-canvas

**Comment by rosancoderian** [comment]
i got these errors when requiring phaser module in node.js
ReferenceError: navigator is not defined
ReferenceError: WEBGL_RENDERER is not defined

**Comment by EricEisaman** [comment]
Are there any simple examples in the community at this point which use phaser3 headless?

**Comment by iamchristopher** [comment]
@EricEisaman There's [an example](http://labs.phaser.io/view.html?src=src\game%20config\headless%20renderer.js) available in the labs, but it looks like headless rendering is broken in v3.7.1

**Comment by EricEisaman** [comment]
@iamchristopher Thanks.
