### ISSUE TITLE
Bug: status of scene is not correct when changing status in 'create' stage

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3257]
* A bug in the phaser3 engine 3.1.0

Here is the simplest source code of this issue:
```
function preload() {
}
function create() {
    this.sys.sleep();  // try to sleep this scene at beginning
}
var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create
    }
};
var game = new Phaser.Game(config);
```

`function create()` will be invoked in SceneManager, [create function](https://github.com/photonstorm/phaser/blob/master/src/scene/SceneManager.js#L401), and reset the status to [`RUNNING` ](https://github.com/photonstorm/phaser/blob/master/src/scene/SceneManager.js#L410), thus the status won't be `SLEEPING`.

**Comment by photonstorm** [comment]
Do it via the Scene Plugin instead and it should queue it ready: `this.scene.sleep()`.

**Comment by rexrainbow** [comment]
Oops, my mistake, sorry.
