### ISSUE TITLE
Filipino Localization of Readme.md

### ISSUE THREAD

**Issue by cordeta** [photonstorm/phaser#3263]
Hi there ! i would like to create a tagalog localization of your README.md . Thus, this will help you reach some of Filipino gamers who would like to play your game . Rest assured that my work is credible

If you may , please make a Language Folder so i could create a TL translation folder there. 

Thanks !

**Comment by photonstorm** [comment]
Sorry for the delay in replying to this. The README file changes really frequently - it has been updated 3 times this week for example. While I would love to have it translated it is changing so often I really worry it would be out of date almost immediately :-/
