### ISSUE TITLE
Add animation event example broken

### ISSUE THREAD

**Issue by givionte** [photonstorm/phaser#3265]
- Example Add animation event does not load

[https://labs.phaser.io/view.html?src=src\animation\add%20animation%20event.js
](https://labs.phaser.io/view.html?src=src\animation\add%20animation%20event.js
)
I've been looking through many of the examples and trying them out in my own environment.  This example fails on the labs page, and throws up errors in VS code Line 26 reads 'Cannot find name 'addAnimation'. Did you mean the instance member 'this.addAnimation'?'.  Changing that did nothing in the lab environment and my own.

**Comment by photonstorm** [comment]
This example is now fixed, thank you.
