### ISSUE TITLE
Object based atlas loader not working properly

### ISSUE THREAD

**Issue by seancheung** [photonstorm/phaser#3268]
* A bug in the API (v3.1.1)

I followed what the [official api doc](https://phaser.io/phaser3/api/loader) says:

```javascript
//  Original atlas loader signature:
//  this.load.atlas(key, textureURL, atlasURL, textureXhrSettings, atlasXhrSettings)

this.load.atlas('level1', 'assets/level1/items.png', 'assets/level1/items.json');

//  Object based
this.load.atlas({ key: 'level1', texture: 'assets/level1/items.png', data: 'assets/level1/items.json' });
```

The original method works fine, but using the object based signature will always cause the loader to fetch `{key}.png` and `{key}.json` no matter what the passed texture/data values are.

For this example, calling `this.load.atlas({ key: 'level1', texture: 'assets/level1/items.png', data: 'assets/level1/items.json' })`

**Expects**: 

`HTTP GET /assets/level1/items.png`
`HTTP GET /assets/level1/items.json` 

**But Get**:

`HTTP GET /level1.png`
`HTTP GET /level1.json`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
