### ISSUE TITLE
onUpdate() calls of tween timeline keep firing after target has been destroyed

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3270]
So as the title indicates, if a sprite is the target of a timeline and gets destroyed at some point, the `onUpdate()` calls of the timeline will keep firing until the end. I have reproduced this in 
 [this fiddle](https://jsfiddle.net/uL1bbe8s/7/) .  A `setTimeout()` call destroys the image after 1 second, but the as can be seen in the console, the `onUpdate()` calls keep firing long after. This is problematic when the onUpdate calls attempt to modify the target.

**Comment by hilts-vaughan** [comment]
Should you really be destroying Phaser Objects with setTimeout? I figured a Phaser Time was for that.

**Comment by photonstorm** [comment]
No, but I don't think it matters in this case - as what it's demonstrating is that Tweens are not checking if targets still exist or not before trying to modify their properties.

If you do nuke a Game Object outside of the game step (i.e. via setTimeout) then on your head be it really, but I think there's still an issue here to fix.

I've updated the code in master so a TweenData will now check to see if a target exists before updating it, but this still may not be enough. What we may require is that when you destroy a Game Object it doesn't actually do anything, it just flags it as destroyed, and then added to a purge list which is cleared at the end of the Scene step. This should help avoid race conditions like you'd get with setTimeout, but it also means your code would have to assume and account for the fact it may be a whole frame before the object is actually removed.

**Comment by photonstorm** [comment]
I added a conditional check into the 3.1.2 release that addresses this issue, so a Tween will no longer update an undefined target. I'm still tempted to look at using a destroy queue though. For now, please test 3.1.2 against this situation.
