### ISSUE TITLE
In tutorials part5, particleEmitter is not working with 3.1.1

### ISSUE THREAD

**Issue by xyzith** [photonstorm/phaser#3275]
https://phaser.io/tutorials/getting-started-phaser3/part5
ParticleEmitter is not working with 3.1.1

**Comment by rexrainbow** [comment]
Another bug in section `Making a Game in Phaser Tutorial` in [Part 6 - The Phaser Examples](https://phaser.io/tutorials/getting-started-phaser3/part6), the link [Making a Game in Phaser 3](http://phaser.io/tutorials/making-your-first-phaser3-game) directs to 404.

**Comment by photonstorm** [comment]
Yes, sorry about this (see #3274) - all fixed in 3.1.2 which is now live on the site and published to the examples too, so should be good now. Also fixed that 404.
