### ISSUE TITLE
Phaser.ScaleManager.RESIZE; has no canvas/screen size limit.

### ISSUE THREAD

**Issue by nandobentzen** [photonstorm/phaser#3276]
Noob here using Phaser. But here's my issue:
I'm struggling to get to a perfect scale on the game I'm building. The best option for me so far is Phaser.ScaleManager.RESIZE; 
But this method doesn't have a limit to the canvas size. If an user has a huge screen, say 30 inches, he'd have a lot of advantage over an user with a medium size screen, say 17 inches. The 30 inches user would have much more view of the world.

I've tried to set the canvas to a fixed size, like 1280x720, then dynamically resize the canvas style. And using Phaser.ScaleManager.SHOW_ALL;  But it doesn't do the trick because it shows the black borders and I can't get rid of it.

To make it clear what I want to achieve, I'm building an online multiplayer game (.io). If you notice the most famous .io games like agar.io, diep.io and slither.io, the game scale is perfect for any screen size. If the screen is too big, the game doesn't show more screen. It just adjusts for a more zoomed game.

Here's a gif of what I need and how my game is now:
agar.io: 
[![Screenshot from Gyazo](https://gyazo.com/94a41e06816b8dc9a1fd4608c0cfa525/raw)](https://gyazo.com/94a41e06816b8dc9a1fd4608c0cfa525)
Notice that in agario, the screen only goes so far before the game starts to scale.

My game:
[![Screenshot from Gyazo](https://gyazo.com/4269ecfb1253b9ddbcd6e917ad1a8602/raw)](https://gyazo.com/4269ecfb1253b9ddbcd6e917ad1a8602)
Notice how much of the world I can see after scaling the game. Meaning that there is no limit for the canvas.

Please let me know if you need more information in order to help me out here!

Thanks in advance!

**Comment by photonstorm** [comment]
Thank you for taking the time to work on this and open your issue. However, Phaser 2 is now maintained in the [Phaser CE GitHub repo](https://github.com/photonstorm/phaser-ce). Also, as this is more of a support question rather than a potential bug in the framework, you may find you get a more helpful response from the Phaser 2 Forum, rather than GitHub.
