### ISSUE TITLE
[request] deciding wether tween.stop() should trigger the onComplete callback

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3280]
I found very useful in Phaser 2 that `tween.stop()` was accepting an argument to control whether the `onComplete` callback should fire or not when interrupting the tween. It would be great to have this in Phaser 3 as well. For now, `tween.stop()`  stops the tween without calling `onComplete`. 

Unless there is a reason not to/a different way to do so now?

**Comment by photonstorm** [comment]
This feature has been added. I didn't want to add it to Tween.stop because of the `resetTo` argument, but I think this works well enough as its own method.
