### ISSUE TITLE
Broken drag example - Camera Move and Rotate

### ISSUE THREAD

**Issue by zdandoh** [photonstorm/phaser#3281]
This Issue is about

* An error on the web site (example broken)

The following example seems to be broken:
https://labs.phaser.io/view.html?src=src/input/dragging/camera%20move%20and%20rotate.js

When I run it locally I get the following error:
`Uncaught TypeError: cards.rotate is not a function`

Commenting out the call to rotate makes the scene render, but it doesn't seem like the handler for "DRAG_EVENT" ever gets called, so there may be some issue with that as well. I haven't been able to get "DRAG_EVENT" to work on my own in other contexts either.

**Comment by photonstorm** [comment]
Sorry about that, none of the drag examples had been updated. I have fixed them all today, so check out the latest versions in the repo / on labs and you'll see how to get dragging working!
