### ISSUE TITLE
Offset in sprites vs matter physics objects

### ISSUE THREAD

**Issue by CodeAndWeb** [photonstorm/phaser#3282]
Phaser Version: 3.1.1
Browser: Safari, Chrome

MatterJs uses the center of mass as the reference point for the physic shapes.
The phaser3 examples all work because the sprite's center and the center of mass are identical.

Sprites like this one don't work: (Triangle in the bottom right center of the sprite):

![2018-02-26_14-09-45](https://user-images.githubusercontent.com/716009/36672211-c76a9ae4-1afe-11e8-8e3a-eecb64739c58.png)

![2018-02-26_14-08-21](https://user-images.githubusercontent.com/716009/36672162-8f66c32a-1afe-11e8-926c-24d163b85b84.png)

There's an offset between the physics shape and the sprite. The renderer has to compensate for this difference.

Demo of the bug: https://www.codeandweb.com/public/demos/phaser3-matter-bug/index.html

Project for download: [phaser-matter.zip](https://github.com/photonstorm/phaser/files/1758666/phaser-matter.zip)

    const shapes = {
        "triangle": [
            [ {"x":99,"y":79}, {"x":77,"y":118}, {"x":124,"y":118} ]
        ]
    };

    function create ()
    {
        var img1 = this.matter.add.sprite(game.config.width/2, 200, 'triangle', null, { shape: { type: 'fromVerts', verts: shapes.triangle }});
    }

**Comment by photonstorm** [comment]
This is fixed in 3.3.0 in the master branch. It will now set the sprite origin to match the x/y offset of the body, but to adjust it for cases like this (where the image is not central) you need to supply the offset values to matter:

```
    var triangle = this.matter.add.sprite(400, 100, 'triangle', null, {
        shape: { type: 'fromVerts', verts: shapes.triangle },
        render: { sprite: { xOffset: 0.30, yOffset: 0.15 } }
    });
```

3.3 + the above offsets work properly for me in your example.

**Comment by jtsiskin** [comment]
I don't believe this was fixed. I'm still having the same issue in 3.16

**Comment by CodeAndWeb** [comment]
The fix above just adjusts the offset in this special case.

The problem is fixed if you use PhysicsEditor: It contains a calculation for the correct offset.
See this tutorial: https://www.codeandweb.com/physicseditor/tutorials/how-to-create-physics-shapes-for-phaser-3-and-matterjs

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/matter-sprite-with-vertices-and-center-of-mass-not-fitting-image/9472/2
