### ISSUE TITLE
Allow different render orders for Tilemap layers

### ISSUE THREAD

**Issue by etienne** [photonstorm/phaser#3284]
This Issue is about a feature request (3.1.2).

Phaser currently renders tiles in a right down direction (starting from the top left corner). This is fine in most cases, but in some cases other render orders may be needed. The Tiled editor offers four options (right down, right up, left down, left up), which it includes in its exported JSON maps (under the `renderorder` key).

Here is an example of a case where a different render order is required (left down in this case):

![render-order](https://user-images.githubusercontent.com/9656/36690616-db413ada-1b00-11e8-9d3e-bd8212c5461e.png)

The feature I suggest would include:
* Supporting all four render orders for tilemap layers
* Respecting the value specified in Tiled JSON maps

Thanks!

**Comment by etienne** [comment]
@photonstorm Here's a test project with a sample map: https://github.com/etienne/tileorder-test

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

All 4 draw orders are supported for both Dynamic and Static Layers :) You can find tests in the Labs and docs in the repo.

**Comment by etienne** [comment]
Just now had a chance to test it, it works perfectly! Just wanted to say thanks.
