### ISSUE TITLE
Texture packer atlas animation ignores pivot points

### ISSUE THREAD

**Issue by CodestarGames** [photonstorm/phaser#3288]
* A bug in the API (version 3.1.2)

So I loaded in a regular texturepacker atlas for phaser v3 
and set some pivot points on the frames.

The expected behavior should be that it offsets the frames by the pivot points per animation frame, changing the height/width if each frame is a different size, but always re-orienting the frames in accordance with their pivot point.

![recording](https://user-images.githubusercontent.com/5861090/36714377-fcec78a2-1b5f-11e8-8c0a-ce052b79b8ed.gif)

```javascript

    this.load.atlas('mario-sprites', 'assets/sprites/source/mario.png', 'assets/sprites/mario/mario.json');

                        this.anims.create({
                            key: 'idle',
                            frames: this.anims.generateFrameNames('mario-sprites', { prefix: 'mario/attack/', end: 5, zeroPad: 4 }),
                            repeat: -1,
                            frameRate: 10,
                            yoyo: false
                        });

//example atlas file
{
	"textures": [
		{
			"image": "mario.png",
			"format": "RGBA8888",
			"size": {
				"w": 128,
				"h": 128
			},
			"scale": 1,
			"frames": [
				{
					"filename": "mario/attack/0003",
					"frame": {
						"x": 1,
						"y": 1,
						"w": 46,
						"h": 54
					},
					"rotated": false,
					"trimmed": true,
					"spriteSourceSize": {
						"x": 0,
						"y": 0,
						"w": 46,
						"h": 54
					},
					"sourceSize": {
						"w": 40,
						"h": 52
					},
					"anchor": {
						"x": 0,
						"y": 1
					}
				},
				{
					"filename": "mario/attack/0004",
					"frame": {
						"x": 1,
						"y": 57,
						"w": 46,
						"h": 38
					},
					"rotated": false,
					"trimmed": true,
					"spriteSourceSize": {
						"x": 0,
						"y": 0,
						"w": 46,
						"h": 38
					},
					"sourceSize": {
						"w": 42,
						"h": 37
					},
					"anchor": {
						"x": 0,
						"y": 1
					}
				},
				{
					"filename": "mario/attack/0005",
					"frame": {
						"x": 1,
						"y": 97,
						"w": 46,
						"h": 30
					},
					"rotated": false,
					"trimmed": true,
					"spriteSourceSize": {
						"x": 0,
						"y": 0,
						"w": 46,
						"h": 30
					},
					"sourceSize": {
						"w": 39,
						"h": 30
					},
					"anchor": {
						"x": 0,
						"y": 1
					}
				},
				{
					"filename": "mario/attack/0001",
					"frame": {
						"x": 49,
						"y": 1,
						"w": 38,
						"h": 38
					},
					"rotated": false,
					"trimmed": true,
					"spriteSourceSize": {
						"x": 0,
						"y": 0,
						"w": 38,
						"h": 38
					},
					"sourceSize": {
						"w": 38,
						"h": 32
					},
					"anchor": {
						"x": 0.684211,
						"y": 0.96875
					}
				},
				{
					"filename": "mario/attack/0002",
					"frame": {
						"x": 89,
						"y": 1,
						"w": 38,
						"h": 38
					},
					"rotated": false,
					"trimmed": true,
					"spriteSourceSize": {
						"x": 0,
						"y": 0,
						"w": 38,
						"h": 38
					},
					"sourceSize": {
						"w": 37,
						"h": 33
					},
					"anchor": {
						"x": 0.702703,
						"y": 1
					}
				},
				{
					"filename": "mario/idle/0003",
					"frame": {
						"x": 49,
						"y": 41,
						"w": 30,
						"h": 38
					},
					"rotated": false,
					"trimmed": true,
					"spriteSourceSize": {
						"x": 0,
						"y": 0,
						"w": 30,
						"h": 38
					},
					"sourceSize": {
						"w": 23,
						"h": 32
					},
					"anchor": {
						"x": 0.5,
						"y": 1
					}
				},
				{
					"filename": "mario/idle/0001",
					"frame": {
						"x": 49,
						"y": 81,
						"w": 22,
						"h": 38
					},
					"rotated": false,
					"trimmed": true,
					"spriteSourceSize": {
						"x": 0,
						"y": 0,
						"w": 22,
						"h": 38
					},
					"sourceSize": {
						"w": 20,
						"h": 34
					},
					"anchor": {
						"x": 0.5,
						"y": 1
					}
				},
				{
					"filename": "mario/idle/0002",
					"frame": {
						"x": 73,
						"y": 81,
						"w": 22,
						"h": 38
					},
					"rotated": false,
					"trimmed": true,
					"spriteSourceSize": {
						"x": 0,
						"y": 0,
						"w": 22,
						"h": 38
					},
					"sourceSize": {
						"w": 22,
						"h": 33
					},
					"anchor": {
						"x": 0.5,
						"y": 1
					}
				},
				{
					"filename": "mario/idle/0004",
					"frame": {
						"x": 73,
						"y": 81,
						"w": 22,
						"h": 38
					},
					"rotated": false,
					"trimmed": true,
					"spriteSourceSize": {
						"x": 0,
						"y": 0,
						"w": 22,
						"h": 38
					},
					"sourceSize": {
						"w": 22,
						"h": 33
					},
					"anchor": {
						"x": 0.5,
						"y": 1
					}
				}
			]
		}
	],
	"meta": {
		"app": "https://www.codeandweb.com/texturepacker",
		"version": "3.0",
		"smartupdate": "$TexturePacker:SmartUpdate:76800206bd86ead14baabd4edaa784e1:24386c9ddd9a7c8719a262b77c11ec17:049a1e10ddf44989e4af4e84fecd01e8$"
	}
}


```

**Comment by CodestarGames** [comment]
So after doing some additional digging, I found that the problem was that the parent sprite's OriginX and OriginY were not getting updated to what the PivotX and PivotY is in the current animation. I managed to fix my problem by doing the following code in my sprite's class.

```javascript
  preUpdate (time, delta) {

      this.setOriginFromFrame();
      this.setSizeToFrame();
      this.updateDisplayOrigin();

      super.preUpdate(time, delta);

  }
``` 
However, I feel that if the sprite has an animation with pivot points set on it's frames, it should automatically set the originX and originY of it's parent's sprite to what it is. I also had to set the parent sprite's size manually as well in the code above, because it too wasn't getting updated to what the size was of the current animation frame.

**Comment by photonstorm** [comment]
I did think about doing this automatically but hit the problem whereby it wasn't possible to tell if you'd manually set your own origin on a sprite, then if you play an animation it would overwrite that origin with whatever was set on each frame (same goes for dimensions) - I guess maybe that's just something you have to put up with if you play an animation (losing any previously set origin)

It should probably use the frame anchor / pivot _relative_ to the origin and never actually change it, but that will require quite a refactor internally first.

**Comment by CodeAndWeb** [comment]
TexturePacker only writes pivot points if they are enable on the sprite sheet. `anchorPoint` is left empty if they are disabled.

Maybe it would be an option to set them from the frame if they are enabled and use keep the sprite's pivots if they are disabled? This would give the user the freedom to use them or not.

**Comment by photonstorm** [comment]
The master branch has been updated with this a few days ago: "The `setFrame` method of the Texture component has been updated so that it will now automatically reset the `width` and `height` of a Game Object to match that of the new Frame. Related, it will also adjust the display origin values, because they are size based. If the Frame has a custom pivot it will set the origin to match the custom pivot instead." - I'm still not convinced this is a great idea, but let's go with it and see what happens!

**Comment by DouglasLapsley** [comment]
Thanks, this sounds like exactly what I need.  Probably being very dim, but how do I use it please?  I currently have the following in the create function:

```
this.ninja = this.physics.add.sprite(this.gameWidth/2, this.gameHeight/2, 'sprites', 'stand').setCollideWorldBounds(true);
this.ninja.play('run');
```
...and this in the update function:

```
        if(this.ninjaFrameNo == 6){
            this.ninjaFrameNo = 1;
        }
        this.ninja.setFrame('run' + this.ninjaFrameNo, true, true);
        this.ninjaFrameNo++;
```
This sort of works, but is clearly **horrible** and looses all the framerate config etc.  

What's the proper way to use this please?  

Thanks!
