### ISSUE TITLE
RandomDataGenerator.frac is not so random

### ISSUE THREAD

**Issue by migiyubi** [photonstorm/phaser#3289]
* A bug in the API v3.1.2

The difference between first two numbers returned by RandomDataGenerator.frac
is always almost-equal even if the seed is different.

    Phaser.Math.RND.sow([Date.now()]);
    console.log(Phaser.Math.RND.frac() - Phaser.Math.RND.frac()); // always about -0.056

EDIT: The original implementation of Alea is different from that of Phaser in the following points.

1) In [hashing](https://github.com/coverslide/node-alea/blob/master/alea.js#L89) function, Alea caches "n" but Phaser doesn't.
2) In [sowing](https://github.com/coverslide/node-alea/blob/master/alea.js#L37) function, Alea initializes (s0, s1, s2) using the same string, but Phaser doesn't.

It seems (1) causes such regularity. (2) is not essential.

**Comment by photonstorm** [comment]
Our class is a port of [Nonsense](https://github.com/jocafa/Nonsense/blob/master/Nonsense.js) - I just checked their code and I think this issue is present in that library too (for the same reasons quite likely) - happy to receive a PR for this if you fancy trying it?
