### ISSUE TITLE
Bug:  incorrect event name and callback parameter in input/zones/ examples

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3291]
This Issue is about (delete as applicable)
* An error on the example

Event name and callback parameters are incorrect in 
- [input/zones/basic input zone.js](https://github.com/photonstorm/phaser3-examples/blob/master/public/src/input/zones/basic%20input%20zone.js#L44)
- [input/zones/circular drop zone.js](https://github.com/photonstorm/phaser3-examples/blob/master/public/src/input/zones/circular%20drop%20zone.js#L47)
- [input/zones/drop zone.js](https://github.com/photonstorm/phaser3-examples/blob/master/public/src/input/zones/drop%20zone.js#L47)
- [input/zones/resize zone.js](https://github.com/photonstorm/phaser3-examples/blob/master/public/src/input/zones/resize%20zone.js#L29)

Event names are `gameobjectdown`, `drag`, `dragstart`, etc...

**Comment by photonstorm** [comment]
These have now all been fixed - which uncovered a bug with drop zones, which is now fixed in the master branch too.
