### ISSUE TITLE
Module parse fail on WebGL Shaders: Unexpected character '#'

### ISSUE THREAD

**Issue by pixelhijack** [photonstorm/phaser#3293]
I haven't really found a similar issue like this here, but I'm getting the following error after `npm install phaser` (installed the latest, 3.1.2) and ES6 importing it into the project (`import Phaser from 'phaser'`) after Webpack build: 

![screen shot 2018-02-27 at 15 40 25](https://user-images.githubusercontent.com/5672651/36734845-ffe7b2b8-1bd4-11e8-8581-257c4288ab7f.png)

ERROR in ./~/phaser/src/renderer/webgl/shaders/ForwardDiffuse.frag
Module parse failed: /Users/attilapoth/dev/platformer-state-machine/node_modules/phaser/src/renderer/webgl/shaders/ForwardDiffuse.frag Unexpected character '#' (1:0)

Babel and webpack config was set for the previous versions. 
Is there anything I miss?

**Comment by photonstorm** [comment]
Are you using the [Phaser 3 webpack project template](https://github.com/photonstorm/phaser3-project-template)? It has special build flags in the config that you'll need.

**Comment by pixelhijack** [comment]
Hi Rich! thank you for the quick reply! No, i was trying to use my own webpack project template for older versions, i saw there are multiple templates including quite complex ones, but was not aware we have this simple one! Thanks! 

(I see now in the documentation and the Phaser 3 release page, maybe it would worth to highlight even more in the documentation that if you want to setup a project it will need special webpack configs. Anyway, great work, super community, keep up the spirit, i am planning to contribute)

**Comment by pixelhijack** [comment]
@photonstorm also, is there an official Phaser 3 + Webpack + ES6 boilerplate project template? I see lots of boilerplate projects, some with ES6, most of them is very verbose as boilerplate projects usually are - is there one you could approve as an official?

**Comment by rblopes** [comment]
@pixelhijack There's a [discussion](http://www.html5gamedevs.com/topic/35798-phaser-3-boilerplates-starters-list-discussion-and-features/) at the Phaser 3 forums about building a community-driven boilerplate happening now.

**Comment by pixelhijack** [comment]
@rblopes just what i was looking for, thanks!!

**Comment by photonstorm** [comment]
Closing off this issue as I've added to the readme the importance of using our webpack config.
