### ISSUE TITLE
Documentation: Broken Link to Code of Conduct in phaser/.github/CONTRIBUTING.md

### ISSUE THREAD

**Issue by melissaelopez** [photonstorm/phaser#3297]
This Issue is about:
* An error in the documentation

Hello! I have noticed that in the first section of CONTRIBUTING.md, the link to the code of conduct is outdated, and thus results in a 404 error. See the image below to see the broken link highlighted in blue. 

<img width="955" alt="screen shot 2018-02-28 at 1 51 24 pm" src="https://user-images.githubusercontent.com/16906897/36806595-80da908e-1c8e-11e8-8d09-6ff6f49d2b63.png">

The fix would be to edit the url of the link from "[...]/v2/CODE_OF_CONDUCT.md", to "[...]/.github/CODE_OF_CONDUCT.md". I'm happy to issue a pull request with this fix!

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
