### ISSUE TITLE
Game.resize not working properly (Phaser 3.2)

### ISSUE THREAD

**Issue by JimZeeKing** [photonstorm/phaser#3302]
I have updated the code here to use the master branch version to test game.resize() function [here](http://tim.cgmatane.qc.ca/phaser/v3/)

The canvas is resized, but it seem phaser stage is not (you can see it by playing with the browser dimensions as my text is always centered in the browser window)

In canvas mode, i see the background-color get resized, but not in WebGL. Both modes show that the Phaser stage is not resized correctly.

[Here](https://tim.cgmatane.qc.ca/phaser/v3/assets/js/main.js) is my setup code.

Thanks a bunch for your work!

**Comment by photonstorm** [comment]
Can you post your code for the Menu scene as well please.

**Comment by JimZeeKing** [comment]
[Here is the menu script code](https://tim.cgmatane.qc.ca/phaser/v3/assets/js/menu.js)

**Comment by photonstorm** [comment]
This is working properly in 3.4. I've updated the example to show how to use it properly with a window event + tile sprite: http://labs.phaser.io/view.html?src=src\game%20config\game%20resize.js

**Comment by JimZeeKing** [comment]
Yes it does!

Thanks a bunch Rich!

**Comment by charneykaye** [comment]
@photonstorm as of 3.19 I'm seeing "TypeError: game.resize is not a function"

Core example is broken https://phaser.io/examples/v3/view/game-config/game-resize#
