### ISSUE TITLE
Perspective Camera scale issue

### ISSUE THREAD

**Issue by devhang** [photonstorm/phaser#3305]
I'm interested to test the ability of 3D camera usage, that is the main reason to push me to Phaser 3.
I follow the example at https://labs.phaser.io/view.html?src=src\camera\3D%20camera\perspective%20camera.js

it seems work nice, but when I play around it with some non square sprite, I found that the camera will scale the sprite disproportionally
![image](https://user-images.githubusercontent.com/1468055/36889605-bde65adc-1e35-11e8-8e4e-76f0ebf55196.png)

Here is my scene snippet (base on Phaser 3.2.0 as the latest repo)
```
  this.preload = function() {
    this.load.image('star', 'assets/star.png');
    this.load.image('bomb', 'assets/bomb.png');
    this.load.spritesheet('dude', 'assets/dude.png', {frameWidth: 32, frameHeight: 48});
  }

  this.create = function() {
    this.camera = this.cameras3d.add(90).setPosition(0, 0, 20);

    this.player = this.camera.create(0, 0, 0, 'dude');

    this.anims.create({
      key: 'left',
      frames: this.anims.generateFrameNumbers('dude', { start: 0, end: 3 }),
      frameRate: 10,
      repeat: -1
    });

    this.anims.create({
      key: 'turn',
      frames: [ { key: 'dude', frame: 4 } ],
      frameRate: 20
    });

    this.anims.create({
      key: 'right',
      frames: this.anims.generateFrameNumbers('dude', { start: 5, end: 8 }),
      frameRate: 10,
      repeat: -1
    });

    this.player.gameObject.anims.play('turn');

    cursors = this.input.keyboard.createCursorKeys();
  }
```

what my expect is the below
![image](https://user-images.githubusercontent.com/1468055/36889655-f180ed26-1e35-11e8-9a18-cee0c6cdf790.png)

I think that the camera will calculate scale of sprite in NDC, but use this scale params at screen space, so issue came out, or am I misunderstanding to use the 3D Camera API, thanks.

**Comment by photonstorm** [comment]
Sorry, this fell by the wayside. Yes, this happens on purpose but isn't made clear in the docs. Camera 3D support is being removed from core and moved to a plugin with 3.12, so I'll look to address it from there.

**Comment by photonstorm** [comment]
I've had a look into this and the scaling is correct based on the perspective of the Camera. If you wish you can stop the objects from being scaled vertically (or horizontally) by setting the `adjustScaleX/Y` booleans, or you could change the amount of distortion by changing the fov of the camera.
