### ISSUE TITLE
Support Curves.QuadraticBezier in the API

### ISSUE THREAD

**Issue by RiCoTeRoX** [photonstorm/phaser#3306]
Add QuadraticBezier in the API

**Comment by photonstorm** [comment]
Feel free.

**Comment by RiCoTeRoX** [comment]
Ok.
[#3307](https://github.com/photonstorm/phaser/pull/3307)

**Comment by photonstorm** [comment]
PR merged and updated. In future there's no need to open an issue as well, the PR on its own is enough.
