### ISSUE TITLE
Group#createCallback is called by Group#add, not Group#create

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#3308]
This Issue is about

* A bug (?) in the API: v3.1.2

Expected: Phaser.GameObjects.Group#createCallback is called only in Phaser.GameObjects.Group#create.

Actual: Phaser.GameObjects.Group#createCallback is called only in Phaser.GameObjects.Group#add.

**Comment by photonstorm** [comment]
It's called by `Group.create` as well, because `create` passes over to `add` for the final step.
