### ISSUE TITLE
[iOS] Input event issues

### ISSUE THREAD

**Issue by chancezeus** [photonstorm/phaser#3311]
Because the input events on phaser are async with respect to the actual event (they are handled during the "update" cycle and not directly in the pointerdown/touchdown/click trigger), I seem to be unable to trigger some stuff that "requires" user interaction (audio, trigger the keyboard (by focussing a hidden text input)) since the function trace does not lead back to the actual user input event...

Is there a trick I can use to have the phaser input system behave in such a way that iOS does play the audio or shows the keyboard when the user touched a button or tries to focus my input area or am I out of luck here...

I'm using the latest release from npm.

**Comment by chancezeus** [comment]
Did a quick and dirty test/fix this morning and found one (not so nice, but it works) solution:

In the `src/input/touch/TouchManager.js`:
Add a reference to `this` in the startListeners method (something like: `var that = this`;) and then update the handler to call `that.manager.game.loop.tick()`.

By running a "tick" of the engine the update loop(s) get triggered on the same call as the input happened and at least the input focus works as expected.

Unfortunately audio (both html5 and webaudio) still seem broken (at least on iOS) so I will have to look into that further

**Comment by chancezeus** [comment]
Also traced the audio issue (at least for html5 audio), my game does not load/use any audio in the beginning (it will load assets as needed based on the progress) and the HTML5AudioSoundManager's unlock function will fail if there are no assets yet but does remove the event listeners...

To remedy this I injected the following before the removal of the listeners:
```js
            if (!_this.game.cache.audio.entries.size)
            {
                return;
            }
```

This way the unlock listener remains attached up until the point where there actually is any audio loaded instead of removing itself and failing with a "undefined" error.

**Comment by photonstorm** [comment]
Thanks for opening this issue. I think there are 2 separate things going on here. The first is the bug with not unlocking audio unless it was preloaded in the first Scene. This is now fixed in the master branch. The second is getting access to the native touch event for iOS permissions. As this is more of an edge-case (now that audio unlocking responds properly) I'm happy for devs to add their own touch handlers specifically for this.
