### ISSUE TITLE
EventListener does not receive/have access to Listener Type

### ISSUE THREAD

**Issue by pagesrichie** [photonstorm/phaser#3322]
I wired up an eventListener on a sprite object, and sent an emit with some test data.
```
test = this.add.sprite(400, y);
test.addListener('TestListener', testListenerFunc, this);
test.addListener('TestListener2', testListenerFunc, this);

test.emit("TestListener", {data: "testData"})

function testListenerFunc(dataObj, secondArgReturnsUndefined) {
    console.log(dataObj,  secondArgReturnsUndefined) //{data: "testData"}, undefined
    console.log("testListener invoked!")
    
    //  Inside function there is no way to access which listener was called.
    //  Was it 'TestListener' or 'TestListener2'?  We can't know..
}
```

It works, however, in the example above, in case we want to wire up multiple Listener Event Types (such as 'TestListener', and 'TestListener') to use the same function ('testListener'), there is no way to differentiate between which event was sent.  Inside the function, the data gets sent, however there is no way to access which event type was sent.

The only workaround I saw was sending in the event type via the emitter function, but that seems **_hacky/duplicating/bad form_**:

```
test.emit("TestListener", {data: "testData", eventType: 'TestListener'})
test.emit("TestListener2", {data: "testData", eventType: 'TestListener2'})
```

That doesn't seem to be the best strategy.  Is there a way to capture the event type within the listener function?  If not, then it would seem a good idea to add this functionality.

**Comment by pixelpicosean** [comment]
The `emit` method is inherited from `EventEmitter` which is a third party lib, so it's not easy to add that functionality. But the `emit` method support multiple parameters, you can simply do this `test.emit("TestListener", "TestListener", { data: "testData" })`.

**Comment by photonstorm** [comment]
This isn't a feature of the [EventEmitter3](https://github.com/primus/eventemitter3) lib we use, so we can't offer it I'm afraid. As EE3 is meant to be a drop-in replacement for the node EE I'm guessing it's not a feature present there either.
