### ISSUE TITLE
Phaser.Math.RND.sign property and method collision

### ISSUE THREAD

**Issue by vinerz** [photonstorm/phaser#3323]
**Issue type:** A bug in the API
**Phaser version:** 3.2.0

Hey guys! I can not express words for how awesome this project is.
I am deeply diving into Phaser 3 for a mid-complex project and it is amazing so far.

I got into trouble trying to use the `Phaser.Math.RND.sign`, as it also declares `sign` as its own property inside the constructor and overrides the method.

My suggestion would be to change the property to _sign and keep the method as is.

Thanks again! 😆

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
