### ISSUE TITLE
GitHub release too big for jsDelivr

### ISSUE THREAD

**Issue by sandysandysandy123** [photonstorm/phaser#3324]
I'm trying to load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/gh/photonstorm/phaser) but it fails because the package is over 50 MB. Are there any files that could be removed to reduce the package size?

**Comment by samme** [comment]
<https://www.jsdelivr.com/package/npm/phaser> should work.

<https://cdn.jsdelivr.net/npm/phaser@3.1.2/dist/phaser.js>

**Comment by photonstorm** [comment]
The CDN is for including the build files in your games, rather than the entire repo. Even so, the entire Phaser repo is only 19MB.
