### ISSUE TITLE
Bug: zoom and resolution issue on mobile screen

### ISSUE THREAD

**Issue by yewmint** [photonstorm/phaser#3328]
I'm using phaser 3 with cordova to create mobile game and trying to solve blurring render on high dpi mobile screen with GameConfig. My config looks like:

```` javascript
  let config = {
    type: Phaser.AUTO,
    parent: 'app',
    width: window.screen.width,
    height: window.screen.height,
    zoom: 1,
    resolution: window.devicePixelRatio,
    scene: [LogoScene, GameScene, ScoreScene]
  }
````

I found that `zoom: 1, resolution: window.devicePixelRatio` will zoom in and render only left-top part of my scene. But `zoom: 0.99999999, resolution: window.devicePixelRatio` will render whole scene in high resolution.

Though 0.99999999 of zoom solved my problem, it looks more like a hack not a best practice. Is this weird behavior a bug?

phaser 3.1.2
cordova-android 7.0.0

**Comment by kirillbunin** [comment]
Unfortunately for me, not even the hack resolves the issue. Everything stays blurred on higher DPI (I'm loading SVG assets, but even text is blurred) and the backgroundColor square gets smaller, while the rest of the background is black.

**Comment by yewmint** [comment]
@kirillbunin My text stays blurred as well.

**Comment by samme** [comment]
I think you have to scale the canvas yourself, as `resolution` doesn't do that: <https://codepen.io/samme/pen/wyVKBG>

**Comment by yewmint** [comment]
@samme Thanks for your example, which shows a more proper solution of resolving blurred canvas. I guess that `zoom` only works when it's not equal to 1.

**Comment by kirillbunin** [comment]
I would still leave this open, atleast as a feature. Matter.js for example, has `pixelRatio` option in config, which resolves this, without the canvas needed to be resized manually. And in example provided by **samme** the text is still blurred for me.

**Comment by samme** [comment]
Text objects also have a `resolution` property you can set. It's initially set to 1, not `game.config.resolution`.

**Comment by samme** [comment]
Aha, you should set `autoResize: true` as well: <https://codepen.io/samme/pen/wyVKBG>.
