### ISSUE TITLE
Load HTML Texture doesn't work

### ISSUE THREAD

**Issue by alexandernst** [photonstorm/phaser#3334]
This one I'm not really sure if it doesn't work or it's just me not understanding what the output should look like...
http://labs.phaser.io/view.html?src=src\loader\load%20html%20to%20texture.js

I'd expect to see the HTML in `assets/html/test1.html` to get rendered (as an image?).
Instead, all I see it an empty black box with green borders.

**Comment by iamchristopher** [comment]
What browser/ OS are you testing on? Works for me (Chrome, macOS).

**Comment by alexandernst** [comment]
Also, I'm trying to test this demo in plnkr ( http://plnkr.co/edit/KunEdb45Cpv5692IotDX?p=preview ) in Chrome, but I'm getting 

```
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.
    at initialize.createTexture2D (http://cdn.jsdelivr.net/npm/phaser@3.1.2/dist/phaser.min.js:1:457924)
    at initialize.createTextureFromSource (http://cdn.jsdelivr.net/npm/phaser@3.1.2/dist/phaser.min.js:1:457365)
    at initialize.init (http://cdn.jsdelivr.net/npm/phaser@3.1.2/dist/phaser.min.js:1:291826)
    at new initialize (http://cdn.jsdelivr.net/npm/phaser@3.1.2/dist/phaser.min.js:1:291742)
    at new initialize (http://cdn.jsdelivr.net/npm/phaser@3.1.2/dist/phaser.min.js:1:289688)
    at initialize.create (http://cdn.jsdelivr.net/npm/phaser@3.1.2/dist/phaser.min.js:1:288095)
    at initialize.addImage (http://cdn.jsdelivr.net/npm/phaser@3.1.2/dist/phaser.min.js:1:286464)
    at http://cdn.jsdelivr.net/npm/phaser@3.1.2/dist/phaser.min.js:1:581926
    at initialize.each (http://cdn.jsdelivr.net/npm/phaser@3.1.2/dist/phaser.min.js:1:48649)
    at initialize.processCallback (http://cdn.jsdelivr.net/npm/phaser@3.1.2/dist/phaser.min.js:1:581823)
```

**Comment by photonstorm** [comment]
Safari really is garbage :) Demo works fine here, so again it's blocking for some unknown reason. The error above is a CORs error - it's basically saying "won't render this because I don't trust where it came from". If you force it to use CANVAS (instead of AUTO / WEBGL) it'll probably get past it with just a warning. Otherwise, make sure all the assets and source are coming from the same domain, or it's not going to be happy.

**Comment by alexandernst** [comment]
I agree, nevertheless, Phaser is a *web* game library, I'd expect it to work on all major browsers. Doing web games which will actually work only in Chrome defeats the purpose of the entire idea of *web*.

Please let me know if I can help you debug further the problem.

**Comment by photonstorm** [comment]
That's not what I meant, it's a Safari limitation. There's nothing you can do about it other than satisfy its CORs restrictions. Then at least it may stand a chance of working.

**Comment by alexandernst** [comment]
I was talking about the audio issue. The CORS issue I understood perfectly ;)

**Comment by alexandernst** [comment]
Just to keep this updated. I changed `AUTO` to `CANVAS` and now the code is working on Chrome, but it still doesn't work in Safari.

http://plnkr.co/edit/6pvftCUBZa6h2WCf2buv?p=preview

**Comment by photonstorm** [comment]
Thank you for opening this issue, however I'm going to close it off now as there has been no progress made on this issue in quite some time, and sadly no contributions from anyone else to help fix it. I'm sorry we couldn't resolve it in this case.

**Comment by eduraices** [comment]
Hi. That was my solution. Thanks to photonstorm:

> Safari really is garbage :) Demo works fine here, so again it's blocking for some unknown reason. The error above is a CORs error - it's basically saying "won't render this because I don't trust where it came from". If you force it to use CANVAS (instead of AUTO / WEBGL) it'll probably get past it with just a warning. Otherwise, make sure all the assets and source are coming from the same domain, or it's not going to be happy.

Changing AUTO to CANVAS, it will work, now i would like to learn what was changed on my conf. Greetings
