### ISSUE TITLE
Incorrect color in render texture object

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3336]
* A bug in the API (v3.2.0)

[Here](https://codepen.io/rexrainbow/pen/jZjYeg?editors=0010) is a test code for this issue. Tested on chrome and firefox.
Steps:

1. draw something in Graphics object with white color (0xffffff)
2. create drawing result in texture 'draw'
3. create a Sprite with 'draw' texture without putting on display list, clean graphics object
4. create a Render Texture object, paste that 'draw' texture from sprite

Color in Graphics and Sprite objects are white, but color in Render Texture object is *red*.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
