### ISSUE TITLE
Texture scaling differs between WebGL and canvas TileSpriteRenderer

### ISSUE THREAD

**Issue by TCatshoek** [photonstorm/phaser#3338]
* A bug in the API (v3.2.0)

I noticed a difference between the scale textures are drawn between the webgl and canvas tilesprite renderers.

[Example here](https://jsfiddle.net/5ozxfh1v/16/)

This should draw the given image with both renderers, and I would expect them to draw the exact same thing here, but they draw the texture at different scales.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by TCatshoek** [comment]
[Jsfiddle](https://jsfiddle.net/5ozxfh1v/19/) using a fresh build of the master branch. Seems like it's working perfectly now!
