### ISSUE TITLE
Some features of Graphics object

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3340]
* Request some features of Graphics object

1. [gradient fill style](https://www.w3schools.com/tags/canvas_createlineargradient.asp)
2. Add parameter x, y  in `Graphics.generateTexture()` function: this function seems creating a texture from a rectangle, size = width* height, at (0,0). Is it possible to assign the (top-ledt) position of this rectangle?
3. Add a Boolean parameter 'overwrite' in `Graphics.generateTexture()` to overwrite (clean then write) existed texture instead 'draw to it'.

**Comment by rexrainbow** [comment]
I found a workaround to clean existed texture, for issue 3
```
var texture = this.textures.get(key);
var src = texture.getSourceImage();
var ctx = src.getContext('2d');
ctx.clearRect(0, 0, src.width, src.height)
```
get the canvas element of that texture then clean it.

**Comment by rexrainbow** [comment]
Another feature request:
Canvas of a texture could be got by 
```
var texture = this.textures.get(key);
var src = texture.getSourceImage();
var ctx = src.getContext('2d');
```
to allow user to draw on it. But `texture.source[0].glTexture` would be updated. It might be useful to add a function to update glTexture from canvas. 
[Reference](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/graphics/Graphics.js#L1101)- restore glTexture from canvas.

**Comment by photonstorm** [comment]
There are no plans to add any gradient support to Graphics. It's trivial under Canvas, but absolutely not trivial to do in WebGL.

x/y properties to `generateTexture` are a nice idea and relatively easy to implement, although it bugs me we'd have to change the method signature to put them first. They could come after the w/h definition but that feels a bit backwards.

**Comment by rexrainbow** [comment]
Thank you for explaining clearly.
