### ISSUE TITLE
parnet - child relationship in phaser 3 

### ISSUE THREAD

**Issue by bogdaniudean** [photonstorm/phaser#3343]
What I am trying to achive is to link the head to the body so when i move the sprite of the body the sprite of the head will follow the movement. I am new to Phaser but as far as I've seen in v2 this could be done by using the .addChild(). In Phaser 3 the game seems to freeze if I call this. Any clue?
```
var body = this.physics.add.sprite(135, 236, 'body');
var head = this.physics.add.sprite(135, 120, 'head');

// body.addChild(head);
```

**Comment by 16patsle** [comment]
The display list is flat in v3, so no parent/child relationships are possible. Containers are going to offer a solution to this when they come out. Work on that should start in a couple of weeks according to the newsletter

**Comment by Jackafeller** [comment]
Show username

**Comment by 16patsle** [comment]
?

**Comment by photonstorm** [comment]
There is no `addChild` method available in v3. Containers / Transform Nodes are in development. Please see the newsletter for details in the coming weeks.
