### ISSUE TITLE
[Question] how to add mask to a group?

### ISSUE THREAD

**Issue by koalaylj** [photonstorm/phaser#3347]
* A problem with my own code
In PhaserCE  I Can add mask to group like this.
```javascript
var mask = game.add.graphics(x,y);
mask.beginFill(0x000000);
mask.drawRect(0, 0, width, height);
if (group.mask !== null) {
    group.mask.destroy();
}
group.mask = mask;
```
but group in phaser3 does not have mask property, how to add a mask for a group?

**Comment by pixelpicosean** [comment]
Group is no longer a node in Phaser 3, it now performs just like a list (think a more powerful Array), and so come with no visual properties like `mask`.

**Comment by photonstorm** [comment]
Correct, there are no plans to add anything visual to Groups (such as masks) as they are non-exclusive collections of Game Objects. We will discuss it for Containers.
