### ISSUE TITLE
game.scene.start

### ISSUE THREAD

**Issue by bogdaniudean** [photonstorm/phaser#3359]
I have the following configuration:
`
let config = {
        type: Phaser.AUTO,
        width: 800,
        height: 600,
        pixelArt: true,
        physics: {
            default: 'arcade',
            arcade: {
                gravity: { y: 400 },
                debug: true
            }
        },
        scene : [ Match, Main]
    };

    let game = new Phaser.Game(config);
`

`
    class Main extends Phaser.Scene
    {

        constructor()
        {
            super({ key: 'main' });
        }
      }
`

`
    class Match extends Phaser.Scene
    {

        constructor()
        {
            super({ key: 'match' });
        }
     }
`

Inside of main I check if the space button was pressed, if it was I than want to pass to the Match scene by using: game.scene.start('match', true, true); 
Hovever, when I'm in the Match scene and I press space again the collider bodies from the Match scene keep duplicating ( i see their shape with debug)  ( when I start the scene I already have 1 duplicate of each).
I have tried changing the start to false - false and all the other possible combination but no success.
How can I switch the scene and delete everithing from the previous one? And when I start I don't want to have no duplicate colliders. If I run the match scene without the Main there are no problems of duplicates.

**Comment by photonstorm** [comment]
Don't use `game.scene` - always go via the Scene itself: `this.scene.start()` so it uses the ScenePlugin correctly.
