### ISSUE TITLE
[request] Timeline#seek

### ISSUE THREAD

**Issue by allanbreyes** [photonstorm/phaser#3362]
This issue is *feature request* for a `#seek` method on the `Phaser.Tweens.Timeline` Public API.

**Motivation**
Fine-grained control over a sequence of tweens, e.g. [`Tween#seek`](https://github.com/photonstorm/phaser/blob/master/src/tweens/tween/Tween.js#L739-L805) but for a collection of tweens.

**Expected Behavior**
- Determinism
- Tweens that are completed at the chosen point in the timeline stay completed
- Tweens that are yet-to-be played at the chosen point in the timeline are reset, queued, and ready to kick-off in the future
- Tweens that are active (currently playing) during the chosen point in the timeline seek to their respective point in time

**Example API** (adapted from http://labs.phaser.io/edit.html?src=src\tweens\seek.js)

```javascript
var config = {
    type: Phaser.CANVAS,
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var timeline;
var progressBar;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('block', 'assets/sprites/block.png');
}

function create ()
{
    var marker = this.add.image(100, 250, 'block').setAlpha(0.3);
    var image = this.add.image(100, 250, 'block');
    timeline = this.tweens.createTimeline();

    timeline.add({
        targets: image,
        props: {
            x: { value: 700, duration: 4000, ease: 'Power2' },
            y: { value: 500, duration: 1500, ease: 'Bounce.easeOut' }
        }
    });

    timeline.add({
        targets: image,
        props: {
            x: { value: 100, duration: 4000, ease: 'Power2' },
            y: { value: 250, duration: 1500, ease: 'Bounce.easeOut' }
        }
    });

    progressBar = document.createElement('input');
    progressBar.type = 'range';
    progressBar.min = '0';
    progressBar.max = '100';
    progressBar.step = '.001';
    progressBar.value = '50';
    document.body.appendChild(progressBar);

    progressBar.addEventListener('input', function (e) {
        timeline.pause();
        timeline.seek(e.target.value / 100); // <-- suggested method
    });

    timeline.play();
}

function update ()
{
    if (timeline.isPlaying())
    {
        progressBar.value = Math.floor(timeline.progress * 100);
    }
}
```

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
