### ISSUE TITLE
Phaser 3 labs example not working: Registry Data Exchange

### ISSUE THREAD

**Issue by rdamborsky** [photonstorm/phaser#3367]
This Issue is about
* An error in the documentation

https://labs.phaser.io/edit.html?src=src\scenes\registry%20data%20exchange.js

This example doesn't work due to missing `registry.after` method, that was removed from DataManager here: [Recoded the Data component](https://github.com/photonstorm/phaser/commit/4ec30b8db8d3a881b4c948f00f1d954d221d0acc#diff-46017b722aedf03241a85305ea88b60dL117)

Is there going to be an alternative method to get notified of registry changes? Should `Phaser.EventEmitter` be used for shared data?

**Comment by photonstorm** [comment]
This example has been fixed. You can use `registry.events.on('changedata')` to emulate 'after'.

**Comment by rdamborsky** [comment]
Great, thank you!
