### ISSUE TITLE
renderer.onContextRestored in HEADLESS

### ISSUE THREAD

**Issue by 16patsle** [photonstorm/phaser#3368]
This Issue is about

* A bug in the API (v3.2.0)

v3.2.0 introduced the HEADLESS rendering mode. There is currently an issue when using this in combination with a static tilemap layer, because the tilemap layer tries to access the renderer, which is null. The issue is caused by the following line, which I believe may not be necessary in headless:
```js
this.renderer.onContextRestored(this.contextRestore, this);
```
https://github.com/photonstorm/phaser/blob/v3.2.0/src/tilemaps/staticlayer/StaticTilemapLayer.js#L197

The same issue seems to exist in other game object classes as well, for instance Text. A quick search found that BitmapMask and TileSprite contains the same line, so those are likely to be affected as well. DynamicTilemapLayer is not affected.

The issue appears if you change the following example to use the headless mode:
http://labs.phaser.io/edit.html?src=src\game%20objects\tilemap\collision\csv%20map%20arcade%20physics.js

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
