### ISSUE TITLE
Matter.js render fillStyle option doesn't work

### ISSUE THREAD

**Issue by kirillbunin** [photonstorm/phaser#3369]
Default Matter.js accepts `render: { fillStyle: '#bada55' }` as a prop when creating objects. I even think that I tried it in earlier version and it worked.

If you remove `debug: true` you wont see the square.
https://codepen.io/anon/pen/yKNPaB

**Comment by photonstorm** [comment]
If there is no debug layer then Matter itself won't render or display anything as we do not bundle any of the Matter renderer files in our build. The default Matter.Body object doesn't have a `render.fillStyle` property.

I suspect the Matter renderer injects that into the render object as part of the body config, but it's not a default property, so our debug sweep in `World.postUpdate` doesn't check for it either. I guess it could do so at the cost of adding another conditional in the middle of the render loop. Then again it's just for debugging so maybe the cost isn't too bad and the benefit of setting a per-body line style would be more useful than the expense of it.

**Comment by kirillbunin** [comment]
So would would be desired way to create Matter.js bodies which would render so the user may see them?
I want to create a plain-black rope from several rectangles and I don't think creating them from sprites is most effective way.
