### ISSUE TITLE
Phaser.Display.Color.Interpolate.RGBWithRGB returns NaN color values.

### ISSUE THREAD

**Issue by samid737** [photonstorm/phaser#3372]
This Issue is about:

* A bug in the API (v.3.2.0)

Demo:

http://jsfiddle.net/66ad67x3/8/

The intended function call at [L41](https://github.com/photonstorm/phaser/blob/935a89342da540cc9bdf502e8ded56ce16b4557d/src/display/color/Interpolate.js#L41) seems to be [Phaser.Math.Linear](https://github.com/photonstorm/phaser/blob/935a89342da540cc9bdf502e8ded56ce16b4557d/src/math/Linear.js#L19), but instead
[Phaser.Math.Interpolation.LinearInterpolation](https://github.com/photonstorm/phaser/blob/935a89342da540cc9bdf502e8ded56ce16b4557d/src/display/color/Interpolate.js#L7) is being loaded (and actually called).

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
