### ISSUE TITLE
Bug: Text.setStyle() won't return text object back

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3373]
* A bug in the API (v3.2.0)

[Text.setStyle()](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/static/Text.js#L538) will [return the 'style' object](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/TextStyle.js#L345) back, therefore Text.setStyle could not be used in chain ( Text.setStyle(...).setText(...) )

Other text methods like [Text.setFont](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/static/Text.js#L553) will return text object back.

**Comment by photonstorm** [comment]
This seems to work fine for chaining things:

```
this.add.text(100, 200, 'Phaser').setStyle({ fontFamily: 'Arial', fontSize: 64, color: '#00ff00' }).setFill('#ff0000');
```

It only returns the TextStyle object back if you call `style.setStyle` directly and explicitly tell it to not update the text parent object (the 2nd argument, which is true by default)

**Comment by rexrainbow** [comment]
Thank you!
