### ISSUE TITLE
Rendertexture.draw() only draws the initial frame of A sprite.

### ISSUE THREAD

**Issue by samid737** [photonstorm/phaser#3374]
This Issue is about

* A bug in the API (v.3.2.0)

The rendertexture only draws the initial frame set to A sprite when using rt.draw(sprite.texture, sprite.frame) and does not seem to draw any other frames. An example:

WEBGL:
http://jsfiddle.net/s7jazo1g/6/

CANVAS:
http://jsfiddle.net/s7jazo1g/4/

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
