### ISSUE TITLE
Support loading assets from disk in Electron

### ISSUE THREAD

**Issue by nickaversano** [photonstorm/phaser#3382]
Hi, I'm running my game in Electron and am having trouble loading any asset with a `file://` url. I'm trying to load an asset selected by the user. For example in the `preload` method I'm calling:

```javascript
this.load.image('test', 'file:///some/file/on/my-computer.png')
```

This was working until `phaser@3.0.0-beta.16`. Now, I don't get any errors from the loader and no network requests are sent. When I try creating a GameObject with the `test` sprite, it is completely transparent.

Please advise how to work around this.

Thanks so much!

**Comment by photonstorm** [comment]
Why did you close this? Did you manage to resolve it?

**Comment by nickaversano** [comment]
no, didn't manage to resolve but wasn't able to reproduce starting from https://github.com/electron/electron-quick-start and adding phaser then rendering a game. even worked in an iframe, so it must be something very specific to my setup that is broken

**Comment by bradharms** [comment]
I was having issues with Electron dealing with file paths as well, which I talked about [here](http://www.html5gamedevs.com/topic/35077-use-with-electron/?tab=comments#comment-202516).

Additionally, the issues I was having with `file:///` not working actually resolved themselves when I switched from `electron-webpack` to `electron-prebuilt`. So, I suspect this may be more of an issue with Electron.

**Comment by nickaversano** [comment]
OK, I actually figured out my specific issue: on `preload` I was calling `game.scene.stop(key)` for all `game.scene.keys` which turned out to also include the scene that was trying to preload things. This seems like the expected behavior in this case, though it would be nice to get some sort of warning like: Stopping a scene before preload has finished!

**Comment by photonstorm** [comment]
Well, that's an edge case and then some! Will have a think about implications of stopping a scene during preload.
