### ISSUE TITLE
Sounds destroying not working?

### ISSUE THREAD

**Issue by DouglasLapsley** [photonstorm/phaser#3383]
Phaser version: 3.2.1

I think there may be a bug in Phaser.Sound when destroying sounds.  

I am using Angular 4 and creating an interface which has a number of games.  They load in a modal (i.e. no page refresh/change) and I then destroy them with this.phaserGame.destroy(true);

I have background audio that I am playing with the following:

```
preload () : void
{
  this.load.audio('bg', [
    this.p('audio/bg.mp3'),
    this.p('audio/bg.ogg')
  ]);
}
```
this.p() just gets the relative path.

```
create () : void
{
  this.sound_bg = this.sound.add('bg', { loop: true });
}
```
When I destroy and reload the game, the background audio object seems to still be in the DOM and plays over itself on second game launch.

I've had a look through the documentation and tried removeByKey() remove() and destroy() in the BaseSoundManager() namespace just before destroying the game.

None of these seem to solve the problem though.

Is this a bug?  I didn't get any responses to this in the forum, so I'm thinking maybe people haven't seen this before?

Thanks!

**Comment by DouglasLapsley** [comment]
The same seems to happen for Keyboard Input events.  If I set up a keyboard input like this:
```
this.LEFTKey = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.LEFT);
```
...and then destroy the game.  And then launch the game again.  The left key no longer works in the game.

As above for sounds, if I try to remove the keyboard input before destroying the game, it doesn't seem to do anything.

```
this.input.keyboard.removeKey(Phaser.Input.Keyboard.KeyCodes.LEFT);
```
Thanks!

**Comment by TravisGit** [comment]
text/html;charset=utf-8;base64,PCFET0NUWVBFIEhUTUw%2BDQo8aHRtbCBs
YW5nPSJlbiI%2BDQogPGhlYWQ%2BDQogIDx0aXRsZT5QcmV0dHkgR2xvd2luZyBMaW5lczwvd
Gl0bGU%2BDQogPC9oZWFkPg0KIDxib2R5Pg0KPGNhbnZhcyB3aWR0aD0iODAwIiBoZWlnaHQ
9IjQ1MCI%2BPC9jY..."</a>

**Comment by tstauch** [comment]
I think my issue is related to this...
I am loading multiple  audio files, using a content management system, so there are occasions when the instruction to load the audio is added to the game, but the actual audio file is missing (if the user did not upload a file).

When I try to destroy this game using

> this.sys.game.destroy(true);	


I get this error:

> appjs.js:2 Uncaught TypeError: Cannot read property 'destroy' of undefined
>     at initialize.h.emit (appjs.js:2)
>     at initialize.destroy (appjs.js:2)
>     at initialize.destroy (appjs.js:2)
>     at initialize.<anonymous> (appjs.js:2)
>     at appjs.js:2
>     at Array.forEach (<anonymous>)
>     at initialize.forEachActiveSound (appjs.js:2)
>     at initialize.destroy (appjs.js:2)
>     at initialize.destroy (appjs.js:2)
>     at h.emit (appjs.js:2)

So it seems that the method "forEachActiveSound" needs to make sure that the audio is valid before trying to destroy it.

I've done a workaround but I hope that helps.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
