### ISSUE TITLE
Rendertexture alpha not changing in WEBGL mode.

### ISSUE THREAD

**Issue by samid737** [photonstorm/phaser#3385]
This Issue is about

* A bug in the API (v3.2.1)

The (global? not sure) alpha of the rendertexture does not change in WEBGL mode. It does work in CANVAS.

CANVAS:
http://jsfiddle.net/e2e6w77r/14/

WEBGL:
http://jsfiddle.net/e2e6w77r/17/

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
