### ISSUE TITLE
WebGL context is created with antialias: undefined

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#3386]
This looks like a mistake since there is no `antialias` property in `game.config`.

https://github.com/photonstorm/phaser/blob/22901a1b05abf5c37ff1e6fd0c4c7974d90d6017/src/renderer/webgl/WebGLRenderer.js#L42

* A bug in the API: 3.2.1

**Comment by photonstorm** [comment]
This isn't actually used internally anyway, so it safe to remove from the webgl context config.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
