### ISSUE TITLE
Result of Text.getWrappedText() is different from Text.updateText()

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3389]
* A bug in the API (v3.2.1)

I tried to get wrapped lines in text object. And found that:

Result (**Text.runWordWrap(text)**) of [Text.getWrappedText(text)](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/static/Text.js#L489) is different from[Text.updateText()](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/static/Text.js#L926)

It might because that [the font is not sync to canvas](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/static/Text.js#L920) in Text.getWrappedText()
In my testing, font size is
- Text.getWrappedText: "12px sans-serif"
- Text.updateText: "16px Courier"

Should I call `style.syncFont(canvas, context)` in my code?

**Comment by rexrainbow** [comment]
Here is another problem of Text.getWrappedText() -- [sample code](https://codepen.io/rexrainbow/pen/xWZeNW?editors=0010)

I try to display text page by page.
So I get wrapped text, display them in text object, and expect the line number should be equal to set text directly.

In this sample code, string in line 3 
```
community-lead continuation of the Phaser 2 codebase 
``` 
will be wrapped to 2 lines
```
community-lead continuation of the Phaser 2 
codebase 
```

It seems that extra "\n" will affect the wrapping result.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
