### ISSUE TITLE
game.resize only working properly when canvas becomes smaller

### ISSUE THREAD

**Issue by sftsk** [photonstorm/phaser#3391]
* A bug in the API 3.2.1 (always say which version you're using!)

When having a canvas with `window.innerWidth` and `window.innerHeight` and using `game.resize` the view only resizes properly if the new size is smaller then the original game size.
If it becomes larger the newly available space stays black but you can see the sprites (coordinates) are extending behind it.

Tested in Safari and Chrome on macOS.

![resize-demo](https://user-images.githubusercontent.com/646910/37424972-814269ba-27ca-11e8-9deb-208254936799.gif)

**Comment by pixelpicosean** [comment]
You need to resize the main camera to show more content

**Comment by sftsk** [comment]
Cheers @pixelpicosean for pointing me to a solution!

I am now running the following code:
```
game.scene.scenes.forEach( function (scene) {
  scene.cameras.main.setViewport( 0, 0, window.innerWidth, window.innerHeight );
});
```
after `game.resize(window.innerWidth, window.innerHeight)`.

Still thinking this should probably happen automatically when doing the `game.resize()` but it works for now!

**Comment by photonstorm** [comment]
It will be part of the new Scale Manager (to do it automatically) but it isn't always desirable, which is why it doesn't happen atm.
