### ISSUE TITLE
Typo: duplicate lines

### ISSUE THREAD

**Issue by 12casper3** [photonstorm/phaser#3395]
This Issue is about (delete as applicable)

* A typo/ possible bug

One of the `faceBottom`s should probably be an `faceTop`.

https://github.com/photonstorm/phaser/blob/1d23aad9767863dbd823147a2cbdc3f9ad25642f/src/tilemaps/components/CalculateFacesAt.js#L30-L37

**Comment by mikewesthad** [comment]
@12casper3 Thanks - fixed!
