### ISSUE TITLE
Possible bug: StaticTilemap shrink tiles vs DynamicTilemap

### ISSUE THREAD

**Issue by joey-squla** [photonstorm/phaser#3396]
I use the same way of loading a spritesheet for both Dynamic and StaticTilemap. The result is different however. See the forumpost below for more details:

If this is expected behaviour, you can ignore this issue.

http://www.html5gamedevs.com/topic/36314-statictilemap-shrinks-tiles/

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
