### ISSUE TITLE
Bug: dragging something in one scene seems to disable input in another scene

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3399]
I have reproduced the issue in [this fiddle](https://jsfiddle.net/zkyrobf2/9/), which is based on the code for the parallel scenes example, using Phaser 3.2.1.

The situation: there are two scenes, UI scene and Game scene. UI scene contains one draggable image, Game scene contains two clickable images. UI scene is on top of Game scene. When you click the images in Game scene, they properly react to the event and their tints change. The image in UI scene can be dragged around, and that too works. But **after you have dragged that image once, Game scene (so the _other_ scene) stops responding to input**, as seen from the fact that clicking on images of Game scene doesn't change their tints anymore.

This problem only arises when something is dragged, other events do not seem to affect input in other scenes. No errors show up in the console.

**Comment by Jerenaux** [comment]
Toneal on Slack has looked into it a bit, and here is what he found:

> In phaser/src/input/InputPlugin.js, `manager.ignoreEvents` is flagged to true - which is what initially stops the input on the bottom layer... *but* it's never toggled off.
> 
> So basically, drag events aren't accounted for.  Only single tap events.

**Comment by photonstorm** [comment]
`ignoreEvents` is toggled off at the start of the InputManager.update. The error was the total calculation in the update loop. This is now fixed and pushed to master. Thank you :)
