### ISSUE TITLE
Tint not working

### ISSUE THREAD

**Issue by DouglasLapsley** [photonstorm/phaser#3400]
Phaser 3.2.1.

I think setTint may not be working.  This seems to be the case for all GameObject types.

```
    this.clouds1 = this.add.tileSprite(100, 100, 1024, 140, 'sprites', 'cloudsBack');
    this.clouds1.setTint(0xff00ff);
```
This does nothing.  I've tried with passing 4 parameters too.

Thanks!

**Comment by vinerz** [comment]
Hi @DouglasLapsley and people trying to find a solution, I've found the same behaviour using tint with `Phaser.CANVAS`.
It doesn't appear to affect WEBGL mode.

**Comment by photonstorm** [comment]
Looks good to me: http://labs.phaser.io/view.html?src=src\display\tint\tile%20sprite%20tint.js

Note this is a WebGL only feature. We do flag it as such in the jsdocs, but I appreciate they're not live yet so wouldn't have been seen.

**Comment by DouglasLapsley** [comment]
Thank you. I was using canvas so that will be it.
