### ISSUE TITLE
iOS Safari - Messed up tileSprite x-axis scrolling on WEBGL

### ISSUE THREAD

**Issue by vinerz** [photonstorm/phaser#3402]
* A bug in the API (Phaser v3.2.1)

Hey guys! I've found a severe issue on tileSprite scrolling using iOS Safari and WEBGL.

**Reproducible steps:**
1. Start scrolling the tileSprite x-axis using the Scene's `update()` method (the larger the increment, the faster the issue rises up);
2. After a while (2~3 minutes) you will notice a little jittering.
3. This is all downhill from here. As the time passes, it becomes weirder, shakes back and forth and the sprite even distorts itself, shown at the recording below:

![ezgif-5-7807c6e7a4](https://user-images.githubusercontent.com/1482034/37507323-aa583fc0-28cc-11e8-9d73-c230eee224e6.gif)

Relevant fiddle: https://jsfiddle.net/zkyrobf2/23/

### It doesn't affect Phaser on CANVAS mode.

Also, **this is not a global fps drop**, all other elements above it should run smoothly (including physics and tweens), affecting only the tileSprite rendering itself.

**Comment by vinerz** [comment]
After more testing, it is not reproducible by scrolling the y-axis, limiting this issue to x-axis and WEBGL only.

**Comment by FrancescoNegri** [comment]
I discovered a similar issue on Windows while using Phaser.AUTO or Phaser.WEBGL (not with Phaser.CANVAS). If I move on the x axis a sprite of a non-integer number of pixels it show vertical lines shaking like in the picture.
![bug](https://user-images.githubusercontent.com/11014462/37626815-d075aa78-2bd1-11e8-86fb-1f09e9e969cc.PNG)

There are 6 lines in the upper part and 3 in the beige part

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
