### ISSUE TITLE
Can't call super on Phaser.Physics.Matter.Image

### ISSUE THREAD

**Issue by alexandernst** [photonstorm/phaser#3404]
It's not possible to call `super` on `Phaser.Physics.Matter.Image`. 

Debug:

![localhost_8080](https://user-images.githubusercontent.com/89727/37513523-9be607b8-2905-11e8-9c1f-ae1d07764463.png)

![localhost_8080](https://user-images.githubusercontent.com/89727/37513572-bd980d34-2905-11e8-96fe-b7ddb1b309f4.png)

![localhost_8080](https://user-images.githubusercontent.com/89727/37513675-02d1fa18-2906-11e8-904b-373c838b120e.png)

**Comment by photonstorm** [comment]
In the first screenshot, you call `Matter.Image` and pass the `scene` as the first argument. It should be the Matter World instance, not the Scene:

```
MatterImage (world, x, y, texture, frame, options)
```

Have a look at the `Factory.js` in the matter-js folder for an example.

**Comment by alexandernst** [comment]
@photonstorm The problem is not the `Matter.Image.call` (but thanks for pointing that out, I'll fix it). The problem occurs when I call `super(scene)`.
