### ISSUE TITLE
Tween#restart takes no effect after its completion

### ISSUE THREAD

**Issue by vinerz** [photonstorm/phaser#3408]
* A bug in the API (Phaser 3.3.0)

Using the `Tween#restart` works well if the tween is still running, but it is not possible to start it again after the tween completes its lifecycle.

The example itself is capable to reproduce this issue: http://labs.phaser.io/edit.html?src=src\tweens\restart.js

**Comment by vinerz** [comment]
This regression appears to be a recent change (last two days maybe?).
I just noticed that all my other Tweens are also affected.

**Comment by vinerz** [comment]
I've made some tests with previous commits and found that the issue was caused by this recent commit: https://github.com/photonstorm/phaser/commit/4ab98eb4924ac5349194e662f57a82fa2dbeaff2

**Comment by fariazz** [comment]
I'm experiencing the same issue. Did you find a workaround to restart a tween after it completes?

**Comment by kuoruan** [comment]
```
tween.seek(0)
scene.tweens.makeActive(tween)
```
This will restart the tween.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
