### ISSUE TITLE
[Feature request] Dynamically create text with physics body

### ISSUE THREAD

**Issue by alexandernst** [photonstorm/phaser#3411]
It would be very useful to be able to dynamically create a text with physics body.
Bonus points if that could be matter.js physics.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by alexandernst** [comment]
https://github.com/photonstorm/phaser/commit/2f86100f873836a396c5f06e30f545fa973fac34

Got it! Let me play with it ;)

**Comment by photonstorm** [comment]
There are several new examples in the examples repo if you'd like to reference them.
