### ISSUE TITLE
WebPack: Relative modules were not found

### ISSUE THREAD

**Issue by ExNG** [photonstorm/phaser#3413]
This Issue is about (delete as applicable)
* A problem with my own code

It looks like WebPack cannot find the following files (which exist):
```
* ../shaders/TextureTint.frag in ./node_modules/phaser/src/renderer/webgl/pipelines/TextureTintPipeline.js
* ../shaders/ForwardDiffuse.frag in ./node_modules/phaser/src/renderer/webgl/pipelines/ForwardDiffuseLightPipeline.js
* ../shaders/FlatTint.frag in ./node_modules/phaser/src/renderer/webgl/pipelines/FlatTintPipeline.js
* ../shaders/BitmapMask.frag in ./node_modules/phaser/src/renderer/webgl/pipelines/BitmapMaskPipeline.js
```

To try it out yourself check my repo: [Kong](https://github.com/ExNG/kong)
The following file contains the pahser code: `src/pages/index.vue`

**Comment by rblopes** [comment]
Hi. I've tried your project here. I'm not familiar with all the details of Quasar framework but I think these hints will take you in the right direction.

There are a few changes you'll need to perform to make your project work.

First, replace that `phaser-glsl-loader` with `raw-loader`. It is the recommended one for use with the included Phaser shaders at the moment. You'll need to update your Quasar configuration like below (don't forget to `require('webpack')` at the top of that file).

```js
extendWebpack (cfg) {
  cfg.module.rules.push({
    enforce: 'pre',
    test: /\.(js|vue)$/,
    loader: 'eslint-loader',
    exclude: /(node_modules|quasar)/
  })

  cfg.module.rules.push({
    test: /\.(frag|vert)$/,
    loader: 'raw-loader'
  })

  cfg.plugins.push(new webpack.DefinePlugin({
    // Required by Phaser: enable WebGL and Canvas renderers.
    WEBGL_RENDERER: true,
    CANVAS_RENDERER: true
  }))
}
```

Edit you `index.vue` to move the `preload` and `create` methods inside the scene object. The script will look like this.

```js
import Phaser from 'phaser'

export default {
  data () {
    return {
      config: {
        type: Phaser.AUTO,
        width: 800,
        height: 600,
        physics: {
          default: 'arcade',
          arcade: {
            gravity: { y: 200 }
          }
        },
        scene: {
          preload () {
          },

          create () {
            //  Set this scene background color, so we know it's working.
            this.cameras.main.setBackgroundColor('#336699')
          }
        }
      },

      game: null
    }
  },

  methods: {
  },

  created () {
    this.game = new Phaser.Game(this.config)
  }
}
```

One thing I couldn't figure out is why a new game instance is added to the page every time you edit the `index.vue` component, though. I guess HMR is not working properly.

**Comment by ExNG** [comment]
Thank you merry much that relly helped me! :)
