### ISSUE TITLE
Button up/down events are not emitted on global input level

### ISSUE THREAD

**Issue by Patrik-Stas** [photonstorm/phaser#3414]
This Issue is about (delete as applicable)
* A bug in the API (always say which version you're using!)

Version:
* 3.2.1

Following works on Scene level:
```
class BasicWorld extends Phaser.Scene {

    constructor() {
        super({
            key: 'BasicWorld'
        });
    }

    preload() {
    }

    create() {
        this.input.keyboard.on('keyup_S', function (event) {
            console.log('pressed S !!!');
        });
    }
}
```
The - "pressed S" string is printed out.

However, the documentation says:
`The Input Manager consists of two parts: The Global Input Manager, which is owned by the Game itself, and the Input Manager, which is a Scene level system.`
 
Hence I assumed it would analogically work on global level, but it doesn't. Following code doesn't print anything when "R" is pressed.

```

const config: GameConfig = {
    type: Phaser.CANVAS,
    parent: 'content',
    width: 640,
    height: 480,
    resolution: 1,
    backgroundColor: '#EDEEC9',
    scene: [
        TestScene
    ]
};

const game = new Phaser.Game(config);

game.input.keyboard.on('keyup_R', function (event) {
    console.log('pressed R !!!');
}, game);
```
Is this a bug or expected behaviour?

Apart from the above, one side question:
In phaser2, the way of reacting to key up/down events was this
```
let keyLeft = game.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.LEFT);
keyLeft.onDown(function() { console.log('LEFT PRESSED'); });
```
I liked the fact that one could set up event callback using the KeyCodes enumeration - any plans for getting that into Phaser3? I think that would be nicer than "keyup_R" magic strings.

**Comment by photonstorm** [comment]
This is absolutely correct. All input should be handled via the Scene.

You can create a Key object in v3 using exactly the same call as you did in v2: `keyA = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.A);`
