### ISSUE TITLE
Loading tileset from atlas

### ISSUE THREAD

**Issue by HaoboZ** [photonstorm/phaser#3415]
This Issue is about
* A problem with my own code

I'm not too sure how to load a tileset image from an atlas. If you load an atlas, it generates a key for the whole atlas, and all the separate parts are frames. However, the API for Tilemap.addTilesetImage does not include a frame option, which makes it so it can't load from there. Is there an easy way to use it, or otherwise it will just be separately loaded?

**Comment by jestarray** [comment]
What was your solution bro?
