### ISSUE TITLE
Alpha not working on Graphics in webGL

### ISSUE THREAD

**Issue by Ziao** [photonstorm/phaser#3426]
This Issue is about
* A bug in the API (v3.2.1)

It seems that graphics objects do not support the alpha property in WebGL mode. In canvas mode, this works fine. Graphics stays at full opacity, no matter what.

```javascript
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    scene: {
        create: create
    }
};

var game = new Phaser.Game(config);

function create() {

   let circ =  this.add.graphics();
    circ.fillStyle(0xffffff);
    circ.fillCircle(200, 200, 300);
    circ.alpha = 0.5;
}
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
