### ISSUE TITLE
Phaser - Elements misplaced 

### ISSUE THREAD

**Issue by matsossah** [photonstorm/phaser#3434]
Hello,

We have a game that shows a lobby screen with phaser elements in the background and html ones in the forefront (those with no issues).  Upon loading, the elements are sometimes misplaced.  Any idea what could be happening?

Thanks in advance for your help!

NORMAL BEHAVIOUR
![image uploaded from ios 2](https://user-images.githubusercontent.com/14054277/37668847-b692ca70-2c65-11e8-99a5-c71880a316ad.png)

PROBLEM
![image uploaded from ios 1 copy](https://user-images.githubusercontent.com/14054277/37668852-b9556bd2-2c65-11e8-8aa2-ecd451787bb3.png)

**Comment by photonstorm** [comment]
I'm sorry but we can't debug screenshots. Needs code, or a URL, or an isolated test case if this is an actual issue within the API (if it's not, it needs opening on the forum)

**Comment by photonstorm** [comment]
Sorry, but I'm going to close this issue. GitHub isn't for technical support, for that we have Slack, Discord and the Forum, so please use one of those to get help with your game code. If you think you've found a bug in the API that's a different matter, and we'd welcome an issue with test case to demonstrate it.
