### ISSUE TITLE
Typo in the Contributors Guide

### ISSUE THREAD

**Issue by mzguimaraes** [photonstorm/phaser#3435]
This Issue is about (delete as applicable)

* An error in the documentation
* An error on the web site

Small issue, but this could open a further discussion.  There's a typo in page 7 of the contributors' guide:

> It only looks after truly global systems, of which there are (currently) only 3: The Request Animation Frame handler, the Texture Manager, the Scene Manager and the Device class.

Clearly, there are four global systems listed.  

I wouldn't mind cleaning up typos in this, but I don't see a way to contribute to the main website.  Is this something only PhotonStorm can edit?  If so, is there some way it can be opened for contributions?

**Comment by photonstorm** [comment]
There are actually 11 global systems, so neither is correct!

**Comment by mzguimaraes** [comment]
What is your plan for maintaining the contributor's guide and other web assets as Phaser3 changes?  I'm in the process of learning Phaser, and as I work through the material on the site I am finding small errors here and there.  None of them make the tutorials impossible to follow, but every typo represents a small barrier where Phaser can lose a potential new developer.  They ought to be fixed.

**Comment by photonstorm** [comment]
It's not possible to make the site repo public. If someone spots something and tells me, I'll fix it.

**Comment by mzguimaraes** [comment]
I'll make a list of errors I find and submit it at as another issue.  Thanks!
