### ISSUE TITLE
 window is not defined at AudioContextMonkeyPatch.js:181:3

### ISSUE THREAD

**Issue by NebSehemvi** [photonstorm/phaser#3437]
I use Phaser 3.2.1 and I have an issue. 
I also use  EJS 2.5.7 and Express 3.2.6.
When I try to set Phaser as server-side variable so I can access it in all EJS pages
`var Phaser = require("phaser");`
`app.locals.phaser = Phaser;`

I get a message in my CLI:

`/home/ubuntu/workspace/node_modules/phaser/src/polyfills/AudioContextMonkeyPatch.js:181`
`}(window));`
   ` ^`
`ReferenceError: window is not defined`
 `   at Object.<anonymous>`
`(/home/ubuntu/workspace/node_modules/phaser/src/polyfills/AudioContextMonkeyPatch.js:181:3)`

As I understand, window could not be defined for server and it stops Node from running server.
Is there a way to make it local available for all pages or Phaser is strictly client-side framework that should be included in all pages manually?

**Comment by RemiFokz** [comment]
+1

**Comment by photonstorm** [comment]
I've updated the polyfill to avoid the use of `window` in the function invocation, which will hopefully get around this. However, `window` is used extensively elsewhere in v3, so this may be a high road to nowhere. Give it a try though!

**Comment by Minious** [comment]
Hi,

Digging up some old issue here. I'm having a similar issue with window in the polyfill.

```
AudioContextMonkeyPatch.js:60 Uncaught ReferenceError: window is not defined
    at AudioContextMonkeyPatch.js:60
    at Object../node_modules/phaser/src/polyfills/AudioContextMonkeyPatch.js (AudioContextMonkeyPatch.js:181)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/phaser/src/polyfills/index.js (index.js:3)
    at __webpack_require__ (bootstrap:19)
    at Object.<anonymous> (phaser.js:7)
    at Object../node_modules/phaser/src/phaser.js (phaser.js:94)
    at __webpack_require__ (bootstrap:19)
    at Module../src/app/grid/grid.ts (grid.ts:1)
    at __webpack_require__ (bootstrap:19)
```

I'm trying to use Phaser in a Web worker where window won't be defined. Is there a workaround ?

(Using Phaser 3.23.0)

**Comment by Minious** [comment]
Btw it might just be plain stupid to try to use Phaser in a Web worker, I'm just using some Phaser Vector2 throughout the game logic and it would be a pain to replace all of that with my own Vector  implementation. That would be an alternative though, just wondering.

**Comment by halilcakar** [comment]
Well I were in this place, I would just create another version of output that only inlcudes Phaser's Vector2 and use that build instead  =)

**Comment by Minious** [comment]
Could you explain what you mean by that ? I'm not that familiar with webpack or imports. Also I'm using typescript, will that be an issue ?

**Comment by halilcakar** [comment]
Well obviously i'm not an expert about these stuff to but [this](https://phaser.io/news/2019/06/phaser-custom-build-tutorial) url might help about creating custom builds of phaser :)

**Comment by Minious** [comment]
Thank you ! I managed to get something working but I'm really not proud of how I did it. I followed your url and built a version of Phaser containing only Math. I then have a js file but still containing reference to window. I just manually commented out those lines 😥 The thing is Typescript doesn't have the types for this js file so I just have Phaser as an any type. If someone used to Typescript pass by, could you explain the right way of doing that ?

**Comment by halilcakar** [comment]
Hi again, Can you share the build you have made?

> Phaser containing only Math. I then have a js file but still containing reference to window. I just manually commented out those lines

It's probably coming from `require('./polyfills');` if you left this line from top. 

About types: I really don't know how to handle types in phaser at all. I'm using js most of the time :(

**Comment by Minious** [comment]
I did forget to remove this line.. I rebuilt Phaser without the polyfills. There is still one mention of window in the first few lines that I just replaced with undefined. It still works. Thank you :)

**Comment by Minious** [comment]
FYI

```
(function webpackUniversalModuleDefinition(root, factory) {
  if (typeof exports === "object" && typeof module === "object")
    module.exports = factory();
  else if (typeof define === "function" && define.amd)
    define("Phaser", [], factory);
  else if (typeof exports === "object") exports["Phaser"] = factory();
  else root["Phaser"] = factory();
})(window, function () {
```

**Comment by halilcakar** [comment]
I'm glad if it works out 👍
