### ISSUE TITLE
Bug with new add.gameObject() method [matterjs]

### ISSUE THREAD

**Issue by alexandernst** [photonstorm/phaser#3447]
The new feature from https://github.com/photonstorm/phaser/issues/3411 has a bug. The body doesn't get into account the origin.

If I add a text object, than I add a body to that text, and then I run `setOrigin()` and `setPosition`, the body and the text itself will be at different positions.

**Comment by photonstorm** [comment]
You should never change the origin of a game object that has a matter body, they’re calculated to match the physic bodies centre of mass. If you need to offset it from that you can do so using the xOffset and yOffset values when creating the shape.

**Comment by alexandernst** [comment]
Oh, I see. I'll keep that in mind. Thank you!
