### ISSUE TITLE
update() is not being called on GameObject.Text

### ISSUE THREAD

**Issue by alexandernst** [photonstorm/phaser#3449]
I'm subclassing `GameObject.Text` and adding a body to it with the recently added `gameObject()` method. The problem is that the `update` method of my class is not being called. Is that by design or is it a bug?

In case it's by design and there are no plans for implementing `update` in text objects, how should I refactor my code to still be able to have dynamically generated text with matterjs physics bodies?

**Comment by pixelpicosean** [comment]
Add a `preUpdate` method to the text object and then use `this.add.existing` to make sure it is added to update list. Only objects added into the update list will be updated every frame.

**Comment by alexandernst** [comment]
The `preUpdate` method wasn't being called, so I added `this.scene.add.existing(this);` to my constructor method. This made my `preUpdate` method to start getting called, but not the `update` method.

**Comment by pixelpicosean** [comment]
`preUpdate` is just what you need, why do you need another `update`? Or simply call the `update` inside the `preUpdate`.

**Comment by alexandernst** [comment]
Yes, you're right. I get `time` and `delta` from `preUpdate` too, so that should be enough. Thank you!

**Comment by photonstorm** [comment]
Text doesn't call `preUpdate` because it doesn't need to (it has nothing to update, so why waste an empty call every frame?) - however, this is tightly related to #3379 and the discussion there is relevant.
