### ISSUE TITLE
Phaser.Mouse.mouseDownCallback& mouseUpCallback not triggered in IE

### ISSUE THREAD

**Issue by kaboompixel** [photonstorm/phaser#345]
This works fine in every browser I tested, except IE10 / 11

e.g.

// mouse handlers
this.input.mouse.mouseUpCallback = this.handleMouseUp; // NOT called in IE
this.input.mouse.mouseDownCallback = this.handleMouseDown; // NOT called in IE
this.input.mouse.mouseMoveCallback = this.handleMouseMove; // Works OK

**Comment by zonex5** [comment]
still not works (((

**Comment by goowikns** [comment]
Doesn't seem to work for me neither on IE11.0.96

simply using the following

`  this.game.input.mouse.mouseDownCallback = this.mouseDown.bind(this);
  this.game.input.mouse.mouseUpCallback = this.mouseUp.bind(this);

  ...

Settle.prototype.mouseUp = function () {
  this.isDragging = false;
};

Settle.prototype.mouseDown = function () {
  this.isDragging = true;
};`

everything triggers well in Chrome and firefox but not IE11

**Comment by photonstorm** [comment]
I thought IE11 changed to be MSPointer only now? Pretty sure those mouse events don't even fire in it (which is why your callback doesn't either).

**Comment by goowikns** [comment]
Thanks seems to work with MSPointer!
