### ISSUE TITLE
Scene pause and resume example needs fixing

### ISSUE THREAD

**Issue by 16patsle** [photonstorm/phaser#3455]
This Issue is about (delete as applicable)

* An error on the web site

The scene pause and resume example uses the old MOUSE_DOWN_EVENT event, and therefore doesn't work.
http://labs.phaser.io/edit.html?src=src\scenes\pause%20and%20resume.js

This can be fixed by using the pointerdown event instead. The same goes for the scene sleep and wake example
https://labs.phaser.io/edit.html?src=src%5Cscenes%5Csleep%20and%20wake.js (as mentioned in https://github.com/photonstorm/phaser3-examples/issues/26)

**Comment by photonstorm** [comment]
These examples have been fixed.

**Comment by harriscory730** [comment]
6015516712
