### ISSUE TITLE
velocityFromRotation is missing in Matterjs

### ISSUE THREAD

**Issue by alexandernst** [photonstorm/phaser#3456]
Is there a way I can set the velocity (direction) of an object by using angle?

Said in other words: How can I set the direction at which an object should be moving at in MatterJS physics?

**Comment by photonstorm** [comment]
To move a Matter body in a specific direction you need to apply a force to the Body based on that direction vector. You can use `applyForceFrom` to do this, where the first argument is the position (as a vec2) and the second is the force itself. If you just want to apply a force based on the angle of the object then use `thrust(speed)` instead.
