### ISSUE TITLE
Resolution makes game disregard width and height in config

### ISSUE THREAD

**Issue by Legomite** [photonstorm/phaser#3468]
I have the config looking like this,
`width: 800,
        height: 600,
        resolution: window.devicePixelRatio,`

the window should be 800x600, but upon setting the resolution, it sets it to what I am assuming is my browser pixel width and height, which is 1600x1200.

**Comment by kirillbunin** [comment]
If you also set `autoResize: true` it will resize itself to 800x600

**Comment by photonstorm** [comment]
This issue is currently blocked pending development of the Scale Manager, which will begin during the month of May 2018. It will be updated once it has been tested against the new Scale Manager.

**Comment by photonstorm** [comment]
Resolution in the game config is now applied to the canvas and CSS is used to scale the canvas to the given dimensions, so you no longer need to do it yourself, or use the `autoResize option. This is now in the master branch.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
