### ISSUE TITLE
Bitmap Font letter spacing

### ISSUE THREAD

**Issue by nickaversano** [photonstorm/phaser#3472]
Hi, I was wondering if it was possible to adjust the letter spacing for Bitmap Fonts? I guess this could be applicable for all font objects too. I'm following [this example](https://github.com/photonstorm/phaser3-examples/blob/master/public/src/game%20objects/bitmaptext/dynamic/tinted%20retro%20text.js) to render a retro bitmap font and noticing that there's a 1px space between each character in a tightly-packed font sprite where all the characters are next to each other.

Any advice would be great!

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. This has been implemented and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
