### ISSUE TITLE
Bug : An animation containing varying image sizes is not anchored to a center point

### ISSUE THREAD

**Issue by jp-gc** [photonstorm/phaser#3473]
Issue:
----------
An animation that contains sequence of images with varying sizes cannot be rendered by anchoring to a center point.

Environment details:
--------------------------
Phaser version: v3.2.1  ( and also tested on v3.3.0 and this issue is there )
OS (tested): Mint Linux and Mac OS 
Browser (tested): Chrome 

Example in detail:
----------------------
Test case: https://cdn.gamecommerce.com/jp/phaser3/assets/test.html

The test case, has an animation. The animation is comprised of 9 images of varying sizes. I want to render these images at the center of the screen in order. But because of the bug, the animation does not look right ( It behaves, as if the anchor point is at the left corner, even though we specify the anchor point as the center ).

Potential fix for the bug:
------------------------------
In the method "updateFrame" of Animation.js : [src/gameobjects/components/Animation.js](https://github.com/photonstorm/phaser/blob/31bf979eb25c70441b8228d5c9643a97746ea7fa/src/gameobjects/components/Animation.js#L752), if we add the following code, then the bug is fixed:

        sprite.width = sprite.frame.width;
        sprite.height = sprite.frame.height;
        sprite.updateDisplayOrigin();

Why?
--------
During the animation, the width/height of the new frame is different from the initial frame ( or the prior frame), and we need to adjust the width/height ( and _displayOriginX / _displayOriginY ). 

( Perhaps, there is an even better solution, if so, please use that )

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by jp-gc** [comment]
Thank you very much for getting this fixed (and in such a short time). 

I verified that with the latest build ( built and tested locally ), the bug is fixed.
