### ISSUE TITLE
Error when run destroy of RenderTexture

### ISSUE THREAD

**Issue by kuoruan** [photonstorm/phaser#3475]
```
let rt = new Phaser.GameObjects.RenderTexture(scene, 0, 0, 100, 100)
rt.destroy()
```

Console output:
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at RenderTexture.destroy (VM173683 RenderTexture.js:118)
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
