### ISSUE TITLE
[Feature request][Matterjs] Make it possible to subscribe to collision events on each game object

### ISSUE THREAD

**Issue by alexandernst** [photonstorm/phaser#3483]
Make it possible to subscribe to collision events on each game object instead of having to keep the entire collision login in `this.matter.world.on('collisionstart')`.

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
