### ISSUE TITLE
DisplayList and UpdateList events

### ISSUE THREAD

**Issue by hexus** [photonstorm/phaser#3487]
This is a feature request for the `DisplayList` and `UpdateList` systems to fire events when a game object is added to or removed from either list.

Potential use cases I see for this:

- Maintaining custom lists of game objects that are part of a scene
- Augmenting game objects as they are added to the scene
- Cleaning up custom data (stored separately) as game objects are removed

I can see this being useful for plugins and user code.

If you like, I could take a crack at an implementation. I had `displayList.events` in mind, so each list just holds onto its own event emitter rather than extending the event emitter (because `DisplayList` already extends `List`).

Cheers!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
