### ISSUE TITLE
Keyboard listeners remain active after changing scene

### ISSUE THREAD

**Issue by kugyousha** [photonstorm/phaser#3489]
Getting started with the Phaser framework I was trying to transition between scenes and noticed some strange behavior. Upon investigating I found that the `this.input.keyboard.on` listeners were firing for scenes that I had already left. I was about to use `this.scene.isActive()` which returns false to stop this behavior. Or is the following not the correct way to transition between scenes, I tried `this.scene.switch('Play')` and `this.scene.stop('Start')` as well with no effect.

```
this.input.keyboard.on('keyup', ({key}) => {
      if (this.scene.isActive()) {
        if (key === '2') {
          this.scene.start('Play');
        }
      }
});
```
Shouldn't the event listeners for scenes be disabled/removed by default when they are inactive?

**Comment by photonstorm** [comment]
The Keyboard event emitter is global (shared between all Scenes), so there's no way to automatically clear out events set in a specific Scene.

The proper use-case in this scenario would be to listen for the 2 key specifically using a `once` event (i.e. `once('keyup_TWO')`), or to clear the listeners out in your Scene shutdown method.
