### ISSUE TITLE
Do you have a "DTS" file？

### ISSUE THREAD

**Issue by peony-ma** [photonstorm/phaser#3492]
Do you have a "DTS" file？

**Comment by erd0s** [comment]
One has just been published for phaser 3 in the phaser3-docs repo a few days ago https://github.com/photonstorm/phaser3-docs, have a look at the README in that repo.

**Comment by photonstorm** [comment]
It’s also linked from the readme in this repo.

It will be added to this repo once more testing has been done and feedback implemented.
