### ISSUE TITLE
Mask is killing fps, if it applied on multiple objects

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#3500]
```
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var quad = {
    topLeftX: -200, topLeftY: -200,
    topRightX: 200, topRightY: -200,
    bottomLeftX: -200, bottomLeftY: 200,
    bottomRightX: 200, bottomRightY: 200
};

var mesh;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('image', 'assets/pics/sao-sinon.png');
    this.load.image('phaser2', 'assets/sprites/phaser2.png');
}

function create ()
{
    mesh = this.make.mesh({
        key: 'phaser2',
        x: 400,
        y: 300,
        vertices: [
            quad.topLeftX, quad.topLeftY,
            quad.bottomLeftX, quad.bottomLeftY,
            quad.bottomRightX, quad.bottomRightY,

            quad.topLeftX, quad.topLeftY,
            quad.bottomRightX, quad.bottomRightY,
            quad.topRightX, quad.topRightY
        ],
        uv: [ 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0 ],
        add: false
    });
    var img
    for(var i = 0; i < 30; i++){
    img = this.make.image({x: 400, y: 300, key: 'image'});
    img.mask = new Phaser.Display.Masks.GeometryMask(this, mesh);
    }
}
```

this code is from example GeometryMask Example0, i've removed mesh tweening and created 30 images with same place and same mask, and i see, that fps droped to 20, so if i want to use mask on multiple images i'll kill my fps
with 60 images i've 4 fps

i mean, that if my display object is consist of several images, and i've for example 10 of them with mask, my game wont work on most of mobile devices

**Comment by photonstorm** [comment]
Using a mesh as a mask is a bit of an edge-case. What happens if you use a more traditional shape like a rectangle, or a bitmap mask?

**Comment by RollinSafary** [comment]
same problem, if game is running with WEBGL

**Comment by photonstorm** [comment]
And what hardware? (because your example above runs at a solid 60fps for me)

**Comment by RollinSafary** [comment]
Asus ROG zx50 with Core i7 6700hq CPU, DDR4 8GB RAM and NVidia GTX 960m 2GB 128bit video card

**Comment by photonstorm** [comment]
Just to say that I've pushed the new mask system to the master branch. It will now batch masks properly (as well as restore them when used in depth). A Scene with 100 masked Sprites under 3.16 was running at 20fps and generating 1500 gl ops per frame. Under the new system it runs at a solid 60fps and generates only 25 gl ops per frame. This is working fully for Geometry Masks now. Bitmap Masks are different, but I'll look at those soon.

**Comment by irenusfer** [comment]
Still really bad performance when running on mobile devices.
Made a rect mask that is used on 25 sprites and fps is in shambles.

Tested on: Huawei mate 10 pro, OnePlus 5T,  Galaxy s8, Iphone 8.

**Comment by photonstorm** [comment]
Necro posting year-old closed issues is a waste of my time and yours. If you seriously want this looked at, open a new issue with a test case.
