### ISSUE TITLE
Wrong "main" file in packages.json ?

### ISSUE THREAD

**Issue by orblazer** [photonstorm/phaser#3501]
This Issue is about (delete as applicable)
* An error on `package.json` ?

Hello, i have an question, the `main` file it is wrong ?
We probably need change `./src/phaser.js` by `./dist/phaser.js` for fix needed alias when `require` the module.

**Comment by hexus** [comment]
`src/phaser.js` is fine for me, webpack (in my own project) builds it wonderfully, and I can just `import Phaser from 'phaser';`.

**Comment by orblazer** [comment]
Yes my too but we need create alias :(

**Comment by snowbillr** [comment]
I was wondering about this too. Phaser has multiple distribution builds though, and I don't know which one would be appropriate for the `main` field in the `package.json`. I guess with having your own project build Phaser, you get more fine-grained control over what's included.

**Comment by hexus** [comment]
I don't use typescript, just Webpack and ES6. Once Webpack is up and running (i.e. watching and caching) then it rebundles very quickly.

**Comment by samme** [comment]
The problem is that [other tools](https://survivejs.com/webpack/appendices/comparison/#bundlers) will find the `main` entry but they can't use it.

**Comment by photonstorm** [comment]
I’m really not interested in supporting anything other than webpack for building phaser. If another tool works, then great, but it’s a bonus side effect.

**Comment by samme** [comment]
It's fine that building Phaser itself is a webpack-only job.

It's just that the `main` entry is awkward for bundling your own game using any non-webpack bundler.

**Comment by NaNdreas** [comment]
Changing main to `./dist/phaser.js` in package.json would work across all platforms without any extra config(!)

And if you for whatever reason *do* need to use the src files, or a specific distribution file as mentioned by @snowbillr, you can do something like this in Webpack:
```
resolve: {
  alias: {
    phaser: path.join(__dirname, 'node_modules/phaser/src/phaser.js'),
  },
},
```

**Comment by photonstorm** [comment]
Tonight I updated our build process a little, which has completely removed the need for `raw-loader` - shaders are just plain JS now. And we're using `typeof` checks for DefinePlugin, which work perfectly outside of webpack, but if you use webpack you get the bonus of being able to specify which renderer to include. This should make packaging with anything else now a lot easier.
