### ISSUE TITLE
Giving Geom a Matter body

### ISSUE THREAD

**Issue by kirillbunin** [photonstorm/phaser#3505]
I'm struggling with giving a Geom a Matter body, or with updating graphics according to matter bodies movement. I'm trying looping through all my Geoms, created from all my matter bodies, and then updating each with the position of the matter body and drawing it in to the graphics, but the results performance is really bad. Can anyone please provide me with an example? I found none at [labs.phaser.io](labs.phaser.io)
Thanks!

**Comment by iamchristopher** [comment]
You should ask questions like this on the [forums](http://www.html5gamedevs.com/forum/33-phaser-3/) or [Slack](https://phaser.io/community/slack).

**Comment by photonstorm** [comment]
You cannot give a piece of geometry a physics body. They're not game objects, just bundles of math.

You'll have to come up with your own method of taking the relevant data you need from a matter body and drawing it to a Graphics object. The more you draw, the slower it will get.
