### ISSUE TITLE
Matter Image destroy() throws error

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#3516]
* A bug in the API (always say which version you're using!)

```
createBody (x, y, key, index) {
    this.circ = this.matter.add
      .image(x, y, GENERAL_ASSETS_KEY, key)
      .setInteractive()
    this.circ.setBody(
      {
        type: 'circle',
        radius: 60 * 0.8,
      },
      {
        label: `Circ${index}`,
        mass: 11,
      },
    )
  }

```
so when i'm calling
`this.circ.destroy()`
i see this error

> Transform.js:36 Uncaught TypeError: Cannot read property 'position' of undefined
>     at MatterImage.get [as x] (Transform.js:36)
>     at Camera.cull (Camera.js:561)
>     at InputManager.hitTest (InputManager.js:380)
>     at InputPlugin.hitTestPointer (InputPlugin.js:450)
>     at InputPlugin.update (InputPlugin.js:1490)
>     at EventEmitter.emit (index.js:203)
>     at Systems.step (Systems.js:278)
>     at SceneManager.update (SceneManager.js:480)
>     at FingerBallsGame.step (Game.js:367)
>     at TimeStep.step (TimeStep.js:527)
>  

i saw that MatterImage extends from Image which is extends from GameObject, the last have destroy() method that destroying body, than itself, and i thought that destroy is the function to remove MatterImage from my scene

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
