### ISSUE TITLE
Tween.seek(to) doesn't work

### ISSUE THREAD

**Issue by Yazir** [photonstorm/phaser#3517]
Phaser 3.3.0

I have a problem with tweening a sprite. It's parameters value get changed instead of tween's progress when using seek().

Super simple example is presented here.
https://jsbin.com/butuzarifu/edit?html,output

**Comment by photonstorm** [comment]
Sorry this issue didn't get a reply, but Tween.seek is working correctly as of 3.18.1 (and likely earlier, but I've only tested it against that version today)
