### ISSUE TITLE
Allow adding new files during loading

### ISSUE THREAD

**Issue by universal-cosmic-destroyer** [photonstorm/phaser#3523]
**This Issue is about: A bug in the API (v3.3.0)**

`LoaderPlugin.addFile` does absolutely nothing if you try to load a file while it's not "ready." This includes while it's currently trying to load files.

In Phaser 2 I sped up a lot of my loading by letting files reference the other files they needed and adding them to the queue as things became available (vs loading more than was needed). For example, a tilemap can specify what music it has, or an object on a map says what sprite it uses. By waiting for the map JSON and then loading these things, I could load only the things needed.

I'm trying to see how viable it is to convert to Phaser 3, but currently my previous approach is not possible for the above listed reason.

e.g. (ES6 code)

```
class MyMapDataFile extends Phaser.Loader.FileTypes.JSONFile {
    onComplete() {
        if (this.data.properties.music) {
            this.loader.audio(
                'music.'+this.data.properties.music,
                'music/'+this.data.properties.music+'.mp3'
            );
        }
        super.onComplete();
    }
}
```

The requested audio is never actually loaded. Instead, I would like the file to be added to the queue if the loader is currently active.

**Comment by photonstorm** [comment]
I guess we could allow this as long as people don't mind their progress bars jumping all over the place when new files are added in. Seem's like it's just enabling a poor practise that is better dealt with in other ways (like a scene files payload or boot scene), then again, could be handy for things like Texture Packer multi-atlas files where one json contains the image paths. Will have a think about it as it's a feature request and we've got enough on at the moment in 3.4.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
