### ISSUE TITLE
fadeIn following a fadeOut doesn't seem to work

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3527]
I have reproduced the issue in [this fiddle](https://jsfiddle.net/jtcuuuub/11/) using Phaser 3.3. It's very similar to the fadeIn/out example, but in the opposite order. As can be seen, the camera remains dark although the fade callbacks are called (as seen from the `console.log` calls).

**Comment by photonstorm** [comment]
Ok, I got some time today to refactor how I wanted Camera effects to work, and I'm very happy with them now. Please, could you have a look at the master branch and test it out if you get a chance. The method signatures have changed slightly (the callback is now an `onUpddate` one, not `onComplete`) and there are new events and properties that can be used. See the new examples in labs for details but I also finished all jsdocs for Camera class, which should help too :)

**Comment by photonstorm** [comment]
Closing as now fixed in master and the updated labs tests show it running as expected :)
