### ISSUE TITLE
SVG and Text still blurry with after setting resolution

### ISSUE THREAD

**Issue by kirillbunin** [photonstorm/phaser#3528]
There has been several reports of this, but using Phaser `3.3.0` my game is still blurred on higher DPI devices, even after setting resolution to `resolution: window.devicePixelRatio` (or higher).
I'm using SVG assets and loading them as such. This is also the case for Text objects.

**Comment by kirillbunin** [comment]
There was discussion about Text objects having `resolution` prop of their own, but it is permanently set to `1`, and even after changing it in the source code, it does nothing.

**Comment by kirillbunin** [comment]
Still an issue in 3.4.0

**Comment by kanthi0802** [comment]
This issue still exists in 3.6.0

**Comment by photonstorm** [comment]
If it’s still open, it hasn’t been fixed yet. This issue won’t be done until the new scale manager is complete.

**Comment by kanthi0802** [comment]
@photonstorm If so please let us know when can we expect the new ScaleManager

**Comment by photonstorm** [comment]
This issue is currently blocked pending development of the Scale Manager, which will begin during the month of May 2018. It will be updated once it has been tested against the new Scale Manager.

**Comment by photonstorm** [comment]
Thanks for all your PRs and contributions towards getting it started sooner, they were really helpful. 😒

**Comment by photonstorm** [comment]
Text now works with resolution > 1. Resolution can be configured on a per-Text object basis. This is now in master branch.

SVGs are rendered to textures upon loading, the size of which is controlled by the SVG file itself. They render at the same size the SVG file specifies. If you need them to be crisper, make the export dimensions bigger in the files themselves.

**Comment by kanthi0802** [comment]
@photonstorm . Text is now crispy . Looks great. Thanks 👍

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
