### ISSUE TITLE
Best approach for the create event context using React and Redux

### ISSUE THREAD

**Issue by gazpachu** [photonstorm/phaser#3532]
Hi,

I'm starting a small game (easter egg) for an app that is based on React+Redux. I'm basically loading the phaser lib and creating the game object when the component loads. Then I've found that when passing `this.create` to the phaser config, the context used is the one from phaser, not the one from my component `BugBusters`. That's fine, as I can use `create: this.create.bind(this)` to force the method to use the context of the parent component. The issue is that I seem unable to get it right...

If use the Phaser context inside create, I cannot access `this.props.componentProp` but if use the component's context inside create, `this.game` doesn't seem to contain the `add` method to start adding assets to the game.

So what should be the right approach?

```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import Script from 'react-load-script';
import { setData } from '../../actions/actions';
import * as CONSTANTS from '../../constants/constants';

class BugBusters extends Component {
  constructor(props) {
    super(props);

    this.state = {
      config: null
    };

    this.game = null;
  }

  handleScriptLoad() {
    this.setState({
      config: {
        type: Phaser.AUTO,
        width: window.innerWidth,
        height: window.innerHeight - 50,
        parent: 'bugbusters',
        physics: {
          default: 'arcade',
          arcade: {
            gravity: { y: 200 }
          }
        },
        scene: {
          preload: this.preload,
          create: this.create
        }
      }
    });

    this.game = new Phaser.Game(this.state.config);
  }

  init() {
    // This is to change the data in my redux store
    this.props.setData(CONSTANTS.SET_LOADING, false);
    this.props.setData(CONSTANTS.SET_PHASER_STATE, 'loaded');
  }

  preload() {
    this.load.setBaseURL(process.env.NODE_ENV === 'development' ? '/assets/static/phaser' : '/dashboard/assets/static/phaser');

    this.load.image('sky', 'space3.png');
    this.load.image('logo', 'phaser3-logo.png');
    this.load.image('red', 'red.png');
    this.load.audio('soundtrack', ['soundtrack.mp3', 'soundtrack.ogg']);
  }

  create() {
    // Now the create method is using the Phaser context, so calling this.init() fails
    this.add.image(400, 300, 'sky');

    const music = this.sound.add('soundtrack');
    music.play();
  }

  render() {
    return (
      <section>
        <Script
          url="//cdn.jsdelivr.net/npm/phaser@3.3.0/dist/phaser.min.js"
          onLoad={() => this.handleScriptLoad()}
        />
        <div id="bugbusters" className="bug-busters" />
      </section>
    );
  }
}

const mapDispatchToProps = {
  setData
};

const mapStateToProps = ({
  mainReducer: {
    phaserState
  }
}) => ({
  phaserState
});

export default connect(mapStateToProps, mapDispatchToProps)(BugBusters);

```

**Comment by photonstorm** [comment]
Never used React in my life, but you can pass in external objects to the Scene like this:

```
    scene: {
        preload: preload,
        create: create,
        extend: {
            hello: 1,
            test: 'atari',
            addImage: addImage
        }
    }
```

From within the Scene methods (like create) you can now access `this.hello`, `this.test` and the function `this.addImage` - using this approach you could easily define some references back to your react component.

**Comment by jdotrjs** [comment]
@gazpachu I haven't actually tested this to verify but an alternate method that doesn't pass stuff in via scene's extend is:

```javascript
class BugBuster extends React.Component {
  // ...

  handleScriptLoad() {
    this.setState({
      config: {
      ...
      scene: {
        preload: this.preload,
        create: this.mkCreate(),
      }
    }
  })

  mkCreate() {
    const reactScope = this
    return function() {
      reactScope.init()

      // normal phaser create with this => Phaser.Scene
    }
  }
```

`mkCreate` will get called with `this` bound to to the react object... which you then bind it to `reactScope`. Once that's done you can continue to use that in the anonymous function that will serve as your scene's create.

Note: It's essential that you don't return an arrow function or it'll bind your `this` lexically which is not what you want.

**Comment by photonstorm** [comment]
Just tidying up and closing off this issue, as I know you got it working from your discussion on Slack.
