### ISSUE TITLE
Arcade Physics collisions aren't occuring

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#3535]
- <http://labs.phaser.io/edit.html?src=src\physics\arcade\collider%201.js>
- <http://labs.phaser.io/edit.html?src=src\physics\arcade\sprite%20vs%20group.js>

This Issue is about

* A bug in the API: 3.4.0 (12d27518da8975dbcea38569bc7eb9513b7e7c01)

**Comment by jdotrjs** [comment]
FWIW I bisected this using [this demo][demo] to test each sha and [this commit][bad-ref] looks like the offender. It doesn't revert cleanly so I can't trivially verify but I'll poke around a bit and see if I can figure what's going on here.

[demo]: https://pastebin.com/dFy4rz8a
[bad-ref]: https://github.com/photonstorm/phaser/commit/88647a487
