### ISSUE TITLE
Light2D not working for DynamicTilempas

### ISSUE THREAD

**Issue by FrancescoNegri** [photonstorm/phaser#3544]
The Light2D pipeline works fine with Sprites, anyway I'm not able to get it working with a Tiled generated background which is a DynamicTilemapLayer

**Comment by FrancescoNegri** [comment]
Here the error message I get
![bug](https://user-images.githubusercontent.com/11014462/38640128-ab43066a-3dd3-11e8-90ab-8c982336521a.PNG)

**Comment by photonstorm** [comment]
Yes, it was never meant to work with tilemaps, which is why I’ve marked this as a long term feature request.

**Comment by photonstorm** [comment]
Ok, Dynamic Tilemap Layers now support normal maps properly. However, Static Layers do not (and will remain this way for the foreseeable future)

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
