### ISSUE TITLE
Containers don't work with Phaser.Actions.GridAlign (maybe other actions too)

### ISSUE THREAD

**Issue by zajako** [photonstorm/phaser#3545]
This Issue is about A bug in the API (latest Dev)

**Code Example:**

> var cards = [];
for(var x = 0; x < 119; x++)
{
   var frame = this.add.image(0, 0, 'cardframe');
   frame.setOrigin(0, 0);
   var back = this.add.image(0, 0, 'card1');
   back.setOrigin(0, 0);
   var container = this.add.container(50, 50, [frame, back]);
   cards[x] = container;
}
Phaser.Actions.GridAlign(cards, {
   width: 17,
   height: 50,
   cellWidth: 60,
   cellHeight: 60,
   x: 125,
   y: 195
});

**Expected Result:**
The containers aligned in a grid as any other gameObject

**Result:**
The containers have their x and y values set to NaN

**QuickFix:**
Manually setting the container's originX and orginY to 0 in the loop fixes the issue and it works as intended.

I tracked the bug down to SetLeft and the other Set functions, they cause this when originX and originY are undefined.

I'm guessing the engine fix would be to ensure that originX & orginY are assigned for containers in the same way as other objects like Images

**Comment by photonstorm** [comment]
I've added in originX/Y to Container, however it still won't work unless you specifically call `setSize` on the Container first, otherwise it will think it has a size of 0x0 (which it does unless set otherwise)

**Comment by zajako** [comment]
I declare mine with a size, so I hadn't noticed this issue.
