### ISSUE TITLE
Zoom and bounds issues

### ISSUE THREAD

**Issue by nkholski** [photonstorm/phaser#3547]
I think I've stumbled upon a bug with zoom and bounds, possibly only on tilemaps.

If you zoom into a tilemap and want to keep 0,0 in the top left corner I need to adjust scrollX to "-gameWidth/(2*zoomFactor)" (and likewise for scrollY) and not (scrollX, scrollY) = (0,0) as expected.

If you set camera bounds you cant reach the upper left corner at all. Expected result of bounds with x,y-coordinates at 0,0 and width and height of what current zoom would fit should result in a zoomed in version of the top left rectangle of the tilemap (If I set x,y-properties to 0,0 I expect to see the 0,0 tile in upper left corner but the expected lower right tile will be centered). Setting a negative value for x does nothing, but positive values will move the camera but if height/width is less than the canvas with the camera will freak out. 

Reproduce by replacing the create function with the code below in this example: http://labs.phaser.io/edit.html?src=src\game%20objects\tilemap\static\zoom.js

```
function create ()
{
    // Build a random level as a 2D array
    var level = [];
    for (var y = 0; y < height; y++)
    {
        var row = [];
        for (var x = 0; x < width; x++)
        {
            var tileIndex = Phaser.Math.RND.integerInRange(0, 6);
            tileIndex = (x===0 || y === 0||x===width-1||y===height-1) ? 1 : tileIndex;
            row.push(tileIndex);
        }
        level.push(row);
    }
    var map = this.make.tilemap({ data: level, tileWidth: 32, tileHeight: 32 });
    var tileset = map.addTilesetImage('tiles');
    var layer = map.createStaticLayer(0, tileset, 0, 0);
    layer.originX = 0;
    layer.originY = 0;
    console.log(this.cameras.main);
    this.cameras.main.setBounds(0, 0, layer.width, layer.height);
    setTimeout(()=>{
         this.cameras.main.zoom = 4;
         console.log("Zoom")

    }, 2000);
    setTimeout(()=>{
         this.cameras.main.setBounds(0, 0, 800/4, 600/4);
        console.log("SetBounds, should show top left corner")
    }, 4000);
    setTimeout(()=>{
         this.cameras.main.setBounds(1, 0, 799, 600);
        console.log("SetBounds, horror")
    }, 6000);
}
```

**Comment by nkholski** [comment]
It's probably related to the issue when zooming out described in this thread:
http://www.html5gamedevs.com/topic/37357-creating-minimap-as-second-camera-view/
@samme created a codepen that demonstrates the issue within a mini-map:
https://codepen.io/samme/pen/zjdgEm?editors=0010

**Comment by marcinlesek** [comment]
Yes, I also forced with this issue. @photonstorm could you take a look? 🙏

**Comment by LaP0573** [comment]
This also causes issues when scrolling the camera. If your camera has set bounds and has a zoom level different to the standard one (which is 1), you will have very weird behaviours when scrolling the camera close to the bounds (by following a moving game object for example). It won't stop as soon as it hits the bounds, it goes too far, then as your followed game object gets closer to the bounds itself, the camera slowly adjusts itself to the right position (so basically it overshoots, then the closer you scroll to the bounds, the more it corrects itself).

**Comment by nkholski** [comment]
Made something to testa against.
1. Clone https://github.com/samme/brunch-phaser-es6
2. Update package.json to latest Phaser version. Run install.
3. Replace app folder with this: [app.zip](https://github.com/photonstorm/phaser/files/2080611/app.zip)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by nkholski** [comment]
I did some testing yesterday. For my test case camera position works fine when scaled up (haven't tried to set scale<1). However, I cant get it to work as expected by manipulating bounds. If you remember the Metroid clone I once did in Phaser two I had just one world map and tweened bounds for room transition. I need to test it a bit more to ensure I'm doing it right, and I'll update the example to test against.

**Comment by photonstorm** [comment]
I've worked on it some more since then as I fixed the issue with stuttering when following a sprite and a heavily zoomed-in camera, which highlighted a different issue when the bounds didn't fit into the camera viewport. So give it another go against master if possible.
