### ISSUE TITLE
MatterEvents.off() causes a TypeError

### ISSUE THREAD

**Issue by pixelscripter** [photonstorm/phaser#3562]
This Issue is about:

* A bug in the API: Version 3.4.0 - Miyako

MatterEvents.off() causes the following error in matter-js/lib/core/Events.js:
phaser.js:39960 Uncaught TypeError: Cannot set property 'events' of undefined

This is because the Events.off method needs the object as a parameter.
The call to MatterEvents.off() was added in [this commit](https://github.com/photonstorm/phaser/commit/70c7732a1ee53ff43ef0fe3aa09485d09aca3355).

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by pixelscripter** [comment]
Thanks. Passing this.engine was also my [initial solution](https://github.com/photonstorm/phaser/pull/3561).

Although this fixes the TypeError, then the events are never bound again (when switching scenes f.e.). Maybe this is because the event proxy is only initialised in the Matter.World constructor, not every time a new scene is started.

**Comment by photonstorm** [comment]
Each Scene has its own World instance, so starting a _new_ Scene shouldn't matter. However, restarting a current Scene (or restarting a previously stopped one) may skip the Scene boot. Will have a look.

**Comment by pixelscripter** [comment]
That could be the case here. I encountered this when restarting a previously stopped scene indeed.

**Comment by photonstorm** [comment]
Yeah, it's a much wider problem actually.

**Comment by photonstorm** [comment]
Created a Matter one too, all working :)

**Comment by pixelscripter** [comment]
That's quite an overhaul. Good this came to light. Very solid & generic structure indeed. Validated restarting a stopped Matter scene in my game and works as a charm now.

**Comment by photonstorm** [comment]
It's been on my list for a while - there were other little side effects that happened before this change, like restarting a scene wouldn't pick-up the physics config correctly when it recreated the world. Feels a lot better now but will carry on testing.
