### ISSUE TITLE
Phaser 3.4.0 - new animation event emit forever

### ISSUE THREAD

**Issue by murteira** [photonstorm/phaser#3565]
The new animation event `sprite.on('animationcomplete')` should only emit once, but keep emiting forever.

**Comment by hexus** [comment]
Can you provide a code example using JSBin or Codepen?

**Comment by photonstorm** [comment]
Agreed, as I can't replicate this yet. There must be some specific way to trigger it happening.

**Comment by samid737** [comment]
Seems fixed in dev build.

[v3.4.1-beta](http://jsfiddle.net/4hfxgs69/5/)

[v3.4.0](http://jsfiddle.net/4hfxgs69/4/)

**Comment by murteira** [comment]
Its fixed on 3.5.0, thanks!
