### ISSUE TITLE
Rotation on Phaser.Physics.Arcade.Body does not work

### ISSUE THREAD

**Issue by Reynicke** [photonstorm/phaser#3570]
Phaser version 3.3.0 / 3.4.0

Rotating a gameobject does not change the rotation of the physics body.

    var logo = this.physics.add.image(400, 100, "logo");
    logo.setAngle(10);
    logo.body.angularVelocity = 8;

In this case the image is rotated, but the bounding box of the physics body stays the same.

See here:
https://codepen.io/anon/pen/ZxdaOz

**Comment by photonstorm** [comment]
Yes, this is by design. Arcade Physics is AABB only. If you need rotated bodies please use Matter instead.
