### ISSUE TITLE
Support for compressed textures

### ISSUE THREAD

**Issue by Secretmapper** [photonstorm/phaser#3572]
Looking from the docs and the source code, it seems like support for compressed textures are gone. At least, on the docs, the second parameter has only a string type for the asset url instead of compressed texture object config like listed a couple of years ago https://gist.github.com/photonstorm/5eaab1e1ad1728483d2549be3454289f.

**Comment by photonstorm** [comment]
Yes, this feature was left out of the initial release. I don't have an eta for it being added back in, but it will eventually.

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
