### ISSUE TITLE
[Feature] Live video feature

### ISSUE THREAD

**Issue by AlexisTM** [photonstorm/phaser#3575]
Do you consider implementing a live video stream input or do you have a proposition on how to integrate one live feed in an Phaser application? 

The following example shows how to use the Webcam or a Video with THREE.js: http://learningthreejs.com/blog/2012/02/07/live-video-in-webgl/

The first step is to create a video element using the webcam, then to create a texture of it and updating the texture on every frame if available.

```javascript
video      = document.createElement('video');
video.width    = 320;
video.height   = 240;
video.autoplay = true;
video.src = "rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov";

var videoTexture = new THREE.Texture( video );

// @game speed
var material   = new THREE.MeshLambertMaterial({
  map : videoTexture
});
```

Video example: https://www.youtube.com/watch?v=vnNihxl3taE

I am thinking of a real-time stream of an online camera. 

For reference, Phaser CE implementation: https://github.com/photonstorm/phaser-ce/blob/master/src/gameobjects/Video.js

Another implementation: MJPEG on Canvas: https://github.com/rctoris/mjpegcanvasjs/blob/develop/build/mjpegcanvas.js

The missing parts: 
* [ ] Video API to be defined
* [ ] Gameobject from video
* [ ] Video to texture
* [ ] Texture update @gamerate

**Comment by photonstorm** [comment]
We had video support in v2 but it appeared to be so seldom used we didn't bother migrating it to v3 yet. I'll flag it as a long-term feature request.

**Comment by MarkSky** [comment]
Hope to join the API let us could input the MP4 files to the game.

**Comment by CorayThan** [comment]
I was migrating my app from Phaser 2 to Phaser 3. I don't need live video, just the ability to load and play an MP4 in general, but if Phaser 3 can't play videos that's basically a hard stop for me in my migration.

The app is an educational game that also plays videos integrated into the Phaser game from time to time.

**Comment by iamchristopher** [comment]
@CorayThan You could try using a [`DOMElement`](http://labs.phaser.io/index.html?dir=game%20objects/dom%20element/&q=) to render your video.

**Comment by mnzxc3** [comment]
Hope to join the API let us could input the MP4 files to the game.  ><

**Comment by JoepBC** [comment]
I was just bumping onto the same disappointment migrating from V2 to V3. A GameObject to preload and play static (e.g.) MP4 files would be really great. 

One of the reasons for me to use Phaser is to avoid calling browser-related-javascript features as much as possible. Most DOMElement examples produce errors here btw (Chromium @ Debian Linux), for example @ http://labs.phaser.io/edit.html?src=src\game%20objects\dom%20element\div%20depth.js

Uncaught TypeError: this.add.dom is not a function
    at Scene.create (eval at <anonymous> (frame.html:45), <anonymous>:33:29)
    at SceneManager.create (3.15.1.js:81750)
    at SceneManager.loadComplete (3.15.1.js:81644)
    at LoaderPlugin.emit (3.15.1.js:2255)
    at LoaderPlugin.loadComplete (3.15.1.js:114244)
    at LoaderPlugin.fileProcessComplete (3.15.1.js:114203)
    at ImageFile.onProcessComplete (3.15.1.js:4333)
    at Image.data.onload (3.15.1.js:10557)

**Comment by photonstorm** [comment]
That's because they're in the labs for testing with a specific build. DOM Elements aren't part of any release version yet.

**Comment by rgoldsto** [comment]
Thanks Yoeleven for the very helpful example.  Would love to see it extended to include input from a webcam!

**Comment by riksof-shahwar** [comment]
> I love phaser3 and our games need video support with all the abilities of gameobjects. So here is a solution below and a demo of [Phaser3 Video Gameobjects](https://github.com/yoeleven/phaser3-gameobject-video).
> 
> The method here is to create a texture canvas, which is an obscure but brilliant object that integrates with an html5 video element. We then use the html5 video element as the data source to draw an image directly onto the context of a phaser3 image gameobject texture.
> 
> I hope this helps others who are looking for video support.
> 
> ```js
> /* video typedef. */
> video_t=function(scene, id, x, y, texture, file, width, height, loop) {
>   /* set texture pointer to new canvas. */
>   scene.textures.createCanvas(texture, width, height);
>   Phaser.GameObjects.Image.call(this, scene, x, y, texture);
> 
>   /* gameobject data. */
>   this.id=id;
>   this.x=x;
>   this.y=y;
>   this.width=width;
>   this.height=height;
> 
>   /* video data. */
>   this.loaded=false;
>   this.loop=false;
>   if (loop)
>     this.loop=true;
> 
>   /* create video as html5 video element. */
>   this.video=document.createElement('video');
>   this.video.muted=true;
>   this.video.src=file;
> 
>   /* laziness - should use .call(this, ...) */
>   var _this=this;
> 
>   /* hook video event listener into animation. */
>   this.video.addEventListener('loadeddata', function() {
>     this.play();
>     _this.texture.context.drawImage(this, 0, 0);
>     _this.texture.refresh();
>     _this.loaded=true;
>   });
>   /* loop by playing on 'end' event listener. */
>   if (this.loop) {
>     this.video.addEventListener('ended', function() {
>       this.play();
>     });
>   }
> 
>   /* dragging. */
>   this.setInteractive({draggable:true});
>   this.on('dragstart', function (gameobject) {
>     this.setTint(0xff0000);
>   });
>   this.on('drag', function (gameobject, drag_x, drag_y) {
>     this.x=drag_x;
>     this.y=drag_y;
>     console.log('x: '+this.x+' y: '+this.y);
>   });
>   this.on('dragend', function (gameobject) {
>     this.clearTint();
>   });
> 
>   scene.add.existing(this);
> 
>   return this;
> }
> video_t.prototype.constructor=video_t;
> video_t.prototype=Object.create(Phaser.GameObjects.Image.prototype);
> 
> video_t.prototype.update=function() {
>   /* phaser's update call. */
>   if (this.loaded) {
>     this.texture.context.drawImage(this.video, 0, 0);
>     /* beware of refresh and issues with overloading the GPU - need solution here. */
>     this.texture.refresh();
>     //this.texture.update();                                            
>   }
> }
> ```

Hi @yoeleven,
Thanks for your solution it works like a charm in web but on mobile device it's not working just show a black screen. for android devices i mean Android Web View. any help will be appreciated.
Thanks in advance.

**Comment by photonstorm** [comment]
As of Phaser 3.20 (currently in the master branch) there is now a native Video Game Object, which allows for live video streams, or local video file playback, and streaming to texture. Please check out 3.20 for this feature.

**Comment by AlexisTM** [comment]
You are awesome @photonstorm Thanks!

**Comment by yoeleven** [comment]
Very excited about this, thank you!

**Comment by qroft** [comment]
> As of Phaser 3.20 (currently in the master branch) there is now a native Video Game Object, which allows for live video streams, or local video file playback, and streaming to texture. Please check out 3.20 for this feature.

That sound awesome - could anyone please post an example to the DOCS ? I am trying to figure it out and already asked for help on the Discord channel without luck. In theory i understand the process of putting the video on a texture and if this works like i think, something like "motion detecture" via Webcam or Phone is possible with Phaser 3.
I am currently playing around with diffyjs and diff-cam-engine and though it does work, i would love to use Phaser 3 without any of these plugins.
