### ISSUE TITLE
TexturePacker MultiPack feature - Loading the Atlas

### ISSUE THREAD

**Issue by NemoStein** [photonstorm/phaser#3577]
TexturePacker offers a MultiPack option that, when packing multiple atlas together, outputs:

* One JSON file describing all assets, referencing all the atlas files
* Multiple image files named sequentially (e.g.: img-0.png, img-1.png, img-2.png etc)

Sadly, as I can understand, Phaser3 doesn't support this because it's API expects:

* Path to one image and one JSON file
* Array of paths to the images and an array of paths to the JSONs
* A number (the count of atlas files)

I'd like to be able to call the loader only with a JSON file and it would parse the JSON and find out the paths to the images by itself. Something like this:

```javascript
this.load.multiatlas('key', 'path/to/atlas.json')
```

The `atlas.json` have a structure similar to this:

```json
{
	"textures": [
		{
			"image": "img-0.png",
			...
		},{
			"image": "img-1.png",
			...
		},{
			"image": "img-2.png",
			...
		}
	]
}
```

Is it possible?
I understand that this would force the JSON to be loaded first than the images later, but without this behavior the feature is useless.

ps: I know that I can pass all my files (images and JSONs) beforehand, but in my case this is unfeasible, since the atlas is build at compile time with a gulp task.

**Comment by photonstorm** [comment]
This feature request is reliant on #3523 being implemented first before it's possible.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
