### ISSUE TITLE
[3.5.0] Regression: Ability to add game objects to a scene before launching

### ISSUE THREAD

**Issue by rblopes** [photonstorm/phaser#3579]
It looks like 3.5.0 removed a feature I was using quite a lot in a few of my projects.

Before, it was possible to add game objects to the display list of a scene before it was displayed. That may sound like an unusual use case but that allowed me, for example:

-   to show a proper progress bar graphic over a splash screen (combined with a camera viewport for the bar stretching effect) ([example](https://jsfiddle.net/rblopes/vkvLuaqo/));
-   get references to game objects on scenes launched in parallel.

The sample code provided below demonstrates a reduced example of that feature. It works well with 3.4.0, but fails in 3.5.0, because neither `displayList` or `updateList` exist in the scene object.

Those features may be lost due changes made for the addition of transition effects in the scene manager.

<details>
<summary>Code sample (<a href="https://jsfiddle.net/rblopes/7Lny2dsc/">live</a>)</summary>

```js
class SceneA extends Phaser.Scene {
    constructor() {
        super({
            key: 'SceneA',
            files: [{
                key: 'atari1200xl',
                type: 'image'
            }]
        });
    }
    create() {
        const sceneB = this.scene.get('SceneB');
        sceneB.getLogo();

        this.scene.launch(sceneB);
    }
}

class SceneB extends Phaser.Scene {
    constructor() {
        super({
            key: 'SceneB'
        });
    }
    getLogo() {
        return this.add.image(320, 180, 'atari1200xl');
    }
}

const game = new Phaser.Game({
    type: Phaser.AUTO,
    width: 640,
    height: 360,
    backgroundColor: '#2d2d2d',
    loader: {
        baseURL: 'https://labs.phaser.io/',
        path: 'assets/sprites/',
        crossOrigin: true
    },
    scene: [SceneA, SceneB]
});
```
</details>

**Comment by photonstorm** [comment]
This is nothing to do with transitions I'm afraid, it's because we fixed how scene systems start up and shut down, allowing you to close a scene down properly, re-run it later, etc without the internal systems crashing or getting confused about what state they were in, re: all the issues about re-running Matter worlds, etc. It's a lot cleaner and more robust now. However, while the above code feels like an anti-pattern I can see why it would be useful in some cases, so I'll see if I can reenable it without losing what was achieved in the restructure.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
The comment in the code is true though. If you already have a reference to the Scene it’s pointless getting it from the Scene Manager again!

**Comment by rblopes** [comment]
But that method is used by several others (eg: `start`, `pause`, `remove` etc) internally. Enabling that branch, it is possible to pass an scene object and operate on scenes the same way as using string keys. What that branch did was (as I understand) check if that given object is a scene registered in the manager ─ if that's efficient is another matter.

Ok. If that is how things are supposed to work from the start then I'll revert to using string keys instead. :/

**Comment by photonstorm** [comment]
If you have the Scene you don’t need to go via the Scene Manager for any of those, can just do ‘menuRef.scene.start’ etc. I guess I could re-enable it, it’s a bit wasteful but happens so rarely under normal use it likely makes no difference.
