### ISSUE TITLE
multiple once.('destroy' events from scene plugins

### ISSUE THREAD

**Issue by jmcriat** [photonstorm/phaser#3581]
plugins 'destroy' on 'scene'.events are being multiplied every time a scene 'start'.
such event should only be needed to be added once in the the initialise function or in the re-added boot event maybe?

**Comment by photonstorm** [comment]
Yeah, we could change it to happen in either the boot method or the constructor. I actually think this is a bug in the EventEmitter library though. The function is identical in each call, the event name is the same and it's flagged as `once`, it should never get added again.

**Comment by jmcriat** [comment]
yep, adding something to eventemitter3 will create a event however it is, the library doesn't check if such call is already on the emitter or not it simple pushes it into it. that also causes issues when using scene.events in personal code if you are not careful in removing each event on scene shutdown, since it will keep multiplying every time create() is called (if one uses the same scene multiple times). this only happens to scene.events tho, since that is the only one that removeAllListeners() can't be called once shutdown is triggered.

**Comment by photonstorm** [comment]
I’m quite tempted to just take eventemitter3 and tweak it slightly, it’s small enough and not often updated so would be easy to maintain.

I’m also thinking about making System extend EE and have that for system and plugin events only, then leave scene.events for just user events, no internal ones, making it safe to clear entirely on shutdown.

It’s good practise for devs to tidy up events anyway, it’s not like the dom does it for you, so I don’t mind forcing them to do it, but mixing system with user events is potentially dangerous, so keeping them apart might be wise. Will think it over.

**Comment by Antriel** [comment]
In my opinion, eventemitter3's behavior is correct. If I call `.once(...` multiple times, same event/callback or not, it should fire it multiple times.

Tweaking this behavior to only ever call the same listener once per event would not only add additional overhead to the core, but also possibly cause unexpected situations for developers.

Cleaning up after yourself is always to be expected.

**Comment by jmcriat** [comment]
I agree with antriel, EE design choice is alright. i don't think tweaking it would be worth it. one should be careful anyway. I only mentioned it because the behaviour used on the event plugin class is differently from the other classes extended from EE, those all call removeAll on shutdown, but events can't because it is being used by the plugins, due to seeing that behaviour before i knew why the 'destroy' event was being multiplied the moment i saw it.
Personally after understanding this i had the same idea Rich had, to separate internal and user events, so i did that on my end. I think it was more logical having systems being/having a separated instance of EE (so i left scene.events alone) and that is for now emitting (update, wake, sleep, etc) events from another instance of EE (i made scene extend form EE, so it is like the same as all the others plugins). With that I can be lazy and add one line to remove all the events that i added in the respective scene instance. 
Since i have it already tweaked it like that in my end, I like Rich proposal a lot.
I do wonder tho why ScenePlugin itself isn't extended from EE like all the other gameobjs and plugins are (at least the ones that have events emitting capability) and rather have it as a separated plugin that must be used anyway or things simple wouldn't work. Is't it better having scene.on('update', since that follows the same pattern was input.on('keydown', sprite.on('drag', etc? and then have systems have or be another instance of EE to deal with the internals one that including emitting the respective events on the scene? I don't know if it is only me, but having scene.events.on felt like an eyesore since it didn't follow the 'recipe' like the rest, so i ended changing it on my end, but since i had been careful the change wasn't worth of a PR, it is too core for me to dare to change deeper, but since Rich is considering on separating it I finally have a change to point this out. I hope this makes sense.

**Comment by photonstorm** [comment]
I'm not interested in making the Scene itself extend EE. It would inject a crap load of properties and methods into your Scene that you may not even be aware of, and would have to be careful to work around. The whole point of the Scene in v3 was that it _didn't_ have anything required in there other than `sys`, and making it extend EE would go completely against that. If a user wants a Scene to extend EE it's trivial for them to do it themselves.

Which just leaves the Scene Systems instance of EE. My suggestion was simply that Systems itself extends EE, and that is what all the plugins use for internal chatter, and that `Systems.events` (which is the one that gets mapped into the Scene as a property) is just empty and not touched internally, other than to clear it when a Scene shuts down.

However, this does mean there are cases where we'd have to dispatch the same event twice. `transitionstart` for example is needed internally and also useful externally, but if we're isolating the two it would need sending down both channels. The same goes for most events the ScenePlugin emits actually.

Which makes me think separating them doesn't actually solve anything much, it just doubles the workload of every Scene. I will, however, resolve the annoying double-once issue.
