### ISSUE TITLE
For new Scene Transitions, we aren't currently passing "data" to the new scene

### ISSUE THREAD

**Issue by willywu** [photonstorm/phaser#3586]
It looks like in the new "Scene Transitions" functionality (`Phaser.Scenes.ScenePlugin#transition`), we aren't currently passing the "data" of the SceneTransitionConfig into the new scene that we're transitioning into.

Here's a jsfiddle to reproduce (https://jsfiddle.net/ay8h8ekt/3/), where SceneOne is transitioning to SceneTwo and it's trying to pass some data into SceneTwo's init() method.  The alert shows that the value is undefined.

If I edit the line that says `this.manager.start(key);` and instead put `this.manager.start(key, GetFastValue(config, 'data', {}));`, then it works as expected.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by willywu** [comment]
Great, thanks for the quick turnaround.  Tested locally and it looks good.
