### ISSUE TITLE
[Feature] Add drawText to RenderTexture?

### ISSUE THREAD

**Issue by kuoruan** [photonstorm/phaser#3587]
Hi @bitnenfer, is there any plan to add drawText to RenderTexture?
I'd like to make text buttons with RenderTexture. So I use RenderTexture.context to draw it myself. But I hope there is a method to draw text on  RenderTexture. Thanks

**Comment by photonstorm** [comment]
We'll consider adding a `RenderTexture.draw(gameObject)` for compatible Game Objects.

**Comment by molingyu123** [comment]
I have just contacted the game development, want a complete development process, and tools to use the document, do you?

**Comment by photonstorm** [comment]
Leave it open or it’ll never get implemented.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
