### ISSUE TITLE
Adding resolution property to config object does not trigger the pointer events for GameObjects in a Container

### ISSUE THREAD

**Issue by kanthi0802** [photonstorm/phaser#3589]
If when using resolution property on config object the GameObjects which are created with in a container are not receiving pointer events . Using Phaser version 3.5.1 ( Issue is also observed in v3.4.0 ).

Below is the code
---------
main.js
---------

var getGameWidth = function () {
    //var clientWidth = window.innerWidth;
    //var clientHeight = window.innerHeight;

    var clientWidth = screen.width;
    var clientHeight = screen.height;
    console.log("Return client width ", clientWidth + " - " + clientHeight);
    if (clientWidth > clientHeight) {
        return clientWidth;
    } else {
        return clientHeight;
    }
};

var getGameHeight = function () {
    console.log("Return client width ", clientWidth + " - " + clientHeight);
    //var clientWidth = window.innerWidth;
    //var clientHeight = window.innerHeight;

    var clientWidth = screen.width;
    var clientHeight = screen.height;
    if (clientWidth > clientHeight) {
        return clientHeight;
    } else {
        return clientWidth;
    }
};

window.onload = function () {
    var config = {
     type: Phaser.AUTO,
     width: getGameWidth(),
     height: getGameHeight(),
     backgroundColor: "#2e2e2e",
     resolution: window.devicePixelRatio,
     autoResize:true,
     scene: [MyFirstScene]
     };

   /*var config = {
        type: Phaser.AUTO,
        width: gameWidth(),
        height: gameHeight(),
        backgroundColor: "#2e2e2e",
        scene:[MyFirstScene]
    };*/

    game = new Phaser.Game(config);
};

-----------
MyFirstScene.js
-------------

class MyFirstScene extends Phaser.Scene {
    constructor() {
        super("MyFirstScene");
    }

    preload() {
        this.load.image("background", "assets/background.png");
        this.load.spritesheet("cards", "assets/cards_sprite_sheet.png", {frameWidth: 113, frameHeight: 148, endFrame: 55});
        this.load.script("CustomLayout", "js/CustomLayout.js");
    }

    create() {
        var gameWidth = game.config.width;
        var gameHeight = game.config.height;
        var background = this.add.image(0, 0, "background");
        background.setOrigin(0, 0);
        var imageWidth = background.width;
        var imageHeight = background.height;
        background.setScale(gameWidth / imageWidth, gameHeight / imageHeight);
        background.setInteractive();
        background.on("pointerup",function(){
            console.log("Pointer up on background");
        },this);
       
        
        var layout = new CustomLayout(this,0,300);
        this.children.add(layout);
    } 

}

--------------
CustomLayout.js
---------------

var CustomLayout = function (scene, x, y, children) {
    Phaser.GameObjects.Container.call(this, scene, x, y, children);
    this.createChildren();
};

CustomLayout.prototype = Object.create(Phaser.GameObjects.Container.prototype);
CustomLayout.prototype.constructor = CustomLayout;

CustomLayout.prototype.createChildren = function () {
    console.log("Create Children ", this.scene.input);
    for (var index = 0; index < 10; index++) {
        var image = new Phaser.GameObjects.Image(this.scene);
        image.setTexture("cards");
        image.setFrame(index);
        image.name = "card - " + index;
        image.setOrigin(0, 0);
        var screenWidth = Math.max(screen.width, screen.height);
        var imageWidth = screenWidth * 0.11;
        var imageHeight = screenWidth * 0.15;
        var actualWidth = image.width;
        image.setScale(imageWidth / actualWidth, imageWidth / actualWidth);
        image.setPosition(Math.floor((index) * image.width / 4), 30);
        console.log("Image position ", image.x + " -- " + image.y);
        image.setInteractive();
        image.on("pointerup", function () {
            console.log("Image Pointer events ", arguments);
        }, this);
        this.add(image);
    }
};

**Comment by photonstorm** [comment]
This issue is currently blocked pending development of the Scale Manager, which will begin during the month of May 2018. It will be updated once it has been tested against the new Scale Manager.

**Comment by kanthi0802** [comment]
@photonstorm . The issue is fixed with version 3.6.0.
