### ISSUE TITLE
[Future] make AddChild method in Scene, to add custom game objects to scene

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#3590]
I think that, if `this.add` is an object that have factory methods for standard Phaser's game objects, we need for a method in scene, to add custom game objects which are extending from Phaser's game objects. So I suggest to have `addChild `method in scene. I think that it's confusing that there isn't any method for that in scene methods
```
addChild (child) {
   this.sys.displayList.add(child)
}
```

**Comment by photonstorm** [comment]
`this.children.add()`

**Comment by photonstorm** [comment]
or `this.add.existing(child)`
