### ISSUE TITLE
Arcade physics: bounce restitution

### ISSUE THREAD

**Issue by helmi77** [photonstorm/phaser#3593]
When using arcade physics and setting the bounce value of an object to `1` I expected it would return to its original position. But even though friction is disabled, it doesn't. More specifically: the minimum Y position of the object gets higher and higher after each bounce.

For an example please refer to [this CodePen](https://codepen.io/anon/pen/gzOjBR).

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
