### ISSUE TITLE
Arcade Physics performance regression in 3.4.0 and later?

### ISSUE THREAD

**Issue by 16patsle** [photonstorm/phaser#3594]
Thanks to zor in the Discord server for noticing this.

It seems that the performance of Arcade Physics has gotten worse after version 3.4.0. I've not done much investigating yet, but comparing v3.3.0 and v3.4.0, I get about 37 fps vs 15 fps.

Tested using this example
http://labs.phaser.io/view.html?src=src/physics/arcade/10000%20world%20bodies.js

zor also observed that both versions of the Arcade Physics example run much slower than the equivalent example for Impact does:
http://labs.phaser.io/view.html?src=src/physics/impact/10000%20world%20bodies.js

Could this be a performance regression worth investigating? I'm planning on looking a bit more into it later

**Comment by photonstorm** [comment]
The only thing that has changed in AP (of any significance) is within the RTree class to remove the eval CSP violation. If I revert the change made in #3441 then performance returns to 3.3 levels.

Which is interesting. It basically means this:

```
        var compareArr = ['return a', ' - b', ';'];

        this.compareMinX = new Function('a', 'b', compareArr.join(format[0]));
        this.compareMinY = new Function('a', 'b', compareArr.join(format[1]));

        this.toBBox = new Function('a',
            'return {minX: a' + format[0] +
            ', minY: a' + format[1] +
            ', maxX: a' + format[2] +
            ', maxY: a' + format[3] + '};');
```

Is significantly faster than this:

```
        format = format.map(
            function (f)
            {
                return f.substring(1);
            }
        );

        var mkCompareFn = function(attr) {
          return function(a, b) {
            return a[attr] - b[attr];
          };
        };

        this.compareMinX = mkCompareFn(format[0]);
        this.compareMinY = mkCompareFn(format[1]);

        this.toBBox = function(a)
        {
            return {
                minX: a[format[0]],
                minY: a[format[1]],
                maxX: a[format[2]],
                maxY: a[format[3]],
            };
        };
```

I'll have a look into it some more.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by 16patsle** [comment]
Tested the example on the dev version now, and the performance does indeed seem to be back on the right level. Good job!

**Comment by jdotrjs** [comment]
@photonstorm bleh, sorry - I should have thought of this difference given that it was in collision hot path and patched it using the solution you ended up with.

Anyway, the root here (I believe) is that the `Function` constructor was baking a function that used dot-notation to access the attributes vs the anonymous function which was building taking the attribute name and dereferencing the object.  I couldn't find the best writeup I've seen of this before but it's roughly documented [here](https://stackoverflow.com/a/30360979).
