### ISSUE TITLE
Game.destroy(true) throws Error in version 3.5.1

### ISSUE THREAD

**Issue by kuoruan** [photonstorm/phaser#3596]
In #3569, fixed a Error, but still throws Error when the game has multi scenes.
Version: 3.5.1

https://jsfiddle.net/xonw21q6/6/

```
Uncaught TypeError: Cannot read property 'events' of null
  at DataManagerPlugin.destroy
```

**Comment by photonstorm** [comment]
Here's an example using multiple Scenes running at once and it still destroys properly:

http://labs.phaser.io/view.html?src=src\game%20config\game%20destroy%20with%20multi%20scenes.js

What do I need to do to the above example to replicate the error you're seeing?

**Comment by kuoruan** [comment]
![2018-04-20 10 36 37](https://user-images.githubusercontent.com/8685618/39027910-bef64da2-4486-11e8-9d32-ef1615130fef.png)

**Comment by kuoruan** [comment]
OK, I know what happen. If I do not set ```active: true``` to the Scene, error throws when destroy the game.
@photonstorm

**Comment by kuoruan** [comment]
http://labs.phaser.io/edit.html?src=src\scenes\launch%20parallel%20scene.js
Try this example. add
```
setTimeout(function () {
  game.destroy(true)
}, 3000)
```
To the bottom.
