### ISSUE TITLE
Can't require Phaser in Electron

### ISSUE THREAD

**Issue by tgrajewski** [photonstorm/phaser#3598]
I'm not being able to require Phaser in a desktop application running in Electron v1.8.4.

According to the readme file, one's could install Phaser 3 using NPM like this:

    npm install phaser

After that, when running Electron and trying to require Phaser, an error is thrown:

    Uncaught ReferenceError: WEBGL_RENDERER is not defined

This error is thrown in the [SpriteRender](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/sprite/SpriteRender.js) module.

Is Webpack required here and some build steps not explained in the readme? Would be great if it worked as is in Electron, without any additional build steps and requirements if possible.

Phaser v3.5.1, Electron v1.8.4.

**Comment by photonstorm** [comment]
https://github.com/photonstorm/phaser#webpack

**Comment by tgrajewski** [comment]
I was afraid that would be the answer here.

It seems that there are two things in that Webpack config that could be simplified and allowing to skip Webpack completely when using Electron.

One is to allow requiring shader files. This could be done like this:

    var fs = require('fs');

    require.extensions['.frag'] = function (module, filename) {
        module.exports = fs.readFileSync(filename, 'utf8');
    };

    ...

    var shader = require("./shader.frag");

And the other thing would be to set `WEBGL_RENDERER` and `CANVAS_RENDERER` being requireable or defined as global true.

**Comment by photonstorm** [comment]
As long as it doesn't break our build process I'll be happy to take a PR for this.

**Comment by tgrajewski** [comment]
I'll try, please be patient.

**Comment by tgrajewski** [comment]
I've investigated the situation and it appears, that there are no shortcuts here and both `WEBGL_RENDERER` and `CANVAS_RENDERER` would need to be turned into regular constants and maybe put inside the `const` module:

    var CONST = {
        _WEBGL_RENDERER: WEBGL_RENDERER,
        _CANVAS_RENDERER: CANVAS_RENDERER,
        ...

And then everywhere they are used of course we would need to have to import (require) them like you do already:

    var CONST = require('./const');

    if (CONST._WEBGL_RENDERER && CONST._CANVAS_RENDERER)
        ...

That would require around 20 files to be modified. Would you accept such PR, or you have a different idea how to approach this?

**Comment by tgrajewski** [comment]
That complicates things a bit. I'm not a Webpack user, but maybe that would just work in the Webpack config file:

    plugins: [
        new webpack.DefinePlugin({
            'CONST._CANVAS_RENDERER': JSON.stringify(true),
            'CONST._WEBGL_RENDERER': JSON.stringify(true)
        }),
    ],

**Comment by photonstorm** [comment]
Possibly. Will test it now and see.

**Comment by photonstorm** [comment]
Damn, sadly not. Swapping to use `CONST.CANVAS_RENDERER` (and using that in the source) seems to make it get skipped by DefinePlugin, as the bundle contains:

```
if (CONST.WEBGL_RENDERER)
{
    renderWebGL = __webpack_require__(/*! ./ImageWebGLRenderer */ "./gameobjects/image/ImageWebGLRenderer.js");
}

if (CONST.CANVAS_RENDERER)
{
    renderCanvas = __webpack_require__(/*! ./ImageCanvasRenderer */ "./gameobjects/image/ImageCanvasRenderer.js");
}
```

Where-as if the plugin had run properly it would contain:

```
if (true)
{
    renderWebGL = __webpack_require__(/*! ./ImageWebGLRenderer */ "./gameobjects/image/ImageWebGLRenderer.js");
}

if (true)
{
    renderCanvas = __webpack_require__(/*! ./ImageCanvasRenderer */ "./gameobjects/image/ImageCanvasRenderer.js");
}
```

**Comment by photonstorm** [comment]
Yeah that works: `process.env.WEBGL_RENDERER` and it gets compiled out properly. Any use to Electron?

**Comment by tgrajewski** [comment]
Yes, I believe it should work, that would of course require to define these environment variables before requiring Phaser.

I've also found another way from the DefinePlugin's documentation, by leveraging the `typeof` keyword we could have this:

        new webpack.DefinePlugin({
            "typeof CANVAS_RENDERER": JSON.stringify(true),
            "typeof WEBGL_RENDERER": JSON.stringify(true)
        }),

And it seems to work too, with code like this:

    if (typeof WEBGL_RENDERER && typeof CANVAS_RENDERER)

Of course that would require to prefix all `WEBGL_RENDERER` occurences with `typeof`.

**Comment by tgrajewski** [comment]
@photonstorm So, I can make a PR with `typeof's` or you can modify the code yourself, because it seems to be fast find and replace (if you accept such solution). Your decision here. It won't yet make it run in Electron, but I think this was the biggest obstacle.

**Comment by photonstorm** [comment]
I don't mind sticking the `typeof` checks in as they are only used when including the render files, it won't make any difference to the runtime speed if built via Webpack, and I doubt if ingested via any other means either.

Doesn't get around the shader raw-loader use though.

**Comment by tgrajewski** [comment]
For shader loading we can leverage the code from my earlier comments and it will work fine.

**Comment by tgrajewski** [comment]
It would need to be in Phaser's source, somewhere at the beginning, before first requires. It could be completely disabled when building with Webpack using the same trick with the DefinePlugin (it would be always stripped with Webpack).

**Comment by photonstorm** [comment]
Ahh ok - it'd still try and bundle in the whole of `fs` for any other packager though, which seems a tad much, but better than not working at all I guess.

**Comment by photonstorm** [comment]
Can `require.extensions` take multiple extensions? As it needs to cover both `.frag` and `.vert` files. Perhaps: `require.extensions['.frag', '.vert']` ?

**Comment by tgrajewski** [comment]
@photonstorm It's done, that's awesome, thanks you very much!

**Comment by photonstorm** [comment]
I'm going to have to undo the `require.extensions` change because it breaks packaging Phaser with Parcel. I'll keep the `typeof` change in though. Will try and find a new workflow for the shaders for the next release to avoid needing raw-loader or fs.

**Comment by photonstorm** [comment]
Ok all sorted :) 3.7.1 includes a new way of handling shaders, so Electron should work fine now.

**Comment by tgrajewski** [comment]
I was bit worried for a moment, but great you've managed this. Desktop games in Phaser, yay! :)

**Comment by honkskillet** [comment]
Can you recommend the best way to scaffold out  a Phaser + Electron project?
