### ISSUE TITLE
Convert elemento position do CSS cordinates??

### ISSUE THREAD

**Issue by murteira** [photonstorm/phaser#3602]
Is it possible to get current position of an element on Phaser Canvas and get corresponding CSS left and top Position.

I need to make a DOM element to get over e Phaser Element!

Thanks!

**Comment by photonstorm** [comment]
Not built-in, no. But it could be useful so I'll consider it a feature request. If you need something more immediate, ask on the forum / slack.

**Comment by photonstorm** [comment]
This issue is currently blocked pending development of the Scale Manager, which will begin during the month of May 2018. It will be updated once it has been tested against the new Scale Manager.

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
