### ISSUE TITLE
Gradient availability in Graphics GameObject

### ISSUE THREAD

**Issue by kanthi0802** [photonstorm/phaser#3603]
Hi ,

In Phaser v2 we have Gradients that can be drawn onto sprites. Any idea if this feature will be implemented in v3?

**Comment by photonstorm** [comment]
It's not built into v2 (there's no Gradient feature anywhere) - you would have had to create a Canvas or BitmapData, then draw the gradient onto that, then use that as a texture for a Sprite. You can do the same in v3:

```
var canvasTexture = this.textures.createCanvas('yourTextureKey', 320, 200);
var src = canvasTexture.getSourceImage();
var ctx = src.getContext('2d');

// do gradient ops here

this.add.image(0, 0, 'yourTextureKey');
```

**Comment by kanthi0802** [comment]
Hi , 
Thank you for the reply. I've tried what you have mentioned above. But it does not seem to work. Please have a look at the code below.

**Comment by rexrainbow** [comment]
@kanthi0802 Try setting render mode to `Phaser.CANVAS` in your case.

[Here](http://www.html5gamedevs.com/topic/37084-plugin-rexcanvas/) is my canvas plugin which could draw by canvas api in `Phaser.WEBGL` or `Phaser.CANVAS` mode.

**Comment by rexrainbow** [comment]
@kanthi0802 The magic is to [canvasTexture object](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/graphics/Graphics.js#L1142), which won't be updated when canvas content had changed in current version of phaser engine.

**Comment by rexrainbow** [comment]
@kanthi0802 You might reference [generateTexture](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/graphics/Graphics.js#L1142) of graphics object, which updated texture by canvas.

( But I had not tested that solution directly, since I had my own canvas plugin. It is more convenience, imo. )

**Comment by kanthi0802** [comment]
@photonstorm Any chance that gradients above mentioned will work in Phaser.AUTO/Phaser.WEBGL ?

thanks.

**Comment by rexrainbow** [comment]
@kanthi0802 I saw Rich had added new `CanvasTexture` object in code base, which might solve this issue.

**Comment by kanthi0802** [comment]
@rexrainbow  . OK thank you for the info. Will look forward to it.
