### ISSUE TITLE
Resolution results in bugs (input/camera)

### ISSUE THREAD

**Issue by Secretmapper** [photonstorm/phaser#3606]
I'm using resolution: 2 to essentially scale the game up twice. This works for the most part, until input and cameras are used. Namely for example, camera background color works on the 'smaller' resolution (hence it's smaller), and input doesn't work on cameras when zoomed.

I'm going to put sample code soon, just rushing right now for Ludum Dare ;) I'm not necessarily sure if it's a bug (perhaps this is expected behavior?) but it's quite unintuitive.

This is on 3.6 as well

**Comment by Secretmapper** [comment]
Hey, sorry for taking so long to reply,

@samid737 That's awesome, your examples pinpointed **exactly** the problems I faced. In particular

- the first fiddle demonstrates how the camera background colour doesn't show up in the new entire screen,
- the fourth [example](http://jsfiddle.net/9roqyue9/13/) shows the input problem (I guess input not working was too strong of a word - as you mentioned it simply results in input offset.)

**Comment by photonstorm** [comment]
This issue is currently blocked pending development of the Scale Manager, which will begin during the month of May 2018. It will be updated once it has been tested against the new Scale Manager.

**Comment by RichardGale** [comment]
Seeing the same thing as example 4 above, http://jsfiddle.net/9roqyue9/13/.

Two cameras, one for game play objects and one for the UI, scaled differently the drag collision areas are offset.

**Comment by photonstorm** [comment]
Camera color issue fixed in master.

Input resolution issues being worked on at the moment.

Anything not to do with resolution > 1 in this issue will not be covered by this work and needs to be opened in their own separate issues.

**Comment by photonstorm** [comment]
Ok, input is fixed now too. Also fixed issue with Camera Flash and Fade effects. Setting resolution > 1 will now stop these from all breaking.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
