### ISSUE TITLE
Some emitter properties are eased when set with {min, max}

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#3608]
When you set any of `alpha`, `rotate`, `scale`, `scaleX`, `scaleY`, or `tint` in the {min, max} form, the property is first assigned a random value in the range [min, max) (as with the emit-only properties), and **also** eased to max during the particle's lifespan: <https://codepen.io/samme/pen/ZobeER>

I expected {min, max} would set the initial value for these properties and do no easing at all: <https://codepen.io/samme/pen/ELVWKr>

Phaser Version: 3.16.2 to 3.23.0

**Comment by pe-linguaphone** [comment]
Can confirm this is the case with at least the `scale` property

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
