### ISSUE TITLE
Phaser.Boot namespace is missing (for PluginManager.register)

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#3609]
It seems to be required for Phaser.Boot.PluginManager.register.

**Comment by samme** [comment]
A static method would let a plugin class register itself automatically, even before any user code is run. That would be super convenient.

**Comment by photonstorm** [comment]
Fair enough, but I don't want to do this via Boot, it doesn't make any sense (grammatically I mean), so will look at moving it elsewhere.

**Comment by samme** [comment]
That's fine, I'm not attached to Boot. :)

**Comment by doubleprincez** [comment]
Can someone help me stop this threads from always mailing me, its flooding
my mail!!!and github unsubscribe button ain't working!!!

**Comment by photonstorm** [comment]
@doubleprincez we have no control over it, contact GitHub support directly. Or disable ‘watch’ on this repo.

**Comment by photonstorm** [comment]
Closing this off as the new plugin system is coming in 3.8 and we've moved namespace to `Phaser.Plugins` and made sure it's exposed :)
