### ISSUE TITLE
restoredContextCallbacks are never removed

### ISSUE THREAD

**Issue by Twilrom** [photonstorm/phaser#3610]
restoredContextCallbacks are never removed once created, retaining references to any objects that have called game.renderer.onContextRestored, even if they're destroyed.

**Comment by Twilrom** [comment]
Would probably be better off using EventEmitter3 for this.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
