### ISSUE TITLE
Set default origin (globally) for all GameObjects

### ISSUE THREAD

**Issue by NemoStein** [photonstorm/phaser#3611]
It's really strange to me that images/sprites are aligned in the center, not in the top-left corner, which makes it hard to build UIs.

So, is it possible to add a option to set the default origin of gameobjects?

---
**EDIT:** I just found out about the `Phaser.Display.Bounds` namespace, which eases the work with positioning of objects.
Is it the "Phaser 3 Way™" of aligning objects?
If so, shouldn't a GameObject have a delegate to it?
```javascript
// Something like this
this.add.image(0, 0, 'image').bounds.setLeft(100)
```

**Comment by photonstorm** [comment]
It's quite normal for game frameworks to have x/y represent the center. You can just do `this.add.image(x, y, key).setOrigin(0)` if you want to have x/y represent the top-left represent instead. There are no plans to make a configurable 'global' origin as it would introduce an extra look-up for every single GO created, which isn't worth it when it's so simple to adjust the origin at run-time.
