### ISSUE TITLE
Adding group with array of sprites broken since 3.5

### ISSUE THREAD

**Issue by fariazz** [photonstorm/phaser#3612]
The following code rendered a sprite until Phaser 3.4. From version 3.5 on-wards, nothing is rendered. No errors are shown in the console.

I've put together this [screencast](https://www.screencast.com/t/0jKqs5rx1s) showing this issue. Happy to provide any more info that can help fix this.

```js
let gameScene = new Phaser.Scene('Game');

gameScene.preload = function() {
  this.load.image('building', 'assets/building.png');
};

gameScene.create = function() {

  this.add.group([{
      key: 'building',
      setXY: {
        x: 100,
        y: 240
      }
    }
  ]);
};

let config = {
  type: Phaser.AUTO,
  width: 640,
  height: 360,
  scene: gameScene,
};

let game = new Phaser.Game(config);
```

**Comment by samme** [comment]
<http://labs.phaser.io/edit.html?src=src\game%20objects\group\multiple%20adds.js>

**Comment by samme** [comment]
My fault (#3573).

**Comment by fariazz** [comment]
Thanks @samme for the quick fix!

**Comment by fariazz** [comment]
@samme still experiencing this issue with your fixes/3612 branch. These are the steps I followed:

- cloned your repo
- ` git checkout --track origin/fix/36121`
- `npm install`
- `npm run dist`
- used `dist/phaser.js` in my project

**Comment by samme** [comment]
You can search for `(config[0].key === undefined)` in `dist/phaser.js` to confirm it includes the change.

You can also work around the bug by using

    this.add.group().createMultiple([/* ... */]);
