### ISSUE TITLE
Adding resolution property to config object reduces the frame rate considerably when running in Phaser.AUTO/Phaser.WEBGL

### ISSUE THREAD

**Issue by kanthi0802** [photonstorm/phaser#3615]
Hi,

When adding resolution property to config object of the game, the FPS reduces to around 35 when running in Phaser.AUTO/Phaser.WEBGL mode. The same seems to be running at 60 FPS when in Phaser.CANVAS mode.

Device is Samsung j5 with the following hardware
GPU - Adreno 306
RAM - 1.5GB
Chipset  - Qualcomm MSM8916 Snapdragon 410
CPU - Quad-core 1.2 GHz Cortex-A53

**Comment by photonstorm** [comment]
You're hitting the limits of what the browser can handle with the GPU of that device. It's having to process x `resolution` more pixels than before, creating larger textures, using more memory. How much this matters depends on what you've got in your game, but you're now using double of everything (or more), so the impact is going to scale linearly.

**Comment by photonstorm** [comment]
With a x2 resolution that's now a 2560 x 1600 canvas, which might well be too large for that device to cope with. If the fps drops that much it sounds like it's hitting the fillrate limit, or having to do something internally that the GPU doesn't like (maybe it has a max texture size of 2048? I don't know) - in short, that's a lot of pixels to handle for a mobile browser. Honestly, it's more than some desktops can handle smoothly too. It might be worth removing Phaser entirely and just trying it out with a bog standard vanilla JS and a canvas and see what happens, there are a few helper WebGL libs out there that would get you up to speed quickly.
