### ISSUE TITLE
Interactive object inside invisible container

### ISSUE THREAD

**Issue by NemoStein** [photonstorm/phaser#3620]
Consider the following:
```javascript
const outside = this.add.image(100, 100, 'image.png')
	.setInteractive()
	.on('pointerdown', () => console.log('outside'))

const inside = this.add.image(200, 100, 'image.png')
	.setInteractive()
	.on('pointerdown', () => console.log('inside'))

const container = this.add.container()
container.add(inside)

outside.setVisible(false)
container.setVisible(false)
```

One image (`outside`) is created and left on the scene, the other (`inside`) is put inside the container.
Both `outside` and `container` is set not visible.

Clicking in the region where image `outside` is doesn't do anything, as expected.
Clicking in the region where image `inside` is do log `"inside"` in console.

**Comment by photonstorm** [comment]
Yeah, this ought to be covered somehow - `visible` has no parent look-up taking place, i.e. a child could think it is visible, but its parent or a parent of a parent isn't, and it doesn't know about it. It's frustrating because to derive it we'll have to do a parent look-up every time you check the `visible` property. Will have a think about it some more to try and avoid that for non-container elements.

**Comment by NemoStein** [comment]
Since a `GameObject` (except the `Container`) can't have children, I don't think that a lookup would impact on performance that much, even in extreme cases (hundreds/thousands of gameobjects in the scene), but I could be (terribly) wrong... =P

**Comment by photonstorm** [comment]
The `visible` property is already checked, this is why `outside` didn't log anything in your example. The cost I'm talking about comes from having to do this:

```
if (this.parentContainer)
{
  // look-up all parents to see if any of them return false
}
```

Which you would have to do for every Game Object, every time it tests if it's visible or not. Adding in this check is a cost on its own, never mind the look-up itself. Globally adding this check to every Game Object impacts performance negatively, even if you're not using Containers at all.

**Comment by photonstorm** [comment]
Even adding extra properties like that just adds to the overall complexity / size of every object, even if they don't touch a container in their game. I think it would just be easier to limit the visible look-up check to the input handler alone, or alternatively setting `visible = false` on a Container immediately passes that value down to all children, so their `visible` property gets changed too. Then the input system doesn't need updating. It does mean you could then turn a specific child 'back on' again, and it won't render but it'd still pick-up input, but perhaps that's a limitation worth living with.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
