### ISSUE TITLE
container setInteractive add callback default  

### ISSUE THREAD

**Issue by poasher** [photonstorm/phaser#3622]
callback is marked as an optional parameter
Typescipt
setInteractive(shape?: any, callback?: HitAreaCallback, dropZone?: boolean): Phaser.GameObjects.GameObject; 

```
let shape = new Phaser.Geom.Rectangle(0, 0, this.image.width, this.image.height);
this.setInteractive(shape);

```

 input.hitAreaCallback is not a function
    at InputManager.pointWithinHitArea 
    at InputManager.hitTest 
    at InputPlugin.hitTestPointer

**Comment by photonstorm** [comment]
It's optional if you don't specify the shape. If you do, it's not optional. There's no way to reflect both variations in just the data-types / defs.

**Comment by photonstorm** [comment]
Docs updated to reflect the requirement.

**Comment by clickblipclick** [comment]
@photonstorm Just for my own understanding - why do you need a callback if you provide a shape? Should I be doing anything in the callback?
