### ISSUE TITLE
container getBounds child Graphics

### ISSUE THREAD

**Issue by poasher** [photonstorm/phaser#3623]
```
         let cont1 = this.add.container(0, 0);
         let backMask = new  Phaser.GameObjects.Graphics(this, null);
         backMask.fillStyle(0x000000);
         backMask.fillRect(0, 0, 500, 500);
         cont1.add(backMask);
         cont1.getBounds();

```
https://github.com/photonstorm/phaser/blob/ef136f684d4ff59547c50373047e98459ef91bbf/src/gameobjects/container/Container.js#L324
error
    entry.getBounds is not a function
    at Container.getBounds

**Comment by photonstorm** [comment]
Yes, needs fixing. There's no `getBounds` for Graphics, nor can there be, so it needs to skip children that don't have that method.

**Comment by poasher** [comment]
If we skip children for the container, how then to get the exact width and height of the container?
Please add  width , height in container.
Thank you.

**Comment by photonstorm** [comment]
You can’t get the bounds for a Graphics object, so those specifically will need skipping. Everything else can be calculated is the getBounds call.
