### ISSUE TITLE
Bug: extra space in wrap mode of text object

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3626]
This Issue is about (delete as applicable)

* A bug in the API (v3.6.0)

[Here](https://codepen.io/rexrainbow/pen/Lmboma) is a live demo of this bug. There are 2 text objects.
- The first one has `wordWrap.width` = 200, which has an extra space in each line end.
- The second one does not have wordWrap, which works well.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
