### ISSUE TITLE
animation.setProgress error

### ISSUE THREAD

**Issue by benhhopkins** [photonstorm/phaser#3633]
Looks like there is an issue here:
https://github.com/photonstorm/phaser/blob/8d6eb2f9edfc9480ff2658dc76b20b3e12b0d465/src/gameobjects/components/Animation.js#L563

AnimationManager does not have `getFrameByProgress`.

I believe it should be:
`this.setCurrentFrame(this.currentAnim.getFrameByProgress(value));`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by benhhopkins** [comment]
Thanks! Yes, I did make the change in my copy of the source and can confirm that it worked.
