### ISSUE TITLE
Can someone help me fix Travis CI?

### ISSUE THREAD

**Issue by photonstorm** [photonstorm/phaser#3634]
If you look at Travis you'll see that it no longer works, complaining about the command `eval yarn` no longer working. I haven't changed anything, it just decided to stop working and I'm not entirely sure why.

Does anyone know or can figure it out? Here's an example error:

https://travis-ci.org/photonstorm/phaser/builds/372712165

**Comment by woutercommandeur** [comment]
Looks like travis is using node 10 and the upath module requires <=9:
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module

**Comment by woutercommandeur** [comment]
You should be able to set the version in the travis.yaml
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by photonstorm** [comment]
Done. Fingers crossed.

**Comment by woutercommandeur** [comment]
It seems to work, no longer erroring on the upath module but on regular linting errors.

**Comment by photonstorm** [comment]
Awesome, thank you :) that's been bugging me for days.

**Comment by photonstorm** [comment]
Wahhh! And now it's erroring again, even though I'm specifying node 9 :(

At least it worked for a few hours. Bloody thing.

**Comment by woutercommandeur** [comment]
remove 'node' just 'keep the '9'
my bad :(
It's now doing two builds.

```
language: node_js
node_js:
  - '9'
```
