### ISSUE TITLE
3.5.1/3.6 After restarting the main scene and launching a scene from it, the camera of new scene is undefined in the first tick.

### ISSUE THREAD

**Issue by Yazir** [photonstorm/phaser#3636]
Phaser 3.6.0

I've updated from Phaser 3.4 to 3.6, but the bug is apparent in 3.5.1 already. It worked fine in 3.4.
When restarting a scene which is launching a new scene, a reference to main camera of the launched scene is undefined.
A workaround would be adding a timeEvent on a short delay but that's a temporary solution.

Super simple example is presented here.
https://jsbin.com/nacemoqala/edit?html,output (open console to see logs and errors)

**Comment by Yazir** [comment]
Main camera is also undefined on the last tick of the scene and it doesn't have to be a different scene than the main one.

**Comment by photonstorm** [comment]
Think of `this.scene.launch` as being like an async process, because it is. If you want to do something immediately with the scene that you've asked to be launched (which doesn't happen immediately) then listen for its `start` event and do what you need inside that.

**Comment by Yazir** [comment]
`this._background = this.scene.manager.getScene('background')
this._background.events.on('start', function(){
    this._background.cameras.main.setBackgroundColor('#7EC0EE')
})`

Tried doing this and the main camera is still undefined.
