### ISSUE TITLE
GraphicsCreator should not append Graphics object to displayList by default

### ISSUE THREAD

**Issue by mikuso** [photonstorm/phaser#3637]
A bug introduced in b23ad3b1306eeb9ff3c59a506125467d308a363d causes the GraphicsCreator (`this.make.graphics(...)`) to add Graphics objects to the displayList by default.

Other game objects delegate this responsibility to the Factory, rather than the Creator.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
