### ISSUE TITLE
Add Fullscreen support

### ISSUE THREAD

**Issue by Secretmapper** [photonstorm/phaser#3639]
There seems to be some fullscreen detection but it's not exposed in the scene/scale managers (or I missed in on search)

**Comment by photonstorm** [comment]
This issue is currently blocked pending development of the Scale Manager, which will begin during the month of May 2018. It will be updated once it has been tested against the new Scale Manager.

**Comment by flahhi** [comment]
from my point of view, it is a very important thing to have an ability to play games in full screen. So, I don't think it is the low priority

**Comment by hexus** [comment]
It's currently absolutely possible to fill a page with the canvas using the browser's and Phaser's resize events.

The rest of the full-screen support, after that fact, that hasn't been wrapped up by Phaser yet, but you can still implement it yourself.

Check out this example:

http://labs.phaser.io/edit.html?src=src\game%20config\game%20resize.js

Hit `Launch` to see it in action outside of an iframe.

**Comment by flahhi** [comment]
@hexus thanks for your answer
Yes, I know about the resize. But fullscreen and resize has slightly different meanings. Play game in fullscreen means that everything in the screen except the game is hidden. So we don't see address bar, all browser tabs etc. This is the thing that I want to see in the new phaser, like it was in the previous version.

**Comment by hexus** [comment]
As I said:

> The rest of the full-screen support, after that fact, that hasn't been wrapped up by Phaser yet, but you can still implement it yourself.

I do understand the difference. :) 

You can still use the browser's Fullscreen API to achieve what you want, until the Scale Manager is implemented to do it for you.

**Comment by rexrainbow** [comment]
@raisen 

[boot/ScaleManager.js](https://github.com/photonstorm/phaser/blob/master/src/boot/ScaleManager.js)

**Comment by iamchristopher** [comment]
@raisen According the [devlog](https://madmimi.com/p/933c9c), the Scale Manager will be available in `v3.12-beta3` closer to the end of August.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
