### ISSUE TITLE
BitmapText renders only certain portion of text when in WEBGL and resolution property set on config

### ISSUE THREAD

**Issue by kanthi0802** [photonstorm/phaser#3642]
Hi 
Issue occurs in 3.6.0. When using bitmaptext with WEBGL and resolution property set on config object of the Game, the bitmaptext renders only certain portion of the text. In CANVAS mode it working good.

Further, the issue does not occur when the bitmaptext is positioned at (0,0) co-ordinates.

**Comment by photonstorm** [comment]
This issue is currently blocked pending development of the Scale Manager, which will begin during the month of May 2018. It will be updated once it has been tested against the new Scale Manager.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by kanthi0802** [comment]
@photonstorm . Tested against 3.11.0-beta1. It's working as expected. thanks
