### ISSUE TITLE
Tint has switched blue and red values for particles.

### ISSUE THREAD

**Issue by rgk** [photonstorm/phaser#3643]
If you set tint to a red value it shows blue. (0xff0000)

http://labs.phaser.io/edit.html?src=src\game%20objects\particle%20emitter\tint.js

Change tint to 0xff0000.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
