### ISSUE TITLE
Input Numeric Pad Keys With NumLock On

### ISSUE THREAD

**Issue by Gaushao** [photonstorm/phaser#3648]
I couldn't input numbers by the numeric pad with 'numlock on'. It seems not declared as I read [here](https://github.com/photonstorm/phaser/blob/37eb938d99f55bf2e481372e6fc501aa7e36430e/src/input/keyboard/keys/KeyCodes.js). Theresn't numbers referred to the numeric pad, since the codes 48 to 57 refers to the alphanumeric section of the keyboard. Could the declaration of the key codes from 96 to 105 be done?

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
