### ISSUE TITLE
[Feature] Use provided WebGL context or allow WebGL 2 context

### ISSUE THREAD

**Issue by tgrajewski** [photonstorm/phaser#3653]
Would be great if Phaser would allow to use an already created WebGL context when instancing the `Phaser.Game` class instead of creating own.

If that's problematic, then would be great if Phaser would provide an option to create a WebGL 2 context.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

You can also find 2 examples in the labs showing how to use this.
