### ISSUE TITLE
Cannot read property 'key' of undefined when creating a group

### ISSUE THREAD

**Issue by TheColorRed** [photonstorm/phaser#3657]
After updating from `3.6` to `3.7` I am getting an error:

> Uncaught TypeError: Cannot read property 'key' of undefined

```ts
export class MainGame extends Scene {
  public constructor() {
    super({
      key: 'MainGame'
    })
  }

  public create() {
    // The following line triggers the error
    this.pillars = this.add.group([])
  }
}
```

![cannot read property key of undefined](https://user-images.githubusercontent.com/1571806/39896109-7722629e-5472-11e8-93d1-df716fbdaeff.PNG)

**Comment by photonstorm** [comment]
While I could definitely catch this, I'd like to know why you're passing in an empty array in the first place :)

**Comment by TheColorRed** [comment]
I am using typescript, and it accepts `children: GameObjects.GameObject[]` as a parameter, since I have no objects the this time, I was passing an empty array. I see that I could otherwise pass `GroupConfig`. I don't have one, so passing `{}` as a parameter fixes the error. Not sure if that is the correct thing to do...

**Comment by TheColorRed** [comment]
If no parameter is required, then it looks like the typedoc needs to be updated from this:

```ts
/**
 * Creates a new Group Game Object and adds it to the Scene.
 *
 * Note: This method will only be available if the Group Game Object has been built into Phaser.
 * @param children [description]
 * @param config [description]
 */
group(children: Phaser.GameObjects.GameObject[] | GroupConfig, config?: GroupConfig): Phaser.GameObjects.Group;
```

to this:

```ts
/**
 * Creates a new Group Game Object and adds it to the Scene.
 *
 * Note: This method will only be available if the Group Game Object has been built into Phaser.
 */
group(): Phaser.GameObjects.Group;
/**
 * Creates a new Group Game Object and adds it to the Scene.
 *
 * Note: This method will only be available if the Group Game Object has been built into Phaser.
 * @param children [description]
 * @param config [description]
 */
group(children: Phaser.GameObjects.GameObject[] | GroupConfig, config?: GroupConfig): Phaser.GameObjects.Group;
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release.

**Comment by Macedaj** [comment]
El 10 may. 2018 5:01 PM, "Richard Davey" <notifications@github.com>
escribió:

While I could definitely catch this, I'd like to know why you're passing in
an empty array in the first place :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/photonstorm/phaser/issues/3657#issuecomment-388199306>,
or mute the thread
