### ISSUE TITLE
Crash when stoping a scene that has a TileSprite inside a container

### ISSUE THREAD

**Issue by PaNaVTEC** [photonstorm/phaser#3661]
The following crashes:

```function create() {
  const a = this.add.container(0, 0)
  a.add(new Phaser.GameObjects.Container(this, 0, 0, [
    new Phaser.GameObjects.TileSprite(this, 0, 0, 100, 100, 'logo')
    //new Phaser.GameObjects.Text(this, 0, 0, 'logo')
  ]))
  this.scene.stop('sceneKey')
}
```

with:

```
TileSprite.js:279 Uncaught TypeError: Cannot read property 'gl' of null
    at TileSprite.destroy (TileSprite.js:279)
    at EventEmitter.emit (index.js:202)
    at Systems.shutdown (Systems.js:612)
    at SceneManager.stop (SceneManager.js:1090)
    at ScenePlugin.stop (ScenePlugin.js:618)
    at TotalWarScene.onMessage (TotalWarScene.ts:121)
    at WebSocket.<anonymous> (socketClient.ts:4)
```

But if instead you create the container with the text object that I've attached, it works.

**Comment by laptou** [comment]
I am also experiencing this problem. It appears that the TileSprite is destroyed twice, and the second time is when it fails because the `renderer` property is null.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by PaNaVTEC** [comment]
It works like a charm, thanks!!
