### ISSUE TITLE
Some emitter ops fail when set with an array of numbers

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#3663]
createEmitter({ scale: [0.5, 1] })

updates the particle's `scaleX` with `[0.5, 1]`. <https://codepen.io/samme/pen/KRoGmg>

    createEmitter().fromJSON({ alpha: [0.5, 1] })

updates the particle's `alpha` with `[0.5, 1]`. <https://codepen.io/samme/pen/YLvjZb>

**Comment by samme** [comment]
The reason is that staticValueUpdate is assigned when the op is first configured but it's not removed when the op is reconfigured.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
