### ISSUE TITLE
No Sound since Chrome Version 66

### ISSUE THREAD

**Issue by Maqsyo** [photonstorm/phaser#3664]
https://www.androidpolice.com/2018/05/12/chromes-new-autoplay-requirements-breaking-online-games/

It would be really great, if you could add Chrome to the this.game.sound.touchLocked Component

Please Close if it's already fixed and i just haven't found it ^^

Thanks :)

**Comment by photonstorm** [comment]
Yeah, we fixed this in 3.7.1 :)
