### ISSUE TITLE
[Safari] setTexture from a Promise sometime doesn't work

### ISSUE THREAD

**Issue by kirillbunin** [photonstorm/phaser#3667]
Hey guys, for quite some time now, I'm trying to resolve some issues on Safari (iOS & OSX) which works fine on Chrome/FF/IE. It's hard for me to put up an example, since it is a part of bigger codebase, but what I'm experiencing is pretty much - `setTexture` on `Image` object from within a `Promise` works only 20% of the time.
I've tried dynamically loading new image after the `load`, using async Fetch with polyfill, and I managed to get it working. But once I got to Safari, everything went down.
`obj.texture.key` changes, but visually it does not. I tried setting texture (from the promise, after loading new image) to something that has been loaded during `load`, and still i get only 80% of success. I'll try to make an example, but maybe somebody is experiencing this as well?

**Comment by photonstorm** [comment]
I need an example to understand the flow going on here. As long as the texture is loaded and in the cache, it shouldn't matter _too much_ when `setTexture` is called, Promise or not. If, however, you're trying to set the texture as the result of an out-of-Loader image call, then sure, I can see that causing problems. But I'll need an example to figure it out.

**Comment by kirillbunin** [comment]
https://github.com/kirillbunin/phaser-3-7-1-safari-loader-bug
live demo http://phaser-safari-loader-bug.kirillbunin.com/

Sorry it's a bit of a mess.

Try it on chrome, then on Safari on iOS or OSX, reloading it a several time (i found there are 4 possible behaviours).

**Comment by kirillbunin** [comment]
To explain what is happening there, I have two main `Image` objects (+ some decorative one, just for the sake of it) first one, the main one, is `red`. When triggered change, it should hide the `red` one, and display the second one. The second one is initially `green`, but I'm trying to load an processed image there ( `BasketBall.js` lines `107`-`143`). So in Chrome you'll get a Cat Ball.
In Safari, about 5% of the time, the Ball will stay red. 35% of the time it will be green. And 60% of the time it will be BLUE. I have no idea why Blue, since I'm not even using it. It's just a texture I happen to load.

**Comment by kirillbunin** [comment]
In my other findings, Safari overall has problems working with masks. I'm taking advantage of the `depth` to put some objects in front of the other, but only Safari can't handle it. After tweening it randomly renders object in bad order, even though the `depth` prop says it should be okay. Since I'm using Mask here as well, I thought it would be related.
Also, this was an issue in earlier versions as well. Just the Safari though.

**Comment by samid737** [comment]
Chrome 64.0.3282.112 on iOS 11,Iphone 7 has the same issue as Safari (on the same device). I cannot test OSX.

**Comment by photonstorm** [comment]
Log something out before calling setTexture. Are you 100% sure it always gets that far? As I counted I think 4 un-caught Promises and an uncaught onload, any of which could have failed or generated an image that Safari can’t handle.

Also, there’s no point loading an image you created dynamically. Just add it directly to the Texture Manager.

**Comment by kirillbunin** [comment]
I updated repo and live demo. I replaced native promise with [Axios](https://github.com/axios/axios). I've added some logs, and on iOS 10.2 Safari I get
```
...
load completed, setting texture
texture.key before ball-green
texture.key after 4uuhz0jfzwrwcgknmfxhzi
```
while the ball is blue. On Windows Chrome it works as expected.

**Comment by kirillbunin** [comment]
I've replaced using Loader with directly adding it to the Texture Manager, no change on the result tho. (thanks for the tip tho!)

**Comment by kirillbunin** [comment]
Issue is not with the loading/promises but rather SVGs themselves, moved to separate ticket.
