### ISSUE TITLE
Unable to destroy scene when a global plugin is used

### ISSUE THREAD

**Issue by Telokis** [photonstorm/phaser#3668]
Using an example found in the lab (https://labs.phaser.io/edit.html?src=src\plugins\global%20plugin%20test%201.js), I tried to destroy the game using `game.destroy(true)` as the last line of the `create` method.
Doing so triggers an error stating that `Uncaught TypeError: this.plugins[i].destroy is not a function`.

By adding a `console.log(this.plugins)` before the loop in this method:
https://github.com/photonstorm/phaser/blob/master/src/plugins/PluginManager.js#L772-L782

I noticed that plugins is equal to `[{ key: 'RandomNamePlugin', plugin: RandomNamePlugin, start: true }]`.
There is no `destroy` method on this object since it's not the instance of the plugin.

Therefore, the example crashes when I try to destroy the game.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by Telokis** [comment]
I confirm it's working as intended. Thanks!
