### ISSUE TITLE
Camera shake broken for Tilemaps in WebGL since 3.7.1

### ISSUE THREAD

**Issue by kainage** [photonstorm/phaser#3669]
The following commit broke the camera shake effect when using tilemaps on WebGL

https://github.com/photonstorm/phaser/commit/1ce2311465b5e82bc0f3585b8e6dbf5b77401c3c

Can be reproduced by adding:

```
this.cameras.main.shake(2000)
```

to any of the labs using tilemaps.

This one for example: 
http://labs.phaser.io/edit.html?src=src\game%20objects\tilemap\dynamic\randomize%20tiles.js

Changing it back to canvas works fine.

Reverting the above commit makes it work again.

**Comment by photonstorm** [comment]
I've looked into this further and it only impacts dynamic tilemap layers. Static ones work fine with camera shake.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by kainage** [comment]
Camera shake works again 🎉 

Thanks @photonstorm
