### ISSUE TITLE
Keydown event behavior bug/question?

### ISSUE THREAD

**Issue by jdotrjs** [photonstorm/phaser#3670]
This example demonstrates the behavior I'm talking about: http://labs.phaser.io/edit.html?src=src\input\keyboard\keydown.js

Basically registering for keydown events will result in an event being fired on every tick of the game loop even if the key was not pressed more than once.  I don't know if that is expected behavior but based on the event I've seen a bunch of folks get tripped up by it thinking that the event would fire once on keydown.

**Comment by photonstorm** [comment]
The `keydown` event will fire as many times as the browser fires it, for as long as the key is held down. If you only want to get one event, use `input.keyboard.once('keydown_?)`, or listen for the key up event instead (which by its nature can only fire once), or use `Phaser.Input.Keyboard.JustDown` check.
