### ISSUE TITLE
Pixelart while moving it gets blurry

### ISSUE THREAD

**Issue by hasezoey** [photonstorm/phaser#3685]
I was trying with Phaser where i saw that this gets some kind of blurred when moving (ingame) 
Testet it in Canvas & WebGL both had the same result
then i tried it to setting `pixelArt` to false in the gameconfig and when i tried it then, it worked smooth,  but it seemd that it had activated some kind of antialiasing so it got washed-out but the moving was smooth 

Phaser 3.8
(Original) Tileset tiles 16x16 (no spaceing / margin)
(Extruded) Tileset tiles 16x15 (1px margin / 2px spaceing)
Map made with Tiled
Vivaldi & Chrome & Windows Edge
[Tileset Extruder](https://github.com/sporadic-labs/tile-extruder)
[Code Example / Project](https://github.com/hasezoey/phaser-tiled-test)
[Footage]( https://youtu.be/1p4BVFgA4wk) (not good visible, sorry)
([Original Question](https://stackoverflow.com/questions/50432202/weird-phaser-black-lines-and-blur-while-moving)) (posting here because it got `on hold` there)

**Comment by photonstorm** [comment]
You need to do two things: Set `pixelArt: true` in the game config to stop it from anti-aliasing the textures, and set `roundPixels = true` on all cameras in your game, to stop it from interpolating sprite positions during drawing. For more details please use the Phaser forum, as GitHub is for issues with the API and this is just a support request really.

**Comment by hasezoey** [comment]
Moved to http://www.html5gamedevs.com/topic/37816-pixelart-while-moving-it-gets-blurry/

[And i tried it, but it is still there](https://github.com/hasezoey/phaser-tiled-test/blob/5860415f12560415fe3b3695a2b34fe3623651f0/public/js/internals/main.js#L60-L62)
