### ISSUE TITLE
Giving an Arcade body to a tileSprite doesn't take the correct dimensions if static

### ISSUE THREAD

**Issue by fariazz** [photonstorm/phaser#3690]
When giving a non-static Arcade body to a tileSprite, the dimensions of the body will correspond to those of the tileSprite, so that works as expected:

```js
// non-static (size of physics body correctly  matches that of tileSprite)
  let platform1 = this.add.tileSprite(10, 100, 36 * 4, 30, 'block').setOrigin(0);
  this.physics.add.existing(platform1, false);﻿
```

However, if the Arcade body is set as static, the dimensions of the body don't match those of the tileSprite. Screenshot: https://www.screencast.com/t/nZZxbUKEm

```js
// static (size of the physics body doesn't match that of the tileSprite)
  let platform2 = this.add.tileSprite(10, 200, 36 * 4, 30, 'block').setOrigin(0);
  this.physics.add.existing(platform2, true);﻿
```

Full example:   https://github.com/fariazz/phaser-tilesprite-size-issue

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by fariazz** [comment]
Thanks for the quick fix @photonstorm ! That fixed it on my end.
