### ISSUE TITLE
With pixelArt: true, textures are sometimes inaccurate in WebGL but not Canvas.

### ISSUE THREAD

**Issue by siolfyr** [photonstorm/phaser#3698]
When using pixelArt: true, sometimes textures are drawn with pixels from the top being displayed at the bottom of the texture, and possibly also left/right as well (this only happens in WebGL, Canvas is fine).

I have examples of it happening in Phaser 3.8.0.  Press up to jump, and you will see it in the WebGL example:

http://phaser.octobeta.com/snow_380_webgl.html
http://phaser.octobeta.com/snow_380_canvas.html

Thanks so much for your time.

**Comment by photonstorm** [comment]
This is normal when the textures are not prepared properly, it's the bleeding from one edge to another. It can be solved by using a package like Texture Packer or Shoebox to prepare your atlases, and make sure you enable the frame border / pixel extruding feature (which is on by default.) You can find out the technical reasons behind it by searching for 'texture bleeding'.
