### ISSUE TITLE
Collision filter with mouse for matter physics

### ISSUE THREAD

**Issue by rimonmath** [photonstorm/phaser#3699]
I found two methods 
body.setCollisionCategory(cat1);
body.setCollidesWith([cat1, cat2]);
Using these two methods I can easily filter collision between two bodies. But I didn't find any example or documentation about how to do collision filter with mouse. I want that some bodies can be dragged with mouse and some bodies can't. Can you give an example?

**Comment by hexus** [comment]
Check out this example:

http://labs.phaser.io/edit.html?src=src\physics\matterjs\drag%20with%20pointer.js

**Comment by rimonmath** [comment]
This example contains only one body which is draggable. Can you add another body which is not draggable?

**Comment by photonstorm** [comment]
The easiest way is to just set a collision group in the constraint options:

http://labs.phaser.io/view.html?src=src\physics\matterjs\drag%20filter%20with%20pointer.js

Not sure this needs new constraint methods as you can pass it in easily enough (and for a constraint it's unlikely to change beyond creation either)

If you're going to use matter then it's well worth spending some time learning about how it handles collision groups and filters internally, which you can find in the matter.js docs.

**Comment by hexus** [comment]
Ah, brilliant! I didn't realise that was possible. :)

@rimonmath:

```js
this.matter.add.mouseSpring({ length: 1, stiffness: 0.6, collisionFilter: { group: canDrag } });
```

https://github.com/photonstorm/phaser3-examples/blob/73bc72df0a0aba50589e199400ba404cb47987c5/public/src/physics/matterjs/drag%20filter%20with%20pointer.js#L28-L46

**Comment by hexus** [comment]
No worries - @photonstorm made it for you! :)
