### ISSUE TITLE
Do not support multi-touch?

### ISSUE THREAD

**Issue by JetLua** [photonstorm/phaser#3701]
I want to simulate a gamepad.

![2018-05-24_235259](https://user-images.githubusercontent.com/6738986/40497005-bc14e2c8-5fad-11e8-8b09-52a7abdc44db.png)

**Comment by photonstorm** [comment]
Not yet supported, will be part of the Input Manager work we do shortly. Already on our internal road map, so keep an eye on the Change Log in future versions to see when it has been implemented. There is no fixed date for this.
