### ISSUE TITLE
Camera.centerToBounds() doesn't regard bounds offset

### ISSUE THREAD

**Issue by cyantree** [photonstorm/phaser#3706]
When calling `camera.centerToBounds()` it doesn't take the bounds offset into account. Therefore it produces unexpected results when camera bounds don't start at `0,0`.

Please see this example. The background should cover the whole canvas but doesn't:
https://codepen.io/anon/pen/ELqGqq

The fix for it could be:
```
    centerToBounds: function ()
    {
        if (this.useBounds)
        {
            this.scrollX = this._bounds.x + (this._bounds.width * 0.5) - (this.width * 0.5);
            this.scrollY = this._bounds.y + (this._bounds.height * 0.5) - (this.height * 0.5);
        }

        return this;
    },
```

Thanks for your great work on this lib!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
