### ISSUE TITLE
Scene shutdown does not clear the pipeline out of lights

### ISSUE THREAD

**Issue by samvieten** [photonstorm/phaser#3707]
Reproducable problem: If you got a scene (scene1), that implements light:
**Enable lights in the scene1:**
`this.lights.enable().setAmbientColor(0xffffff);`
**use a light in the scene1:**
`this.lights.addLight( x, y ).setColor(0xff5f0a).setIntensity(1);`

And then switch to a second scene via: `this.scene.start('scene2')`
The light is successfully cleared from the array of lights in the Manager. 
But a "ghostimage" remains in the new, started scene2 if: 
**Scene2**
1. scene2 has lights enabled. 
2. But scene2 got no own lights.

result: you see the lights from scene1 in scene2

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
