### ISSUE TITLE
How to add composite body to the world for matter physics.

### ISSUE THREAD

**Issue by rimonmath** [photonstorm/phaser#3709]
I have read the documentation of matter.js. We can add compound body as follows:

```js
var size = 150,
x = 400,
y = 300;

var partC = Bodies.circle(x, y, 30),
partD = Bodies.circle(x + size, y, 30),
partE = Bodies.circle(x + size, y + size, 30),
partF = Bodies.circle(x, y + size, 30);

var compoundBodyB = Body.create({
     parts: [partC, partD, partE, partF]
});

World.add(world, [compoundBodyA]);
```

How can I add this kind of compound body on phaser?

**Comment by hexus** [comment]
It's very similar in Phaser 3 at the moment, I haven't seen a Phaser-specific API that wraps it up.

This example creates a compound body for the player object:

http://labs.phaser.io/edit.html?src=src\game%20objects\tilemap\collision\matter%20platformer%20with%20wall%20jumping.js

**Comment by hexus** [comment]
I'm going to close this issue because it hasn't had a response in a couple of months. Hopefully the example makes it clear enough how to use MatterJS in Phaser 3.

**Comment by rimonmath** [comment]
Thanks for the example.
