### ISSUE TITLE
RenderTexture doesn't render properly on CANVAS mode

### ISSUE THREAD

**Issue by saqsun** [photonstorm/phaser#3710]
I am trying to make something like 9patch image and for that I am using RenderTexture. Everything works as expected on WEBGL mode but not on CANVAS mode

Here is the plugin link I created.
https://github.com/koreezgames/phaser3-ninepatch-plugin

![webgl](https://user-images.githubusercontent.com/1752099/40619351-cc035994-62a5-11e8-9610-d696fa83fc7a.png)
![canvas](https://user-images.githubusercontent.com/1752099/40619352-cc24bd0a-62a5-11e8-9a51-7fd2e0f53832.png)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by saqsun** [comment]
Thanks for responding my request so fast. Has tested and everything works like a charm!
