### ISSUE TITLE
To be able to change RenderTexture initial size

### ISSUE THREAD

**Issue by saqsun** [photonstorm/phaser#3711]
I would suggest for RenderTexture to have resize method.
```javascript
function create()
{
    var rt = this.make.renderTexture({ x: 0, y: 0, width: 800, height: 600 });
    rt.resize(200, 300);
}
```

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by saqsun** [comment]
It works!
