### ISSUE TITLE
In Arcade, collision between a sprite and an array of groups is not working

### ISSUE THREAD

**Issue by fariazz** [photonstorm/phaser#3714]
According to the [doc in Collider.js](https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/Collider.js#L21), it should be possible to declare a collider between a single sprite and an array of groups, however when trying this, the collision is not happening (and neither are overlap calls).

Example: https://github.com/fariazz/phaser-group-collision-issue

The gorilla in this example should stop the block from falling.

Code:

```js
let gameScene = new Phaser.Scene('Game');

gameScene.preload = function() {
  this.load.image('block', 'assets/images/block.png');
  this.load.image('gorilla', 'assets/images/gorilla3.png');
};

gameScene.create = function() {

  let gorilla = this.add.sprite(200, 300, 'gorilla');
  this.physics.add.existing(gorilla);
  gorilla.body.allowGravity = false;


  let block1 = this.add.sprite(200, 0, 'block');
  this.physics.add.existing(block1);

  let blocks = this.add.group();
  blocks.add(block1);

  // collision between a sprite and an array of groups
  // according to the doc, it should work: https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/Collider.js#L21
  this.physics.add.collider(gorilla, [blocks]);
};

let config = {
  type: Phaser.AUTO,
  width: 400,
  height: 400,
  scene: gameScene,
  physics: {
    default: 'arcade',
    arcade: {
      gravity: {
        y: 1000
      },
      debug: true
    }
  }
};

let game = new Phaser.Game(config);
```

**Comment by fariazz** [comment]
If you remove the array from my example, so this:

```js
this.physics.add.collider(gorilla, blocks);
```
instead of this:

```js
this.physics.add.collider(gorilla, [blocks]);
```

It does work as expected (the gorilla stops the block). According to the docs in the code, an array of groups (`Group`, not necessarily `PhysicsGroup`) should work as well, otherwise it's either a bug or the documentation needs fixing.

**Comment by photonstorm** [comment]
I know why this is happening, and how to resolve it, but I don't think I want to. By using a normal Groups you ignore all the benefits of the static / dynamic trees now built in. It's just a bad idea and I'd rather people get used to using PhysicsGroups instead. So I think I'll update the docs for this one.

**Comment by fariazz** [comment]
Thanks for your response @photonstorm ! 

Just to be sure I'm teaching this correctly, will colliders work when passing any of these?:

1- A Sprite that was physics-enabled after creation (with `this.physics.add.existing`)?
2- A single Group (as opposed to an array of Group which was my original question)

**Comment by photonstorm** [comment]
Yes. They also work with an array of PhysicsGroups too.

Plus they also work with a _single_ Group, but not an array of Groups.
