### ISSUE TITLE
How to do with 3d Rotation of Sprites

### ISSUE THREAD

**Issue by kanthi0802** [photonstorm/phaser#3716]
Hi,

Just curious to know if something like [this](https://jsfiddle.net/0gxtgytd/) is possible now in Phaser V3 ?

**Comment by photonstorm** [comment]
Using the Mesh game object, yes.

http://labs.phaser.io/index.html?dir=game%20objects/mesh/&q=

For all subsequent questions like this, please use either Slack, Discord or the forum. Issues are for reporting issues with the API.
