### ISSUE TITLE
depth sorting

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#3720]
Lets imagine that we have 2 containers, both have 2 sprites, so
Container1:
```
this.depth = 0
sprite1.depth = 1
sprite3.depth = 3
```
Container2:
```
this.depth = 0
sprite2.depth = 2
sprite4.depth = 4
```
so i need to show in back `sprite1`, than `sprite2` in front of it ,than ... `sprite4`, how can i do that?

I'm understanding that depths that I've gave to sprites are working locally in parent containers, is it possible to set something like absolute depth?

**Comment by photonstorm** [comment]
No, don’t use Containers if you want full control over depth sorting in this way.

**Comment by RollinSafary** [comment]
Okay thanks for answer)
