### ISSUE TITLE
setInteractive on Container

### ISSUE THREAD

**Issue by kanthi0802** [photonstorm/phaser#3722]
Issue with V3.9.0 . setInteractive() on Container disregards its position and dimensions.

**Comment by RollinSafary** [comment]
have you called `setSize  `on container before `setInteractive()`?

**Comment by kanthi0802** [comment]
@RollinSafary yes

**Comment by RollinSafary** [comment]
@kanthi0802, it seems you're right ) Click on container's body doesn't work on whole body
```
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#010101',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('buttonBG', 'assets/sprites/button-bg.png');
    this.load.image('buttonText', 'assets/sprites/button-text.png');
}

function create ()
{
    var bg = this.add.image(0, 0, 'buttonBG');
    var text = this.add.image(0, 0, 'buttonText');

    var bg2 = this.add.image(0, 80, 'buttonBG');
    var text2 = this.add.image(0, 80, 'buttonText');

    var container = this.add.container(400, 200, [ bg, text, bg2, text2 ]);

    container.setInteractive(new Phaser.Geom.Circle(0, 0, 60), Phaser.Geom.Circle.Contains);

    bg2.setInteractive();

    container.on('pointerover', function () {

        bg.setTint(0x44ff44);

    });

    container.on('pointerup', function () {
        bg.setTint(0x8e8e8e)
    })

    container.on('pointerout', function () {

        bg.clearTint();

    });

    bg2.on('pointerover', function () {

        this.setTint(0xff44ff);

    });

    bg2.on('pointerout', function () {

        this.clearTint();

    });

    //  Just to display the hit area, not actually needed to work
    var graphics = this.add.graphics();

    graphics.lineStyle(2, 0x00ffff, 1);

    graphics.strokeCircle(container.x, container.y, container.input.hitArea.radius);
}

```

**Comment by kanthi0802** [comment]
@RollinSafary That's exactly what i've mentioned. :) . We'll have to wait till V3.10 then

**Comment by photonstorm** [comment]
What exactly is the issue being reported here? because Container hit areas are working as intended in 3.9 and this won't be changing in 3.10. Please post some code demonstrating the problem.

**Comment by kanthi0802** [comment]
@photonstorm . Here is an [example](https://jsfiddle.net/aoucx1mt/17/). Just click on the ListView at the bottom of the demo. The clicks does not work on the entire container. They work in the empty area just above Container and also only on certain area of the container. Not the full container.

**Comment by photonstorm** [comment]
This is because the hit area shapes are _centered_ on the Container. So in your code, you create a hit area rectangle that is 360 x 640, but the center of that rectangle is the Container x/y, which is why clicks only "work" in the top-left of your list view, because all of your children are positioned as if the Container x/y is the top-left.

To solve it you can do this in your `measure` function:

```
this.input.hitArea.x += this.w / 2;
this.input.hitArea.y += this.h / 2;
```
