### ISSUE TITLE
Automatic update (runChildUpdate) for groups run to late/early for collision detection

### ISSUE THREAD

**Issue by nkholski** [photonstorm/phaser#3724]
If you have a pool with bullets like this:
```
   bullets = this.add.group({
        classType: Bullet,
        maxSize: 10,
        runChildUpdate: true
    });
    this.bullet = bullet.fire(x,y);
```
and check for collision in your Bullet class:
`this.scene.physics.world.collide(this, tilemaplayer, ()=> this.collided());`
it will never detect collision. After digging into this i found out that body.deltaY() (and body.deltaX() even if I haven't actually checked) is always 0 which cancels out the collision check. The position and prev coordinates is always equal which suggets that the update method is called to late.

If I set "runChildUpdate" to false and run an update manually in the scene update method it works like expected:
`this.bullet.update(time, delta)`

Tested with Phaser 3.9.

**Comment by nkholski** [comment]
The  updates conditioned by runChildUpdate is fired in preUpdate in Group.js. If it was done in the update-method the problem is probably solved.
Also, I changed the title from pools to groups because this should be an issue for all kind of groups.

**Comment by photonstorm** [comment]
I was considering refactoring the update flow for a while now, but have decided that it's just the way it works in v3. Therefore, there's no direct way to do this, so the only real solution is to set `Group.runChildUpdate = false` and then call `Group.getChildren()` and iterate that array during a Scene update handler.
