### ISSUE TITLE
Phaser Arcade Collision Issue.

### ISSUE THREAD

**Issue by gaojunming** [photonstorm/phaser#3725]
你好，我最近在phaser3中碰到一个物理穿透的问题，和phaser ce[https://github.com/photonstorm/phaser/issues/1940](https://github.com/photonstorm/phaser/issues/1940)的问题一模一样。
问题展示如下：
<img src="https://cloud.githubusercontent.com/assets/5163918/3930338/a86ac380-243f-11e4-95b5-572ef6338083.gif" alt="Collision bug" style="max-width:100%;">
这是phaser3的问题还是我自己的问题？要如何解决呢？

**Comment by photonstorm** [comment]
This is a side-effect of the fact Arcade Physics uses the projection method for separation. If you need a more stable simulation please use Matter.js instead.
