### ISSUE TITLE
Container loses rotation pivot when using camera.startFollow() in CANVAS mode.

### ISSUE THREAD

**Issue by samid737** [photonstorm/phaser#3728]
This issue is about:

* a bug in v3.9.0

Rotations seem to mismatch when following A container in CANVAS mode. It looks like the camera bounds should be taken into account in CANVAS mode, or the scrollX and scrollY (still investigating).  this does not occur in WEBGL mode.

[Expected behaviour](http://jsfiddle.net/0aztztxe/4/) (WEBGL mode).

[Actual behaviour](http://jsfiddle.net/0aztztxe/3/) (CANVAS mode).

[placing the container](http://jsfiddle.net/0aztztxe/5/) at the center (400, 300) reproduces expected behaviour.

Translations work fine both in [CANVAS](http://jsfiddle.net/0aztztxe/7/) and [WEBGL](http://jsfiddle.net/0aztztxe/9/) mode.

**Comment by alexeymolchan** [comment]
still exists in 3.10.1 in Canvas mode, Webgl works fine

**Comment by photonstorm** [comment]
It will exist for as long as this issue remains open. The issue being closed means it has been fixed. Please try and keep issue chatter to a minimum, thanks.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
