### ISSUE TITLE
Render texture - Scale / Rotate - draw add a bad line effect

### ISSUE THREAD

**Issue by faistoiplaisir** [photonstorm/phaser#3730]
Hi,

My problem is difficult to explain, so I setup an easy codepen to see the problem. A lot more easier.

Here: https://codepen.io/Zor/pen/ERKxye

Summary: When I render a sprite to a render texture, by scaling, or rotate it, there's an extra line rendered. There's some comment in the codepen example.

The picture I used is this one: https://image.ibb.co/dunf7d/bolt_128_cap.png

I setup 3 cases: 

- the first has no problem (and you can see that my picture doesn't have a problem).

- the 2nd rotate the texture before draw => a line effect appear on the left side. Note that the original doesn't have any pixel on the left side (the picture is transparent). The extra line you actually see come from the right of the picture.

- the 3rd case illustrate better because more visible: just a scale up of the texture. Same, on the left you can see the pixel column that come from the right of the texture.

When pixelArt is activated, the problem disapear.

**Comment by hexus** [comment]
It looks like this is due to wrapped sampling. The line your seeing on the left is from the semicircle on the right.

Try extruding (padding) your texture.

![](https://cdn.codeandweb.com/o/img/tp-documentation/extrude-640.png)

TexturePacker can automate this (search this page for "extrude").

https://www.codeandweb.com/texturepacker/documentation/texture-settings

**Comment by faistoiplaisir** [comment]
Ok, I'll check that. 

But, when you said "could be fixed", you mean "it will be fixed" or maybe / maybe not ?

**Comment by photonstorm** [comment]
This will need to be handled with the textures themselves. as the use of texture clamping only works with power of 2 sized textures, which means depending on the texture sometimes it'll work and sometimes it won't, which isn't very consistent. Better to fix it at the source.

Also, please see the master branch + change log for a huge update to what Render Textures can do now!
