### ISSUE TITLE
sprite setOrigin doesn't work on animation frames

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#3735]
Phaser v3.9.0 & Phaser v3.10.0-beta1 
`setOrigin `method doesn't work on animations
[jsFiddle](https://jsfiddle.net/RollinSafary/x5kfo4zp/4/)

**Comment by photonstorm** [comment]
The json you're using to test this has a custom anchor point defined in it, which overrides the `setOrigin`:

```
				{
					"filename": "diamond_0009",
					"frame": {
						"x": 744,
						"y": 2,
						"w": 37,
						"h": 60
					},
					"rotated": false,
					"trimmed": true,
					"spriteSourceSize": {
						"x": 14,
						"y": 2,
						"w": 37,
						"h": 60
					},
					"sourceSize": {
						"w": 64,
						"h": 64
					},
					"anchor": {
						"x": 0.5,
						"y": 1
					}
				}
```
So this is behaving as I'd expect. If you want to specify the origin yourself, the frame data should have no anchor property.

**Comment by RollinSafary** [comment]
thanks for answer)
