### ISSUE TITLE
text.addColor broke the letter spacing.

### ISSUE THREAD

**Issue by geoff001** [photonstorm/phaser#3737]
Hello,

I'm just a newbie here but I hope someone could help me with this problem. Please see my screenshot:

![addcolorissue](https://user-images.githubusercontent.com/40050308/41138641-3f02ea8c-6b15-11e8-88a1-fbebc9b8bdc8.PNG)

When I used the addColor method, that happens. I tried to remove the addColor in my text and the letter spacing in my text goes back to normal. This issue was hard to notice when you're using Arial Black font. In the screenshot attached, I'm using Japanese3017 font. You may use any font but to notice it, you should have a straight letter and semi-circular/circular letter beside each other like "I" and "O" or "1" and "0".

Thank you in advance and have a great day!

**Comment by photonstorm** [comment]
Thank you for taking the time to work on this and open your issue. However, this is a Phaser 2 issue (as `addColor` isn't available in Phaser 3), which is now maintained in the [Phaser CE GitHub repo](https://github.com/photonstorm/phaser-ce). If the issue still exists in Phaser CE then please submit your PR there and I'm sure the community will be only too happy to look at it.
