### ISSUE TITLE
Device.os.desktop bug

### ISSUE THREAD

**Issue by alexeymolchan** [photonstorm/phaser#3743]
somehow im getting sys.game.device.os.desktop = true on iOS safari

is it expected behaviour ?

**Comment by RollinSafary** [comment]
@alexeymolchan the concept that is device desktop or not is very relative. The `boolean `values that you can get from `sys.game.device.os,` can help you to check the case that is answer for you concept.
For example, we think that if device is desktop, it's mean that we need for mouse pointer only,
but computer with touch monitor will be exception from your desktop concept, and now we can connect to mobile devices a mouse, and in this case it will be exception from mobile concept.
So you need to use several values to check your concept validation

**Comment by alexeymolchan** [comment]
@RollinSafary thanks for the explanation
