### ISSUE TITLE
GeometryMask: Children of sprites in a container displays incorrectly outside the mask

### ISSUE THREAD

**Issue by oklar** [photonstorm/phaser#3746]
A reference to: [http://www.html5gamedevs.com/topic/38217-geometrymask-childrensprites-of-a-container-displayed-inside-a-zone/](http://www.html5gamedevs.com/topic/38217-geometrymask-childrensprites-of-a-container-displayed-inside-a-zone/)

Is seems like when the sprites are overlapping the second sprite is detracting on the first sprite from the above reference post. 

There's also a difference in the Phaser.Display.Masks.BitmapMask and Phaser.Display.Masks.GeometryMask.

Where the BitmapMask actually work as intended:
[https://jsfiddle.net/jdotrjs/59tc3gbu/4/](https://jsfiddle.net/jdotrjs/59tc3gbu/4/)

Whereas GeometryMask does not:
[https://jsfiddle.net/jdotrjs/59tc3gbu/](https://jsfiddle.net/jdotrjs/59tc3gbu/)

**Comment by orgertot** [comment]
I have this problem too ! :+1:

**Comment by jjalonso** [comment]
me too ! I was getting crazy

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
