### ISSUE TITLE
LoaderPlugin doesn't emit "filecomplete-image-key" events

### ISSUE THREAD

**Issue by NokFrt** [photonstorm/phaser#3751]
According to the following comment in phaser.js:

     * For example, if you have loaded an image with a key of `monster`, you can listen for it
     * using the following:
     *
     * ```javascript
     * this.load.on('filecomplete-image-monster', function (key, type, data) {
     *     // Your handler code
     * });

this should work but it does not: https://jsfiddle.net/NokFrt/uhnxt3pw/8/

**Comment by photonstorm** [comment]
The docs are wrong, it's an underscore, not a hyphen (i.e. `filecomplete_image_monster`), which works. However, I think it'd make more sense to be a hyphen, so I'll update the code instead.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
