### ISSUE TITLE
Camera deadzone

### ISSUE THREAD

**Issue by Razvan-Stafan** [photonstorm/phaser#3752]
Is there anything similar on Phaser3 to camera's deadzone that exists on phaser-ce ?

The example of deadzone in phaser-ce:
https://phaser.io/examples/v2/camera/deadzone

**Comment by photonstorm** [comment]
Nope.

**Comment by GregoireDucharme** [comment]
That would actually be pretty useful
+1

**Comment by Loxo** [comment]
@GregoireDucharme Indeed
@photonstorm Any way to implement it in a simplified manner with the current version?

**Comment by halilcakarr** [comment]
By the way **i don't if this is the right place to write this** but there a strange thing on deadzone example.

![image](https://user-images.githubusercontent.com/18047554/41581051-e50cf8d0-73a5-11e8-89c5-0fbc1fb6a10a.png)

On middle left corner u can leave area.

**Comment by GregoireDucharme** [comment]
I reckon that's not the correct place to write this 😂
But it's a normal behaviour, since you reach the end of the world you can get out of the deadzone and reach the border.

**Comment by photonstorm** [comment]
That's correct. The deadzone just defines the region within which the camera will not scroll. It's not a clamp on where a sprite is allowed to move.

**Comment by halilcakarr** [comment]
I see thanks for answers @GregoireDucharme and ofc @photonstorm 👍

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
