### ISSUE TITLE
Support tint on objects drawn to a Render Texture

### ISSUE THREAD

**Issue by LaP0573** [photonstorm/phaser#3758]
Hello,

I'm trying to display a 300x300 grid of pixels in a way that allows me to paint each pixel with a specific color depending on my needs.

Going this way causes massive FPS drops:

        for (let i = 0 ; i < 300 ; i++) {
            for (let j = 0 ; j < 300 ; j++) {
                factory.image(i, j, "pixel");
            }
        }

(factory being my scene's `this.add`, "pixel" being a 1x1 white pixel I saved as a .png and that I load in my scene)

In some other frameworks I used, draw calls are batched to limit them and allow this kind of stuff at virtually no performance cost, as all the images are on the same texture, so no texture swapping comes ruining performances inbetween each drawcall. My guess is that there's no batching there in Phaser, given the massive FPS drop I get.

Is there a batch drawing functionality somewhere in Phaser 3 that I could take advantage of, to allow me displaying 300x300 separate 1px images and use a .setTint() indifferently on each one ?

Thanks !

**Comment by photonstorm** [comment]
If there is no texture change the draw calls are already batched, although at 90,000 objects that’s still around 45 draw calls minimum (as the batch size is 4k before it flushes). Profile it to see exactly where the slow down is coming from.

**Comment by iamchristopher** [comment]
Could you not achieve this using a RenderTexture?

**Comment by photonstorm** [comment]
Pretty sure you're going to need a small change to RenderTexture for this to work, because it doesn't currently take on the tint of a drawn object to it.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
