### ISSUE TITLE
.setInteractive() has a bad/confusing return

### ISSUE THREAD

**Issue by t1gu1** [photonstorm/phaser#3759]
It could be nice if you could change the return of setInteractive() like the other methods to chain it all.

**E.G**:
**I can do:** object.setX(x).setY(y).setInteractive();
**I can't do:** object.setInteractive().setX(x).setY(y)

This is cause by the fact that the setInteractive() method doesn't return the same thing. (it's just confusing for nothing)

Thank for your works!
We makes something nice with your phaser engine.
If you want to test it :package:  -> [https://greatcoffeebreak.com/](https://greatcoffeebreak.com/)

Try to complete it haha. it's hard to know what to do but it's desired to be like that

**Comment by photonstorm** [comment]
That method is absolutely chainable: https://github.com/photonstorm/phaser/blob/master/src/gameobjects/GameObject.js#L356

**Comment by t1gu1** [comment]
I use typescript. Maybe it's in the typing file?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
