### ISSUE TITLE
setInteractive(SHAPE) doesn't seems work with an object in a container

### ISSUE THREAD

**Issue by t1gu1** [photonstorm/phaser#3760]
When I make someting like this:
object.setInteractive(new Rectangle(-120, -120, 300, 300), Rectangle.Contains)

and that --^ is set in a container. Sometime i feel like it doesn't works.
I have some weird felling about the set of shape.

Maybe just take a moment to check it. I'm not sure if i'm wrong.

In all, 
Thanks for your great power lazer works! haha

**Comment by photonstorm** [comment]
Runnable test case needed please.

**Comment by photonstorm** [comment]
Closing as this is a month old now and no test code was provided yet. If you do find time to make a test case please feel free to comment on this issue and I can re-open it. Cheers.
