### ISSUE TITLE
ParticleEmitter.startFollow target param should be of type Phaser.GameObjects.GameObject

### ISSUE THREAD

**Issue by DrevanTonder** [photonstorm/phaser#3764]
https://github.com/photonstorm/phaser/blob/16f61b402b8aa50b09a869c85a840eed363e1052/src/gameobjects/particles/ParticleEmitter.js#L1050

this should be `Phaser.GameObjects.GameObject`

Discovered this while using typescript.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
