### ISSUE TITLE
Font scaling (font become ugly)

### ISSUE THREAD

**Issue by t1gu1** [photonstorm/phaser#3768]
I discover that you should not scale a font cause it will appear hugly.
**You have to increment the font-size itself and not use scale to keep a nice font.**

It does the same thing **if you scale a container** that contain a font. (You have to make some reverse engineering like **downscale the scale of the font and change the font size with the ratio of your scaling**)

It could be nice if you can have a check on this. :)

Thanks and nice work!!

**Comment by photonstorm** [comment]
This is literally impossible to handle from within Phaser as it depends entirely on the font face being used, its original size and how far you scale it. There's no way to come up with something that would work with all fonts for all games.

Perhaps that may be some way to have all scale operations for a Text object routed through to a custom function that then increased the font size accordingly, but the rate at which scale values change vs. font sizes are so very different.

This feels like something you need to handle by using BitmapText, or your own Text object that monitors its scale and then adjusts its font size accordingly, which would be quite a bit of trial and error (and very font specific) but ultimately worth doing.

**Comment by photonstorm** [comment]
Thinking about this a bit more, maybe the trick is to use something similar to CSS breakpoints. So between certain scales, you use a specific font size, and so on. The trouble is that when you then change font size, you'd want to reduce the scale too! Which is a bit of a catch 22.
