### ISSUE TITLE
[Requirement] Could you please add P2.js into phaser.js?

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#3769]
out projects use p2.js so if it's supported by pharser.js that will be a big advantage to improve our integrating efficent.

**Comment by photonstorm** [comment]
I have thought about this, but it isn't something I'm willing to spend my own time on. If p2 wasn't abandoned then I'd have included it from the start, but no updates and no developer response for years now just makes it not worth the effort I'm afraid.

I feel v3 has a flexible enough structure that someone else could handle integrating it themselves quite cleanly, without needing to touch much of the internal code at all. I'd accept PRs for this (that passed our eslint tests) but there are simply too many other things to focus on right now that I can't entertain the thought of doing it myself, sorry.

**Comment by jcyuan** [comment]
@photonstorm understand! I'll try to integrate it myself. yes v3 is absolutely great, thanks for your effort.
