### ISSUE TITLE
Mask in containers uses global position and not local. Clarify in the docs or fix behavior

### ISSUE THREAD

**Issue by shadowofsoul** [photonstorm/phaser#3770]
Well, i struggled for a while why my mask wasn't working properly and in phaser labs example was actually working.

I supposed that masks used local position to define where start to show it, but i was wrong. Here is the code example modified from phaser labs:
```
    var config = {
    type: Phaser.CANVAS,
    parent: 'phaser-example',
    width: 640,
    height: 480,
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var checker;
var game = new Phaser.Game(config);

function drawStar (graphics, cx, cy, spikes, outerRadius, innerRadius, color, lineColor)
{
    var rot = Math.PI / 2 * 3;
    var x = cx;
    var y = cy;
    var step = Math.PI / spikes;

    graphics.save();
    graphics.lineStyle(4, lineColor, 1);
    graphics.fillStyle(color, 1);
    graphics.beginPath();

    graphics.strokeRect(0,0,100,100);
    graphics.closePath();
    graphics.fillPath();
    graphics.restore();
}

function preload() {

    this.load.image('swirl', 'assets/pics/color-wheel-swirl.png');
    this.load.image('checker', 'assets/pics/checker.png');
}

function create() {

    var shape = game.scene.scenes[0].make.graphics({ lineStyle: { width: 2, color: 0xaa0000 }, fillStyle: { color: 0x0000aa } });
    var containerShape = game.scene.scenes[0].add.container(100,100);


    var swirl = game.scene.scenes[0].make.sprite({
        x: game.config.width / 2, 
        y: game.config.height / 2, 
        key: 'swirl',
        add: true
    });
    containerShape.add(swirl);

    /*shape.x = game.config.width / 2;
    shape.y = game.config.height / 2;*/

    shape.fillRectShape(new Phaser.Geom.Rectangle(0,0,100,100));

    containerShape.mask = new Phaser.Display.Masks.GeometryMask(game.scene.scenes[0], shape);

    

}

var t = 0.0;
function update()
{
    //checker.x += Math.sin(t) * 1;
    t += 0.01;
}
```

as you see, even if container is placed at an offset, the mask is placed at the global position of `0,0`. the only thing that can modify mas position, is by `shape` position or at the `fillRectShape` drawing position.

I don't mind that this is the default behavior (even if i don't agree) but at least a warning or clarification on the docs could save some hours for others in the same situation.

Thanks.

**Comment by photonstorm** [comment]
Masks are definitely positioned in global space because they're non-exclusive. I will see if I can find time to create an example showing what I mean.

Also, why, why this?! : `game.scene.scenes[0]...` it makes me so sad :( and reinforces my belief that I absolutely must remove all `game` level properties in a coming release, so it's impossible to do things like this in future.

**Comment by shadowofsoul** [comment]
@photonstorm found the `getAt()` function at the scene object, my bad.

**Comment by photonstorm** [comment]
`this` absolutely refers to the current Scene within any Scene method, which is why `this.load` works in your `preload` function. The `create` function is run in the exact same scope.

**Comment by shadowofsoul** [comment]
Yes, you are right, i messed up my conception of the scope with the structure i built with webpack (forgot i was calling a member function inside the .`create`, `preload` etc.. )

**Comment by photonstorm** [comment]
Back to the original point, I need to double-check the code (as I didn't write it) but I'm 99% sure that multiple game objects can share a single mask, which is why they're positioned globally.

**Comment by shadowofsoul** [comment]
Good to know, wasn't aware of that. then of course it makes sense they are globally positioned. just that in my project context where everything was black and i had an offset in my container, it took me a while to have the idea that this was the problem and not something else.

**Comment by photonstorm** [comment]
Ok, sorry it took a while, but I was right and made a test tonight: multiple Game Objects can all share the exact same mask, which is why they're positioned in global space, not local. I'll update the mask jsdocs now to reflect this.
