### ISSUE TITLE
Phaser.GameObjects.Blitter.Bob.setFrame() does not work

### ISSUE THREAD

**Issue by NokFrt** [photonstorm/phaser#3774]
I tried to set bob's frame via bob.setFrame("frame_from_bobs_texture") and it doesn't work and the bob had still the same frame.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
