### ISSUE TITLE
this.cameras.main undefined on scene mid-transition

### ISSUE THREAD

**Issue by jjalonso** [photonstorm/phaser#3776]
Hi, I found an issue (at least in 3.10.1) where this.cameras.main is undefined when I trigger a transition of scenes. 

The update method is called once when i think that the camera is already destroyed.

I wrote this small codepen for that:
https://codepen.io/jjalonso/pen/vrdwoW

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by jjalonso** [comment]
Thanks.
