### ISSUE TITLE
Arcade Physics world.collide() via scene update() fails to separate sprites

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#3777]
<https://codepen.io/samme/pen/gKeMgd>

`add.collider()` with the same arguments works as expected.

`world.collide()` is separating correctly but the body's new position isn't applied back to the sprite. Calling `sprite.body.postUpdate()` after `world.collide()` fixes the problem.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
