### ISSUE TITLE
Misplaced rotated tiles in scaled tilemap layers

### ISSUE THREAD

**Issue by nkholski** [photonstorm/phaser#3778]
As the title says, rotated tiles get misplaced on scaled tilemap layers. Example below with original (scale=1) compared to the same scaled by 2.1.

![original](https://user-images.githubusercontent.com/5206576/41704243-02b066ba-7536-11e8-8956-564c45160699.png)
![scaled](https://user-images.githubusercontent.com/5206576/41704244-02caf8d6-7536-11e8-951a-18e0b6e3cf14.png)

**Comment by photonstorm** [comment]
Do you have a sample map I could use to test this with please? Also, are you scaling the layer, or zooming the camera?

**Comment by nkholski** [comment]
I've got multiple issues and it's both a little bit hard to explain and probably tedious to reproduce (not only with rotated tiles). The issues remain in 3.11.

My project mixes Graphics, Sprites and a two-layer tilemap. I've tried different approaches: setting scale of individual GameObjects, a scaled container with everything inside and setting zoom of the main camera or an extra camera.  

The example above is scaled layers. If I instead scale a container with everything inside the tilemap layers are unaffected, Sprites are duplicated (both original and one scaled as expected) and Graphics work as expected. If I set a higher zoom of the camera one tilemap layer is scaled as expected but positioned in the top left corner with most of it outside the screen while the other layer, graphics and sprites are not zoomed but probably positioned correctly if it were scaled.

Would you accept the full source code on from the project I'm working on? All zooming or scaling are done in the create method and can be toggled by uncommenting lines to try the different approaches. The issues are immediately visible when the game boots. If you need a minimal example code it might take a while until I have the time to do that.

**Comment by photonstorm** [comment]
As long as I don't have to set-up any kind of build tools or anything, a zip would be fine.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
