### ISSUE TITLE
Bug: isDown state won't update when mouse released outside of game canvas

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3779]
[Here](https://codepen.io/rexrainbow/pen/wXmXJq?editors=0010) is a sample code of this issue (v3.10.1)
1. Press left-key of mouse inside  game canvas, 
1. Drag outside game canvas,
1. Release left-key outside game canvas,
1. Move cursor back to game canvas.

No mouse key pressed after last step, but the `scene.input.activePointer.isDown` is still `true`.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
