### ISSUE TITLE
Input.Keyboard.JustDown skips one event if keyboard input was disabled and reenabled

### ISSUE THREAD

**Issue by Aivean** [photonstorm/phaser#3784]
Here is a simple code snippet to illustrate the problem (taken from here: http://labs.phaser.io/edit.html?src=src/input/keyboard/just%20down.js):

```javascript
if (Phaser.Input.Keyboard.JustDown(spacebar)) 
    {
        var bullet = bullets.get();

        if (bullet)
        {
            bullet.fire(ship.x, ship.y);
            this.input.keyboard.enabled = false;
            setTimeout(()=>{
                this.input.keyboard.enabled = true;
            }, 1000)
        }
    }
```
`input.keyboard` is disabled immediately after `JustDown` is fired and reenabled after one second delay.  However, if you wait for input to be reenabled (e.g. 5+ seconds) and try pressing `space` again, `JustDown` won't fire.  Basically, with this setup `JustDown` fires every other time, regardless of the delay between key presses.

Expected behavior: 
`JustDown` should fire every time corresponding key is pressed (if keyboard input is enabled).

This issue is reproducible in Phaser 3.9.0 and 3.10.1.  (was working correctly in 3.8.0).

**Comment by photonstorm** [comment]
Why on earth would anyone disable the keyboard handler in this way though? It seems utterly pointless.

**Comment by Aivean** [comment]
@photonstorm, well, it worked until it stopped.
What is the correct way to globally disable keyboard input then?

**Comment by photonstorm** [comment]
Forgot to update this issue, but it was resolved when the input system was rewritten recently to avoid using a queue and instead handle native dom events immediately. I've tested it just now and it's fine in 3.20 (and likely much earlier)
