### ISSUE TITLE
Displayed body does not get scaled in sync with physical body with matter

### ISSUE THREAD

**Issue by bergben** [photonstorm/phaser#3785]
Hey!

I have noticed a weird behavior when using `.setScale` with the matter physics engine. 
It seems like the displayed body works as intended, but the physical body does not get scaled accordingly. 

I've create an example that reproduces this issue: https://codepen.io/anon/pen/ERpxGV 
Just click on the logo and you will see that the displayed body gets bigger, whilst the physical body gets smaller.

I've been trying to find a way to scale both those bodies synchronously but couldn't find a solution. I don't think this works as intended? 

Thanks for all your work!

**Comment by photonstorm** [comment]
You can scale the body once and it'll remain in sync for the first call:

```
    //  By default it will create a rectangular body the size of the texture
    var rect = this.matter.add.image(200, 50, 'blue');

    //  Just make the body move around and bounce
    rect.setVelocity(3, 1);
    rect.setAngularVelocity(0.01);
    rect.setBounce(1);
    rect.setFriction(0, 0, 0);

    rect.setInteractive();

    rect.once('pointerup', function () {

        rect.setScale(2);

    });
```

The above works fine, no matter which scale value you give it.

However, Matter.js does not scale in the same way as Phaser. Body scaling in Matter has no notion at all of a base scale value. When you create the body and then scale it, the new size becomes the base size. For example, say you had a body that was 100x100. You scale it by 2. The body is now 200x200 as expected, but this is now the base size. Scale it by 1 and nothing will happen, it'll remain at 200x200. Scale it by 2 again and it will become 400x400. Scale that by 2 again and it'll become 800x800 and so on. It's quite confusing, but it's how Matter works internally and there's nothing we can really do to change it.

**Comment by bergben** [comment]
Hey @photonstorm,

thank you so much for the explanation. Thanks to your explanation I was able to solve the problem by manually tracking the scaling factor and just resetting the matterJS scaling factor to 1 every time before rescaling. 
The code is available here: https://codepen.io/anon/pen/mjabqN 

It's quite straight forward to be honest but I am sure this could help a lot of people, especially anyone building something like a .io game where scaling is oftentimes key! 

Thanks for your time, I think this counts as a solution to this issue!

**Comment by glantucan** [comment]
Hi.
It seems 'matterImage.scale = 2` does scale the image but not the body. Using 'matterImage.setScale(2,2)` works fine though.
I'm posting it here instead of creating a new issue cause it seems related.
