### ISSUE TITLE
how to defined png sequence frame position?

### ISSUE THREAD

**Issue by txiaocao** [photonstorm/phaser#3786]
version
Phaser3
￼
I have some png frame, like these
![image](https://user-images.githubusercontent.com/3929991/41888983-bb93b77e-793a-11e8-846a-29b6d5fd1682.png)

and some frame data is frame position and delay time
```json
"0": {
    "type": "png",
    "value": require("./0.png"),
    "origin": {
      "x": "41",
      "y": " 77"
    },
    "delay": 150,
    "_hash": "44ac7eaf0c85d0198d4e9917b8e56679d1b0875c7eca7c96d2a916e488e3601e"
  },
  "1": {
    "type": "png",
    "value": require("./1.png"),
    "origin": {
      "x": "41",
      "y": " 77"
    },
    "delay": 150,
    "_hash": "5dc34922965f5d7008aae5219e319a66640a7d28bc2e76c2868e02ac5718300c"
  },
  "2": {
    "type": "png",
    "value": require("./2.png"),
    "origin": {
      "x": "41",
      "y": " 77"
    },
    "delay": 150,
    "_hash": "c100e67eafbb5230cab5cfec77aa126b59dc8c0ce9e3a47a53e2cb04aff09010"
  },

```

load frame
```js
const helloAnims = {
      key: "hello",
      frames: [],
      frameRate: 8,
      repeat: -1
    }
    for (const helloKey in hello) {
      const helloItem = hello[helloKey]
      helloAnims.frames.push({
        key: `hello${helloKey}`,
        duration: helloItem.delay,
      })
    }
    this.anims.create(helloAnims)

```

the png has an position and the sprite has position…the real position is 
left to right: -x --- 0 --- +x
top to bottom: -y --- 0 --- +y

the position is not fixed
￼
![image](https://user-images.githubusercontent.com/3929991/41888987-c05b5ce4-793a-11e8-8392-a16238bd1cc7.png)

**Comment by photonstorm** [comment]
If you need per-frame origins, which I _think_ is what this issue is about, then you should use a texture atlas that supports it, such as Texture Packer. With that you can define the pivot point of every frame, and Phaser will use it when rendering, even in animations.

**Comment by txiaocao** [comment]
Very thanks for your reply, I'm going to looking them carefully frame, animations, texture api...
Because of my data is derived, the related material data is very big and complicated.
I'm trying to use the code tools from the data file parsing and code generation, and use organized by webpack slice the chunk of these resources manage, and merger
🧐
