### ISSUE TITLE
container addAt doesnt accept array as doc says

### ISSUE THREAD

**Issue by jjalonso** [photonstorm/phaser#3788]
I saw that container addAt([gameObject1, gameObject2], 2) is not allowed as the doc say:
https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Container.html#addAt__anchor

it gives:

Container.js:362 Uncaught TypeError: Cannot read property 'once' of undefined

**Comment by samme** [comment]
AddAt() is working on an undefined entry.

![Trace](https://user-images.githubusercontent.com/435681/41941803-f8da104e-7951-11e8-9ca2-f9bac57cba71.png)

**Comment by jjalonso** [comment]
What you mean?
 sorry

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
