### ISSUE TITLE
tileSprite getBounds() return image bounds instead of the tileSprite bounds

### ISSUE THREAD

**Issue by jjalonso** [photonstorm/phaser#3789]
Not sure if is a bug.

I have a image called box-cell of 100x100 pixels. but when I use tilesprite to repeat it.
ex: this.scene.add.tileSprite(0, 0, 400, 400, 'box-cell');

getBounds() always return a rectangle 100x100 instead of the 400x400

Is that expected or is a bug?

**Comment by samme** [comment]
`displayWidth` and `displayHeight` have the same values (also unexpected).

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
