### ISSUE TITLE
puzzled default config value for "input.activePointers"

### ISSUE THREAD

**Issue by Sunqinying** [photonstorm/phaser#3793]
The default config value for "input.activePointers" is not very clear to someone new to phaser3,
if we use default value, there would no response for mobile touch event.

default config for activePointers is 1
https://github.com/photonstorm/phaser/blob/ada46566011efd6a761502d64905e186a84de2fb/src/boot/Config.js#L259

default there is two creates 2 pointer objects
https://github.com/photonstorm/phaser/blob/0329b8dfb74a0e83a5f1571e4138b76952be94aa/src/input/InputManager.js#L692

if we do not set ``input.activePointers = 2`` in config,  it will ignore the event, the default value is puzzled
https://github.com/photonstorm/phaser/blob/0329b8dfb74a0e83a5f1571e4138b76952be94aa/src/input/InputManager.js#L608

**Comment by photonstorm** [comment]
2 pointers are created by default. The mouse pointer, which is pointer 0 and is for desktop use only, and one touch pointer (as long as `input.touch = true`, which it is by default).

This is what the `activePointers` config property refers to - the number of touch pointers to create. 

If you use the default configuration then touch and moue input will work automatically, allowing 1 single finger input. Change the `activePointers` value to add more from the config, or use `addPointer` to add them within the game code. This is only needed if you require _more_ than 1 touch input.

**Comment by Sunqinying** [comment]
If I use a default config, It will not work for touch event, becase ``for (var i = 1; i < this.pointersTotal; i++) ``, pointersTotal is default to 1, and will not trigger touchstart for second default pointer

**Comment by photonstorm** [comment]
Yes it will, because 2 pointers are created by default. Actually try it on a device maybe?

**Comment by photonstorm** [comment]
https://github.com/photonstorm/phaser/blob/master/src/input/InputManager.js#L224

**Comment by Sunqinying** [comment]
Thanks for your reply, I find I use a older version of phaser, and did not set ``pointersTotal  = 2``
