### ISSUE TITLE
Issue about createStaticLayer - We just can add only one tileset into a layer?

### ISSUE THREAD

**Issue by thanh-taro** [photonstorm/phaser#3794]
I see in the docs: https://photonstorm.github.io/phaser3-docs/Phaser.Tilemaps.Tilemap.html#createStaticLayer

```createStaticLayer(layerID, tileset, x, y)```
That means we can add only one tileset into a layer when create it?

**Comment by photonstorm** [comment]
Yes.

**Comment by thanh-taro** [comment]
In Tiled, I can add many tileset in to one layer. I wonder that how can I use Phaser 3 in this case?

**Comment by photonstorm** [comment]
You can't yet.

**Comment by photonstorm** [comment]
StaticLayer really needs a bit of an overhaul. It's massively inefficient for large maps and is limited to a single texture frame. However, it works and works fast, so I'm flagging this as a long-term feature request.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by thanh-taro** [comment]
Yes. I see it in release notes. Thank you so much. ❤️
