### ISSUE TITLE
Documentation inaccuracy: removeTileAt, removeTileAtWorldXY

### ISSUE THREAD

**Issue by tarsupin** [photonstorm/phaser#3795]
Simple documentation error, easily remedied:

https://photonstorm.github.io/phaser3-docs/Phaser.Tilemaps.Tilemap.html#removeTileAt__anchor

The first parameter says "tile", when in fact it makes no sense to declare the tile. The actual code is correct: removeTileAt: function (tileX, tileY, replaceWithNull, recalculateFaces, layer)

According to the documentation:
removeTileAt(tile, tileX, tileY [, replaceWithNull] [, recalculateFaces] [, layer])

The same error applies to 'removeTileAtWorldXY' as well.

**Comment by photonstorm** [comment]
PR?

**Comment by tarsupin** [comment]
Just submitted PR.

**Comment by hexus** [comment]
Merged (#3802). Thanks. :+1:
