### ISSUE TITLE
Discrepancy for `Mask` mixin in the `Container` game object code and documentation

### ISSUE THREAD

**Issue by zilbuz** [photonstorm/phaser#3797]
There is a discrepancy between the `Container` game object code and its documentation: the documentation states that the class extends `Mask`, but `Mask` isn't present in the `Mixins` array.

Documentation: https://github.com/photonstorm/phaser/blob/master/src/gameobjects/container/Container.js#L63
Mixins array: https://github.com/photonstorm/phaser/blob/master/src/gameobjects/container/Container.js#L77-L86

I can make a PR to fix the issue, but should I remove `Mask` from the documentation or add it to the mixins?

**Comment by photonstorm** [comment]
I was in there anyway so just added it directly. Cheers for the report.
