### ISSUE TITLE
BitmapText setOrigin() issues if different from 0,0

### ISSUE THREAD

**Issue by SBCGames** [photonstorm/phaser#3799]
Hi, if origin for BitmapText is different from 0,0 it brings unexpected results. Here is test code I used for explanation / images below:
``` javascript
            let t = this.add.bitmapText(0, 0, "BoardFont", "12-21", 72);
            t.setOrigin(0.5);

            let render = this.add.graphics({ x: 0, y: 0 });

            render.lineStyle(1, 0xff0000);
            render.strokeRect(t.x - 1, t.y - 1, 3, 3);

            let bounds = t.getTextBounds();
            console.log(bounds.global.width, bounds.global.height);
            render.strokeRect(bounds.global.x - t.displayOriginX, bounds.global.y - t.displayOriginY, bounds.global.width, bounds.global.height);
```
Here is image with results with current code:
![before](https://user-images.githubusercontent.com/8962889/42087451-81e1e060-7b96-11e8-9a54-2447bcd5b361.jpg)
 Red dot is BitmapText position, red rectangle is calculated size of bounds.
 Problem is, that bounds are calculated tight - without any character offsets, etc. But when rendering, these are taken back into account. On image on right is printing of only one character "-". It is printed with so big offset, that it looks like underscore. Also notece, its y offset is different when printed individually and when printed in text "12-21". 
 Origin 0,0 is in fact correct. Characters in font definition have offsets, but bounds are tight. This is reason why dot position is out of bounds rectangle.
 Origin 1,1 is not correct.

 If I make a few changes into GetBitmapTextSize(), then I get these results:
![after](https://user-images.githubusercontent.com/8962889/42087727-59b205f6-7b97-11e8-9109-7fb06565b6e6.jpg)

I am sacrificing tight bounds for correct origin. Height and width of text is based on font including its offsets / advances. Printing single "-" or as part of text now works (see its y position relative to center)

 Here are changes I made in GetBitmapTextSize() - changes are marked with ***** and original code is commented:
``` javascript
        glyphW = glyph.width;
        glyphH = glyph.height;

        x = xAdvance; // indexCount + glyph.xOffset + xAdvance;        // ***** 1
        y = yAdvance; // glyph.yOffset + yAdvance;                     // ***** 2

        if (lastGlyph !== null)
        {
            var kerningOffset = glyph.kerning[lastCharCode];
            x += (kerningOffset !== undefined) ? kerningOffset : 0;
        }

        if (bx > x)
        {
            bx = x;
        }

        if (by > y)
        {
            by = y;
        }

        var gw = x + glyph.xAdvance; // x + glyphW - bx;    // ***** 3
        var gh = y + lineHeight;     // y + glyphH - by;    // ***** 4
```

 There is one more thing I noticed in this method as well as in rendering methods like batchBitmapText() and others. It is use of parameter indexCount in line "***** 1". This parameter should not be there in my opinion. It makes additinal spacing between characters, while spacing should be controlled with letterSpacing parametr. If it is removed, it has to be removed also from rendering routines.

**Comment by photonstorm** [comment]
Thanks for this. I agree with the change. I'm redoing all the rendering methods at the moment, so will make this change to them as I do that.

**Comment by SBCGames** [comment]
Thanks! Any chance to add text alignment as in Phaser 2? Like "left" / "center" / "right"? It was very convenient and handy. For single line text it is not so important. But for multiline text it allows you for example to align values in table to right.
 I think in GetBitmapTextSize(), width of line is more or less calculated already now.

**Comment by photonstorm** [comment]
Ok, all of these changes are now in the master branch and I added text alignment as well :)
