### ISSUE TITLE
Tiles using a frame with 50% transparency rendering as a solid colour

### ISSUE THREAD

**Issue by Upperfoot** [photonstorm/phaser#3801]
I've been trying to render tiles with 50% transparency so I can simulate shadows but for some reason, it seems to render as a solid colour; Has anyone had an issue like this before?

Here is an example image

![Example](https://i.imgur.com/0rREDtB.png)

The top of the image is the source image with a partially transparent area to simulate shadows, the bottom of the image is it rendered and the blue background is the background set in the game config when I initialise.

As you can see the colour of the shadow is showing as a solid colour, and doesn't take into account the alpha channel.

Tested On: 

Chrome 67.0.3396.99 - Windows 10 (64 bit) - Nvidia 1050ti
Edge 42.17134.1.0 - Windows 10 (64 bit) - Nvidia 1050ti
@16patsle - Chrome 67.0.3396.87 - macOS High Sierra - Intel Iris Graphics 6100

**Comment by photonstorm** [comment]
Upload the actual png here so someone else can test it.

**Comment by Upperfoot** [comment]
@photonstorm thanks Rich here is the tileset ![Tileset](https://transfer.sh/bKdVE/pokemon.png)

And the JSON export of the map https://transfer.sh/12L9DK/dungeon.json

**Comment by photonstorm** [comment]
Which tile in the set is the one with transparency in?

**Comment by Upperfoot** [comment]
@photonstorm Sorry out having a pint and dont have my laptop but its this one if you can make out the index.

![Pinpoint](https://i.imgur.com/UZIYiJX.jpg)

**Comment by samid737** [comment]
Example : [v3.10.1](http://jsfiddle.net/kdv739fm/1/)

@Upperfoot  Which version are you working on?

**Comment by Upperfoot** [comment]
Latest master as of speaking, Ill look into it a bit further as I might be doing something wrong, I might be overlaying the same tiles multiple times, ill update this issue if I find anything.

**Comment by Upperfoot** [comment]
False alarm, double checked my code and I had duplicate tile layers which created the effect of it looking like a solid colour, sorry guys!
