### ISSUE TITLE
Uncaught TypeError: Cannot read property 'queueDepthSort' of undefined

### ISSUE THREAD

**Issue by bt-zz** [photonstorm/phaser#3805]
![image](https://user-images.githubusercontent.com/4394024/42163556-a3d70122-7e35-11e8-93ae-50bff81cfd3e.png)

used version: 3.10.1

**Comment by photonstorm** [comment]
And the code that caused this is .... ?

**Comment by photonstorm** [comment]
No example provided so closing this issue.

**Comment by raphaklaus** [comment]
I've got this error when I've instantiated a `Phaser.GameObjects.Sprite` class inside a `Phaser.Scene` direct in the constructor. It meant to be done inside `create` method.

If you're playing with TypeScript, don't forget to mark the property with the `!` (bang) operator, otherwise you will get the following error: `Property 'YOUR PROPERTY' has no initializer and is not definitely assigned in the constructor.`

Cheers

**Comment by bpkennedy** [comment]
I also saw this error when creating a class that inherited from a base class, and the one inheriting was redefining scene like:

```
// GameScene.js
import Goon from '../sprites/Goon';
class GameScene extends Phaser.Scene {
  constructor(test) {
    super({
      key: 'GameScene'
    });
    this.cursors;
    this.goon;
  }

  preload() {
    this.goon = new Goon({
      scene: this,
      x: this.sys.game.config.width / 2,
      y: this.sys.game.config.height / 2,
      key: 'person'
    });
  }
 ....etc...

// Goon.js
import Enemy from './Enemy.js';
export default class Goon extends Enemy {
  constructor(config) {
    super(config);
    config.scene = scene; // <--- DO NOT DO THIS
    this.body.setVelocity(0, 0).setBounce(0.2).setCollideWorldBounds(true);
  }
  preload() {}
  create() {}
  update() {}
  destroy() {}
}

// Enemy.js
export default class Enemy extends Phaser.GameObjects.Sprite {
  constructor(config) {
    super(config.scene, config.x, config.y, config.key);
    config.scene.physics.world.enable(this);
    config.scene.add.existing(this);
    this.body.setVelocity(0, 0).setBounce(0.2).setCollideWorldBounds(true);
  }
}
```

**Comment by Tyrone2333** [comment]
@bpkennedy I have encountered the same problem as you did when extend the class extends Phaser.GameObjects.Sprite
