### ISSUE TITLE
Plan to support mouse wheel event in Phaser 3

### ISSUE THREAD

**Issue by zilbuz** [photonstorm/phaser#3806]
Is there a plan to support mouse wheel events in Phaser 3?

I need to react to a mouse wheel event on a gameobject, and I didn't find a way 
to do it in Phaser like you can already do for 'pointerdown' or 'pointerup' 
event.

I saw an attempt to support the mouse wheel event in a branch of @jdotrjs: https://github.com/jdotrjs/phaser/tree/jdotrjs/hack-in-mousewheel

What do you think of this implementation? Should it be considered for merging in 
the main repository?

**Comment by jdotrjs** [comment]
I just spoke briefly with Rich about this and the tl;dr is that there aren't plans to support it in the immediate future but he would be happy to consider a PR that followed the current input management structure.

The change I have in place is ... probably approaching okay but I need to actually sit down and decide if there is a better model (i.e. something closer to touch start/stop). I'm happy to take PRs on my branch but before any real development there probably needs a real design in place on how scroll events will be surfaced/cleared on the pointer object.

**Comment by photonstorm** [comment]
Just to say that this feature landed in version 3.18.0!
