### ISSUE TITLE
Weird mask behavior on WebGL with bordered graphics objects

### ISSUE THREAD

**Issue by zilbuz** [photonstorm/phaser#3807]
When using a mask on a graphics object with a border, the webgl version doesn't work as expected. The following example illustrate the problem: 

![test_masks](https://user-images.githubusercontent.com/434964/42232196-fb3f80e8-7eed-11e8-8111-0e58ab362073.png)

<details>
 <summary>index.html</summary>

```html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Test masks</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/phaser@3.10.1/dist/phaser.min.js"></script>
</head>

<body>
    <h2>Canvas:</h2>
    <canvas id="canvas_game"></canvas>
    <h2>Webgl:</h2>
    <canvas id="webgl_game"></canvas>
    
    <script>
            function create_test() {
                var square1 = this.add.graphics({
                    fillStyle: {
                        color: 0xff0000,
                        alpha: 0.5
                    },
                    lineStyle: {
                        color: 0xff0000,
                        alpha: 1,
                        width: 10
                    }
                });
                square1.fillRect(50, 50, 100, 100);
                square1.strokeRect(50, 50, 100, 100);

                var mask1 = this.add.graphics({});
                mask1.fillRect(80, 25, 40, 150);

                var square2 = this.add.graphics({
                    fillStyle: {
                        color: 0xff0000,
                        alpha: 0.5
                    },
                    lineStyle: {
                        color: 0xff0000,
                        alpha: 1,
                        width: 10
                    }
                });
                square2.fillRect(200, 50, 100, 100);
                square2.strokeRect(200, 50, 100, 100);

                var mask2 = this.make.graphics({});
                mask2.fillRect(230, 25, 40, 150);
                square2.mask = mask2.createGeometryMask();
            }

            var config1 = {
                type: Phaser.CANVAS,
                width: 350,
                height: 200,
                backgroundColor: '#2d2d2d',
                canvas: $('#canvas_game').get(0),
                scene: {
                    create: create_test,
                }
            };
            var game1 = new Phaser.Game(config1);
                
            var config2 = {
                type: Phaser.WEBGL,
                width: 350,
                height: 200,
                backgroundColor: '#2d2d2d',
                canvas: $('#webgl_game').get(0),
                scene: {
                    create: create_test,
                }
            };
            var game2 = new Phaser.Game(config2);
        </script>
</body>

</html>
```
</details>
<br>

It seems that the problem comes from this line: https://github.com/photonstorm/phaser/blob/master/src/display/mask/GeometryMask.js#L82 where the operation on the stencil is marked as `INVERT`. If I change it to `KEEP`, the mask has the same behavior in webgl and canvas. I think the invert parameter flips the status of the stencil when drawing the borders of the object.

Is there a reason why `INVERT` was chosen instead of `KEEP`? Should I submit a pull request to change it or is there something I should test with this modification before submitting something?

**Comment by photonstorm** [comment]
Could probably do with creating a bunch of mask tests in the labs, just to test how it works against various Game Objects, then we'd know what repercussions this change would have - if any. I'll see about creating some when I get a chance this week. I still think it should be `KEEP` though.

**Comment by photonstorm** [comment]
I've made a bunch of tests and I'm happy with changing this to `KEEP` so I've done that in the next build. We can monitor feedback from there on.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by zilbuz** [comment]
I've just tried with the latest master branch and it works as expected on my end. Thanks :)
