### ISSUE TITLE
Feature Request: createFromObjects add custom properties to the sprites

### ISSUE THREAD

**Issue by scalemailted** [photonstorm/phaser#3808]
This feature request is based on the issue that I described in the html5gamedev forums:
[http://www.html5gamedevs.com/topic/37539-help-createfromobjects-doesnt-copy-my-objects-custom-properties/](url)

The createFromObjects() method doesn't add a tile's custom properties into the sprite.

**Comment by photonstorm** [comment]
Should probably set them in the Game Objects Data Manager, rather than directly on the GO itself and mutating its class.

**Comment by samme** [comment]
Oh, it already does BuildGameObject. So it just needs setData etc.?

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by kevthehermit** [comment]
I had some issues with this. I have added a comment to the pull. 

https://github.com/photonstorm/phaser/pull/3819#issuecomment-449648442
