### ISSUE TITLE
Incorrect overlap location (sprite scrollFactor and origin ignored)

### ISSUE THREAD

**Issue by jdjoshuadavison** [photonstorm/phaser#3810]
I'm using a callback function on the overlap method to do something when 2 sprites overlap each other. However, the function is being called in the wrong place (I.E. when they're not overlapping), and is not being called in the correct place (I.E. when they are overlapping).

After a bit of calculation and trial and error, I discovered that it seems that the overlap method is ignoring the origin and scrollFactor that I have applied to the sprite when calculating the overlap location. When I leave these properties as their defaults, the overlap fires in the correct place.

**[I've created a demo on jsFiddle.](https://jsfiddle.net/jd_joshuadavison/rsp02Lgw/embedded/result,js)**

Josh

**Comment by samme** [comment]
I'm not sure Arcade Physics is supposed to consider the scroll factor at all.

Since you used a StaticImage you need to update the body after changing the display origin, then it will work as expected: <https://jsfiddle.net/kuwqs4c7/2/>

**Comment by jdjoshuadavison** [comment]
Thanks Samme. As you've shown, `refreshbody()` does solve the issue with the origin. Really appreciate it!

I've actually solved the scrollFactor issue with maths, and I'm so new to game design/build and Phaser that I couldn't possibly argue whether Arcade Physics should consider scroll factor or not. If @photonstorm is happy that Arcade Physics isn't supposed to consider scrollFactor, then he can close this issue.

Tangent: I haven't gotten around to creating the issue/feature request on GitHub yet, but I wonder if you are able to offer any insight into another [issue that I've described on the html5gamedevs forum?](http://www.html5gamedevs.com/topic/38604-tilemap-layer-offset/)

**Comment by photonstorm** [comment]
There's no easy way to properly support `scrollFactor` within the physics system as it's Camera specific and applied in the rendering stage - all collisions would need checking against all Cameras, and you may get a collision happen in one Camera (because of its viewport position + scroll factor) but not in another. However, I think this highlights that the API docs need to make this clear, so I'll make sure they are changed to reflect this.
