### ISSUE TITLE
Should TileMaps run cullTiles when camera has not changed?

### ISSUE THREAD

**Issue by georgzoeller** [photonstorm/phaser#3811]
On a larger map (1024x1024), most frametime is spent culling tiles (CullTiles.js). Is there an optimization here where we can skip this if the camera viewport has not changed? nice to have/premature optimization ;)

**Comment by photonstorm** [comment]
Hmm, yes, but it's not quite as straightforward as you'd think. The Camera itself could determine if it's dirty or not - but it would have to check both its viewport dimensions and its position, rotation and zoom factor every frame (as a change in any of those would make it dirty). And also, the Tilemap Layer would need to internally store the previously culled tiles somewhere too, but it would have to do it for _every Camera_ in the Scene. All of which makes me think this shouldn't just be enabled wholesale but should be some user-level feature you could turn on.

**Comment by photonstorm** [comment]
Just to say that in the master branch for 3.11 you'll find a whole raft of updates all to do with tilemap culling. Including the ability to set your own culling callback function. There is also the option to disable culling, or set extra cull padding, and the whole culling function has been recoded and is now a lot faster. All in all, I'm happy you can do whatever you need with culling now - so am going to close this issue off. If you get time to test it, that'd be great :)
