### ISSUE TITLE
scene.pause(this.scene.key) called at the end of create() is not working.

### ISSUE THREAD

**Issue by Waclaw-I** [photonstorm/phaser#3812]
Hi!

I was trying to run my GameScene and then immediately pause it and run another scene on top of it, using **run()**, like this:

`this.scene.pause(this.scene.key);`
`this.scene.run("StartLevelScene");`

**pause()** and **run()** were called at the end of **create()** method of the GameScene.

New scene has poped up on top of GameScene, but the GameScene **update()** was still running.
Using sleep() caused the GameScene to go black (no rendering) but the **update()** was being called.

When the **pause()** call was changed to this (thanks @Antriel ):

`this.scene.manager.queueOp('pause', this.scene.key);`

everything started to work fine.

Have a nice day!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
