### ISSUE TITLE
flipX does not mirror animation correctly

### ISSUE THREAD

**Issue by B3L7** [photonstorm/phaser#3813]
From what I can tell sprite.flipX(true) does not mimic sprite.scale = -1 in the way expected.
This causes issues with animations to be off when flipped almost as if they have an incorrect origin. To illustrate I made this repo:

[Example](https://b3l7.github.io/flipIssue/)

[Source](https://github.com/B3L7/flipIssue)

Normally I would be fine with using .setScale to flip the sprite but that seems to cause an even larger issue with matterjs( sprite ends up rolling around the scene, not sure if that is expected with that physics engine or you would like me to post a separate issue).

Thanks!

**Comment by gooderist** [comment]
Not sure if this is correct, but I was able to get the correct result by modifying TextureTintPipeline.js:batchSprite:408


        var fx = 1;
        var fy = 1;

        if (sprite.flipX)
        {
            fx = -1;
        }

        if (sprite.flipY)
        {
            fy = -1;
        }

        var xw = x + frameWidth;
        var yh = y + frameHeight;

        spriteMatrix.applyITRS(sprite.x, sprite.y, sprite.rotation, sprite.scaleX * fx, sprite.scaleY * fy);


If someone is willing to give feedback or nudge me in a more correct direction, I would be happy to work on a PR.

**Comment by OmarShehata** [comment]
Just wanted to add I've recently run into this as well, and @gooderist 's code produces the correct result for me.

**Comment by PhaserEditor2D** [comment]
The other workaround you can do is to set in the texture packer "do not remove extra whitespaces".

**Comment by PavelMishin** [comment]
I have also experienced this issue under the following conditions: 
1. Phaser is version17.0. There was no issue with 16.3
2. Using WebGL renderer. No problem with Canvas
3. Animation frames have different size as the result of using trimming in the Texture Packer, even with "Crop, keep position" mode and pivot points on (0.5, 0.5)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
