### ISSUE TITLE
Dynamic Tilemap zoom problem

### ISSUE THREAD

**Issue by Mursaat** [photonstorm/phaser#3818]
I'm trying to zoom in on a dynamic tilemap (using WEBGL)  but I have some problems. I asked on the forum and it seems to be a bug. I tried on the example
"Home/Game Objects/Tilemap/Dynamic/Endless Map", and I added ```this.cameras.main.setZoom(2)``` at line 51.

The result :
![zoom-1](https://user-images.githubusercontent.com/12541829/42413806-52223558-8228-11e8-915f-719639d879ca.png)

I've tried a few things since I need this feature.

The zoom property seems to be used in CullTiles.js. When I replace that (l.34)
```js
camera.matrix.scale(zoom, zoom);
camera.matrix.translate(-originX, -originY);
camera.matrix.invert();
```

by this
```js
camera.matrix.translate(-originX, -originY);
camera.matrix.invert();
camera.matrix.scale(zoom, zoom);
```

I get a little less strange result, but I don't know if it is the expected result.
![zoom-2](https://user-images.githubusercontent.com/12541829/42413841-443cc056-8229-11e8-9783-5696c7ba3893.png)

Note: The result obtained with Canvas is also different, no text and the map is scrolling faster  :
![zoom-3](https://user-images.githubusercontent.com/12541829/42413895-45afdf58-822a-11e8-803c-8b241bd6e3b1.png)

I hope I have provided enough information about that problem, I've never opened an issue before. 🙂
Thanks

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by Mursaat** [comment]
It works perfectly, thanks. 🙂
