### ISSUE TITLE
container.setSize() called a second time leads to an offset of the original size being used for pointer events

### ISSUE THREAD

**Issue by paulsymphony** [photonstorm/phaser#3824]
To recreate, use this demo:

http://labs.phaser.io/edit.html?src=src\game%20objects\container\container%20hitarea%20from%20size.js

And add this line at the bottom of the create() function:

container.setSize(100,100);

The result is a rollover that appears to be exactly 1/2 the width and height offset from the container. This result occurs no matter what values are passed to setSize().

**Comment by photonstorm** [comment]
When you call `setInteractive` you are telling it to create a hit area the size of the Container _at that point in time_. If you change the size of the Container after this, the hit area will not automatically update. If you were to scale the Container, the hit area will understand that and use it, but it doesn't monitor resizing. This is true for all Game Objects, not just Containers.

The solution is to either call `removeInteractive`, resize it and then make it interactive again. Or, far easier, just resize the hit area.
