### ISSUE TITLE
Minor memory leak with mySound.play()

### ISSUE THREAD

**Issue by maximtsai** [photonstorm/phaser#3825]
Bug: Playing a sound causes a small memory leak. This becomes much more noticeable when a sound is repeatedly played several thousand times.

The following code will cause memory usage on Chrome to rise by about 100mb every 10-15 seconds:
```
var audioContext;
try {
    audioContext = new (window.AudioContext || window.webkitAudioContext)();
} catch (e) {
    console.error(e);
}

var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
        update: update
    },
    pixelArt: true,
    audio: {
        context: audioContext
    }
};

var game = new Phaser.Game(config);
var explosion;

function preload ()
{
    this.load.audio('explosion', ['assets/audio/SoundEffects/explosion.mp3']);
}

function create ()
{
    explosion = this.sound.add('explosion', {
        volume: 0.5
    });
}

function update ()
{
    if(explosion) {
        for (let i = 0; i < 1000; i++) {
            explosion.play();
        }
    }
}
```
Bug was encountered on a Windows 10 desktop using the Chrome browser on Phaser 3.10.1.

**Comment by pavle-goloskokovic** [comment]
@maximtsai Does memory usage decrease at some point when running the code above or does it just keeps rising?
If it doesn't decrease, can you find out what objects are NOT being garbage collected and are causing memory leak?

This code creates 1000 `AudioBufferSourceNode` objects per frame, 60000 per second. 
Is not a real world use case scenario, you won't even be able to hear any sound if you run this code.

Most likely Web Audio garbage collector is being overloaded and requires much more time to release all created objects.

**Comment by maximtsai** [comment]
I haven't been able to reproduce this issue with the 3.14 Phaser build and the conditions are indeed beyond what a normal game would expect to do so I guess this is a non-issue at worse.

**Comment by photonstorm** [comment]
I know the issue is several years old, but I've tested under the new 3.60 version, and with a reduced (and more realistic) audio creation rate, it's not leaking anything anymore (as long as gc has time to run)
