### ISSUE TITLE
Box2D Plugin: Phaser.Physics.Box2D setBounds() does not set collisionCategory and collisionMask

### ISSUE THREAD

**Issue by xiaoandtell** [photonstorm/phaser#3827]
version 1.0.2

    setBounds: function (x, y, width, height, left, right, top, bottom, collisionCategory, collisionMask) {
...

BUG:
        fixtureDef.filter.categoryBits = Phaser.Physics.Box2D.worldBoundsFilterCategory;
        fixtureDef.filter.maskBits = 0xFFFF;
FIX:
        fixtureDef.filter.categoryBits = collisionCategory;
        fixtureDef.filter.maskBits = collisionMask;

**Comment by photonstorm** [comment]
Thank you for opening this issue (all those months ago!) - your fix has been merged into 1.0.4 of the Box2D Plugin.
