### ISSUE TITLE
Add ability to play Animations in reverse

### ISSUE THREAD

**Issue by qzix13** [photonstorm/phaser#3837]
Trying to play an animation in reverse. The forward property does not help.

This variant is not working. `Play `function set `forward `to true
```
spr.anims.forward = false;
spr.anims.play();
```

I hoped this would work. But no luck.
```
spr.anims.play();
spr.anims.forward = false;
```

**Comment by photonstorm** [comment]
It's an internal property and should have been flagged as private, as it doesn't do what you assumed it would do. I'll rename this issue and turn it into a feature request.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by Ben-Millions** [comment]
I just pulled 3.12.0 Beta 3 Release with the intention of testing out the playReverse. And it appears to disregard the setting for repeat when yoyo: true, and it appears to repeats infinitely. I suspect it's line 645 of Animation.js, but I know I don't fully understand the class yet, and I'm not sure when I'll have time to dig around and rebuild and test it.

**Comment by khaleb85** [comment]
@Ben-Millions can you send us a sample of the bug?

**Comment by photonstorm** [comment]
@Ben-Millions I just tried your codepen against 3.12 Beta 4 and I can confirm that setting `yoyo` to `true` makes it repeat forever, regardless of the `repeat` value. So yes, definitely a bug in the playReverse changes.

**Comment by photonstorm** [comment]
Re-opening until `yoyo` is fixed.

**Comment by Glerek** [comment]
Should I resubmit my pull request? Back then I tested the full matrix: yoyo, repeat and forward/backward so maybe it would be easier for you to merge it?

**Comment by khaleb85** [comment]
@photonstorm I'll try to solve it this weekend, I don't know what can cause this problem...
