### ISSUE TITLE
Manual tween replay

### ISSUE THREAD

**Issue by pantoninho** [photonstorm/phaser#3839]
Good evening,

Invoking `Tween.prototype.play` after finish does not trigger the tween:
https://codepen.io/anon/pen/ZjQvry

Not sure if it is related but `Tween.prototype.restart` does not trigger the tween either if invoked inside `onComplete` callback:
https://codepen.io/anon/pen/bjEaKE?editors=0010

Due to lack of time I'm not able to further inspect the issue right now.

As a side-question, is there any reason for tweens not to fire events? A `complete` event would be very useful.
Thanks for the amazing work on phaser3 so far!

**Comment by pantoninho** [comment]
This is still reproducible on v3.12.0.
Bumping.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
