### ISSUE TITLE
timeline loop ignores delay

### ISSUE THREAD

**Issue by Antriel** [photonstorm/phaser#3841]
```
this.tweens.timeline({
	targets: image,
	loop: 10,
	tweens: [{
		alpha: 0,
	},
	{
		alpha: 1,
		delay: 1000
	}]
});
```
The first time this plays, the delay of the second tween is applied. The remaining loops it is ignored and alpha tweens from 0 back to 1 immediately.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
