### ISSUE TITLE
setDeadzone position

### ISSUE THREAD

**Issue by Sunhat** [photonstorm/phaser#3842]
hi,

trying to keep my player to the left of the screen while the camera follows, although this doesn't seem to work with setDeadzone, as it sets a box in the center of the screen

**Comment by photonstorm** [comment]
You'll need to implement your own deadzone, the built-in one is always centered on the camera. Or open a feature-request issue I guess, with an example of possible syntax.

**Comment by Sunhat** [comment]
This exists in Phaser 2 and is used in your own examples. Bit of a joke that v3 has gone backwards in features?

`game.camera.deadzone = new Phaser.Rectangle(100, 100, 600, 400); `
