### ISSUE TITLE
delayedCall paused when browser tab is changed

### ISSUE THREAD

**Issue by alexeymolchan** [photonstorm/phaser#3843]
when i change browser tab timer just stops and after i switch back to game tab it continue, but doesn't consider seconds that i was in different tab.

**Comment by photonstorm** [comment]
This is the correct behavior. All timers work on elapsed game time, not wall-clock time, and the browser automatically pauses the game when you switch tabs (there's nothing you can do to stop this happening, all modern browsers do it).

There's probably a case to be made for a brand new feature that fired an event after a fixed time based on the wall-clock, but that's out of the scope of the current Timers.

**Comment by alexeymolchan** [comment]
@photonstorm thanks for explanation, we can close this then
