### ISSUE TITLE
Can't add rectangle to container

### ISSUE THREAD

**Issue by gbangban** [photonstorm/phaser#3846]
This is a followup to https://github.com/photonstorm/phaser/issues/3740.  

Essentially adding a rectangle to a physics container gives the same/similar error.

Uncaught TypeError: child.setScrollFactor is not a function
    at ContainerWebGLRenderer [as renderWebGL] (phaser.js:141484)
    at WebGLRenderer.render (phaser.js:65133)
    at CameraManager.render (phaser.js:114533)
    at Systems.render (phaser.js:27184)
    at SceneManager.render (phaser.js:46818)
    at Game.step (phaser.js:109346)
    at TimeStep.step (phaser.js:106091)
    at step (phaser.js:66488)

Thanks for all the hard work!

**Edited**
From the physics container demo, modified to add a rectangle body to the container
```
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#1b1464',
    parent: 'phaser-example',
    physics: {
        default: 'matter',
        matter: {
            debug: true,
            gravity: {
                y: 0.3
            },
        }
    },
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('platform', 'assets/sprites/platform.png');
    this.load.image('mushroom', 'assets/sprites/mushroom2.png');
}

function create ()
{
    var image1 = this.add.image(0, -30, 'mushroom');
    var image2 = this.add.image(-40, 30, 'mushroom');
    var image3 = this.add.image(40, 30, 'mushroom');
   const line = this.matter.add.rectangle(20, 30, 20, 5, {
            });

    container = this.add.container(100, 100, [  image1, image2, image3 ]);

    //  A Container has a default size of 0x0, so we need to give it a size before enabling a physics body
    container.setSize(128, 64);

    var physicsContainer = this.matter.add.gameObject(container);

    physicsContainer.add(line);

    physicsContainer.setFrictionAir(0.001);
    physicsContainer.setBounce(0.9);

    this.matter.add.image(350, 450, 'platform', null, { isStatic: true }).setScale(2, 0.5).setAngle(10);
}
```

**Comment by photonstorm** [comment]
A Rectangle is just a Geometry object, you can't add it to a Container because it's not a Game Object and they only contain Game Objects. It's the same reason you can't add a Rectangle to the display list. If you want to do this, it needs to be a Graphics object that is rendering a Rectangle.

**Comment by gbangban** [comment]
Appreciate the feedback 👍
