### ISSUE TITLE
Wrong container width when used with for nested containers

### ISSUE THREAD

**Issue by Riderrr** [photonstorm/phaser#3848]
code: https://codepen.io/Riderrr/pen/MBbJNz?editors=1111
issue: when I trying to get bounds width for the nested container with sprite and change its position when the parent container is scaled, it affects on the current container width.
expected width: 32
actual: 82

**Comment by photonstorm** [comment]
Your example uses Phaser 3.11. Change it to use 3.55.2 and you'll get the correct size.
