### ISSUE TITLE
Container lose interactivity after calling removeInteractive and setInteractive

### ISSUE THREAD

**Issue by alexeymolchan** [photonstorm/phaser#3849]
version 3.11.0

Actually i didn't find a proper way to change container input hitArea after first setSize -> setInteractive, maybe i missed something ?

https://jsfiddle.net/zp7ky4fe/, i tried to reset interactivity with shape (same behaviour with setSize), if i do in way ```container.removeInteractivity``` and immediately ```container.setInteractivity(shape, callback)``` interactivity lost anyway. But if i call ```container.removeInteractivity -> setTimeout(() => container.setInteractivity(shape, callback), 1000)``` - everything works as expected.

So i checked the source code and found that condition for insertion ```this._pendingInsertion.indexOf(child) === -1 && this._list.indexOf(child) === -1``` is false when i call  ```container.removeInteractivity``` and immediately ```container.setInteractivity(shape, callback)``` -  because current container still exist in  the ```_list``` and this part of code 
```
for (var i = 0; i < toRemove; i++)
        {
            var gameObject = removeList[i];

            var index = current.indexOf(gameObject);

            if (index > -1)
            {
                current.splice(index, 1);
                this.clear(gameObject);
            }
        }
```
 executes after ```queueForInsertion()``` finished, also i dont really understand why do we call this.clear(gameObject) when we already cleared gameObject here: 
```
this.scene.sys.input.clear(this);
    this.input = undefined;
    return this;
```

Sorry for my not perfect english, kinda hard to explain :0

**Comment by photonstorm** [comment]
What is it you're trying to actually achieve?

When you call `removeInteractive` it _queues_ the Input Handler for removal, it doesn't happen immediately. Which is why you can't set it right away again. One game step needs to have happened before you could do that. Also, it's a bit of a strange thing to do: Why remove something only to immediately add it again? Why not just edit the hit area if you want to change its size?

**Comment by alexeymolchan** [comment]
@photonstorm for example i set container size(100, 30) and call setInteractive, after game resize container size changed to 80x30 and i call setSize(80, 30), how should i change hitArea to 80x30 ?

**Comment by photonstorm** [comment]
`container.input.hitArea.setSize(80, 30)` assuming your hit area is a Rectangle, which it is by default.

Usually, you'd scale things to manage game resizing, not actually give them a new size, in which case you don't need to change the hit area because it uses the parents scale already.

**Comment by alexeymolchan** [comment]
@photonstorm thanks, didn't try to change hitArea like this. sorry for your time
