### ISSUE TITLE
Problem with GroupFactory's this.add.group(children)

### ISSUE THREAD

**Issue by pedro-w** [photonstorm/phaser#3854]
I'm using Phaser 3.11.0 from cdn.jsdelivr.net, running on Firefox 61

I was trying to add a group using the Factory syntax:
``` javascript
var a = ..., b = ..., c = ...;
var gp = this.add.group([a, b, c]);
```
where `a`, `b` & `c` are `GameObject`s. According to the docs this ought to work but I find that `gp` has no children.

See https://jsfiddle.net/w3u65e4o/8/ for minimal example.

When I look at the source  there is a test for making the children parameter optional. 
https://github.com/photonstorm/phaser/blob/4f6790f450ed6d3daa44c700d2d70d6d5adb7f1b/src/gameobjects/group/GroupFactory.js#L23-L32
However I don't think this is right; `typeof children` is 'object' even if children is an array. By contrast the constructor for Group does the right thing (as far as I can see) - in which case having the same logic in the Game constructor may well be redundant.
https://github.com/photonstorm/phaser/blob/4f6790f450ed6d3daa44c700d2d70d6d5adb7f1b/src/gameobjects/group/Group.js#L117-L123

**Comment by photonstorm** [comment]
Agreed. I think it's the Factory logic that is redundant, it may as well stay in the Group constructor.

**Comment by pedro-w** [comment]
Thanks for the swift response. I've checked and as far as I can see that's the only case of it. I can do a pull-request if you want but I think it might be quicker for you to do than review/approve the PR on github!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
