### ISSUE TITLE
Global Plugins key check issue after game destroy

### ISSUE THREAD

**Issue by photonstorm** [photonstorm/phaser#3856]
Global Plugins add to a window level cache, so the key check needs to be skipped if a Phaser game is created then destroyed and re-created again.

Source: http://www.html5gamedevs.com/topic/39003-plugin-key-in-use-after-game-destroyed/

**Comment by jcyuan** [comment]
just wanna say, from Flixel -> Phaser 2 -> Phaser 3, the framework becomes more more mature, the architecture is really really great in Phaser 3, I love Phaser 3!
many thanks for your efforts!
