### ISSUE TITLE
Wrong input for negative scaled sprites in container

### ISSUE THREAD

**Issue by Riderrr** [photonstorm/phaser#3858]
code: https://codepen.io/Riderrr/pen/ZjBqdy
The input works wrong for negative scaled sprites in the container (not nested)

**Comment by Riderrr** [comment]
Sorry, accidentally past the wrong link.

**Comment by photonstorm** [comment]
Investigated today and issue is caused by scale + origin (scale on its own works fine, combined with origin it is offset from Container). Considering leaving as-is until Containers are re-coded in 3.14.

**Comment by photonstorm** [comment]
Containers will not be re-coded (by me, anyway) for Phaser 3. They are what they are, I'm afraid.
