### ISSUE TITLE
Bug: displayOrigin of Zone object is not correct

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3865]
[Demo](https://codepen.io/rexrainbow/pen/ejRoZR?editors=0011), see messages in console. Running at phaser 3.11.0

[displayOriginX, displayOriginY](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/components/Origin.js#L187-L193) : 
```javascript
this._displayOriginX = Math.round(this.originX * this.width);
this._displayOriginY = Math.round(this.originY * this.height);
```

Therefore the value of displayOriginX, displayOriginY should *NOT* be `0, 0`, because that the originX, originY is `0.5, 0.5`

**Comment by rexrainbow** [comment]
Zone object might miss `this.setOrigin(0.5, 0.5);` in construct function.

Sorry I could not submit a PR because that my previous PR #3781 has not been processed yet.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
