### ISSUE TITLE
[Question] Can someone give some suggestions on performance improving for a long scrolling map?

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#3868]
For example if I have a very long map (X axis) with many BODIES on it, will they be rendered even if they are out of the camera view? I think I can't create all the BODIES when init the map layer, that will use a lot of memory.

Why I do not use tilemap is because that my layers have different tileWidth/tileHeight but tilemap can only has the same tileWidth/tileHeight for all its layers.

for the background layer I can create 2 same images, and place the off-screen one ahead of the screen alternately.

but I have no idea how to manage the good many of BODIES, create incoming one and destroy the off-screen one when scrolling in every frames? (a bit afraid of screen sticking when create a complex gameobject)

so please, I need some suggestion on this, thank you very much.

**Comment by jcyuan** [comment]
my current solution is:

1. repeatable image use tileSprite and set offset to scroll
2. BODIES: in update function to check camera.scrollX, and then to decide which object needs to be created or destroied.

**Comment by photonstorm** [comment]
The Camera does not cull anything. So it will render everything it is told to, regardless if it can "see" it or not.

I would suggest as your game scrolls, you kill off objects that are out of view (and cannot be scrolled back again) - you could do something similar for objects coming into view, but give it plenty of space. It's very game specific (i.e. speed of scroll, can player move left and right? etc) but generally, I think it'd be safe to have 4 screens worth of content alive at any one time.

Ideally please move discussion of this topic to Slack / Discord or the forum, as it's not really an API issue, thanks.
