### ISSUE TITLE
phaser.d.ts issue.

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#3869]
I found some errors in the .d.ts:

![image](https://user-images.githubusercontent.com/850854/43310451-296841d8-91ba-11e8-8ab2-fca2df203579.png)

GameConfig:
I think this is correct:

    {
         render: { pixelArt: true  }
    }

but in .d.ts it was generated as `"render.pixelArt": boolean`.

because this is auto-generated from JSDoc, so I can't modify it and make a PR.

actually If the item is an object in the GameConfig or other class, it will be generated as a wrong format in .d.ts.

**Comment by jcyuan** [comment]
the correct format should be:

    banner?: boolean | {
        hidePhaser?: boolean,
        text?: string,
        background?: string
    };

    render?: {
        antialias?: boolean,
        pixelArt?: boolean,
        autoResize?: boolean,
        roundPixels?: boolean,
        transparent?: boolean,
        clearBeforeRender?: boolean,
        premultipliedAlpha?: boolean,
        preserveDrawingBuffer?: boolean,
        failIfMajorPerformanceCaveat?: boolean,
        powerPreference?: string,
        batchSize?: integer
    }

**Comment by jcyuan** [comment]
another BIG catch:

    Phaser.Utils.Object

this namespace should be `Phaser.Utils.Objects`

missed 's' in the JSDoc.

**Comment by jcyuan** [comment]
and

    matter.add.gameObject

returns a wrong type, sould be `MatterGameObject` but `GameObjects.GameObject`

I think there is still more errors in the .d.ts, is there a good way to fix? e.g. to create .d.ts project on github and everyone could do PR on it?

**Comment by photonstorm** [comment]
The vast majority of them can be fixed by editing the JSDocs in the source code, from which the defs are generated. Changing the defs file directly won't help anyone, as it'll just be replaced the next time the parser is run.

**Comment by jcyuan** [comment]
ok, I'll try to fix docs
