### ISSUE TITLE
[Light2D] rotating normal map, spot light issue

### ISSUE THREAD

**Issue by fazzamatazz** [photonstorm/phaser#3870]
Hi,

I think I've spotted an issue with the Light2D pipeline. When a sprite using a normal map for per-pixel lighting rotates, a spot light will illuminate the correct pixels, but not take the sprite angle into account, and so the pixels are highlighted from the wrong angle.

I've coded up a little [demo](https://madcarrot.itch.io/phaser3-demo?secret=70SZ1Whbm3Wsf9onEXXdRM2deQ)

If you position the spot light (attached to pointer) behind the insect to highlight the abdomen, when the insect is facing downward, the light angle is correct, when the insect is facing upward, the light angle is 180 degs off.

Assets are attached to [this post](http://www.html5gamedevs.com/topic/39115-light2d-rotating-normal-map-issue/) if you need them. Code for demo is below.

```javascript
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var game = new Phaser.Game(config);

var insect;

function preload () {

    this.load.image('insect', [
        'assets/images/bug-99x103.png',
        'assets/images/bug-nm-99x103.png'
    ]);
}

function create () {
    
    this.lights.enable().setAmbientColor(0x333333);
    
    insect = this.add.image(400, 300, 'insect').setOrigin(0.5).setScale(3);
    insect.setPipeline('Light2D');
    
    var light = this.lights.addLight(180, 80, 200).setColor(0xffffff).setIntensity(2);
    
    this.input.on('pointermove', function (pointer) {
        light.x = pointer.x;
        light.y = pointer.y;
    });
}

function update() {
    
    insect.angle += 0.5;
}
```

Let me know if you need any more information. Thanks,

**Comment by hexus** [comment]
Thanks for spotting this, the pipeline will likely need to take into account the rotation of each game object.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
