### ISSUE TITLE
There are some missing ' in the docs

### ISSUE THREAD

**Issue by Yudikubota** [photonstorm/phaser#3873]
I spotted that there are some missing characters in the docs. 
Affected files:
```
src/loader/filetypes/TilemapImpactFile.js
src/loader/filetypes/TextFile.js
src/loader/filetypes/TilemapCSVFile.js
src/loader/filetypes/TextFile.js
src/loader/filetypes/TilemapJSONFile.js
```

```javascript
function preload ()
{
    this.load.tilemapCSV('level1', maps/Level1.csv');
}
```

For example: https://photonstorm.github.io/phaser3-docs/Phaser.Loader.LoaderPlugin.html#tilemapCSV__anchor

**Comment by hexus** [comment]
These have been fixed. I went over all the loader file type descriptions (crikey, they're long and duplicated!) just to make sure there weren't any other instances of this, and found one in the `HTMLFile` type.

This will be included in the next release.

Cheers!
