### ISSUE TITLE
Missing jsdoc comment at FixedKeyControl.js

### ISSUE THREAD

**Issue by guzmonne** [photonstorm/phaser#3874]
On the `jsdoc` comment for the FixedKeyControl object, I believe there is a line missing to the down direction. This is the line I think the change should go:

https://github.com/photonstorm/phaser/blob/7aa46657c278c4f1ea285c1b4ac1bf95827469a9/src/cameras/controls/FixedKeyControl.js#L24

And it should say something like this:

```javascript
 * @property {Phaser.Input.Keyboard.Key} [down] - The Key to be pressed that will move the Camera down.
```

It is such a small change that a PR might be too much. That said, if it would help I would gladly create one.

Keep up the good work

**Comment by hexus** [comment]
I've just added this in (1ceec993). Thanks for finding this!

**Comment by guzmonne** [comment]
No problem! Thanks for the quick fix.
