### ISSUE TITLE
Problem with Graphics.generateTexture() call for 3.12.0-beta1

### ISSUE THREAD

**Issue by aahz** [photonstorm/phaser#3879]
When calling `generateTexture` method for `Graphics` instance the execution of `Camera.updateSystem` leads to this exception:

```
Uncaught (in promise) TypeError: Cannot read property 'width' of undefined
    at Camera.updateSystem (Camera.js:1957)
    at Camera.set [as x] (Camera.js:2047)
    at Camera.setViewport (Camera.js:1730)
    at Graphics.generateTexture (Graphics.js:1497)
    at Abilities.create (index.js:113)
    at InGameStage._createAbilities (in-game.js:424)
    at in-game.js:133
```

Seems like it relates to this strings in Camera.js:
```
var gameWidth = this.config.width;
var gameHeight = this.config.height;
```
, 'cause the debbuger says there is no `config` field in `this`. And as a result application stops at the first `generateTexture` call.

BTW, very exited about ScaleManager you are going to release and really wait for it =) It will solve all the pains with dynamic scaling I have, so I tried to run my app with the latest `master` version and got this. If you need more assistance and more data to find out the problem, just let me know ;)

***

__P.S.__ 3.11.0 and lower versions works great with it

**Comment by hexus** [comment]
Introduced by commit 1a62a356.

**Comment by hexus** [comment]
This should now be fixed.

The Graphics object had new dependencies (1a62a35) that were not provided when the static `Graphics.TargetCamera` object was used by the `Graphics.generateTexture()` method. Providing a `Graphics` instance's scene reference to the `TargetCamera` at texture rendering time resolved the issue for me.

Please feel free to test this on the master a branch and let us know if this fixes the issue for you.

I'm leaving this open in case @photonstorm would like to solve this in a different way.

**Comment by photonstorm** [comment]
Nah, I'm happy with how that's fixed. Please test the master branch @aahz and if you're happy it works close this issue off.

**Comment by aahz** [comment]
Wow, that's was fast =))))

Seems the issue is solved. Now everything is working as expected
Thanks a lot for your work @hexus, and, I suppose, we can close the issue
