### ISSUE TITLE
[Phaser 3.12.0-beta1] Nested containers visibility bug

### ISSUE THREAD

**Issue by aahz** [photonstorm/phaser#3881]
Here is one another issue with 3.12.0-beta1.

It seems like changing visibility of a container nested into another container does not leads to scene redraw and container with all its content still visible on the screen.

Here is the way to reproduce the problem. May be there is another ways, for ex. without ScenePlugin, but in my case it is looks like this:

First, I've created a ScenePlugin with a container and nested container in it. Containers will be added to the scene like this:

```
import {Scene, Plugins} from 'phaser';

// --- Plugin -----------------------------------------------------------------------------
class MyPlugin extends Plugins.ScenePlugin {
	static NAME = 'MyPlugin';

	constructor(scene, pluginManager) {
		super(scene, pluginManager);

		this._container = null;
		this._nestedContainer = null;
	}

	get mainContainer() { // Main container
		return this._container;
	}
	
	get nestedContainer() { // Nested container
		return this._nestedContainer;
	}

	create() {
		this._container = this.scene.add.container(0, 0);
		this._nestedContainer = this.scene.add.container(0, 0);

		this._text = this.scene.add.text(
			20, 20,
			'I\'m still can see this =(',
			{fontFamily: 'Arial', fontSize: 20, fill: '#FF0000'}
		);

		this._nestedContainer.add(this._text);
		this._container.add(this._nestedContainer);

		return this;
	}
}

// --- Scene ------------------------------------------------------------------------------
class MyScene extends Scene {
	constructor() {
		super('MyScene');
	}

	preload() {
		this.load.scenePlugin(MyPlugin.NAME, MyPlugin);
	}

	create() {
		const myPlugin = this[MyPlugin.NAME].create();

		console.log(myPlugin.mainContainer.visible) // > true
		console.log(myPlugin.nestedContainer.visible) // > false, but the text is still on the screen

		myPlugin.mainContainer.visible = false;

		console.log(myPlugin.mainContainer.visible) // > false, and screen is now empty
	}
}

const game = new Phaser.Game({
	width: 1920,
	height: 1080,
	type: Phaser.WEBGL,
	fps: {
		min: 10,
		target: 24,
	},
	resolution: (
		window.devicePixelRatio || window.screen.deviceXDPI / window.screen.logicalXDPI || 1
	),
	render: {
		transparent: true,
		roundPixels: true,
		antialias: true,
		pixelArt: false,
		clearBeforeRender: true,
		autoResize: false,
		powerPreference: 'high-performance',
	},
	scene: [MyScene],
});
```

Any attempts to control visibility of the nested container does not leads to redraw. But, for ex., interaction for elements inside of nested container is not available when `visible` field set to `false`.

Not sure if this is enough to fix the bug but feel free to ask for any assistance from me ;)

**Comment by photonstorm** [comment]
That's a _very_ strange use of the ScenePlugin class. I can't understand for a second why it would have containers added to it as it's an internal Scene Systems plugin. Regardless though, this is still a bug but it's now fixed in the master branch.

Also, be aware that nested container support is being removed in 3.13: #3852
