### ISSUE TITLE
Phaser.Tilemaps.Tile tint property seems to not work properly

### ISSUE THREAD

**Issue by plissken2013es** [photonstorm/phaser#3882]
Hi.

When I set the tint prop from a tilemap tile, it seems to modify the final color displayed on screen.
I've tried to use the same colors on a Graphics layer with MULTIPLY blend mode to "tint" my tiles, and it works fine.

You may see the example with commented code here: https://codesandbox.io/s/04y572xxmw

Thanks for your time.

**Comment by mapsandapps** [comment]
I'm having the same issue, where tiles are not getting tinted the color I would expect.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
