### ISSUE TITLE
[2] Camera stuttering when using with camera.startFollow & tilemap

### ISSUE THREAD

**Issue by mishelen** [photonstorm/phaser#3883]
So the problem is the following. This is a top-down shooter, the camera follows player + both static and dynamic layers are used. Map size is **12800 * 12800 px** (100 tiles * 100 tiles * 128px * 128px ) . Tilesheet about **3000 px**. Twitching occurs only in static layers. This is especially noticeable with deep layering and when dynamic layers neighborhoods with static ones. This appears on the mobile especially. One colleague has ironized that it can cause an attack of epilepsy. 

The camera is used as is on the desktop and with double zoom out on the mobile. I tried to remove the zoom for mobile, but effect only became more noticeable.  

Also tried different settings, nothing helps. 

- `roundPixels`, as a global config and as a camera setup. No changes.  
- `pixelArt` in the global config - increased fps quite well, but no changes.  
- Also tried in addition `followOffset` for the camera and `lerp`. First variant also make twitching not only layers, but player too.

**Comment by mishelen** [comment]
Just have finded Phaser 3 Dev Log #122:

> **Tilemap Mini-Tutorial**

> The downside is that if you have a particularly large layer, in terms of quantity of tiles, not pixel dimensions, then that's a lot of data to dump on the GPU every frame, especially considering potentially the vast majority of it isn't even going to be visible after rendering (as it'll be off-screen). Because it dumps the whole buffer every frame there is no culling involved. So they're fast, but equally, a bit dumb. And should likely be avoided if you have got a large layer to deal with. For a single-screen layer though, it's fast. Very fast.

So in my case it's a bug, or do I really need to use dynamic layers?

**Comment by photonstorm** [comment]
Yes, use Dynamic Layers. It will make no actual difference to the game code, but the renderer can then cull and apply pixel offsets, which it's impossible to do with Static Layers.

**Comment by mishelen** [comment]
Big thanks Richard!
@photonstorm
