### ISSUE TITLE
Wrong rectangle's right/bottom coordinates

### ISSUE THREAD

**Issue by imilo** [photonstorm/phaser#3884]
Hello!

I've noticed a little wrong calculations of the rectangle's borders. Simple code example:
```javascript
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        create: create
    }
};

var game = new Phaser.Game(config);

function create ()
{
    var rect = new Phaser.Geom.Rectangle(0, 0, 2, 2);
    console.log(rect);
}
```

Console says:
```
Rectangle {x: 0, y: 0, width: 2, height: 2}
    bottom: 2
    centerX: 1
    centerY: 1
    height: 2
    left: 0
    right: 2
    top: 0
    width: 2
    x: 0
    y: 0
```

Theoretically, if a rectangle starts at position **0** and it's width is **2** - it's **right** coord. should be **1**, isn't it? Because this rectangle takes exactly 2 pixels: 0'th and 1'st, but not the 2'nd. Same with the bottom.

---

P.S. Why this 1 pixel is still important - when there are 2 objects next to each other, pixel to pixel, function `Phaser.Geom.Intersects.RectangleToRectangle()` returns **True**, but it should be **False**.

**Comment by photonstorm** [comment]
Hi - As counter-intuitive as this may seem, the values are correct and consistent with other languages and frameworks:

AS3:
```
import flash.geom.Rectangle;

var rect:Rectangle = new Rectangle(0, 0, 2, 2);

trace(rect.right);
trace(rect.bottom);
```

Paper.js:

```
var rect = new paper.Rectangle(0, 0, 2, 2);
console.log(rect.right, rect.bottom);
```

Pixi.js (any version)

```
var rect = new PIXI.Rectangle(0, 0, 2, 2);
console.log(rect.right, rect.bottom);
```

All the above output 2 and 2 for the right and bottom values.

If you need to count the overlap of just 1 pixel, then you need to change the intersection test to the following to allow for the boundaries:

`return !(rectA.right <= rectB.x || rectA.bottom <= rectB.y || rectA.x >= rectB.right || rectA.y >= rectB.bottom);`

Geometrically though, the current implementation is correct (although it's worth adding to the docs I think)
