### ISSUE TITLE
Bug: CANVAS MODE problems with mask

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#3885]
Masks doesn't work in Phaser 3.11.0 in Canvas mode, but are working in 3.9.0
Tested  on Chrome and Safari

**Comment by photonstorm** [comment]
I just checked the Geometry mask examples and noticed they were missing a call to `beginPath`. Have added this and every example now works fine in Canvas and WebGL: http://labs.phaser.io/index.html?dir=display/masks/geometry%20mask/&q=

Using 3.11.

If you still think there's a bug, please post code demonstrating it.

**Comment by photonstorm** [comment]
Closing this as I've tested a number of complex geometry paths and they all work fine in Canvas mode in 3.12 beta 1 if using `beginPath` at the start.
