### ISSUE TITLE
useDamping prevents initial movement

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#3888]
<https://codepen.io/samme/pen/GBdPJp?editors=0010>

When an Arcade Body is created with velocity, drag, and useDamping=true, its velocity is reduced to zero during the first step.

It happens because `body.speed`, initially 0, is used in computeVelocity().

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
