### ISSUE TITLE
RetroFont doesn't allow setting line height to anything other than character height

### ISSUE THREAD

**Issue by FelixNemis** [photonstorm/phaser#3890]
RetroFont doesn't let you set extra spacing for the line height like you can with a plain bitmapfont.
You can work around this by manually adding space in the font texture and increasing the character height, but this would be a good feature I think.
You also can't define horizontal spacing but you can change that via the bitmaptext game object.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
