### ISSUE TITLE
Cannot resize SVG

### ISSUE THREAD

**Issue by thanh-taro** [photonstorm/phaser#3892]
Hello there,

I have a problem with resize SVG image files. The `setSize(width, height)` is useless and there is no effect.

I'm using Phaser v3.11.0 with ES6 on Webpack.

**Comment by raisen** [comment]
Have you tried setting the displayWidth and displayHeight properties? That's how I've been doing, not sure if it's the recommended way.

**Comment by thanh-taro** [comment]
Yeah. I tried and it works. I think this is the only way the effect the width/height of images (or sprites) is using `setScale` that changes displayWidth and displayHeight or setting them directly.

I wonder what is the purpose of using `setSize` method? :(

**Comment by photonstorm** [comment]
The purpose is for setting the internal size of the Game Object, as used by frames or physics body creation. To adjust how it's rendered, use `setScale` or `setDisplaySize`. I've updated the jsdocs to make this more clear.
