### ISSUE TITLE
Each sound loop end creates new AudioBufferSource

### ISSUE THREAD

**Issue by Xesenix** [photonstorm/phaser#3895]
While debugging problems with disappearing sound I have noticed that each finished sound loop creates new AudioBufferSourceNode potentially causing a memory leak.
![obraz](https://user-images.githubusercontent.com/2124257/43742605-dad1e878-99d2-11e8-9d42-c0034f31ed28.png)
For debugging I'm using chrome web audio inspector.

# Code

This code causes this behaviour:
```
const soundtrack = sound.add('soundtrack');
soundtrack.play({ loop: true });
```
This code doesn't:
```
const soundtrack = sound.add('soundtrack');
soundtrack.play();
soundtrack.source.loop = true;
```
# Expected
First code sample shouldn't create new AudioBufferSourceNode after each loop finish.

# Environment
Phaser v3.11.0
Chrome 67.0

**Comment by pavle-goloskokovic** [comment]
From https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode : 

```An AudioBufferSourceNode can only be played once; after each call to start(), you have to create a new node if you want to play the same sound again. Fortunately, these nodes are very inexpensive to create, and the actual AudioBuffers can be reused for multiple plays of the sound. Indeed, you can use these nodes in a "fire and forget" manner: create the node, call start() to begin playing the sound, and don't even bother to hold a reference to it. It will automatically be garbage-collected at an appropriate time, which won't be until sometime after the sound has finished playing.```

Hence there is no way for this to cause a memory leak.

Using second `AudioBufferSourceNode` was necessary to enable support for cross-browser marker looping.

**Comment by Xesenix** [comment]
Still, there is some bug related to creating new AudioBufferSource I didn't exactly pinpoint what it is but generally, if I use `soundtrack.play({ loop: true });` for looping purpose and combine it with muting and moving Phaser canvas to different DOM node it stops playing what doesn't happen if I use the second approach.

#### Some more details:
I have React application that shows Phaser canvas on one route and if I move to different route its removed from DOM and paused I have possibility to turn app into fullscreen that uses only subset of DOM when I get back to route with Phaser and restart it (i think after enough time so the loop finish) it wont start playing next loop.

Scene playing music loop: https://github.com/Xesenix/xes-games/blob/v0.2.2/src/lib/scene/music.scene.ts
React component hosting phaser: https://github.com/Xesenix/xes-games/blob/v0.2.2/src/game-01/components/phaser-view/phaser-view.tsx

Important methods for this issue componentDidMount and componentWillUnmount

Now I'm kind of trending towards not using Phaser sound manager at all and creating my own maybe then I will have a better understanding to be able to find what causes that issue.

#### Also this screen above is after 3 loops those AudioBufferSources dont dissapear after some time you can have something like this:

![obraz](https://user-images.githubusercontent.com/2124257/43976182-16cdef92-9ce0-11e8-9ee7-cb13d8e3c732.png)

**Comment by steve-salmond** [comment]
I've been using the Web Audio Inspector myself recently to try and track down some playback issues I'm getting with Phaser 3 audio on iOS (seems to relate to using looped audio sprites in my case).

It seems like the Web Audio Inspector itself prevents GC of audio nodes:
```
Web Audio Inspector keeps references to all AudioNodes created in order to allow the user to obtain references to the nodes (via the __node__ method). AudioNodes hence do not get GC-ed until the user leaves the web page. Sometimes, this behavior may unfortunately produce tall graphs.
```

https://github.com/google/audion/wiki/How-to-Use#no-audionodes-are-garbage-collected

The Firefox version of this tool, Web Audio Editor (https://developer.mozilla.org/en-US/docs/Tools/Web_Audio_Editor) seems to do a better job of removing nodes from the display as they get GC'ed.  However, Mozilla seem to have deprecated and removed the tool in Firefox 67, so you'd have to downgrade to try it out.

**Comment by photonstorm** [comment]
Thanks for posting that information @steve-salmond - I'm going to close this issue off as I'm happy we're doing what the spec says with audio nodes.
