### ISSUE TITLE
Phaser.Display.Color.ComponentToHex return "[object Object]"

### ISSUE THREAD

**Issue by jjalonso** [photonstorm/phaser#3904]
var c = new Phaser.Display.Color(95, 245, 65);
Phaser.Display.Color.ComponentToHex(c)
"[object Object]"

**Comment by photonstorm** [comment]
`ComponentToHex` takes a number as its argument, not an object (which is what a Color object is) - I guess the function could check if the input is a number before doing anything with it, but it does say in the docs (which are complete for that function) what to provide, so the onus is on the dev really.
