### ISSUE TITLE
Unable to set tile depth on tilemap

### ISSUE THREAD

**Issue by Telokis** [photonstorm/phaser#3906]
## Version
* Phaser Version:
3.9.0
* Operating system:
Windows
* Browser:
Chrome 68

## Description

When using a tilemap (either dynamic or static), I am unable to set the depth for each tile individually.

I just did
```js
const layer = createDynamicLayer(0,...);

layer.forEachTile(tile => {
  tile.depth = tile.y * tile.height + tile.height / 2;
});
```

## Additional Information

I noticed that [this isometric tilemap example](http://labs.phaser.io/view.html?src=src/depth%20sorting/isometric%20map.js) is creating the map manually by placing images. It makes me think that it may not (yet) be possible to set a per-tile depth without placing images manually in the world.

**Comment by photonstorm** [comment]
Tiles don't have a `depth` property, so setting it won't do anything. All you've done in the code above is to give your tile a new dynamic property, but nothing will actually use it. There are no plans for this as a feature either, as it doesn't really make sense because tiles generally never overlap, so there's no depth required for them within their own layer. Even in isometric maps you still just define them using a single draw order.

We are going to provide alternative tile draw orders though (see #3284)

**Comment by Telokis** [comment]
Ok, thanks for the quick answer. I am used to RPG Maker mapping in which each tile has an inherent depth value and I thought Phaser worked the same way.
On the screenshot provided, you can see the map I made. Everything on screen is the tilemap except the characters.
Should I change and make the trees and tent pure image objects in order to be able to use the depth on them?

![image](https://user-images.githubusercontent.com/6382729/43910693-d024daf2-9bfd-11e8-8fc9-0072d9249665.png)

**Comment by mikewesthad** [comment]
@Telokis, you can split your map into multiple layers and then adjust the depth on those layers. Are you using Tiled? If so, your Tiled setup might look something like:

![1_9zv7jbeonwwzmqad2idbpg](https://user-images.githubusercontent.com/1131802/43930909-87efd9b8-9c01-11e8-8568-ce77f400963b.gif)

This [example](https://labs.phaser.io/edit.html?src=src/game%20objects/tilemap/static/tiled%20%20multi%20tileset.js) from Phaser Labs features multiple layers. You might also want to join the Phaser [Slack](https://phaser.io/community/slack) or [Discord](https://phaser.io/community/discord) where you could ask for more of a step-by-step breakdown of how to split you map into layers.

**Comment by Telokis** [comment]
Yes, I am using Tiled.
However, the player's depth is dynamic (let's say it's `player.depth = player.y`) so I have to set the layers' depths to at least the map's height in order for the player to never be able to step in front of it. Am I right?
This is a good solution before I make my own Tilemap GameObject to handle it better! Thank you !

**Comment by photonstorm** [comment]
Layers have a depth property, just like sprites, so you can change them dynamically as needed. You just can’t do it on a per tile per layer basis.

**Comment by photonstorm** [comment]
Just to say that the feature of tile draw orders has been implemented and is now in the master branch.

**Comment by Telokis** [comment]
@photonstorm Wow! That's nice! Is there a doc available for it? Or just a method name I should find in the code to get started understanding it, please? (Not scared of your code, I've read it a lot! :) )

**Comment by photonstorm** [comment]
@Telokis if you use Tiled it'll just pick it up automatically from the map data. If you don't, you can use the `setRenderOrder` method (either on the map, or on a layer)

**Comment by amemn** [comment]
Hey @Telokis did you manage to find a workaround short of implementing your own tilemap?

**Comment by Telokis** [comment]
> Hey @Telokis did you manage to find a workaround short of implementing your own tilemap?

I haven't gone back to working on the map as of yet. I plan to rebuild the Tilemap to be able to handle this specific issue as well as some other things I want.
