### ISSUE TITLE
[Feature Request] I need to skew my image

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#3911]
is this possible? I think this is a basic transform feature?

**Comment by jcyuan** [comment]
or please provide raw operation on GameObject's matrix, thank you very much.

**Comment by jcyuan** [comment]
@photonstorm thanks for replying, actually I'm integrating DragonBones into Phaser3, and all things done except skew. an object to attach to a slot will be a GameObjects.Image or GameObjects.Container, so which is the best way to implement this? to use mesh I think (although currently mesh does not have indices but still ok for the basic display - DragonBones advanced functionality uses vertex grid which needs indices to do disortion etc).

**Comment by jcyuan** [comment]
a high advantage that I use GameObjects.Image to attach to a slot is that it's very easy to get animation work, just set new frame for it that's enough, If use Mesh I need to figure out how to implemenet this, let me have a review in the source code.

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
