### ISSUE TITLE
Fill rounded rectangle look weird in CANVAS type game

### ISSUE THREAD

**Issue by valse** [photonstorm/phaser#3912]
## Version

* Phaser Version: 3.12.0-beta2

* Operating system: Windows 10

## Description

`fillRoundedRect` method draws weird in CANVAS type:

CANVAS:
![img1](https://user-images.githubusercontent.com/1492995/43966910-6a8babaa-9cc3-11e8-8e51-6c88936b6b3d.png)

WEBGL:
![img2](https://user-images.githubusercontent.com/1492995/43966929-7924723c-9cc3-11e8-9e7d-360276266d8a.png)

## Example Test Code

http://labs.phaser.io/view.html?force=Canvas&v=dev&src=src/game%20objects/graphics/fill%20rounded%20rectangle.js

**Comment by TadejZupancic** [comment]
[Here's](https://github.com/photonstorm/phaser/pull/3755) my comment on this

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
