### ISSUE TITLE
Drag and Bounce: Odd behavior when colliding with other body which has world boundary close to it

### ISSUE THREAD

**Issue by raphaklaus** [photonstorm/phaser#3914]
Scenario:

1) Moving a body (let's call it as `actor`) with X velocity of `-800`
2) `setBounce(1,0)` and `setDrag(420, 0)`
3) The other body (let's call it something like, `extra-world-boundary`) is immovable and don't allow gravity.
4) Actor is anchor point at 0,0 of its image/graphic
5) Position:150,150
6) World gravity active. 
7) `setCollideWorldBounds` as true.

Problem:
When the `actor` collide the `extra-world-boundary` due to it's high-speed reminiscent of the "weak" drag, it's way beyond the `extra-world-boundary` and even from the original world boundary. It causes the engine to calculate bouncing twice.

Firstly in the Separation logic: https://github.com/photonstorm/phaser/blob/d1f5f8a82b4a64d2a6a6a269e148232b51661a19/src/physics/arcade/SeparateX.js#L22

And secondly in the `checkWorldBounds`: https://github.com/photonstorm/phaser/blob/d1f5f8a82b4a64d2a6a6a269e148232b51661a19/src/physics/arcade/Body.js#L927

It results in the `actor` been stuck for a second in the `extra-world-boundary`. Ugly.

I think the engine could have a way to cleverly check it and don't re-bounce. Maybe in some scenario, it's nice to be able to handle bouncing with world boundary + bodies/tiles nicely.

In my case (I'm developing a game that has this border in all gameplay) I simply removed left, and right boundaries and keep with bottom and top using: `world.setBoundsCollision`

Hope this can help someone in the future or even help to elucidate some issues from this engine.

**Comment by hexus** [comment]
It would help if this could be reproduced minimally in JSBin, JSFiddle or Codepen.

**Comment by raphaklaus** [comment]
Sure. I'll work on it.

**Comment by raphaklaus** [comment]
Here it is: https://codepen.io/anon/pen/GBVOMd (Phaser 3.10.1)
https://codepen.io/anon/pen/qyepZo (Phaser 3.12.0)

Click for the first time and you should see the issue. Click for the second time, and it normally bounces.

**Comment by photonstorm** [comment]
Have tested this against 3.5 and I cannot reproduce the problem any longer. To be honest, I went back to 3.12 and it didn't happen with the following test in there either, despite having the same set-up. Even so, as this is a couple of years old now I don't expect you to check this out (or even respond), but I'm happy it's working even with really high velocities against immovable objects:

```js
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    backgroundColor: '#2d2d2d',
    physics: {
        default: 'arcade',
        arcade: {
            gravity: { y: 0 },
            debug: true
        }
    },
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('bar', 'assets/demoscene/raster-bw-64.png');
    this.load.image('block', 'assets/sprites/block.png');
}

function create ()
{
    var bar = this.physics.add.staticImage(0, 300, 'bar');

    var test = this.physics.add.image(100, 500, 'block');

    test.setBounce(1, 0);
    test.setDrag(420, 0);

    this.physics.add.collider(bar, test);

    this.input.on('pointerdown', pointer => {

        test.setVelocityX(-1800);

    });
}
```

**Comment by raphaklaus** [comment]
@photonstorm I've just replicated the error again in the last beta version. I believe you couldn't be able to reproduce because it only happens when the body is next to the wall. Here is a GIF:

![bug_gif](https://user-images.githubusercontent.com/901936/94798270-b12d6800-03e1-11eb-9ba8-4a02bf1c4546.gif)

To reproduce you have to click a few times and let that stop next to the wall, when clicked you will check the issue.

**Comment by photonstorm** [comment]
@raphaklaus you need to build a new version from the master branch. Is that what you tested against? The latest beta does not have this fix in it.

**Comment by raphaklaus** [comment]
I tried but I get error "Uncaught ReferenceError: Phaser is not defined" in the console. I don't receive this error in the beta version.
