### ISSUE TITLE
TouchManager.js:123 [Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

### ISSUE THREAD

**Issue by iKest** [photonstorm/phaser#3915]
I have error when tap on border canvas area.

Solve it by adding this to line 121 in TouchManager.js
Before:
```
if (this.capture)
        {
            event.preventDefault();
        }
```
After:
```
if (this.capture && event.cancelable)
        {
            event.preventDefault();
        }
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
