### ISSUE TITLE
TileLayer Light2D warning

### ISSUE THREAD

**Issue by Mursaat** [photonstorm/phaser#3917]
Hello,

I was running the code from that example (Chrome + Phaser v3.12.0-beta2) : https://labs.phaser.io/edit.html?src=src/loader/tile%20maps/load%20tile%20map%20json%20with%20normal%20map.js

But it seems line 47 (`layer.setPipeline('Light2D')` ) is causing some strange warnings : 
```
[.Offscreen-For-WebGL-000002AA428BB2D0]RENDER WARNING: there is no texture bound to the unit 1
```

Also the light around the pointer is not circular.

**Comment by photonstorm** [comment]
This has never actually worked (in any version of v3!) - will see about either removing the feature so it doesn't break, or fixing it properly.

**Comment by photonstorm** [comment]
The error with the example was it was using a Static Tilemap Layer. Lights only work with Dynamic Layers. I've updated the example to fix this, all good now.

**Comment by davidzwa** [comment]
I just saw this issue and saw the `Also the light around the pointer is not circular.` sidenote. I have this as well currently:

![image](https://user-images.githubusercontent.com/6005355/80420338-e7b70200-88da-11ea-879f-47678fcb89f2.png)

This is a light attached to the cursor, applied on an image with a plain-gray normal map of the same pixel size.
![menu2](https://user-images.githubusercontent.com/6005355/80420431-0cab7500-88db-11ea-936e-3cb0f64b8e8d.png) (Image) 
![menu2-normal](https://user-images.githubusercontent.com/6005355/80420450-12a15600-88db-11ea-859e-4bade64dacbb.png) (Normal map) 

## Repro function
This is converted to JS by hand. Should work, but only tested as TS.

```
function createLogo(imageName) {
    const x = this.width / 2; // Centered
    const y = this.height / 4; // Top of scene
    this.lights.enable();
    const light = this.lights.addLight(x, y, 130, 0x42b983, 1);

    this.input.on('pointermove', function (event) {
        light.x = event.x;
        light.y = event.y;
    });
    this.add
        .image(x, y, imageName)
        .setPipeline('Light2D');
}
```
