### ISSUE TITLE
Phaser 3.11.0 changing image alpha also changes text alpha for CANVAS type game

### ISSUE THREAD

**Issue by maximtsai** [photonstorm/phaser#3918]
## Version

* Phaser Version: 3.11.0

* Operating system: Windows 10

* Browser: Chrome, Firefox, IE, Edge (have not tested on Safari yet)

## Description

Changing the alpha value of an image also changes the alpha value of all text that is instantiated after the image. This only happens when using CANVAS mode.
Expected behavior: Changes to the alpha value of an image do not affect the alpha values of text.

## Example Test Code

```
var config = {
    type: Phaser.CANVAS,
    width: 400,
    height: 300,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('myImage', 'myimage.png');
}

function create ()
{
    var text1 = this.add.text(50, 20, "TEXT BEFORE IMAGE ", {fontFamily: 'Arial', fontSize: 30, color: '#FF0000'});
    var myImage = this.add.image(200, 150, 'myImage');
    myImage.alpha = 0.2;
    var text2 = this.add.text(50, 240, "TEXT AFTER IMAGE", {fontFamily: 'Arial', fontSize: 30, color: '#FF0000'});
    // text2 also becomes transparent even though its alpha value was never set
}
```
## Additional Information

![image](https://user-images.githubusercontent.com/6758316/44004879-1b2180e6-9e1f-11e8-8c5b-bacb18fe2590.png)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by maximtsai** [comment]
Thanks!
