### ISSUE TITLE
v3.12.0-beta2 Setting the "text" property on a "Text" GO, doesn't update the text properly

### ISSUE THREAD

**Issue by hackhat** [photonstorm/phaser#3919]
For example if I create a new text game object with the text "bye", then I set `myText.text = ''` it will remove all text, if I do `myText.text = 'hello'`, it will not show 'hello', it will show "bye"

**Comment by samid737** [comment]
reproducable:

http://jsfiddle.net/axu4Lqfk/

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
