### ISSUE TITLE
v3.12.0-beta2 BUG: Hit area broken if sprite is rotated and added to a container

### ISSUE THREAD

**Issue by hackhat** [photonstorm/phaser#3920]
Behaviour: HitArea is the NON rotated area of the pipe.

If I remove it from the container, hit are is fine!

To reproduce simply rotate the tileSprite and add it to a container, set a new displayHeight then hit area is broken.

Example code:

```

        const pipe = scene.add.tileSprite(midpoint.x, midpoint.y, Math.round(distanceBetweenPlanets), 64, 'pipe');
        this.containers.shipStreams.add(pipe);
        pipe.displayHeight = 24;
        pipe.rotation = pathSlope;
        pipe.setInteractive();
        pipe.on('pointerdown', () => {
        });

```

**Comment by hackhat** [comment]
To reproduce simply rotate the tileSprite and add it to a container, hit area is broken.

**Comment by photonstorm** [comment]
This is what a proper code example looks like:

```
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('mushroom', 'assets/sprites/mushroom2.png');
}

function create ()
{
    var container = this.add.container(400, 300);

    var image = this.add.tileSprite(0, 0, 512, 256, 'mushroom');

    // following line to try and replicate issue. Makes no difference with or without though
    image.displayWidth = 256;

    container.add(image);

    image.setInteractive();

    image.setAngle(20);

    image.on('pointerdown', function () {

        this.setTint(Math.random() * 16000000);

    });
}
```

I had to spend time creating this example to test the issue, only to find it works fine.

So please, if you're going to report something, reproduce it first and post a complete example, as all this has really done is waste a bit of both our time. The combination of a container + a rotated TileSprite isn't the cause of whatever you were seeing, so there must be another factor.

**Comment by hackhat** [comment]
Hi, actually the key is to have different `displayWidth` than you originally set (my bad I didn't notice that was the important thing). Change your example to `image.displayWidth = 128;` or some other number. At the moment I can reproduce if:

 - starts with 32
 - then `displayHeight = 24;`

Code again here:

          const pipe = scene.add.tileSprite(fromPoint.x, fromPoint.y, fromPlanet.radius + 32 * 4, 32, 'pipe');

          pipe.displayHeight = 24;
          this.containers.shipStreams.add(pipe);
          pipe.rotation = pathSlope;
          pipe.setInteractive({cursor: 'pointer'});



Hit area is highlighted here:
![image](https://user-images.githubusercontent.com/11173732/44312003-f4a40280-a423-11e8-98c2-043a164c6305.png)

Would you mind allowing other people to re-open an issue?

**Comment by chaping** [comment]
I have the same problem as @hackhat ,and it’s very easy to reproduce this problem,just go to the Phaser3's official example page:[https://labs.phaser.io/edit.html?src=src/game%20objects/container/rotated%20input%20test.js](url)
the code is
```
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#010101',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('buttonBG', 'assets/sprites/button-bg.png');
    this.load.image('buttonText', 'assets/sprites/button-text.png');
}

function create ()
{
    var bg = this.add.image(0, 0, 'buttonBG').setInteractive();
    var text = this.add.image(0, 0, 'buttonText');

    var container = this.add.container(400, 300, [ bg, text ]);

    container.setAngle(20);  // change the angle here from 20 to 150

    this.tweens.add({
        targets: text,
        alpha: 0.5,
        duration: 1000,
        ease: 'Sine.easeOut',
        yoyo: true,
        repeat: -1
    });

    bg.on('pointerover', function () {
        this.setTint(0x44ff44);
    });

    bg.on('pointerout', function () {
        this.clearTint();
    });

    bg.once('pointerup', function () {
        this.tweens.add({
            targets: container,
            y: 900,
            duration: 500
        });
    }, this);
}
```
then change the code on line 28 from `container.setAngle(20);` to `container.setAngle(150);` and rerun it.
You will see some parts of the button have no effect on the input,and I found that it only works fine from -90 to 90 degrees.
Is it a bug of Phaser3's container?

**Comment by photonstorm** [comment]
@hackhat the code I posted above _does_ have a different `displayWidth` compared to what was originally set for the Tile Sprite.

@chaping thank you! That's the actual problem in a nutshell. Now I've something to work from.

**Comment by hackhat** [comment]
@photonstorm well you changed the width, not the height. Anyway looks like I can reproduce with the code I sent to you.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
