### ISSUE TITLE
v3.12.0-beta2 GameObjects.Text default origin is 0,0 instead of 0.5, 0.5 that is in docs.

### ISSUE THREAD

**Issue by hackhat** [photonstorm/phaser#3924]

**Comment by photonstorm** [comment]
This doesn't appear possible to override. JSDoc is taking it from the parent component, as it should be, but trying to add `originX` definitions directly to the Text class, jsdoc just ignores them.

I've tried an [@override](http://usejsdoc.org/tags-override.html) tag, `@augments` and all sorts but the component seem to have priority and replace the class level property docs no matter what. What it needs is the opposite of [@inheritdoc](http://usejsdoc.org/tags-inheritdoc.html) but I can't find one.
