### ISSUE TITLE
scene.stop() does not seem to "reset" camera

### ISSUE THREAD

**Issue by sftsk** [photonstorm/phaser#3925]
`Phaser 3.12.0-beta2` `macOS 10.13` `Safari 11.0`

## Description

I have a scene with a camera pan effect that "scrolls" into view from the top when starting. If I start the scene a second time, all the sprites I place within have the wrong coordinates (y coordinates are off). It seems like although I do a `scene.stop()` and then a `scene.start()` it still keeps some values from the `scrollY` of the first scene start.

I would expect the scene to behave exactly the same every single time I start it. I have tried running `camera.resetFX()` and `camera.resetBounds()` but that does not seem to help :(

## Example Test Code

```
create () {
  this.cameras.main.setBounds(0, 0, 500, 2000, false);
  this.cameras.main.pan(250, 2000, 500, 'Sine.easeInOut');
}
```

## Additional Information

Any help is very appreciated!

**Comment by photonstorm** [comment]
Do you have an example test case for this I can run? If you stop a Scene it will destroy all Camera's currently held in the Camera Manager. If you start a Scene, it will create them all from scratch again, so there should be nothing left over. Unless the Scene didn't have a chance to clear itself down before being started again perhaps? (hard to tell without a test really)

**Comment by samid737** [comment]
includes a scene.stop() and scene.start() and above pan:

http://jsfiddle.net/zu2qg067/7/

@sftsk does the problem appear in the above example?

**Comment by sftsk** [comment]
Sorry, my bad and thank you for the help.

I've had some additional logic in my code that added to the `y` coordinate every single time I've started the scene (and was persistent across calls). As I couldn't figure that out and after a lot of debugging I could only see the camera having a different `scrollY` on consecutive calls so I thought the problem might be there. All is good now!

Sorry again, thank you for the help!
