### ISSUE TITLE
Game Resize / Image Resize issue in 3.12 Beta

### ISSUE THREAD

**Issue by Mursaat** [photonstorm/phaser#3928]
Hello,

On that example, i'm using Phaser 3.11.0 : https://jsfiddle.net/s3La9crn/
When you resize the window at the bottom right, you can see that the sprite fits the maximum available space in the window. 

Now check the same example, with Phaser 3.12.0 : https://jsfiddle.net/d08e4v7q/
The behavior is different and strange.

Maybe I'm not doing this the right way, but it sounds more like an issue.

(I have the same problem with a tilemap instead of a sprite)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
