### ISSUE TITLE
v3.12.0-beta2 camera.pan vs camera.scrollXY produce different results

### ISSUE THREAD

**Issue by hackhat** [photonstorm/phaser#3930]
This will not scroll by x and y amount after 1 second.

        mainCamera.pan(x, y, 1000);

if I do this code instead

        mainCamera.scrollX = x;
        mainCamera.scrollY = y;

It will scroll to x and y

Code:

    var config = {
      type: Phaser.AUTO,
      parent: 'phaser-example',
      width: 800,
      height: 600,
      pixelArt: true,
      physics: {
        default: 'arcade',
      },
      scene: {
        preload: preload,
        create: create,
        update: update
      }
    };
    
    var game = new Phaser.Game(config);
    
    function preload ()
    {
      this.load.image('map', 'assets/tests/camera/earthbound-scarab.png');
    }
    
    function create ()
    {
      this.cameras.main.setBounds(0, 0, 1024, 2048);
    
      this.add.image(0, 0, 'map').setOrigin(0);
    
      this.cameras.main.setZoom(4);
      this.cameras.main.centerOn(0, 0);
    
      console.log(this.cameras.main.getScroll(767, 1096));
    
      text = this.add.text(304, 230).setText('Click to move').setScrollFactor(0);
      text.setShadow(1, 1, '#000000', 2);
    
      var pos = 0;
    
      this.input.on('pointerdown', function () {
    
        var cam = this.cameras.main;
    
        if (pos === 0)
        {
          cam.scrollX = 767
          cam.scrollY = 1096
          pos++;
        }
        else if (pos === 1)
        {
          cam.pan(767, 1096, 2000, 'Power2');
          pos++;
        }
        else if (pos === 2)
        {
          cam.scrollX = 767
          cam.scrollY = 1096
          pos++;
        }
    
      }, this);
    }
    
    function update ()
    {
      var cam = this.cameras.main;
    
      text.setText(['Click to move', 'x: ' + cam.scrollX, 'y: ' + cam.scrollY ]);
    }

I tried to save the example, but nothing happens, so I pasted the code here.

**Comment by samid737** [comment]
http://jsfiddle.net/g2my3Lah/

**Comment by photonstorm** [comment]
`Camera.pan` moves the camera so that its viewport is _centered_ on the given coordinates. This is not the same as `scrollX/Y`, which doesn't represent the center of the camera. So giving the same values to both properties would give very different results.

**Comment by hackhat** [comment]
> setScroll(x [, y]) Set the position of where the Camera is looking within the game.

> pan(x, y [, duration] [, ease] [, force] [, callback] [, context]) This effect will scroll the Camera so that the center of its viewport finishes at the given destination, over the duration and with the ease specified.

So scroll changes what exactly? because from the docs you specify center on the pan, but on the scroll you don't say which part. Is top left of the camera?

**The strange thing is that, when I do `scroll` it actually centers the camera on that object... With pan it centers, but adds a few 100s of pixels both on x and y axis.**
