### ISSUE TITLE
Problems with sound

### ISSUE THREAD

**Issue by thanh-taro** [photonstorm/phaser#3932]
Hi, thanks for good work on Phaser 3.12-beta2.

It's me again. Today, I found some problems about playing sounds:
1. On Android (not tested on iOS yet) that was built with cordova, when I press the Home button while I'm on the game, the sounds is still playing on background. I think it should pause and resume after I re-enter the game again.
2. When playing the same sound many times while it's already playing, sound's volume seams increasing exponentially (louder and louder until it ends).

I don't know these problems are bugs or just features. If they are features, how can we disable them?

I also got a notice about autoplay on Chrome that may affect to the engine:
```The Web Audio autoplay policy will be re-enabled in Chrome 70 (October 2018). Please check that your website is compatible with it. https://goo.gl/7K7WLu```

**Comment by thanh-taro** [comment]
I'll reproduce and give you soon.

**Comment by paulrbt** [comment]
In regards to the sound playing in the background of a Cordova app that has been paused, that's something that has to be handled in the logic of your Cordova app and is not a Phaser issue.  You can set up event listeners (for 'backbutton' and 'pause') to stop all playing audio.

**Comment by Nishanth14293** [comment]
hi @thanh-taro, i am also facing this same issue.did you found any solution for that, please me know

**Comment by thanh-taro** [comment]
Thank you @paulrbt. I did it by listen on onPause and onResume event of cordova (pause all sound and resume again via Phaser). Here is my code:

```js
let app = {
    initialize: function () {
      document.addEventListener('deviceready', this.onDeviceReady.bind(this), false)
      document.addEventListener('pause', this.onPause.bind(this), false)
      document.addEventListener('resume', this.onResume.bind(this), false)
    },
    onDeviceReady: function () {
      // When the device is ready, start Phaser Boot state.
      startGame()
    },
    onPause: function () {
      window.game.sound.pauseAll()
    },
    onResume: function () {
      window.game.sound.resumeAll()
    }
  }

  app.initialize()

  // note: window.game is my phaser game instance
```

**Comment by thanh-taro** [comment]
@Nishanth14293 About the issue number 2, I faced the problem when I use `BaseSoundManager.play(soundKey)` function. Change it to `BaseSoundManager.add(soundKey).play()` instead and the problem solved.

**Comment by thanh-taro** [comment]
I forgot to give the example code for the issue number 2. But as I said above, when using `BaseSoundManager.play(soundKey)` many times, the sound's volume get louder and louder.

**Comment by photonstorm** [comment]
Glad you managed to resolve this one in the end!
