### ISSUE TITLE
WrapDegrees Does Not Work

### ISSUE THREAD

**Issue by codyseibert** [photonstorm/phaser#3933]
## Version
* Phaser Version: 3.12.0-beta2
* Operating system: MacOs High Sierra 10.13.4
* Browser: All

## Description
Phaser.Math.Angle.WrapDegrees returns the exact value passed in, but it should convert radians to degrees.

## Example Test Code
Phaser.Math.Angle.WrapDegrees(Math.PI) // 3.1415926535897825
Phaser.Math.Angle.WrapDegrees(2) // 2

https://codepen.io/seibertsoftwaresolutions/pen/xJoLvN?editors=1111

## Additional Information
The proper formula should probably be:
```
function WrapDegrees(angle) {
  return angle * 180 / Math.PI
}
```

**Comment by TadejZupancic** [comment]
I think you are looking at [the wrong function](https://photonstorm.github.io/phaser3-docs/Phaser.Math.Angle.html#.WrapDegrees__anchor) for conversion to degrees

**Comment by hexus** [comment]
Yes, use the [`Phaser.Math.RadToDeg`](https://photonstorm.github.io/phaser3-docs/Phaser.Math.html#.RadToDeg__anchor) function.

`WrapDegrees` simply clamps an angle in degrees between `-180` and `180`, there is no conversion.
