### ISSUE TITLE
Pixel-perfect hit test doesn't work correctly with atlas files

### ISSUE THREAD

**Issue by goldfire** [photonstorm/phaser#3938]
## Version

* Phaser Version: 3.12.0-beta2

* Operating system: macOS 10.13.5

* Browser: Chrome 68.0.3440.106

## Description

The `pixelPerfect` option in `setInteractive` works perfectly in the demos because they are single textures. However, when using this with a sprite from an atlas, it runs into issues. One of those issues if fixed with this PR: https://github.com/photonstorm/phaser/pull/3937 (it wasn't getting the frame name) The other issue I'm having trouble solving.

The other issue is that the hit test is performed on the entire atlas rather than the area that contains the specified frame. The easiest way to explain is to look at the below codepen. Just hover around and whenever the hit test is positive, the alpha on the sprite will change. It should only change when hitting the actual pixels of the sprite, but it also changes when hitting other pixels on the atlas texture that aren't part of the game object.

Bug Demo: https://codepen.io/goldfire/pen/GBbwrG

I attempted to fix this by updating [CreatePixelPerfectHandler](https://github.com/photonstorm/phaser/blob/master/src/input/CreatePixelPerfectHandler.js) with a `hitArea` check like so:

```javascript
if (hitArea instanceof Phaser.Geom.Rectangle && !Phaser.Geom.Rectangle.Contains(hitArea, x, y))
{
    return false;
}
```
However, the `hitArea` is getting cleared when `pixelPerfect` is set, and even setting `hitArea` directly after the fact didn't fully fix the issue (I'm guessing there might still be issues with trimming, etc?).

**Comment by photonstorm** [comment]
This looks like it is working correctly in Beta 3 now. I created a test that used a trimmed atlas frame and pixel perfect clicks are happening as I'd expect now. You can find the test below but it's also in the Labs in the 'input / pixel perfect' folder:

```
var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#efefef',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.atlas('megaset', 'assets/atlas/megaset-0.png', 'assets/atlas/megaset-0.json');
}

function create ()
{
    var sprite = this.add.sprite(400, 300, 'megaset', 'mask-test2').setInteractive({ pixelPerfect: true });

    var text = this.add.text(10, 10, 'Click the sprite', { font: '16px Courier', fill: '#000000' });

    this.input.on('pointerdown', function () {

        text.setText('');

    });

    sprite.on('pointerdown', function () {

        text.setText('Clicked Sprite');

    });
}
```

Unless you can spot anything wrong?

**Comment by goldfire** [comment]
This is not fixed, the PR I made for the atlas frame was only part of the problem. The below video shows me testing this new demo with the latest master. As you can see, clicking in random areas on the screen triggers it, and this is obviously because the other sprites in the atlas that are outside of this frame are triggering it.

https://streamable.com/yqczh

**Comment by photonstorm** [comment]
Have updated the method so that the x/y is always within the frame dimensions, which fixes the issue shown in the video. Still needs testing on an atlas frame with a buttload of space trimmed off it though.

**Comment by goldfire** [comment]
It is definitely better, though as you mentioned, still off if you use trimming (which we do). I can confirm the demo you posted without trimming is working correctly now.

**Comment by photonstorm** [comment]
The frame in the demo is trimmed, just not by much, which is why it still looks ok I think.

**Comment by photonstorm** [comment]
There we go, works properly now, trimmed or not.

**Comment by goldfire** [comment]
Thanks so much, working perfectly now!
