### ISSUE TITLE
v3.12.0-beta2 "tileSprite.anchorX = 0" breaks hit area

### ISSUE THREAD

**Issue by hackhat** [photonstorm/phaser#3939]
const pipe = scene.add.tileSprite(x, y, width, height, 'pipe');
          pipe.originX = 0;

Hit area becomes this one:

![image](https://user-images.githubusercontent.com/11173732/44262386-7261e580-a24d-11e8-9655-08a63684d3e5.png)

**Comment by photonstorm** [comment]
Full test:

```
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('mushroom', 'assets/sprites/mushroom2.png');
}

function create ()
{
    var image = this.add.tileSprite(200, 100, 512, 256, 'mushroom');

    image.setInteractive();

    image.setAngle(20);

    image.setOrigin(0);

    image.on('pointerdown', function () {

        this.setTint(Math.random() * 16000000);

    });
}
```

Works fine, regardless of which value is given to `setOrigin`, meaning the cause of this issue is something else not evident from the code given above. If you can isolate it, post it and I'll re-open.

**Comment by hackhat** [comment]
Reproduced here: https://codepen.io/anon/pen/RYwpBq?editors=1010

I wonder if there is a simpler to put this code as phaser labs is broken or so slow it doesn't work.

Code:

    var config = {
        type: Phaser.AUTO,
        width: 800,
        height: 600,
        parent: 'phaser-example',
        scene: {
            preload: preload,
            create: create
        }
    };

    var game = new Phaser.Game(config);

    function preload ()
    {
        this.load.image('mushroom', 'https://labs.phaser.io/assets/sprites/mushroom2.png');
    }

    function create ()
    {
        var image = this.add.tileSprite(100, 100, 50, 100, 'mushroom');
        image.originX = 0;
        image.setInteractive({cursor: 'pointer'});

        //image.setAngle(20);

        //image.setOrigin(0);

        image.on('pointerdown', function () {

            this.setTint(Math.random() * 16000000);

        });
    }
