### ISSUE TITLE
Lack of camerafadefromcomplete event

### ISSUE THREAD

**Issue by raphaklaus** [photonstorm/phaser#3943]
Fade in/out has their proper events. Unfortunately, `fadeFrom` hasn't. The event emit only checks for fade in or out, as you can see here: https://github.com/photonstorm/phaser/blob/a3c4c605197c189ccbb46311c0dccdddabd33de3/src/cameras/2d/effects/Fade.js#L391

**Comment by hexus** [comment]
`fadeFrom` doesn't need another event. It triggers both of these events still. If you observe the calling code in `Camera#fadeIn`, `Camera#fadeOut` and `Camera#fadeFrom`, you can see how the `Fade` class is used.

`camerafadeincomplete` is the event you need to listen to when using `fadeFrom`.

**Comment by raphaklaus** [comment]
Thank you for the explanation. It's enough so far. Closing the issue.
