### ISSUE TITLE
3D Camera: add() does not add Sprite3D to displayList or updateList

### ISSUE THREAD

**Issue by vvega** [photonstorm/phaser#3945]
## Version

* Phaser Version: v3.11.0

* Operating system: OS X El Capitan - 10.11.6

* Browser: Any

## Description

The create() method creates, and then adds the new Sprite3D to the displayList and updateList. However, when leveraging add() to supply the camera with an existing Sprite3D instance, it is left out of these lists and doesn't render.

## Example Test Code
Codepen [here](https://codepen.io/veronica-vega/pen/rrXqBK).

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
