### ISSUE TITLE
Cropped sprites behave unexpectedly when recropped

### ISSUE THREAD

**Issue by lgibson02** [photonstorm/phaser#3948]
- Phaser Version: 3.11
- Operating System: Windows 7 Professional x64
- Browser: Firefox Developer Edition 62.0b13 x64

I have noticed while working on a project of mine that if you use .setCrop on an already cropped sprite, all other cropped sprites will also be affected. Here's a small demo to try and show this:

    var config = {
	    type: Phaser.AUTO,
	    width: 800,
	    height: 600,
	    backgroundColor: '#2d2d2d',
	    parent: 'phaser-example',
	    scene: {
	        preload: preload,
	        create: create
	    }
	};

	var group;

	var game = new Phaser.Game(config);

	function preload()	{
	    this.load.spritesheet('diamonds', 'diamonds32x24x5.png', { frameWidth: 32, frameHeight: 24 });
	}

	function create() {
	    group = this.add.group();
	    group.createMultiple({ key: 'diamonds', frame: [0,1,2,3,4], frameQuantity: 2, repeat: 1 });
	    group.children.iterate(function(child) {
	    	child.setCrop(0, 0, 32, 32);
	    });
	    group.children.entries[10].setCrop(0, 0, 32, 8);
	    Phaser.Actions.SetXY(group.getChildren(), 32, 100, 32);
	}

To start off with .setCrop(0, 0, 32, 32) is ran on all children of the group, I don't believe this should have any immediately visible effect. However, strangely the frame is set to four (the last of the sprite sheet).

So this is what I would have expected:
![Image 1](https://i.imgur.com/URUKRWO.png)
This is what I actually got:
![Image 2](https://i.imgur.com/BhDvWMt.png)

After this the 10th child of the group is cropped with .setCrop(0, 0, 16, 16) which I would think would make it so you could only see a quarter of that particular sprite. But for some reason all the sprites in the group are cropped this way instead of just the one.

So in end what I would expect to see is this:
![Image 3](https://i.imgur.com/ozIMlag.png)
What I actually end up with is this:
![Image 4](https://i.imgur.com/Vpux1eZ.png)

If you need any more information for this issue, please let me know.

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
