### ISSUE TITLE
Light enabled objects are not being rendered when far enough from a light source

### ISSUE THREAD

**Issue by imilo** [photonstorm/phaser#3953]
## Version

* Phaser Version: 3.11
* Operating system: Linux
* Browser: Tested on Chromium and Firefox

## Description

When light source is far enough from the visible object - it is not being rendered (like is fully transparent).

I've noticed it depends on the light X/Y coordinates, light radius, canvas width/height - manipulating any of them can cause the object to become invisible.

## Example Test Code

JSFiddle: https://jsfiddle.net/ag3r8nm1/29/

In the initial state you can see a flare, it is being lighted by the light. Now try to comment out **line 30** and uncomment **line 31** - flare disappears, but the only thing has changed is light's X position a little. Now go back to the initial state and comment out **line 3** and uncomment **line 4** - flare again will disappear and the only thing has changed is canvas width by 100px.

## Additional Information

In my environment world (tilemap) size is **6400x3200**. To make my image visible in any map's place I have to put an extra light source at map center and set it's radius to **3200** - only then with the smallest window size everything is still visible. But I believe this is a big overhead to add such a big light source. You can notice it is the same as map's **width/2**. If I set it to **3100** then the image is invisible when is near the map corners.

**Comment by photonstorm** [comment]
If the sprite isn't close enough to a light source then it won't render, i.e. if it's outside the radius of the light. Why not just position a light in the center of the camera and move it as the camera moves?

**Comment by imilo** [comment]
If this is an expected behavior, than thanks for explanation. Just one more question about fixing my issue - what is more efficient in Phaser internally:

1. positioning a light in the center of the camera and moving it as the camera moves. Light will have smaller radius, but we'll need to set it's X/Y location on every frame.
2. creating a static light in the center of the map with a much bigger radius to cover the whole map. No need to move it, but the size is much bigger.

**Comment by photonstorm** [comment]
It depends what kind of effect you want to achieve. A small light with the camera will have a consistent falloff at the edges, where-as one massive one will have a much wider fall-off, meaning areas on the extreme edges will look much darker than those in the middle, because of the combination of a larger radius and intensity setting.

You could always just use the `setAmbientColor()` method so that your Scene always has a light source (from no fixed position), so Sprites always render.

**Comment by imilo** [comment]
@photonstorm , what I want to achieve is to prevent objects to disappear from player's screen. And by "efficient" I meant CPU/Memory efficient. So you recommend to use a moving smaller light source in front of camera?

**Comment by photonstorm** [comment]
It will make no difference to processing as it's still just 1 light. One is tiny, the other is large. I would use a small light tracked to the camera to keep the style consistent.
