### ISSUE TITLE
Camera pan effect is not working if you create one game and then create another game.

### ISSUE THREAD

**Issue by hackhat** [photonstorm/phaser#3954]
v3.12.0-beta2

I know is a bit of an edge case but:

 - Create game
 - Note that I don't destroy the game here
 - camera.pan
 - Remove canvas
 - Create game again
 - camera.pan

Now the camera doesn't pan anymore. I have a feeling there is some code that acts like a singleton, somehow unexpectedly.

If I do `game.destroy` it will work fine.

I know it will not really be fixed, but this issue is to investigate a bit deeper as it seems something wrong is going on there.

**Comment by photonstorm** [comment]
You don't state how you're removing the canvas, but with the following the second game instance works and pans just fine, even with the first one still present, just the canvas removed from the DOM. You can also find this test in the labs in the 'bugs' folder (as `multi pan.js`)

```
var config2 = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        preload: preload2,
        create: create2
    }
};

function preload2 ()
{
    this.load.image('map', 'assets/tests/camera/earthbound-scarab.png');
}

function create2 ()
{
    this.cameras.main.setBounds(0, 0, 1024, 2048);
    
    this.add.image(0, 0, 'map').setOrigin(0);

    this.cameras.main.centerOn(0, 0);

    this.add.text(0, 0).setText('Game 2').setScrollFactor(0).setShadow(1, 1, '#000000', 2);

    var pos = 0;

    this.input.on('pointerdown', function () {

        var cam = this.cameras.main;

        if (pos === 0)
        {
            cam.pan(767, 1096, 2000, 'Power2');
            pos++;
        }
        else if (pos === 1)
        {
            cam.pan(703, 1621, 2000, 'Elastic');
            pos++;
        }
        else if (pos === 2)
        {
            cam.pan(256, 623, 2000, 'Sine.easeInOut');
            pos++;
        }
        else if (pos === 3)
        {
            cam.pan(166, 304, 2000);
            pos++;
        }
        else if (pos === 4)
        {
            cam.pan(624, 158, 2000);
            pos++;
        }
        else if (pos === 5)
        {
            cam.pan(680, 330, 2000);
            pos++;
        }
        else if (pos === 6)
        {
            cam.pan(748, 488, 2000);
            pos++;
        }
        else if (pos === 7)
        {
            cam.pan(1003, 1719, 2000);
            pos = 0;
        }

    }, this);
}

var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

function preload ()
{
    this.load.image('map', 'assets/tests/camera/earthbound-scarab.png');
}

function create ()
{
    this.cameras.main.setBounds(0, 0, 1024, 2048);
    
    this.add.image(0, 0, 'map').setOrigin(0);

    this.cameras.main.centerOn(0, 0);

    this.add.text(0, 0).setText('Game 1').setScrollFactor(0).setShadow(1, 1, '#000000', 2);

    var pos = 0;

    this.input.on('pointerdown', function () {

        var cam = this.cameras.main;

        if (pos === 0)
        {
            cam.pan(767, 1096, 2000, 'Power2');
            pos++;
        }
        else if (pos === 1)
        {
            cam.pan(703, 1621, 2000, 'Elastic');
            pos++;
        }
        else if (pos === 2)
        {
            this.game.canvas.parentNode.removeChild(this.game.canvas);

            var game2 = new Phaser.Game(config2);
        }

    }, this);
}

var game1 = new Phaser.Game(config);
```

**Comment by hackhat** [comment]
I use react and change a route. It will destroy the canvas element completely (without calling `game.destroy()`). Then will create another canvas and another game instance. This second game instance

Updated steps:

- Create game
- Note that I don't destroy the game here
- camera.pan
- **Remove canvas from dom completely (I think phaser game instance will still have a reference to that)**
- **Add another canvas element**
- Create game again **with the new canvas element**
- camera.pan

**Comment by photonstorm** [comment]
Exactly how does React 'remove the canvas from the dom completely' ? As all the other steps are the same.

**Comment by hackhat** [comment]
I'm not really sure, they use "the fastest way to remove" https://reactjs.org/docs/reconciliation.html

What ways are there to remove the element? I guess this is the way https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove

`parent.removeChild(child);` or `element.remove()`, I can't tell which one. But probably will do this higher up in the dom hierarchy.

**Comment by photonstorm** [comment]
This is exactly what the example above does (it's literally the only way to request the browser removes something from the DOM. It's still up to the browser when it actually happens though! React may do something extra to await the removal, who knows)

The Device and Global Plugins are the only singletons in Phaser because I made sure from the start that you could run multiple Phaser games at the same time on the same page. As they all use their own canvas objects to allow this. The only way I could see React bodging it up would be if it tried to use the same Canvas for the 2nd game instance.

**Comment by hackhat** [comment]
>  The only way I could see React bodging it up would be if it tried to use the same Canvas for the 2nd game instance.

Yes there is chance for that to happen actually... They can reuse the dom elements.

**Comment by photonstorm** [comment]
Thank you for opening this issue, however, I'm going to close it off now as there has been no progress made on this issue in quite some time, and sadly no contributions from anyone else to help fix it. I'm sorry we couldn't resolve it in this case.
