### ISSUE TITLE
BUG: Render texture is cropped if draw after a bit of time [code example & reproducible]

### ISSUE THREAD

**Issue by hackhat** [photonstorm/phaser#3958]
Example: https://codepen.io/anon/pen/RYwpBq?editors=0010
![image](https://user-images.githubusercontent.com/11173732/44364645-225b7b00-a4fa-11e8-90a6-4bae8996f628.png)

Note changing the width and height of the game config will increase this area.

Even this hack will kind of fix it, but the width and height has to match the render texture width and height, otherwise the clipped area increases just a bit (so strange):

     // scene.game.config.width = 15000;
     // scene.game.config.height = 15000;

Note: **Something very strange happens. So basically I was playing with it and was working outside the cropped area. Now is not working anymore, no code change. I wonder if is a chrome bug or memory related issue?**

The thing is that if you draw something in the create method, or in the update method (here only works once) it renders outside the crop area like this:

![image](https://user-images.githubusercontent.com/11173732/44364920-d52bd900-a4fa-11e8-9423-f81fb7f56527.png)

In the update method renders once outside the render method:
![image](https://user-images.githubusercontent.com/11173732/44365137-77e45780-a4fb-11e8-8421-47738283cb32.png)

Code:
 
      var config = {
          type: Phaser.AUTO,
          parent: 'phaser-example',
          width: 800,
          height: 600,
          scene: {
              preload: preload,
              create: create,
              update: update
          }
      };

      var rt1;
      var rt2;

      var game = new Phaser.Game(config);

      function preload ()
      {
          this.load.image('bunny', 'https://labs.phaser.io/assets/sprites/bunny.png');
          this.load.image('grid', 'https://labs.phaser.io/assets/sprites/128x128-v2.png');
      }

      function create ()
      {
          this.bunny = this.textures.get('bunny').get();
          //this.gridImage = this.add.image(0, 0, 'grid').setVisible(false).setOrigin(0);

          rt1 = this.add.renderTexture(0, 0, 1024, 1024);
          //rt1.draw(this.bunny, 0, 0);
          //rt1.draw(this.gridImage, 128, 0);
          //rt1.draw(this.gridFrame, 256, 0);

          rt1.draw(this.bunny, 0,0);
          rt1.draw(this.bunny, 555,555);
          this.cameras.main.zoom =0.5

          // rt2 = this.add.renderTexture(200, 200, 800, 600);
          // rt2.draw(bob, 200, 200);
          // rt2.draw(rt2, 0, 0);
      }
      let i = -100;
      function update ()
      {
          rt1.draw(this.bunny, 666 + i, 666+ i);
         // this.cameras.main.scrollX++;
          rt1.draw(this.bunny, i++, i++);
          //rt.camera.rotation -= 0.01;
          // rt.clear();
           //rt.draw(graphics, 0, 0);
      }

Another example (remove the setTimeout and notice how it renders outside of the crop area)

      var config = {
          type: Phaser.AUTO,
          parent: 'phaser-example',
          width: 800,
          height: 600,
          backgroundColor: 0x2d2d2d,
          scene: {
              preload: preload,
              create: create,
              update: update
          }
      };

      var rt;
      var graphics;
      var offset;

      var game = new Phaser.Game(config);

      function preload ()
      {

                this.load.image('bunny', 'https://labs.phaser.io/assets/sprites/bunny.png');
          this.load.atlas('megaset', 'assets/atlas/megaset-0.png', 'assets/atlas/megaset-0.json');
      }

      function create ()
      {
                this.bunny = this.textures.get('bunny').get();
          rt = this.add.renderTexture(0, 0, 800, 800);
          this.cameras.main.zoom = 0.5

          var atlasTexture = this.textures.get('megaset');

          var frames = atlasTexture.getFrameNames();

      setTimeout(()=>{

          for (var i = 0; i < frames.length; i++)
          {
              var x = Phaser.Math.Between(0, 800);
              var y = Phaser.Math.Between(0, 600);

              rt.drawFrame('megaset', frames[i], x, y);
              rt.draw(this.bunny, x, y)
          }
      }, 0)

          graphics = this.add.graphics();

          var cropWidth = 290;
          var cropHeight = 120;

          offset = rt.getTopLeft();

          this.input.on('pointermove2', function (pointer) {

              rt.setCrop(
                  (pointer.x - offset.x) - cropWidth / 2,
                  (pointer.y - offset.y) - cropHeight / 2,
                  cropWidth,
                  cropHeight
              );
          });
      }

      function update ()  
      {
          //graphics.clear();
          //graphics.lineStyle(1, 0x00ff00);
          //graphics.strokeRect(offset.x + rt._crop.x, offset.y + rt._crop.y, rt._crop.width, rt._crop.height);
      }

**Comment by photonstorm** [comment]
Internally a Render Texture creates a Frame Buffer Object. FBO maximum sizes are GPU dependent, so it'll always 'crop' a Render Texture to this max size, regardless.

https://webglstats.com/webgl/parameter/MAX_RENDERBUFFER_SIZE

It's probably worth forcing RTs to limit themselves to what the GPU can handle, so if a value is given in code beyond this it just resets the width / height of them to force them to be the right allowed size.

I'll check the examples tomorrow to see if there is something else going on, but it's probably related to this somehow.

**Comment by hackhat** [comment]
But how do you explain that if you change the game.config.width it allows bigger render textures?

**Comment by photonstorm** [comment]
Looked at this today, some more findings:

1) Only happens in WebGL. Canvas is fine.

2) The trigger is creating a Render Texture that is larger than the Canvas it is being drawn to. An RT of the same size, or less, works as expected.

3) Creating an FBO beyond what the GPU can support throws all kinds of fun errors (from both the Camera FBO and the RT), which is to be expected really, but needs catching.

**Comment by hackhat** [comment]
@photonstorm 

>The time of the draw appears to be irrelevant and not the trigger.

What do you mean? I wonder because if you render a few 100s of times in the update method it will render only a few of them outside the crop area. So I assume for a few milliseconds the crop is not applied, only after that.

If you have a update method and there you draw 1000 times per update, you will see what I mean.

**Comment by hackhat** [comment]
Hi! I was wondering when do you think this will be fixed?

**Comment by hackhat** [comment]
Hi @photonstorm is this still being worked on are there any news?

**Comment by hackhat** [comment]
Hi! I was wondering if you have any news about this @photonstorm thank you

**Comment by hackhat** [comment]
Hello @photonstorm is there anything I can do to help on this issue? It's really blocking my game at the moment.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

You can find a demo here: http://labs.phaser.io/view.html?src=src%5Cbugs%5Crt%20crop.js&v=dev

Use the arrows to move the camera and Q/E to zoom in/out.

The Render Texture is 1024 x 1024, larger than the game canvas. The Phaser logo is being drawn randomly in the range -3000 to 3000, so well outside the size of the Render Texture. It no longer draws anything outside of the RTs size.

**Comment by hackhat** [comment]
Thank you
