### ISSUE TITLE
Delta passed to update is fixed/incorrect

### ISSUE THREAD

**Issue by okaybenji** [photonstorm/phaser#3959]
## Version

* Phaser Version: 3.12.0-beta2

* Operating system: macOS High Sierra

## Description

The delta passed to a scene's update method is always ~16.6667 (60 FPS) regardless of the actual frame rate.

## Example Test Code

You can see the issue here: https://codepen.io/anon/pen/RYwjQV?editors=0011

This will log the delta time passed to the update method as well as "real delta" which is calculated each frame. (If there's no difference, you probably have a beefy PC. Try throttling the CPU using Chrome dev tools.)

The essential code is:
```
function update(time, delta) {
  if (!this.lastUpdate) {
    this.lastUpdate = this.time.now;
  }
  const realDelta = this.time.now - this.lastUpdate;
  this.lastUpdate = this.time.now;
  
  console.log(time, delta, realDelta)
}
```

## Additional Information

Thanks very much!!

**Comment by photonstorm** [comment]
The delta value is a smoothed and capped average collected over the previous 10 frames, to specifically avoid spiking and fall-outs and all the random crap browsers like to do. If you want the 'raw' value, use `game.loop.rawDelta` instead, which is the date based delta value similar to your code above. If you intend to use that value in your calculations be extremely careful as it can fluctuate _massively_ depending on whatever the heck the browser feels like doing at the time.

**Comment by okaybenji** [comment]
Ok, thanks!
