### ISSUE TITLE
Special Characters in Text Game Objects get cut off

### ISSUE THREAD

**Issue by Loonride** [photonstorm/phaser#3960]
## Version

* Phaser Version: v3.11

* Operating system: Windows 7

* Browser: Chrome, Firefox

## Description

When large special characters are added as Text Objects and drawn, they get cut off.

Here is one such character: ⎝

This is what it looks like on Chrome:

![textcutoff](https://user-images.githubusercontent.com/22580625/44373694-1f3b9d00-a4b0-11e8-96f9-b10d0a0a952e.PNG)

On Firefox, it also gets cut off, but completes the black stroke on the top edge, rather than cutting it off.

## Example Test Code
```
let textStyle = { fontFamily: 'Arial', fontSize: '28px', fill: 'rgba(255,255,255,1)' };
let text = this.add.text(0, 0, "⎝ example text", textStyle).setOrigin(0.5);
text.setStroke(0x111111, 6);
```

**Comment by photonstorm** [comment]
This needs handling in your code based on whatever font you need to support. The Text class provides a couple of ways to deal with it. First, you can change the Text padding property to give lines the extra height they need for characters such as this (see the labs for an example).

Or secondly, you can change the `testString` property of the Text style object from the default, which is `|MÉqgy` to something including your special characters. There is also the method `Text.style.setTestString` which can change it post-creation, but it's probably easier to just give a new test string in the style config object.
