### ISSUE TITLE
Ability to modify animation's duration/frameRate

### ISSUE THREAD

**Issue by inmylo** [photonstorm/phaser#3963]
When animation is used sometimes it needs to be run slower or faster than initial speed. Currently I need to create additional animation to be able to run it with another duration/frameRate.

Would that be possible to add an efficient way to modify existing animation's speed at runtime?

(I've tried changing some animation's parameters, asked on forum, but no results, so I assume that currently that's not possible)

**Comment by katsos** [comment]
Is anyone working on this? I want to give it a try or two.

**Comment by photonstorm** [comment]
I'm not working on it yet, so feel free.

**Comment by katsos** [comment]
Hey, @photonstorm I'm working on this. 
I was able to adjust frameRate on runtime by creating a `setFrameRate()` inside `/components/Animation.js`, 
but I was wondering @imilo `sprite.anims.setTimeScale()` doesn't do the job for you?

Do you want a working example to see it live?

**Comment by imilo** [comment]
@katsos , `setTimeScale()` seems interesting, I really haven't seen this function before.

I tried now and there is one issue - if I do this:
```javascript
scene.anims.create({
        key: 'name',
        frames: scene.anims.generateFrameNumbers('name', { start: 0, end: 47 }),
        duration: 1000,
        hideOnComplete: true
});

sprite.anims.setTimeScale(1.25);
```

.. scaling doesn't happen. I've added logging to the animation's `update` function and it says that `this._timeScale` is still **1**. Only if I change `this._timeScale` after the first animation run it becomes **1.25**.

How can I set scaling during the animation's creating or right after it, but before the first run?

**Comment by katsos** [comment]
@photonstorm thoughts on this one?

**Comment by photonstorm** [comment]
The time scale is reset to 1 whenever a new animation is loaded into a Sprite. I guess it could be left alone, so if you change it, it impacts every animation that Sprite plays, no matter which one it is.

This feels like something entirely different to setting a different frame rate though. You should be able to use them both together.

**Comment by imilo** [comment]
@photonstorm , in my case I have only 1 animation for that sprite, so setting a scale could be Ok. Is that possible to set the scale before the first run?

If not, then I'll wait for the new `setDuration` function.

@katsos , could you add `setDuration` function if the answer to the question above will be No?

**Comment by photonstorm** [comment]
With current master branch you can set time scale at any point now.

**Comment by scarejar** [comment]
.setTimeScale() modifies the speed of animation for all animations on the sprite.. 

is there a way to setTimeScale on a specific animation or do I just duplicate animation objects?

`        this.anims.create({
            key: "right",
            frameRate: 5,
            frames: this.anims.generateFrameNumbers(`playerTexture`, {
                frames: [6, 10, 14, 2],
            })
        });

        this.anims.create({
            key: "right_running",
            frameRate: 10,
            frames: this.anims.generateFrameNumbers(`playerTexture`, {
                frames: [6, 10, 14, 2],
            })
        });`

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
