### ISSUE TITLE
Setdata event not working

### ISSUE THREAD

**Issue by PBird** [photonstorm/phaser#3974]
## Version

* Phaser Version: 3.11.0

* Operating system: Ubuntu 18.04

* Browser: Chrome

## Description

Phaser.GameObjects. GameObject   on function is not working 3.11.0 however it is working properly on Phaser v3.9.0. i put link below. 

https://labs.phaser.io/view.html?src=src\components\data\set%20data%20event.js&v=3.11.0

**Comment by iamchristopher** [comment]
The `setdata` event is only emitted the first time a value is set and subsequent changes emit the `changedata` event. This behaviour is documented [here](https://github.com/photonstorm/phaser/blob/224d587928265e9ce28609ca48d0b11a72f159e3/src/data/DataManager.js#L236-L240) and was changed in [v3.10](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md#data-manager-new-features-and-updates). The labs example should be updated to reflect this behaviour.
