### ISSUE TITLE
game resize bugged in v3.12.0-beta3

### ISSUE THREAD

**Issue by Antriel** [photonstorm/phaser#3977]
## Version
* Phaser Version: 3.12.0-beta3

## Description

Game resizing no longer works.

## Example Test Code

http://labs.phaser.io/view.html?src=src/game%20config\game%20resize.js&v=dev

**Comment by photonstorm** [comment]
Yup, still in transition to the SM.

**Comment by photonstorm** [comment]
Actually, this is a duplicate of #3928 so going to close this issue to keep the list clean and track progress on the original issue.
