### ISSUE TITLE
v3.12.0-beta3 Error when use TextureTintPipeline instead of FlatTintPipeline

### ISSUE THREAD

**Issue by kid-wumeng** [photonstorm/phaser#3978]
## Version

* Phaser Version: *v3.12.0 Beta 3*
* Operating system: *macOS Sierra 10.12.6*
* Browser: Chrome  *68.0.3440.106 64bits*

## Description

Hi, I seem the [Release log](https://github.com/photonstorm/phaser/releases/tag/3.12.0-beta3) and understand the changed of FlatTintPipeline. Now I update my code using the TextureTintPipeline to instead of the FlatTintPipeline, Furthermore I wasn't changed any other codes. But the program throws an error that:

```
phaser.js:31598 Uncaught TypeError: Cannot read property 'u0' of null
    at Pipeline.batchFillRect (phaser.js:31598)
    at GraphicsWebGLRenderer [as renderWebGL] (phaser.js:104238)
    at WebGLRenderer.render (phaser.js:65881)
    at CameraManager.render (phaser.js:114781)
    at Systems.render (phaser.js:29019)
    at SceneManager.render (phaser.js:46625)
    at Game.step (phaser.js:111495)
    at TimeStep.step (phaser.js:107536)
    at step (phaser.js:67170)
```

What happend about it ? It is ok when use FlatTintPipeline, so... What else should I do ?

## Example Test Code

My Pipeline extends TextureTintPipeline ( extends FlatTintPipeline at Phaser v3.11 ), Only simply create pipeline object from the shader string caches ( codeing by CoffeeScript ).

```coffeescript
class Pipeline extends Phaser.Renderer.WebGL.Pipelines.TextureTintPipeline

   constructor: ( game, options = {} ) ->

      ########################################
      #|
      #|   @params {Phaser.Game} game
      #|   @params {object}  options
      #|                    {string}   options.vert
      #|                    {string}   options.frag
      #|
      ########################################

      super({
         game:       game
         renderer:   game.renderer
         vertShader: if options.vert then game.cache.shader.get(options.vert) else undefined
         fragShader: if options.frag then game.cache.shader.get(options.frag) else undefined
      })
```

The Scene Class, create a rectangle and use the pipeline.

```coffeescript
class SceneTest extends Phaser.Scene

   constructor: ->
      super('testScene')

   create: ->
      game.renderer.addPipeline('test', new Pipeline(game, { frag: 'test.frag' }))

      graphics = this.add.graphics()
      graphics.fillRect(0, 0, 700, 700)
      graphics.setPipeline('test')
```

The pipeline use a fragment shader ( [A water effect](http://glslsandbox.com/e#33088.0) ) and the GLSL run succeed when use FlatTintPipeline on Phaser v3.11

```glsl
#ifdef GL_ES
precision mediump float;
#endif

#extension GL_OES_standard_derivatives : enable

uniform float time;
uniform vec2 resolution;

#define f length(fract(q*=m*=.6+.1*d++)-.5)
void main()
{
    float d = 0.;
    vec3 q = vec3(gl_FragCoord.xy / resolution.yy-13., time*.2);
    // Yes, I realise this mat3 looks a little gay in a homo way ... :)teehee
    mat3 m = mat3(-2,-1,2, 3,-2,1, -1,1,3);
    vec3 col = vec3(pow(min(min(f,f),f), 7.)*40.);
    gl_FragColor = vec4(clamp(col + vec3(0., 0.35, 0.5), 0.0, 1.0), 1.0);
}
```

**Comment by photonstorm** [comment]
Ah, it's because it's expecting `currentFrame` to be set to something, but in an extended pipeline it won't be. Try adding this into your custom pipeline:

```
this.currentFrame = renderer.blankTexture;
```

That should resolve it. In the meantime, I'll see about making that the default. Currently, it happens in the renderer's `boot` method but it happens directly on the TTP, not on any custom pipelines, hence the error.

**Comment by photonstorm** [comment]
Actually, ignore the above. I've pushed a fix up now which I think should work just fine for your case. Please could you try it out and let me know?

**Comment by kid-wumeng** [comment]
@photonstorm Thanks! I add the code:

```js
this.currentFrame = game.renderer.blankTexture
```

and it is working good now in v3.12 beta-3 ~

**Comment by kid-wumeng** [comment]
@photonstorm Sorry, I just didn't notice your second reply. I am now trying to download and build the latest project ( v3.12-beta4 ). It’s success to run my code ( I has removed the `this.currentFrame = game.renderer.blankTexture` )

**Comment by photonstorm** [comment]
Excellent, thanks for reporting this!
