### ISSUE TITLE
Huge request animation call stack, may have a hit on performance?

### ISSUE THREAD

**Issue by hackhat** [photonstorm/phaser#3980]
Here is how it looks like, do you think has any performance issues? 

![image](https://user-images.githubusercontent.com/11173732/44621403-6ecb0000-a8d8-11e8-8f92-ad8bd929a3cd.png)

![image](https://user-images.githubusercontent.com/11173732/44621405-83a79380-a8d8-11e8-8a2e-983b7c503383.png)

**Comment by samme** [comment]
That's normal. The _async_ calls aren't actually part of the stack (except the first).

**Comment by hackhat** [comment]
Ok
