### ISSUE TITLE
camera.ignore() allow pointer events to pass through

### ISSUE THREAD

**Issue by NemoStein** [photonstorm/phaser#3984]
## Version
* Phaser Version: v3.11.0 ~ v3.12.0-beta3

I was able to reproduce this on 3.12-beta3 with webpack only. Using the precompiled file yields a "Uncaught TypeError: Cannot read property 'id' of undefined"

## Description
Having a `camera` ignoring a `container`, if a `object` inside this `container` have a `obj.on('pointerover', callback)` and `camera` bounds overlaps with that object, even though the camera doesn't render it, passing the cursor over the object DOES call the `callback`.

## Example Test Code
In the following example, there is a "A" image (ignored by the main camera) in the black area above the "B" image.
Passing the cursor over the "A" will make "B" appear/disappear on `a.on('pointerover')`  and `a.on('pointerout')`.

[CodePen version](https://codepen.io/anon/pen/JaXxMX)
```javascript
var game = new Phaser.Game(
{
	type: Phaser.AUTO,
	width: 200,
	height: 400,
	scene:
	{
		preload: function()
		{
			this.load.setBaseURL('https://labs.phaser.io')
			this.load.image('a', 'assets/sprites/a.png')
			this.load.image('b', 'assets/sprites/b.png')
		},

		create: function()
		{
			var a = this.add.image(100, 100, 'a')
			var b = this.add.image(100, 300, 'b')

			a.setInteractive()

			a.on('pointerover', () => b.setVisible(false))
			a.on('pointerout', () => b.setVisible(true))

			this.cameras.main.ignore(a)
		}
	}
})
```

**Comment by NemoStein** [comment]
Note that using `camera.inputEnabled = false` partially solves the problem, but defeats the purpose (UI camera, for example).

**Comment by samid737** [comment]
reproducable for similar testcase (Einstein is located lower right): 

[v3.11.0](http://jsfiddle.net/ynzdcoq5/2/):

removing setInteractive() from above code solves TypeError in dev build , same for this example:

[v3.12.0-Beta3](http://jsfiddle.net/ke7yxLa2/6/):

The test is checking if pointer events are triggered for the lower right Einstein.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
