### ISSUE TITLE
[3.12 beta 3] None of the BitmapMask examples work anymore

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3988]
In the examples, none of the BitmapMask examples (for example [this one](http://labs.phaser.io/view.html?src=src\display\masks\BitmapMask%20Example.js&v=dev) or [that one](http://labs.phaser.io/view.html?src=src\display\masks\BitmapMask%20Alpha.js&v=dev)) work when selecting "dev build", which at the moment corresponds to 3.12 beta 3. No error is raised in the console. They work fine when selecting 3.11.  

This matches my experience of having broken bitmap masks in my own project when using 3.12 beta 3, also without errors in the console.

**Comment by photonstorm** [comment]
I know. I started fixing it today but ran out of time. Will finish tomorrow.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
