### ISSUE TITLE
resume event is triggered by setActive will not trigger again

### ISSUE THREAD

**Issue by yuyenkan** [photonstorm/phaser#3991]
## Version

* Phaser Version: 3.11

* Operating system:Windows 10 32 bit

* Browser:Google Chrome

## Description

Scene resume event in sceneA will is triggered by this.scene.setActive(true, "sceneA") in sceneB and the next line this.scene.resume('sceneA', { data: data }) is not trigger the resume event afterward. 

In this case, the data is not passing to sceneA.

## Example Test Code

in sceneB

```
backToSceneA: function(){
                this.scene.setActive(true, "SceneA");
		this.scene.setVisible(true, "SceneA");
        	this.scene.resume('SceneA', { data: data });
},
```

in scene B
```
openSceneB: function(){
		this.stopInputEvents();
		this.scene.pause("sceneA");
		
		this.scene.setVisible(false);
		this.scene.setActive(false);
		this.scene.launch('sceneB');

                this.events.once('resume', function (scene, data) {
			console.log(data);
		});
    },
```

**Comment by photonstorm** [comment]
Because calling `setActive` automatically resumes the Scene, so there's nothing for the `resume` call to do, so it bails out. You should pass the data object with the `setActive` call.
