### ISSUE TITLE
GameObject alpha not observed when using tintFill

### ISSUE THREAD

**Issue by trl-bsd** [photonstorm/phaser#3992]
## Version

* Phaser Version: 3.11

* Operating system: Windows 10

* Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)

## Description

On game objects where both alpha and tintFill are set, the object will be tinted as per the color set by the setTintFill method, but the object is displayed as a solid, ignoring the object's alpha property.

Expected behaviour: a replace-tinted object that is "see-through"
Observed behaviour: a replace-tinted object that is not "see-through"

## Example Test Code

https://jsfiddle.net/0pe9k1rq/8/

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
