### ISSUE TITLE
Arcade physics engine, body.setSize(w, h) in a graphics object does not set offset to center

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3997]
## Version
* Phaser Version: 3.12.0-beta1

## Description

In arcade physics engine, `body.setSize(w, h)` will set offset to center of this rectangle. But it dose not when the parent game object is Graphics game object.

## Example Test Code

https://codepen.io/rexrainbow/pen/eLvmrz

Draw a rectangle at (0,0) with offset (-size/2, -size/2), but the collided bound is not offset to the center. 
Add `body.setOffset (-size/2, -size/2)` to set offset to the center.

## Additional Information

Graphics does not have `getCenter` method, that's why it could not set offset to center.

https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/Body.js#L1110

**Comment by photonstorm** [comment]
I'm happy with this as a limitation. Graphics objects have no bounds, so cannot have a `getCenter` method. `setSize` works in that it doesn't use this method unless it exists, so I've updated the docs to make it more explicit.

**Comment by photonstorm** [comment]
It doesn't matter too much where the center is, it all depends on where you draw to it. If you `fillRect(0, 0, w, h)` then you'd need a totally different offset than if you did a `fillRect(-w/2, -h/2, w, h)`. I think it's fair we should make the dev choose the combination they prefer and `setOffset` explicitly.

**Comment by rexrainbow** [comment]
Thank you, `body.setOffset` is a solution at least.
