### ISSUE TITLE
Tiled 1.2 map JSON support

### ISSUE THREAD

**Issue by halgorithm** [photonstorm/phaser#3998]
The Tiled 1.2 beta made some breaking changes to the map JSON export format, which seems to (partially) break phaser's current tilemap loading behavior. I noticed it when using `setCollisionByProperty` and none of my tiles had any properties. It's not an issue right now since Tiled 1.1.6 is still the stable release, but I just wanted to give a heads up to anybody that might run into this.

https://www.mapeditor.org/2018/08/22/tiled-1-2-beta-released.html

**Comment by photonstorm** [comment]
Yes, we've already seen this surface with people downloading the beta and expecting it to work as-is. We'll work on supporting _both_ formats at some point in the future.

**Comment by kosich** [comment]
May I suggest showing a warning if tiled map file version is not supported?
Cz load and parse might go just well, just the properties would not be bound properly.

Theres already a check against [non-orthogonal](https://github.com/photonstorm/phaser/blob/master/src/tilemaps/parsers/tiled/ParseJSONTiled.js#L41) projection, so we could add there another one.
Imho, might save some time for people trying new versions of Tiled (would've saved me an hour at least...)

Tiled exports its file version via a number in JSON.
Seems like for current beta version (Version 2018.09.12 MacOS) -- its `1.2` and for the one, phaser supports -- its just `1` (might be phaser supports `1>` and `<1.2`, not sure)

Maybe, in future we could use different strategies based on this version.

==
* I'm a total newbie to both Phaser and Tiled, so sorry if this is irrelevant.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
