### ISSUE TITLE
Arcade physics / physics.world.collide is broken

### ISSUE THREAD

**Issue by nkholski** [photonstorm/phaser#3999]
Manual collision check (physics.world.collide) against tile layers is broken for Arcade physics since 3.10. 

Doing this in the scene update method will just fail silently in Phaser 3.10+ but worked fine in Phaser 3.9:
` this.physics.world.collide(sprite, layer);`

While doing this in the create method will work as expected (while a bit less flexible solution):
`this.physics.add.collider(sprite, layer);`

@mikewesthad has set up a demo here:
https://codesandbox.io/s/l2lmk8oxom?expanddevtools=1&module=%2Fjs%2Fplatformer-scene.js
"In the console, it demos how the body delta is 0 when you use World#collide (which the tilemap collision separation code expects to be non-zero)."

**Comment by mikewesthad** [comment]
Chiming in to add a little extra description to that demo:

- The player is set up to collide with the ground (steel girders) via a collider. This works fine.
- The player is set up to collide with the spikes via World#collide. This doesn't work.

The console dumps the sprite's deltaY within the collide process callback. It's non-zero for the collider (as expected) and zero for calling World#collide. With a zero delta in World#collide, when the tile separation code runs, it doesn't think the player and the tiles overlap, so no resolution occurs. This is related to #3987.

**Comment by nkholski** [comment]
By the description it seems the same issue as #3777, and I haven't tested any Phaser build post that fix. You might want to test that before putting any work into fixing this. (The current dev build fail for me atm)

**Comment by jbpuryear** [comment]
I also think this is related to #3987 and I think I have [a solution](https://codesandbox.io/s/84knvjrm6l). Check out my comment over [here](https://github.com/photonstorm/phaser/issues/3987#issuecomment-418246949) for an explanation.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by mikewesthad** [comment]
Thanks! Verified that it's working in my test case.

**Comment by nkholski** [comment]
Little late, but the issue is gone for me too.
