### ISSUE TITLE
Incomplete Tilemap layer loading (3.11 -> 3.12 beta3 regression)

### ISSUE THREAD

**Issue by jdotrjs** [photonstorm/phaser#4002]
## Version

Tried 3.12 beta3 and 3.12.beta4
Win7 FF + Chrome latest versions

## Description

Starting a new project for a game jam and was loading an 80x80 tilemap. Only the top-left 40x40 section is rendered when a new layer is constructed via `createStaticLayer`.

## Example Test Code

The relevant bits:

```javascript
class Game extends Phaser.Scene {
  constructor() {
    super({ key: Name })
  }

  preload() {
    this.load.image('item_pack', 'assets/16x16_item_pack.png')
    this.load.tilemapTiledJSON('level', 'assets/level1.json')
  }

  create() {
    const map = this.add.tilemap('level', 0, 0)
    const items = map.addTilesetImage('item_pack')
    // note that map.createDynamicLayer doesn't surface the same broken behavior
    map.createStaticLayer('Background', items)
  }
}
```

## Additional Information

This doesn't seem to impact all maps. I've tested 40x40 and 50x60 and static layers seem to fully load in those so it suggests there is something wrong with the handling of this particular map. Included is [report.zip](https://github.com/photonstorm/phaser/files/2342747/report.zip) which should be sufficient to repro:

```console
yarn install
yarn webpack:watch
```

Then hit http://localhost:8080 to view a repro. If you edit `src/index.html` and swap to 3.11 the full map is loaded.

## Misc Notes

Yea, I know, beta builds are beta for a reason 😄. I'm mostly filing this in case there isn't active work against tilemap that would be expected to surface with this kind of regression. I did not do a lot of work to check active areas of development so I'd buy this is expected right now. In that event this can probably be closed off hand.

**Comment by photonstorm** [comment]
I can't replicate this, even with a huge map. Can anyone else?

**Comment by jdotrjs** [comment]
Did you try with the attached project? I was only able to repro on the map that I included. I'll assign this one to myself and take a deeper look at it over the next couple of days and make sure it's reproducible across multiple machines and it wasn't some weird caching issue.

(I don't believe that was it though as I was editing the map json and saw the new fields I had added get delivered)

**Comment by pinkkis** [comment]
I think I've been able to reproduce this in my project. I just noticed that I have some walls missing, though their collision is still present. it's a 100x100 map and phaser 3.12.0. If i swap to 3.11.0, it loads fine again.

it seems that a slice of 0,0 to 100,31 renders fine, then all but the floor layer (bottom layer) is missing below that, all the way down

I have 5 tile layers in the map, all the same size. 32x32 tiles. two object layers with some stuff on them, all of which loads fine.
Win10 + Chrome 69

ps. I can also reproduce error on the included report.zip from OP

**Comment by pinkkis** [comment]
I should also add, the collision from the "wall" layer still works, and there are a couple random tiles from other layers. Just the tiles from the wall layer are not visibly drawn on screen past the top 32 rows.

**Comment by pinkkis** [comment]
@photonstorm Is there anything we can provide to help with reproducing this? 12 and more importantly 13 will have features I really want, but if the maps won't load, i can't really update.

**Comment by pinkkis** [comment]
I just noticed that in the labs examples, this can also be reproduced at least with this example: 
Tiled Multi Tileset and swapping between versions. It loads correctly in 3.11 and below, and fails to load all tiles in 3.12 and above (including dev build)

https://labs.phaser.io/view.html?src=src\game%20objects\tilemap\static\tiled%20%20multi%20tileset.js&v=3.11.0

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by pinkkis** [comment]
@photonstorm, I tested with 3.14-beta1 and the map is loading correctly now. Thank you!
