### ISSUE TITLE
Object still draggable after setting it to false

### ISSUE THREAD

**Issue by strahius** [photonstorm/phaser#4003]
## Version
* Phaser Version: 3.11.0
* Operating system: Arch Linux

## Description
It seems to me that drag is not disabled once an object has already been dragged. When I enable and disable drag before I have touched the object, disable is working. Once the object has been dragged, the disable drag commands, executed from inside the 'dragend' event, seem to have no effect, my object is still draggable, even though no `drag` events are fired. Could it be that something is leaked to DOM?

## Example Test Code
How I initialize drag:
```
export default class MyObject extends Phaser.GameObjects.Sprite {
  constructor(config) {
    super(config.scene, config.x, config.y, config.key);

    this.setInteractive();
    this.scene.matter.add.mouseSpring();
    this.scene.input.setDraggable(this);
}
```
When I disable drag just after that, I can no longer drag. But my code does this:
```
    this.scene.input.on('dragend', function(pointer, gameObject) {
      gameObject.scene.input.setDraggable(gameObject, false);
      gameObject.setInteractive(false);
      gameObject.input.draggable = false;
```
Essentially all I think I need is `gameObject.scene.input.setDraggable(gameObject, false);` but I've put the rest there just to show I've tried them. I have also checked that `gameObject.input.draggable` is still `false` while dragging is happening.

## Additional information
![draggable](https://user-images.githubusercontent.com/908935/44959293-b27ac680-aee3-11e8-85fa-a2e7a6bcfd40.gif)

**Comment by alexeymolchan** [comment]
@strahius https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Sprite.html#disableInteractive__anchor or even this https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Sprite.html#removeInteractive__anchor

**Comment by strahius** [comment]
Thanks @alexeymolchan, forgot to mention I had also tried these, tried again now, same result.

**Comment by alexeymolchan** [comment]
@strahius i tried here https://labs.phaser.io/edit.html?src=src\input\dragging\enable%20for%20drag.js

just added gameObject.disableInteractive() in dragend handler and image has become non draggable 

```
this.input.on('dragend', function (pointer, gameObject) {

        gameObject.clearTint();
        gameObject.disableInteractive();

    });
```

**Comment by strahius** [comment]
Thanks alot for looking at this @alexeymolchan! Then it must be something else in my setup, there's a few things going on. Not sure what's the best way of sharing this, but I kind of reproduced it on that example:
```
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    },
    physics: {
        default: 'matter',
        matter: {
            gravity: { y: 0.8 },
            debug: false,
        }
    },
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('eye', 'assets/pics/lance-overdose-loader-eye.png');
}

function create ()
{
    // var image = this.add.sprite(200, 300, 'eye').setInteractive();
    var image = this.matter.add.image(200, 300, 'eye', null, {friction: 0.9});
    image.setStatic(true);

    image.setInteractive();
    this.matter.add.mouseSpring();
    this.input.setDraggable(image);

    var constraint = Phaser.Physics.Matter.Matter.Constraint.create({
        pointA: {x: 200, y: 300},
        bodyB: image.body,
        stiffness: 0.0001,
        damping: 1,
    });
    this.matter.world.add(constraint);

    this.input.on('dragstart', function (pointer, gameObject) {
        gameObject.setStatic(false);
        gameObject.setTint(0xff0000);
    });

    this.input.on('drag', function (pointer, gameObject, dragX, dragY) {
        if (Phaser.Math.Distance.Between(200, 30, dragX, dragY) > 200) {
            constraint.stiffness = 1;
            constraint.length = 200;
        } else {
            constraint.stiffness = 0.0001;
        }

        gameObject.x = dragX;
        gameObject.y = dragY;
    });

    this.input.on('dragend', function (pointer, gameObject) {
        gameObject.clearTint();
        gameObject.disableInteractive();
    });
}
```
I _think_ it's the constraint...

**Comment by strahius** [comment]
But removing that does not change anything:
```
function create ()
{
    var image = this.matter.add.image(200, 300, 'eye', null, {friction: 0.9});
    image.setStatic(true);

    image.setInteractive();
    var spring = this.matter.add.mouseSpring();
    this.input.setDraggable(image);
    var scene = this;

    ...

    this.input.on('dragend', function (pointer, gameObject) {
        gameObject.clearTint();
        scene.matter.world.remove(spring);
        gameObject.disableInteractive();
    });
}
```

**Comment by alexeymolchan** [comment]
@strahius just call ```spring.destroy();```

**Comment by strahius** [comment]
Ah yes! Had not seen that on the API doc. That did it!

For the constraint, I don't think I want to destroy it, as I need it again later. So I create it once, and add/remove from the scene.
