### ISSUE TITLE
setNewFrameRate() by gammafp on Discord

### ISSUE THREAD

**Issue by Project-Magenta** [photonstorm/phaser#4005]
The method Phaser.Animations.Animation.setNewFrameRate() will have 1 parameter corresponding to the new frameRate.
This would be useful to change the speed of an animation for different situations and remove the need for many similar animations to change speed.

**Comment by gammafp** [comment]
this.load.sprite(... bla bla).anims.setTimeScale(0.2);  // For change the speed in realTime :D Thanks Photostorm.
