### ISSUE TITLE
setStyle() on text object makes it disappear

### ISSUE THREAD

**Issue by okcompewter** [photonstorm/phaser#4011]
## Version

* Phaser Version:
3.12.0

## Description

I am styling a text object as a button, using setInteractive() to allow pointer events. When the events trigger a setStyle() on the button, it disappears (but is still clickable). This was not an issue on 3.11.0.

## Example Test Code

https://codepen.io/anon/pen/oPwwrN

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
