### ISSUE TITLE
TileSprite setTileScale bug

### ISSUE THREAD

**Issue by alexeymolchan** [photonstorm/phaser#4013]
Phaser 3.12

Hi, setTileScale method setting tilePosition instead of tileScale
```
setTileScale: function (x, y)
    {
        if (x !== undefined)
        {
            this.tilePositionX = x;
        }

        if (y !== undefined)
        {
            this.tilePositionY = y;
        }

        return this;
    },
```

i created pr for this

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
