### ISSUE TITLE
Unhandled MouseManager exceptions after destroying a game instance

### ISSUE THREAD

**Issue by garethwhittaker** [photonstorm/phaser#4015]
## Version

* Phaser Version: 3.12.0

* Operating system: MacOS High Sierra

* Browser: Chrome 68.0.3440.106

## Description

Unhandled exceptions are triggered after destroying a Phaser instance.

The MouseManager seems to have listeners that continue to trigger after game teardown.

![image](https://user-images.githubusercontent.com/2885325/45081318-da8a4580-b0ee-11e8-9726-e83559d62c60.png)

## Example Test Code

This is just the Phaser Labs First Game example with the addition of the destroy call after a few seconds.

```javascript
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var game = new Phaser.Game(config);

function preload () {}
function create () {}
function update () {}

setTimeout(function () {
    game.destroy();
}, 10000);
```

**Comment by photonstorm** [comment]
Investigated and this only happens if the parent canvas isn't removed (i.e. passing `true` to the `destroy` method stops this error happening)

**Comment by kosanr1** [comment]
I have similar issue. When I use game.destroy(true) it doesn't remove canvas and I have this error. And the game just stops
![screenshot from 2018-09-07 10-10-49](https://user-images.githubusercontent.com/42383376/45206852-6aaec300-b286-11e8-957a-0d767a208f0a.png)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
