### ISSUE TITLE
Issue Loading sprite sheet base64

### ISSUE THREAD

**Issue by shubhamseth2527** [photonstorm/phaser#4020]
I have load a base64 spritesheet when clear my history it will not load the spritesheet but after reload it will automatically disappear warning. but my issue is every time when i run on new system or mobile my spritesheet will not load .
```
var image1sprite = 'base64anydfefrvfcbv';
var image2sprite = 'base64anybfgbfbgfbf';
cardRandomDistribute = [image1sprite , image2sprite];
 for (var i = 0; i < 10; i++) {
        var cardsImg = new Image();
        var key = "cards" + i;
        cardsImg.onload = cardSpriteSheetLoad(i, key, cardsImg);
    }
    function cardSpriteSheetLoad(i, key, cardsImg) {
    cardsImg.src = cardRandomDistribute[i];
    tempGame.textures.addSpriteSheet(key, cardsImg, {
        frameWidth: gameOptions.cardSheetWidth,
        frameHeight: gameOptions.cardSheetHeight
    });
}
```
When First time load all my image were distribute but when click on show image  it will show empty image but when i refresh warning will auto remove and next time it will work perfect. 
![screen shot 2018-09-10 at 5 11 44 pm](https://user-images.githubusercontent.com/17332279/45295529-a793e780-b51c-11e8-9ee1-9e3bc6487646.png)

**Comment by photonstorm** [comment]
The error is because the Image has not finished loading, so it cannot make a texture from it. You need to move the texture creation inside the `onload` handler for the Image. Or, don't use base64 of course, then it would work perfectly.

**Comment by photonstorm** [comment]
Also, this is wrong: `cardsImg.onload = cardSpriteSheetLoad(i, key, cardsImg);` - that is invoking the function immediately. You should only have the callback reference here.
