### ISSUE TITLE
Odd display when using Light2D with game resolution > 1

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#4022]
## Version

* Phaser Version: 3.12.0
* Operating system: macOS
* Browser: Chrome, Safari

## Description

Move the cursor/spotlight near the bottom-right of the game canvas.

Expected: the robot texture shows the ambient color (blue) and spotlight (red) at the cursor location.

Actual: robot texture disappears (all black).

## Example Test Code

<https://codepen.io/samme/pen/pOarKN?editors=0010>

**Comment by photonstorm** [comment]
Closing this off as there will be no resolution > 1 support in v3.
