### ISSUE TITLE
Calling stop on a tween after it was paused causes memory leak

### ISSUE THREAD

**Issue by goldfire** [photonstorm/phaser#4023]
## Version

* Phaser Version: 3.12.0

* Operating system: macOS

* Browser: Chrome

## Description

When you pause a tween it will be placed in the `_pending` array rather than the `_active` array. This prevents the tween's `update` from calling, which means if you call `stop` it won't ever be removed from the `_pending` array and build up in memory.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
