### ISSUE TITLE
Split Pointer values like upTime out to a Button object

### ISSUE THREAD

**Issue by pinkkis** [photonstorm/phaser#4025]
## Version

* Phaser Version: 3.11

* Operating system: Windows 10 & MacOs

* Browser: Chrome 68 & 69

## Description

I'm trying to distinguish between short and long clicks, or more specifically, not firing the normal "click behaviour, if the user is holding the mouse down to move, but then releases it after a while.

in `this.inputs.on('pointerup')` callbacks, I try to use `evt.upTime - evt.downTime > 500` or something similar.

On left click, this works fine, and I just have a console log there, to note when it was a long click. But with right click, it triggers "long click" incorrectly even for normal very short (some ms) clicks and the times in those event properties seem weird.

## Example Test Code

```javascript
create() {
  this.inputs.on('pointerup', (evt) => {
    if (evt.upTime - evt.downTime > 2000) {
      console.log('long click');
    } else {
      console.log('short click');
    }
  }, this);
}
```

## Additional Information

I have the `disableContextMenu: true` set in game config, but not sure this makes a difference, as in the labs editor, this seems to show a context menu either way.

**Comment by pinkkis** [comment]
Hmm.. Sorry if I missed to docs. I guess I could use rightButtonDown() in update() and keep track when it started and when it stopped. I probably should do this anyway, if i need to keep track where the pointer is on the screen to move a character towards it.

As for the events, since the event has which button it is  in `evt.buttons`, I made an assumption that the rest of the properties would be for the button in that prop. Same would go for pressing two buttons, you'd send an event for each, and you could tell which one it was, but that would add keeping track of each button separately.

Anyway, thanks for the answer, I seem to have misunderstood the events.

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
