### ISSUE TITLE
Wrong collision with a scaled tilemap layer

### ISSUE THREAD

**Issue by JasonHK** [photonstorm/phaser#4026]
## Version

* Phaser Version: 3.12.0

* Operating system: Kubuntu 16.04

* Browser: Firefox for Linux 61.0.1

## Description

As I said on the title, I scaled up the tilemap just like the sample code below. But after I set the collision for the ground, I found that the collision box is in the original size of the tileset, not the scaled-up one.

P.S. I haven't tested it with an actual player object, I just found out that in the debug mode. I hope that is the problem of the debug mode...

## Example Test Code

```javascript
function onPreload () {
    this.load.setBaseURL('assets/');

    this.load.image("ts-ground", "tilesets/ground.png");
    this.load.tilemapTiledJSON("tm-ground", "tilemaps/ground.json");
}

function onCreate () {
    let tilemapGround = this.make.tilemap({ key: "tm-ground" });
    let tilesetGround = tilemapGround.addTilesetImage("ground", "ts-ground");

    let platformLayer = tilemapGround.createStaticLayer("platform-layer", tilesetGround, 0, 0).setScale(3);
    platformLayer.setCollisionByProperty({ collides: true });

    const debugGraphics = this.add.graphics().setAlpha(0.75);
    platformLayer.renderDebug(debugGraphics, {
        tileColor: null, // Color of non-colliding tiles
        collidingTileColor: new Phaser.Display.Color(243, 134, 48, 255), // Color of colliding tiles
        faceColor: new Phaser.Display.Color(40, 39, 37, 255) // Color of colliding face edges
    });
}
```

## Additional Information

![screenshot_20180912_191558](https://user-images.githubusercontent.com/4410086/45422674-7dc8f500-b6c3-11e8-86a2-39ab45032ecd.png)

**Comment by the-realest-stu** [comment]
I've also noticed this issue in 3.12.0. I've been sticking with 3.12.0-beta3 since the problem does not occur with that build of Phaser.

**Comment by the-realest-stu** [comment]
Turns out this has been fixed in version 3.13.0.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

The issue was with the debug graphic, not the collision btw.

**Comment by JasonHK** [comment]
Thanks for your help, it's working perfectly now.
