### ISSUE TITLE
DOMElement scaling.

### ISSUE THREAD

**Issue by kanthi0802** [photonstorm/phaser#4031]
Using phaser 3.12

We've started using DOMElement and it's pretty good. However we have few queries. Do we need to write CSS rules when using DOMElement for different mobile screens/ DPI or will this be handled by Phaser . Because we've observed the UI does not fit properly on devices with high resolution ( viz devicePixelRatio greater than 2 ). 

thanks.

**Comment by kanthi0802** [comment]
@photonstorm any update on this. We were expecting DOMElement's in 3.14. I see they have been pushed. Any word on the above ?

**Comment by photonstorm** [comment]
They were only ever experimental, never part of the official build and not in the change log or docs, so shouldn’t have been used in production either. I will return to them later, but for now there are other things to do first.

**Comment by photonstorm** [comment]
Not for several months, and harassing me will have the opposite effect to speeding things up.

**Comment by kanthi0802** [comment]
is this implemented now ?

**Comment by photonstorm** [comment]
Yes, DOM Elements are now part of the official build and no longer experimental. Yes, you'll have to rewrite your own rules to handle device-specific scaling for them.
