### ISSUE TITLE
Cursor does not reset when interactive object is destroyed while hovered

### ISSUE THREAD

**Issue by pantoninho** [photonstorm/phaser#4033]
## Version
* Phaser Version: v3.12.0 (but still present in v3.13.0-beta1)
* Operating system: OSX
* Browser: Reproducible in Firefox and Chrome (maybe Safari too, can't test)

## Description

If an interactive sprite has a custom cursor (custom as in different from the default one) and is destroyed while the cursor is hovering it, the cursor does not reset to the default state.
I guess the same will happen if a scene's input plugin has a custom pointer and is destroyed while its' being hovered.

## Example Test Code

https://labs.phaser.io/edit.html?src=src\input\game%20object\use%20hand%20cursor.js
https://labs.phaser.io/edit.html?src=src\input\cursors\custom%20cursor.js

In both examples, add the piece of code below, and click the sprite.
```
  sprite.on('pointerup', () => sprite.destroy());
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by pantoninho** [comment]
It did fix the issue, but two visual glitches surfaced on my game. one related to generating textures from graphics and another one related to re-sizing images.

I can't go into more detail right now, but I'll post more data soon.
