### ISSUE TITLE
RenderTexture resize not working with webgl

### ISSUE THREAD

**Issue by jbpuryear** [photonstorm/phaser#4034]
In the constructor for RenderTexture the [comments](https://github.com/photonstorm/phaser/blob/a5338955697ccadf2925c8feb39e21b45bafc8dd/src/gameobjects/rendertexture/RenderTexture.js#L120) say an instance is only has its canvas property populated if  it's using the canvas renderer, but it looks like it's getting populated no matter what. Is this supposed to happen? It's causing an issue with resize because resize [skips the webgl stuff](https://github.com/photonstorm/phaser/blob/a5338955697ccadf2925c8feb39e21b45bafc8dd/src/gameobjects/rendertexture/RenderTexture.js#L259) if the canvas property is set.

Setting canvas to null causes the right code to run, but that code throws `Uncaught TypeError: Failed to execute 'framebufferTexture2D' on 'WebGLRenderingContext': parameter 4 is not of type 'WebGLTexture'`. 

but changing `this.framebuffer = this.renderer.createFramebuffer(width, height, this.texture, false);`

to `this.framebuffer = this.renderer.createFramebuffer(width, height, this.frame.source.glTexture, false);`
seems to fix this.

**Comment by TadejZupancic** [comment]
I've been trying to add some feature to the RenderTexture source and have also noticed (and probably fixed) that, but did not have time to test everything enough to make a pull request.

Besides changing the line you mention, I think 

```
if (this.canvas)
{
    this.canvas.width = width;
    this.canvas.height = height;
}
else
{
```
has to be changed to
```
if (this.canvas)
{
    this.canvas.width = width;
    this.canvas.height = height;
}
if (this.gl)
{
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
