### ISSUE TITLE
Tiles from Tiled are not rotated in Phaser when using static layers (no longer needs an example)

### ISSUE THREAD

**Issue by thisredone** [photonstorm/phaser#4037]
## Version
* Phaser Version: 3.12.0
* Tiled Version: 1.1.6

## Description
I don't think this is related to #3778 but I dunno. This could also be a bug in Tiled but I can't decipher the exported json to know if the rotation is there.

Tiles rotated in Tiled and then exported (embedded, single-image tileset) to JSON and loaded with
```javascript
this.load.tilemapTiledJSON('map', 'assets/map.json');
```
are displayed in their default form - they're not rotated.

**Comment by photonstorm** [comment]
This rotated tile test case appears to be working fine:

http://labs.phaser.io/view.html?src=src%5Cgame%20objects%5Ctilemap%5Ctests%5Cvisual%20flipping%20test.js

Do you have a test that demonstrates otherwise?

**Comment by thisredone** [comment]
Yes, https://codepen.io/thisredone/pen/XPxzJN
It seems that it works ok with `createDynamicLayer` but fails when using `createStaticLayer`

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
