### ISSUE TITLE
[3.13 beta 1] tileSprite.setFrame() doesn't work properly

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#4039]
In v3.13  beta, calling `setFrame()` on a Tile Sprite doesn't have the intended effect, the frame doesn't change but the size is distorted. Reproduced in [this example](http://labs.phaser.io/edit.html?src=src\game%20objects\tile%20sprite\Atlas.js): adding `images[0].setFrame('bunny');` at the end of `create()` should change the frame of the first scrolling column, but it doesn't. Both frames (the old and the new) belong to the same atlas.

Interestingly, adding `images[0].setFrame('bunny');` in `update()` instead, so that it's called every frame, does work! I guess this suggests that at some point the change of frame is overridden by internal code. 

I reproduce it here in v13.3 beta1 but I initially encountered the issue in my project which uses v3.12.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
