### ISSUE TITLE
Scale manager missing functions

### ISSUE THREAD

**Issue by isaacjohnsononline** [photonstorm/phaser#4042]
Just noticed some empty functions within the scale manager class, namely [resizeHandler](https://github.com/photonstorm/phaser/blob/master/src/boot/ScaleManager.js#L222), and [doc links](https://github.com/photonstorm/phaser/blob/master/src/boot/ScaleManager.js#L80) to a non-existent setMinMax function. 

Is the scale manager still a WIP?

**Comment by photonstorm** [comment]
Very much so, that is why it's not included in the build or docs.

Please see the Dev Log in Issue 128 of Phaser World for a roadmap for the next few versions.
