### ISSUE TITLE
Adding a group to a container throws an error

### ISSUE THREAD

**Issue by kanthi0802** [photonstorm/phaser#4045]
Adding a group to a container throws the following error
<img width="398" alt="screen shot 2018-09-20 at 2 38 35 pm" src="https://user-images.githubusercontent.com/38486571/45808276-0c043300-bce3-11e8-8ac2-aa68e2e02e50.png">

**Comment by photonstorm** [comment]
This is correct because you can't add a Group to a Container because a Group isn't a display object. It's just a glorified array at heart. It has no events or display properties of its own. You could add all the children of the Group to the Container: `container.add(group.getChildren())`

**Comment by kanthi0802** [comment]
okay.... :)

**Comment by spayton** [comment]
I tried to do exactly the same.  The docs say container.add() will add a Game Object and a group is a Game Object.  The docs should maybe be more specific that only some types of Game Object can be added this way, or allow the add function to pull the children from a group and add them as the user expects.
