### ISSUE TITLE
Unpredictable SVG behaviour on iOS

### ISSUE THREAD

**Issue by kirillbunin** [photonstorm/phaser#4047]
## Version
* Phaser Version:
v3.12.0
* Operating system:
iOS 10, iOS 11
* Browser:
Safari

## Description

As we discussed on Discord, some SVGs may break the expected behavior of other files on iOS Safari.

## Example Test Code

* Example URL:
http://test.kirillbunin.com/

* Example URL which works on all devices, due to the removal of `ball`:
http://test.kirillbunin.com/index2.html

* Download example
http://test.kirillbunin.com/package.zip

* Screenshot of correct behaviour
http://test.kirillbunin.com/correct.png

* Screnshot of bad iOS10 behaviour
http://test.kirillbunin.com/ios10.png

* Screnshot of bad iOS11 behaviour
http://test.kirillbunin.com/ios11.jpg

* Screnshot of bad iPad behaviour (provided by @hypertrifle, thx)
http://test.kirillbunin.com/ipad.png

## Additional Information

This is debunk of my previous issue #3667 where I thought problem is in loading. By further research I now think it is in the way SVG behave.

**Comment by photonstorm** [comment]
Sorry, but am closing this issue off as it's been 4 years and we never found an easy way to resolve it at the time, and it hasn't been reported since, so I believe it's either no longer an issue (or such an edge case no-one else encountered it since)
