### ISSUE TITLE
Uncaught exceptions if game is destroyed while loading assets

### ISSUE THREAD

**Issue by pantoninho** [photonstorm/phaser#4049]
## Version

* Phaser Version: 3.12.0

* Operating system: OSX

* Browser: not browser specific

## Description

If `game.destroy()` is called while a scene is preloading assets, some unhandled exceptions pop up.

Is phaser supposed to handle this edge case?

Exceptions that pop up (they are not consistent):
![screen shot 2018-09-21 at 12 03 09](https://user-images.githubusercontent.com/14220276/45877708-ad988c80-bd96-11e8-8f38-4c8bcf61beb3.png)
![screen shot 2018-09-21 at 12 03 23](https://user-images.githubusercontent.com/14220276/45877712-affae680-bd96-11e8-937b-032151f7bb31.png)
![screen shot 2018-09-21 at 12 03 59](https://user-images.githubusercontent.com/14220276/45877716-b1c4aa00-bd96-11e8-930d-ca4c870ef97f.png)

## Example Test Code

with this example: https://labs.phaser.io/edit.html?src=src\game%20objects\sprites\multiple%20sprites.js

add the following line after `var game = new Phaser.Game(config);`

```
setTimeout(() => {
    console.log('destroying');
    game.destroy()
}, 10);
```

You may change the timeout duration to see different exceptions being thrown.

**Comment by photonstorm** [comment]
I suspect it's just the xhr calls returning, regardless of the fact the Game instance has been destroyed and trying to carry on, creating a texture, etc.

Part of me honestly doesn't care this happens, because you should never do it anyway. And if you do, this is the consequence. Equally, I'd accept a non-invasive PR that resolved it, as long as it's a nice small change to the Loader.

**Comment by pantoninho** [comment]
There are some times where you have no other options but to do it. 

I'm building a SPA with multiple sequential phaser games. You can navigate through games and It's probable that a user navigates to a new game while the current one is still preloading.

I could prevent the user from navigating while the current game is still preloading but that would add up to a terrible UX if the internet connection is slow (the user would have to download all current game assets just to navigate to the next one).

I'll have a look at it.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
