### ISSUE TITLE
3.13v . Strange WEBGL warnings when using CanavsTexture and Graphics

### ISSUE THREAD

**Issue by kanthi0802** [photonstorm/phaser#4050]
Using 3.13 . 
Looks like the operations made on CanvasTexture and Graphics objects are not working. 
Attached is the screen shot showing the warings in WEBGL. 
<img width="1087" alt="screen shot 2018-09-21 at 4 34 21 pm" src="https://user-images.githubusercontent.com/38486571/45878384-7342e580-bdbe-11e8-91aa-33f585d768dd.png">

**Comment by photonstorm** [comment]
Post the code you're using, because all the Graphics examples I tested against 3.13 still work fine, i.e.:

http://labs.phaser.io/view.html?force=WebGL&v=3.13.0&src=src\game%20objects\graphics\Graphics%20Rendering.js

**Comment by kanthi0802** [comment]
Below is the code 

        var graphicsOne = new Phaser.GameObjects.Graphics(this.scene);
        graphicsOne.fillStyle("0X2A2A2A");
        graphicsOne.fillRect(0, 0, this.explicitWidth, this.rowHeight);

        var graphicsTwo = new Phaser.GameObjects.Graphics(this.scene);
        graphicsTwo.fillStyle("0x1F1F1F");
        graphicsTwo.fillRect(0, 0, this.explicitWidth, this.rowHeight);


        graphicsOne.generateTexture("0", this.scene.game.config.width, this.rowHeight);
        graphicsTwo.generateTexture("1", this.scene.game.config.width, this.rowHeight);

----------------
And this is for the CanvasTexture.

var separatorTexture = this.scene.textures.createCanvas("lineSeparator", 1, this.explicitHeight);
        var source = separatorTexture.getSourceImage();
        var context = source.getContext("2d");
        var gradient = context.createLinearGradient(0, 0, 0, this.explicitHeight);
        gradient.addColorStop(0, "#1D1D1D");
        gradient.addColorStop(0.5, "#ffffff");
        gradient.addColorStop(1, "#131313");
        context.fillStyle = gradient;
        context.fillRect(0, 0, 1, this.explicitHeight);
        separatorTexture.refresh();

**Comment by kanthi0802** [comment]
Here is a fiddle [issue](https://jsfiddle.net/nz6u2gLw/4/)

**Comment by photonstorm** [comment]
Ok, that makes more sense now (being the call to `generateTexture`, not just Graphics objects in general). Equally, it appears the call to `refresh()` does the same, as if you skip that, it works fine.

Will have a look as a priority.

**Comment by kanthi0802** [comment]
Ok. And in between, I've sent a mail to you on support@phaser.io. Could you please look into it :) 

thanks.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by kanthi0802** [comment]
working fine now. thanks

**Comment by panganibanpj** [comment]
seeing a similar issue now w `renderTexture`. Here's a [fiddle](https://jsfiddle.net/omjnfk57/1/)
here's the code:
```javascript
  var circle2 = this.add.circle(0, 0, 80, 0x6666ff);
  var rt = this.add.renderTexture(0, 0, 160, 160);
  rt.draw(circle2, 80, 80);
  rt.saveTexture('circle');
  // these 2 lines make it the error happen and never draw my circle
  // to fix, either:
  //	don't add the 'test' frame,
  //	use '__BASE' frame for sprite
  //	or don't pass a frame name
  rt.texture.add('test', 0, 0, 0, 80, 80);
  this.add.sprite(320, 320, 'circle', 'test');
```

the same exact error message is appearing the in console:
`WebGL: INVALID_OPERATION: bindTexture: attempt to use a deleted object`

**Comment by photonstorm** [comment]
@panganibanpj please don't necro-post _13 month old_ issues if they are closed! as it will never be seen or dealt with.
