### ISSUE TITLE
Fix animations memory leak

### ISSUE THREAD

**Issue by Aveyder** [photonstorm/phaser#4051]
Bug is the same like: https://github.com/photonstorm/phaser/pull/4024#event-1841241172

After destroying Sprites the AnimationManager continue holding "remove" event listener (animation.remove) which causes memory leak.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
