### ISSUE TITLE
.setOrigin(0,0) does not update collision box in arcade physics

### ISSUE THREAD

**Issue by SolarOmni** [photonstorm/phaser#4052]
## Version

* Phaser Version: 3.13.0

* Operating system: Windows 10

* Browser:

## Description

Setting the origin to (0,0) on a sprite and turning on debug for arcade physics shows that the collision box does not update properly along with the image, is this an issue?

**Comment by KingCosmic** [comment]
pasting the following code into [This example](http://labs.phaser.io/edit.html?src=src\game objects\sprites\single sprite.js)

gives the output @SolarOmni was talking about

```js
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    physics: {
        default: 'arcade',
        arcade: {
            debug: true,
            gravity: {y: 0}
        }
    },
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

var bunny;

function preload() {

    this.load.image('bunny', 'assets/sprites/bunny.png');

}

function create() {

    bunny = this.physics.add.sprite(400, 300, 'bunny').setOrigin(0);

}```

for a easy visual reference

![image](https://user-images.githubusercontent.com/24766991/45918936-d7fc4f80-be53-11e8-82a8-9e20a3814ebe.png)

the collider does not update properly when the sprite has changed it's origin from 0.5, 0.5 was unsure if this is ment to happen or a bug

**Comment by samme** [comment]
<https://codepen.io/samme/pen/vzMzBZ?editors=0010>

**Comment by KingCosmic** [comment]
@photonstorm you say "for now" what sorta implementation do you have in mind? I feel like having the bounds sync with the sprite would make sense so an option on the physics body?

**Comment by KingCosmic** [comment]
if you let me know what you have in mind I could go about making a pr for it

**Comment by KingCosmic** [comment]
ah I understand

**Comment by photonstorm** [comment]
This is now in 3.14 so will remain active unless any issues arise.
