### ISSUE TITLE
setOrigin for scaled BitmapText

### ISSUE THREAD

**Issue by Aveyder** [photonstorm/phaser#4054]
setOrigin works incorrectly for scaled BitmapText.

For example: 

 let word1 = new BitmapText(this, 300, 300, "my_font", 'hello!', 72);
            word1.setOrigin(0.5, 0.75);
            word1.setScale(0.5,0.5);
            word1.setOrigin(0.5, 0.75);
            word1.setScale(1,1);

            let word2 = new BitmapText(this, 300, 300, "my_font", 'hello!', 72);
            word2.setOrigin(0.5, 0.75);

            this.add.existing(word1);
            this.add.existing(word2);

I think that both of words should eventually be on the same place, but actually they don't.

**Comment by B3L7** [comment]
Can confirm. Having the same issue. I created this repo as an example:

[Example](https://github.com/B3L7/phaser3BitmapTextScale/tree/master)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
