### ISSUE TITLE
Spritesheet textures don't appear in Light2D pipeline

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#4055]
## Version

* Phaser Version: 3.13.0

## Description

Loaded a spritesheet with normal map. Also an image from the same assets, for comparison.

Created two Image objects and added to Light2D pipeline.

The image-texture object (left side of canvas) is lit correctly, in yellow.

The spritesheet-texture object (right side) is invisible.

## Example Test Code

<https://codepen.io/samme/pen/aaMYEz?editors=0010>

## Additional Information

TextureManager#addSpriteSheet doesn't add a data source?

**Comment by photonstorm** [comment]
Yup, duplicate of #3995
