### ISSUE TITLE
Incorrect LayerData's fields used

### ISSUE THREAD

**Issue by imilo** [photonstorm/phaser#4057]
## Version
* Phaser Version: 3.13

## Description

In `Tilemap.js` (https://github.com/photonstorm/phaser/blob/master/src/tilemaps/Tilemap.js) there is a function `setBaseTileSize`, which contains:
```javascript
this.layers[i].baseWidth = tileWidth;
this.layers[i].baseHeight = tileHeight;
```

.. here `this.layers[i]` is a `LayerData` object and it doesn't has the fields **baseWidth** and **baseHeight**. Maybe this should be instead:
```javascript
this.layers[i].baseTileWidth = tileWidth;
this.layers[i].baseTileHeight = tileHeight;
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
@mikewesthad should this update `baseTileWidth` AND `tileWidth`, or just one or the other?

**Comment by mikewesthad** [comment]
Good catch - thanks @imilo.

@photonstorm, yeah this method should update both `Tilemap.tileWidth` and `LayerData.baseTileWidth` (but not `LayerData.tileWidth`). It looks good with the recent commit. `Tilemap.tileWidth` and `Tilemap.tileHeight` represent the base tile size / grid size for all the layers. The `LayerData.baseTileWidth` & `LayerData.baseTileHeight` are for convenience (mainly for the shared functions like `TileToWorldX` which operate on LayerData).
