### ISSUE TITLE
process undefined

### ISSUE THREAD

**Issue by hollowdoor** [photonstorm/phaser#4058]
I'm using version 3.13, and I'm on Linux. I'm also transpiling with rollup.

When I run phaser in the browser I get a `process is undefined` error.

This comes from the environment checks:

```javascript
if (process && process.versions && process.versions.node)
	    {
	        OS.node = true;
	    }
```

If the first part of the logic `process` is changed to `typeof process !== 'undefined'` that should fix it.

Like:

```javascript
if (typeof process !== 'undefined' && process.versions && process.versions.node)
	    {
	        OS.node = true;
	    }
```

This problem can be partially fixed by adding a global to the page like `let process = null`, but I think it would be better if it were fixed in the phaser code base.

**Comment by photonstorm** [comment]
This must be something that happens in your build process because no mobile or desktop browser throws this error using the dist build. While it could be fixed with a `typeof` check, that still doesn't get to the root of the problem.

**Comment by hollowdoor** [comment]
Depending on how you look at it it is the build process, or it's not the build process. It's really more of opinion on what's a viable inclusion of APIs from node that ends up being a part of the build.

There's this code in the built phaser.js file (line 144923 as of today):

```javascript
// shim for using process in browser
var process = module.exports = {};
```
A shim can also be inserted using rollup with a prepend, but it feels like something that will potentially make things harder than it's worth down the line. I don't know where that shim comes from. Base rollup doesn't create it because base rollup only transpiles modules.

As I said it can be fixed by adding a global `let process = null;` so I have it shimmed, and so technically the build works even when the shim is not present in the build. So it's not the build, or it is the build. The error is actually for variables that are not declared within a scope.

```html
<script>
//Fixes process undefined error
let process = null;
</script>
```

**Comment by samme** [comment]
`process` is shimmed in the dist script (via webpack), but not in the src script.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
