### ISSUE TITLE
activePointer.worldX & worldY bug

### ISSUE THREAD

**Issue by Aveyder** [photonstorm/phaser#4059]
I have 4 scenes at one time. The second scene from the top is outputing the worldX & worldY position of activePointer:
![bug](https://user-images.githubusercontent.com/1591844/45929593-97d4c400-bf5c-11e8-8433-de8d39113a8d.png)

When I had 2 scenes (and this scene was also the second from the top) I hadn't encountered this problem.

Phaser version 3.12

If I'm trying to output the world position of active pointer from the top scene I get this:
![2](https://user-images.githubusercontent.com/1591844/45929751-94423c80-bf5e-11e8-9314-8656743f6196.png)

If I'm trying to output from the bottom scene - ALL IS OK!

**Comment by Aveyder** [comment]
I could reproduce only the second case, but I guess it can give a clue to resolve the first one:

class MainScene extends Phaser.Scene {
    constructor ()
    {
        super('MainScene');
    }
    create ()
    {
        this.scene.get('SceneOne').scene.restart();
    }
}

class SceneOne extends Phaser.Scene {
    constructor ()
    {
        super('SceneOne');
    }
    create ()
    {
        let frame = this.add.graphics();
        frame.lineStyle(3, 0xFFFFFF);
        frame.strokeRect(0, 0, 1024, 768);
        this.cameras.main.setZoom(0.5);
        this.cameras.main.setScroll(-100, -100);
    }
    update() {
        console.log(this.input.activePointer.worldX, this.input.activePointer.worldY);
    }
}

let config = {
    type: Phaser.CANVAS,
    scene: [MainScene, SceneOne]
};

let game = new Phaser.Game(config);

**Comment by photonstorm** [comment]
Sorry for leaving this issue open for so long - it was actually fixed way back in version 3.16!
