### ISSUE TITLE
Tilemap layer renderDebug does not count in the layer position

### ISSUE THREAD

**Issue by Zax37** [photonstorm/phaser#4061]
Checked on DynamicTilemapLayer. To replicate:

- create new layer with x, y > 0
- set some tiles as colliding
- call renderDebug on that layer

The debug layer is drawn in wrong place, not taking layer's position into account.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
