### ISSUE TITLE
Time.Clock.now does not return actual current time

### ISSUE THREAD

**Issue by SolarOmni** [photonstorm/phaser#4064]
## Version

* Phaser Version: 3.13.0

* Operating system: Windows 10

* Browser:

## Description

The property  Time.Clock.now always returns the same time from when the clock was made, not the actual current time. Is this intended?

## Example Test Code

```
import "../src/lib/phaser.js";

var Scene = new Phaser.Class( {
	Extends: Phaser.Scene,

	preload: function preload ()
	{
	
	},

	create: function create ()
	{
		this.clock = new Phaser.Time.Clock(this);
		this.timeText = this.add.text(0, 0, "Nothing");
	},
	
	update: function update(time, delta)
	{
		this.timeText.text = this.clock.now.toString();
	}
});

var config = {
    type: Phaser.CANVAS,
    width: 800,
    height: 600,
    backgroundColor: '#000000',
    parent: 'phaser-example',
    pixelArt: true,
    scene: [Scene],
}
var game = new Phaser.Game(config);
```

**Comment by photonstorm** [comment]
If you create your own instance of a Clock then you are responsible for updating it.

Scene's have a Clock instance ready enabled (`this.time` from within the Scene) for which the value is correct, as the Scene updates it as part of the game loop.
