### ISSUE TITLE
black areas when making browser window bigger

### ISSUE THREAD

**Issue by Quinten** [photonstorm/phaser#4066]
## Version

* Phaser Version: 3.13

* Operating system: OS X 10.13.6 (High Sierra)

* Browser: Chrome 69

## Description

When you have a game config set to autoResize, the rendering context doesn't seem to resize well. When you load the following example in a browser window that is half the size of the screen and then make it larger, a black area will appear.

## Example Test Code

You can see it in the following example: https://labs.phaser.io/view.html?src=src\game%20config\game%20resize.js

Also when you run the following code, you would expect to see a complete blue screen, when you resize, but instead a black area appears.

```
var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: window.innerWidth,
    height: window.innerHeight,
    autoResize: true,
    backgroundColor: '#00FF00',
    scene: {
        create: create,
        resize: resize
    }
};

function create ()
{
    document.body.background = '#FF0000';
    this.cameras.main.setBackgroundColor('#0000FF');
    this.events.on('resize', resize, this);
}

function resize (width, height)
{
    if (width === undefined) { width = this.sys.game.config.width; }
    if (height === undefined) { height = this.sys.game.config.height; }
    this.cameras.resize(width, height);
}

var game = new Phaser.Game(config);

window.addEventListener('resize', function (event) {
    game.resize(window.innerWidth, window.innerHeight);
}, false);
```

**Comment by totov** [comment]
Changing the config from `type: Phaser.AUTO` to `type: Phaser.CANVAS` stops this behaviour, so I think we can narrow it down to the WebGL renderer if that helps at all.

**Comment by samme** [comment]
I see the same problem (black areas after resizing from small to large) in the [example](https://labs.phaser.io/view.html?src=src%5Cgame%20config%5Cgame%20resize.js) even after removing `autoResize: true`.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by Quinten** [comment]
I've tested it with a build with that commit and can confirm it is fixed. Thanks!

**Comment by hsan999** [comment]
I have tested with 3.14 and can confirm that a build using ONLY phaser.min.js works.  However, if I include phaser-arcade-physics.min.js OR phaser-facebook-instant-games.min.js the old behavior is still observed (not filling screen).  Simply including them in the html file causes this behavior.  Thanks for the quick response on this issue.  Original post #4076

**Comment by photonstorm** [comment]
@hsan999 sort your browser cache out / local cache, because I guarantee those versions work just fine.

**Comment by hsan999** [comment]
ok will do that, thanks.
