### ISSUE TITLE
Adding Matter body to Polygon breaks origin

### ISSUE THREAD

**Issue by iamchristopher** [photonstorm/phaser#4067]
## Version

* Phaser Version:
v3.13.0 and v3.14.0-beta1

* Operating system:
OSX 10.13.6

* Browser:
Chrome 69.0.3497.100

## Description

When adding a Matter body to a Polygon Shape, it appears to break the origin (resetting it to 0,0). Manually using `setOrigin` or `setDisplayOrigin` doesn't seem to fix it. It's possible that I'm missing something in the setup, but I believe I'm doing this correctly and that it's a bug.

## Example Test Code

Below is a repro case I wrote in the labs (I couldn't figure out how to save it there, though).

```js
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#1b1464',
    parent: 'phaser-example',
    physics: {
        default: 'matter',
        matter: {
            debug: true
        }
    },
    scene: {
        create: create
    }
};

var game = new Phaser.Game(config);

function create ()
{
    this.matter.world.setBounds().disableGravity();

    var data = [
        0, 0,
        50, 0,
        50, 50,
        0, 50
    ];
    var poly = this.add.polygon(0, 0, data, 0x0000ff, 0.8);
    this.matter.add.gameObject(poly);
}
```

## Additional Information

N/A

**Comment by photonstorm** [comment]
Running your code against the master branch (or 3.13 actually) gives me the origin reported as 0.5 as seen in the following screenshot (the red dot is the center of the screen, 400x300):

![image](https://user-images.githubusercontent.com/164476/46068442-12762d00-c171-11e8-9fd2-f8bda9eea5a5.png)

I made one change to your code, I positioned the polygon at 400x300 to test origin alignment with the red dot marker.

**Comment by iamchristopher** [comment]
@photonstorm I left out the important bit, my apologies. I meant to say that I set origin to 0,0 before creating the body, and then the origin is reset to 0.5,0.5 afterwards.

```js
var poly = this.add.polygon(0, 0, data, 0x0000ff, 0.8).setOrigin(0, 0);
this.matter.add.gameObject(poly);
```

**Comment by photonstorm** [comment]
This is correct, all Game Objects that are given a Matter physics body have their origin updated to reflect the render offset of the Body, which is adjusted based on the shape data.

**Comment by iamchristopher** [comment]
Is the solution to set origin to 0,0 again? If I do, I end up with this:
![image](https://user-images.githubusercontent.com/5909516/46078957-ad680a80-c163-11e8-9ce4-44ef4757de76.png)

**Comment by photonstorm** [comment]
Nope, you have to provide an offset from the Matter shape data to the Game Object itself:

```
    var triangle = this.matter.add.sprite(400, 100, 'triangle', null, {
        shape: { type: 'fromVerts', verts: shapes.triangle },
        render: { sprite: { xOffset: 0.30, yOffset: 0.15 } }
    });
```

(from http://labs.phaser.io/view.html?src=src\physics\matterjs\offset%20body.js)

**Comment by iamchristopher** [comment]
I see. So I have to position the GO from 0.5,0.5 now? I'd prefer to do it from 0,0 but if that's the way it is then I can adjust. What is the unit of the offset? I set the `xOffset` to 0.025 without setting the `yOffset` and I don't really understand why it fixed the positioning.

**Comment by photonstorm** [comment]
As soon as you apply a Matter Physics body to any Game Object, the x and y coordinates (as well as the rotation and scale) are no longer that of the Game Object, but of the Matter Body itself. Changes made to the body are reflected in the Game Object. So the x/y values are now the computed center of the body (depending on the shape, compound bodies, etc).

All the `xOffset` does is allow you to modify the relationship between the body x/y and where the texture is drawn. It's a number that defines the offset in the x-axis for the sprite (normalised by texture width).

You can change the origin as well to modify where the texture is drawn, but you're changing it in relation to the body. Most the time the texture and body should align. If you want to adjust where the center of the body actually is, that's a different thing altogether (i.e. to apply rotation to a rectangle from say the bottom corner)

**Comment by photonstorm** [comment]
I'm going to close this because I'm happy it's not actually a bug, but feel free to keep on commenting if you need.

**Comment by iamchristopher** [comment]
Thanks for all your help and explanations on this, @photonstorm. I haven't solved this for myself yet (I can't wrap my head around manipulating the body/ sprite relationship) but I've come up with a different implementation that got the job done.
