### ISSUE TITLE
3.13 Line Shape Doc doesn't mention lineWidth parameter

### ISSUE THREAD

**Issue by netgfx** [photonstorm/phaser#4068]
## Version

* Phaser Version:
3.13
* Operating system:
Windows
* Browser:
Chrome

## Description

The new (3.13) Line Shape `setStrokeStyle( [color] [, alpha])` doesn't mention lineWidth parameter, resulting in invisible lines when used (because alpha is read as the color)

https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Shape.html#setStrokeStyle

## Example Test Code

```
let r1 = this.add.line(200, 200, 0, 0, 0, 100, 0x6666ff);
r1.setStrokeStyle(0xff0000, 1.0);
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
