### ISSUE TITLE
Masking stops working when adding to child of container.

### ISSUE THREAD

**Issue by Restrictment** [photonstorm/phaser#4071]
## Version

* Phaser Version: 3.12

## Operating System
* Operating system: Windows 10 x64

## Browser
* Browser: Chrome

## Description

When adding either a bitmap mask or a geometry mask, the masking stops when applied to an element of a container.

## Example Test Code

```
let rec = this.add.graphics({ fillStyle: { color: color }});
rec.displayOriginX = width * .5;
rec.displayOriginY = height * .5;
rec.fillRectShape(new Phaser.Geom.Rectangle(x, y, width, height));

 let mask = new Phaser.Display.Masks.BitmapMask(this, rec);
maskedChild.setMask(mask);

let container = new Phaser.GameObjects.Container(this);
this.add(container);
container.add(maskedChild); 
```

**Comment by Restrictment** [comment]
Turns out this just does not work with the Phaser.image class.

**Comment by photonstorm** [comment]
From the Container docs:

```
 * Containers can have masks set on them and can be used as a mask too. However, Container children cannot be masked.
 * The masks do not 'stack up'. Only a Container on the root of the display list will use its mask.
```

**Comment by Restrictment** [comment]
@photonstorm Is there a plan to allow masks to be added to children in the future? I feel like this will be a common request.

**Comment by photonstorm** [comment]
Not at this moment in time, no. Masks will need to be recoded completely before this will work.
