### ISSUE TITLE
add.tileSprite in new version is not convenient to use

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#4073]
in previous version I can pass width/height with 0 to add.tileSprite `add.tileSprite(x, y, w, h, atlas, frame)`;

but in 3.13 pass width/height with 0 will cause error because the class wants to fetch imageData from the canvas.

my purpose is to create a tileSprite and use its frame to init the width / height:

    const spr = this.scene.add.tileSprite(0, 0, 0, 0, "atlas", "ground");
    spr.width = spr.frame.width;
    spr.height = spr.frame.height;

this works in previous verison but 3.13.
the problems:

1. can't pass width/height as 0
2. when pass width/height as 1 and finally created a tileSprite, but you will find both `spr.frame.width, spr.frame.height` are 0 which does not exist in previous version.

**Comment by jcyuan** [comment]
and actually.... the image added to scene is cut, I don't know why....

**Comment by photonstorm** [comment]
If you now pass zero as either the width or height of a TileSprite it will use the size of the texture frame as the width and height. If you want to change it like you were doing before, you need to get the size from the `displayTexture` and `displayFrame` properties, not `texture` and `frame` which just refer to the canvas the texture has been drawn to.

**Comment by jcyuan** [comment]
got it, thanks
