### ISSUE TITLE
zooming camera applies twice (i.e. zoom value is quadratic) on tilemaps

### ISSUE THREAD

**Issue by baturinsky** [photonstorm/phaser#4075]
## Version

* Phaser Version:
3.12.0
* Operating system:
Windows 7
* Browser:
Firefox and Chrome

## Description

Zooming camera applies twice on tilemaps. I.e. zoom(n) will work as zoom(n*n) on tilemaps

## Example Test Code

```scene.cameras.main.setZoom(2)```

**Comment by photonstorm** [comment]
![camera-zoom-test](https://user-images.githubusercontent.com/164476/46279335-ba6c6b80-c560-11e8-9f31-38ce18a0ee85.png)

If you can provide a code example demonstrating this bug I can re-open it and investigate, but as is, there's not enough information and it doesn't manifest in a simple test.
