### ISSUE TITLE
setVelocity bug

### ISSUE THREAD

**Issue by LoolzRules** [photonstorm/phaser#4078]
I'm making top-down game with player facing in direction of mouse pointer. Strange player shaking is present, like he is ttrying to look a two points at the same time. I tried to investigate the reasons and here is what i have found:
I try to set velocity of my player by using setVelocity on his physics body each scene.update() call:
```
// x direction - AD keys
if ( d && !a ) this.container.body.setVelocityX( this.speed );
else if ( a && !d ) this.container.body.setVelocityX( -this.speed );
else this.container.body.setVelocityX( 0 );
// y direction - WS keys
if ( s && !w ) this.container.body.setVelocityY( this.speed );
else if ( w && !s ) this.container.body.setVelocityY( -this.speed );
else this.container.body.setVelocityY( 0 );
```
On some ticks, however, he moves exactly twice as fast as he should have moved. I check this by logging the differerence between his old and current positions in scene.update(). Both `body.deltaAbsX()` and `body.deltaAbsY()` show that change is constant.

if I change player position manually everything but collisions works smooth as hell. Since I need collisions I need to use setVelocity

Also, the most annoying thing - player moves with correct velocity first seconds after page reload, then fps drops from 60 to 35 and shaking starts

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

If it's easier, use a service like Code Sand Box or JSBin to demonstrate the issue live.
