### ISSUE TITLE
More lights on Phaser3

### ISSUE THREAD

**Issue by FrancescoNegri** [photonstorm/phaser#4081]
Hi everyone, 
I'm actually working with Phaser's LightManager and I noticed that it permits to use only a pre-defined number of simultaneous lights, in particular 10. I see that limitation to avoid lights spamming, resulting in a drop of fluidity for the game, but I think that setting a default but EDITABLE value would be a better approach, if no I would like you to help me to understand why it itsn't a good idea! 
Thanks in advance for your help! :)

**Comment by photonstorm** [comment]
The value is a const available at `LightPipeline.LIGHT_COUNT` and defaults 10 lights _within the range of a single Camera_. The total you have in your game is up to you. I can make the value editable via the game config (not at 'runtime'), as it needs to be bound into the shader, but 10 is pushing it already, so increase it at your peril.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
