### ISSUE TITLE
Error thrown when particles are added to containers in CANVAS mode

### ISSUE THREAD

**Issue by maximtsai** [photonstorm/phaser#4083]
## Version

* Phaser Version: Encountered on all versions 3.12 and onwards. 3.11 does not experience this bug.

* Operating system: Windows 10

* Browser: Bug encountered on Chrome, Firefox and IE11

## Description

`Uncaught TypeError: child.setBlendMode is not a function` error is thrown when adding particles to a container while the game is in CANVAS mode.

Expected Behavior: No errors should appear by adding particles to a container in CANVAS mode.

## Example Test Code

This error can be reproduced by copy pasting the following code into a Phaser Labs example page (eg. http://labs.phaser.io/edit.html?src=src\game%20objects\particle%20emitter\create%20emitter.js)

```
var config = {
    type: Phaser.CANVAS,
    width: 800,
    height: 600,
    backgroundColor: '#000',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('spark', 'assets/particles/blue.png');
}

function create ()
{
    var particles = this.add.particles('spark');
    var container = this.add.container(0, 0);
    container.add(particles);
}
```

## Additional Information

![image](https://user-images.githubusercontent.com/6758316/46375703-f975ec00-c648-11e8-88af-77d66ab4f7fc.png)

**Comment by maximtsai** [comment]
Related question is, how do you set the depth of a particle without placing it inside a container? I'd like my particles to show on top but there's no setDepth function for particles.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

To set the depth you have to do it on the Particle Emitter Manager, not on the Emitters the manager creates. The manager can have a depth but emitters are children of the manager and render in a single pass through the manager, so you cannot change the depth on them specifically, not without creating a new manager instance.

**Comment by maximtsai** [comment]
Sweet! I'll set depth on the Particle Emitter Manager.
