### ISSUE TITLE
DataManager, behaviors between `data.set(key, value)` and `data.values.key=value`

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4084]
## Version
* Phaser Version: v 3.13

## Description

Behaviors between `data.set(key, value)` and `data.values.key=value` when **setting that key first time** are not the same.

In data manager, `data.set(key, value)` will [fire 'setdata' event](https://github.com/photonstorm/phaser/blob/master/src/data/DataManager.js#L333), and [register callback for firing 'changedata' events](https://github.com/photonstorm/phaser/blob/master/src/data/DataManager.js#L317-L327) when [setting that key first time](https://github.com/photonstorm/phaser/blob/master/src/data/DataManager.js#L294).
If uses `data.values.key=value` to set that key in the same situation, it won't fire 'setdata' event, eithor register callback for firing 'changedata' events.

[Test code](https://codepen.io/rexrainbow/pen/BqKWGv?editors=0011) :
- Only `this.data.set('var0', 300);` could fire 'setdata' event

**Comment by photonstorm** [comment]
This is fine, I'm happy with this as a limitation as the docs state to use the `values` object as a way to read or modify _already set data_. I've made the docs even more explicit.
