### ISSUE TITLE
Input on tilesprites not working

### ISSUE THREAD

**Issue by DotTheGreat** [photonstorm/phaser#4085]
## Version
* Phaser Version: v3.13.0 - v3.14.0
* Operating system: Windows 10

## Description

Input detection on tilesprites isn't working.
When pixelPerfect is set to false, a TypeError will also occur (`TypeError: input.hitAreaCallback is not a function`).

## Example Test Code

http://labs.phaser.io/view.html?src=src/input/game%20object/tilesprite%20on%20down.js&v=3.14.0

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
