### ISSUE TITLE
Shared animation frames

### ISSUE THREAD

**Issue by scarejar** [photonstorm/phaser#4090]
Discussion here:  http://www.html5gamedevs.com/topic/40368-how-to-reuse-gameanims-animations/

Animations that have a shared frame scheme, e.g
[0,1,2] are the set of frames responsible for moving a monster and player in their respective sprite sheets, would require duplicate code like so:

```javascript
        this.anims.create({
            key: 'down',

            frames: this.anims.generateFrameNumbers("playerTexture", { frames: [0, 1, 2] }),
            frameRate: 4
        });

        this.anims.create({
            key: 'down',

            frames: this.anims.generateFrameNumbers("monsterTexture", { frames: [0, 1, 2] }),
            frameRate: 4
        });
```
I was thinking in the `this.anims.generateFrameNumbers()` , the textures it takes in will be an array, for shared animation frames. 
I guess that would mean the animation key, when running `player.play("down")` , would need to be relative to the sprite sheet its using.

**Comment by jestarray** [comment]
feel like this is becoming more needed. the latest feature of Animation.on("animation{event}-key") for example
if we had a reuse animation system then it would be: ```javascript
 this.anims.create({
            key: 'walkDown',

            frames: this.anims.generateFrameNumbers("APPLY TO ALL TEXTURES", { frames: [0, 1, 2] }),
            frameRate: 4
        }).on("animationstart-walkDown", ()=>{ //play walking sound})

 this.anims.create({
            key: 'walkLeft',

            frames: this.anims.generateFrameNumbers("APPLY TO ALL TEXTURES", { frames: [0, 1, 2] }),
            frameRate: 4
        }).on("animationstart-walkLeft", ()=>{ //play walking sound})

```
then all the sprites that share the same walking frames would only have 1 listener rather than every spritesheet + their states having their own listeners that do the same thing

**Comment by samme** [comment]
<http://www.html5gamedevs.com/topic/40585-how-to-re-use-animations-for-different-sprite-sheets/?tab=comments#comment-231436>

**Comment by ouya99** [comment]
I want to create my player sprite animation inside its own file/class (modular code)

```
export default class extends Phaser.Scene {
  constructor () {

```

and use this Player sprite class in my main scene.
How can I define its animations and access them from my main class after I created the Player object? Any sample very welcome. Thanks!

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
