### ISSUE TITLE
Camera.setScene( ) doing nothing

### ISSUE THREAD

**Issue by james-pierce** [photonstorm/phaser#4094]
## Version

* Phaser Version: 3.14.0

* Operating system: Windows 10

* Browser: Chrome

## Description

I want to have 2 cameras active simultaneously, each rendering a different scene. But calling setScene on a camera does nothing. No matter which scene I set, it still renders the current scene I am in.

Cameras:
- main -> this.cameras.main
- this.cam_anticheat -> this.cameras.getCamera('cam_anticheat');

Scene I am currently in: PlayScene
this.cameras.main is rendering the PlayScene.

Second scene I want to render is: AntiCheatScene
this.cam_anticheat should render the AntiCheatScene, but it is still rendering the PlayScene.

## Example Test Code

```
this.cam_anticheat	= this.cameras.add(0, 0, 200,100, false, 'cam_anticheat');
this.cam_anticheat.setOrigin(0);
this.cam_anticheat.setScene(this.scene.manager.getScene('AntiCheat'));

// This correctly logs the AntiCheatScene but it is still rendering the PlayScene
console.log(this.cam_anticheat.scene);
```

## Additional Information

I already tried setting the AntiCheatScene to active via the SceneManager. It did not make a difference.
```
this.scene.manager.isActive('AntiCheat');
```

**Comment by photonstorm** [comment]
Camera's can only render the Scene to which the CameraPlugin (that they belong to) exists in. I will update the `setScene` method to make it private to avoid issues like this.

**Comment by james-pierce** [comment]
Understood!
