### ISSUE TITLE
v3.14 Arcade physics: zones don't overlap with bodies that have zero velocity

### ISSUE THREAD

**Issue by Quinten** [photonstorm/phaser#4098]
## Version

* Phaser Version: Phaser v3.14.0-FB
* Operating system: OS X High Sierra 10.13.6
* Browser: Chrome 69.0.3497.100

## Description

Arcade physics bodies stop overlapping with overlap zones, when you set their velocity to zero. As long as they are moving they still overlap, but as soon as they stop moving the `zone.body.touching.none` is set to `true`. The expected behavior is that they still overlap even when the other body is not in motion.

## Example Test Code

You can test this by replacing the code of example  
http://labs.phaser.io/view.html?src=src\physics\arcade\overlap%20zone.js  
with the following:

```
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    physics: {
        default: 'arcade',
        arcade: {
            debug: true,
            gravity: { y: 0 }
        }
    },
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var zone;

new Phaser.Game(config);

function preload ()
{
    this.load.image('space', 'assets/skies/space.jpg');
    this.load.image('block', 'assets/sprites/block.png');
}

function create ()
{
    this.add.image(400, 300, 'space');

    zone = this.add.zone(300, 200).setSize(200, 200);
    this.physics.world.enable(zone);
    zone.body.setAllowGravity(false);
    zone.body.moves = false;

    var group = this.physics.add.group({
        key: 'block',
        frameQuantity: 4,
        bounceX: 1,
        bounceY: 1,
        collideWorldBounds: true,
        velocityX: 0,
        velocityY: 0,
        setXY: {x: 400, y: 300}
    });

    this.physics.add.overlap(group, zone);
}

function update ()
{
    zone.body.debugBodyColor = zone.body.touching.none ? 0x00ffff : 0xffff00;
}
```

**Comment by Quinten** [comment]
I added a temporary fix in my own fork, but it might need to be expanded to include the left, right, up, down touching props.

I was wondering: why does the overlap skips 2 objects that aren't moving?

**Comment by samme** [comment]
You can check [body.embedded](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Body.html#embedded__anchor) for that case.

`collide` needs to compare body velocities to separate them.

`collide` and `overlap` need to compare body velocities to set the [touching](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Body.html#touching__anchor) directions.

**Comment by Quinten** [comment]
Ok, thanks! I wasn't sure what the body.embedded was for. Now it is clear that it is for this specific use case. I will close this issue now.
