### ISSUE TITLE
BitmapMask isn't applied when using a canvas renderer 

### ISSUE THREAD

**Issue by garethwhittaker** [photonstorm/phaser#4102]
## Version

* Phaser Version: 3.14.0
* Operating system: MacOS High Sierra

## Description

For certain devices / browsers I need to use the Canvas rather than WebGL renderer. I'm finding that bitmap masks aren't being applied when falling back to Canvas.

## Example Test Code

Use the Phaser Labs BitmapMask Example
http://labs.phaser.io/edit.html?src=src\display\masks\BitmapMask%20Example.js
and just change the renderer type to Canvas.

**Comment by photonstorm** [comment]
Canvas cannot support bitmap masking. This is a WebGL only feature (it does say as much in the docs, but it's easy to miss)
