### ISSUE TITLE
setFlipX() affects origin differently for WebGL / Canvas

### ISSUE THREAD

**Issue by garethwhittaker** [photonstorm/phaser#4103]
## Version

* Phaser Version: 3.14.0

* Operating system: MacOS High Sierra

* Browser: Multiple

## Description

Sprite origins are behaving differently when using flipX depending on the renderer type.

## Example Test Code

Using the Phaser Labs Single Sprite example
https://labs.phaser.io/edit.html?src=src\game%20objects\sprites\single%20sprite.js
add these to the `create` method and run with Canvas / WebGL renderer types.

```
bunny.setOrigin(1, 0);
bunny.setFlipX(true);
```

The bunny will be placed in differing positions.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
