### ISSUE TITLE
setOrigin() has no effect on DynamicBitmapText with Canvas renderer

### ISSUE THREAD

**Issue by garethwhittaker** [photonstorm/phaser#4108]
## Version
* Phaser Version: 3.14.0

* Operating system: MacOS High Sierra

* Browser: Multiple

## Description

I've modified one of the Phaser Labs demo's below to show how an origin applied to a DynamicBitmapText instance has no effect when using renderer type CANVAS. If you change this to WEBGL, then their origins change as expected.

## Example Test Code

```javascript
const config = {
    type: Phaser.CANVAS,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

const game = new Phaser.Game(config);

function preload() {
    this.load.bitmapFont('ice', 'assets/fonts/bitmap/iceicebaby.png', 'assets/fonts/bitmap/iceicebaby.xml');
}

function create() {
    const example1 = this.add.dynamicBitmapText(200, 200, 'ice', '10', 128)
        .setOrigin(0, 0);

    const example2 = this.add.dynamicBitmapText(200, 200, 'ice', '10', 128)
        .setOrigin(0.5, 0.5);

    const example3 = this.add.dynamicBitmapText(200, 200, 'ice', '10', 128)
        .setOrigin(1, 1);
}
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
