### ISSUE TITLE
DynamicBitmapText positioning differs in WebGL / Canvas renderers when using setScroll() on scene

### ISSUE THREAD

**Issue by garethwhittaker** [photonstorm/phaser#4109]
## Version

* Phaser Version: 3.14.0

* Operating system: MacOS High Sierra

* Browser: Multiple

## Description

I've modified one of the Phaser Labs demo's below to show how a DynamicBitmapText instance is being positioned incorrectly when using the Canvas renderer and applying a scroll to a scene. Toggling to WebGL renderer type will show the different results.

## Example Test Code

```javascript
var config = {
    type: Phaser.CANVAS,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload() 
{
    this.load.bitmapFont('desyrel', 'assets/fonts/bitmap/desyrel.png', 'assets/fonts/bitmap/desyrel.xml');
}

function create() 
{
    this.add.bitmapText(0, 0, 'desyrel', 'static bitmap text');
    this.add.dynamicBitmapText(0, 100, 'desyrel', 'dynamic bitmap text');

    this.cameras.main.setScroll(-50, -50);
}

```

**Comment by photonstorm** [comment]
Sorry for the stupid delay in looking at this. I've just tested it in Phaser 3.20 and it renders the same in both Canvas and WebGL, so this was thankfully fixed at some point (although I cannot say when!)
