### ISSUE TITLE
Phaser versions 3.12-3.14 experience worse performance compared to version 3.11 when drawing text

### ISSUE THREAD

**Issue by maximtsai** [photonstorm/phaser#4110]
## Version

* Phaser Version: Encountered on 3.12, 3.13 and 3.14. 

* Operating system: Windows 10, macOS High Sierra, iPad Pro, iPhone 6S, a bunch of other mobile devices from friends and family including Android devices.

* Browser: Tested and encountered on Chrome and Safari. Haven't tried other browsers yet.

## Description

This is probably the same issue that this guy encountered https://github.com/photonstorm/phaser/issues/4086 but I've narrowed down what I think is the performance culprit :)

Using lots of text lags the game more significantly on later versions of Phaser (3.12 onwards) compared to Phaser 3.11. This happens on both PC and mobile but is much more noticeable on mobile.

On PC, Phaser 3.14 starts encountering FPS dips at about 1/2 the number of text objects compared to v3.11. 
**MacBook Pro using Phaser v3.11:** 3000 text objects before FPS goes below 60
**MacBook Pro using Phaser v3.14:** 1500 text objects before FPS goes below 60

On mobile, Phaser 3.14 starts encountering FPS dips at about **1/100th** (no exaggeration) the number of text objects on the same device compared to v3.11.
**iPad Pro using Phaser v3.11:** 2500 text objects before FPS goes below 60
**iPad Pro using Phaser v3.14:** 15 text objects before FPS goes below 60 (ouch)

Side note: At 70 text objects, iPad Pro using Phaser v3.14 hits 5 FPS :(

## Example Test Code

```
var config = {
    type: Phaser.AUTO,
    width: 400,
    height: 300,
    antialias: true,
    backgroundColor: '#111111',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};
var game = new Phaser.Game(config);

function preload ()
{
}

function create ()
{
    this.fpsText = this.add.text(10, 10, "FPS : 0", {fontSize: 30, color: '#ffffff', align: 'left'})
    this.lastUpdateTime = 0;
    this.counter = 0;
    // Note: Mobile experiences fps dips on Phaser 3.12+ with as few as 15-20 text objects
    // Mobile Phaser 3.11 on the same device can handle nearly 3000 text objects before fps dips
    for (let i = 0; i < 4000; i++) {
        this.add.text(i*0.01, 100, "1", { fontSize: 24, color: '#F6F616'});
    }
}

function update() {
    let currTime = Date.now();
    this.counter++;
    if (currTime > this.lastUpdateTime + 1000) {
        this.lastUpdateTime = currTime;
        this.fpsText.setText("FPS : "+this.counter);
        this.counter = 0;
    }
}

```

## Additional Information

Code example should output something that looks like the following:

![image](https://user-images.githubusercontent.com/6758316/46845602-f689a280-cd90-11e8-9791-b547ddbb144b.png)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by maximtsai** [comment]
Just want to say that I'm no longer encountering any performance issues with text on the latest version built from github (added over 2000 text objects without experiencing fps dips on my iPad), so thank you Photonstorm!

**Comment by photonstorm** [comment]
Awesome. It will help with TileSprites too, although I appreciate not many people add thousands of those!

**Comment by iamchristopher** [comment]
Challenge accepted!

**Comment by photonstorm** [comment]
Oh boy.

If you do find they run like turds in tar, please at least wait until tomorrow to inform me. I've already released two versions today :)
