### ISSUE TITLE
[Feature Request] scene.time.addEvent

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#4115]
would you please add an optional parameter for `scene.time.addEvent` (Clock class) method so that I can pass my generated `TimeEvent` object directly? so that I can use a pool to manage my time events and re-use them.
my situation is in a rapid loop.

**Comment by jcyuan** [comment]
and a way to cancel the generated individual time event.
it seems there is only `clearPendingEvents` and `removeAllEvents`...

**Comment by photonstorm** [comment]
*cough* only nearly 2 years late, but hey, this feature just landed in 3.50 :D
