### ISSUE TITLE
Collision end doesn't trigger properly 

### ISSUE THREAD

**Issue by mmolina01** [photonstorm/phaser#4116]
When using Matter physics engine and polygonal shapes the "collision end" event doesn't trigger when an object pass through the polygon and stays within the sprite real (non polygonal) size. 

Here's a c9 example so you can see it better (the console is logging when the collision start and end events trigger)

Editor: https://ide.c9.io/mmolina01/phaser-matter-demo
Application: https://phaser-matter-demo-mmolina01.c9users.io

I've tried this with several versions of phaser including 3.14

OS: Mac OS 10.13.6
Browser: Chrome 69 (69.0.3497.100)

**Comment by photonstorm** [comment]
Sorry, we didn't get a chance to fix this before the code examples were taken offline. I'm going to close the issue as we've overhauled Matter support in the 3.22 release.
