### ISSUE TITLE
Resize rectangle shape game object with initial width 1.

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4126]
[Here](https://codepen.io/rexrainbow/pen/oayrXx?editors=0010) is a test code run in Phaser 3.15.1, chrome and firefox.

There are 3 rectangle shape game objects
- rect1: initial width 1, resize to 60
- rect2: initial width 2, resize to 60
- rect3: initial width 60, resize to 60

Result
- The bounds of these 3 rect object are the same.
- The render result of rect2 and rect3 are the same. But rect1 has an offset.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
