### ISSUE TITLE
Phaser.Geom.Intersects functions

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#4127]
function `Phaser.Geom.Intersects.LineToLine` gets 3 arguments, and the 3rd argument is optional and it will set intersects point (`Phaser.Geom.Point`) in that. I think that it will be fine, if all intersects functions will have that 3rd argument to return `Phaser.Geom.Points[]` array.

**Comment by florianvazelle** [comment]
Hi ! I'll work on it with @gglaive (It's perfect for our school project).

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
