### ISSUE TITLE
Zone object: displayOrigin does not updated after setSize()

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4132]
## Version

* Phaser Version: 3.15.1

* Operating system: window10
* Browser: firefox, chrome

## Description

[Test code](https://codepen.io/rexrainbow/pen/vVPWLj)

There are 2 zone objects, after `setSize()`
- zone2 updates displayOrigin

Touch event works fine in zone2, but zone 3 only activates at right-bottom area, because of displayOrigin is not correct.

From the [comment of updateDisplayOrigin()](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/components/Origin.js#L180): *You don't usually call this directly, but it is exposed for edge-cases where you may.*
It might be better to add `updateDisplayOrigin()` inside `zone.setSize()` function.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
