### ISSUE TITLE
setSize and setDisplaySize not working for matter gameobjects

### ISSUE THREAD

**Issue by DannyT** [photonstorm/phaser#4135]
## Version

* Phaser Version: 3.15.1
* Operating system: Win10

## Description
When calling `matterObject.setSize(w, h)` or `matterObject.setDisplaySize(w, h)` I would expect the body size or rendered size to change respectively. Calling `setSize` seemingly does nothing whereas calling `setDisplaySize` does change the render size but also applies some odd scaling to the body.

## Example Test Code

In this lab: http://labs.phaser.io/edit.html?src=src\physics\matterjs\body%20scale.js

Change `rect.setScale(2);`
To `rect.setDisplaySize(120, 120);`
Or `rect.setSize(120, 120);`

(and click the shape)

## Additional Information

Some investigation by jSnake (in Discord) suggests there needs to be a Size component added to `matter-js/components`.

![image](https://user-images.githubusercontent.com/25999/47676392-6cc13e00-dbb4-11e8-8c90-6db313844076.png)

**Comment by divillysausages** [comment]
Somewhat similar, but it doesn't seem that calling `setDisplaySize()` changes the scale like it states in the docs ("Setting this value will adjust the Game Object's scale property.")

E.g.
````const image = new Phaser.GameObjects.Sprite( scene, 100, 100, "someTexture", "someFrame" ); // image is 100x100
image.setDisplaySize( 50, 50 )

// prints "Size: 100x100, display: 50x50, scale: 1x1"
console.log( `Size: ${image.width}x${image.height}, display: ${image.displayWidth}, ${image.displayHeight}, scale: ${image.scaleX}, ${image.scaleY}` );````

It makes setting a hitarea screwy if you use `displayWidth` and `displayHeight` to generate the `Rectangle` (it's smaller than the object, and offset to the top left), though I'm assuming this is because the scale isn't right.

**Comment by photonstorm** [comment]
Thanks for opening this feature request (all that time ago!) - I'm going to close it now, as this isn't a feature that will be implemented in Phaser 3. You should create your Game Objects to the size required and then give them a Body, or change their size via `setScale` only. If there was a way to override the component docs to make this clearer I would, but sadly there isn't.
