### ISSUE TITLE
Shape.setMask  make mask for all objects in CANVAS

### ISSUE THREAD

**Issue by Kvisaz** [photonstorm/phaser#4138]
## Version

* Phaser Version: 3.15.1

* Operating system: Windows 8

## Description
Phaser.Canvas mode - when we setMask for any Shape, **all objects on scene get same mask**

(in Phaser.WebGL mode mask works correct)

## Example Test Code

` var rect1 = this.add.rectangle(12, 12, 320, 320, 0xfeefee);
  var maskGraphics = this.make.graphics();
    maskGraphics.fillStyle(0xffffff);
    maskGraphics.beginPath();
    maskGraphics.fillRect(23, 23, 32, 32);
    var mask = maskGraphics.createGeometryMask();
for (var i = 0; i < 12; i++) {
            x = 8, y = i * 64;
            var item = this.add.rectangle(x, y, 600, 52, i*0x012111);
            var item2 = this.add.circle(x, y, i*5, 0xffffff);
        }
   rect1.setMask(mask);
`

## Additional Information

What we need (WebGL sample - correct mask for rect12 only)
![2018-10-31_215541-webgl](https://user-images.githubusercontent.com/16399450/47796870-c44bdf00-dd57-11e8-9536-4a4998eb5751.png)

What we get in Canvas - last Phaser.Shape object set mask for all objects (including sprites and images)
![2018-10-31_215524-canvas](https://user-images.githubusercontent.com/16399450/47796878-c9a92980-dd57-11e8-8f85-bbe583fbfd10.png)

**Comment by photonstorm** [comment]
Sorry for the delay in responding to this - thankfully, the bug was quickly fixed in 3.16, released shortly after you made this post. So hopefully it didn't cause a problem for too long.
