### ISSUE TITLE
Can't create RenderTexture bigger than the game size.

### ISSUE THREAD

**Issue by chaoyang805** [photonstorm/phaser#4139]
## Version

* Phaser Version: Phaser v3.15.1

* Operating system: macOS 10.14.1 beta

* Browser: Chrome 70.0.3538.77

## Description

I create a RenderTexture which is bigger than the initial game size and set a fill background to it. But only within the game size the background color was rendered. Is it a bug that RenderTexture can not bigger than the game size?

## Example Test Code
**Below is the sample code or clone from here [https://github.com/chaoyang805/RenderTextureTest.git](https://github.com/chaoyang805/RenderTextureTest.git)**
```javascript
var config = {
  width: 800,
  height: 600,
  parent: 'app',
  type: Phaser.WEBGL,
  backgroundColor: 0xacde00,
  physics: {
    default: 'impact',
    impact: {
      gravity: 0,
      maxVelocity: 100,
      debug: true
    }
  },
  scene: {
    preload: preload,
    create: create,
    update: update
  }
};

var game = new Phaser.Game(config);
var renderTexture
var cursors
function preload() {
  console.log('preload')
  this.load.image('avatar', 'assets/avatar.png');
}

function create() {
  let width = 1600;
  let height = 1200;
  // The world bounds is set bigger than game size so that camera scrolling is possible.
  this.impact.world.setBounds(0, 0, width, height, 10);
  console.log('create')
  // Create a renderTexture bigger than game size
  renderTexture = this.add.renderTexture(0, 0, width, height);
  renderTexture.fill(0x00f0f0);
  // Draw a bunch of objects along X axis.
  for (let i = 0; i < 100; i++) {
    renderTexture.draw('avatar', i * 60, 0);
  }
  cursors = this.input.keyboard.createCursorKeys();
}

function update(time, delta) {
  if (cursors.left.isDown) {
    this.cameras.main.scrollX -= 4;
  }
  if (cursors.right.isDown) {
    this.cameras.main.scrollX += 4;
  }
  if (cursors.up.isDown && this.cameras.main.zoom < 2) {
    this.cameras.main.zoom += 0.02;
  }
  if (cursors.down.isDown && this.cameras.main.zoom > 0.5) {
    this.cameras.main.zoom -= 0.02;
  }
}
```

**Comment by iamchristopher** [comment]
I'm seeing this behaviour as well. It's still unclear to me if this is in fact a bug or a misunderstanding of how a `RenderTexture` should behave. See [this thread](http://www.html5gamedevs.com/topic/40907-can-a-rendertexture-be-larger-than-game-size/) for my ongoing adventure.

**Comment by chaoyang805** [comment]
> I'm seeing this behaviour as well. It's still unclear to me if this is in fact a bug or a misunderstanding of how a `RenderTexture` should behave. See [this thread](http://www.html5gamedevs.com/topic/40907-can-a-rendertexture-be-larger-than-game-size/) for my ongoing adventure.

Yes, I saw this post. Still don't konw how to solve this 😞 .

**Comment by photonstorm** [comment]
It's almost certainly because of the gl scissor settings, which are enabled by default for cameras, and I suspect are scissoring all draws to the render texture beyond the camera range.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
