### ISSUE TITLE
Docs: Phaser.Scene and PluginObjectItem missing plugin-related properties?

### ISSUE THREAD

**Issue by JamesSkemp** [photonstorm/phaser#4142]
## Version
* Phaser Version: 3.15.1
* Operating system: Mac OS

## Description
While trying to work through the [official plugin examples](http://labs.phaser.io/index.html?dir=plugins/&q=) with TypeScript I'm running into what appears to be missing properties.

Specifically, it appears that `Phaser.Scene` has a `plugins`, and `PluginObject` and `PluginObjectItem` should perhaps have a `mapping`.

## Example Test Code

**RandomNamePlugin.ts**:

	export default class RandomNamePlugin extends Phaser.Plugins.ScenePlugin {
		private syllables1;
		private syllables2;
		private current;

		constructor(scene, pluginManager) {
			super(scene, pluginManager);

			this.syllables1 = [ "fro", "tir", "nag", "bli", "mon", "zip" ];
			this.syllables2 = [ "fay", "shi", "zag", "blarg", "rash", "izen" ];

			this.current = this.syllables1;
		}

		public changeSet() {
			this.current = this.syllables2;
		}

		public getNames(qty = 10) {
			const names = [];

			for (let i = 0; i < qty; i++) {
				let name = "";

				for (let j = 0; j < Phaser.Math.Between(2, 4); j++) {
					name = name.concat(Phaser.Utils.Array.GetRandom(this.current));
				}

				names.push(Phaser.Utils.String.UppercaseFirst(name));
			}

			return names;
		}
	}

I'm now trying to add this to my game based upon [scene plugin test1](http://labs.phaser.io/edit.html?src=src\plugins\scene%20plugin%20test%201.js):

	const gameConfig: GameConfig = {
		width: 800,
		height: 600,
		type: Phaser.AUTO,
		parent: "content",
		title: "Starter Project for Phaser 3 with Visual Studio Code, TypeScript, and NodeJS",
		plugins: {
			scene: [
				{ key: "randomNamePlugin", plugin: RandomNamePlugin, mapping: "randomPlugin" }
			]
		}
	};

However, `mapping` is not valid for either `PluginObject` or `PluginObjectItem`, per the current defs. Changing a line to `{ key: "randomNamePlugin", plugin: RandomNamePlugin, mapping: "randomPlugin" } as any` allows it to continue, with this code:

**MainMenu.ts**

	export default class MainMenu extends Phaser.Scene {
		/**
		 * Unique name of the scene.
		 */
		public static Name: string = "MainMenu";

		public create(): void {
			try {
				console.log(this);
				const sceneOverride = this as any;

				const names = sceneOverride.randomPlugin.getNames(10);
				this.add.text(10, 10, names, { font: "16px Courier", fill: "#00ff00" });

				sceneOverride.randomPlugin.changeSet();

				const moreNames = sceneOverride.randomPlugin.getNames(10);
				this.add.text(200, 10, moreNames, { font: "16px Courier", fill: "#ffff00" });
			} catch (e) {
				console.log(e);
			}
		}
	}

However, based upon [the install global plugin at runtime example](http://labs.phaser.io/edit.html?src=src\plugins\install%20global%20plugin%20at%20runtime.js) I should also be able to do something like `let plugin1 = this.plugins.install("myPluginRef1", RandomNamePlugin, true);` in the `create` of my scene (keeping in mind that I would need to change my plugin's constructor).

However, `this` in the code above (which is a `MainMenu` class that extends `Phaser.Scene`) doesn't have a `plugins` property (although `console.log(this);` shows that it does).

Am I missing something, or are these missing?

## Additional Information

Thanks!

**Comment by photonstorm** [comment]
Sorry it took so long to respond to this (insert guilty face here!) but this has been done, probably a while ago now, I just forgot to close the issue :(
