### ISSUE TITLE
Width/height doesn't seem to take scale into account

### ISSUE THREAD

**Issue by divillysausages** [photonstorm/phaser#4143]
## Version

* Phaser Version: 3.15.1 / 3.16.0
* Operating system: Windows 10

## Description

Getting the width/height of an image doesn't seem to take the scale into account. Is this by design?

## Example Test Code

Tested on https://labs.phaser.io/edit.html?src=src\input\game%20object\sprite%20example.js, but it works locally as well

```
var alien = this.add.sprite(400, 300, 'aliens', 0)
console.log( alien.width + ", " + alien.height ); // 192, 160

alien.setScale( 0.5, 0.5 );
console.log( alien.width + ", " + alien.height ); // 192, 160
```

**Comment by samme** [comment]
Use [displayHeight](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Image.html#displayHeight__anchor) etc. instead (cf. [height](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Image.html#height__anchor)).

**Comment by divillysausages** [comment]
Ah, ok, thanks!
