### ISSUE TITLE
Documentation for Phaser.Physics.Arcade.Sprite.setSize is incorrect

### ISSUE THREAD

**Issue by shalmak** [photonstorm/phaser#4145]
## Version

* Phaser Version: 3 (Online API doc)

* Operating system: N/A

* Browser: N/A

## Description

The documentation for Phaser.Physics.Arcade.Sprite.setSize seems to describe the corresponding method in Phaser.GameObjects.Components.Size, but Sprite overrides this method (as stated) and has different args and behavior.

## Example Test Code

N/A

## Additional Information

The correct documentation is present in the code itself, above the correct setSize method.

**Comment by photonstorm** [comment]
Thank you for submitting this docs issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
