### ISSUE TITLE
Enable "pointerout" for touch? Why is it turned off? There is probably a good reason..

### ISSUE THREAD

**Issue by brunotag** [photonstorm/phaser#4146]
Hi team,

I'm pretty new to Phaser3 so I was just for fun trying to adapt the tutorial (the simple platformer game with stars and the bombs) to mobile.

So I wrote a simple three buttons gamepad and I almost immediately noticed a bug: if you click a button on mobile, and you "slide" away your finger from it while it's still pressed, it stays pressed 'forever'. Or at least until you tap it again. That's because the last state it went into was "down", and if you move out of it before you release it, "up" doesn't fire.

With a little bit of investigation I found that was happening because the "pointerout" event doesn't fire on mobile (more precisely doesn't fire if the pointer is 'touch' but I didn't know it at that point).

So I debugged the game, while running it my Android device, through the `/inspect` feature in chrome and instead of finding a bug, as I would have initially thought, I found out that "pointerout" can't fire on mobile, and that's on purpose, because of  [this](https://github.com/photonstorm/phaser/blob/4b1c76229628bd587ed566d64e73e98ca3ad8e9a/src/input/InputPlugin.js#L540) `if (!pointer.wasTouch)` - I basically removed that `if` (made it always `true`), and my specific case now works as expected.

After this long story, my question is: why is `processOverOutEvents` not called if the pointer is 'touch'? In other words, do we know what I am risking to break on my app by removing that '`if`', and allowing the `processOverOutEvents` on 'touch' type pointers?

Cheers

Bruno

**Comment by okcompewter** [comment]
I had a similar problem on both web and mobile. Touching/clicking a navigation button, sliding off it, then releasing, was leaving it as 'pressed'.

In my case, I believe the event that still needs support is 'pointerupoustide', commented here:
'https://github.com/photonstorm/phaser/blob/4b1c76229628bd587ed566d64e73e98ca3ad8e9a/src/input/InputPlugin.js#L1342

Basically a way to know the pointer came up outside of the element that it was down on, so to still capture that as an up on the element that was down.

**Comment by brunotag** [comment]
@okcompewter have you tried removing [this if](https://github.com/photonstorm/phaser/blob/4b1c76229628bd587ed566d64e73e98ca3ad8e9a/src/input/InputPlugin.js#L541)? That should fix it.

The question is: what other problems could that "fix" introduce? I'd hope the `if` is there for a reason.

**Comment by brunotag** [comment]
Thanks Francesco.
Unfortunately it appears that this line mentioned in that doc you posted
`gameObject.on('pointerout', function(pointer, event){ /* ... */ });`
doesn't work on `touch` pointers, because `pointerout` doesn't fire on `touch` pointers.
And according to this piece of code I've mentioned above
https://github.com/photonstorm/phaser/blob/4b1c76229628bd587ed566d64e73e98ca3ad8e9a/src/input/InputPlugin.js#L541
it doesn't fire by design.
My question is: why?

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
