### ISSUE TITLE
Plugins config compatible with others bundlers

### ISSUE THREAD

**Issue by RiCoTeRoX** [photonstorm/phaser#4149]
[parceljs](https://parceljs.org) is another bundler with better and with less configuration.
its not compatible with the actual configuration "if typeof" 
`if (typeof PLUGIN_FBINSTANT)`

it will be compatible if instead of reading that typeof, read a ENV variable and we can be use .env config files

`process.env.PLUGIN_FBINSTANT === "true"`

so, we can have a .env.production && .env.developtment with different [configs](https://github.com/motdotla/dotenv)

I can submit a PR if you want @photonstorm

**Comment by photonstorm** [comment]
Closing this issue due to age. The current solution is less than ideal but works across webpack and rollup, and there are now so many plugins available that adhere to it, it's too late to change it, sorry.
