### ISSUE TITLE
website issue: link to Phaser 3 Getting started

### ISSUE THREAD

**Issue by DannyT** [photonstorm/phaser#4153]
The Phaser 3 home (https://phaser.io/phaser3/home) sidebar links to a getting started page which is outdated (the webpack instructions prompt to install an NPM script that doesn't work) https://phaser.io/phaser3/gettingstarted

Feels like instead it should link to here:
https://phaser.io/tutorials/getting-started-phaser3

**Comment by RiCoTeRoX** [comment]
PR ?

**Comment by DannyT** [comment]
> PR ?

I searched, but doesn't look like the website source is open source ?

**Comment by photonstorm** [comment]
Agreed, have updated this. Thanks!
