### ISSUE TITLE
Wrong anchor position on Sprite/GameObject

### ISSUE THREAD

**Issue by Zax37** [photonstorm/phaser#4155]
Update from Phaser 3.13 to 3.14 or 3.15 brought new rendering bug regarding anchors.

Steps to reproduce(first two might be not necessary)

- create new texture atlas with anchor positions set
- create new animation from this atlas
- create new sprite, play the animation on it

The sprite moves different than intended (in my case it shouldn't move at all!)

**Comment by Zax37** [comment]
I've recorded this and other bug I'm struggling with (https://github.com/photonstorm/phaser/issues/3813):

In 3.13 only flipped anchor is broken:
https://cdn.discordapp.com/attachments/416623653741133837/511464613028560897/3.13.0.webm

But in 3.14+ (here be 3.15.1) EVERYTHING with anchors is broken:
https://cdn.discordapp.com/attachments/416623653741133837/511464626303795220/3.15.1.webm

**Comment by photonstorm** [comment]
Please provide an animation we can test this with.

**Comment by Zax37** [comment]
1. Sprite atlas: http://captainclaw.net/dl/CLAW_SPRITESHEET.zip

2. Animations definition:

```
  this.game.anims.create({
    key: 'stand',
    frames: this.game.anims.generateFrameNames('CLAW',
      {prefix: 'CLAW_', start: 11, end: 18}),
    frameRate: 9,
    repeat: -1
  });

  this.game.anims.create({
    key: 'walk',
    frames: this.game.anims.generateFrameNames('CLAW',
      {prefix: 'CLAW_', start: 1, end: 10}),
    frameRate: 13,
    repeat: -1
  });
```

3. Body size & offset:
```
  this.setSize(32, 112);
  this.setOffset(32, 1);
```

Final effect should look same as on the uploaded videos.

More code, if needed: https://github.com/Zax37/ClawJS

**Comment by Zax37** [comment]
Does it need any more examples?

**Comment by hexus** [comment]
An explicit, minimal reproduction of this issue in a sandbox like JSBin or Codepen would be really helpful.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
