### ISSUE TITLE
Sprite renders flipped when pipeline is set and camera is render-to-texture

### ISSUE THREAD

**Issue by TJ09** [photonstorm/phaser#4158]
## Version
* Phaser Version: v3.15.1-v3.21.0, master (tested in http://labs.phaser.io/edit.html?v=dev)
* Operating system: Linux, OSX, Windows
* Browser: Chrome, Firefox 

## Description

When using `setPipeline` on an image while also using `setRenderToTexture` on the camera, the sprite is flipped across the canvas (note that it's not just the image flipped; the y-coordinate is also flipped)

## Example Test Code

```
var CustomPipeline = new Phaser.Class({
    Extends: Phaser.Renderer.WebGL.Pipelines.TextureTintPipeline,
    initialize: function CustomPipeline(game) {
        Phaser.Renderer.WebGL.Pipelines.TextureTintPipeline.call(this, {
            game: game,
            renderer: game.renderer,
            fragShader: `
              precision mediump float;

              uniform sampler2D uMainSampler;
              varying vec2 outTexCoord;

              void main( void ) {
                 vec4 pixel = texture2D(uMainSampler, outTexCoord);
                 gl_FragColor = pixel;
              }
            `
        });
    }
});

var game = new Phaser.Game({
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#000000',
    scene: {
        preload: preload,
        create: create
    }
});

function preload() {
    this.load.image('hotdog', 'assets/sprites/hotdog.png');
    customPipeline = game.renderer.addPipeline('CustomPipeline', new CustomPipeline(game));
}

function create() {
    this.add.image(200, 200, 'hotdog');
    var hotdogWithShader = this.add.image(500, 200, 'hotdog');

    // With this turned off, both hotdogs render as expected.
    // With this turned on, the hotdog with a custom pipeline is flipped.
    this.cameras.main.setRenderToTexture(customPipeline);

    hotdogWithShader.setPipeline('CustomPipeline');
}
```

**Comment by felipeprov** [comment]
I confirm this problem, it would be nice to have a workaround...

**Comment by hardylr** [comment]
I can also confirm this problem. Started a thread on Phaser discord group that shows my workaround.
[RenderTexture update with custom pipeline ](https://phaser.discourse.group/t/rendertexture-update-with-custom-pipeline/1123)

**Comment by felipeprov** [comment]
Hi @hardylr thank you!
I will be using your solution while it's not officially solved

Thank you!

**Comment by photonstorm** [comment]
Closing this issue off (finally!) as this has all changed in 3.50 and you've a _lot_ more control over the render process. Cameras no longer render to textures, but can instead use their own post-pipelines.
