### ISSUE TITLE
Camera.Fade not rendering when a GameObject is not present

### ISSUE THREAD

**Issue by wildsurvival** [photonstorm/phaser#4160]
## Version
* Phaser Version: v3.15.1-FB
* Operating system: Windows 10 x64
* Browser: Chrome ( also tested in mobile safari)

## Description

*This is assuming that this functionality is not intended*

Using any variation of the camera.fade function while there is no gameobject in the scene that the camera renders causes the camera.fade animation not to be rendered. The function is still called and a callback will be received but there is no visible animation. This includes if all objects on the scene are listed under camera.ignore

Having an object that is still rendered off screen fixes this.

## Example Test Code
https://codepen.io/aschoate/pen/yQawjQ

## Additional Information

You can see the problem from the codepen and also see the intended result by adding an object to the scene that the camera will render (e.g. removing the camera.ignore call on *r* in the codepen)

**Comment by photonstorm** [comment]
Sorry for the delay in responding to this, but I can confirm this is working correctly as of Phaser 3.50 (and I dare say lots of versions earlier, too!) - test case below:

```js
var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        create: create
    }
};

var game = new Phaser.Game(config);

function create ()
{
    this.cameras.main.on('camerafadeoutstart', function () {

        console.log('start');

    });

    this.cameras.main.on('camerafadeoutcomplete', function () {

        console.log('complete');

    });

    //  Every time you click, fade the camera

    this.input.on('pointerdown', function () {

        //  Get a random color
        var red = Phaser.Math.Between(50, 255);
        var green = Phaser.Math.Between(50, 255);
        var blue = Phaser.Math.Between(50, 255);

        this.cameras.main.fade(2000, red, green, blue);

    }, this);
}
```
