### ISSUE TITLE
Graphics object not displaying correctly on iOS 9

### ISSUE THREAD

**Issue by Legomite** [photonstorm/phaser#4161]
## Version

* Phaser Version: 3.12.0 and above

* Operating system: iOS 9

* Browser: Mobile Safari

## Description

Graphics objects do not appear correctly. They show up partially, flickering, or not at all. This behavior does not happen in 3.11.0. 

## Example Test Code

http://labs.phaser.io/view.html?src=src/game%20objects/graphics/Multiple%20Graphic%20Objects.js&v=3.12.0

## Additional Information

Phaser 3.11.0
![img_7233](https://user-images.githubusercontent.com/5732872/48373781-ae9fb900-e677-11e8-8737-48e44904b864.PNG)
Phaser 3.12.0
![img_7234](https://user-images.githubusercontent.com/5732872/48373782-af384f80-e677-11e8-9d45-e0e3a89bbd2e.PNG)

**Comment by photonstorm** [comment]
Sorry for leaving this open for so long, but this issue was resolved a long time ago thanks to an iOS update.
