### ISSUE TITLE
Lights not displaying correctly on mobile (Android)

### ISSUE THREAD

**Issue by FrancescoNegri** [photonstorm/phaser#4162]
## Version

* Phaser Version: 3.15.1 (I encountered this issue also in old versions)
* Operating system: Android 8.1.0
* Browser: Chrome (mobile), Firefox (mobile), Edge (mobile), Mobile Cordova app (WebView)

## Description

I'm working on a project involving some lights and I noticed that on desktop browsers it works awesome, while on Android mobile devices (I did not try on the Apple's ones) the browser/webview only show **one** light, the others are not displayed, moreover it seems to me that they're not affecting the pipeline 'Light2D', since they're not graphically displayed.
I also tried the mobile browser called Puffin, which renders the web page on its servers and then sends back the "finalized" data: there the lights were all working, but probably because it's all rendered by a desktop server.

## Example Test Code

The issue is affecting all the examples using multiple light, like this one, which I used for tests:
http://labs.phaser.io/view.html?src=src/game%20objects/lights/graveyard.js

### **Firefox Mobile**
![firefox-graveyard](https://user-images.githubusercontent.com/11014462/48387923-8a54e280-e732-11e8-8524-3c4b25ef0448.gif)

### **Puffin Mobile**
![puffin-graveyard](https://user-images.githubusercontent.com/11014462/48388164-5af2a580-e733-11e8-9571-2a1958846103.gif)

### **Firefox Desktop**
![firefox-desktop-graveyard](https://user-images.githubusercontent.com/11014462/48388906-30eeb280-e736-11e8-9c8f-12db5a63ed29.gif)

**Comment by HorusGoul** [comment]
I've been trying to find a solution for this problem without results :cry:
Does anyone have any idea about what is wrong with the current implementation of the pipeline?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that (tested on various iOS devices and one modern Android device).
