### ISSUE TITLE
Missing informations on Tutorial 'Making your first Phaser game'

### ISSUE THREAD

**Issue by diegomontania** [photonstorm/phaser#4163]
## Current website [13/11/2018]

* Phaser 2.5.0
* Windows 10 PRO
* Missing informations about 'the first game phaser game'.
(https://phaser.io/tutorials/making-your-first-phaser-2-game/part5)

This is not a bug, but a little mistake on tutorial.

It is not mentioned at any time in the tutorial of the site. In the 'Part5', the method 'update' (update: update) should be passed as parameter in the line of 'Instance' (new Phaser.game ...). If the parameter is not passed, the player has no collision with the ground.

This can lead to the error for a beginner programmer, since, only in the example made available for download the parameter was passed correctly.

And looking very carefully, we can see the difference of the code being done step by step following the site, missing this information.

## Example Test Code

WRONG CODE :
var game = new Phaser.Game(800, 600, Phaser.AUTO, '', { preload: preload, create: create });

RIGHT CODE :
var game = new Phaser.Game(800, 600, Phaser.AUTO, '', { preload: preload, create: create, update: update });

## Additional Information

I sorry if this is not a right place to post this mistake.

**Comment by photonstorm** [comment]
In [Part 1](https://phaser.io/tutorials/making-your-first-phaser-2-game/index) of the same tutorial it shows you how to add an empty `update` function, and in part 5 you populate it with some code. So if you followed through, it should be fine! Thanks for the issue though.
