### ISSUE TITLE
Phaser.Tweens.TimeLine.setTimeScale() not having any effect

### ISSUE THREAD

**Issue by garethwhittaker** [photonstorm/phaser#4164]
## Version

* Phaser Version: 3.15.1

* Operating system: macOS High Sierra

* Browser: Multiple

## Description
Applying `.setTimeScale(value)` appears to have no effect on a tween timeline.

`Phaser.Tweens.TweenManager.setGlobalTimeScale(value)` does work for me but affects all tweens.

## Example Test Code

I've used the [Simple TimeLine 1](https://labs.phaser.io/edit.html?src=src\tweens\timelines\simple%20timeline%201.js) example from Phaser Labs and added the following two lines to toggle between:

timeline.setTimeScale(0.1);
// this.tweens.setGlobalTimeScale(0.1);

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
