### ISSUE TITLE
use CanvasPool.create2D(this).getContext("2d") to detect canvas supporting.

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#4166]
the current way to detect canvas support uses 

    Features.canvas = !!window['CanvasRenderingContext2D'] || OS.cocoonJS;

in the `Features` module.

but in our environment there is no `CanvasRenderingContext2D` context is exposed directly in the window object, you can only access this member though a `canvas` instance (special environment like `cocoonJS`).

so I think the `Features` module could be changed as

    // move the creation from testWebGL function outside
    var canvas2D = CanvasPool.create2D(this);
    var ctx2D = canvas2D.getContext('2d');

    Features.canvas = !!ctx2D || OS.cocoonJS;

is this ok?

**Comment by jcyuan** [comment]
or is there a way to override Features module?

**Comment by jcyuan** [comment]
till now the error I found in our environment using Phaser 3.1.6 Beta2:

1. both `Features.canvas` & `Features.webGL` are false, I modified them as true manually because there is no way to overwrite it.
2. `gl.blendEquation` (in the code I don't know why it passes 2 arguments, from MDN it points out that `gl.blendEquation` only has 1 argument, actually this runs ok on PC etc environment (Function has more arguments passed it won't throw error), but it throws error on our environment. so I manually deleted 1 argument.
[refer to: gl.blendEquation](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendEquation)

except these 2 problems, everything works great!

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by jcyuan** [comment]
cool! thank you very much!
