### ISSUE TITLE
Light2D not properly working for DynamicTilemapLayer from a Tileset

### ISSUE THREAD

**Issue by blackjack26** [photonstorm/phaser#4167]
## Version
* Phaser Version: 3.15.1
* Operating system: Windows 10 Pro 1709 Build 16299.726
* Browser: Chrome v70.0.3538.102 (64-bit)

## Description

When using a normal map with a tileset image, and create a `DynamicTilemapLayer` with that tileset, I should be able to set the layers pipeline as `Light2D`. What occurs is that the console logs the error:

> Uncaught TypeError: Cannot read property 'dataSource' of undefined
    at ForwardDiffuseLightPipeline.batchTexture (VM75183 ForwardDiffuseLightPipeline.js:237)
    at DynamicTilemapLayerWebGLRenderer [as renderWebGL] (VM75270 DynamicTilemapLayerWebGLRenderer.js:89)
    at WebGLRenderer.render (VM75179 WebGLRenderer.js:1752)
    at CameraManager.render (VM74411 CameraManager.js:612)
    at Systems.render (VM74510 Systems.js:375)
    at SceneManager.render (VM74507 SceneManager.js:600)
    at Game.step (VM74482 Game.js:554)
    at TimeStep.step (VM74542 TimeStep.js:560)
    at step (VM74479 RequestAnimationFrame.js:104)

This prevents the scene from loading and rendering anything.

## Example Test Code

This is a subset of the code I am using to generate the tilemap and add the lights.

```es6
preload() {
  this.load.image({
    key: 'my_tiles',
    url: 'assets/my-tileset.png',
    normalMap: 'assets/my-tileset_n.png'
  });
}

create() {
  this.lights.enable().setAmbientColor( 0x555555 );
  this.lights.addLight( 100, 100, 200 );

  const map = this.make.tilemap( { /* ... */ } );
  const tileset = map.addTilesetImage( 'my_tiles', null, 32, 32, 1, 2 );
  this.layer = map.createBlankDynamicLayer( 'Ground', tileset );
  this.layer.setPipeline( 'Light2D' );
}
```

## Additional Information

The problem is in `ForwardDiffuseLightPipeline.js` on [line 237](https://github.com/photonstorm/phaser/blob/master/src/renderer/webgl/pipelines/ForwardDiffuseLightPipeline.js).

Currently the code is referencing `gameObject.tileset.image`, but in Phaser v3.14 the `tileset` property is now an array and not a single reference (according to the [documentation](https://photonstorm.github.io/phaser3-docs/Phaser.Tilemaps.DynamicTilemapLayer.html#tileset__anchor)).

The current code looks like:
```es6
normalTexture = gameObject.tileset.image.dataSource[0];
```

but should probably look something like:
```es6
normalTexture = gameObject.tileset[0].image.dataSource[0];
```

While this is a simple fix if the layer only has one tileset, but if there are multiple tilesets, this logic will become more complex.

References #3544

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
