### ISSUE TITLE
StaticBody#setCircle offset not working and also not rendering as circle in debug

### ISSUE THREAD

**Issue by maikthomas** [photonstorm/phaser#4168]
## Version

* Phaser Version:3.11.0

* Operating system:MacOS 10.13.6

* Browser: Not specific, have tested on Chrome and Firefox

## Description

I have identified two problems:

1. A StaticBody whose body has been set to a circle with `setCircle` does not render as a circle in debug. However the collision body is in fact a circle.
2. The offset parameters appear not to actually offset the body. In this case I observe that the render and collision body are both not offsetting.

## Example Test Code

I made a codepen with a few bodies.
There are two staticbodies on the left. 
The top one is square, the bottom is circle. They both render as square in debug.
I added moving bodies to collide with them. You can see the bottom moving body collides with the circle and bounces off at an angle, confirming the circular collision.

Also please try changing the offset for the static bodies, it has no effect.

https://codepen.io/maikthomas/pen/OaMRGb

## Additional Information
Related forum post I made, has screenshots and code but not complete sample for running: http://www.html5gamedevs.com/topic/41088-setcircle-doesnt-work-on-a-staticgroup-game-object/
It at least shows how for non static bodies the debug render works as expected.

P.s. many thanks for all your effort, I'm new to Phaser and it is great! 👏

**Comment by maikthomas** [comment]
Think these are linked https://github.com/photonstorm/phaser/issues/4213
As far as I can tell no static body offset methods are working correctly.

**Comment by photonstorm** [comment]
Hiya, thank you for opening this (all those months ago!) - static bodies now debug draw properly thanks to your PR and `setOffset` definitely now works for Static bodies, too, as tested in 3.20.

**Comment by Rayanfer32** [comment]
I tried using `setOffset` on this [repl](https://repl.it/@s3/korisukka) ...still doesnt work!!!

**Comment by samme** [comment]
@Rayanfer32 

![Screen Shot 2020-04-03 at 11 29 35 AM](https://user-images.githubusercontent.com/435681/78393390-854e3880-759e-11ea-851e-3051e2b0fd9b.png)
