### ISSUE TITLE
Sounds cannot be muted

### ISSUE THREAD

**Issue by neon-dev** [photonstorm/phaser#4169]
## Version
* Phaser Version: 3.15.1
* Operating system: Windows 10
* Browser: Firefox 63.0.1

## Description

Muting a sound doesn't work. Only global muting works, but muting specific sounds is currently not possible.

## Example Test Code

Try muting the left and/or right channel:
https://labs.phaser.io/view.html?src=src\audio\HTML5%20Audio\Volume%20Mute%20Rate%20Detune.js

This one is working, due to an older version (3.3.0), all newer versions don't work:
https://labs.phaser.io/view.html?src=src\audio\HTML5%20Audio\Volume%20Mute%20Rate%20Detune.js&v=3.3.0

## Additional Information

Maybe related to #3814

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
