### ISSUE TITLE
Calling .get() on an ArcadePhysicsGroup doesn't apply any physics set in class constructor

### ISSUE THREAD

**Issue by DannyT** [photonstorm/phaser#4171]
## Version

* Phaser Version: 
3.15.1

## Description

Calling `.get()` on an ArcadePhysicsGroup will create the gameobject if none are available but will not apply any physics-related calls made in the class constructor. Calling them after the get will work however.

## Example Test Code

Paste the below code into labs, modified from [this lab](http://labs.phaser.io/edit.html?src=src\physics\arcade\extending%20arcade%20sprite.js)

```
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    pixelArt: true,
    parent: 'phaser-example',
    physics: {
        default: 'arcade',
        arcade: {
            debug: false,
            gravity: { y: 0 }
        }
    },
    scene: {
        preload: preload,
        create: create
    }
};

class SpaceShip extends Phaser.Physics.Arcade.Sprite {

    constructor (scene, x, y)
    {
        super(scene, x, y, 'ship', 0);

        //  You can either do this:
        scene.add.existing(this);
        scene.physics.add.existing(this);

        //  Or this, the end result is the same
        // scene.sys.displayList.add(this);
        // scene.sys.updateList.add(this);
        // scene.sys.arcadePhysics.world.enableBody(this, 0);

        //  Set some default physics properties
        this.setScale(2);
        this.setBounce(1, 1);
        this.setCollideWorldBounds(true);

        this.body.onWorldBounds = true;

        this.setVelocity(0, -200);
    }
}

var game = new Phaser.Game(config);

function preload ()
{
    this.load.spritesheet('ship', 'assets/games/lazer/ship.png', { frameWidth: 16, frameHeight: 24 });
}

function create ()
{
    var group = this.physics.add.group({
        classType: SpaceShip
    });

    // will have physics
    var withPhysics = new SpaceShip(this, 100, 200);
    // will not have physics
    var noPhysics = group.get(500, 200);
    // uncommenting below will work so the object is enabled for physics...
    // noPhysics.setVelocity(0, -200);
}

```

**Comment by samme** [comment]
I think this normal. What's happening is the physics group is applying its defaults after the spaceship constructor is called. (And the default velocity values are zero.)

You can add

    group.createCallback = new Function();

to override that. Just keep in mind that any default physics values you set in the physics group config would be ignored too.

**Comment by DannyT** [comment]
@samme ah of course, that makes sense. I wonder if it would be better for those values to only be set if they're explicitly defined, as this was pretty obtuse behaviour.

Knowing this addresses my problem but I'll leave it for @photonstorm to decide if he'd rather this be closed or not. Thanks for answering 👍

**Comment by photonstorm** [comment]
You can define the properties that are set on anything the Group adds or creates in its config object:

```
var group = this.physics.add.group({
    classType: SpaceShip,
    bounceX: 1,
    bounceY: 1,
    velocityY: -200,
    collideWorldBounds: true
});
```

Moving the responsibility for default values from the class to the Group. While I could only set the properties if defined in the config it would then be different from every other way defaults are set in the API, so I'd rather keep it consistent.

**Comment by samme** [comment]
You can also do

```js
group.defaults = {};
```

**Comment by samme** [comment]
As an example: https://github.com/photonstorm/phaser/compare/master...samme:x/physics-group-no-defaults
