### ISSUE TITLE
Touch input isn't working on touch devices

### ISSUE THREAD

**Issue by JasonHK** [photonstorm/phaser#4172]
## Version

* Phaser Version: 3.14.0~3.15.1

* Operating system:  Android, iOS (possibly for all devices with touch support)

* Browser: N/A

## Description

When I was working on my mobile game, my testers found out that its touch control didn't work. After my investigation, I discovered that the pointer/touch input just dosen't work on the first scene using mobile devices. All of the scenes after work perfectly fine. Also, if I load some web fonts inside the `create()` function of the scene, there will be a short period of time that the touch input will work.

## Example Test Code

[Test code on CodePen](https://codepen.io/JasonHK/project/full/XoLbow)

**Comment by JasonHK** [comment]
Thanks for your help!

**Comment by photonstorm** [comment]
No worries - perhaps you could suggest somewhere I can add this in the docs to make it more obvious?

**Comment by rishcd** [comment]
Hello photonstorm
I am using phaser3. I am developing a shooter game in mobile. I have set buttons for movement and a button for shooting. while the movement button is down and if i press shoot button its not working. but if i release movement button i can shoot. i played with activePointer and pointer1 and 2 with 2 active pointer in config. but its not working. please help.

Thank you for the wonderful framework, hope i can earn some day..  :-)

**Comment by rishcd** [comment]
Hey Photonstorm

Got the solution. Just giving active pointers :2 in config doesnt do the trick(and in some article it says 2 is by default). 
we need to add

 this.input.addPointer(2) //or as 3 as needed

Lucky charm

Thank you
