### ISSUE TITLE
Incomplete collisions in Arcade when pushing objects

### ISSUE THREAD

**Issue by inmylo** [photonstorm/phaser#4175]
* Phaser Version: v3.16.0 Beta 2
* Physics: Arcade
* Browser: Chromium

There is a collision bug when 1 object pushes another - at some moment objects start to go through each other, like there is no collision at all.

In the example code below (for **labs.phaser.io**) I have 2 ground platforms and all stars falling on it, and a player. Plus collisions between everything, even between stars themselves. Player initially is in the middle of the screen and stars.

If I move to the right - stars go through the right platform like there is no collision - it's a 1'st issue.
If I move to the left - I'm able to join only 2 stars - all other acts like physicsless and player/stars just go through them. So you get max 2 stars in a row - it's a 2'nd issue.

What can I do to make collisions always work as expected? Can you please fix that?

## Example Test Code

```javascript
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    physics: {
        default: 'arcade',
        arcade: {
            gravity: { y: 300 },
            debug: false
        }
    },
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var player;
var stars;
var platforms;
var cursors;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('sky', 'src/games/firstgame/assets/sky.png');
    this.load.image('ground', 'src/games/firstgame/assets/platform.png');
    this.load.image('star', 'src/games/firstgame/assets/star.png');
    this.load.spritesheet('dude', 'src/games/firstgame/assets/dude.png', { frameWidth: 32, frameHeight: 48 });
}

function create ()
{
    this.add.image(400, 300, 'sky');

    platforms = this.physics.add.staticGroup();

    platforms.create(400, 568, 'ground').setScale(2).refreshBody();
    platforms.create(900, 520, 'ground');

    player = this.physics.add.sprite(300, 450, 'dude');
    player.setCollideWorldBounds(true);

    this.anims.create({
        key: 'left',
        frames: this.anims.generateFrameNumbers('dude', { start: 0, end: 3 }),
        frameRate: 10,
        repeat: -1
    });

    this.anims.create({
        key: 'turn',
        frames: [ { key: 'dude', frame: 4 } ],
        frameRate: 20
    });

    this.anims.create({
        key: 'right',
        frames: this.anims.generateFrameNumbers('dude', { start: 5, end: 8 }),
        frameRate: 10,
        repeat: -1
    });

    cursors = this.input.keyboard.createCursorKeys();

    stars = this.physics.add.group({
        key: 'star',
        repeat: 11,
        setXY: { x: 12, y: 0, stepX: 70 }
    });

    this.physics.add.collider(player, platforms);
    this.physics.add.collider(stars, platforms);

    this.physics.add.collider(player, stars, collideElem, null, this);
    this.physics.add.collider(stars, stars, collideElem, null, this);

}

function collideElem(obj1, obj2) {
    obj2.body.setVelocityX(0);
    obj2.body.setVelocityX(0);
}

function update ()
{
    if (cursors.left.isDown)
    {
        player.setVelocityX(-160);
        player.anims.play('left', true);
    }
    else if (cursors.right.isDown)
    {
        player.setVelocityX(160);
        player.anims.play('right', true);
    }
    else
    {
        player.setVelocityX(0);
        player.anims.play('turn');
    }

    if (cursors.up.isDown && player.body.touching.down)
    {
        player.setVelocityY(-330);
    }
}
```

**Comment by imilo** [comment]
If that's technically and theoretically not possible in Arcade - please add a physics switch to disable energy exchange, so one object can't push the other objects (just stops instead).

**Comment by photonstorm** [comment]
The `immovable` switch is for this.

**Comment by photonstorm** [comment]
I think it still wouldn't work as you need and you should switch to using Matter.

**Comment by photonstorm** [comment]
Also: https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Body.html#customSeparateX__anchor

**Comment by imilo** [comment]
I'm Ok with replacing some Phaser's functions in my local environment, fortunately JavaScript easily allows it. I see that `SeparateX` does a part of job, but if I try to remove/modify lines which change velocity/position - I loose collisions or both objects are still moving. Probably something more needs to be changed. Could you guide me what do I need to edit in Phaser code to disable pushing? Just to stop an object at collision seems to be not a difficult task

**Comment by imilo** [comment]
One more note, that I'm sure is not worth of additional ticket. In `SeparateX` you have:
```javascript
//  Can't separate two immovable bodies, or a body with its own custom separation logic
if (overlapOnly || overlap === 0 || ...
{
    //  return true if there was some overlap, otherwise false
    return (overlap !== 0) || (body1.embedded && body2.embedded);
}
```
.. is there a need to compare `overlap !== 0` if it will always be zero?!

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

Please see the new `Body.pushable` property and corresponding documentation.
