### ISSUE TITLE
tween chain in timeline has incorrect progress value.

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#4176]
--Env:
v3.16.0 beta 2
Chrome 70.0
Win10

--Example code: 

    const tweenObj: any = { x: sx, y: sy };
       scene.tweens.timeline({
            targets: tweenObj,
            tweens: [{
                duration: 360,
                y: 1000,
                onUpdate: (tween: Phaser.Tweens.Tween, target: any): void => {
                    this._hero.setPosition(sx, target.y);
                    console.log(tween.progress);     // here it works fine as it's the first tween
                }
            },
            {
                duration: 180,
                x: 500,
                onUpdate: (tween: Phaser.Tweens.Tween, target: any): void => {
                    this._hero.setPosition(target.x, ey);
                    console.log(tween.progress);   // incorrect value, always 1
                }
            }],
            onComplete: () => {
                      console.log("done");
            }
        });

I have checked with the source code, the `onUpdate` is triggered in `updateTweenData` method, but this method only updates the `progress` value for the `tweenData`, it does not update the `progress` value for the tween itself.

at https://github.com/photonstorm/phaser/blob/master/src/tweens/tween/Tween.js#L1230-L1256

is this a lib bug or a case of wrong usage? thank you.

**Comment by jcyuan** [comment]
if I just use `console.log(tween.tweenData[0].progress);` that will work fine.

**Comment by RaheelYawar** [comment]
I was struggling with the same problem and I wasn't able to find `tween.data[0].progress` property but `tween.timeline[0].progress` does the same thing.

I hope this helps anyone with a similar issue.
