### ISSUE TITLE
Arcade.body.getBoundingBox for custom bounds

### ISSUE THREAD

**Issue by francois-n-dream** [photonstorm/phaser#4178]
I wanted to assign different bounds to an Arcade body instead of the world bounds (so that it bounds in a smaller rect).

I edited the body class myself like this and it seems to work:

```
getBounds() {
  if (this.customBounds) { return this.customBounds }; 
  return this.world.bounds;
}

setBounds(boundsRect) {
  this.customBounds = boundsRect;
}

// Setting it e.g. like:
// sprite.body.setBounds(myCustomBoundsRect);
```

In the part where it gets the bounds I replaced 
``this.world.bounds`` with ``this.getBounds()``

I just don't know if there are any other implications (E.g. with cameras and scrolling etc).
If it's that trivial I would file a pull request :)

**Comment by photonstorm** [comment]
There should be no implications of doing this, so it sounds like a useful PR (please ensure if you submit a PR that your code adheres to our editor config + jslint + coding styles)

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
