### ISSUE TITLE
Firefox error on page reload

### ISSUE THREAD

**Issue by Legomite** [photonstorm/phaser#4182]
## Version

* Phaser Version: 3.15.1

* Operating system: MacOS

* Browser: Firefox

## Description

This bug produces the error "**InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable**" whenever the same page with Phaser is reloaded. It does not occur in the first page load, just every reloaded page after. The error does not provide a line number or any other information.

## Example Test Code

labs.phaser.io

This error is reproducible in every example on Phaser Labs. Refreshing the page will produce the error on Firefox.

**Comment by glor** [comment]
also occurs on linux

**Comment by rmb938** [comment]
This bug still exists.

**Comment by photonstorm** [comment]
Please don't post unhelpful comments. There's no reason for it to not still exist, as no-one has submitted a fix for it yet.

**Comment by photonstorm** [comment]
Just tested this on Firefox Quantum 69.0.1 (64-bit) and it no longer happens, so whatever it was, they fixed it.
