### ISSUE TITLE
calling tween.play() again makes tween state bug

### ISSUE THREAD

**Issue by SamCode** [photonstorm/phaser#4184]
## Version

* Phaser Version: 3.15.1
* Operating system: Windows 10
* Browser: Google Chrome

## Description

When `tween.play()` is called a second time, the expected behavior is for the tween's state to reset so the tween can play again, **OR** `tween.state === Phaser.Tweens.COMPLETE`.

What actually happens is two semantic inconsistencies:

1. after one call of tween.play(), `tween.state === Phaser.Tweens.REMOVED` instead of `Phaser.Tweens.COMPLETE`
2. then jumps to `Phaser.Tweens.ACTIVE` and `tween.isPlaying()` returns true indefinitely, **while the tween does not actually ever update**.

## Example Test Code

1. https://labs.phaser.io/edit.html?src=src/tweens/update%20to.js
2. example code in scene.create()
```js
var tween = this.tweens.create({
    targets: [ sprite ],
    alpha: 0.5,
    ease: Phaser.Math.Easing.Sine.Out,
    duration: 200,
    yoyo: true,
    repeat: 0
});

sprite.setInteractive();
sprite.on('pointerdown', function(pointer) {
    // fails on second attempt
    tween.play();

    // always true
    console.log(tween.isPlaying());
});
```

## Additional Information

Currently, this hack seems to patch the issue, but is not an intuitive way to handle tweens.

```js
if (tween.state === Phaser.Tweens.REMOVED) {
    tween.restart();
    this.tweens.existing(tween);
} else {
    tween.play(true);
}
```

If I have a reference to a tween, I would like to use it freely without having to modify both the tween and the tween manager.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
