### ISSUE TITLE
Capitalized event in InputPlugin.js

### ISSUE THREAD

**Issue by gadelan** [photonstorm/phaser#4185]
## Version
* Phaser Version: 3.15.1 (also in master branch)
* Operating system: Not specific to an OS.
* Browser: Not specific to a browser.

## Description

Line 409 of InputPlugin.js reads

`this.pluginEvents.emit('preUpdate');`

It is the only occurence of this event name in the code and it is against event naming policy if I understand correctly the following comment

https://github.com/photonstorm/phaser/issues/3753#issuecomment-397356069

## Additional Information

This is probably a typo, but my knowledge of the source code is not enough to be sure of it. If this is found to be a bug, fixing it would be easy.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
