### ISSUE TITLE
Possible bug of word wrap in text object

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4187]
## Version
* Phaser Version:

Current version in code base

## Description

In [line 521](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/static/Text.js#L521)
```javascript
result += words[j] + ' ';
```

The [equation of counting of `spaceLeft`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/static/Text.js#L522) is 
```javascript
spaceLeft = wordWrapWidth - wordWidth;
```

Since it add a space ' ' into result, `spaceLeft` might be
```javascript
spaceLeft = wordWrapWidth - wordWidthWithSpace;
```

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
