### ISSUE TITLE
Quad alpha property not working

### ISSUE THREAD

**Issue by enriqueto** [photonstorm/phaser#4188]
on phaser v3.15.1

quad.alpha = .5;
quad.setAlpha(.5, .5, .5, .5);
quad.setAlpha(.5)

don't have any effect

**Comment by photonstorm** [comment]
Sorry, Quad shouldn't even have the Alpha component. I've tidied it up to remove the components you can't use. Quad (and Mesh) alpha should be set per vertice in the alphas array.
