### ISSUE TITLE
Shape is not rendered if there is no image in the scene or masked container

### ISSUE THREAD

**Issue by adrianolobo** [photonstorm/phaser#4190]
## Version

* Phaser Version: Phaser v3.15.1-FB (WebGL | Web Audio) 
* Operating system: Linux Deepin
* Browser:  Tested in Chrome  63.0.3239.132 (Official Build) (64-bit) and Firefox Quantum 58.0 (64-bit)

## Description

The Shape object is not rendered in a Scene if there is no image added.
A geometry masked container with a shape inside is not rendered if there is no image inside the container

## Example Test Code

```javascript
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#010101',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('buttonBG', 'assets/sprites/button-bg.png');
}

function create ()
{
    //  I have to add an image so the shape is not rendered
    const image = this.add.image(1000, 0, 'buttonBG');
    var container = this.add.container(200, 200);
    const rectangle = this.add.rectangle(0, 0, 100, 50, 0xff0000);
    container.add(rectangle);
    this.maskBg = this.make.graphics();
    this.maskBg.fillStyle(0xffffff, 1);
    this.maskBg.fillRoundedRect(200, 200, 50, 100, 5);
    // remove next line comment to make it work
    // container.add(image);
    container.setMask(this.maskBg.createGeometryMask());
}
```

## Additional Information

The sample code provided is this lab example modified:
http://labs.phaser.io/edit.html?src=src\game%20objects\container\multi%20container%20depth%20test.js

**Comment by adrianolobo** [comment]
This error does not occur in Phaser version 3.14

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
