### ISSUE TITLE
We need List view (Scroll view ) in Phaser 3 for Leaderboard Scene

### ISSUE THREAD

**Issue by takaaptech** [photonstorm/phaser#4191]
Please support ListView in Phaser 3 so we can make Leaderboard and high score easier!
Thank so much!

**Comment by rexrainbow** [comment]
Grid/list table is a huge UI componment,
[Here](https://codepen.io/rexrainbow/pen/BGKvXK) is a demo my grid table ui componment.

**Comment by photonstorm** [comment]
Closing this issue off, as it won't be added natively to Phaser 3 and there are great open-source alternatives available like those from rex.

**Comment by manishK18** [comment]
> Please support ListView in Phaser 3 so we can make Leaderboard and high score easier! Thank so much!

Hey @takaaptech you can use [this Scroll list view](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-scrollablepanel/) from rex for now if you need.
