### ISSUE TITLE
Can't get base64 string of RenderTexture

### ISSUE THREAD

**Issue by Eirik81** [photonstorm/phaser#4192]
I need to get the base64 string of the texture created by a RenderTexture. I've created a RenderTexture, drawn to it and saved it like this:
```
rt.saveTexture('bubbleboy');
```
I would then expect to be able to get the base64 string like this:
```
this.textures.getBase64('bubbleboy');
```
But the string returned seems to be an empty image. I've used this tool to test the string: https://codebeautify.org/base64-to-image-converter

When using the getBase64 method with a regular texture it works.

This fiddle reproduces the problem: http://jsfiddle.net/k6dn7fzh/1/

**Comment by Eirik81** [comment]
I've discovered that it works when using canvas (setting type to Phaser.CANVAS in the configuration object), but I need it to work for WEBGL as well.

**Comment by tianyagulvke** [comment]
I have to load assets of base64 at work. If ure 'this.textures.getBase64()' in the create function, it will be not graceful. Hope new version support it...

**Comment by photonstorm** [comment]
RenderTexture has the new `snapshot` function available, which can be used to achieve this. Equally, `TextureManager.getBase64` will now throw an error if you try to use it a non-image based texture. There will be no support for RT direct to base64, you'll have to do the final step yourself from the image that snapshot returns.
