### ISSUE TITLE
Semantic versioning of releases

### ISSUE THREAD

**Issue by ezzatron** [photonstorm/phaser#4196]
I was looking through the "Getting Started" docs, specifically about downloading Phaser.

I would like to use Phaser as a Yarn/NPM dependency, but I noticed that the [download page](https://phaser.io/download/stable) recommends pinning Phaser to a specific patch release, i.e.:

> `npm install phaser@3.15.1`

This leads me to believe that Phaser doesn't follow SemVer for it's releases, which is a bit surprising.

Is there some Phaser version constraint that, when I update my dependencies, will only select new versions that provide bug fixes and/or new features, but not BC breaks?

Could Phaser ever feasibly adopt SemVer, so that we can just use `npm install --save phaser` or `yarn add phaser` (which will both set up a `^3` style constraint by default these days)?

**Comment by photonstorm** [comment]
You can use it without a specific version number, which is the recommended way in the GitHub readme. But it in no way guarantees only non-breaking changes reach your projects. The '3' in the version number should be considered part of the package name, really, and the '15', '16', etc are major version numbers.

For legacy reasons, this can't actually be done in our version numbers, but it's definitely how you should treat them.

**Comment by ezzatron** [comment]
So if I understand correctly, something like `~3.15.1`, or `3.15.x` might be a better constraint to use than `^3.15.1`.

I'm still not 100% sure if you're saying that BC breaks sometimes happen in patch versions though. For example, could `3.15.2` introduce BC breaks from `3.15.1`?
