### ISSUE TITLE
RND(RandomDataGenerator) is null.

### ISSUE THREAD

**Issue by UYEONG** [photonstorm/phaser#4197]
## Version
* Phaser Version: v3.16.0 Beta 3-FB
* Operating system: MacOS
* Browser: Chrome

## Description

Version 3.15.x has rnd in const.js.
```
// math/const.js
// ...
    /**
     * An instance of the Random Number Generator.
     * 
     * @name Phaser.Math.RND
     * @type {Phaser.Math.RandomDataGenerator}
     * @since 3.0.0
     */
    RND: new RND()
};
```

But Version 3.16.0 does not have rnd in const.js.

```
// math/const.js
// ...
    /**
     * An instance of the Random Number Generator.
     * 
     * @name Phaser.Math.RND
     * @type {Phaser.Math.RandomDataGenerator}
     * @since 3.0.0
     */
    RND: null
};
```

So this problem occurs in the demo "[Matter Detect Collision With Tile](https://labs.phaser.io/view.html?src=src\game%20objects\tilemap\collision\matter%20detect%20collision%20with%20tile.js)".

```
matter detect collision with tile.js:66 Uncaught TypeError: Cannot read property 'integerInRange' of null
    at Scene.<anonymous> (matter detect collision with tile.js:66)
    at InputPlugin.emit (index.js:182)
    at InputPlugin.processDownEvents (InputPlugin.js:804)
    at InputPlugin.update (InputPlugin.js:548)
    at EventEmitter.emit (index.js:203)
    at Systems.step (Systems.js:364)
    at SceneManager.update (SceneManager.js:558)
    at Game.step (Game.js:552)
    at TimeStep.step (TimeStep.js:560)
    at step (RequestAnimationFrame.js:104)
```

that the code is missing in the refactored.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by bigswede74** [comment]
@photonstorm I'm using phaser 3 typescript and from looking at the [phaser 3 typescript github page](https://github.com/digitsensitive/phaser3-typescript) the package.json is using v3.18.1. How can I get the updated 3.19.0 if I'm using typescript?

```
  "dependencies": {
    "phaser": "3.18.1"
  },
```

**Comment by photonstorm** [comment]
@bigswede74 necro-posting year old issues isn't a great way to get your issue seen. You'll need to ask whoever maintains that repo (it's not us) to update it.

**Comment by bigswede74** [comment]
@photonstorm Sorry for the necro-post but I was having a similar issue to this one. Is it recommended to use the TypeScript definitions in the [phaser repo](https://github.com/photonstorm/phaser/tree/master/types) instead? I would rather not have a middle repo and get the types directly from the source.

**Comment by photonstorm** [comment]
@bigswede74 yes, definitely use our defs, they're the most up to date and accurate
