### ISSUE TITLE
Cannot play sounds concurrently with HTML5 Audio

### ISSUE THREAD

**Issue by neon-dev** [photonstorm/phaser#4200]
## Version
* Phaser Version: 3.15.1
* Operating system: Windows 7
* Browser: Firefox 63.0.3

## Description
Using HTML5 Audio, it's not possible to play two sounds of the same name concurrently.

## Example Test Code
https://jsfiddle.net/hemyq627/3/ here you will hear only one sound. In fact, the first one never plays, because the second one with the configured delay immediately stops it.
With event based sounds, ist usually happens that a sound gets cut off while playing, because another instance of it starts playing.

https://jsfiddle.net/hemyq627/2/ here you will hear both sounds. The second one shortly after the first one, but before the first one ends.

## Additional Information
I normally would use Web Audio where this issue doesn't exist, but Web Audio seems to have it's own issue. If the server hosting the sound file delivers it with status code 206 (Partial Content), Phaser on Web Audio doesn't seem to handle this. It just says "Audio cache entry missing" in the console, instead of downloading the whole file.
Is there something to configure about it or should I open another report for that?

**Comment by pavle-goloskokovic** [comment]
In order to play multiple instances of a sound when using HTML5 audio you need to define that number when loading audio file.

Take a look at this example:
https://labs.phaser.io/edit.html?src=src/audio/HTML5%20Audio/Markers%20-%20Play.js

In your case it would need to be:
```
this.load.audio('explosion', 'https://labs.phaser.io/assets/audio/SoundEffects/explosion.mp3', {
    instances: 2
});
```

This config value does not affect Web Audio since there is no limit for number of simultaneous audio playbacks when using it.

**Comment by pavle-goloskokovic** [comment]
It is briefly mentioned in the docs here:
https://github.com/photonstorm/phaser/blob/0441e19f2bbd33047fb28c161fb075ce770fa71c/src/loader/filetypes/AudioFile.js#L229

And was explained in detail in one of the previous newsletter issues:
https://madmimi.com/p/937c9b

But I agree, it should be made more obvious.

**Comment by neon-dev** [comment]
Indeed. Now that I know where to look, I could find it [here](https://photonstorm.github.io/phaser3-docs/Phaser.Loader.LoaderPlugin.html#audio__anchor) also. I just expected a config value somewhere in the SoundManager doc when I didn't know what exactly to search for.
I suggest adding a note [here](https://photonstorm.github.io/phaser3-docs/Phaser.Sound.HTML5AudioSoundManager.html#play__anchor) how to play more than one instance. 
Also the `disableWebAudio` property for the audio config doesn't seem to exist in the docs. That'd be also a nice place to mention the `instances` config.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by 123survesh** [comment]
> What I now realize is that I tested the `{instances: 2}` config with a sound instance and not `this.sound.play('name')` back then.
> `soundInstance.play()` cannot play concurrently by design, which makes sense.

This helped a lot. An example somewhat like this in the docs, explaining what works and what not works would be helpfull. Its not easy to understand the current one, **"An object containing an instances property for HTML5Audio. Defaults to 1 "**

**Comment by codenlighten** [comment]
Hey guys, In phaser 3, can i use an external url from a different website I own, for a sound source? Even though i've included a key, it's saying it's missing from audio context. 

example.


	function preload() {
		this.load.audio("boom", "https://abc.com/123.mp3");

**Comment by photonstorm** [comment]
@codenlighten I would strongly recommend posting this either to the Phaser forum or Discord, because it's not related to this issue.
