### ISSUE TITLE
Containers rotation and origin

### ISSUE THREAD

**Issue by PhaserEditor2D** [photonstorm/phaser#4201]
Hi,

I am playing with containers and I see I can rotate a container, but I cannot change the origin, that is constant (in the center).

Maybe I am missing something or I am too attached to v2 groups, but I think it is a bit forced, if we can rotate the container then we want to change the origin.

**Comment by lou** [comment]
I had a hard time playing with container and I finally managed to achieve container rotation thanks to Rex ContainerLite:
https://rexrainbow.github.io/phaser3-rex-notes/docs/site/containerlite/
