### ISSUE TITLE
Problem with collision detection (body.blocked.down)

### ISSUE THREAD

**Issue by PrzemyslawPolrolniczak** [photonstorm/phaser#4202]
## Version
* Phaser Version: 3.15.1 "Batou"
* Operating system: Windows 10

## Description

There is something wrong with collision detection. 

I've tried to follow guide about creating yeahbunny-like game, and everything work flawlessly, but when hero is gripping the wall and he's touching the ground, hero.body.blocked.down is not marked as true.

https://www.emanueleferonato.com/2018/04/28/super-mario-who-html5-platformer-prototype-inspired-by-ios-hit-yeah-bunny-thanks-to-phaser-and-arcade-physics-updated-to-phaser-3-6-0/

I even downloaded this project and run it with newest phaser - still buggy. When I switch back to phaser 3.6.0, it works fine.

## Example Test Code

Exactly same code is posted here:
https://www.emanueleferonato.com/2018/04/28/super-mario-who-html5-platformer-prototype-inspired-by-ios-hit-yeah-bunny-thanks-to-phaser-and-arcade-physics-updated-to-phaser-3-6-0/

## Additional Information

To reproduce this bug, download project form link above and change phaser.min.js from 3.6.0 to 3.15.1

**Comment by photonstorm** [comment]
I know this is a super-old issue, but I just tested the bunny code and the problem no longer exists in Phaser 3.20, so I'm going to close this off.
