### ISSUE TITLE
ScaleManager incorrectly computes hit areas

### ISSUE THREAD

**Issue by ibequa** [photonstorm/phaser#4203]
## Version

* Phaser Version: 3.16 beta

* Operating system: all

* Browser: Chrome

## Description

`ScaleManager` with `Phaser.DOM.CONTAIN` setting incorrectly computes hit areas of all Phaser.GameObjects. In the example below I'm using `Phaser.Image`
![test](https://user-images.githubusercontent.com/10791652/49226507-e3419d80-f3f7-11e8-986d-dfee8842c266.gif)

## Example Test Code

```
var config = {
    type: Phaser.AUTO,
    backgroundColor: '#2dab2d',
    scale: {
        mode: Phaser.DOM.CONTAIN,
        width: 800,
        height: 600
    },
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('pic', 'assets/pics/zero-two.png');
    this.load.image('buttonBG', 'assets/sprites/button-bg.png');
}

function create ()
{
    this.add.image(0, 0, 'pic').setOrigin(0);
    var button = this.add.image(200, 150, 'buttonBG');
    button.setInteractive();
    button.on('pointerover', function() { button.setScale(1.2); });
    button.on('pointerout', function() { button.setScale(1); });
}
```

**Comment by photonstorm** [comment]
Closing as this is now working correctly in master. Thank you for the submission though :)
