### ISSUE TITLE
Get error when start a scene using plugin rexUI

### ISSUE THREAD

**Issue by raphlee** [photonstorm/phaser#4204]
## Version

* Phaser Version: 3.14 and 3.15.1

* Operating system: Windows 10

* Browser: Google Chrome | 70.0.3538.102 (Official Build) (64-bit) (cohort: Stable)
-- | --

## Description

My game have plugin rexUI from [rexUI](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/index.html) to create a simple scroll view (use GridTable) in a scene called Menu. Everything works fine, until I click an item view, this call a callback to start a scene (called Game). In console, it showed error and the game got frozen.
Actually, the game got frozen in version 3.14. When I update to version (just downloaded in webs) 3.15.1, it no longer frozen, the Game scene is loaded but the error still thrown.

## Example Test Code

Import plugin in scene (Menu)

`preload() {
        this.load.scenePlugin({
            key: 'rexuiplugin',
            url: 'assets/libs/rexuiplugin.min.js',
            sceneKey: 'rexUI'
        });
    }`

Event:

`// event
        table.on('cell.click', function (cellContainer, cellIndex) {
                console.log('Game scene with index ' + cellIndex);
                this.scene.start('Game');
            }, this);`

## Additional Information

Here is screen shot:
![error](https://user-images.githubusercontent.com/16055569/49235428-ab088200-f42c-11e8-8a72-623f74687e64.PNG)

---
I guess, the problem is when start a scene, the old scene is destroy, but not everything, specially is plugin. I tried use 'switch' scene instead, it's working like a charm, but I don't want to change scene like this.

**Comment by rexrainbow** [comment]
Please report to [my github](https://github.com/rexrainbow/phaser3-rex-notes/issues), with a very simple and run-able test code. I would like to solve it first.

**Comment by raphlee** [comment]
thanks to @rexrainbow , plugin was fixed.
