### ISSUE TITLE
Tweening graphic widths

### ISSUE THREAD

**Issue by SKEPDIMI** [photonstorm/phaser#4205]
Currently I'm attempting to take a rectangle I created and tween it's width. Is there a way to achieve this in Phaser 3?

```
// health bar is a rectangle made using game.add.graphics().fillRect()
var healthBar = state.healthBar;

var newHealthWidth = Math.random() * 100;

this.add.tween(healthBar)
.to({ width: newHealthWidth }, 500);
```

**Comment by photonstorm** [comment]
The Graphic Game Object doesn't have a size, so you can't do it like this. You'd be better off using the Rectangle Shape Game Object and tweening that. Or, if you need to use a Graphics object, clear it in the tween update callback and redraw its contents every time the tween updates.
