### ISSUE TITLE
scaleX then scaleY lead to matterjs shape error

### ISSUE THREAD

**Issue by YannCaron** [photonstorm/phaser#4206]
## Version

- Phaser Version: 3.15.1

- Operating system: ubuntu

- Browser: All

## Description

When a Matter.Image, configured with a physic shape, is scaled on X then on Y or vice versa, the shape become distorted.
It seems that the second scale apply again the first one.

``` javascript
class Actor extends Phaser.Physics.Matter.Image {
    constructor(scene, x, y, texture) {
    super(scene.matter.world, x, y, texture, 0, {
        shape: scene.fixtures[texture]
    });

    // ....

}

let gem = new Actor(this, 100, 400, 'Gem Blue');
gem.scaleX = 0.5;
// here everything is ok
gem.scaleY = 0.5;
// here the shape x is resized again
```

give that (with debug mode activated) :
- With scaleX = 0.5 then scaleY = 0.5
![image](https://user-images.githubusercontent.com/5962300/49328080-bbbf1200-f56a-11e8-816a-923424092ec4.png)

- With scaleY=0.5 then scaleX = 0.5
![image](https://user-images.githubusercontent.com/5962300/49328121-54559200-f56b-11e8-8221-012e52a9c513.png)

## turn around
Use `setScale(0.5, 0.5)` instead.

## words
Many thanks to Phaser and matterjs teams that give us so valuable tools.
Cheers.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by YannCaron** [comment]
Many thanks @photonstorm, I will try to compil it when I find a few time :1st_place_medal:
