### ISSUE TITLE
Collision between DynamicLayer and sprite doesn't always work

### ISSUE THREAD

**Issue by donfrigo** [photonstorm/phaser#4208]
## Version

* Phaser Version: 3.15.1

* Operating system: Linux

* Browser: Chrome

## Description

I am working on a shooter game and collision between the ground and bullets doesn't always work right, as seen on the [gif](https://user-images.githubusercontent.com/10243549/49340953-dc5c9a00-f646-11e8-8a7a-b5b75e7c8be9.gif). Thank you!

## Example Test Code

Here is a codesandbox [link](https://codesandbox.io/s/61l18709yw).

I am using the following code to load the tiles and add the collision:

```
 this.load.tilemapTiledJSON("map", "../assets/tilemaps/sheet.json");
 const map = this.make.tilemap({ key: "map" });
 const tiles = map.addTilesetImage("sheet", "tiles");

 this.groundLayer = map.createDynamicLayer("Ground", tiles);

 this.groundLayer.setCollisionByProperty({ collides: true });

 this.bullets = this.physics.add.group({
            classType: Bullet,
            runChildUpdate: true
        });

this.physics.world.addCollider(this.bullets, this.groundLayer);

```

**Comment by photonstorm** [comment]
I cannot replicate this with the code given on my system / browser, although based on the gif I do wonder if this is just a typical tunneling issue. I.e. the bullet is going too fast for the thickness of the wall (Arcade Physics has absolutely no form of CCD built into it, so it's easy for fast-moving projectiles to penetrate walls)
