### ISSUE TITLE
this.anims doesn't get cleaned up when stopping the scene

### ISSUE THREAD

**Issue by neon-dev** [photonstorm/phaser#4209]
## Version
* Phaser Version: 3.15.1
* Operating system: Windows 7
* Browser: Firefox 63.0.3

## Description
Changing to a previously visited scene or restarting it creates warnings about duplicate animations. I suppose they just don't get cleaned up like images and sounds do.

## Example Test Code
https://jsfiddle.net/rmhbyLtf/ Open the console, then click on the canvas.

**Comment by photonstorm** [comment]
This is by design. Animations are global, just like textures, so can be shared between multiple Scene's. If you know you don't need the animation ever again when the Scene ends, you can delete it from the Animation Manager.

**Comment by neon-dev** [comment]
How are we supposed to load these only once or per scene?

Example: A game where you switch through all scenes during normal gameplay and only need certain animations in per specific scene. At the end of the game, it restarts by switching back to the first scene again.
In this case I'd need to create a special scene just for preloading animations, so they can't get initialized twice. All other assets can be loaded per scene without warnings and it's a great way to encapsulate and organize all "steps" of a game. It reduces maintainability of code and more easily leads to dead and unused (but still loaded) resources, if you start ripping that apart.

I'd rather live with this warning, instead of relocating code outside of its "proper" position or adding some superficial checks to suppress the warning/secondary loading.

Maybe I'm doing it all wrong, but I though scenes were meant to be these reusable containers in where you can do all kinds of stuff and don't worry much about resource cleanup when switching to the next one.
I know it's not really that easy, but why shouldn't it? I think it would be more self explanatory if global scope and scene scope were more easily distinguishable from each other (API-wise). If I remember correctly, scene specific event listeners are another thing that are not cleaned up. Meaning each scene reentry adds another handler because the old instance never got unregistered. If that's still the case, at least that must be a bug (?)

Phaser 3 is not that straight forward in some regards as I had hoped and the still only partly migrated homepage from v2 doesn't make it easier. Often times I feel like there's no example on how to properly organize a Phaser 3 project, etc. Or how and what to share, when and why. This game engine can do all kinds of things, but it's not easy to find out about certain features even if you search and dig really deep. Often the JS doc and labs examples don't tell the whole story.
Anyway, sorry for OT, just wanted to let you know this too.

**Comment by photonstorm** [comment]
Everything stored in a global system that uses a key does the same thing. Textures, Scenes, Audio, Animations - if you try to create any of these twice, you will get a warning because the key is already in use. They are global assets for use by any Scene in the game, not just the one in which they are created, which is why they should be preloaded in a central location and treated as such.

The only difference is that the Loader will suppress these warnings. If you try to load an asset using a key already in use, the Loader will silently fail (the asset does not get loaded again) before it even gets as far as the global system. If you wish to utilize this behavior for animations then you could load those from json files.

**Comment by neon-dev** [comment]
Thanks for this clarification, I see.
I already assumed that most of the stuff in preload functions are available globally, but never tried. And this makes sense. Maybe it'd be wise to treat animations more like assets and should be better loaded via the loader and in a preload function. Current examples load them in the create function, which seems incorrect with the new information I now have.
Also it's the first time I read that preloading should happen centralized and not per scene. As you can tell I'm not a Phaser 3 veteran, so the examples I followed made me assume it'd be right way. And it's not that far fetched, since only scenes have preload functions, but the game instance itself has none. So hopefully you agree that it's easy to misinterpret the system with no official multi-scene tutorial (at least I couldn't find one).
In my personal opinion, there should at least be clear and easily accessible guides for this. Or better yet as I mentioned, a global preload function and a note in the documentation that scene specific preload functions should be only used in the rare cases where they make sense.
