### ISSUE TITLE
dose Phaser 3 support Spine？

### ISSUE THREAD

**Issue by angelia-yuqi-personal** [photonstorm/phaser#4211]
**We're constantly trying to make Phaser 3 better**

So we'd love to hear about feature requests for the v3 API. Screenshots, example code or links to blog posts / other APIs are encouraged.

Please try and keep the requests sensible. We will only keep those we feel are within our abilities to add to Phaser, or that are a good fit for our API.

**[Optional] Do you want to help provide this feature?**

If you would like to get involved in helping build the feature, please let us know. We can then discuss implementation with you and the best way to approach it. Again, screenshots or mockups are really useful.

**Comment by photonstorm** [comment]
Full support for Spine will be available when Phaser 3.16 is released.
