### ISSUE TITLE
Feature request : Install scene plugin into existed scene

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4212]
## Version

* Phaser Version: 3.15.1

## Description

[Here](https://codepen.io/rexrainbow/pen/pQmLWR?editors=1011) is a sample code.

All scene instances will be created when they are defined in Game configuration, for example

```javascript
var game = new Phaser.Game({
    scene: [MainScene, SubScene],
});
```

They are 2 scenes : *MainScene*, *SubScene*. These scenes will [install custom scene plugin](https://github.com/photonstorm/phaser/blob/master/src/scene/Systems.js#L324) when creating, 

Then user might download and install scene plugin during **preload** stage in MainScene. This new scene plugin will be available in MainScene.

Since SubScene has [installed custom scene plugin](https://github.com/photonstorm/phaser/blob/master/src/scene/Systems.js#L324) already, this new scene plugin can not be mapped into SubScene.

One possible solution is to add a method to install scene plugin into existed scene.

Current workaround solution is to add custom scene plugin in Game configuration object, which will be installed before any scene creating.

**Comment by photonstorm** [comment]
To be honest, I've thought about this and I can't see a benefit from changing it. As you said, if you need a Scene Plugin in all of your Scenes from the start, you can just add it to the Game Config and it'll be added properly. I'm struggling to think of a use-case where you would need a plugin retroactively installed in your older Scenes. If you can think of one, let me know (here or Discord) and I may revisit this.

**Comment by rexrainbow** [comment]
Scene plugin only can be loaded inside a scene in preload stage from url (`scene.load.scenePlugin(key, url, systemKey, sceneKey)`). Game Config might not be worked in this case.

It is fine to keep current solution, just have note to warning user that scene plugin won't be added to existed scene.

**Comment by photonstorm** [comment]
You can also load it in the Scene payload, but I guess that's still too late to use it in the current Scene.

**Comment by rexrainbow** [comment]
Another workaround : put an extra boot scene in Game config, to load scene plugins (in preload stage, for example), then add original scenes after loaded scene plugins (in create stage).
