### ISSUE TITLE
Arcade.Components.Size#setSize fails to center a static body

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#4213]
## Version

* Phaser Version: 3.15.1

## Description

Arcade.Components.Size#setSize() should center the body on the texture when the `center` argument is true or omitted, but for static bodies this doesn't happen.

## Example Test Code

On <http://labs.phaser.io/edit.html?src=src\physics\arcade\static%20body.js> change line 37 to

```javascript
static1 = this.physics.add.staticImage(400, 100, 'bar').setSize(150, 150);
```

## Additional Information

StaticBody#setSize(width, height, offsetX, offsetY) is being called with the wrong third argument.

**Comment by photonstorm** [comment]
`StaticBody` doesn't have, or use, the `setSize` component though. It has its own internal method.

**Comment by samme** [comment]
E.g.,

```javascript
static1.setSize(150, 150, true);
```

calls

    Arcade.Components.Size#setSize( width=150, height=150, center=true ) →
      Arcade.StaticBody#setSize( width=150, height=150, offsetX=true, offsetY=undefined )

And that gives

    body.offset.x === true

So probably Phaser.Physics.Arcade.Components.Size#setSize() should check the body type and ignore the `center` argument for static bodies.

**Comment by samme** [comment]
I wonder if `Arcade.Components.Size#setSize()` should be renamed to `setBodySize()` (despite the inconvenience).

In `Arcade.Sprite` etc., it overrides `GameObjects.Components.Size#setSize()`, which is a little confusing, because the methods are unrelated.

**Comment by photonstorm** [comment]
Yes, worth a rename while 3.16 is still imminent.

**Comment by samme** [comment]
#4145
