### ISSUE TITLE
Custom blend modes example UI not working

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#4218]
The [custom blend mode example](http://labs.phaser.io/view.html?src=src/display/blend%20modes/custom%20blend%20mode.js) is not working properly. More specifically, the selection menu that should allow to change the blend mode doesn't display, because `$ is not defined`.

**Comment by photonstorm** [comment]
Thank you for reporting a problem with this example. It has now been fixed. You can find the updated version in this repo and on the labs.phaser.io site.
