### ISSUE TITLE
Mistake in docs or wrong input param's type

### ISSUE THREAD

**Issue by imilo** [photonstorm/phaser#4220]
## Version
* Phaser Version: 3.15

## Description

Function `Phaser.Tilemaps.Tilemap#hasTileAt` (and neighbors) according to the docs rewrites input parameter `layerData` with `layerData`, like with itself.

```javascript
    /*
     ...
     * @param {Phaser.Tilemaps.LayerData} [layer] - The tile layer to search. If not given the current layer is used.
     ...
     */
    hasTileAt: function (tileX, tileY, layer)
    {
        layer = this.getLayer(layer);
        ...
```

It sends `layer` to the function `getLayer()` which expects only:
- string
- integer
- Phaser.Tilemaps.DynamicTilemapLayer
- Phaser.Tilemaps.StaticTilemapLayer

.. but returns `layerData` according to the docs:

```javascript
    /*
     * @param {(string|integer|Phaser.Tilemaps.DynamicTilemapLayer|Phaser.Tilemaps.StaticTilemapLayer)} [layer] - The name of the
     * layer from Tiled, the index of the layer in the map, a DynamicTilemapLayer or a
     * StaticTilemapLayer. If not given will default to the maps current layer index.
     *
     * @return {Phaser.Tilemaps.LayerData} The corresponding LayerData within this.layers.
     */
    getLayer: function (layer)
    {
        var index = this.getLayerIndex(layer);

        return index !== null ? this.layers[index] : null;
    },
```

`this.getLayerIndex()` also doesn't expect `layerData`, so it will never return correct result. Is something missing in JS code or the issue is in docs only?

Probaly `hasTileAt()` expects string, int, DynamicTilemapLayer and StaticTilemapLayer, but not `layerData`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
