### ISSUE TITLE
camera renderToTexture: camera zoom is applied twice

### ISSUE THREAD

**Issue by wayfu** [photonstorm/phaser#4221]
## Version
* Phaser Version: 3.15.1
* Operating system: win
* Browser: chrome

## Description
When using `setRenderToTexture` on a camera, its zoom will be applied twice. 

## Example Test Code
To test, add `this.cameras.main.zoom = 2;` to the create function here and watch it zoom to 4x: 
http://labs.phaser.io/edit.html?src=src/camera/render%20to%20texture%20shader.js

**Comment by bja1011** [comment]
I have a related problem with this issue. Details here: https://phaser.discourse.group/t/setrendertotexture-and-camera-zoom/3694
The problem occurs only on WebGL renderer.

**Comment by DanMcgraw** [comment]
Has anyone ever found a solution to this?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
