### ISSUE TITLE
StaticBody#reset doesn't use its x and y arguments

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#4224]
## Version

* Phaser Version: 3.15.1, 3.16.0 Beta 3

## Description

If you pass `x` and `y` arguments to [StaticBody#reset](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.StaticBody.html#reset__anchor) they have no effect. The body is always reset to the game object's coordinates.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
