### ISSUE TITLE
Camera getWorldPoint() briefly inaccurate during zoom change while following sprite

### ISSUE THREAD

**Issue by Legomite** [photonstorm/phaser#4225]
## Version

* Phaser Version: 3.15.1, 3.17.0, 3.24.1

* Operating system: MacOS, iPad OS

* Browser: Tested on Safari, Chrome, Firefox

## Description

If the camera is set to follow something, calling getWorldPoint() while the camera zoom is changing will very briefly send an inaccurate coordinate. 

## Example Test Code

```
class myScene extends Phaser.Scene {
  constructor() {
    super('sceneTest');
  }

  preload() {
    this.load.image('player', 'player.png');
  }

  create() {
    var sprite = this.add.sprite(0, 0, 'player');

    this.cameras.main.startFollow(sprite);

    var context = this;

    this.input.keyboard.on('keydown_P', function (event) {
        if(context.cameras.main.zoom > 0.5)
          context.cameras.main.setZoom(Math.round(1000 * (context.cameras.main.zoom - 0.05)) / 1000);
    });

    this.input.keyboard.on('keydown_O', function (event) {
        if(context.cameras.main.zoom < 1)
          context.cameras.main.setZoom(Math.round(1000 * (context.cameras.main.zoom + 0.05)) / 1000);
    });

    this.coordinates = [];
  }

  update() {
    if(this.cameras.main.getWorldPoint(0, 0).x === this.coordinates[0] && this.cameras.main.getWorldPoint(0, 0).y === this.coordinates[1])
      return;

    this.coordinates = [
      this.cameras.main.getWorldPoint(0, 0).x,
      this.cameras.main.getWorldPoint(0, 0).y
    ];

    console.log(this.coordinates);

    var thing = this.add.text(this.coordinates[0], this.coordinates[1], 'O');
  }
}

var config = {
  type: Phaser.AUTO,
  width: document.documentElement.clientWidth,
  height: document.documentElement.clientHeight,
  resolution: window.devicePixelRatio,
  autoResize: true,
  pixelArt: true,
  scene: [ myScene ]
};

var game = new Phaser.Game(config);
```

## Additional Information

In the example, the update code is checking whether the coordinates from getWorldPoint() is the same as the last check. If it is different, it will log the console and put text unto the coordinate it was given. This means that with each camera zoom, a letter "O" will appear at coordinates from getWorldPoint(0, 0). 

There are only 10 camera zooms, so ideally there will only be 10 "O"s and 10 logs from the console. Instead, there is 20 "O"s and 20 logs implying that there is a brief moment of inaccuracy when calling getWorldPoint().

This issue only happens when the camera is set to follow something.

**Comment by photonstorm** [comment]
When following something, the Camera matrix is updated in the `preRender` step. Testing it in `update` is testing it prior to those changes, so it's entirely possible for the camera matrix to be updated in the same game step, but after your test takes place. If you wish to use the latest camera matrix (which is what `getWorldPoint` does) then you need to check it based on a Scene `render` event, so it has the most current values within it.

**Comment by photonstorm** [comment]
See the new Camer `FOLLOW_UPDATE_EVENT` to deal with this situation.
