### ISSUE TITLE
Destroy interactive on mobile lead to Uncaught TypeError on other sprite events.

### ISSUE THREAD

**Issue by YannCaron** [photonstorm/phaser#4228]
## Version

- Phaser Version: 3.15.1

- Operating system: android

- Browser: chrome

## Description
On mobile device, when a draggable interactive image is destroyed, the 'pointerdown' event on other 'draggable' sprite lead to 'Uncaught Type Error' exception.

Here is the example to illustrate:
``` javascript
const sprite1 = this.add.image(150, 150, 'Character Pink Girl');
sprite1.setInteractive({
    pixelPerfect: true,
    draggable: true,
});
sprite1.on('pointerdown', () => {
    sprite1.destroy();
});

const sprite2 = this.add.image(250, 150, 'Character Pink Girl');
sprite2.setInteractive({
    pixelPerfect: true,
    draggable: true,
});
sprite2.on('pointerdown', () => {
    sprite2.destroy();
});
```

![image](https://user-images.githubusercontent.com/5962300/49954515-edd45a80-ff00-11e8-947f-4de000022eaa.png)

On Desktop, everything is fine. We can click on both images and both are deleted properly.
On my Android phone, the first one works well but the second one does not works.
It generate the following LogCat log:
```bach
12-13 16:28:51.817 14773 14773 I chromium: [INFO:CONSOLE(76876)] "Uncaught TypeError: Cannot read property 'dragState' of undefined", source: http://192.168.42.238:4000/vendors~game.js (76876)
```

After some investigation, it appears that problem come from the fact to destroy the image into the event.
When doing this:
``` javascript
const sprite1 = this.add.image(150, 150, 'Character Pink Girl');
sprite1.destroy();

const sprite2 = this.add.image(250, 150, 'Character Pink Girl');
sprite2.setInteractive({
    pixelPerfect: true,
    draggable: true,
});
sprite2.on('pointerdown', () => {
    sprite2.destroy();
});
```
it works well.

## Thanks
Big thank to Phaser team :+1:

**Comment by YannCaron** [comment]
Found source of the problem.
We must destroy the event first:
```javascript
const sprite1 = this.add.image(150, 150, 'Character Pink Girl');
sprite1.setInteractive({
    pixelPerfect: true,
    draggable: true,
});
const handler = () => {
    sprite1.off('pointerdown', handler);
    sprite1.destroy();
};
sprite1.on('pointerdown', handler);
```

I don't know if it is even a bug or my misunderstanding :-)

**Comment by Loick1109** [comment]
i get the same error when i destroy my image inside of the dragenter event

              this.input.on('dragenter',  (pointer:PointerEvent, gameObject, dropZone)=> {

                
                try {
                  this.myBillet = gameObject as Billet;
                    
                  let v:string = gameObject.texture.key;
                  v=v.substr(0,v.length-2);
                 
                  
                  if(this.myBillet._zone!="ZONE_REPONSE" && dropZone.name=="ZONE_REPONSE"){
                   
                    this.myBillet._zone=dropZone.name;
                    this.billets_sur_table.push(this.myBillet);
                    if(!this.tables.containsKey(v)){
        
                     
                      this.tables.add(dropZone.name,this.billets_sur_table);
                        
                     }
                     else{
                      this.tables[this.myBillet._zone]=this.billets_sur_table;
                     }
                     var billet = new Billet(this,gameObject.input.dragStartX, gameObject.input.dragStartY,v,this.groupe_portefeuilles,"ZONE_CREATION", {font:"20px 'Arial'",fill:"#000"});
                     this.tweens.add({
                      targets: gameObject,
                      y: pointer.y,
                      x:pointer.x,
                      duration: 1000,
                      ease: 'Power2',
                      completeDelay: 1000
                  });
                  }else if(this.myBillet._zone=="ZONE_REPONSE" && dropZone.name=="ZONE_CREATION"){
                
                    var b = this.myBillet;
                    var evens = _.remove(this.billets_sur_table, function(n) {
                      return n == b;
                    });
                    
                    this.tables["ZONE_REPONSE"]=this.billets_sur_table;
                    this.myBillet.input.enabled=false;
                    this.myBillet.destroy();
                   
                 
                  }

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by YannCaron** [comment]
Many thanks @photonstorm. I Put to test it as an entry in my backlog. Therefor it will be done soon :-)

**Comment by YannCaron** [comment]
I've just tested on v3.16.2 and it works perfectly. Many thanks again.
