### ISSUE TITLE
Can't limit fps with FPSConfig

### ISSUE THREAD

**Issue by johanlindfors** [photonstorm/phaser#4229]
## Version
* Phaser Version:
3.15.1
* Operating system:
Windows 10

## Description
Trying to limit the frame rate by setting a fps target of 15 through the FPSConfig but nothing seems to work.

## Example Test Code

var config = {
    type: Phaser.AUTO,
    width: 400,
    height: 400,
    fps: {
        target: 15,
    },
    scene: {
        create: create,
        update: update
    }
};

**Comment by photonstorm** [comment]
This isn't implemented yet and shouldn't have been added to the config. Will put it down as a feature request to get looked into.

**Comment by idpokute** [comment]
Do you have any changes for this feature?

**Comment by garkin** [comment]
At the moment (3.22) it could be done with a hack:
```js
export function installPhaserFpsLimitHack(
    game: Phaser.Game,
) {
    const noop = () => {};
    let callback: any = game.loop.raf.callback;
    Object.defineProperty(game.loop.raf, "callback", {
        get() {
            return shouldSkipFrame() ? noop : callback;
        },
        set(v: any) {
            callback = v;
        }
    });
}
```

Not sure how will it play with frame smoothing, since not using it. So assume to have a following config: 
```typescript
new Game({ /**/ fps: { smoothStep: false } /**/ })
```

**Comment by photonstorm** [comment]
I have updated the documentation to make it clearer that isn't what the property is for. This feature does not exist in v3.x and won't be added I'm afraid.

**Comment by geotheory** [comment]
How are we supposed to limit framerate @photonstorm? This is a basic requirement.

**Comment by geotheory** [comment]
Ah I see it's resolved under 3.52. Awesome cheers.

**Comment by ProgrammingLife** [comment]
@geotheory it doesn't work properly. It can limit fps only when you use setTimeout over requestAnimationFrame which can lead you to some trouble because setTimeout running even when you unfocus your tab. So it cat consume more CPU power than requestAnimationFrame method.

**Comment by photonstorm** [comment]
Browsers will still throttle (and then entirely pause) setTimeout when you focus another tab, they make no distinction between that and RAF in this respect.
