### ISSUE TITLE
Camera Zoom : set Min / Max allowed

### ISSUE THREAD

**Issue by giviz** [photonstorm/phaser#4231]
Phaser 3

The camera zoom do not have parameter to set a min and max zoom we allow the user to go to.
The minimum is 0.1, but in some cases that do not make any sense to allow the user to go beyond 0.5 for example.

Here are 2 cases where the min zooming is too high and that's not user friendly at all :

![screen_shot_2018-12-12_at_10 31 54_pm](https://user-images.githubusercontent.com/3670552/49978352-6bde4300-ff8d-11e8-97ad-1166a0000c57.png)

![screen_shot_2018-12-12_at_10 34 03_pm](https://user-images.githubusercontent.com/3670552/49978364-77316e80-ff8d-11e8-8526-c416ed9ad33b.png)

Thank you !

**Comment by photonstorm** [comment]
To be honest, this is so game specific that you need to manage it in your own code. There's no point Phaser enforcing this. While I could add in min and max properties it seems a bit pointless when it's solved so easily by a quick logic check in the game code.
