### ISSUE TITLE
skipMissedFrames seems not to be implemented

### ISSUE THREAD

**Issue by colorcube** [photonstorm/phaser#4232]
## Version

* Phaser Version: 3.15.1
* Operating system: windows, linux
* Browser: Chrome, FF

## Description

I have an animation with 60 fps (yes that's very much, but there's a reason)

The browsers seem not to be able play 60fps. The option skipMissedFrames: true should play the animation at the required speed nevertheless by skipping frames. But it looks like every frame is displayed (at 25fps maybe). Therefore the animation plays 2-3 times longer than expected.

My expectation is that frames will be skipped when necessary to play the animation at the wanted speed.

I looked out for code in phaser but could find any implementation. Is it missing?

## Example Test Code

```
    this.anims.create({
      key: name,
      frames: frames,
      frameRate: framerate,
      repeat: 0,
      skipMissedFrames: true
    });
```

**Comment by photonstorm** [comment]
It was never added and shouldn't be part of the config object yet either.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/tweens-paused-after-losing-focus-workaround/8770/11
