### ISSUE TITLE
Rope in Phaser3

### ISSUE THREAD

**Issue by Secretmapper** [photonstorm/phaser#4234]
In Phaser 2, there was a pretty useful Rope GameObject.

Is this something that would/could potentially be added to Phaser 3?

**Comment by photonstorm** [comment]
Yes, but there are no plans for it at the moment. We'd take a community PR though.

**Comment by samme** [comment]
<https://pixijs.io/examples/#/demos/strip-demo.js>

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
