### ISSUE TITLE
List.js scope conext for sort handler is missing

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#4241]
Phaser Version: v3.5.1, Phaser.Structs.List.js

    sort: function (property)
    {
        if (property)
        {
            this._sortKey = property;

            StableSort.inplace(this.list, this.sortHandler);
        }

        return this;
    },
    sortHandler: function (childA, childB)
    {
        return childA[this._sortKey] - childB[this._sortKey];
    },

as you can see, here it passes this.sortHandler to the StableSort.inplace function, but when later this handler is executed by the StableSort, the _sortKey is lost in the scope because `this` is pointed to the Window object.

**Comment by jcyuan** [comment]
btw, I think better to have a optional paramter `customizedHandler` for complex object sorting.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
