### ISSUE TITLE
Render texture is dependent on scene.game.config.width/height

### ISSUE THREAD

**Issue by hackhat** [photonstorm/phaser#4243]
I'm not sure why the width/height of the game breaks the render texture, but it does even in the phaser@3.15.1

If I don't set the game width/height the rendercanvas is very small around 500x500, no the size I give it to it when I create it.

This is related to this bug https://github.com/photonstorm/phaser/issues/3958 (has not been answered for months)

**Comment by hackhat** [comment]
Also there is something very weird that if it breaks, and then restore the commit back the texture is still cropped. I'm not sure where this cache is stored. Maybe in webpack, but it never happened to me before.

What I'm trying to say is that the same commit (exact code) has 2 different results dependent on previous code changes.

**Comment by photonstorm** [comment]
You can't _not_ set a game width and height. If you don't provide one, it will default to 1024 x 768.

You can't not set a RenderTexture size either. If you don't provide one, it'll default to 32 x 32.

If I remove the game width/height from any of the RT demos, even under 3.15.1, they work as before (just with a larger canvas in most cases)

What is it, exactly, that you're seeing happening?

**Comment by hackhat** [comment]
So if I don't change the `scene.game.config.width` I see the max drawable rendertexture the size of my screen, which is 600 x 500px. So the render texture is 600x500 even if I set it to 15000x15000.

If I change `scene.game.config.width` to 15000 then the rendertexture renders the correct size, 15000.

> You can't not set a RenderTexture size either. If you don't provide one, it'll default to 32 x 32.

I might be wrong but render texture has a width:

![image](https://user-images.githubusercontent.com/11173732/50145876-7c741d80-02ed-11e9-9c10-5ee0115a511c.png)


Note that the rendertexture is inside a container which is viewed with a camera that is zoomed out and panned.

> You can't not set a game width and height. If you don't provide one, it will default to 1024 x 768.

I know, it's a hack that works sometimes... and tricks the render texture to be of the size I request and not of the size of the screen.

**Comment by hackhat** [comment]
Just to correct. This behaviour only works in the phaser@3.12.0. On the 3.15.1 I can't make the rendertexture any size except the screensize.

here is the size: https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.RenderTexture.html

![image](https://user-images.githubusercontent.com/11173732/50146145-150a9d80-02ee-11e9-97f9-172040800fe7.png)


I'm not sure why you say can't set the size on a RenderTexture.

**Comment by hackhat** [comment]
Here is https://labs.phaser.io/edit.html?src=src\game%20objects\render%20texture\container%20to%20render%20texture.js

So if the render texture is 5k x 5k, then when is scaled by 0.2, should be 1k width. But is not as you can see in the output:

![image](https://user-images.githubusercontent.com/11173732/50147187-7a5f8e00-02f0-11e9-8b4e-b33b3d622543.png)

**Comment by hackhat** [comment]
A more obvious example here as well: https://labs.phaser.io/edit.html?src=src\game%20objects\render%20texture\container%20to%20render%20texture.js

If the width is 2000px:
![image](https://user-images.githubusercontent.com/11173732/50147476-302adc80-02f1-11e9-89be-86ba575ced7a.png)

If the width is 1000px:
![image](https://user-images.githubusercontent.com/11173732/50147498-3caf3500-02f1-11e9-8e7a-ea2f836a3b66.png)


The width is the same, how can be possible when the width is double in the first example?

**Comment by hackhat** [comment]
Another example. If I change the game width.

Game width 400px:
![image](https://user-images.githubusercontent.com/11173732/50147670-b6472300-02f1-11e9-92fb-84c72c2dfb5e.png)

Game width 600px:

![image](https://user-images.githubusercontent.com/11173732/50147702-c4953f00-02f1-11e9-8b33-36f34cb59550.png)

**Comment by hackhat** [comment]
Related issue here https://github.com/photonstorm/phaser/issues/4139

I wonder when we bump the new version and deploy to npm?

**Comment by photonstorm** [comment]
It'll be released when it's ready. It's irrelevant how long ago the previous version was.

I'm happy render textures crop correctly now, but their internal camera doesn't allow it to be repositioned, which needs fixing. You can zoom and rotate the internal camera just fine, but not scroll it.

**Comment by photonstorm** [comment]
Ok, the internal RenderTexture camera viewport now works correctly. You can resize the camera viewport and it will update the internal crop rect accordingly. Changing the scroll factor still has no impact on game objects, but this is a different issue.

**Comment by photonstorm** [comment]
My mistake, scrolling the RT camera works perfectly, as long as you're rendering game objects to it. Plain texture frames won't take the camera into account, as they bypass it, which is fine.

**Comment by hackhat** [comment]
Ok, thanks.
