### ISSUE TITLE
TypeError: ArrayUtils.GetFirstElement is not a function

### ISSUE THREAD

**Issue by miran248** [photonstorm/phaser#4244]
## Version

* Phaser Version: v3.15.1-FB (WebGL | Web Audio) (default build)

* Operating system: macos v10.14.1

* Browser: chromium v70.0.3535.0

## Description

I've been using `Group` class as a pool of alive / dead objects but since i'm using multiple cameras in one scene I thought the `Container` might be a better choice, so I've tried it - replaced `getFirstDead` with `getFirst("active", false)` and got the following error:
```
Uncaught TypeError: ArrayUtils.GetFirstElement is not a function
    at Container.getFirst (Container.js:613)
    ...
```
It looks like `GetFirstElement`has been renamed to `GetFirst`.
Did a search on the repo and found only [two occurrences](https://github.com/photonstorm/phaser/search?q=GetFirstElement&unscoped_q=GetFirstElement) but not the source.

## Example Test Code

The following crashes:
```
const c = new Phaser.GameObjects.Container(scene);
...
c.getFirst("active", false); // throws an error
```

The following works: (taken from Container#getFirst)
```
Phaser.Utils.Array.GetFirst(c.list, "active", false);
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
