### ISSUE TITLE
Spritesheet from RenderTexture

### ISSUE THREAD

**Issue by jestarray** [photonstorm/phaser#4246]
I have 2 body part sprite sheets, a head and a body, and I merge those together using RenderTexture so it can be a singular sprite, but then it is no longer a spritesheet as now it only has 1 frame.
```javascript
rt.draw(head, x, y);
rt.draw(body, x, y);
//on that note, is there a way to add without using draw?
```

 I can't find a way to create a spriteSheet from an already existing texture. ```this.textures.addSpriteSheet()``` takes in an HTMLImageElement , of which i cannot find a reference to on the texture, and ```this.textures.addSpriteSheetFromAtlas()``` requires an atlas.

On that note, I am aware there is a `textures.add()` but I can't seem to get it working correctly. I'm doing `rt.draw(["spritesheetKey1", "spritesheetKey2"])` but when it seems i can't slice any further than the first frame. Do i have to input them as images ?

**Comment by photonstorm** [comment]
For this, specifically, don't use a Render Texture. A CanvasTexture would make a lot more sense.

You don't need to parse anything. Just create a texture and then use `Texture.add` to add frames to it. Like this example: http://labs.phaser.io/view.html?src=src%5Canimation%5Ccreate%20animation%20from%20canvas%20texture.js&v=dev
