### ISSUE TITLE
Typo in function chooseContext

### ISSUE THREAD

**Issue by yadurajiv** [photonstorm/phaser#4248]
## Version

* Phaser Version: v3.15.1-FB

* Operating system: Windows 10

* Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

## Description

There is a typo in the function chooseContext in https://github.com/photonstorm/phaser/blob/master/plugins/fbinstant/src/FacebookInstantGamesPlugin.js#L1325 

contextChoseAsync should be contextChooseAsync

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
