### ISSUE TITLE
Draggable game objects issue in concurrent active scenes

### ISSUE THREAD

**Issue by probt** [photonstorm/phaser#4249]
## Version

* Phaser Version: v3.15.1-FB

* Operating system: MacOS 10.14.2

* Browser: Chrome, FF, Safari

## Description

I’ve come across an issue of having a game object’s drag events stop emitting when I have two scenes running actively, with draggable objects set up in each scene. Specifically, the issue occurs in the lower depth scene.  I’m not sure if this a bug or not, or if I’m doing something wrong in my setup.

## Example Test Code

https://codepen.io/paulrbt/pen/ebZRKy

## Additional Information

I was testing a new button class, where the button is interactive as draggable and as a dropZone, to enable animation/tweening when dragging the pointer on and off the button. All works well in the top scene, but for any similar game object set up in the lower scene, the drag events only fire once then stop. In looking at the input for the game object, it looks like the dragState is getting stuck at 2.

**Comment by photonstorm** [comment]
Have replicated this locally and confirmed bug.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
