### ISSUE TITLE
Error when iframing Phaser + Webgl in Brave broswser

### ISSUE THREAD

**Issue by EddieOne** [photonstorm/phaser#4251]
## Version
Phaser v3.15.1-FB
* Phaser Version:
Phaser v3.15.1-FB
* Operating system:
Windows 10!
* Browser:
Brave

## Description

project.bundle.js:64510 Uncaught Error: Failed to compile Vertex Shader:

## Example Test Code
Put an iframe somewhere without https
<iframe src="http://localhost:8000"></iframe>

Start https://github.com/photonstorm/phaser3-project-template

**Comment by photonstorm** [comment]
This is almost certainly a problem with how Brave works. If it does the same thing when deployed to a proper web server (i.e. not running over localhost) then there's nothing we can do about it I'm afraid. It's just Brave being overly paranoid and protective. Which is its mantra, really.

**Comment by EddieOne** [comment]
Yeah, it might be blocked to avoid fingerprinting, I'm not sure. Should I open an issue on their repo?

Here's a public test https://jsfiddle.net/pdbjo563/

**Comment by Zelrain** [comment]
My webgl site fails to compile the shader when run in an iframe in brave. It works outside the iframe in brave, and works on chrome/firefox in the iframe just fine.

**Comment by EddieOne** [comment]
I did noticed this when creating the issue. 

Does the issue resolve itself when disabling Brave Shields? Yes

Showing a message for Brave users, maybe that's possible. Hopefully this is not the best solution.

Let's close this issue for now.
