### ISSUE TITLE
When Restarting Scene Gameobject Data Throws Error

### ISSUE THREAD

**Issue by codingphasedotcom** [photonstorm/phaser#4253]
**ISSUE**
I have 2 gameobjects one is a box that holds data "box_number 6" another is a button that restart the scene. When the scene starts everything works good I click the box and console.logs "box_number: 6", but if I restart the scene I get an error "Cannot read property 'get' of null". Now whats weird even though I have that error showing up when I click the button I get right box_number 6. I'm guessing this might be something to do with the lifecycle of the scene.

**VERSION 3.15.1**

**REPRODUCE**

```javascript
export default class Level2 extends Phaser.Scene {
	constructor() {
		super({
			key: 'Level2'
		});
	}

	preload() {
		this.load.image('box', '/assets/sprites/box_blank.png');
		this.load.image('button', '/assets/sprites/box_ored.png');
	}

	create() {
		this.box = this.add
			.image(116, 144, 'box')
			.setOrigin(0, 0)
			.setInteractive()
			.setDataEnabled()
			.data.set('box_number', 6);

		this.button = this.add
			.image(0, 144, 'button')
			.setOrigin(0, 0)
			.setInteractive();

		this.button.on('pointerdown', (pointer, localX, localY, event) => {
			this.scene.restart();
		});
		this.showData();
	}
	showData() {
		this.input.on('gameobjectdown', (pointer, gameObject) => {
			if (gameObject.data.get('box_number') == 6) {
				console.log(`BoxNumber: ${gameObject.data.get('box_number')}`);
			}
		});
	}
	update() {}
}

```
**ERROR**
```javascript
Level2.js:33 Uncaught TypeError: Cannot read property 'get' of null
    at initialize.input.on (Level2.js:33)
    at initialize.h.emit (phaser.min.js:1)
    at initialize.processDownEvents (phaser.min.js:1)
    at initialize.update (phaser.min.js:1)
    at initialize.h.emit (phaser.min.js:1)
    at initialize.step (phaser.min.js:1)
    at initialize.update (phaser.min.js:1)
    at initialize.step (phaser.min.js:1)
    at initialize.step (phaser.min.js:1)
    at e (phaser.min.js:1)
```

**Comment by samme** [comment]
I think you're getting an error because 'gameobjectdown' is triggered for the button click, and the button has a null `data` property.

**Comment by codingphasedotcom** [comment]
the thing is that button shouldn't be triggered because I'm not clicking it. must be a bug

**Comment by photonstorm** [comment]
`gameobjectdown` will fire for _any_ Game Object clicked on. But, in the `showData` handler you don't check if `gameObject` actually has a data component or not, you just read from it directly. So if you click your box, it works because you enabled it for data. If you click the button, it throws that error because it has no data on it.

If I change your showData handler to include this, it works fine with no errors:

```
if (gameObject.data && gameObject.data.get('box_number') == 6)
```

Tested against master branch 3.16 and 3.15.

Also, be aware that in the code above `this.box` isn't an Image, it's a DataManager, because that is what `data.set` returns.

**Comment by codingphasedotcom** [comment]
Thanks Richard got it!
