### ISSUE TITLE
MatterJS imageStack floating box issue in Phaser 3

### ISSUE THREAD

**Issue by PeterTucker** [photonstorm/phaser#4254]
## Version

* Phaser Version: 3.15.1

* Operating system: MacOS Sierra & Windows 10

* Browser: Chrome

## Description

When an image stack is chained, the bounding boxes of the chained images start floating upwards for no apparent reason.

## Example Test Code

Codepen of issue: [https://codepen.io/petertucker/pen/ebWZjV](https://codepen.io/petertucker/pen/ebWZjV)

**Comment by PeterTucker** [comment]
Note for anyone else who runs into this problem. In the meantime, I'm using this example as a substitute which uses joints, as opposed to the chain functionality:
[http://labs.phaser.io/edit.html?src=src\physics\matterjs\chain.js](http://labs.phaser.io/edit.html?src=src\physics\matterjs\chain.js)

**Comment by photonstorm** [comment]
Tested this out in 'native' Matter.js and with these settings, it does the same there, so it appears to just be the combination of Matter chains with stiffness etc.
