### ISSUE TITLE
Calling super() on Phaser.Physics.Matter.Sprite creates body with empty texture

### ISSUE THREAD

**Issue by marwan38** [photonstorm/phaser#4255]
## Version

* Phaser Version: v3.16.0 Beta 4-FB

* Operating system: Windows 10

* Browser:

## Description

Creating a custom class that extends `Phaser.Physics.Matter.Sprite` does not render texture. The debug boundaries still show, which also react to key inputs (move left, right.. etc)

## Example Test Code

```
class Player extends Phaser.Physics.Matter.Sprite {
    constructor(scene, x, y, key, frame) {
        super(scene.matter.world, x, y, key, frame)
    }
}

new Player(scene, x, y, texture_key, frame);
```

EDIT:
Can be replicated using this example
https://codesandbox.io/s/j44k3844j3

Extend the class with `Phaser.Physics.Matter.Sprite` and call super() instead of `this.sprite = scene.matter.add.sprite(0, 0, "player", 0);` and finally `this.sprite = this` to not break the code

## Additional Information
[View screenshot of empty bodies](https://i.ibb.co/c8SsZTL/invisible-sprite.jpg)

**Comment by antoine10245** [comment]
try to add the sprite to the scene after initialising `Player`
`    this.scene.add.existing(this);
`

**Comment by photonstorm** [comment]
The Sprite needs adding to the display list in order to render. It has a texture, it's just not on the display list in your example.

**Comment by dondon67** [comment]
contact@innoagram.comcontact@innoagram.comEmail
Sent from Yahoo Mail on Android 
 
  On Thu, Jan 24, 2019 at 4:08 AM, Richard Davey<notifications@github.com> wrote:   

Closed #4255.

**Comment by Wambosa** [comment]
for anyone else encountering this issue

```
export default class MyClass extends Phaser.Physics.Matter.Sprite {
  constructor({scene, x, y, texture, frame, options}) {
    super(scene.matter.world, x, y, texture, frame, options)
    scene.add.existing(this)
  }
```

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/how-to-create-a-custom-matterjs-sprite-class-with-phaser-3/6594/1

**Comment by truehazker** [comment]
Here is the TypeScript  example, just in case ;)


```typescript
export default class Player extends Phaser.Physics.Matter.Sprite {
    constructor(scene: Phaser.Scene, x: number, y: number, texture: string, frame?: number, options?: Phaser.Types.Physics.Matter.MatterBodyConfig) {
        super(scene.matter.world, x, y, texture, frame, options)
        scene.add.existing(this)
    }
}
```
