### ISSUE TITLE
processDomCallbacks not emptying 'once' array

### ISSUE THREAD

**Issue by iArePJ** [photonstorm/phaser#4257]
## Version

* Phaser Version: 3.16.0 Beta 4

* Operating system: Windows 10

* Browser: Chrome

## Description
I'm using the addUpCallback to open a new window using a Phaser "button". The upOnce callback is being added to the domCallbacks array each time I click the button even though it should be emptying the array so that it only happens once. 

Looking through the source code I noticed you empty the array in line 888:
https://github.com/photonstorm/phaser/blob/master/src/input/InputManager.js#L888
I logged it and it empties the array, but when I check the InputManager in-game the callback is still in the array.

In the example code, it will open google just fine the first time, but then the second time it will open 2 and then 3 and so on.

## Example Test Code
```Javascript
this.add.image(40, 80, 'patchNotes')
            .setOrigin(0)
            .setInteractive({useHandCursor: true})
            .on('pointerdown', () => {
                game.input.addUpCallback(() => {
                    window.open('https://www.google.com.com/docs');
                }, true)
            });
```

## Additional Information

I changed
```
once = [];
```
to 
```
this.domCallbacks.upOnce = [];
this.domCallbacks.downOnce = [];
this.domCallbacks.moveOnce = [];
```
and it works as intended.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
