### ISSUE TITLE
Matter Object toJson() throws exception

### ISSUE THREAD

**Issue by svdragster** [photonstorm/phaser#4263]
So far no solution on my forum thread: https://phaser.discourse.group/t/matterjs-and-tojson/443

Calling toJson() on MatterJS Objects results in the exception:
```
Uncaught TypeError: Cannot read property ‘position’ of undefined
at MatterSprite.get [as x] (phaser.js:166821)
at Object.ToJSON (phaser.js:94119)
at MatterSprite.toJSON (phaser.js:11382)
at JSON.stringify ()
```

**Comment by photonstorm** [comment]
This works fine for me in both 3.15 and master branch:

```
var block = this.matter.add.sprite(400, 300, 'block');

var data = block.toJSON();

console.log(data);
```

**Comment by svdragster** [comment]
It seems to happen when the Scene that the sprite is added in has been stopped. I'm saving all game objects in the scene when switching to the main menu. Calling toJSON() _before_ stopping the current scene seems to work fine. Is that intended behaviour?

**Comment by photonstorm** [comment]
That's because the Sprite no longer has a physics body, as the Scene has been stopped and the world cleared, so it can't read the x/y position from the body. This is too far outside the bounds of acceptable use to warrant changing I'm afraid.
