### ISSUE TITLE
3.15.0 Scene restarts on exception

### ISSUE THREAD

**Issue by galarant** [photonstorm/phaser#4264]
## Version

* Phaser Version:
Bug appears in versions >= 3.15.0

* Operating system:
Windows 10, not tested in other OS

* Browser:
Google Chrome 71.0.3578.98, not tested in other browsers

## Description
It seems that under certain conditions Scenes will continually restart in an infinite loop when an exception is raised. Steps to reproduce:

1. Create two `Scene` classes (e.g. `BootScene` and `LoadScene`) which both inherit from `Phaser.Scene`

2. Start the game on the `BootScene` and then start the `LoadScene` from the `BootScene`

3. Raise an exception somewhere in `LoadScene`. Either in `preload` or `create`, it doesn't seem to matter. I did this for example by calling a scene function that doesn't exist, `this.foobar()`

In Phaser 3.15.0 and above this will raise the expected exception, however the raise will be repeated over and over again in an infinite loop. It seems that the scene is continually trying to restart itself on the exception. Testing this in 3.14.0 and below yields the desired behavior, i.e. the app raises the exception once and then halts.

## Example Test Code
https://jsfiddle.net/billnreed/zmfovn46/1/

## Additional Information

Please see the forum post https://phaser.discourse.group/t/3-15-0-bug-scene-restarts-on-exception/514  for additional details and discussion.

**Comment by photonstorm** [comment]
Sorry for leaving this issue open for so long, it was actually fixed shortly after this release in v3.16.0, but I forgot to close this issue with those details.
