### ISSUE TITLE
Add a tintAdd method for additive tints to lighten images

### ISSUE THREAD

**Issue by Telokis** [photonstorm/phaser#4266]
After looking for a way to "brighten" my sprites, I noticed the methods `setTint` and `setTintFill`.

I immediately tried to do `sprite.setTint(0xFFFFFF)` hoping this would make my sprite "more white" but nothing changed.  
After looking around on the internet, I stumbled on a [forum post](http://www.html5gamedevs.com/topic/18254-spritetint-white-color-problem/) reporting this issue and you saying it's an additive process.  
After trying to find alternative, I began to be quite annoyed to not be able to do such a simple thing and decided to look through the code. I knew that it would be as simple as "adding" white to the color of my texture.  

I finally found the fragment shaders and, after reading and understanding it carefully, I began to work toward a solution which would be to do something like this:

```js
  if (outTintEffect == 3.0)
  {
    texel.rgb += outTint.rgb;
  }
```

That works perfectly but it does not care about alpha whatsoever.  
Is that something you would consider acceptable for Phaser?

PS: I used [this](http://shdr.bkcore.com/#1/hVTLbtswEPyVrU5SIsh5nWL4lD7QAn0ALXqpi4CWVzIDiRRIKrES5N+7pEhJVmwUsGxaszu7nFnyJdrKvK1RGB3d/okahTnXXArY8XLXQFFJZpZr0QpeSFX3/8HwGicvHzG/AoVaVq2hVEIemeq4KC1yDcUPqflR4Btls4peE4D5DZRoPoumNXeykipO1uJlLYCYTauETbmJfUoKl9lFsoTFAr602gADg9qsxetAZeQnxTqdswpj3idDbmkDa78T9oiKlQgriB2aKTjv47JyWG0SWMB1drGcd+OzU3i7cP1NG3JU/Hnspgz9pXC0QV8oHuLgzAcMvJJvoWZcDFKRHr92XAN9zA77cOhkC09MkG0SWNNUnY+kqjZoHYXW1hFog00GP3eyraCtyGdmsOpggyTxYDdTmaXoWybpnBa0Ybfr8StxxvqmkMqRs1CQPHbavLQev2OCXtRIsKydm3vavNUTwsTQRhjFCEM7GcvzYVyoj9n4OLtCAUkuKCfBqGfBlTa3A9cIrGbjEzgPdyQOpdt0oHlN8kJtlaOFbdsqPBD73Cdudg7YouYKtxMtDkZl+701VrPVODyToclDN/28c2GCFfZwOT/8kwx2wHCAhflQFJjbnCs/2fbhBcRT0KGJRdx8wby3TJUbOF85Qrt2RK/2CyuNR+gu/0+3gprv4yNIOpRJ3ySy5LD06Rpw5mUKZHSu3JJ5/pHK+/VeCnxn12V1/5HmN8zbjLg/llF68hJlxii+aQ32118zXoszRIR7MRw5Oobh7VdGoftD7AZqucXqN8en43Cj5AMZQMUG/MRNfPLmPnbd+DSSou/NTui0S1K2/9sr6gaVdm0dPuyXAp0lQZLpwIYeKIvgbN89L70XU2S2QSKkYOtI9DeNXLXotv/VC90+MyHw3rqTPejo9R8=) online shader editor to test things out.

**Comment by Telokis** [comment]
@photonstorm Would it be possible to get some feedback on this idea, please? It's something I'd really like to have. (Along with an outline/glow effect, even if not related)

**Comment by photonstorm** [comment]
I'm glad you found a solution and you should roll this into your own custom WebGL pipeline so you can use it. It's not something I'm willing to add into the standard shader for several reasons, the first being branching, the second all of the extra tint methods required to handle it. Alternatively, you could just edit the default shader and then you wouldn't even need your own pipeline (but you would need your own build of Phaser)

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/color-adjustment/8399/4
