### ISSUE TITLE
Phaser.Display.Color darken and lighten methods not working

### ISSUE THREAD

**Issue by halilcakar** [photonstorm/phaser#4269]
## Version

* Phaser Version: 3.15.1

* Operating system: Windows 10

* Browser: Google Chrome v71.0.3578.98

## Description

Phaser.Display.Color's darken and lighten methods changes `this.v` property which is declared as `this._v` in the constructor. Possible typo mistake.

## Example Test Code

Please check on the constructor and darken, lighten methods on ["Color"](https://github.com/photonstorm/phaser/blob/master/src/display/color/Color.js)

**Comment by photonstorm** [comment]
`this.v` is a setter for the `this._v` property and then further updates the other internal HSV values, so changing it is correct.
