### ISSUE TITLE
The 'pointerout' and 'pointerover' events are not sent for the whole scene/game

### ISSUE THREAD

**Issue by BigZaphod** [photonstorm/phaser#4270]
There are `pointerout` and `pointerover` events but it seems they are only triggered for interactive game objects and do not apply to the whole scene/game. I wanted to be able to track when the pointer enter/left the whole game scene, but that doesn't work - unlike `pointermove` and `pointerup` and `pointerdown` which all trigger even if the pointer moves or clicks over non-interactive game objects (or no gameobjet at all).

```
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
    }
};
var game = new Phaser.Game(config);

function preload () {
    this.load.image('block', 'assets/sprites/block.png');
}

function create () {
    var image = this.add.image(200, 300, 'block');
    image.alpha = 0.5;

    // if this line is commented out, the pointerout/pointerover events
    // are never sent - but shouldn't they also be sent for the scene itself?
    // image.setInteractive();

    this.input.on('pointerout', function(pointer) {
        image.alpha = 0.5;
    })

    this.input.on('pointerover', function(pointer) {
        image.alpha = 1;
    })
}
```

Phaser Version: 3.15.1
macOS/Safari (and Chrome)

**Comment by photonstorm** [comment]
The new `gameout` and `gameover` events are what should be used here. `pointerout` is a Game Object level event, rather than a Scene, Camera or Game level event.
