### ISSUE TITLE
Draggable objects break when restarting a scene

### ISSUE THREAD

**Issue by iArePJ** [photonstorm/phaser#4278]
## Version

* Phaser Version: 3.16.10 Beta 4

* Operating system: Windows 10

* Browser: Chrome

## Description

Dragging an object works fine the first time the scene is created, but if you stop a scene and then start it again, you are no longer able to drag the object. I have tried both this.input.on() and gameObject.on() drag events.

## Example Test Code

```Javascript
class Drag {
    create() {
        let image = this.add.image(50, 50, 'yes')
            .setInteractive();

        this.input.setDraggable(image);

        image.on('drag', function (pointer, x, y) {
            this.x = x;
            this.y = y;
        });
    }
}
```

## Additional Information

Fix: 
https://github.com/photonstorm/phaser/blob/master/src/input/InputPlugin.js#L2288
Change this line to 
```Javascript
this._dragState = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ];
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
