### ISSUE TITLE
Matterjs with atlas texture and shape json

### ISSUE THREAD

**Issue by Tasades** [photonstorm/phaser#4282]
## Version

* Phaser Version: 3.15.1

* Operating system: Windows 10

## Description

I tried to use a texture atlas with pivot points and matterjs with a shape json (created by TextureLoader and PhysicsEditor). But the pivot point is not recognized by matterjs and the collision shape is not aligned with the rendered sprite. This is important if I use a sprite with different sized frames. How can I change the offset for my vertices? Did I miss something? Thanks in advanced.

![trex-texture](https://user-images.githubusercontent.com/10619154/50744419-558d7500-1223-11e9-8728-964cbaa7c3f6.png)

![trex-texture](https://user-images.githubusercontent.com/10619154/50744422-60480a00-1223-11e9-9bf8-ddb3695af35e.png)

[images.zip](https://github.com/photonstorm/phaser/files/2731117/images.zip)

## Example Test Code
```
export class TrexGameMatterScene extends Phaser.Scene {
    private trex: Phaser.Physics.Matter.Sprite;
    private cursors: Phaser.Input.Keyboard.CursorKeys;
    constructor() {
        super({
            key: "MainScene"
        });
    }

    preload(): void {
        this.load.atlas('trex-game', 'images/trex-texture.png', 'images/trex.json');
        this.load.json('trex-shapes', 'images/trex.matter.json');
    }

    create(): void {
        const shapes = this.cache.json.get('trex-shapes');
        this.matter.world.setBounds(0, 0, this.game.config.width as number, this.game.config.height as number);
        this.trex = this.matter.add.sprite(200, 75, 'trex-game', 'trex-0.png', {
            shape: shapes['trex-0']
        });

        this.trex.setStatic(true);
        const frameNames = this.anims.generateFrameNames('trex-game', {
            start: 1, end: 2, zeroPad: 0,
            prefix: 'trex-', suffix: '.png'
        });

        this.anims.create({key: 'walk', frames: frameNames, frameRate: 10, repeat: -1});

        const duckFrames = this.anims.generateFrameNames('trex-game', {
            start: 3, end: 4, zeroPad: 0,
            prefix: 'trex-', suffix: '.png'
        });
        this.anims.create({key: 'duck', frames: duckFrames, frameRate: 10, repeat: -1});

        this.cursors = this.input.keyboard.createCursorKeys();
    }

    update(time, delta): void {
        if (this.cursors.down.isDown) {
            this.trex.play('duck', true);
        } else {
            this.trex.play('walk', true);
        }
    }
}

const config: GameConfig = {
    width: 400,
    height: 150,
    type: Phaser.AUTO,
    backgroundColor: '#dddddd',
    scene: TrexGameMatterScene,
    physics: {
        default: 'matter',
        // arcade: {
        //     gravity: {y: 300},
        //     debug: true
        // },
        matter: {
            debug: true
        }
    },
};


class SimpleGame extends Phaser.Game {
    constructor(config: GameConfig) {
        super(config);
    }
}



window.onload = () => {
    var game = new SimpleGame(config);
};
```

**Comment by hexus** [comment]
This appears to be a technical support question rather than a bug report. I suggest reaching out to one of Phaser's many community channels, as mentioned in the Bug Report template you will have seen when submitting this issue:

> 2. This repo should not be used for technical support. If you're struggling to use Phaser then post your question to the [forum](https://phaser.discourse.group/), [Slack](https://phaser.io/community/slack) or [Discord](https://phaser.io/community/discord) channels. GitHub Issues are for bugs and feature requests only.

That said, this seems like an issue that will be covered by this PhysicsEditor tutorial (I also mentioned this in #5007 which seems like the same issue):

https://www.codeandweb.com/physicseditor/tutorials/how-to-create-physics-shapes-for-phaser-3-and-matterjs
