### ISSUE TITLE
Texture Manager Spritesheet frameTotal reports 1 too many frames.

### ISSUE THREAD

**Issue by ciabaros** [photonstorm/phaser#4285]
## Version

* Phaser Version: 3.15.1

* Operating system: Windows 10

* Browser:

## Description

In the Texture Manager, when you look up a spritesheet (e.g. scene.textures.get("<key>")), its frameTotal property shows 1 too many frames.

## Example Test Code

`
// 1. Preload any multi-frame spritesheet with key "abc"

// 2. Compare frameTotal (Texture Manager) vs. length of generateFrameNumbers (Animation Manager)

console.log( "Frames:", this.textures.get( 'abc' ).frameTotal, "VS", this.anims.generateFrameNumbers( 'abc' ).length );

// Notice console output above will show 2 different numbers, off by 1 (this.textures.get( ) version is wrong)
`

## Additional Information

I'm guessing that the Texture Manager (this.textures.get( 'abc' ).frameTotal) reports one too many frames, because you are counting the number of own keys in the frames property (e.g. Object.keys( this.textures.get( 'abc' ).frames ).length ), and this object includes a __BASE property, along with all the valid frames.

**Comment by photonstorm** [comment]
I'm going to leave it like this, because the `__BASE` frame is actually a frame, so it should count towards the total.

**Comment by ciabaros** [comment]
Even if __BASE is technically a frame type, it has no relevance to why anytime would be counting or retrieving frames of this object. It's like saying that every array should count it's length as an item. Consider if you think there is any developer that would expect those 2 numbers to be different because of some unrelated inheritance technicality. That's why we count own properties of an object in 99% of use cases. Hope this helps to clear up why this is still an issue.

**Comment by photonstorm** [comment]
By this definition, a texture created from a single image (not a sprite sheet) would have a frame total of zero, which is incorrect. I have updated the jsdocs in the file to clarify this, but I'm not changing the value.
