### ISSUE TITLE
Arcade Physics step callback

### ISSUE THREAD

**Issue by fant0m** [photonstorm/phaser#4289]
If I understand Phaser's arcade physics correctly it currently uses fixed time-step. Thus the player is receiving same number of physics updates on different fps / hz. Am I right?

Is it possible to provide some kind of callback function after `step` method is applied? Currently I'm setting player's velocity inside `update` method, but I think I should do that inside/after `step` method.

I'm building MMO real-time game (so the server has also fixed time-step) and I need to inform the server about player movement. If send that information inside `update` method, multiple physics (`step`) updates might occur between two `update` calls. So the player might move by 5 fields on the client and the server will have information just about 1 movement. That's why I need to call server on each player position update.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
