### ISSUE TITLE
Align 'justified' in text gameobject

### ISSUE THREAD

**Issue by andrewbaranov** [photonstorm/phaser#4291]
## Version

* Phaser Version: last Phaser 3 Sandbox

* Operating system: Windows 10 64 bit

* Browser: Chrome 71.0.3578.98 (64 bit)

## Description

Justified style not work in Text GameObject.
In Phaser docs:
https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Text.html
setAlign(align)
Set the text alignment.
Expects values like 'left', 'right', 'center' or 'justified'.

## Example Test Code

1. Open Phaser3 labs
http://labs.phaser.io/edit.html?src=src/game%20objects/text/static/multi%20line%20text%20with%20alignment.js
2. Replace text style with    align: 'justified'
3. Align becomes like align left
Expected text bocomes justified

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by andrewbaranov** [comment]
Works perfect.
Usage: set text style { fontFamily: 'Arial', color: '#00ff00', align: 'justify' }
Pay attention for align: '**justify**' NOT '**justified**'
