### ISSUE TITLE
easeParams do not work when tweening multiple properties

### ISSUE THREAD

**Issue by willblackmore** [photonstorm/phaser#4292]
## Version
* Phaser Version: v3.15.1-FB

## Description

When using the syntax for tweening multiple properties the `easeParams` option does not work.

## Example Test Code

This does not work:
```javascript
this.scene.tweens.add({
    targets: this,
    angle: {
        value: 90,
        duration: 200,
        ease: 'Elastic.easeOut',
        easeParams: [ .5, .5 ], // Ignored
    },
    y: {
        value: 100,
        ease: 'Cubic.easeOut',
        duration: 300,
    }
});
```

This works:
```javascript
this.scene.tweens.add({
    targets: this,
    angle: 90,
    duration: 200,
    ease: 'Elastic.easeOut',
    easeParams: [ .5, .5 ],
});

this.scene.tweens.add({
    targets: this,
    y: 100,
    duration: 300,
    ease: 'Cubic.easeOut',
});
```

**Comment by whynne** [comment]
I'm also having this issue.  Any luck finding a solution?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
