### ISSUE TITLE
setBlendMode getting called in a Zone object inside a Container (Canvas)

### ISSUE THREAD

**Issue by emanuel15** [photonstorm/phaser#4295]
## Version

* Phaser Version: v3.15.1

* Operating system: Ubuntu 18.04.1

* Browser: Firefox

## Description

This issue happens only in the Canvas renderer, if you add a zone inside a container an error will be raised: "TypeError: child.setBlendMode is not a function", this error points to gameobjects/container/ContainerCanvasRenderer.js

## Example Test Code

```javascript
var game = new Phaser.Game({
  type: Phaser.CANVAS,
  width: 640,
  height: 480,
  scene: {
    preload: preload,
    create: create
  }
});

function preload() { }

function create() {
  var container = this.add.container(0, 0);
  var zone = this.add.zone(0, 0, 100, 100);
  
  container.add(zone);
}
```

## Additional Information

I've managed to fix this problem by applying the same logic used in ContainerWebGLRenderer.js, but I'm not sure if this is the best way to fix this error. It looks like Zone is missing the BlendMode component as well since it has the blendMode property but has no setBlendMode function.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by emanuel15** [comment]
It's working fine now, thank you.
