### ISSUE TITLE
Optimize setAlpha by checking if is the same value

### ISSUE THREAD

**Issue by hackhat** [photonstorm/phaser#4296]
Hi!

Not sure if you checked but you could optimize the `setAlpha` method:

![image](https://user-images.githubusercontent.com/11173732/51082967-34a9b000-174c-11e9-980c-c6cee8e525bd.png)

as you can see from my performance report this method is wasting a lot of resources. Not sure if is possible to optimize or not but give it a try. 

![image](https://user-images.githubusercontent.com/11173732/51082978-5acf5000-174c-11e9-9db8-73b18d92a960.png)

For example, I wrapper the sprite in another game object so when you set the alpha it checks if is the same value and ignore. This increased my fps dramatically, so I guess you can apply this to the sprite as well.

**Comment by photonstorm** [comment]
The check would need to be `if (v !== this._alpha || v !== this._alphaTL || v !== this._alphaTR || v !== this._alphaBL || v !== this._alphaBR) { change alpha }` which is quite a conditional to have every time an alpha is changed. If it can be proven it will actually speed it up, I'll add it.

**Comment by hackhat** [comment]
You can do a quick one just for `this._alpha`. Maybe we could have a function `setOnlyAlpha` or something like that?

**Comment by photonstorm** [comment]
Looked at this again today but there's no way to do this without adding in 5 conditional checks or a new method. If you really need to optimize this away then you can modify the `GameObject._alpha` property directly, to avoid the setter entirely.
