### ISSUE TITLE
TileSprite in Headless mode crashes

### ISSUE THREAD

**Issue by clesquir** [photonstorm/phaser#4297]
## Version
* Phaser Version: v3.15.1-FB
* Operating system: OSX
* Browser: Chrome

## Description

Running a game with the HEADLESS mode renderer will crash if there is a tileSprite created in the game.

## Example Test Code

```
new Phaser.Game({
    type: Phaser.HEADLESS,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: function() {
            this.load.image('pic', 'assets/pics/baal-loader.png');
        },
        create: function() {
            this.add.tileSprite(0,0,400,300,'pic');
        }
    }
});
```

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
