### ISSUE TITLE
Improvement suggestion for EventEmitter-based classes docs

### ISSUE THREAD

**Issue by williamd1k0** [photonstorm/phaser#4300]
Hi, I'm using Phaser 3 in a job for the first time but I'm having some issues when I need to look for some object events.

I'm a Godot Engine user. There all events (signals) are documented, so it's very easy to find the event names.

Doc example: https://docs.godotengine.org/en/3.0/classes/class_node.html#signals

It would be really useful if there was a straightforward way to find the event names.

**Comment by photonstorm** [comment]
Work on doing this has now been completed and will be part of the 3.16 release. Every single event is now fully namespaced, exposed in the docs and listed against the methods that dispatch it.

![image](https://user-images.githubusercontent.com/164476/51397810-ecb6ce80-1b39-11e9-9150-61600ae670f6.png)

**Comment by williamd1k0** [comment]
Thanks! 💜
