### ISSUE TITLE
Load tileset from atlas

### ISSUE THREAD

**Issue by jestarray** [photonstorm/phaser#4302]
closed here but not sure what the solution is: https://github.com/photonstorm/phaser/issues/3415

https://phaser.discourse.group/t/loading-tileset-from-atlas/811

"I have a texture atlas that packs together all my tilesets(10 of them at the moment*), and I need to load them into Phaser TileSet so I can use it to generate static and dynamic layers. Seems like there is no frame option on .addTilesetImage and .createStaticLayer"

**Comment by photonstorm** [comment]
There is no solution, this has never been possible.

**Comment by jestarray** [comment]
Seems like it shouldn't be too hard to implement ? Just adjust `tileset.updateTileData()` to take the frame offset of where to start slicing from.

**Comment by photonstorm** [comment]
Go on then.

**Comment by photonstorm** [comment]
Make sure it works in an atlas where the frames are trimmed (i.e. in Texture Packer when you've got trim option turned on + potentially padding and margin). For example, if you had a tileset where maybe the top row of tiles didn't fill the tile size, it would get vertically trimmed, and that is when things start going awry.

**Comment by jestarray** [comment]
Yeah, it doesn't seem to work if trimmed. I don't know how to add back the trimmed transparent pixels though, either way, there's little point to trim entire tile sheets.

**Comment by Cirras** [comment]
Look at the SpriteSheetFromAtlas parser for an example of how to deal with getting trimmed frames from an atlas.

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
