### ISSUE TITLE
Game.destroy() throws an error in React

### ISSUE THREAD

**Issue by cztflove** [photonstorm/phaser#4305]
## Version
* Phaser Version:3.11.0
* Operating system: OSX
* Browser: Chrome

## Description
I want to destroy the Game instance when the React Component is going to unmount 
but it throws an error like this:
ArcadePhysics.js:472 Uncaught TypeError: Cannot read property 'update' of null
    at ArcadePhysics.shutdown (ArcadePhysics.js:472)
    at ArcadePhysics.destroy (ArcadePhysics.js:489)
    at EventEmitter.emit (index.js:214)
    at Systems.destroy (Systems.js:591)
    at SceneManager.destroy (SceneManager.js:1349)
    at Game.runDestroy (Game.js:603)
    at Game.step (Game.js:427)
    at TimeStep.step (TimeStep.js:514)
    at step (RequestAnimationFrame.js:98)

## Example Test Code
```
class RedpacketPlay extends Component {
  componentDidMount() {
    this.game = new Phaser.Game({
      type: Phaser.AUTO,
      parent: 'canvas'
    });
  }
  componentWillUnmount() {
    this.game.destroy();
    this.game = null;
  }
}
```

**Comment by photonstorm** [comment]
Check this against the master branch please, 3.11 is a really old version.

**Comment by cztflove** [comment]
> Check this against the master branch please, 3.11 is a really old version.

I want upgrade to the new version, but zoom in GameConfig can't work above 3.11,and I don't find out how to manage scaling in the new version.
The example code below can't resolve my requirement
Can you give me some help so that I can upgrade to 3.15, Thanks a lot
```
var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    scale: {
        width: 750,
        height: 1336,
        scale: 'SHOW_ALL'
    },
    ...
};
```

**Comment by jaszczur171** [comment]
I had some problems dealing with scaling as well. I have just got back to Phaser after years away from it and came up with following solution. It might not work for you, but you might be able to adapt it for your needs. In my case I just needed to be able to work with virtual resolution and letterbox the canvas as the scale of the window changed.

https://gist.github.com/jaszczur171/86036dc29dcb6ac9bfdb5c5c014c6727

Hope this helps you in any way.

**Comment by cztflove** [comment]
> I had some problems dealing with scaling as well. I have just got back to Phaser after years away from it and came up with following solution. It might not work for you, but you might be able to adapt it for your needs. In my case I just needed to be able to work with virtual resolution and letterbox the canvas as the scale of the window changed.
> 
> https://gist.github.com/jaszczur171/86036dc29dcb6ac9bfdb5c5c014c6727
> 
> Hope this helps. I'm on 3.15 and works like a charm.

Great thanks for your reply, but the link seems to have some problems, I can't open it

**Comment by photonstorm** [comment]
Closing this issue due to its age. For those coming here after the event, you can find a nice guide on integrating Phaser 3 with React here: https://medium.com/@Tnodes/integrating-react-and-phaser-3-tutorial-eb96717d4a9d
