### ISSUE TITLE
how to disable ScaleManager for newest dev version?

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#4309]
this ScaleManager deals with a lot of HTML features, create div, insert / append dom, calculate boudning box of a container etc...

but our environment does not have HTML.....

this actually is not a bug so I have to post a feature request.

**Comment by jcyuan** [comment]
I think there is no option in the gameconfig, I have tried to set scaleMode in it with noScale, but the scaleManager is still used while booting.

**Comment by jcyuan** [comment]
BTW: `config.customEnvironment`   great one :smile:   thanks!

**Comment by jcyuan** [comment]
![image](https://user-images.githubusercontent.com/850854/51612895-4d407400-1f5d-11e9-8b49-0dbbfb03f310.png)
 error is in `getParentBounds` method

**Comment by photonstorm** [comment]
Perhaps worth checking latest commit as I've changed the way parents are handled quite a bit.

**Comment by jcyuan** [comment]
> Perhaps worth checking latest commit as I've changed the way parents are handled quite a bit.

got it, I'll check it again.

**Comment by jcyuan** [comment]
@photonstorm thanks

but new problem:

![image](https://user-images.githubusercontent.com/850854/51675035-791b3280-200d-11e9-948e-b7e51b7ad893.png)

Fileprototype..onLoad `responseURL` is not supported... :sob: 

others all passed, thanks man.

and another strange thing, in this version, I tested on both PC and our special environment, on PC all are ok, but on platform, the update delta becomes vary small, normally it should be say 100ms, but on the platform it's around 0.1ms... I can't figure out why.

**Comment by photonstorm** [comment]
hmm, nothing has changed re: the delta values in 3.16 at all! I'll look at that `responseURL` thing now

**Comment by jcyuan** [comment]
thanks a lot,, I'll double check to see what happened.

**Comment by jcyuan** [comment]
cool, thanks~
