### ISSUE TITLE
Readme.md tutorial points to dead link.

### ISSUE THREAD

**Issue by FractalBobz** [photonstorm/phaser#4312]
## Version
* Phaser Version: Live. Still there as of commit ebe4af217c2539ebe8e750b77e18d3ad89b33ff3

* Operating system: Windows 10 but affects all.

* Browser: N/A

## Description

Issue was found in the readme.md on github page, the section for first example, linked here:
https://github.com/photonstorm/phaser#create-your-first-phaser-3-example

The code all looks fine, but the source for the engine seems to be dead, when i tried to run the code I got
﻿
phaser-arcade-physics.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

Code looked correct to I took a look at
    <script src="https://labs.phaser.io/build/phaser-arcade-physics.min.js">

Browsing to labs.phaser.io I noticed that phaser-arcade-physics.min.js is not in the build folder.
Nor in fact is any of the assets for this source (that I could see)

## Example Test Code

<script src="https://labs.phaser.io/build/phaser-arcade-physics.min.js"> 

## Additional Information

I get the impression I just scrolled too far into the readme, but this is the first demo I saw on the site.
While trying to figure this out I also noticed that there is a new repo for examples, I'm going to check out some of those next but i had to open some kind of ticket when I didn't see any relating to this.

It's a long time since I've opened any bug reports, but this should be an easy win.
__thank you__

**Comment by photonstorm** [comment]
Ok scratch that, you meant in the actual README.md itself! (that took some deciphering)

It was removed from the labs, so I've updated the README code to reflect that. It is correct on the web site and in the gist the README links to, though. The asset paths are perfectly fine too.

Closing as fixed.

**Comment by FractalBobz** [comment]
Thanks very much! I figured it was old documentation or something. 
To clarify I just browsed to https://labs.phaser.io/build/ and couldn't see the file.
Glad to have been of some help because running into might be endgame for a total game engine newbie.
Have a **great** day.
