### ISSUE TITLE
SetTint doesn't work on chrome (Phaser3 only)

### ISSUE THREAD

**Issue by charmingny** [photonstorm/phaser#4314]
## Version

* Phaser Version:3

* Operating system:windows10

* Browser:chrome

## Description
It works on Firefox.  It doesn't work on Chrome even with Phaser 3 examples. it works on Firefox (both Phaser 2 and Phaser 3)

![download](https://user-images.githubusercontent.com/46999906/51682741-8a1c7180-2016-11e9-8454-ac66e56438e5.png)

**Comment by photonstorm** [comment]
It works fine in Chrome in WebGL. However, it _doesn't_ work in Canvas mode in any browser, which I'd guess is what you're testing it under. This isn't implemented and there are no current plans to add it.
