### ISSUE TITLE
Docs: Phaser.Tilemaps.Parsers.Tiled.{functions} do not exist

### ISSUE THREAD

**Issue by jestarray** [photonstorm/phaser#4318]
https://photonstorm.github.io/phaser3-docs/Phaser.Tilemaps.Parsers.Tiled.html
Using version: 3.16 RC1
The docs list a bunch of static functions that don't exist on `Phaser.Tilemaps.Parser.Tiled` namespace.

For example: 
```javascript
Phaser.Tilemaps.Parser.Tiled.ParseJSONTiled("mappy", jsonData, false);
// and all of Tiled.{staticFunction}() are missing and don't work. 
``` 
gives you:
![image](https://user-images.githubusercontent.com/34615798/51773692-7d465f00-20a4-11e9-953b-b1458c597b12.png)

where as
```javascript
Phaser.Tilemaps.Parser.Tiled.("mappy", jsonData, false); //works fine but according to generated type defs and docs, this isn't supposed to exist.
``` 

I'd like to fix the documentation and namespacing, but which direction? Should I change the docs to fit the code? Or make the code fit the docs?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
