### ISSUE TITLE
TilemapLayer.destroy() doesn't cleanup Tilemap layer name cache

### ISSUE THREAD

**Issue by APXEOLOG** [photonstorm/phaser#4319]
## Version
* Phaser Version: Phaser v3.15.1-FB (WebGL | Web Audio)
* Operating system: Windows 10

## Description
The only wat to remove specific TilemapLayer from the Tilemap is to call `TilemapLayer.destroy()`. While it removes the layer visually, it doesn't remove itself from the Tilemap.layers cache. Later you cannot add layer with the same name again ![Image](https://images-ext-2.discordapp.net/external/ogfWldHw05Lg0t_ATI8C9MJfxAxsAJ5gkrJyQ9v0yrw/https/i.imgur.com/M6iBFLk.png)

## Example Test Code
```
let map = this.make.tilemap({
      width: 10,
      height: 10,
      tileWidth: 32,
      tileHeight: 32
    });
let tileset = map.addTilesetImage("tiles", "tiles", 32, 32, 0, 2);
let layer = map.createBlankDynamicLayer('test', tileset, 0, 0);
layer.destroy()
map.createBlankDynamicLayer('test', tileset, 0, 0); <-- Error
```

## Additional Information
As a workaround i manually remove name when destroy layer
`Vue.delete(map.layers, map.getLayerIndexByName(layerName));`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
