### ISSUE TITLE
quad.colors.fill wrong RGB channel order 

### ISSUE THREAD

**Issue by charmingny** [photonstorm/phaser#4325]
## Version

* Phaser Version: 3.15.1

* Operating system: Windows10

* Browser: Chrome

## Description
 I try to color my quad. I was expecting RGB order. but result I am seeing is different. So, I changed some values to test and I found out quad.color.fill is using BGR order. Is it a bug?

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.
