### ISSUE TITLE
MultiAtlas with same texture name between different atlas

### ISSUE THREAD

**Issue by giviz** [photonstorm/phaser#4330]
Hi :)

Impacted version : last one

Issue is on line : https://github.com/photonstorm/phaser/blob/master/src/loader/filetypes/MultiAtlasFile.js#L120

Example to reproduce the bug is there : 
https://github.com/giviz/phaser3_test/blob/master/src/index.js

Basically, the loader use the texture name as the key to load the image file, but as multiple atlas can use the same texture name, that cause the issue.

**Comment by photonstorm** [comment]
Adding for clarity when I come to fix this: it's the duplicate texture _filename_ that is causing the issue.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
