### ISSUE TITLE
body.checkCollision.none

### ISSUE THREAD

**Issue by digitsensitive** [photonstorm/phaser#4331]
## Version
* Phaser Version:
v3.15.1

* Operating system:
macOS Mojave Version 10.14.2

* Browser:
Google Chrome Version 71.0.3578.98.

## Description
If `body.checkCollision.none` is set to true, the collision checks are still done, but it shouldn't.

Additionally the descriptions are contrary in `src/physics/arcade/StaticBody.js` and `src/physics/arcade/Body.js`:

You can set `checkCollision.none = false` to disable collision checks.
vs.
You can set `checkCollision.none = true` to disable collision checks.

## Example Test Code

I wouldn't know which code I have to add more here.

## Additional Information

I can make a PR if you have the same opinion regarding the problem.

**Comment by samme** [comment]
It [works as expected for me in v3.16.1](https://codepen.io/samme/pen/MLEeOZ?editors=0010).

**Comment by digitsensitive** [comment]
That is strange ... I tried it with v3.16.2 but it is still not working for me.

https://github.com/digitsensitive/phaser3-typescript/blob/9f72370045b86a6716a5a8ba7a6aa05deceabcaa/src/games/super-mario-land/objects/mario.ts#L216

**Comment by photonstorm** [comment]
Have re-tested and can confirm it's working as expected in 3.50 too. Test case below:

```js
var config = {
  type: Phaser.AUTO,
  width: 800,
  height: 600,
  parent: 'phaser-example',
  physics: {
    default: "arcade",
    arcade: {
      debug: true,
      gravity: { y: 200 }
    }
  },
  scene: {
    preload: preload,
    create: create
  }
};

var game = new Phaser.Game(config);

function preload() {
  this.load.image("block", "assets/sprites/block.png");
}

function create() {
  var group = this.physics.add.group({
    bounceX: 1,
    bounceY: 1,
    collideWorldBounds: true
  });

  var block1 = group.create(100, 200, "block").setVelocity(100, 200);
  var block2 = group.create(500, 200, "block").setVelocity(-100, -100);
  var block3 = group.create(300, 400, "block").setVelocity(60, 100);
  var block4 = group.create(600, 300, "block").setVelocity(-30, -50);

  block1.body.checkCollision.none = true;
  block2.body.checkCollision.none = true;
  block3.body.checkCollision.none = true;
  block4.body.checkCollision.none = true;

  this.physics.add.collider(group, group);
}
```
