### ISSUE TITLE
Add a callback function after adding a scene

### ISSUE THREAD

**Issue by iArePJ** [photonstorm/phaser#4339]
Hey! Adding a scene to the game and then trying to get the scene immediately returns undefined.
```Javascript
game.scene.add('Dialogue', Dialogue);
game.scene.getScene('Dialogue');
// Returns undefined
```
If we could have a function that is called after the scene is done being added that would be nice.

**Comment by clesquir** [comment]
Did you make sure the game is entirely booted at the time of the check?

Here is an example of the method you could use:
```
var game = new Phaser.Game({
	callbacks: {
		postBoot: function(game) {
			var upAndRunningScene = game.scene.getScene('Dialogue');
			//Should be OK here!
		}
	}
});

game.scene.add(
	'Dialogue',
	Dialogue,
	true
);
```

**Comment by iArePJ** [comment]
Oh my gosh I didn't know about that callback config. Thank you!
