### ISSUE TITLE
'gameout' event doesn't get fired

### ISSUE THREAD

**Issue by RademCZ** [photonstorm/phaser#4344]
## Version

* Phaser Version: 3.16.1

* Operating system: Windows

* Browser:

## Description

Callback registered to the 'gameout' event via this.input.on(Phaser.Input.Events.GAME_OUT, callback) from a scene is never invoked when mouse leaves canvas or moves to an overlay. 'gameover' event works fine, though.

**Comment by gammafp** [comment]
I can confirm this too.

**Comment by BigZaphod** [comment]
Same problem for me. macOS / Safari.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
