### ISSUE TITLE
Docs: resetKeys documentation

### ISSUE THREAD

**Issue by maretana** [photonstorm/phaser#4345]
I might be confused but in the [resetKeys documentation](https://photonstorm.github.io/phaser3-docs/Phaser.Input.Keyboard.KeyboardPlugin.html#resetKeys__anchor) of keyboard input, it says `createCursors` instead of the correct method name `createCursorKeys`. It's a minor issue but thought it would help to report.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by maretana** [comment]
Seems fixed locally. Thanks
