### ISSUE TITLE
MouseInputConfig.target will not work with an id string

### ISSUE THREAD

**Issue by BigZaphod** [photonstorm/phaser#4353]
## Version

* Phaser Version: 1.16.1

* Operating system: macOS 10.14.2

* Browser: Safari 12.0.2

## Description

Several of the game config structures have properties for an element to use for some purpose. For example, `ScaleConfig` has the `parent` and `fullscreenTarget` properties and `GameConfig` has `parent`. In these cases (and several others), either an `HTMLElement` or a `string` with the element's id is accepted. Some, however, do not accept an id string!

I spent quite awhile confused by somewhat cryptic (to me) console errors before I figured out that `MouseInputConfig`'s `target` property seemingly requires an `HTMLElement` and does *not* accept a string! It looks as if the other input config's (keyboard, touch, gamepad) suffer from this, too, as their `target` properties are also documented as being of type `{*}`.

IMO these properties should accept an id string *or* an HTMLElement to be consistent with the other properties.

**Comment by photonstorm** [comment]
I'll label this as a feature request for now, but unless the mouse target is the exact same size and location as the canvas anyway, it will not work as a source of input, so really needs removing entirely.

**Comment by BigZaphod** [comment]
Hmm. I discovered the property last night and at first try it seemed to work for what I wanted - but maybe there are bugs lurking and a better way to handle this. Specifically, I wanted to be able to track the mouse pointer while it was held down even if the user dragged the mouse out of the canvas area a little bit. (I was making a rubber band selection and having it stop or cancel the moment the mouse left the canvas wasn't feeling very nice.)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
