### ISSUE TITLE
pointerup not triggering when releasing mouse outside of canvas

### ISSUE THREAD

**Issue by BigZaphod** [photonstorm/phaser#4354]
## Version

* Phaser Version: 1.16.1

* Operating system: macOS 10.14.2

* Browser: Safari 12.0.2

## Description

The release notes say that `pointerup` should now be triggered even when releasing the mouse button outside of the canvas, but I'm not seeing that. The game still seems to think that the mouse is down when the pointer comes back over the game's canvas.

**Comment by photonstorm** [comment]
The notes are incorrect, the events are actually `Phaser.Input.Events#POINTER_DOWN_OUTSIDE` and `Phaser.Input.Events#POINTER_UP_OUTSIDE`. The flow is as in the docs:

``` 
* The event hierarchy is as follows:
 * 
 * 1. [GAMEOBJECT_POINTER_DOWN]{@linkcode Phaser.Input.Events#event:GAMEOBJECT_POINTER_DOWN}
 * 2. [GAMEOBJECT_DOWN]{@linkcode Phaser.Input.Events#event:GAMEOBJECT_DOWN}
 * 3. [POINTER_DOWN]{@linkcode Phaser.Input.Events#event:POINTER_DOWN} or [POINTER_DOWN_OUTSIDE]{@linkcode Phaser.Input.Events#event:POINTER_DOWN_OUTSIDE}
```

I've tested this just now and it's working as expected.
