### ISSUE TITLE
Fullscreen doesn't work in mobile phone

### ISSUE THREAD

**Issue by matrizet** [photonstorm/phaser#4355]
The full screen api doesn't seem to work in android phone.
I used the example from https://labs.phaser.io/100.html?src=src\scalemanager\full%20screen%20game.js

**Comment by photonstorm** [comment]
Which browser? and which version of Android? Support is limited on mobile. If the device + browser don't support it, there's nothing that can be done.

**Comment by matrizet** [comment]
> Which browser? and which version of Android? Support is limited on mobile. If the device + browser don't support it, there's nothing that can be done.

Uh, Browser is chrome

And android versions are 6 and 8

**Comment by pfdtravalmatic** [comment]
Same here. 

- Chrome version 72.0.3626.96 using emulator _and_ Phone with Android 7
- Phaser experimental build 3.17.0

Console output is two-fold:

> Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture

and

> Uncaught (in promise) TypeError: fullscreen error

I've done some investigation and it seems to occur in the function startFullscreen (specifically line 68526 in phaser.js:

`                fsTarget[fullscreen.request](fullscreenOptions);
`

Desktop seems to work fine. I've tried setting the fullscreenTarget to document.documentElement, as well as not setting it at all. Furthermore, I'm not able to get console outputs, but iPad+Safari and Mozilla Firefox emulator don't appear to work either.

**Comment by photonstorm** [comment]
iPad and iPhone work fine for me on real devices.

The Android issue is weird because it _is_ coming from a user gesture in that demo. I could understand the error if it was being called automatically without a gesture.

**Comment by SnipersCode** [comment]
I'm getting the same thing.

* iPhone 7S Plus
* iOS version 12.1.4
* iOS Safari
* Fullscreen API Experimental WebKit feature enabled

Pushing the fullscreen button changes the button to the "return to fullscreen" version, but nothing actually happens. 
The button then goes unresponsive and you can't switch it back to the "go to fullscreen" version.

**Comment by matrizet** [comment]
I'm getting this message when I click the button
"Performing operations that require explicit user interaction on touchstart events is deprecated and will be removed in M54, around October 2016."

**Comment by matrizet** [comment]
I get this error 

MESSAGE: Uncaught TypeError: Cannot read property 'isFullscreen' of undefined

**Comment by photonstorm** [comment]
Looking at this today. It's interesting. If you tap anywhere on the canvas first (before tapping the fullscreen button) and THEN tap the fullscreen button, it works perfectly. If the very first thing you do is tap the fullscreen button, it errors.

So, something appears to be getting in the way of the first tap, because the code path is identical. I'm guessing maybe the web audio unlocking.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

Please note the updated documentation + example regarding this feature on mobile.

**Comment by swissquant-test** [comment]
@photonstorm not sure if this is the desired behaviour, but the function works only if invoked in the `pointerup` event callback. If called in the `pointerdown` callback, I get:

```
phaser-arcade-physics.min.js:1 Uncaught TypeError: Cannot read property 'then' of undefined
    at initialize.startFullscreen (phaser-arcade-physics.min.js:1)
    at initialize.<anonymous> (bundle.js:13092)
    at initialize.h.emit (phaser-arcade-physics.min.js:1)
    at initialize.processDownEvents (phaser-arcade-physics.min.js:1)
    at initialize.update (phaser-arcade-physics.min.js:1)
    at initialize.updateInputPlugins (phaser-arcade-physics.min.js:1)
    at initialize.onTouchStart (phaser-arcade-physics.min.js:1)
    at HTMLCanvasElement.onTouchStart (phaser-arcade-physics.min.js:1)
```

Tested on Samsung Internet browser.

**Comment by monteiz** [comment]
@photonstorm not sure if this is the desired behaviour, but both functions `toggleFullscreen` and `startFullscreen` work only if invoked in the `pointerup` event callback. If called in the `pointerdown` callback, I get:

```
Uncaught TypeError: Cannot read property 'then' of undefined
    at ScaleManager.startFullscreen (phaser-arcade-physics.js:66758)
    at Sprite.<anonymous> (bundle.js:13092)
    at Sprite.emit (phaser-arcade-physics.js:2373)
    at InputPlugin.processDownEvents (phaser-arcade-physics.js:151699)
    at InputPlugin.update (phaser-arcade-physics.js:151442)
    at InputManager.updateInputPlugins (phaser-arcade-physics.js:61595)
    at InputManager.onTouchStart (phaser-arcade-physics.js:61645)
    at HTMLCanvasElement.onTouchStart (phaser-arcade-physics.js:64485)
```

Tested on Samsung Internet browser.
