### ISSUE TITLE
[TypeScript] Error on access Tile.properties keys

### ISSUE THREAD

**Issue by rootasjey** [photonstorm/phaser#4356]
## Version

* Phaser Version: 3.16.1

* Operating system: MacOS Mojave 10.14.1

* Browser: Any

## Description

Hello,

Due to [`object`](https://github.com/photonstorm/phaser/blob/cd67fd61081df6c841ca503abbf04ab185cfb029/src/tilemaps/Tile.js#L154) type for [`Tile.properties`](https://github.com/photonstorm/phaser/blob/cd67fd61081df6c841ca503abbf04ab185cfb029/src/tilemaps/Tile.js#L157), [TypeScript](https://www.typescriptlang.org/docs/handbook/basic-types.html) isn't happy trying to access properties keys like the following: `Tile.properties.toto`.

It throws the following warning/error: `Property 'toto' does not exist on type 'object'.`

## Example Test Code

```TypeScript
// Preload assets (map, tilesets) in the preload function.
// ...
const map = this.make.tilemap({ key: 'level0' });
const tileset = map.addTilesetImage('units', 'unitsTileset');
const unitsLayer = map.createDynamicLayer('Units', tileset, 0, 0);

unitsLayer.forEachTile((tile) => {
  // The following line raises a TypeScript error.
  console.log(tile.properties.name);
});
```

* [Repo demo](https://github.com/rootasjey/phaser-tile-prop)
* [Codesandbox demo](https://codesandbox.io/s/github/rootasjey/phaser-tile-prop)

NOTE: TypeScript definitions do not seem to load on Codesandbox. The issue will pop when `git clone` the GitHub [repo](https://github.com/rootasjey/phaser-tile-prop).

## Additional Information

Changing the type from `object` to `any` would solve this issue (I can make a PR).

**Comment by photonstorm** [comment]
Please PR this.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
