### ISSUE TITLE
Give Container a GameObjectFactory?

### ISSUE THREAD

**Issue by BigZaphod** [photonstorm/phaser#4358]
I was experimenting with using containers as layers in my scene and it started to feel like it'd be very nice if `Container` was also a `GameObjectFactory`. For example, I found myself writing this sort of code:
```javascript
    hudLayer = this.add.container().setScrollFactor(0)
    hudLayer.add(this.add.image(0, 0, 'hud-frame').setOrigin(0, 0))
```

And it would be nicer to to able to write it this way instead (not to mention it avoids adding the object first to the scene and then moving it to the container later):
```javascript
    hudLayer = this.add.container().setScrollFactor(0)
    hudLayer.add.image(0, 0, 'hud-frame').setOrigin(0, 0)
```

I looked into using `GameObjectCreator` functions instead, but many of those function signatures differ from the `GameObjectFactory` signatures in that they only take configuration objects. Even if I adapted everything to use those, it still wouldn't read as cleanly as it would if `Container` had a `GameObjectFactory` like the scene does.

**Comment by photonstorm** [comment]
I quite liked this idea, but it's a big change to make this far into Phaser's life, so I'm afraid I'm going to close it off to try and tidy things up around here!
