### ISSUE TITLE
Rotation and flipping custom tile collision shape

### ISSUE THREAD

**Issue by PavelMishin** [photonstorm/phaser#4360]
## Version
* Phaser Version: 3.16.1
* Tiled Version: 1.2.2
* Operating system: Windows 10
* Browser: Opera

## Description

When tile that have custom collision shape (applied by Tiled collision editor), rotated or flipped (with Tiled map editing or maybe even in code), it is not affected on Matter body shape.

## Example Test Code

handling tile map created in Tiled, and applied Matter physics to it:
```
const map = this.make.tilemap({key: 'level'})
const tilesetMain = map.addTilesetImage('main')
const main = map.createStaticLayer('main', tilesetMain, 0, 0)
main.setCollisionByExclusion(-1)
this.matter.world.convertTilemapLayer(main)
```
## Additional Information

As a temporary solution I use this code for rotating:
```
main.layer.data.forEach((row) => {
    row.filter((tile) => tile.physics.matterBody && tile.physics.matterBody.body.label === 'Body') // Tiles with editing collision
        .filter((tile) => tile.rotation > 0)
        .forEach((tile) => {
            const matterBody = tile.physics.matterBody.body
            const angle = tile.rotation
            const rotationPoint = {
                x: tile.pixelX + tile.width / 2,
                y: tile.pixelY + tile.height / 2,
            }
            Phaser.Physics.Matter.Matter.Body.rotate(matterBody, angle, rotationPoint)
        })
})
```
But I'm not sure how correctly to flip Matter tile body shape.

**Comment by phaserhelp** [comment]
Hi,

Thanks for the rotation tip! Here is how you can fix the Flipping:
```
if (tile.flipX || tile.flipY) {
  let rotationPoint = {x: tile.getCenterX(),
                       y: tile.getCenterY()}
  let scaleX = 1;
  let scaleY = 1;
  if (tile.flipX) {scaleX = -1}
  if (tile.flipY) {scaleY = -1}
  Phaser.Physics.Matter.Matter.Body.scale(matterBody,
                                          scaleX,
                                          scaleY,
                                          rotationPoint);
}
```

**Comment by PavelMishin** [comment]
Of course, the scale workaround! I guess I should have realized it.
Thank you @phaserhelp!

**Comment by Olliebrown** [comment]
It's worth noting that this is still and issue in the codebase.  While the above code does provide a workaround, it doesn't seem to be integrated into Phaser yet (at least not in 3.60.0-beta.3).

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
