### ISSUE TITLE
UpdateList.prototype.remove issue

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#4365]
remove: function (child)
    {
        var index = this._list.indexOf(child);

        if (index !== -1)
        {
            this._list.splice(index, 1);
        }

        return child;
    },

I think should push the `child` into `_pendingRemoval` list but not directly remove from the active list? otherwise `_pendingRemoval` becomes useless?

and if use `_pendingRemoval` I think the `indexOf` check is unnecessary here because later it will be checked in the `preUpdate` method.

you think? or is this designed originally like so?

**Comment by photonstorm** [comment]
It should go in the `pendingRemoval` array.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
