### ISSUE TITLE
Support JSON5 in Loader (OR: support "transformResponse" for XHRLoader)

### ISSUE THREAD

**Issue by G-Rath** [photonstorm/phaser#4368]
When dealing with JSON, Phaser uses `JSON.parse`, which means you can't use standards such as JSON5.

This could be added by just using the `JSON5` library to parse json, instead of `JSON.parse`.

Alternatively, a `transformResponse`-style setting could be added "somewhere" (I'd imagine around the `XHRLoader` or `JSONLoader`, but there might be a better place) that takes a function (or array of functions) that can transform the response before it's returned.

I'd imagine the function would look something like `fn(data, loader, fileType)`, and it'd expect you to return the transformed data.

You'd provide the data for transforming and the `loader` to help identify what type of data was expected.

This is similar to the axios library, which lets you do the above, via the `transformResponse`.

This would let us leverage the different loader plugins, such as `pack` & `atlas`, while using our own arbitrary data structures, as we'd carry the burden of ensuring the end result the loader sees is structured to its specifications. 

**[Optional] Do you want to help provide this feature?**

I'm interested in helping build this feature, but don't know how much time I can spare for the actual programming unless it's very straightforward to implement, given that I've not worked with the Phaser codebase before. 

While my initial proposal might not be the best solution, I think the feature itself would make a very powerful addition to the `Loader` system of Phaser, at minimal cost.

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
