### ISSUE TITLE
phaser example Create From Sprite Config random generator issue

### ISSUE THREAD

**Issue by sanadov** [photonstorm/phaser#4369]
## Version

Phaser v3.16.2

window 10 

chrome
firefox

## Description

trying to use phaser random with sprite config generator by following phaser example

it gives this error in chrome 
phaser.min.js:1 Uncaught TypeError: Cannot read property 'integerInRange' of null

in firefox:
TypeError: n.RND is null

## Example Test Code

let config = {
        key: 'textureKey',
        x: { randInt: [ 0, 10 ] },
        y: { randInt: [ 0, 10 ] },
    };
    this.make.sprite(config);

## Additional Information
related phaser 3 example 
https://labs.phaser.io/view.html?src=src\animation\create%20from%20sprite%20config.js&v=3.16.2

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
