### ISSUE TITLE
Support custom property other than `files` for pack loading

### ISSUE THREAD

**Issue by G-Rath** [photonstorm/phaser#4372]
I'm using json files for my game, with files including an array of assets to be loaded by the loader, like so:

```
{
  "$schema": "stage.schema.json5",
  name: "The Tower",
  assets: [
    {
      type: "image",
      key: "grey-square",
      url: "assets/grey-square.png"
    }
  ],
  layout: [
    {
      type: "staticGroup",
      objects: [
        {
          x: 400,
          y: 568,
          asset: "grey-square",
          scale: 2
        },
        {
          x: 600,
          y: 400,
          asset: "grey-square"
        }
      ]
    }
  ]
}

```

```
preload() {
  this.load.pack('loaded-stage', this._stageUrl, 'assets');
}
```
However, the problem is that the above json file won't actually work as a pack, due to this line:

https://github.com/photonstorm/phaser/blob/376f06d2a93424bc3d6e7f491f0f23e4485e4d39/src/loader/LoaderPlugin.js#L607

Instead, the `assets` key needs to look like this:

```
assets: {
  files: [
    {
      type: "image",
      key: "grey-square",
      url: "assets/grey-square.png"
    }
  ],
}
```

Ideally, it'd be great if we could somehow provide our own key to be used inplace of `files`.

While I'm happy to help with this, I'm not sure where the best place to implement this feature would be.

However, another secondary feature that I would be happy to have a got at implementing would be to check if `config` is an array, and if so use that as if it was `files` (& use the default options for everything else).

This could be mitigated somewhat by the `transformResponse` feature proposed #4368, as it'd let you transform the files before they reached the loader to alter the `assets` properties to contain `files`.

**Comment by photonstorm** [comment]
Sorry, I've no intention of letting you specify your own key instead of `files`. It's part of a larger pack file schema, and in this full context, it accurately describes what the property should contain:

```
    "test2": {
        "prefix": "TEST2.",
        "path": "assets/pics",
        "defaultType": "image",
        "files": [
            {
                "key": "donuts",
                "extension": "jpg"
            },
            {
                "key": "ayu"
            }
        ]
    },
```

However, I would be open to allowing it to check if an array is given and assuming it's a `files` array if that's the case, although you'd then need to ignore the `packKey` parameter from the method too. I guess the `url` argument is the one that would need to have an array check on it.

Then again, if you've already got the array by that point, it would make a lot more sense to just call `this.load.addPack()` instead - so really, perhaps it is _that_ method that should take an array?

**Comment by G-Rath** [comment]
> It's part of a larger pack file schema, and in this full context, it accurately describes what the property should contain.

Yes - this issue was about supporting a somewhat custom schema, where you specify one of the properties. In the context of my schema the `assets` property accurately describes what the `files` property should contain. 

In this proposal, the rest of the schema would still be valid:

```
{
  "$schema": "stage.schema.json5",
  name: "The Tower",
  assets: [
    {
      type: "image",
      key: "grey-square",
      url: "assets/grey-square.png"
    }
  ],
  "prefix": "TEST2.",
  "path": "assets/pics",
  "defaultType": "image",
  layout: [
    {
      type: "staticGroup",
      objects: [
        {
          x: 400,
          y: 568,
          asset: "grey-square",
          scale: 2
        },
        {
          x: 600,
          y: 400,
          asset: "grey-square"
        }
      ]
    }
  ]
}
```

But if that's how you feel, I'll leave the matter be 😃 

> so really, perhaps it is _that_ method that should take an array?

I'll get back to you on that, when I've had some time to look back into this.

Ultimately, I suspect I'll just roll my own loader 😄 Thanks for the info!

**Comment by G-Rath** [comment]
Out of interest, what harm do you envision that has you making such a hard stance letting developers specify their own key?

Just to be clear: Completely fine with your response - it's your library, but I'm just interested in if there's something I might have overlooked or not understood, as as far as I could find, that's the only place the key is used 😊

**Comment by photonstorm** [comment]
Thank you for opening this issue, however, I'm going to close it off now as there has been no progress made on this issue in quite some time, and sadly no contributions from anyone else to help fix it. I'm sorry we couldn't resolve it in this case.
