### ISSUE TITLE
Camera shake even shakes game objects that have a scrollFactor of 0

### ISSUE THREAD

**Issue by BigZaphod** [photonstorm/phaser#4374]
## Version

* Phaser Version: 3.16.2

* Operating system: macOS

* Browser: Safari

## Description

I was using `setScrollFactor(0)` to define some parts of my HUD, but it turns out that the camera shake will even shake those game objects - which I don't think I want in this case. I suppose I should have expected this, but it was surprising!

It might be nice if camera shake could respect the scroll factor somehow? My HUD has a frame that goes around the border of the screen and isn't really part of the "game", exactly, so having it shake just feels wrong.

I'm not sure if there's any way to work around this without redoing everything I've got so far and pulling the HUD out into a separate scene that runs over top in parallel. It's possible that's a better approach in the long run, but I was trying to keep things "simple."

**Comment by photonstorm** [comment]
Shaking has nothing to do with scrolling I’m afraid. This is working as expected. The hud should be in its own scene really.
