### ISSUE TITLE
No warning if GameObject's construction scene does not match the scene it's added to

### ISSUE THREAD

**Issue by BigZaphod** [photonstorm/phaser#4375]
## Version

* Phaser Version: 3.16.2

* Operating system: macOS

* Browser: Safari 12.0.3

## Description

Since the `GameObject` constructor requires passing a `Scene`, many game objects ultimately assume this scene is the one you're going to add the game object *to* and the constructor might do things based on that assumption. If you manually create a new game object instance using `new` and pass it a scene instance, but then (most likely accidentally) use `add.existing()` of a *different* scene instance to add that new game object, there's no warning in the console. Depending on the game object, though, random things might not work the way you thought and you might spend entirely too long trying to figure out why. (Not that this happened to *me*..... ahem.)

It seems like there's probably a (maybe unspoken) contract that game objects must be constructed with the same scene they will ultimately be added to. This creates a bit of seemingly unnecessary boilerplate code, too, when contracting game objects using `new` instead of the factory methods. You end up having to pass in the scene to all of the constructors only to also have to add the resulting instance of the game object to the same scene again manually after it is constructed.

Personally, I might opt to changing `GameObject` so that a newly created instance is always just added to the scene during construction and if you don't want that behavior, you could pass some config flag or simply remove it after constructing. I'm not an experienced game dev, but so far it seems like every time I make a game object, I want it in the scene at the same time.

**Comment by photonstorm** [comment]
Game Objects belong to a specific scene and are bound to it until destruction. This isn’t optional, it’s just how they work. The choice you have is when they are added to the Display List of the Scene. That is what the factory automates for you. If you’re finding you always need your objects to  appear immediately then use the factory. There’s no benefit to creating them via a constructor. You only really need to do that if you’re seeding a pool in advance of it being added to the display. You can skip the factory if you need explicit control over when they are added to the display, but they’ll always belong to the scene.

**Comment by BigZaphod** [comment]
That makes sense. This comes up when I have my own subclass of a game object and I’m creating it a lot (like making a bunch of button objects to populate the UI). I could add my own constructor to the factory, I guess. Would it be possible for the factory to have a utility function that’s something like: ‘scene.add.new(MyGameObjectSubclass, ... args)’ and it instantiates an object with the scene and adds it? It seems like that might be nice sometimes. (Of course I could still be misunderstanding something dumb here and am simply doing it wrong at a deep level :p)

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
