### ISSUE TITLE
Sprite positioning on Y Axis is incorrect

### ISSUE THREAD

**Issue by NikolaPi** [photonstorm/phaser#4377]
## Version

* Phaser Version: 3.16.2

* Operating system: Linux Mint 19 Cinnamon

* Browser: Both Chrome and Firefox

## Description

When I create a new sprite from a sprite sheet with specified coordinates, the sprite is off in position. It displays by an inconsistent offset every time.

## Example Test Code

<a href="https://repl.it/@ParkerSmith4/Phaser-Bug-Report">The Source Code REPL</a>
<a href="https://phaser-bug-report--parkersmith4.repl.co">The Result(running inside the normal page does not work)</a>

**Comment by photonstorm** [comment]
There's a _lot_ of extra code in that example, including Matter objects. Boil it down, please. If the issue is that sprites don't appear on the right `y` coordinate with your sprite sheet, then that should be demonstrable with just a single line of code in the create function.

**Comment by NikolaPi** [comment]
I am closing this issue because i was unable to reproduce it when I tried to rewrite the code again.
