### ISSUE TITLE
Phaser renders incorrect color

### ISSUE THREAD

**Issue by sharifzadesina** [photonstorm/phaser#4379]
## Version

* Phaser Version: 3.16.2

* Operating system: Ubuntu 16.04.1

* Browser: Chrome Version 72.0.3626.109 (Official Build) (64-bit)

## Description

If you check the test code, you will notice that background color of the canvas doesn't obey the color defined in config object, we have `#2d2d2d` in config object but what gets rendered is `#313131`.

## Example Test Code

https://codepen.io/anon/pen/wNRjvr

## Additional Information

I doubt if this is only about background color or the whole game like images and etc, also I've tested using both Chrome and Firefox.

**Comment by KingCosmic** [comment]
![image](https://user-images.githubusercontent.com/24766991/52940951-5d196100-332d-11e9-89dd-8837bfc8e475.png)
I'm getting the correct color on my end

**Comment by sharifzadesina** [comment]
For me, it is always wrong.
![screenshot from 2019-02-18 13-00-39](https://user-images.githubusercontent.com/15300551/52941251-95e12680-337d-11e9-90b8-b4d95ea5c03b.png)

**Comment by KingCosmic** [comment]
After chatting on the discord server and it works for everything but them, Antriel hopped in and said it seemed like an HDR issue he's had before, unsure how to fix. conversation started [here](https://discordapp.com/channels/244245946873937922/416623653741133837/546985903609085974)

**Comment by sharifzadesina** [comment]
It seems this is an old Chrome issue. (maybe happened cause of new update again?)
It effects both CSS and canvas.
http://www.html5gamedevs.com/topic/25294-color-problem-with-chrome-osx-desktop-browser/
https://bugs.chromium.org/p/chromium/issues/detail?id=637801&desc=2
