### ISSUE TITLE
Why not publish the 'd.ts' into `@types`?

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [photonstorm/phaser#4382]
Since phaser3 has a `d.ts` file in the [`docs` repo](https://github.com/photonstorm/phaser3-docs/tree/master/typescript), why not published it into `@types` ?

**Comment by photonstorm** [comment]
Because of the time and effort involved in maintaining yet another dependency elsewhere. The defs will move to the main repo with the 3.17 release, where they can remain in sync with the code.

**Comment by zhengxiaoyao0716** [comment]
Well I'm  am looking forward to it, thank you.
