### ISSUE TITLE
'fillGradientStyle' not works with 'generateTexture' function

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [photonstorm/phaser#4383]
## Version
* Phaser Version: Phaser v3.16.2-FB (WebGL | Web Audio)  https://phaser.io
* Operating system: Microsoft Windows [Ver 10.0.15063]
* Browser: 72.0.3626.109

## Description
When I called `fillGradientStyle()` an then create texture used 'generateTexture', it would not has the gradient colors.

## Example Test Code
```
    // preload
    const graphics = new Phaser.GameObjects.Graphics(this);
    graphics.fillGradientStyle(0x66CCFF, 0x66CCFF, 0x99FFFF, 0x99FFFF);
    graphics.fillRect(0, 0, 256, 256);
    graphics.generateTexture('test');

    // create
    this.add.image(256, 256, 'test');
```

**Comment by photonstorm** [comment]
Yes, this is unfortunate but I'm afraid there's no simple way to resolve it as the gradient is actually a vertex tint and `Graphics.generateTexture` uses the canvas renderer to create the texture, which doesn't support tints. I'll take a PR if anyone can think of a way around this, but for now I need to close it as it's not going to change any time soon.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/phaser-3-l-systems-demo/5860/1
