### ISSUE TITLE
Phaser.io/contact website not working

### ISSUE THREAD

**Issue by LifeVirus** [photonstorm/phaser#4385]
When accessing phaser.io/contact, I run into an exception. I get the same error on safari, chrome, and firefox. 
![image](https://user-images.githubusercontent.com/42986305/53125268-9ae3d880-352b-11e9-9f2e-18b70efcb6c8.png)

**Comment by photonstorm** [comment]
This is correct in the sense that there is no contact page. Where did you find a link to it?

**Comment by rgk** [comment]
http://phaser.io/community/anti-harassment-policy is one of the pages I found it on.

If you remove the route, you shouldn't get all the debug stuff and a nice Laravel 404 page.

**Comment by LifeVirus** [comment]
Yes, I found it under http://phaser.io/community/anti-harassment-policy like rgk mentioned, when you click the "contact us" hyperlink, sorry for not including that in the original post. 
![image](https://user-images.githubusercontent.com/42986305/53142609-8ec73d80-3562-11e9-8481-3dad92c6f278.png)

**Comment by photonstorm** [comment]
Link removed.
