### ISSUE TITLE
SoundManager should mute when game is unfocus/paused

### ISSUE THREAD

**Issue by georgiee** [photonstorm/phaser#439]
It's easy as this:
game.onPause.add(function(){game.sound.mute = true})
game.onResume.add(function(){game.sound.mute = false})

Maybe we should integrate this intro Phaser.Game, either in the game loop game#update or maybe game should attach itself to onPause/onResume during game#boot ?

There is only one problem:
SoundManager#mute is exposed as a public property, so we could get the following problem (like with timers)

```
//1. mute all sounds by purpose at moment A - because the player do not want any sound and that's the way to got
game.sound.mute = true

//2. player unfocus game, action by game class
game.sound.mute = true
//Now it's muted

//3. player focus game, action by game class
game.sound.mute = true
//Now it's unmuted- even if it was manual muted before.
```

What to do ? Is it time to bring in a second state variable for mute or rather use a single state variable with bitmasking like so: 

```

OtherGameStates = {}
OtherGameStates.GAME_PAUSED = 1 //'0001'
OtherGameStates.USER_PAUSED = 2 //'0010'

SoundStates = {}
SoundStates.USER_MUTED = 4 //'0100'
SoundStates.GAME_MUTED = 8 //'1000'
SoundStates.TOTALLY_UNRELATED_STATE = 16 //'10000'

//set active states (muted and paused by user and game)
gameStates = 0
gameStates |= SoundStates.USER_MUTED | SoundStates.GAME_MUTED
gameStates |= OtherGameStates.USER_PAUSED | OtherGameStates.GAME_PAUSED
gameStates |= SoundStates.TOTALLY_UNRELATED_STATE

console.log('starting with: MUTED by GAME and USER and additionally game PAUSED by GAME and USER', asBinary(gameStates))

//game unmutes now
gameStates &= ~SoundStates.GAME_MUTED
console.log('action: unmuted by game', asBinary(gameStates))
//state checking (after an event for example)

if ((gameStates & (SoundStates.GAME_MUTED | SoundStates.USER_MUTED)) != 0){
  if ((gameStates & SoundStates.USER_MUTED) ==  SoundStates.USER_MUTED){   
    console.log('** but only by user', gameStates)
  }
}

//user unmutes now
gameStates &= ~SoundStates.USER_MUTED

if ((gameStates & (SoundStates.GAME_MUTED | SoundStates.USER_MUTED)) == 0){
  console.log('** nothing is muted')
}

if ((gameStates & OtherGameStates.GAME_PAUSED) != 0){
   console.log('game is paused')
}

```

See my gist for a full blown bitmask example. I used the opportunity to refresh my bitmasking knowledge
https://gist.github.com/georgiee/9074497

Or how is this somewhat classical multiple states problem resolved normally ? Maybe this is not the responsibility of the game framework ? I do not think so.

**Comment by cribalik** [comment]
It seems like the Sound's that are being managed by game.sound do not fire their respective onMute events when the sound manager is paused. Is this by design?
