### ISSUE TITLE
renderTexture.fill() doesn't properly fill the texture

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#4390]
## Version

* Phaser Version: 16.1

* Operating system: Window 10

* Browser: Chrome

## Description

When filling a `renderTexture` (with `fill()`), the fill doesn't appear at the right coordinates.

## Example Test Code
It works in version 15.1, as can be seen in [this fiddle](https://jsfiddle.net/j50deox8/), which shows the intended behavior.

It doesn't work properly in version 16.1 anymore, as can be seen in [this fiddle](https://jsfiddle.net/mqjdkgst/) (the black area should touch the white one).

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by LorenzoBoccaccia** [comment]
23.0 is showing some more fill positioning issues https://jsfiddle.net/f2maodx9/
