### ISSUE TITLE
performance drop spine animations

### ISSUE THREAD

**Issue by Mariusz1990** [photonstorm/phaser#4393]
## Version
* Phaser Version: Phaser v3.15.1 (Canvas | Web Audio) 
* Operating system: Windows 10 Home
* Browser: Tested only on Chrome

## Description

I have a problem with the Spine plugin for the latest version of Phaser 3. I would be grateful for the help. The problem only occurs for repeated animations, after (circa) (3-5 min) and window minimalize/lost focus there is a dramatic decrease in performance. After re-calling the "setAnimation" method, everything returns to normal over a period of time. Of course, there are no errors in the console. The error occurs with several (10) animations.

## Example Test Code
var config = {
    type: Phaser.CANVAS,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d66',
    scene: {
        preload: preload,
        create: create,
        pack: {
            files: [
                { type: 'scenePlugin', key: 'SpineCanvasPlugin', url: 'plugins/SpineCanvasPlugin.js', sceneKey: 'spine' }
            ]
        }
    }
};

var game = new Phaser.Game(config);

function preload ()
{
		this.load.setPath('assets/');

		this.load.spine('carrot', 'Carrot_Field.json', 'Carrot_Field.atlas');
		this.load.spine('banana', 'Banana.json', 'Banana.atlas');
		this.load.spine('cows', 'Cows.json', 'Cows.atlas');
}

function create ()
{
        var obj1 = this.add.spine(100, 300, 'carrot', 'idle', true);
		var obj2 = this.add.spine(400, 300, 'banana', 'idle', true);
		var obj3 = this.add.spine(800, 300, 'cows', 'idle', true);
		
		var obj4 = this.add.spine(100, 0, 'carrot', 'idle', true);
		var obj5 = this.add.spine(400, 0, 'banana', 'idle', true);
		var obj6 = this.add.spine(800, 0, 'cows', 'idle', true);
		
		var obj7 = this.add.spine(100, 600, 'carrot', 'idle', true);
		var obj8 = this.add.spine(400, 600, 'banana', 'idle', true);
		var obj9 = this.add.spine(800, 600, 'cows', 'idle', true);
}

**Comment by photonstorm** [comment]
Spine objects are now fully batched and the plugin has been rewritten for Phaser 3.19. Please use this version and test against that.
