### ISSUE TITLE
Unclear documentation for Phaser.GameObjects.Rectangle

### ISSUE THREAD

**Issue by TheBeege** [photonstorm/phaser#4395]
In the reference documentation for Phaser.GameObjects.Rectangle, it's [unclear what the x and y in the constructor are referring to](https://github.com/photonstorm/phaser/blob/04080bc1bab46834e4e9947a17905c1be0d5560b/src/gameobjects/shape/rectangle/Rectangle.js#L30). Is it the top-left corner? Is it the center? Similar confusion around origin.

If I want to create a Rectangle based on its top-left corner, I should write something like the below:
```javascript
scene.add.rectangle(
    x + width/2,
    y + height/2,
    width,
    height,
    fillColor
);
```

It appears that x and y refers to the center point of the rectangle. 

This is inconsistent with Phaser.Geom.Rectangle, which defaults to the top left corner, [as written in its docs](https://photonstorm.github.io/phaser3-docs/Phaser.Geom.Rectangle.html).

This is confusing. Can we fix this? My preference would be to set the GameObject Rectangle's constructor x and y as the top-left corner and use that as the default origin, but I see how this would break backwards compatibility. At the very least, can we update the documentation to explicitly state where x and y refer to and how to adjust the origin to one's liking?

Thanks

**Comment by TheBeege** [comment]
Also, the originX and originY of Phaser.GameObjects.Text appear to [default to 0 rather than 0.5 as described](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Text.html#originX__anchor).

**Comment by photonstorm** [comment]
All Game Objects (other than Text) have a default origin of 0.5. Use `setOrigin(0)` to change it, then you don't need to adjust the x/y coordinates. `Geom.Rectangle` isn't a display object, it's just a bit of math, so it doesn't have an origin.

The only reason Text has an origin of 0 is that in most cases game text reads from left to right, so you'd want to left-align it.
