### ISSUE TITLE
Create Dynamic Layer doesn't properly get default tileheight/width with multiple tilesets

### ISSUE THREAD

**Issue by Aedalus** [photonstorm/phaser#4397]
## Version

* Phaser Version: 3.16 +

* Operating system: Mac

* Browser: All

## Description

Creating a blank dynamic layer doesn't set defaults if multiple tilesets are specified.

## Example Test Code
```
    // Works fine
    const terrainLayer = map.createBlankDynamicLayer(
      "terrainLayer",
      tiles, 
    );
    // Doesn't work, no errors thrown
    const terrainLayer = map.createBlankDynamicLayer(
      "terrainLayer",
      [tiles], 
    );
   // Works once all these optional params are supplied
    const terrainLayer = map.createBlankDynamicLayer(
      "terrainLayer",
      [tiles], 
      0,
      0,
      map.width,
      map.height,
      16,
      16
    );
```

## Additional Information

Looks like the culprit is here in the Tilemap.js file.

```
  createBlankDynamicLayer: function createBlankDynamicLayer(name, tileset, x, y, width, height, tileWidth, tileHeight) {
    if (tileWidth === undefined) {
      tileWidth = tileset.tileWidth;
    }

    if (tileHeight === undefined) {
      tileHeight = tileset.tileHeight;
    }
```

tileWidth and tileHeight aren't properly assigned if tileset is an array.

I can get a PR in to fix this, but wanted to confirm if there was a better way to set the default than just grabbing the first tileset in the array and using its tileWidth and tileHeight. At the very least it seems like a warning should be shown in the console if tileWidth and tileHeight aren't passed in for multiple tilesets.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
