### ISSUE TITLE
Arcade static group config doesn't change classType

### ISSUE THREAD

**Issue by Legomite** [photonstorm/phaser#4401]
## Version

* Phaser Version: 3.16.2

* Operating system: MacOS

* Browser: Safari

## Description

When attempting to set the class type of a group through the config, it doesn't change anything. 

## Example Test Code
I'm extending Phaser.Physics.Arcade.StaticGroup and calling super()

super(world, scene, {
      classType: Block,
      maxSize: 1936
    });

## Additional Information

I'm not entirely sure since I'm not familiar with Phaser's source code, but it appears to me that the config argument doesn't change anything in StaticGroup. It seems like this line is reverting the changes the config did: https://github.com/photonstorm/phaser/blob/04080bc1bab46834e4e9947a17905c1be0d5560b/src/physics/arcade/StaticPhysicsGroup.js#L58

This pattern reappears for the other config stuff, but I'm not really sure if this is intentional.. 🤷‍♂️

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
