### ISSUE TITLE
`SceneManager.switch("AlreadyRunningScene")` starts the scene instead of being idempotent - probably needs to stay but could be documented?

### ISSUE THREAD

**Issue by ralokt** [photonstorm/phaser#4403]
When you use `SceneManager.switch` to switch to a scene that is already running, that scene will be started again. This leads to weird behavior where there are apparently two instances of a scene running at the same time.

The relevant code is here:

https://github.com/photonstorm/phaser/blob/04080bc1bab46834e4e9947a17905c1be0d5560b/src/scene/SceneManager.js#L1201-L1221

As someone new to Phaser, I find this very counterintuitive - I would have expected scene switching to be idempotent. I understand that the assumption probably is that this method will usually be called as `this.scene.switch("OtherScene")` from scene code, and as such the other scene will usually either not be running or not be awake, especially if only one scene is running at a given time.

However, my use case does not fit this assumption - I have UI controls in an HTML form below my game, and they are always visible (which makes sense, because starting a new game makes sense regardless of current game state). I also believe that this use case is not exactly unique - Phaser is awesome, but doesn't support a number of important GUI elements (no text input widget). For prototyping, or where there will be many and/or complex inputs, writing a HTML UI that talks to a Phaser instance is a really good idea.

A more concrete use case would be a simulation that uses Phaser to display graphical data that has more than one useful representation. Each representation is implemented as a Phaser scene, and there are HTML buttons to switch between representations. In this case it would greatly simplify the event handler if it could just perform a `switch` without worrying about the current state of the UI.

I realize that changing this behavior would break backwards compatibility, so fixing it may not be an option, but I'd like to suggest documenting it as a gotcha. "Do not switch to a scene that is already running" is easy enough to remember, it's just hard to discover.

**Comment by photonstorm** [comment]
Scenes in Phaser are non-exclusive. There is nothing stopping you having multiple instances of _the same Scene_ running in parallel together, so there are plenty of cases where you would want this behavior to remain. I've added in more documentation to clarify it, but it's an important point to remember when using any Scene functions: don't assume this is the only instance of a Scene, because nothing enforces that unless you do so specifically if you code.
