### ISSUE TITLE
Wrong positioning of flipped & animated sprite

### ISSUE THREAD

**Issue by PhaserEditor2D** [photonstorm/phaser#4406]
## Version

* Phaser Version: 3.16.2
* Operating system: Ubuntu 64 bits (Linux)

## Description

A sprite is not well animated if it is created with this data:

* Create an animation with frames from a multi-atlas with trimmed frames (removed extra whitespaces).
* Set the sprite `flipX=true`. 
* Play the animation.

## Example Test Code

Here I attach the code and assets to reproduce the error. It can be tested locally or can be run here: http://games.boniatillo.com/bug-flipX-animations/

## Additional Information

Note in the example there are 4 sprites. The last sprite `skull2_trim` is the one with the problem:

```!javascript

var skull2_trim = this.add.sprite(400, 300, "skull-trim", "Idle_000");
skull2_trim.flipX = true;
// ERROR: this is not playing well!
skull2_trim.play("idle-trim");
```

[bug_flipX_animation.zip](https://github.com/photonstorm/phaser/files/2919534/bug_flipX_animation.zip)

**Comment by photonstorm** [comment]
Yeah, this is actually a duplicate of #3813 and needs sorting soon.

**Comment by PhaserEditor2D** [comment]
Ah, ok, I close this then. I will follow the other issue. Thanks!
