### ISSUE TITLE
Phaser.Input.Events.POINTERLOCK_CHANGE do not work.

### ISSUE THREAD

**Issue by gammafp** [photonstorm/phaser#4407]
Hi. The event  **Phaser.Input.Events.POINTERLOCK_CHANGE** do not work correctly.

**Comment by jorbascrumps** [comment]
Hi @gammafp, can you please provide an example of the behaviour you're seeing? You can use something like codesandbox.io to illustrate the issue if needed.

**Comment by gammafp** [comment]
You can see the example of Phaser Labs: 
https://labs.phaser.io/edit.html?src=src\input\mouse\pointer%20lock.js
If you in  this.input.on('pointerlockchange', function (event) you add a console.log do not work

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
