### ISSUE TITLE
RenderTexture draws blurry images when resolution is not 1

### ISSUE THREAD

**Issue by Eirik81** [photonstorm/phaser#4408]
When the resolution for a game is greater than 1 an image drawn too a RenderTexture will become blurry. It seems to be scaled up from a lower resolution. For phaser version 3.16.1 and 3.16.2 the resolution is hardcoded to 1. I've therefor made a fiddle using the previous version (3.15.1) which demonstrates the issue:

https://jsfiddle.net/a35gcot8/2/

**Comment by photonstorm** [comment]
Closed via https://github.com/photonstorm/phaser/issues/4417#issuecomment-691461351
