### ISSUE TITLE
tween.seek() doesn't work with delays

### ISSUE THREAD

**Issue by cristib84** [photonstorm/phaser#4409]
Tween.seek() behaves erratically if tween has a delay.
Added a delay to example from: [https://labs.phaser.io/view.html?src=src\tweens\seek.js](url)
Commenting line with "delay: 1000" everything works(this is the original code from phaser labs, link above) but with delay when setting the scroll bar values jump all over the place.
See code:

`

        var config = {
               type: Phaser.CANVAS,
               width: 800,
               height: 600,
               backgroundColor: '#2d2d2d',
               parent: 'phaser-example',
               scene: {
                   preload: preload,
                   create: create,
                   update: update
               }
        };

    var text1;
    var text2;
    var tween;
    var progressBar;

    var game = new Phaser.Game(config);

    function preload ()
    {
        this.load.image('block', 'assets/sprites/block.png');
    }

    function create ()
    {
    var marker = this.add.image(100, 250, 'block').setAlpha(0.3);
    var image = this.add.image(100, 250, 'block');

    text1 = this.add.text(30, 20, '0', { font: '16px Courier', fill: '#00ff00' });
    text2 = this.add.text(400, 20, '0', { font: '16px Courier', fill: '#00ff00' });

    tween = this.tweens.add({
        targets: image,
        delay: 1000,
        props: {
            x: { value: 700, duration: 4000, ease: 'Power2' },
            y: { value: 500, duration: 1500, ease: 'Bounce.easeOut' }
        }
    });

    console.log(tween);

    progressBar = document.createElement('input');
    progressBar.type = 'range';
    progressBar.min = '0';
    progressBar.max = '100';
    progressBar.step = '.001';
    progressBar.value = '50';
    document.body.appendChild(progressBar);

    progressBar.addEventListener('input', function (e) {

        tween.pause();

        tween.seek(e.target.value / 100);

    });
    }

    function update () {
    //  Tween
    text1.setText([
        'Progress: ' + tween.progress,
        'Elapsed: ' + tween.elapsed,
        'Duration: ' + tween.duration,
        ' ',
        'Loops: ' + tween.loopCounter,
        'TProgress: ' + tween.totalProgress,
        'TElapsed: ' + tween.totalElapsed,
        'TDuration: ' + tween.totalDuration
    ]);

    //  TweenData
    text2.setText([
        'Progress A: ' + tween.data[0].progress,
        'Progress B: ' + tween.data[1].progress
    ]);

    if (tween.isPlaying())
    {
        progressBar.value = Math.floor(tween.progress * 100);
    }

    }
`

**Comment by ryanw999** [comment]
.seek() also has weird behavior with yoyo and loops as well. Please see this post:
https://phaser.discourse.group/t/how-can-i-set-the-progress-of-tween-in-phaser3/714

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by halgurdh** [comment]
Hi, my tween is not working any more

here is the code, i have the tween.seek in an update function,
also the tween.restart is not working from there

the tween:
`this.dynamicProperties = {
        x: {
            value: function () {
                if (this.target.pointerx > this.target.scene.cameras.main.width / 2) {
                    return this.target.initX + 200;
                } else if (this.target.pointerx < this.target.scene.cameras.main.width / 2) {
                    return this.target.initX - 200;
                } else {
                    return this.target.initX;
                }
            },
            duration: 1000, 
            ease: 'Linear'
        },
        rotation: {
            value: function () {
                if (this.target.pointerx > this.target.scene.cameras.main.width / 2) {
                    return 0.2;
                } else if (this.target.pointerx < this.target.scene.cameras.main.width / 2) {
                    return -0.2;
                } else {
                    return 0;
                }
            },
            duration: 1000,
            ease: function (t) { return Math.pow((t + 0.02), 6) }
        },
        onComplete: function () { },
    }
    return this;`

The update function:
`class HTap {
    constructor(scene, target) {
        target.leanSpeed = 50;

        scene.input.on('pointerdown', function (pointer) {
            target.pointerx = pointer.x;

            let camX = target.scene.cameras.main.width/2;
            let pointerRight = target.pointerx > camX;
            let pointerLeft = target.pointerx < camX;
            let playerRight = target.x > camX +50;
            let playerLeft = target.x < camX -50;
    
            //console.log("pointerR:" + pointerRight + " playerR: " + playerRight + " pointerL: " + pointerLeft +" playerL: " + playerLeft)

            if(pointerRight == playerRight || pointerLeft == playerLeft){
                target.pointerdown = true;
                target.dynamics.restart();

            }else{
                target.pointerdown = false;
            } 
        });

        scene.input.on('pointerup', function (pointer) {
            target.pointerx = scene.cameras.main.width / 2;
            target.pointerdown = false;
        });
    }

    update (target){

        if(target.pointerdown){

            let dx = Math.abs(target.pointerx - target.scene.cameras.main.width/2);

            target.leanFactor += (dx / 20) + (target.leanSpeed/10);

            if(target.dynamics.progress > 0.09){
                target.leanFactor /= 1.01;
                target.dynamics.seek(target.leanFactor/1000);
            }else{
                target.dynamics.seek(target.leanFactor/1000);
            }

        }else{
            target.leanFactor /= 1.05 + (target.leanSpeed/10);   
            target.dynamics.seek(this.maxoutFactor(target)/10);
        }

    }

}

export default HTap;`
