### ISSUE TITLE
Phaser 3 tutorial docs bug

### ISSUE THREAD

**Issue by alextotheroh** [photonstorm/phaser#4410]
This tutorial page:
http://phaser.io/tutorials/making-your-first-phaser-3-game/part10

Has incorrect code.  All of this code should come _after_ the if block, not be inside it:

```
var x = (player.x < 400) ? Phaser.Math.Between(400, 800) : Phaser.Math.Between(0, 400);

var bomb = bombs.create(x, 16, 'bomb');
bomb.setBounce(1);
bomb.setCollideWorldBounds(true);
bomb.setVelocity(Phaser.Math.Between(-200, 200), 20);
```

Sorry for not following the requested format, but I didn't know a better way to report the error.  Thanks for the awesome platform and tutorials, really looking forward to diving in!

**Comment by theNeedle** [comment]
Actually we can't say that it's a bug. It creates one _bomb_ every time player collects all _stars_ . So, it's like you enter a new level with increase in difficulty. I think it's working as intended. 

You can report tutorial or example bugs/issues on [phaser3-examples repo](https://github.com/photonstorm/phaser3-examples).

**Comment by alextotheroh** [comment]
D'oh!  Sorry- didn't consider that.
