### ISSUE TITLE
Utils Array Add Uniqueness Bug

### ISSUE THREAD

**Issue by mudala** [photonstorm/phaser#4411]
## Version
Phaser Version: 3.15.1

## Description
`Phaser.Utils.Array.Add`'s behavior is incorrect when adding elements to an array in which they already exist.

Example:
```javascript
let a = [1, 2, 3];
Phaser.Utils.Array.Add(a, [1, 2, 4]);
console.log(a); // expected: [1, 2, 3, 4], actual: [1, 2, 3, 1]
```

This manifests itself when adding game objects to the display list through `scene.children.add`. If a game object has already been added to the scene's display list, and it is added again as a part of an array using `scene.children.add`, it can prevent valid game objects from being added.

### Direct example
```javascript
let a = [1, 2, 3];
Phaser.Utils.Array.Add(a, [1, 2, 4]);
console.log(a); // expected: [1, 2, 3, 4], actual: [1, 2, 3, 1]
```

### Game object example
```javascript
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        create: create,
    }
};

var game = new Phaser.Game(config);

function create() 
{
    let text1 = this.make.text({ y: 0,  text: 'Text 1' }, true);
    let text2 = this.make.text({ y: 20, text: 'Text 2' }, false);
    let text3 = this.make.text({ y: 40, text: 'Text 3' }, false);

    this.children.add([text1, text2, text3]);
}
```
The expected behavior here is to see all three text objects. The actual result is `text1` being added twice and `text2` being added once, while `text3` is not added at all.

## Additional Information
The problematic code is here: https://github.com/photonstorm/phaser/blob/04080bc1bab46834e4e9947a17905c1be0d5560b/src/utils/array/Add.js#L75

A quick fix is to replace `item.pop();` with `item.splice(itemLength, 1);`.

`item.pop();` is incorrect because the duplicate item is not always in the last position of the array!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
