### ISSUE TITLE
Scene tilemapTiledJSON not Working outside of 'Create'

### ISSUE THREAD

**Issue by ArronFerguson** [photonstorm/phaser#4412]
I'm using Phaser 3.16.2 and adapting a code example from:

https://www.dynetisgames.com/2018/02/24/manage-big-maps-phaser-3/

Which uses Phaser 3.1.0. The call in question is a call to Scene.load.tilemapTiledJSON.

The 3.1.0 version loads outside of create however somewhere along the way tilemapTiledJSON does not actually load anything. I noticed in the docs for Phaser 3 that it states that the "file is not loaded right away. It is added to a queue ready to be loaded either when the loader starts, or if it's already running, when the next free load slot becomes available". But the file is never loaded again and subsequent calls to it do not load either.

I think this is a bug.

**Comment by ArronFerguson** [comment]
Been looking into the code of this example app and the code. I've got the input wired into the cursors keys (i.e., cursors.keys.isDown) in the update method of the scene.

At some point TileMap objects are being detached from their respective scene objects. Still looking more into why this is. Not sure if it's in the BaseCache or some other object.

**Comment by photonstorm** [comment]
Any files can be loaded at any point, as long as the Loader is handled properly. There are [several examples](http://labs.phaser.io/index.html?dir=loader/loader%20events/&q=) of this in the labs. If you find a bug, please post an example that replicates it cleanly and which can be debugged here.

**Comment by ArronFerguson** [comment]
I pretty much just did: the tutorial code that works perfectly with an older version of 3.x where the stated newer version breaks. You can do with that what you want.

**Comment by photonstorm** [comment]
A link to a tutorial isn't a test case.
