### ISSUE TITLE
setScaleMode won't take effect

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#4413]
I think currently this feature is not availabe yet right? as I found that Components.ScaleMode is not used anywhere for example in pipeline.

**Comment by jcyuan** [comment]
example

    const obj = this.add.image(....);
    obj.scaleMode = Phaser.ScaleModes.NEAREST;
    obj.setScale(100, 100);   // test

no change, still LINEAR mode.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
