### ISSUE TITLE
Arcade physic of two immovable colliding objects not working

### ISSUE THREAD

**Issue by CipSoft-Components** [photonstorm/phaser#4415]
## Version

* Phaser Version: 3.16.2

* Operating system: Windows 10

* Browser:

## Description

Two immovable objects with collidation set between them, do not collide at all. If collidation is set only to one of them, it move the other object.
In my case, I have a player character, and enemies which move towards the player. The two should collide with each other, but not be able to move the other.

## Example Test Code

Here a codepen with the different cases: [https://codepen.io/anon/pen/gEWdrL](https://codepen.io/anon/pen/gEWdrL)

**Comment by samme** [comment]
This is expected, because a collision can be be resolved only by moving at least one of the bodies.

**Comment by CipSoft-Components** [comment]
Than, how can I make two objects collide, without pushing/moving each other? Or is this not possible with the physic engine in phaser?

**Comment by samme** [comment]
Here is one possibility: <https://codepen.io/samme/pen/NEwGeJ>

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

Please see the new `Body.pushable` property and corresponding documentation.
