### ISSUE TITLE
Bug: `fixedWidth` and `fixedHeight` does not change the size of Text object

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4424]
## Version
* Phaser Version: 3.16.2
* Browser: Chrome/firefox

## Description

Parameters `fixedWidth` and `fixedHeight` will change the size of Text object only in method `Text.setFixedSize(width, height)` ([set width](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/TextStyle.js#L662), [set height](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/TextStyle.js#L667)).
It won't change the size of text if `fixedWidth` and `fixedHeight` are passed in the configuration of creating this Text object, like
```javascript
var gameObject = scene.add.text(x, y, text, {
    // ...
    fixedWidth: 200,
    fixedHeight: 50
    // ...
});
```

(BTW, the width and height of this text object will be `1` in this case.)

## Example Test Code

[codepen](https://codepen.io/rexrainbow/pen/gEXZaq), see the result in console.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
