### ISSUE TITLE
Facebook plugin "chooseContext" method type issue

### ISSUE THREAD

**Issue by krzysztof-grzybek** [photonstorm/phaser#4425]
## Version

* Phaser Version:

3.16.2
* Operating system:

N/A
* Browser:
N/A

## Description

Method argument is named `contextId`, though it should be `options` object

## Example Test Code

`this.facebook.chooseContext(options)`

## Additional Information

I can add proper types, but I have some doubts. This object could could be represented in TS like:
```
chooseContext(options?:{ filters?: 'NEW_CONTEXT_ONLY' | 'INCLUDE_EXISTING_CHALLENGES' | 'NEW_PLAYERS_ONLY', minSize?: number, maxSize: number})
```

I didn't found any way to define optional object properties without using` @typedef`. Should we add new file into `src/core/typedefs`?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
