### ISSUE TITLE
Animation's delayedPlay fires "animationstart" immediately

### ISSUE THREAD

**Issue by bdaenen** [photonstorm/phaser#4426]
## Version
* Phaser Version: v3.16.2-FB
* Operating system: Any

## Description
When calling `physicsSprite.anims.delayedPlay(delay, key)`, the `animationstart` event is immediately fired. I expect it to be fired as soon as the animation actually starts (after the delay).

## Example Test Code
https://jsbin.com/rupolepume/edit?js,output

## Additional Info
I looked into making a PR for this, but since it seems to work by actually starting the animation and setting `nextTick += delay` I'm not sure how to proceed.

**Comment by LoolzRules** [comment]
Not sure that this is an actual problem. As a workaround, I would suggest to use delay by using setTimeout(startAnimation, delay).

**Comment by bdaenen** [comment]
That's exactly what I did for now, it just took me some time to figure out why my code wasn't working as I expected it to.

It's not something very urgent or serious, just something unintuitive, causing confusion.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

`Animation.delayCounter` is a new property that allows you to control the delay before an animation will start playing. Only once this delay has expired, will the animation `START` events fire.
