### ISSUE TITLE
GameObject - Graphics missing screenshots

### ISSUE THREAD

**Issue by DylanC** [photonstorm/phaser#4431]
https://labs.phaser.io/index.html?dir=game%20objects/graphics/&q=

GET https://labs.phaser.io/screenshots/game%20objects/graphics/Line%20Rendering.png 404 (Not Found) 
GET https://labs.phaser.io/screenshots/game%20objects/graphics/Multiple%20Graphic%20Objects.png 404 (Not Found)
GET https://labs.phaser.io/screenshots/game%20objects/graphics/Trail.png 404 (Not Found)

**Comment by photonstorm** [comment]
Thanks for opening the issue. New batches of screenshots are generated when we publish new releases. So am happy to leave these as-is for now.
