### ISSUE TITLE
Physics Arcade - missing screenshots

### ISSUE THREAD

**Issue by DylanC** [photonstorm/phaser#4432]
https://labs.phaser.io/index.html?dir=physics/arcade/&q=

`GET https://labs.phaser.io/screenshots/physics/arcade/body%20stack%20test%203.png 404 (Not Found)
GET https://labs.phaser.io/screenshots/physics/arcade/body%20stack%20test%202.png 404 (Not Found)
GET https://labs.phaser.io/screenshots/physics/arcade/basic%20platform.png 404 (Not Found)
GET https://labs.phaser.io/screenshots/physics/arcade/body%20stack%20test%204.png 404 (Not Found)
GET https://labs.phaser.io/screenshots/physics/arcade/body%20stack%20test%205.png 404 (Not Found)
GET https://labs.phaser.io/screenshots/physics/arcade/body%20stack%20test%205B.png 404 (Not Found)
GET https://labs.phaser.io/screenshots/physics/arcade/body%20stack%20test.png 404 (Not Found)
GET https://labs.phaser.io/screenshots/physics/arcade/fps%20test.png 404 (Not Found)
GET https://labs.phaser.io/screenshots/physics/arcade/get%20bodies%20within%20rectangle.png 404 (Not Found)`

**Comment by photonstorm** [comment]
Thanks for opening the issue. New batches of screenshots are generated when we publish new releases. So am happy to leave these as-is for now.
