### ISSUE TITLE
Physics Matter.js - missing screenshots

### ISSUE THREAD

**Issue by DylanC** [photonstorm/phaser#4433]
https://labs.phaser.io/index.html?dir=physics/matterjs/&q=

`GET https://labs.phaser.io/screenshots/physics/matterjs/draw%20chain.png 404 (Not Found)
GET https://labs.phaser.io/screenshots/physics/matterjs/draw%20smoother%20stiff%20line.png 404 (Not 
GET https://labs.phaser.io/screenshots/physics/matterjs/draw%20stiff%20line.png 404 (Not Found)
GET https://labs.phaser.io/screenshots/physics/matterjs/draw%20triangles.png 404 (Not Found)`

**Comment by photonstorm** [comment]
Thanks for opening the issue. New batches of screenshots are generated when we publish new releases. So am happy to leave these as-is for now.
