### ISSUE TITLE
Moving scene and Multi demo not working

### ISSUE THREAD

**Issue by DylanC** [photonstorm/phaser#4434]
Moving scene
https://labs.phaser.io/boot.html?src=src\scenes\moving%20scenes%20demo\boot.json
Multi
https://labs.phaser.io/boot.html?src=src\scenes\multi%20demo\boot.json

Both have same error:
`GET https://labs.phaser.io/Controller.js?_=1552777020448 404 (Not Found)
Uncaught SyntaxError: Unexpected token <`

**Comment by xavax31** [comment]
same problem for me on mac. 
The reason in the \ in boot.json path. If I replace them by /, that's work.
The problem is present in many examples in scenes folder

**Comment by xavax31** [comment]
Problem resolved for me by modify the file boot.html in window.load function, but may be that"s not the original cause:
```
    window.onload = function ()
    {
       // replace: var filename = getQueryString('src') by:
        var filename = getQueryString('src').replace(/\\/g, "/");
...
}
```

Note this is for labs.phaser.io site. For phaser.io/examples/v3, there is a problem too, but it seems not be the same, and I have not found solution:
<img width="590" alt="Capture d’écran 2019-08-26 à 21 12 40" src="https://user-images.githubusercontent.com/4051022/63716510-7d7b2880-c846-11e9-9947-6a6edf7e4804.png">

**Comment by photonstorm** [comment]
Thank you for reporting a problem with this example. It has now been fixed. You can find the updated version in this repo and on the labs.phaser.io site.
