### ISSUE TITLE
Overlaps with static bodies shouldn't cause blocking

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#4435]
Authors may want to check for overlaps with static bodies. That seems to be a valid use. But a positive overlap with a static body also gives positive results for `onFloor()`, `onCeiling()`, `onWall()`, via `blocked`, [which is probably not wanted](https://phaser.discourse.group/t/body-onfloor-true-when-overlapping-with-staticgroup-body/1746). (#3691)

Proposal: Body–body overlaps never set `blocked`.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
