### ISSUE TITLE
Remove scene from scene list, but error throws.

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#4436]
Phaser 3.16.2

step:
1, mouse down on an image
2, call myScene.destroy() -> inside the destroy method, there is `this.scene.remove(this)`
3, but it seems that the inputPlugin of this scene still handle the UP event, see the pic below:

![image](https://user-images.githubusercontent.com/850854/54680968-2b6f0200-4b46-11e9-8297-beb990160481.png)

**Comment by jcyuan** [comment]
ah, yes, I have called `this.input.destroy();` first, because I have read from the source code and found from the comment: ` A scene level Input Manager Plugin.`

do I need to call this?

**Comment by photonstorm** [comment]
`InputPlugin.destroy` will be called automatically when the Scene is shut down. Calling it before that point will cause all kinds of fun side-effects.

**Comment by jcyuan** [comment]
Ok thank you Richard, I just modified my code as this, and it seems works now:

![image](https://user-images.githubusercontent.com/850854/54683728-5c066a00-4b4d-11e9-817e-99c3bcf56776.png)

**Comment by photonstorm** [comment]
I would have thought you'd want to call `this.sys.destroy()`, as you seem to be destroying lots of other stuff? Also the events, tweens, display list, etc will all be cleared and destroyed automatically if you do.

**Comment by jcyuan** [comment]
yes, I want to completely destroy a scene, for example, the game boot splash, tutorial screen etc, these stuff will only be used once.

in `system.destroy` method I found the code only set them as null but does not call destroy.
so I manually call them in my `destroy` method.

**Comment by jcyuan** [comment]
actually the `scene.sys.destroy` will be auto called if you call `sceneManager.remove(scene);`
I wanna make sure that only call `systems.destroy()` is enough to completely destroy a scene or not...

**Comment by photonstorm** [comment]
`system.destroy` emits the DESTROY event, which is what all the plugins (like tween, input, etc) listen for.

**Comment by jcyuan** [comment]
got it, I'll check this again and give the feedback later, thank you so much Richard.

**Comment by jcyuan** [comment]
seems work fine! thanks man~~

**Comment by jcyuan** [comment]
@photonstorm Hi man, have to re-open this, now I only call sys.destroy(), all things will be destroied as I thought, but if you call scene.destroy in a Click event, it will throw error, MOUSE_UP want's to deal with the `game` member (cause actually the input.destroy was called but UP still wants to be emitted)......

![image](https://user-images.githubusercontent.com/850854/55390617-23618a00-556a-11e9-8585-7b84bbcc0fb7.png)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
