### ISSUE TITLE
Dragging an object in a rotated container does not work as expected

### ISSUE THREAD

**Issue by aliblong** [photonstorm/phaser#4437]
## Version

* Phaser Version: 3.16.2

* Operating system: Windows 10

* Browser:

## Description

Dragging an object in a rotated container does not work as expected. The `dragX` and `dragY` parameters to the `'drag'` input function correctly account for the `x` and `y` position of the container, but not its `rotation`.  As a result, when dragging from a rotated container using the typical `object.x = dragX; object.y = dragY;`, the object will not follow the cursor. Furthermore, it is not sufficient to perform 2D vector rotation on the inputs, i.e.: 
```
gameObject.x = dragX * Math.cos(rot) + dragY * Math.sin(rot);
gameObject.y = dragY * Math.cos(rot) - dragX * Math.sin(rot);
```
because it will cause the initial position of the object to jump to a predictable location. I imagine the workaround would have to somehow involve the cursor position on `'dragstart'`, which is doable, but not ideal compared to a hypothetical implementation that automatically accounted for the rotation in the `dragX` and `dragY` parameters.

## Example Test Code

```
// Class definitions elided so as not to clutter the example, but I can try to
// provide a complete, self-contained, working example if you think it's necessary.
const obj = new objectThatInheritsFromGameObject(this, {});
const cont = new objectThatInheritsFromContainer(this, {rotation: Math.PI});
this.add.existing(obj);
obj.setInteractive();
cont.add(obj);
this.input.setDraggable(card);
this.input.on('drag', (pointer, gameObject, dragX, dragY) => {
    gameObject.x = dragX;
    gameObject.y = dragY;
});
```
## Additional Information

[Naive drag](https://i.imgur.com/fUb1R4W.gifv)
[Drag with trigonometric transformation](https://i.imgur.com/vGWg3eX.gifv)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
