### ISSUE TITLE
Would you like to support wechat mini game development ^_^

### ISSUE THREAD

**Issue by LittleBoy1993** [photonstorm/phaser#4438]
First thanks for this game engine, I think it is so great!
I am a developer from China, may be you do not know the wechat mini game, In China many developer develop game for this, it is like facebook instant game. So i hope you can support wechat mini game and this will help us a lot, forgive my english is not well. ^_^
This is the document for wechat mini game develop. https://developers.weixin.qq.com/minigame/en/dev/index.html?t=18121023

So hope you apply and have a nice day. Thanks!

**Comment by photonstorm** [comment]
Thank you. We will look at this, although to be honest I would like the community to add support for this to Phaser, because it feels like something that needs to be driven by those who use wechat (as we cannot use it here)
