### ISSUE TITLE
Expose Phaser.Physics.Arcade.Components to the user

### ISSUE THREAD

**Issue by jackfreak** [photonstorm/phaser#4440]
I was trying to implement my own GameObject using as a base Phaser.GameObjects.Zone. My new GameObject needs a body (arcade) so I'm using scene.physics.add.existing(this, true).

No problem there. But I wanted to decorate that GameObject with Phaser.Physics.Arcade.Components.Enable and others and I found that the Arcade Components are not exposed in Phaser.Physics.Arcade.

https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/index.js 

It would be great to be able to use them (and all other internal components too). :)

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
