### ISSUE TITLE
Any plans on adding 3D support?

### ISSUE THREAD

**Issue by sagar1garg** [photonstorm/phaser#4441]
Would love to be able to build 3D games with phaser. @photonstorm

**Comment by photonstorm** [comment]
This is possible using a combination of three.js and the Extern Game Object (as can be seen in the Phaser 3D class published to Patreon this week) - but there are no further plans to add 'native' (i.e. home-grown) 3D support into Phaser at this time. Honestly, we just don't have the bandwidth to cope with such a massive undertaking.
