### ISSUE TITLE
Camera setLerp doesn't affect transition

### ISSUE THREAD

**Issue by denvaar** [photonstorm/phaser#4443]
## Version

* Phaser Version: 3.16.2

* Operating system: Mac OSX Mojave

* Browser: Google Chrome 72.0.3626.121 (Official Build) (64-bit)

## Description

The documentation for `setLerp` reads:

> The default values of 1 means the camera will instantly snap to the target coordinates. A lower value, such as 0.1 means the camera will more slowly track the target, giving a smooth transition.

However, when I use a value less than 1.0, the camera still immediately snaps to the new object. This is also the case if lerpX and lerpY values are provided via `setFollow`. So, these values don't appear to change anything about how the camera moves to follow an object.

## Example Test Code

Example demo can be found here: https://github.com/denvaar/camera-lerp-bug-demo

**Comment by samme** [comment]
I think you're seeing the intended behavior, but perhaps Phaser could add an `immediate` argument that could control that.

You could also get that effect by tweening the camera's `scrollX` and `scrollY`.

**Comment by photonstorm** [comment]
This is working correctly. `setLerp` applies interpolation to the camera position as it _tracks a moving target_. It has no impact on setting a target. The moment you call `startFollow` you tell the camera to immediately reposition itself onto the new target. The interpolation doesn't come into effect until the target moves, which it never does in your example.
