### ISSUE TITLE
Mouse input goes through overlay HTML

### ISSUE THREAD

**Issue by fobaz** [photonstorm/phaser#4447]
## Version
* Phaser Version: 3.16.2
* Operating system: Win10
* Browser: Chrome and Firefox

## Description
Mouse input on overlayed HTML elements goes through the overlay. For example, if there is an interactive sprite underneath the DOM button, clicking the button also triggers sprite's pointerdown event. Bug does not exist on 3.15.1.
On Chrome mouse down events sometimes gets handled twice on a single click. 
Tried playing with various settings (input.globalTopOnly, input.useQueue, input.addDownCallback()), but couldn't manage to make it work properly.

## Example Test Code 
```
<head>
   <style type="text/css">
    #ui{
      position: absolute;
      top: 0;
      left: 0;
      width: 50%;
      height: 100%;
      background-color: rgba( 0,0,0,0.3); 
    }
    button{
      height: 200px;
    }
    </style>
  </head>
  <body>
    <div id="game"></div>
    <div id="ui">
      <button onclick="alert('TEST'); ">test</button>
    </div>
    <script src="bundle.js"></script>
  </body>

```

## Additional Information
I guess, it's the same issue: https://phaser.discourse.group/t/click-on-div-under-phaser-object/1656/13

**Comment by LoolzRules** [comment]
Did you try to use event.stopPropagation()? For your example:
in HTML: `<button` onclick="buttonOnClick()">test</button>`
in code: `function buttonOnClick(event) {
  event.stopPropagation()
  alert('TEST'); 
}`

**Comment by fobaz** [comment]
Tried `event.stopPropagation()`, didn't do anything, click still goes through and gets also handled by Phaser.

**Comment by LoolzRules** [comment]
So, you tried my code above with input.useQueue(false)?

As cited from https://photonstorm.github.io/phaser3-docs/Phaser.Input.InputManager.html#useQueue__anchor:
> Use the internal event queue or not?
> Set this via the Game Config with the inputQueue property.
> Phaser 3.15.1 and earlier used a event queue by default.

**Comment by fobaz** [comment]
Yes, I have tried `preventDefault()`. With `input.useQueue` set to `false` it's the same. With set to `true`, no input event listeners are called (it seems, Phaser does not register any input. The following callback gets called, with `input.useQueue = true`, but it also goes through overlay: (it's TypeScript)
```
    this.input.addDownCallback((ev:any) => {
      console.log(ev); //this works, but gets called no matter if clicked on overlay or canvas
      this.input.events.emit("pointerdown", ev); //listeners not triggered
      this.events.emit("pointerdown", ev); //listeners not triggered
      this.scene.getScenes(true).forEach( (scene) => {
        scene.input.emit("pointerdown", ev); //listeners not triggered
      });
    }, false);
```

To sum up: overlay works with 3.15.1, doesn't with 3.16.2. Tried:

- e.stopPropagation();
- e.preventDefault();
- input.useQueue = true/false
- config.inputQueue = true/false
and probably all combinations of these.

**Comment by samme** [comment]
You need to call stopPropagation() from the button's `mousedown` handler, not `click`. https://codepen.io/samme/pen/LvYrEo?editors=0010

**Comment by rgk** [comment]
Just want to state you might want to use stop stopPropagation() with `mouseup` too.

**Comment by photonstorm** [comment]
As @samme wrote above, this needs stopping in the correct handler.

**Comment by vikkio88** [comment]
if anyone ever needs this, I had the same issue, sort of, had a UI over a phaser canvas and the clicks were going through.
![2020-05-14_19-39](https://user-images.githubusercontent.com/248805/81977098-73da6080-9621-11ea-9bda-f22a03875585.png)
I solved doing this just before creating the game on the phaser bootstrap phase
```js
const uiRoot = document.getElementById('uiRoot');
for (const eventName of ['mouseup','mousedown', 'touchstart', 'touchmove', 'touchend', 'touchcancel']){
    uiRoot.addEventListener(eventName, e => e.stopPropagation());
}
```

**Comment by wexlt** [comment]
> if anyone ever needs this, I had the same issue, sort of, had a UI over a phaser canvas and the clicks were going through. ![2020-05-14_19-39](https://user-images.githubusercontent.com/248805/81977098-73da6080-9621-11ea-9bda-f22a03875585.png) I solved doing this just before creating the game on the phaser bootstrap phase
> 
> ```js
> const uiRoot = document.getElementById('uiRoot');
> for (const eventName of ['mouseup','mousedown', 'touchstart', 'touchmove', 'touchend', 'touchcancel']){
>     uiRoot.addEventListener(eventName, e => e.stopPropagation());
> }
> ```

Worked!

**Comment by vikkio88** [comment]
happy to help my friend @wexlt

**Comment by CodeDeyya** [comment]
> happy to help my friend @wexlt

Hey pal can I please know how to do it on react. Currently when I click on dialog boxes on react it triggers game click events :/

**Comment by vikkio88** [comment]
@CodeDeyya it's explained in my comment [here](https://github.com/photonstorm/phaser/issues/4447#issuecomment-628842367)

**Comment by CodeDeyya** [comment]
@vikkio88 Yes I added it to the react as follows

   const overlay = React.useRef();

    useEffect(() => {

        // This is ok
        if (overlay && overlay.current) {
            for (const eventName of ['mouseup', 'mousedown', 'touchstart', 'touchmove', 'touchend', 'touchcancel']) {
                overlay.current.addEventListener(eventName, e => {
                    e.stopPropagation()
                    console.log("stopped propagation")
                });
            }
        }
    })

But now the event does not propagate to the canvas if I first click anywhere and then click again. The first click still propagates.

**Comment by vikkio88** [comment]
I see @CodeDeyya, I do that outside react, before the root node is mounted example

I do it in here https://github.com/vikkio88/downara/blob/master/src/phaser/index.js#L16

and the react app mounts here https://github.com/vikkio88/downara/blob/master/src/index.js#L30

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/event-stoppropagation-works-for-pointerdown-but-not-for-pointer-up/11933/1
