### ISSUE TITLE
Text interactive wrong area when calling setFontSize() after setInteractive()

### ISSUE THREAD

**Issue by thanh-taro** [photonstorm/phaser#4456]
## Version

* Phaser Version: 3.16.2-FB

* Operating system: Mac OS Mojave 10.14.4

* Browser: Chrome v73.0.3683.86 (Official Build) (64-bit)

## Description

Text interactive wrong area when calling setFontSize() after setInteractive()

## Example Test Code

```js
var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: { create: create }
};

var game = new Phaser.Game(config);

function create ()
{
    var text = this.add.text(10, 50, 'hover me and watch the cursor change');
    text.setInteractive({ cursor: 'pointer' });
    text.setFontSize(22);
}

```

## Additional Information

I think the reason is the interactive area did not update when changing font size.

**Comment by thanh-taro** [comment]
No one cares?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
