### ISSUE TITLE
`static` is a reserved keyword in coming ES standard

### ISSUE THREAD

**Issue by m31271n** [photonstorm/phaser#4458]
`static` is a reserved keyword in coming ES standard, `npm run distfull` will cause an error when using new version of Babel.

There are two places should be fixed - [here](https://github.com/photonstorm/phaser/blob/14781003b313481a76a941263dac894a358beaef/src/physics/arcade/components/OverlapRect.js#L23) and [here](https://github.com/photonstorm/phaser/blob/14781003b313481a76a941263dac894a358beaef/src/physics/arcade/ArcadePhysics.js#L567).

Related Information:
+ testing branch: master

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release.
