### ISSUE TITLE
Adding a new frame with the same name as an existing frame to Texture results in incorrect frame count

### ISSUE THREAD

**Issue by BigZaphod** [photonstorm/phaser#4459]
Phaser: 3.16.2

`Texture`'s `add()` function to add a new frame increments the texture's `frameTotal` variable even if the given name already exists in the texture. It doesn't check to make sure the name is actually unique first. The code probably should just check for this case before deciding to increment the counter.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
