### ISSUE TITLE
Texture has no way to remove an existing Frame

### ISSUE THREAD

**Issue by BigZaphod** [photonstorm/phaser#4460]
Phaser: 3.16.2

`Texture` does not have a function to remove an existing frame, and `Frame`'s `destroy()` function does not appear to remove the `Frame` instance from the source texture, either.

**Comment by photonstorm** [comment]
True. This is a highly unusual requirement though.

**Comment by BigZaphod** [comment]
I only discovered this when looking for a workaround for #4459. I was procedurally generating an atlas, and the way I had stuff working ended up causing it to re-add the same frame names to the CanvasTexture again as part of that process.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
