### ISSUE TITLE
Destroying a Texture does not remove the key from the TextureManager

### ISSUE THREAD

**Issue by BigZaphod** [photonstorm/phaser#4461]
Phaser: 3.16.2

This might be intentional, but `Texture`'s `destroy()` function does not actually remove the texture's key from the `TextureManager`. I see where this might cause some kind of infinite loop (if not properly handled) if the texture is removed by name using `TextureManager`'s `remove()` function, but it seems like it should work both ways here. I was bitten by this, anyway!

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
