### ISSUE TITLE
Frame's `x` and `y` properties are always 0

### ISSUE THREAD

**Issue by BigZaphod** [photonstorm/phaser#4462]
Phaser: 3.16.2

`Frame` has an `x` and `y` property, but they don't appear to ever be set to anything except 0. Tracing through the code, I see the constructor eventually calls `setSize(width, height, x, y)` which then does a bunch of configuration using the given x and y (setting `cutX` and `cutY`, for example), but `this.x` and `this.y` never seem to change. I'm guessing something here is vestigial, but I don't know what.

**Comment by photonstorm** [comment]
These are set in the `setTrim` method, so you won't see them change unless you're using a trimmed atlas frame. They _are_ needed, however.
