### ISSUE TITLE
Camera follow with roundPixels and game zoom

### ISSUE THREAD

**Issue by Antriel** [photonstorm/phaser#4464]
Phaser 3.16.2

Round pixels seems entirely broken. https://github.com/photonstorm/phaser/blob/v3.16.2/src/cameras/2d/Camera.js#L748-L752 should probably also round `sx` and `sy`. That might put it outside of clamp range, but rounding it before clamp could result in non-rounded values.

Furthermore the way worldView is calculated creates another assumption, that canvas size is divisible by zoom * 2 (other sizes would end up with non-integer worldView position a cause issues). That could probably be avoided with a well placed rounding too.

Related issues:
https://github.com/photonstorm/phaser/issues/4391
https://github.com/photonstorm/phaser/issues/3836

**Comment by photonstorm** [comment]
Forgot to close this issue, but was updated in https://github.com/photonstorm/phaser/commit/1df4661487904deb92246ba31865180f79eab6ad#diff-fe2c70d5b6baaae99dd2740d8d9a25af1ef13e2ef8f64f3bbd3790f249e83080 so that both sx/sy and worldView are rounded now.
