### ISSUE TITLE
hitArea inside container scrolls even when container has scrollFactor(0)

### ISSUE THREAD

**Issue by pinkkis** [photonstorm/phaser#4466]
## Version

* Phaser Version: 3.16.2

* Operating system: Win 10

* Browser: Chrome (latest)

## Description

* Create a container with scrollFactor(0)
* add an element inside with setInteractive()
* scroll camera
-> element stays in place, but interactive hitarea has scrolled with camera movement

## Example Test Code

Here's a quick example: 
https://jsbin.com/jizijaqote/edit?js,output

In the example, every time you hover over the element, the camera is scrolled down a bit, so you can eventually see the hit area move above the image

**Comment by LoolzRules** [comment]
I've looked through your example ad found out that manually setting `sprite.setScrollingFactor(0)` solves your problem, so it can be used as temporary workaround

**Comment by photonstorm** [comment]
The `Container.setScrollFactor` method now has an optional argument `updateChildren` which can be used to do this directly.
