### ISSUE TITLE
Multi scene bug in HEADLESS mode

### ISSUE THREAD

**Issue by AndreaBoeAbrahamsen** [photonstorm/phaser#4467]
## Version 
* Phaser Version: 3.16.2
* Operating system: Windows 8

## Description

When running phaser in headless mode and having more than one scene, Phaser throws the error "Cannot read property 'gl' of null" in the prerendering function. It seems to be calling the wrong functions in headless mode when there is more than one scene. 

Headless mode is great for running multiplayer games on the server, and I love to split up the game in multiple scenes, so fixing this bug would be greatly appreciated. 

## Example Test Code

https://codesandbox.io/s/llj8y70l0z

## Additional Information

![image](https://user-images.githubusercontent.com/9437230/55822021-09422180-5aff-11e9-93bc-e19674d02160.png)

**Comment by samme** [comment]
I think it’s not multiple scenes per se but scene destroy, which is calling camera destroy.

**Comment by MrSplinter** [comment]
I have the same problem right now. FeelsBadMan

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
