### ISSUE TITLE
drawing confusion when create rounded rectangle (3.16.2) on Huawei Mate 10

### ISSUE THREAD

**Issue by baidan4855** [photonstorm/phaser#4468]
a line from the left top corner of canvas to each corner of the rounded rectangle. 
only appears on Huawei phone
as follow
![WechatIMG74](https://user-images.githubusercontent.com/10466275/55883067-37476480-5bd8-11e9-80bc-549a88859d15.jpeg)

**Comment by photonstorm** [comment]
Fixed as a result of https://github.com/photonstorm/phaser/commit/559127a53fdb9bd7d22c929b2800bd892fec472a
