### ISSUE TITLE
All children of a Container should have scroll factor 0

### ISSUE THREAD

**Issue by enriqueto** [photonstorm/phaser#4475]
When using a container it should be enough to set scroll factor 0 for all its children to remain fix to the camera.

Now I need to do child.setScrollFactor(0) for every child.

**Comment by photonstorm** [comment]
This brings up an interesting dilemma though. Should a Container `scrollFactor` override whatever the child has set? Or be added to it? (in the same way alpha does), especially as Containers don't have to be an exclusive parent.

**Comment by enriqueto** [comment]
Override would work for me. I basically use Containers for game menus.

**Comment by photonstorm** [comment]
I guarantee this is a 50/50 thing. What works for you will annoy the other 50% who'd expect scrollFactors to be combined, rather than replaced.

**Comment by photonstorm** [comment]
The `Container.setScrollFactor` method now has an optional argument `updateChildren` which can be used to do this directly.
