### ISSUE TITLE
accelerationFromRotation, Angle, Math help etc.

### ISSUE THREAD

**Issue by BluePC1** [photonstorm/phaser#4477]
Hi everyone!!
I'm new to phaser & know nothing about JS so don't hate on me. ;)

I'm trying to start myself off with a really basic asteroids game. When I imported an image of a space ship into the game I quickly realized that the spaceship character I had imported was facing upwards, kinda like this:

l__^__l

When really, it's meant to be facing the side;

--
>>>>
--
Excuse my bad drawings. Anyway, I'm basically trying to create this:

https://phaser.io/examples/v2/arcade-physics/asteroids-movement

But because of my spaceship being imported facing up, the code treats the spaceship as if the side of it is the front so when its at a 90 degree angle, it goes downwards, with its, right side facing +y.

Level.prototype.update = function() {
	
    space_bar = this.input.keyboard.addKey(Phaser.Keyboard.SPACEBAR);
    left = this.input.keyboard.addKey(Phaser.Keyboard.LEFT);
    right = this.input.keyboard.addKey(Phaser.Keyboard.RIGHT);
    up = this.input.keyboard.addKey(Phaser.Keyboard.UP);
    down = this.input.keyboard.addKey(Phaser.Keyboard.DOWN);
    
	if (left.isDown){
        this.fPlayer.body.angularVelocity = -200;
    }
    else if (right.isDown){
        this.fPlayer.body.angularVelocity = 200;
    }
    else {
        this.fPlayer.body.angularVelocity = 0;
    }
	
	this.angle_fPlayer = 0;
	this.angle_fPlayer = this.fPlayer.rotation;
	this.angle_fPlayer += 90;

    if (up.isDown){
        this.physics.arcade.accelerationFromRotation(this.angle_fPlayer, 200, this.fPlayer.body.acceleration);
    }
    else if (down.isDown){
        this.physics.arcade.accelerationFromRotation(this.angle_fPlayer, -200, this.fPlayer.body.acceleration);
    }
    else {
        this.fPlayer.body.acceleration.set(0);
    }
};

As you can see in this code, I'm trying to have a variable that represents the spaceships angle + 90 degrees. But I'm held back because I've just realised that rotation, an angle are different. And so the spaceship goes at a weird angle when it flies.

How do I base the "accelerationFromRotation" on an angle rather than rotation?
Thanks
Blue

**Comment by photonstorm** [comment]
Honestly, it'd be much easier if you just loaded your sprite into an art package, rotated it and saved it. Otherwise, you're going to have to deal with the extra 90 degrees through-out all of your code, which is quite a pain imho.
