### ISSUE TITLE
Incorrect initial position of dom element 

### ISSUE THREAD

**Issue by sudhirquestai** [photonstorm/phaser#4478]
## Version

* Phaser Version: Master
* Operating system: Mac OS

* Browser: Chrome/Safari

## Description

I am trying to use dom elements using master code. I'm using scale manager with WIDTH_CONTROLS_HEIGHT. The scaling of the dom elements works fine. However the initial position of the dom elements is not correct. It is only correct if the initial width of the window matches the passed game width.If the initial width is different then the elements are to the left or right depending on initial window width. Once positioned the scaling works correctly with resize. 

## Example Test Code
I modified one of the examples in phaser labs on dom elements and I can reproduce this issue. Code below.

var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    parent: 'phaser-example',
    dom: {
        createContainer: true
    },
    scene: {
        preload: preload,
        create: create
    },
    scale: {
                parent: 'phaser-example',
                width: 500,
                height: 500,
                mode: Phaser.Scale.WIDTH_CONTROLS_HEIGHT,
                autoCenter: Phaser.Scale.CENTER_BOTH,
                expandParent: false
            },
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('einstein', 'assets/pics/ra-einstein.png');
}

function create ()
{
    this.add.image(250, 250, 'einstein');

    var div1 = document.createElement('div');
    div1.style = 'background-color: lime; width: 220px; height: 100px; font: 48px Arial; font-weight: bold';
    div1.innerText = 'Phaser 3';

    var element1 = this.add.dom(250, 250, div1);
}

## Additional Information

Looks like the intial dom element position is using the game size and not the window size.  The scaling part however works fine.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
Also, DOM Elements inside of Containers should now scale and position correctly.

**Comment by sudhirquestai** [comment]
Tested this fix. Works as expected. Thanks Rich!
