### ISSUE TITLE
Camera.ignore / except

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#4480]
let me introduce the situation:
I'm creating an animation splash scene, there is a lot of animation and camera effects like zoom shake pan, and I want to add a SKIP button on top of the screen...
yes you'll think that it's easy to solve...
I'm currently using the way of camera to solve: 

    cameras.add(btnX, btnY, btnW, btnH).setScroll(btnX, btnY);    // so only the btn is displayed in the second camera
    cameras.main.ignore(btn);

it works, but... the button corner is rounded, so the content of the main camera is still rendered in the second camera and you can see through from the corner.

and the other way: use another scene
this can solve the problem 'perfectly', but actually a little bit waste, it will create a few of plugins which are unnecessary because there is only 1 button will be added into the new scene...

so, I'm wondering is it possible to add a method similar with `ignore` to the camera class, like `camera.except`, so only the objects specified will be rendered?

this is only a thought, if it's not possible, I'll use the way of createing new scene for the button, I know you are really busy.   :smiley:

**Comment by jcyuan** [comment]
emmm, actually a bit contradictory.
because textures are globally cached, so in the new scene I only need to set the InputPlugin available like this:

        const key = 'tmpSkipScene';
        const sceneObj = {
            plugins: ['InputPlugin'],
            create: () => {
                this._skipScene = this.scene.scene.get(key);
                this._skipButton = this._skipScene.add.image(this.scene.scale.width - 260, this.scene.scale.height - 180, "home", "skipBtn").setDepth(99999).setAlpha(0).setOrigin(0);
                this.scene.tweens.add({
                    targets: this._skipButton,
                    alpha: 1,
                    ease: "Linear",
                    duration: 500,
                    onComplete: () => {
                        this._skipButton.setInteractive().on(Phaser.Input.Events.POINTER_UP, this.onSkip, this);
                    }
                });
            }
        };
        this.scene.scene.add(key, sceneObj, true);

and, yes this actually is acceptable.

**Comment by samid737** [comment]
Not something done usually, but you could select cameras using the camera ID:

https://github.com/photonstorm/phaser/blob/e82e7c6ba0214b1dd9a3a7211c0ebaa6d2797dca/src/cameras/2d/BaseCamera.js#L124

Maybe this example will help:

https://labs.phaser.io/edit.html?src=src\camera\camera%20filter.js

You could have the second camera ignore all objects first, afterwards apply the above example.

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
