### ISSUE TITLE
Phaser.Physics.Arcade.Events is not exported

### ISSUE THREAD

**Issue by danielalves** [photonstorm/phaser#4481]
## Version

* Phaser Version: 3.16.2

* Operating system: macOS High Sierra

* Browser: All

## Description

[Arcade Physics events constants](https://github.com/photonstorm/phaser/tree/master/src/physics/arcade/events) are not being exported in [Arcade Physics index file](https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/index.js), although they're declared as being visible in the [typescript types definition file](https://github.com/photonstorm/phaser3-docs/blob/master/typescript/phaser.d.ts).

## Example Test Code

This code will compile:

```js
import * as Phaser from 'phaser';

// ...

gameObject.on(Phaser.Physics.Arcade.Events.COLLIDE, () => {
  console.log('Collided!');
});
```

But will throw a runtime error like this one:

> TypeError: phaser__WEBPACK_IMPORTED_MODULE_0__.Physics.Arcade.Events is undefined

## Additional Information

This problem is quite easy to fix. We just need to add the following property to the [`Arcade` variable](https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/index.js#L21) in the [Arcade Physics index file](https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/index.js):

```js
Events: require('./events'),
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
