### ISSUE TITLE
Testing results of new intersect points methods

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4483]
## Version
* Phaser Version: 3.17

## Description

Here are some testing results of new intersect points methods.
- `LineToLine`, `GetLineToRectangle`, `GetRectangleToRectangle`, `GetRectangleToTriangle`, `GetTriangleToTriangle`
    Works fine
- `GetCircleToCircle`
    Can't find intersect point when `y0 === y1` ([Test code](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/test/GetCircleToCircle.js))
- `GetLineToCircle`, `GetCircleToRectangle`, `GetTriangleToCircle`
    When [`LineToCircle(...)`](https://github.com/photonstorm/phaser/blob/master/src/geom/intersects/GetLineToCircle.js#L28) return true, it should return 1 or more intersect points. But sometime it will return 0 point. ([Test code](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/test/GetCircleToRectangle.js))

**Comment by florianvazelle** [comment]
Hi, I saw your message on my PR and I think I forget a division in getCircleToCircle that gives a bad result. I corrected that on my side.
I am currently watching `GetLineToCircle`, `GetCircleToRectangle`, `GetTriangleToCircle`.

**Comment by photonstorm** [comment]
If it's easier for you to test from this repo @rexrainbow then let me know and I can merge the fork here.

**Comment by rexrainbow** [comment]
@florianvazelle
All fixed in my tests, thank you.

**Comment by photonstorm** [comment]
Excellent - could you submit a PR please @florianvazelle ?
