### ISSUE TITLE
setScale doesn't update synchronously the size of tileSprite body

### ISSUE THREAD

**Issue by iagorm** [photonstorm/phaser#4497]
## Version
* Phaser Version: 3.16.2
* Operating system: MacOS 10.14.4
* Browser: Version 73.0.3683.103 (Official Build) (64-bit)

## Description
When I create a tileSprite and set scale to 2 for example and try to get the body height, it returns me the value in original scale, tested with staticGroup and using refreshBody works like a charm, but doesn't fit my need.

## Example Test Code
The example is pretty simple:

```JS
        this.sprite = this.game.add.tileSprite(
            0,
            window.innerHeight - 200,
            window.innerWidth,
            109,
            'land'
        );
        this.game.physics.add.existing(this.sprite);
        this.sprite.setOrigin(0, 0);
        this.sprite.setScale(2);
        
        console.log(this.sprite.body); // will show the sprite body with correct height of 218
        console.log(this.sprite.body.height); // will return 109, but it should return the double of that value
```

## Additional Information

Follow screen shots for more details

<img width="161" alt="Screen Shot 2019-04-28 at 11 12 50" src="https://user-images.githubusercontent.com/13892132/56865728-8860a200-69a7-11e9-9e64-90a5e783e6ca.png">
<img width="113" alt="Screen Shot 2019-04-28 at 11 12 56" src="https://user-images.githubusercontent.com/13892132/56865729-8860a200-69a7-11e9-9202-b3ed3b0222ba.png">

**Comment by photonstorm** [comment]
This is the correct behavior. These values should not be updated until a physics step occurs. If you need to read them before this, you could do `Body.updateBounds()` first.
