### ISSUE TITLE
Adding spine to physics causes position to become NaN

### ISSUE THREAD

**Issue by hizzd** [photonstorm/phaser#4501]
## Version

* Phaser Version: 3.16.2

* Operating system: Windows

* Browser: Chrome

## Description
The GameObject created with scene.add.spine will cause the position of this GameObject to become NaN after being added to physics.

## Example Test Code
Open DevTools Console, you can see that the position is not NaN after the first update of spineA is called, but the position is changed to NaN after the second update is called.
After spineB sets displayOriginX and displayOriginY, position will not be changed to NaN.
https://codepen.io/hizzd/pen/LvopXW

## Additional Information
After my debug, I found that the GameObject created by scene.add.spine has no displayOriginX and displayOriginY attributes.
However, the displayOriginX and displayOriginY properties are read in the update method of physics/arcade/Body.js, so the position are changed to NaN.
https://github.com/photonstorm/phaser/blob/v3.16.2/src/physics/arcade/Body.js#L927-L928

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
