### ISSUE TITLE
after calling this.sys.game.destroy(true), all input events can't be detected and fired

### ISSUE THREAD

**Issue by bigblueblue** [photonstorm/phaser#4502]
## Version

* Phaser Version:  Phaser v3.16.2-FB(Canvas | WebAudio)

* Operating system:

* Browser: chrome

## Description

when window got resize, I call , and new Phaser.Game(), and 
```
this.sys.game.destroy(true)
let game = new Phaser.Game(config)
create: function () {
let logo = this.add.image(0, 0, 'logo').setInteractive()
logo.on('pointerdown', function () {
    console.log('click')
})
}
```
when i use mouse to click this, it doesn't fire the pointerdown

**Comment by photonstorm** [comment]
`Game.destroy` is asynchronous. You need to listen for the destroy event from Game before you can create another instance.

**Comment by bigblueblue** [comment]
> `Game.destroy` is asynchronous. You need to listen for the destroy event from Game before you can create another instance.

this.events.on('destroy', () => {})

**Comment by bigblueblue** [comment]
> `Game.destroy` is asynchronous. You need to listen for the destroy event from Game before you can create another instance.

this.events.on('destroy', () => {})

**Comment by bigblueblue** [comment]
> `Game.destroy` is asynchronous. You need to listen for the destroy event from Game before you can create another instance.

this.events.on('destroy', () => {})
thanks, I call this methods but this events has no arguments return. so i can't sure whether Game had totally destroyed, Can you talk more details? I am still learning phaser that't  not familiar yet. 
ps: i changed phaser vesion with 3.15.1 ,it's amazing to solve it.

**Comment by photonstorm** [comment]
You need to listen for it from the Game object itself, so from within a Scene do:

`this.game.events.on('destroy')`

There are no arguments. The very fact it is called means the game instance has been destroyed.

**Comment by photonstorm** [comment]
To continue this discussion please move to either the forum or Slack / Discord, thank you.
