### ISSUE TITLE
Make `Phaser.Physics.Matter.Factory.circle` parameters `options` and `maxSides` optional

### ISSUE THREAD

**Issue by schomatis** [photonstorm/phaser#4506]
Phaser's [`Factory.circle`](https://github.com/photonstorm/phaser/blob/40b325accfc5982be62d792705f569de4c95730b/src/physics/matter-js/Factory.js#L119) has `options` and `maxSides` as mandatory parameters while the underlying Matter.js' [`Bodies.circle`](https://github.com/photonstorm/phaser/blob/40b325accfc5982be62d792705f569de4c95730b/src/physics/matter-js/lib/factory/Bodies.js#L111) doesn't.

Happy to submit a PR about it but first wanted to make sure there wasn't an API design issue I'm missing.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
