### ISSUE TITLE
Physics Group with array doesn't add body.

### ISSUE THREAD

**Issue by rgk** [photonstorm/phaser#4511]
## Version
* Phaser Version: 3.16.2
* Operating system: Linux

## Description

When adding an array of items to a physics group, it does not add the body object etc... but it works when only adding a single config object.

## Example Test Code

https://labs.phaser.io/edit.html?src=src/physics/arcade/simple%20group.js <- This example works. If you replace the group variable with:
`    var group = this.physics.add.group(
        [
            {
                key: 'block',
                frameQuantity: 1,
            },
            {
                key: 'block',
                frameQuantity: 1,
            },
            {
                key: 'block',
                frameQuantity: 1,
            },
            {
                key: 'block',
                frameQuantity: 1,
            }
        ]
    );

    console.log(group.children.entries);`

As you can see no body.

## Additional Information

I might be doing something wrong but shouldn't a physics group always add a physics body?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
