### ISSUE TITLE
Avoid overloading the Arcade Physics overlap

### ISSUE THREAD

**Issue by schomatis** [photonstorm/phaser#4513]
The `overlap` magnitude computed by functions like [`GetOverlapY`](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.html#.GetOverlapY__anchor) is being overloaded in some corner cases by setting its value to `0`, not to indicate that the overlap distance in the Y axis is actually zero but just to signal a _do not process this overlap_ case.

https://github.com/photonstorm/phaser/blob/04080bc1bab46834e4e9947a17905c1be0d5560b/src/physics/arcade/GetOverlapY.js#L39-L42

(In itself this isn't really an important issue, it just makes it harder to reason about the code. A student was playing with the `setScale` method in the Phaser intro example to see his player go below the platform boundary and sink at the bottom. When going deeper into the Arcade engine to understand why the player wasn't "floating up", it found a puzzling `overlap` magnitude of `0` that didn't match what he was seeing in the game where the player fully overlapped with the platform.)

Ideally I think that logic could be extracted from the `GetOverlapY` (and similar) methods so a consumer like `SeparateY` would be the one to decide what to do, for example, when the non-zero `overlap` exceeds the `maxOverlap` limit (specified in `bias`, and hence `GetOverlapY` shouldn't care or even receive that argument).

The problem I see with this change, from my _very limited_ understanding of the code, is that the overlap is exported in [`overlapY`](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Body.html#overlapY__anchor) to be consumed by external overlap-processing logic (see [`customSeparateY`](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Body.html#customSeparateY__anchor)), so the above proposal would be an API-breaking change (although I would suppose that an external consumer of the `GetOverlapY` information would want to know the exact overlap before making the decision to separate or not, but at this point external code may already depend on the current behavior). If that is the case, I'll happily just submit a documentation PR to add some details about what conditions may set the overlap to zero.

**Comment by photonstorm** [comment]
While I agree with this change in principle, it's been this way for years now, so I'd rather not modify it at this stage, sorry.
