### ISSUE TITLE
Support loading via ES6 import of JSON and Image files

### ISSUE THREAD

**Issue by gnesher** [photonstorm/phaser#4515]
When loading a resource via load.tilemapTiledJSON / load.image we currently supply a path / url to the resource. As the resource is loaded during it's difficult to debug (game will compile and fail to run and the errors will not always be indicative of exactly where we failed)

I would suggest that we start support ES6 imports as an alternative - so instead of a command like:
```load.tilemapTiledJSON('map', 'assets/map.json');```

We could do :
```
import mapObj from '../../assets/map.json';
load.tilemapTiledJSON('map', mapObj);
```

This way errors will be caught during build time and make debugging much simpler.

As a side note tools like Webpack can separate said imports to individual files avoiding a longer than necessary initial load

**Comment by photonstorm** [comment]
Any Loader filetype that requires JSON can use an actual JSON object instead of a URL. Here's an example specifically for Tilemaps:

http://labs.phaser.io/view.html?src=src%5Cloader%5Ctile%20maps%5Cload%20tile%20map%20from%20local%20json.js

So the question then becomes, why doesn't your approach above return a proper JSON object?

**Comment by ampled** [comment]
Depending on how webpack is setup, doing an import of a json file can result in a valid javascript object, the actual JSON string or an url to the bundles json file itself, so this seems more like a webpack issue than a Phaser issue.

**Comment by photonstorm** [comment]
I'm going to close this off. As long as your build process returns valid JSON, it'll work, and there's nothing Phaser itself can do if that isn't returned really.
