### ISSUE TITLE
Passing frame as a Textures.Frame object to Bob.reset() doesn't work

### ISSUE THREAD

**Issue by NokFrt** [photonstorm/phaser#4516]
## Version

* Phaser Version: 3.16.2

* Operating system:

* Browser:

## Description

Passing frame as a Textures.Frame object to Bob.reset() doesn't work. Passing the same fame as a frame name works.

## Example Test Code
`resetBox(frame: Phaser.Textures.Frame, x: number, y: number): void {
	this._bob.reset(x, y, frame); // This DOES NOT WORK
	this._bob.reset(x, y, frame.name); // This WORKS
}`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
