### ISSUE TITLE
The default camera is destroyed on scene shutdown and never recreated

### ISSUE THREAD

**Issue by telinc1** [photonstorm/phaser#4520]
## Version
* Phaser Version: 3.17.0
* Operating system: Windows 7

## Description
The default camera of a scene (not the main camera, keep in mind) is created once, in the `boot` method of the Camera Manager, but it's destroyed when the scene shuts down. Because of this, restarting a scene (or stopping it, then starting it again later) will cause problems with anything which uses the default camera.

## Example Test Code
One of the features affected by this is camera masks with fixed positions, which will throw a seemingly unrelated error on rendering. [This pen](https://codepen.io/telinc1/full/gJMWGO) is a minimally modified version of [one of the examples](http://labs.phaser.io/view.html?src=src/display/masks/Camera Mask Test 1.js). Press R to restart the scene, which will fail (open the console to see the error).

If you change line 40 of the example ([here's a link to the editor view](https://codepen.io/telinc1/pen/gJMWGO)) to `this.cameras.main.setMask(mask1, false);`, the scene will restart properly because non-fixed masks do not rely on the default camera.

## Additional Information
Theoretically, fixing this should be as easy as destroying the default camera in `destroy` instead of `shutdown` of the Camera Manager.

**Comment by photonstorm** [comment]
Good catching! We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
