### ISSUE TITLE
Tween problem with v3.17

### ISSUE THREAD

**Issue by TonioParis** [photonstorm/phaser#4525]
With v3.17 this exemple ( http://labs.phaser.io/edit.html?src=src/tweens/paused%20tween.js&v=3.17.0 ) doesn't work. When I click on the box there is no tween.

**Comment by 16patsle** [comment]
Based on discussion on Discord it seems to be because of a change in tween.play(), possibly causing it to be stuck in a pending_add state.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
