### ISSUE TITLE
Unable to import global plugins

### ISSUE THREAD

**Issue by gnesher** [photonstorm/phaser#4533]
## Version
* Phaser Version: 3.16.2 (can also replicate on 3.17)
* Operating system: Windows
* Browser: N/A

## Description

I'm unable to import plugins into a scene. It works fine when I use a simple project without Typescript / Webpack but as soon as I move to a more complex build process the import fails. I've created an example using the most popular typescript boilerplate (https://github.com/digitsensitive/phaser3-typescript) which can be found here : https://github.com/gnesher/phaser-plugin-problem

There's no error thrown when I load the plugin from the game config, but when I try to get it within the scene it returns null and I can't act on any of it's properties

## Example Test Code

You do need to npm install - I couldn't create a simpler example, as the process works fine when I use a single file Phaser project
https://github.com/gnesher/phaser-plugin-problem

**Comment by samme** [comment]
You need to verify that the imported value is correct, e.g.,

    import VirtualJoyStickPlugin from "./rexvirtualjoystickplugin.min.js";
    console.log(VirtualJoyStickPlugin);

**Comment by gnesher** [comment]
Good catch - returns undefined, might want to throw an error when we pass that to the game object? shouldn't be difficult to validate and there's no reason not to through on this.

Should I close this and open another suggestion for error handling on import or should I leave this open?

I'll also ping the developer of the plugin to see what's up as the guide suggests importing the plugin.

**Comment by samme** [comment]
Sure, close this.

I can make a PR to add a warning for empty `plugin` values.

**Comment by gnesher** [comment]
Cheers
