### ISSUE TITLE
tween makes image vanish in 3.17 

### ISSUE THREAD

**Issue by SavedByZero** [photonstorm/phaser#4536]
I followed the example format precisely with tweens, I know the image I'm adding loads and adds itself to the screen and exists in the variable.  Yet when I tween it from 400,400 to 400,370 (values are stored in xml and checked in the debugger), all it does is vanish. 

```

    function executeStep(step)
    {
         var parts = step.innerHTML.replace(/\s+/gm,' ').split(" ");
            var location = parts[3].split(",");

            if (parts[0].toLowerCase() == "add")
            {
                var image = this.add.image(location[0],location[1], parts[1]);
                imagePool[parts[1]] = image;
            }
            else if (parts[0].toLowerCase() == "move")
            {
               var image = imagePool[parts[1]];
                var tween = this.tweens.add({
                    targets: image,
                     x: Number(location[0]),
                    y: Number(location[1]),
                    ease: 'Linear',
                    duration: Number(parts[5]),
                    delay: 200,
                    yoyo: false,
                    repeat: 0,
                    onComplete: function(){}
                });
            }
    }
```

**Comment by photonstorm** [comment]
Tweens are working in 3.17, or all these examples would be broken: http://labs.phaser.io/index.html?dir=tweens/&q= (and believe me, there would be hundreds of open issues reporting it too)

So, please create a reproducible test case (the above isn't without the xml data) and re-open if you can consistently recreate this, having validated the data passed to the tween is of the correct data type.
