### ISSUE TITLE
pointer events intermittently not registered

### ISSUE THREAD

**Issue by paulsymphony** [photonstorm/phaser#4538]
I believe this issue started when the new Input system was put in place in 3.16. I see the issue intermittently (but consistently) with different releases of phaser after 3.16. If I add the 'input' object to the config, and set 'queue:true', the issue goes away.

**Comment by jbgomez21** [comment]
Hi @paulsymphony 
I think I have the same problem, sometimes 'pointerup' event is not fired.
I don't understand your solution, can you give me a example?

Greetings

**Comment by paulsymphony** [comment]
Hi @jbgomez21 ,

My original post is incorrect regarding the version in which this changed: it's 3.16. If you read the changelog, you will find an explanation of the change to input events. I haven't isolated the condition yet, but I will work on an example to post. The temporary solution is to add an object to the game config parameters. Like this:

var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create,
        update: update
    },
  input: {
    queue:true
  }
};

var game = new Phaser.Game(config);

**Comment by jbgomez21** [comment]
Hi @paulsymphony thank you for your answer.
I still have the same problem using:

```
input: {
 inputQueue: true
}
```

I will be thoughtful about this issue!
My problem is with 'pointerup' event, sometimes there is that do three or four 'click' before this fired.

Samsung galaxy s10 and galaxy s10 plus with android 9.

![error](https://user-images.githubusercontent.com/3789684/58039093-20b1f880-7b08-11e9-91a8-92a26f9eb15b.jpg)

**Comment by GlantzDK** [comment]
@jbgomez21  use 
```
input: {
queue: true
}
```
, not 
```
input: {
inputQueue: true
}
```
 as typescript suggests

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by paulsymphony** [comment]
Tested - looks to be fixed!
