### ISSUE TITLE
if setPollAlways() 'pointerdown' will call two times

### ISSUE THREAD

**Issue by Neyromantik** [photonstorm/phaser#4541]
This print "Click" dooble shot if setPollAlways(). Is it OK?
```
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    scene: {
        create: create
    }
};

var game = new Phaser.Game(config);

function create ()
{
    this.input.setPollAlways();
    this.input.on('pointerdown', function () {
        console.log("Click");
    });

}
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
