### ISSUE TITLE
"Down" Events does not trigger in some cases

### ISSUE THREAD

**Issue by GlantzDK** [photonstorm/phaser#4543]
## Version
Phaser Version: 3.17.0
Operating system: Windows 10 
Browser: Edge, Chrome.

## Description
The "pointerdown" and "gameobjectdown" events do not trigger when the cursor has just enteret the object (about less than a quarter of a second)

Moving the cursor fast inside the object and clicking does also not trigger the events

## Example Test Code
It can be reproduced in the example:
https://labs.phaser.io/view.html?src=src\input\mouse\click%20sprite.js&v=3.17.0

Changing to earlier version fixes the problem

**Comment by photonstorm** [comment]
Yes, duplicate of #4538 - please track in that issue.
