### ISSUE TITLE
Custom Pipeline breaking Graphics Objects

### ISSUE THREAD

**Issue by Loonride** [photonstorm/phaser#4548]
## Version

* Phaser Version: 3.17.0

* Operating system: Windows 7

* Browser: Chrome

## Description

When I make a custom pipeline that extends the `TextureTintPipeline` and do `setPipeline` on some image with that pipeline, I can no longer see graphics objects added via `this.add.graphics`. In the project where I noticed it, there was a flickering effect where I could sometimes see the graphics object, and sometimes not. I wasn't able to reproduce the flickering in a small example, but I was able to show the graphics object not appearing in the repo below.

If I create the pipeline but do not do `setPipeline` on any graphics objects, no problem occurs.

Additionally, it seems that doing `setPipeline` on the graphics object itself causes the object to disappear.

Everything works fine in 3.15.0, but stops working at 3.16.0.

## Example Test Code

https://github.com/Loonride/phaser3-pipeline-graphics-issue

do:
```
npm install

npm start
```

What I see in 3.15.0:

![prob2](https://user-images.githubusercontent.com/22580625/58204995-2263f380-7ca3-11e9-9ebc-0366a94a1619.PNG)

What I see in 3.16.x, 3.17.0:

![prob1](https://user-images.githubusercontent.com/22580625/58204950-082a1580-7ca3-11e9-99bc-a460e9940882.PNG)

## Additional Information

None

**Comment by samid737** [comment]
Seems reproducable  in existing example (pointer events still work though, just the display):

http://jsfiddle.net/873k4gbe/

**Comment by samid737** [comment]
noticed they go through the same pipeline. @Loonride  , updating the shader to include the outTintEffect (like the default shader in https://github.com/photonstorm/phaser/blob/b649ec3783b82157e6460a78d15b3f698dc408bb/src/renderer/webgl/shaders/TextureTint-frag.js#L9) varying should show the Graphics objects, perhaps as a workaround:

http://jsfiddle.net/v7tzs3x2/

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
