### ISSUE TITLE
HTML5 video dom object breaks pointer events

### ISSUE THREAD

**Issue by paulsymphony** [photonstorm/phaser#4549]
## Version

* Phaser Version:
3.17, 31.8 (beta)

* Operating system:

iOS

* Browser:

Safari ( iOS 10.3.3 and iOS 12.3 tested )

## Description

After an HTML5 video begins playing on iOS, pointer events are not emitted

## Example Test Code

https://codepen.io/paulsymphony/pen/pmpQEd

Click to show pointer counters updating. On iOS, no more events are registered after the video starts playing.

**Comment by photonstorm** [comment]
This is standard iOs behavior and needs addressing directly in your own code. I'd suggest making the video play inline, or removing the controls attributes, plus removing the video entirely when playback completes so it no longer steals pointer events. Either way, this isn't something Phaser can do directly I'm afraid. If you do find a solution it'd be worth posting here for future search results.

**Comment by paulsymphony** [comment]
Thanks Rich. The solution is to NOT use 'controls' on the HTML5 video. This allows events to be recognized in both the dom element and the phaser events queue. I revised my pen to show this.
