### ISSUE TITLE
Facebook plugin gameStarted() issue

### ISSUE THREAD

**Issue by bchee** [photonstorm/phaser#4550]
## Version

* Phaser Version: v3.17.0-FB

* Operating system: macOS Mojave

* Browser: N/A

## Description

The `gameStarted()` function (`Phaser.FacebookInstantGamesPlugin#gameStarted`) in the facebook plugin assumes that it is called after `FBInstant.startGameAsync()` promise is resolved. This assumption is true if you are loading assets because `scene.load` will call the following code on complete that wraps `gameStarted()` in the `FBInstant.startGameAsync()` promise (line 390).

https://github.com/photonstorm/phaser/blob/a854a96307bccbd4c4a9affd3a9b09239e42848a/plugins/fbinstant/src/FacebookInstantGamesPlugin.js#L384-L393

However, if `gameStarted()` is called without preloading assets like it suggests in the [docs](https://photonstorm.github.io/phaser3-docs/Phaser.FacebookInstantGamesPlugin.html#gameStarted__anchor) using `this.facebook.gameStarted()`, then you will get the warning/error `{code: "INVALID_OPERATION", message: "Can not perform this operation before game start."}` from line 456 because `FBInstant.getEntryPointAsync()` needs to be called after `FBInstant.startGameAsync()`.

https://github.com/photonstorm/phaser/blob/a854a96307bccbd4c4a9affd3a9b09239e42848a/plugins/fbinstant/src/FacebookInstantGamesPlugin.js#L447-L457 

## Example Test Code

The following code block is from http://phaser.io/tutorials/getting-started-facebook-instant-games/part4 under the title "Starting without a Preloader". However, this will error out as described above with warning `{code: "INVALID_OPERATION", message: "Can not perform this operation before game start."}`.
```javascript
class Preloader extends Phaser.Scene {

    constructor ()
    {
        super('Preloader');
    }

    create ()
    {
        this.facebook.once('startgame', this.startGame, this);
        this.facebook.gameStarted();
    }

    startGame ()
    {
        this.scene.start('MainMenu');
    }

}
```

## Possible solutions

One solution is the whole `gameStarted()` function should be wrapped in the `FBInstant.startGameAsync()` promise moving it from being the callees responsibility rather than the callers.

Another fix is just to update the documentation and phaser facebook instant game tutorial. It should say if you want to call it directly you need to wrap it so it is called after the `FBInstant.startGameAsync()` promise.
```javascript
FBInstant.startGameAsync().then(this.facebook.gameStarted.bind(this));
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
