### ISSUE TITLE
Unable to set text shadow properties through initial style object.

### ISSUE THREAD

**Issue by XekeDeath** [photonstorm/phaser#4551]
* Phaser Version: 3.17.0
* Operating system: Win 7
* Browser: Chrome

Trying to create a text object with a shadow using an object as the style parameter results in text with no shadow, using values from the documentation.

```
var style = { 
    fontFamily: 'Courier New',
    align: 'left',
    color: 'white',
    fontSize: "36px",
    // These are listed in the documentation for TextStyle objects.
    shadowFill: true,
    shadowOffsetX: 2,
    shadowOffsetY: 2,	
};
var text = this.add.text(100, 100, "Shadow Text", style);	
```

Stepping though the text object creation, the TextStyle.setStyle function passes `shadow.offsetX/Y` to the `GetAdvancedValue` function, while the key on the style object is `shadowOffsetX/Y`

Issue can be worked around using the setShadow function on each individual text object, or by using the `shadow.` notation instead:
```
var style = { 
    fontFamily: 'Courier New',
    align: 'left',
    color: 'white',
    fontSize: "36px",
    // These values work, but are not in the documentation.
    'shadow.fill': true,
    'shadow.offsetX': 2,
    'shadow.offsetY': 2,
};
var text = this.add.text(100, 100, "Shadow Text", style);	
```

**Comment by rexrainbow** [comment]
It ought be
```javascript
shadow: {
    fill: true,
    offsetX: 2,
    offsetY: 2,
}
```

**Comment by photonstorm** [comment]
The way rex described it above is the correct way to specify the shadow in the config object. I have just added typedefs for the whole Text Style, which should make this a lot easier to see in the docs now.
