### ISSUE TITLE
3.17.0  "pointerup" bug

### ISSUE THREAD

**Issue by baozi510** [photonstorm/phaser#4556]
I am not good at English.

windows10  chrome 74.0.3729.169

i use phaser 3.17.0

click and hold mouse  fast move,when finish move. trigger "pointerup" event  multiple times and if too fast can not trigger “pointerup”

3.16.2 is good

code：

var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var game = new Phaser.Game(config);

function preload ()
{
}

function create ()
{
    this.input.on("pointerup",function(){
        console.log('pointerup')

    })
}

function update ()
{
}

**Comment by photonstorm** [comment]
Don't worry, this is already being worked on. Please see #4538 - you can follow progress on the bug there.
