### ISSUE TITLE
Attaching shader to sprite

### ISSUE THREAD

**Issue by dev-zetta** [photonstorm/phaser#4557]
Hello there,

not sure if I checked everything in the docs, but it seems that shaders can be only created as objects.

I don't want to add shaders as objects into the game. I would like to attach them to existing objects, like sprites.

Is there a way, how to do that? I have not seen such usage in examples.

**Comment by photonstorm** [comment]
You cannot attach a shader to a Sprite directly. You have to use a Custom Pipeline if you don't want to use the Shader object. There are examples in the labs for this.
