### ISSUE TITLE
3.17.0 - broken tweens timeline when looped 

### ISSUE THREAD

**Issue by peteroravec** [photonstorm/phaser#4558]
## Version
* Phaser Version: 3.17.0
* Operating system: macOS Mojave 10.14.4
* Browser: Google Chrome 74.0.3729

## Description
Tween timelines not working properly, some which should be looped behaves weird

## Example Test Code

3.16.2 - everything is OK
https://labs.phaser.io/view.html?src=src\tweens\timelines\loop%20timeline.js&v=3.16.2

3.17.0 - loop have "jump" and also weird speed change
https://labs.phaser.io/view.html?src=src\tweens\timelines\loop%20timeline.js&v=3.17.0

**Comment by fyyyyy** [comment]
tween.seek also doesnt seem to work properly

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
