### ISSUE TITLE
Chrome Mobile transparency Issue with RenderTexture.draw method

### ISSUE THREAD

**Issue by YannCaron** [photonstorm/phaser#4561]
I have written my own NinePatch object for several reasons.
To do that I extends the Phaser.GameObjects.RenderTexture class and implement this method that do the job :

``` javascript
    buildFrames() {
        const textureSource = this._scene.textures.get(this._src);

        for (const frame of this.frames) {
            textureSource.add(frame.name, 0, frame.rect.x, frame.rect.y, frame.rect.width, frame.rect.height);

            const tmpImage = this._scene.make.image({
                key: this._src,
                frame: frame.name
            });
            tmpImage.setOrigin(0);
            const w = frame.width ? frame.width : frame.rect.width;
            const h = frame.height ? frame.height : frame.rect.height;
            tmpImage.setScale(w / frame.rect.width, h / frame.rect.height);

            this.draw(tmpImage, frame.x, frame.y);
            tmpImage.destroy();
        }
    }
```

It works perfectly on all browsers exept Chrome 74.0 on my Android 7.0 smartphone.
The transparency are not transparent (source is a png image with Alpha) :
![image](https://user-images.githubusercontent.com/5962300/58514640-cddcde80-81a2-11e9-8bc4-0c622d4b67f6.png)

Where it works just fine on Firefox in the same device :
![image](https://user-images.githubusercontent.com/5962300/58514702-fa90f600-81a2-11e9-8a4d-06bcefce5018.png)

I make some tries to identify the problem and I think it come from the RenderTexture.draw method.

**Comment by photonstorm** [comment]
There's nothing I can really do about this from within Phaser. Images drawn to Render Textures use the exact same method as drawing to the canvas itself. It looks and smells like a Chrome bug which is hopefully now fixed given Chrome 74 is a pretty old version for Android.

**Comment by YannCaron** [comment]
Many thanks @photonstorm to reply this issue.
Regards
