### ISSUE TITLE
memory leak after game.destroy called

### ISSUE THREAD

**Issue by atbulbs** [photonstorm/phaser#4564]
## Version

* Phaser Version:  3.15.1

* Operating system: macOS Mojave 10.14.3(18D109)

* Browser: Chrome/70.0.3538.110

## Description

We built a SPA and use phaser to create game. In our project, the game instance created and destroyed for many times. Mean while, we found that, the momory increased every time.What was the worest, our app in mobile always crashed, so we test the memory leak by this demo. Looking forward to your reply.

## Example Test Code

you can run the demo online [https://atbulbs.github.io/phaser_memory_leak_test/](https://atbulbs.github.io/phaser_memory_leak_test/)
and there is a test detail report md here [https://github.com/atbulbs/phaser_memory_leak_test](https://github.com/atbulbs/phaser_memory_leak_test)
```javascript
<!DOCTYPE html>
<html>
  <head>
    <title>phaser_memory_leak_test</title> 
    <script src="./phaser.min.js" type="text/javascript">
    </script>
  </head>
  <body>
    <span>
      please input the count createAndDestroyGame run
    </span>
    <br/>
    <input id="input" value="10" onchange="handleInput(value)"> 
    </input> 
    <br/>
    <button style="margin: 25px; height: 25px; background-color: #ccc" onclick="createAndDestroyGame()">
      click run test
    </button>
    <div id="container">
    </div>

    <script>
      var input = document.getElementById('input');
      var times = input.value;
      function handleInput (value) {
        times = value
      };
      var count = 0;
      function createAndDestroyGame () {
        var game;
        var config = {
            type: Phaser.AUTO,
            width: 800,
            height: 600,
            parent: 'container',
            scene: {
                preload: preload,
                create: create,
            }
        };
        game = new Phaser.Game(config);
        function preload () {
          this.load.image('dude', 'https://phaser.io/images/img6.png');
        };
        function create () {
            this.add.image(400, 300, 'dude')
            this.add.text(100, 200, 'game created', 
            { fontFamily: 'Arial', fontSize: 64, color: '#f0f000' });
            console.log('created', ++count)
            game.destroy(true, false)
        };
        game.events.on('destroy', function () {
            console.log('destroyed', count)
            game = null
            if (count < times) {
              createAndDestroyGame()
            }
        });
      }
    </script>
  </body>
</html>
```

## Additional Information

you can use the chrome dev tool to test if there is any memory leak
[https://developers.google.com/web/tools/chrome-devtools/memory-problems/](https://developers.google.com/web/tools/chrome-devtools/memory-problems/)

**Comment by jamaalsawyerd** [comment]
I'm having the same issue. It seems to be tied to WebGL?

**Comment by photonstorm** [comment]
Thank you for spending the time opening this issue originally. I'm sorry, but I am closing off really old issues that we were unable to attend to at the time. It's very likely this has since been resolved via either updates to Phaser or the mobile os / browser in question. Happy to re-open if it can be demonstrated as still broken on modern devices via a test case.
