### ISSUE TITLE
Improve scene loading parameters and behaviour

### ISSUE THREAD

**Issue by antoine-pous** [photonstorm/phaser#4566]
For an unknown reason the way `active` Scenes are implemented broke the Scene loading order. Then i would like suggest a small change about it to be more compliant with devs needles:

1) Ensure that `active` respect the Scene order from the game configuration. With that we can set an active scene without breaking any Scenes which load some required stuff

2) Implement a `required` Scenes array into the Scene config. With it we can set an active Scene right after required Scenes even if it don't respect the loading order from the config file

**Usage with active**
```typescript
// Scenes declared in game config
{
    scene: [LoadingScene, GameScene, MenuScene]
}

class LoadingScene extends Phaser.Scene {
    constructor() { 
        super({key:"LoadingScene"}) 
    }
}

// Loaded in order, right after LoadingScene, and before MenuScene
class GameScene extends Phaser.Scene {
    constructor() { 
        super({key:"GameScene", active: true}) 
    }
}

// Last loaded scene
class MenuScene extends Phaser.Scene {
    constructor() {
        super({key:"MenuScene"})
    }
}
```

**Usage with required**
```typescript
// Scenes declared in game config
{
    scene: [LoadingScene, GameScene, MenuScene]
}

class LoadingScene extends Phaser.Scene {
    constructor() {
        super({key:"LoadingScene"})
    }
}

// Loaded right after the whole required Scenes
class GameScene extends Phaser.Scene {
    constructor() {
        super({key:"GameScene", active: true, require:["LoadingScene", "MenuScene"]})
    }
}

// Last loaded scene
class MenuScene extends Phaser.Scene {
    constructor() {
        super({key:"MenuScene"})
    }
}
```

**Comment by photonstorm** [comment]
Thanks for opening this issue. I'm curious what this is supposed to fix? Scenes are _instantiated_ in the exact order in which you specify them in the Game Config. They're then moved to being active only if they are either the first Scene in the array, or their config says to make them active.

They're never 'loaded' by Phaser (in the traditional sense of loading files).

In the second example above, if the GameScene requires LoadingScene and MenuScene, then it should be placed after them in the Scenes array. If it requires those Scenes to both be _active_, that is a different requirement (and needs handling via your own code)

**Comment by antoine-pous** [comment]
Actually when i use `active` the third Scene is loaded before the first. This is why i've opened this ticket to change this behaviour, i've thinked it was designed like that.

This behaviour broke my third Scene, because all assets are loaded from the LoadingScene which is my first Scene in my game config.

**Comment by photonstorm** [comment]
Phaser doesn't _load_ the Scene files at all, it just instantiates them and it will always do that in the order of the array. When you say 'load' do you actually mean 'load'? As in loaded from the filesystem?

**Comment by photonstorm** [comment]
Almost certainly the reason your 3rd Scene couldn't access assets loaded in your loading scene is that they hadn't finished loading when you tried to use them. Loading is an async process, so you need to listen out for the load complete event if another Scene is already running and trying to use assets currently being loaded. Alternatively (and this is more common), just don't start any other Scenes that require assets to be loaded before they can run. They can be started at the end of the LoadingScene.
