### ISSUE TITLE
Changing pollRate will call the "pointerdown" event twice

### ISSUE THREAD

**Issue by Legomite** [photonstorm/phaser#4567]
## Version

* Phaser Version: 3.17.0

* Operating system: macOS

* Browser: Tested in Safari

## Description

If using input.setPollAlways() or changing the pollRate, the "pointerdown" event will be called twice. 

## Example Test Code

Using this example, inserting this code will log to the console twice, instead of once like it's suppose to.

`this.input.on('pointerdown', function() {
        console.log('test');
    });`

http://labs.phaser.io/edit.html?src=src/input\mouse\poll%20always.js

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
