### ISSUE TITLE
Tilemaps Won't Load (Using Phaser3 Project Template)

### ISSUE THREAD

**Issue by BonitaTerror** [photonstorm/phaser#4571]
## Version

* Phaser Version: 3.17.0

* Operating system: Linux Mint 19

## Description

I am loading a tilemap exported from Tiled. It's pretty simple and I followed the recommended export to json. Unfortunately I am getting some warnings and the screen appears blank. Here are the warnings I get in the console:
```
No map data found for key map ParseToTilemap.js:59
Invalid Tileset Image: RPGpack_sheet Tilemap.js:323
Invalid Tilemap Layer ID: Background Tilemap.js:736
Invalid Tilemap Layer ID: Blocked Tilemap.js:736
```

## Example Test Code

Here is my class that extends Phaser.Scene where I attempt to load and create the tilemaps:

```javascript
import 'phaser';

export default class GameScene extends Phaser.Scene {
  constructor(key) {
    super(key);
  }

  preload() {
    this.load.tilemapTiledJSON('map', 'assets/tilemaps/map.json');
    this.load.spritesheet('RPGpack_sheet', 'assets/images/RPGpack_sheet.png', {
        frameWidth: 64, 
        frameHeight: 64
    });
  }

  create() {
    this.map = this.make.tilemap({key: 'map'});
    this.tiles = this.map.addTilesetImage('RPGpack_sheet');
    this.backgroundLayer = this.map.createStaticLayer('Background', this.tiles, 0, 0);

    this.blockedLayer = this.map.createStaticLayer('Blocked', this.tiles, 0, 0);

  }
}
```
and this is where I am using that class. I have verified it works fine as long as I am not trying to load these tilemaps:
```javascript
import Phaser from "phaser";
import config from './config'
import GameScene from './scenes/Game';

class Game extends Phaser.Game {
  constructor() {
    super(config);
    this.scene.add('Game', GameScene);
    this.scene.start('Game');
  }
}

window.game = new Game();
```
I'm also using this config file but otherwise I have left everything as is from the phaser3 project tempate
```javascript
import 'phaser';

export default {
  type: Phaser.AUTO,
  parent: "phaser-example",
  width: 800,
  height: 800,
  pixelArt: true,
  roundPixels: true,
  physics: {
    default: 'arcade',
    arcade: {
      gravity: {y: 0},
      debug: true
    }
  }
}
```

## Additional Information

I printed out the value of this.map after creating it in the create method and got these values back:
```
currentLayerIndex: 0
format: null
height: 10
heightInPixels: 320
imageCollections: Array []
images: Array []
layers: []
length: 0
<prototype>: Array []
objects: {}
orientation: "orthogonal"
properties: Object {  }
renderOrder: "right-down"
scene: Object { sys: {…}, game: {…}, anims: {…}, … }
tileHeight: 32
tileWidth: 32
tilesets: Array []
version: "1"
width: 10
widthInPixels: 320
```
many values are wrong (i.e tileHeight and tileWidth should be 64) but it gets things like height and width correct, perhaps this is just because 10 is default and this is a coincidence.

I have tried other json files for my tilemaps and still have the same issue so I am led to believe that it isn't an issue with the tilemap I am using. This is rather hard for me to debug, due to the fact I am using the project template so I don't have a specific solution in mind. Thank you!

Edit 1: 
I changed a line from the GameScene create function. Now it appears as:
```javascript
create() {
    this.map = this.make.tilemap('map');
    this.tiles = this.map.addTilesetImage('RPGpack_sheet');
    this.backgroundLayer = this.map.createStaticLayer('Background', this.tiles, 0, 0);

    this.blockedLayer = this.map.createStaticLayer('Blocked', this.tiles, 0, 0);

  }
```
Now this got rid of the first warning ```No map data found for key map ParseToTilemap.js:59``` but the other 3 remain

**Comment by PavelMishin** [comment]
Make sure that the tileset image name match tileset name in Tiled, and the layer name in the code match the layer name in Tiled, as it described in [this article](https://medium.com/@michaelwesthadley/modular-game-worlds-in-phaser-3-tilemaps-1-958fc7e6bbd6)
![naming](https://cdn-images-1.medium.com/max/2600/1*6vg2E6qe8Tj9fvBS_83i4A.gif)

**Comment by BonitaTerror** [comment]
@PavelMishin thank you for the reply. All my names match up, I can verify in Tiled as well as in the json file that I exported from it, The final 3 warnings and black screen still appear

Here might be a better way of showing the result, rather than me explaining:
![image](https://user-images.githubusercontent.com/39413300/58905715-665dec00-86d8-11e9-8b1b-77128e13a646.png)

**Comment by photonstorm** [comment]
Post the JSON file up here please.

**Comment by BonitaTerror** [comment]
@photonstorm  sure thing, here it is
```json
{ "height":10,
 "layers":[
        {
         "data":[22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22],
         "height":10,
         "name":"Background",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }, 
        {
         "data":[204, 204, 0, 0, 0, 0, 0, 0, 0, 0, 224, 224, 182, 184, 0, 0, 0, 0, 0, 0, 184, 186, 186, 184, 0, 0, 0, 0, 0, 0, 182, 184, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 206, 206, 202, 0, 0, 0, 189, 190, 0, 0, 226, 226, 222, 227, 247, 208, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":10,
         "name":"Blocked",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }],
 "nextobjectid":1,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.0.3",
 "tileheight":64,
 "tilesets":[
        {
         "columns":20,
         "firstgid":1,
         "image":"..\/images\/RPGpack_sheet.png",
         "imageheight":832,
         "imagewidth":1280,
         "margin":0,
         "name":"RPGpack_sheet",
         "spacing":0,
         "tilecount":260,
         "tileheight":64,
         "tilewidth":64
        }],
 "tilewidth":64,
 "type":"map",
 "version":1,
 "width":10
}
```
it's directly exported from tiled without any modifications

**Comment by photonstorm** [comment]
The map data looks fine. You shouldn't be giving it a sprite sheet though, it should just be an image:

```
this.load.image('RPGpack_sheet', 'assets/images/RPGpack_sheet.png');
```

**Comment by BonitaTerror** [comment]
Thank you, I just got the chance to switch that. The warnings and black screen remain still. Is there any other info I could provide that may help?

**Comment by photonstorm** [comment]
You could upload the asset files so a full test can be run from them, although given all the tilemap tests are working fine I'm not sure this is actually an API error at all, and is something specific to your map data or tileset. Would be curious to see what though.

**Comment by BonitaTerror** [comment]
Okay, that sounds good to me. Do you have a preference as to where I upload them?

**Comment by photonstorm** [comment]
Not really, here would be fine if they're small enough.

**Comment by BonitaTerror** [comment]
![RPGpack_sheet](https://user-images.githubusercontent.com/39413300/59072186-a3201380-888f-11e9-9862-7a05670d3fea.png)

This is the tile sprite that I used, and that's actually the only asset I've used so far. I might get a chance soon to test with other images. That's actually one thing I have yet to change yet while looking for a solution

**Comment by BonitaTerror** [comment]
I started with scratch with a new asset for the tile sheet, made a new map and exported it again in case there were any issues or corruption with the first. Oddly enough it still warns that it's an invalid tile set image along with the other 3 warnings and the black screen remains. I'm not sure if this actually added any helpful information but I thought I should mention it

**Comment by photonstorm** [comment]
Using the assets you uploaded I got the map to display instantly. Here is the code I used (most of it is just extra code for letting you use the cursors to move around):

```
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var controls;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('RPGpack_sheet', 'assets/tests/RPGpack_sheet.png');
    this.load.tilemapTiledJSON('map', 'assets/tests/map.json');
}

function create ()
{
    var map = this.make.tilemap({ key: 'map' });

    var tiles = map.addTilesetImage('RPGpack_sheet');

    var layer1 = map.createStaticLayer('Background', tiles, 0, 0);
    var layer2 = map.createStaticLayer('Blocked', tiles, 0, 0);

    this.cameras.main.setBounds(0, 0, map.widthInPixels, map.heightInPixels);

    var cursors = this.input.keyboard.createCursorKeys();

    var controlConfig = {
        camera: this.cameras.main,
        left: cursors.left,
        right: cursors.right,
        up: cursors.up,
        down: cursors.down,
        speed: 0.5
    };

    controls = new Phaser.Cameras.Controls.FixedKeyControl(controlConfig);
}

function update (time, delta)
{
    controls.update(delta);
}
```

Worked on Phaser 3.18, 3.17 and 3.16. Both map layers render properly.

So, there's nothing wrong with the map files. Which means it has to be somewhere else in your set-up. Possibly with how the game is being constructed like it's not getting given the game config or something. Or the build process isn't working. This isn't an API bug though, or at least not one that's anything to do with creating tilemaps.

**Comment by photonstorm** [comment]
![maptest](https://user-images.githubusercontent.com/164476/59144801-8ee52f00-89d3-11e9-9a14-7300a048839e.png)

**Comment by BonitaTerror** [comment]
Thanks for all the help and hints!! I finally got it to work. This is the final code that I used to get it working:

```javascript
import Phaser from 'phaser';

export default class GameScene extends Phaser.Scene {
  constructor (key) {
    super(key);
  }

  preload() {
    this.load.image('tiles', 'src/assets/images/RPGpack_sheet.png', {
      frameWidth: 64,
      frameHeight: 64
    });
    this.load.tilemapTiledJSON('map', 'src/assets/tilemaps/map.json');
  }

  create() {
    this.map = this.make.tilemap({key: 'map'});
    this.tiles = this.map.addTilesetImage('RPGpack_sheet', 'tiles', 64, 64);

    this.backgroundLayer = this.map.createStaticLayer('Background', this.tiles, 0, 0);
    this.blockedLayer = this.map.createStaticLayer('Blocked', this.tiles, 0, 0);
  }

}
```
So after checking the network tab I noticed I was getting 404s for loading in the images and json files. I tried changing the path to begin at src and this fixed mostly everything. So I suppose somewhere my root path isn't set correctly. As of now I'm fine just specifying ```src/assets/...```

Then of course I should have been passing the object as ```{key: 'map'}``` rather than just passing ```'map'``` to ```this.make.tilemap()``` as I was in the beginning. Even though this got rid of one of my original warnings, it was apparently why it was arriving as a string in ParseToTilemap
