### ISSUE TITLE
Flipping does not affected matter body

### ISSUE THREAD

**Issue by PavelMishin** [photonstorm/phaser#4574]
## Version

* Phaser Version: 16.3, 17.0

* Operating system: Windows 10

## Description

When using setFlipX on an instance of Phaser.Physics.Matter.Sprite, it's not flip the body shape, unlike using a negative scale.

## Example Test Code
https://jsfiddle.net/Trobing/h3bdfgcL/23/

**Comment by photonstorm** [comment]
This is correct behavior, flipping is a rendering toggle and should never impact the scale or any associated body. I have updated the docs to make this clearer.

**Comment by PavelMishin** [comment]
@photonstorm Then, what is the proper way to flip body shape?

**Comment by photonstorm** [comment]
For Matter, you'd need to inverse the scale. Just be careful when you do it. It's entirely possible to inverse a body directly into another one by mistake.
