### ISSUE TITLE
Pointer events received, but shouldn't be

### ISSUE THREAD

**Issue by dev-zetta** [photonstorm/phaser#4575]
Hello everyone,

I have same issue as mentioned here: https://github.com/photonstorm/phaser/issues/4447

All mouse click events now go thru overlay HTML layer right to the Phaser canvas. This behavior appeared in recent version, as everything worked fine until I updated deps to **Phaser v3.17.0**.

In my overlay HTML, I have dat.gui and custom UI. Now whenever I click on overlay HTML, the event is also received in Phaser (e.g. I get onObjectClick event).

I tried to twiddle with z-index, but that didn't help. I also tried everything mentioned in that issue above.

```
    e.stopPropagation();
    e.preventDefault();
    input.useQueue = true/false
    config.inputQueue = true/false
    and probably all combinations of these.
```

Nothing of that helped.

Any ideas?

Edit: The pointer events are received event when I add pointer-events: none; to the canvas element. This is odd, because they should not be received.

**Comment by dev-zetta** [comment]
Okay. I've found where it problem is.
The behaviour of the event handling has changed in recent version(s). Now there is window event handler that is enabled when setting windowEvents to true. 

I did not set it in any way. Now I see that it is enabled by default. So all window mouse events are passed into Phaser, non only from canvas element, which is I believe, unwanted behaviour in most cases.

It should be set to false by default.

**Comment by photonstorm** [comment]
The reason it is `true` by default is that the number one complaint about input events was that if you mouse down on your game, then release the mouse while outside of it, the game still thinks the pointer is down. Equally, changing mouse state while outside the game made it impossible for the input manage to reflect those updates. There is a game config switch to disable this behavior (as you've found before I had a chance to point you towards it) but I'm going to leave it enabled, as the majority of Phaser games are fully self-contained within a single canvas and don't make use of DOM elements over the top.

**Comment by dev-zetta** [comment]
If that is the only reason for the game to hook window mouse events, then you could simply hook only windows' mouse up event and listen to canvas mouse down events.

**Comment by photonstorm** [comment]
No, because then if you mouse down outside the canvas and then move over it, the values are still incorrect.

**Comment by dev-zetta** [comment]
Okay :)

**Comment by photonstorm** [comment]
I've updated the Input Plugin docs to hopefully make this easier to find.
