### ISSUE TITLE
Light pipeline broken

### ISSUE THREAD

**Issue by dev-zetta** [photonstorm/phaser#4578]
Hello,

after upgrade to the latest version of Phaser, lights are not "working" in my game anymore.
I have lights plugin enabled, ambient color set, lights created, color, radius, intensity, etc. also set.

But all I see is black sprites. I didn't change any of the lights related code in my game, only updated Phaser to the latest version.

It seems that there is a bug in a light shader.

![image](https://user-images.githubusercontent.com/3283719/59071513-3f154380-88bf-11e9-83f8-b92fbee34c3d.png)

**Comment by dev-zetta** [comment]
Okay, I see that Light2D pipeline is not even activated on those sprites because they don't have a normal map.

Lights were working just fine in previous versions. Why it is now required by the pipeline to have normal map for each sprite?

I have thousands of sprites without normal maps...

**Comment by jcyuan** [comment]
there is a default normal map will be set if you don't set a normal map for your sprite. so this should not be the problem. could you build a fiddle test? so probably others will help to test and analyze, as you know the author is busy.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
