### ISSUE TITLE
generateFrameNames returns empty array

### ISSUE THREAD

**Issue by sean256** [photonstorm/phaser#4583]
## Version
* Phaser Version: 3.17.0 Installed via NPM
* Operating system: Mac and Ubuntu

## Description
When I use `this.anims.generateFrameNames` it returns an empty array.

## Example Test Code

```js
function create() {
    const frames = this.anims.generateFrameNames('player', { prefix: 'p1_walk', start: 1, end: 11, 
    zeroPad: 2 });
    // frames = []
}
```

**Comment by photonstorm** [comment]
If it returns an empty array, it means there is no texture loaded with the key `player`.

**Comment by sean256** [comment]
I know how silly this issue post is due to how obvious this bug would have been. I can assure you I loaded a texture in preload with the same key. I was actually following a guide by TexturePacker: https://www.codeandweb.com/texturepacker/tutorials/how-to-create-sprite-sheets-for-phaser3
(note I used a different key than cityscape).

Later tonight I will distill it to the minimum amount of code to replicate and post it.

**Comment by sean256** [comment]
@photonstorm here is super simple example of it not working. The zip contains everything you need.

[Archive.zip](https://github.com/photonstorm/phaser/files/3279192/Archive.zip)


```html
<!DOCTYPE html>
<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/phaser@3.15.1/dist/phaser-arcade-physics.min.js"></script>
</head>
<body>
    <script>
    var config = {
        type: Phaser.AUTO,
        width: 800,
        height: 600,
        physics: {
            default: 'arcade',
            arcade: {
                gravity: { y: 200 }
            }
        },
        scene: {
            preload: preload,
            create: create
        }
    };
    var game = new Phaser.Game(config);
    function preload () {	
		this.load.multiatlas('gameSheet', '/mario-test.json', '/');
    }
    function create () {
		const minion = this.add.sprite(200, 400, 'gameSheet', 'mario/walk/001.png');
		const frameNames = this.anims.generateFrameNames('gameSheet', {
			start: 1,
			end: 3,
			zeroPad: 3,
			prefix: 'mario/walk/',
			suffic: '.png',
		});
		console.log(frameNames);
    }
    </script>
</body>
</html>
```

**Comment by photonstorm** [comment]
Your zip file and code works fine for me, once I correct the typo of `suffic` to `suffix`. Here's the full code I used:

```
    const mario = this.add.sprite(200, 400, 'gameSheet', 'mario/walk/001.png');

    const frameNames = this.anims.generateFrameNames('gameSheet', {
        start: 1,
        end: 3,
        zeroPad: 3,
        prefix: 'mario/walk/',
        suffix: '.png',
    });

    var config = {
        key: 'walk',
        frames: frameNames,
        frameRate: 20,
        repeat: -1
    };

    this.anims.create(config);

    mario.play('walk');
```

And Mario happily appears running.
