### ISSUE TITLE
Phaser.GameObjects.Grid not rendering in CANVAS mode

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser#4585]
Happens in v. 3.16.2 and v.3.17.0, latest Chrome MacOS
Phaser.GameObjects.Grid only seem to render with WEBGL

**Comment by photonstorm** [comment]
Looking at it, this was never even coded! It's never worked, ever. Which just goes to show how often people need this Game Object and/or Canvas!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
