### ISSUE TITLE
Get REKT using this.add.line if you forget this

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser#4590]
Try following example:
http://labs.phaser.io/edit.html?src=src\game%20objects\shapes\line.js

Without the setOrigin(0) you will get screwed on coordinates. I first thought its a bug but it seems to be default. However when drawing lines the origin 0.5 doesn't make sense.
```

var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('bg', 'assets/skies/background1.png');
}

function create ()
{
    this.add.image(400, 300, 'bg');

    // this is not a right angle :p
    var r1 = this.add.line(0, 0, 100, 100, 100, 200, 0x00FF00);
    var r2 = this.add.line(0, 0, 100, 200, 200, 200, 0x00FF00);


    var o1 = this.add.line(0, 0, 200, 200, 200, 300, 0x9966ff).setOrigin(0);
    var o2 = this.add.line(0, 0, 200, 300, 300, 300, 0x9966ff).setOrigin(0);
}

```

**Comment by photonstorm** [comment]
I'm happy to leave this as-is. The origin is 0.5 for all Game Objects and it should be for Lines too. If you want the first coordinate pair to be the start of the line, then set the origin to zero. If you want it to be the end, set it to 1.

I've updated the Line jsdocs to make this more obvious, but the behavior is correct.
