### ISSUE TITLE
events.off does not de-register a custom event

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser#4591]
## Version

* Phaser Version: 3.17.0

* Browser: Brave/Chrome

## Description

events.off does not deregister a user created event.
Events are still received after component is destroyed.

## Example Test Code

```

class UI extends Phaser.Scene { ... }


class TEST extends Phaser.GameObjects.Container  {
    constructor(...) {
        super(...)
        UI.events.on('test', this.onTest.bind(this), this);
    }

    onTest(){
       // still firing after destroyed
    }

    destroy() {
        UI.events.off('test', this.onTest.bind(this), this);
        super.destroy();
    }
}
```

**Comment by photonstorm** [comment]
When you `bind` a function you create a brand new anonymous function, so the `off` doesn't work in your code because the function signature doesn't match the anonymous one used in the `on`. You've two choices:

```
this.handler = this.onTest.bind(this);

on('test', this.handler);
off('test', this.handler);
```

Or, you can use `off('test')` without specifying the handler and it'll remove anything bound to the 'test' event, which is handy in cases of anonymous functions like this.

**Comment by fyyyyy** [comment]
Even with out the bind, i find that the event removal is not reliable.
I have written my own event removal code which works without problems. I haven't figured out what the issue is exactly with the engine's event removal.
To me it seems odd that events can be either a single object or an array of events. Maybe for performance reasons ?

    removeEvent(name, context) {
        // monkey patch
        var eventOrEvents = this.events._events[name];

        // multiple events
        if(_.isArray(eventOrEvents)) {
            var event = _.find(eventOrEvents, { context });
            if(!event) {
                console.warn("no removeEvent", name);
                return;
            }
            _.remove(eventOrEvents, event);
        }
        // single event
        else {
            if(eventOrEvents.context === context) delete this.events._events[name];
            else console.warn("no removeEvent", name);
        }
    }

**Comment by fyyyyy** [comment]
Ok i figured it out, it were some uncleared references i had to remove on destroy.
I think it works fine now, thanks 👍

**Comment by fyyyyy** [comment]
In any case, if i may suggest the engine to throw a warning if an event could not be removed ?
Because they fail silently and then linger around.

**Comment by photonstorm** [comment]
_All_ events in Phaser 3 are handled by [EventEmitter3](https://www.npmjs.com/package/eventemitter3) due to its performance and massive user base (6.8 million weekly downloads). I'm very confident if there was an issue with `off`, it would already be flagged in such a widely used library. You're welcome to discuss any questionable code you think is in it with the authors directly, but it's one of the (very very few) packages we use wholesale in Phaser without modifications.

**Comment by fyyyyy** [comment]
Thank, i have looked into that library.

It seems that EventEmitter3 doesn't throw an error for `.off` aka `.removeListener` if an event is not found.
That means you can get those silently lingering events if you are not very careful that you clear them in the right way. E.g. using bind or anonymous functions would create such circumstances like you said. And finding the issue can be tough because you expect .off to throw a warning if the event cant be found.

I will make a suggestion in their library but it seems that its more critical in a game context where you have lot more memory clogging than with a web app.

**Comment by fyyyyy** [comment]
If eventEmitter cant be updated, another option would be for Phaser to discover events where the `context.active === false`
Imo it doenst make sense that destroyed objects still receive events and therefore linger in memory?

**Comment by photonstorm** [comment]
It's not possible for an object to de-register itself from any event listener it may have been added to as there is no binding kept in that direction. If you're worried about making sure all handlers are removed from an event then use the `removeAllListeners()` method. If you just want to confirm that one handler has been removed, you can check `listenerCount()` before and after the call. Or you could poll the contents of the array returned by `listeners()`. There are quite a number of ways to validate what is still lingering in an event emitter, so really it's up to the developer to use those tools if they're worried they've fluffed their context scope or something.
