### ISSUE TITLE
Children of invisible and inactive scenes receive input

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser#4592]
v3.16.2 and v.3.17.0

I have a UI Scene on top of the Game scene.

I call  this.scene.setVisible(false);
        this.scene.setActive(false);

The UI is no longer visible. But its children still receive click input and prevent clicking on the Game scene below.

**Comment by fyyyyy** [comment]
It seems i must reorder scenes for input management https://phaser.io/phaser3/devlog/121
So hiding a scene isn't enough, i also should call         this.scene.sendToBack();
to disable it from receiving input.

**Comment by photonstorm** [comment]
Just checked this in 3.18 and 3.17 and it's working fine. Look at [this example](http://labs.phaser.io/view.html?src=src%5Cinput%5Cpointer%5Cmultiple%20scene%20down%20event.js) for a multi-scene test. Now, in the SceneC `button` handler change it to this:

```
        button.on('pointerdown', function () {
            console.log('Scene C');
            this.scene.scene.setActive(false);
        });
```

So it sets SceneC to inactive after one click on it.

From this point on, clicking the right-most arrow (SceneC) doesn't trigger at all, as it should, even though it still renders.

The InputPlugin update method checks if either the Input Plugin itself, or the Scene it belongs to, is active or not before processing events via the [isActive](https://github.com/photonstorm/phaser/blob/master/src/input/InputPlugin.js#L523) method, which is called right at the start of [update](https://github.com/photonstorm/phaser/blob/master/src/input/InputPlugin.js#L640-L645). If this method returns true all updates bail out.
