### ISSUE TITLE
Tween.restart() doesn't work if the tween is running

### ISSUE THREAD

**Issue by NokFrt** [photonstorm/phaser#4594]
## Version

* Phaser Version: 3.17

* Operating system: Win10

* Browser: Chrome

## Description
Tween.restart() doesn't work correctly if the tween is running. It stops the running tween and resets targets values, but the tween is not running anymore.

## Example Test Code
https://labs.phaser.io/view.html?src=src\tweens\restart.js&v=3.17.0

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
