### ISSUE TITLE
Arcade Physics: Phaser.GameObjects.Line Does Not Collide In Group

### ISSUE THREAD

**Issue by andrewaustin** [photonstorm/phaser#4596]
## Version
* Phaser Version:

3.17.0
* Operating system:

OS X
* Browser:

Firefox 67.0

## Description

When adding a `Phaser.GameObjects.Line` to a group that you then set up a collider with `this.physics.add.collider(sprite, group);`, the collision does not happen correctly. Instead if you turn on arcade physics debug, you see the line bounding box is in a weird place.

Since the Line object is the correct type to add to a group, I would expect collisions to work correctly. As demonstrated in the code, a workaround is to use a Rectangle, which works correctly, so it seems like an API inconsistency.

## Example Test Code

Just press the up arrow  on your keyboard and see the sprite does not collide with the line but does not with the group.

https://jsfiddle.net/9wrgta0s/

**Comment by dmariaa** [comment]
Problem does not only happen when adding the line to a group, it happens trying to collide with the line directly. I haven’t had enough time to investigate it, but it seems to be a problem related to the way Line class handles it’s coordinates x, y, width, height.

**Comment by photonstorm** [comment]
If you turn on debugging in Arcade Physics it's easy to see what's going on. Line Shapes don't have any height, so they're given the default height of 64px. Where-as the Rectangle above has a height of 2. Give it a height of 0 and you'll see the same thing. In 3.5 Lines now have a default height of 1, so bodies can be created from them, but they still need offsetting manually.
