### ISSUE TITLE
Physics sprite is interpreted as normal sprite by Typescript definition file

### ISSUE THREAD

**Issue by KokoDoko** [photonstorm/phaser#4598]
## Version
* Phaser Version 3.17
* Operating system: MacOS
* Browser: chrome, safari

## Description
When trying to alter the settings of `this.body` in a physics sprite, only options for normal sprites show up. Setting gravity is not allowed by the typescript definition file. When manually asserting the body to be a physics body, the code works.

## Example Test Code

```
export class Demo extends Phaser.Physics.Arcade.Sprite {
    demo(){
        // Not allowed by typescript compiler
        this.body.setAllowGravity(false)

        // When using type assertion, the code DOES work
        let body = this.body as Phaser.Physics.Arcade.Body
        
        // now you can adjust physics settings
        body.setAllowGravity(false)
     }
}
```

**Comment by photonstorm** [comment]
Just checked the latest TypeScript defs and it correctly types the `body` property now:

```
                /**
                 * This Game Object's Physics Body.
                 */
                body: Phaser.Physics.Arcade.Body | Phaser.Physics.Arcade.StaticBody;
```

Although I fully appreciate it might not have when you opened this issue! But I'm going to close it as the defs are now correct.
