### ISSUE TITLE
Delay to change a scene if the current scene has many objects

### ISSUE THREAD

**Issue by redfoc** [photonstorm/phaser#4599]
## Version
3.17
* Phaser Version:

windows 7
* Operating system:

* Browser:

## Description

there are 7200 tiles object, tile size are 352x64 (separate with 4 sprite) to cover the game map.

If i switch scenes or start another scenes, it’s take about 7 seconds until it’s moved to target scene.
but starting game scene are quite fast, look like there are no delay to process.

My test link http://cdn.redfoc.com/test/p3_tiles

## Example Test Code

class load extends Phaser.Scene {
	constructor(){
		super('load');
	}
	preload(){
		this.load.spritesheet('tiled', 'tiles.png', {frameWidth: 88, frameHeight: 64});
	}
	create(){
		this.scene.start('menu')
	}
}
class main_menu extends Phaser.Scene {
	constructor(){
		super('menu');
	}
	create(){
		this.add.text(20,20, 'Press A to change scene',{fontFamily: 'Arial', fontSize: '30px',color: '#fff'});
		this.input.keyboard.on('keydown', function(e,f){
			if(e.key == 'a'){
				this.scene.start('game')
			}
		}, this);
	}
}
class main_game extends Phaser.Scene {
	constructor(){
		super('game');
	}
	preload(){
		this.load.spritesheet('tiled', 'tiles.png', {frameWidth: 88, frameHeight: 64});
	}
	create(){
		var size = {
	      w: 60,
	      h: 120
	    }
	    for(var y=0; y<size.h;y++){
	      for(var x=0; x<size.w; x++){
	        var o = this.add.sprite(x*88,y*64,'tiled');
	        o.setFrame(Math.round(Math.random()*3));
	      }
	    }
	    this.add.text(20,20, 'Press B to back to previous scene',{fontFamily: 'Arial', fontSize: '30px',color: '#fff'});
		this.input.keyboard.on('keydown', function(e,f){
			if(e.key == 'b'){
				this.scene.start('menu')
			}
		}, this);
	}
}
var config = {
  type: Phaser.AUTO,
  width: 1280,
  height: 720,
  scene: [load, main_menu, main_game],
}
var game = new Phaser.Game(config);

## Additional Information

"Try adding o.destroy = function(){}; in your nested for loop, like so:

for(var y=0; y<size.h;y++){
	for(var x=0; x<size.w; x++){
	    var o = this.add.sprite(x*88,y*64,'tiled');
	    o.setFrame(Math.round(Math.random()*3));
        o.destroy = function(){};
	}
}"

"Unfortunately this is just how Phaser is processing the destruction of it’s GameObjects. I would suggest creating an issue on Phaser’s Github so others can look into this. Worst case, this is a necessary evil and not an issue. If that is the case, you can choose whether to preference memory (not using destroy = function(){}; or performance (using destroy = function(){};)."

by Jake.Caron

**Comment by photonstorm** [comment]
I don't really get what this issue is about. Are you asking why it takes a few seconds to destroy thousands and thousands of Sprites? A better question may be, why are you creating that many in the first place and why destroy them? :)

**Comment by redfoc** [comment]
Actually i use regular sprite objects as a tilemap to draw/fill game map, i'm not using built-in tilemap since my game style are isometric.

I think if i change another scenes, current secene objects are destroyed, is that right ?

Someone from the forum tell me to use "Blitter" instead of sprite objects, now my problem are fixed.
