### ISSUE TITLE
JPEG Blend modes issue in Pixi 2.2.9 with Phaser 2.6.2

### ISSUE THREAD

**Issue by redsanso** [photonstorm/phaser#4602]
Hello,
I have a png animation spritesheet of some "light FX" with transparent pixels.
Since I must spare on assets weight in my game, I'm trying to:

- export it as jpg to shrink its size a little bit
- use it in PIXI with the blendMode ADD
- put it over a png sprite in blendMode NORMAL that uses an animation spritesheet
- put them above a jpg background.

The undesired result is the following:
The "jpg light fx" in mode ADD seems to "pierce" my underlying character just like it also had ADD. The background is unaffected.

Can you help me?

**Comment by photonstorm** [comment]
Phaser 2.6.2 is no longer supported. If you want to try this with Phaser 3 we can help, but 2.6 hasn't been updated in _years_ and isn't supported here.
