### ISSUE TITLE
[ScaleManager] TypeError: this.removeFullscreenTarget is not a function

### ISSUE THREAD

**Issue by darklightcode** [photonstorm/phaser#4605]
## Version

* Phaser Version: **3.18.1**

* Operating system: **Microsoft Windows [Version 10.0.18362.175]**

* Browser: **Google Chrome 75.0.3770.100 (Official Build) (64-bit)**
* Browser: **Firefox 67.0.4 (64-bit)**

## Description

I have tried implementing the fullscreen functionality in my game using `this.scale.toggleFullscreen()`, and hoped that it will scale my game properly, but instead i got an error in the console `TypeError: this.removeFullscreenTarget is not a function`. 
I have tried the Fullscreen Demo from examples, and the scaling is done properly (but the error is still triggered, perhaps from `this.scale.stopFullscreen();` ), so it's safe to assume that my code is wrong, but the `removeFullscreenTarget` error slipped into **3.18.1** from **3.18.0-beta1**.
( I was using this previously because 3.17 was failing on Internet Explorer 11 )

See the error in the image attached.

![phaser_3 18 1](https://user-images.githubusercontent.com/2173780/59906177-bba43800-9410-11e9-93ab-130cc536c205.png)

## Example Test Code

```

let item = this.add
            .image(0, 0, 'background_default')
            .setOrigin(0.12, 0); 

item.setInteractive();
item.on('pointerdown', ()=>{
    if(!this.scale.isFullscreen) {
        this.scale.toggleFullscreen(); // will trigger the error
        // this.scale.startFullscreen(); // this works ok
     }
}, this);

```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
