### ISSUE TITLE
graphics.save & graphics.restore not working as expected

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser#4606]
Phaser 3.17.0, 3.16.2
Brave browser

I have an extended graphics class where i like to keep the "background rectangle" and draw over it every frame.

class myGraphics extends Phaser.GameObjects.Graphics {

```
constructor() {
  super()
  this.fillRect(.....) // background rectangle
  this.save()
}
```

In the update function, i call 

```
update() {
  graphics.restore() // restore background
  graphics.lineTo(....) // geometry that changes every frame
}
```

to recreate the background image and then i draw a bunch of moving geometry.

It seems however that calling graphics.restore() repeatedly is throwing an error.

>>> TypeError: Cannot read property '0' of undefined
    at TransformMatrix.copyFromArray (TransformMatrix.js?2ed9:617)
    at Chart.GraphicsWebGLRenderer [as renderWebGL] (GraphicsWebGLRenderer.js?e993:319)
    at WebGLRenderer.render (WebGLRenderer.js?4602:2049)
    at CameraManager.render (CameraManager.js?0262:600)
    at Systems.render (Systems.js?9339:402)
    at SceneManager.render (SceneManager.js?cec0:585)
    at Game.step (Game.js?22d5:491)
    at TimeStep.step (TimeStep.js?fdd3:550)
    at step (RequestAnimationFrame.js?7d37:105)

**Comment by photonstorm** [comment]
You should only call `restore` the same number of times as you call `save`. So in this case, once. You didn't provide a testable code sample, so this may have been outside of the code shown, but if you're constantly drawing to a Graphics object without clearing it, you're eventually going to overflow its buffer and everything will grind to a halt. Graphics objects are long lists of drawing operations, so with every command added, the list grows and grows until it can't go any further.

**Comment by photonstorm** [comment]
Thank you for opening this issue, however, I'm going to close it off now as there has been no progress made on this issue in quite some time, and sadly no contributions from anyone else to help fix it. I'm sorry we couldn't resolve it in this case.
