### ISSUE TITLE
setData typescript def requires null in the second argument

### ISSUE THREAD

**Issue by vacarsu** [photonstorm/phaser#4607]
When using ```setData({ data: data })``` typescript requires the second argument.
it's assuming the ```setData(key, value)``` syntax. The current work around for this is to do ```setData({ data: data }, null)```.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
