### ISSUE TITLE
getDuration()/upTime/downTime returns NaN on mobile devices

### ISSUE THREAD

**Issue by BobtheUltimateProgrammer** [photonstorm/phaser#4612]
## Version

* Phaser Version: 3.18.1

* Operating system: iOS 12.1.1

* Browser: Safari

## Description

Hi. There is another problem I have relating to the pointer events. Apparently using getDuration() returns NaN on touch events (like iOS devices). But getDuration() works correctly on desktop computers.

Note: the same problem applies to the pointer properties downTime, upTime, etc.....
Thank you for your time. You are truly the best. Have a great start to summer.
## Example Test Code

```
this.input.on("pointerup", function (pointer) {
        alert(pointer.getDuration()); //returns NaN on mobile devices, returns correct value on desktop devices
});
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
