### ISSUE TITLE
Support classType in CreateFromObjects/Tiles

### ISSUE THREAD

**Issue by Secretmapper** [photonstorm/phaser#4613]
createFromObjects/Tiles in the Tilemap API does not support a custom classType, which is quite unfortunate, as group for example supports classType

Would it be good to consider supporting this? Or is there a recommend approach to dynamically inject logic and data on runtime to an already created sprite

**[Optional] Do you want to help provide this feature?**

If the design and API is approved I'd be willing to make a PR 😊

**Comment by Secretmapper** [comment]
In the meantime, I'm simply using mixins and a more ECS approach, but leaving this issue for discussion (as I searched and there doesn't seem to be one current about this)

**Comment by samme** [comment]
This would be helpful.

As written the functions could be easily extended with, e.g.,

    @param {string} [creator='sprite'] - The Game Object Creator method to call (on `scene.make`).

But people who have made custom game object classes without a creator method would need something else.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/createfromobjects-classtype-and-typescript-extends/10239/5

**Comment by airtonix** [comment]
this only works in javascript, not in typescript as the function doesn't provide type parameters to test if it can extend from GameObject.
