### ISSUE TITLE
Issue with input in desktops/laptops with touchscreen

### ISSUE THREAD

**Issue by mmolina01** [photonstorm/phaser#4615]
Phaser Version: 3.18.1

When using a computer with touchscreen the input events (pointerdown, pointerup, etc) stop working when alternating between click and touch, it only keeps working with the first type of input used (touch or click). Is not necessary to use a touchscreen computer to reproduce it, it will happen by switching the preview in browser from desktop to mobile (chrome toggle device in inspector will trigger the issue).

**Comment by JstnPwll** [comment]
Here's an example: https://codepen.io/jstnpwll/pen/eYZMpaO

Switch to mobile preview in dev tools, click, then switch back to desktop mode and click.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
