### ISSUE TITLE
Using BitmapMask inside container has interesting behavior.

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#4619]
## Version

* Phaser Version:3.17.0 and 3.18.1

* Operating system: Windows 10

* Browser: Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

## Description

We have a container added to scene and 2 sprites in it (`sprite0` and `sprite1`). Trying to set mask to sprite0 from sprite1 and both of them are becoming invisible.

before applying mask
![image](https://user-images.githubusercontent.com/30594036/60169904-aff1b080-9818-11e9-8336-375689d9391b.png)
after
![image](https://user-images.githubusercontent.com/30594036/60170131-f1825b80-9818-11e9-85ec-e89f24f8b268.png)

## Example Test Code

```
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    backgroundColor: '#000066',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
    }
};

var controls;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('brain', 'assets/sprites/brain.png');
    this.load.image('truck', 'assets/sprites/astorm-truck.png');
}

function create ()
{
    var container = this.add.container(400, 300);
    var sprite0 = this.add.sprite(10, 0, 'truck');
    var sprite1 = this.add.sprite(0, 0, 'truck');
    container.add(sprite0);
    container.add(sprite1)
    sprite1.setMask(sprite0.createBitmapMask())
}
```

## Additional Information

lets change texture of `sprite0` to `brain` and we'll see another unexpected behavior.

```
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    backgroundColor: '#000066',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
    }
};

var controls;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('brain', 'assets/sprites/brain.png');
    this.load.image('truck', 'assets/sprites/astorm-truck.png');
}

function create ()
{
    var container = this.add.container(400, 300);
    var sprite0 = this.add.sprite(10, 0, 'brain');
    var sprite1 = this.add.sprite(0, 0, 'truck');
    container.add(sprite0);
    container.add(sprite1)
    sprite1.setMask(sprite0.createBitmapMask())
}
```
![image](https://user-images.githubusercontent.com/30594036/60170191-07901c00-9819-11e9-8825-603914aeffcf.png)

**Comment by photonstorm** [comment]
Remember that mask positions are in world space, not local container space. I'll need to build a test here but those coordinates don't look right to me.

**Comment by RollinSafary** [comment]
I've tested with container in `x: 0, y: 0` and you're right Rich, but anyway, I think, that nobody will create additional masker object to apply mask in container.
Below i'm explaining what i'm going to make (maybe it will useful)
I've `AvatarView `which is `Phaser.GameObjects.Container`. It consist of `avatarFrame` (circular) and `avatar`, I'm going to set avatar picture to be masked with it's frame. because avatar texture is rectangle.
How you told, mask works with coordinates in world space, the first thing that I can think, is making `Phaser.GameObject.Graphics` object and drawing circle shape in avatar's `globalTransformMatrix` `tx` `ty` positions with `avatarFrame.width / 2` radius and giving geometric mask or recreating one more `avatarFrame` image on scene with needed positions.
But i'm trying to avoid using `Phaser.GameObject.Graphics` objects, because it's harms FPS on mobile devices.

**Comment by taoabc** [comment]
Because mask cannot add to container, I'm forced fallback to phaser 2. @RollinSafary Like your situation, I need a batch of cirle mask above avatar. Then attach the root container to dragonbones or spine slot.

**Comment by photonstorm** [comment]
@taoabc you can add masks to Containers! This was added months ago and there are lots of examples of it in the labs (like [this one](http://labs.phaser.io/view.html?src=src%5Cdisplay%5Cmasks%5CContainer%20Mask%20Test%202.js&v=dev))

**Comment by photonstorm** [comment]
Have tested this under 3.5 and it works properly, nothing vanishes (as long as you get the mask coordinates correct). Probably worked lots of versions prior to this, but don't have time to figure out which version it worked from, sorry.

**Comment by halilcakar** [comment]
Hi @photonstorm, I'm sorry to open this again but i'm having kinda problem on the example you give 

> @taoabc you can add masks to Containers! This was added months ago and there are lots of examples of it in the labs (like [this one](http://labs.phaser.io/view.html?src=src%5Cdisplay%5Cmasks%5CContainer%20Mask%20Test%202.js&v=dev))

I really couldn't understand what's the problem :(

![image](https://user-images.githubusercontent.com/18047554/94131482-a6655700-fe66-11ea-992d-7c2bd5f71ded.png)

**Comment by photonstorm** [comment]
That beta build was probably from before I fixed this yesterday, use the one attached:

[dev.zip](https://github.com/photonstorm/phaser/files/5275409/dev.zip)
