### ISSUE TITLE
Problem with removing frame from the animation which has only 2 frames total

### ISSUE THREAD

**Issue by orlicgms** [photonstorm/phaser#4621]
## Version

* Phaser Version: 3.18.1

* Operating system: Windows 10, 64-bit

* Browser:

## Description

When I try to remove a frame from the animation by using either it's "removeFrame(frame)" or "removeFrameAt(index)" method, it all works fine except in the case when the animation has 2 frames in total. If I try to play that animation afterwards, in some Sprite object for example, an error appears.

## Example Test Code

let config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    pixelArt: true,
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create
    }
};

let game = new Phaser.Game(config);

function preload() {

    this.load.image("img1", "https://labs.phaser.io/assets/pics/ayu.png");
    this.load.image("img2", "https://labs.phaser.io/assets/pics/ayu2.png");
}

function create() {
    // create the animation, add 2 frames
    let anim = this.anims.create({
        key: 'test',
        frames: [{
            key: "img1"
        }, {
            key: "img2"
        }],
        frameRate: 4,
        repeat: -1
    });

    // now let's try to remove one of the frames from the animation
    anim.removeFrameAt(1);

    // adding the sprite
    let sprite = this.add.sprite(400, 250);
    // playing the animation. This will cause an error
    sprite.play('test');
}

## Additional Information

It looks like that the problem is in the "updateFrameSequence" method of the "Phaser.Animations.Animation" class.  "updateFrameSequence" method is called form within "removeFrameAt" method of the same class, and as mentioned, the method works fine when animation has either 1, or more than 2 frames. However, if there are 2 frames in the animation, and one of them is removed (with either "removeFrame" or "removeFrameAt"  method), the error appears when animation is played.

This is the code of the "updateFrameSequence" method. I commented above the line where I think the error in the code is:

updateFrameSequence: function ()
    {
        var len = this.frames.length;
        var slice = 1 / (len - 1);

        for (var i = 0; i < len; i++)
        {
            var frame = this.frames[i];

            frame.index = i + 1;
            frame.isFirst = false;
            frame.isLast = false;
            frame.progress = i * slice;

            if (i === 0)
            {
                frame.isFirst = true;
                frame.isLast = (len === 1);
                frame.prevFrame = this.frames[len - 1];
                frame.nextFrame = this.frames[i + 1];
            }

            ///////////////////////////////////////////////////////////
            // HERE IS THE PROBLEM!
            // Instead of "else if()", only "if()" should be used
            else if (i === len - 1)
            {
                frame.isLast = true;
                frame.prevFrame = this.frames[len - 2];
                frame.nextFrame = this.frames[0];
            }
            else if (len > 1)
            {
                frame.prevFrame = this.frames[i - 1];
                frame.nextFrame = this.frames[i + 1];
            }
        }

        return this;
    }

If the animation had only 2 frames, and after that one of the frames was removed, both  (i === 0) and (i === len - 1) conditions are true. But when "else if(i === len -1)" is used instead of "if(i === len -1)", the second condition is not met, and "frame.nextFrame" is not set to the right value of "this.frames[0]". Instead, "frame.nextFrame" is set to this.frames[i + 1] which is undefined, because there is only one frame, and that causes the error.

Hope this helps :) Perhaps you have a better solution for this problem, I am not quite sure this fix will work good in all cases of adding /removing new frames.

Kind regards

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
