### ISSUE TITLE
PIXI BlendModes are not the same as Phaser ones

### ISSUE THREAD

**Issue by KennethGomez** [photonstorm/phaser#4622]
## Version
* Phaser Version: v3.18.1-FB
* Operating system: Windows 10

## Description

I've been testin with Pixi blendmodes and Phaser blendmodes, and what I've seen is that they make different result, I'd like to have the same result as PIXI's blendModes has

## Example Test Code

Phaser
`sprite.blendMode = Phaser.BlendModes.ADD`

Pixi
`sprite.blendMode = PIXI.BLEND_MODES.ADD`

**Comment by photonstorm** [comment]
You can create your own custom blend modes in Phaser, so if you want them to match the Pixi blend modes, then you'll have to use that feature because I don't see the need to change the way our blend modes are currently configured.
