### ISSUE TITLE
startFullscreen causing Dom objects hidden

### ISSUE THREAD

**Issue by redfoc** [photonstorm/phaser#4624]
## Version

* Phaser Version:

3.17
* Operating system:

* Browser:

chrome, firefox, chrome android

## Description

If i set my game to fullscreen (startFullscreen), all Dom objects are hidden (iframe, text input, img), if exit fullscreen, dom object are shown.

## Example Test Code

this.scale.startFullscreen();

this.add.dom(640,360).createFromCache('contact').setOrigin(0.5,0.5);

**Comment by kanthi0802** [comment]
We are also facing the same issue. Any updates ?

**Comment by photonstorm** [comment]
You can only fullscreen one single dom element (and its children) at a time. So create one in your page, make sure Phaser uses it as the parent in the game config and set that as being the fullscreen target.

**Comment by kanthi0802** [comment]
Yes. creating a div explicitly in html and passing that as the parent to the game object solved the issue. thanks.
