### ISSUE TITLE
Type definitions for addBlendMode are wrong

### ISSUE THREAD

**Issue by KennethGomez** [photonstorm/phaser#4625]
## Version

* Phaser Version:  v3.18.1-FB
* Operating system: Windows 10

## Description

TypeScript definitions for addBlendMode are wrong they require a function and some types are not present while calling Phaser.Renderer.WebGL.WebGLRenderer for the renderer

## Example Test Code

```ts
var renderer = this.sys.game.renderer as Phaser.Renderer.WebGL.WebGLRenderer;
        var { gl } = renderer;

        var modeIndex = renderer.addBlendMode([gl.ONE, gl.ONE_MINUS_SRC_ALPHA], gl.FUNC_ADD);
```

## Additional Information

Changing the type definitions of the renderer to any would work, so we can safely assume that the types are missing or wrong

**Comment by photonstorm** [comment]
The correct type should be `GLenum[]` as its an array of GL constants.
