### ISSUE TITLE
Phaser.Text.fixedWidth/fixedHeight behaviour

### ISSUE THREAD

**Issue by Jazcash** [photonstorm/phaser#4631]
Would it be possible to add some scaling options on Phaser.Text objects if fixedWidth and/or fixedHeight is set to control how the text should behave in relation to these values?

I'm currently using this in my own class that extends Phaser.Text:

```
if (this.displayWidth> this.maxWidth){
    this.displayWidth = this.maxWidth;
    this.scaleY = this.scaleX;
}
```

Which would shrink the text to make it always fit in a specified width. But it would be nice if I could do something like this:

```
const text = scene.add.text(0, 0, "Hello world", {
    fixedWidth: 100,
    scaleMode: Phaser.Types.blahblah.SCALEDOWN
});
```

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
