### ISSUE TITLE
Cannot play Tween created via `create`

### ISSUE THREAD

**Issue by mikewesthad** [photonstorm/phaser#4632]
This appears to apply to v3.17 through master. You cannot play a Tween created via `create`. Here's a [codesandbox](https://codesandbox.io/embed/focused-mestorf-5nxqe) demo that uses master branch, or some portable copy & paste code:

```js
const tween = this.tweens.create({
  targets: {x: 0},
  x: 600,
  duration: 1000,
  onStart: () => console.log("Started!")
});
tween.play();
// Will not log started
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by mikewesthad** [comment]
Thanks! Verified the fix is working in my tests.
