### ISSUE TITLE
Scale Manager setZoom() will not set zoom back to one

### ISSUE THREAD

**Issue by lgibson02** [photonstorm/phaser#4633]
* Phaser Version: Phaser v3.19.0-beta1

I've found in testing that once you set zoom level above one you aren't able to set it back to one again. 

Demo: [https://jsfiddle.net/2g0ydpuh/](https://jsfiddle.net/2g0ydpuh/)

In the demo an image as added before the scale manager sets zoom to x4, this works as expected but the call directly after to set zoom back to x1 has no effect and the finished image is left at a x4 zoom. Changing that last line's parameter to anything other than one works as expected. For example, setZoom(2) on the last line will correctly make the image finish with a x2 zoom.

The demo runs on 3.18 but the bug is still present in 3.19.0-beta1.

**Comment by photonstorm** [comment]
Just leaving this note here as a reminder to myself: this issue is just line 999 needing `>=`. However, also look at dividing resize sizes by zoom factor too.

**Comment by BinaryMoon** [comment]
Happy to help test this if you need it Rich.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by BinaryMoon** [comment]
@photonstorm did you also change the zoom factor based on the scale or is this just fixing the originally reported bug? I'd be happy to make a new ticket for my suggestion if that's easier?

**Comment by photonstorm** [comment]
This only fixes being able to set the zoom factor back to 1 again, the other bug needs its own issue really.
