### ISSUE TITLE
Incorrect flip behaviour in CANVAS mode

### ISSUE THREAD

**Issue by jronn** [photonstorm/phaser#4636]
## Version
Phaser Version: *v3.18.1* 

Operating system: *macOS Mojave 0.14.5*

Browser: *Chrome 75.0.3770.100* (but does not seem to be browser-specific)

## Description

When setting the flip of a sprite that has a non-centered origin along the flip axis, the position of the sprite changes in CANVAS mode (while in WEBGL mode the image is simply rendered mirrored, which I would assume is the correct behaviour).

I.e, display of flipped sprite is inconsistent depending on if you're in CANVAS / WEBGL mode.

## Example Test Code

https://codepen.io/anon/pen/dBeBPE

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
