### ISSUE TITLE
Graphics as a Sprite

### ISSUE THREAD

**Issue by bigswede74** [photonstorm/phaser#4637]
I'm attempting to make a graphic interactive so the user can click on the graphic that is drawn. Is it possible to add a graphic as a sprite?

**Comment by photonstorm** [comment]
I don't fully understand the question, do you mean a `Graphics` Game Object, or just a graphic file you've loaded? It sounds like this question would be best asked on the Phaser Discord or Forum to be honest, as it doesn't sound like an API issue.

**Comment by bigswede74** [comment]
You are correct, I do mean a GameObject.Graphics object having greater capabilities. An example would be drawing a rounded rectangle and being able to tie into the mouse click events for the rectangle.

**Comment by photonstorm** [comment]
Sure, you can add a hit area to a Graphics object. Have a look at the code behind this example for one way of doing it: http://labs.phaser.io/view.html?src=src%5Cinput%5Cgame%20object%5Cgraphics%20object%20example.js

If you don't mind I'd like to close this issue, as it's not an API bug. Please come chat with us in the Phaser Discord or forum where we'll be only too happy to help further!

**Comment by bigswede74** [comment]
@photonstorm Thanks for the help I think this example will work for me.
