### ISSUE TITLE
Create Base64 from Images

### ISSUE THREAD

**Issue by DanLiamco** [photonstorm/phaser#4638]
I have 3 images in my scene.

this.trees = this.add.image(0, 0, 'trees');
this.grass = this.add.image(0, 0, 'grass');
this.sky = this.add.image(0, 0, 'sky');

I want to combine them and then create a base64 image string of the three images combined.

Is this possible?

Thanks!

**Comment by DanLiamco** [comment]
So far I'm thinking of making a canvas outside of Phaser

        this.canvas = document.createElement('canvas');
        this.ctx = this.test.getContext('2d');

I think the next step might be drawing the image on the canvas somehow then using this.canvas.toDataURL();

Am I on the right track? If so, how do you add images from Phaser to the canvas?

**Comment by photonstorm** [comment]
Use a Render Texture and the new `snapshot` feature that is coming in the 3.19 release (already in master branch ready for you to test)

**Comment by DanLiamco** [comment]
Thank you! :)
