### ISSUE TITLE
Jumping Logo (first tutorial) is broken on Firefox in Android

### ISSUE THREAD

**Issue by j2l** [photonstorm/phaser#4639]
## Version
Phaser 3.18.1
Android 5.1.1
Firefox 67.0.3 (2019 June 18)

## Description
![Screenshot_2019-07-05-10-19-06](https://user-images.githubusercontent.com/65325/60709236-3b9dc800-9f10-11e9-90cd-a2d4aa1774f4.png)

Just a frozen full screen logo on top of background. No flame.

## Example Test Code
See Phaser 3 first tutorial (jumping logo with flame).

## Additional Information
Run with "Phaser plus" gulp server on LAN
I know Android 5.1.1 is old, but it's mostly related to Firefox that happily runs on it.
There's no console to check though.

**Comment by j2l** [comment]
Even weirder,
```
create(){
    const x = this.cameras.main.width/2;
    const y = this.cameras.main.height/2;
    this.add.image(x,y,'sky');
    this.add.image(10, 10, 'logo');
}
```
results in:
![Screenshot_2019-07-05-10-45-18](https://user-images.githubusercontent.com/65325/60710171-5cffb380-9f12-11e9-8162-b24762add46f.png)

It removes the last element.

**Comment by photonstorm** [comment]
Thank you for opening this issue, however, I'm going to close it off now as there has been no progress made on this issue in quite some time, and sadly no contributions from anyone else to help fix it. I'm sorry we couldn't resolve it in this case.
