### ISSUE TITLE
Display.Align.To.* and Display.Align.In.* methods works incorrectly with scaled game objects

### ISSUE THREAD

**Issue by bruce87x** [photonstorm/phaser#4640]
**Phaser Version: 3.18.1**

Scaled game objects will be positioned incorrectly when using Display.Align methods. 
Problem apply to both positioned object and object which serves as reference point.

It's propably caused by using width/height instead of displayWidth/displayHeight when calculating position.

**Comment by rexrainbow** [comment]
Yes, it uses width/height, and originX/originY. For example, [SetCenterX.js](https://github.com/photonstorm/phaser/blob/master/src/display/bounds/SetCenterX.js#L22-L24).

**Comment by photonstorm** [comment]
I'm in two minds about changing this, as to do so will prevent it from working on Game Objects that don't have a display size, but equally, it makes sense to change it, even though it's an API breaking change too.

**Comment by bruce87x** [comment]
I assume that objects without display size properties are not scalable, for this objects calculation can fallback to width/height

**Comment by photonstorm** [comment]
Which requires a conditional check in every call.

**Comment by bruce87x** [comment]
Alternatively those objects could have const displayWidth/displayHeight properties set equal to width/height

**Comment by rexrainbow** [comment]
It is very easy to implement this feature, just replacing 
- `gameObject.height` to `gameObject.displayHeight`, and 
- `gameObject.width` to `gameObject.displayWidth` 

in all files of `display\bounds\` folder. 

Could I create PR for it? Since **it's an API breaking change**, I am not sure what is a better way to solve this incompatible issue.

**Comment by samme** [comment]
I think [BitmapText](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.BitmapText.html) and [DynamicBitmapText](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.DynamicBitmapText.html) are the only classes with `width` and `height` but no `displayWidth` and `displayHeight`.

**Comment by photonstorm** [comment]
It has worked like this for many years now, so honestly, at this stage, I'm happy to leave it be. I looked at changing it for 3.50 but it's not quite as trivial as it appears and I'd rather not change it for the sake of it.
