### ISSUE TITLE
Issue with multiple instances of the same shader using uniforms

### ISSUE THREAD

**Issue by davidmball** [photonstorm/phaser#4641]
##  Version
* Phaser Version: 3.17.0, 3.18.1
* Operating system: Ubuntu 19.04
* Browser: Chrome

## Description
Multiple instances of the same shader using uniforms doesn't work and gives this error:
"WebGL: INVALID_OPERATION: uniform1f: location not for current program"

## Example Test Code
http://labs.phaser.io/edit.html?src=src\display\shaders\shader%20test%208.js
This example code breaks when adding a second instance of the 'Stripes' shader. Eg adding the shader2 as shown below. 
```
    var shader = this.add.shader('Stripes', 400, 300, 800, 600).setVisible(false);
    var shader2 = this.add.shader('Stripes', 400, 300, 800, 600).setVisible(false);
```

## Additional Information
Perhaps each instance of a shader needs to make its own copy of the shader program?

**Comment by photonstorm** [comment]
It does have its own shader program instance and copies of the uniforms too. My guess is that it's just not swapping to the new shader because it's the same as the previous one. Will investigate further.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by davidmball** [comment]
Confirming that this merge has fixed this issue. Thank you.
