### ISSUE TITLE
Part of Canvas area  goes black after ScaleManager.resize() when using RenderTexture object as background

### ISSUE THREAD

**Issue by bruce87x** [photonstorm/phaser#4643]
## Version

* Phaser Version: 3.18.1

* Operating system: Fedora 30

* Browser: Firefox, Chrome

## Description

I have game with resolution 1920x1080(landscape mode), this can be changed  dynamically 
to 1080x1920(portrait mode).

RenderTexture object servers as background, it's using 1920x1920 texture as source.

Before  resolution changes from landscape to portrait mode(or vice-versa) RT object is deystroyed and after resolution changes new RT object is created to fit updated canvas, but then part of the canvas area goes black. Problem occurs only in WEBGL mode, in CANVAS mode everything works fine. 
And it's related to RenderTexture object, when i replace it with Image problem disapears.

## Example Test Code

```

import * as phs from "phaser";


class MainScene extends phs.Scene {


  public preload() {
    //1920 x 1920
    this.load.image("background");
  }

  public create() {
    let isLandscape = true;

    let getSize = () => {
      return [
        isLandscape ? 1920 : 1080,
        isLandscape ? 1080 : 1920,
      ];
    };


    let rt = this.add.renderTexture(0, 0, 1920, 1080).setOrigin(0, 0).setDepth(1);
    rt.draw("background");

    let hRect = this.add.rectangle(0, 0, 1920, 100, 0x00ff00).setOrigin(0, 0).setDepth(2);
    phs.Display.Align.In.TopLeft(hRect, rt);

    let vRect = this.add.rectangle(0, 0, 100, 1920, 0x00ff00).setOrigin(0, 0).setDepth(2);
    phs.Display.Align.In.TopLeft(vRect, rt);


    let applyCallback = (item: phs.GameObjects.RenderTexture) => item.setInteractive().on("pointerdown", () => {
      isLandscape = !isLandscape;
      let size  = getSize();
      item.destroy();
      this.game.scale.resize(size[0], size[1]);
      item = this.add.renderTexture(0, 0, size[0], size[1]).setOrigin(0, 0).setDepth(1);
      item.draw("background");
      applyCallback(item);
    });
    applyCallback(rt);
  }
}


let config: phs.Types.Core.GameConfig = {
  type: phs.WEBGL,
  width: 1920,
  height: 1080,
  scale: {
    mode: Phaser.Scale.NONE,
    zoom: Phaser.Scale.NO_ZOOM
  },
  scene: [MainScene]
};


```

## Additional Information

**CANVAS  mode**

![landscape_good](https://user-images.githubusercontent.com/52576950/60921931-ed841e00-a29b-11e9-98ec-278df8b7a1c9.png)
![portrait_good](https://user-images.githubusercontent.com/52576950/60921936-ed841e00-a29b-11e9-9329-6969df1620f2.png)

**WEBGL mode**

![landscape_bad](https://user-images.githubusercontent.com/52576950/60921930-ed841e00-a29b-11e9-8c57-5897929b9d31.png)
![portrait_bad](https://user-images.githubusercontent.com/52576950/60921935-ed841e00-a29b-11e9-878d-8fc36dc45daa.png)

**Comment by pavels** [comment]
Just hit the same thing

Basically if you try to draw anything into RenderTexture right after creating it in resize callback, things start to get very weird. Even fill (looks like the fill actually breaks things the most, looks like it depends on how much you draw).

the workaround - but rather clunky - is to use `scene.time.delayedCall` and draw in there. Interesting is that low timeouts (like 1) don't work. Also drawing in next update don't work either - it must be later than that.

Also it doesn't work only if `Phaser.Scale.RESIZE` is used. `Phaser.Scale.FIT` or `Phaser.Scale.FILL` works fine - at least for me.

**Comment by photonstorm** [comment]
I'm not really sure why you would destroy and then create a RenderTexture in a resize callback, it seems an intense thing to do. Why not call `RenderTexture.resize()` instead, with the new width and height?

**Comment by bruce87x** [comment]
This is just a simplified example. My game has different hud on desktop, mobile landscape nad mobile portrait, each is implemented as separate scene. When I rotate phone and scene changes, different RenderTexture object must be created.

**Comment by pavels** [comment]
@photonstorm i omitted one major point - i use the RenderTexture as mask. Resizing RenderTexture when used as mask never worked correctly - when you make it smaller, very strange glitches will appear. The only workaround was to unset the mask, destroy the texture, create new one and set that as mask.  Unsetting the mask than resizing and setting it back made no differences - still glitched the same way.

Now (3.18.1) looks like resizing is broken completely - if you try to resize it to smaller dimensions, the dimensions are never correct, the RenderTexture will always be smaller than dimensions you give. Also looks like after resize, objects drawn to RenderTexture looks deformed.

Also one strange thing, when you try to use RenderTexture.resize(), all text (browser font) in whole game  gets very blurry, like something breaks somewhere in the pipeline and affects other non related things.

**Comment by photonstorm** [comment]
Closing this off as I have tested this under 3.50 and it's working perfectly, both normally resizing a Render Texture and resizing one being used as a mask (no setting and resetting of it required any longer). Test code below:

```js
var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('brush', 'assets/sprites/brush1.png');
    this.load.image('pic', 'assets/pics/brilliance-jim-sachs.png');
}

function create ()
{
    var rt = this.add.renderTexture(0, 0, 800, 600);

    var mask = rt.createBitmapMask();

    var pic = this.add.image(400, 300, 'pic');

    pic.setMask(mask);

    this.input.on('pointermove', function (pointer) {

        if (pointer.isDown)
        {
            rt.draw('brush', pointer.x - 32, pointer.y - 32);
        }

    }, this);

    this.input.keyboard.on('keydown-SPACE', function (event) {

        rt.resize(400, 300);

    });
}
```
