### ISSUE TITLE
Spine objects flip when camera uses setRenderToTexture

### ISSUE THREAD

**Issue by probt** [photonstorm/phaser#4647]
## Version
* Phaser Version: 3.18.1
* Operating system: MacOS 10.14.4
* Browser: Chrome

## Description
Setting a camera to setRenderToTexture flips/mirrors any Spine objects on the y axis.

## Example Test Code
https://codepen.io/paulrbt/pen/wLRMjG

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
