### ISSUE TITLE
add a moveTo(gameObject, x, y, speed) method that stops the player at the given location

### ISSUE THREAD

**Issue by mmorainville** [photonstorm/phaser#4648]
Hi,

I'm currently developping a Pokemon-style RPG and one of the issue I had was to implement a grid-based movement. Indeed, the player in Pokemon moves according to a tilemap of 16x16 cells and when the player hit a movement key (say left), he should go left from his position to his position + 16px left even if the key has been released.

Currently this can't be achieved simply using the Arcade Physics system because the current moveTo method doesn't stop the player when it arrives at its location (see https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.ArcadePhysics.html#moveTo).

And we can't either check `player.x % 16 === 0` because the update ticks are not exact while using setVelocity on the body.

So this feature would really people that are trying to achieve grid-based movement without plugins.

Thanks for reading and regards,
M.

**Comment by photonstorm** [comment]
I'll add this as a feature request with a low priority because there are several plugins out there that already do this for you.

**Comment by kendistiller** [comment]
@mmorainville I feel like the existing `Phaser.Math.GetSpeed` would help a lot with this.

```
GetSpeed(distance: number, time: number): number

Calculate the speed required to cover a distance in the time given.

  @param distance — The distance to travel in pixels.

  @param time — The time, in ms, to cover the distance in.
```

**Comment by mmorainville** [comment]
@kendistiller mmh that's interesting! I'll give it a shot. Thanks for your input! ;)

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.
