### ISSUE TITLE
SmoothedKeyControl MinZoom vs BaseCamera minZoom

### ISSUE THREAD

**Issue by giviz** [photonstorm/phaser#4649]
## Version

* Phaser Version: Phaser v3.18.1-FB (WebGL)

* Operating system: MAC OS

* Browser:

## Description

SmoothedKeyControl.js L449 min allowed zoom : 0.1
BaseCamera.js L1410 min allowed zoom : 0.001

## Example Test Code

Just update SmoothedKeyControl.js to have also a min allowed zoom of 0.001

## Additional Information

Thank you.

**Comment by photonstorm** [comment]
To be honest, the 0.001 value is only there to avoid a divide by zero error elsewhere in the code. In all practical uses, a zoom of 0.1 is already too tiny! However, there's no harm in making these match up, so I have.
