### ISSUE TITLE
The cursors.right.timeUp property is having a value of 0

### ISSUE THREAD

**Issue by Kailcor** [photonstorm/phaser#4650]
## Version

* Phaser Version: 3.18.1, 3.17.0 and 3.16.0
* Operating system: Windows 10
* Browser:

## Description
The cursors.right.timeUp is returning 0, but it's not been pressed. 
In my game I create a function to check double tap for a arrow: 

`function doubleTap(cursor) {
  console.log(cursor+" timeDown: " + cursor.timeDown + ",timeUp: "+cursor.timeUp);
  return cursor.timeDown - cursor.timeUp < 100;
}`

where cursor is cursors.right, in this case. 
I tested for all the directions and is working fine, but for the right cursor it is not. 
To discard something else in my code was the problem, I try this phaser lab example, adding my function doubleTap, and I get the same result: 

[Cursors Example](https://labs.phaser.io/edit.html?src=src/input\keyboard\cursor%20keys.js)

For right cursor:  timeDown: 3734.3500000424683,timeUp: 0
For left cursor: timeDown: 3734.3500000424683,timeUp: 3806.2950000166893
## Example Test Code
` var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    backgroundColor: '#0072bc',
    physics: {
        default: 'arcade',
        arcade: {
            debug: true
        }
    },
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var cursors;
var player;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('block', 'assets/sprites/block.png');
}

function create ()
{
    cursors = this.input.keyboard.createCursorKeys();

    player = this.physics.add.image(400, 300, 'block');

    player.setCollideWorldBounds(true);
}

function update ()
{
    player.setVelocity(0);
    
    if (cursors.left.isDown)
    {
        doubleTap(cursors.right);
        player.setVelocityX(-300);
    }
    else if (cursors.right.isDown)
    {
        doubleTap(cursors.right);
        player.setVelocityX(300);
    }

    if (cursors.up.isDown)
    {
        player.setVelocityY(-300);
    }
    else if (cursors.down.isDown)
    {
        player.setVelocityY(300);
    }
}
function doubleTap(cursor) {
  console.log(cursor+" timeDown: " + cursor.timeDown + ",timeUp: "+cursor.timeUp);
  return cursor.timeDown - cursor.timeUp < 100;
} `

## Additional Information

I'm not complety sure, but I think this error do not happen on a previos version (when I wrote that code) but I can't remember which one. I tested this issue with the versions that I wrote above.

I will try with another version to find out in which version it work well.
I try to look in the phaser code when it is seted (timeUp value) and it just is setted in two parts: 

`onUp: function (event)
    {  ...
      this.timeUp = event.timeStamp;
       ....}
`
and
`reset: function () {
...
 this.timeUp = 0;
...
`
So this make me think: 
or the onUp event is never triggered for cursors.right or it is been reseted.... 

 
It might be related to issue #4635. Where onUp appears to not be called.

**Comment by tranchikhang** [comment]
In your example code, when left button is pressed, are you passing the correct parameter?
```javascript
if (cursors.left.isDown)
{
    // This should be cursors.left I think
    // doubleTap(cursors.right);
    doubleTap(cursors.left);
    player.setVelocityX(-300);
}
```

**Comment by photonstorm** [comment]
This is working fine in the current dev build and 3.18.1 too. Here is a test I created to demonstrate:

http://labs.phaser.io/view.html?src=src%5Cinput%5Ckeyboard%5Ccursors%20time.js&v=dev

If the Key has never been _released_  before, then `timeUp` should absolutely be zero. After it has been pressed once it is correctly populated from that point on. Obviously, it can't be any other value until you've released it once.

I'll re-open this issue if you can demonstrate why the above doesn't work, please.
