### ISSUE TITLE
Cannot init Phaser.Textures.CanvasTexture

### ISSUE THREAD

**Issue by Jugacu** [photonstorm/phaser#4651]
## Version
* Phaser Version: v3.18.1-FB
* Operating system: Windows 10
## Description
Cannot initialize Phaser.Textures.CanvasTexture

So, whenever i try to create an instance of CanvasTexture it throws me an error that says:

![error](https://i.gyazo.com/ac12876b2922cb73b4c34e0e862075b7.png)

Also i wanna mention that its type definitions requires itself at the constructor so it can't be never initialized.

## Example Test Code

https://codepen.io/anon/pen/pXBQYx

**Comment by photonstorm** [comment]
I've exposed it so you can instantiate it directly now if you wish, although you cannot then use it as a texture for any other Game Object, and it's up to you to clear the canvas element it creates after you're done with it.
