### ISSUE TITLE
DynamicBitmapText setSize() does not account for container position

### ISSUE THREAD

**Issue by lgibson02** [photonstorm/phaser#4653]
* Phaser Version: Phaser v3.19.0-beta1 (latest master)

It seems if you put a DynamicBitmapText in a container and then crop it using it's setSize() method, the position of the container is not accounted for. This causes the results seen in the demo I made below.

[Demo Here](https://labs.phaser.io/edit.html?src=https://gist.githubusercontent.com/lgibson02/d9ee4ee8407076dec96df8571ad62348/raw/09fd5c06e0c3afd3761eec96cccab06dbd05736a/test.js&v=dev)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
