### ISSUE TITLE
Canvas resize when keyboard is opened for text input

### ISSUE THREAD

**Issue by kanthi0802** [photonstorm/phaser#4655]
When a text input dom element is focused the game canvas is resized instead of the keyborad overlaying on top of the canvas.

**Comment by photonstorm** [comment]
If you're scaling your game based on available window space in the browser, and that changes, then the game will scale. This isn't a bug, it's doing exactly what you asked it to. We have absolutely zero control over what the browser does when it opens a virtual keyboard, all we can do is respond to it. If this is something you don't want your game to do, you need to disable scaling before focusing the text input, and re-enable it afterward.
