### ISSUE TITLE
Support tint in bob object

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4656]
It seems that [bob has a default tint value 0xffffff](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/blitter/BlitterWebGLRenderer.js#L97) in webgl render code. 
Is it possible to assign this tint value of any bob object?

**Comment by rexrainbow** [comment]
Particle also has [single tint property](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/particles/Particle.js#L198), thus it is fine to have single tint property in bob object, imo.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
