### ISSUE TITLE
Physics Group createCallback not working as expected, removes hit detection

### ISSUE THREAD

**Issue by kendistiller** [photonstorm/phaser#4657]
## Version
* Phaser Version: 3.18.1
* Operating system: Mac OS

## Description

I'm having an issue related to #4420, but with createCallback on Physics group. createCallback is _never_ called within a Physics Group config. If you manually assign the createCallback property after the group has been created, then the physics body becomes invalidated and collision does not work. You have to manually enableBody on the created child to get it to work again.

## Example Test Code

CreateCallback is _never_ called within a Physics Group config:
```
const bullets = this.physics.add.group({
    createCallback: () => console.log('create'); // DOES NOT GET CALLED
});
```

The callback _will_ get called if adding it subsequently as a property:
```
bullets.createCallback = () => console.log('create');` // GETS CALLED
```
**However**, once you add the above callback property, _collision detection stops working completely_:
```
this.physics.add.overlap(this.player, bullets, () => console.log('overlap')); // DOES NOT GET CALLED
```

## Additional Information
This hack (re-enabling child body in callback) works, but feels like working against what it's supposed to do. We're trying to say "all objects in this group have a physics body" so having to enable physics again isn't great. Perhaps I'm doing something wrong from the get-go:
```
bullets.createCallback = (child) => { if (!child.body) { this.physics.world.enableBody(child); } };
```

**Comment by kendistiller** [comment]
This hack works, but feels like working against what it's supposed to do. We're trying to say "all objects in this group have a physics body" so having to enable physics again isn't great. Perhaps I'm doing something wrong from the get-go:
```
bullets.createCallback = (child) => { if (!child.body) { this.physics.world.enableBody(child); } };
```

**Comment by photonstorm** [comment]
The Physics Group uses this callback itself for its own internal requirements, so when you replace it (as per the second example) you override what it needs to do, hence no physics bodies are created. It should be marked as private, but JSDoc is a bit crappy when it comes to overriding docs inherited from parent classes.

**Comment by kendistiller** [comment]
@photonstorm That makes a lot of sense, and like I mentioned it felt very hacky. Is there any way we can get a hook into this for the physics groups, while still allowing it to do its own work internally?

**Comment by photonstorm** [comment]
Override it, like you're doing, but make sure to call `Group.createCallbackHandler(child)` at the start of your own handler so it's still given all the right properties by the Group, then you can do whatever you need extra after that.

**Comment by kendistiller** [comment]
Yep, that will work thanks. Is there any reason not to implement this directly into the physics group itself? (calling createCallbackHandler + custom hook)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
