### ISSUE TITLE
Pointer worldX, worldY not updating correctly 

### ISSUE THREAD

**Issue by Nick-lab** [photonstorm/phaser#4658]
As seen in the phaser example `https://phaser.io/examples/v3/view/input/camera/world-coordinates` if the mouse is not moved when camera is scrolled the pointers world positions are not updated. and `this.input.setPollAlways();` does not fix this issue. in this instance how would i get the angle between the "player" position x/y and the pointers x/y is the pointer does not update its world x/y ?

I thought of using the main cameras scrollX and scrollY + pointers screen x/y as this will allow for correct world position hever the scrollX and scrollY are incorrect when using camera zoom

**Comment by photonstorm** [comment]
If you want to check the `worldX/Y` values _outside_ of an input event handler, then you need to update the Pointer for the given camera first. You can do this by calling `Camera.getWorldPoint(pointer.x, pointer.y)` and then assigning the return values to `worldX/Y`. Or, you can use the function ``Pointer.updateWorldPoint`` which is new in 3.19 Beta 1.
