### ISSUE TITLE
Angular 7 and Phaser 3

### ISSUE THREAD

**Issue by fromnowhereuser** [photonstorm/phaser#4661]
Hello,

I've just installed the last release of phaser 3 like:
    "phaser": "^3.18.1",
in my package.json.

In my angular.json i put:
            "scripts": [
              "node_modules/phaser/dist/phaser.js"
            ],
To statically add phaser.js to my angular app.
When i start my application, compilation failed because of:

ERROR in node_modules/phaser/types/phaser.d.ts(7645,54): error TS2304: Cannot find name 'ActiveXObject'.

this is the line 7645:         
function ParseXML(data: string): DOMParser | ActiveXObject;

What is this activeXObject ?? Does it come from IE ? Do i have to use polyfills ?

**Comment by photonstorm** [comment]
This is a TypeScript requirement, not a polyfill. In your `tsconfig.json` file add `"scripthost"` in the `lib` array otherwise you won't get the ActiveXObject types included.
