### ISSUE TITLE
Custom Game Phaser.GameObjects.Container 

### ISSUE THREAD

**Issue by fromnowhereuser** [photonstorm/phaser#4662]
Hello,

I defined a custom GameObject like this:

`export class Button extends Phaser.GameObjects.Container {
  button: any;
  text: any;

  constructor(scene: Phaser.Scene, x, y, text, callback) {
    super(scene, x, y);

    this.button = scene.add.sprite(0, 0, 'bblank');
    const t = this.scene.add.text(0, 0 - 15 / 2, text, {
      font: '17px industrial',
      fill: '#759eb8'
    });
    t.setX(0 - t.width / 2);
    t.setY(0 - t.height / 2);

    this.add(this.button);
    this.add(t);
    this.button
      .setInteractive({ useHandCursor: true })
      .on('pointerover', () => this.enterButtonHoverState())
      .on('pointerout', () => this.enterButtonRestState())
      .on('pointerdown', () => this.enterButtonActiveState())
      .on('pointerup', () => {
        this.enterButtonHoverState();
        callback();
      });
  }

  enterButtonHoverState() {
    this.button.setTint(0xd6d3cb);
  }

  enterButtonRestState() {
    this.button.clearTint();
  }

  enterButtonActiveState() {
    this.button.setTint(0xefdabd);
  }
}
`

Everything is fine. I also had this, on my main Angular Component:
@HostListener('window:resize', ['$event'])
  onResize(event) {
    this.config.width = event.target.innerWidth;
    this.config.height = event.target.innerHeight;

    this.mainVew.destroy(true, false);
    this.mainVew = new Phaser.Game(this.config);
  }

Everything work well if my custome object dont have any events handled. (without setInteractive({ useHandCursor: true }) and everything else)

BUT, if i add event handler, everytime my 'this.mainVew.destroy(true, false);' is destroyed i have this error:
core.js:15724 ERROR TypeError: Cannot read property 'style' of null
    at InputManager.resetCursor (InputManager.js:463)
    at InputPlugin.clear (InputPlugin.js:767)
    at Sprite.destroy (GameObject.js:591)
    at Button.removeAll (Container.js:865)
    at Button.preDestroy (Container.js:1308)
    at Button.destroy (GameObject.js:576)
    at Container.removeAll (Container.js:865)
    at Container.preDestroy (Container.js:1308)
    at Container.destroy (GameObject.js:576)
    at DisplayList.shutdown (DisplayList.js:169)

It is clearly events related, but i dont get why "STYLE" is involved...

Can you help me a bit ?

Thx you in advance

**Comment by photonstorm** [comment]
I've fixed a bug that will stop the style being reset if the canvas has been destroyed, which will get past the issue you're having here. However, you shouldn't destroy and then re-create the game instantly, you should wait for the destroy process to complete first (there is an event to listen for this) and then re-create the game.

Either way, the style bug fix is now in the master branch.

**Comment by fromnowhereuser** [comment]
ok, thx you very much. But... i dont understand, the destroy event is throwed by:
Phaser.Scene object ?
Phaser.Game object ?

Any of these instance have something like .on('destroy', () => { // rebuild another Phaser.Game}),

**Comment by photonstorm** [comment]
```
game.events.on('destroy', function () {
  // re-create your can instance here
});
```

**Comment by fromnowhereuser** [comment]
Either way, the style bug fix is now in the master branch:
    "phaser": "^3.18.1" ???
`
  @ViewChild('phaserview')
  phaserview: ElementRef;

  mainVew: Phaser.Game;

  config: Phaser.Types.Core.GameConfig = {
    title: 'synoptic',
    width: 800,
    height: 600,
    parent: 'content',
    physics: {
      default: 'arcade',
      arcade: {
        gravity: { y: 300 },
        debug: false
      }
    },
    render: {
      antialias: true,
      roundPixels: true
    },
    input: {
      activePointers: 3,
      keyboard: true,
      touch: true,
      windowEvents: true
    },
    canvasStyle: '',
    scene: [SmScene],
    backgroundColor: '#e5e6e9'
  };

  @HostListener('window:resize', ['$event'])
  onResize(event) {
    this.config.width = event.target.innerWidth;
    this.config.height = event.target.innerHeight;

    this.mainVew.events.on('destroy', () => {
      this.mainVew = new Phaser.Game(this.config);
    });
    this.mainVew.destroy(true, false);
  }

  ngOnInit(): void {}

  ngAfterViewInit(): void {
    console.log(this.phaserview);
    this.config.width = window.innerWidth;
    this.config.height = window.innerHeight;
    // this.config.width = 200;
    // this.config.height = 200;
    this.mainVew = new Phaser.Game(this.config);
  }

  ngOnDestroy(): void {
    this.mainVew.destroy(true);
  }
`

**Comment by photonstorm** [comment]
3.18 isn't the master branch. That's the previous release build. You have to make your own build from the master branch source if you want to use it now, or wait for the official 3.19 release.
