### ISSUE TITLE
ScaleMode.None setZoom() and resize() behaviour change 

### ISSUE THREAD

**Issue by seejay92** [photonstorm/phaser#4663]
## Version

* Phaser Version:  >= 3.18.0
* Operating system: Win 10
* Browser: Chrome, Firefox

## Description

Since version 3.18.0 there appears to be a change to ScaleMode.None mode, and expected behaviour of related functions. Using a "safezone" method I calculate scale and max height/width from config values, and run setZoom() + resize(). 3.17.0 and below this works fine, but there appears to be some internal refactoring that has affected my identical examples, and the canvas is stretched wrongly when the window is resized. Not sure if there's something that can be done my end to fix this, but happy to share scale mode example if I can rectify.

## Example Test Code

3.17.0 (Expected behaviour)
https://codepen.io/seejay92/pen/voBPPP

3.18.0
https://codepen.io/seejay92/pen/ymydbd

## Additional Information

Possibly related to issue/note in #4633.

**Comment by photonstorm** [comment]
Sorry, should have mentioned this ages ago, but it was fixed in 3.19 (make sure you use the correct CONST of `Phaser.Scale.NONE` though)
