### ISSUE TITLE
Camera causing stutter on tilemap or sprite

### ISSUE THREAD

**Issue by JChouCode** [photonstorm/phaser#4664]
When I use the camera to follow my sprite, the background stutters slightly. It is not super apparent, but still noticeable. I am using a tilemap: 21 tiles x 200 tiles, 16 px x 16 px, and an object sprite that the user can control. I checked the framerate and I am at a constant 60 fps, however the background generated by the tilemap still stutters. Is this unavoidable? I am using **typescript** btw.

I have pixelart on and zoom set to 1. I already tested roundPixels on/off, lerp 1/0.1/0.05, anti-aliasing on/off, all dynamic or all static layers. Nothing seems to fix the background stutter. 

With roundpixels on the stutter seems to actually get more apparent and my character sprite also starts to stutter a lot.

I saw that this was fixed in #3738, but I still have the same issue.

**Comment by jrrockett** [comment]
I am having a similar issue. Primarily when the game object that the camera is following moves in the X and Y directions simultaneously. Did you happen to find a fix?

**Comment by JChouCode** [comment]
> I am having a similar issue. Primarily when the game object that the camera is following moves in the X and Y directions simultaneously. Did you happen to find a fix?

Unfortunately, no. I just deal with it, it's slightly noticeable but fine.

**Comment by chadj** [comment]
Adding another voice here - I'm also running into this.

**Comment by jrrockett** [comment]
I found that this only occurred when the object that the camera was attached to had a velocity. When I just update the objects positions manually - by adding/subtracting from the body.position - things smooth out. This was kind of an issue for collisions, but seems to work fine doing overlap checks when updating the velocity (to see if you should manually update the position).

**Comment by chadj** [comment]
@jrrockett Yup, that also did the trick for me.  Thanks for the tip.  I wonder if this is due to the arcade physics fps not matching the monitor framerate.

**Comment by Wambosa** [comment]
Good day,
First off phaser is an excellent engine!

I also ran into this jitter problem.
The plan was to remove the connection between the possibly unstable physics position and the camera tween. This code did dramatically improve the jitter to where it is even less noticeable. However, setting lerpX or lerpYto anything other than 1 causes the jitter comes back furiously.

Some things I'd like to try to further improve are:
A. only update the `cameraFocus` every N seconds _(fixed update)_ since it should not need to move every frame.

B. figure out what @photonstorm meant [when he said](https://github.com/photonstorm/phaser/issues/3738#issuecomment-396904512);
> ...it looks like a standard WebGL issue when sprite sheets aren't correctly prepared for GL textures and get pixel bleeding from edge frames...

If I can figure out if my sprites are properly prepared or not, maybe this becomes a non issue.

`pseudo code`
```
create() {
  // new Phaser.Physics.Matter.Sprite
  this.sprite = this.matter.add.sprite(0, 0, 'mytexture')
  this.sprite.speed = 4
  this.destination = {x: 100, y: 100}

  //try to create a invisible image that follows around the player without physics
  this.cameraFocus = {x: this.sprite.x, y: this.sprite.y}
    this.cameras.main.startFollow(
      this.cameraFocus,
      true,
      1,
      1
    )
}

update() {
   // shortened physics move code
    this.setVelocity(0)
    this.setAngularVelocity(0)

    let dx = this.destination.x - this.x
    let dy = this.destination.y - this.y
    let angle = Math.atan2(dy, dx)
    let deltaLock = delta / 16.6 // framerate modifier
    let vx = Math.cos(angle) * this.sprite.speed * deltaLock
    let vy = Math.sin(angle) * this.sprite.speed * deltaLock
    this.sprite.setVelocityX(vx)
    this.sprite.setVelocityY(vy)

    //dramatically reduce jitter by setting an invisible objects position manually
    this.cameraFocus.x = Math.round(this.sprite.x)
    this.cameraFocus.y = Math.round(this.sprite.y)
}
```

`phaser config`
```
  return new Phaser.Game({
    type: Phaser.AUTO,
    width: Math.min(window.innerWidth, 1920),
    height: Math.min(document.body.clientHeight - 82, 1080),
    backgroundColor: '#000000',
    parent: containerId,
    forceSetTimeOut: true,
    roundPixels: false,
    pixelArt: true,
    physics: {
      default: 'matter',
      matter: {
        debug: true,
        enableSleeping: false,
        gravity: {
          y: 0,
          x: 0,
        }
      }
    },
    scene: Scene
  })
```

**Comment by photonstorm** [comment]
Going to close this issue as it's the same discussion going on in #5018. I appreciate that this issue came first, and thank you for opening it, however, the other issue has more traction (and resolutions), so rather than keep a duplicate I'd suggest tracking that one instead, please.
