### ISSUE TITLE
Debug Colliding tiles throw an error: t.translate is not a function.

### ISSUE THREAD

**Issue by Kailcor** [photonstorm/phaser#4665]
## Version

* **Phaser Version**: 3.18.0 and 3.18.1

* Operating system: Windows 7

* Browser: No browser related

## Description

When trying to debug tiles collisi;on with renderDebug() throw the error: t.translate is not a function.

![image](https://user-images.githubusercontent.com/14263139/61579859-046b1180-aae1-11e9-9756-b24ac13e2bd4.png)

## Example Test Code

When I look for examples to check if the way to debug has changed, I saw that the example fails too, so it works as an test code:

https://phaser.io/examples/v3/view/game-objects/tilemap/static/debug-colliding-tiles

## Additional Information

The weird thing is that it works with: 3.17.0 and with "Development build" version.
The error happen in the renderDebug function, 
    **_graphics.translate(layer.tilemapLayer.x, layer.tilemapLayer.y);_**
 
here:

`var RenderDebug = function (graphics, styleConfig, layer)
{
    if (styleConfig === undefined) { styleConfig = {}; }

    // Default colors without needlessly creating Color objects
    var tileColor = (styleConfig.tileColor !== undefined) ? styleConfig.tileColor : defaultTileColor;
    var collidingTileColor = (styleConfig.collidingTileColor !== undefined) ? styleConfig.collidingTileColor : defaultCollidingTileColor;
    var faceColor = (styleConfig.faceColor !== undefined) ? styleConfig.faceColor : defaultFaceColor;

    var tiles = GetTilesWithin(0, 0, layer.width, layer.height, null, layer);

    graphics.translate(layer.tilemapLayer.x, layer.tilemapLayer.y);
    graphics.scale(layer.tilemapLayer.scaleX, layer.tilemapLayer.scaleY);`

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
