### ISSUE TITLE
Typescript defs: Namespace 'Phaser.Tweens' has no exported member 'Events'

### ISSUE THREAD

**Issue by PhaserEditor2D** [photonstorm/phaser#4666]
## Version

* Phaser Version: 3.19.0-beta1

* Operating system: Linux

## Description

If I run:

```
$ npm run tsdev
```

I get the following errors:

```
$ cat scripts/tsgen/test/output.txt 
../../../types/phaser.d.ts(81189,56): error TS2694: Namespace 'Phaser.Tweens' has no exported member 'Events'.
../../../types/phaser.d.ts(81406,49): error TS2694: Namespace 'Phaser.Types.Tweens' has no exported member 'StaggerBuilderConfig'.
../../../types/phaser.d.ts(82297,57): error TS2694: Namespace 'Phaser.Tweens' has no exported member 'Events'.
../../../types/phaser.d.ts(82304,53): error TS2694: Namespace 'Phaser.Tweens' has no exported member 'Events'.
```

## Additional Information

I think different methods are using `Phaser.Tweens.Events` as an argument type but it is declared as a namespace.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
