### ISSUE TITLE
Functions in SceneConfig do not have the right context value (`this`)

### ISSUE THREAD

**Issue by posva** [photonstorm/phaser#4669]
## Version

* Phaser Version: 3.18

* Operating system: N/A

* Browser:
 N/A

## Description

When creating a `Game` instance, the `scene` option allows to define functions like `create`, `init`, `preload` and `update`. All of these have access to the scene through `this` but this isn't set in typings forcing the user to add the parameter manually: 

```ts
new Phaser.Game({
  scene: {
    preload(this: Phaser.Scene) {}
  }
})
```

## Example Test Code

```ts
new Phaser.Game({
  scene: {
    preload() {
      this.load.setBaseURL('') // property preload does not exist on type Function | Phaser.Scene | Phaser.Scene[] | Phaser.Types.Scenes.SettingsConfig | Phaser.Types.Scenes.SettingsConfig[] | Phaser.Types.Scenes.CreateSceneFromObjectConfig | Phaser.Types.Scenes.CreateSceneFromObjectConfig[] | Function[]
    }
  }
})
```

## Additional Information

I tried adding `@this` to the JsDocs but it is omitted (https://github.com/photonstorm/phaser/pull/4668#issuecomment-513569021)

```diff
/**
 * Can be defined on your own Scenes.
 * This method is called by the Scene Manager when the scene starts, before `preload()` and `create()`.
 *
 * @callback Phaser.Types.Scenes.SceneInitCallback
 * @since 3.0.0
 *
+ * @this {Phaser.Scene}
 * @param {object} data - Any data passed via `ScenePlugin.add()` or `ScenePlugin.start()`. Same as Scene.settings.data.
 */
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
