### ISSUE TITLE
i need phaser3 docs link but not (https://photonstorm.github.io/phaser3-docs/),it's catalogueis on the left 

### ISSUE THREAD

**Issue by wlinglinux** [photonstorm/phaser#4673]
**We're constantly trying to make Phaser 3 better**

So we'd love to hear about feature requests for the v3 API. Screenshots, example code or links to blog posts / other APIs are encouraged.

Please try and keep the requests sensible. We will only keep those we feel are within our abilities to add to Phaser, or that are a good fit for our API.

**[Optional] Do you want to help provide this feature?**

If you would like to get involved in helping build the feature, please let us know. We can then discuss implementation with you and the best way to approach it. Again, screenshots or mockups are really useful.

**Comment by photonstorm** [comment]
Not sure I really get what this issue is asking. You can browse the docs online, or you can download the repo and run them locally, where you can also edit the jsdoc template should you need to change their layout for your own requirements.
