### ISSUE TITLE
Adding DOM Elements causes issues in Internet Explorer 11

### ISSUE THREAD

**Issue by DanLiamco** [photonstorm/phaser#4674]
### Version

- Phaser Version: 3.18.1

- Operating System: Windows 10 64 bit

- Browser: Internet Explorer 11
### Description
Adding the following code to the Phaser Game Config causes issues:
`    dom: {
        createContainer: true
    }`

The game seems to be shifted below the DOM Container
### Example Test Code
http://labs.phaser.io/view.html?src=src%5Cgame%20objects%5Cdom%20element%5Cform%20input.js
### Additional Information
The following shows what the test code looks like in Mozilla Firefox 68.0.1
![image](https://user-images.githubusercontent.com/39140486/61776140-fdb80380-ae2c-11e9-80ed-8704a716f0c2.png)

The following shows what the test code looks like in Internet Explorer 11
![image](https://user-images.githubusercontent.com/39140486/61776235-33f58300-ae2d-11e9-9918-3c87299c5981.png)

**Comment by DanLiamco** [comment]
Additional Information: 

The issue was also observed in Phaser 3.17.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by DanLiamco** [comment]
I'll make sure to do that! Thank you!

**Comment by DanLiamco** [comment]
Just tested it on IE and it works as intended. Thanks again!
