### ISSUE TITLE
BitmapMask with Atlas

### ISSUE THREAD

**Issue by JacobCaron** [photonstorm/phaser#4675]
## Version

* Phaser Version: 3.17 & 3.18
* Operating system: Windows 10
* Browser: Chrome

## Description
When you have two images as part of the same atlas and you attempt to add a bitmap mask from one image to the other, WEB_GL throws infinite errors and the images are not rendered.

## Example Test Code
Paste the following here: https://labs.phaser.io/edit.html
```
var game = new Phaser.Game({
    type: Phaser.AUTO,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
});

function preload ()
{
    this.load.atlas('atlas', 'assets/atlas/megaset-1.png', 'assets/atlas/megaset-1.json');
}

function create ()
{
    let titan = this.add.image(400, 400, 'atlas', 'titan-mech');
    let ship = this.add.image(400, 400, 'atlas', 'ship');
    titan.mask = new Phaser.Display.Masks.BitmapMask(this, ship);
}
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
