### ISSUE TITLE
Event documentation is incorrect

### ISSUE THREAD

**Issue by enzeart** [photonstorm/phaser#4680]
## Version

* Phaser Version: 3.18.1

* Operating system: Mac OS Mojave 10.14

* Browser: Chrome, and when running the engine in HEADLESS mode on the server

## Description

Scene events don't work as specified in the documentation. Additionally, the documentation specifies some usage patterns that are invalid. For example: "[...]Listen to it from a Scene using this.scene.events.on('boot', listener)". When trying follow that example, I get the following typescript error: "Property 'events' does not exist on type 'ScenePlugin'." I'm using the documentation at https://photonstorm.github.io/phaser3-docs/Phaser.Scenes.Events.html

## Example Test Code

```typescript
import "phaser";
import Scene = Phaser.Scene;
import SettingsConfig = Phaser.Types.Scenes.SettingsConfig;
import { SCENE_AVAILABLE } from "src/event/event";
import START = Phaser.Scenes.Events.START;
import DESTROY = Phaser.Scenes.Events.DESTROY;
import SHUTDOWN = Phaser.Scenes.Events.SHUTDOWN;
import UPDATE = Phaser.Scenes.Events.UPDATE;

class ServerDemoScene extends Scene {
  constructor(public readonly config: SettingsConfig) {
    super(config);
  }

  init() {
    console.log(`Initializing demo scene: ${this.config.key}`);
    console.log(JSON.stringify(this.events.eventNames()));
    this.events.on(START, () => {
      console.log(`${this.config.key}: start`);
    });
    this.events.on(DESTROY, () => {
      console.log(`${this.config.key}: destroy`);
    });
    this.events.on(SHUTDOWN, () => {
      console.log(`${this.config.key}: shutdown`);
    });
    this.events.on(UPDATE, () => {
      // console.log(`${this.config.key}: update`);
      // this.game.events.emit(SCENE_AVAILABLE, this);
    });
    this.events.on("ready", () => {
      console.log(`${this.config.key}: start`);
    });
  }

  create() {
    // console.log(`Creating demo scene: ${this.config.key}`);
  }

  preload() {
    // console.log(`Preloading demo scene: ${this.config.key}`);
  }

  update(time: number, delta: number): void {}
}

export default ServerDemoScene;
```

**Comment by photonstorm** [comment]
The context is important. The documentation is written from the point of view of a Scene Plugin (as it says in it), and from that context `this.scene.events` is the correct context to use to listen for those events. If you want to listen to them from within a Scene itself then you need to adjust the context accordingly (`this.events`, for example).

You also can't listen for the `START` event of a Scene from _within_ that Scene itself, as the event is meant for plugins and is dispatched way before the `init` method is called. You could listen for that event from a different Scene, however.

**Comment by enzeart** [comment]
> The context is important. The documentation is written from the point of view of a Scene Plugin (as it says in it), and from within that `this.scene.events` is the correct context to use to listen for those events. If you want to listen to them from within a Scene itself then you need to adjust the context accordingly (`this.events`, for example).
> 
> You also can't listen for the `START` event of a Scene from _within_ that Scene itself, as the event is meant for plugins and is dispatched way before the `init` method is called. You could listen for that event from a different Scene, however.

Thank you, that clears things up immensely! The verbiage in the documentation is a little confusing, and the contextual implications aren't clear for at least a novice like myself. I'll try to come up with some time to suggest some edits to the documentation via a pull request if that sounds reasonable to you @photonstorm ?

**Comment by photonstorm** [comment]
Feel free. Always happy to merge useful docs PRs.
