### ISSUE TITLE
iOS onpointer event not firing until device rotate

### ISSUE THREAD

**Issue by imann24** [photonstorm/phaser#4682]
## Version

* Phaser Version: 3.18.1

* Operating system: iOS 12.4

* Browser: Safari

## Description

Hi, I'm experiencing an issue where a `gameObject.on("pointerup", function)` handler does not fire on Safari on iOS (until after the browser is rotated). The handler works without issue on Chrome for Mac and Android. 

## Example Test Code
(_snippet revised from source code_)
```javascript
 playAgainButton.on("pointerup", (pointer) => {
    gameIsOver = false;
    player.x = playerStartX;
    player.y = playerStartY;
    player.body.allowGravity = true;
    playAgainButton.active = false;
    playAgainButton.visible = false;
}, this);
```
https://github.com/imann24/gishwhes-2019/blob/fbdd2d502fc0111bb4d00f1c083364c6afc104cb/js/game.js#L192-L199

## Additional Information

1. Playable repro link: https://imann24.github.io/gishwhes-2019/build/v2
1. The "Play Again" button is the affected UI element
1. Repro GIF: http://stout.hampshire.edu/~ibm13/gif/phaser_pointer_repro.gif

**Comment by photonstorm** [comment]
Sorry, this may have been happening back when this issue was opened, but I just tested it today on the latest iOS release and no rotation is needed. Both `pointerdown` and `pointerup` work fine immediately. Test case here:

```js
var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 400,
    height: 300,
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('block', 'assets/sprites/block.png');
}

function create ()
{
    var image = this.add.image(200, 150, 'block').setInteractive();

    image.on('pointerdown', function () {

        image.setTint(0xff0000);

    });

    image.on('pointerup', function () {

        image.setTint(0x00ff00);

    });
}
```
