### ISSUE TITLE
Adding spine to scene fails with webgl errors and clears existing objects

### ISSUE THREAD

**Issue by MrBaummann** [photonstorm/phaser#4684]
Hi there,

not sure if the title is perfect, so please correct it if its too unclear.

If you try to add a spine object to a scene with existing objects(even a simple image is enough), the objects are "removed" (as in, not visible suddenly anymore, they are not destroyed) from the screen.
Additionally, there are many webgl errors visible in the console:
```
WebGL: INVALID_OPERATION: vertexAttribPointer: no ARRAY_BUFFER is bound and offset is non-zero
WebGL: INVALID_OPERATION: bufferSubData: no buffer
WebGL: INVALID_OPERATION: drawArrays: no buffer is bound to enabled attribute
```

This can easily be replicated using the "basic spineboy" example and changing it like this:
```
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    scene: {
        preload: preload,
        create: create,
        pack: {
            files: [
                { type: 'scenePlugin', key: 'SpinePlugin', url: 'plugins/SpinePlugin.js', sceneKey: 'spine' }
            ]
        }
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.setPath('assets/spine/demos/');
    this.load.image("test", "atlas1.png");
    this.load.spine('set1', 'demos.json', [ 'atlas1.atlas' ]);
}

function create ()
{
    this.add.image(100,100, "test");
    this.add.spine(400, 600, 'set1.spineboy', 'idle', true); //commenting out this line removes the erros in console and the added image before stays
}
```
You will see the image again by commenting out the adding of the spine object.
I am able to replicate this on latest chrome(75.0.3770.142 (Offizieller Build) (64-Bit)) and safari(12.1.2 (14607.3.9))

If you need anything more to replicate, please let me know.

Update: This is *just* happening if using `SpinePlugin`. If the `SpineWebGLPlugin` is used, its fine.

**Comment by photonstorm** [comment]
I've been working on the Spine Plugin all week, you probably just caught it in a moment of broken-ness. As of today, it's working fine no matter what else is on the display list.

**Comment by MrBaummann** [comment]
I just tried it again with the latest Plugin, it is still happening.
