### ISSUE TITLE
Keyboard Input only catches the first keystroke

### ISSUE THREAD

**Issue by voanhcuoc** [photonstorm/phaser#4688]
## Version

* Phaser Version: 3.18.1 and 3.17

* Operating system: RHEL 7

* Browser: Firefox 60.8.0esr

## Description

Keyboard input only catches the first keystroke of a specific key. To get it to catch another keystroke, I must unfocus the game canvas and then focus again.

As I found out: `keyup` event is never triggered, so the next `keydown` is never triggered. I have tried it with all 3 way of handling keyboard input: `keydown` event on keyboard, `down` event on specific key, and checking `JustDown` in `update` function.

For example:

1. I press `S`: `down` event on `S` is triggered
2. I press `A`: `down` event on `A` is triggered
3. I press `S` again: now `down` event is not triggered
4. I press `A` again: now `down` event is not triggered
5. I press `D`: because this is my first keystroke of `D`, `down` event get triggered

## Example Test Code

```
function create() {
    R = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.R);
    S = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.S);
    P = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.P);
    W = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.W);
    L = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.L);
    D = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.D);
    ESC = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ESC);

    R.on('down', recordButtonClick);
    S.on('down', stopButtonClick);
    P.on('down', playButtonClick);
    W.on('down', saveButtonClick);
    L.on('down', loadButtonClick);
    D.on('down', deleteButtonClick);
    ESC.on('down', toggleControl);
}

var preload = () => {};
var update = () => {};

var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    physics: 'arcade',
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var game = new Phaser.Game(config);
```

## Additional Information

Today, this bug just disappears and I can't reproduce it, but I think it's worth a note. It's not a bug in my code, as I also checked the example of `JustDown` in labs.phaser.io , got the same misbehaviour. It maybe caused by one of my browser extension.

**Comment by photonstorm** [comment]
I tested your sample (and a few of the Labs tests) and keyboard input is working fine here across Chrome and FF (I didn't test any further). I believe this issue to be local to your setup I'm afraid, otherwise, GitHub issues would be flooded with similar reports! Non-working keyboard input is the kind of thing people notice quickly :)

If you do narrow this down to a browser extension (which is entirely possible) then leave a comment so we can have a log of it, please.
