### ISSUE TITLE
Bug: can't use key, frame when creating render texture game object

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4692]
## Version

* Phaser Version: 3.18.1

## Description

Can't use [key, frame](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/rendertexture/RenderTexture.js#L57-L58) when creating render texture game object.

## Example Test Code

[Test code](https://codepen.io/rexrainbow/pen/XvVxON)

Error message

*Uncaught TypeError: [this.canvas.getContext](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/rendertexture/RenderTexture.js#L230) is not a function*

It seems that [`this.canvas`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/rendertexture/RenderTexture.js#L214) is an img object, not a canvas object under *key is not undefined* case.

**Comment by TadejZupancic** [comment]
This works if you provide an object, that is drawn on canvas (e.g. frames inside atlas). Image is drawn using an <img> tag and that's why it does not work.

This feature was created to enable editing a texture or a frame, which updates it everywhere it is used. If you need this with an image, then you can create a new RenderTexture, save it to the texture manager, draw onto it the image and then you will be able to recreate it with the RenderTexture key.

I didn't see before, that it can't be done with images, so maybe a note in the documentation should say when it can be used.

**Comment by rexrainbow** [comment]
@TadejZupancic 

Agree with you. User might draw frame via `rt.drawFrame(key, frame)` instead of assign (key, frame) parameter in config of constructor.

**Comment by hbiblia** [comment]
Hola, yo tengo este error al utilizar el **renderTexture** con **TileSprite**.
```
    var w = window.innerWidth;
    var h = window.innerHeight;

    var shape = this.Scene.add.grid(0, 0, 512, 512, 64, 64, colorA)
        .setAltFillStyle(colorB).setOutlineStyle().setOrigin(0);

    var render = this.Scene.add.renderTexture(0, 0, 512, 512);
    render.draw(shape, 0, 0);
    render.saveTexture('__gridTexture');

    this.Scene.add.tileSprite(0, 0, w, h, '__gridTexture').setOrigin(0);
    shape.destroy();
    render.destroy();
```

![image](https://user-images.githubusercontent.com/1939353/97096403-bd4fc280-1639-11eb-81ed-deb668f21fe6.png)

**Comment by gammafp** [comment]
> Hola, yo tengo este error al utilizar el **renderTexture** con **TileSprite**.
> Phaser v3.24.1
> 
> ```
>     var w = window.innerWidth;
>     var h = window.innerHeight;
> 
>     var shape = this.Scene.add.grid(0, 0, 512, 512, 64, 64, colorA)
>         .setAltFillStyle(colorB).setOutlineStyle().setOrigin(0);
> 
>     var render = this.Scene.add.renderTexture(0, 0, 512, 512);
>     render.draw(shape, 0, 0);
>     render.saveTexture('__gridTexture');
> 
>     this.Scene.add.tileSprite(0, 0, w, h, '__gridTexture').setOrigin(0);
>     shape.destroy();
>     render.destroy();
> ```
> 
> ![image](https://user-images.githubusercontent.com/1939353/97096403-bd4fc280-1639-11eb-81ed-deb668f21fe6.png)

Hola. hbiblia, podrías realizar tu pregunta por separado? Y has probado la última versión de Phaser (3.50 beta) que corrige muchos errores?
Y por último: Para poder revisar las preguntas estaría genial que las hicieras en inglés así el equipo de Phaser puede revisarla más fácilmente.
