### ISSUE TITLE
Missing Matter TypeScript type definitions

### ISSUE THREAD

**Issue by gammafp** [photonstorm/phaser#4694]
There is a error in typescript definitions (Phaser 3.18.1).

The propertie 'Matter' does not exist in:
```js
Phaser.Physics.Matter.Matter
```
![anotacion](https://user-images.githubusercontent.com/9221946/62606034-a2414780-b8fb-11e9-8084-f50ddbc54143.png)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

The correct new way to do this is via `this.matter.bodies.x`
