### ISSUE TITLE
Bug: add shader gameobject can only pass a img which width and heigth is power-of-2

### ISSUE THREAD

**Issue by cristlee** [photonstorm/phaser#4695]
## Version

* Phaser Version: 3.18.1

* Operating system: MacOS

* Browser:  Chrome

## Description

add shader method can only pass a img which width and heigth is power-of-2

## Example Test Code
var shader = this.add.shader('Tunnel', 400, 300, 800, 600, [ 'metal' ]);

For example, if "metal" img width is not power-of-2, there is an error as below, it's easy to present in the phaser3-example repository.

<img width="866" alt="屏幕快照 2019-08-07 17 27 19" src="https://user-images.githubusercontent.com/1849042/62612168-7e9cf200-b939-11e9-9fc7-b0c358e06bc0.png">

**Comment by cristlee** [comment]
there seems to have a solution  

https://stackoverflow.com/questions/47368120/render-warning-texture-bound-to-texture-unit-0-is-not-renderable-it-maybe-non?rq=1

**Comment by photonstorm** [comment]
This is because the Tunnel shader in that example requires a POT texture, rather than a bug in the Shader Game Object. Lots of shaders have this requirement. It's up to you to either provide a POT texture or code your shader in such a way that it can work with NPOT textures.

**Comment by cristlee** [comment]
I wrote a very simple sharder that can work with NPOT textures. The shader is to turn any image to grayscale.  But still have the problem

or where can I config if I do not need a POT texture? I am debuging this for a few hours and still can not find the reason. Below is my screenshot


<img width="730" alt="1" src="https://user-images.githubusercontent.com/1849042/62637817-d4d85800-b96e-11e9-8212-20b9e9199c2b.png">
<img width="789" alt="2" src="https://user-images.githubusercontent.com/1849042/62637819-d570ee80-b96e-11e9-8ff7-9a34be0b9444.png">
<img width="1075" alt="3" src="https://user-images.githubusercontent.com/1849042/62637822-d570ee80-b96e-11e9-978b-e0a248a4e7dc.png">
