### ISSUE TITLE
List wich events are supported for tweens in the documentation.

### ISSUE THREAD

**Issue by chepe263** [photonstorm/phaser#4699]
I would like the [documentation ](https://photonstorm.github.io/phaser3-docs/Phaser.Tweens.Tween.html#callbacks__anchor)for tweens event to list the available events. Currently I have to visit the [source code](https://github.com/photonstorm/phaser/blob/d2738f084b82ff5d60cb9d4965a383b75c4756e5/src/tweens/tween/Tween.js#L269) to obtain such information. This is not friendly for people new to Phaser 3, like me.

**Comment by photonstorm** [comment]
Tween Events are new in 3.19 and fully documented. You linked to the Tween callbacks, though, which you can find on the config page for the Tween: https://photonstorm.github.io/phaser3-docs/Phaser.Types.Tweens.html#.TweenBuilderConfig__anchor which in turn links to pages like this: https://photonstorm.github.io/phaser3-docs/Phaser.Types.Tweens.html#.TweenOnCompleteCallback

They're a bit of a pain to find, I agree, but the information is in there if you follow the links. When 3.19 is published the new Tween events will be listed under the Evens drop-down in the docs too.
