### ISSUE TITLE
antialiasing disable not working on CANVAS render for sprites. working good for tileSprites

### ISSUE THREAD

**Issue by agar3s** [photonstorm/phaser#4701]
## Version

* 3.19.1 // and previous. Doesn't happen on 3.15.1
* Windows 10
* Chrome, Firefox

## Description

![image](https://user-images.githubusercontent.com/1063587/62745180-64cdde80-ba0f-11e9-923e-f2944e45454f.png)

Antialiasing is not disabled when the render is set to CANVAS.

## Example Test Code

I'm testing with this snippet on demo:
3.19.0
https://labs.phaser.io/edit.html?src=src/game%20objects/tile%20sprite/tilesprite%20pixel%20art%20test.js&v=3.19.0

3.15.1
https://labs.phaser.io/edit.html?src=src/game%20objects/tile%20sprite/tilesprite%20pixel%20art%20test.js&v=3.15.1

```
var config = {
    type: Phaser.CANVAS,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    pixelArt: true,
    backgroundColor: '#2d2d2d',
    zoom: 2, 
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var tilesprite;
var iter = 0;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('mushroom', 'assets/sprites/mushroom16x16.png');
}

function create ()
{
    tilesprite = this.add.tileSprite(400, 300, 800, 600, 'mushroom');
    sprite = this.add.sprite(50, 50, 'mushroom')
    sprite.scaleX = 5
    sprite.scaleY = 5
    this.add.image(100, 200, 'mushroom').setName('mushy').setScale(5);
}

function update ()
{
    tilesprite.rotation -= 0.01;
    tilesprite.tileScaleX = Math.sin(iter) * 10;
    tilesprite.tileScaleY = Math.sin(iter) * 10;
    iter += 0.01;
}

```

## Additional Information

I was checking the code looking for some clues about what could be the problem and it looks like is related with the ScaleManager.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
