### ISSUE TITLE
Phaser.FacebookInstantGamesLeaderboard.getConnectedScores() ignores count and offset parameters

### ISSUE THREAD

**Issue by NokFrt** [photonstorm/phaser#4702]
## Version

* Phaser Version: 3.18.1

* Operating system: 

* Browser:

## Description

Phaser.FacebookInstantGamesLeaderboard.getConnectedScores() ignores count and offset parameters.

**Comment by photonstorm** [comment]
Copy pasta error. This call doesn't need those parameters.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
