### ISSUE TITLE
Phaser.FacebookInstantGamesLeaderboard - mistake in phaser.d.ts

### ISSUE THREAD

**Issue by NokFrt** [photonstorm/phaser#4703]
## Version

* Phaser Version: 3.18.1

* Operating system:

* Browser:

## Description

1 ) Phaser.FacebookInstantGamesLeaderboard extends Phaser.Event.EventEmitter but this information is missing in the phaser.d.ts file.

2) Phaser.FacebookInstantGamesPlugin.chooseContext(contextID) - invalid name and a description of the parametr.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
