### ISSUE TITLE
Scene ths.time.now is inconsistent in create() and update() when scene is started for 2nd+ time

### ISSUE THREAD

**Issue by koobazaur** [photonstorm/phaser#4704]
Let's take a simple scene:

`class MyScene extends Phaser.Scene {

    create() {
   
       console.info(this.time.now);   
    }

    update()
    {
		console.info(this.time.now);   
    }

}`

On first run, everything works properly. But If I change scene to something else, then change it back to MyScene, I experience an issue.

the this.time.now in create() seems to continue where it left off when this scene last stopped.
the this.time.now in update() seems to continue the global time and is thus much bigger than the one in create()

This causes issues when I try to track the time since start of the scene by saving the time in create() (this._StartTime = this.time.now;) and then using it in update() (var sceneTime = this.time.now - this._StartTime). I can get around it by instead using time delta passed into the update() function, but it still looks like a major inconsistency or a bug.

this.time should ALWAYS be either scene time or global time.

**Comment by photonstorm** [comment]
Runnable code example required.

**Comment by photonstorm** [comment]
I know this issue is several years old, but I'm closing it off as it works exactly as it should now (and likely has for quite a while!).

`this.time.now` as logged in either create or update will give the exact same global clock time.
