### ISSUE TITLE
game.input.activePointer worldX / worldY not updated when mouse pointer is kept down and mouse isn't moved.

### ISSUE THREAD

**Issue by K-marad** [photonstorm/phaser#4705]
<!--
## Version
* Phaser Version: Phaser v3.17.0-FB
* Operating system: Fedora Linux

## Description
When I click somewhere my character moves to that position.
When I keep the click down, my character should follow the mouse pointer, but if I don't move it at all, the worldX and worldY coordinates aren't updated at all.

I've made a video to illustrate it : https://youtu.be/2uPZv5aEP9c

## Example Test Code
```javascript
  update(time, delta) {
    if(this.game.input.activePointer.isDown){
      console.log(this.game.input.activePointer.worldX, this.game.input.activePointer.worldY)
    }
```
Also, the camera follows the character, this code is run when the player character information are received from the websockets server:
```javascript
      this.camera = this.cameras.main
      this.camera.scaleManager.setZoom(0)
      this.camera.startFollow(this.characters[character.id])
```

## Additional Information

I think that worldX and worldY coordinates in game.input.activePointer are only updated when the mouse moves or when the click is pressed.
The problem is, in games where the camera follows the character, even if the mouse doesn't move, the world coordinates change with the movement of the player.

**Comment by K-marad** [comment]
Wow, my whole description got deleted... :'(

So I'm using  Phaser v3.17.0-FB and this bug isn't related to OS / browser.

The problem I'm having is that when I keep the mouse click pressed, and I don't move the mouse, the coordinates of game.input.activePointer.worldX / Y aren't updated.

I've made a video to illustrate the bug : https://www.youtube.com/watch?v=2uPZv5aEP9c

I don't think code can really illustrate the problem. It's a very specific case.

Thank you.

**Comment by photonstorm** [comment]
The `worldX/Y` values are only valid at the time the callback is invoked. If the pointer doesn't move, they don't update. 3.19 gave you the following method to work around this:

`Pointer.updateWorldPoint` is a new method that takes a Camera and then updates the Pointers `worldX` and `worldY` values based on the cameras transform
