### ISSUE TITLE
group scale in Phaser3

### ISSUE THREAD

**Issue by wyu1202** [photonstorm/phaser#4708]
In the Phaser 2, the scale can be used in the group. 

e.g. this.group.scale.set(e);

But in the Phaser 3, I can't find the method not only in the group but alse in the container.

(In the container, scale is just a member, not method)

Can I find the same function in the Phaser 3?

**Comment by halilcakar** [comment]
You can use
```javascript
Phaser.Actions.Call(function(ch) => {
    ch.setScale(1.5);
});
```
It's setting the scales as individual. So it maybe broke the places depends on your origins.

**Comment by photonstorm** [comment]
`Container.setScale()` is the method. Groups have no scale in v3.
