### ISSUE TITLE
Calling setScale on an object in an object pool causes the physics collider to be put in the incorrect position

### ISSUE THREAD

**Issue by the-simian** [photonstorm/phaser#4709]
* Phaser Version: 3.18
* Operating system: Windows 10, Chrome Browser
* Browser: Reproduced in Brave and Chrome

I am currently using Phaser 0.18 and experiencing this issue. I am posting here because I am not certain this is a bug, but I'll do my best to describe it.

I did see another issue in the forum here: https://phaser.discourse.group/t/phaser-bug-animation-changing-gameobject-s-body-position/3454

while there are some similarities to my problem, it did not seem identical, so I am posting.

Here is the short version: when I am using `Phaser.Arcade.Group` with a pool of objects consisting of `Phaser.Arcade.Sprite`, I am experiencing an issue whereby the position of the body collider seems to be calculated correctly until I `getFirstDead` of the existing items. At this time, if (and only if) I have used `setScale` on the sprite, the calculation of the position of the collider is off. 

This is tricky to explain, so I will use some images and gifs to illustrate what I am describing. Here is the setup code:

```
import Phaser from 'phaser';

import flaresJSON from '../../assets/particles/flares.json';
import flaresPNG from '../../assets/particles/flares.png';

class WonderBullet extends Phaser.Physics.Arcade.Sprite {
  constructor(scene, x, y) {
    super(scene, x, y, 'flares', 'red');
  }
  preload() {}

  fire(x, y) {
    //this.setScale(0.5);
    this.body.reset(x, y);
    this.setOrigin(0.5, 0.5);
    this.setSize(5, 5);
    this.setActive(true);
    this.setVisible(true);
    this.setVelocityX(300);
    this.lastX = this.x;
  }

  preUpdate(time, delta) {
    super.preUpdate(time, delta);

    if (this.x - this.lastX > 500) {
      this.setActive(false);
      this.setVisible(false);
    }
  }

  update() {
    
  }
}

export class WonderBullets extends Phaser.Physics.Arcade.Group {
  constructor(scene) {
    scene.load.atlas('flares', flaresPNG, flaresJSON);
    super(scene.physics.world, scene);

    this.createMultiple({
      frameQuantity: 2,
      key: 'wonder-bullet',
      active: false,
      visible: false,
      classType: WonderBullet
    });
  }

  rates = {
    bulletSpacing: 800,
    lastBullet: 0
  };

  fireBullet(x, y) {
    let bullet = this.getFirstDead(false);
    if (bullet && this.scene.time.now > this.rates.lastBullet) {
      bullet.fire(x, y);
      this.rates.lastBullet = this.scene.time.now + this.rates.bulletSpacing;
    }
  }
}
```

this code basically works. I am using the x,y coordinates to emit a bullet (which is one of the flares) in front of the player.

![working-bullets|800x266](https://discourse-cloud-file-uploads.s3.dualstack.us-west-2.amazonaws.com/free1/uploads/phaser1/original/2X/d/dbbc775fb5acd38d886514856160aa131afacbdf.gif) 
The bullet pool size is 2, and everything is working correctly. you can see that the 'box' in debug mode is in the center of the flare and that the velocity is being set, the size is set (otherwise it is very big).

Now watch when I uncomment the setSize, to reduce the size of the art for the bullet, (but not the collider).

```
import Phaser from 'phaser';

import flaresJSON from '../../assets/particles/flares.json';
import flaresPNG from '../../assets/particles/flares.png';

class WonderBullet extends Phaser.Physics.Arcade.Sprite {
  constructor(scene, x, y) {
    super(scene, x, y, 'flares', 'red');
  }
  preload() {}

  fire(x, y) {
   
    this.body.reset(x, y);
    this.setOrigin(0.5, 0.5);
    this.setSize(5, 5);
    this.setScale(0.2); ///<======THIS!
    this.setActive(true);
    this.setVisible(true);
    this.setVelocityX(300);
    this.lastX = this.x;
  }

  preUpdate(time, delta) {
    super.preUpdate(time, delta);

    if (this.x - this.lastX > 500) {
      this.setActive(false);
      this.setVisible(false);
    }
  }

  update() {
    
  }
}

export class WonderBullets extends Phaser.Physics.Arcade.Group {
  constructor(scene) {
    scene.load.atlas('flares', flaresPNG, flaresJSON);
    super(scene.physics.world, scene);

    this.createMultiple({
      frameQuantity: 2,
      key: 'wonder-bullet',
      active: false,
      visible: false,
      classType: WonderBullet
    });
  }

  rates = {
    bulletSpacing: 800,
    lastBullet: 0
  };

  fireBullet(x, y) {
    let bullet = this.getFirstDead(false);
    if (bullet && this.scene.time.now > this.rates.lastBullet) {
      bullet.fire(x, y);
      this.rates.lastBullet = this.scene.time.now + this.rates.bulletSpacing;
    }
  }
}
```
![non-working-bullets|800x266](https://discourse-cloud-file-uploads.s3.dualstack.us-west-2.amazonaws.com/free1/uploads/phaser1/original/2X/0/03a1782a8a489f77c5b2479f862b3798ccf26b36.gif) 
Notice the arcade collider 'moves' from the center to the top?

Here's what I can see:
1. First two bullets work great, but when I pull from the pool I get aberrant behavior when I scale.
2. If I set the Scale *before* I call `body.reset`, then they never work, not even the first two.

There's some sort of interplay between getting the dead items, scaling and resetting that is not producing the behavior I'd expect. There's also a possibility I need to resequence things a certain way, but I've had no luck with getting the hitbox to be in the correct spot when the sprite is rescaled. I've tried many different orders.

Here is the corresponding Forum Post: https://phaser.discourse.group/t/bug-report-calling-setscale-on-an-object-in-an-object-pool-causes-the-physics-collider-to-be-put-in-the-incorrect-position/3456

**Comment by photonstorm** [comment]
Just saying I can confirm this works as expected under 3.5. I also went back quite a long way and it worked under 3.12 too (I didn't go any further back), so I'm confident I can close this now. Here is the test case I used (assets in the repo)

```js
class Bullet extends Phaser.Physics.Arcade.Sprite
{
    constructor (scene, x, y)
    {
        super(scene, x, y, 'bullet');
    }

    fire (x, y)
    {
        this.setScale(0.5);

        this.body.reset(x, y);

        this.setActive(true);
        this.setVisible(true);

        this.setVelocityY(-300);
    }

    preUpdate (time, delta)
    {
        super.preUpdate(time, delta);

        if (this.y <= -32)
        {
            this.setActive(false);
            this.setVisible(false);
        }
    }
}

class Bullets extends Phaser.Physics.Arcade.Group
{
    constructor (scene)
    {
        super(scene.physics.world, scene);

        this.createMultiple({
            frameQuantity: 2,
            key: 'bullet',
            active: false,
            visible: false,
            classType: Bullet
        });
    }

    fireBullet (x, y)
    {
        let bullet = this.getFirstDead(false);

        if (bullet)
        {
            bullet.fire(x, y);
        }
    }
}

class Example extends Phaser.Scene
{
    constructor ()
    {
        super();

        this.bullets;
        this.ship;
    }

    preload ()
    {
        // this.load.image('bullet', 'assets/sprites/bullets/bullet7.png');
        this.load.image('bullet', 'assets/demoscene/ball.png');
        this.load.image('ship', 'assets/sprites/bsquadron1.png');
    }

    create ()
    {
        this.bullets = new Bullets(this);

        this.ship = this.add.image(400, 500, 'ship');

        this.input.on('pointermove', (pointer) => {

            this.ship.x = pointer.x;

        });

        this.input.on('pointerdown', (pointer) => {

            this.bullets.fireBullet(this.ship.x, this.ship.y);

        });
    }
}

const config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    physics: {
        default: 'arcade',
        arcade: {
            debug: true,
            gravity: { y: 0 }
        }
    },
    scene: Example
};

let game = new Phaser.Game(config);
```
