### ISSUE TITLE
Camera with setuped pipeline cause rotation viewport rectangle and apply strange transformation of position and rotation to RenderTexture gameobject with other pipeline

### ISSUE THREAD

**Issue by pavel-shirobok** [photonstorm/phaser#4713]
## Version

* Phaser Version: 3.19.0

* Operating system: Windows 8.1

* Browser: Chrome / Electron 5.0.1

## Description

Strange behavior of camera when pipeline applied and changed rotation of camera:
* viewport rotates with content in it
* render texture rotates and moves strangely if also has applied pipeline(other then camera has)
## Example Test Code
https://codepen.io/pavel-shirobok/pen/dybMeWj
if comment line with setting up pipeline for camera all works as expected

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
