### ISSUE TITLE
Request about Tween.getValue, Tween.updateTo and Tween data set current value

### ISSUE THREAD

**Issue by chepe263** [photonstorm/phaser#4717]
I noticed a few odd things with the class Tween.

In function [getValue()](https://github.com/photonstorm/phaser/blob/e0ec646496fbc8a6083f8ef88813dd9a90233150/src/tweens/tween/Tween.js#L355) you cannot specify which property to obtain the value. It returns the value of the first item in the data array, Would it be possible to add a `key` parameter similar to updateTo() function?

The function updateTo() is a little unclear as of what is being updated. The documentation states 
> Updates the value of a property of this Tween to a new value, without adjusting the Tween duration or **current progress**.
>
>You can optionally tell it to set the 'start' value to be the current value (before the change).

Current progress refers to the current value of the property being tweened (in tween data) and not to the member `progress` of the Tween Class. Would it be possible for the documentation to state it updates the tween data's `end` to make it clearer?

Similar to getValue() function, would it be possible to add a setValue() function to set the value `current` in the tween data?

**Comment by photonstorm** [comment]
I forgot that method even still existed. It is a left-over from Phaser 2. It's useless and should be removed! If you want a tween value you should obtain it via the config callbacks instead really.
