### ISSUE TITLE
Game.resize is not a function

### ISSUE THREAD

**Issue by charneykaye** [photonstorm/phaser#4718]
I'm looking at this example from the Phaser 3 website, which replicates the issue I am experiencing. 

https://phaser.io/examples/v3/view/game-config/game-resize#

Phaser: 3.19
Browser: Firefox 68.0.2
OS: Ubuntu Desktop 18

1. Open the editor version of the aforementioned example: https://labs.phaser.io/edit.html?src=src/game%20config/game%20resize.js&v=3.19.0

2. Resize the window in any direction

3. Expect background to resize, logo to re-center. Actually, no change occurs. Error is thrown in JavaScript console: TypeError: game.resize is not a function

**Comment by photonstorm** [comment]
I have removed this example, it is no longer how it should be done (and hasn't been for months now). The correct resizing examples are to be found in the Scale Manager folder: http://labs.phaser.io/index.html?dir=scalemanager/&q=

**Comment by charneykaye** [comment]
@photonstorm I don't mean to sound ungrateful, but... how exactly does one see the source code used for one of the  http://labs.phaser.io/index.html?dir=scalemanager/&q= projects? I see that code working, for example http://labs.phaser.io/100.html?src=src\scalemanager\resize.js -- however the source code for that example is obfuscated. I would expect a link from http://labs.phaser.io/index.html?dir=scalemanager/&q= to the link such as http://labs.phaser.io/edit.html?src=src\scalemanager\resize.js -- however the latter is not easy to find, I had to write the URL myself. In any case, Thanks!!

**Comment by photonstorm** [comment]
The easiest way is to just browse the GitHub repo: https://github.com/photonstorm/phaser3-examples/tree/master/public/src

Personally, if you're using the examples a lot, it's well worth having a local copy of the repo so you can use your fav. IDE to look at source, etc.
