### ISSUE TITLE
UpdateList Memory Leak

### ISSUE THREAD

**Issue by darkgod6** [photonstorm/phaser#4721]
## Version

* Phaser Version: 3.18.1

* Operating system: Windows 10

* Browser: Chrome

## Description

If a GameObject is added to the UpdateList, e.g. by getting a groups child, and then is destroyed in the same frame, it will not be removed from the UpdateList. It stays there until the end of the scene.

## Example Test Code

[https://jsfiddle.net/2Ls1md4t/](https://jsfiddle.net/2Ls1md4t/)

## Additional Information

After looking into the UpdateLists code, you can see, that the pending removal list and pending insert lists are handled in wrong(?) order. First objects are removed , and then objects are added. The first do nothing for such objects, because they are not in the UpdateList yet. Then the destroyed object will be added.
Because an object is always be added before its destruction, I would do first the inserts, and afterwards the removal.
[https://github.com/photonstorm/phaser/blob/da49fcc4997fb97c8b4ccc05b34479ecd6299b42/src/gameobjects/UpdateList.js#L148](https://github.com/photonstorm/phaser/blob/da49fcc4997fb97c8b4ccc05b34479ecd6299b42/src/gameobjects/UpdateList.js#L148)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
