### ISSUE TITLE
enableDebug for input on gameobjects does not display correctly if offset

### ISSUE THREAD

**Issue by HaoboZ** [photonstorm/phaser#4722]
## Version

* Phaser Version: 3.19

* Operating system: Windows 10

* Browser: Chrome

## Description

When using enableDebug to draw the interactive area, if you give a hitArea to the config in setInteractive, the enableDebug will not draw the correct boundaries for the input area. It doesn't take into account the x and y values of the rectangle given. The actual boundaries do work since in the example, when highlighted over the bottom right of the rectangle, it will still show the hand cursor changing. 

## Example Test Code

```
var config = {
	type:   Phaser.WEBGL,
	parent: 'phaser-game',
	scene:  {
		preload: preload,
		create:  create
	}
};

var game = new Phaser.Game( config );

function preload() {
	this.load.image( 'eye', 'assets/pics/lance-overdose-loader-eye.png' );
}

function create() {
	var sprite = this.add.rectangle( 100, 100, 100, 100, 0xff0000 )
		.setInteractive( {
			hitArea:         new Phaser.Geom.Rectangle( 50, 50, 50, 50 ),
			hitAreaCallback: Phaser.Geom.Rectangle.Contains,
			useHandCursor:   true
		} );
	this.input.enableDebug( sprite );
}
```

**Comment by photonstorm** [comment]
This is definitely a bug, but I'm not sure there's an easy fix for it, as the shapes it creates are kept in sync with the game object, not the hit area.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
