### ISSUE TITLE
Make plugins separate npm packages

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#4725]
I think that making plugins with their working type definitions as separate npm packages will be better than adding them into phaser build.
Today i was trying to add Spine plugin to my project (Phaser 3.19.0, webpack 4 and TypeScript) and have done that partial. In result i got that `Phaser.Scene` has new property `spine` and there are no `Factory` and `Creator` methods for `Spine` in `Phaser.Scene`. One more problem for me is that I couldn't implement Spine definitions in my project and had to write them myself, just from consoling `Spine object`.
I think that plugins updates must be published in ChangeLog as it's being now. But they must be in separate repo and published as a separate npm package.
For example, I have a project that isn't targeting facebook instant games, and I don't need for that plugin in my game bundle. 

Please take a look of cordova plugins. All of them have `cordova-plugin-<plugin-name>` package names. So developer can search plugins just in npm by searching `phaser3` word.
So, we can have plugins with following names `phaser3-plugin-<plugin-name>` and it will really make our life better.

And yes, I'm ready and will be happy to help you in this.

**Comment by photonstorm** [comment]
This is being done for Phaser 4, but will remain as-is for Phaser 3 because it's not worth the time to change it all up (the plugins don't get included into your actual game unless you specifically do so, so it doesn't hurt having them in the repo)
