### ISSUE TITLE
setPosition does not update collisions

### ISSUE THREAD

**Issue by HaoboZ** [photonstorm/phaser#4727]
## Version

* Phaser Version: 3.19

* Operating system: Windows 10

* Browser: Chrome

## Description

When setting an object's position that has collisions, it will not update the touching property correctly when using the function setPosition. If velocity is set for the object, then the property correctly updates, however, it also messes with the actual collision for boundary cases.

## Example Test Code

```
var config = {
    type: Phaser.AUTO,
    antialias: false,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    physics: {
        default: 'arcade',
        arcade: { debug: true }
    },
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var sprite;
var group;

new Phaser.Game(config);

function preload() {
    this.load.image('mushroom', 'assets/sprites/mushroom2.png');
    this.load.image('ball', 'assets/sprites/shinyball.png');
}

function create() {
    sprite = this.physics.add.image(400, 300, 'mushroom')
        // .setVelocity(1);

    group = this.physics.add.staticGroup({
        key: 'ball',
        frameQuantity: 30
    });

    Phaser.Actions.PlaceOnRectangle(group.getChildren(), new Phaser.Geom.Rectangle(84, 84, 616, 416));

    group.refresh();

    this.physics.add.overlap(sprite, group);
}

function update() {
    sprite.setPosition(this.input.activePointer.worldX, this.input.activePointer.worldY)
    sprite.body.debugBodyColor = sprite.body.touching.none ? 0x0099ff : 0xff9900;
}
```

**Comment by photonstorm** [comment]
This is the correct behavior for Arcade Physics. If you want to use physics, you must use physics to move the object as well, otherwise, it has no velocity, so has no ability to separate. The same goes for Matter as well (which is why mouse movement in Matter attaches a spring constraint from the pointer position to the body you're dragging)
