### ISSUE TITLE
FacebookInstantGamesPlugin - bug in showAd()/showVideo()

### ISSUE THREAD

**Issue by NokFrt** [photonstorm/phaser#4728]
## Version

* Phaser Version: 3.19

* Operating system: Windows 10

* Browser: Chrome

## Description

Phaser stores all ads in an ads array. After the ad is displayed it sets ad.shown to "true" and keep the ad in the array (which is useless). The ad can't be shown again - it has to be preloaded once again with the same placementId. After the ad is preloaded again, there are two ads with the same placementId in the array - and that's the problem, because showAd() and ShowVideo() does not check if the ad has been already shown and use the first one in the array.

## Example Test Code

`fb.ads.splice(fb.ads.indexOf(this._instance), 1);`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
