### ISSUE TITLE
Tween could not be played if created with paused: true

### ISSUE THREAD

**Issue by t0il3ts0ap** [photonstorm/phaser#4735]
## Version

* Phaser Version: v3.19.0

* Operating system: MacOS Mojave

* Browser: Tested on chrome/firefox

## Description
Tween could not be played if created with paused: true

## Example Test Code
https://labs.phaser.io/edit.html?src=src\tweens\paused%20tween.js

**Comment by photonstorm** [comment]
This works fine in 3.19: http://labs.phaser.io/view.html?src=src%5Ctweens%5Cpaused%20tween.js&v=3.19.0

Make sure, when using the edit.html link, you add the version into the URL. So add `&v=3.19.0` to the URL if it's loading an older build.
