### ISSUE TITLE
Safari mobile IPAD air when recording then playing back with recorder.js (getUserMedia). Sound is distorted.

### ISSUE THREAD

**Issue by geoff-mathspathway** [photonstorm/phaser#4736]
## Version

3.19.0

IPAD air 12.4.1

safari  

If you use getUserMedia library to record sound then play it back ONLY when phaser is running it is distorted. I use a wrapper called recorder.js

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

I'd be surprised if Phaser itself was distorting the audio. Far more likely, is that the device doesn't have enough CPU to handle running Phaser and recording audio at the same time, and this is how it manifests itself. A runnable code sample could test this theory, however.

**Comment by geoff-mathspathway** [comment]
HI!

Thanks for getting back to me. You are right the problem seems to be a cpu issue when WEBGL and ipad are used. If you switch to canvas rendering it works ok. All other devices seem fine on WEBGL.
