### ISSUE TITLE
Component gem example broken since 3.10

### ISSUE THREAD

**Issue by SavedByZero** [photonstorm/phaser#4738]
* Phaser Version:
3.10-3.19
* Operating system:
* Browser:
Firefox, live example. 

## Description

See the phaser 3 example for Components -> Data, I believe there's only one there.  When I click on the gem, nothing happens.  I have to go back to before version 3.10 for it to work.  I know you archived a bunch of old examples recently, but I'm still seeing this one.  

## Example Test Code
https://phaser.io/examples/v3/view/components/data/change-data-event

**Comment by photonstorm** [comment]
Thank you for reporting a problem with this example. It has now been fixed. You can find the updated version in this repo and on the labs.phaser.io site.
