### ISSUE TITLE
Container + few particles emitters

### ISSUE THREAD

**Issue by IvanDem** [photonstorm/phaser#4739]
* Phaser Version:

* Operating system:

* Browser:
Version 76.0.3809.132 (Official Build) (64-bit)

## Description

when I try to add particles to container with scale 0.5 it works well, but if we have more then 1 emitter, they inherit wrong position. One of the emitter has right position (x=0.5 of it's) but others, has like 0.5*position of previous emitter, unless they are active. 

## Example Test Code

to test fast - just replace code here: https://labs.phaser.io/edit.html?src=src\game%20objects\particle%20emitter\emit%20from%20sprites.js
with this code: 

var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    backgroundColor: '#000',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.atlas('explosion', 'assets/particles/explosion.png', 'assets/particles/explosion.json');
}

function create ()
{
    var particles = this.add.particles('explosion');

    this.container = this.add.container(0,0);
    this.container.setScale(0.5);
    this.container.add(particles);

    //  Setting { min: x, max: y } will pick a random value between min and max
    //  Setting { start: x, end: y } will ease between start and end

    particles.createEmitter({
        frame: [ 'smoke-puff', 'cloud', 'smoke-puff' ],
        angle: { min: 240, max: 300 },
        speed: { min: 200, max: 300 },
        quantity: 6,
        lifespan: 2000,
        alpha: { start: 1, end: 0 },
        scale: { start: 1.5, end: 0.5 },
        on: false
    });

    particles.createEmitter({
        frame: 'red',
        angle: { min: 0, max: 360, steps: 32 },
        lifespan: 1000,
        speed: 400,
        quantity: 32,
        scale: { start: 0.3, end: 0 },
        on: false
    });

    particles.createEmitter({
        frame: 'stone',
        angle: { min: 240, max: 300 },
        speed: { min: 400, max: 600 },
        quantity: { min: 2, max: 10 },
        lifespan: 4000,
        alpha: { start: 1, end: 0 },
        scale: { min: 0.05, max: 0.4 },
        rotate: { start: 0, end: 360, ease: 'Back.easeOut' },
        gravityY: 800,
        on: false
    });

    particles.createEmitter({
        frame: 'muzzleflash2',
        lifespan: 200,
        scale: { start: 2, end: 0 },
        rotate: { start: 0, end: 180 },
        on: false
    });

    this.input.on('pointerdown', function (pointer) {

        particles.emitParticleAt(pointer.x, pointer.y);

    });
}

**Comment by RollinSafary** [comment]
this happens even with 1 emitter for me

**Comment by acheo** [comment]
+1

**Comment by acheo** [comment]
So emitters in containers are not fully supported?

**Comment by acheo** [comment]
My workaround, set position and scale on the manager instead:

//this.view.add(particles);
particles.setScale(scaleFactor);
particles.x = this.view.x;
particles.y = this.view.y;

where "view" is my container and scaleFactor is it's scale

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
