### ISSUE TITLE
Some games on Examples can not be visualized

### ISSUE THREAD

**Issue by LearningCode2023** [photonstorm/phaser#4741]
The folder ' Pac-man ' returns you to the Games folder instead of show files about the game 

![multi](https://user-images.githubusercontent.com/53314644/64492819-27db4e80-d23e-11e9-9d43-96f04ae08ec7.png)
![cannon](https://user-images.githubusercontent.com/53314644/64492821-2ca00280-d23e-11e9-8fa4-33c2e3d5d479.png)

**Comment by photonstorm** [comment]
Yup, they need a good tidy-up.

**Comment by photonstorm** [comment]
All broken game examples have now been removed.
