### ISSUE TITLE
Phaser.Geom.Point.Divide method is missing

### ISSUE THREAD

**Issue by keerifox** [photonstorm/phaser#4742]
running https://phaser.io/examples/v3/view/geom/point/divide on Phaser 3.19.0 throws a "Phaser.Geom.Point.Divide is not a function" error, should the example be removed due to redundancy of having that static function, or should the method be added to the source code and documentation?

**Comment by keerifox** [comment]
also applies to

- Phaser.Geom.Point.Multiply https://phaser.io/examples/v3/view/geom/point/multiply
- Phaser.Geom.Point.Add https://phaser.io/examples/v3/view/geom/point/add
- Phaser.Geom.Point.Subtract https://phaser.io/examples/v3/view/geom/point/subtract
- Phaser.Geom.Point.Normalize https://phaser.io/examples/v3/view/geom/point/normalize

**Comment by photonstorm** [comment]
These were all removed ages ago. The examples need a good tidy-up, will flag as such.

**Comment by photonstorm** [comment]
Thank you for reporting a problem with this example. It has now been fixed. You can find the updated version in this repo and on the labs.phaser.io site.
