### ISSUE TITLE
Phaser 3.19 + MatterJS > Typescript Typings (How?)

### ISSUE THREAD

**Issue by Tomiha** [photonstorm/phaser#4746]
How exactly are the typings for MatterJS working with Phaser 3.19?
Do we always have to cast a MatterJS.body to Matter.Body?

this.matter.add.circle(0,0, 20); >> returns a MatterJs.Body (inside Phaser.d.ts, the typings for this type are empty)
Casting the returned body to Matter.Body gives us the functions we need (as defined in matter.d.ts). Is this the correct way?

What's the correct usage for these matterjs typings?

**Comment by Jonchun** [comment]
I had the same issue trying to use the Spine plugin: https://github.com/photonstorm/phaser/issues/4759

I would recommend using https://www.npmjs.com/package/tsd-jsdoc to just generate your own for now.

**Comment by photonstorm** [comment]
This has been redone for the 3.22 release, now in the master branch. You just include the Phaser defs and it will reference the new (and correct) Matter defs automatically.
