### ISSUE TITLE
Typescript tutorial is broken

### ISSUE THREAD

**Issue by Darker7** [photonstorm/phaser#4747]
Due to the API changes the typescript tutorial is hopelessly broken.

I would furthermore appreciate it if Code was used instead of Visual Studio in the fixed tutorial.

**Comment by samme** [comment]
Which tutorial?

**Comment by photonstorm** [comment]
Probably means the one for Phaser 2? As there haven't been any written for Phaser 3, by me anyway, but there are lots of community ones that are correct. VS Code didn't exist when the original tutorial was written!
