### ISSUE TITLE
Timeline infinite looping does not work

### ISSUE THREAD

**Issue by NokFrt** [photonstorm/phaser#4750]
## Version

* Phaser Version: 3.19

* Operating system: Win10

* Browser: Chrome

## Description
If you set Timeline.loop = -1, it will not work. You can check it here: https://labs.phaser.io/view.html?src=src\tweens\timelines\loop%20timeline.js and set loop: -1.

## Example Test Code

`timeline = this.tweens.timeline({

        targets: image,
        loop: -1,

        tweens: [
        {
            x: 700,
            ease: 'Sine.easeInOut',
            duration: 2000,
        }]});`

**Comment by photonstorm** [comment]
Works fine for me. If I change the loop counter to -1 then the crate just circles around the screen forever. Works in 3.20, 3.19 and 3.18 (but not 3.17).

**Comment by NokFrt** [comment]
That's strange because it does not work for me. Please check this video: https://drive.google.com/file/d/14Wt_w8AuahNTklCWAsMttuz_GQKVBsjD/view?usp=sharing

**Comment by photonstorm** [comment]
As I said, it doesn't work in 3.17.
