### ISSUE TITLE
Phaser.Math.RND.Between is undefined

### ISSUE THREAD

**Issue by bigswede74** [photonstorm/phaser#4753]
## Version

* Phaser Version: 3.19.0

* Operating system: win7, win10

* Browser: chrome 77.0.3865.75

## Description

when using Phaser.Math.RND in a scene an undefined error is thrown, Phaser.Math.RND.between is undefined.

## Example Test Code

public myRndNumber: number = Phaser.Math.RND.between(1000, 5000);

## Additional Information

Calls in debug mode seem to work but once I build the full phaser game as a typescript module and consume the game I see the error. Could this be something missing with the typescript module?

**Comment by photonstorm** [comment]
This must just be a TS defs issue, because it actually works on a code level (and from JS).

**Comment by bigswede74** [comment]
@photonstorm We are referencing the phaser types under the npm package.

```
{
  "compilerOptions": {
    "target": "ES2016",
    "module": "CommonJS",
    "sourceMap": true,
    "noImplicitAny": false,
    "strict": false,
    "declaration": true,
    "declarationDir": "./build/dist/types/"
  },
  "typeRoots": [
    "./node_modules/phaser/types"
  ],
  "types": [
    "Phaser"
  ]
}
```

**Comment by bigswede74** [comment]
@photonstorm Is this something that needs to be fixed in the phaser TS defs?

**Comment by photonstorm** [comment]
Looking at the defs file, it is correctly typed in there:

```
        /**
         * An instance of the Random Number Generator.
         * This is not set until the Game boots.
         */
        var RND: Phaser.Math.RandomDataGenerator;
```

This is within the `Phaser.Math` namespace, as it should be. So, I don't believe there is anything we could change in the defs. You could perhaps try using `Phaser.Math.RandomDataGenerator` instead (as RND is just an alias for that)

**Comment by bigswede74** [comment]
I ended up using `Phaser.Math.Between` instead and it works.
