### ISSUE TITLE
Drag problem when game object in transformed camera or container.

### ISSUE THREAD

**Issue by ganlvtech** [photonstorm/phaser#4755]
Drag problem when game object in transformed camera or container.

## Version

* Phaser Version: v3.19.0

* Operating system: Windows 10 OS Version 1903 (Build 18362.356)

* Browser: Chrome 64bit 77.0.3865.75

## Description

Drag problem when game object transformed. Scaling or rotating a container, zooming or rotating a camera will cause this bug.

![01](https://user-images.githubusercontent.com/8651285/64908272-71410780-d730-11e9-9502-116c5c304e2b.gif)

Additionally, when camera scrolled during dragging, the game object won't be transformed. [input/dragging/camera move and rotate.js](https://labs.phaser.io/view.html?src=src/input/dragging/camera%20move%20and%20rotate.js)

![02](https://user-images.githubusercontent.com/8651285/64908671-e6fba200-d735-11e9-898f-a44967c7ad30.gif)

## Example Test Code

This code can be run directly at <http://labs.phaser.io/edit.html>

### Camera

```javascript
var config = {
    scene: {
        create: create
    }
};

var game = new Phaser.Game(config);

function create () {
    var rect = new Phaser.GameObjects.Rectangle(this, 100, 100, 100, 100, 0x00ff00);
    this.children.add(rect);
    rect.setInteractive({
        draggable: true
    });
    rect.on('drag', (pointer, dragX, dragY) => {
        rect.x = dragX;
        rect.y = dragY;
    });
    this.cameras.main.setOrigin(0, 0);
    this.cameras.main.setZoom(2);
    // this.cameras.main.setRotation(0.5);
}
```

### Container

```javascript
var config = {
    scene: {
        create: create
    }
};

var game = new Phaser.Game(config);

function create () {
    var rect = new Phaser.GameObjects.Rectangle(this, 100, 100, 100, 100, 0x00ff00);
    rect.setInteractive({
        draggable: true
    });
    rect.on('drag', (pointer, dragX, dragY) => {
        rect.x = dragX;
        rect.y = dragY;
    });
    var container = this.add.container(0, 0);
    container.add(rect);
    container.setScale(2);
    // container.setRotation(0.5);
}
```

## Additional Information

Maybe related to #1542

Related doc: [Phaser.Input.Events.html#event:GAMEOBJECT_DRAG](https://photonstorm.github.io/phaser3-docs/Phaser.Input.Events.html#event:GAMEOBJECT_DRAG__anchor)

GAMEOBJECT_DRAG

| Name | Type | Description |
| -- | -- | -- |
| dragX | number | The x coordinate where the Pointer is currently dragging the Game Object, in world space. |
| dragY | number | The y coordinate where the Pointer is currently dragging the Game Object, in world space. |

`dragX` and `dragY` should be coordinate in world space. But is not apply the transform from camera.

When within a container, we cannot using world coordinate directly, but this may still be a bug.

https://github.com/photonstorm/phaser/blob/e0ec646496fbc8a6083f8ef88813dd9a90233150/src/input/InputPlugin.js#L892-L902

`hitTestPointer` doesn't have bug. But `processDragStartList` `processDragMoveEvent` Directly using `pointer.x`.

https://github.com/photonstorm/phaser/blob/e0ec646496fbc8a6083f8ef88813dd9a90233150/src/input/InputPlugin.js#L1117-L1126

I think there should be a transformation. And I think `dragX` and `dragY` shouldn't using world space, parent container space may be better.

Thank you.

**Comment by lifeinchords** [comment]
I'm having the same issue on `3.22.0`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
