### ISSUE TITLE
Issue of render-texture's setSize/resize method

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4757]
Zone and RenderTexture game object both have *setSize* method.

Bug:

In RenderTexture game object, resize method won't update displayOrigin via [`updateDisplayOrigin()`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/zone/Zone.js#L168). Render result is incorrect if origin is not at (0,0) after resizing.

Feature suggestion:

In Zone game object, [hit-area will be updated if hit-area is not *customHitArea*](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/zone/Zone.js#L172-L176). Could RenderTexture game object have the same behavior?

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
