### ISSUE TITLE
Tween UpdateTo only updates the first target

### ISSUE THREAD

**Issue by RBrNx** [photonstorm/phaser#4763]
## Version
* Phaser Version: v3.19.0
* Operating system: Windows 10
* Browser: Chrome v77.0.3865.90

## Description
When using the `updateTo` method on a Tween that targets multiple objects, only the first object's property is updated, the rest continue to tween with their original value.

## Example Test Code
https://codesandbox.io/s/weathered-monad-c9yxc?fontsize=14

## Additional Information

I believe the issue is the `break;` statement in the `updateTo` function, that will exit the loop as soon as the first `tweenData` has been updated. 

```
updateTo: function (key, value, startToCurrent)
    {
        if (startToCurrent === undefined) { startToCurrent = false; }

        for (var i = 0; i < this.totalData; i++)
        {
            var tweenData = this.data[i];

            if (tweenData.key === key)
            {
                tweenData.end = value;

                if (startToCurrent)
                {
                    tweenData.start = tweenData.current;
                }

                break;
            }
        }

        return this;
    },
```
Removing the `break` is the obvious choice, but I do not know if this would have unintended consequences? I am happy to put a PR in place if this is the correct solution.

**Comment by RBrNx** [comment]
Just attempted to remove the `break` and I can confirm that my tween now works as expected. 

Does anyone know if this is the correct fix for the issue, or if I should be doing this is a completely different way? I figured I could create a tween for each child, but that seems wasteful, especially since a tween seems to be able to handle multiple items in other ways.

**Comment by photonstorm** [comment]
I can't see any reason to keep the `break` statement, so I'll remove it.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
