### ISSUE TITLE
SpinePlugin can fail to load skeleton if there is no default skin

### ISSUE THREAD

**Issue by Jonchun** [photonstorm/phaser#4764]
## Version
* Phaser Version: 3.19.0
* Operating system: N/A

## Description
In the plugin, when loading a SpineGameObject's skeleton, there is a call to `this.setSkeleton` which calls ` skeleton.setSkinByName('default');` at https://github.com/photonstorm/phaser/blob/v3.19.0/plugins/spine/src/gameobject/SpineGameObject.js#L517

However, it is possible for there to not be a default skin. You will get
```
Skin not found: default
```
I initially reported this issue without doing enough research at https://github.com/EsotericSoftware/spine-runtimes/issues/1503, thinking this was a backwards compatibility issue (in the 3.8 runtime, you get `null` instead of an empty "default" skin if there are no attachments)

However, it appears this has always been the behavior as per @badlogic. 
> If the default skin does not have any attachments in the editor, no default skin will be exported to either JSON or .skel.

**Comment by badlogic** [comment]
Quick note after looking at the Phaser code: there's no reason to
explicitely set the "default" skin as in the line of code linked to by OP.
Removing that line will do the trick.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
