### ISSUE TITLE
Mask and container  mechanism blocked me migrate phaser 2 to phaser 3

### ISSUE THREAD

**Issue by taoabc** [photonstorm/phaser#4765]
Hello
    I'm glad to report my situation here, I'm plan to migrate my phaser ce to phaser 3, But I'm blcoked by a issue, here's my issus outline:
    
 I have a batch of image, and I want to mask everyone of it (such as mask a circle over avator), then add these item to one container, and set this container for dragonbone's slot. But I find It's unreachable. Just one thing block: Mask can not add to container.

The first problem I faced is mask can not applied to children of container, I use a container for every item, then add these containers to root container, tricky, but fixed.

The second problem, I have no idea to fix. Because of dragonbone's slot display may have animation on it, like move,  transform，etc. The circle mask over avator must synchronize with avator under, but I can't add either graphics or mask created from graphics to container.

I think the problem is not only produced when use dragonbones, If I want to do same thins at a batch of item in container, of just set these item to a outer function, It can not maked.

If you have any idea to resolve this, please tell me, thank you!

**Comment by photonstorm** [comment]
You can add masks to Containers. This has worked for quite a few versions now. Here is one example: http://labs.phaser.io/view.html?src=src%5Cdisplay%5Cmasks%5CContainer%20Mask%20Test%201.js&v=dev - you'll need to provide a code example demonstrating how the masks on a container don't work for us to take this further. As for the Dragbones side of it, that's out of our control I'm afraid.

**Comment by taoabc** [comment]
HI Rich, here's my code
```
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    backgroundColor: '#000066',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('bg', 'assets/ui/undersea-bg.png');
    this.load.image('ayu', 'assets/pics/ayu.png');
}

function createAvatar (scene)
{
    const container = scene.add.container(400, 300);

    const sprite1 = scene.add.sprite(0, 0, 'ayu');
    // must set x y exactly same with container's x and y here
    // even though shape1 is added to container
    const shape1 = scene.make.graphics().fillRect(400, 300, 100, 100);

    // !! I want mask attached to sprite1
    // !! because I don't know what will happen next
    container.add(shape1);
    container.add(sprite1);
    const mask = shape1.createGeometryMask();
    sprite1.setMask(mask);

    // return one game object, don't care how to show
    return container
}

function create ()
{
    var bg = this.add.image(400, 300, 'bg');

    // create a game object, don't care what's inside
    const avatar = createAvatar(this)

    // !! this is what happend next
    this.tweens.add({
        targets: avatar,
        angle: { value: 360, duration: 6000 },
        scaleX: { value: 0.5, duration: 3000, yoyo: true, ease: 'Quad.easeInOut' },
        scaleY: { value: 0.5, duration: 3000, yoyo: true, ease: 'Quad.easeInOut' },
        repeat: -1
    });
}
```

**Comment by photonstorm** [comment]
That's not how masks in v3 work though, as it says in the docs: all mask coordinates are world based, not local based, and are never bound to the item they are masking. One mask can mask many different objects all at the same time. They are not children of anything, you can't add a mask to a container, they're just stencils that impact the rendering of the objects using them.

I agree this isn't how it works in v2 (not that you could ever do bitmap masking in v2), but it's equally not a bug, as it was designed this way and won't be changed for any v3 version I'm afraid.

**Comment by taoabc** [comment]
I am very sad to hear this. I have read the document and learned about the mechanis before post this issue.

I wanted to come here to find a solution. 

It is to treat both the mask and the covered object as if they were one object. Like draw a circle avatar but image below is rectangle.

Do you have any Suggestions?

**Comment by taoabc** [comment]
By the way, why the mask is global based. Is this for performance optimization or bitmap mask? 

Is there another way to do things like CSS: **overflow: hidden.**

**Comment by rexrainbow** [comment]
@taoabc 

I had a plugin to show an image with a circle mask. Here is a [demo](https://codepen.io/rexrainbow/pen/XWrMKBY), and [document](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/circlemaskimage/). 
The concept of this plugin is:
1. Create a canvas, fill with texture image.
2. [Draw a circle mask on this canvas](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/gameobjects/circlemaskimage/ApplyCircleMask.js#L9-L19).

**Comment by taoabc** [comment]
@rexrainbow Thank you so much, your code just show me how to create  containered mask. Give me idea to create my own complex mask~

**Comment by photonstorm** [comment]
Sorry, but there isn't a "solution" as it isn't a problem, it's was a design decision. It just doesn't work the way you want it to and there's no way to enable it to do so, either. Masks are global and one single mask can mask many, many different objects in a single pass, something not possible in v2.
