### ISSUE TITLE
How to change the spine slot's attachment to dynamic created gameobject

### ISSUE THREAD

**Issue by taoabc** [photonstorm/phaser#4766]
I have tried to use spine to replace my dragonbones, But I faced a serious problem soon. I found there's no way to change the spine slot's attachment to my own gameobjects, like image, text.

The dragonbones has ability to do, but I met another problem: https://github.com/photonstorm/phaser/issues/4765

Now I was forced to fallback.

**Comment by photonstorm** [comment]
Sorry it took so long to respond to this issue, but there are no plans for providing this feature I'm afraid.
