### ISSUE TITLE
Simple arcade collisions issue since Phaser 3.17.0

### ISSUE THREAD

**Issue by mrdannael** [photonstorm/phaser#4770]
## Version
* Phaser Version: 3.17.0 and above
* Operating system: Ubuntu 18.04.3
* Browser: Chrome 77

## Description

It looks like there is some issue with the arcade physics in Phaser 3.17.0 and above.
I'm adding three sprites with collisions, two dynamic (red icon and blue icon) and one static (square icon). The red one can be moved with WSAD keys. When red is colliding with the blue one from the left side, then red is pushing blue one without any problems. But when you try to push the blue ball from the bottom, top or right collision physics are not working correctly. Red ball is "jumping" through the blue one when pushing from the right.

Also when trying to push square sprite from the right side you can sometimes go through collision box.

Good behavior: 3.16.2

![GIF](https://imgur.com/lKDEHkc.gif)

Bad behavior: 3.17.0 (and above)

![gif](https://imgur.com/r1ykfow.gif)

## Example Test Code

Here's JSFiddle with source code > [source code](https://jsfiddle.net/ypcfzxad/3/)

```
<!doctype html> 
<html lang="en"> 
<head> 
    <meta charset="UTF-8" />
    <title>Arcade Physics Test</title>
    <script src="//cdn.jsdelivr.net/npm/phaser@3.19.0/dist/phaser.js"></script>
    <style type="text/css">
        body {
            margin: 0;
        }
    </style>
</head>
<body>
<script type="text/javascript">
    var config = {
        type: Phaser.AUTO,
        width: 800,
        height: 600,
        scene: {
            preload: preload,
            create: create,
            update: update
        },
        backgroundColor: '0xffffff',
        physics: {
        	default: 'arcade',
         	arcade: {
          	debug: true
          }
        }
    };

    var game = new Phaser.Game(config);

function preload() {
    this.load.image('player', 'https://cdn4.iconfinder.com/data/icons/32x32-free-design-icons/32/Cancel.png');
    this.load.image('crate', 'https://cdn4.iconfinder.com/data/icons/32x32-free-design-icons/32/Transparent_color.png')
}

function create() {
    this.player = this.physics.add.sprite(100, 100, 'player');
    this.player.setCircle(16);
    this.player.setTint(0xff0000);

    this.enemy = this.physics.add.sprite(200, 200, 'player');
    this.enemy.setCircle(16);
    this.enemy.setTint(0x0000ff);

    this.crates = this.physics.add.staticGroup();
    this.crates.create(400, 400, 'crate');

    this.physics.add.collider(this.player, this.enemy);
    this.physics.add.collider(this.player, this.crates);

    this.keys = this.input.keyboard.addKeys('W,S,A,D');
}

function update() {
    this.player.setVelocity(0);

    if (this.keys.A.isDown) {
        this.player.setVelocityX(-100);
    } 
    if (this.keys.D.isDown) {
        this.player.setVelocityX(100);
    }
    if (this.keys.W.isDown) {
        this.player.setVelocityY(-100);
    } 
    if (this.keys.S.isDown) {
        this.player.setVelocityY(100);
    }
}
</script>
</body>
</html>
```

**Comment by photonstorm** [comment]
Please test this again 3.20 (the current master branch) as it contains several Circle related fixes.

**Comment by mrdannael** [comment]
Testing on 3.20.0-beta1

![](https://imgur.com/yQc0eXb.gif)

So now circle collision behave correctly but there's still problem with collision with square object as you can see on GIF above. Ball can go trough it from the top-right side of the square.

ps. It's nice to see references to Shield Hero and Ghost in the Shell in Phaser :smiley:

**Comment by JRB-y** [comment]
Does a Patch exists or we use 3.16.0 and below ?

**Comment by mrdannael** [comment]
https://jsfiddle.net/g7opuh09/ using 3.21.0 - issue with square object still occurs.

**Comment by JRB-y** [comment]
Version below 3.16.0 don't have this bug ?

**Comment by mrdannael** [comment]
That's right.

**Comment by cfortuner** [comment]
Hey. I'm noticing that circle-circle collisions are still an issue in v3.23.

I was able to reproduce the issues when colliding a circle with another circle and the wall boundary: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5430709/85637562-6492fd80-b638-11ea-8873-0a807676256f.gif)

I was also able to reproduce circle / rectangle collisions. This only occurs from the top right corner of the rectangle.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/5430709/85637797-ff8bd780-b638-11ea-8e8a-a160f0df08ca.gif)

Here is the updated fiddle https://jsfiddle.net/vtkojf0y/

**Comment by cfortuner** [comment]
I also noticed that when adding two way colliders, the problems get worse.

ex.
```
this.physics.add.collider(this.player, this.enemy);
this.physics.add.collider(this.enemy, this.player)
// or
this.physics.add.collider(this.playersGroup, this.playersGroup)
```

**Comment by samme** [comment]
Example: https://codepen.io/samme/pen/PoZjLad

You can try with a circular or rectangular block, there are different problems for each.

**Comment by samme** [comment]
Try this fix: [phaser-arcade-physics.js.zip](https://github.com/photonstorm/phaser/files/4860106/phaser-arcade-physics.js.zip)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

Note this isn't a complete fix, but it does address most issues raised here.
