### ISSUE TITLE
As of 3.20beta, Spine GameObjects are not appearing in the scene

### ISSUE THREAD

**Issue by RichardSneyd** [photonstorm/phaser#4771]
## Version

* Phaser Version: 3.20beta

* Operating system: Windows 10

* Browser: Not browser specific

## Description

Expected behavior: Spine game objects will appear in the scene when added to the display list.

What happens: They don't.

## Example Test Code

export default class SpineObject {
    spine: SpineGameObject;
    scene: Phaser.Scene;
    track: number = 1;
    constructor(scene: Phaser.Scene, x: number, y: number, key: string, container: Phaser.GameObjects.Container, animation?: string, loop?: boolean) {
        this.scene = scene;
        this.spine = scene.add.spine(x, y, key, animation, loop);
        this.spine.setInteractive(this.spine.getBounds());

        // @ts-ignore
        this.scene.sys.displayList.add(this.spine);
        // @ts-ignore
        this.scene.sys.updateList.add(this.spine);

        // @ts-ignore
        console.log('should see ' + key);
        console.log(this.scene.sys.displayList.getAll());

        // @ts-ignore
        // container.add(this.spine);
        //console.log(container);
        //   debugger;
          this.scene.input.enableDebug(this.spine);
    }

    public getAttachments() {
        return this.spine.skeleton.skin.attachments;
    }

    public getSlots() {
        return this.spine.skeleton.slots;
    }

    public changeSkin(skinName: string) {
        // @ts-ignore
        this.spine.setSkin(null);
        // @ts-ignore
        this.spine.setSkinByName(skinName);
    }

}

## Additional Information

I was using this class with phaser 3.19 to add spine objects to the scene, and it was working. I copied over the updated build of the SpinePlugin in the dist folder for the coming 3.20 release, and now it doesn't work (nothing appears). There are no errors showing in the console. Furthermore, I have logged the displayList to the console, and as you can see in the screenshot, all of the spine objects are appearing in the list.

Any idea what is going on here? 

Thanks in advance,
Richard
![spineobjects-not-appearing](https://user-images.githubusercontent.com/12007351/65867224-ef76ee00-e36d-11e9-8374-6f17fceed548.jpg)

**Comment by RollinSafary** [comment]
Same here

**Comment by RichardSneyd** [comment]
@RollinSafary could you clarify your commend regarding the -infinity and infinity values?

**Comment by photonstorm** [comment]
Are you definitely using 3.20 as well? Lots of the Container related fixes are in Phaser directly, not the plugin.

**Comment by RichardSneyd** [comment]
@photonstorm that might be it... I had difficulty building phaser with parcel, so I copied the build over from the dist folder, assuming, perhaps rashly, that it had been build since those commits were made to the repo. I'll try again to build 3.20, and let you know if the problem persists.

**Comment by RichardSneyd** [comment]
@photonstorm I've done a git pull origin master > npm run dist, and copied over the newly built file, but I'm still having the same problem.

**Comment by RichardSneyd** [comment]
As a side note, when I try npm run build, I get the following error: 

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\sites\phaser\scripts\copy-to-examples.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

This path should be C:\sites\phaser\src\scripts\copy-to-examples.js, from what I can see.

**Comment by photonstorm** [comment]
You could use a dev build from the labs to avoid spending time building, but it should really be done with webpack. That scripts path is correct, too. Maybe a Parcel side effect assuming the scripts are es6 or something (they're not)

Aside from this, I still cannot replicate what you're seeing. I've created 3 different ways of adding a Spine Game Object into a Scene and they all work. You can see the code below and I've uploaded it to the Labs too, so you can run it directly and download the Phaser + plugin builds I'm using.

http://labs.phaser.io/view.html?src=src%5Cspine%5C3.8%5Cextended%20class.js&v=dev

```
class CustomSpineObject1
{
    constructor (scene, x, y, key, animationName, loop)
    {
        this.scene = scene;

        this.spine = scene.add.spine(x, y, key, animationName, loop);
    }
}

class CustomSpineObject2
{
    constructor (scene, x, y, key, animationName, loop)
    {
        this.scene = scene;

        this.spine = scene.make.spine({ scene, x, y, key, animationName, loop });

        scene.sys.displayList.add(this.spine);
        scene.sys.updateList.add(this.spine);
    }
}

class CustomSpineObject3
{
    constructor (scene, x, y, key, animationName, loop)
    {
        this.scene = scene;

        this.parent = scene.add.container(x, y);

        this.spine = scene.make.spine({ scene, x, y, key, animationName, loop });

        scene.sys.displayList.add(this.spine);
        scene.sys.updateList.add(this.spine);

        this.parent.add(this.spine);
    }
}

class Example extends Phaser.Scene
{
    constructor ()
    {
        super({
            pack: {
                files: [
                    { type: 'scenePlugin', key: 'SpinePlugin', url: 'plugins/3.8/SpinePlugin.js', sceneKey: 'spine' }
                ]
            }
        });
    }

    preload ()
    {
        this.load.image('logo', 'assets/sprites/phaser.png');

        this.load.setPath('assets/spine/3.8/demos/');

        this.load.spine('set1', 'demos.json', [ 'atlas1.atlas' ], true);
    }

    create ()
    {
        this.add.image(0, 0, 'logo').setOrigin(0);

        let custom1 = new CustomSpineObject1(this, 100, 550, 'set1.spineboy', 'idle', true);
        let custom2 = new CustomSpineObject2(this, 350, 550, 'set1.spineboy', 'walk', true);
        let custom3 = new CustomSpineObject2(this, 600, 550, 'set1.spineboy', 'run', true);

        custom1.spine.setScale(0.5);
        custom2.spine.setScale(0.5);
        custom3.spine.setScale(0.5);
    }
}

const config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    scene: Example
};

const game = new Phaser.Game(config);
```

Also worth mentioning - if you do `scene.add` then adding it to `displayList` and `updateList` in the same function is just skipped by Phaser, as it's already in them.

**Comment by RichardSneyd** [comment]
@photonstorm OK, thanks for the heads up about the dev builds, I'll try it again with that and see what happens..

**Comment by photonstorm** [comment]
Ok. If you still can't get it working, please post a new code example I can just run right away to reproduce it, as I've spent quite a while looking at this now and am confident it's probably not an API issue.

**Comment by RichardSneyd** [comment]
@photonstorm I think I spotted a typo in your example above, I don't if that is why we're seeing different results or not, the 3rd instantiation line calls the CustomSpineObject2 class a second time, when it should call CustomSpineObject3. That may not be anything of significance, but I thought I'd point it out all the same.

**Comment by photonstorm** [comment]
You're right. It still works though. Here is the new test3:

```js
class CustomSpineObject3
{
    constructor (scene, x, y, key, animationName, loop)
    {
        this.scene = scene;

        this.parent = scene.add.container(0, 0);

        this.spine = scene.make.spine({ scene, x, y, key, animationName, loop });

        this.parent.add(this.spine);
    }
}
```

**Comment by RichardSneyd** [comment]
OK. Well do some more digging to see if I can figure out why I'm having a different experience, because I'm using the dev build now. Also, when I add the spine object to a container, I get this error in the console now: 

dev.js:41178 Uncaught TypeError: child.setBlendMode is not a function
    at ContainerCanvasRenderer [as renderCanvas] (dev.js:41178)
    at CanvasRenderer.render (dev.js:146721)
    at CameraManager.render (dev.js:9896)
    at Systems.render (dev.js:160535)
    at SceneManager.render (dev.js:157983)
    at Game.step (dev.js:14632)
    at TimeStep.step (dev.js:15434)
    at step (dev.js:27564)

I'm sure at this point that it must be a mistake somewhere on my end, I'll post the answer once I've figured it out.

**Comment by photonstorm** [comment]
Ahh, you're using the Canvas Renderer! That makes all the difference. I ran my test under canvas and get the blend mode error too, this is now fixed in the master branch.

This is why runnable examples that fully reproduce the errors are _so important_.

**Comment by RichardSneyd** [comment]
OK, will be sure to provide _complete_ examples in the future :) Thanks for the fix! I'll go try it now -- I'm surprised it was using the Canvas renderer, I had it set to AUTO and I'm running decent hardware.

**Comment by RichardSneyd** [comment]
Actually, it was set to Canvas. Don't know how that happened, must have been doing some debuggin and forgot to change it back. Anyway, thanks.

**Comment by RichardSneyd** [comment]
I'm no longer getting the error, but the spine objects still aren't appearing for me. After staring at the console for an extended period of time, I noticed that these properties have odd values: 

displayOriginX: -Infinity
displayOriginY: NaN
displayWidth: -Infinity

This is the case for all fo the spine objects I am creating. I'll put together a repo so you can test a complete example and see exactly what I'm seeing.

**Comment by photonstorm** [comment]
All of those values are populated directly by the Skeleton data. Please note that in order to use this version of the plugin, you _must_ re-export all of your skeletons using Spine 3.8 (or above, I believe they're testing 3.9 at the moment). Open your skeleton json files and have a look. If the Spine version number in there isn't 3.8.x then you're going to experience various issues with the runtime.

**Comment by garkin** [comment]
How older plugin versions are supposed to be used? 
Is manual clone to the local codebase the only way?

**Comment by photonstorm** [comment]
Yes, but I doubt you can use it with 3.20.

I wish it was backward compatible, but it isn’t and it’s completely out of my control. If they change their runtimes that much, there’s nothing you can do. Technically, I could maintain two versions of the plugin, but honestly that’s just too much effort. Especially when you consider the fact that you legally can’t even use the Spine plugin unless you own the software, so you have the means to re-export as 3.8 already. It’s a chore, I agree, but not of my making.

**Comment by RichardSneyd** [comment]
@photonstorm Yes, when I had the artist rebuild the spine files with 3.8, it worked. Thanks again.
