### ISSUE TITLE
The return value of BaseSound.addAudioSprite is strange.

### ISSUE THREAD

**Issue by r-onodera** [photonstorm/phaser#4772]
## Version

* Phaser Version:
Phaser v3.19.0

* Operating system:
Windwos 7 64bit

* Browser:
Google Chrome v77.0.3865.90 (64bit)

## Description

In the definition of phaser.d.ts, BaseSoundManager.addAudioSprite returns Phaser.Types.Sound.AudioSpriteSound.
However, Phaser.Types.Sound.AudioSpriteSound only defines the spritemap property.
Isn't the correct return value Phaser.Sound.BaseSound?

The above is Google Translate of the following sentence.
```
phaser.d.tsの定義では、BaseSoundManager.addAudioSpriteはPhaser.Types.Sound.AudioSpriteSoundを返します。
ただし、Phaser.Types.Sound.AudioSpriteSoundはspritemapプロパティのみを定義します。
正しい返り値はPhaser.Sound.BaseSoundではないでしょうか。
```

## Example Test Code

```typescript
const sound = this.sound.addAudioSprite('example');
sound.play('foo');  // <- TS2339: Property 'play' does not exist on type 'AudioSpriteSound'.
```

**Comment by photonstorm** [comment]
Yes, this is wrong. I have fixed it in the master branch.
