### ISSUE TITLE
Where is SoundManagerCreator.create?

### ISSUE THREAD

**Issue by r-onodera** [photonstorm/phaser#4774]
## Version

* Phaser Version:

Phaser v3.19.0
* Operating system:

Windwos 7 64bit
* Browser:
Google Chrome v77.0.3865.90 (64bit)

## Description

In the definition of phaser.d.ts, SoundManagerCreator is a function and the return value is void.

However, SoundManagerCreator is actually a static class and has a create method.
The return value is NoAudioSoundManager, WebAudioSoundManager or HTML5AudioSoundManager.

The above is Google Translate of the following sentence.

```
phaser.d.tsの定義ではSoundManagerCreatorは関数で返り値がvoidです。

しかし実際にはSoundManagerCreatorは静的クラスであり、createメソッドを持っています。
また返す値がNoAudioSoundManager、WebAudioSoundManagerもしくはHTML5AudioSoundManagerです。
```

## Example Test Code

```typescript
const game = new Phaser.Game(config);

// TS2339: Property 'create' does not exist on type ''
const mng = Phaser.Sound.SoundManagerCreator.create(game);
```
![types_SoundManagerCreator](https://user-images.githubusercontent.com/33089857/65949902-00ac2180-e478-11e9-9dcf-c52eeed96eef.png)

https://github.com/photonstorm/phaser/blob/v3.19.0/src/sound/SoundManagerCreator.js
![image](https://user-images.githubusercontent.com/33089857/65950053-4963da80-e478-11e9-9c84-fc7555783d1b.png)

**Comment by photonstorm** [comment]
This function should not be called directly and is not public. Phaser already calls it automatically in the Game class.

**Comment by r-onodera** [comment]
Oh...
I see. Thanks!

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/is-it-possible-to-have-2-sound-managers/11354/1
