### ISSUE TITLE
disableContextMenu setting doesn't work in mobile

### ISSUE THREAD

**Issue by simplewei** [photonstorm/phaser#4778]
### Version
* Phaser Version: 3.19.0
* Operating system: ios  & andriod
* Browser: safari & chrome

### Description
disableContextMenu setting doesn't work when I enable touch and disable mouse config.

### Example Test Code
```
const config = {
      input: { mouse: false, touch: { capture: false } },
      disableContextMenu: true,
}
```

### Additional Information
This could be caused by the [TouchManager](https://github.com/photonstorm/phaser/blob/v3.19.0/src/input/touch/TouchManager.js#L176)
forgot to add the following code https://github.com/photonstorm/phaser/blob/v3.19.0/src/input/mouse/MouseManager.js#L208

**Comment by photonstorm** [comment]
Are you sure this is even possible to disable from mobile? I'm pretty sure it isn't, but it's been a while since I lasted tested it.

**Comment by simplewei** [comment]
In my project scenario (mobile), I need to hold the button for a while, then the context menu will pop up and cause a bug.

I have tested it and temporarily solved it with the following code :

```
document.body.addEventListener('contextmenu', function (event){
   event.preventDefault();
  return false;
 });
```

**Comment by simplewei** [comment]
Maybe you can test it with the following example:

https://codepen.io/simplewei/full/pozMMMd

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
