### ISSUE TITLE
Collision shape does not align with sprite after setOrigin (matter)

### ISSUE THREAD

**Issue by soyrandom** [photonstorm/phaser#4782]
when setOrigin is used on a matter sprite, it's collision origin does not change and creates an offset
without setOrigin https://imgur.com/13mpO97
with setOrigin https://imgur.com/TlRUhf3

**Comment by photonstorm** [comment]
The origin of a Matter Sprite should always represent the center of mass of the body +/- whatever offset you set in the `render.sprite` offset values. If you adjust the origin post-creation of the Body, then you need to include the center of mass with the origin, or the body will not be aligned. You can access the com via `Body.centerOfMass` in 3.22.
