### ISSUE TITLE
scale.setGameSize don't work correct with FIT mode.

### ISSUE THREAD

**Issue by iKest** [photonstorm/phaser#4784]
when i resizing the game with setGameSize acpect ratio of the canvas style does not change

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so (and a lot more details than currently given!). Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

**Comment by samme** [comment]
#4971
