### ISSUE TITLE
Phaser.Physics.Arcade.Sprite.setSize in Typescript definition cannot set center

### ISSUE THREAD

**Issue by wingyplus** [photonstorm/phaser#4786]
## Version
* Phaser Version: ^3.19.0
* Operating system: macOS

## Description

In Typescript definition, setSize in types/phaser.d.ts line 57389 define like this: 

```typescript
/**
 * Sets the internal size of this Game Object, as used for frame or physics body creation.
 *
 * This will not change the size that the Game Object is rendered in-game.
 * For that you need to either set the scale of the Game Object (`setScale`) or call the
 * `setDisplaySize` method, which is the same thing as changing the scale but allows you
 * to do so by giving pixel values.
 *
 * If you have enabled this Game Object for input, changing the size will _not_ change the
 * size of the hit area. To do this you should adjust the `input.hitArea` object directly.
 * @param width The width of this Game Object.
 * @param height The height of this Game Object.
 */
setSize(width: number, height: number): this;
```

As I understand, setSize method come from Size component. That it's [this](https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/components/Size.js#L48). So that's means setSize in class Sprite should be like this:

```typescript
setSize(width: number, height: number, center?: boolean)
```

## Additional Information 

I'm not sure I understand correctly. If I understand it wrong, please suggest to me. :)

**Comment by samme** [comment]
For Arcade Game Objects, [Physics.Arcade.Components.Size#setSize()](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Components.Size.html#setSize) overrides [GameObjects.Components.Size#setSize()](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Components.Size.html#setSize), but the two methods are actually unrelated (and have different signatures). It is confusing. 🙁 

https://github.com/photonstorm/phaser/issues/4213#issuecomment-455898802

**Comment by wingyplus** [comment]
@samme Thanks for your clarify. I got really confusing too.

**Comment by photonstorm** [comment]
This function has been deprecated, replaced with `setBodySize` in 3.24.

**Comment by wingyplus** [comment]
@photonstorm Thanks for this fixed. :)
