### ISSUE TITLE
Axis event not firing for Gamepad

### ISSUE THREAD

**Issue by ouya99** [photonstorm/phaser#4788]
Phaser Version 3.16
System: MacOs Sierra

`
 this.input.gamepad.on('down', function (pad, button, index) {
      console.log(button)
      console.log(index)
      console.log(pad.pad.axes)
    })
    this.input.gamepad.on('axis', function (pad, button, index) {
    })
`

The axis callback does not seem to work, neither does **pad.pad.axis** . How do you query the axis for a standard gamepad? (snes like)

**Comment by binaryer** [comment]
same

**Comment by photonstorm** [comment]
There is no `axis` event. You read it directly from a Gamepad instance in your `update` handler:

```js
    if (this.input.gamepad.total === 0)
    {
        return;
    }

    var pad = this.input.gamepad.getPad(0);

    if (pad.axes.length)
    {
        var axisH = pad.axes[0].getValue();
        var axisV = pad.axes[1].getValue();

        sprite.x += 4 * axisH;
        sprite.y += 4 * axisV;

        sprite.flipX = (axisH > 0);
    }
```
