### ISSUE TITLE
iOS: SAFARI: INTERMITTENT?: Audio doesn't resume after opening link or switching tabs

### ISSUE THREAD

**Issue by micsun-al** [photonstorm/phaser#4790]
## Version
* Phaser Versions:
Phaser v3.22.0 (WebGL | Web Audio)
Phaser v3.20.1 (WebGL | Web Audio)
Phaser v3.20.0-FB (WebGL | Web Audio) 
Phaser v3.19.0-FB (WebGL | Web Audio)
* Operating system:
Reproduced on iOS 10.3.3, 12.1.4, 12.2, 12.3.1, 12.4.1, 12.4.2, 13.0
* Browser:
Safari
* Devices reproduces this issue consistently:
iPhone X (Safari 12.4.1)
iPhone 7 (Safari 13.0)
iPhone 6 Plus (Safari 12.4.2)
iPhone 6 (Safari 12.3.1)
iPad 4 (Safari 10.3.3, MD514LL/A)

* Devices NOT REPRODUCED (could have sworn it did reproduce at one point, meh):
iPhone 5 (Safari 10.3.3) ... may be intermittent or some other factor?

## Description
Steps:
1. On the iPhone, inside of Safari, go to https://adidasbaseballsnextlevel.com/
(also, bare-bones reproduction is available at https://micsun-al.github.io/tests/phaser3-ios-audio-issue/index.html)
2. Tap once to begin the background audio loop.
3. Tap one of the logos to open a link in a new tab.
4. Close the new tab and return to the game.

Expected Behavior:
The audio should resume playing.

Current Behavior:
Returning to the app tab does not resume audio ... sometimes.  It doesn't seem consistent for some reason.  Sometimes minimizing the game using the home button, and then returning to it has the same behavior.  I can't seem to get this to reproduce, or not reproduce 100% of the time on any of the iPhones.

Here's a video of it reproducing on the iPhone X:
https://youtu.be/QvzvDy2yAyo

## Example Test Code
*Code:*
https://github.com/micsun-al/phaser3-test-audio-ios

*Preview:*
https://micsun-al.github.io/tests/phaser3-ios-audio-issue/index.html

...But basically, a looping sound will reproduce this issue, and also any new audio `play` seems to not be audible also.
```javascript
function preload(){
  this.load.audio('music', ['music.mp3'])
}

function create(){
  const someMusic = this.sound.add('music')
  someMusic.play({ loop: true })
}
```

## Additional Information
This reproduces on https://adidasbaseballsnextlevel.com/
This does NOT seem to reproduce with the Phaser 2.13.3 music example: https://phaser.io/examples/v2/audio/play-music

**Comment by paulsymphony** [comment]
I have also recreated this issue on iOS 12 and 13 - and setting pauseOnBlur = false has no effect

**Comment by photonstorm** [comment]
I wonder if iOS just disposes of the AudioContext and so all future sounds fail?

This new commit may help: https://github.com/photonstorm/phaser/commit/5e1d86b75b2b8a93e4f9f11f9e548df1179506e1

If you pass in a new context when you detect it coming back.

**Comment by paulsymphony** [comment]
A temporary solution to this issue: use a custom audioContext, then put a listener in for the app 'focus', and wait a bit before calling resume():

`window.addEventListener("focus", function(event) 
{ 
  setTimeout(function(){ 
    console.log('resuming...')
    audioContext.resume(); 
  }, 1000);

}, false);`

**Comment by photonstorm** [comment]
@paulsymphony have you had luck with the above setTimeout approach working?

**Comment by paulsymphony** [comment]
Yes! No loss of sound on iOS 12 or 13 with this patch. I've reduced the timeout to 500ms with no problems. I also put in a listener for 'blur', and pause() the context.

**Comment by jamaalsawyerd** [comment]
@paulsymphony this doesn't work for me when I go to the home screen, let Safari fully rest and come back into the browser.

**Comment by paulsymphony** [comment]
Have you paused the context? That's necessary. In the end, I needed to use a custom audioContext in Phaser so that I could regenerate it if necessary. On iOS 13, the soft keyboard sometimes disrupts the audio context in Cordova apps. It's a real pain. I actually provide a tool in my app to allow users to 'Repair Sound' if they lose it. To repair, I generate a new sound context, then set the Phaser audio context to that new one.

**Comment by jamaalsawyerd** [comment]
See the following video I made:
https://owncloud.thegameagency.com/next/index.php/s/nsmAxZPdtQNjwwQ

Going to the home screen and then coming back in the sound doesn't re-enable unless I exit and re-enter the tab? Is this implementation similar to what you've implemented?

`window.addEventListener('focus', () => {
        setTimeout(
          () => {
            console.log('resuming audio context...');
            window.phaserAudioContext.resume();
          }, 500);
      }, false);
      window.addEventListener('blur', () => {
        console.log('pausing audio context...');
        window.phaserAudioContext.suspend();
      }, false);`

**Comment by paulsymphony** [comment]
Weird - my app doesn’t work on iPhone either. It’s meant for iPad and it does work on there. Fun

**Comment by paulsymphony** [comment]
Mine does work. Here's what I do:

First, I use my own audioContext, which I create before the new Phaser.Game call:

var audioContext = new ((<any>window).AudioContext || (<any>window).webkitAudioContext)();

Then, in the config, I specify this audioContext:
*** in config: ***
audio: {
    context: audioContext
  },

Then, I use these call for blur and focus:

window.addEventListener("blur", function(event) 
{ 
  audioContext = game.sound.context;
  if (audioContext.state==='running' && UrlUtil.isSafariOrIOS(game.scene.getScene('Main'))) {
    console.log('suspending audio');
    audioContext.suspend();
  }
}, false);

window.addEventListener("focus", function(event) 
{ 

  setTimeout(function(){ 
    audioContext = game.sound.context;
    if (audioContext.state==='suspended' && UrlUtil.isSafariOrIOS(game.scene.getScene('Main'))) {
      console.log('resuming audio')
      audioContext.resume(); 
    }
  }, 500);
}, 
false);

**Comment by jamaalsawyerd** [comment]
Interesting. I just used exactly your code and it still happens. See the following:
https://owncloud.thegameagency.com/next/index.php/s/2G5XC4K2Xepm9k5

You are using Cordova? Perhaps it behaves differently than running in Safari browser. The only work-around I could figure was to of redo the unlock event handlers that Phaser 3 does initially and showing them an alert to touch the screen to re-enable audio.

**Comment by paulsymphony** [comment]
No, works in Safari too. Hmm. I am also manually refreshing the audio at key points in my app. I wonder if the first refresh prevents this error?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by micsun-al** [comment]
I installed using `yarn add -D phaser@beta` and it seems to install `Phaser v3.54.0-dev`.

This still seems to reproduce on the following configurations:
iPhone 7, iOS 14.4.1
...coworker tested it on a newer iPhone X (or higher?) and it seems to reproduce for him too. I'll update this once they tell me what model and iOS they have.

**Comment by micsun-al** [comment]
With `Phaser v3.54.0-dev`, setting the following seems to make audio work as expected (it resumes playing after tab switching):
```javascript
this.sound.pauseOnBlur = false
```

**Comment by micsun-al** [comment]
Setting it to false made it keep playing audio while tab was switched on **Android**, but not iOS (but it made audio resume correctly on iOS after coming back to the tab).

My workaround for now is:
```javascript
scene.sound.pauseOnBlur = !scene.sys.game.device.os.iOS
```

**Comment by photonstorm** [comment]
Give the new version in master a go (you _will_ have to build it, it's not on npm yet)

**Comment by ubershmekel** [comment]
I was googling for an hour, stumbled upon this issue. I just couldn't figure out why my iPhone audio wasn't working. I even cloned the repo, built it and tested out the new version. Nothing worked. Turns out the phone was silent because of the physical silence switch 🤦.

**Comment by karthickTT** [comment]
While play the html 5 game  in chrom/firefox browsers, the sounds plays well iphone & ipad version 16.6.
Once minimize & return to the game page, the sound is not playing.
Immediately again minimize & return to the game page, the sound is playing well.
As like this happen alternatively.

Note: The same html 5 game plays and check in iPhone 7, version V 15.7.7 - audio plays properly.

[html5gamelink
](https://preview.codecanyon.net/item/plinko-html5-casino-game/full_screen_preview/21129096?_ga=2.117735744.85217285.1692960433-1127400555.1691637078)

Use the above link, to check in the ios device directly as i mentioned above.

Can anyone help to resolve this issue? Thanks in advance.
