### ISSUE TITLE
ScaleManager. Unable to get property 'then' of undefined or null reference.

### ISSUE THREAD

**Issue by maksdk** [photonstorm/phaser#4795]
## Version

* Phaser Version: 3.19.0

* Operating system: Microsoft Windows 10 Pro / Version 1809 / Build 17763.775

* Browser:  Microsoft Edge 44.17763.771.0

## Description
I am using ScaleManager's  `this.scale.startFullscreen()`  function and it works ok in all browsers exept Edge. In Edge when I try to call the method I get an error in the console :  `Unable to get property 'then' of undefined or null reference`.

Image of error: 
![issue_phaser](https://user-images.githubusercontent.com/33781214/66545214-e55da800-eb42-11e9-8006-ac6584bc2ec0.png)

## Example Test Code
```javascript

const config = {
   type: Phaser.AUTO,
   width: 600,
   height: 600,
   scene: { create: create },
   scale: {
      mode: Phaser.Scale.FIT,
      autoCenter: Phaser.Scale.CENTER_BOTH
   },
   backgroundColor: 0xFFFF00
};

const game = new Phaser.Game(config);

function create() {
   const button = new Phaser.GameObjects.Rectangle(this, 300, 300, 300, 100, 0xFF0000);
   button.setInteractive();
   this.add.existing(button);

   button.on("pointerdown", () => {
      if (this.scale.isFullscreen) {
         this.scale.stopFullscreen();
      } else {
         this.scale.startFullscreen();
      }
   });

   const title = new Phaser.GameObjects.Text(this, 300, 300, "CLICK ME TO\nCALL FULLSCREEN", {
      color: "#ffffff", 
      fontSize: "20px", 
      align: "center"
   });
   title.setOrigin(0.5);
   this.add.existing(title);
}
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by maksdk** [comment]
> Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

I have tested 3.20.0v and everything works well. Thank you for your quickly answer.
