### ISSUE TITLE
New game object type definition for typescript users.

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#4796]
Hi, i'm testing Phaser v3.20.0 build and as I saw `getValue` method was removed from `Phaser.Tweens.Tween` class. In result `Phaser.GameObjects.PathFollower` crashes, because it was using that method. And I've decided to use `Phaser.GameObjects.Components.PathFollower` component for creating my own path following game object. 
I'm using typescript.
So first problem was that `Phaser.GameObjects.Components.PathFollower` class isn't exported, which makes uncomfortable importing it, so I had to do that via `var Components = require('phaser/src/gameobjects/components');` which returns an any type object.
Next problem was that `Phaser.Utils.Class` class isn't exported, and the same problems are with this class.
[**information for those, who want to have PathFollower in typescript**]
Then I had to cheat my compiler to have type definitions for new type this way
```
export interface PathFollowerImage
  extends Phaser.GameObjects.Image,
    Phaser.GameObjects.Components.PathFollower {}
```
So please add a comfortable way to generate game object types for developers in typescript.
I think it will be enough to export all components and `Phaser.Util.Class`.

Thanks in advance.

**Comment by photonstorm** [comment]
The Game Object components are all exported, including PathFollower. The mistake is assuming it's a class. It isn't, it's a mixin.

There's absolutely no point using `Phaser.Utils.Class` in TypeScript, though.

**Comment by RollinSafary** [comment]
Maybe here problem is in my knowledge level of typescript, but I think we need for mixins to have possibility in using all Phaser features. If it possible, please publish any example or part of code to show how we can use mixins in typescript.

Thanks in advance.

**Comment by photonstorm** [comment]
Mixins are not native to TypeScript. They provide a section in the handbook on how to use them, but it requires using an `applyMixins` shim to get working: https://www.typescriptlang.org/docs/handbook/mixins.html
