### ISSUE TITLE
Animation bug on scene restart

### ISSUE THREAD

**Issue by jronn** [photonstorm/phaser#4799]
## Versions

* Phaser Version: 3.20
* Operating system: Windows 10
* Browser: Chrome 77.0

## Description

Animations playing on a sprite are sped up when a scene is restarted (see example, press any key to trigger scene restart. Each time the scene is restarted the animation speeds up)

## Example Test Code

https://jsfiddle.net/9v5k1La6/

## Additional Information

Issue is new with 3.20, wasn't present in 3.19

**Comment by photonstorm** [comment]
This has to be the new UpdateList not clearing properly. Will have a look.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by kreso22** [comment]
I can confirm this issue was present for me in 3.19, and it was fixed in 3.21. Thanks!
