### ISSUE TITLE
DynamicTilemapLayer.setCollision() is broken in 3.20

### ISSUE THREAD

**Issue by PavelMishin** [photonstorm/phaser#4800]
## Version
* Phaser Version: 3.20
* Operating system: Windows 10
* Browser: Firefox

## Description
Setting collision on dynamic tilemap layer with `setCollision` method caused an error
`Uncaught TypeError: Cannot read property 'indexOf' of undefined`

## Example Test Code
https://jsfiddle.net/Trobing/vz0fpjhr/22/

## Additional Information
It works for static layers, and it works for dynamic layer with 3.19

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
