### ISSUE TITLE
Phaser.Geom.Line type definition bug

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#4801]
## Version

* Phaser Version: 3.20.0

* Operating system: Windows 10

* Browser: Google Chrome

## Description

Type definition of `getPoints` function is wrong in `phaser.d.ts` file.

current type definition is
`getPoints<O extends Phaser.Geom.Point>(quantity: integer, stepRate?: integer, output?: O): O;`
must be
`getPoints<O extends Phaser.Geom.Point[]>(quantity: integer, stepRate?: integer, output?: O): O;`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by RollinSafary** [comment]
@photonstorm Isn't fixed in 3.21.0 release.

**Comment by photonstorm** [comment]
Damn it, yes, the PR from @ilyaryabchinski updated the defs file directly instead of the JSDocs, so the change was lost the instant the new release was published. This is why the defs file should never be edited, only the JSDocs should.

**Comment by ilyaryabchinski** [comment]
@photonstorm sorry. going to fix it asap
