### ISSUE TITLE
Overlapping DIV with Phaser object with any version > 3.15

### ISSUE THREAD

**Issue by oduvan** [photonstorm/phaser#4802]
when I put DIV with absolute position on top of phaser game and click on it I have two very bad issues:

* the phaser object receives a click even, but should not, because click was on div object, not on phaser
* the phaser object receives even click before div does. 

I  though the bug is pretty much obvious, and when I tried to upgrade from 3.15 to 3.16 - I through - "ok, they will probably fix it in the next version", but it is version 3.20 now, and it is still there.

Maybe I should use overlapped DIV in a new way? 

Here is the source code I was used to replicate an issue. https://github.com/oduvan/phaser3-my-examples/blob/master/click_event.html 

Thank you for your support.

**Comment by photonstorm** [comment]
The problem is that you don't prevent the click event on the div from going any further. Events in the DOM propagate unless you tell them not to, and you didn't, so it's going to carry on through all elements until it reaches one that captures it, or it just reaches the end. There is nothing Phaser can do to prevent this, it's your responsibility to manage any extra DOM elements _you created_.

More info here: https://javascript.info/bubbling-and-capturing

**Comment by photonstorm** [comment]
Also worth adding that you can prevent Phaser from listening to input events on the `window` element by setting the game config boolean property `inputWindowEvents` to `false`. The downside is that Phaser will be unable to tell if the pointer leaves the canvas, so you'll lose some functionality as a result.

**Comment by oduvan** [comment]
Thanks for answer

> The problem is that you don't prevent the click event on the div from going any further. 

I tried. It didn't work. See the second problem I described. The phaser receive the event before the div even though it is under it. (So it is impossible to for me to look in the future)

> There is nothing Phaser can do to prevent this, it's your responsibility to manage any extra DOM elements you created.

It works for Phaser 3.15 without any issue.

> you can prevent Phaser from listening to input events on the window element by setting the game config boolean property inputWindowEvents to false

I've tried this one. Doesn't work, please check the updated example.

https://github.com/oduvan/phaser3-my-examples/blob/master/click_event.html

**Comment by photonstorm** [comment]
It works just fine if you capture and deal with the input event properly: https://jsbin.com/faneper/edit?html,output

![ftaTFPmv0l](https://user-images.githubusercontent.com/164476/66834153-08c68f80-ef55-11e9-8203-cc3b1424a650.gif)

**Comment by oduvan** [comment]
@photonstorm for some reason your example shows a different result on my side.

FF, Mac - https://monosnap.com/file/LjhFZfBhVmiw3eQnGskswdLvGvf4Ea
