### ISSUE TITLE
Can't set the mask of a container in WebGL

### ISSUE THREAD

**Issue by paulsymphony** [photonstorm/phaser#4803]
## Version

* Phaser Version: 3.20.0

* Operating system: MacOS

* Browser: Chrome

## Description

In WebGL, setting the mask of a container has no effect. This is not the case in versions earlier than 3.20.0 (like 3.19.0).

## Example Test Code

var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('pic', 'assets/pics/rick-and-morty-by-sawuinhaff-da64e7y.png');
}

function create ()
{
    var image = this.add.image(400, 300, 'pic');
    var cntr = this.add.container(0,0);
    cntr.add(image);
    var shape = this.make.graphics();
    shape.beginPath();
    shape.fillRect(0,0,100,100);
    var theMask = shape.createGeometryMask();
    cntr.mask = theMask;

    this.input.on('pointermove', function (pointer) {
        shape.x = pointer.x;
        shape.y = pointer.y;

    });
}

## Additional Information

If you force 'CANVAS' with the above code, it works properly.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by paulsymphony** [comment]
Fix confirmed - thank you
