### ISSUE TITLE
Headless game fails to destroy itself

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#4804]
## Version

* Phaser Version: 3.20.0

## Description

When a game is created with the HEADLESS renderer, `game.destroy()` has no effect. The game keeps running.

## Example Test Code

https://codepen.io/samme/pen/QWWNera

## Additional Information

`headlessStep()` is missing the `pendingDestroy` check that `step()` has.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
