### ISSUE TITLE
Body broken for container in scaled container

### ISSUE THREAD

**Issue by nt-pch** [photonstorm/phaser#4806]
* Phaser Version: 3.20.1
* Operating system: Mac 10.13.4

## Description
I resized a Phaser Container to fit the assets on the mobile screen. It is scaled down with container.setScale(0.47). Inside that container is another container which has added to it an Arcade Physics body. The body has its width and height set larger than the default.When I scale it down for mobile, the width and height do not change, they remain at the default size.

I originally built this game for desktop.  The desktop game works perfectly fine without the container scaled.

## Example Test Code
https://codepen.io/nick005/pen/zYYBPqN
If you comment out line 66 you will see that the player's body is now the correct width. But when line 66 is uncommented, the body reverts to the default.

**Comment by samme** [comment]
This can be solved by using [Body#setSize()](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Body.html#setSize) instead.

Maybe [Body#width](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Body.html#width) and Maybe [Body#height](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Body.html#height) should be marked read-only.

**Comment by photonstorm** [comment]
Agreed. I've updated the docs, so `width` and `height` are read-only and link to the `setSize` method.
