### ISSUE TITLE
我遇到了文本自动换行BUG

### ISSUE THREAD

**Issue by iiig** [photonstorm/phaser#4809]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
</html>
<script src="https://cdn.jsdelivr.net/npm/phaser@3.20.1/dist/phaser-arcade-physics.min.js"></script>
<script>
  var game = new Phaser.Game({
    type: Phaser.AUTO,
    scene: {
      create: create
    }
  });

  function create() {
    this.add.text(100, 100, "本次操作 需要1个星星        通过下 面的途径可以获 得星星 哦！自动换行自动换行自动换行", {
      fontFamily: "Arial",
      fontSize: 32,
      color: "#ff0000",
      backgroundColor: "#ffffff",
      wordWrap: {width: 350, useAdvancedWrap: true}
    })
  }
</script>

运行以上代码，请问为什么第一个"星星"文字后面的多个空格没有了？第二个”星星“文字后面为什么又自动换行了？这是bug吗？

**Comment by photonstorm** [comment]
Sorry, but I'm not able to read any languages other than English. Could you please find someone to help translate your issue into English.

**Comment by RollinSafary** [comment]
He mean this :D


<script src="https://cdn.jsdelivr.net/npm/phaser@3.20.1/dist/phaser-arcade-physics.min.js"></script> <script> var game = new Phaser.Game ({ type: Phaser.AUTO, scene: { create: create } });
Function create() {
This.add.text(100, 100, "This operation requires 1 star. You can get the stars through the following path! Automatic line breaks automatically wrap and wrap", {
fontFamily: "Arial",
fontSize: 32,
Color: "#ff0000",
backgroundColor: "#ffffff",
wordWrap: {width: 350, useAdvancedWrap: true}
})
}
</script>

Run the above code, why is there more than one space after the first "star" text? Why did the second "Star" text automatically wrap after the text? Is this a bug?

**Comment by rexrainbow** [comment]
From api of [Text](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Text.html): 
```
useAdvancedWrap: Whether or not to use the advanced wrapping algorithm. If true, spaces are collapsed and whitespace is trimmed from lines. If false, spaces and whitespace are left as is.
```
set `useAdvancedWrap` to `false` might solve this issue.

**Comment by iiig** [comment]
`
<script>
  var game = new Phaser.Game({type: Phaser.AUTO, scene: {create: create}});

  function create() {
    this.add.text(100, 100, "本次操作 需要1个星星       通过下 面    的 途 径可以获 得星星 哦！自动换行自动换行自动换行", {
      fontFamily: "Arial",
      fontSize: 32,
      color: "#ff0000",
      backgroundColor: "#ffffff",
      wordWrap: {width: 450, useAdvancedWrap: false}
    })
  }
</script>
`
![image](https://user-images.githubusercontent.com/12097799/67061014-7ced7700-f191-11e9-9508-42ca72c13cac.png)

Running the above code is not what I want. Why does the text after the second "星星" wrap?

**Comment by iiig** [comment]
`
<script>
  var game = new Phaser.Game({type: Phaser.AUTO, scene: {create: create}});

  function create() {
    this.add.text(100, 100, "本次操作 需要1个星星       通过下 面    的 途 径可以获 得星星 哦！自动换行自动换行自动换行", {
      fontFamily: "Arial",
      fontSize: 32,
      color: "#ff0000",
      backgroundColor: "#ffffff",
      wordWrap: {width: 450, useAdvancedWrap: false}
    })
  }
</script>
`
![image](https://user-images.githubusercontent.com/12097799/67061155-fbe2af80-f191-11e9-8713-0e468af4970e.png)
![image](https://user-images.githubusercontent.com/12097799/67061164-043aea80-f192-11e9-9166-930d4b6155dd.png)

Running the above code is not what I want. Why does the text after the second "星星" wrap?

**Comment by iiig** [comment]
> Sorry, but I'm not able to read any languages other than English. Could you please find someone to help translate your issue into English.

I wrote the English description, please help me to read it when it is convenient, thank you.

**Comment by rexrainbow** [comment]
**Word** wrap is based on space character, content will be spitted into these words:
- '本次操作', 
- '需要1个星星'
- '通过下'
- '面'
- '的'
- '途'
- '径可以获'
- '得星星'
- '哦！自动换行自动换行自动换行'

 '哦！自动换行自动换行自动换行' is a single word, and put into a wrapped new line.

Official text game object does not support *character wrapping* by default, you might assign a custom wrapping  callback to implement character wrap. ([Here](https://labs.phaser.io/edit.html?src=src/game%20objects/text/static/word%20wrap%20by%20callback.js) is an example of using custom wrapping callback). or try [bbcodeText plugin](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/bbcodetext/), which support [character wrapping](https://codepen.io/rexrainbow/pen/MWWjVyg), and more, image texture also could be [drawn on bbcodeText](https://codepen.io/rexrainbow/pen/OZbOyg) with text content.

**Comment by iiig** [comment]
> **Word** wrap is based on space character, content will be spitted into these words:
> 
> * '本次操作',
> * '需要1个星星'
> * '通过下'
> * '面'
> * '的'
> * '途'
> * '径可以获'
> * '得星星'
> * '哦！自动换行自动换行自动换行'
> 
> '哦！自动换行自动换行自动换行' is a single word, and put into a wrapped new line.
> 
> Official text game object does not support _character wrapping_ by default, you might assign a custom wrapping callback to implement character wrap. ([Here](https://labs.phaser.io/edit.html?src=src/game%20objects/text/static/word%20wrap%20by%20callback.js) is an example of using custom wrapping callback). or try [bbcodeText plugin](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/bbcodetext/), which support [character wrapping](https://codepen.io/rexrainbow/pen/MWWjVyg), and more, image texture also could be [drawn with text content](https://codepen.io/rexrainbow/pen/OZbOyg).

I don't think this is reasonable, because it will cause the "星星            通过" space in the middle of the text automatically disappear. The space text in the middle is useful, and I don't want to break lines.

**Comment by iiig** [comment]
> **Word** wrap is based on space character, content will be spitted into these words:
> 
> * '本次操作',
> * '需要1个星星'
> * '通过下'
> * '面'
> * '的'
> * '途'
> * '径可以获'
> * '得星星'
> * '哦！自动换行自动换行自动换行'
> 
> '哦！自动换行自动换行自动换行' is a single word, and put into a wrapped new line.
> 
> Official text game object does not support _character wrapping_ by default, you might assign a custom wrapping callback to implement character wrap. ([Here](https://labs.phaser.io/edit.html?src=src/game%20objects/text/static/word%20wrap%20by%20callback.js) is an example of using custom wrapping callback). or try [bbcodeText plugin](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/bbcodetext/), which support [character wrapping](https://codepen.io/rexrainbow/pen/MWWjVyg), and more, image texture also could be [drawn with text content](https://codepen.io/rexrainbow/pen/OZbOyg).

I don't think this is reasonable, because it will cause the `"星星&nbsp;&nbsp;&nbsp;&nbsp;通过"` space in the middle of the text automatically disappear. The space text in the middle is useful, and I don't want to break lines.

**Comment by rexrainbow** [comment]
Space characters in bbCodeText object will be kept. I modified the [test pen](https://codepen.io/rexrainbow/pen/MWWjVyg), to show content :
```
本次操作 需要1个星星    通过下 面 的 途 径可以获 得星星 哦！自动换行自动换行自动换行
```

Anyway, it is not a bug of official text object, because official text object support word wrap by default.

**Comment by iiig** [comment]
> Space characters in bbCodeText object will be kept. I modified the [test pen](https://codepen.io/rexrainbow/pen/MWWjVyg), to show content :
> 
> ```
> 本次操作 需要1个星星    通过下 面    的 途 径可以获 得星星 哦！自动换行自动换行自动换行
> ```
> 
> Anyway, it is not a bug of official text object, because official text object support word wrap by default.

Thank you for your answer
