### ISSUE TITLE
Rectangle Stroke has a problem

### ISSUE THREAD

**Issue by aolsx** [photonstorm/phaser#4811]
var rect = this.add.rectangle(0, 0, 300, 300, 0x9966ff);
 rect.setStrokeStyle(4, 0xefc53f);
---------------------
rect.setSize(100, 100);
--------------------
But stroke didn't change.

**Comment by rexrainbow** [comment]
Phaser3 uses [`path`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/shape/StrokePathWebGL.js#L32) to stroke edges, but path object is not updated after `setSize(w, h)`. 
Here is a workaround of this bug:
```javascript
var setSize = function(rect, width, height) {
    rect.setSize(width, 100);
    rect.geom.setSize(width, height);
    rect.updateData();
}
``` 
[Demo](https://codepen.io/rexrainbow/pen/xxxrQXm)

**Comment by photonstorm** [comment]
Technically, it shouldn't, as `setSize` doesn't change the display size of a Game Object. However, there are other side-effects of allowing `setSize` on Shapes, for example it makes no sense on a Curve object, and indeed is overwritten if you then call `updateData` with the bounds values! So I think the best solution is to remove the ComputedSize component and merge with the Shape class.

**Comment by amshegarh** [comment]
How should i also update bounds that are used for events? ie it shows correctly but events like pointerdown dont trigger on the new area

**Comment by amshegarh** [comment]
Solved it, add to the function at the bottom
`        rect.input.hitArea.width = width;
        rect.input.hitArea.height = height;`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by alexchandler100** [comment]
I ran into this problem and your solution worked for me! Thanks for putting it here.
