### ISSUE TITLE
SpinePlugin path optimization

### ISSUE THREAD

**Issue by a610569731** [photonstorm/phaser#4813]
## Version
 
* Phaser Version:v3.20.1

## Description
Path cannot load PNG uses root directory

## Example Test Code
this.load.spine('goblin2', 'test/IK.json', 'test/IK.atlas')

## Additional Information
SpinePlugin onFileComplete
onFileComplete: function (file)
    {
        var parentUrl ="";
        var parentIndex = file.src.indexOf("/");
        if(parentIndex != -1){ 
            parentUrl=file.src.substr(0,parentIndex+1);
            var path = GetFastValue(config, 'path', this.path);
            if(parentUrl == path){
                parentUrl="";
            } 
        }
        var index = this.files.indexOf(file);

        if (index !== -1)
        {
            this.pending--;

            if (file.type === 'text')
            {
                //  Inspect the data for the files to now load
                var content = file.data.split('\n');

                //  Extract the textures
                var textures = [];

              
                for (var t = 0,contentLen=content.length; t < contentLen; t++)
                {
                    var line = content[t];

                    if (line.trim() === '' && t < contentLen - 1)
                    {
                        line = content[t + 1];

                        textures.push(line);
                    }
                }

                var config = this.config;
                var loader = this.loader;

                var currentBaseURL = loader.baseURL;
                var currentPath = loader.path;
                var currentPrefix = loader.prefix;

                var baseURL = GetFastValue(config, 'baseURL', this.baseURL);
                var path = GetFastValue(config, 'path', this.path);
                var prefix = GetFastValue(config, 'prefix', this.prefix);
                var textureXhrSettings = GetFastValue(config, 'textureXhrSettings');

                loader.setBaseURL(baseURL);
                loader.setPath(path);
                loader.setPrefix(prefix);

                for (var i = 0,texturesLen=textures.length; i < texturesLen; i++)
                {
                    var textureURL = textures[i];

                    var key = 'SP' + this.multiKeyIndex + '_' + textureURL;

                    var image = new ImageFile(loader, key, parentUrl+textureURL, textureXhrSettings);

                    this.addToMultiFile(image);

                    loader.addFile(image);
                }

                //  Reset the loader settings
                loader.setBaseURL(currentBaseURL);
                loader.setPath(currentPath);
                loader.setPrefix(currentPrefix);
            }
        }
    }

**Comment by a610569731** [comment]
var parentIndex = file.src.lastIndex("/");

**Comment by photonstorm** [comment]
Thanks for opening this issue, but what exactly is this about and what does the code above actually fix?

**Comment by a610569731** [comment]
Use relative path
Load according to the image path in atlas

demo

this.load.setPath('assets/spine/demos/');
this.load.spine('set1', 'demos.json', [ 'atlas1.atlas' ], true);

path optimization ->
this.load.spine('set1', 'assets/spine/demos/demos.json', [ 'assets/spine/demos/atlas1.atlas' ], true);

**Comment by FostUK** [comment]
Does this PR fix it?
Specifically changed to load images to be loaded out of the atlas path.

https://github.com/photonstorm/phaser/pull/4893

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
