### ISSUE TITLE
MultiAtlasFileConfig object takes url instead of atlasURL

### ISSUE THREAD

**Issue by xense** [photonstorm/phaser#4815]
## Version
* Phaser Version: v3.20.1
* Operating system: Windows 7 Ultimate
* Browser: 

## Description

As described in docs and in phaser.d.ts, `MultiAtlasFileConfig` must have an `atlasURL` field, but in fact `MultiAtlasFile` class takes `atlasURL` param from `url` object field
```atlasURL = GetFastValue(config, 'url');```

so config real config object looks like this
## Example Test Code
```
scene.load.multiatlas({
    key: "my_atlas",
    url: "my/atlases/my_atlas.json",
});

```
## Additional Information

I think, that someone already uses `url` key, so it would be better to create an additional alias for this field, corresponding to docs, so we can have backward compatibility.

**Comment by photonstorm** [comment]
It can take either a config object _or_ a string. I've fixed the JSDoc to reflect this.
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
