### ISSUE TITLE
Spine audio playback ability

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#4817]
My game artist told me that now there is audio available in Spine 3.8.34. So in idea we will load sounds with spines and after changing sound path to our sound path spine animation will play it.
Is it possible to implement it in Spine plugin ?

This feature will help us in attaching sounds to our spine animations. So there will be no need to find timings for them.

Thanks in advance.

**Comment by photonstorm** [comment]
This isn't part of the official Spine runtimes yet (https://github.com/EsotericSoftware/spine-runtimes/tree/3.8/spine-ts) - it can't be added to the Phaser plugin until it surfaces there. I'll keep an eye on it. For now, you'll have to figure out another way around it (maybe using events)
