### ISSUE TITLE
Phaser does not support event flows?

### ISSUE THREAD

**Issue by iiig** [photonstorm/phaser#4819]
`<script src="https://cdn.jsdelivr.net/npm/phaser@3.20.1/dist/phaser-arcade-physics.min.js"></script>
<script>
  var game = new Phaser.Game({
    type: Phaser.AUTO,
    transparent: true,
    backgroundColor: 0x1099bb,
    scene: {
      create: create
    }
  });

  function create() {
    let layer1 = this.add.container(0, 0)
    layer1.setInteractive({
      hitArea: new Phaser.Geom.Rectangle(0, 0, 100, 100),
      hitAreaCallback: Phaser.Geom.Rectangle.Contains,
      cursor: "pointer",
      useHandCursor: false
    })
    layer1.on('pointerup', () => {
      console.log('layer1 pointerup')
    })

    let rect2 = this.add.graphics().fillStyle(0xffff00, 1).fillRect(0, 0, 80, 80)
    layer1.add(rect2)
    rect2.setInteractive(new Phaser.Geom.Rectangle(0, 0, 80, 80), Phaser.Geom.Rectangle.Contains);
    rect2.on('pointerup', () => {
      console.log('rect2 pointerup')
    })

    let rect = this.add.graphics().fillStyle(0xff0000, 1).fillRect(0, 0, 50, 50)
    rect.setInteractive(new Phaser.Geom.Rectangle(0, 0, 50, 50), Phaser.Geom.Rectangle.Contains);
    rect.on('pointerup', () => {
      console.log('rect pointerup')
    })
    layer1.add(rect)
  }
</script>`

![2985B797-9FDC-4067-A6C1-9F262117E03C](https://user-images.githubusercontent.com/12097799/67386160-06081200-f5c7-11e9-938b-7ac9809ebe9d.png)

### Why does clicking rect, rect2, layer1 object not execute? Doesn't Phaser support event flows?

**Comment by rexrainbow** [comment]
rect, and rect2 game object are placed overlapping, touch events on overlapping game objects will only be fired for top-most game object. Disable this feature by 
```javascript
scene.input.setTopOnly(false);
```

**Comment by iiig** [comment]
> rect, and rect2 game object are placed overlapping, touch events on overlapping game objects will only be fired for top-most game object. Disable this feature by
> 
> ```js
> scene.input.setTopOnly(false);
> ```

thanks
