### ISSUE TITLE
No 'destroy' event fired in video game object

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4821]
## Version

* Phaser Version: 3.20.1

## Description

The [`destroy`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/video/Video.js#L1722) method of new Video game object is not consistent with [destroy method  of other game objects](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/GameObject.js#L564), which does not fire `destroy` event, neither other clean-up actions.
Might this `destroy` method be renamed to `preDestroy`? like [preDestroy in sprite game object](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/sprite/Sprite.js#L163).

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
