### ISSUE TITLE
createCallBack on physics.group not working

### ISSUE THREAD

**Issue by scrubperson** [photonstorm/phaser#4822]
This doesnt work:
```
enemyGroup = this.physics.add.group({
        defaultKey: 'enemy',
        maxSize: 5,
        createCallback: function(enemy){
            enemy.setData('health',3);
            console.log(enemy.getData(health));
        },
    });
```
but changing `this.physics.add.group` to `this.add.group` does

**Comment by samme** [comment]
#4657

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
