### ISSUE TITLE
Issue of POINTER_UP_OUTSIDE event

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4824]
## Version

* Phaser Version: 3.20.1

* Operating system: window

* Browser: chrome

## Description

[Example Test Code](https://codepen.io/rexrainbow/pen/eYYWPBv)

![圖片](https://user-images.githubusercontent.com/817962/67547139-cc531a80-f730-11e9-8c91-0efe92607528.png)

In **firefox**, pointer-up at 1 and 2 both could fire `POINTER_UP_OUTSIDE` event.
In **chrome**, pointer-up at 1 could fire `POINTER_UP_OUTSIDE` event, but pointer-up at 2 couldn't.

**Comment by photonstorm** [comment]
I assume because it's outside of the iframe. I'm not entirely sure I'm worried about this unless it's a really trivial fix.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
