### ISSUE TITLE
Fix the docs - CHANGE_DATA_KEY_EVENT is not passing 'key' argument to listeners

### ISSUE THREAD

**Issue by dranitski** [photonstorm/phaser#4825]
[In docs we can read that CHANGE_DATA_KEY_EVENT](https://github.com/photonstorm/phaser/blob/v3.20.0/src/data/events/CHANGE_DATA_KEY_EVENT.js) calls listener with **parent, key, value, previousValue** args. But in fact in is not passing the 'key' argument, only '**parent, value, previousValue**'

you can easily reproduce it in existing example:
https://labs.phaser.io/edit.html?src=src/components/data/change%20data%20event.js

![image](https://user-images.githubusercontent.com/27373393/67574610-6f149480-f743-11e9-80c1-dcac5b935af7.png)

**Comment by shainmock** [comment]
thanks alot specialy for you example
[medium growth](https://www.avecinashimi.com/%d8%ae%d8%b1%db%8c%d8%af-%d9%85%d8%ad%db%8c%d8%b7-%da%a9%d8%b4%d8%aa/)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
