### ISSUE TITLE
Unable to load video file as data URI

### ISSUE THREAD

**Issue by apasov** [photonstorm/phaser#4830]
## Version

* Phaser Version: 3.20.1

* Operating system: Windows 10

* Browser: Chrome

## Description

When I try to load a video file as base64 encoded data URI using this code:
```javascript
const dataUrl = 'data:video/mp4;base64,AAAAGGZ0eXBtcDQyAAAAAGlzb........Qo='
this.load.video('videofile', dataUrl, 'loadeddata', false, true)
this.load.start()
```
loader tries to load /videofile. instead of data URI

![image](https://user-images.githubusercontent.com/28765662/67781846-a13e3300-fa70-11e9-9464-56817fab4bab.png)

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.

**Comment by photonstorm** [comment]
This was actually correct behavior, as none of the file types support data URIs (the thought of base64 encoding videos is horrendous imho) - however, it doesn't hurt to allow this, so I merged your PR anyway.

**Comment by apasov** [comment]
Thanks for merging! However horrendous, sometimes (as in my case) it can be extremely useful to base64 encode all game assets, including videos.

**Comment by photonstorm** [comment]
I'm certainly aware there are situations when it's a technical requirement, such as for banner ad games / playables, where everything needs to be in a single html file (with no external files), but aside from this, I'm struggling to think of a valid reason for ever actually doing it - at least not one that makes-up for the extra drain in network / cpu and device memory that base64 imposes.

**Comment by apasov** [comment]
Yes, my situation is that I store all assets in a single html or xml file. 
Maybe I should consider storing them separately as standalone files, but the current solution when everything is in one file is much more convenient for my purposes.
Do you know the exact percentage of the extra drain in cpu and device memory that base64 imposes?
Network overhead is practically 0%, because html and xml files are transferred gzipped. I tested a short video file with gzip compression level = 6:
video.mp4 - 5,107,877 Bytes
video.base64.txt - 6,870,526 Bytes
video.base64.txt.gz - 5,151,768 Bytes
