### ISSUE TITLE
Failed to create a RenderTexture when using a large height number

### ISSUE THREAD

**Issue by chaoyang805** [photonstorm/phaser#4832]
## Version

* Phaser Version: v3.20.1

* Operating system: macOS, Debian

* Browser: chrome v78

## Description

I am creating a RenderTexture on a game scene using `this.add.renderTexture(0, 0, width, height)`, but when the `height` of renderTexture gets bigger, WEBGL reports an error in console.

![image](https://user-images.githubusercontent.com/11256895/67831828-8a541b00-fb1a-11e9-83c5-ad6533508d32.png)

This height value seems related to n*1024, that means when height=8192 is fine, but 8193 it crashs. Sometimes setting to 4097 it also crashs. 

I have set some breakpoints and figured out that the crash was happened here: [WebGLRenderer.js#createFrameBuffer](https://github.com/photonstorm/phaser/blob/c25331cf30373d685ba59afef7520486d9212e01/src/renderer/webgl/WebGLRenderer.js#L1582), but I don't know why.
**Is there a way to fix this? Or I just can't use a texture this big?**

## Example Test Code

example code was edited from [https://labs.phaser.io/edit.html?src=src\camera\follow%20zoom.js](https://labs.phaser.io/edit.html?src=src\camera\follow%20zoom.js)
```javascript

var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    pixelArt: true,
    physics: {
        default: 'arcade',
    },
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var ship;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('map', 'assets/tests/camera/earthbound-scarab.png');
    this.load.image('ship', 'assets/sprites/fmship.png');
}

function create ()
{
    this.cameras.main.setBounds(0, 0, 1024, 2048);
    
    this.add.image(0, 0, 'map').setOrigin(0).setScrollFactor(1);

    cursors = this.input.keyboard.createCursorKeys();

    ship = this.physics.add.image(400.5, 301.3, 'ship');

    // create a renderTexture with a very big height and add to the scene
    // this height seems related to n*1024, it crashes on my Macbook's chrome when height=16385, 
    // and crashes on another Debian OS computer's chrome when height=8193
    let height = 8193
    const texture = this.add.renderTexture(0, 0, 100, height)
    texture.fill(0xff0000)
}


function update ()
{

}


```

**Comment by photonstorm** [comment]
Render Textures are just standard WebGL Textures, so are under the same restrictions internally. The maximum size is based on a combination of the width and height and is determined by your gpu. Gaming grade GPUs can handle bigger textures than mobile or integrated, for example. Essentially, you’ve hit the max on your specific system.

**Comment by chaoyang805** [comment]
> Render Textures are just standard WebGL Textures, so are under the same restrictions internally. The maximum size is based on a combination of the width and height and is determined by your gpu. Gaming grade GPUs can handle bigger textures than mobile or integrated, for example. Essentially, you’ve hit the max on your specific system.

In my understanding, maximum size means maximum width*height. But even if I set a very small value of width, for example width=1 along with a large height, it will crash as well. Or maximum size only constraints one dimension?

**Comment by photonstorm** [comment]
Whenever you get the `width or height out of range` error from WebGL, you've exceeded what your browser / GPU combination supports.

https://webglstats.com/webgl/parameter/MAX_RENDERBUFFER_SIZE

**Comment by chaoyang805** [comment]
Ok, I understand now, thank you!

**Comment by photonstorm** [comment]
Closing this off as it's a WebGL + hardware limitation.
