### ISSUE TITLE
Phaser.GameObjects.Text stroke and shadow

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#4834]
## Version

* Phaser Version: 3.2.0

* Operating system: Windows 10

* Browser: Chrome

## Description

Shadow covers stroke.

## Example Test Code

```
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    backgroundColor: 0xbdbdbd,
    scene: {
        create: create,
    }
};

var game = new Phaser.Game(config);

function create() 
{
    var text1 = this.add.text(20, 50, "Shadow Stroke", { fontFamily: "Arial Black", fontSize: 74, color: "#c51b7d" });
    text1.setStroke('#de77ae', 16);
    text1.setShadow(-15, 0, '#fff', 1)
}

```

## Additional Information

![image](https://user-images.githubusercontent.com/30594036/67942539-7f1fee80-fbf1-11e9-9ca3-f0de1a15e0ef.png)

text color yellow
stroke color black
shadow color brown

**Comment by photonstorm** [comment]
Please look at the arguments for `setShadow` - you can control what the shadow is applied to: the stroke, the fill, or nothing. To fix your example: `setShadow(-15, 0, '#fff', 1, true, false)`.
