### ISSUE TITLE
Can't pause animation after set play("other_anim").

### ISSUE THREAD

**Issue by murteira** [photonstorm/phaser#4835]
## Version
* Phaser Version: Phaser v3.20.1
* Operating system: Mac Catalina
* Browser: Safari

## Description

After I set a new animation to a sprite, the pause() stop working.

## Example Test Code

//first anim
this.fChildren.anims.play("child_front",true);

this.fChildren.setInteractive();
this.fChildren.on("pointerup", function(){
    if(this.fChildren.anims.isPlaying){
        this.fChildren.anims.pause();	
    }else{
        //secondanim
        this.fChildren.anims.play("child_right");
    }
},this);

**Comment by hacktivista** [comment]
I can confirm this bug. If I do `thingToAnimate.anims.isPlaying = false;` it works though

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
