### ISSUE TITLE
Text in a container and the conatiner not stays over sprite,even with conatiner.depth great than sprite.depth

### ISSUE THREAD

**Issue by cpusam** [photonstorm/phaser#4839]
## Version

* Phaser Version: 3.18.0

* Operating system: XUbuntu 18.04

* Browser: Chrome 73.0.3683.103 (official) 64 bits

## Description
If I put a text inside a container and set the text or the container depth in a value great than any sprite.depth, the text on the container shown at the screen stays under the sprite.

## Example Test Code
-Just add a sprite
-create a container
-create a text and add it to the container
-set the positions of sprite and text to overlap
-now set the depth of the container or the text to stays over the sprite
-the text and container will appears over the sprite, but afetr some milliseconds, the text will jump to under the sprite. This happens verry quickly.

**Comment by rexrainbow** [comment]
[Render order of child game objects](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/container/ContainerWebGLRenderer.js#L25) in a container are not followed up with depth property. Try [these methods](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/container/#order-of-child) to reorder child game objects.

**Comment by cpusam** [comment]
@rexrainbow thanks for the info, so, why the children of a container stays with depth equals to teh parent? Is this not to obvious to do? Or it's complexy to make that? I will use the methods of container, but it's not to "beautiful" solution.

**Comment by cpusam** [comment]
@rexrainbow man, that methods not work here. I tried container.moveTo(child, index) and container.bringToTop() and even the sprite that is not inside container, stays over the container.

I want the container with all childs go up over the sprite, but I only can do this if I not use any container, or just the text object as not child of any container. Is this really possible?

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/wvvpmzR) is a test of using `bringToTop` method to change render order. You could change the top child in this test code to see the render result.

**Comment by cpusam** [comment]
ok man, thanks for your help, but, I give up.
I will make my own way of set child by a Point.
Container is horrible way.
NOTE: yes, I used container.bringToTop(text) and nothing changed.

Thanks for your patience with me.
