### ISSUE TITLE
Zoomed camera view when following an object is off by a large margin

### ISSUE THREAD

**Issue by spoike** [photonstorm/phaser#4841]
## Version

* Phaser Version: Tested on 3.17 and 3.20.1 (CodePen example uses 3.0)

* Operating system: macOS Mojave 10.14.6

* Browser: Chrome, don't think it is specific to that

## Description

When setting zoom or using `zoomTo`, the camera view port does not center on the object it is following with `startFollow` and using default values.

## Example Test Code

Here is a CodePen demonstrating the issue: https://codepen.io/spoike/pen/LYYerBN

I forked a previous Phaser 3 codepen and other than tweaking the viewport size I added the following:

```
this.cameras.main.startFollow(logo)
this.cameras.main.setZoom(2.0)
```

You can see that the camera doesn't keep the logo at the center of the viewport. If the zoom is set to 1.0 it does.

## Additional Information

Origin/anchors appear to be right. I've tried following several different types of GameObjects (Container, Sprite, Zone) but the behaviour is unfortunately the same.

This might be a duplicate of https://github.com/photonstorm/phaser/issues/4464 that doesn't have any repro or demo.

On my own project I'm using `startFollow` with no offset and no actual lerp being performed as in docs, with the same result:

```
this.cameras.main.startFollow(this.followObject, false, 1, 1, 0, 0);
```

**Comment by samme** [comment]
It seems to be working as expected in <http://labs.phaser.io/view.html?src=src/camera/follow%20zoom.js&v=3.20.1>.

**Comment by spoike** [comment]
I changed to 3.20.1 in the code pen and it seems to be working

**Comment by spoike** [comment]
So I found out on my code base that I did a `.setRenderToTexture(pipeline)`... when I removed this call, it worked.

Not sure why adding a render pipeline to the camera object would offset the whole thing.

**Comment by vinerz** [comment]
@spoike I remember having the same issue applying pixelation pipeline from Rex. Ended up giving up on zoom since the pipeline was more important at the time.

**Comment by photonstorm** [comment]
Am happy to leave this as-is for 3.x as it works properly outside of rendering to a texture.
