### ISSUE TITLE
SpinePlugin: ignoreIfPlaying is broken for multiple tracks

### ISSUE THREAD

**Issue by vinerz** [photonstorm/phaser#4842]
## Version
* Phaser Version: 3.20.2

## Description

The `ignoreIfPlaying` flag does not consider the `trackIndex` being applied to.
It is hardcoded as `trackIndex` 0, thus failing if the check is being applied to other tracks.

https://github.com/photonstorm/phaser/blob/c25331cf30373d685ba59afef7520486d9212e01/plugins/spine/src/gameobject/SpineGameObject.js#L1003

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
