### ISSUE TITLE
Typescript definitions: TS2339: Property 'bodies' does not exist on type 'World'.

### ISSUE THREAD

**Issue by klase** [photonstorm/phaser#4844]
## Version
* Phaser Version: 3.20.1

## Description

When trying to reference ```matter.world.localWorld.bodies``` typescript throws an error

**Comment by SerhiiBilyk** [comment]
@klase Could you please provide some example ?

**Comment by photonstorm** [comment]
@klase try this - edit `phaser/types/matter.d.ts` and change:

```
export = Matter;
export as namespace Matter;
```

to

```
export = MatterJS;
export as namespace MatterJS;
```

as that is what Phaser uses when referencing Matter objects, so I think it may help.

**Comment by klase** [comment]
No luck I'm afraid, just results in more TS errors for any matter bodies.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
