### ISSUE TITLE
Touch Events Stop Working During HTML Video Playback on Mobile Devices

### ISSUE THREAD

**Issue by BobtheUltimateProgrammer** [photonstorm/phaser#4846]
## Version

* Phaser Version: 3.20

* Operating system: iOS 12.1

* Browser: Mobile Safari

## Description

On iOS devices, as you could see from the code below, I have added using JS a HTML Video element as a tutorial video before the game and then after the video ends, it should automatically switch to another scene for the game.
However after the user hits play on the video, the game seems to freeze. Only the video works. No touch events or other interactions work. However this works perfectly on desktop devices. Any ideas?

## Example Test Code
<b> A live example is at https://jsfiddle.net/ja4g1b6k/1/. </b>
```javascript
 this.video = document.createElement('video');
 this.video.src = "assets/video.mp4";
 this.video.style.position = 'absolute';
 this.video.style.left = "75px";
 this.video.style.top = "50px";
 this.video.width = 650;
 this.video.height = 550;
 this.video.controls = true;
 this.video.addEventListener("ended", function() {
     this.video.pause();
     document.body.removeChild(this.video);
     bgMusic.setVolume(1);
     if (launch == 1) {
         this.scene.start('Game');
     } else {
         this.scene.start('About');
     }
 }.bind(this));
 bgMusic.setVolume(0.3);
 document.body.appendChild(this.video);
 this.video.play();
```

**Comment by ermite1408** [comment]
It's working for me:
// I detect mobile devices because the PC version is breaking
`if (isMobile) this.input.manager.touch.capture = false;`

**Comment by RollinSafary** [comment]
Have you tried to trigger focus on your game's canvas after showing video ?

**Comment by BobtheUltimateProgrammer** [comment]
How do you trigger focus on the game's canvas after showing video?

**Comment by BobtheUltimateProgrammer** [comment]
I figured it out.
Just added to my game config:
```
input: {
	windowEvents: false
}
```
https://jsfiddle.net/yqw92krm/
