### ISSUE TITLE
createGeometryMask on Polygon game object not working in WebGL

### ISSUE THREAD

**Issue by klase** [photonstorm/phaser#4848]
## Version
* Phaser Version: 3.20.1
* Chrome 77.0.3865.90 on macOS Mojave 10.14.6

## Description
When trying to create a mask using createGeometryMask on a polygon game object the resulting geometry mask is undefined.
```
GeometryMask {geometryMask: undefined, invertAlpha: false, isStencil: true, level: 0}
geometryMask: undefined
invertAlpha: false
isStencil: true
level: 0
```

## Example Test Code
https://codesandbox.io/s/silly-shaw-f00n0

**Comment by photonstorm** [comment]
As per the method signature,`createGeometryMask` requires a Graphics object to work from, and none has been provided in the example, so it creates an empty mask.
