### ISSUE TITLE
Unable to update matterjs body sprite offset

### ISSUE THREAD

**Issue by klase** [photonstorm/phaser#4855]
## Version
* Phaser Version: 3.20.1
* Operating system: macOS Catalina 10.15

## Description
I need to update the x and y offset of the sprite on a generated matterjs body based on the center of mass (i.e after it has been created since I don't know the values at spawn time), however when setting body.render.sprite.xOffset nothing happens. The only way I can make the offset apply is to pass it as an option to matter.add.sprite, but at that point I don't know the center of mass yet.

## Example Test Code
https://codesandbox.io/s/agitated-https-cuzc2

**Comment by hexus** [comment]
Possibly related to #3282.

**Comment by photonstorm** [comment]
The `render.sprite` offsets are not used at render time, only when setting the Game Object's origin. Matter Bodies now have a new property `centerOfMass` which stores their com post-creation (or part setting).

They also have a new property `centerOffset` which can be used in conjunction with their texture frame size to set the origin, i.e.: `this.setOrigin(rx + (cx / this.displayWidth), ry + (cy / this.displayHeight));` (where rx and ry are the render offsets and cx and cy are the center offsets)

Origin can be changed at any time, of course, so as long as you allow for the center of mass when doing so, this could easily be post-Body creation. You'll find all the above changes in the 3.22 release.
