### ISSUE TITLE
Please split phaser.d.ts into multiple files

### ISSUE THREAD

**Issue by JasonHK** [photonstorm/phaser#4856]
**We're constantly trying to make Phaser 3 better**

Don't you think that a single TypeScript definition file is just too difficult to manage? Using multiple definition files will be easier to find the missing definitions. Also, I suggest you referencing the definition of Matter.js instead of cloning it directly.

**[Optional] Do you want to help provide this feature?**

Yes! I can help you in converting the definition by submitting pull requests.

**Comment by photonstorm** [comment]
The definitions file is automatically generated from our JSDocs, so no, it's not hard to manage for us at all. It's created every time we produce a new build. If something is missing in the defs then it means it is missing from the JSDocs too, so any PRs need to address those directly and the defs will automatically be fixed as a result.

**Comment by JasonHK** [comment]
> The definitions file is automatically generated from our JSDocs, so no, it's not hard to manage for us at all. It's created every time we produce a new build. If something is missing in the defs then it means it is missing from the JSDocs too, so any PRs need to address those directly and the defs will automatically be fixed as a result.

But your method cannot utilize the full potential of TypeScript. Please take a look at the example below:

```typescript
namespace Phaser
{
    namespace Input.Keyboard
    {
        class KeyboardPlugin
        {
            addKeys<R extends Record<string, number>>(keys: R, enableCapture?: boolean, emitOnRepeat?: boolean): Phaser.Types.Input.Keyboard.KeysRecord<Extract<keyof R, string>>;
            addKeys(keys: string, enableCapture?: boolean, emitOnRepeat?: boolean): Phaser.Types.Input.Keyboard.KeysRecord<string>;
        }
    }

    namespace Types.Input.Keyboard
    {
        type KeysRecord<Keys extends string> = { [Key in Keys]: Phaser.Input.Keyboard.Key };
    }
}
```

With the modification above, it enables better type definitions for:

1. Enforce the type of `keys` parameter, allow it to be either `string`, or `object` with `number` value only.
2. Enforce the return type to be `object` with `Phaser.Input.Keyboard.Key` value only.
3. If `keys` parameter is `object` with `number` value, enforce to only use the keys of the return `object` with the keys defined in the `object` of `keys` parameter. `// Broken English`

**Comment by samme** [comment]
(1) and (2) can be done by modifying the JSDocs.

**Comment by JasonHK** [comment]
> (1) and (2) can be done by modifying the JSDocs.

This is just one of many examples. Like there are still no type definitions for the objects that extended the `EventEmitter` class. Some methods that should return a `this` doesn't return a `this` but a `Phaser.Events.EventEmitter`. And `Physics.Matter.Factory.gameObject` should return the input Game Object with `Phaser.Physics.Matter.Components.*` instead of a `Phaser.GameObjects.GameObject`

To get worse, I've to do this to make the compiler not to complain because your type definitions for Matter.js are empty.

```typescript
import MatterJS from "matter-js";
import Phaser from "phaser";

export class ControllableMinecart
{
    private _player: Phaser.Physics.Matter.Image;

    constructor(scene: Phaser.Scene)
    {
        ...
        (scene.matter.body as typeof MatterJS.Body).setInertia(this._player.body as MatterJS.Body, Infinity);
    }
}
```

Using `as` is really bad in TypeScript you know.

**Comment by samme** [comment]
Make a PR and fix those, then.

Phaser 4 will be 100% TypeScript but for Phaser 3 we have to write accurate JSDocs.

**Comment by JasonHK** [comment]
> Make a PR and fix those, then.

Sure, but the problem is I'm not familiar with the syntax of JSDoc, especially their generic syntax.

> Phaser 4 will be 100% TypeScript but for Phaser 3 we have to write accurate JSDocs.

That's great! Then I don't have to worry about the above problem I've mentioned above. Do you have the estimate release date of Phaser 4?

**Comment by photonstorm** [comment]
I'm going to close this issue off, as it's not about a specific thing that can be actioned, but rather a general feature request. For Phaser 3, if the TS defs need to be improved, those changes have to be made at the JSDoc level. For Phaser 4, we're coding entirely in TypeScript anyway. There is no ETA for release, however.
