### ISSUE TITLE
Low image quality after resize

### ISSUE THREAD

**Issue by ermite1408** [photonstorm/phaser#4857]
## Version

* Phaser Version: 3.20.1

* Operating system: Windows 10

* Browser: Chrome

## Description

I can't find a way to not loose quality when I resize my images. I tried different variants: setDisplaySize or setScale on image and setZoom on camera, but image look pixelated.

In game config I changed "type" to WebGl/Canvas, sets to render object params: antialias, pixelArt, roundPixels.

My game config:
```
{
    type: Phaser.AUTO,
    disableContextMenu: true,
    scale: {
        height,
        width,
        parent: 'canvas',
        mode: Phaser.Scale.NONE,
        autoRound: true,
    },
    render: {
        roundPixels: true,
    },
}
```

## Additional Information

Example:
![Example](https://user-images.githubusercontent.com/57718126/68774348-09c70b80-063e-11ea-9263-fe270ebf5d1d.PNG)

1. resize image in html
2. resize image by setScale
3. setZoom on camera

**Comment by RollinSafary** [comment]
Have you tried this without option `roundPixels: true` ?

**Comment by ermite1408** [comment]
> Have you tried this without option `roundPixels: true` ?

yes

**Comment by photonstorm** [comment]
Mipmap filter levels are now in v3.21 in the master branch. You can also find examples in the labs (here: http://labs.phaser.io/view.html?src=src%5Ctextures%5Cset%20mipmap%20filter.js&v=dev)

Note that as per WebGL1 limitations, they only work with power-of-two sized base textures.

This is the only way to improve on the quality of scaled textures in WebGL.
