### ISSUE TITLE
Add Num+ and Num- to key events

### ISSUE THREAD

**Issue by Martin-Antonov** [photonstorm/phaser#4861]
Hey Phaser 3 team,

I have noticed that Numpad+ and Numpad- keys are missing from Phaser 3. I am not sure, but maybe adding them to this class here would be sufficient:

https://github.com/photonstorm/phaser/blob/v3.20.0/src/input/keyboard/keys/KeyCodes.js

The reason is that I would like to override ctrl + Num+ and Num- for a zooming functionality of a mathematical software. 

Thanks :)

**Comment by photonstorm** [comment]
I've added them in and they'll be part of the 3.21 release.

For any other missing keys, you can just specify the keycode yourself when creating a Key object. You can get a list of keycodes from here: https://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes
