### ISSUE TITLE
crop shape

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#4866]
**Crop shapes**
As we know we have `setCrop` function on some game objects like `Phaser.GameObjects.Image` or `Phaser.GameObjects.RenderTexture`. But this function crops just rectangle shape.
Is it possible to make `setCrop` function to have shape argument and crop the texture with that shape.  I think that main geometry shapes (circle, triangle, polygon, rounded rectangle) support will be great.

I'm now trying to optimize rendering in my game and need to remove masks from players' avatars (circle shapes). And feature like this could be very helpful.

Thanks in advance.
**[Optional] Do you want to help provide this feature?**
 Yes.

**Comment by photonstorm** [comment]
Sorry, this isn't possible. All crop does is modify the UV coordinates for the texture, which is a rectangle. You have to use a mask for a non-rectangular shapes.
