### ISSUE TITLE
Word wrap adds space if the last line is only one word long.

### ISSUE THREAD

**Issue by gaamoo** [photonstorm/phaser#4867]
## Version

* Phaser Version: 3.20.1

* Operating system: Windows 10

* Browser:

## Description

Basic wordwrap adds a space to the end of the last line if the last line is only one word long.

Expected behaviour: no space is added.

## Example Test Code

From https://github.com/photonstorm/phaser/blob/v3.20.0/src/gameobjects/text/static/Text.js#L531:

    result += words[j] + ' ';

## Additional Information

Simple fix, replace with this:

    result += words[j];
                    
    if (j < (words.length - 1))
        {
            result += ' ';
        }

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
