### ISSUE TITLE
How does phaser 3 set the spine animation base point?

### ISSUE THREAD

**Issue by sbfkcel** [photonstorm/phaser#4869]
In Spine animation, the base point of the animation is inconsistent with Phaser. Causes Spine to have a deviation in the position in the scene.
How to solve it? There is no `origin` attribute or setting method in `SpineGameObject`.

---
**code：**

```javascript
preload(){
    this.load.setPath('app/assets/spine/');
    this.load.spine('test', 'raptor-pro.json', ['raptor-pro.atlas'], true);
    this.load.spine('demon', 'demon.json', ['demon.atlas'], true);
}
create(){
    let scale = 0.2,
        test = this.add.spine(200, 400, 'test', 'walk', true).setScale(scale);
    test.width *= scale;
    test.height *= scale;

    this.matter.add.rectangle(200, 500, 300, 30, { isStatic: true });
    this.matter.add.gameObject(test);
}
```

**spine：**
![image](https://user-images.githubusercontent.com/5469785/69127739-cc52fa00-0ae5-11ea-9032-bd7eca9bf965.png)

**Preview：**
![image](https://user-images.githubusercontent.com/5469785/69128201-c7db1100-0ae6-11ea-82e1-f58162db7fcd.png)

**Comment by RollinSafary** [comment]
Default origin is on x and y rays intersection point

**Comment by RollinSafary** [comment]
It's not a good idea to use `gameobject.width = something`. Try ti use `setSize`

**Comment by sbfkcel** [comment]
No change

**Comment by sbfkcel** [comment]
Modify `boot.y` to solve it.

**Comment by photonstorm** [comment]
Whatever you set as the x/y coordinate for the Spine Game Object gets set as the Spine Skeleton x/y values - the origin of those x/y values are defined in the Spine editor (the intersection of the cross-hairs in your screenshot).

Changing the `width` and `height` properties is not how you scale objects, especially not Spine objects. Use `setScale`. The Spine runtime will then pass that scale to the skeleton directly.
