### ISSUE TITLE
DOM gameObject visible when scene is sleeping

### ISSUE THREAD

**Issue by peonmodel** [photonstorm/phaser#4870]
## Version
V3.20.0
Mac 10.14.6 
## Description

When a scene is slept, the non-DOM game object is no longer visible, but the DOM game object remains visible
the setVisible function also doesnt seemed to work

## Example Test Code

```
export class MapInterface extends Phaser.Scene {
constructor() {
super({ key: 'MapInterface' });
}
create(){
document.test = this
this.add.text(0,0,'normal text');
this.add.dom(10,10,'div',{}, 'dom text');
}    
}
// render scene
// normal text is visible
// dom text is visible

// in console
document.test.scene.sleep();
// normal text is not visible
// dom text is visible (should not be)
```

## Additional Information

Current workaround is to destroy and recreate each time scene is slept/woke

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
