### ISSUE TITLE
Phaser.Utils.Array.Replace documentation error

### ISSUE THREAD

**Issue by ghclark2** [photonstorm/phaser#4871]
Phaser.Utils.Array.Replace documentation is missing the array argument - code below

 * @function Phaser.Utils.Array.Replace
 * @since 3.4.0
 *
/////////SHOULD BE ARRAY parameter here//////////////////////////////////////
 * @param {*} oldChild - The element in the array that will be replaced.
 * @param {*} newChild - The element to be inserted into the array at the position of `oldChild`.
 *
 * @return {boolean} Returns true if the oldChild was successfully replaced, otherwise returns false.
 */
var Replace = function (array, oldChild, newChild)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
