### ISSUE TITLE
Destroy texture when game.destroy()

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#4876]
## Version

* Phaser Version: 3.21.0

* Operating system:

* Browser:

## Description

[Here](https://codepen.io/rexrainbow/pen/MWWRPap) is a test code.
- pointer-down to run `game.destroy()`
- See the error message in console `TypeError: this.manager is null`.

It seems that texture manager will be destroyed first, then destroying game objects (and [extra texture](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/rendertexture/RenderTexture.js#L1219)),

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
