### ISSUE TITLE
Can't mute/unmute on iOS (any browser)

### ISSUE THREAD

**Issue by alexandernst** [photonstorm/phaser#4878]
## Version

* Phaser Version: 3.21.0-FB

* Operating system: iOS

* Browser: All browsers

## Description

It's impossible to unmute the sounds once muted. 

## Example Test Code

```
create() {
        this.sound = this.add.text(0, 0, "");
        this.sound.setInteractive({
            useHandCursor: true
        });

        this.input.on("gameobjectup", (pointer, button) => {
            switch (button) {
                case this.sound:
                    this.game.sound.mute = !this.game.sound.mute;
                    break;
            }
        });
}

update() {
        if (this.game.sound.mute) {
            this.sound.setText("sound off");
        } else {
            this.sound.setText("sound on");
        }
}
```

## Additional Information

This code will work as expected on Android / Windows / Linux / Mac (even Safari on Mac OS), but it won't work as expected on iOS (all browsers).

What happens in iOS:

1. The text is set to "sound on"
2. I click on the text
3. The text doesn't get changed, but the sound gets muted
4. No matter how many times I click on the text, the sound remains muted, and the text remains displaying "sound on".

What happens in any other OS:

1. The text is set to "sound on"
2. I click on the text
3. The text gets changed to "sound off" (and the sound is muted)
4. If I click again (and again and again and again) the text keeps changing and sound is toggled between muted and unmuted (as expected).

**Comment by scott20145** [comment]
hmm... It works fine at version: `3.19.0`. Tested on iOS chrome

**Comment by alexandernst** [comment]
I just tested on 3.19.0 on Chrome iOS and I keep getting the buggy behaviour.

**Comment by alexandernst** [comment]
@scott20145 are you able to repro the bug in 3.19.0 on Safari iOS?

**Comment by photonstorm** [comment]
Tested in 3.54.0 and working fine (likely before, but definitely now!)
