### ISSUE TITLE
Option for showing a constraint without showing debug graphics

### ISSUE THREAD

**Issue by roberto257** [photonstorm/phaser#4880]
I have a game where I use the Matter js constraint to have a player swing on ropes. The only simple way to show this currently is to turn on debug, which obviously turns on debug for everything else. I just think it'd be nice and simple if there was a way to make a constraint visible when debug is off :)

**Comment by rexrainbow** [comment]
There are [some parameters](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/matterjs-world/#configuration) like `debugShowBody`, `debugShowStaticBody`. ... Turn them off by adding `debugShowBody: false`, `debugShowStaticBody: false` into game config.

**Comment by roberto257** [comment]
Is there an example for this? I can't seem to get this to work either

**Comment by rexrainbow** [comment]
@roberto257  You are right. 
[Here](https://github.com/photonstorm/phaser/blob/master/src/physics/matter-js/World.js#L205-L220) is the possible parameters of debug graphics, but some of them don't work. Like `debugShowBody`, `debugShowStaticBody`, which could not be found in code base.

**Comment by photonstorm** [comment]
I have recently rewritten how Matter Debug is handled. There are _lots_ of new options and I've exposed the API, so you can render bodies, constraints or convex hulls to your own Graphics object, regardless of if debugging is even enabled or not. Check out the Change Log for full details of the update.

**Comment by roberto257** [comment]
@photonstorm thank you sir. Your hard work on this amazing framework is greatly appreciated

**Comment by photonstorm** [comment]
I'll upload some new examples to the labs shortly, showing how they're used - keep an eye on that repo to know when they're ready.

**Comment by roberto257** [comment]
@photonstorm how can I download the dev version (3.21.1) so that I can make use of these features?

**Comment by photonstorm** [comment]
You have to build it, so if you clone the repo, do `npm install` (wait for 30 mins as half the internet downloads) then do `npm run build` and it'll build a debug version you can test with. If you want a full version, do `npm run dist` instead.

**Comment by photonstorm** [comment]
Also, enter `npm run help` to get a full list of available options, too.

**Comment by roberto257** [comment]
I solved it by going to the examples repo and downloading the dev.js. Thanks
