### ISSUE TITLE
BitmapText with maxWidth set fails to change when its text is updated

### ISSUE THREAD

**Issue by oxguy3** [photonstorm/phaser#4881]
## Version

* Phaser Version: v3.21.0

* Operating system: macOS

* Browser: Chrome 78

## Description

If you set a `maxWidth` value on a BitmapText object (let's call it `myBitmapText`), it will fail to recalculate its bounds when you update the value of `myBitmapText.text` value more than once. As a result, once you have assigned a value to `myBitmapText.text` once, that string will be displayed forever; no further re-assignments of `myBitmapText.text` will have any visual effect.

## Example Test Code

https://jsfiddle.net/e6x2avbh/3/

This test code features two BitmapText objects which are almost identical. The only difference is that the first one (`goodText`) does not have a maxWidth set, while the second one (`badText`) does have a maxWidth.

Both objects start with no text in them, but every time `update()` is called, I add a single character to each of them, until a full message is added. In `goodText`, this makes for a pretty animation as the entire message becomes visible; however, in `badText`, only the first character of the message appears.

## Additional Information

The bug seems to occur because the conditional statement on [line 101 of GetBitmapTextSize](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/bitmaptext/GetBitmapTextSize.js#L101) only evaluates to `true` the first time the function is called. Thus, I found a workaround: if you change the value of `myBitmapText._bounds.maxWidth` immediately after you change `myBitmapText.text`, that conditional will evaluate to `true` again, and the bounds will successfully update.

I've included this workaround in a comment in my jsFiddle's `update()` method. If you uncomment it, `badText` will behave identically to `goodText`.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
