### ISSUE TITLE
Create a bug where game mouse events do not execute

### ISSUE THREAD

**Issue by siyuanqiao** [photonstorm/phaser#4883]
## Description
If you specify the parent div to create the canvas and the div creates the Game during the transform animation, the mouse event will not execute. Mouse events cannot be executed unless you change the width and height of the div or manually change the size of the browser window.（如果指定了创建canvas的父级div，并且这个div在执行transform动画的过程中创建了Game，那么鼠标事件无法执行。除非更改一下div的宽高或者手动更改浏览器窗口的大小，鼠标事件才能执行。）

```
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
  <style>
    * {
      margin: 0;
      padding: 0;
    }

    html, body {
      width: 100%;
      height: 100%;
    }

    .animated {
      -webkit-animation-duration: 2s;
      animation-duration: 2s;
      -webkit-animation-fill-mode: both;
      animation-fill-mode: both;
    }

    @-webkit-keyframes fadeInRight {
      0% {
        opacity: 0;
        -webkit-transform: translate3d(100%, 0, 0);
        transform: translate3d(100%, 0, 0)
      }
      100% {
        opacity: 1;
        -webkit-transform: none;
        transform: none
      }
    }

    .fadeInRight {
      -webkit-animation-name: fadeInRight;
      animation-name: fadeInRight
    }
  </style>
</head>
<body>
<div id="phaser_player" class="animated fadeInRight"></div>
</body>
</html>
<script src="https://cdn.jsdelivr.net/npm/phaser@3.20.1/dist/phaser-arcade-physics.min.js"></script>
<!--<script src="../../assets/lib/phaser/phaser-3.19.0.min.js"></script>-->
<script>
  setTimeout(() => {
    let game = new Phaser.Game({
      type: Phaser.AUTO,
      transparent: true,
      autoFocus: true,
      backgroundColor: 0x1099bb,
      scale: {
        parent: "phaser_player",
        mode: Phaser.Scale.FIT,
        autoCenter: Phaser.Scale.CENTER_BOTH
      },
      scene: {
        preload,
        create
      }
    })

    setTimeout(() => {
      let playerEle = document.getElementById('phaser_player')
      playerEle.style.width = '50%'
    }, 3000)
  }, 1000)


  function preload() {
    this.load.image('icon_energy.png', '../../assets/img/icon_energy.png')
  }

  function create() {
    let img = this.add.image(0, 0, 'icon_energy.png').setOrigin(0, 0).setInteractive()
    img.on('pointerup', () => {
      console.log('pointerup img')
    })
  }
</script>
```

**Comment by photonstorm** [comment]
Thank you for taking the time to report this issue. However, I'm afraid I'm going to close it, as in this situation I feel it's well beyond the scope of what Phaser should be responsible for - if you are applying CSS transforms, then it's your responsibility to ensure that Phaser is activated / updated after they have completed.

**Comment by siyuanqiao** [comment]
> Thank you for taking the time to report this issue. However, I'm afraid I'm going to close it, as in this situation I feel it's well beyond the scope of what Phaser should be responsible for - if you are applying CSS transforms, then it's your responsibility to ensure that Phaser is activated / updated after they have completed.

Can you provide a method that can be called to activate the Phaser mouse event after the CSS animation is complete?

**Comment by samme** [comment]
Probably you need to call `game.scale.refresh()`.

**Comment by siyuanqiao** [comment]
> 可能您需要致电`game.scale.refresh()`。

thanks for you
