### ISSUE TITLE
Image isn't crisp after scaling comparing to browser scale

### ISSUE THREAD

**Issue by ermite1408** [photonstorm/phaser#4884]
## Version

* Phaser Version: 3.21.0

* Operating system: windows 10

* Browser: Chrome, Opera, Mozilla

## Description

After resize image (by setScale/setDisplaySize on image or change camera zoom) becomes a low quality.

In Phaser v. 3.15.1 it was possible set resolution in game config, but it doesnt work now.

If set resolution in scale manager
`this.scale.resolution = 3;`
game size will change.

If you can point out to "resolution" peace of code for hardcoding change, it would be also nice option.

## Example:
![77bfa713b38510839f9c0bfe60f45db5](https://user-images.githubusercontent.com/57718126/69638304-7a711d80-106b-11ea-97b7-3cd93fe5846a.png)

**Comment by photonstorm** [comment]
Thanks for opening this issue. However, I'm going to close it, as we've already an open issue re: `resolution` in the Scale Manager - and more importantly, mipmap support was released in 3.21, which allows you to finely control the quality of scaled-down textures. See the change log for more details.
