### ISSUE TITLE
adfinished event called with wrong adInstance after calling showAd function

### ISSUE THREAD

**Issue by east62687** [photonstorm/phaser#4888]
## Version

* Phaser Version: 3.20

* Operating system: Android (Facebook Instant Game)

* Browser:

## Description
I preload two ads (one Interstitial and one rewarded video ads) and listen to 'adfinished' that will be emmited after the ads was shown. Both ads were loaded perfectly then I show the interstitial. The interstitial was shown correctly, however, the adfinished event was emitted with the adInstance of the rewarded video ad. The interstitial also wasn't marked as shown so the next attempt to show the interstitial results in trying to show an ad that has already shown which result in "INVALID_PARAM" error.

## Example Test Code
	//preload the ads
	this.facebook.preloadAds(ADS_INTERSTITIAL);
	this.facebook.preloadVideoAds(ADS_VIDEO);	

	//register listener to adfinished
	this.facebook.on('adfinished', function (ad) {
		//this could be called with the wrong ad		
	}, this);

	//call showad anytime after BOTH ads was preloaded
	this.facebook.showAd(ADS_INTERSTITIAL);	

## Additional Information

My fix to this problem was overriding the showAd and showVideo function. Adding a break command after phaser has found an ad to be shown and calling function showAsync.

	this.facebook.showAd = function (placementID)
	{
		var _this = this;

		for (var i = 0; i < this.ads.length; i++)
		{
			var ad = this.ads[i];

			if (ad.placementID === placementID && !ad.shown)
			{
				ad.instance.showAsync().then(function ()
				{
					ad.shown = true;

					_this.emit('adfinished', ad);

				}).catch(function (e)
				{
					if (e.code === 'ADS_NOT_LOADED')
					{
						_this.emit('adsnotloaded', ad);
					}
					else if (e.code === 'RATE_LIMITED')
					{
						_this.emit('adratelimited', ad);
					}
					
					_this.emit('adshowerror', e, ad);
				});			
				break; // the fix
			}
		}
		return this;
	}

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
