### ISSUE TITLE
Empty gamepad array in create function in new scene

### ISSUE THREAD

**Issue by Sytten** [photonstorm/phaser#4890]
## Version

* Phaser Version: 3.21.0

* Operating system: Macos

* Browser: Chrome

## Description

The `this.input.gamepad.gamepads` array is empty when switching to a new scene, even though the previous scene had handled the `connected` event. This means we can't easily hook the events, because we never get a `connected` event from the plugin.

EDIT: I found a work around. You can call `refreshPads` and you will get the list of connected pads. I feel this should be done by the constructor.

EDIT2: It seems like the event from the previous scene is replicated to the new scene using this method. We should be able to discard the previously handled events.

**Comment by Olliebrown** [comment]
I have observed this too (in 3.20 on Chrome).  I will see if I can help with a code example / debugging in the next week here.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
