### ISSUE TITLE
Animation Event SPRITE_ANIMATION_COMPLETE fires immediately

### ISSUE THREAD

**Issue by scott20145** [photonstorm/phaser#4894]
## Version

* Phaser Version: 3.19.0

* Operating system:

* Browser:

## Description

The sprite is playing a `loop` animation, and it will play a `attack` animation then back to `loop` animation. In this situation, event `SPRITE_ANIMATION_COMPLETE` will triggered immediately when `attack` triggered, so `attack` animation won't be displayed.

pseudo code:
```javascript
// MySprite.ts
// play(key: 'string', loop?: boolean ):Promise;
const item = new MySprite();
item.play('loop', true);

window.setTimeout(() => {
    item.play('attack', false).then(() => {
        item.play('loop', true);
    });
},3000);


```

The reason is because when loading animation it will check if it is playing:

```javascript
   //Phaser.GameObjects.Components.Animation
    load: function (key, startFrame)
    {
        if (startFrame === undefined) { startFrame = 0; }

        if (this.isPlaying)
        {
            this.stop();
        }
      //...
    },
```

It should be a different event like `animation_stop` but not `animation_completed` in my opinion. I think it is a bit unclear.

Current workaround is to set `isPlaying = false` before playing animation.

Or  I missed anything?

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
