### ISSUE TITLE
TimelineBuilderConfig: "delay" should only fire at the start of the timeline and not when looping

### ISSUE THREAD

**Issue by micsun-al** [photonstorm/phaser#4896]
## Version
* Phaser Version: Phaser v3.21.0 (WebGL | Web Audio)
* Operating system: macOS Catalina 10.15.1
* Browser: Version 78.0.3904.108 (Official Build) (64-bit)

## Description
* Expected behavior: The "delay" specified in the TimelineBuilderConfig should apply to starting the timeline and not trigger when the timeline is starting a loop.
* Current behavior: The "delay" specified in the TimelineBuilderConfig applies when starting the timeline, and when the timeline loops.

## Example Test Code
https://codepen.io/micsun-al/pen/QWwwvYz

## Additional Information
"loopDelay" and "repeatDelay" should be able to cover any scenarios where "delay" is currently defaulting to delaying in addition to at the start of the timeline.

**Comment by micsun-al** [comment]
Also, is it a little strange that the tweens don't seem to animate sync'ed together?  Do the delay/loopDelay pad the tween duration so it animates faster or slower than the other variations?

**Comment by photonstorm** [comment]
Just to say that Timelines have been removed from Phaser 3.60 and replaced with the new Tween Chain system, which enables perfectly sequenced playback. Although this is a breaking change, I feel it was worth making for the benefits it brings (such as fixing issues like this!)
