### ISSUE TITLE
Phaser loader - Load Images Using Tags Not XHR

### ISSUE THREAD

**Issue by BobtheUltimateProgrammer** [photonstorm/phaser#4897]
Hi,
Is there a way to tell the Phaser loader to load the images using image tags and NOT by XHR requests. I seem to prefer tag loading better because it is more efficient to use in my game.
I know that Phaser Videos could be loaded via video tags and that audio could be loaded via audio tags because it says in the docs but there is no info in the docs about how to load images via tags.

"In this dev log, https://phaser.io/phaser3/devlog/58, it says there is an option to load images via XHR or Tags but I couldn't find anything in the docs.
To support Canvas the array buffers are converted back into Image tags via base64 encoding, or you can instruct the Loader to just use Image tags anyway. The key thing here is choice: You now actually have one."

**Comment by BobtheUltimateProgrammer** [comment]
Question : Do you know when is this feature going to be implemented so I can plan my game development accordingly? Thanks.

**Comment by photonstorm** [comment]
There are no immediate plans to add this. That Dev Log is years old, now, what may have been mentioned in it doesn't relate to today I'm afraid. Don't wait-up on this feature, it may never actually land.
