### ISSUE TITLE
use Vector2 class for all positions, also for camera.scroll

### ISSUE THREAD

**Issue by milahu** [photonstorm/phaser#4898]
i use [Phaser.Math.Vector2](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/vector2/) to optimize vector operations
but on the "first mile" and "last mile"
i must convert between scalar variables and vector variables

this is the case at least for camera.scroll
which is only defined with scalar variables scrollX and scrollY

[fiddle here](https://jsfiddle.net/x79yhwgk/): drag canvas, zoom canvas

ideal i can write
```js
pointer.camera.scroll =
pointer.position
.scale(pointer.camera.zoomInvNeg)
.add(pointer.camera.scrollStart)
;
```

now i must write

```js
const temp =
pointer.position
.scale(pointer.camera.zoomInvNeg)
.add(pointer.camera.scrollStart)
;
pointer.camera.scrollX = temp.x;
pointer.camera.scrollY = temp.y;
```

scalar operations are verbose and slow

```js
pointer.camera.scrollX =
pointer.position.x
 * pointer.camera.zoomInvNeg
 + pointer.camera.scrollStartX
;

pointer.camera.scrollY =
pointer.position.y
 * pointer.camera.zoomInvNeg
 + pointer.camera.scrollStartY
;
```

ps

camera.scroll is just a sample
where performance can be limited by scalar operations

this is more of a general request
to enable vector operations for all positions

.. and auto-generate the scalar methods via meta-programming?

**Comment by photonstorm** [comment]
Having thought about this some more, it's not a change I'm willing to make at this stage of Phaser 3's life. The ramifications, both in breaking the API and through-out the entire codebase are massive (especially when you factor in other more widely used properties like `scaleX` etc.)

Too large of a change for the sake of skipping a couple of property assignments, I'm afraid.
