### ISSUE TITLE
Phaser.Actions.GridAlign ignoring width of -1

### ISSUE THREAD

**Issue by BenjaVR** [photonstorm/phaser#4899]
## Version

* Phaser Version: Phaser v3.21.0-FB (WebGL | Web Audio)

* Operating system: Windows 10 Pro, Version 1903, Build 18362.476

* Browser: /

## Description

`Phaser.Actions.GridAlign` accepts a configuration parameter `width`, which is the amount of items the grid should have horizontally. When passing `-1` as value, all the items should be spread out horizontally, no matter the amount of items, just as the docs say:

```
The width of the grid in items (not pixels). -1 means lay all items out horizontally, regardless of quantity.
If both this value and height are set to -1 then this value overrides it and the `height` value is ignored.
```

However, when using `-1` as the value of `width`, the items get spread out vertically instead of horizontally, which is actually the behavior a `height` of `-1` should have.

## Example Test Code

A slightly modified version of https://labs.phaser.io/edit.html?src=src/actions\grid%20align.js:

https://codesandbox.io/s/laughing-kilby-hrbxw

## Additional Information

/

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by BenjaVR** [comment]
@photonstorm works as expected now, thanks for the fix!
