### ISSUE TITLE
Text lineSpacing do not work, when version over 3.17.0

### ISSUE THREAD

**Issue by FantaZZ** [photonstorm/phaser#4901]
Text lineSpacing do not work, when version over 3.17.0

http://labs.phaser.io/view.html?src=src\game%20objects\text\static\line%20spacing.js

Like this example, when you change verison under 3.18.0, lineSpacing is work again.

**Comment by FantaZZ** [comment]
Has any suggest ? Thank you ~

**Comment by FantaZZ** [comment]
ok, I find something.

If you create text with lineSpacing, it is not work, like this
```
let text = this.scene.add.text(0, 0, ['text, 'text', 'text'], {lineSpacing: '15'});
````

You have to call updateText() after create
`text.updateText()` or `text.setLineSpacing(15)`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
