### ISSUE TITLE
GetBounds methods fail for Mesh and Quad objects

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#4902]
## Version

* Phaser Version: 3.21.0

## Description

E.g.,

```
quad.getBounds() // -> { x: NaN, y: NaN, width: NaN, height: NaN }
```

## Additional Information

Probably Mesh shouldn't include the [GetBounds](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Components.GetBounds.html) component, as it lacks [Origin](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Components.Origin.html).

**Comment by photonstorm** [comment]
Yeah it shouldn't, I'll remove it.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
