### ISSUE TITLE
Documentation: setDepth vs setZ

### ISSUE THREAD

**Issue by louisth** [photonstorm/phaser#4903]
## Version

* Phaser Version: v3.20.1

* Operating system: (not relevant - Win10)

* Browser: (not relevant - Chrome)

## Description

It should be made clear in the documentation for Base Object (and all derived classes like image) that (in a 2D environment) setting the Z value does not affect the rendering depth (which objects are drawn over the top of others). For example, (property) z, setZ, setPosition should say "Note that the z coordinate does not control the render order of 2D game objects. Use setDepth to control which objects render on top of others.."

**Comment by hexus** [comment]
Cheers, I've clarified this in the commit above (15ac5e7). The improved docs will be part of 3.22.0.
