### ISSUE TITLE
Type config Phaser.Tilemaps.LayerData.data is not right, impossible to loop over 2D array in TypeScript

### ISSUE THREAD

**Issue by GBurg** [photonstorm/phaser#4904]
Type of **data** member in **Phaser.Tilemaps.LayerData** is not Array of Number but rather an array of an array of Tiles. This is an issue when manually looping over the data Array, as Typescript doesn't allow you to dig in the multidimensional array.

https://photonstorm.github.io/phaser3-docs/Phaser.Tilemaps.LayerData.html#data__anchor

![image](https://user-images.githubusercontent.com/3472613/70395669-72b55f80-1a01-11ea-8583-cc36bdf00770.png)

How can I fix it quickly?

**Comment by GBurg** [comment]
I worked around it for now by casting the result to any:
`let sub:Phaser.Tilemaps.Tile[] = layer.layer.data[i] as any;`

However, might be good if the typings themselves are also fixed...

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
