### ISSUE TITLE
Input debug has the wrong position when a game object has been scaled and the hit area is smaller than the game object

### ISSUE THREAD

**Issue by PavelMishin** [photonstorm/phaser#4905]
## Version

* Phaser Version: 3.21.0
* Operating system: Windows 10
* Browser: Firefox, Chrome

## Description

If the geometry object which used as input shape is smaller than the initial game object size, and the game object is scaled, the input debug graphics position seemed as if the game object was not scaled.

## Example Test Code

```
const image = this.add.image(400, 400, 'test') // test image has 200x200 size for example
image.setScale(0.7)
image.setInteractive(new Phaser.Geom.Circle(100, 100, 80), Phaser.Geom.Circle.Contains)
this.input.enableDebug(image)
```

## Additional Information

If the radius of Circle in the example will be 100, then the debug graphics position will be correct.

I suspect that it's related to the Fix #4722.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
