### ISSUE TITLE
[Website] Images doesn't fit on mobile devices

### ISSUE THREAD

**Issue by Regnander** [photonstorm/phaser#4907]
I tend to read the documentation on my phone while cooking, cleaning or doing other chores but since the example images won't fit the screen, it ruins the experience quite a bit.

Current behavior | Expected behavior
------------ | -------------
![1a](https://user-images.githubusercontent.com/17113053/70664795-69c7c680-1c6b-11ea-92f3-71035088e44a.png) | ![1b](https://user-images.githubusercontent.com/17113053/70664824-806e1d80-1c6b-11ea-80d8-61fa7bd77670.png)
![2a](https://user-images.githubusercontent.com/17113053/70664830-8401a480-1c6b-11ea-9bef-b5840b08de6a.png) | ![2b](https://user-images.githubusercontent.com/17113053/70664814-75b38880-1c6b-11ea-9ce5-424f81914f0f.png)

_Screenshots taken from [part 1](http://phaser.io/tutorials/making-your-first-phaser-3-game/part1) and [10](http://phaser.io/tutorials/making-your-first-phaser-3-game/part10) of the tutorial. The images in the second column was manipulated by adding_ `width: 100%` _in the developer console._

**Comment by classicmatsuo** [comment]
adding `width: 100%` to `#content .tutorialItem img` in `http://phaser.io/css/phaser.css` should do the trick
dont think the website docs are here in the repo though.
fixes issue #4907
![Screen Shot 2019-12-17 at 3 37 13 PM](https://user-images.githubusercontent.com/13067641/71036780-f21eef00-20e3-11ea-9007-bacb0930fb9e.png)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the web site.
