### ISSUE TITLE
Particle position broken with canvas when using camera zoom

### ISSUE THREAD

**Issue by smjnab** [photonstorm/phaser#4908]
## Version

* Phaser Version: 3.21

* Operating system: Linux Ubuntu

* Browser: Tested in Firefox, Safari and Chrome

## Description

//Edited and removed the issue with mask/tint as it was not an issue.

Particle position is changed when a camera is zoomed. The example shows an object and a particle, changing the camera zoom changes the position of the particle relative to the box when using canvas, but stays in place when using webgl.

Camera zoom breaks particle positions (and perhaps more):
example url: https://labs.phaser.io/edit.html?src=src\game%20objects\particle%20emitter\death%20zone%20from%20arcade%20body.js

Replace with code:

    var config = {
        type: Phaser.CANVAS, // SWITCH TO WEBGL TO CHECK THAT THE PARTICLE KEEPS POSITION
        width: 800,
        height: 600,
        backgroundColor: '#000',
        parent: 'phaser-example',
        physics: { default: 'arcade' },
        scene: {
            preload: preload,
            create: create
        }
    };

    var game = new Phaser.Game(config);

    var block;

    function preload ()
    {
        this.load.atlas('flares', 'assets/particles/flares.png', 'assets/particles/flares.json');
        this.load.image('block', 'assets/sprites/block.png');
    }

    function create ()
    {
        var source = {
            contains: function (x, y)
            {
                return block.body.hitTest(x, y);
            }
        };

        var particles = this.add.particles('flares');

        particles.createEmitter({
            frame: [ 'red', 'green', 'blue' ],
            x: 400,
            y: 100,
            speed: 300,
            gravityY: 400,
            lifespan: 4000,
            scale: 0.4,
            blendMode: 'ADD'
        });

        block = this.physics.add.image(400, 100, 'block');

        block.setBounce(1, 1);
        block.setCollideWorldBounds(true);

        this.cameras.main.setZoom(0.5); //TRY DIFFERENT ZOOMS TO SEE HOW THE PARTICLE HAS A DIFFERENT POSITION TO THE BOX
    }

**Comment by photonstorm** [comment]
There may be something going on with masking, but tints have _never_ worked in Canvas mode in Phaser 3, in any version.

**Comment by photonstorm** [comment]
Actually, in the magnify mask example linked, that doesn't work in Canvas either because it uses a Bitmap Mask which is a WebGL only feature. It doesn't work in canvas mode in any version of Phaser. Look at your link, then look in the dev tools and you'll see it's using a WebGL renderer which is why it works. Edit the example, force it to canvas and you'll see it does nothing as expected.

Which just leaves the camera zoom.

**Comment by smjnab** [comment]
Ah, sorry! Had the error in my project, went to labs to check and used the force canvas button and saw how it "worked" in the older versions. I see now it stays in WebGL when checking the console.

**Comment by photonstorm** [comment]
Yeah the force canvas feature was added after 3.11, which is why the button doesn't force anything on earlier builds.

**Comment by shainmock** [comment]
thanks for your useful information


[اَوِسینا شیمی](https://www.avecinashimi.com/)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
