### ISSUE TITLE
scale.orientationchange not work in iOS safari

### ISSUE THREAD

**Issue by cuihu** [photonstorm/phaser#4914]
you can run Oreientation Check demo in iOS safari.
I guess when oreientation in safari don't change screen.width or window.innerWidth....

**Comment by johanlindfors** [comment]
Same issue as here #4361

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
