### ISSUE TITLE
Does it have a size limit to `Adds a Sprite Sheet Image` on the mobile phones?

### ISSUE THREAD

**Issue by shenjo** [photonstorm/phaser#4928]
loading a Sprite Sheet Image as the doc says
`this.load.spritesheet('myImage', imageUrl, config)`
and then use it 
`this.add.sprite(100,100, 'myImage',0)`

but when my image is 7000 * 500 , it cannot diplay on the phones  while the browser is ok(chrome)

when I change the size to 2800 * 200, everything goes well.

So, Is there a size limit on phones?

**Comment by shenjo** [comment]
![image](https://user-images.githubusercontent.com/13912646/71510732-d5946b00-28ca-11ea-977e-8ecd18f2c7b1.png)

**Comment by photonstorm** [comment]
The texture size is larger than your phone can handle. This is specific to the GPU within the phone, not Phaser. Check the hardware docs for your phone's GPU to see what the maximum texture size it can support is, and also appreciate that the lower-end phones will only handle smaller textures, while more powerful phones will handle larger ones. Even with top-end iPhones a 7k texture is massive, though.
