### ISSUE TITLE
Input pointer stuck at active and pointerup does not get called

### ISSUE THREAD

**Issue by doug1e** [photonstorm/phaser#4932]
Hi there,

I have the following call to change the position of the ball in my game. Basically, I slide across the screen to move the ball; i.e. almost like a drag but not attached to an object.

```
this.input.on('pointerup', this.moveBall, this);  
```

The moveBall function is called most of the time perfectly fine. However, once in a while it stops working for no reason! I have been trying but cannot find a way to replicate the bug in a consistent way. However, it happens often enough and I only observed it on iOS.

During this problem the below always returns true
```
this.input.isActive()
```

Even if I remove the listeners by 
```
this.input.removeAllListeners();
```
the pointer still is stuck at active. Once the game gets into that state, it does not receive further pointerup events; even after scene restart().

I restart my scene when I switch from level to level and also pause the scene during level transition. I am not sure if the bug is somehow related to restart/pause functions.

I am aware that this is not an ideal bug submission but I am struggling to find a way to consistently replicate the issue. However, I'd be happy to provide more information if you could provide me pointers.

As I have seen similar bugs in previous versions, I want to highlight that I am using version 3.21.0

Best regards,

Doug

**Comment by photonstorm** [comment]
Do you reckon you may have inadvertently activated an OS gesture?

**Comment by doug1e** [comment]
Hi Richard,

Yes, it is possible. I will close this issue as I really struggle to replicate it and I do not want to waste your time on a goose chase. If I can figure out a way to replicate this consistently, I will open a new issue and will provide more context.

Many thanks for responding.

Cheers,

Doug

**Comment by photonstorm** [comment]
@doug1e thanks for being considerate :)
