### ISSUE TITLE
Scene ScaleManager events not removed after scene.remove()

### ISSUE THREAD

**Issue by faceth** [photonstorm/phaser#4933]
## Version 3.21

* Phaser Version: 3.21

* Operating system: Windows 10

* Browser: Firefox 

## Description

When using scene.remove, scene ScaleManager event Listeners ( such as scale.on('resize') for exemple ) are not removed.

When creating a new scene, if one is using scale.on event listeners, the previously deleted scene events will trigger as well since they are not cleared by scene.remove

It's debatable to consider this as a bug, but one could expect that the method scene.remove would clear everything.

## Example Test Code

var config = {
    type: Phaser.AUTO,
    backgroundColor: '#2dab2d',
    scale: {
        mode: Phaser.Scale.RESIZE,
        parent: 'phaser-example',
        width: 800,
        height: 600,
        min: {
            width: 800,
            height: 600
        },
        max: {
            width: 1600,
            height: 1200
        }
    },
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('pic', 'assets/pics/zero-two.png');
}

function create ()
{
    this.add.image(0, 0, 'pic').setOrigin(0);
    this.scale.on('resize',function(){alert(1)});
    this.scene.remove();
//When the window is resized after this, alert will still trigger.
}

**Comment by samme** [comment]
I think that's normal. `this.scale` is the global Scale Manager so its events are global too.

**Comment by photonstorm** [comment]
Based on the code posted above, this is working how I'd expect. The handler has been added to the global Scale Manager, not the Scene, so removing Scene level handlers won't do anything to a global system. The following approach works:

```js
this.scale.on('resize', this.resize, this);
// in your Scene shutdown ...
this.scale.off('resize', this.resize, this);
```
