### ISSUE TITLE
Newest Version of Chrome (79.0.3945.88) Breaks Phaser in Windows 7

### ISSUE THREAD

**Issue by heidisanchez** [photonstorm/phaser#4937]
In Chrome 79.0.3945.88 (released Dec 17) Phaser animations are extremely slow and jerky.  

[](https://phaser.io/examples/v3/view/animation/cubes 1)

Just look at this Phaser example animation. Run it in Chrome (Version 79.0.3945.88, released Dec 17, 2019), then run it in Firefox or another browser.

Make sure to CLOSE the one running in Chrome when you go test in another browser, because whatever mischief Chrome is doing seams to drag the whole system when a Phaser file is running.

Anyone have a guess as to what’s going on?

Thanks, all.

**Comment by photonstorm** [comment]
Using the exact same version of Chrome on macOS and Windows 10 and it runs fine for me, with no system slow-down. Canary is fine too. If no-one else can replicate this (other than the original poster) then this is just a local system issue. Perhaps Chrome has now blacklisted your GPU?

**Comment by heidisanchez** [comment]
I tested on Windows 10, it runs fine.  I have tested on 4 different computers running Window 7 and the slowdown is consistent.

**Comment by photonstorm** [comment]
Then it's out of our control. There is literally nothing we can do about this, as there isn't a single line of code in Phaser that is 'chrome' specific (or specific to Windows 10). If they've released a version of Chrome that doesn't run well on Windows 7 then report it to them, or wait for another version and see if they address it.

**Comment by heidisanchez** [comment]
I have already opened a bug report with them.  Just thought you all might want to be aware of it.
