### ISSUE TITLE
Extending from Group fails to add the group to updateList

### ISSUE THREAD

**Issue by T-Grave** [photonstorm/phaser#4941]
## Version

* Phaser Version: 3.21.0

* Operating system: PopOS 19.10

* Browser: Chrome 79

## Description

When I extend a new class `PlaneGroup` from `Phaser.Physics.Arcade.Group` (or `Phaser.GameObjects.Group`) with `{ runChildeUpdate: true }` passed as a config, the children do not get their `update` method called.

When I `console.log(this.scene.sys.updateList)` it contains only the two `Plane` objects I added in the group, but not the PlaneGroup itself, resulting in the ability to have `Plane.preUpdate()` called, but not `Plane.update()` or `PlaneGroup.preUpdate()` being called.

## Example Test Code

```
export default class PlaneGroup extends Phaser.Physics.Arcade.Group {
  constructor(world: Phaser.Physics.Arcade.World, scene: Phaser.Scene) {
    super(world, scene, { runChildUpdate: true });

    this.scene = scene;
    this.world = world;
  }
}
```

## Additional Information

I've seen multiple posts on the forums about the expected behavior being groups adding themselves to the updateList, but there was also [this post](https://phaser.discourse.group/t/extended-group-no-update-of-children/1163) which is interesting, as the suggestion is to add the group manually to the scene, but the TypeScript definitions don't allow me to pass a Group to `this.add.existing()`

**Comment by photonstorm** [comment]
This doesn't just apply to Groups, not one of the Game Objects will automatically add itself to the Scene - they only do that if created via the factory. If you're creating them outside of the factory, you need to add them to the display and update lists yourself.

**Comment by photonstorm** [comment]
I have, however, updated the JSDocs, so the defs will allow you to use `add.existing` (although just using `this.updateList.add(group)` would be quicker.
