### ISSUE TITLE
ambiguous parameter for `pipeline.addAttribute`

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#4942]
the second parameter (`type` ) for `pipeline.addAttribute` method will make user confused.
normally I'll use this method like this:

        ppl.addAttribute('inBlur', 2, renderer.gl.UNSIGNED_BYTE, true, Float32Array.BYTES_PER_ELEMENT * 5 + Uint8Array.BYTES_PER_ELEMENT * 4);

that is, directly use GL consts to pass to this method, but actually this method requires a number to use (for example `addAttribute('name', 2, 2, true, offset)`),
https://github.com/photonstorm/phaser/blob/5b17e0e61e9bdf902eb40899eaa7df498d4986be/src/renderer/webgl/WebGLPipeline.js#L268-L276
(line 273)

so should we just improve the TS doc or change to use another way?

this is not a bug so I made it as feature request.

if doc improvement is enough, I'll PR, thanks.

**Comment by photonstorm** [comment]
At this late stage of Phaser 3's life, I'd rather we just fix the docs to be honest.

**Comment by jcyuan** [comment]
ok, thanks man~
