### ISSUE TITLE
scaleManager.destroy doesn't called when game destroy

### ISSUE THREAD

**Issue by sunshineuoow** [photonstorm/phaser#4944]
## Version

* Phaser Version: v3.18.1

* Operating system: mac os 10.15.2

* Browser:  Electron v4.0.8

## Description

when I invoke `game.destroy(true)`,
`game.scale`cannot be current destroy
that caused my scene cannot be correctly gc

## Additional Information

here is the game.runDestroy implement
```javascript
runDestroy: function ()
    {
        this.events.emit(Events.DESTROY);

        this.events.removeAllListeners();

        this.scene.destroy();
       // seems to call this.scale.destroy(); here

        if (this.renderer)
        {
            this.renderer.destroy();
        }

        if (this.removeCanvas && this.canvas)
        {
            CanvasPool.remove(this.canvas);

            if (this.canvas.parentNode)
            {
                this.canvas.parentNode.removeChild(this.canvas);
            }
        }

        if (this.domContainer)
        {
            this.domContainer.parentNode.removeChild(this.domContainer);
        }

        this.loop.destroy();
        
        this.pendingDestroy = false;
    }
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
