### ISSUE TITLE
Cannot load different Spine models which share an atlas (texture)

### ISSUE THREAD

**Issue by Nomy1** [photonstorm/phaser#4947]
#4105  Version

* Phaser Version: v3.20.1-FB
* Operating system: macOS 10.15
* Browser: Firefox (dev edition) 72.0b11

## Description

Expected: I expect to be able to load multiple spine models that share a texture.
Result: TextureManager complains that texture already exists in cache.

## Example Test Code

```
this.load.spine("jsonkey", "json-filename1", "atlas-filename");
this.load.spine("jsonkey", "json-filename2", "atlas-filename");
```

## Possible fix

I dug into SpinePlugin.js and located where I can avoid the error inside the addToCache function. But this seems janky?

before:
`this.loader.textureManager.addImage(key, file.data);`

after:

```
if(!this.loader.textureManager.exists(key)){
  this.loader.textureManager.addImage(key, file.data);
}
```

**Comment by raimon-segura** [comment]
Hi!,

Your example test code works with las Phaser 3 version

regards!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
