### ISSUE TITLE
Custom Phaser.Sound.BaseSoundManager's add function doesn't return Phaser.Sound.BaseSound object

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#4953]
## Version

* Phaser Version: 3.21.0

* Operating system: Windows 10

* Browser: Google Chrome

## Description

In my project I'm using `this.sound` for music and creating `this.sfx` for sfxs via
`this.sfx = new Phaser.Sound.BaseSoundManager(this.game);`
Adding new sound manager to play sound effects and background musics separately.
And I've different behavior for `this.sound` and `this.sfxs` managers' `add` functions.

## Example Test Code

```
var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create
    },
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.audioSprite('sfx', 'assets/audio/SoundEffects/fx_mixdown.json', [ 'assets/audio/SoundEffects/fx_mixdown.ogg', 'assets/audio/SoundEffects/fx_mixdown.mp3' ]);
}

function create ()
{
    var spritemap = this.cache.json.get('sfx').spritemap;
    var keys = Object.keys(spritemap);
    console.warn(keys);
    this.customSoundManager = new Phaser.Sound.BaseSoundManager(this.game);
    console.warn(this.customSoundManager)
    this.customBaseSound = this.customSoundManager.add(keys[0]);
    console.warn(this.customBaseSound)
}
```

## Additional Information

Returned object is `undefined`.

**Comment by samme** [comment]
I don't think BaseSoundManager can be used on its own. Only HTML5AudioSoundManager or WebAudioSoundManager will work.

**Comment by RollinSafary** [comment]
@samme thanks for the answer.
From here the second question: in some situations (different devices or browsers) phaser automatically creates HTML5 or Web audio sound manager for the scene. So if I need one more sound manager, how can I do that via phaser's native functionality? I mean something like `this.add.soundManager` in `scene` or `game` instance.

P.S. manually created Web or HTML5 Sound managers are returning `undefined` too.

**Comment by samme** [comment]
It is

```
Phaser.Sound.SoundManagerCreator.create(game)
```

**Comment by photonstorm** [comment]
Closing this issue off as the answer the above :)

**Comment by samme** [comment]
> So if I need one more sound manager, how can I do that via phaser's native functionality?

https://codepen.io/samme/pen/mdJQbBr
