### ISSUE TITLE
Loading errors on Android devices

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#4957]
Parallel downloads on an android device can be not more than 6 (default is 32) based on HTTPS protocol that android devices are using (I've read about that somewhere, unfortunately, can't find the link). So I think it will be nice if the phaser will automatically set that value in the game configuration if the device is android and of course if there is no manual config of that property. Haven't tested for ios devices

**Comment by samme** [comment]
What are the errors?

**Comment by RollinSafary** [comment]
@samme `Failed to load resource: net::ERR_FAILED`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
