### ISSUE TITLE
Geom.Rectangle lacks centerX and centerY properties, cannot Display.Align.In

### ISSUE THREAD

**Issue by rei-shards** [photonstorm/phaser#4959]
When centering a game object onto a geometry rectangle, it's properties x and y both get set to NaN,  disappearing in the process.  This is because the Phaser.Display.Align.In and it's various alignments call for Phaser.Display.Bounds.GetCenterX, and Phaser.Display.Bounds.GetCenterY.  Both get centers call for the given gameObject to have the property centerX and centerY.  Geom.Rectangle lack the properties centerX and centerY, so plugging undefined into the math results in NaN.

**Comment by photonstorm** [comment]
A `Geom.Rectangle` is not a valid data type for any of the Align functions, which is why they're not listed as a valid type in the JSDocs or TS defs.
