### ISSUE TITLE
Missing BodyType type on matterImage / GameObject for Typescript

### ISSUE THREAD

**Issue by meisterpeeps** [photonstorm/phaser#4962]
Phaser v3.22.0

Excellent work with the typescript types update for matter;  I have run into a type that still seems to be missing.   Accessing the body property of a matterImage object doesn't have any awareness of matterjs BodyType properties, and the compiler throws an error if you try to access the speed property.
```
Property 'speed' does not exist on type 'object | BodyType | Body | Body'.
  Property 'speed' does not exist on type 'object'.ts(2339)
```
I tried to add a MatterJS.BodyType type to the phaser body property on the GameObject type manually but it still didnt work.
`body: object | Phaser.Physics.Arcade.Body | Phaser.Physics.Impact.Body | MatterJS.BodyType;`

I don't really have much experience with manipulating the d.ts files of types, so I could very well be doing something wrong.
`line 14834 body: object | Phaser.Physics.Arcade.Body | Phaser.Physics.Impact.Body  `
I suspect that line needs to be modified with something?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
