### ISSUE TITLE
Matter - gameObject.emit is not a function

### ISSUE THREAD

**Issue by reinildo** [photonstorm/phaser#4967]
On Phaser 3 matterJs examples, like this one: http://labs.phaser.io/view.html?src=src\game%20objects\tilemap\collision\matter%20platformer%20with%20wall%20jumping.js
, when thow bodies collides we receive this error: i.gameObject.emit is not a function

Looking on the source code file: MatterCollisionEvents.js
```javascript
if (bodyA.gameObject) {
  // bodyA.gameObject.emit('collide', bodyA, bodyB, pair)
      matter.Events.trigger('collide', bodyA, bodyB, pair)
 }
```
if I replace the commented line with code below it works without error.
Is it an issue or am I doing something wrong?

Thanks

**Comment by photonstorm** [comment]
It depends what the Game Object is. If it's a Sprite, Image, TileSprite, etc, then `emit` will work fine, as they have Event Emitters by default. If it's a `Matter.Tile` then it won't, as we never give individual tiles emitters.

**Comment by reinildo** [comment]
In the phaser 3 example: http://labs.phaser.io/view.html?src=src\game%20objects\tilemap\collision\matter%20platformer%20with%20wall%20jumping.js
what should I do to fix the error?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by Hetachi** [comment]
What was the fix? What version is the last that did not have this bug? 
I am on 3.15 and I got this error too.

**Comment by photonstorm** [comment]
It's impossible for 3.15 to have this error, as it came about as a result of a brand new plugin added in 3.22. The fix is for 3.23, which isn't published yet.

**Comment by Hetachi** [comment]
> It's impossible for 3.15 to have this error, as it came about as a result of a brand new plugin added in 3.22. The fix is for 3.23, which isn't published yet.

Awesome thanks for the info, any eta on 3.23 ?

**Comment by Brandoning** [comment]
Any update on when 3.23 will be released? I am experiencing this bug

**Comment by Hetachi** [comment]
> Any update on when 3.23 will be released? I am experiencing this bug

As far as I know the update is supposed to be released sometime in April, there was a news blog posted about it, not sure if it was just for patrons or not. 

You can use the master branch its quite stable and has a fix for it already.

**Comment by embeddedt** [comment]
Is there a timeline for when `3.23.0-beta1` will be published to NPM? At the moment I'm using a manually built version of Phaser which works but makes it harder to use typings (as it's not installed in `node_modules`).

**Comment by Brandoning** [comment]
I'm using 3.23-beta1 and I still seem to be getting this issue? Unless I modify the code to matter.Events.trigger it'll error

**Comment by embeddedt** [comment]
@Brandoning What type of game object is it? https://github.com/photonstorm/phaser/issues/4967#issuecomment-578394248

**Comment by Brandoning** [comment]
@embeddedt it's a `Phaser.Physics.Matter.Sprite`

**Comment by embeddedt** [comment]
That's strange. I also use sprites in my game that collide with each other and I don't have this problem.

This is the [Phaser minified JS file](https://raw.githubusercontent.com/embeddedt/PhysicsFun/master/src/phaser.min.js) I'm using (compiled from https://github.com/photonstorm/phaser/commit/7fbe57c2ddb42d3ad1966de13737cce11b95e7c4 last week).

**Comment by starikcetin** [comment]
Where can I get the 3.23-beta* versions? They are not on the npm and there is no git tag that includes 3.23.

**Comment by embeddedt** [comment]
Yes; you have to manually clone the `master` branch and build it. Nothing has been tagged yet.
