### ISSUE TITLE
Changing game size with scale mode FIT results in a canvas with a incorrect aspect ratio.

### ISSUE THREAD

**Issue by Kitsee** [photonstorm/phaser#4971]
## Version

* Phaser Version: 3.22.0

* Operating system: Android & Linux (Ubuntu-based)

* Browser: Chrome (mobile & desktop emulator)

## Description

 I'm starting up the game with the following settings

> {
> width: 1777,
> height: 999,
> scale:
> {
> mode: Phaser.Scale.FIT,
> autoCenter: Phaser.Scale.CENTER_HORIZONTALLY,
> },

. In my primary scene I'm listening for the 'orientationchange' and adjusting the game size accordingly as the code snippet below shows

>     this.scale.on('orientationchange', (Orientation)=> {
>         console.log(Orientation);
> 
>         if (Orientation === Phaser.Scale.PORTRAIT) 
>         {
>             this.scale.setGameSize(999,1777);
>         } 
>         else if (Orientation === Phaser.Scale.LANDSCAPE) 
>         {
>             this.scale.setGameSize(1777,999);
>         }
>     }, this );

When orientation is set to landscape and the setGameSize arguments match the original game size, everything works fine, however in portrait mode the resulting height is completely incorrect, resulting in a actual size of 980x550 with an aspect ratio of 1.78 instead of the expected 0.56 on my device for a game size of 999x1777.

## Example Test Code

Game Config
> {
> width: 1777,
> height: 999,
> scale:
> {
> mode: Phaser.Scale.FIT,
> autoCenter: Phaser.Scale.CENTER_HORIZONTALLY,
> },

Add this code to create in an active scene.

>     this.scale.on('orientationchange', (Orientation)=> {
>         console.log(Orientation);
> 
>         if (Orientation === Phaser.Scale.PORTRAIT) 
>         {
>             this.scale.setGameSize(999,1777);
>         } 
>         else if (Orientation === Phaser.Scale.LANDSCAPE) 
>         {
>             this.scale.setGameSize(1777,999);
>         }
>     }, this );

## Additional Information

This issue appears to be very similar to a previously resolved issue [here](https://github.com/photonstorm/phaser/issues/4482)

I dont fully understand the code however I believe the issue is stemming from the "constrain" function. On line 76998
height = width / this.aspectRatio;
this.aspectRatio appears to still be the old aspect ratio of 1.7 instead of 0.5 resulting in the incorrect height.

**Comment by Kitsee** [comment]
Some further discoveries:
workaround can be achieve using the follow line of code
```
this.game.scale.displaySize.aspectRatio = 1777/999;
this.game.scale.setGameSize(1777,999);
```
also in the SetGameSize function there is the follow snippet of code

```
//  The size used for the canvas style, factoring in the scale mode and parent and zoom value
//  We just use the w/h here as this is what sets the aspect ratio (which doesn't then change)
this.displaySize.setSize(width, height);
```
I believe this is the source of the fault as the comment indicates that setSize updates the aspect ratio which it does not, at least not when in FIT mode.

**Comment by samme** [comment]
https://codepen.io/samme/pen/qBdoyoe

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/am-i-using-setgamesize-wrong-not-working-as-expected/3890/5
