### ISSUE TITLE
Spine: setScale() acts wrong for bones without "inherit rotation"

### ISSUE THREAD

**Issue by HotPinkMuffin** [photonstorm/phaser#4974]
## Version

* Phaser Version: 3.22.0

* Operating system: Windows 10

* Browser: chrome/ie/ff

## Description
Imagine we have a simple arm setup consisting of 3 bones: arm -> forearm -> wrist. The "inherit rotation" option for wrist is unchecked in spine. If we will try to call setScale(0.5) on our skeleton, the wrist will be scaled down x4, instead of x2. 

## Example Test Code
```
this.arm = scene.add.spine(0, 0, 'skeleton', 'animationName', true);
this.arm.setScale(0.5); // arm and forearm are ok, wrist acts like setScale(0.25)
```

**Comment by photonstorm** [comment]
It's possible this is a Spine runtime bug, so the latest runtimes I've just added may resolve it. If not, I don't think there is anything I can do, as when you set the scale on a Spine Game Object all it does is use the runtime `scaleX` and `scaleY` properties, so this issue must be inherent in the runtimes themselves.
