### ISSUE TITLE
this.add.text BUG in HEADLESS mode

### ISSUE THREAD

**Issue by raimon-segura** [photonstorm/phaser#4976]
## Version

* Phaser Version:  Phaser v3.22.0 (Headless | Web Audio) 

* Operating system: Ubuntu 18.04

* Browser: Version 79.0.3945.130 (Official Build) (64-bit) & Karma/mocha ChromeHeadless tests

## Description
"this.add.text" crashes, seems that code should check the current renderer :

3.22.0.js:43566 Uncaught TypeError: Cannot read property 'gl' of null
    at Text.updateText (VM41 3.22.0.js:43566)
    at Text.setText (VM41 3.22.0.js:42902)
    at new Text (VM41 3.22.0.js:42572)
    at GameObjectFactory.text (VM41 3.22.0.js:155187)
    at Scene.create (eval at <anonymous> (frame.html:45), <anonymous>:15:26)
    at SceneManager.create (VM41 3.22.0.js:77900)
    at SceneManager.bootScene (VM41 3.22.0.js:77786)
    at SceneManager.start (VM41 3.22.0.js:78486)
    at SceneManager.bootQueue (VM41 3.22.0.js:77526)
    at EventEmitter.emit (VM41 3.22.0.js:1751)

...
if (this.renderer.gl) { // <= failing line!
     this.frame.source.glTexture = this.renderer.canvasToTexture(canvas,       
     this.frame.source.glTexture, true);
    this.frame.glTexture = this.frame.source.glTexture;
}
....

## Example Test Code
Using this example as a template( https://labs.phaser.io/edit.html?src=src/display/tint/text%20tint.js&v=3.22.0 ) : 

var config = {
    type: Phaser.HEADLESS,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        create: create
    }
};

var game = new Phaser.Game(config);

function create () {
    var text1 = this.add.text(100, 100, 'Phaser Text with Tint');
    text1.setTint(0xff00ff, 0xffff00, 0x0000ff, 0xff0000);
}

Thanks!

**Comment by mattjennings** [comment]
I am also running into this.

**Comment by raimon-segura** [comment]
As a  workaound you could check what is the render used:

if(this.game.config.renderType!=Phaser.HEADLESS){
    var text1 = this.add.text(100, 100, 'Phaser Text with Tint');
}

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
