### ISSUE TITLE
Tween onLoop event is never fired in a looping Timeline

### ISSUE THREAD

**Issue by monteiz** [photonstorm/phaser#4977]
## Version

* Phaser Version: 3.22.0

* Operating system: macOS Mojave 10.14.6

* Browser:

## Description

Not sure if this is the intended behaviour, but if I set an `onLoop` event of a `Tween`, and this tween is played in a looping `Timeline`, the `Tween` `onLoop` event is never fired. Same behaviour for `onRepeat`.

## Example Test Code

https://codepen.io/monteiz/pen/ExaqVmx

**Comment by samme** [comment]
For looping that's correct because the Tween and Timeline loops are distinct. In <https://codepen.io/monteiz/pen/ExaqVmx> the Timeline is looping but the Tween isn't, so the Tween's onLoop isn't called.

If you add `loop` and `repeat` values to the tween config there, onLoop and onRepeat will be called.

**Comment by photonstorm** [comment]
Just as @samme said. `Phaser.Tweens.Events#TIMELINE_LOOP` and `Phaser.Tweens.Events#TWEEN_LOOP` are two different events, a Timeline looping won't cause a Tween loop (and of course, the opposite is true)

**Comment by monteiz** [comment]
Thank you for your answers @samme and @photonstorm, this is what I suspected (and it makes sense).
But I have a use case which seems to be not covered, or maybe I am missing something. Here it is:

what if I want to have a looping Timeline composed by two tweens (A and B), with B having an absolute offset greater than zero, and I want a function to be called every time B is started/looped/repeated?
