### ISSUE TITLE
Create two Phaser instances & Spine plugin BUG - Only works the first instance

### ISSUE THREAD

**Issue by raimon-segura** [photonstorm/phaser#4979]
## Version

* Phaser Version:  Phaser v3.22.0 (Headless | Web Audio) 

* Operating system: Ubuntu 18.04

* Browser: Version 79.0.3945.130 (Official Build) (64-bit)

## Description
If you create two Phaser instances it shows a error message, Using Phaser examples shows this error:

> WebGL: INVALID_OPERATION: bufferSubData: no buffer
3.22.0.js:53724 WebGL: too many errors, no more errors will be reported to the console for this context.

But using a simple web page served with "php -S"/Apache without an Iframe, it shows a different message, but seems they are related:

> Uncaught TypeError: Cannot read property 'add' of undefined
    at SpineFile.addToCache (new_SpineWebGLPlugin.js:24516)
    at initialize.fileProcessComplete (new_phaser.min.js:1)
    at ImageFile.onProcessComplete (new_SpineWebGLPlugin.js:2714)
    at Image.data.onload (new_SpineWebGLPlugin.js:24640)

=== Function that fails of SpinePlugin
`addToCache: function ()
    {
        if (this.isReadyToProcess())
        {
            var fileJSON = this.files[0];

            fileJSON.addToCache();

            var atlasCache;
            var atlasKey = '';
            var combinedAtlasData = '';
            var preMultipliedAlpha = (this.config.preMultipliedAlpha) ? true : false;

            for (var i = 1; i < this.files.length; i++)
            {
                var file = this.files[i];

                if (file.type === 'text')
                {
                    atlasKey = file.key.substr(0, file.key.length - 2);

                    atlasCache = file.cache; // ==== BUG? : IT ADDS AN UNDEFINED

                    combinedAtlasData = combinedAtlasData.concat(file.data);
                }
                else
                {
                    var src = file.key.trim();
                    var pos = src.indexOf('_');
                    var key = src.substr(pos + 1);
       
                    this.loader.textureManager.addImage(key, file.data);
                }

                file.pendingDestroy();
            }

            atlasCache.add(atlasKey, { preMultipliedAlpha: preMultipliedAlpha, data: combinedAtlasData }); // FAILING LINE

            this.complete = true;
        }` 

=== SpinePlugin doesn't add a valid custom cache entry for the second instance 
`
function SpinePlugin (scene, pluginManager)
    {
        ScenePlugin.call(this, scene, pluginManager);

        var game = pluginManager.game;

        /**
         * A read-only flag that indicates if the game is running under WebGL or Canvas.
         *
         * @name SpinePlugin#isWebGL
         * @type {boolean}
         * @readonly
         * @since 3.19.0
         */
        this.isWebGL = (game.config.renderType === 2);

        /**
         * A custom cache that stores the Spine atlas data.
         * 
         * This cache is global across your game, allowing you to access Spine data loaded from other Scenes,
         * no matter which Scene you are in.
         *
         * @name SpinePlugin#cache
         * @type {Phaser.Cache.BaseCache}
         * @since 3.19.0
         */
        this.cache = game.cache.addCustom('spine'); // ==== BUG? : ONLY ASSIGN ON THE FIRST ONE
`

its related with https://github.com/photonstorm/phaser/issues/4986 & https://github.com/photonstorm/phaser/issues/4987 I think

## Example Test Code
Based on: https://labs.phaser.io/edit.html?src=src/spine/3.8/basic%20spineboy.js&v=3.22.0

// 1 =============================================
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    scene: {
        preload: preload,
        create: create,
        pack: {
            files: [
                { type: 'scenePlugin', key: 'SpinePlugin', url: 'plugins/3.8/SpinePlugin.js', sceneKey: 'spine' }
            ]
        }
    }
};
function preload ()
{
    this.load.image('logo', 'assets/sprites/phaser.png');
    this.load.setPath('assets/spine/3.8/demos/');
    this.load.spine('set1', 'demos.json', [ 'atlas1.atlas' ], true);
}
function create ()
{
    this.add.image(0, 0, 'logo').setOrigin(0);
    this.add.spine(400, 600, 'set1.spineboy', 'idle', true);
}
var game = new Phaser.Game(config);

// 2 =============================================
var config2 = {
    type: Phaser.WEBGL,
    parent: 'phaser-example-2',
    width: 600,
    height: 400,
    backgroundColor: '#2d2d2d',
    scene: {
        preload: preload2,
        create: create2,
        pack: {
            files: [
                { type: 'scenePlugin', key: 'SpinePlugin', url: 'plugins/3.8/SpinePlugin.js', sceneKey: 'spine' }
            ]
        }
    }
};
function preload2 ()
{
    this.load.image('logo', 'assets/sprites/phaser.png');
    this.load.setPath('assets/spine/3.8/demos/');
    this.load.spine('set1', 'demos.json', [ 'atlas1.atlas' ], true);
}

function create2 ()
{
    this.add.image(0, 0, 'logo').setOrigin(0);
    this.add.spine(200, 300, 'set1.spineboy', 'idle', true);
}
var game2 = new Phaser.Game(config2);

## Additional Information

Thanks!

**Comment by RollinSafary** [comment]
Hi rebuild the spine plugin and everything will work.
To do that navigate to `node_modules/phaser`. Open terminal call `npm i`, then run `npm run plugin.spine.dist`. And then run your project again.

**Comment by raimon-segura** [comment]
Hi Rollin!,

I've rebuilded the spine dist but unfortunately shows the same message, I've checked that new build is updated... 

Do you have any other idea?

Many Thanks!

**Comment by raimon-segura** [comment]
This bug is related to #4987 , now I install plugin with game config, like official examples. This bug appears also when I destroy & create Phaser instances, but works if I remove the pluin first :
`
game.plugins.removeScenePlugin('SpinePlugin');
game.destroy(true);
`

**Comment by photonstorm** [comment]
I've added this into the JSDocs, but it's definitely your responsibility to clear the plugin if you wish to destroy the game instance and then re-create it on the same page, without reloading.
