### ISSUE TITLE
Add setOrigin function in SpineGameObject like Sprite

### ISSUE THREAD

**Issue by raimon-segura** [photonstorm/phaser#4981]
Hi!,

I've made a simple game using Spine, the characters are positioned in a board made with tiles. 

The Spine object have the pivot/origin/anchor point at their feet, but in my game I have to use the ~center coordinate as a pivot/origin/anchor point. I could add to the SpineGameObject an offset(x,y) but then I should take care of that offset by hand. By the way "setOffset( [offsetX] [, offsetY]).setOffset( [offsetX] [, offsetY])" doesn't work for me. Anyway, the offset are in pixels insted of percentage like pivot/origin/anchor point

This pivot/origin/anchor point cannot be modified because SpineGameObject doesn't have the setOrigin function.

https://photonstorm.github.io/phaser3-docs/SpineGameObject.html

https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Components.Origin.html#setOrigin

Thanks!

**Comment by photonstorm** [comment]
This isn't a feature the Spine Runtimes provide to Phaser, so it's not something to easily expose in the plugin either. You'll have to just work with what the runtimes offer, I'm afraid.
