### ISSUE TITLE
PathFollower.startFollow broken between 3.21.0 and 3.22.0 ?

### ISSUE THREAD

**Issue by landrey** [photonstorm/phaser#4982]
It seems that startFollow does not take the duration when using phaser 3.22.0. 
In the joint example the triangle goes as fast as possible from the start of the line to the end on space hit. The funny part is that the evaluated elapsed time using onStart/onComplete callbacks is pretty good (5.0...s in the joint example). 

I browse a little in github between the versions of a couple of related files but I am not expert enough  to have found anything.

On Version 79.0.3945.130 (Official Build) (64-bit)/Ubuntu 18.04.3 LTS
Same issue with FireFox 72.0.2 (64-bit)

But using 3.21.0 (or older) things are ok. 

Btw, inline "official samples" seem  to have the same trouble:
ex: https://phaser.io/examples/v3/view/paths/followers/change-path#
https://phaser.io/examples/v3/view/paths/followers/basic-follower
Nothing is moving (or  everything moves once very fast) until you ask for 3.21.0 with the menu.
------------------------------------------------------------------------------------
To be used within a poor html page.

window.addEventListener("DOMContentLoaded", (event) => {
    'use strict';
    var config = {
        type: Phaser.AUTO,
        width: 800,
        height: 600,
	backgroundColor: '#2d2d2d',
	physics: {
            default: 'arcade',
            arcade: {
		gravity: {x: 0,  y: 0 },
		debug: true
            }
	},
        scene: {
	    init: init,
            preload: preload,
            create: create,
            update: update
        }
    };

    new Phaser.Game(config);
    var follower;
    var path;
    var graphics;
    
    function init(){

    }
    
    function preload () {
	
	//DEBUG
	window.scene=this;

	//this.load.image('player', '../assets/firstaid.png'); 
    }

    function create (){
	const line=new Phaser.Curves.Line(new Phaser.Math.Vector2(0,0), new Phaser.Math.Vector2(300, 300));
	let g=this.add.graphics({x:0, y:0});
	g.lineStyle(5, 0xFF0000, 1.0);
	line.draw(g);

	path = this.add.path(0, 0);
	path.add(line);
	
	g=this.add.graphics();
	g.setVisible(false);
	g.fillStyle(0x00ff00, 1);
	g.beginPath();
	g.moveTo(0,0);
	g.lineTo(30, 10);
	g.lineTo(0, 20);
	g.lineTo(0, 0);
	g.fillPath();
	g.generateTexture('player',60,40);
	follower = this.add.follower(path, 0, 0, 'player');

	window.follower=follower;
	this.cursors=this.input.keyboard.createCursorKeys();
    }
	
    function update(){
	var deltaT;
	if (this.cursors.space.isDown && !follower.isFollowing()){	    
	    follower.startFollow({
		duration: 5*1000,
		useFrames: false,
		from:0,
		to:1,
		repeat: 0,
		positionOnPath:true,
		rotateToPath: true,
		onComplete:()=>{ deltaT-=Date.now(); console.log("FINITO %s s",  -deltaT/1000); },
		onStart:()=>{ deltaT=Date.now(); console.log("STARTED"); },
	    });
	    
	    console.log("startFollow");
	   // follower.startFollow(4000);
	}
    }// update

    
});//  DOMContentLoaded

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
