### ISSUE TITLE
Inconsistent behavior of Tiled layer "properties" member 

### ISSUE THREAD

**Issue by Nightspeller** [photonstorm/phaser#4983]
## Version
* Phaser Version: 3.22.0
* Operating system: Windows 10
* Browser: firefox

## Description
class LayerData has a member 'properties' which type is specified as 'object', while actual type is inconsistent: in case layer (defined in Tiled) has properties - it is an array of objects, in case it has no properties - an empty object.

Expected behavior: type should be object[] and in case of no properties specified, member should be an empty array.

## Example Test Code

1. Create a Tiled map with 2 layers. On one layer specify some property.
2. On the scene, create a tilemap: `const map = this.make.tilemap({key: 'example}).`
3. Get the layers:  `const layer1 = map.layers[0]; const layer2 = map.layers[1];`
4. Look at the properties member of layer1 and layer2: `console.log(layer1.properties, layer2.properties)`
5. See that one layer properties is an empty object and the other - is an array (typescript also should show you a warning if you try to do anything with that array, like use '.forEach' since properties type is 'object').

## Additional Information
Solution in mind: change type of the 'properties' to object[] in definitions, and in the implementation (**as far as I understand**) change  `properties: GetFastValue(curl, 'properties', {})` to  `properties: GetFastValue(curl, 'properties', [])` in ParseTileLayers function. (again, this is according to my best understanding - dunno if that is all what needed to be done neither)

**Comment by samme** [comment]
That sounds right, you could make a PR. 🙂

**Comment by Nightspeller** [comment]
You know, I actually decided to try it out and create a fix and the PR. Here it is: https://github.com/photonstorm/phaser/pull/4984

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
