### ISSUE TITLE
Spine plugin cannot be installed, only from game config, constructor has two params instead of one? 

### ISSUE THREAD

**Issue by raimon-segura** [photonstorm/phaser#4986]
## Version

* Phaser Version:  Phaser v3.22.0 (Headless | Web Audio) 

* Operating system: Ubuntu 18.04

* Browser: Version 79.0.3945.130 (Official Build) (64-bit)

## Description
1. If I try to install the Spine Plugin instead of using game config shows the following error:
`
VM241:13067 Uncaught TypeError: Cannot read property 'game' of undefined
    at SpinePlugin.BasePlugin (<anonymous>:13067:35)
    at SpinePlugin.ScenePlugin [as constructor] (<anonymous>:12927:20)
    at new SpinePlugin (<anonymous>:6497:21)
    at PluginManager.createEntry (3.22.0.js:74482)
    at PluginManager.start (3.22.0.js:74458)
    at PluginManager.install (3.22.0.js:74351)
    at PluginFile.onProcess (3.22.0.js:170872)
    at LoaderPlugin.nextFile (3.22.0.js:173894)
    at PluginFile.onLoad (3.22.0.js:4233)
`

It come from spine constructor, has two params: 
https://github.com/photonstorm/phaser/blob/v3.22.0/plugins/spine/src/SpinePlugin.js#L111
`
function SpinePlugin (scene, pluginManager)
`

But the constructor its called from:
https://github.com/photonstorm/phaser/blob/v3.22.0/src/plugins/PluginManager.js#L591
`
var instance = new entry.plugin(this); // this => PluginManager
`

2. By the way, when its installed using game config, it calls from PluginManager.addToScene with two params
https://github.com/photonstorm/phaser/blob/v3.22.0/src/plugins/PluginManager.js#L272
`
var plugin = new source.plugin(scene, this);
`

There are so plugin examples that has only one param:
https://labs.phaser.io/edit.html?src=src/plugins/install%20global%20plugin%20at%20runtime.js&v=3.22.0

... why there are this two ways to write a plugin constructor? ..it should only one for all, right?

3. To workaround this I use in preload function:
`
this.game.plugins.installScenePlugin('SpinePlugin',  window.SpinePlugin, 'spine', this.scene.scene, true);
`

Note that last param is true (fromLoader) , so that way I avoid the PluginCache.hasCore check when I destroy & create again the Phaser instance
https://github.com/photonstorm/phaser/blob/v3.22.0/src/plugins/PluginManager.js#L373
`
        .....
        else if (!fromLoader && PluginCache.hasCore(key))
        {
            //  Plugin wasn't from the loader but already exists
            console.warn('Scene Plugin key in use: ' + key);
            return;
        }
        ...
` 

4. its related with https://github.com/photonstorm/phaser/issues/4979 & https://github.com/photonstorm/phaser/issues/4987 I think

## Example Test Code
based on: https://labs.phaser.io/edit.html?src=src/spine/3.8/basic%20spineboy.js&v=3.22.0
`
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    scene: {
        preload: preload,
        create: create,
       /* 
       pack: {
            files: [
                { type: 'scenePlugin', key: 'SpinePlugin', url: 'plugins/3.8/SpinePlugin.js', sceneKey: 'spine' }
            ]
        }
        */
    }
};

var game = new Phaser.Game(config);

function preload (){
    this.load.plugin('SpinePlugin', 'plugins/3.8/SpinePlugin.js', true, 'spine');
    this.load.image('logo', 'assets/sprites/phaser.png');

    // this.load.setPath('assets/spine/3.8/demos/');
    // this.load.spine('set1', 'demos.json', [ 'atlas1.atlas' ], true);
}

function create (){
    this.add.image(0, 0, 'logo').setOrigin(0);
    // this.add.spine(400, 600, 'set1.spineboy', 'idle', true);
}
`

**Comment by samme** [comment]
That's the wrong load method. You would use [scenePlugin()](https://photonstorm.github.io/phaser3-docs/Phaser.Loader.LoaderPlugin.html#scenePlugin).

```javascript
this.load.scenePlugin('SpinePlugin', 'plugins/3.8/SpinePlugin.js', 'spine', 'spine');
```

**Comment by raimon-segura** [comment]
I use `import * as SpinePlugin from 'phaser_spine';` to import Spine into Phaser. Only install , 
& installScenePlugin accepts "The plugin code. This should be the non-instantiated version" , https://photonstorm.github.io/phaser3-docs/Phaser.Plugins.PluginManager.html

This bug is related to https://github.com/photonstorm/phaser/issues/4987 , now I install plugin with game config, like official examples. So I don't use installScenePlugin anymore .

**Comment by samme** [comment]
Ok, but this isn't a Phaser bug. The error comes from using the wrong load method.
