### ISSUE TITLE
Phaser.Plugins.Cache doesn't remove at game destroy using ES6 & Vue

### ISSUE THREAD

**Issue by raimon-segura** [photonstorm/phaser#4987]
## Version

* Phaser Version:  Phaser v3.22.0 (Headless | Web Audio) 

* Operating system: Ubuntu 18.04

* Browser: Version 79.0.3945.130 (Official Build) (64-bit)

## Description
If I destroy a game instance and then create again Phaser.Plugins.Cache has entries, so PluginManager cannot create a new plugin instance again:
`
...
        else if (!fromLoader && PluginCache.hasCore(key))
        {
            //  Plugin wasn't from the loader but already exists
            console.warn('Scene Plugin key in use: ' + key);
            return;
        }
....
`
https://github.com/photonstorm/phaser/blob/v3.22.0/src/plugins/PluginManager.js#L373

It doesn't happen in Phaser examples... Is it needs any other call beside destroy? 

I've used the workaround of https://github.com/photonstorm/phaser/issues/4986

## Example Test Code
`
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    scene: {
        preload: preload,
        create: create,
plugins = {
                scene: [
                    { key: 'SpinePlugin', plugin: window.SpinePlugin, mapping: 'spine', start: true, sceneKey: 'spine' }
                ],
/*
        pack: {
            files: [
                { type: 'scenePlugin', key: 'SpinePlugin', url: 'plugins/3.8/SpinePlugin.js', sceneKey: 'spine' }
            ]
*/
        }
    }
};

var game = new Phaser.Game(config);

setTimeout(function(){
    game.destroy(true)
},1000);

setTimeout(function(){
    game = new Phaser.Game(config);
},2000);

function preload ()
{
    this.load.image('logo', 'assets/sprites/phaser.png');
    this.load.setPath('assets/spine/3.8/demos/');
    this.load.spine('set1', 'demos.json', [ 'atlas1.atlas' ], true);
}

function create ()
{
    this.add.image(0, 0, 'logo').setOrigin(0);
    this.add.spine(400, 600, 'set1.spineboy', 'idle', true);
}

`

**Comment by samme** [comment]
I think that's expected. You can do 

```javascript
game.plugins.removeScenePlugin('SpinePlugin');
game.destroy(true);
```

**Comment by raimon-segura** [comment]
YEAH!!!! .. your are right! , now it works like a charm. 

I didn't realize, I guess this is the right way to do it if you destroy & create Phaser instaces.

Many Thanks! ..bug closed :D

**Comment by raimon-segura** [comment]
Just a little comment, seems that in test/headless mode has the same issue, so if I use installScenePlugin to install, insted game config, all works as expected

this.game.plugins.installScenePlugin('SpinePlugin', window.SpinePlugin, 'spine', this.scene.scene, true);
