### ISSUE TITLE
Spine Plugin crashes in HEADLESS mode

### ISSUE THREAD

**Issue by raimon-segura** [photonstorm/phaser#4988]
## Version

* Phaser Version:  Phaser v3.22.0 (Headless | Web Audio) 

* Operating system: Ubuntu 18.04

* Browser: Version 79.0.3945.130 (Official Build) (64-bit) & Karma/mocha ChromeHeadless tests

## Description
"this.add.text" crashes, seems that code should check the current renderer :

VM53:26911 Uncaught TypeError: Cannot read property 'height' of null
    at SpineGameObject.updateSize (<anonymous>:26911:31)
    at SpineGameObject.setSkeleton (<anonymous>:26710:21)
    at new SpineGameObject (<anonymous>:26390:18)
    at GameObjectFactory.add [as spine] (<anonymous>:6666:27)
    at Scene.create (eval at <anonymous> (frame.html:45), <anonymous>:33:14)
    at SceneManager.create (VM42 3.22.0.js:77900)
    at SceneManager.loadComplete (VM42 3.22.0.js:77812)
    at LoaderPlugin.emit (VM42 3.22.0.js:1754)
    at LoaderPlugin.loadComplete (VM42 3.22.0.js:173994)
    at LoaderPlugin.fileProcessComplete (VM42 3.22.0.js:173960)

https://github.com/photonstorm/phaser/blob/v3.22.0/plugins/spine/src/gameobject/SpineGameObject.js#L761
...
var height = renderer.height;
....

## Example Test Code
Using this example as a template( https://labs.phaser.io/edit.html?src=src/spine/3.8/basic%20spineboy.js&v=3.22.0 ) : 

var config = {
    type: Phaser.HEADLESS,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    scene: {
        preload: preload,
        create: create,
        pack: {
            files: [
                { type: 'scenePlugin', key: 'SpinePlugin', url: 'plugins/3.8/SpinePlugin.js', sceneKey: 'spine' }
            ]
        }
    }
};

var game = new Phaser.Game(config);

function preload (){
    this.load.image('logo', 'assets/sprites/phaser.png');
    this.load.setPath('assets/spine/3.8/demos/');
    this.load.spine('set1', 'demos.json', [ 'atlas1.atlas' ], true);
}

function create (){
    this.add.image(0, 0, 'logo').setOrigin(0);
    this.add.spine(400, 600, 'set1.spineboy', 'idle', true);
}

Thanks!

**Comment by raimon-segura** [comment]
I've found a workaround, just create a renderer object literal if its a test:
`
if(process.env.NODE_ENV=="testing"){
            try {
              this.game = new Phaser.Game(config)
              this.game.renderer = {width:100, height:100, preRender: function(){}, postRender: function(){}, render: function(){}}
            }
            catch(error) {
              console.error("===========================================================\n"+error)
            }        
`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
