### ISSUE TITLE
Cannot read property ‚inline‘ of undefined at chrome-extension

### ISSUE THREAD

**Issue by ouya99** [photonstorm/phaser#4993]
## Version

* Phaser Version: 3.19.0

* Operating system: Linux Mint 18.3 (Desktop) / Mac Sierra (Notebook, also here the browser is not responsive suddenly)

* Browser: Chrome v79

## Description

Suddenly (out-of-nowhere) 
I am getting this
**Uncaught (in promise) TypeError: Cannot read property ‚inline‘ of undefined at chrome-extension://g…… include.preload.js** error
in Chrome, when launching my game in the chrome browser and then my whole computer is super super slow (I hardly manage to close the browser tab -> everything normal then)

In Firefox there is no error message, but it is also very slow, but the game works

Thanks for any hint

**Comment by ouya99** [comment]
seems like a complete cache clear on the browser helped. Strange that this error happened on all computers and browsers though

**Comment by KopteLove** [comment]
this script is part of AdBlock, just reinstall the extension &#129304;

**Comment by aleksandrnikitenko** [comment]
> this script is part of AdBlock, just reinstall the extension 🤘

Thats it! Thank you!
