### ISSUE TITLE
Typescript definitions - body.onfloor

### ISSUE THREAD

**Issue by gnesher** [photonstorm/phaser#4994]
## Version

* Phaser Version: 3.22.0
* Operating system: windows 10
## Description
physics.add.sprite returns a Phaser.Physics.Arcade.Sprite which includes a body property that is either  Phaser.Physics.Arcade.Body or Phaser.Physics.Arcade.StaticBody
Since StaticBody does not contain the onfloor method, Typescript throws an error when you try to run
player.body.onFloor()

**Comment by bmpickford** [comment]
This is a typescript thing, not so much phaser
From the Typescript docs:
`If we have a value that has a union type, we can only access members that are common to all types in the union.`

https://www.typescriptlang.org/docs/handbook/advanced-types.html#union-types

**Comment by bmpickford** [comment]
If you want to access onFloor() you could always do something like `const body = player.body as Phaser.Physics.Arcade.Body;` and then you'll be access it without it throwing an error

**Comment by gnesher** [comment]
@bmpickford while you are technically correct, union types should generally be used when we want to use only those properties that are shared by both types. If we use it in a way that throws an error when I try to access certain properties/methods than we are probably doing something wrong :/

I've got a few ideas on how we can fix this, but I really need to understand if this is something we are willing to change as there are quite a few similar problems across the framework

**Comment by samme** [comment]
```typescript
export type ArcadeImageWithBody        = Phaser.Physics.Arcade.Image   & { body: Phaser.Physics.Arcade.Body       };
export type ArcadeImageWithStaticBody  = Phaser.Physics.Arcade.Image   & { body: Phaser.Physics.Arcade.StaticBody };
export type ArcadeSpriteWithBody       = Phaser.Physics.Arcade.Sprite  & { body: Phaser.Physics.Arcade.Body       };
export type ArcadeSpriteWithStaticBody = Phaser.Physics.Arcade.Sprite  & { body: Phaser.Physics.Arcade.StaticBody };
export type GameObjectWithBody         = Phaser.GameObjects.GameObject & { body: Phaser.Physics.Arcade.Body       };
export type GameObjectWithStaticBody   = Phaser.GameObjects.GameObject & { body: Phaser.Physics.Arcade.StaticBody };
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
