### ISSUE TITLE
maxWidth has no effect on DynamicBitmapText

### ISSUE THREAD

**Issue by AndreaBoeAbrahamsen** [photonstorm/phaser#4997]
## Version

* Phaser Version: 3.22.0

* Operating system: Windows 10

* Browser: Chrome, Edge, Firefox

## Description

When using DynamicBitmapText, setting maxWidth does not seem to have any effect.

## Example Test Code

https://codesandbox.io/s/dynamicbitmaptext-setmaxwidth-oc20p

## Additional Information

Setting maxWidth for static BitmapText works well.

**Comment by AndreaBoeAbrahamsen** [comment]
Been reading some of the source code, could it be as simple as adding this to the render function I wonder:
`    //  Update the bounds - skipped internally if not dirty
    var bounds = src.getTextBounds(false);

    //  In case the method above changed it (word wrapping)
    if (src.maxWidth > 0)
    {
        text = bounds.wrappedText;
        textLength = text.length;
    }`
I am going to test it out tomorrow

**Comment by photonstorm** [comment]
It's not supposed to have any effect, as it can be completely overwritten by the layout callback, so it should be enforced within that. Unfortunately, it gets inherited from the static version automatically, but really ought to be removed from the docs for dynamic specifically.

**Comment by AndreaBoeAbrahamsen** [comment]
I understand your decision, though I do find using the displayCallback for this task to seem much more complicated as of now, and I tried adding the code above to the render function and seem to work well, I am fin with the maxWidth not effecting the result of the displayCallback function, so I think I will be looking into overriding the render function for my game.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
