### ISSUE TITLE
Lighting System

### ISSUE THREAD

**Issue by tybeck** [photonstorm/phaser#4999]
* Phaser Version: 3.22.0
* Operating system: Mac/Windows/All Above
* Browser: Chrome/FF

**Example:** https://phaser.io/examples/v3/view/game-objects/lights/blitter-light

Please review above example.  I'm not seeing lights working within 3.22.0 since 3.15.1, after calling `addLight` I don't see any light source other than the ambient color that you can set within 3.22.0.   If you switch the phaser code engine to 3.15.1 you'll see the light sources show up.  Is there something breaking with this example that I'm not aware of?  I reviewed the API documentation and it looks good, but I can't get any lights to work.

**Comment by photonstorm** [comment]
The Light System is now deprecated and will be removed in 3.23, as it never quite worked the way it was meant to, and is now just adding dead weight to the API. The ability to load normal maps and bind them to textures will remain, so you're able to use those with your own lighting shaders or pipelines, which is a much more sensible route, longer-term.

**Comment by tybeck** [comment]
Thanks, I had a feeling this was true - thanks for the quick response!

**Comment by photonstorm** [comment]
Yeah, it's a bit of a pain, but I'd rather remove it and fix it up properly, then add it back again - than leave it in there in its broken state. And as I don't have a concrete eta on when I can do this, I don't want to have to delay 3.23 because of it. Thanks for understanding.
