### ISSUE TITLE
Scene.add() not returning any scene

### ISSUE THREAD

**Issue by renatodex** [photonstorm/phaser#5002]
## Version
Phaser Version: 3.22
Operating system: MacOS
Browser: Last Chrome

## Description

Hello! I'm the author of this Package based on Phaser:
https://github.com/renatodex/grider

I'm having an issue with Phaser Scenes. It's not urgent, but it's bothering me.
I've created a simple `Phaser.Game` instance, and added the Scene right after.

The documentation from Phaser states that:
![image](https://user-images.githubusercontent.com/68507/74405073-0133cc00-4e0b-11ea-9ac8-7e481af96a9c.png)
"Scene will be returned from the `add` method if it was said to be added immediately".

However, the scene.add() method always returns null.
Maybe I forgot something?

I've been using the `Phaser.Events.EventEmitter` to work around this issue, but I would like to understand why it's happening. And if possible, know if there is some good practice around this, since I want to add the scenes programmatically, and not in the Phaser Game object.

## Example Test Code

https://jsfiddle.net/fuzo2hcr/1/

## Additional Information

This is the console showing that the add method is not a method from null (Because the scene is null)
![image](https://user-images.githubusercontent.com/68507/74404474-5b339200-4e09-11ea-8a6b-c0115dd66537.png)

**Comment by photonstorm** [comment]
Looking at your fiddle, at the point at which you add the Scene, the game has not yet booted, so returning `null` is correct. Had the game booted, it would have returned the Scene instance. Instantiating the Game class doesn't immediately boot it (there are DOM events it will wait for, first). 

So you either need to delay adding the Scene until the Game has emitted its boot event, or get a reference to it from within the Game itself.

**Comment by photonstorm** [comment]
Also, `input: queue` doesn't do anything in 3.22 anymore, just in case you thought it did.

**Comment by renatodex** [comment]
Oh, thanks for your quick response @photonstorm!
Is there an event or something that triggers after the Game is booted?

Looking to the Getting started section from `phaser.io`, they show only 2 events that seem to make sense only if you start the `Phaser.Game` object with a Scene attached to it.

![image](https://user-images.githubusercontent.com/68507/74481103-d8eeb080-4e90-11ea-955a-2bd7a348ddc5.png)

But what if you don't start with the scene attached and add the scene later as I did?
There is a `GameCreated` event or something?

**Comment by photonstorm** [comment]
Yes, I would use this one: https://photonstorm.github.io/phaser3-docs/Phaser.Core.Events.html#event:READY__anchor

```
const game = new Phaser.Game(...);

game.events.on('ready', () => {
  // your Scene stuff can go here
}
```

**Comment by samme** [comment]
```js
new Phaser.Game({
  callbacks: {
    postBoot: function (game) {
      game.add.scene(…);
    }
  }
});
```
