### ISSUE TITLE
GameObjectFactory video returns Phaser.GameObjects.Image

### ISSUE THREAD

**Issue by majalon** [photonstorm/phaser#5003]
I'm getting an error in TypeScript when I use this.add.video because I'm receiving a Phaser.GameObjects.Image and I cannot use the play method.

`video(x: number, y: number, texture: string, frame?: string | integer): Phaser.GameObjects.Image;
`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by NavidMitchell** [comment]
That is great news, I was wondering about this as well. Thanks for all the great work!
