### ISSUE TITLE
Utils Size Examples are calling translate on graphics instance instead of translateCanvas.

### ISSUE THREAD

**Issue by atursams** [photonstorm/phaser#5005]
## Version

* Phaser Version: 3.22.0

* Operating system: Windows 10

* Browser: Any

## Description

The examples under `Utils -> Size` are calling `translate `on a `Graphics` object instead of `translateCanvas` which is the current name of the method.

I would push a fix but I never did a push request before to a repository on Github.

**Comment by halilcakar** [comment]
@atursams I've just checked all of the examples under `Utils ->Size`. They all use `translateCanvas` 😄

**Comment by photonstorm** [comment]
Yeah I fixed them a few days ago.
