### ISSUE TITLE
Utils RBush Examples is not using left, top, right, bottom members.

### ISSUE THREAD

**Issue by atursams** [photonstorm/phaser#5006]
## Version

* Phaser Version: 3.22.0

* Operating system: Windows 10

* Browser: Chrome / Explorer

## Description

The first RBush example is not using left, top, right, bottom,  members and that's why its search returns no results. The second Rbush example freezes on my browsers.

**Comment by photonstorm** [comment]
Thank you for reporting a problem with these examples. They have now been fixed. You can find the updated versions in this repo and on the labs.phaser.io site.
