### ISSUE TITLE
Firefox, IndexSizeError, Animation

### ISSUE THREAD

**Issue by Maeggi** [photonstorm/phaser#5008]
Phaser v3.22.0 (Canvas | Web Audio)

```
this.load.spritesheet('smoke', 'assets/smoke.png', { frameWidth: 40, frameHeight: 40, endFrame: 0 });

var deadeconfig = {
      key: 'deadplode',
      frames: this.anims.generateFrameNumbers('smoke', { start: 0, end: 5, first: 0 }),
      frameRate: 10
};

this.anims.create(deadeconfig);

var boom = this.add.sprite(this.player.x, this.player.y, 'smoke');
boom.depth = 10;
boom.anims.play('deadplode');
```
Console.log: IndexSizeError: Index or size is negative or greater than the allowed amount

Works in Chrome, but not in Firefox. What can I do?

**Comment by photonstorm** [comment]
Where is the actual error coming from? Which line of code?

Also, remove `endFrame: 0` from the `load.spritesheet` - as that basically says "there aren't any frames in this spritesheet", which I assume isn't the actual case.

**Comment by Maeggi** [comment]
Tahnks,  it works wonderfully
