### ISSUE TITLE
How to destroy every object in phaser 3

### ISSUE THREAD

**Issue by alearm246** [photonstorm/phaser#5009]
I'm currently trying to destroy any reference to any of my objects in my game when I switch level. Is there a way to destroy everything using phaser instead of me trying to build my own destroyEverything method.

**Comment by samme** [comment]
If you're using scenes then [scene.remove()](https://photonstorm.github.io/phaser3-docs/Phaser.Scenes.ScenePlugin.html#remove) will help. But other than that Phaser can't really know how you're using references.

**Comment by alearm246** [comment]
> If you're using scenes then [scene.remove()](https://photonstorm.github.io/phaser3-docs/Phaser.Scenes.ScenePlugin.html#remove) will help. But other than that Phaser can't really know how you're using references.

Alright thanks I’ll try that.

**Comment by halilcakar** [comment]
Removing scene is an option yes but i'm mostly just creating a level group and add every object in that level inside this group i created. And destroying the group after that.

**Comment by RollinSafary** [comment]
Nothing can help you to handle custom references in 100% cases. The best way is to handle that manually. If your game level is a scene, you can create 'destroy' method and handle there your references, then call scene remove, if level is a group or container, so override destroy function.
And never forget to remove all event listeners from object you're trying to destroy.

**Comment by hexus** [comment]
Thanks for helping here, everyone. In future, @alearm246, I'd recommend keeping general development questions to the following channels as mentioned in Phaser's Bug Report template:

> This repo should not be used for technical support. If you're struggling to use Phaser then post your question to the [forum](https://phaser.discourse.group/), [Slack](https://phaser.io/community/slack) or [Discord](https://phaser.io/community/discord) channels. GitHub Issues are for bugs and feature requests only.
