### ISSUE TITLE
Rotated frames in an Atlas appear to be working incorrectly

### ISSUE THREAD

**Issue by atursams** [photonstorm/phaser#5012]
## Version

* Phaser Version: 3.22.0

* Operating system: Windows 10

* Browser: Chrome

## Description

Rotated frames are mirrored vertically and then stretched to the correct rotated size.

## Example Test Code

[Example](https://phaser.io/examples/v3/view/textures/rotated-frames-from-single-atlas#)

**Comment by photonstorm** [comment]
This example should be removed as the feature isn't part of Phaser 3.

**Comment by photonstorm** [comment]
Thank you for reporting a problem with this example. It has now been removed from the repo.

**Comment by klwfwdk** [comment]
> Thank you for reporting a problem with this example. It has now been removed from the repo.

Does this mean that the latest version of Phaser no longer supports atlas containing rotated frames?

**Comment by photonstorm** [comment]
No version of Phaser 3 supported this. It was in a beta version but removed as it broke too many things and won't be implemented until v4.
