### ISSUE TITLE
Flickering pixels near sprites

### ISSUE THREAD

**Issue by atursams** [photonstorm/phaser#5015]
## Version

* Phaser Version: 3.22.0

* Operating system: Windows 10

* Browser: Chrome/Firefox/Edge

## Description

I see tiny gray pixels appear and flicker near moving sprites
![halo2](https://user-images.githubusercontent.com/59334483/75096445-5361b380-55a8-11ea-84d0-043853ddbab5.png)
![halo](https://user-images.githubusercontent.com/59334483/75096451-5b215800-55a8-11ea-889e-c1fe44eead51.png)

## Example Test Code

[dist.zip](https://github.com/photonstorm/phaser/files/4239665/dist.zip)
The code is placing images on the scene and then moving them.

## Additional Information

This issue happens when the sprite is positioned on a non-integer (fraction) value. However, because of the nature of Arcade (in this case) physics the position is often not an integer during movement and setting it to an integer at the end of the update loop does not solve the issue.

It looks similar to the tile extrude issue but in this case extruding does not seem to be a sloution.
I solved this by turning on pixelArt mode but the issue is strange to me... The gray lines appear near places that are not gray so I don't know what is causing them and why would that be a desired behavior.

**Comment by samme** [comment]
Are you using a spritesheet or texture atlas?

**Comment by atursams** [comment]
Hi Samme,
I was using a single png image.

Inside preload()
`this.load.image('gurl', 'assets/game_main_object.png');`

Inside create()
`this.playerObject = this.physics.add.image(0, 0, 'gurl');`

**Comment by spayton** [comment]
When the images are drawn on fractional positions the source pixels get sampled at surrounding positions so can drag in information from nearby pixels.  When the sampling occurs at a texture edge, the renderer can either 'clamp' to that edge or 'wrap' to the opposite edge.

In your case, the grey line on the right of the characters neck is coming from the hair on the left edge.  If you delete that chunk of hair from the image, I'm sure the grey line will disappear.  Similarly, for the monster thing, the flickering pixels will be from the tips of the spikes on the opposite edge.

Easiest fix is to border of transparency around these images.  I'd suggest a 2 pixel border.

**Comment by atursams** [comment]
Hi spayton, thanks a lot for helping me under things! Now I can turn off pixel art mode.

**Comment by spayton** [comment]
Thanks.

And its all down to using 3d hardware for a 2d job, so it won't go away.  My VIC-20 can chuck a sprite on the screen with more accuracy.
