### ISSUE TITLE
SpineGameObject's setFlipX method not working. 

### ISSUE THREAD

**Issue by cristlee** [photonstorm/phaser#5016]
## Version

* Phaser Version: 3.22
* Operating system: MacOs
* Browser: Chrome

## Description

The SpineGameObject's setFlipX method not working. 

## Example Test Code
```javascript
var spineGameObject = this.scene.add.spine(0, 0, 'spineName', 'animationName', false)
spineGameObject.setFlipX()
```

**Comment by spayton** [comment]
FlipX/Y was replaced with scaleX/Y in the Spine runtimes 3.7.  There may have been the intention for Phaser3's Spine plugin to emulate this old functionality, but currently it doesn't do anything.

Use the spine objects scaleX/scaleY, it combines scaling and flipping functionality, with negative values setting the flip.

**Comment by cristlee** [comment]
> FlipX/Y was replaced with scaleX/Y in the Spine runtimes 3.7. There may have been the intention for Phaser3's Spine plugin to emulate this old functionality, but currently it doesn't do anything.
> 
> Use the spine objects scaleX/scaleY, it combines scaling and flipping functionality, with negative values setting the flip.

Got it, thanks
