### ISSUE TITLE
MatterDebugConfig types

### ISSUE THREAD

**Issue by Jazcash** [photonstorm/phaser#5017]
* Phaser Version: 3.23.0-beta1

## Description

https://photonstorm.github.io/phaser3-docs/Phaser.Types.Physics.Matter.html

The docs/defs for MatterDebugConfig have a bunch of properties typed as Boolean, but their names and defaults imply they should allow numbers. E.g.

![image](https://user-images.githubusercontent.com/1434248/75112258-df6feb80-5639-11ea-929a-020a2d0c429c.png)

**Comment by hexus** [comment]
Hmm, looks like they should be `integer`. Do you have a list of all the properties you deem affected? No worries if not, we can go through them either way.

**Comment by Jazcash** [comment]
https://photonstorm.github.io/phaser3-docs/Phaser.Types.Physics.Matter.html#.MatterDebugConfig

![image](https://user-images.githubusercontent.com/1434248/77097834-4d28f080-6a09-11ea-9438-69d10a3b2c35.png)

All the ones highlighted here

**Comment by hexus** [comment]
Thanks :+1:

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
