### ISSUE TITLE
drag and click can not use together

### ISSUE THREAD

**Issue by akeboshi1** [photonstorm/phaser#5021]
## Version

* Phaser Version:3.19.0

* Operating system:Chrome OS Version 79

* Browser:

## Description

When drag and click listen at the same time, they will have an effect on both events at the same time. What to do in the phaser

**Comment by halilcakar** [comment]
Hi @akeboshi1,

I think you might use POINTER_UP event for to fire click events, I'm not sure if this is your case where you wanna drag first fire click event second? if this is the case, just listen up event and done! :)

**Comment by RollinSafaryCW** [comment]
@akeboshi1 You can just use `dragDistanceThreshold` or `dragTimeThreshold`
```
this.input.dragDistanceThreshold
this.input.dragTimeThreshold
```

using `dragDistanceThreshold` will fire `dragstart` event only when user have moved pointer by `dragDistanceThreshold`  pixels.
using `dragTimeThreshold` will fire `dragstart` event only if pointer still down after `dragTimeThreshold` ms.

**Comment by akeboshi1** [comment]
> 嗨@ akeboshi1，
> 
> 我认为您可能会使用POINTER_UP事件来触发点击事件，但是我不确定这是否是您要拖动第二个触发点击事件的情况？如果是这种情况，请监听事件并完成！:)

Hi halilcakar, I am using pointerdown, up, and move to simulate drag and drop for the moment. I need to press and hold the edit status in my project. If you use drag, you may have to pay attention to whether there is a shift after clicking, but this may not be very good in code. Good control, thank you for giving me ideas, useful

**Comment by akeboshi1** [comment]
> @ akeboshi1您可以使用`dragDistanceThreshold`或`dragTimeThreshold`
> 
> ```
> // `this` is current scene
> this.input.dragDistanceThreshold
> this.input.dragTimeThreshold
> ```
> 
> 仅当用户按 像素移动指针时，using `dragDistanceThreshold`才会触发`dragstart`事件`dragDistanceThreshold`。仅当指针在ms 之后仍然向下时，
> using `dragTimeThreshold`才会触发`dragstart`事件`dragTimeThreshold`。


Yes, this is useful! I used pointerdown and other events to simulate drag and drop, and simulated clicks through up and down time to meet the needs of the project. Thank you.

**Comment by halilcakar** [comment]
Sure! But why aren't you just use normal drag events instead using pointerdown, up, and move to simulate drag and drop?

**Comment by akeboshi1** [comment]
> Sure! But why aren't you just use normal drag events instead using pointerdown, up, and move to simulate drag and drop?

Because of this, in the pointerdown event, I can handle the requirements of dragging and long-press design patterns required by the project. If drag is used, then long press and drag become two methods, I can't judge whether it is long press or drag

**Comment by RollinSafaryCW** [comment]
> I can't judge whether it is long press or drag

You can, you've `dragDistanceTrashold`, which differs drag and press. You can check that with `pointer.dragState`. You can keep long press logic on `pointerdown` and implement dragging with events for dragging.

**Comment by akeboshi1** [comment]
> > 我无法判断是长按还是拖曳
> 
> 您可以拥有`dragDistanceTrashold`，这与拖放不同。您可以使用进行检查`pointer.dragState`。您可以保持长按逻辑`pointerdown`并使用事件进行拖动以进行拖动。
> 
> PS
> 我正在研究的游戏是纸牌游戏，一次有多种玩法。
> 
> 1. 玩家可以拖动卡来玩
> 2. 玩家可以将卡拖回以取消卡玩
> 3. 玩家可以点击卡牌来玩
> 4. 纸牌可以有1个以上的可能动作，玩家可以长按卡以查看可能的动作。
> 5. 玩家只需轻按几下棋牌，然后单击到突出显示的位置即可玩。
> 
> 所有这些在我的游戏中都运作良好。我为此使用了拖动事件。


Ok i'll try the way you say

**Comment by halilcakar** [comment]
> > I can't judge whether it is long press or drag
> 
> You can, you've `dragDistanceTrashold`, which differs drag and press. You can check that with `pointer.dragState`. You can keep long press logic on `pointerdown` and implement dragging with events for dragging.
> 
> P.S.
> The game I'm working on, is card game and there are multiple playing mechanics at once.
> 
> 1. Player can drag card to play
> 2. Player can drag card back to cancel card play
> 3. Player can just tap on card to play
> 4. Card can have more than 1 possible moves, player can long-press the card to see possible moves.
> 5. Player can just tap on card with multiple moves and then click to high-lighted place to play.
> 
> And all of this is working pretty well in my game. And I'm using dragging events for that.

Make sense when you think about this 👍
