### ISSUE TITLE
Tween onstop event missing

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#5030]
Hi, I'm using tweens to animate my UI components, and sometimes there is a need to kill tweens then start another tween, I'm using promises for tweens and I need to resolve promise if tween was killed.
`this.scene.tweens.killTweensOf` calls stop on running tweens, but there are no emitting events to handle tween killing. So if it's possible, please implement `stop` or `kill` event on tween stop.

Thanks in advance.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
