### ISSUE TITLE
getMultiple with GroupConfig

### ISSUE THREAD

**Issue by atursams** [photonstorm/phaser#5031]
Hi,

It would be nice if there was a build in method to get more than one game object from a group.
This could be used with Phaser.Action and Tween to get a few game objects and position them in a certain formation and move them around.

Another option:
I noticed that Phaser has a useful `GroupConfig` type that let's us create multiple game objects quickly with relatively simple code.

Phaser also has a `get` method that let's you recycle an existing instance by getting an inactive one.

It would be nice to have getMultiple so you could recycle multiple game objects neatly and simply.

**Comment by samme** [comment]
Could add `Group#getAll(property, value, startIndex, endIndex)` → [GetAll()](https://photonstorm.github.io/phaser3-docs/Phaser.Utils.Array.html#.GetAll "Phaser.Utils.Array.GetAll()")

**Comment by atursams** [comment]
I don't understand?

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
