### ISSUE TITLE
Wrong game scale in iPhone when game is embedded in iframe.

### ISSUE THREAD

**Issue by scott20145** [photonstorm/phaser#5034]
## Version

* Phaser Version: v3.20.0

* Operating system: iOS 12.4.4

* Browser: Safari
* Device: iPhone6

## Description

I tried load the game inside the iframe in portrait mode, 
the iframe size is full width, and height is about 1/2, but scaleManager doesn't scale down the game  size to fit the iframe. As a result, I can only see partial of the game.

The behavior is correct in desktop, and other android browsers.
It seems only occurs in almost all iPhone devices, I also tried Chrome and still no luck.

I also tried:
1. initialize the game after a delay. - not working
2. call `this.game.scale. setGameSize()` every few seconds. - not working  

**EXPECTED RESULT**: The game should exactly fill the iframe(container).

## Example Test Code

The Game Scale Config:
```
const config: Phaser.Types.Core.GameConfig = {
	type: Phaser.AUTO,
	parent: "canvas",
	width: size.width,
	height: size.height,
	backgroundColor: 0,
	transparent: true,
	scale: {
		mode: Phaser.Scale.FIT,
		autoCenter: Phaser.Scale.CENTER_BOTH
	},
	dom: {
		createContainer: true,
		behindCanvas: false
	}
};
```

Testing html:
```
<!doctype html>
<html>

<head>
	<meta name="viewport"
		content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no,shrink-to-fit=no">
	<% if(htmlWebpackPlugin.options.weinreScript) { %>
	<script src="<%= htmlWebpackPlugin.options.weinreScript %>"></script>
	<% } %>

	<style>

		iframe {
			border: none;
			display: block;
			position: absolute;
			width: 100%;
			margin: 0 auto;
			bottom: 52px;
			height: 307px;
		}

	</style>
</head>

<body>
	<div id="debug"></div>
	<div id="root">
		<iframe src="http://localhost:8080/index.html" frameborder="0"></iframe>
	</div>
</body>

</html>
```

**Comment by samme** [comment]
Screenshot?

What are the contents of `http://localhost:8080/index.html`?

**Comment by scott20145** [comment]
**game html**
```
<style>
html,
body {
	height: 100%;
	width: 100%;
	margin: 0;
}

.zindex-top {
	z-index: 1 !important;
	pointer-events: inherit !important;
}


canvas {
	display: block;
	margin: 0;
	position: absolute;
	top: 0%;
}
</style>
<body>
	<div id="canvas"></div>
	<div id="debug"></div>
</body>
<script>
	var node = document.createElement("p");
	node.innerHTML = document.body.clientWidth + ':' + document.body.clientHeight;
	document.getElementById('debug').appendChild(node);
</script>
```


**CORRECT**
![Screen Shot 2020-03-04 at 10 33 57 AM](https://user-images.githubusercontent.com/6193675/75839662-4c3a7100-5e04-11ea-90f2-233ea13efb06.png)


**iPhone**
![HLuwdPB - Imgur](https://user-images.githubusercontent.com/6193675/75839668-50668e80-5e04-11ea-9c3c-3c8abae4ca3f.png)

**Comment by scott20145** [comment]
Finally, I can make it correct by modify the scaleManager as below. However, it should have more test.
```javascript
//Method getParent()
if (config.expandParent && config.scaleMode !== CONST.SCALE_MODE.NONE)
{
	var DOMRect = this.parent.getBoundingClientRect();

	if (this.parentIsWindow || DOMRect.height === 0)
	{
		document.documentElement.style.height = '100%';
		document.body.style.height = '100%';

		DOMRect = this.parent.getBoundingClientRect();

		//  The parent STILL has no height, clearly no CSS
		//  has been set on it even though we fixed the body :(
		if (!this.parentIsWindow && DOMRect.height === 0)
		{

			this.parent.style.overflow = 'hidden';
			
			if(this.game.device.os.iOS && window.self !== window.top) {// iPhone, in iFrame
				this.parent.style.width = window.innerWidth + 'px';
				this.parent.style.height = window.innerHeight + 'px';
			} else {
				this.parent.style.width = '100%';
				this.parent.style.height = '100%';
			}
		}
	}
}



```

**Comment by samme** [comment]
What are `size.width` and `size.height`?

**Comment by samme** [comment]
I tried the original code, as best as I could reconstruct it, and it displayed correctly in iPhone 8 Simulator.

![Simulator Screen Shot - iPhone 8 - 2020-03-06 at 11 05 23](https://user-images.githubusercontent.com/435681/76116118-44aecf80-5f9e-11ea-8881-d84ed7048bc1.png)

I would advise:

- In `game.html`, add a doctype.
- In `game.html`, is the `canvas` selector supposed to be `#canvas'? You probably shouldn't style `canvas`.
- I'm not sure you need absolute positioning at all.
