### ISSUE TITLE
 Can pixelart be used for a single gameobject？

### ISSUE THREAD

**Issue by akeboshi1** [photonstorm/phaser#5036]
I'm working on a pixel game. I scaled the scene to fit the scene, but I found that some elements will be jagged. I want to know if pixelart can generate applications on a single gameobject, not the global

**Comment by samme** [comment]
Not per game object, but you can set per texture:

```js
this.textures.get('key').setFilter(Phaser.Textures.FilterMode.NEAREST)
```

**Comment by akeboshi1** [comment]
> Not per game object, but you can set per texture:
> 
> ```js
> this.textures.get('key').setFilter(Phaser.Textures.FilterMode.NEAREST)
> ```


Yes, this is indeed possible, but it seems to consume a bit of performance

**Comment by akeboshi1** [comment]
> ```js
> this.textures.get('key').setFilter(Phaser.Textures.FilterMode.NEAREST)
> ```


I looked at the code, and it is true! 
Thanks buddy
