### ISSUE TITLE
 phaser problem under ios

### ISSUE THREAD

**Issue by akeboshi1** [photonstorm/phaser#5039]
After the ios mobile phone logs in to the browser：
**1: enter the text and double-click the page to enlarge; 
2: after the ios soft keyboard is back down, the phaser game will only display the part of the soft keyboard that is not covered.** 
How to solve these two problems?

**Comment by RollinSafary** [comment]
More details?

**Comment by akeboshi1** [comment]
> More details?


I found a solution to the problem，https://muffinman.io/ios-safari-get-bounding-client-rect-bug/，
Thank you for following up

**Comment by samme** [comment]
@akeboshi1 could you close, please.

**Comment by hexus** [comment]
Got you covered @samme :wink:
