### ISSUE TITLE
fillGradientStyle: all colors have individual alpha channel (now only has one)

### ISSUE THREAD

**Issue by zhangciwu** [photonstorm/phaser#5044]
fillGradientStyle of Graphics is now only accept one alpha param, to apply to all colors
https://github.com/photonstorm/phaser/blob/b46776a2c0a623bf2078b533cf29d02d24663fc0/src/gameobjects/graphics/GraphicsWebGLRenderer.js#L181

I don't know if there is something webGL limit for this scenario, but I think it could be done by change the api params,
it should be able to use individual alpha channels for every color.

I'd like to help if I got some time.

If there is some limitation (from WebGL or others), please comment

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
