### ISSUE TITLE
Emitter Follow Sprite example (and maybe functionality) broken since 3.6

### ISSUE THREAD

**Issue by maikthomas** [photonstorm/phaser#5045]
## Version

* Phaser Version: 3.22

* Operating system: MacOS

* Browser: Chrome

## Description
The Emitter Follow Sprite example is broken since versions > 3.6 (try 3.5.1 in the dropdown).
https://phaser.io/examples/v3/view/game-objects/particle-emitter/emitter-follow-sprite#

## Additional Information
I'm not sure if this is just the example broke or the functionality itself. I haven't been able to get following working and 3.5.1 doesn't work with my code

**Comment by samme** [comment]
I think the problem in that one is the Impact Physics methods.

https://phaser.io/examples/v3/view/game-objects/particle-emitter/follow-sprite is working.

**Comment by photonstorm** [comment]
Thank you for reporting a problem with this example. It has now been fixed. You can find the updated version in this repo and on the labs.phaser.io site.
