### ISSUE TITLE
Wrong type definition for pack attribute in scene config

### ISSUE THREAD

**Issue by Dinozor** [photonstorm/phaser#5046]
## Version

* Phaser Version: v3.22.0-FB

* Operating system: All

* Browser:

## Description

There is an error on `pack` variable on scene config. Like by documentation and type hints it is:
`pack     false | Phaser.Types.Loader.FileTypes.PackFileConfig`, but it does not work, however it does compile without errors.
On the other hand, all JS tutorials and examples say that pack should be some object with files array, where every file is object with type, url and some other attributes.
It does compile with errors, but it works.

## Example Test Code
```typescript
export class BootScene extends Phaser.Scene {
    constructor() {
        console.log('Constructing BootScene');
        let pack: Phaser.Types.Loader.FileTypes.PackFileConfig = {
            key: 'scenes',
            extension: 'json'
        };
        super({
            key: "BootScene",
            pack: pack // does compile without errors, but also does nothing when scene launched
        });
    }
}
```

```typescript
export class BootScene extends Phaser.Scene {
    constructor() {
        console.log('Constructing BootScene');
        let files = [];
        files.push({ type: "json", key: "scenes", url: "scenes.json" });
        super({
            key: "BootScene",
            pack: {
                files: files // actually works and loads provided files, but compiles with error
            }
        });
    }
}
```
Error: 
```
ERROR in D:\Projects\Phaser\first_try\src\scenes\bootScene.ts
./src/scenes/bootScene.ts
[tsl] ERROR in D:\Projects\Phaser\first_try\src\scenes\bootScene.ts(23,17)
      TS2322: Type '{ files: { type: string; key: string; url: string; }[]; }' is not assignable to
 type 'false | PackFileConfig | undefined'.
  Object literal may only specify known properties, and 'files' does not exist in type 'PackFileCon
fig'.
```

## Additional Information
I was trying to experiment and build some base for future games using vanilla typescript as strict as possible. 
As I understed this is just typo on pack type variable.
Tried to figure out what type it actually should be but cannot find any type inside Scenes or Loader namespace with `files` attribute on it. But assume that `files` itself are `Array<Phaser.Types.Loader.FileConfig> or something similar.

**Comment by samme** [comment]
It's something like

```typescript
interface PackFileSection {
  baseURL?: string;
  defaultType?: string;
  path?: string;
  prefix?: string;
  files: PackFileConfig[];
}
```

I think the same type in [LoaderPlugin#pack](https://photonstorm.github.io/phaser3-docs/Phaser.Loader.LoaderPlugin.html#pack) must be wrong as well.

**Comment by Dinozor** [comment]
Can we add this type docs and type definitions?
Also not sure how to verify what attributes this must have. (did not find anything similat on docs also)

**Comment by samme** [comment]
I will try 😺 

https://github.com/photonstorm/phaser/blob/e4c158c883d7b9223ddc5c8b4a00a2d432d18d8f/src/loader/LoaderPlugin.js#L615-L619
