### ISSUE TITLE
 Regarding the problem of masks, if you add a mask to a container, when the children in the container are displayed, they can still accept interactive events outside the mouth.

### ISSUE THREAD

**Issue by akeboshi1** [photonstorm/phaser#5049]
Ask for help. After the scroller component is scrolled, the container child item moves outside the display viewport, and the child item can still accept interactive events. 
Container children need to accept interactive events in the viewport range. I don't want to modify the onlyTop parameter.
How to solve this problem?

**Comment by akeboshi1** [comment]
![image](https://user-images.githubusercontent.com/18412751/77052126-4e591e00-6a07-11ea-9bab-a501e9db836d.png)

**Comment by samme** [comment]
http://phaser.io/community/forum

**Comment by photonstorm** [comment]
This is correct, the mask has no influence on the hit areas of children at all and this feature will not be added to Phaser 3, sorry.
