### ISSUE TITLE
Error when calling snapshotCanvas

### ISSUE THREAD

**Issue by JanekovicS** [photonstorm/phaser#5050]
snapshotCanvas: function (canvas, callback, getPixel, x, y, width, height, type, encoderOptions)
    {
        if (getPixel === undefined) { getPixel = false; }

        this.snapshotArea(x, y, width, height, callback, type, encoderOptions);

        var state = this.snapshotState;

        state.getPixel = getPixel;

        // Here is the error
        CanvasSnapshot(this.canvas, state);
        // It should be CanvasSnapshot(canvas, state) or CanvasSnapshot(this.gameCanvas, state)

        state.callback = null;

        return this;
    }

**Comment by samme** [comment]
How to reproduce?

**Comment by JanekovicS** [comment]
Call snapshotArea method of RenderTexture class when using CANVAS as renderer.

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.
