### ISSUE TITLE
PathFollower not working, just sets at end of path

### ISSUE THREAD

**Issue by thenonamezz** [photonstorm/phaser#5053]
## Version

* Phaser Version: 3.22.0

* Operating system: Windows 10

* Browser:

## Description

Bug:

When creating a PathFollower and running startFollow(<time>) it doesn't follow the path assigned, it just sets it at the end of the path instantly.

Expected: 

Having the PathFollower follow the path correctly

## Example Test Code

http://labs.phaser.io/view.html?src=src\paths\followers\basic%20follower.js

## Additional Information

Works in Phaser Version: 3.21.0

**Comment by samme** [comment]
#4958

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
