### ISSUE TITLE
CanvasTexture: width and height are not updated after a setSize()

### ISSUE THREAD

**Issue by sebbernery** [photonstorm/phaser#5054]
## Version

* Phaser Version: 3.22

* Operating system: Ubuntu 19.10

* Browser: Firefox

## Description

When you call setSize() on a CanvasTexture, the canvas is resized but the width and height attributes of the CanvasTexture are not updated.

## Example Test Code

Here is an example on jsbin: https://jsbin.com/jusasaroce/

## Additional Information

Here is an example of the issue I get with bad width and height values on canvasTexture after a resize.
![Capture d’écran de 2020-03-24 09-28-47](https://user-images.githubusercontent.com/3611014/77404362-e8c3b380-6db1-11ea-9b06-2f0e8052fa5a.png)

In my code, I set manually canvas_texture.width and canvas_texture.height to the new value and it solves the problem. [Here (resize source code)](https://github.com/photonstorm/phaser/blob/v3.22.0/src/textures/CanvasTexture.js#L569) you can see that this.width and this.height are never changed (and it's not done in refresh). I post an issue instead of a pull request because I'm not confident enough about any side effect that can happend but I guess the solution would be add this.width = width and this.height = height before the refresh call.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
