### ISSUE TITLE
[Collisions][Matter] Need prevent collision following conditions

### ISSUE THREAD

**Issue by knakyBall** [photonstorm/phaser#5057]
Hello, i have a zombie, and a player, and a ground.

Zombies and players have colliders for collide with the ground, all have sensors and body.
But i want to slow the player when he touch a zombie, but pass through, not collide with.

And if i not use setCollidesWith with the zombies category, collisionstart not detect the collision, if i use it, player is physically stopped by zombies.

How to use sensor, and pass through body between only zombies and players ? Thx.

**Comment by samme** [comment]
http://phaser.io/community/forum

**Comment by hexus** [comment]
> This repo should not be used for technical support. If you're struggling to use Phaser then post your question to the [forum](https://phaser.discourse.group/), [Slack](https://phaser.io/community/slack) or [Discord](https://phaser.io/community/discord) channels. GitHub Issues are for bugs and feature requests only.
