### ISSUE TITLE
 Multi-picture stitching on mobile terminal has gaps

### ISSUE THREAD

**Issue by akeboshi1** [photonstorm/phaser#5063]
My friends, there is a strange problem in my project. After the large map is stitched in the mobile terminal, there will be a lot of gaps. I have tried coordinate rounding, texture with 2 pixel borders, and filter interpolation.

**Comment by samme** [comment]
If this is a bug report, we need a test case.

If not, please use [the forum, Slack, or Discord](http://phaser.io/community).

**Comment by akeboshi1** [comment]
Ok i have found the solution，thanks

**Comment by akeboshi1** [comment]
> If this is a bug report, we need a test case.
> 
> If not, please use [the forum, Slack, or Discord](http://phaser.io/community).

Ok i have found the solution，thanks
