### ISSUE TITLE
Scene update is called before create

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5065]
## Version

* Phaser Version: 3.22.

## Description

If you restart or stop/start a scene and then queue at least one new file in `preload()`, the scene's `update()` function is called before its `create()` function, likely causing an error.

## Example Test Code

https://codepen.io/samme/pen/MWwRYpd

Click at the prompt, then see console. Assertion should pass: scene status is [RUNNING (5)](https://photonstorm.github.io/phaser3-docs/Phaser.Scenes.html#.RUNNING).

## Additional Information

Scenes.Systems#sceneUpdate needs to be reassigned NOOP before starting the loader.

**Comment by samme** [comment]
A bit late now, but I think it would be much simpler without sceneUpdate:

https://github.com/photonstorm/phaser/compare/master...samme:x/remove-sceneUpdate

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/error-referencing-this-in-update-when-switching-scenes/8143/5
