### ISSUE TITLE
False warning: Local data URIs are not supported 

### ISSUE THREAD

**Issue by a513476726** [photonstorm/phaser#5067]
// Problem code snippet: 
``
this.state===s.FILE_POPULATED?this.loader.nextFile(this,!0):(this.src=a(this,this.loader.baseURL),0===this.src.indexOf("data:")?console.warn("Local data URIs are not supported: "+this.key):this.xhrLoader=l(this,this.loader.xhr))
``

// In the use of vue + phaser3 use the following code
``
this.load.image('map',  require('../../assets/img/game_jumpingStump/bg.png'));
``

//There will be some images that have been converted to bese64 standards but .indexOf does not detect data: using .includes can solve this

//After modification:
``
this.state===s.FILE_POPULATED?this.loader.nextFile(this,!0):(this.src=a(this,this.loader.baseURL),0===this.src.includes("data:")?console.warn("Local data URIs are not supported: "+this.key):this.xhrLoader=l(this,this.loader.xhr))
``

**Comment by hexus** [comment]
Looks like your change finds `data:` anywhere in the source, which isn't necessarily correct. A base64 encoded file needs to _begin_ with `data:`.

What, exactly, is your `require('../../assets/img/game_jumpingStump/bg.png')` call actually returning? Is there any whitespace at the beginning of the value, perhaps?

**Comment by photonstorm** [comment]
Given that data URIs are not allowed in the Loader (other than for video and audio files), you really shouldn't be importing assets like this anyway. If you think you've got a fix for something, please open a PR, or at least state which file you've edited and why.
