### ISSUE TITLE
fullscreenchange event never called

### ISSUE THREAD

**Issue by novaknole** [photonstorm/phaser#5068]
## Version 

* Phaser Version: 3.22

* Operating system: Mac

* Browser: Chrome

## Description

This is the code I am running.  `startFullScreen` works fine. `stopFullScreen` works fine. All good, but the event `fullscreenchange` never gets called.  Mind taking a look into this?

## Code

```js
 this.game.scale.on('fullscreenchange', function(e){
      console.log("full screen change event happened");
 })
 this.game.scale.startFullscreen();

 setTimeout(() => {
     this.game.scale.stopFullscreen();
 }, 10000);
```

**Comment by samme** [comment]
There's no such event, only [ENTER_FULLSCREEN](https://photonstorm.github.io/phaser3-docs/Phaser.Scale.Events.html#event:ENTER_FULLSCREEN) and [LEAVE_FULLSCREEN](https://photonstorm.github.io/phaser3-docs/Phaser.Scale.Events.html#event:LEAVE_FULLSCREEN).

**Comment by novaknole** [comment]
```js

this.game.scale.on('ENTER_FULLSCREEN', function(e){
    console.log("enter full screen");
 })

this.game.scale.on('LEAVE_FULLSCREEN', function(e){
       console.log("leave full screen");
 })
```

These don't get called too.
