### ISSUE TITLE
Lock Orientation breaks in Firefox

### ISSUE THREAD

**Issue by 123survesh** [photonstorm/phaser#5069]
## Version

* Phaser Version: 3.21.0-FB

* Operating system: Debian 10

* Browser: Firefox 68.6.0esr (64-bit)

## Description

Get the following error while using game.scale.lockOrientation() in firefox (both in mobile and desktop).
**'TypeError: 'mozLockOrientation' called on an object that does not implement interface Screen.'**

(Works fine in Chrome and Safari)

## Example Test Code

game.scale.lockOrientation(Phaser.Scale.PORTRAIT);

## Additional Information

Checked online about this issue, seems that screen.lockOrientation is deprecated and not supported by latest versions of firefox.
https://developer.mozilla.org/en-US/docs/Web/API/Screen/lockOrientation

**Comment by 123survesh** [comment]
I checked **ScreenOrientation.lock**, it does not exist in Firefox nor chrome at this moment.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
