### ISSUE TITLE
 Webgl and canvas text rendering issues

### ISSUE THREAD

**Issue by akeboshi1** [photonstorm/phaser#5071]
I found that the same text code in webgl mode will render the text thicker multiple times, but using canvas will not
canvas:
![image](https://user-images.githubusercontent.com/18412751/78316772-10293600-7593-11ea-9adc-931704545117.png)
webgl:
![image](https://user-images.githubusercontent.com/18412751/78316824-38189980-7593-11ea-9e9a-fb22265ad191.png)

**Comment by akeboshi1** [comment]
The same code, but after multiple renderings, webgl has a problem that the font becomes thicker

**Comment by samme** [comment]
https://github.com/photonstorm/phaser/blob/master/.github/CONTRIBUTING.md#reporting-issues

**Comment by akeboshi1** [comment]
> https://github.com/photonstorm/phaser/blob/master/.github/CONTRIBUTING.md#reporting-issues

Ok, I will pay attention to the submission criteria, this problem is in the latest version of phaser3

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.
