### ISSUE TITLE
Getting Started Guide Is Quite Weird (Phaser CLI?? 😉)...

### ISSUE THREAD

**Issue by JimLynchCodes** [photonstorm/phaser#5072]
HELLO!

First, let me say huge props and thanks to Rich and everyone involved in phaser! Honestly, I first realized I loved coding years ago experimenting with Actionscript 3 and flash games, and Phaser really seems to be the only thing that comes remotely close to filling that void since things moved over to JavaScript!

With that said, the getting started guide just seems super weird to me. 

Try to think about it as a complete n00b coming to phaser game development for the first time.

There is this gigantic, 7-part getting started guide here: https://phaser.io/tutorials/getting-started-phaser3

Then there is this guide (https://phaser.io/phaser3/gettingstarted) that tells you to install `phaser3-project-template`, cd into the node_modules, and then run it there...? Then it leaves the user like, "ok, now what? Am I supposed to copy this entire node_modules directory to my root and then npm uninstall the `phaser3-project-template` package? No offense, but no other framework in the universe works like this, and it seems like kind of a lot of work just make a new project...

Personally, I thing it would be really awesome if there was a phaser cli that was the "official" way of making a new project. Possibly we could get some inspiration from the angular cli (https://cli.angular.io/).

I'm imagining something like this- first, you install the "phaser cli"
```
npm i -g phaser-cli
```

Then you make a new project with "phaser new"
```
phaser new <project-name>
```
which creates a new folder named "project-name", and inside of it is the default phaser project files. 

Also, you can pass the --template flag with will scaffold different phaser starter projects...

Now THAT would be pretty awesome!

I would be willing to help out with this, although I've really only made this one simple cli tool: https://www.npmjs.com/package/jims-derp-cli

Caveat- I am a bit drunk rn and also going crazy from this social distancing thing, but I still think this is a good idea! Hopefully, some others will +1 this.

Thanks! ♥️

**Comment by photonstorm** [comment]
The guide at https://phaser.io/phaser3/gettingstarted was meant purely for those testing the Phaser 3 beta releases, way back before we even released 3.0.0 and, who had to build it from source. Hence the 'Labs' logo at the top and the 2 year old date on the tutorial. I'll remove this guide when I next update the site. It's not linked from the main Learn section, though, but I guess would still appear in Google results so people may stumble across it. It's not something we ever actively direct people to, though.

The main project template can be found here: https://github.com/photonstorm/phaser3-project-template

And this is the standard way to create a new project (although, not the only one) and common with how most modern web projects work these days.

There is a Phaser CLI as well, not created by us, if you like that sort of thing.

**Comment by JimLynchCodes** [comment]
Thanks! 

I just tried out the (phaser-cli)[https://github.com/phaser-cli/phaser-cli], and tbh I like it a lot!

Not only does it use a pretty new 3.22 version of phaser, but it also sets up your project in TypeScript and gives you a nice example of using scenes and loading images with the `import` syntax! Awesome! 🔥

**Comment by JimLynchCodes** [comment]
Even if the cli was made by a rando and not in-house, I think it's worth mentioning in the getting started guide!
