### ISSUE TITLE
Small error in "Class: Text" documentation

### ISSUE THREAD

**Issue by najmm01** [photonstorm/phaser#5076]
## Version

* Phaser Version: 3.22

* Operating system: Win 10

* Browser: NA

## Description

According to the docs <i>" If the font you wish to use has a space or digit in its name, such as 'Press Start 2P' or 'Roboto Condensed', then you must put the font name in quotes".</i> But I've seen that it is only true with names containing digits in them & not the ones with a space(s).

## Example Test Code
```javascript
this.add.text(0, 0, 'Hi', { fontFamily: '"Press Start 2P"', fontSize: 16, color: '#5656ee' }).setOrigin(0.5, 0); //this works

this.add.text(0, 0, 'Hi', { fontFamily: 'Finger Paint', fontSize: 150, color: '#ff3434' }).setOrigin(0.5, 0); //this also works

this.add.text(0, 0, 'Hi', { fontFamily: 'Press Start 2P', fontSize: 16, color: '#5656ee' }).setOrigin(0.5, 0); //this doesn't work
```
## Additional Information

I came across this while going through your Google Web Fonts example for Phaser 3.

**Comment by hexus** [comment]
Thanks, the improved docs will be available in 3.23. :beers:
