### ISSUE TITLE
re-using a Scene and passing new Data

### ISSUE THREAD

**Issue by MrMadClown** [photonstorm/phaser#5078]
I am using transitions to switch between Scenes.
My Scenes are all more or less state-less and I am passing the contextual data in the transition call:

```
this.scene.transition({
      target: 'ExampleScene',
      data: contextualDataForTheScene,
      sleep: true,
      duration: 400
 });
```

This works fine when the Scene is first used, but the Second time it won't get the new Data, since the ScenePlugin calls the `Phaser.Scenes.Systems.wake` method without the Data from the transition:
https://github.com/photonstorm/phaser/blob/b46776a2c0a623bf2078b533cf29d02d24663fc0/src/scene/ScenePlugin.js#L322

Is there a reason for this? Shouldn't I be re-using Scenes that way?

**Comment by samme** [comment]
For scene wake and resume, `init()` and `create()` aren't called, so there's nothing to pass the data to. You could modify `targetScene.sys.settings.data` directly.

**Comment by MrMadClown** [comment]
But wake does have a data Parameter, which is passed on to the `wake` event handler, wouldn't it make sense to use that in the transition?
https://github.com/photonstorm/phaser/blob/master/src/scene/Systems.js#L508-L536

**Comment by samme** [comment]
I see, that would make sense.

**Comment by MrMadClown** [comment]
@samme can you take a look at the pull request I made?
