### ISSUE TITLE
setOrigin(0, 0) is not in sync with Arcade Physics body

### ISSUE THREAD

**Issue by dsabsay** [photonstorm/phaser#5079]
## Version

* Phaser Version: v3.22.0
* Operating system: macOS 10.14.4
* Browser: Applies to at least Chrome 80 and Safari 12.1

## Description

When creating a new Game Object on an Arcade Physics StaticGroup, using `setOrigin(0, 0)` seems to cause the associated physics body to be out of sync with where the sprite is drawn, which causes unexpected overlap/collision behavior. The "hitbox" appears to be accounting for the change in origin:

<img width="560" alt="Screen Shot 2020-04-05 at 7 04 16 PM" src="https://user-images.githubusercontent.com/11727932/78517008-7e771f80-7770-11ea-9d36-34c59356186d.png">

This is related to #4052, where a fix was supposedly implemented. But it seems that fix doesn't cover creating game objects in this manner.

## Example Test Code
This can be reproduced by opening this codepen (from #4052): https://codepen.io/samme/pen/vzMzBZ?editors=0010 and doing these steps:
1. Change the Phaser version to 3.22.0 (Can be easily done in codepen settings. Don't forget to click `Run` afterward).
2. Replace lines 34 and 35 with this:
```
  var block = this.physics.add.staticGroup();
  block.create(400, 100, 'block')
```

## Additional Information
A workaround is to avoid using the StaticGroup, and just create e.g. Sprite objects directly. As such, I don't know if this is a major bug, but it is certainly unexpected behavior, in my opinion.

**Comment by dsabsay** [comment]
If you create the sprite object first and then add it to the StaticGroup, this issue doesn't seem to occur. For example:
```javascript
const seeds = this.physics.add.staticGroup();
...
let seed = this.physics.add.sprite(mapX + o.x, mapY + o.y - tileSize, 'seed');
seed.setOrigin(0, 0);
seeds.add(seed);
...
```
The hitbox is correctly aligned in this case.

**Comment by samme** [comment]
I think you're seeing the expected behavior. You need to update the static body manually:

```
var group = this.physics.add.staticGroup();
  
group.create(200, 150, 'block').setOrigin(0, 0).refreshBody();
  
this.physics.add.staticImage(400, 150, 'block').setOrigin(0, 0).refreshBody();
```

**Comment by photonstorm** [comment]
You cannot alter a Static Body post-creation, because it's static. If you do change something, call `refreshBody` to re-sync the object with the body.

**Comment by mohanvaddi** [comment]
I'm having a similar issue, My gameObject is not in sync with the body. I am using a static matter sprite.
I know I can use `refreshBody` to re-sync the object with body when using Arcade sprite.

Is there a method to do the same thing as `refreshBody` in this case where I'm using static matter sprite: 

```
        const block = this.matter.add.sprite(x, y, TextureKeys.BLOCK, undefined, {
          isStatic: true,
        })
          .setSize(blockWidth, blockheight)
          .setTint(this.getRandomColor())
          .setOrigin(0);
```

**Comment by photonstorm** [comment]
@mohanvaddi your issue isn't similar because it's not using Arcade Physics. This issue is 2 years old. If you need some help, you need to open your own - although, as this isn't reporting a bug, talking about it in our Discord or Forum would be a better option.
