### ISSUE TITLE
Build Doesn't Have a "--Prefix-Path" Option?

### ISSUE THREAD

**Issue by JimLynchCodes** [photonstorm/phaser#5083]
using phaser v3.22 on macOs v10.15.3

I'm having issues deploying to gh-pages, and I'm pretty sure it had to do with `phaser-scripts build` not taking into account the "prefix path" that gets added when deploying to gh-pages. 

For example, I made a build using `phaser-scripts build` which created an index file that looks like this:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, user-scalable=no"
    />
    <title>Phaser Project</title>
    <link rel="shortcut icon" href="/static/favicon.png" />
    <style>
      html,
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>

  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="app"></div>
    <!-- Scripts will be injected automatically -->
  <script type="text/javascript" src="/js/vendor.61bc7ae5.bundle.js"></script><script type="text/javascript" src="/js/app.fd700d8b.bundle.js"></script></body>
</html>
```

I then deploy it to the site here: https://everybodycodes.github.io/Phaser-Fish-Game/

And I get lots of errors for all the files because it is trying to look for them at a location that doesn't include `Phaser-Fish-Game`...

Sadly, I can't find any option to add the prefix-path to the phaser-scripts build command and don't get much help when running `phaser-scripts --help` or `phaser-scripts build --help`...  😢

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/errors-when-trying-to-host-on-gh-pages/5832/3

**Comment by JimLynchCodes** [comment]
Lol are you a bot @photonstorm ? 

that is my post with no one else posting on it... 😁

**Comment by JimLynchCodes** [comment]
Seems like someone got it working my manually going through the build folder and changing all the file paths... is this the only way? 😢

https://www.html5gamedevs.com/topic/36571-host-phaser-game-on-github/

**Comment by photonstorm** [comment]
Not sure which build script you're using, but it doesn't sound like one we created. Maybe some 3rd party template? Anyway, if it can't load assets, then just set the base URL / path in the calls to the Loader. It's the Loader code that's important here.

**Comment by JimLynchCodes** [comment]
Hmm I use the phaser-cli's scripts to build my project. I didn't realize that was not part of phaser...

https://github.com/EverybodyCodes/Phaser-Fish-Game/blob/master/phaser-fish-single-player/package.json#L7

Also, I'm not sure what you mean by "calls to Loader". There is no reference to a Loader anywhere in my project. 🤔

**Comment by photonstorm** [comment]
Yeah, Phaser CLI isn't something we created, it's a pet project by a member of the community and I'm not familiar with how it handles bundling assets. It would be better to ask the maintainer, really.

re: Loader - Are you not loading any graphics in your game at all? No pngs, etc? The Phaser Loader is what, well, loads them. And you can control the base URL / path prefix directly from it.

**Comment by JimLynchCodes** [comment]
Aha, I see what you mean now. 

In my boot phase I'm now doing this:

`this.load.setBaseURL('https://everybodycodes.github.io/Phaser-Fish-Game/')`

But when I build and deploy it doesn't seem to be looking in a different place for the files...

I also tried :

`this.load.setBaseURL('/Phaser-Fish-Game/')`

and

`this.load.setBaseURL('Phaser-Fish-Game')`

Sadly, the documentation (https://photonstorm.github.io/phaser3-docs/Phaser.Loader.LoaderPlugin.html) for setBaseUrl doesn't really explain what is the correct string to pass to this function.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/how-to-use-setbaseurl/5836/1

**Comment by JimLynchCodes** [comment]
@photonstorm can you please elaborate on how to use this setBaseUrl properly?

I asked  the question in that thread you mentioned, but the users responding don't seem to understand my question...

**Comment by JimLynchCodes** [comment]
Someone helped me to get it working there, but I didn't set the baseUrl... 🤷‍♂️
