### ISSUE TITLE
dragstart event reported before pointerdown

### ISSUE THREAD

**Issue by rattias** [photonstorm/phaser#5084]
## Version

* Phaser Version: 3.22.0
* Operating system: macOS catalina
* Browser: Chrome 80.0.3987.163

## Description

in an object where on() has been called to register callbacks for pointerdown and dragstart/drag/dragend, dragstart is called before pointerdown. This seem incorrect, as, for example, one may want to mark an object as selected on pointerdown, and records deltas for selected objects (possibly more than one) on dragstart, so that on drag they can all be moved together, but with the reversed event one is forced to consider as selected the object for which the event was notified, even if it is not yet selected.

I would expect the order to be pointerdown, dragstart, drag, dragend, pointerup. Instead, the observed order is: dragstart, pointerdown, drag, dragend, pointerup

## Example Test Code

class Example1 extends Phaser.Scene {
  constructor() {
    super({ key:'Example1' })
  }
  
  preload() {
    this.load.baseURL = 'https://examples.phaser.io/assets/';
    this.load.crossOrigin = 'anonymous';

    this.load.image('phaser', 'sprites/phaser-dude.png');
  }
  create() {
    this.image  = this.add.image( 50, 50, 'phaser' );
    this.image.setInteractive();
    this.input.setDraggable(this.image); 
    this.input.on('pointerdown', function( event ) {console.log('pointerdown'); });
    this.input.on('pointerup', function( event ) {console.log('pointerup'); });
    this.input.on('dragstart', function(event) {console.log('dragstart'); });
    this.input.on('drag', function(event) {console.log('drag');});
    this.input.on('dragend', function(event) {console.log('dragend');});
    
   
  }
 
}

var config = {
  type: Phaser.AUTO,
  width: 800,
  height: 600,
  physics: {
    default: 'arcade',
    arcade: {
      gravity: {
         y: 200
      }
    }
  },
  scene: [
    Example1
  ]
}

var game = new Phaser.Game( config );

**Comment by photonstorm** [comment]
While I agree it would make more sense the other way around (as it would match the DOM), it's been this way for years now and I'm not going to change it at this stage in Phaser 3s life, sorry, as I don't consider it a big enough issue that can't be easily worked around as-is.
