### ISSUE TITLE
Can't translate Camera 3D Axis to Blender

### ISSUE THREAD

**Issue by esromneb** [photonstorm/phaser#5085]
I am trying to orient myself in Phaser using Blender.  (starting with https://phaser.io/examples/v3/view/camera/3d-camera/dot-sphere) My understanding of Phaser 3D camera:
-X is left, +X is right
-Y is up, +Y is down
-Z is in +Z is out

If I try to create this in Blender, I'm left with an impossible task.  This is the closest I've gotten, however the Z Axis is Flipped:

![screenshot](https://user-images.githubusercontent.com/919008/79084589-66138180-7ce9-11ea-8555-adb48d257d8f.png)

If I move the camera to fix Z I will break X.  Is it possible that a fundamental Matrix inside the Camera plugin has a sign flipped?  Or am I missing something else.  Thanks.

Here's the blender file: https://github.com/esromneb/phaser-3d-camera

**Comment by esromneb** [comment]
Is it possible that this line is responsible?

https://github.com/photonstorm/phaser/blob/master/plugins/camera3d/dist/camera3d.js#L4216

**Comment by photonstorm** [comment]
Sorry, the Camera3D Plugin is deprecated and I'm no longer supporting it directly in this repo. I'd accept PRs, but that's about all really. I have updated it to work with Phaser 3.50 but that will be the final update for it. The readme has been changed to reflect this, too.
