### ISSUE TITLE
setOffset behaves weirdly if used in wrong order

### ISSUE THREAD

**Issue by Rayanfer32** [photonstorm/phaser#5086]
## Version

* Phaser Version:

3.22
* Operating system:

* Browser:
firefox 

## Description

collision boundaries are not set properly 
**whats not working:**
```js
 chick.setOffset(20,20);// must be set after anims
 chick.setCircle(10,26,38); // cropping physics boundaries for chick
 chick.anims.play('run');
```

**whats working:**
```js
 chick.anims.play('run');
 chick.setCircle(10,26,38); // cropping physics boundaries for chick
 chick.setOffset(20,20);// must be set after anims
      
```
**Why does the order of settings matter so much here... ?**
## Example Test Code
https://repl.it/@Rayanfer32/kori

**Comment by samme** [comment]
Which offset do you want, (20, 20) or (26, 38)?

Of course you're getting two different results.

**Comment by Rayanfer32** [comment]
keep em same and try.... if it helps take 20,20

**Comment by samme** [comment]
Remove `setOffset()`. Use only `setCircle()`.

**Comment by Rayanfer32** [comment]
> 
> 
> Remove `setOffset()`. Use only `setCircle()`.

yes that worked !!... thank u bro

**Comment by samme** [comment]
You're welcome. Next time please try to make a reduced test case.
