### ISSUE TITLE
Inaccurate Phaser.Display.Color.HSVToRGB algorithm

### ISSUE THREAD

**Issue by DiamondeX** [photonstorm/phaser#5089]
## Version

* Phaser Version: v3.22.0

* Operating system: Win8

* Browser:

## Description

When you try to convert HSV-values (those you've got with `Phaser.Display.Color.RGBToHSV()`) you will get other RGB-values than original. The code inside `Phaser.Display.Color.HSVToRGB()` resembles what you can find in the [HSV to RGB](https://en.wikipedia.org/wiki/HSL_and_HSV#HSV_to_RGB) subtitle from **HSL and HSV** page on Wikipedia, but it obviously lacks proper rounding usage. I'm using only one test case below, but there are many of them.

## Example Test Code

```javascript
var rgb1 = {r: 255, g: 17, b: 20, color: 16716052};
var hsv1 = Phaser.Display.Color.RGBToHSV(rgb1.r, rgb1.g, rgb1.b);
var rgb2 = Phaser.Display.Color.HSVToRGB(hsv1.h, hsv1.s, hsv1.v);
console.assert(
  rgb1.r === rgb2.r && rgb1.g === rgb2.g && rgb1.b === rgb2.b, 
  "Colors are not equal:", rgb1, rgb2
);

// Output:
//  Assertion failed: Colors are not equal:
//  {r: 255, g: 17, b: 20, color: 16716052}
//  {r: 255, g: 16, b: 19, color: 16715795}
```

## Additional Information

The better solution to this issue is to adapt algorithm from the [HSV to RGB alternative](https://en.wikipedia.org/wiki/HSL_and_HSV#HSV_to_RGB_alternative) subtitle in **HSL and HSV** page on Wikipedia. I guess it's more concise. I'll provide pull request to address this issue a little bit later.

**Comment by DiamondeX** [comment]
If it is required, I could improve my pull request. Just say how.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
