### ISSUE TITLE
Upon world.on collision event the returned gameObject doesnt contain physics members such as body

### ISSUE THREAD

**Issue by Rayanfer32** [photonstorm/phaser#5090]
## Version

* Phaser Version:3.22

* Operating system:Windows

* Browser:firefox

## Description

 `this.physics.world.on('worldbounds', collideWithWorld,this);`
**Upon world.on collision event the returned gameObject doesnt contain physics members such as body**
## Example Test Code
http://repl.it/@rayanfer32/kori

**Comment by samme** [comment]
https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Events.html#event:WORLD_BOUNDS

**Comment by Rayanfer32** [comment]
i looked into the docs... but i feel is returning an object from the group ...but it still doesnt contain physics attributes such as velocity

> 
> 
> https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Events.html#event:WORLD_BOUNDS

**Comment by Rayanfer32** [comment]
oh geez ... its contained it inside .gameObject

**Comment by samme** [comment]
The first argument **is** the body.
