### ISSUE TITLE
Can't click on 3d sprites using Camera3DPlugin

### ISSUE THREAD

**Issue by esromneb** [photonstorm/phaser#5091]
I am trying to click on a Sprite3D with no luck.  I'm using the camera like this:
`camera = this.cameras3d.add(85).setZ(350).setPixelScale(16);`

When I register the click handler nothing happens
```javascript
      sprite.on('pointerup', function() {
         // do something to the cookie
         // this.doSomething();
         console.log("got click");

      }, sprite);
```

I also looked into `camrea.unproject` and `camera.getPickRay`  Both of which give me results in a coord system I don't understand.  If `camera.getPickRay` (undocumented) is supposed to return a ray into the scene, I should be able to "Advance" the ray and hit an object.  This also gives me wrong results.  Thanks.

**Comment by photonstorm** [comment]
Sorry, but Camera3D was removed from Phaser in 3.12 and remains an unsupported 3rd party plugin. I'm afraid no time will be spent trying to make it work with the main API beyond what it already does. The 3rd party lib it comes from was fully undocumented as well, which doesn't help matters.

**Comment by esromneb** [comment]
who was the last maintainer. and would you guys accept pull requests if they were mutually deemed as helpful or increased documentation?

**Comment by victorzzt** [comment]
Here after having the same problem, but later for simple shapes, got a temporary workaround:
The camera does provide a ray when giving (x,y) on window.

The example I used to test is : http://labs.phaser.io/edit.html?src=src\camera\3D%20camera\floor.js

at line 33 add a variable to remember objects: 
```javascript
var balls = camera.createRect({ x: 8, y: 1, z: 8 }, 32, 'ball');
```

Inside create():
```javascript
    balls.forEach( function(ball){
        ball.setData('tag', 'ball'+ball.x+':'+ball.y+':'+ball.z);
    } )

    this.input.on('pointerdown', function (pointer) {

        ray = camera.getPickRay(pointer.x, pointer.y);
        balls.forEach( function(ball){
            // r is hardcoded here
            let r = 4;
            // calculate x y @ z of the object
            let tx, ty;
            let tz = ball.z;
            tx = ray.origin.x + ray.direction.x * (tz - ray.origin.z ) / ray.direction.z;
            ty = ray.origin.y + ray.direction.y * (ray.origin.z - tz) / ray.direction.z;
            let tl = Math.sqrt( Math.pow(tx - ball.x, 2) + Math.pow(ty - ball.y, 2) );
            if( tl < r ){
                console.log(ball.getData('tag')+' isHit');
                ball.gameObject.alpha = 0;
            }
        } );

    }, this);
```

Also relates to #5105 , so I could only use <sprite3d>.gameObject.alpha = 0 here.
Does not work on complex shapes ( for obvious reasons )
Did not sort z level, so object on the same ray will all be triggered
