### ISSUE TITLE
Wrong type definition for Phaser.Loader.FileTypes.SpineFileConfig

### ISSUE THREAD

**Issue by EmilSV** [photonstorm/phaser#5098]
The Typedef for Phaser.Loader.FileTypes.SpineFileConfig is wrong it has the properties: textureURL and textureExtension, that appears to be unused, and are missing the propeties: jsonURL, jsonExtension, jsonXhrSettings.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by EmilSV** [comment]
should XHRSettingsObject not be Phaser.Types.Loader.XHRSettingsObject
