### ISSUE TITLE
Wrong doc for `gameobject.body.drag`

### ISSUE THREAD

**Issue by A-312** [photonstorm/phaser#5100]
## Version

Last doc

## Description

The documentation doesn't provide the good description for `gameobject.body.drag`.

URL:  https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Body.html#useDamping__anchor

## Example Test Code

```
gameobject.body.drag = 0.5; // doesn't work because `drag` is Vector2.
gameobject.body.setDrag(0.5); // works
```

## Additional Information

The documentation should be updated to type -> `Vector2`

**Comment by samme** [comment]
`drag` is a number only if `useDamping` is true.

**Comment by samme** [comment]
I was wrong. @hexus reopen?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
