### ISSUE TITLE
Camera3DPlugin forces children to be visible

### ISSUE THREAD

**Issue by esromneb** [photonstorm/phaser#5105]
## Version

* Phaser Version: Phaser v3.22.0

* Operating system: Ubuntu 18.04

* Browser:

## Description

Due to this line in the Sprite3D class, it's impossible to mark Sprite3D objects as hidden.  It seems that this section of the code is written to handle the case where a negative scale should mark the sprite as hidden.  However this prevents the user from manually setting a sprite as hidden that would otherwise be visible

https://github.com/photonstorm/phaser/blob/master/plugins/camera3d/src/sprite3d/Sprite3D.js#L135

## Example Test Code

My example code is a modified version of the `edit.html?src=src\camera\3D%20camera\rectangle.js` from the examples.  The expected result is that half the mushrooms blink visible every 30 frames.  The actual result is that the mushrooms are always visible.
```javascript
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var text;
var camera;
var cursors;
var transform;
var xAxis;
var yAxis;
var zAxis;
var isPosition = true;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.scenePlugin('Camera3DPlugin', 'plugins/camera3d.min.js', 'Camera3DPlugin', 'cameras3d');

    this.load.image('particle', 'assets/sprites/mushroom2.png');
}

function create ()
{
    graphics = this.add.graphics();

    camera = this.cameras3d.add(85).setZ(300).setPixelScale(128);

    var sprites = camera.createRect({ x: 4, y: 4, z: 16 }, { x: 48, y: 48, z: 32 }, 'particle');

    //  Our rotation matrix
    transform = new Phaser.Math.Matrix4().rotateX(-0.01).rotateY(-0.02).rotateZ(0.01);

    cursors = this.input.keyboard.createCursorKeys();

    text = this.add.text(10, 10, '', { font: '16px Courier', fill: '#00ff00' });

    xAxis = new Phaser.Math.Vector3(1, 0, 0);
    yAxis = new Phaser.Math.Vector3(0, 1, 0);
    zAxis = new Phaser.Math.Vector3(0, 0, 1);
}

function visibleHalf(visible) {
    let children = camera.getChildren();
    for(var i = 0; i < children.length/2; i++) {
        children[i].setVisible(visible);
    }
}


var frameNumber = 0;

function update ()
{
    camera.transformChildren(transform);

    if( frameNumber % 60 == 0 ) {
        visibleHalf(true);
    }
    if( frameNumber % 60 == 30 ) {
        visibleHalf(false);
    }

    frameNumber++;
}

```

## Additional Information

If I comment out lines 135-138 in this file I get the expected result.  (I understand that commenting out this will break the negative scale functionality).

**Comment by photonstorm** [comment]
Sorry, the Camera3D Plugin is deprecated and I'm no longer supporting it directly in this repo. I'd accept PRs, but that's about all really. I have updated it to work with Phaser 3.50 but that will be the final update for it. I appreciate this issue still exists. It needs a different way of dealing with visibility really, but that isn't something I'll be adding (I would accept a PR, though)
