### ISSUE TITLE
phaser3 three.js depth issue

### ISSUE THREAD

**Issue by immangrove-supertree** [photonstorm/phaser#5109]
## Version

* Phaser Version: 3.22.0

* Operating system: mac OS

* Browser: firefox

## Description

I am rendering three.js with reference to the pager example extern (https://labs.phaser.io/edit.html?src=src/bugs%5Cextern.js).

In Chrome and Safari browsers, there is no problem with 3D object depth rendering. But Firefox browser has a problem.

Is there a solution to the problem?

## Example Test Code

```
var config = {
    width: 800,
    height: 600,
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    backgroundColor: '#2d2d88',
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var camera;
var scene;
var mesh;
var renderer;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('logo', 'assets/sprites/phaser.png');
    this.load.script('threejs', 'assets/tests/three.min.js');
}

function create ()
{
    // this.add.text(10, 10, 'Extern Test 1');

    var e = this.add.extern();

    this.add.image(400, 300, 'logo');

    camera = new THREE.PerspectiveCamera( 70, window.innerWidth / window.innerHeight, 1, 1000 );
    camera.position.z = 400;

    scene = new THREE.Scene();

    var texture = new THREE.TextureLoader().load('assets/textures/tiles.jpg');

    var geometry = new THREE.BoxBufferGeometry( 200, 200, 200 );
    var material = new THREE.MeshBasicMaterial( { map: texture } );
    for(var i=0; i<3; i++){
        mesh = new THREE.Mesh( geometry, material );
        mesh.position.z = i*-500;
        mesh.position.y = i*400;
        mesh.rotation.x = 100;
        scene.add( mesh );
    }

    renderer = new THREE.WebGLRenderer( { canvas: this.game.canvas, context: this.game.context, antialias: true } );
    // renderer = new THREE.WebGLRenderer();
    // renderer.setSize(800, 600);

    e.render = function (prenderer, pcamera, pcalcMatrix)
    {
        renderer.state.reset();
        renderer.render(scene, camera);
    }

    renderer.autoClear = false;


    // document.body.appendChild( renderer.domElement );
}

function update ()
{
    renderer.render( scene, camera );
}

```

chrome / safari browser
<img width="736" alt="chrome" src="https://user-images.githubusercontent.com/55978011/80183680-3434e000-8644-11ea-82cf-56d0cfe081aa.png">
firefox browser
<img width="736" alt="firefox" src="https://user-images.githubusercontent.com/55978011/80183968-c0df9e00-8644-11ea-8d90-0ff1f9861a03.png">

**Comment by photonstorm** [comment]
Have you tested the three.js code here directly in Firefox, without using Phaser?

Also, it's highly likely you'd need to enable depth testing on the webgl context for it to work, which you can do via the game config, as it's disabled by default.

**Comment by immangrove-supertree** [comment]
> Have you tested the three.js code here directly in Firefox, without using Phaser?
> 

> Also, it's highly likely you'd need to enable depth testing on the webgl context for it to work, which you can do via the game config, as it's disabled by default.

**Comment by immangrove-supertree** [comment]
> Have you tested the three.js code here directly in Firefox, without using Phaser?
> 
> Also, it's highly likely you'd need to enable depth testing on the webgl context for it to work, which you can do via the game config, as it's disabled by default.

Yes, I tested three.js on firefox without using phaser3.
Using only three.js does not cause any problems.

I have the same problem in Firefox even though depth testing is added to the WebGL context.

**Comment by JonDevoS** [comment]
hi, have the same issue in firefox did someone figure how to fix it?

**Comment by JonDevoS** [comment]
found this all fixed
https://discourse.threejs.org/t/firefox-does-not-render-the-depth-correctly/11823/5
