### ISSUE TITLE
Use html2canvas for DOMElements?

### ISSUE THREAD

**Issue by IsaaacD** [photonstorm/phaser#5110]
The use case I'm solving is that I have some score I want to display but I want to lay it out in an HTML table (rather than making layout code in Phaser). This score could have other windows popping in front of it and as such the existing DOM Element in Phaser is not sufficient.

Here's a sample code that I have working to show my table

````javascript
                let table = document.createElement('table');
                table.innerHTML = row;
                document.body.append(table);
                html2canvas(table).then(canvas => {
                    this.textures.addCanvas('score', canvas);
                    table.remove();
                    var sprite = this.add.sprite(x, y, 'score');
                    sprite.setDepth(this.depth + 1);
                });
````
![image](https://user-images.githubusercontent.com/5303125/80208806-f1044e00-85fe-11ea-865d-a6e4bd1c4dbc.png)

This would allow the developer to use HTML elements without having to change much of their workflow, and I think would clean up the API a bit as there wouldn't be caveat to using DOM.

This wouldn't work for form input, but that's a bit of a different situation. This scenario could have ads or other menus coming in front of it.

**Comment by photonstorm** [comment]
I'm glad it works for you, but it's a couple hundred KB and also not a replacement for DOMElement as it can't handle things like interactive forms or media elements, as it's just a snapshot tool.
