### ISSUE TITLE
Pointer.getDuration() incorrectly reports duration for right click

### ISSUE THREAD

**Issue by veleek** [photonstorm/phaser#5112]
## Version

* Phaser Version: 3.22.0

* Operating system: Windows 10

* Browser: Microsoft Edge (haven't confirmed with other browsers, but I think it should repro everywhere)

## Description

While clicking and holding the LMB, get duration increases with time as expected.  Releasing stops downTime from increasing.  Clicking again restarts downTime from zero again.

Clicking and holding RMB appears to cause `getDuration()` to return down-time duration since last LMB click.  Releasing results the value of `getDuration()` resetting back to what it was from the previous LMB press.  

Press LMB -> getDuration = 0... goes up... 1000 -> Release LMB
getDuration = 1000
Wait...
getDuration = 1000
Press LMB -> getDuration = 0... increases 500 (or whatever) -> Release LMB
getDuration = 500
Press RMB -> getDuration = 550 (anything greater than last duration)... increases to 1000 -> Release RMB
getDuration = 500
Wait...
getDuration = 500
Press RMB -> getDuration = 2500... continues increasing. -> Release LMB
Press LMB -> getDuration = 0...100 Release
Press RMB -> getDuration = 200...500, etc.

## Example Test Code

```
var config = {
    width: 800,
    height: 600,
    type: Phaser.AUTO,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var text;

var game = new Phaser.Game(config);

function create ()
{
    text = this.add.text(10, 10, '', { fill: '#00ff00' }).setDepth(1);

    this.input.mouse.disableContextMenu();
}

function update ()
{
    var pointer = this.input.activePointer;

    text.setText([
        'x: ' + pointer.worldX,
        'y: ' + pointer.worldY,
        'isDown: ' + pointer.isDown,
        'rightButtonDown: ' + pointer.rightButtonDown(),
        'downTime: ' + pointer.getDuration()
    ]);
}
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by kinghenrythe5th** [comment]
Stop sending me these fucking phaser emails

**Comment by veleek** [comment]
@kinghenrythe5th - These are automated notification e-mails from GitHub, you are not being manually added by anybody (with the exception of this message that I explicitly tagged you in).  You should be able to go into your GitHub preferences somewhere and add/remove notifications for a thread/project/organization to stop getting them.

**Comment by photonstorm** [comment]
@kinghenrythe5th you've likely enabled 'Watch' on the Phaser GitHub repo. No-one can turn this off for you, other than you, because no-one can turn it on other than you. Go to the repo and make sure the 'Watch' drop-down in the top-right is set to "Ignoring".
