### ISSUE TITLE
Bug with looping timeline and value increment

### ISSUE THREAD

**Issue by Feavy** [photonstorm/phaser#5114]
## Version

* Phaser Version: 3.23.0

* Operating system: Windows

## Description

Hello,

I tried to create a timeline that increments the x and y properties of an object with "+=100" and loops infinitely.
It works fine the first time but a problem comes after: the tweens keep using the initial position of the object as starting values.

So it makes something strange like:
**Loop 1**
x: 0 -> 100 / y: 0 -> 100
**Loop 2**
x: 0 -> 200 / y: 0 -> 200
**Loop 3**
x: 0 -> 300 / y: 0 -> 300
…

The expected behavior would be:
**Loop 1**
x: 0 -> 100 / y: 0 -> 100
**Loop 2**
x: 100 -> 200 / y: 100 -> 200
**Loop 3**
x: 200 -> 300 / y: 200 -> 300
…

## Example Test Code

https://codepen.io/Feavy/pen/pojwqrm

**Comment by photonstorm** [comment]
Just to say that Timelines have been removed from Phaser 3.60 and replaced with the new Tween Chain system, which enables perfectly sequenced playback. Although this is a breaking change, I feel it was worth making for the benefits it brings (such as fixing issues like this!)
