### ISSUE TITLE
matterjs-attractor plugin Doesn't seem to work

### ISSUE THREAD

**Issue by Vi-jay** [photonstorm/phaser#5116]
https://rexrainbow.github.io/phaser3-rex-notes/docs/site/matterjs-attractor/

my code is here 
```ts
 this.matter.world.setBounds()
        this.matter.world.localWorld.gravity.scale= 0;
        this.matter.enableAttractorPlugin();
        this.matter.add.circle(50,500,50)
        this.matter.add.circle(50,500,50,{
            plugin: {
                attractors: [
                    function (bodyA, bodyB) {
                        return {
                            x: (bodyA.position.x - bodyB.position.x) * 0.000001,
                            y: (bodyA.position.y - bodyB.position.y) * 0.000001
                        };
                    }
                ]
            }
        })
        this.matter.add.mouseSpring();
```
They cannot be attracted and the callback is not triggered

**Comment by rexrainbow** [comment]
[Here](https://labs.phaser.io/edit.html?src=src\physics\matterjs\attractors.js) is the official example of matterjs-attractor. See *shape* parameter (line 45-48)

**Comment by Vi-jay** [comment]
thanks for your help

**Comment by Vi-jay** [comment]
> [Here](https://labs.phaser.io/edit.html?src=src%5Cphysics%5Cmatterjs%5Cattractors.js) is the official example of matterjs-attractor. Check _shape_ parameter (line 45-48)

This case is a pile of adsorption, how to let one adsorb to another location
