### ISSUE TITLE
Spine change in 3.23 not built to /dist

### ISSUE THREAD

**Issue by FostUK** [photonstorm/phaser#5118]
## Version
* Phaser Version: 3.23
* Operating system: any

## Description
Re this PR: https://github.com/photonstorm/phaser/pull/4893
which was merged and is part of 3.23 (supporting spine load via manifest)

I neglected running the build script for spine so changes are not present in the /dist versions.

Apologies - assumed these were part of a larger build script.
Just tested `npm run plugin.spine.full.dist` and it seems to have updated properly.

Is this the correct one to use out of the list of spine build scripts?
Happy to run the script and make a PR for the result if needed.

**Comment by FostUK** [comment]
PRs:

* **phaser:** https://github.com/photonstorm/phaser/pull/5136
* **phaser-examples:** https://github.com/photonstorm/phaser3-examples/pull/311

**Comment by photonstorm** [comment]
The new Spine plugin will be part of the 3.50 release (the dist files are now available in the repo)
