### ISSUE TITLE
Warning for incorrect Shader.setUniform call

### ISSUE THREAD

**Issue by pavel-shirobok** [photonstorm/phaser#5119]
## Version
* Phaser Version: Current from master
* Operating system: any
* Browser: any

## Description

Hi,
It's not an actual bug and not the feature request, but small improvement for a bit uncomfortable behavior of Shader.setUniform.
Setup of uniform's values must looks like this `shader.setUniform('uUniform.value.x')`, but very easy to get mistake and use something like `shader.setUniform('uUniform.x')`. And as shader use the `https://github.com/photonstorm/phaser/blob/master/src/utils/object/SetValue.js` and it's very silent for cases like this, maybe will be nice add change to setUniform so it checks the return value of `SetValue` call and do the warning:
```
setUniform: function (key, value)
    {
        
       if(!SetValue(this.uniforms, key, value))
      {
           console.warn('Can't install uniform:', key);
      }

        return this;
    },
```

**Comment by photonstorm** [comment]
I've long hated the `value.x` syntax, there's just no easy way to avoid it. Perhaps a warning is a good idea, although for a uniform it could spam the log fast.

**Comment by pavel-shirobok** [comment]
@photonstorm Did you review possibility to use Proxy for improvement this api?

**Comment by photonstorm** [comment]
I can't use `Proxy`, it's an ES6 feature, doesn't work in IE, and has no easy polyfill that won't just add a whole bunch of wasteful processing onto the top of it :( Honestly, I feel like this one just has to come down to user education / documentation, sadly.
