### ISSUE TITLE
Scaled world confuses camera follow, breaks fixedToCamera

### ISSUE THREAD

**Issue by jigglycrumb** [photonstorm/phaser#512]
See live example here: [http://phasercamera.hpcodecraft.me](http://phasercamera.hpcodecraft.me)

Holding down the right arrow key makes the mushroom leave the screen and the camera does not follow. Also, the UI at the top starts to wander off screen. If globalScale is set to 1 everything works as expected.

**Comment by hayesmaker** [comment]
The camera was never designed to zoom? wtf? surely this is a requirement. (or should be).  How many cameras do you own which can't zoom?

**Comment by hayesmaker** [comment]
+1, cameras should zoom

**Comment by photonstorm** [comment]
There are lots of things it would be nice for the Camera to do, but it doesn't alter the fact it can't actually do it yet. It's why we wrote them entirely for Phaser 3.

**Comment by hayesmaker** [comment]
How many cameras do you own which can't zoom?

**Comment by photonstorm** [comment]
Irrelevant. The only one that matters here is the Phaser one, and it doesn't claim to be able to support it anywhere. It's not that the feature doesn't work, it's that it doesn't exist. Feel free to add it.
