### ISSUE TITLE
add outTexCoord varying for default BaseShader's vertex shader

### ISSUE THREAD

**Issue by pavel-shirobok** [photonstorm/phaser#5120]
Hi, 
I've faced with BaseShader provides the inPosition varying, but it's not the same with outTexCoord in pipeline's shaders.
I've tried to extend BaseShader's vertex shader with it and it looks very simple for implement:

```precision highp float;
uniform mat4 uProjectionMatrix;
uniform mat4 uViewMatrix;
uniform vec2 uResolution;
attribute vec2 inPosition;
varying vec2 fragCoord;
varying vec2 outTexCoord;
void main () {
         gl_Position = uProjectionMatrix * uViewMatrix * vec4(vec2(inPosition.x, inPosition.y), 1.0, 1.0);
         fragCoord = vec2(inPosition.x, uResolution.y - inPosition.y);
         outTexCoord = vec2(fragCoord.x / uResolution.x, fragCoord.y/ uResolution.y);
}
```

Is it possible to add it to default BaseShader's vertex shader? Or have I done something incorrect?

Thanks!

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
