### ISSUE TITLE
.setInteractive() parameters names are misleading

### ISSUE THREAD

**Issue by liorGameDev** [photonstorm/phaser#5122]
## Description

the api of .setInteractive(): https://github.com/photonstorm/phaser/blob/d6e860076637c1686adcfcd64afd40c829b5d181/src/gameobjects/GameObject.js#L454
calls the InputConfiguration - shape
and HitAreaCallback - callback
Which is confusing and can cause mistake if you pass an object instead of shape (for example if you want to change the cursor + set hit area)

Because here:
https://github.com/photonstorm/phaser/blob/d6e860076637c1686adcfcd64afd40c829b5d181/src/input/InputPlugin.js#L2145
it seeks for ""hitArea" and "hitAreaCallback" instead.

Maybe the names should be changed or let 'setHitArea' search for shape / callback as well.

## Example Test Code

`
var sprite = scene.add.sprite(x, y, "key");
sprite.setInteractive({ 
          shape: new Phaser.Geom.Rectangle(0, 0, 50, 50), 
         callback: Phaser.Geom.Rectangle.Contains, 
         cursor: "url(assets/cursors/myCursor.cur), pointer" 
 })`

## Additional Information

If you decide you want to change it, i would be happy to add a pull request.

**Comment by samme** [comment]
I agree that `setInteractive(hitArea, hitAreaCallback, dropZone)` would be clearer.

You can probably go ahead and PR.

**Comment by liorGameDev** [comment]
@samme It seems like the callback and shape name are appearing across the code. In InputPlugin.js and other Objects that call .setInteractive()
Do you think i should PR for all the occurences of it?
Sorry for the noob question, i didn't PR Phaser before, do i need some kind of permission for it?

**Comment by samme** [comment]
You would only rename the `shape` and `callback` arguments of the public functions. I think those are

- Phaser.GameObjects.GameObject#setInteractive
- Phaser.GameObjects.Zone#setDropZone
- Phaser.Input.InputPlugin#enable
- Phaser.Input.InputPlugin#setHitArea

You don't have to get permission to PR.

**Comment by liorGameDev** [comment]
![image](https://user-images.githubusercontent.com/15868082/80895366-c300c700-8cec-11ea-82eb-a3303323b5d3.png)

**Comment by photonstorm** [comment]
@liorGameDev the way to do a PR is to fork the repo, make the change in your fork, and then create a Pull Request from that fork, so I can merge it in. You can never 'push' directly to any repo you don't own.
