### ISSUE TITLE
Adding shadows to graphic

### ISSUE THREAD

**Issue by liorGameDev** [photonstorm/phaser#5123]
It will be great if Phaser will add the option to add Shadow and it's properties like color and blur to the Graphics class. Maybe use the same api as in Canvas2d.

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/shadowBlur
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/shadowColor

**Comment by liorGameDev** [comment]
```
var graphics = scene.add.graphics({
    x: 0,
    y: 0,
   shadowBlur: 20,
   shadowColor: 'red'
    add: true
});
```

**Comment by rexrainbow** [comment]
Graphics game object in WebGL render dose not use canvas api for drawing, therefore it dose not support gradient or shadow, imo.

**Comment by photonstorm** [comment]
Sorry, this isn't something I plan to support in Phaser 3.
