### ISSUE TITLE
TypeError when loading JSON objects in `url` argument

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5125]
## Version

* Phaser Version: 3.23.0

## Description

Load any JSON file type (json, animation, atlas, pack, etc.) and pass an object in `url`.

> TypeError: this.url.indexOf is not a function

## Example Test Code

https://codepen.io/samme/pen/pojdJNX

**Comment by BenjaminDRichards** [comment]
This addresses an issue I've encountered, right down to the line I traced as the source of the problem. Thanks for doing the heavy lifting! Looking forward to this one going into release. We use a unique JSON structure, and have to convert it to an object at runtime, so this is a real bottleneck for upgrades.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
