### ISSUE TITLE
Loading spine (one skeleton with two atlas) in scene one to be used in scene two

### ISSUE THREAD

**Issue by Slaskchuck** [photonstorm/phaser#5140]
## Version

* Phaser Version: Phaser v3.23.0-FB (WebGL | Web Audio)

* Operating system: Ubuntu 18.04.4 LTS

* Browser: Chrome Version 81.0.4044.138

## Description

Expected: Spine (one skeleton with two atlas) load from scene one to be used in scene two should render.
![image](https://user-images.githubusercontent.com/13134377/81522771-46ba5380-937e-11ea-8baf-48c9f9262408.png)
Result: Texture from atlas two will be missing
![image](https://user-images.githubusercontent.com/13134377/81522790-5d60aa80-937e-11ea-980f-a50811717431.png)

## Example Test Code
scene one:
`
preload() {
this.load.setPath('assets/spine/demo')
this.load.spine('spineDemo', 'demos.json', 'atlas1.atlas')
}
`
scene two:
`
create() {
this.add.spine(400, 500, 'spineDemo.alien').setScale(0.5)
}
`

## Additional Information
[Spine being Used](https://github.com/photonstorm/phaser3-examples/tree/master/public/assets/spine/demos)

**Comment by photonstorm** [comment]
You should be loading both atlases in the preload call. Here is a full working example (it uses the latest Spine plugin too)

```js
class Preloader extends Phaser.Scene
{
    constructor ()
    {
        super({
            key: 'Preloader',
            pack: {
                files: [
                    { type: 'scenePlugin', key: 'SpinePlugin', url: 'plugins/3.8.95/SpinePluginDebug.js', sceneKey: 'spine' }
                ]
            }
        });
    }

    preload ()
    {
        this.load.setPath('assets/spine/3.8/demos/');

        this.load.spine('set1', 'demos.json', [ 'atlas1.atlas', 'atlas2.atlas' ], true);
    }

    create ()
    {
        this.scene.start('Example');
    }
}

class Example extends Phaser.Scene
{
    constructor ()
    {
        super('Example');
    }

    create ()
    {
        //  From atlas1
        this.add.spine(200, 600, 'set1.spineboy', 'run', true).setScale(0.5);

        //  From atlas2
        this.add.spine(600, 600, 'set1.armorgirl', 'animation', true).setScale(0.25);

        this.add.text(10, 10, 'Scene 2', { font: '16px Courier', fill: '#00ff00' });
    }
}

const config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#000000',
    parent: 'phaser-example',
    scene: [ Preloader, Example ]
};

let game = new Phaser.Game(config);
```
