### ISSUE TITLE
Issue with a MatterJS tutorial for Body Creation while adding to setExistingBody function

### ISSUE THREAD

**Issue by mdere-unbound** [photonstorm/phaser#5141]
## Version

* Phaser Version:  3.23

* Operating system: Windows 10

* Browser: Chrome

## Description

I was trying to follow this tutorial with my Typescript template Phaser 3 I spun up. https://phaser.io/examples/v3/view/physics/matterjs/compound-sensors

As soon I try to add the compoundBody I keep on getting this error:

entities/player/index.ts(46,26): semantic error TS2345: Argument of type 'Body' is not assignable to parameter of type 'BodyType'.
  Type 'Body' is missing the following properties from type 'BodyType': id, type, label, parts, and 45 more.

## Example Test Code

I modified it just slightly to fit my needs:

```
        this.sprite = scene.matter.add.sprite(
            props.x,
            props.y,
            'zombie'
        );
        // Create the physics-based sprite that we will move around and animate
        const { width: w, height: h } = this.sprite;
        const mainBody = Bodies.rectangle(0, 0, w, h, { chamfer: { radius: 10 } });
        this.sensors = {
            bottom: Bodies.rectangle(0, h * 0.5, w * 0.25, 2, { isSensor: true }),
            left: Bodies.rectangle(-w * 0.35, 0, 2, h * 0.5, { isSensor: true }),
            right: Bodies.rectangle(w * 0.35, 0, 2, h * 0.5, { isSensor: true })
        };
        const compoundBody = Body.create({
            parts: [mainBody, this.sensors.bottom, this.sensors.left, this.sensors.right],
            frictionStatic: 0,
            frictionAir: 0.02,
            friction: 0.1
          });
        
        this.sprite
        .setExistingBody(compoundBody);
```

## Additional Information

   ```
 "dependencies": {
        "@types/matter-js": "^0.14.2",
        "phaser-matter-collision-plugin": "^0.10.2",
        "rollup-plugin-copy-assets": "^2.0.1"
    },
    "devDependencies": {
        "@rollup/plugin-replace": "^2.3.0",
        "eslint": "^7.0.0",
        "eslint-config-strongloop": "^2.1.0",
        "lint": "^0.7.0",
        "phaser": "^3.23.0",
        "rollup": "^1.29.0",
        "rollup-plugin-commonjs": "^10.1.0",
        "rollup-plugin-copy": "^3.3.0",
        "rollup-plugin-node-resolve": "^5.2.0",
        "rollup-plugin-serve": "^1.0.1",
        "rollup-plugin-typescript2": "^0.25.3",
        "rollup-plugin-uglify": "^6.0.4",
        "typescript": "^3.7.4"
    }
```

**Comment by mdere-unbound** [comment]
I am also doing this at the top of my file to make Body / Bodies be accessible

// @ts-ignore: Property 'Matter' does not exist on type 'typeof Matter'.
const Matter: typeof MatterJS = Phaser.Physics.Matter.Matter;

**Comment by meisterpeeps** [comment]
It appears that the CustomMain.js file in physics/matter-js/ isn't properly being exposed by the typescript dts file.

**Comment by photonstorm** [comment]
`"@types/matter-js": "^0.14.2",` this is the wrong defs to use for Matter. You need to use the ones we provide in the Phaser repo (in the `types` folder), as they're specifically for our implementation of Matter.js (they're also much better than the ones in the types repo, as I fixed lots of issues those had!)
