### ISSUE TITLE
phaser 3 `startFullscreen()` not works on safari.

### ISSUE THREAD

**Issue by novaknole** [photonstorm/phaser#5143]
## Version

* Phaser Version:3.22

* Operating system: Macos

* Browser: Safari

## Description
hi @photonstorm 

I am using `game.scale.startFullscreen()` method.  Problem that appears is it doesn't work on safari macos.  of course, it also doesn't work on ios safari. but it works correctly on other browsers.

On safari, it throws `fullscreenfailed` event.....

I've noticed that phaser uses prefixes.  but still, what could be the reason ? 

```js
<div id="video">
    
</div>
<button onclick="enablefullscreen()">Enable</button>
<script>
function enablefullscreen(){
    toggleFullscreen();
}
function toggleFullscreen() {
  let elem = document.getElementById("video");
  elem.webkitRequestFullscreen()
}
</script>
```

I tried this code and this worked on macos safari as a fullscreen pretty well. So I sum up that fullscreen works fine in safari, but why doesn't phaser's `startFullscreen()` work even though it uses prefixes? 

Any idea... ?

**Comment by samme** [comment]
https://codepen.io/samme/full/XWmYVdX fails in Safari.

https://codepen.io/samme/pen/ZEbRvKb succeeds in Safari.

**Comment by AdamXA** [comment]
If you breakpoint `if (fsPromise)` in `startFullscreen()` it says its evaluating `if (undefined)`, then calling the error handler.

If you breakpoint this line in `startFullscreen()`
`fsPromise = fsTarget[fullscreen.request](fullscreenOptions);`

Then wait a second or two, then step forward, it actually goes fullscreen and succeeds.
Might be some race condition.

**Comment by samme** [comment]
I think that fullscreenErrorHandler() → removeFullscreenTarget() is actually causing the request to fail in Safari.

**Comment by samme** [comment]
This will work in Safari: https://github.com/photonstorm/phaser/compare/master...samme:x/startFullscreen

**Comment by novaknole** [comment]
@samme  Thanks for this pull request. 

Any idea when it will be approved->merged ?

**Comment by samme** [comment]
No PR yet 😃

**Comment by novaknole** [comment]
@samme 

Would you mind making a pull request ?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
