### ISSUE TITLE
bug/types: Property 'x' / 'y' does not exist on type 'Group'.

### ISSUE THREAD

**Issue by twoco** [photonstorm/phaser#5145]
Group type does not contain x and y position properties. 

```ts
import * as Phaser from 'phaser';

export class MyScene extends Phaser.Scene {
  myGroup: Phaser.GameObjects.Group;

  constructor() {
    this.myGroup = this.add.group();
    console.log(this.myGroup.x);
    // Result: Error: Property 'x' does not exist on type 'Group'.
  }
}
```

If I force `any` as type, it works on runtime. It's just missed in types declaration.

```ts
 myGroup: any;
// Position props x and y works on runtime. 
```

`phaser 3.23.0` (TypeScript)

**Comment by rexrainbow** [comment]
*Group* is a kind of data structure which hold reference of game objects, it dose not have `x`, `y` properties. You might try container if you want to move game objects together.
