### ISSUE TITLE
KeyboardPlugin.checkDown doesn't work if optional parameter left out

### ISSUE THREAD

**Issue by lozzajp** [photonstorm/phaser#5146]
https://github.com/photonstorm/phaser/blob/85873d2958ba70344c9b5efd3c642e6799af9b6f/src/input/keyboard/KeyboardPlugin.js#L629

It has the (TypeScript) signature of: `checkDown(key: Phaser.Input.Keyboard.Key, duration?: number): boolean;` and a statement that if left out, `duration?` is defaulted to 0 `@param duration The duration which must have elapsed before this Key is considered as being down. Default 0.`

However it simply doesn't work, I suspect that `duration` is left undefined and further functions don't work.

Reproduction:

```ts
// in update
    let keyboard = this.input.keyboard;

    if (keyboard.checkDown(keyboard.addKey('A'), 0)) {
      console.log('A was held down for 0ms');
    }

    if (keyboard.checkDown(keyboard.addKey('S'), 100)) {
      console.log('S was held down for 100ms');
    }

    if (keyboard.checkDown(keyboard.addKey('W'))) {
      console.log('W was held down for 0ms but I wont print');
    }
```

**Comment by samme** [comment]
Specifically, [checkDown()](https://photonstorm.github.io/phaser3-docs/Phaser.Input.Keyboard.KeyboardPlugin.html#checkDown) always returns `false` when `duration` is omitted.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
