### ISSUE TITLE
Canvas flipping certain pieces of spine animation

### ISSUE THREAD

**Issue by LukeSkinn77** [photonstorm/phaser#5148]
## Version

* Phaser Version: v3.23.0-FB

* Operating system: Windows 10

* Browser: No specific browser

## Description

I am attempting to use spine animations with both WebGL and Canvas support, while everything works correctly on WebGL, with the spines properly positioned and playing, I have had issues with the Canvas rendering mode, with some components such as eyes becoming out of position and/or rotation and scale on other spines behaving weirdly (i.e. too large/small, upside down). While consulting the examples on the Phaser website, I noticed they appeared to break when attempting to run them in Canvas mode, so I wonder if this is a common issue?

## Example Test Code

This issue occurs whenever adding a spine to the scene when running in Canvas mode:

        let v = this.add.spine(150, 350, 'skeleton', 'Dad', true).setScale(0.1,0.1);

## Additional Information

I have included the spine files, as well as screenshots of the spine running in both Canvas and WebGL, note the out of place eye in the Canvas version.

https://drive.google.com/open?id=1QDp4RyjGLo5UNT1WXy8rNCjLXApHwZN4

![WEBGL EYE](https://user-images.githubusercontent.com/36535196/81836486-72cf0380-953b-11ea-8339-f56a4e55bd43.png)
![CANVAS EYE](https://user-images.githubusercontent.com/36535196/81836488-74003080-953b-11ea-8054-d8222ed370b2.png)

**Comment by photonstorm** [comment]
I'm afraid there's nothing I can really do about this. All the Canvas rendering is handled by the Spine runtime itself, nowhere does Phaser actually get involved (beyond setting-up the skeleton position). I would check this against the latest Spine Plugin, which I updated today to use the new 3.8.95 runtimes, but aside from that, file it as a bug on the Spine runtime repo.
