### ISSUE TITLE
Wrong static body position from scaled sprite

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5149]
## Version

* Phaser Version: 3.23.0

## Description

If you add a static body to a sprite with scale ≠ 1, the body position is incorrect. 

## Example Test Code

https://codepen.io/samme/pen/ZEbjjww

See console. Assertions should pass. Instead two bodies have incorrect `left` and `top`.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
