### ISSUE TITLE
`children` passed to created group aren't added/removed correctly

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5151]
## Version

* Phaser Version: 3.23.0

## Description

If you pass `children` when creating a group, [createCallback](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Group.html#createCallback) isn't called for those game objects.

If you destroy any of `children`, [https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Group.html#removeCallback] isn't called and the destroyed game object is not removed from the group.

## Example Test Code

https://codepen.io/samme/pen/WNQKgPq

See console. Assertions should pass.

## Additional Information

`children` need to be added after the group is configured.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
