### ISSUE TITLE
`children` passed to created physics group don't receive bodies

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5152]
## Version

* Phaser Version: 3.23.0

## Description

If you pass `children` when creating a physics group or static physics group, those game objects don't receive physics bodies.

## Example Test Code

https://codepen.io/samme/pen/VwvBEwx

Should not error, console assertions should pass.

https://codepen.io/samme/pen/JjYBmdO

Should see bodies (blue and purple) on the debug display.

## Additional Information

This is partly caused by #5151 and partly by problems in the physics group constructors.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
