### ISSUE TITLE
iOS - Audio does not resume after navigating away from Safari window

### ISSUE THREAD

**Issue by AdamXA** [photonstorm/phaser#5156]
## Version

* Phaser Version: 3.23.0 - bug might not occur in 3.22.0

* Operating system: iOS 13.4.1

* Browser: Safari

## Description

1. Go to the following Phaser example (v3.23.0): https://labs.phaser.io/view-iframe.html?src=src/audio/Web%20Audio/play%20audio%20file.js&v=3.23.0

2. Tap to make the audio start playing.

3. Swap to a new tab in Safari or press the Home button.

4. Navigate back to the example in Safari. No audio will resume playing.

If you try this using Phaser v3.22.0, the audio will resume playing (for me, most the time, at least): https://labs.phaser.io/view-iframe.html?src=src/audio/Web%20Audio/play%20audio%20file.js&v=3.22.0

## Example Test Code

https://labs.phaser.io/edit.html?src=src/audio/HTML5%20Audio/play%20audio%20file.js&v=3.23.0
## Additional Information

Seemed to reproducible on all iPhones I have tried, which were iPhone X, iPhone 11 and iPhone 7 running either iOS 13.4 or 13.4.1. Do not think it occurred in iOS simulator, real devices only.

**Comment by AdamXA** [comment]
Not sure if this is new to 3.23.0 anymore... seems to be a bit random 😕

**Comment by micsun-al** [comment]
Is this related to this? https://github.com/photonstorm/phaser/issues/4790

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
