### ISSUE TITLE
Left side of IsoTriangle does not render for the first triangle

### ISSUE THREAD

**Issue by mattjennings** [photonstorm/phaser#5164]
## Version

* Phaser Version: 3.23.0

* Operating system:  macOS 10.15

* Browser: Chrome

## Description

When adding an IsoTriangle, the first one is missing the left-side. Any triangles added afterwards render OK.

## Example Test Code

I've made a codesandbox here:

https://codesandbox.io/s/phaser-isotriangle-bug-w9q4h?file=/package.json

If you comment out the first triangle, the 2nd triangle will be missing its left side.

This is also reproducible with the IsoTriangle example from the Phaser website

https://labs.phaser.io/edit.html?src=src/game%20objects/shapes/iso%20triangle.js&v=3.23.0

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
