### ISSUE TITLE
add.text font placement buggy in Brave web browser

### ISSUE THREAD

**Issue by Athaman** [photonstorm/phaser#5165]
## Version
* Phaser Version: 3.23.0
* Operating system: Windows 10.0.18363 Build 18363
* Browser: Brave V1.92.71 Chromium: 81.0.4044.138

## Description

First off, it's a Brave so I'm mostly reporting it for the academic side of things :) 

The add.text() function displaces the text based on the fontSize parameter when rendering with WebGL in brave. As I increase the fontSize it moves the text further down the canvas.

Actual behaviour:
Each fontSize increment pushes the text further down the screen.

Expected behaviour: 
The text renders in the same location but at a larger size.

## Example Test Code

```
class TitleScene extends Phaser.Scene {
  constructor() {
    super('Title');
  }

  preload() {}

  create() {
    //  create title text
    this.titleText = this.add.text(0, 0, 'MMORPG', {
      fontSize: '60px',
      fille: '$fff',
    });
  }
}

```

## Additional Information
fontSize: 15px on a 600 high canvas
![Small Font](https://user-images.githubusercontent.com/17151688/82779240-0a671700-9e97-11ea-8ee6-3dd6606b02ad.png)

fontSize: 64px on a 600 high canvas:
![bigFont](https://user-images.githubusercontent.com/17151688/82779217-f6231a00-9e96-11ea-8217-560ead39e627.png)

**Comment by Athaman** [comment]
Note: I tested on Chrome and Edge locally and both presented just fine.

**Comment by mbruchetpro** [comment]
I have the same issue than you, I don't understand why ... Did you find any solution ?

**Comment by Athaman** [comment]
Unfortunately my 'solution' was to stop developing in Brave >.>

I didn't delve very deep into it but documented it here for the sake of it. Honestly I don't expect it will get solved any time particularly soon.

**Comment by photonstorm** [comment]
I really don't think there is anything we can do about this. Brave is a terrible browser from an html5 game perspective. I appreciate what it is trying to prevent re: tracking and privacy, but it's too draconian in how it manages it, causing far too many canvas-based operations to fail, such as this.

**Comment by enriqueto** [comment]
Brave is getting popular among blockchain users. Is there anything to be done?

**Comment by photonstorm** [comment]
> Brave is getting popular among blockchain users. Is there anything to be done?

Basically brave blocks pixel scanning of a canvas, which is idiotic but there we go. Text objects in v3 can use pre-calculated text metrics, so you don't have to do this at runtime. You'll have to do it as part of your workflow and include the metrics in your code, but it will avoid this issue at least.

**Comment by samme** [comment]
I think this may be caused by incorrect calculations in the `!imagedata` condition block in `MeasureText()`. The metrics there are much too large.

An acceptable solution might be to estimate the metrics from the font size.

**Comment by Akshitsharma111** [comment]
will this work in phaser ce

**Comment by samme** [comment]
@Akshitsharma111 in Phaser CE you can pass `fontProperties` in the text `style` argument. See https://photonstorm.github.io/phaser-ce/Phaser.Text.html
