### ISSUE TITLE
NOOP importing from wrong file

### ISSUE THREAD

**Issue by gregolai** [photonstorm/phaser#5170]
In [KeyboardManager.js](https://github.com/photonstorm/phaser/blob/master/src/input/keyboard/KeyboardManager.js#L12)

and in [MouseManager.js](https://github.com/photonstorm/phaser/blob/master/src/input/mouse/MouseManager.js#L10)

There may be more instances - thought I'd bring it up really quick.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
