### ISSUE TITLE
WebKit - Json data loaded through Loader.pack cannot be accessed by cache.json.get()

### ISSUE THREAD

**Issue by TuriSc** [photonstorm/phaser#5173]
## Version
* Phaser Version: 3.23.0
* Operating system: macOS, iOS
* Browser: Safari

## Description
On webkit something goes wrong while parsing loaded data. On the example below, json data referenced in the pack is loaded and stored into the cache, but it's not linked in a way that can be accessed by cache.json.get().
This test passes on Firefox and Chrome but fails on Safari.

## Example Test Code
```
function preload ()
{
    this.load.pack('pack', 'testpack.json')
}

function create ()
{
    var output
    var testdata = this.cache.json.get('testdata')
    if(testdata) output = testdata.teststring  
    this.add.text(100, 100, 'testdata: ' + output)
}
```

###### testdata.json
```
{ 
    "teststring": "hello"
}
```

###### testpack.json
```
{ 
    "testpack": {
	"files": [
            {
                "type": "json",
		"key": "testdata",
		"url": "testdata.json"
            }
	]
    }
}
```

**Comment by samme** [comment]
What happens in Safari?

**Comment by TuriSc** [comment]
My bad, everything is working as expected.
While testing on Safari I was accidentally running cached code.
