### ISSUE TITLE
Bug reading JSON data in File.js when loading atlas

### ISSUE THREAD

**Issue by juakiz** [photonstorm/phaser#5176]
I just switched to version 3.23 and `scene.load.atlas('key', img, JSONdata)` stopped working due an error in `File.js` when loading JSON data.
I don't have time to search for the specific issue in Phaser files this time, but I just want to warn to save others time ;)
Cheers!

**Comment by samme** [comment]
#5125

**Comment by juakiz** [comment]
Oh didn't expet 29 days with this issue.
Thanks Samme.
