### ISSUE TITLE
Can graphics.fill() support eventodd mode ? 

### ISSUE THREAD

**Issue by lumixraku** [photonstorm/phaser#5177]
I found that graphics.fill() method takes 0 parameters, which is different from origin html5 canvas.

It would be very useful when drawing a hollow area.

**Comment by rexrainbow** [comment]
Graphics game object dose not use html5 canvas in webgl rendering mode.

Phaser3 has [canvas texture](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/canvas-texture/#create-canvas-texture) which can work with html5 canvas api.
Or, [here](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/canvas/) is a 3rd party Canvas game object. It also can work with html5 canvas api.

**Comment by lumixraku** [comment]
Does this 3rd party canvas works with webGL ?

**Comment by rexrainbow** [comment]
Yes, it can.
