### ISSUE TITLE
Tilemap collision documentation inconsistency

### ISSUE THREAD

**Issue by BoltKey** [photonstorm/phaser#5179]
Based on documentation, it would seem that calling `setCollisionBetween(10, 999999)` and `setCollisionByExclusion([-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])` will have the same effect (considering there will be no tiles with id > 999999). 

However, that is not the case. If you use the collision between approach, the collision will apply to all tiles that will be added to the tilemap in future and have the id in the range specified. If you use the second approach and add a tile with a new id that is not yet present in the tilemap and is not one of the values specified, the collision does not apply.

**Comment by samme** [comment]
#### setCollision()

> Sets collision on the given tile or tiles within a layer by index.

#### setCollisionBetween()

> Sets collision on a range of tiles in a layer whose index is between the specified `start` and `stop` (inclusive).

#### setCollisionByExclusion()

> Sets collision on all tiles in the given layer, except for tiles that have an index specified in the given array.

I think the key phrase is _all tiles in the given layer_, but I guess it could be clearer.
