### ISSUE TITLE
Phaser 

### ISSUE THREAD

**Issue by im-not-io** [photonstorm/phaser#5181]
## Version

* Phaser Version: Phaser official website 

* Operating system: Mac OS Mojave 10.14.6

* Browser: Google Chrome

## Description

Phaser website sidebar blocks the documentation on a 13" MacBook Pro. This makes it hard to read the documentation! Not a Phaser issue, but it does make it hard to read the Phaser docs.

## Example Test Code

alert("There's no code to show, but the website still has a bug!");

## Additional Information

<img width="1440" alt="Screen Shot 2020-06-02 at 3 29 32 PM" src="https://user-images.githubusercontent.com/16009065/83576212-13369900-a4e6-11ea-83ac-cd412c3a32fc.png">

**Comment by im-not-io** [comment]
This page is one of the pages partially blocked by the sidebar on my laptop:
https://photonstorm.github.io/phaser3-docs/Phaser.Types.Core.html#.GameConfig

To emulate the error just use the device toolbar, and resize the window from small to large until you see the sidebar is blocking the screen.

**Comment by photonstorm** [comment]
This is a problem with the Docstrap theme that we use to generate the docs from. It'll be solved once they migrate to the Phaser site, but I'm not going to spend any time pouring through all the docstrap template code right I'm afraid (I will accept a PR for this, though)

**Comment by im-not-io** [comment]
Not a problem! Was able to get around it by shrinking my screen or deleting the sidebar in devtools. Definitely for future versions make sure it's a bit more readable on various devices it would help a ton especially since reading the docs is one of the main tools a developer has!

Have a nice day! :)
