### ISSUE TITLE
Creates a Path from a Path Configuration object with custom curve class

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5182]
It is harder to create path from custom curve class in [`path.fromJSON(data)`](https://github.com/photonstorm/phaser/blob/master/src/curves/path/Path.js#L344) method, because that curve classes are parsed by [a hard code switch statement](https://github.com/photonstorm/phaser/blob/master/src/curves/path/Path.js#L359-L380). 

It is nice if curve classes are registered in somewhere and use the type-class dictionary to rebuild path from path configuration object.

**Comment by photonstorm** [comment]
I'd take a PR for this, but it seems a bit edge-case to spend time directly on.

**Comment by rexrainbow** [comment]
Put this new feature in phaser4 is fine.
Phaser4 might need that, since all built-in curves won't be put together by default.

**Comment by photonstorm** [comment]
Yup, will have to approach them in a totally different way for v4 (and quite looking forward to it!) - for v3, what we have now will have to do I think.
