### ISSUE TITLE
Spines do not work with RenderTextures

### ISSUE THREAD

**Issue by Kitsee** [photonstorm/phaser#5184]
## Version

* Phaser Version: 3.23.0

* Operating system: Ubuntu

* Browser: Chrome

## Description

Webgl currently crashes when a spine is being rendered by a render texture. The crash appears to happen the mesh rendered unbinds both the Array Buffer and Program without updating the current variables in the renderer. This causes the next object to be render to assume that the buffer and program are both bound correctly causes a crash. We attempted to work around this issue by add the following 2 lines to SpineGameObjectWebGLRenderer 
```
    if (!renderer.nextTypeMatch)
    {
        //  The next object in the display list is not a Spine object, so we end the batch
        sceneRenderer.end();
        renderer.currentVertexBuffer = null;
        renderer.currentProgram = null;
        renderer.rebindPipeline(renderer.pipelines.TextureTintPipeline);
    }
```
This corrected the webGL warnings and prevent the rendering from failing however the spine still does not get rendered correctly onto the render texture, being both out of scale and out of position. It appears to still be using certain values from the main screen when calculating its transform. 
We started to attempt to work around these issue with the following injection however we have decided to discontinue our investigation due to time constraints.
```
        const spineBatchList = function (children, x, y, alpha, tint)
        {
            for (var i = 0; i < children.length; i++)
            {
                var entry = children[i];

                const oldW = this.renderer.width;
                const oldH = this.renderer.height;
                this.renderer.width = this.camera._cw;
                this.renderer.height = this.camera._ch;

                this.drawGameObject(entry, x, y);

                this.renderer.width = oldW;
                this.renderer.height = oldH;
            }
        };
        this.rt = scene.add.renderTexture( 7000+800,800, this.spine.width,this.spine.height).setDepth(10000);
       this.rt.batchList = spineBatchList;
```

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
