### ISSUE TITLE
Image Is Pixelated When Scaled Down

### ISSUE THREAD

**Issue by Program4GitHub** [photonstorm/phaser#5187]
I added an image to the canvas as a sprite, and scaled it down using `.setScale(0.36)`.
The problem is that the image looks pixelated (while the image file itself is in high res).
Before I scaled down the image it looked just fine. The problem only occurs after the scaling.

This is the image file that I imported into phaser 3 (scaled, in the image viewer of my computer):
![image](https://user-images.githubusercontent.com/38870042/84083715-d9d0c280-a9ea-11ea-8368-08ab0f67925e.png?v=4&s=2)

This is how the image looks on Phaser 3 before scaling down (just fine):
(the tint here is different, but it doesn’t matter)
![image](https://user-images.githubusercontent.com/38870042/84085586-96785300-a9ee-11ea-97eb-2bc0ce1efccb.png)

And this is how it looks after scaling down:
<img src="https://user-images.githubusercontent.com/38870042/84083730-ddfce000-a9ea-11ea-984d-c32b21c4a369.png" width="300">

As you can see, the result is very pixelated.
How can I overcome this?
Thanks a lot in advance :pray:

Here is a shortened version of my code:

```
var config = {
  backgroundColor: "#ffb3c9",
  type: Phaser.WEBGL,
  width: 600,
  height: 600,
  parent: "pageContent",
  physics: {
    default: "arcade",
    arcade: {
      gravity: { y: 200 },
    },
  },
  scene: {
    preload: preload,
    create: create,
  },
};
var game = new Phaser.Game(config);
function preload() {
    this.load.image("img", "img.png");
}
function create() {
    var sprite = this.add.sprite(50,50,"img").setScale(0.36);
    sprite.tint = 0x000000;
}
```

### Update
I discovered that this problem occurs because of the use of the HTML canvas. However, there are ways to overcome this:

- Writing manually certain algorithms for better resizing.
- Using `ctx.imageSmoothingQuality = "high";`, which supports at least 76% of the cases.
- Preventing Phaser from resizing the image, by doing it manually with the actual image (which is a really bad solution in most cases)

But still, when using Phaser3, I didn't manage to enable the `imageSmoothingQuality` option (since `canvas.getContext("2d")` is `null`.
I think that Phaser should, as a good game engine, implement an easy way to help the developers resize their sprites without losing quality.
Thanks again in advance ☺

**Comment by photonstorm** [comment]
If you're running canvas mode, you can use the `imageSmoothingQuality` setting (it's provided for you). If you're running in WebGL and resizing large images down really small, you should enable mipmapping (support for this is built-in already), to help WebGL handle the drastic reduction in pixels. There's a mipmapping demo in the labs to see how it's done.
