### ISSUE TITLE
JSONFile.js does not load when you pass in a json object instead of a url, even though comments say it should work

### ISSUE THREAD

**Issue by awweather** [photonstorm/phaser#5189]
## Version

* Phaser Version: 3.23.0

* Operating system: Windows 10

* Browser: Chrome

## Description

Phaser does not account for using preloaded json for multiAtlas, tilemapTiledJSON, or anything that requires JSON and travels through File.js  Although the code comments appear to say its allowed to pass in either a URL or a json object.

Why is this the case?  If you look at line 72 in the JSONFile.js, there is a check for if the passed in url is a plain object.  If that's the case, it uses the object as the data instead of loading it.  But this line wont ever be reached because if url is passed in as an object, it will blow up in the code snipped below.  The specific error happens because indexOf is not a function on the object prototype.
-

## Example Test Code

This is from File.js in Phaser.  Blows up on this.url.indexOf because this.url is an object and not a string
```
        if (this.url === undefined)
        {
            this.url = loader.path + loadKey + '.' + GetFastValue(fileConfig, 'extension', '');
        }
        else if (typeof(this.url) !== 'function' && this.url.indexOf('blob:') !== 0 && this.url.indexOf('data:') !== 0)
        {
            this.url = loader.path + this.url;
        }
```
This example code would break:

```

import playerJsonAtlas from '../assets/player.json';
...
preload() {
 this.load.multiatlas('player', playerJsonAtlas)
}
```

## Additional Information

I have a couple of workarounds.  One is editing File.js and putting an extra check for this.url.indexOf existing.  Instead of

`if (typeof(this.url) !== 'function' && this.url.indexOf('blob:') !== 0 && this.url.indexOf('data:') !== 0)`

we have 
`if (typeof(this.url) !== 'function' && **this.url.indexOf** && this.url.indexOf('blob:') !== 0 && this.url.indexOf('data:') !== 0)`

The current workaround I'm using is just adding a indexOf stub function on the object prototype for any json object I'm passing into phaser which works, but it's gross and I think this could be an easy fix.

It looks like this should be supported, but if I'm wrong please let me know.

**Comment by samme** [comment]
#5125

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
