### ISSUE TITLE
GameConfig takes null parent config property and treats it as undefined/invalid

### ISSUE THREAD

**Issue by MerganThePirate** [photonstorm/phaser#5191]
## Version
* Phaser Version: 3.23.0
* Operating system: Windows 10
* Browser: Google Chrome

## Description

The documentation states the following for the `parent` property of GameConfig:

> **Description**
>The DOM element that will contain the game canvas, or its id. If undefined or if the named element doesn't exist, the game canvas is inserted directly into the document body. If null no parent will be used and you are responsible for adding the canvas to your environment.
>
> **Default**
>null

However, when manually setting it to `null`, or leaving it as null, the corresponding canvas is appended to the body of the document. This clearly indicates that either the documentation is incorrect, or the behavior is unexpected.

## Example Test Code

```
var canvas = document.createElement("canvas");
var config = {
    type: Phaser.WEBGL.AUTO,
    width: 800,
    height: 600,
    canvas: canvas,
    parent: null,
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var game = new Phaser.Game(config);

function preload () {}
function create () {}
function update () {}
```

## Additional Information

I've delved into the source code for a bit, and found that the error might be located on the fallback in the method `AddToDOM` (export 122?), for when the  `target` is `null`, the if statement is accessed since `!null` & `!undefined` both output `true`.

I believe that this issue could be fixed by simply adding ` || parent === null` after `else if (element.parentElement` such as that the lines would look like the following code segment:

```
else if (element.parentElement || parent === null)
    {
        return element;
    }
```

I also recommend that the _default_ value is changed to `undefined`, since this behavior may confuse some users on why their "parent-less" configuration is not attaching anything to the document body.

**Comment by MerganThePirate** [comment]
Just downloaded `phaser.js`, modified the lines I mentioned and it (`null`) works perfectly. No need to change the default value, since it's already undefined, though; only in documentation. I'm a bit new to git, is there a way I can upload the changes?

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
