### ISSUE TITLE
Incorrect type definition for GameObjects

### ISSUE THREAD

**Issue by j-waters** [photonstorm/phaser#5199]
## Version

* Phaser Version: 3.23.0

* Operating system: Linux

## Description

`GameObjects ` can take `Texture` objects to set their texture, not just strings. This isn't mentioned in the docs to my knowledge, but more importantly isn't in the Typescript definitions.

For example, this is the current Typescript definition for `Phaser.GameObjects.GameObjectFactory.image` is:
```typescript
image(x: number, y: number, texture: string, frame?: string | integer): Phaser.GameObjects.Image;
```
When it should be:
```typescript
image(x: number, y: number, texture: string | Phaser.Textures.Texture, frame?: string | integer): Phaser.GameObjects.Image;
```

I'll see if I can make a MR at some point but I thought I'd report it here for now.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
