### ISSUE TITLE
game.load.video is not a function

### ISSUE THREAD

**Issue by ranashoaibaslam** [photonstorm/phaser#5203]
I am using phaser 3.23.0 and when trying to load video in preload method it says that this.load.video is not a function.

this.load.video('video', 'assets/video.mov','loadeddata', false, true);

**Comment by samme** [comment]
You must use `this.load.video()`, not `game.load.video()` (which doesn't exist).

Double-check the Phaser version in console.

**Comment by ranashoaibaslam** [comment]
I am actually  using this.load.video()

<img width="659" alt="Screenshot 2020-07-02 at 11 19 00 PM" src="https://user-images.githubusercontent.com/61887943/86396003-a23bfa00-bcba-11ea-9598-0510938a8c6f.png">

**Comment by zackexplosion** [comment]
@ranashoaibaslam You should put whole part of this object here, that helps.

**Comment by ranashoaibaslam** [comment]
So I console.log(this.load) and video option wan't there.

<img width="620" alt="Screenshot 2020-07-03 at 2 18 16 PM" src="https://user-images.githubusercontent.com/61887943/86454049-26809280-bd38-11ea-8e5d-2f231c1af126.png">
<img width="617" alt="Screenshot 2020-07-03 at 2 18 28 PM" src="https://user-images.githubusercontent.com/61887943/86454085-2ed8cd80-bd38-11ea-8ac1-ed37f3b3c778.png">

**Comment by photonstorm** [comment]
The only cause for this is that you're not using 3.21 or later.

What version does it output in the console when it runs?

**Comment by photonstorm** [comment]
Just tested this in 3.21, 3.22 and 3.23 and they all load videos. Ensure you're using the right version please.
