### ISSUE TITLE
Dynamic bodies no longer hit walls when riding an horizontally moving platform --- ok until 3.9, broken from 3.10

### ISSUE THREAD

**Issue by Dercetech** [photonstorm/phaser#5210]
## Version
* Phaser Version: ok until 3.9, broken from 3.10 to latest (3.23)
* Operating system: tested on OSX, Win10, iOS and Android
* Browser: Chrome, Safari (both desktop + mobile)

## Description

Consider a 2D platformer game. The characters can ride moving platforms (up/down/left/right). When riding a platform that moves horizontally, the riding body should hit any wall that would be in the way.

As per below Codepen sandboxes, I tested with all minor Phaser 3 versions:
- it works well until 3.9 included
- it is broken from 3.10 to latest 3.23

About the moving platforms:
- they move thanks to velocity (and NOT by being re-positioned every time step).
- they don't allowGravity and are immovable.
- Their frictionX is 1 to fully transfer motion to riding bodies.

## Example Test Code

The following two Codepen workspaces run the same sandbox, only the Phaser version differs:
- [it works as we'd expect until 3.9](https://codepen.io/jemreactor/pen/OJMOwox)
- [it's broken from 3.10 to 3.23](https://codepen.io/jemreactor/pen/VwerBWL)

NB. cursor keys are enabled. Running towards the wall still triggers the collision after 3.10. Only "passive" movement due to transportation is failing.

## Additional Information
- I uploaded a [quick screencast](https://youtu.be/UQQ2Yqa_-5w) to make it easier to discover the problem.
- The topic has been [discussed on the forum](https://phaser.discourse.group/t/bug-regression-riding-a-moving-body-ignore-collisions/6827/7) before  being reported here. It also documents my workaround until a clean solution is applied.
- Thanks for your attention!

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/bug-regression-riding-a-moving-body-ignore-collisions/6827/7

**Comment by Dercetech** [comment]
Hi,
Indeed, that's my topic. As mentionned in the "addition information", that's the forum post where it was initially discussed and led us to post it here.
Solve this and I promise to register via pateron :-)

**Comment by samme** [comment]
I suppose we could update `_dx` and `_dy` when applying friction. I'm not sure of the other consequences.

**Comment by samme** [comment]
Try this fix: [phaser-arcade-physics.zip](https://github.com/photonstorm/phaser/files/4899179/phaser-arcade-physics.zip).

**Comment by Dercetech** [comment]
> Try this fix: [phaser-arcade-physics.zip](https://github.com/photonstorm/phaser/files/4899179/phaser-arcade-physics.zip).

Sorry Samme, I only see your contribution now. I test your fix this morning (y)

**Comment by Dercetech** [comment]
> Try this fix: [phaser-arcade-physics.zip](https://github.com/photonstorm/phaser/files/4899179/phaser-arcade-physics.zip).

Awesome, @samme ! You nailed it:
[codepen 3.23 with Samme's patch](https://codepen.io/jemreactor/pen/eYJLOoo)

I tested with the new 3.24 : 
- 3.24 still has the issue
- Samme's patch works properly on 3.24, too.

**Comment by Dercetech** [comment]
Thank you very much Samme!
