### ISSUE TITLE
Phaser.Physics.Matter. Sprite.setCrop throws TypeError

### ISSUE THREAD

**Issue by MatthewRorke** [photonstorm/phaser#5211]
## Version: 3.x - 3.23 (I can't find a version this works on).

* Phaser Version:

* Operating system: Linux/Windows

* Browser: N/A. Electron, Chrome 83

## Description

Expected Behaviour: `Phaser.Physics.Matter. Sprite` gets cropped using the `Phaser.Physics.Matter. Sprite.setCrop` method. Line 19404 of Phaser.js has the property `ui` of the variable class property `crop` expecting a re-assignment of it's current value and assumes a previous value has been set by the class method `this.resetCropObject();` as stipulated in the "constructors" (class methods who share the same name as the class itself).

Actual Behaviour: The `crop` property was never set to a default value and so attempting to access the child property (EG: crop.u0 causes it to throw an undefined property `TypeError`.

## Example Test Code
https://codepen.io/MattRorke/pen/wvMmQWw

## Additional Information
**Fix**: I've managed to fix it by adding `this._crop = this.resetCropObject();` to line 99 of .\phaser-master\src\physics\matter-js\MatterSprite.js
I'm not sure if there is a better way to do this by inheritance, but it at least fixed the issue for me, for now.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/error-trying-to-load-a-sprite-into-my-scene/7178/1
