### ISSUE TITLE
ERROR Error: Uncaught (in promise): ReferenceError: global is not defined

### ISSUE THREAD

**Issue by blackyale** [photonstorm/phaser#5212]
https://github.com/photonstorm/phaser/blob/000beb2bd0401494e2dc958916f42731e5663f7a/src/phaser.js#L88

I need to comment this line in order to make Phaser work in Chrome, I'm using Phaser 3.23.0

**Comment by photonstorm** [comment]
Why are you loading Phaser via a promise?

**Comment by blackyale** [comment]
> Why are you loading Phaser via a promise?

Hello, thanks for such a quick answer. I'm not loading Phaser via Promise, I'm loading it by using ES6 syntax with "import". To be more specific I'm using it from an Angular 10 project with Typescript. This error can be easily reproduced creating an Angular project from the scratch and then installing and importing Phaser.

This is how I import it:
`import Phaser from 'phaser';`

and then I instantiate it like this:
`this.game = new Phaser.Game(config);`

As I told before If I comment the line 88 it perfectly works. I'd like to know what is exactly that line doing to understand what's my issue. Thanks a lot in advance.

**Comment by samme** [comment]
I suppose that line is redundant now.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
Having now tested this, it breaks all imports of Phaser by removing this line. So I'm going to revert this change to make it work again.
