### ISSUE TITLE
Typescript and "Animation From Png Sequence" example not consistent

### ISSUE THREAD

**Issue by volkans80** [photonstorm/phaser#5217]
## Version
* Phaser Version: v3.23.0-FB
* Operating system: Windows 10 Pro 2004
* Browser: Chrome 83.0.4103.116

## Description
When you reproduce "Animation From Png Sequence" example with Typescript, example syntax is not valid for Typescript.
Also i don't understand why Phaser3 API and Typescript type definitions are not consistent. In the API there is not a key member. It is textureKey.

![image](https://user-images.githubusercontent.com/3122625/87240979-1a2ac280-c427-11ea-8208-2d8ba940afea.png)

In the Typescript type definitions frame member is required.
![image](https://user-images.githubusercontent.com/3122625/87240963-e780ca00-c426-11ea-8c75-d54211d07b61.png)

Thanks,

**Comment by abhijeet-pathak** [comment]
Can I look into this?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
