### ISSUE TITLE
Camera zoom with static tilemap layers broken in 3.24.0

### ISSUE THREAD

**Issue by kainage** [photonstorm/phaser#5219]
## Version

* Phaser Version: 3.24.0
* Operating system: MacOS / Ubuntu

## Description

Camera zoom for static tilemap layers is broken in this latest version. It's kinda hard to explain what is happening things are just scaled and positioned wrong. Run the lab example at different zoom levels to see the issue.

## Example Test Code

You can see this issue in this labs example http://labs.phaser.io/view.html?src=src\camera\follow%20zoom%20tilemap.js.
If you change it back to `3.23.0` everything is working fine.

## Additional Information

It was this https://github.com/photonstorm/phaser/pull/5215 commit which caused the issue (as everything seems to work fine if I revet it). I'm not sure how to go about actually fixing it with this new code.

**Comment by photonstorm** [comment]
Yeah, I should have tested #5215 more carefully (it works if you don't camera zoom!). I'll revert that PR and publish a point release today with the fix in, as it's just too broken to remain until 3.25.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
