### ISSUE TITLE
Container and poinerdown bug

### ISSUE THREAD

**Issue by Stasikiii** [photonstorm/phaser#5221]
create scene_1
create scene_2
add sprite. to scene_1
add container. to scene_2
add event to sprite,
sprite.on('pointerdown', function(pointer){
   ...
});
Now put this sprite in container.
change x and y position of container.
Move camera in left or right.
Try click onsprite again.
move container again.
move camera to left or right again.
Event not works enymore.

**Comment by photonstorm** [comment]
Game Objects are bound to the Scene in which they are created.

You cannot, and should not, put a sprite from Scene 1 inside a Container from Scene 2.
