### ISSUE TITLE
Typescript this.load.spritesheet method not calculating spacing values

### ISSUE THREAD

**Issue by volkans80** [photonstorm/phaser#5223]
## Version

* Phaser Version: v3.23.0-FB

* Operating system: Windows 10 Pro 2004

* Browser: 83.0.4103.116

## Description
I am using one of kenney's spritesheets. Its frame size with space is 16x16 pixel and spaces are on the right and down. load.spritesheet method not calculating spacing values.
![image](https://user-images.githubusercontent.com/3122625/87530728-6715cf80-c699-11ea-900b-bd17a8ae0cb4.png)

I am loading this spritesheet and using like this with typescript.
```
this.load.spritesheet('sheet1','tilesets/tileset1.png',{ frameWidth: 16, frameHeight: 16, spacing:1 });
let map = this.make.tilemap({width: 10, height: 10, tileWidth: 15, tileHeight: 15 });
let tileset = map.addTilesetImage('sheet1');
```

Result like this:
![image](https://user-images.githubusercontent.com/3122625/87535750-a72c8080-c6a0-11ea-994d-1d67d6725df9.png)

If i change code like this, it works normally.
`let tileset = map.addTilesetImage('sheet1',null,16,16,0,1);`

**Comment by photonstorm** [comment]
You shouldn't use `load.spritesheet` to load a tileset, that's not how they work. Load it as an `image` and then use the tileset properties to control the tile size and spacing between them. Best to ask on Discord / the forum if you need more help than this.
