### ISSUE TITLE
DynamicBitmapText displayCallback seems to reverse red and blue channel.

### ISSUE THREAD

**Issue by teebarjunk** [photonstorm/phaser#5225]
## Version

* Phaser Version: 3.24.1

* Operating system: Kubuntu (Linux)

* Browser: Firefox

## Description

For DynamicBitmapText.setDisplayCallback, when setting the characters color, the red and blue channels seem to be reversed.
It works fine when setting the DynamicBitmapText's tint color. Just not individual characters.

I think the problem lines are 236-239 in: [DynamicBitmapTextWebGLRenderer.js](https://github.com/photonstorm/phaser/blob/7e71b240bde9372314c15e663bd1fa0d13472da3/src/gameobjects/bitmaptext/dynamic/DynamicBitmapTextWebGLRenderer.js#L236)
Where it calls: [Utils.getTintAppendFloatAlpha](https://github.com/photonstorm/phaser/blob/f2f6d69f1ec25cf3916e4ea6d59b801b0e36f4c7/src/renderer/webgl/Utils.js#L76)
 

## Example Test Code

```javascript
this.text = this.add.dynamicBitmapText(16, 16, "font", "This should be red.");
this.text.setDisplayCallback((data) => {
	data.color = 0xff0000;
	return data;
});
```
## Additional Information

I got it to work by swapping the r and b:
```javascript
this.text = this.add.dynamicBitmapText(16, 16, "font", "This should be red.");
this.text.setDisplayCallback((data) => {
	data.color = 0xff0000;
	var b = data.color & 255;
	var g = (data.color >> 8) & 255;
	var r = (data.color >> 16) & 255;
	data.color = (1 << 24) + (b << 16) + (g << 8) + r;
	return data;
});
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
