### ISSUE TITLE
onFullScreenChange is not called

### ISSUE THREAD

**Issue by monteiz** [photonstorm/phaser#5229]
## Version

* Phaser Version: 3.22.0

* Operating system: macOS 10.14.6

* Browser: Chrome 84.0.4147.89 (Official Build) (64-bit)

## Description

`ScaleManager.onFullScreenChange` is not fired when entering/leaving full screen.

## Example Test Code

https://codepen.io/monteiz/pen/OJMawWp

**Comment by monteiz** [comment]
Looking into the code, I think I misinterpreted the documentation. I thought it was a function to override, but it seems an internal function instead. Maybe it should be specified in the docs.

Thanks for this amazing framework, I love it ❤️

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by monteiz** [comment]
Very happy to give a (very little) contribution to this amazing project.
