### ISSUE TITLE
Input.activePointer returns last used touch pointer instead of mouse pointer

### ISSUE THREAD

**Issue by Legomite** [photonstorm/phaser#5232]
## Version

* Phaser Version: 3.24.1

* Operating system: iPad OS 13.5.1

* Browser: Tested in Safari

## Description

When I get the active pointer via input.activePointer using a mouse pointer after I used a touch pointer, it returns the pointer used by a touch pointer instead of returning the mouse pointer.

I’m not sure if this is an edge-case on iPad OS and I can’t test this on another device since this is the only one I have that supports touch and mouse. 

## Example Test Code

Use mouse pointer, then
Use touch pointer, then
Use mouse pointer, then

Console.log(this.input.activePointer);

All data is identical to the touch pointer

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
