### ISSUE TITLE
[Typescript definitions] Why use types instead of interfaces?

### ISSUE THREAD

**Issue by vforsh** [photonstorm/phaser#5237]
Is there a specific reason why Phaser use types instead of interfaces in `Phaser.Types` namespace?

The issue with types is that I can't use Typescript [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) and sometimes it can be useful. For example, in 3.25 beta there is a new field `maxTextures` that was introduced to `Phaser.Types.Core.RenderConfig` but it wasn't added to phaser.d.ts yet (I'm sure it will be fixed before release). If we were using types instead of interfaces I could quickly create a file like

```
declare module Phaser {
	namespace Types {
		namespace Core {
			interface RenderConfig {
				maxTextures?: number
			}
		}
	}
}
```

And get autocomplete and other TS goodies but I can't do this because we use types and types don't merge.

So if there is no specific reason to use types I suggest switching to interfaces. I could help with a pull request.

**Comment by photonstorm** [comment]
Aside from this edge-case, which could be solved by running `npm run tsgen` from the repo to build local 3.25 defs for you, what other reason can you think of to use an interface? We use them because what we're describing are concrete data types, not something you'd ever typically merge, extend or otherwise modify.

**Comment by vforsh** [comment]
Thanks for the hint about `tsgen `- I will use it when I will be testing new releases in the future.

Declaration merging is only one but major advantage interfaces have over types. Especially when they are part of a library that users can extend (like Phaser). I often have to battle this limitation when I try to create my own classes which extend Phaser game objects like Groups or Emitters. Because `GroupCreateConfig `is type, `ParticleEmitterConfig `is a type and the list goes on.

I don't see any advantage which types give us over interfaces in Phaser TS definitions. I personally use types when I need to create a union or an intersection of existing classes or interfaces. Or when I want to "[brand](https://basarat.gitbook.io/typescript/main-1/nominaltyping)" some primitives like strings or numbers. But when I want to define the object shape I always use interfaces.

**Comment by photonstorm** [comment]
Thanks for the explanation. I'm not willing to change the way TS Gen works at this stage of Phaser's life, though. It's a bit too late to be messing around with such a fundamental part of the build tools really. Something to consider for v4 perhaps.
