### ISSUE TITLE
Uncaught TypeError: Cannot read property 'useProgram' of null

### ISSUE THREAD

**Issue by jdnichollsc** [photonstorm/phaser#5238]
## Version
* Phaser Version: v3.24.1
* Operating system: macOS Mojave 10.14.6
* Browser: Chrome

## Description

I'm running Phaser inside a React application, I'm getting this warning after reopening the page that contains the game created by Phaser:
```
Uncaught TypeError: Cannot read property 'useProgram' of null
    at WebGLRenderer.setProgram (7.chunk.js:355658)
    at TextureTintPipeline.bind (7.chunk.js:274684)
    at WebGLRenderer.setPipeline (7.chunk.js:355353)
    at GraphicsWebGLRenderer [as renderWebGL] (7.chunk.js:384053)
    at GeometryMask.applyStencil (7.chunk.js:300705)
    at GeometryMask.preRenderWebGL (7.chunk.js:300676)
    at BusinessProgressBar.ContainerWebGLRenderer [as renderWebGL] (7.chunk.js:383275)
    at BusinessCard.ContainerWebGLRenderer [as renderWebGL] (7.chunk.js:383290)
    at WebGLRenderer.render (7.chunk.js:356237)
    at CameraManager.render (7.chunk.js:369881)
    at Systems.render (7.chunk.js:279675)
    at SceneManager.render (7.chunk.js:319118)
    at Game.step (7.chunk.js:376200)
    at TimeStep.step (7.chunk.js:309468)
    at step (7.chunk.js:309688)
```

## Example Test Code

- Creating the game when the page is opened: `const game = new Game({ ...config, parent: container })`
- Detroying the game before leave the page: `game.destroy(true)`

## Additional Information

I'm getting this warnings if I don't destroy the game before to unmount the component
```
WebGL: INVALID_OPERATION: bindTexture: object does not belong to this context
```

Any help is really appreciated!

**Comment by photonstorm** [comment]
Has the game definitely been destroyed before it is re-run? (i.e. do you hook into the `destroy` event it gives at all?)

Also, is the game allowed to create its own canvas, or are you passing one in?

**Comment by jdnichollsc** [comment]
This is the repository of example: https://github.com/jdnichollsc/adventure-closure/blob/feature/login-page/app/src/game/index.ts
It's working as well using `Phaser.CANVAS` as you can see, the issue only occurs using `Phaser.AUTO`

>Has the game definitely been destroyed before it is re-run? (i.e. do you hook into the destroy event it gives at all?)

Yes sir, **game.destroy** is executed when the component is unmounted

>Also, is the game allowed to create its own canvas, or are you passing one in?

Yes, I'm only passing a div container as parent, check here: https://github.com/jdnichollsc/adventure-closure/blob/feature/login-page/app/src/hooks/useGame/index.ts#L10

Thanks for your help Rich!

**Comment by photonstorm** [comment]
`game.destroy` is not an immediate process, it queues the destroy until the next frame. I think you should call it and then listen for the `destroy` event and when you get that, then unmount the component, but not before.

**Comment by jdnichollsc** [comment]
I'm getting the same wrong behavior calling the **destroy** event before unmount the component and navigating back to create a new phaser game (Only occurs with Phaser.AUTO, it works as well with Phaser.CANVAS): 
![image](https://user-images.githubusercontent.com/2154886/88753657-5a29bf00-d122-11ea-8735-3f5983e07081.png)

**Comment by jdnichollsc** [comment]
This was the previous logic I was using but in this way we can't call the `destroy` event before unmount the component:
```ts
export function useGame (
  config: Types.Core.GameConfig,
  container: HTMLDivElement | null
): Game | undefined {
  const [game, setGame] = useState<Game>()
  useEffect(() => {
    if (container) {
      const newGame = new Game({ ...config, parent: container })
      setGame(newGame)

      return () => newGame.destroy(true)
    }
  }, [config, container])

  return game
}
```

But In both cases, I'm getting the same issue with WebGL when the phaser game is created again

**Comment by photonstorm** [comment]
I need a fully reproducible test case before I can look at this again. So all the required HTML / react / Phaser code in a single minimal example, so I can run it and debug it locally. I'm not willing to learn how to use React just to test this issue, sorry. Feel free to post a zip file here with the required contents in and I'll be happy to re-open this issue and take a look.

**Comment by jdnichollsc** [comment]
Oh Is this not a reproducible demo? https://github.com/jdnichollsc/adventure-closure/tree/master/app

**Comment by jdnichollsc** [comment]
@photonstorm is this ok to be a minimal example of this issue? https://stackblitz.com/edit/react-ts-yz2wke?file=index.tsx
