### ISSUE TITLE
onStart event in a tween within a looped timeline is called just once

### ISSUE THREAD

**Issue by monteiz** [photonstorm/phaser#5240]
## Version

* Phaser Version: 3.22.0

* Operating system: macOS Mojave 10.14.6

* Browser: Chrome Version 84.0.4147.89 (Official Build) (64-bit)

## Description

The `onStart` event of a tween added to a looped timeline fires only once. On the other hand, the `onComplete` event of the same tween is fired every time the timeline loops.

## Example Test Code

https://codepen.io/monteiz/pen/ExaqVmx

**Comment by halilcakar** [comment]
Hello @monteiz,
I was looking into your problem on timeline and tweens.

So here is what i came up with:

Tweens when created, they have state of `hasStarted` and `isSeeking`  by false default.
And when it's started it's looking for this flags to call onStart callback. [Here](https://github.com/photonstorm/phaser/blob/master/src/tweens/tween/Tween.js#L1159) you can see it's checking these values and if it fits, [calls](https://github.com/photonstorm/phaser/blob/master/src/tweens/tween/Tween.js#L1167) the `onStart` function. 

I'm really not sure if this is the actual behaviour. 

Anyways, you may use this solution for your problem.

```javascript
const timeline = this.tweens.timeline();
timeline.add({
    targets: image1,
    alpha: 0,
    duration: 1000,
    onComplete: (tween) => {
        tween.hasStarted = false;
        console.log('onComplete');
    },
    onStart: () => { console.log('onStart'); },
});
timeline.loop = -1;
timeline.play();
```

**Comment by monteiz** [comment]
Hello @halilcakar,
thanks for looking into this problem and nice shot from you!

I was tempted to use the very same workaround for my code, but since the `hasStarted` property is [marked as readonly in the documentation](https://github.com/photonstorm/phaser/blob/85873d2958ba70344c9b5efd3c642e6799af9b6f/src/tweens/tween/Tween.js#L165), I fear that it could give troubles with next Phaser releases, something I want to avoid (even if looking at the code, it looks quite safe, but more on this later).

So for my problem I have eventually used a different approach (using `time.delayedCall` and calling a function at the end of every execution).

Regarding the code itself, my opinion is that it would be great to have a RESTART event (and a `onRestart` callback) fired in the [restart](https://github.com/photonstorm/phaser/blob/00e5c5fe0f4c63a08e204eaaf6afb9ff2c7fbb5c/src/tweens/tween/Tween.js#L483) function and when the tween is reset from a timeline iteration ([here](https://github.com/photonstorm/phaser/blob/00e5c5fe0f4c63a08e204eaaf6afb9ff2c7fbb5c/src/tweens/tween/Tween.js#L767)). Something like:

```
if (resetFromTimeline) {
    this.dispatchTweenEvent(Events.TWEEN_RESTART, this.callbacks.onRestart);
}
```

This way the developer can discriminate between an `onStart`, when the tween is started for the first time, and a `onRestart`, when the tween is restarted by a timeline iteration (or directly, through the `Tween.restart` function).
This approach would also preserve the backward compatibility, since it would not touch the preexisting `hasStarted` variable.
I also feel that changing the `hasStarted` to `false` at some point in the code would be semantically incorrect, since the tween has effectively _started_: the contrary would be false.

If @photonstorm agrees with that, I can create a pull request implementing this little new feature.

In any case, thanks @halilcakar and happy coding with this awesome framework! 🚀

**Comment by photonstorm** [comment]
Just to say that Timelines have been removed from Phaser 3.60 and replaced with the new Tween Chain system, which enables perfectly sequenced playback. Although this is a breaking change, I feel it was worth making for the benefits it brings (such as fixing issues like this!)

**Comment by monteiz** [comment]
I am very excited to see the new Tween Chain system in action.

Just thinking loudly: how long would it take to create a bridge that would translate the old Timeline API to the new Tween Chain system calls?

This way we could avoid a breaking change. I guess most of the games out there rely on Timelines!

Another option could be avoiding to completely remove the Timelines, but keep it and mark it as `deprecated`, so that the transition to the new system could be smoother.

**Comment by photonstorm** [comment]
I did a poll before removing TImelines, and most people didn't even know what they were, and those that did never used them at all. There are going to be a few exceptions, but on the whole, removing them won't make much difference to the majority of people.

There is no way to convert the new API to be backward compatible, and not really worth the time either, as they're fundamentally different in how they work. Timelines allowed for parallel tweens with offset start points and so on, which is what caused them to break all the time when a fixed sequence was required. Chains address this. Most people want guaranteed tween order, not overlapping tweens, so that is what I've modified it to be.

**Comment by monteiz** [comment]
@photonstorm first of all thanks for your explanation.

I have been thinking about this during these days, and I came to the conclusion that this intervention would dramatically affect our codebase. In fact, all our games (https://www.pangagames.com) are heavily based on the `Timeline` class. Strangely we never had problems with the tweens order, which have always been respected. We had other minor problems, like the one reporter in this issue, but never something serious. On the contrary, we were able to base on the Timeline class about 95% of the games animations with success.

I am sure we are not the only ones using it, so I kindly ask you to consider my request to keep the Timeline class alive, without further improving it, even mark it as `deprecated`, but removing it completely would be a mistake.

Keeping the Timeline class would not hurt anyone. But do not forget that removing it would violate the sem versioning principles: in fact, this is a severe breaking change, and as such it should go to Phaser v4.

**Comment by photonstorm** [comment]
Phaser has never (and for v3) will never follow semver. This shouldn't surprise anyone who has been using it for a while.

Unless you are using parallel _overlapping_ tweens in your Timelines, there is nothing Chain cannot do and do better.

**Comment by monteiz** [comment]
Indeed, that's why we use `Timeline`s. We heavily rely on the `offset` property which let us overlapping tweens. It's working brilliantly for us. Never had a problem with tween sequences.

A chain can for sure guarantee the order of the tweens, but in order to overlap tweens, one would be forced to create parallel chains, I guess. Which is not very friendly to orchestrate.

Why not keeping both? They apparently serve two different purposes.

**Comment by monteiz** [comment]
@photonstorm , I see why you felt that Timeline was somehow an itch ( #5144), but removing that altogether would be a **disaster** for us. All our games are based on the Timeline class, so way we cannot keep up with the updates.

To be honest, if used with `offset` as we did, they serve a great job.

I think the right thing to do here is mark them as `@deprecated`, so newcomers would know that they do not have to use it. But at least, old users like us would not be so much penalized. Then you can remove them altogether in Phaser 4, that would be perfectly reasonable.

I hope you can hear me, it would be a pity for us being stuck on a legacy version.

**Comment by monteiz** [comment]
I really like the 3.60 Timeline class. Thank you @photonstorm !
