### ISSUE TITLE
SmoothedKeyControl drag not applied properly on Chrome/MacOS

### ISSUE THREAD

**Issue by snfredo** [photonstorm/phaser#5247]
## Version

* Phaser Version: 3.17, 3.21, and 3.24.1

* Operating system: MacOS 10.14.8 and 10.15.6

* Browser: Chrome 84.0.4147.105 (Stable). Does NOT manifest on Safari 13.1.2 (Stable)

## Description

Scrolling and zoom in/out do not respect the Phaser.Cameras.Controls.SmoothedKeyControl drag parameter. Scrolling or zooming continues infinitely, and is difficult to reverse.

## Example Test Code

https://labs.phaser.io/edit.html?src=src/camera/move%20camera%20with%20keys.js&v=3.24.1

[Note that the bug manifests only if "Launch" is clicked, NOT if "Run Code" is clicked]

**Comment by photonstorm** [comment]
I cannot duplicate this at all, are you sure it's not a browser extension causing it? Have you tried it in the latest Canary release (so you can test it with all extensions disabled, without messing up your standard Chrome browser) ?

**Comment by snfredo** [comment]
Thanks for the fast response! 

Have confirmed that it doesn't show up in Canary. Quick search through my extensions reveals that "Evernote Web Clipper" v 7.13.0 is the culprit.

**Comment by photonstorm** [comment]
Evernote is such a pain in the butt! Glad you confirmed it, though, cheers.
