### ISSUE TITLE
Dom element not creating without parent in config

### ISSUE THREAD

**Issue by Harchvertelol** [photonstorm/phaser#5249]
## Version

* Phaser Version: 3.24.1

* Operating system: windows 10

* Browser: chrome

## Description

If you do not specify the parent element explicitly, then the dom-elements are not displayed without errors.
Solution: paste 'parent: document' in config (or 'parent: window').

**Comment by photonstorm** [comment]
I'm happy to leave this as-is because the config docs specifically state:

`Phaser.Core.Config#domCreateContainer - Should the game create a div element to act as a DOM Container? Only enable if you're using DOM Element objects. You must provide a parent object if you use this feature.`

**Comment by Tristoung** [comment]
thank you so much i couldnt find anything telling me why it didnt display
