### ISSUE TITLE
Pipelines are not initialized correctly if added after the game boots

### ISSUE THREAD

**Issue by telinc1** [photonstorm/phaser#5251]
## Version
* Phaser Version: 3.50.0-beta.0 (on commit 6aaf54e)

## Description
A custom pipeline added after the game has booted will never have its `boot` method called. Before the changes in 3.50, almost no pipeline used this method. In the beta, however, the Texture Tint Pipeline, which is commonly used for custom shaders, will break.

## Example Test Code
This occurs within the [Custom Pipeline](http://labs.phaser.io/edit.html?src=src\renderer\Custom%20Pipeline.js&v=dev) example. I've shared a version that works with multi-texturing (as far as I can tell, anyway) [in this forum post](https://phaser.discourse.group/t/v3-25-beta-and-custom-pipelines/7085/2?u=telinc1).

## Additional Information
This hack fixes the problem by calling `boot` in `addPipeline` if the renderer has already booted:
```diff
diff --git a/src/renderer/webgl/WebGLRenderer.js b/src/renderer/webgl/WebGLRenderer.js
index a791ee2ac..7b58409f0 100644
--- a/src/renderer/webgl/WebGLRenderer.js
+++ b/src/renderer/webgl/WebGLRenderer.js
@@ -1031,6 +1031,11 @@ var WebGLRenderer = new Class({
 
         pipelineInstance.name = pipelineName;
 
+        if (this.blankTexture != null)
+        {
+            this.pipelines[pipelineName].boot();
+        }
+
         this.pipelines[pipelineName].resize(this.width, this.height, this.config.resolution);
 
         return pipelineInstance;
```
Using `this.blankTexture` for the check is probably far from ideal, which is why I'm not going to open a pull request right now. If there's a better way to work around this (or a better place to put it), I'd gladly help with the implementation.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/v3-25-beta-and-custom-pipelines/7085/4

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
