### ISSUE TITLE
scene.sys.queueDepthSort (undefined is not an object)

### ISSUE THREAD

**Issue by matronator** [photonstorm/phaser#5252]
## Version

* Phaser Version: 3.24.1 and the same with 3.20.1

* Operating system: macOS Catalina

* Browser:

## Description

Can't create anything, even code copypasted straight from examples breaks.

## Example Test Code

```import Phaser from 'phaser'

class HealthBar {
    constructor(scene, x, y) {
        this.bar = new Phaser.GameObjects.Graphics(scene)

        this.x = x
        this.y = y
        this.value = 100
        this.p = 76 / 100

        this.draw()

        scene.add.existing(this.bar)
    }

    decrease(amount) {
        this.value -= amount

        if (this.value < 0) {
            this.value = 0
        }

        this.draw()

        return (this.value === 0)
    }

    draw() {
        this.bar.clear()

        //  BG
        this.bar.fillStyle(0x000000)
        this.bar.fillRect(this.x, this.y, 80, 16)

        //  Health

        this.bar.fillStyle(0xffffff)
        this.bar.fillRect(this.x + 2, this.y + 2, 76, 12)

        if (this.value < 30) {
            this.bar.fillStyle(0xff0000)
        } else {
            this.bar.fillStyle(0x00ff00)
        }

        const d = Math.floor(this.p * this.value)

        this.bar.fillRect(this.x + 2, this.y + 2, d, 12)
    }
}

const config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    scene: {
        preload,
        create
    }
}

const game = new Phaser.Game(config)

function preload() {
}

function create() {
    let asdf = new HealthBar(game.scene, 30, 30)
    let fml = new Phaser.GameObjects.Rectangle(this.scene, 20, 20, 200, 20, 0xff00ff)
}
```

## Additional Information

<img width="1280" alt="Snímek obrazovky 2020-08-06 v 22 26 00" src="https://user-images.githubusercontent.com/5470780/89579334-e1b6b280-d833-11ea-8872-0a3051ab432c.png">

**Comment by rexrainbow** [comment]
As I know, `game.scene` is not reference of scene instance, it is scene manager I guess. Try replace `game.scene` to `this`.

**Comment by photonstorm** [comment]
Game Objects require a Scene instance to attach themselves to. In the code above you’ve passed the Scene Manager to the HealthBar and the ScenePlugin to the Rectangle, neither of which are Scene instances. In both cases it should just be ‘this’, because that’s the Scene you’re in.

**Comment by matronator** [comment]
I'm an idiot, sorry... I thought I tried just `this` because I tried multiple variations, but apparently I didn't because it works... Thank you!
