### ISSUE TITLE
Camera follow game object before Game's 'prerender' event

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5253]
I try to draw game objects on render texture, with the related position of game window. It works fine if camera dose not follow a game object (startFollow). I can't get camera's final scrollX, scroll if camera follows game object. 
Camera follows game object in [`game.scene.render`](https://github.com/photonstorm/phaser/blob/master/src/core/Game.js#L491), there is no event I can use to get the result of camera scrolling. 
My workaround is replacing built-in camera following by setting camera scrolling manually under 'prerender' event.

**Comment by photonstorm** [comment]
See the new `FOLLOW_UPDATE_EVENT` to deal with this situation.
