### ISSUE TITLE
Frag code of custom shader pipeline in phaser.io

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5254]
## Version

* Phaser Version: 3.50.0

* Operating system: window10

* Browser: Chrome/firefox

## Description

[Frag code of custom shader pipeline](https://labs.phaser.io/edit.html?src=src/camera/16%20camera%20shader%20test.js&v=dev) in phaser.io has not been updated to 3.50 yet.
It seems that `uMainSampler` has been replaced to [`uMainSampler[%count%]`](https://github.com/photonstorm/phaser/blob/master/src/renderer/webgl/shaders/TextureTint-frag.js#L6)... etc.

**Comment by telinc1** [comment]
See also [this forum topic](https://phaser.discourse.group/t/v3-25-beta-and-custom-pipelines/7085?u=telinc1). Looks like custom TTPs [have to generate those replacements on their own](https://github.com/photonstorm/phaser/blob/0cca0018451ad141795ed0c8153193dabeb62ef6/src/renderer/webgl/pipelines/TextureTintPipeline.js#L84) and I'm not convinced that's ideal with respect to ease of use.

**Comment by photonstorm** [comment]
This has now been sorted (as there are 4 new examples showing how to do this)
