### ISSUE TITLE
Text gets an ultra thin outline after "setText()"

### ISSUE THREAD

**Issue by mbpictures** [photonstorm/phaser#5259]
## Version
* Phaser Version: v3.23.0-FB
* Operating system: Win10
* Browser:

## Description
Text gets an ultra thin outline, which can't be removed, after "setText()" has been called.

## Example Test Code
"Roboto-Bold" is a custom imported font, which works.
```JavaScript
this.sampletext = this.add.text(0, 0, "Sample text", {fixedWidth: 200, align: "center", fontSize: 20 + "px", fontFamily: "Roboto-Bold", color: "#222222"});
// ....
this.sampletext.setText("Sample text 2"); // now text has outline. setting strokeThickness to 0 has no affect.
```

**Comment by photonstorm** [comment]
I cannot duplicate this, even with that font. Please provide a CodePen or similar that demonstrates this problem fully, as I suspect there is more going on in your code that just the two lines provided above.

**Comment by photonstorm** [comment]
Closing for now. Feel free to re-open if you can provide a code snippet that replicates it, and I'll happily look into this.
