### ISSUE TITLE
fullscreen mode keep inner html?

### ISSUE THREAD

**Issue by ramarro123** [photonstorm/phaser#526]
hi,

i have this case of use

```
<div id='target'>
<div>
<span>jquery-ui-overlay</span>
<div>blabla</div>
</div>

</div>
```

then i create a game with target 'id' and the phaser create a canvas inside of my target (great & expected!)

i am using jquery-ui to make an overlay menu over the canvas, and i can say that work as expected.

but, when i use fullScreen, only the canvas goes in fullscreen not the target div.

it's possible to make 'target' and all the content, in fullscreen?

is possible to 'add' html inside a game? (i will say no, game is a canvas, it doesn't make any sense)

i really don't want to draw all the menu' with phaser.io, i will miss all jquery ui acceleration.

am i missing something?

**Comment by fyyyyy** [comment]
:+1:
