### ISSUE TITLE
getTweensOf(target) tween manager

### ISSUE THREAD

**Issue by pcharest2000** [photonstorm/phaser#5260]
## Version

* Phaser Version: Latest

* Operating system: Linux, Ubunut 20.04

* Browser: All

## Description

getTweensOf(target)  only return objects if the tween are active, i.e tweening.  if a tween is done this method returns no object.  is this the expected behavior?

## Example Test Code
import * as Phaser from "phaser";

const sceneConfig: Phaser.Types.Scenes.SettingsConfig = {
  active: false,
  visible: false,
  key: "Test"
};

  var squareTest;
  var tweenTest;
export class ClockScene extends Phaser.Scene {
  constructor() {
    super(sceneConfig);
  }
  public create() {
     squareTest = this.add.rectangle(0, 0, 200, 200, 0xffff00)
     tweenTest = this.add.tween({
      targets: squareTest,
      scaleX: 0.2,
      scaleY: 0.2,
      // angle: Phaser.Math.Between(-360, 360),
      yoyo: true,
      repeat: 1,
      duration: 1000,
      paused: true
    });

  public update(time,delta) {
    console.log(this.tweens.getTweensOf(squareTest));
  }
}

**Comment by photonstorm** [comment]
If the Tween has completed, then it shouldn't be returned in this call as the tween is queued for destruction.

However, it makes sense to optionally include pending tweens, so this feature has been added.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by pcharest2000** [comment]
Thank you!  Will do test !
