### ISSUE TITLE
Improve performance of text game object

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5261]
In phaser3, text game object uses [MeasureText method](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/MeasureText.js) to get ascent and descent by scanning canvas's [image data](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/MeasureText.js#L64).
In phaser4, text game object gets ascent and descent by [`metrics.actualBoundingBoxAscent`, `metrics.actualBoundingBoxDescent`](https://github.com/phaserjs/phaser/blob/master/src/gameobjects/text/Text.ts#L128-L129). This solution might have better performance.

**Comment by photonstorm** [comment]
It has _much_ better performance! But I'm not willing to make this change in v3, sorry. There's enough changing in 3.5 already without rewriting how Text objects fundamentally work :) Happy to leave this as a v4 benefit!
