### ISSUE TITLE
Web Audio doesn't work on latest iOS

### ISSUE THREAD

**Issue by DanLiamco** [photonstorm/phaser#5262]
## Version
* Phaser Version: 3.22.0
* Operating system: Windows 10 64-bit

## Description
Web Audio doesn't work on the latest iOS. 

My device have the following specs:
Model Name: iPad Pro (11-inch)
Software Version: 13.6

No sound is heard when clicking audio sprites in the following link: https://labs.phaser.io/view.html?src=src\audio\Web%20Audio\AudioSprite.js

HTML5 Audio sort of works as sound can be heard when clicking audio sprites in the following link: https://labs.phaser.io/view.html?src=src\audio\HTML5%20Audio\AudioSprite.js
The sound can be heard, however, only after a few seconds of clicking the audio sprites.

## Example Test Code
No test code provided as the test case is from Phaser Labs which includes code.

## Additional Information
The only scenario where I got Web Audio to work on my project is when I played a video first via an iframe. The behavior feels like playing a video activated some sort of setting that allowed all Web Audio to be played.

Please let me know if you require more information. 
Thanks!

**Comment by photonstorm** [comment]
I just tested this on my iPad (latest iOS update) and the demos work fine.

There has to be something else causing this specific to your set-up. Perhaps a Safari setting, mute setting, etc on a hardware level, rather than a code one.

**Comment by gogoprog** [comment]
I found the issue:

``` if (audioElement.canPlayType('audio/wav; codecs="1"').replace(/^no$/, ''))
            {
                Audio.wav = true;
            }
```
iOS14 returns false on this condition so `wav` is set to `false`.

The sound is functional when forcing `wav` to `true`.

**Comment by photonstorm** [comment]
Closing this issue off as Web Audio is definitely working on iOS. More specific test case needed.
