### ISSUE TITLE
SetGameSize does not work in iphone mobile. 

### ISSUE THREAD

**Issue by IDNMAX** [photonstorm/phaser#5263]
## Version

* Phaser Version:
    Phaser v3.24.1 (Canvas | Web Audio)
* Operating system:
    IphoneX,Iphone7
* Browser:
   Chrome 84.0.4147.71/ Safari 13.1.2

## Description

The problem I encountered is somewhat similar #4355 , I have a game that can have a horizontal/vertical version on my phone, So when the user turns the phone, I will use the Phaser.Scale.ScaleManager to reset his width and height.

This feature is successful in the desktop version/android phone. Whether using Safari or Chrome.

But in the iphone. this feature does not work,I can't find any way to fix.

And when I using Iphone click this issue it can not do the fullscreen function #4355 in Iphone mobile.

https://labs.phaser.io/100.html?src=src%5Cscalemanager%5Cfull%20screen%20game.js

So how can I let it work in Iphone mobile?

## Example Test Code

![image](https://user-images.githubusercontent.com/65384978/89878824-a7af2d00-dbf4-11ea-98b0-2aaea332b25b.png)

   update(){
        this.game.scale.on( 'orientationchange', ( orientation: string ) => {
            console.log('go try get landscape')
            if ( orientation === Phaser.Scale.PORTRAIT||'portrait-primary'||'portrait-secondary' ||'portrait') {
                if (!this.creates){
                console.log('im portrait')
                    this.scale.setGameSize(414,736);
                    this.scene.switch('testGame');//change to the other scene for portrait version
                }
                this.creates=true;
            } else if ( orientation === Phaser.Scale.LANDSCAPE||'landscape-primary'||'landscape-secondary'||'landscape') {

            }
        } );
}

## Additional Information
My html is very simple.

![image](https://user-images.githubusercontent.com/65384978/89878788-97974d80-dbf4-11ea-9205-10ddcf651186.png)

**Comment by samme** [comment]
What actually happens?

**Comment by IDNMAX** [comment]
> What actually happens?

It just does not have any effect. When I using android it works.

I can using DOM to delete/create a canvas to handler it. but too slowly and can not rotate to many times.

It's work from using chrome on android/PC but iphone.

you can using Iphonx to open this

https://labs.phaser.io/100.html?src=src%5Cscalemanager%5Cfull%20screen%20game.js

can not work. but in android phone it works.

**Comment by samme** [comment]
Can you make a test case?

iPhone doesn't do fullscreen, that's unrelated to setGameSize().

**Comment by IDNMAX** [comment]
> setGameSize

I just want to say the iphone dose not do a lot of function phaser made before.
Now I can not using setGameSize() on the IphoneX and Iphone6/7

**Comment by IDNMAX** [comment]
this is my demo : git@github.com:IDNMAX/phaser.git
When you using iphone chrome/safari can not using setGameSize().

Please help me.
