### ISSUE TITLE
Animation play not working while adding sprite in container

### ISSUE THREAD

**Issue by mbpictures** [photonstorm/phaser#5267]
## Version
* Phaser Version: v3.23.0-FB
* Operating system: Windows 10
* Browser:

## Description
I'm not sure whether this is a bug or intended behaviour, but I'm assuming that it is actually not intendet. So I create a bug report. Playing an animation on a sprite added to an container using ```container.add(sprite)``` doesn't work. The animation stucks on the first frame.

## Example Test Code
```JavaScript
//constructor of a class, which extends Phaser.GameObjects.Container
this.character = new Phaser.GameObjects.Sprite(scene, position.x, position.y, this.baseAttributes.character);
this.add(this.character);

scene.anims.create({
    key: "idle",
    frames: this.scene.anims.generateFrameNames("idle_spritesheet", null),
    frameRate: 30,
    repeat: -1
});

this.character.play("idle", false);
```

## Additional Information
The animation actually works when I replace:
```JavaScript
this.add(this.character);
```
by:
```JavaScript
this.scene.add.existing(this.character);
```

**Comment by photonstorm** [comment]
It's always done this, because the Sprite needs adding to the UpdateList, and a Container won't do that part for you. I'll leave this open for now because I've not yet decided if this will be changed or not. It would likely cause quite a mess if changed, but 3.5 may be the right time to do that.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
