### ISSUE TITLE
pointermove (mousemove) event with pointerlock continously receives events on Firefox

### ISSUE THREAD

**Issue by spwilson2** [photonstorm/phaser#5268]
## Version

* Phaser Version:  All 3.x versions.
* Operating system: Linux
* Browser: Firefox

## Description

On Firefox the pointermove callback will be continuously called with an invalid `movementX` value even when the mouse is not physically moved. It appears this only happens when pointerlock is enabled.

In the topdown examples, this results in the cursor continuously floating to the topleft corner.

## Example Test Code

https://phaser.io/examples/v3/view/games/topdownshooter/topdownaveragefocus

## Additional Information

This seems to be a firefox bug based on other reports. It may need a workaround or documentation of the failure for Firefox. This works on chrome.

https://forum.babylonjs.com/t/firefox-pointerlock-mousemove-mousedown-behavior/960

**Comment by photonstorm** [comment]
I've tested this in FF 80.0.1 and it works fine with no drift, so I suspect either they fixed it, or it just doesn't manifest on Windows systems?

In 3.50 in the master branch you can now set `preventDefaultDown`, `preventDefaultUp`, and `preventDefaultMove` as 3 separate flags, which can be toggled at run time too. This is how Babylon solved it, so I've made that change available in Phaser as well and added it to the JS Docs for pointer locking.
