### ISSUE TITLE
Add ability to pan the sounds when using WebAudio

### ISSUE THREAD

**Issue by pi-kei** [photonstorm/phaser#5273]
I think that the ability to pan the sounds is pretty useful.
WebAudio API has a simple [StereoPannerNode](https://developer.mozilla.org/en-US/docs/Web/API/StereoPannerNode) for this.
It adds just one property `pan` that sits in the range from -1 to 1.

What do you think about sound panning feature?
I can try to implement it.

**Comment by photonstorm** [comment]
I think there are quite a few bugs with the sound API that need fixing first, but I'd be happy with a simple PR for this feature.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
