### ISSUE TITLE
Spine Plugin removes itself from the global plugin manager when any scene is deleted

### ISSUE THREAD

**Issue by Racoonacoon** [photonstorm/phaser#5279]
Spines will fail to make after any scene has been removed, as the add and make prototypes are removed from all scenes after any scene removal. I narrowed the issue down to the this.pluginManager.removeGameObject('spine', true, true); line of the destroy() function in the SpinePlugin.js. If I comment out this line of code then Spines will make after scene removal. Commenting out this.sceneRenderer.dispose() was also necessary to prevent errors on canvas resize. 

This is using the Plugins/3.8/SpinePlugin.js code.

All in all, it seems that destroy is being called prematurely, as it does not take into account that other scenes may be using the plugin.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
