### ISSUE TITLE
Scene plugins are being added to core plugins and don't get deleted when destroying the game

### ISSUE THREAD

**Issue by awweather** [photonstorm/phaser#5282]
## Version

* Phaser Version: 3.24.1

* Operating system: Windows 10

* Browser:

## Description

Similar to the issue that was fixed here, I'm running into an issue where a plugin is not deleted when destroying the game.
https://github.com/photonstorm/phaser/issues/3856

Adding the RexUI plugin at the scene plugin level gets added to corePlugins, and core plugins aren't deleted unless you turn on the noReturn flag.  Is there a reason scene level plugins are added to corePlugins, or am I doing something wrong?  I need these to be deleted when I destroy the game so that they will reload when a new game is created.

## Example Test Code
```

const config = {
  type: Phaser.WEBGL,
  backgroundColor: constants.styles.colors.primaryBlue,
  parent: "game-viewport",
  dom: {
    createContainer: true,
  },
  scale: {
    autoCenter: Phaser.Scale.CENTER_BOTH,
    mode: Phaser.Scale.FIT,
    width: WIDTH,
    orientation: Phaser.Scale.Orientation.PORTRAIT,
    height: HEIGHT,
  },
  scene: [TitleScene, MainScene, ScoreScene],
  plugins: {
    global: [
      {
        key: "rexRoundRectanglePlugin",
        plugin: RoundRectanglePlugin,
        start: true,
      },
    ],
    scene: [
      {
        key: "rexUI",
        plugin: RexUIPlugin,
        mapping: "rexUI",
      },
    ],
  },
  physics: {
    default: "arcade",
    arcade: {
      // debug: true,
      gravity: { y: 0 },
    },
  },
  disableContextMenu: true,
};

```

## Additional Information

![image](https://user-images.githubusercontent.com/19537970/91910673-75d23900-ec7d-11ea-879c-a4da275a13fe.png)

**Comment by makario** [comment]
I'm also running into this problem. I have a scene plugin for tweening on a fixed time step instead of a variable one. I override the current `tweens` plugin with mine:
```
this.load.scenePlugin("FixedTweenManager", FixedTweenManager, "FixedTweenManager", "tweens");
```

I thought this would be isolated to my current scene, but all newly created scenes have the `FixedTweenManager` instead of the original one.

I worked around this issue by giving my plugin a separate scene key and manually overriding the reference:

```
// in preload()
this.load.scenePlugin("FixedTweenManager", FixedTweenManager, "FixedTweenManager", "fixedTweens");

// in create()
this.tweens = this.fixedTweens;
```

I was under the impression that scene plugins that weren't global wouldn't be...well, global; maybe I'm understanding things wrong.

**Comment by rexrainbow** [comment]
Global and scene plugin class will be stored in plugin manager after loaded, then plugin manager
- reate 1 Global plugin instance for whole Game
- Create 1 Scene plugin instance for each scene

**Comment by photonstorm** [comment]
The difference between a Global and a Scene plugin is that like rex said, for a global plugin, you have 1 instance of the plugin for the entire game - so when a Scene references it, it's just dealing with the one single plugin (Sound Manager and Texture Manager work like this).

However, a Scene Plugin gets an instance of it installed into each Scene (that has it in its Injection Map). There's no feature for a plugin that exists just in one single Scene.
