### ISSUE TITLE
setGameSize corrupts spine scale/position with multiple scenes

### ISSUE THREAD

**Issue by spayton** [photonstorm/phaser#5286]
## Version
* Phaser Version: 3.50 beta3
latest commit [https://github.com/photonstorm/phaser/commit/af0f207cbb3d7cecbf8fc60881ced5e9a2f904c5](url))

## Description

When using multiple scenes, calling setGameSize() causes the display of a spine to move/resize roughly inline with the new aspect ratio.

The problem is not seen when using only 1 scene or an older versions of phaser, eg 3.22

## Example Test Code

The example has two scenes, the first is a preloader for the assets and the other one is the main scene.

It displays a static image (smiley) and an animating spine (spineboy-pro) on top of it.

![setGameSize_before](https://user-images.githubusercontent.com/4949575/92289457-716d8080-ef08-11ea-9980-a742b2c8b15d.png)

Clicking the canvas will call setGameSize with the canvas width doubled.  Now the smiley image has stayed the same position/size as expected but the spine has moved to the right and is also stretched horizontally.

![setGameSize2_after](https://user-images.githubusercontent.com/4949575/92289482-88ac6e00-ef08-11ea-9a6a-1a7a089eede3.png)

Here is the example source with two examples, they run the exact same code but use different versions of phaser & SpinePlugin:

> index_bad.html uses phaser 3.5b3, shows the problem
> index.good.html user phaser 3.22, no problem

[setGameSize.zip](https://github.com/photonstorm/phaser/files/5177245/setGameSize.zip)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
