### ISSUE TITLE
 [Phaser 3.50] DynamicBitmapText do not render correct with some fonts

### ISSUE THREAD

**Issue by EmilSV** [photonstorm/phaser#5303]
## Version

* Phaser Version: 3.5 beta 6

* Operating system: Windows 10

## Description
When using DynamicBitmapText with some fonts for us it was a font made with BMFont base on cambo https://fonts.google.com/specimen/Cambo or the gothic bitmap font taken from Phasers example assets, the text either does now show or is a mess.
![billede](https://user-images.githubusercontent.com/3351370/92979020-bc037580-f491-11ea-84d4-9ba978da4661.png)

## Example Test Code

```
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);


function preload()
{
    this.load.bitmapFont('gothic', 'gothic.png', 'gothic.xml');
    this.load.bitmapFont('desyrel', 'desyrel.png', 'desyrel.xml');
    this.load.bitmapFont('cambo', 'cambo.png', 'cambo.xml');
}

function create()
{
    var dynamicTextGothic = this.add.dynamicBitmapText(400, 100, 'gothic', 'gothic');
    var textGothic = this.add.bitmapText(400, 200, 'gothic', "gothic");

    var dynamicTextDesyrel = this.add.dynamicBitmapText(400, 300, 'desyrel', 'desyrel');
    var textDesyrel = this.add.bitmapText(400, 400, 'desyrel', 'desyrel');

    var dynamicTextCambo = this.add.dynamicBitmapText(400, 500, 'cambo', 'cambo');
    var textCambo = this.add.bitmapText(400, 600, 'cambo', "cambo");
}

```
Made a simple git repo with everything needed for showing the bug
[https://github.com/EmilSV/Phaser3_5_dynamicBitmapText_bug](url)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
