### ISSUE TITLE
Groups added by existing() are not on the update list

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5304]
## Version

* Phaser Version: 3.50.0-beta.6

## Description

Call [GameObjectFactory#existing()](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.GameObjectFactory.html#existing) on a new Group instance.

The Group isn't added to the update list.

## Example Test Code

```js
var group = this.add.existing(new Phaser.GameObjects.Group(this));

console.assert(this.sys.updateList._pending.includes(group));
```

## Additional Information

https://github.com/photonstorm/phaser/commit/f513f5bf3181001753077ab659511098af621a14

I suppose Group needs an `addedToScene()` method.

**Comment by photonstorm** [comment]
Should now be fixed in master. Please let me know if not.
