### ISSUE TITLE
Cannot change some data of the initial game settings.

### ISSUE THREAD

**Issue by shimozurdo** [photonstorm/phaser#5305]
## Version 

* Phaser Version: 3.24.1

* Operating system: Windows 10

* Browser: Chrome / Edge

## Description

I cannot change some values in the config game for example **gameTitl**e or **gameVersion**, but concretely I was interested in change the value of **loaderPath**, as the docs says:

_A URL path used to resolve relative paths given to the loader. Example: 'images/sprites/'._

https://photonstorm.github.io/phaser3-docs/Phaser.Core.Config.html#loaderPath

## Example Test Code

![image](https://user-images.githubusercontent.com/4074823/93005330-b94a6400-f515-11ea-8710-33486b0a2c4c.png)

then a console.log(this.game); in the _main.menu_ Scene

![image](https://user-images.githubusercontent.com/4074823/93005403-3d9ce700-f516-11ea-8c4a-a98c920c7506.png)

This values never are changed

## Additional Information

Amazing game engine!

**Comment by halilcakar** [comment]
Hello @shimozurdo ,

The properties should be like following:

```javascript
const config = {
    title: 'Blaster x',
    version: '1.0'
}
```

In src/core/Config.js code is following [this](https://github.com/photonstorm/phaser/blob/master/src/core/Config.js#L181):
```javascript
/**
 * @const {string} Phaser.Core.Config#gameTitle - The title of the game.
 */
this.gameTitle = GetValue(config, 'title', '');

/**
 * @const {string} Phaser.Core.Config#gameURL - The URL of the game.
 */
this.gameURL = GetValue(config, 'url', 'https://phaser.io');

/**
 * @const {string} Phaser.Core.Config#gameVersion - The version of the game.
 */
this.gameVersion = GetValue(config, 'version', '');
```

Hopefully this solves your problem =)

**Comment by shimozurdo** [comment]
Awesome! thank you @halilcakar .
