### ISSUE TITLE
Make public the scene field of a game object

### ISSUE THREAD

**Issue by PhaserEditor2D** [photonstorm/phaser#5308]
It would be great if we can get access to the scene of a game object. Right now there is a [GameObject.scene](https://github.com/photonstorm/phaser/blob/00421243e2fb46976fb4fa667f640dd299292d69/src/gameobjects/GameObject.js#L44)
 field but it is tagged as **protected**. In editors like VS Code, this field is not listed in the auto-completion list.
 
This small change allows us in Phaser Editor to create components and get access to the scene and its events through the entity (game object).

**[Optional] Do you want to help provide this feature?**

Yes, I want help to provide this feature.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by PhaserEditor2D** [comment]
Thanks!
