### ISSUE TITLE
RenderConfig pixelArt should also set antialiasGL to false

### ISSUE THREAD

**Issue by Vegita2** [photonstorm/phaser#5309]
## Version

* Phaser Version: 3.24.1

* Operating system: Ubuntu 20.04.1 LTS

## Description

Phaser version 3.20.0 introduced a new [RenderConfig](https://photonstorm.github.io/phaser3-docs/Phaser.Types.Core.html#.RenderConfig) property `antialiasGL` which is currently not overrriden by the `pixelArt` property.

I think `pixelArt` should override both `antialias` and `antialiasGL` in order to properly render pixel perfect graphics.

## Example Test Code

```javascript
const game = new Phaser.Game({
	width: scale.width,
	height: scale.height,
	type: Phaser.AUTO,
	parent: 'content',
	scale: {
		mode: Phaser.Scale.ScaleModes.NONE,
		zoom: 1 / window.devicePixelRatio
	},
	render: {
		// antialiasGL: false,
		pixelArt: true
	},
	zoom: 1,
	scene: [scene]
});
```

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
