### ISSUE TITLE
RetroFont bitmap text isn't rendering (3.50.0-beta.5)

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5310]
## Version

* Phaser Version: 3.50.0-beta.5

## Description

The text object isn't visible.

No error in console.

## Example Test Code

http://labs.phaser.io/view.html?src=src/game%20objects/bitmaptext/retro%20font/retro%20text%201.js&v=3.50.0-beta.5

**Comment by photonstorm** [comment]
Yeah I know, it's on my list :) Along with particle emitters with masks on!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
