### ISSUE TITLE
Cursor changes incorrectly when an interactive object is destroyed

### ISSUE THREAD

**Issue by JstnPwll** [photonstorm/phaser#5321]
## Version

* Phaser Version: 3.24.1

* Operating system: Windows

* Browser: Chrome

## Description

When hovering the cursor over an interactive object with the `useHandCursor` option enabled, if another interactive object with  `useHandCursor` enabled is destroyed, the cursor changes back to an arrow.

Expected behavior is that the cursor will only change if there is no longer an interactive object with the `useHandCursor` option under the pointer.

## Example Test Code

Paste this code into the Phaser 3 sandbox. After running, click one of the images.

```js
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

var image1, image2;

function preload ()
{
    this.load.image('logo', 'assets/sprites/phaser3-logo.png');
}

function create ()
{
    image1 = this.add.image(400, 300, 'logo')
              .setInteractive({ useHandCursor: true})
              .on('pointerdown', ()=> {
                  image2.destroy();
              })
    image2 = this.add.image(100, 100, 'logo')
              .setInteractive({ useHandCursor: true})
              .on('pointerdown', ()=> {
                  image1.destroy();
              })
}
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by JstnPwll** [comment]
> Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

Awesome. Just out of curiosity, will this also handle objects that are stacked? I.e. if the destroyed object is above a different one, will the cursor take into account the object which is interactive below the destroyed object?

**Comment by photonstorm** [comment]
No, just like you won't get a `pointerover` event if you destroy an object and the pointer is suddenly over the top of another one. It won't update until you next move the mouse.

**Comment by JstnPwll** [comment]
That was my guess. If I want to add this myself in my game, where should I start? Would I iterate through all children of the scene and somehow check the pointer position for collision with the hit area if they are interactive objects?

**Comment by JstnPwll** [comment]
Nevermind on this, I figured out a solution. I just call the mouse move update function on the scene's input plugin to refresh the hover state:

`this.sys.input.update(Phaser.Input.MOUSE_MOVE, [this.input.activePointer]);`
