### ISSUE TITLE
Atlas Remove Texture and Reload with Same Key Does Not Work

### ISSUE THREAD

**Issue by TedGriggs** [photonstorm/phaser#5323]
As with issue #4720, I am encountering the same issue with regular atlases:

this.scene.load.atlas("mykey", "/path.to/mykey.file"");

...loader says loaded and textures within atlas work. Later:

this.scene.textures.remove("mykey"]);
this.scene.load.atlas("mykey", "/path.to/mykey.file"");

...loader says loaded and textures within atlas do not work.

Perhaps the same fix should be applied here?  The same code sample from #4720, but using a regular atlas reproduces the error.

Thanks!

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
