### ISSUE TITLE
Website example not working

### ISSUE THREAD

**Issue by indignant** [photonstorm/phaser#5324]
## Version
* Operating system: OSX
* Browser: Firefox

## Description
I tried to find a repo for the website, but didn't have any luck. Please forgive me if this is in the incorrect repo.

I was looking at the website and noticed that some examples weren't working as expected.

Steps to reproduce:
- Go to: https://phaser.io/examples/v3/view/animation/single-sprite-sheet
- Note the example doesn't load
- Open dev tools
- Note the error: `Loading failed for the <script> with source “https://labs.phaser.io/src/animation/single%20sprite%20sheet.js”.`

Thank you for maintaining this project and I hope you have a good day!

**Comment by photonstorm** [comment]
Yeah, for now, use http://labs.phaser.io, please. The main site will be updated once I release 3.5 and sync the new examples with the site.
