### ISSUE TITLE
Camera setTint does not seem to do anything

### ISSUE THREAD

**Issue by carystanley** [photonstorm/phaser#5327]
First, I want to say Phaser is really awesome, you guys have a lot of excellent features, I love going thorough the docs trying to find new tricks and features.

## Version
* Phaser Version: v3.24.1
* Operating system: Mac OS
* Browser: Chrome 85

## Description

I saw camera had setTint, was expecting to use it to give a night time effect. But it does not seem to do anything.

## Example Test Code

```
        this.input.keyboard.on('keydown-' + 'N', () => {
            this.cameras.main.setTint(0x0000aa);
            this.time.delayedCall(3000, () => {
                 this.cameras.main.clearTint();
            });
        });
```

## Additional Information

Seems to pull in the Tint component here:
https://github.com/photonstorm/phaser/blob/v3.22.0/src/cameras/2d/Camera.js#L61

But if it has no real effect on the camera, I wonder if it makes sense to even mix in.

**Comment by photonstorm** [comment]
Hmm, no it doesn't use the Tint component at all. It needs removing.

**Comment by photonstorm** [comment]
Just looked at this further and tint is used when the Camera is rendering to a texture. So for this reason, I will leave it in.
