### ISSUE TITLE
Spines that use a previously loaded atlas is not loaded

### ISSUE THREAD

**Issue by Racoonacoon** [photonstorm/phaser#5331]
Spine Plugin : 8af35be

There seems to be a caching/loading issue with spines that share an atlas. Any spine that uses an atlas that has been previously loaded is not added to the cache, and will throw a ("no atlas found for : [atlas name]") warning when the spine is added via this.add.spine. There is even the possibility of a race condition here. In the example below, if background loads first, then the error will throw when congrats is added with this.add.spine method. If congrats happens to load first, however, the error will throw when background is added with this.add.spine. The example code works in earlier versions of the SpinePlugin.

Example (pseudo code):

preload()
{
this.load.spine("background", "Spines/backgrounds.json", "Spines/shared.atlas.txt", false);
this.load.spine("congrats", "Spines/congrats.json", "Spines/shared.atlas.txt", false);
this.load.spine("congrats2", "Spines/congrats2.json", "Spines/shared.atlas.txt", false);
}

create()
{
this.add.spine(0, 0, "background");

//If background loads first, I will get an : Uncaught TypeError: Cannot read property 'skeletonData' of null at //SpineGameObject.setSkeleton (SpinePlugin.min.js:31886)
this.add.spine(0, 0, "congrats");
this.add.spine(0, 0, "congrats2");
}

I investigated the code and was unable to find any definitive resolution, but I was able to conclude that the keys of "congrats" and "congrats2" do not exist when SpineFile.addToCache is called, but that they do exist when SpineFile.onFileComplete is called.

**Comment by photonstorm** [comment]
Do you have a test case or at the very least assets to test this with?

**Comment by Racoonacoon** [comment]
I'm working with my project manager to get some assets I can share publicly. I hope to have an example set up for you within a day or two.

**Comment by Racoonacoon** [comment]
[SpineErrorTest.zip](https://github.com/photonstorm/phaser/files/5295708/SpineErrorTest.zip)
I have attached a simple project that exhibits the error. Navigate to SpineErrorTest/scenes/mainScene.js to view the scene code.

**Comment by photonstorm** [comment]
Thanks for the zip file. I cannot get it to display either of the skeletons, though. See my version of your code below. It doesn't error, it's just an empty scene:

```js
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    scene: {
        preload: preload,
        create: create,
        pack: {
            files: [
                { type: 'scenePlugin', key: 'SpinePlugin', url: 'plugins/3.8.95/SpinePluginDebug.js', sceneKey: 'spine' }
            ]
        }
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.setPath('assets/tests/spinemulti/');

    this.load.spine('question', 'skeleton.json', 'test.atlas.txt', false);

    // this.load.spine('exclaim', 'skeleton2.json', 'test.atlas.txt', false);
}

function create ()
{
    let question = this.add.spine(400, 300, 'question');

    // let exclaim = this.add.spine(400, 300, 'exclaim');
}
```

There are no errors. The `test.png` loads file in the network panel. Everything is there in the Spine cache, it just won't render anything. I'll keep playing to see if I can figure it out.

**Comment by photonstorm** [comment]
Interesting... this is almost certainly why:

![image](https://user-images.githubusercontent.com/164476/94545165-18151a80-0244-11eb-9c48-c7ba4421a066.png)

**Comment by photonstorm** [comment]
Right, I've pushed a fix for this to the repo just now. Am very sure this will work, but I can't test it properly to be 100%, so please do so when you get a chance. The Spine Plugin has also been updated to the 3.8.99 runtimes, too.
