### ISSUE TITLE
Timeline bug?

### ISSUE THREAD

**Issue by MadDogMayCry0** [photonstorm/phaser#5335]
3.24.1
https://playcode.io/683803

I noticed that my character often twitches when moving. At first I attributed this behavior to small browser freezes, but then I noticed that when a character twitches, other characters that animate without using timeline continue to run smoothly.

I made a small preview. I don’t know, maybe I’m doing something wrong.

**Comment by photonstorm** [comment]
Duplicate of #5144 (just tidying up as I refactor Timelines)
