### ISSUE TITLE
Spine Atlases that refer to an image that contains an underscore character are not displayed.

### ISSUE THREAD

**Issue by Racoonacoon** [photonstorm/phaser#5336]
Spine Plugin : e11c820
Phaser Build : 6bc858e

If a Spine atlas refers to a texture that has an underscore in its name, that texture will not display, and will instead return a "__MISSING" texture. I did some internal digging and it seems that the texture key is getting chopped before the first underscore, so it cannot find the texture by its referred name. I have attached an example of the error. For example, in the code I posted, the expected key name is "test_with_underscore.png", but it is being stored as "with_underscore.png"

[SpineErrorTest_NamesWithUnderscores.zip](https://github.com/photonstorm/phaser/files/5314250/SpineErrorTest_NamesWithUnderscores.zip)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
