### ISSUE TITLE
Error creating a Group (v3.50.0-beta.7)

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5339]
## Version

* Phaser Version: 3.50.0-beta.7

## Description

```js
this.add.group();
```

> TypeError: this.on is not a function. (In 'this.on(Events.ADDED_TO_SCENE, this.addedToScene, this)', 'this.on' is undefined)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by samme** [comment]
It works, but — I don't think Group#addedToScene() and Group#removedFromScene() will ever be called, because ADDED_TO_SCENE and REMOVED_FROM_SCENE are fired by the Display List, which the group isn't in.
