### ISSUE TITLE
Custom shader pipeline issue

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5341]
## Version

* Phaser Version: 3.50-beta.7

* Operating system: win10

* Browser: Chrome

## Description

I try to run custom shader pipeline in this [official example](https://labs.phaser.io/edit.html?src=src\renderer\custom%20pipeline%20multi%20texture.js&v=dev), which dose not support for p3.50-beta.7 yet.

After changing

- `game.renderer.addPipeline` to `game.renderer.pipelines.add` in line 83
- `customPipeline.setFloat2` to `customPipeline.set2f`  in line 85
- `customPipeline.setFloat1` to `customPipeline.set1f` in line 113

I can run this example code without any error shown at console, but I can't get correct result, the sprite with custom pipeline dose not show 
![圖片](https://user-images.githubusercontent.com/817962/94990405-5e54db80-05ae-11eb-9f02-d7de6829df2a.png)

Here is my modified code : 

```javascript
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var CustomPipeline = new Phaser.Class({

    Extends: Phaser.Renderer.WebGL.Pipelines.MultiPipeline,

    initialize:

    function CustomPipeline (game)
    {
        Phaser.Renderer.WebGL.Pipelines.MultiPipeline.call(this, {
            game: game,
            fragShader: `
            precision mediump float;

            uniform sampler2D uMainSampler[%count%];
            uniform vec2 uResolution;
            uniform float uTime;

            varying vec2 outTexCoord;
            varying float outTexId;
            varying vec4 outTint;

            vec4 plasma()
            {
                vec2 pixelPos = gl_FragCoord.xy / uResolution * 20.0;
                float freq = 0.8;
                float value =
                    sin(uTime + pixelPos.x * freq) +
                    sin(uTime + pixelPos.y * freq) +
                    sin(uTime + (pixelPos.x + pixelPos.y) * freq) +
                    cos(uTime + sqrt(length(pixelPos - 0.5)) * freq * 2.0);

                return vec4(
                    cos(value),
                    sin(value),
                    sin(value * 3.14 * 2.0),
                    cos(value)
                );
            }

            void main()
            {
                vec4 texture;

                %forloop%

                texture *= vec4(outTint.rgb * outTint.a, outTint.a);

                gl_FragColor = texture * plasma();
            }
            `
        });
    }
});

var game = new Phaser.Game(config);

var bunny;
var time = 0;
var customPipeline;

function preload ()
{
    this.load.image('beball', 'assets/sprites/beball1.png');
    this.load.image('atari', 'assets/sprites/atari400.png');
    this.load.image('bikkuriman', 'assets/sprites/bikkuriman.png');
    this.load.image('bunny', 'assets/sprites/bunny.png');
}

function create ()
{
    customPipeline = game.renderer.pipelines.add('Custom', new CustomPipeline(game));

    customPipeline.set2f('uResolution', game.config.width, game.config.height);

    this.add.sprite(100, 300, 'beball');
    this.add.sprite(400, 300, 'atari').setPipeline('Custom');
    bunny = this.add.sprite(400, 300, 'bunny').setPipeline('Custom');
    this.add.sprite(700, 300, 'bikkuriman');

    this.input.on('pointermove', function (pointer) {
        bunny.x = pointer.x;
        bunny.y = pointer.y;
    }, this);

    this.input.on('pointerdown', function (pointer) {

        if (bunny.pipeline === customPipeline)
        {
            bunny.resetPipeline();
        }
        else
        {
            bunny.setPipeline('Custom');
        }

    }, this);
}

function update ()
{
    customPipeline.set1f('uTime', time);

    time += 0.05;

    bunny.rotation += 0.01;
}
```

Sorry I could not provide more information.

**Comment by rexrainbow** [comment]
BTW, shader pipeline applied on camera works great in my testing (3.50-beta 7)

**Comment by telinc1** [comment]
You have to pass the names of the uniforms that the shader uses in its config or they won't be cached:
```js
Phaser.Renderer.WebGL.Pipelines.MultiPipeline.call(this, {
    game: game,
    uniforms: ['uResolution', 'uTime'],
    // ...
```

With this, the images are shown (because the resolution gets properly set), but the time doesn't update correctly since the new uniform methods no longer enable the pipeline's program. Binding the pipeline before setting the time in `update` seems to work - `game.renderer.pipelines.set(customPipeline);`. You can also just use the methods on `game.renderer` to update the uniform - `game.renderer.setFloat1(customPipeline.program, 'uTime', time);`. I'm not sure which solution is better (or if both are bad), but the latter is equivalent to what the old pipeline methods did.

**Comment by rexrainbow** [comment]
@telinc1 

Thank you, after adding `uniforms: ['uResolution', 'uTime']`, I got the sprite indeed. And `game.renderer.pipelines.set(customPipeline)` both. It seem I missed 2nd instruction in my plugin testing.

**Comment by rexrainbow** [comment]
@telinc1 

It seems that using `game.renderer.setFloat1` is better, compared wuth `customPipeline.set1f`. We don't know if this custom shader pipeline program is here or not, in application.

**Comment by telinc1** [comment]
Still, is there an official stance on this? Given that the examples haven't been updated yet, what is the preferred way to set uniforms in 3.50?
