### ISSUE TITLE
[3.50] private anim helpers

### ISSUE THREAD

**Issue by juanitogan** [photonstorm/phaser#5345]
When using `sprite.anims.create` one would expect to find the other helpers such as `generateFrameNumbers` there as well.  Currently, `generateFrameNumbers` is found only under `scene.anims`, which works for private anims, just a bit wordier.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
