### ISSUE TITLE
Current Spine plugin has issues setting its bounds

### ISSUE THREAD

**Issue by Racoonacoon** [photonstorm/phaser#5351]
Phaser Build : 2e50061
Spine Plugin Build : ea36036

The current Spine plugin has issues setting its bounds. I have identified at least four errors related to bounds:
+ spineObj.getBounds() returns an AABB-like as expected, but all its values are +- Infinity
+ spineObj.updateSize() followed by spineObj.getBounds() returns an object with the errors above
+ spineObj.bounds property returns null
+ spineObj.drawDebug = true will not draw a rectangle around the spine object. A central green point is drawn, however.

I have uploaded an example showcasing the errors.
[SpineErrorTest_GetBounds.zip](https://github.com/photonstorm/phaser/files/5361266/SpineErrorTest_GetBounds.zip)

Thank you.

**Comment by photonstorm** [comment]
Hmm, `getBounds` is literally a direct pass-thru to the Spine Runtimes function of the same name. I wonder if they changed this without documenting it.

**Comment by Racoonacoon** [comment]
I looked at the spine runtimes, and I've been able to narrow the error down, but I'm still not positive on what code base the error lies. The issue is that slot.getAttachment() in skeleton.prototype.getBounds() returns null and thus the bounds are not calculated. If I get a slot manually via question.skeleton.drawOrder[0] and print it, I see that there is, indeed, an attachment present. slot.getAttachment() returns null however, as does slot.attachment, even though it is visible via console.log. Retrieving an attachment via the skeleton.getAttachment(index, name) function works. If I call getAttachment on the skeleton, and then call setAttachment on the slot, subsequent slot.getAttachment() calls function as intended. 

Furthermore, after calling setAttachment on the slot, calling getBounds on the skeleton functions as intended.
[Uploading SpineErrorTest_GetBounds.zip…]()


I have modified the example to express the latest debugging efforts.

**Comment by Racoonacoon** [comment]
[SpineErrorTest_GetBounds.zip](https://github.com/photonstorm/phaser/files/5365761/SpineErrorTest_GetBounds.zip)

**Comment by photonstorm** [comment]
I've tested this against a couple of the standard models that Esoteric provides (Spine Boy, etc) and it functions properly. As all Phaser does is pass the call through to the Spine runtimes, there's nothing more I can do. All of your digging to me indicates a problem in the runtimes, not the plugin, as all of those calls are their end. I would suggest reporting it on their repo tbh.

**Comment by photonstorm** [comment]
Also, the plugin is currently using 3.8.95 runtimes. If they've updated again, I could update the plugin to use any newer runtimes, which may resolve it (possibly)
