### ISSUE TITLE
Plug in your headphones, unplug them, and the audio stops

### ISSUE THREAD

**Issue by helloyoucan** [photonstorm/phaser#5353]
## Version
Phaser Version: 3.23.0 - bug might not occur in 3.22.0
Operating system: iOS 13.4.1
Browser: Safari

## Description

I use Web Audio.

Eveny paser Game Will this.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
