### ISSUE TITLE
[3.50beta9] masked spineContainer doesn't behave the same as normal container

### ISSUE THREAD

**Issue by spayton** [photonstorm/phaser#5354]
## Version

* Phaser Version:  3.50 beta9

## Description

Applying a geometry mask to a nested spineContainer doesn't work as expected.  Works ok when a normal container is used.

## Example Test Code

[jsFiddle here](https://jsfiddle.net/stupot/m3yvjtd5/)

This sets up nested left & right containers, each with a spineboy.  A mask is defined to show the bottom half of both spines.

Change the value in the switch statement to select the test.  The tests have all variations of applying the mask to neither, the outer container, the innerLeft or innerRight containers - for each of normal containers or spineContainers.

So, compare these test pairs (normal container vs spineContainer):

  nothing masked:  10 & 20 = same
  outer masked:  11 & 21 = same
  left masked:  12 & 22 = different
  right masked:  13 & 23 = different

eg. left nested container masked, 12 & 22.  Show the difference between normal container and spineContainer.

Test 12, normal container
![image](https://user-images.githubusercontent.com/4949575/95915168-ae961f80-0d9e-11eb-8859-6003875f49d8.png)

Test 22, spineContainer
![image](https://user-images.githubusercontent.com/4949575/95915212-bc4ba500-0d9e-11eb-9355-f23cc7a64f87.png)

**Comment by photonstorm** [comment]
Thanks for the detailed example. I've looked at this and after some fixes am happy it's working as well as it can, with one caveat.

First, the new plugin build will render all of your states correctly now, but only if you change this:

```js
        var containerOuter = this.add.spineContainer();
```

If you mix and match the container types (Spine Container within Container) then it's impossible for it to know what to do. If you keep the container types consistent (either both Container, or both Spine Container) then the new build of the plugin will work properly with masking.

I'm happy with this outcome and will add it to the docs. I'm not willing to shoe-horn all kinds of plugin conditional code into the Container code just to cope with this. I think it's fair enough to insist you stick to one type of Container if you wish to use masks.

**Comment by spayton** [comment]
I seem to tangle a lot with masking and containers, it's a tricky issue I know.  I'll try the changes
