### ISSUE TITLE
Phaser.Geom.Polygon - Missing types in constructor

### ISSUE THREAD

**Issue by trynx** [photonstorm/phaser#5357]
## Version

* Phaser Version: 3.24.1

## Description

Hello :)

I'm using Phaser with Typescript, while creating a polygon geometry object, the construct only receives `Phaser.Geom.Point[]` and doesn't let insert other type of data type per the description.

## Example Test Code

Example of how it should work but doesn't : `new Phaser.Geom.Polygon([0, 143, 0, 92, 110, 40, 244, 4, 330, 0, 458, 12, 574, 18, 600, 79, 594, 153, 332, 152, 107, 157])`

Description: 
@**param** points List of points defining the perimeter of this Polygon. Several formats are supported: 
             * - A string containing paired x y values separated by a single space: `'40 0 40 20 100 20 100 80 40 80 40 100 0 50'`
             * - An array of Point objects: `[new Phaser.Point(x1, y1), ...]`
             * - An array of objects with public x y properties: `[obj1, obj2, ...]`
             * - An array of paired numbers that represent point coordinates: `[x1,y1, x2,y2, ...]`
             * - An array of arrays with two elements representing x/y coordinates: `[[x1, y1], [x2, y2], ...]`

Constructor: 
`Phaser.Geom.Polygon(points?: Phaser.Geom.Point[]):`

## Additional Information

For now going around this I do:  `new Phaser.Geom.Polygon().setTo([<the vertex points in numbers array>])`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
