### ISSUE TITLE
[3.50] Particles alpha is ignored 

### ISSUE THREAD

**Issue by vforsh** [photonstorm/phaser#5358]
## Version
Phaser v3.50.0-beta.9

## Description
Particle alpha is ignored with WebGL renderer.  It doens't matter if I use some ease or just set fixed value, it always renderer with alpha = 1. It works fine with Canvas renderer though.

## Example Test Code
Demo - https://robowhale.com/html5/phaser-issues/particles-alpha/

I use very basic emitter to demonstrate the issue:
```
let particles = this.add.particles("star");
        particles.createEmitter({
            x: this.scale.width / 2,
            y: this.scale.height / 2,
            frequency: 33,
            quantity: 1,
            alpha: { start: 1, end: 0, ease: "Cubic.easeOut" },
            lifespan: 1500,
            speed: 100,
        });

```

**Comment by vforsh** [comment]
Looks like [this commit ](https://github.com/photonstorm/phaser/commit/951457c8813f34fa643623311bbee1ccae0b5557#diff-56001b836b7efe7ce00ad8d61745db7222249137b8676c050ffc966e39cb2b3a) caused the issue.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by vforsh** [comment]
Oh wow, that was quick! Thank you 🙏
