### ISSUE TITLE
Wrong definition of TAU (τ)

### ISSUE THREAD

**Issue by xMamo** [photonstorm/phaser#5361]
In [`src/math/const.js`](https://github.com/photonstorm/phaser/blob/v3.24.1/src/math/const.js#L18), Phaser defines the constant `TAU` to be `0.5 * PI`. This is <em>wrong</em>: the correct definition would be: τ = 2π, as described by [Wikipedia](https://en.wikipedia.org/wiki/Turn_(angle)#Tau_proposals) and the [Tau Manifesto](https://tauday.com/tau-manifesto).

`TAU` should be defined as being `2 * PI`, thus making `PI2` an alias for `TAU`.

**Comment by photonstorm** [comment]
I know, this is fixed in v4 but it's been this way forever in v3 and I'm not sure it's worth changing it now.
