### ISSUE TITLE
Share mask

### ISSUE THREAD

**Issue by wingcd** [photonstorm/phaser#5363]
## Version

* Phaser Version: 3.24.1

* Operating system: all

* Browser: all

## Description
I want use shared mask for gameobjects. but those display is not same with gameobject by own mask. So, how to use shared mask.
objects with share mask:
![image](https://user-images.githubusercontent.com/7530901/96460925-58215900-1256-11eb-9048-3a67ab4cbe8b.png)
objects with own mask:
![image](https://user-images.githubusercontent.com/7530901/96461016-72f3cd80-1256-11eb-80a5-ae4ac59c7d18.png)

## Example Test Code
```
class UIScene extends Phaser.Scene {
    constructor() {
        super({key: 'game', active: true})
    }

    preload() {

        this.load.image('aaa', './res/1.jpg');
    }

    create() {
        let g = this.add.graphics({x: 0, y: 0});
        g.visible = false;           
        g.fillStyle(0x1, 1);
        for(let i=0;i<10;i++) { 
            g.fillCircle(i*10+100, i*10+100, 50);
        }

        for(let i=0;i<10;i++) {
            let img = this.add.image(i*10+100, i*10+100, 'aaa');
            img.mask = img.createGeometryMask(g);
        }
    }

    update(time: number, delta: number) {
        super.update(time, delta);

        if(!(this as any).__fps) {
            (this as any).__fps = this.add.text(0,0,"",{
                color: "#00ff00"
            });
        }
        (this as any).__fps.text = 1000 / delta;
    }
}

export class App extends Phaser.Game {
    constructor(config: Phaser.Types.Core.GameConfig) {
        super(config);
    }
}

const config: Phaser.Types.Core.GameConfig = {
    title: "Starfall",
    parent: "game",
    type: Phaser.WEBGL,
    width: 960,
    height: 540,
    backgroundColor: "#f0f0f0",    
    scene: [UIScene], 
    scale: {
        mode: Phaser.Scale.RESIZE,
        autoCenter: Phaser.Scale.CENTER_BOTH,
        autoRound: true,   
    },
};


window.onload = () => {
    var game = new App(config);
}
```

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/share-mask-for-gameobjects/7746/7

**Comment by wingcd** [comment]
yeah. It's also my question on forum. but also display incorrect.

**Comment by wingcd** [comment]
I want do a ui framework. There will be some mask like scrollpane, circle avatar etc. So draw on a single graphic is not the workable way.
![image](https://user-images.githubusercontent.com/7530901/96666865-87d17d80-138a-11eb-944d-8ced04bcc0a9.png)
![image](https://user-images.githubusercontent.com/7530901/96666945-a768a600-138a-11eb-83cb-ce75bdb06e46.png)
![image](https://user-images.githubusercontent.com/7530901/96666993-be0efd00-138a-11eb-9dfa-c54361c08ae5.png)
![image](https://user-images.githubusercontent.com/7530901/96667147-10e8b480-138b-11eb-8dd8-9336c5626fa5.png)
![image](https://user-images.githubusercontent.com/7530901/96667325-75a40f00-138b-11eb-9f9c-2aef9b463fe7.png)

**Comment by photonstorm** [comment]
The only way to do this is to have a unique mask for each Game Object that needs it. Or, under 3.50, look at creating your own Post FX Pipeline to handle shared masking with a custom shader.
