### ISSUE TITLE
[3.50.0-beta.10] Color filling of render-texture

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5364]
## Version

* Phaser Version: Phaser v3.50.0-beta.10

* Operating system: win10

* Browser: Chorme, and firefox

## Description

In this [official demo of render-texture](https://labs.phaser.io/edit.html?src=src\game%20objects\render%20texture\render%20texture%20larger%20than%20camera.js). Change the filling color to `0xff0000` (red)  in line 27.
- It fills red color in Phaser v3.50.0-beta.5 
- But fills **blue** color in Phaser v3.50.0-beta.10

It seems the order of RGB is changed in render

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
