### ISSUE TITLE
GameObject.Text displays incorrect due to Spine

### ISSUE THREAD

**Issue by necrokot** [photonstorm/phaser#5366]
## Version

* Phaser Version: 3.24.1

* Operating system: Windows 10 Build 17763, Ubuntu 18.04.5 LTS, Manjaro Linux

* Browser:

## Description

Phaser.GameObject.Text displays incorrect when I change it's value after creating spine in same scene.

## Example Test Code

```js
var config = {
    type: Phaser.AUTO,
    width: 400,
    height: 200,
    scene: {
        preload: preload,
        create: create,
        pack: {
            files: [
                {
                    type: "scenePlugin",
                    key: "SpinePlugin",
                    url: "https://labs.phaser.io/plugins/SpinePlugin.js",
                    sceneKey: "spine"
                }
            ]
        }
    }
};

var game = new Phaser.Game(config);

function preload() {
    this.load.setPath("https://labs.phaser.io/assets/spine/demos/");
    this.load.spine("set1", "demos.json", ["atlas1.atlas"], true);
}

function create() {
    var first = this.add.text(0, 0, "1234567890", {
        fontFamily: "Georgia",
        fontSize: 40
    });
    var second = this.add.text(0, 50, "1234567890", {
        fontFamily: "Georgia",
        fontSize: 40
    });
    this.add.spine(400, 600, "set1.spineboy", "idle", true);
    second.text = "1234567890.";
}
```

[Codepen](https://codepen.io/necrokot/pen/abZmbVG)

## Additional Information

Upper text displays correct, bottom - incorrect.
![image](https://user-images.githubusercontent.com/39699106/96547518-e75d5980-12b4-11eb-9fee-029951925c18.png)

**Comment by photonstorm** [comment]
This is already fixed in the master branch. You need to _build_ the latest version of both the Spine Plugin and Phaser 3.50, but it works fine after that:

![image](https://user-images.githubusercontent.com/164476/96566563-a0c02d00-12bd-11eb-8824-220da6345296.png)
