### ISSUE TITLE
video doesn't load when using "loadeddata" on iOS 13.7 with cordova.

### ISSUE THREAD

**Issue by Kosmoon** [photonstorm/phaser#5368]
Tested on iOS 13.7 on cordova, the loader never fires the "complete" event when using "loadeddata" as loadEvent for a video. It seems that its waiting for a user interaction.
However it works when setting asBlob to "true"

**Comment by photonstorm** [comment]
I can't see how you can avoid this. It's up to your game to get that user interaction from them before you try and load the video. It's not really anything I can enforce on a code level. Failing that, load it as a blob?

**Comment by spayton** [comment]
Is this related to [#4910](https://github.com/photonstorm/phaser/issues/4910)

**Comment by Kosmoon** [comment]
> I can't see how you can avoid this. It's up to your game to get that user interaction from them before you try and load the video. It's not really anything I can enforce on a code level. Failing that, load it as a blob?

Yep loading it as blob resolves the issue and works both for iOS and Android, tested on many devices from old to new.
