### ISSUE TITLE
Safari iOS/macOS - Game audio continues playing after leaving page

### ISSUE THREAD

**Issue by AdamXA** [photonstorm/phaser#5370]
## Version

* Phaser Version: 3.24.1 and earlier

* Operating system: macOS 10.15.7 and iOS 14

* Browser: Confirmed on Safari 14.0, seen on older versions too.

## Description

- Bug only occurs on iOS/macOS Safari.
- Bug occurs only when an iframe on the page redirects to the same domain.
- Bug only occurs when Web Audio is enabled.

When I click on an iframe on the same page as the game, that tells the browser to navigate to another page on the domain, any game sound that is currently playing will continue playing on another webpage.

## Example Test Code

https://github.com/AdamXA/phaser3-webaudio-bug

`git clone git@github.com:AdamXA/phaser3-webaudio-bug.git` `npm install` `npm start`
Forked from Phaser 3 boilerplate.

In the example, once it is running, hear the audio playing, then click the white "Click here" text in the top left of the canvas to be redirected.

## Additional Information

This is one weird bug.

**Comment by photonstorm** [comment]
You're navigating away from the page in which Phaser lives? If so, I can't see how we could possibly fix this, sounds like (yet another) Safari bug to me.

**Comment by AdamXA** [comment]
Thanks I'll try forward it onto them then 👍

**Comment by AdamXA** [comment]
https://bugs.webkit.org/show_bug.cgi?id=218078

**Comment by AdamXA** [comment]
should be fixed in Safari Tech Preview 117

**Comment by photonstorm** [comment]
That's unusually quick of them to address :)

**Comment by photonstorm** [comment]
Closing this off as they've thankfully fixed it.
