### ISSUE TITLE
Phaser & Electron, Phaser Not Being Displayed

### ISSUE THREAD

**Issue by SwitchGM** [photonstorm/phaser#5372]
## Version

* Phaser Version: 3.24.1

* Operating system: win10 64bit

* Browser: Chrome (Electron.js)

## Description

Using phaser and electron, attempting to display a very simple circle on the screen. Upon running the command "electron .", nothing is displayed on the "screen". Only when I resize the window is something displayed. 

`window.addEventListener('resize', () => {
    game.scale.resize(window.innerWidth, window.innerHeight);
});`

Removing that bit of code and trying to resize again, doesn't display anything either. 

## Example Test Code

`let game = new Phaser.Game({`
`    type: Phaser.AUTO,`
`    parent: 'phaser-example',`
`    width: window.width,`
`    height: window.height,`
`    scene: {`
`        preload: preload,`
`        create: create,`
`        update: update`
`    },`
`    transparent: true`
`});`
` `
`let ball;`
` `
`function preload () {`
` `
`}`
` `
`function create() {`
`    ball = this.add.circle(200, 200, 80, 0x6666ff);`
`}`
` `
`function update() {`
` `
`}`
` `
`window.addEventListener('resize', () => {`
`    game.scale.resize(window.innerWidth, window.innerHeight);`
`});`

## Additional Information

I've got a repo holding all of this, for any other bits of code. https://github.com/SwitchGM/twitch-donation-ball

**Comment by MadDogMayCry0** [comment]
const config = {
	type: Phaser.WEBGL,
	scale: {
		mode: Phaser.Scale.FIT,
		autoCenter: Phaser.Scale.CENTER_BOTH,
		width: 1920,
		height: 1080
	},
	audio: {
		noAudio: true
	}
	scene: [SceneMain]
};

var game = new Phaser.Game(config);
