### ISSUE TITLE
When I was using HTMLAudio, Phaser didn't load audio File in cache

### ISSUE THREAD

**Issue by helloyoucan** [photonstorm/phaser#5375]
## Version
Phaser Version: 3.23.0 - bug might not occur in 3.22.0
Operating system: iOS 13.4.1
Browser: Safari

## Example Test Code

When I was using HTMLAudio, Phaser didn't load audio File in cache.

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one, including the assets (these are important for audio issues) and then we'll revisit this issue and look at resolving it for you if possible. Also, it's important to test this against the latest stable release (3.24)
