### ISSUE TITLE
Graphics setTexture make rectangle not visible

### ISSUE THREAD

**Issue by phamconganh** [photonstorm/phaser#5376]
## Version 3.24.1

* Phaser Version: 3.24.1

* Operating system: ubuntu

* Browser:  chrome

## Description
I draw a rectangle and a graphic game object. When i set Texture for graphic, the rectangle not visible!

## Example Test Code
`var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('bunny', 'assets/sprites/bunny.png');
}

function create ()
{
    var bunny = this.add.image(400, 300, 'bunny');
    this.add.rectangle(150,150,200,200).setFillStyle(0x6005ae)
    this.add.rectangle(500,500,200,200).setFillStyle(0xff0303)
    var graphics = this.add.graphics();
    graphics.setTexture('bunny');
}
`

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue and providing a code example (so many people don't!).

However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release (3.50).
