### ISSUE TITLE
Scene.add.Sprite on external fine

### ISSUE THREAD

**Issue by cosimocelestegoglia** [photonstorm/phaser#5379]
## Version

* Phaser Version: 3.24.1

* Operating system: windows 10

* Browser: google chrome

## Description
I try add the sprite not in the file when i defined the scene, but this external file, when i use scene.add.sprite, the add method return the sprite not exists. I use typescript and webpack.
Sorry for my bad english

**Comment by DRL9** [comment]
When and where do you invoke `MainClass.getPhaserManager().getPhaserScene().add.sprite(this.tileX(x, y) - 12, this.tileY(x, y) - 51, 'room_wall_y').setDepth(100).setOrigin(0.5, 0.5);`?
