### ISSUE TITLE
body.touching values not responsive on static Arcade objects

### ISSUE THREAD

**Issue by juanitogan** [photonstorm/phaser#5381]
## Version

* Phaser Version: 3.50.0.beta9

* Operating system: Win10

* Browser:

## Description

The `body.touching` flags are not updating as expected on a the static object during (or after) a collision between a static and a dynamic object in Arcade physics.  Also, the `body.wasTouching` flags do not update at all.  These are both true only for the static object.  The dynamic object reports flags as expeted.

Once a touching property (such as up, down, etc) turns true, it remains true forever, even after the collision.  My objects are currently set for overlap collisions but I believe the case was the same with collider.

I don't know how far back this behavior goes in Phaser versions.

As a side note, I was disappointed to find that these flags are set after processCallback and before collideCallback.  While this makes logical sense, I am currently not seeing the specific use cases for that setup.  I would find it more useful if the flags were set before processCallback.  Then, I could use the flags in my logic to decide if the collision should take place.  For example, I have a dynamic object that I also calc Z values for.  When it collides with certain objects, I would like to cancel the collision based on both its Z value and the side of the other object (different sides respond to different Z values -- a soccer goal, including the top cross bar, in this case).  Without these flags yet set in processCallback, I have to either calc the side on my own in processCallback, or I have to switch to an overlap and create the collision on my own in collideCallback.

**Comment by samme** [comment]
[StaticBody#blocked](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.StaticBody.html#blocked) and [StaticBody#touching](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.StaticBody.html#touching) are never reset. It's always been this way in Phaser 3. It may not be ideal, but it's documented.

**Comment by juanitogan** [comment]
Ah, I see.  Very surprising.  Yes, not ideal.  I admit, I may not have read StaticBody's version of the touching property (surprising that I would need to).  And, if I did, I obviously missed that detail.  Regardless, it breaks the rule of least surprise.  Also, wasTouching is still nonfunctional and, thus, certainly doesn't match the doc.  I didn't mention blocked because I don't have a use case for it and haven't tested it.

If the touching prop is that different in behavior between objects, it should be renamed to make it less surprising; like hasTouched or everTouched.  Aside from that, however, I fail to see the usefulness of a prop that keeps historic state.  That, alone, is also surprising.  That concept is a serious head scratcher.  I would expect the programmer to always handle historic state -- that way they can reset it when and where they choose.  Sure, keeping state from one tick behind, like wasTouching does, is useful to detect begin/end of an event but, anything beyond a tick, is really odd.  (Also, in theory, wasTouching could be removed from visibility in favor of begin/end collision events, a la Unity, but I have no agenda to get into that.)

So, while I can imagine some incredibly weak and rare use cases for StaticBody.touching as it currently behaves, personally, I would remove both it and StaticBody.wasTouching entirely until their behavior is changed and/or fixed.  I wouldn't even rename it to hasTouched as I mentioned above (and would also remove anything else that keeps deep historic state).  It's not worth the code it takes up.

**Comment by samme** [comment]
I thought a lot about how to document those. They're not useful, but they exist for compatibility with dynamic bodies. It's probably better to describe them that way.

Best alternative is to use a nearly-static dynamic body.

**Comment by juanitogan** [comment]
Yeah, that is a bit of a conundrum.  I'm not a JS OOP guru so I can't say I have a solid recommendation as to what to do about parity between objects.  All I can add is that red herrings are a big time sink and frustration point.

I wasn't too worried as to other solutions.  For me, it was (so far) as simple as switching all logic to just the dynamic body.  I didn't start there because the dynamic object is small, circular, possibly rotated, and fast, and, without full knowledge on the touching logic vs tunneling and penetration, it just seemed safer to put the logic on the larger static object.  Otherwise, yes, I went back and looked at [this example](https://phaser.io/examples/v3/view/physics/arcade/collision-direction) and saw that the "static" platform is indeed dynamic but set to immovable.

Anyhow, thanks for talking and thank you for your work on this engine.
