### ISSUE TITLE
Error when adding image to container

### ISSUE THREAD

**Issue by michalens** [photonstorm/phaser#5382]
* Phaser Version: 3.24.1
* Operating system: MacOS Mojave
* Browser: Mozilla Firefox

## Description

In my scene inside `create()` function I create a container
```
this.dialogueBox = this.add.container(387, 300);
```

After I have an event listener in `create`
```
this.input.keyboard.on('keyup-' + 'ENTER', () => {
            this.playScript(this.getDialogue.next().value);
       })
```

So, my eventListener fires a series of function and gets to this line 

```
const boxImage = this.add.image(387, 300, 'middleBox');
this.dialogueBox.add(boxImage); // this line errors
this.dialogueBox.add(this.make.text(60, 260, text, {fill: 'black', wordWrap: { width: 270 } }), true);
```

And I get an error 
`Uncaught TypeError: this._displayList is null`

However, if I put the previous three lines inside `create` function right after I add a container, it's all fine.

## Additional Information

Can I even add items to the container outside of create? Maybe this is what's causing the issue?

**Comment by photonstorm** [comment]
Without a runnable example, this looks like a scope issue. You can add items into a Container at any point once the Scene has started. There are no limitations, in fact, the Container has absolutely no idea what state your game is in, in order to even prevent it if it wanted to.

**Comment by michalens** [comment]
@photonstorm I can't reproduce it now for some reason. 
I don't get an error, but now image and text that i add to the container are not showing up.
Here's the repo - https://github.com/michalens/ons
run 
```
npm install
npm start
```

The code is in src/scenes/DialogueScene.js on lines 77 and 126

**Comment by halilcakar** [comment]
Hey @michalens.

There is a small mistake on [here](https://github.com/michalens/ons/blob/master/src/scenes/DialogueScene.js#L126)

It need to be like following:

```javascript
 const boxImage = this.make.image({ x: 0, y: 0, key: 'middleBox' });
// or 
const boxImage = this.add.image(0, 0, 'middleBox');
```
That's why you can't see that `boxImage` gameObject :)

**Comment by michalens** [comment]
@halilcakar thanks! But it's still not working either way

**Comment by halilcakar** [comment]
Okey i got your problem so, on DialogScene, you are adding the `this.dialogBox` after that you start your scripts, which adds a background image on top of your dialogBox :)

```javascript
//on line 95 to 98 change
case 'background':
                this.add.image(0, 400, data.backgroundName).setScale(0.5);
                this.children.bringToTop(this.dialogueBox);
                break;
```

And you can see you `dialogueBox` is there =)

![image](https://user-images.githubusercontent.com/18047554/97888433-30dd8800-1d3c-11eb-9ada-72303dbd1dfd.png)

**Comment by michalens** [comment]
@halilcakar Thanks a lot!
