### ISSUE TITLE
null is not an object (evaluating 'this.manager.isLocked')

### ISSUE THREAD

**Issue by helloyoucan** [photonstorm/phaser#5383]
## Version
    "phaser": "^3.24.1",
* Browser: iso webview

## Description

When I was using Html5Audio, I used the following code to simulate clicking unlock sound, but an error occurred.

## Example Test Code

```javascript
    const event: TouchEndEvent = document.createEvent('Events');
    event.initEvent('touchend', true, true);
    event.changedTouches = [];
    document.body.dispatchEvent(event);
```
Error message received:
null is not an object (evaluating 'this.manager.isLocked')

or
Uncaught TypeError: Cannot read property 'isLocked' of null

How do I solve it?
Thanks.

## Additional Information
I wrote a game and applied it to the webview, and then set the webview to allow the media to play automatic sound, but it seems that due to the sound management mechanism of phaser, the user must click to unlock the sound playback when using html5audio, so I wrote Code that simulates a click.

**Comment by photonstorm** [comment]
Browsers require a click to unlock audio playback. It's nothing to do with Phaser (believe me, I wish we didn't have to do this.) We just have to work with what they enforce upon us. I don't believe a 'fake' click will bypass this.
