### ISSUE TITLE
[3.50 beta 10] RenderTexture - draw / drawFrame doesn't work correctly

### ISSUE THREAD

**Issue by vforsh** [photonstorm/phaser#5384]
## Version
Phaser 3.50 beta 10 (latest from the repo)

## Description
When I use drawFrame on render texture the result has an incorrect size and it turned upside down ![2020-11-05_15-56-56](https://user-images.githubusercontent.com/190223/98244464-8f934380-1f80-11eb-988d-87bebc0bb507.png)

## Additional Information
Demo - https://robowhale.com/html5/phaser-issues/render-texture-draw/
Source code - https://robowhale.com/html5/phaser-issues/render-texture-draw/js/index.js

```
    preload() {
        this.load.image('bg', 'assets/graphics/bg.png');
    }

    create() {
        this.addImage();
        this.addRenderTexture();
    }

    addImage() {
        this.addLabel("Original Image", 250, 40);
        this.image = this.add.image(250, 320, "bg");
    }

    addRenderTexture() {
        this.addLabel("Render Texture", 750, 40);
        this.renderTexture = this.add.renderTexture(750, 320, this.image.width, this.image.height);
        this.renderTexture.drawFrame("bg");
        // this.renderTexture.draw(this.image, 0, 0)
        this.renderTexture.fill(0xff0000, 0.33);
        this.renderTexture.setOrigin(0.5);
    }

    addLabel(content, x, y) {
        let style = {
            fontSize: "32px",
            color: "#ffffff",
            align: "center",
        };
        let label = this.add.text(x, y, content, style);
        label.setOrigin(0.5);
        return label;
    }
```

**Comment by vforsh** [comment]
The issue starts to occur after these commits:
https://github.com/photonstorm/phaser/commit/291f588110e31e847502a93a44ee159b72b29d44
https://github.com/photonstorm/phaser/commit/371425a5d23234748e1020ece65b441694a2f687

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
