### ISSUE TITLE
A bug with createLayer and getTilesWithinShape

### ISSUE THREAD

**Issue by gammafp** [photonstorm/phaser#5385]
## Version

* Phaser Version: v3.50.0-beta.10

* Operating system: Windows 10

* Browser: Chrome

## Description
A error with createLayer and  `map.getTilesWithinShape(rect, { isColliding: onlyColliding });`

## Example Test Code
[LINK TO EXAMPLE](https://labs.phaser.io/view.html?src=src\3.50\tilemap\dynamic\get%20tiles%20in%20shape.js).

## Additional Information
![image](https://user-images.githubusercontent.com/9221946/98354116-92457580-2020-11eb-9dfb-d82c939afb83.png)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
