### ISSUE TITLE
iOS audio locks when audio context is interrupted

### ISSUE THREAD

**Issue by SBCGames** [photonstorm/phaser#5390]
## Version

* Phaser Version: tested on 3.50 - beta X and some of the previous versions

* Operating system: iOS

* Browser: Safari

## Description

 iOS often puts audio context state into state "interrupted". It can happen with incoming call and (at least on iPad / iOS 14) it also happens when app is minimized with home button. What also happens is, that audio, previously unlocked in the beginning of game, is locked again and needs to be unlocked. Otherwise game looses all sounds.

 There is similar (maybe the same) issue (https://github.com/photonstorm/phaser/issues/5156) - at least looking at description. But as I am not sure, I started this new one.

 In onFocus (https://github.com/photonstorm/phaser/blob/master/src/sound/webaudio/WebAudioSoundManager.js#L335) code is testing if audio was unlocked. When I changed it to this, I got rid of the problem:
``` javascript
    onFocus: function ()
    {
        /*
        if (!this.locked)
        {
            this.context.resume();
        }
        */
        
        this.locked = true;
        this.unlock();
    },
```

**Comment by AdamXA** [comment]
this seemed to fix a bug I had when using `prompt()` which would also put the state into "interrupted"

**Comment by micsun-al** [comment]
This issue might also be related? https://github.com/photonstorm/phaser/issues/4790

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
