### ISSUE TITLE
phaser.io is offline

### ISSUE THREAD

**Issue by mdtrooper** [photonstorm/phaser#5392]
I check your website https://phaser.io from Spain and it is offline.

**Comment by MMontalto** [comment]
From general channel of Discord:
![image](https://user-images.githubusercontent.com/18440901/98666733-b91be880-234d-11eb-8bdc-74f94c2f09f0.png)

It will be back online soon.

**Comment by photonstorm** [comment]
Yeah I know, host is aware and working on it. Doesn't need an issue here, to be honest, it'll be back when they fix it.

**Comment by TheLandoCal** [comment]
Based on their [Bug Report ISSUE_TEMPLATE](https://raw.githubusercontent.com/photonstorm/phaser/master/.github/ISSUE_TEMPLATE/bug_report.md),

> This repo should not be used for technical support. If you're struggling to use Phaser then post your question to the [forum](https://phaser.discourse.group/), [Slack](https://phaser.io/community/slack) or [Discord](https://phaser.io/community/discord) channels. GitHub Issues are for bugs and feature requests only.

It would be better to check in the [Phaser Discord](https://discord.gg/phaser) for this type of issue. Unfortunately, their Discord links to their website. The easiest way to gain access to the Phaser discord right now is through the [Phaser Discord Community](https://github.com/phaser-discord/community).

It appears that admins are aware of the issue based on this [message](https://discordapp.com/channels/244245946873937922/244245946873937922/775653638030622750).
