### ISSUE TITLE
[3.50.0-beta.10] Incorrect beta version

### ISSUE THREAD

**Issue by MMontalto** [photonstorm/phaser#5393]
## Version

* Phaser Version: 3.50.0-beta.10

* Operating system: Windows 10

* Browser: Google Chrome

## Description
With beta 10 on console it turns out to be 5.
createLayer method doesn't work during create

## Additional Information
package.json
![image](https://user-images.githubusercontent.com/18440901/98665785-6857c000-234c-11eb-9355-854c81b0249e.png)
browser console
![image](https://user-images.githubusercontent.com/18440901/98666157-e4ea9e80-234c-11eb-9fb6-b145712a84ce.png)
![image](https://user-images.githubusercontent.com/18440901/98665920-9b9a4f00-234c-11eb-9198-07c641e6ed81.png)

**Comment by photonstorm** [comment]
Use the dist file I attached to [the release](https://github.com/photonstorm/phaser/releases/tag/v3.50.0-beta.10), or if you clone from npm, do `npm run build` to build your own bundle.
