### ISSUE TITLE
Phaser.io offline during host investigation

### ISSUE THREAD

**Issue by drneecko** [photonstorm/phaser#5394]
What is happened with phaser.io, the website ?

**Comment by spayton** [comment]
I noticed labs was unavailable yesterday, thought maybe down for some maintenance, but still down today.

**Comment by photonstorm** [comment]
Duplicate of #5392 

The site is down due to an on-going ssh attack. The host is working on it. Should be back soon. Please, no more issues about this.

**Comment by photonstorm** [comment]
Host resolved this. Closing.
