### ISSUE TITLE
[3.50-beta10] Can't apply pipeline to camera

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5395]
## Version
* Phaser Version: 3.50-beta10
* Operating system: win10
* Browser: chrome

## Description

I try to apply pipeline to game object, or camera, In this [test code](https://codepen.io/rexrainbow/pen/zYBMaZK?editors=0010)
Applying pipeline to game object works fine, but nothing changed when applying pipeline to camera.

Dose camera only have post-pipeline in 3.50-beta10?

**Comment by FloodGames** [comment]
I have 
![image](https://user-images.githubusercontent.com/60991890/98854130-772c9880-245a-11eb-8dc5-0bf115ec67fe.png)

is that related?

**Comment by photonstorm** [comment]
@rexrainbow yes, Cameras only support post-pipelines in 3.50. Technically, they only ever did in 3.0 as well, it's just a bit clearer now where the difference lays.

@FloodGames no idea, best check you've built the latest master branch + built the latest plugin and tested it. If so, open as a new issue.
