### ISSUE TITLE
sprite.stop is not a function

### ISSUE THREAD

**Issue by yzy463300** [photonstorm/phaser#5397]
` const animConfig = {
      key: item.after,
      frames: [{ key: item.name }, { key: item.after }],
      frameRate: 6,
      repeat: -1,
    }
    game.anims.create(animConfig)
    const sprite = game.add
      .sprite(item.x, item.y, item.name)
      .setOrigin(0)
      .setInteractive()
    sprite.play(item.after)
if (sprite.anims.isPlaying) {
          sprite.stop() //: sprite.stop is not a function
        }
`

**Comment by photonstorm** [comment]
This is a 3.50 feature, and definitely does exist: https://github.com/photonstorm/phaser/blob/master/src/gameobjects/sprite/Sprite.js#L360-L376
