### ISSUE TITLE
Utils.Array.Remove does not correctly return removed items.

### ISSUE THREAD

**Issue by year221** [photonstorm/phaser#5398]
## Version
* Phaser Version: 3.24.0
* Operating system: Windows

## Description

Phaser.Utils.Array.Remove is expected to return the items that are successfully removed. 
Line 76 is supposed to remove items that are not found. However, this won't work as expected if the last element of the item was found and "removed" from the array. 

## Example Test Code
```
    var a = [ 'a', 'b','c','d'];   
    var removed=Phaser.Utils.Array.Remove(a,['e','c','f']);    
    console.log(removed);
```
The expected output should be 'c'. But the output is 'e'.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
