### ISSUE TITLE
Artifacts when resizing masked sprites with BitmapMask (WebGL)

### ISSUE THREAD

**Issue by Patapits** [photonstorm/phaser#5399]
## Version
* Phaser Version:

3.24.1
* Operating system:

Windows 10 10.0.19041
* Browser:

Chrome 86.0.4240.193

## Description

When trying to work with BitmapMask (WebGL), masked objects get some strange artifacts when resizing the window (if `Phaser.Scale.ScaleModes.RESIZE` is used or anything else that resize the game dynamically). When refreshing the game page, artifacts disappear, and will appear again upon resizing.

## Example Test Code

https://jsfiddle.net/nbw930zx/

## Additional Information

Here is a gif of what's happening when resizing : 
![Masking artifacts](https://media.giphy.com/media/oTntM23xQWNib5nu2O/giphy.gif)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by Patapits** [comment]
Just tried and it seems to work just fine, thank you !

**Comment by alinj-13** [comment]
Hello! 
I have same issue in version 3.60
Please check!

**Comment by NikitaShpanko** [comment]
I confirm, it does happen in 3.60.0!!!
