### ISSUE TITLE
[3.50-beta10] Missing properties declaration in constructor of Tile class

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5400]
## Version

* Phaser Version: 3.50-beta10

* Operating system:

* Browser:

## Description

Missing declaration in constructor and value assignment about [`Tile.right`](https://github.com/photonstorm/phaser/blob/master/src/tilemaps/Tile.js#L294) and [`Tile.bottom`](https://github.com/photonstorm/phaser/blob/master/src/tilemaps/Tile.js#L294) properties.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
