### ISSUE TITLE
latest beta - mesh from texture atlas bug?

### ISSUE THREAD

**Issue by MadDogMayCry0** [photonstorm/phaser#5402]
Hi.

Two bugs in one.

1:
I have a texture
![texture](https://user-images.githubusercontent.com/2493591/99523433-5bb01900-2997-11eb-9c16-a9e371c3d2d6.png)

and atlas
```Json
{
	"textures": [
		{
			"image": "texture.png",
			"format": "RGBA8888",
			"size": {
				"w": 112,
				"h": 56
			},
			"scale": 1,
			"frames": [
				{
					"filename": "ball",
					"rotated": false,
					"trimmed": false,
					"sourceSize": {
						"w": 60,
						"h": 56
					},
					"spriteSourceSize": {
						"x": 0,
						"y": 0,
						"w": 60,
						"h": 56
					},
					"frame": {
						"x": 0,
						"y": 0,
						"w": 60,
						"h": 56
					}
				},
				{
					"filename": "ball_2",
					"rotated": false,
					"trimmed": true,
					"sourceSize": {
						"w": 53,
						"h": 36
					},
					"spriteSourceSize": {
						"x": 0,
						"y": 1,
						"w": 52,
						"h": 35
					},
					"frame": {
						"x": 60,
						"y": 0,
						"w": 52,
						"h": 35
					}
				}
			]
		}
	],
	"meta": {
		"app": "http://free-tex-packer.com",
		"version": "0.6.6"
	}
}
```

When i load the atlas,
```Javascript
this.load.atlas('texture', 'texture.png', 'texture.json');
```
and then trying to apply it to mesh
```Javascript
var mesh = this.add.mesh(500, 400, "texture", "ball");
```
then I see the whole texture instead of the frame
![Безымянный](https://user-images.githubusercontent.com/2493591/99523638-a0d44b00-2997-11eb-833e-eb09525d110d.png)

Sry, i cant use fiddle to show src code, take a look demo here:
https://doctoral-arrangemen.000webhostapp.com/texture_atlas_bug/

And a code:

```Javascript
<script>
var SceneMain = new Phaser.Scene('SceneMain');
SceneMain.preload = function(){   
	this.load.dragonbone("Swordsman", "chars/swordsMan/SwordsMan_tex.png", "chars/swordsMan/SwordsMan_tex.json","chars/swordsMan/SwordsMan_ske.json");
	this.load.atlas('texture', 'texture.png', 'texture.json');
}

SceneMain.create = function(){ 
	
	 const vertices = [
            -1, 1,
            1, 1,
            -1, -1,
            1, -1
        ];

        const uvs = [
            0, 0,
            1, 0,
            0, 1,
            1, 1
        ];

    const indicies = [ 0, 2, 1, 2, 3, 1 ];
	var mesh = this.add.mesh(500, 400, "texture", "ball");
	 mesh.addVertices(vertices, uvs, indicies);
	mesh.panZ(60);
}


const config = {
	type: Phaser.WEBGL,
	scale: {
		mode: Phaser.Scale.FIT,
		autoCenter: Phaser.Scale.CENTER_BOTH,
		width: 1920,
		height: 1080
	},
	audio: {
		noAudio: true
	},
	plugins: {
		scene: [
			{ key: "DragonBones", plugin: dragonBones.phaser.plugin.DragonBonesScenePlugin, mapping: "dragonbone" }
		]
	},
	scene: [SceneMain]
};

var game = new Phaser.Game(config);
</script>
```

2:
SetTexture 
it works incorrectly! There are the same problems described in the first paragraph, but also the texture becomes very small and flattened.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/dragonbones-improvments/7673/16

**Comment by photonstorm** [comment]
This is because your UV coordinates are for the entire texture, not just the frame within it.

You need to fix your UV coordinates if you wish to use just a part of the texture.

`setTexture` just changes the texture that is bound to the Mesh. It will still use the same vertices and UVs you've defined in those arrays. If they don't match the texture size, they won't work.

**Comment by OmarShehata** [comment]
Just encountered this same issue and came here to report it as a bug. I think the confusing part is that `mesh` takes a frame in the constructor/also supports setFrame, so I'd update that will automatically update the UV's under the hood. Perhaps `frame` should be removed from the constructor to avoid confusion? @photonstorm
