### ISSUE TITLE
Quad setInteractive event listeners not firing after 3.15.1

### ISSUE THREAD

**Issue by michaelmausler** [photonstorm/phaser#5403]
## Version

* Phaser Version: 3.16.1 +

* Operating system: OS X

* Browser: Chrome, Firefox, Opera, Safari

## Description

Event listeners not firing on Quad using setInteractive after version 3.15.1. Tested `pointerover`, `pointerout`, and `pointerdown`.

## Example Test Code

3.15.1 - https://jsfiddle.net/wLk2zysr/2/
3.16.1 - https://jsfiddle.net/wLk2zysr/1/

**Comment by photonstorm** [comment]
Thanks for reporting this issue. However, I'm afraid it's too late to have this fixed, as Quad Game Objects have been removed in v3.50 which is the next version due out.
