### ISSUE TITLE
Make AnimationFrame's key optional in type def

### ISSUE THREAD

**Issue by justin-calleja** [photonstorm/phaser#5404]
AnimationFrame's key is currently not optional so you can't use `defaultTextureKey` and leave the `key` out e.g.

```ts
      this.anims.create({
        key: 'explode',
        defaultTextureKey: 'krockets',
        frames: [
          {
            // key: 'krockets',
            frame: 'explosion00',
          },
          {
            // key: 'krockets',
            frame: 'explosion01',
          },
          {
            // key: 'krockets',
            frame: 'blacksmoke00',
          },
        ],
        frameRate: 8,
      });
```

> Property 'key' is missing in type '{ frame: string; }' but required in type 'AnimationFrame'.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by justin-calleja** [comment]
@photonstorm thanks for the feedback and fixing this 👍  Sorry I couldn't have a look in time. I'm trying to verify but running in some issues but I'll ask on the Discord channel ("Cannot read property 'indexOf' of undefined" - when running `npm run tsgen`).

Cheers!
