### ISSUE TITLE
GeometryMask invertAlpha documentation

### ISSUE THREAD

**Issue by monteiz** [photonstorm/phaser#5406]
## Version

* Phaser Version: 3.24.1

* Operating system: Not relevant

* Browser: Not relevant

## Description
If I understood well, the `invertedAlpha` property and the `setInvertAlpha` method of the `GeometryMask` is available with the WEBGL renderer only.

If so, it should be stated in the docs.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
