### ISSUE TITLE
CANVAS game object transforms are wrong (v3.50.0-beta.10)

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5408]
## Version

* Phaser Version: v3.50.0-beta.10

## Description

With the CANVAS renderer image/sprite flip, position, rotation, and scale are incorrect.

## Example Test Code

<http://labs.phaser.io/view.html?src=src\transform\angle.js&v=3.50.0-beta.10> and others

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
