### ISSUE TITLE
BitmapMask causes the blend no effect.

### ISSUE THREAD

**Issue by jcyuan** [photonstorm/phaser#5409]
## Version
v3.23.0 (but it should still exist in 3.50)

## Description
```
const testImg = this.add.image(....);
const maskImg = new Phaser.GameObjects.Image(scene, 0, 0, "maskimg");
const mask = new Phaser.Display.Masks.BitmapMask(scene, maskImg);
testImg.mask = mask;
testImg.depth = 10;

const smoke = this.add.sprite(.....);
smoke.blendMode = Phaser.BlendModes.ADD;
smoke.play('wave');
smoke.depth = 11;
```

and the result:
![image](https://user-images.githubusercontent.com/850854/100331896-ac64e900-300b-11eb-9dcb-090d2cf06691.png)
(the black square is the smoke)

i did a inspect using Spector, and from the shot, the blend call is not called for the drawing of the smoke:
![image](https://user-images.githubusercontent.com/850854/100332689-a7ed0000-300c-11eb-8270-a15c17c7b9e7.png)

the bug is in v3.23.0, but i guess it still exists in v3.50 because the code is the same in the WebGLRenderer.js:
https://github.com/photonstorm/phaser/blob/339b4fd3df3194f92dc5b98ebfdff5fcc41e63ab/src/renderer/webgl/WebGLRenderer.js#L2335-L2353

i have fixed it with this change:
![image](https://user-images.githubusercontent.com/850854/100332907-f13d4f80-300c-11eb-94f2-5b8b342a0a4c.png)
move those 3lines after mask rendering, and all works fine, but i'm not sure this is the fix, i don't know what really happended, maybe there is flush or render etc which will reset the current blend mode of the renderer again? so it's just my temp solution just FYI.

after fixing:
![image](https://user-images.githubusercontent.com/850854/100333511-a2dc8080-300d-11eb-8970-bc1b40657ddc.png)

thanks.

**Comment by photonstorm** [comment]
It's the `mask.postRenderWebGL` call that does it, as it calls this:

```js
renderer.setBlendMode(0, true);
```

And because there's no blend mode stack, it resets whatever the Game Object had. I can't see any problem with swapping the order of these, so have done so.

**Comment by jcyuan** [comment]
hi @photonstorm , it has another problem just found:

if my mask image is on the same atlas with the image it masks, after the mask applying, the masked image 'rt' will be bound to `uMainSampler` instead of the atlas texture for coming game object...

if the mask image is on the seperated atlas, all fine~
