### ISSUE TITLE
[v3.50.0-beta.10/11/dev] Aseprite animations handler

### ISSUE THREAD

**Issue by buzzjeux** [photonstorm/phaser#5411]
## Version

* Phaser Version: [v3.50.0-beta.10] / 11 / dev

## Description

Aseprite animation handler seem broken ( anim's key is not found and don't display it)

## Example Test Code

Change to the 10 or dev build to repro
http://labs.phaser.io/view.html?src=src\3.50\animation\aseprite%20animation.js

**Comment by photonstorm** [comment]
This was fixed a couple of hours ago :) You have to use the new `this.load.aseprite` call to load the animation file. See updated example in the examples repo.
