### ISSUE TITLE
[3.50] RenderTexture - draw doesn't work correctly with Canvas renderer

### ISSUE THREAD

**Issue by vforsh** [photonstorm/phaser#5412]
## Version
3.50 - latest from the repo

## Description
This issue occurs only with Canvas renderer. The drawn image (red box) has incorrect dimensions, it is stretched both horizontally and vertically.

![2020-11-26_18-53-27](https://user-images.githubusercontent.com/190223/100371454-d53fab00-3018-11eb-9f36-f6689639e654.png)

## Example Test Code
Live example - https://robowhale.com/html5/phaser-issues/render-texture-draw/?forceCanvas=1
Full source code - https://robowhale.com/html5/phaser-issues/render-texture-draw/js/index.js
```
        private addImage() {
		this.addLabel("Original Image", 250, 40)
		this.image = this.add.image(250, 320, "bg")
	}
	
	private addRenderTexture() {
		this.addLabel("Render Texture", 750, 40)
		
		this.renderTexture = this.add.renderTexture(750, 320, this.image.width, this.image.height)
		this.renderTexture.drawFrame("bg")
		this.renderTexture.setOrigin(0.5)
		
		let position = this.image.getTopLeft()
		let rect = this.add.image(position.x, position.y, "red_rect")
		rect.setOrigin(0)
		
		this.renderTexture.draw(rect, 0, 0)
		// this.renderTexture.drawFrame("red_rect", 0, 0)
	}
```

## Additional Information
If I draw the very same image with `drawFrame` it works fine, with no stretching.

**Comment by photonstorm** [comment]
I'm happy this works properly now. I used the following test against the master branch:

```js
var config = {
    type: Phaser.CANVAS,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d88',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('bg', 'assets/pics/purple-dots.png');
    this.load.image('nayuki', 'assets/pics/nayuki.png');
}

function create ()
{
    var bob = this.make.image({ key: 'nayuki' }).setOrigin(0, 0);

    var rt = this.add.renderTexture(400, 300, 800, 600).setOrigin(0.5, 0.5);

    rt.draw('bg', 0, 0);

    rt.drawFrame('nayuki', null, 0, 0);
    
    rt.draw(bob, 16, 16);
}
```

Assets are from the Phaser 3 Examples repo. The Sprite is offset by 16px. I get the following:

![image](https://user-images.githubusercontent.com/164476/101044495-4cc08d80-3577-11eb-9f9c-fdbff0955d6d.png)

No distortion and in the correct location for both `draw` and `drawFrame`.

**Comment by vforsh** [comment]
Try changing game width to 1200px and use this:
```
function create() {
		let bob = this.make.image({ key: 'nayuki' })
			.setDepth(100)
			.setPosition(700, 0)
			.setOrigin(0, 0);
		
		let rt = this.add.renderTexture(400, 300, 800, 600).setOrigin(0.5, 0.5);
		
		rt.draw('bg', 0, 0);
		
		rt.drawFrame('nayuki', null, 0, 0);
		
		rt.draw(bob, 180, 0);
	}
```

Here what I have got
![image](https://user-images.githubusercontent.com/190223/101058877-b607c700-359e-11eb-8681-9ef3b42a3c81.png)

**Comment by photonstorm** [comment]
Interestingly this only worked for `drawFrame` because it was setting `undefined` for all the context transform values! Now fixed properly.
