### ISSUE TITLE
[3.50-beta11] Feature suggestion of Post-fx pipeline

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5419]
1. There has [`setPostPipeline`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/components/Pipeline.js#L196) method to append a postfx pipeline, but only [`resetPipeline`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/components/Pipeline.js#L301) can remove all postfx pipelines, how about add a method `removePostPipeline(pipeline)` ? Or add an enable switch to turn on/skip a postfx pipeline.

2. How to register pipeline in plugin? Currently pipeline only can be registered in game config.

**Comment by photonstorm** [comment]
1) Yes, I'll add this.

2) You can call `PipelineManager.add()` directly from your plugin.
