### ISSUE TITLE
[3.50-beta11] Create post-fx pipeline in pipelineManager.boot

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5420]
## Version

* Phaser Version: 3.50-beta11

## Description

In [PipelineManager.boot](https://github.com/photonstorm/phaser/blob/master/src/renderer/webgl/PipelineManager.js#L236), it will [create instance](https://github.com/photonstorm/phaser/blob/master/src/renderer/webgl/PipelineManager.js#L246) from registered pipeline class. It works fine for normal pipeline class. 
Post-fx pipeline, registered by [`PipelineManager.addPostPipeline`](https://github.com/photonstorm/phaser/blob/master/src/renderer/webgl/PipelineManager.js#L379) might not able to be created [there](https://github.com/photonstorm/phaser/blob/master/src/renderer/webgl/PipelineManager.js#L246)
(I try to use PipelineManager.addPostPipeline in plugin.start method, which invoked before PipelineManager.boot)

**Comment by photonstorm** [comment]
I can't see why you can't call `addPostPipeline` even before `boot` has run, as all it does is put a new entry into the `classes` Map. As long as the `PipelineManager` has been instantiated by that point it should work?

**Comment by rexrainbow** [comment]
Sorry I forgot to add test code.

[Here](https://codepen.io/rexrainbow/pen/VwKLvbG) is a test code. I test 2 possible loading methods

1. Loading plugin in game config (line 99), which is not worked.
```
Uncaught TypeError: Cannot read property 'gl' of undefined
```
Please see the console for more detail information.

2. Loading plugin during preload stage (line 78), which is worked.

**Comment by photonstorm** [comment]
Thanks for the example, helped isolate it. Now fixed in master.
