### ISSUE TITLE
[3.50] RenderTexture - erase doesn't work correctly with Canvas renderer

### ISSUE THREAD

**Issue by vforsh** [photonstorm/phaser#5422]
## Version
3.50 - latest from the repo

## Description
This issue occurs only with Canvas renderer. When I erase with the texture key (e.g. `renderTexture.erase("texture")`) it draws the texture instead of erasing.
![2020-12-02_17-03-02](https://user-images.githubusercontent.com/190223/100882707-8bdfd780-34c0-11eb-9928-40a3737b3cf7.png)

## Example Test Code
Live example - https://robowhale.com/html5/phaser-issues/render-texture-erase/?forceCanvas=1
Source code - https://robowhale.com/html5/phaser-issues/render-texture-erase/js/index.js
```
preload() {
		this.load.image('bg', 'assets/graphics/bg.png')
		this.load.image('red_rect', 'assets/graphics/red_rect.png')
	}
	
	create() {
		this.addImage()
		this.addRenderTexture()
	}
	
	private addImage() {
		this.addLabel("Original Image", 250, 40)
		this.image = this.add.image(250, 320, "bg")
	}
	
	private addRenderTexture() {
		this.addLabel("Render Texture", 750, 40)
		
		this.renderTexture = this.add.renderTexture(750, 320, this.image.width, this.image.height)
		this.renderTexture.drawFrame("bg")
		this.renderTexture.setOrigin(0.5)
		
		let position = this.image.getTopLeft()
		let rect = this.add.image(position.x, position.y, "red_rect")
		rect.setOrigin(0)
		
		this.renderTexture.erase("red_rect", 0, 0)
	}

```

## Additional Information
The issue occurs only with canvas renderer, WebGL is fine - https://robowhale.com/html5/phaser-issues/render-texture-erase/?forceCanvas=0

Probably related to #5412

**Comment by photonstorm** [comment]
Just tested this example against the master branch in Canvas mode and it's erasing properly now:

http://labs.phaser.io/view.html?src=src%5Cgame%20objects%5Crender%20texture%5Cerase%20part%20of%20render%20texture%20canvas.js&v=dev

Please check for yourself, however.

**Comment by vforsh** [comment]
In this example, you erase with the existing game object and it works fine, yes

But if you will erase using the texture key it will draw it instead of erasing
![2020-12-03_18-36-23](https://user-images.githubusercontent.com/190223/101051421-881e8480-3596-11eb-9bcf-9088df6a7f96.png)

Try use (lines 42 and 49)
`rt.erase("brush", pointer.x - 16, pointer.y - 16); `
instead of 
`rt.erase(brush, pointer.x - 16, pointer.y - 16); `

And you will see the issue
