### ISSUE TITLE
[3.24.1] Can't use RenderTexture with Shader

### ISSUE THREAD

**Issue by ccaleb** [photonstorm/phaser#5423]
## Version
v3.24.1 (also tried with v3.50.0-beta.11)

## Description
When binding a RenderTexture to a shader's iChannel uniform, the shader does not render anything. Whereas, passing a texture from a loaded image does work.

Here's a rough outline of the steps I'm carrying out:

1. Create a RenderTexture object (using power-of-two dimensions)
2. Colour the Render Texture red using .fill()
3. Store a copy of the Render Texture in the Texture Manager using .saveTexture()
4. Add a shader to the display list and pass the texture to it using its key from the Texture Manager

### Expected Behaviour
You should see the shader display object on screen with a predominantly red texture.

### Actual Behaviour
The entire shader display object is black.

## Example Test Code

Live example: https://playground.chunk.co.uk/christopher/phaser-issues/issue1/dist/index.html
Full source code: https://playground.chunk.co.uk/christopher/phaser-issues/issue1/src/index.js

You can see the bulk of the code directly below.

```javascript
function preload() {
  this.load.image('metal', './assets/alien-metal.jpg');
  this.load.glsl('bundle', './assets/bundle.glsl.js');
}

function create() {
  // Create a 512x512 render texture and fill it red.
  var rt = this.make.renderTexture({ x: 0, y: 0, width: 512, height: 512 }, true);
  rt.fill(0xff0000, 1, 0, 0, 512, 512);

  // Store the render texture in the texture manager.
  rt.saveTexture('rt');
  
  // Create a shader and pass it our render texture.
  const shader = this.add.shader('Tunnel', 400, 300, 800, 600, [ 'rt' ]);

  // If the user clicks the shader then toggle between the render texture and the loaded image texture.
  shader.setInteractive();
  shader.on('pointerdown', function () {
    var currentTexture = shader.getUniform('iChannel0').textureKey;
    if (currentTexture === 'rt') {
        shader.setChannel0('metal');
    } else if (currentTexture === 'metal') {
        shader.setChannel0('rt');
    }
  });
}
```

## Additional Information

The code example above listens for mouse clicks on the shader. When clicked, it swaps between the render texture and a texture from a loaded image. Whereas the render texture never renders within the shader, the loaded image does.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by ccaleb** [comment]
Hi, I've re-tested this with the latest code from master (and also from the commit for this bug) and it still seems to be broken.

I've uploaded my source and a latest live demo here:

Live example: https://playground.chunk.co.uk/christopher/phaser-issues/issue1b/dist/index.html
Full source code: https://playground.chunk.co.uk/christopher/phaser-issues/issue1b/src/index.js

And here's a link to the original live example I provided: https://playground.chunk.co.uk/christopher/phaser-issues/issue1/dist/index.html

When comparing the original live version I provided with the latest one, I noticed the following differences:

1. The following WebGL warning is now output to the browser's developer console: `WebGL: INVALID_OPERATION: bufferSubData: no buffer`

2. When I click on the screen to swap the texture that the shader is using, nothing appears to happen. I now see a blank screen in both cases.

Additional Notes:

The version of Phaser I tested with was taken from master and installed as a node package using:

`npm install https://github.com/photonstorm/phaser.git`

I also tried using the actual bug fix commit instead:

`npm install https://github.com/photonstorm/phaser.git#d6d5c095521429daf3151e4bb4b968aa15235927`

Both exhibited the same issues.

Thanks.

**Comment by photonstorm** [comment]
http://labs.phaser.io/view.html?src=src%5C3.50%5Cgame%20objects%5Cshaders%5Cshader%20using%20a%20render%20texture.js&v=dev

This is a dev build prior to further changes being made in Render Texture (to solve an unrelated issue, but the changes will impact the master branch currently)
