### ISSUE TITLE
[3.50-beta12] Render corruption when last spine in container is not visible

### ISSUE THREAD

**Issue by spayton** [photonstorm/phaser#5424]
## Version

* Phaser Version: v3.50, current beta 12 & beta 11 tested

* OS/Browser: Win10 64bit, Chrome 86.0.4240.198

## Description

With at least 2 spines, together and in the last positions of a container.  If the last spine is set visible = false, rendering of all  components, whether inside or outside container, may be affected.

## Example Test Code

jsFiddle example [here](https://jsfiddle.net/stupot/x5tvp8bs/)

It displays a image and 2 spineboys in a container, this is correct:

![image](https://user-images.githubusercontent.com/4949575/100915412-36a9c300-34cc-11eb-9a7f-e844e519e530.png)

If the last spineboy is set visible = false, then all components are not drawn, this is not correct as expected:

![image](https://user-images.githubusercontent.com/4949575/100915542-66f16180-34cc-11eb-8993-7bf645131396.png)

## Additional Information

The app that this example was condensed from, was doing a lot more and exhibited a range of rendering problems, not just all images not drawing like the example.  There were blendmode errors and unknown webgl buffer warnings.  The common trigger was a spine not visible and last in a container.

**Comment by spayton** [comment]
and maybe related, https://github.com/photonstorm/phaser/issues/5277#issuecomment-724724238 has popped up again in current beta13, mixing images and spines, understandably it seems to be a frequent casualty when there's work on the pipeline/binding

seen here in [labs demo](http://labs.phaser.io/view.html?src=src\3.50\spine\basic%20spineboy.js&v=dev), there should be a phaser logo image top left and spineboy, when it's bust the logo is not seen.

**Comment by photonstorm** [comment]
This works fine if the Spine objects are in a SpineContainer, it's only regular containers that break it.

I've pushed up a fix for this to the master branch, however, it has side-effects.

In order to catch this, I had to extend the `willRender` method so that it ends the Scene Renderer batch and flushes the WebGL Pipelines. This restores order and fixes the issue. But, it means it will batch flush and rebind for _every_ Spine Game Object in a Container that doesn't render (i.e. camera ignore flag set, or invisible, etc) as long as there is something in the batch. There's no way to avoid this, either. Not without adding lots of Spine specific code into the Container Game Object, which I refuse to do, as I've already offered a better replacement for it.

**Comment by spayton** [comment]
Great, I'll get it tested.

I can't use the spineContainer because it has less functionality compared to the standard container, specificaly masks.  It's nice to have around though, I'd use it if I could.

**Comment by spayton** [comment]
Spine/image drawing seems ok now, at least I have been able to remove, dummy images that I had to insert in the right places to get things to render properly.

@photonstorm I did notice that on current build spine/mask positioning has shifted a little, which is relevant becase a few beta's back the same thing happened and I had to manualy adjust.  So either it's now fixed or now out, I'll test it properly to see which.

**Comment by photonstorm** [comment]
I didn't change anything to do with masking at all, however, I did use the brand new runtimes for this build.

**Comment by spayton** [comment]
I was using scalemode FIT with some slight manual viewport adjustments using setGameSize, when doing this beta12/13 behaved slightly differently, when not doing this they behaved the same.

This was in an area of code that needed revisiting as quite a while ago it became problematic with older code also messing with aspect ratio.  So I stopped digging as I'll rip it up and rewite it using current documentation.
