### ISSUE TITLE
Impossible to listen to GameObject.DESTROY event

### ISSUE THREAD

**Issue by vforsh** [photonstorm/phaser#5427]
## Version
3.50 latest from the repo

## Description
Listeners for "destroy" event are never called because in the destroy method the `this.removeAllListeners()` is called before `this.emit(Events.DESTROY, this)`

## Example Test Code
https://github.com/photonstorm/phaser/blob/master/src/gameobjects/GameObject.js#L690
https://github.com/photonstorm/phaser/blob/master/src/gameobjects/GameObject.js#L697

Instead of 
```
        this.removeAllListeners();

        if (this.postPipelines)
        {
            this.resetPostPipeline(true);
        }

        this.emit(Events.DESTROY, this);
```

Probably it should be this way
```
        this.emit(Events.DESTROY, this);
        this.removeAllListeners();

        if (this.postPipelines)
        {
            this.resetPostPipeline(true);
        }
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
