### ISSUE TITLE
[3.50-beta11] SpineObject is upside down when drawn to a RenderTexture

### ISSUE THREAD

**Issue by ccaleb** [photonstorm/phaser#5428]
## Version
* Phaser Version: v3.50.0-beta.11
* Operating system: MacOS Catalina Version 10.15.6

## Description

When drawing a Spine object to a RenderTexture, the Spine object's image appears upside down within the render texture. 

Here's a rough outline of the steps I'm carrying out:

1. Create a RenderTexture object and add it to the scene
2. Add a Spine object to the scene
3. The RenderTexture is positioned to the left of the screen, the Spine object is positioned to the right
4. A looping animation is playing on the Spine object
5. On each frame update, I'm drawing the Spine object into the RenderTexture

### Expected Behaviour

You should see the same Spine animation playing on the left and right hand side of the screen. On the left is the RenderTexture containing the current animation frame from the Spine object. On the right is the Spine object itself.

### Actual Behaviour

The RenderTexture on the left of the screen does show the Spine object, but it is shown upside down.

And here's an image showing the actual result:

<img width="799" alt="Screenshot 2020-12-03 at 15 19 42" src="https://user-images.githubusercontent.com/5279132/101049202-37e5f900-357b-11eb-8617-c12d11061a68.png">

## Example Test Code

A CodePen example can be found [here](https://codepen.io/ccaleb/pen/ZEpbyYY)

You can see the main parts of the code below.

```javascript
var rt;
var spineboy;
var spineboyOffsetX = 200;
var spineboyOffsetY = 280;
var renderTextureWidth = 400;
var renderTextureHeight = 300;
var fillBackgroundRed = true;

function create () {
  // Create a RenderTexture.
  rt = this.make.renderTexture({ x: 0, y: 0, width: renderTextureWidth, height: renderTextureHeight }, true);
  
  // Add a Spine object.
  var offsetX = 400;
  spineboy = this.add.spine(spineboyOffsetX + offsetX, spineboyOffsetY, 'boy', 'run', true);
  spineboy.scaleX = 0.4;
  spineboy.scaleY = 0.4;
}

function update () {
  // Draw the Spine object onto the RenderTexture.
  rt.clear();
  if (fillBackgroundRed) rt.fill(0xff0000, 1, 0, 0, renderTextureWidth, renderTextureHeight);
  rt.draw(spineboy, spineboyOffsetX, spineboyOffsetY);
}
```

## Additional Information

As a quick hack, I'm able to correct the issue by setting the render texture's `scaleY` property to `-1`. You can actually do this in the CodePen example above by setting the `correctVerticalMirrorIssue` variable to `true`.

Unfortunately if you are drawing other display objects into the same render texture then this solution won't work as other display object types are rendered the correct way up. In the example code,  you can see this in action by setting the `drawTexture` variable to `true`.

**Comment by PhaserEditor2D** [comment]
It also happens to me with BitmapText and Text objects.

![image](https://user-images.githubusercontent.com/12187299/101503713-63346380-3940-11eb-86b8-f807dd9879da.png)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

Note: Requires new build of plugin AND Phaser.
