### ISSUE TITLE
[3.50] Error - renderer.on is not a function (Canvas renderer)

### ISSUE THREAD

**Issue by vforsh** [photonstorm/phaser#5430]
## Version
3.50 latest from the repo

## Description
[CanvasRenderer ](https://github.com/photonstorm/phaser/blob/master/src/renderer/canvas/CanvasRenderer.js)doesn't extend EventEmitter while WebGLRenderer does hence it throws errors on lines
```
renderer.on(RenderEvents.RESIZE, this.onResize, this);
this.renderer.off(RenderEvents.RESIZE, this.onResize, this);
```

https://github.com/photonstorm/phaser/blob/master/src/gameobjects/rendertexture/RenderTexture.js#L291
https://github.com/photonstorm/phaser/blob/master/src/gameobjects/rendertexture/RenderTexture.js#L1459

**Comment by photonstorm** [comment]
This should be sorted now. I've made the Canvas Renderer emit all the same events as WebGL now, which fixes this and is just more useful.
