### ISSUE TITLE
[3.50-beta11] Initially invisible Spine object produces WebGL error when drawing to RenderTexture

### ISSUE THREAD

**Issue by ccaleb** [photonstorm/phaser#5431]
## Version
* Phaser Version: v3.50.0-beta.11
* Operating system: MacOS Catalina Version 10.15.6

## Description

When drawing a Spine object that is initially invisible to a RenderTexture, the object fails to render within the RenderTexture and a series of WebGL warnings appears in the browser's developer console.

Here's a rough outline of the steps I'm performing:

1. Create a RenderTexture object and add it to the scene
2. Add a Spine object to the scene
3. Initially set the Spine object's `visible` property to `false`
4. The RenderTexture is positioned to the left of the screen, the Spine object is positioned to the right
5. On each frame update, I'm drawing the Spine object into the RenderTexture

## Expected Behaviour

I'd expect the Spine object to be drawn to the RenderTexture and for there to be no WebGL warnings within the console window.

The RenderTexture (on the left of the screen) should show a depiction of the Spine object. The Spine object on the right of the screen however should be invisible because its `visible` property is initially set to `false`.

## Actual Behaviour

Both the RenderTexture (on the left of the screen) and the Spine object (right of the screen) are invisible. The following error is repeatedly written to the console window:

> WebGL: INVALID_OPERATION: bufferSubData: no buffer

## Example Test Code

A CodePen example can be found [here](https://codepen.io/ccaleb/pen/KKgVpjJ)

You can also see the bulk of the code below.

```javascript
var initialVisibility = false;

function create () {
  // Create a RenderTexture.
  rt = this.make.renderTexture({ x: 0, y: 0, width: renderTextureWidth, height: renderTextureHeight }, true);
  
  // Add a Spine object.
  var offsetX = 400;
  spineboy = this.add.spine(spineboyOffsetX + offsetX, spineboyOffsetY, 'boy', 'run', true);
  spineboy.scaleX = 0.4;
  spineboy.scaleY = 0.4;
  spineboy.visible = initialVisibility;
  
  // Allow user to toggle visibility by clicking mouse.
  this.input.on('pointerdown', function (pointer) {
    spineboy.visible = !spineboy.visible;
  });
}

function update () {
  // Draw the Spine object onto the RenderTexture.
  rt.clear();
  rt.draw(spineboy, spineboyOffsetX, spineboyOffsetY);
}
```

## Additional Information

The [CodePen example](https://codepen.io/ccaleb/pen/KKgVpjJ) I provided allows you to click anywhere on the screen to toggle the visibility of the Spine object. This, and the following steps below, should help highlight the issue:

1. When you run the example, the Spine object will have its `visibility` property set to `false`. The RenderTexture (on the left) will be blank and the Spine object (on the right) will be invisible. You will also see WebGL warnings in the console log.
2. Click on the screen to toggle the visibility of the Spine object. Its `visibility` property is now set to `true`. You will now see that the Spine object (on the right) is visible and also that the render texture (on the left) shows the same content as the Spine object.
3. Click once again on the screen. This will toggle the `visibility` property of the Spine object, this time setting it back to `false`. The Spine object (on the right) will become invisible, while the RenderTexture will remain visible and will continue to show the contents of the Spine object.

In steps 1 and 3 you'd expect the result to be the same, but step 1 seems broken with nothing appearing in the render texture and WebGL warnings appearing in the debug console.

Also, ignore the fact that the render texture's image is upside down. I've reported that as a separate bug: #5428

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
