### ISSUE TITLE
Docs: incorrect names (3.50.0-beta.12)

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5432]
## Version

* Phaser Version: 3.50.0-beta.12, e9d359c4d2b0ffc0422f8e6f9c8c22bea65a8bf3

## Description

These names are in the API docs but don't exist at runtime.

- Phaser.GameObjects.GetCalcMatrix
- Phaser.Geom.Mesh.GeneraterGridVerts
- Phaser.Renderer.Events
- Phaser.Renderer.WebGL.Pipelines.UtilityPipeline
- Phaser.Tilemaps.Orientation.FromOrientationString

**Comment by photonstorm** [comment]
Thanks, have fixed those, although `Phaser.Geom.Mesh.GenerateGridVerts` worked fine for me without any changes.

**Comment by samme** [comment]
I think it must be misspelled in the docs (GeneraterGridVerts).

**Comment by photonstorm** [comment]
It is!
