### ISSUE TITLE
[3.50-beta12] Tint Fill Not Working

### ISSUE THREAD

**Issue by kainage** [photonstorm/phaser#5433]
## Version

3.50-beta12

## Description

Tint fill is doing the same thing as a regular tint call.

## Example Test Code

Check out the labs example here http://labs.phaser.io/view.html?src=src\3.50\display\tint\tint%20fill%20effect.js

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
