### ISSUE TITLE
[3.50-beta12] Color value of point light is not consistent

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5435]
## Version

* Phaser Version: 3.50-beta12

* Operating system:

* Browser:

## Description

In [these 2 lines](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/pointlight/PointLight.js#L72-L74)
```javascript
var rgb = IntegerToRGB(color);
this.color = new RGB(rgb.r, rgb.g, rgb.b);
```

Method [`IntegerToRGB`](https://github.com/photonstorm/phaser/blob/e9d359c4d2b0ffc0422f8e6f9c8c22bea65a8bf3/src/display/color/IntegerToRGB.js#L19) return color in range 0-255. [Class RGB](https://github.com/photonstorm/phaser/blob/e9d359c4d2b0ffc0422f8e6f9c8c22bea65a8bf3/src/display/RGB.js#L24) needs color in range 0-1. They are not consistent.

Although the execution result is correct.

**Comment by photonstorm** [comment]
Swapped for the Color component. Makes more sense really.
