### ISSUE TITLE
[3.50-beta12] Camera Resets After Fade Out

### ISSUE THREAD

**Issue by kainage** [photonstorm/phaser#5438]
## Version

* Phaser Version: 3.50-beta12

## Description

Camera resets after fade out effect completes.

## Example Test Code

Run this labs example and see how the camera resets after the fade effect is complete:

http://labs.phaser.io/view.html?src=src\3.50\camera\fade.js&v=3.50.0-beta.12

Change it to another version and see how the fade effect stays after completion:

http://labs.phaser.io/view.html?src=src\3.50\camera\fade.js&v=3.24.1

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
