### ISSUE TITLE
Unlocking sound can fail if document body isn't loaded yet

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5439]
* Phaser Version: 3.24.1
* Operating system: MacOS
* Browser: Safari 14

## Description

Call `new Phaser.Game(…)` via script in document `<head>`. Click on game canvas. Web audio context is still suspended and sounds play silently.

## Example Test Code

<https://codepen.io/samme/project/editor/ArGPWY>

Click on the game canvas. Sound is still locked, context state is suspended, and `unlocked` doesn't appear in console.

## Additional Information

[WebAudioSoundManager.html#unlock](https://photonstorm.github.io/phaser3-docs/Phaser.Sound.WebAudioSoundManager.html#unlock) is called immediately during game instantiation and aborts if `document.body` is missing. I don't think it's ever called again, so its handlers are never added.

Maybe `unlock()` should be called again during game boot. Or only during game boot.

**Comment by samme** [comment]
I added code example.

**Comment by photonstorm** [comment]
I think unlocked only during boot makes more sense.

Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
