### ISSUE TITLE
Code in dragend is executed multiple times

### ISSUE THREAD

**Issue by Gadsss** [photonstorm/phaser#5442]
## Version

* Phaser Version:3.24.1

* Operating system:windows

* Browser:

## Description

Code in dragend is executed multiple times,this caused me to make redundant judgments to make the program run only once.

## Example Test Code

```
this.input.on('dragend', function(pointer, gameObject) {
			if (gameObject.alpha == 0.8) {
				gameObject.setDepth(0)
				gameObject.alpha = 1;
				// this.startX and this.startY are gameObject's start position
				gameObject.x = this.startX;
				gameObject.y = this.startY;
				// If I don't make that judgment,console.log(1) will be run
			} else if(gameObject.x != this.startX){
				console.log(1)
			}
			this.frame.x = -130;
			this.frame.y = 0;
		}, this);
```

## Additional Information

I don't know if there are more application scenarios when executing multiple times. If so, please forgive me

**Comment by FloodGames** [comment]
Interesting... I use dragend quite a lot, and don't have this. 

Trying to remember if I had this issue in the past...

**Comment by Gadsss** [comment]
This is true for a single GameObject, but I don't know how to use this method in a group. I checked the API and found that the group can't set interactive. Do I want to add methods to each sub object when generating?


In addition, I wonder if I can add sub objects to the specified location of the group.


thank you

**Comment by photonstorm** [comment]
Groups cannot be made interactive, so yes, do it for every child of the Group and handle the drag end event for each one of them. You can use a single handler for this, or a unique handler per Game Object, it's up to you. But I would absolutely expect this event to fire multiple times if dragging multiple Game Objects.

If you only want 1 Game Object to fire this event once, ever, use the `once` event instead. So `this.input.once('dragend')`.

The code doesn't demonstrate an API issue, so it may be better to take this to the forum or Discord, please.
