### ISSUE TITLE
[3.50] Feature suggestions about new Mesh game object

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5444]
1. Would you like to add an example about orthographic projection Mesh game object?
    ```javascript
    mesh.hideCCW = false;
    mesh.setOrtho();
    ```
    seems not enough. The image size is not correct.

2. Would you like to add some new methods of [Face](https://github.com/photonstorm/phaser/blob/master/src/geom/mesh/Face.js)? To 
    - Rotate(rotateZ) vertices of this face
    - Move vertices of this face. ([Face.translate](https://github.com/photonstorm/phaser/blob/master/src/geom/mesh/Face.js#L421) dose not apply changing to vertex.vx, vertex.vy, therefore the render result dose not change)

**Comment by photonstorm** [comment]
It's important to give the correct aspect ratio for the orthographic projection. So for a 800 x 600 renderer, you'd do `setOrth(800 / 600, 1)`. I've now made this the default actually.

There is the `RotateFace` function already, but it doesn't offer z rotation.

Translating a Face will work, but you have to get the Mesh to update all of its cached values to see the changes. You can use this property for it:

```js
        /**
         * By default, the Mesh will check to see if its model or view transform has
         * changed each frame and only recalculate the vertex positions if they have.
         *
         * This avoids lots of additional math in the `preUpdate` step when not required.
         *
         * However, if you are performing per-Face or per-Vertex manipulation on this Mesh,
         * such as tweening a Face, or moving it without moving the rest of the Mesh,
         * then you may need to disable the dirty cache in order for the Mesh to re-render
         * correctly. You can toggle this property to do that. Please note that leaving
         * this set to `true` will cause the Mesh to recalculate the position of every single
         * vertex in it, every single frame. So only really do this if you know you
         * need it.
         *
         * @name Phaser.GameObjects.Mesh#ignoreDirtyCache
         * @type {boolean}
         * @since 3.50.0
         */
        this.ignoreDirtyCache = false;
```

Then you could call `Mesh.preUpdate()` directly and turn the property false again.

**Comment by rexrainbow** [comment]
I totally miss that `RotateFace` method. Thank you!
