### ISSUE TITLE
RenderTexture snapshot generates an inverted image

### ISSUE THREAD

**Issue by PhaserEditor2D** [photonstorm/phaser#5445]
## Version

* Phaser Version: v3.50.0-beta.13

* Operating system: Linux

* Browser: Firefox, Google Chrome

## Description

The snapshot method of the RenderTexture is generating a vertically inverted image.

## Example Test Code

https://codepen.io/phasereditor2d/pen/PoGbdpE

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by PhaserEditor2D** [comment]
Thanks! Its working now!
