### ISSUE TITLE
BitmapText drop shadow color not working

### ISSUE THREAD

**Issue by PhaserEditor2D** [photonstorm/phaser#5446]
## Version

* Phaser Version: v3.50.0-beta.12

* Operating system: Linux

* Browser: Firefox

## Description

The new BitmapText.dropShadowColor property is not working. The shadow is always black.

## Example Test Code

https://codepen.io/phasereditor2d/pen/qBaqLPN

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by PhaserEditor2D** [comment]
Thanks! Its working now!
