### ISSUE TITLE
 Cannot use renderTexture.snapshot in canvas rendering mode

### ISSUE THREAD

**Issue by akeboshi1** [photonstorm/phaser#5448]
## Version

* Phaser Version:v3.50.0-beta.13

* Operating system:Linux

* Browser:chrome

## Description

Cannot use renderTexture.snapshot in canvas rendering mode,
The canvas inside canvasrender is undefined

## Example Test Code
https://codepen.io/akeboshi1/pen/eYdvgry

## Additional Information
![image](https://user-images.githubusercontent.com/18412751/102167105-ad7d8d80-3ec8-11eb-813c-e45dde39ca3d.png)

**Comment by akeboshi1** [comment]
My current alternative is to create canvastexture.drawframe to merge dynamic atlas。
const canvas = this.scene.textures.createCanvas("key", width, height);
            for (let i: number = 0, len = frames.length; i < len; i++) {
                const name = frames[i];
                const key = name.split("/")[1].split("_");
                const slotKey = key[4] ? key[0] + "_" + key[1] + "_" + key[3] + "_" + key[4] : key[0] + "_" + key[1] + "_" + key[3];
                const dat = dragonBonesTexture.get(name);
                const loadArr = this.mLoadMap.get(slotKey);
                if (!loadArr) {
                    for (const obj of this.replaceArr) {
                        const skin = this.formattingSkin(obj.skin);
                        const tmpKey = obj.part.replace("#", skin.sn.toString()).replace("$", obj.dir.toString()) + skin.version;
                        const partName: string = ResUtils.getPartName(tmpKey);
                        const frameName: string = "test resources/" + tmpKey;
                        const part: string = obj.slot.replace("$", obj.dir.toString());
                        if (part === slotKey) {
                            const texture = this.scene.textures.get(partName);
                            if (dragonBonesTexture.frames[frameName]) {
                                canvas.drawFrame(this.mDragonbonesName, name, dat.cutX, dat.cutY);
                                break;
                            } else {
                                canvas.drawFrame(partName, texture.firstFrame, dat.cutX, dat.cutY);
                                break;
                            }
                        }
                    }
                    // this.mDragonBonesTexture.drawFrame(this.mDragonbonesName, name, dat.cutX, dat.cutY);
                } else {
                    const drawTextureKey = loadArr[1] + "_png";
                    const drawTexture = this.scene.game.textures.get(drawTextureKey);
                    canvas.drawFrame(drawTextureKey, drawTexture.firstFrame, dat.cutX, dat.cutY);
                }
            }
            const url = canvas.canvas.toDataURL("image/png", 1);
            this.scene.textures.addBase64(this.renderTextureKey, url);
            canvas.destroy();

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
