### ISSUE TITLE
[3.50.0] Graphical error suspected cause: Phaser Containers with Spine Objects

### ISSUE THREAD

**Issue by FloodGames** [photonstorm/phaser#5449]
* Phaser Version: 3.50.0

## Description
During the beta, certain Phaser Containers often got temporary graphical glitches (like the spine 'spritesheet' showing on the phaser container). With the current release, instead of the spritesheet bug they are now blue rectangles (easy to spot 😄 )! Note that in the following images, the 'pure' spineObjects are still working without issues.

**How it should be:**
![image](https://user-images.githubusercontent.com/60991890/102384769-5d3c2380-3fcd-11eb-8b23-fe2a1386c16e.png)

**How it shows sometimes:**
![image](https://user-images.githubusercontent.com/60991890/102384630-3da4fb00-3fcd-11eb-95fe-b843eeac77cd.png)

I also get this error, ater trying to leave the scene, it seems after the render issue - it might be related!
![image](https://user-images.githubusercontent.com/60991890/102383759-316c6e00-3fcc-11eb-8681-a1e40630b10c.png)

![image](https://user-images.githubusercontent.com/60991890/102388783-8317f700-3fd2-11eb-8a23-aca6ec44ac33.png)
(during beta it showed the spine 'spritesheet' on the object)

Apologies for not posting a code sample! Will try to create if there is no followup!

**Comment by TinyDobbins** [comment]
same issu, in 3.52.0 too, vote up for fixing this issue! :)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
