### ISSUE TITLE
Particles displayed at wrong position when following a sprite with Canvas renderer

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5457]
## Version

3.50.0

## Description

Create a game using CANVAS renderer. Create an emitter following a sprite and start. Particles are displayed at the wrong position.

## Example Test Code

https://codepen.io/samme/pen/oNzwpMr

Green flares (following the logo) appear in the wrong place. Particle `x` and `y` are correct though.

Blue flares (not following but using emitter's position) appear in the right place.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/bug-when-using-particle-emitter-startfollow-on-canvas-phaser-3-52-0/8922/3

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
