### ISSUE TITLE
GamePad definitions are browser specific

### ISSUE THREAD

**Issue by Ithamar** [photonstorm/phaser#5461]
## Version

* Phaser Version:

3.50.0

* Operating system:

Windows 10

* Browser:

Firefox, Edge (as examples)

## Description

The GamePad button/axis assignments are actually browser specific, so one generic definition per gamepad will not work properly cross-browser. I've included screenshots below of gamepad-tester.com on both Firefox and Edge browsers, on the same machine, using the same controller, and they show a different number of axis, and the assignment is different.

Unless we're going to keep different mappings per browser, the mappings are essentially unusable. I'm willing to start a PR for that, if there's agreement on that's the way to go.

## Example Test Code

Can be simply tested with https://gamepad-tester.com to show differences.

### Firefox:

Below are the screenshots of the PS3 controller using Firefox and Edge.

![gamepad-tester com-ps3-firefox](https://user-images.githubusercontent.com/541493/102718402-355c0100-42e8-11eb-8efd-d298e46c1c87.png)

### Edge:

![gmaepad-tester com-ps3-edge](https://user-images.githubusercontent.com/541493/102718403-35f49780-42e8-11eb-93dd-d114e4dd6f26.png)

**Comment by gammafp** [comment]
Hello.
The axis work fine for me with xbox one controller and Nintendo Switch Pro, maybe is a error from Playstation 3 controller.

Nintendo Switch:
![controller_edge](https://user-images.githubusercontent.com/9221946/102764598-b1ebef80-437b-11eb-8730-d34102d61c10.PNG)

Xbox One: 
![xbox_controller](https://user-images.githubusercontent.com/9221946/102764632-bca68480-437b-11eb-88cd-890abcd1667c.PNG)

**Comment by jbpuryear** [comment]
Just took a look over at [Bugzilla](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=gamepad) and it seems there are quite a few open bugs related to controller mappings. I'm gonna go ahead and guess that most browser are still working on their gamepad mappings. Implementing a database of device/browser mappings is a huge, maybe even endless task that the browser developers are already working on. I think it's probably best just to wait until the browsers fix this themselves. In the meantime, you can always check to see if a browser has a mapping for a gamepad by checking that the [mapping](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/mapping) property of the gamepad is 'standard', i.e. `Phaser.Input.Gamepad.pad.mapping === 'standard'`.

**Comment by Ithamar** [comment]
Looking at the "age" of the GamePad API, my hopes for "browsers fixing themselves" isn't very high, but lets wait and see what happens....
