### ISSUE TITLE
Bitmaptext display capped on Canvas

### ISSUE THREAD

**Issue by monteiz** [photonstorm/phaser#5462]
## Version

* Phaser Version: 3.50.0

* Operating system: MacOS

* Browser:

## Description

With version 3.50.0, Bitmaptext objects are displayed cropped, like only a small portion of every letter. This happens only with canvas. Using WEBGL, the same code/asset works as expected.

**Comment by vforsh** [comment]
You need to provide an example. I use bitmap texts extensively in [my game](https://html5.gamedistribution.com/f4dea23f49ab4020999121e700bb6ab4/?forceCanvas=1) and they look fine.

**Comment by monteiz** [comment]
@vforsh You're right, all of the Phaser 3 examples also works. It must be a matter of assets. I am trying to prepare an example, but since the issue appears to be asset specific, I cannot find a quick way to share my own .png and .fnt file in the sandbox.

These are the two files: https://ufile.io/f/48e4c

I use the old Shoebox to create my bitmapfonts, which worked well until version `3.24.x`. With version 3.50.0, they appear wrongly cropped.

What do you use to create your bitmapfonts?

**Comment by vforsh** [comment]
@monteiz I always use Littera too. Such a shame that it is a Flash-based tool and it will fade away soon.

**Comment by monteiz** [comment]
@vforsh I agree with you, Littera is great, but a bit limited. With Shoebox you can use Photoshop or Illustrator to make really amazing bitmapfonts, but for some reason Phaser 3.50.0 does not like it anymore. I hope someone can fix that.

Littera in Flash, and Shoebox in Adobe Air. We will say bye to them soon I guess, and that's a shame.

I have just seen your game, it looks awesome! Congratulations, it is beautiful.

**Comment by SBCGames** [comment]
@vforsh @monteiz Another Littera user here. On Adobe site, you can download Flash projector (https://www.adobe.com/support/flashplayer/debug_downloads.html). It is standalone app on PC that can open .swf files. Then download web page with Littera with browser and keep .swf file. Finally, open .swf with projector...

**Comment by monteiz** [comment]
Thank you @SBCGames, that's a good tip.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
