### ISSUE TITLE
there is no texture bound to the unit 1

### ISSUE THREAD

**Issue by ffx0s** [photonstorm/phaser#5464]
## Version

* Phaser Version: 3.50.0

* Operating system: Mac Pro

* Browser: 5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

## Description

Add tileSprite in the create function: ```this.add.tileSprite(0, 0, 200, 500,'ball1')```, and then call ```this.scene.restart()```, I received many of the same errors.

![Xnip2020-12-23_14-04-27](https://user-images.githubusercontent.com/13212645/102965599-1e582180-4529-11eb-9f93-3144a5e9a8ae.jpg)

## Example Test Code
```
create: function ()
    {
        this.add.tileSprite(0, 0, 200, 500, 'ball1')
        this.matter.world.setBounds(0, 0, 800, 600, 32, true, true, false, true);

        for (var i = 0; i < 64; i++)
        {
            var ball = this.matter.add.image(Phaser.Math.Between(100, 700), Phaser.Math.Between(-600, 0), 'ball1');
            ball.setCircle();
            ball.setFriction(0.005);
            ball.setBounce(1);
        }

        this.input.once('pointerdown', function (event) {

            this.scene.restart();

        }, this);
    }
```

**Comment by venarius** [comment]
I am having the same problem. Weirdly it is not happening on latest chrome desktop browser but instead on my latest android chrome browser.

So for me it only happens on mobile browsers but not on desktop.

**Comment by samme** [comment]
Test: <https://codepen.io/samme/pen/zYKPGbe>

I don't see an error in my Safari.

**Comment by venarius** [comment]
Cannot say about safari but still happens on latest chrome android browser.

![Capture](https://user-images.githubusercontent.com/13546486/103103461-7a05d600-4621-11eb-8897-0af1d3f91533.PNG)

**Comment by mark-rushakoff** [comment]
I'm not sure if this is an identical issue, but on latest Chrome, with Phaser 3.50.1, I get errors like `[.WebGL-0x7fdee9d4e600]RENDER WARNING: there is no texture bound to the unit 9` when I have code like:

```javascript
const text = scene.add.text(0, 0, "hello")
// ...
text.destroy()
```

I can suppress the warning by setting the text object's texture to the WebGL blank texture before destroying the text object, e.g.

```javascript
const text = scene.add.text(0, 0, "hello")
// ...
text.texture = scene.renderer.blankTexture // Should be wrapped in conditional when rendering direct to canvas?
text.destroy()
```

**Comment by actionmoon** [comment]
Phaser Version: 3.50.0
Operating system: Mac Pro
Browser: Chrome Version 87.0.4280.88 (Official Build) (x86_64)

I am having the same problem ; but it only appear in my project；it will not encounter when use 
 in https://labs.phaser.io/edit.html

`var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('bunny', 'https://tosv.boe.byted.org/obj/interactive-fiction/internal/resources/bb41734ad51891e27572053cabf2f35c');
}

function create ()
{
    var bunny = this.add.sprite(48, 102, 'bunny');
    bunny.setOrigin(0, 0);
    bunny.setDisplaySize(72, 72);
    // bunny.alpha = 0.5;
}
`
![bugfix](https://user-images.githubusercontent.com/6701451/103340279-9fca2980-4abe-11eb-91a6-2c1f6f244d56.png)

**Comment by actionmoon** [comment]
I encountered this problem using this code
```
class PreloadScene extends Phaser.Scene {
    constructor() {
        super({ key: 'PreloadScene' });
    }
    preload() {
        this.load.image('bunny', 'https://tosv.boe.byted.org/obj/interactive-fiction/internal/resources/bb41734ad51891e27572053cabf2f35c');
    }
    create() {
        console.log('PreloadScene')
        this.scene.start('GameMenuScene');
    }
}

class GameMenuScene extends Phaser.Scene {
    constructor() {
        super({ key: 'GameMenuScene' });
    }
    create() {
        console.log('GameMenuScene')
        var bunny = this.add.sprite(48, 102, 'bunny');
        bunny.setOrigin(0, 0);
        bunny.setDisplaySize(72, 72);
        // bunny.alpha = 0.5;
        bunny.setInteractive().on('pointerdown', () => {
            this.scene.start('GameScene');
        }, this);

        this.add.text(200, 100, 'Case shrugged.\nThe girl to his right giggled and nudged him.', { color: '#00ff00', align: 'left' });
    
        // var text = scene.add.text(0, 0, "hello, world!", element.text.style);
        // text.setOrigin(0.5, 0.5);
        // text.setPosition(0, 0);
        // text.setInteractive().on('pointerdown', () => {}, this);
    }
}

class GameScene extends Phaser.Scene {
    constructor() {
        super({ key: 'GameScene' });
    }
    create() {
        console.log('GameScene')
        var bunny = this.add.sprite(48, 102, 'bunny');
        bunny.setOrigin(0, 0);
        bunny.setDisplaySize(72, 72);
        // bunny.alpha = 0.5;
    }
}

var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: [PreloadScene, GameMenuScene, GameScene]
};
var game = new Phaser.Game(config);
```

**Comment by actionmoon** [comment]
If you comment the code, it works well。

// this.add.text(200, 100, 'Case shrugged.\nThe girl to his right giggled and nudged him.', { color: '#00ff00', align: 'left' });

```
class PreloadScene extends Phaser.Scene {
    constructor() {
        super({ key: 'PreloadScene' });
    }
    preload() {
        this.load.image('bunny', 'assets/sprites/bunny.png');
    }
    create() {
        console.log('PreloadScene')
        this.scene.start('GameMenuScene');
    }
}

class GameMenuScene extends Phaser.Scene {
    constructor() {
        super({ key: 'GameMenuScene' });
    }
    create() {
        console.log('GameMenuScene')
        var bunny = this.add.sprite(48, 102, 'bunny');
        bunny.setOrigin(0, 0);
        bunny.setDisplaySize(72, 72);
        // bunny.alpha = 0.5;
        bunny.setInteractive().on('pointerdown', () => {
            this.scene.start('GameScene');
        }, this);

        // this.add.text(200, 100, 'Case shrugged.\nThe girl to his right giggled and nudged him.', { color: '#00ff00', align: 'left' });
    }
}

class GameScene extends Phaser.Scene {
    constructor() {
        super({ key: 'GameScene' });
    }
    create() {
        console.log('GameScene')
        var bunny = this.add.sprite(48, 102, 'bunny');
        bunny.setOrigin(0, 0);
        bunny.setDisplaySize(72, 72);
        // bunny.alpha = 0.5;
    }
}

var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: [PreloadScene, GameMenuScene, GameScene]
};
var game = new Phaser.Game(config);
```

**Comment by smshuja** [comment]
Facing the same issue.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by actionmoon** [comment]
@photonstorm I encountered a new problem when updating to 3.51.0。

![Uploading Phaser3.png…]()

```
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        create: create,
    }
};

var game = new Phaser.Game(config);

function create() 
{
    //  Default text with no style settings
    var text = this.add.text(100, 100, 'Phaser');

    text.setInteractive().on('pointerdown', () => {
        console.log('hello world');
    });
}

```
