### ISSUE TITLE
How to render the video played by the video tag to the phaser canvas

### ISSUE THREAD

**Issue by JingFanWang** [photonstorm/phaser#5465]
We want to render the video played by the video tag to phaser's canvas. How do I render it?

**Comment by rexrainbow** [comment]
Phaser3 has built-in video game object, see this [official example](https://labs.phaser.io/view.html?src=src\game%20objects\video\play%20video.js)

**Comment by samme** [comment]
https://phaser.io/examples/v3/category/game-objects/video

Please use [the Discord channel or the forum](http://phaser.io/community) for support.

**Comment by JingFanWang** [comment]
> https://phaser.io/examples/v3/category/game-objects/video
> 
> Please use [the Discord channel or the forum](http://phaser.io/community) for support.

What I mean is how to render the video played by the video to the canvas frame by frame. I have not found the API in Phaser3 for the time being.

**Comment by rexrainbow** [comment]
```javascript
video.saveSnapshotTexture(textureKey);
video.snapshot()
```

See this [demo](https://codepen.io/rexrainbow/pen/qBaPgYz)
- Click to take a snapshot
