### ISSUE TITLE
Layer DESTROY event doesn't fire

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5466]
## Version

3.50.0

## Description

Create a Layer game object. Add a listener to its DESTROY event. Destroy the layer. Listener is not called.

## Example Test Code

https://codepen.io/samme/pen/vYXezqw

Nothing is logged to console.

## Additional Information

In Layer#destroy listeners are removed too early.

## Addendum

Docs should clarify that destroying a layer does not destroy its children.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

Also now destroys all children.
