### ISSUE TITLE
Setting originX / originY should call updateDisplayOrigin

### ISSUE THREAD

**Issue by MattG-Seattle** [photonstorm/phaser#5469]
## Version

* Phaser Version: 3.23

* Operating system: Windows 10

* Browser:

## Description

The documentation and source code imply that the originX and originY properties on some GameObjects (such as Sprite) are public. However, setting either one of these doesn't update displayOriginX / displayOriginY, whereas calling setOrigin does. Maybe I'm misunderstanding something?

## Example Test Code

mySprite.originX = 0;  // sprite doesn't display in the correct position as its displayOriginX isn't updated

**Comment by halilcakar** [comment]
well if you want to update originX by yourself, you also need to call `updateDisplayOrigin` function on the GameObject.

If you check [Origin.js](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/components/Origin.js#L121) you will see after updating public properties `setOrigin` function return's a call `this.updateDisplayOrigin()` on the [line 129](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/components/Origin.js#L129).

**Comment by MattG-Seattle** [comment]
I guess my expectation was that setting one of the properties directly (via originX / originY) should behave the same as calling the ‘setter’ method (setOrigin).

Thanks

-- Matt
