### ISSUE TITLE
DOMElement configure pointerEvents independently of transformOnly

### ISSUE THREAD

**Issue by hayatae** [photonstorm/phaser#5470]
Currently, the pointerEvents style property of DOMElements is set on render to be `auto` if the element is not in `transformOnly` mode. This creates a bit of an issue if you'd like to have all the other advantages of having phaser track opactiy, display, zIndex, and blendMode, but do not want the mouse pointer to be intercepted by the element. It is not clear to me why pointerEvents are tied into these display properties.

https://github.com/photonstorm/phaser/blob/416ae58da3e010f051fb03db58389a001536cfbc/src/gameobjects/domelement/DOMElementCSSRenderer.js#L106

It seems like an easy fix would be to expose a separate `pointerEvents` property which could be set to any valid css option for `pointer-events`. This property could be defaulted based on the `trasnformOnly` property to maintain backwards compatibility. This would allow a developer to override the `pointer-events` to anything they need it to be.

I'd be comfortable implementing this feature and creating a PR for it if this sounds like a good approach.

**Comment by endel** [comment]
Hey,  I'm also in the need of this 🙋

I'm wondering if `style.pointerEvents` really needs to be set at all? Maybe the end-user should be responsible for setting this CSS property, like this:

```typescript
scene.add.dom(x, y, "div", `
  color: #000;
  pointer-events: none;
`, "hello world");
```

It seems the `pointer-events` is being overwritten in the current implementation, right?

**Comment by endel** [comment]
The [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) mentions that `auto` is the default value. So I believe it's safe to remove it. 

> `auto`: The element behaves as it would if the pointer-events property were not specified. 

Made a PR for this here 😅  https://github.com/photonstorm/phaser/issues/5470

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
This change has sadly broken so many things it's time to revert it all back to how it was previously.

**Comment by hayatae** [comment]
> This change has sadly broken so many things it's time to revert it all back to how it was previously.

I was afraid of that happening. Can we fix this by simply adding a new separate property (as suggested in the initial post) to allow overriding the default behavior in Phaser? That would allow for overriding this property if desired while not affecting any existing code.

**Comment by photonstorm** [comment]
I could, but the problem is that if you change it to anything else, you'll break Phaser-related input at the same time (see all of the various issues that have arisen from this change to get an idea of what it breaks!).

**Comment by photonstorm** [comment]
Ok, I have reverted both the PRs that caused all the issues. I have also exposed a couple of new properties you can use to set the `pointerEvents` attribute yourself, but as the docs for it says: if you change it without appreciating what you've changed, you'll break Phaser input at the same time.

**Comment by hayatae** [comment]
> Ok, I have reverted both the PRs that caused all the issues. I have also exposed a couple of new properties you can use to set the `pointerEvents` attribute yourself, but as the docs for it says: if you change it without appreciating what you've changed, you'll break Phaser input at the same time.

I finally tried upgrading from 3.52 to 3.53.1 and 3.54.0 and immediately ran into all the various DOM problems that cropped up because of this change. Had to revert back to 3.52.0 for now. Didn't realize how many things that single line affected outside of the CSS that was being applied to user-added dom elements.

Sorry for all the trouble this ended up causing! Does the new update/fix for it allow for setting pointer-events on a per-element basis? Ultimately I just wanted to be able to turn pointer events on/off for specific elements that were being added to the DOM portion of my scene rather than all of them whole-sale.

**Comment by photonstorm** [comment]
Yes, you can now set `pointerEvents` directly on a DOM Element, so you can control it on a per-element basis as well as globally in the game config, which is what you originally suggested but was sadly never provided in the PR.

**Comment by endel** [comment]
I'm sorry to have caused noise & trouble, thanks for your hard work as always @photonstorm.

**Comment by photonstorm** [comment]
No worries. I should have tested the PR, but it just looked so innocent and harmless. Who knew! :)
