### ISSUE TITLE
Keyboard key event filtered out incorrectly as a duplicate

### ISSUE THREAD

**Issue by cjw6k** [photonstorm/phaser#5471]
## Version

* Phaser Version: 3.50.1

* Operating system: Windows

* Browser: Firefox 84

## Description

With any keyboard input, sometimes the keyup event doesn't take effect, because it is filtered out by the keyboard plugin. This happens when a keydown and keyup event for the same key have the same timestamp. Probably related to repeating keydowns lining up with a keyup.

## Example Test Code

The make your first Phaser 3 game tutorial at https://www.phaser.io/tutorials/making-your-first-phaser-3-game/part7 exhibits the problem.

## Additional Information

The keyboard plugin checks for duplicate key events by checking key code and timestamp, but it doesn't check the type. It should check the type.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/making-your-first-phaser-3-game-problem/8401/6

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
