### ISSUE TITLE
Cannot read property 'copyFrom' of undefined

### ISSUE THREAD

**Issue by izure1** [photonstorm/phaser#5474]
## Version

* Phaser Version: 3.50.1

* Operating system: Windows10

* Browser:

## Description

Hello. First of all, I apologize for my poor English.

I'm currently working on a Phaser3 plug-in library, and an error occurs when I use setPipeline('Light2D').

Below is part of the code of the plug-in I'm making.

## Example Test Code

```
// Scene plugin
private setActive(...targets: Phaser.GameObjects.GameObject[]): void {
        for (const target of targets) {
            if ( !('setPipeline' in target) ) {
                continue
            }
            target.setPipeline('Light2D')
        }
}

private onCreated(): void {
        this.setActive(...this.scene.children.list)

        this.scene.lights.enable()
        this.scene.lights.setAmbientColor(0x000000)
}

boot(): void {
        this.scene.events.on(Phaser.Scenes.Events.CREATE, this.onCreated.bind(this))
}
```

And bugs happen like this.

```
/**
 * Renders this Game Object with the WebGL Renderer to the given Camera.
 * The object will not render if any of its renderFlags are set or it is being actively filtered out by the Camera.
 * This method should not be called directly. It is a utility function of the Render module.
 *
 * @method Phaser.GameObjects.Polygon#renderWebGL
 * @since 3.13.0
 * @private
 *
 * @param {Phaser.Renderer.WebGL.WebGLRenderer} renderer - A reference to the current active WebGL renderer.
 * @param {Phaser.GameObjects.Polygon} src - The Game Object being rendered in this call.
 * @param {Phaser.Cameras.Scene2D.Camera} camera - The Camera that is rendering the Game Object.
 * @param {Phaser.GameObjects.Components.TransformMatrix} parentMatrix - This transform matrix is defined if the game object is nested
 */
var PolygonWebGLRenderer = function (renderer, src, camera, parentMatrix)
{
    var pipeline = renderer.pipelines.set(src.pipeline);

    var result = GetCalcMatrix(src, camera, parentMatrix);

    var calcMatrix = pipeline.calcMatrix.copyFrom(result.calc); // <----- Bugs occur here.

    var dx = src._displayOriginX;
    var dy = src._displayOriginY;
```

I always have fun coding with the phaser3 library. Thank you.

**Comment by izure1** [comment]
I've found more information.
The graphical pipeline instance has its own `calcMatrix` information https://github.com/photonstorm/phaser/blob/60cc53f972887f714e8edc70b032badd4a914504/src/renderer/webgl/pipelines/GraphicsPipeline.js#L78
but it does not appear that any other pipeline that inherits the multi-pipeline is specified.

**Comment by photonstorm** [comment]
The Graphics Game Object (including all Shapes) are not supported by the Light2D pipeline, which is why this doesn't work. The Light Pipeline docs state that it's for texture based Game Objects (such as Sprites, Rope, TileSprite, etc)

**Comment by izure1** [comment]
Oh dear, I was a fool. I just found it. The error has been resolved. Thank you.
