### ISSUE TITLE
When using the light2d pipeline, setDepth breaks the texture.

### ISSUE THREAD

**Issue by izure1** [photonstorm/phaser#5476]
## Version

* Phaser Version: 3.50.1

* Operating system: Windows10

* Browser:

## Description

Hello. I apologize for not being familiar with English.
If you can't understand my explanation, please leave a question. I'll answer it again.

When using lights, objects that do not use the `setPipeline('Light2D')` method may break the texture when using `setDepth` together.

Unfortunately, I don't know the WebGL in detail, so I'm not sure it's a bug.
So, I wrote a simple sample code for this.

https://jsfiddle.net/9fmr4wk7/1/

Try moving the texture using the keyboard cursor.
If the depth is greater than the object specified as `setPipeline('Light2D')` then you will see the texture break.
But with `setPipeline('SinglePipeline')`, this didn't happen. I think this only happens to game objects that have Multi_PIPELINE.

## Example Test Code

https://jsfiddle.net/9fmr4wk7/1/

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
