### ISSUE TITLE
Framebuffer status: Incomplete Attachment when changing display style

### ISSUE THREAD

**Issue by venarius** [photonstorm/phaser#5478]
## Version

* Phaser Version: 3.50.1

* Operating system: Windows

* Browser:

## Description

Since Version 3.50.0-beta.11 phaser will crash with the error message `Framebuffer status: Incomplete Attachment` when you toggle the display style of its parent element from block to hidden.

In my project I sometimes want to hide my phaser instance. I do that by changing the `display` css property of the parent element of my phaser instance. This worked great until Version 3.50.0-beta.11 when it suddenly started to produce "Framebuffer status: Incomplete Attachment" errors every time I did that and thus resulting in my webgl context getting killed.

## Example Test Code

https://codesandbox.io/s/phaser-3500-incomplete-attachment-9fg99

You can test it out by changing the phaser version from 3.50.1 to e.g. 3.50.0-beta.10 and use the button to toggle the visibility.

**Comment by OORaiser** [comment]
I found that this bug would arise when resizing with width or height as 0.

Now I am scrolling back to version 3.24.1 which would not arise this error.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by micsun-al** [comment]
Phaser 3.55.2
I just saw this error message on a Samsung Galaxy Tab S7 running android 10.0, Chrome 96.0.4664.45 (using lambadatest.com).

The same app did not reproduce the error with the following configurations:
Windows 10, Chrome 97.0.4692.71
iPhone 7, iOS/Safari 14.8.1
Google Pixel 3 XL, Chrome 97.0.4692.87

...going to investigate what's causing it (I do hide the canvas until Phaser completes loading, maybe that's what's causing it?).

**Comment by micsun-al** [comment]
Figured out what might have been causing the issue...
Inside of my `GameConfig`'s `scale` (`ScaleConfig`) width was too big (`3000`) and I guess maybe the device's max size is `2048` and it blew up...I'm just guessing... >_<
