### ISSUE TITLE
How to preload Scene resources such as pictures/audio/video

### ISSUE THREAD

**Issue by JingFanWang** [photonstorm/phaser#5479]
Question: If I have three Scenes, SceneA, SceneB, SceneC, what should I do if I need to pre-load all the resources of SceneA and SceneB?

**Comment by halilcakar** [comment]
Hi @JingFanWang, 

You can check here: https://phaser.io/news/2018/05/phaser-3-preloader-tutorial

Basicly load everything at first scene or make a seperated scene to preload and show like the example.

**Comment by JingFanWang** [comment]
> 
I saw the example you just provided, but I don’t want to add all the resources in the first shot. Your reply "make a seperated scene to preload" seems to be a good way. Can you give an example?

**Comment by JingFanWang** [comment]
> Hi @JingFanWang,
> 
> You can check here: https://phaser.io/news/2018/05/phaser-3-preloader-tutorial
> 
> Basicly load everything at first scene or make a seperated scene to preload and show like the example.

I saw the example you just provided, but I don’t want to add all the resources in the first shot. Your reply "make a seperated scene to preload" seems to be a good way. Can you give an example?
