### ISSUE TITLE
Adding game object to layer ignores any depth settings for input

### ISSUE THREAD

**Issue by pr4xx** [photonstorm/phaser#5483]
## Version

* Phaser Version: 3.50.1

* Operating system: macOS

* Browser: Firefox

## Description

I have two sprites with `setInteractive`. I give them a specific `depth` for the correct draw order because they overlap.
Without a layer, everything works as expected.
But as soon as I add the sprites to a layer (one layer for all sprites), the depth will be ignored for any `input` related stuff.
Check out the codepen below.

## Example Test Code

[https://codepen.io/pr4xx/pen/dypmWZm](https://codepen.io/pr4xx/pen/dypmWZm)

There are two sprites. The first one is below the second one. But when I click the second one, the first sprite catches the input event. But ONLY when using the layer.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
