### ISSUE TITLE
[Docs] Wrong description for generateFrameNumbers (?)

### ISSUE THREAD

**Issue by kaktus42** [photonstorm/phaser#5484]
## Version
* Phaser Version: v3.50.1 (WebGL | Web Audio)  https://phaser.io
* Operating system: -
* Browser: -

## Description
In the docs for `generateFrameNumbers` it says:
```
 * If you have a sprite sheet loaded called `explosion` and it contains 12 frames, then you can call this method using:
 * `this.anims.generateFrameNumbers('explosion', { start: 0, end: 12 })
 
 * The `end` value tells it to stop after 12 frames. To create an animation using this method, you can do:
```

I guess it should be something like:

> and it contains **13** frames
> [...]
> tells it to stop after **the 12th frame**.

_This doc can be found in multiple parts of the code._

## Example Test Code

```
this.anims.create({
            key: 'left',
            frames: this.anims.generateFrameNumbers('player', { start: 51, end: 54 }),
            frameRate: 10,
            repeat: -1,
        });
```
Creates an animation with 4 frames:

![image](https://user-images.githubusercontent.com/1608815/103480366-3d31a000-4dd4-11eb-85d3-792bcdae2975.png)

**Comment by adarrshpaul** [comment]
Yes, agreed, on this. This particular example in **docs is wrong.**
Here, is the link in Phaser doc's which mentions this example  : 
- [https://photonstorm.github.io/phaser3-docs/Phaser.Animations.AnimationManager.html](https://photonstorm.github.io/phaser3-docs/Phaser.Animations.AnimationManager.html)

But common places of visit, like these one, **docs are correct :** 

- [https://photonstorm.github.io/phaser3-docs/Phaser.Types.Animations.html#.GenerateFrameNumbers__anchor](https://photonstorm.github.io/phaser3-docs/Phaser.Types.Animations.html#.GenerateFrameNumbers__anchor)

-  [https://phaser.io/tutorials/making-your-first-phaser-3-game/part5](https://phaser.io/tutorials/making-your-first-phaser-3-game/part5)

Will keep on updating any other reference, which needs an update.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
