### ISSUE TITLE
Constructors for Point and Vector2 belong together

### ISSUE THREAD

**Issue by tomprogers** [photonstorm/phaser#5486]
Maybe it's just me, but it seems perplexing that the constructors for `Point` and `Vector2` are not siblings.
- `Point` lives at `Phaser.Geom.Point`
- `Vector2` lives at `Phaser.Math.Vector2`

I would expect `Vector2` to live at `Phaser.Geom.Vector2`.

"Vector" is defined specifically with reference to geometry in both the Phaser documentation and on Wikipedia:
![Screen Shot 2021-01-04 at 10 12 01 PM](https://user-images.githubusercontent.com/3911927/103605802-781dfb80-4eda-11eb-9cb4-d6d1bd9d7b69.png)

> A representation of a vector in 2D space
> -- [Phaser 3 documentation](https://photonstorm.github.io/phaser3-docs/Phaser.Math.Vector2.html)

![Screen Shot 2021-01-04 at 10 15 34 PM](https://user-images.githubusercontent.com/3911927/103605854-9be14180-4eda-11eb-902b-7379b2c03a20.png)
> Euclidean vector, a geometric object that has magnitude (or length) and direction
> -- [Wikipedia, on Vector](https://en.wikipedia.org/wiki/Vector)

`Vector2` should be moved (or aliased) into the `Phaser.Geom` collection.

**Comment by photonstorm** [comment]
There's no tangible benefit to moving (or aliasing) this. Point was left over from v2. Vector2 is used almost exclusively internally and in Phaser 4 it's Vector2 only and no Point class. The two have existed like this in v3 for years now and there's no need to change them at this stage of its life.
