### ISSUE TITLE
Collide booleans are not working correctly with matter tile?

### ISSUE THREAD

**Issue by ygongdev** [photonstorm/phaser#5488]
## Version

* Phaser Version: v3.50.1

* Operating system:

* Browser: Chrome

## Description

When my player is moving toward the tile, I expect its bottom sensor to trigger only with the top surface of the tile. To do that, I want to ignore collisions with the bottom surface of the tile by setting `collideDown` property of the tile to false. However, my collision seems to still trigger when the bottom of the tile touches my player's bottom sensor.

`Console.log` at the point of collision shows that the `collideDown` property is set properly.

Attached image shows my player getting stuck after the wrong collision detection. The collision should be detected when the player is above the top of the tile.
[
![bugged](https://user-images.githubusercontent.com/8813928/103720635-a6561680-4f80-11eb-9246-e6cbcf32106d.PNG)
](url)

## Example Test Code
```js
  constructor(scene, layer) {
    this.scene = scene;
    this.layer = layer;

    this.layer.setCollisionBetween(0, this.layer.tilesTotal, true);
    const tiles = this.layer.getTilesWithin(0, 0, this.layer.width, this.layer.height , { isColliding: true });

    const { TileBody: MatterTileBody } = Phaser.Physics.Matter;

    this.matterTiles = tiles.map(tile => new MatterTileBody(this.scene.matter.world, tile).setSensor(true));
  }

  setupPlayerCollision(player) {
    for (let i = 0; i < this.matterTiles.length; i++) {
      const matterTile = this.matterTiles[i];
      // matterTile.tile.setCollision(false, false, false, false);
      matterTile.tile.collideDown = false;
      matterTile.tile.collideLeft = false;
      matterTile.tile.collideRight = false;
      // matterTile.tile.collideUp = false;
  
      this.scene.matterCollision.addOnCollideStart({
        objectA: [matterTile.body],
        objectB: [ player.sensors.bottom ],
        callback: () => {
          debugger;
          matterTile.setSensor(false)
        }
      });
      this.scene.matterCollision.addOnCollideActive({
        objectA: [matterTile.body],
        objectB: [ player.sensors.bottom],
        callback: () => matterTile.setSensor(false)
      });
      this.scene.matterCollision.addOnCollideEnd({
        objectA: [matterTile.body],
        objectB: [ player.sensors.bottom ],
        callback: () => {
          debugger;
          matterTile.setSensor(true);
        }
      });
    }
  }
```

## Additional Information

I'm also using this collision plugin for matter.js
https://github.com/mikewesthad/phaser-matter-collision-plugin

**Comment by photonstorm** [comment]
These properties are used by Arcade Physics, not Matter. I will update the documentation for them now to make this more clear.

For Matter, you should use `this.matter.world.convertTilemapLayer(layer);` which will convert the layer. Any colliding tiles will be given a Matter body. If a tile has collision shapes from Tiled, these will be loaded. If not, a default rectangle body will be used (all faces colliding, as it's a single body). The body will be accessible via `tile.physics.matterBody`, so you can filter the direction in your callback if you require.

**Comment by ygongdev** [comment]
@photonstorm thanks for the explanation.
However, I'm still unable to understand how to filter the direction in my callback if those booleans are ignored?

Does this mean implementing [pass through platforms](https://katyscode.wordpress.com/2013/01/29/2d-platform-games-part-8-pass-through-platforms/) are impossible using the matter engine?

**Comment by photonstorm** [comment]
As with Box2d, in Matter Physics, all non-sensor fixtures are solid, regardless of the direction they are collided from. So you have to literally boil it down to the math of using the player's velocity and the tile collision booleans to determine if the collision has actually happened or not. The links from this issue may help: https://github.com/liabru/matter-js/issues/456

**Comment by ygongdev** [comment]
I see, I will try that. Thanks for the help!
