### ISSUE TITLE
Strange artifacts/rendering bug when using Spine in 3.51

### ISSUE THREAD

**Issue by ChristianTucker** [photonstorm/phaser#5490]
## Version
* Phaser Version: `^3.51.0`
* Operating system: `Windows 10, PRO`
* Browser: All Browsers 

## Description
Note: This also happens in 3.50 (not sure about older versions).

Using the SpinePlugin located on GitHub ([here](https://github.com/photonstorm/phaser/blob/master/plugins/spine/dist/SpinePlugin.js)) when loading a spine character there are several artifacts and missing pieces of the texture that do not occur in other Spine renderers. Per the documentation I have made sure that the version of Spine we've exported the character from matches the version of the Spine Runtimes used, in this case, `3.8.95`. 

## Example Test Code

Demonstration link: https://christiantucker.github.io/phaser3-spine-bug/
Minimum Viable Reproduction: https://github.com/ChristianTucker/phaser3-spine-bug

## Additional Information

I will provide two examples, the first of which is a rendering from Phaser and the second of which is a rendering using PixiJS (both using the same spine assets) and [pixi-spine](https://www.npmjs.com/package/pixi-spine). 

**Phaser**
![Phaser Rendering](https://gyazo.com/2f9a999130f27c14080484addc9a3229.gif)

**PixiJS**
![PixiJS Rendering](https://gyazo.com/72ffb9a7273c3ff077d159d4dd9e1784.gif)

**Comment by photonstorm** [comment]
This is a pre-multiplied alpha issue. You need to set the textures `preMultipliedAlpha` flag in the load call to match how it's exported from Spine.

**Comment by ChristianTucker** [comment]
Hey @photonstorm thanks for reaching out, you were right this absolutely was the issue. I must have missed it in the documentation, however, perhaps I'm blind but I can't seem to find the documentation about that option when calling `.load` in found [here](https://photonstorm.github.io/phaser3-docs/SpinePlugin.html).

However, I can find the documentation [in the code](https://github.com/photonstorm/phaser/blob/master/plugins/spine/src/SpinePlugin.js#L599) stating that you can use a configuration object, which isn't mentioned anywhere in the SpinePlugin documentation available on the website. The only place I can find a config object mentioned is in the documentation for [make(config, [, addToScene])](https://photonstorm.github.io/phaser3-docs/SpinePlugin.html#make__anchor) but this doesn't show initialization of preMultiplyAlpha 

I may just be totally missing it, but where is the documentation located that goes over the initialization parameters? I see things like this in the documentation

```js
this.load.spine('stretchyman', 'stretchyman-pro.json', [ 'stretchyman-pma.atlas' ], true);
```

and judging on the config-object I found in the code earlier I can only assume that `true` here is for `preMultipliedAlpha` but  as shown in the example that doesn't work while the following config does.

```js
this.load.spine({
    key: 'test', 
    jsonURL: 'character.json', 
    atlasURL: 'character.atlas', 
    premultipliedAlpha: true 
});
```

**Comment by photonstorm** [comment]
It's in the docs here: https://photonstorm.github.io/phaser3-docs/Phaser.Loader.LoaderPlugin.html#spine__anchor (which uses the SpineFile object here https://photonstorm.github.io/phaser3-docs/Phaser.Loader.FileTypes.SpineFile.html)

**Comment by ChristianTucker** [comment]
@photonstorm Interesting, I wasn't expecting information like that to be scattered throughout other places, it feels a little strange to me that documentation relating to loading a spine object as defined in the SpinePlugin is documented in the LoaderPlugin. I would have never thought to look there. 

Thanks for all the help! Checking LoaderPlugin and FileTypes documentation will sure save me some headache in the future.
