### ISSUE TITLE
WebAudioSound's destroy() method causes crash in Safari (iOS and Mac)

### ISSUE THREAD

**Issue by ccaleb** [photonstorm/phaser#5492]
## Version
* Phaser Version: 3.51.0
* Operating system: iOS and Max OS 11.1
* Browser: Safari (iOS and Mac OS)

## Description
The WebAudioSound class' `destroy()` method causes a crash when running in Safari both on iOS and Mac OS. This seems to be caused by the new WebAudio panning feature which breaks on Safari.

From looking at the destructor, there's a call to the `disconnect()` method on a panner node instance that is null. This results in the following error appearing in the JavaScript console:

> Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'this.pannerNode.disconnect')

This seems to be related to bug fix #5460

Here's the code from WebAudioSound.js

```javascript
destroy: function ()
{
    BaseSound.prototype.destroy.call(this);

    this.audioBuffer = null;
    this.stopAndRemoveBufferSource();
    this.muteNode.disconnect();
    this.muteNode = null;
    this.volumeNode.disconnect();
    this.volumeNode = null;
    this.pannerNode.disconnect(); // <--- This line is causing the crash
    this.pannerNode = null;
    this.rateUpdates.length = 0;
    this.rateUpdates = null;
},
```

Writing a simple guard around the code seems to get things working again in Safari:

```javascript
destroy: function ()
{
    BaseSound.prototype.destroy.call(this);

    this.audioBuffer = null;
    this.stopAndRemoveBufferSource();
    this.muteNode.disconnect();
    this.muteNode = null;
    this.volumeNode.disconnect();
    this.volumeNode = null;
    if (this.pannerNode) this.pannerNode.disconnect(); // <--- This gets things working again
    this.pannerNode = null;
    this.rateUpdates.length = 0;
    this.rateUpdates = null;
},
```

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG-v3.50.md).

**Comment by ccaleb** [comment]
Sorry should have spotted this in the change log. Thanks for the update!

**Comment by drunkcat** [comment]
the same problem occurs sometimes with other parameters: 
this.muteNode, this.volumeNode and this.rateUpdates
All are (sometimes) reported null.

Phaser Version: 3.55.2
Operating system: Windows 11
Browser: Opera 89.0

**Comment by jjongsu** [comment]
the same problem occurs sometimes with other parameter:
this.muteNode reported null.

Phaser Version: 3.55.2
Operating system: Mac OS Ventura 13.3.1(a)
Browser: Chrome 114.0

This results in the following error appearing in the JavaScript console:
`Uncaught TypeError: Cannot read properties of null (reading 'disconnect')`
