### ISSUE TITLE
Spine Game object above an ellipse in the displayList makes every sprite blue

### ISSUE THREAD

**Issue by EmilSV** [photonstorm/phaser#5493]
## Version
* Phaser Version: 3.51.0
* Operating system: Windows

## Description

if a spine Game object is above an ellipse game object in the displayList every sprite/image becomes purely blue

## Example Test Code
```
class Example extends Phaser.Scene
{
    constructor ()
    {
        super({
            pack: {
                files: [
                    { type: 'scenePlugin', key: 'SpinePlugin', url: 'plugins/3.8.95/SpinePluginDebug.js', sceneKey: 'spine' }
                ]
            }
        });
    }

    preload ()
    {
        this.load.image('logo', 'assets/sprites/phaser.png');

        this.load.setPath('assets/spine/3.8/demos/');

        this.load.spine('set1', 'demos.json', [ 'atlas1.atlas' ], true);
    }

    create ()
    {
        this.add.image(0, 0, 'logo').setOrigin(0);

        const boy = this.add.spine(460, 600, 'set1.spineboy', 'idle', true);
        const circle = this.add.ellipse(130, 200, 250, 250, 0xffffff);

        this.sys.displayList.bringToTop(boy);
    }
}

const config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    scene: Example
};

const game = new Phaser.Game(config);

```
![blue_bug](https://user-images.githubusercontent.com/3351370/104067459-808c7400-5203-11eb-8c87-3c89728049b1.gif)

**Comment by EmilSV** [comment]
maybe this is related to #5449

**Comment by photonstorm** [comment]
This is almost certainly the same as #5449 but I'll leave it open for now.

**Comment by FloodGames** [comment]
Thanks a lot for opening!

A very clear replication demo.

**Comment by samme** [comment]
https://codepen.io/samme/pen/MWbKeEE

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
