### ISSUE TITLE
Loader does not emit FILE_COMPLETE event for atlas files

### ISSUE THREAD

**Issue by mikuso** [photonstorm/phaser#5495]
## Version
* Phaser Version: 3.51.0

## Description

Loader fails to emit FILE_COMPLETE event for atlases. In prior versions (<= 3.24.1), FILE_COMPLETE would be emitted with a reference to the json part of the atlas.

## Example Test Code

Example using Phaser 3.24.1 (working) - https://jsfiddle.net/0yvjhqzr/3/
Example using Phaser 3.51.0 (broken) - https://jsfiddle.net/f2y8do6p/

(see console output)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
