### ISSUE TITLE
`Phaser.GameObjectsFactory.existing` does not recognize `Phaser.GameObjects.Group` in Typescript

### ISSUE THREAD

**Issue by AkshatM** [photonstorm/phaser#5496]
## Version

* Phaser Version: v3.51.0 (latest on NPM)
* Operating system: Ubuntu 18.04
* Browser: Chrome 87.0.4280.88

## Description

The [docs](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.GameObjectFactory.html#existing__anchor) indicate an argument of type `Phaser.GameObjects.Group` is acceptable, but the example test code below throws errors expecting a regular `GameObject`.

(Note: I am not very familiar with Typescript, so maybe this is an error on my part - if so, please correct me!)

## Example Test Code

```
// /home/akshat/workspace/phaser3-game/src/scripts/objects/snake.ts
export default class Snake extends Phaser.GameObjects.Group {
  constructor(scene: Phaser.Scene) {
    super(scene);
    scene.add.existing(this); // line throwing error below
  }
}
```

Compiling, this throws 

```
ERROR in /home/akshat/workspace/phaser3-game/src/scripts/objects/snake.ts
./src/scripts/objects/snake.ts
[tsl] ERROR in /home/akshat/workspace/phaser3-game/src/scripts/objects/snake.ts(7,24)
      TS2345: Argument of type 'this' is not assignable to parameter of type 'GameObject'.
  Type 'Snake' is missing the following properties from type 'GameObject': displayList, state, parentContainer, tabIndex, and 20 more.
```

You can try running it more completely at `https://github.com/AkshatM/snake` (just clone and run `npm start`).

## Additional Information

I noticed in https://github.com/photonstorm/phaser/issues/4941 you added support for `Phaser.GameObjects.Group` in `add.existing` just a few days ago. Maybe there's a patch release to 3.51 I should upgrade to?

**Comment by photonstorm** [comment]
Actually, support was added over a year ago :) (it was added 4th January 2020!)
