### ISSUE TITLE
Performance downgrade from 3.50.0-beta.10 to 3.50.0-beta.12

### ISSUE THREAD

**Issue by venarius** [photonstorm/phaser#5500]
## Version
* Phaser Version: 3.51.0

* Operating system: Windows 10

* Browser: all

## Description

When I upgraded from version 3.50.0-beta.10 to 3.51.0 I noticed that the performance of my game was considerably worse than on the older version.

I used specter.js to inspect the draw calls that the WebGL renderer was creating and found out that the new version made a whopping 113 (including draw calls) commands comparing to the 4 commands from the old version. It has probably something to do with the Multi-Texturing-Pipeline breaking.

I dug a bit deeper and found out, that it changed between 3.50.0-beta.10 and 3.50.0-beta.12. I hope that helps you out when trying to reduce the possible causes.

## Example Test Code

https://codesandbox.io/s/phaser-3500-performance-webglmulti-jn318?file=/src/index.js

You can switch between the phaser versions there and then inspect them with the specter.js chrome extension. (16 vs 19 commands in this small example alone)

### Specter Screenshots

From the new version:
![Capture](https://user-images.githubusercontent.com/13546486/104535274-2da52900-5616-11eb-8823-ba74e5c9f6c9.PNG)

From the old version:
![Capture2](https://user-images.githubusercontent.com/13546486/104535321-401f6280-5616-11eb-9eff-d240aa431ef5.PNG)

**Comment by gammafp** [comment]
There is a new Phaser version (3.51.0 ). You've tried?. [Phaser page download](https://phaser.io/download/stable)

**Comment by photonstorm** [comment]
It would still do this under 3.51 because this example is switching between two pipelines (the multi pipeline and the graphics pipeline), and that is just how many gl ops it takes to do that switch.

**Comment by venarius** [comment]
> There is a new Phaser version (3.51.0 ). You've tried?. [Phaser page download](https://phaser.io/download/stable)

Yes, like I have written, it is still under Version 3.51.0 but I managed to narrow it down to the versions the change / break happened.

**Comment by photonstorm** [comment]
It's not a break, it was fully intentional to split these pipelines apart.

**Comment by venarius** [comment]
@photonstorm so is there any way I can get the old performance on the new version or would it require me to restructure my whole codebase? Or should I just stay on the old version for now?

**Comment by photonstorm** [comment]
Note to self: Could investigate providing a new pipeline which merges Multi and Graphics together, but maybe too late in the v3 dev cycle for this.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release (3.55). If you get time to build and test it for yourself we would appreciate that.
