### ISSUE TITLE
bitmapText not working on Canvas

### ISSUE THREAD

**Issue by DPMakerQB** [photonstorm/phaser#5501]
## Version

* Phaser Version: 3.51.0

* Operating system: Windows

* Browser: Chrome

## Description

bitmapText stopped working after upgrading from 3.24.1 to 3.51 on **CANVAS only**.
The issue is as simple as it sounds. I have a bitmap font that I've been using for a year now, I upgrade to 3.50+ and it stops working. There are no errors, the font just doesn't appear on the screen unless I switch over to WebGL instead of Canvas.

I've attached a repository below that loads the font and displays some text.

## Example Test Code

https://github.com/DPMakerQB/phaser-problem-bitmapText

```
function preload() {
    this.load.bitmapFont('lato', 'assets/lato_0.png', 'assets/lato.xml');
}

function create() {
    this.add.bitmapText(0, 0, 'lato', 'Testing').setOrigin(0);
}
```

**Comment by photonstorm** [comment]
Hmm, this is font specific, as it's rendering all of the fonts in the examples site in Canvas just fine. Will download your font and have a look at it, something in the XML is freaking it out.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
