### ISSUE TITLE
When container is placed over dropZone sprite, it does not receive any input

### ISSUE THREAD

**Issue by Nightspeller** [photonstorm/phaser#5508]
## Version
* Phaser Version: 3.52
* Operating system: win
* Browser: chromium edge

## Description

When container is placed over dropZone sprite it does not receive any input. 

## Example Test Code

var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#010101',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};
var game = new Phaser.Game(config);
function preload () {
    this.load.image('lemming', 'assets/sprites/lemming.png');
}
function create () {
    // if you comment this line, pointerdown will work as expected
    const dropArea = this.add.sprite(400, 300, 'lemming').setInteractive({dropZone: true});
    const container = this.add.container(400, 300);
    const sprite0 = this.add.sprite(0, 0, 'lemming');
    container.add(sprite0).setSize(64, 64)
      .setInteractive()
      .on('pointerdown', () => console.log('I will never happen :-('));;
}

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
