### ISSUE TITLE
RenderTexture.draw with tint: red/blue values inverted

### ISSUE THREAD

**Issue by anthonygood** [photonstorm/phaser#5509]
## Version
* Phaser Version: v3.51.0-FB
* Operating system: MacOS 11.1 (Big Sur)

## Description

Looks similar to this issue (which was apparently fixed): https://github.com/photonstorm/phaser/issues/3643

## Example Test Code

When I use `sprite.setTint(0xff0000)`, the sprite is tinted red as expected:

![image](https://user-images.githubusercontent.com/3775267/104824958-865f0680-584e-11eb-8a09-0a226fd57f11.png)

However, when drawing the frame to a render texture with `renderTexture.draw(frame, 0, 0, 1, 0xff0000)`, the texture is tinted blue:
![image](https://user-images.githubusercontent.com/3775267/104824968-a262a800-584e-11eb-8ef0-df6c69bd3bfe.png)

I added a crude function to swap the red and blue values, and the output looks correct:
```ts
export const invertRB = (colour: number) => {
  const [r,g,b] = colour.toString(16).padStart(6, '0').match(/[\w]{2}/g);
  return parseInt([b,g,r].join(''), 16);
}
```
![image](https://user-images.githubusercontent.com/3775267/104825060-5ebc6e00-584f-11eb-8d34-2257b499e7bb.png)

**Comment by photonstorm** [comment]
Sorry for the delay in responding, but I can confirm this is definitely working properly now (and has been for a few versions)
