### ISSUE TITLE
Minified version of Phaser 3.52.0 causing error on Safari

### ISSUE THREAD

**Issue by KovacicB** [photonstorm/phaser#5511]
Minified version of Phaser 3.52.0 is still throwing error on Safari while calling createStereoPanner(). Full version of Phaser 3.52.0 works normally.

**Comment by photonstorm** [comment]
I just checked the minified source and the panner conditional check is definitely present in there. Are you positive you've updated your files correctly?

**Comment by KovacicB** [comment]
Yes, positive. I have just tested it again and reproduced the error. phaser.min.js v3.52.0 causes error while phaser.js v3.52.0 doesn't.

**Comment by photonstorm** [comment]
3.52.0 min file code: `this.pannerNode&&(this.pannerNode.disconnect(),this.pannerNode=null)`

3.51.0 min file code: `this.pannerNode.disconnect(),this.pannerNode=null`

Hence, 3.51 throws an error in Safari when trying to disconnect the node, as it didn't check if it had been created. 3.52 makes this check correctly.

Both 3.51 and 3.52 do not create the panner node in the first place unless the context supports it: 

`t.context.createStereoPanner?(this.pannerNode=t.context.createStereoPanner() ...`

Where-as 3.50 didn't make this check at all, causing the Safari error.

Please show a codepen including the 3.52 min file demonstrating this fails on Safari, as I can't replicate it on my MacBook.

**Comment by photonstorm** [comment]
Am closing this as I cannot replicate it, the fix is in place in the min file in the repo here, and we cannot issue a fix to minified code anyway.
