### ISSUE TITLE
clearBeforeRender has no effect?

### ISSUE THREAD

**Issue by entozoon** [photonstorm/phaser#5513]
## Version
Phaser: 3.52.0 (latest), Chrome:  87.0.4280.141 (latest)

## Description

I'm possibly using clearBeforeRender wrong, but it seems as if things generally render normally despite setting clearBeforeRender: false. That is to say, they wipe the previous render and redraw on update rather than leaving the previous render stained on the screen.

## Example Test Code
This can be happily pasted into the [Phaser 3 Sandbox](https://labs.phaser.io/edit.html#):
```js
class Brain extends Phaser.GameObjects.Sprite {
  constructor(scene, x, y) {
    super(scene, x, y);
    this.setTexture("brain");
    this.setPosition(x, y);
  }
  preUpdate(time, delta) {
    super.preUpdate(time, delta);
    this.rotation += 0.01;
  }
}
var config = {
  type: Phaser.AUTO,
  parent: "phaser-example",
  scene: {
    preload: preload,
    create: create,
    update: update,
  },
  render: {
    clearBeforeRender: false,
    transparent: true,
  },
};
var game = new Phaser.Game(config);
function preload() {
  this.load.image("brain", "assets/sprites/brain.png");
}
function create() {
  // Graphics are fine
  this.graphics = this.add.graphics({ lineStyle: { color: 0x00ff00 } });
  this.circle = new Phaser.Geom.Circle(400, 500, 20);

  // ! Sprites seem to ignore clearBeforeRender: false
  this.add.existing(new Brain(this, 400, 250));

  // ! Particles seem to ignore clearBeforeRender: false
  const particles = this.add.particles("brain");
  particles.createEmitter({
    x: 110,
    y: 110,
    speed: 100,
    alpha: { start: 1.0, end: 0 },
  });
}
function update() {
  this.circle.radius += 5;
  this.graphics.strokeCircleShape(this.circle);
}
```

## Additional Information

I know it's achievable with PIXI, at least within an autoDetectRenderer instance so I can't imagine why this isn't working.

**Comment by entozoon** [comment]
@gammafp It's the same with canvas or WebGL

**Comment by photonstorm** [comment]
It won't be visible unless the game config is transparent with no background colour set.

**Comment by entozoon** [comment]
No joy, I've added `transparent: true` to render but it didn't help. Also is it possible to have multiple renderers?

**Comment by photonstorm** [comment]
No, you can't have multiple renderers.

`clearBeforeRender` is pointless in v3. Probably sensible to just remove the config property entirely.

**Comment by entozoon** [comment]
Oh really? Bugger.
Was hoping to have a bloodstain kinda layer like a previous project https://entozoon.itch.io/tankblade or a Spheres of Chaos kinda thing going on.
Thank you though, @photonstorm , helpful as ever!

**Comment by photonstorm** [comment]
That's not really how I would do a blood stain effect personally. Would much rather draw the stains to a Render Texture. Then I'd have more control over fading this out over time and not also having my main sprites, UI, etc all drawn to it as well.

**Comment by photonstorm** [comment]
This is now possible in the `master` branch by setting:

```js
    clearBeforeRender: false,
    preserveDrawingBuffer: true
```
