### ISSUE TITLE
Configuration has two "transparent" settings

### ISSUE THREAD

**Issue by robinheidrich** [photonstorm/phaser#5515]
## Version

* Phaser Version: 3.52.0

* Operating system: Windows 10

* Browser: Google Chrome 88.0.4324.96

## Description

There are two `transparent` settings in the configuration, although only `render.transparent` is used.

**Comment by photonstorm** [comment]
Just tested it and it works in both places:

```js
const config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    transparent: true
};
```

and

```js
const config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    render: {
        transparent: true
    }
};
```

As can be seen here: http://labs.phaser.io/view.html?src=src/game%20config/transparent.js&v=dev
