### ISSUE TITLE
Question: Does phaser offer a playground-like environment to built a graphic user interface?

### ISSUE THREAD

**Issue by inglesuniversal** [photonstorm/phaser#5516]
I am looking for a GUI generator that can help me create an interface made on top of Phaser and be able to add buttons, sliders, virtual keyboard and get the coordinates and code to paste it on my project?

Thanks

**Comment by rexrainbow** [comment]
[There](https://github.com/photonstorm/phaser/pull/5517) are some ui game objects, but dose not have  graphic editor.

**Comment by photonstorm** [comment]
Rex has already linked you to the best free UI plugins, so please take a look at those.
