### ISSUE TITLE
this.renderer.pipelines not recognised by TypeScript

### ISSUE THREAD

**Issue by ernest4** [photonstorm/phaser#5519]
* Phaser Version: Phaser v3.52.0 (WebGL | Web Audio) 

* Operating system: N/A

* Browser: N/A

## Description

Seems like some type definitions missing from typescript. Pipelines definitely exists under renderer as I can use them if i disable typescript.

## Example Test Code

with typescript enabled just try

`this.renderer.pipelines`

## Additional Information

<img width="885" alt="Screenshot 2021-01-22 at 21 41 43" src="https://user-images.githubusercontent.com/35740142/105552030-4d65dc80-5cfb-11eb-9a39-6f191a714a1e.png">

**Comment by photonstorm** [comment]
This is because `pipelines` doesn't exist on `CanvasRenderer` (and never will). You'll have to force-type `this.renderer` yourself to `WebGLRenderer` in your code to avoid the error.
