### ISSUE TITLE
Error stopping a scene: cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by schontz** [photonstorm/phaser#5520]
## Version
* Phaser Version: 3.5.1

* Operating system: Mac and Windows

* Browser: Chrome

## Description

Shutting down a scene causes an error:

```
TypeError: Cannot read property 'destroy' of undefined
    at DisplayList.shutdown (phaser.js:163448)
    at EventEmitter.emit (phaser.js:1928)
    at Systems.shutdown (phaser.js:47907)
    at SceneManager.stop (phaser.js:99258)
```

The error in `DisplayList` is here:
https://github.com/photonstorm/phaser/blob/master/src/gameobjects/DisplayList.js#L234

I believe the issue is that some of the objects being destroyed are in turn destroying some sub-objects, which would be on `this.list`, thus making the list shorter.

This could be fixed like so:

```js
while(list.length) {
  list[0].destroy(true);
}
```

That would be unaffected by changes to the list along the way.

**Comment by schontz** [comment]
I did a little more digging and it seems my original hunch is right. I have something like the following:

```js
class MySprite extends Phaser.Physics.Arcade.Sprite {
  constructor() {
    this.label = this.scene.add.text(10, 20, 'hello');
  }

  destroy() {
    this.label.destroy();
  }
}
```

When I trace `DisplayList.shutdown` I get something like so:

```
- shutdown: destroy (i = 7) = SomeObject
  - SomeObject.destroy
- shutdown: destroy (i = 6) = AnotherObject
  - AnotherObject.destroy
- shutdown: destroy (i = 5) = MySprite
  - MySprite.destroy
  - TextLabel.destroy
- shutdown: destroy (i = 4) = undefined because TextLabel was already destroyed.
```

Looking at the base [GameObject.destroy](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/GameObject.js#L710), you can see that destroying removes the item from the display list, thus naively using `i` in shutdown is not a good option. I am currently getting around the issue by manually calling the code in my initial comment before shutdown runs.

**Comment by daneren2005** [comment]
I am running into the same issue and for the same reason.  It is really helpful to be able to let objects manage their own dependencies without needing special logic to handle scene destruction separately.

**Comment by pt-hieu** [comment]
any update on this? I've been having this problem and it's like I don't have any `destroy` or `remove` called in my code

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.

**Comment by yaasinhamidi** [comment]
Hey guys 

I got this problem and trace it that maybe my components have problem but related to image that used in components and those images earlier have been destroyed in destroyed components 

I have been changed `phaser-arcade-physics.js` line `159195` (`shutdown` function) to this and solved this problem:

`while (i--)`
`        {`
`            if(typeof list[i] !== "undefined") {`
`                list[i].destroy(true);`
`          }`
`       }`

those list item that have been destroyed earlier, `typeof list[i] !== "undefined"` can skip destroyed items by this code.

**Comment by fromnowhereuser** [comment]
Hello, i have this problem too, when i try to delete a phaser "container" object. I really dont know how to handle this. My scene is replicated. I am using phaser within an angular comp...
@photonstorm do you have any news ?

**Comment by evan-boissonnot** [comment]
> Hey guys
> 
> I got this problem and trace it that maybe my components have problem but related to image that used in components and those images earlier have been destroyed in destroyed components
> 
> I have been changed `phaser-arcade-physics.js` line `159195` (`shutdown` function) to this and solved this problem:
> 
> `while (i--)` ` {` ` if(typeof list[i] !== "undefined") {` ` list[i].destroy(true);` ` }` ` }`
> 
> those list item that have been destroyed earlier, `typeof list[i] !== "undefined"` can skip destroyed items by this code.

it's the solution i want to do  ... but it's not good ...

**Comment by photonstorm** [comment]
> it's the solution i want to do ... but it's not good ...

This is already fixed in the master branch. Please make a build from there and use that.
