### ISSUE TITLE
confusing behavior when resizing Rectangle gameobject after setOrigin()

### ISSUE THREAD

**Issue by rattias** [photonstorm/phaser#5527]
## Version
* Phaser Version: 3.52.0
* Operating system:  Linux 5.4.0-58-generic #64-Ubuntu SMP

## Description
I'm creating a rectangle with x=0, y=0, w=32, h=200, whose origin is on the bottom-left corner. The rectangle shows up, as expected, aligned to the upper-left corner of the screen.
In `update()` i reduce the height of the rectangle until 0. I would expect the rectangle to maintain it's alignment to the original position of the bottom-left corner, and therefore the top side to move towards the bottom. Instead, I observe a confusing behavior: 
1) `rect.y` remains fixed at 200, and `rect.height` decreases, which is what I would expect, but
2) the rectangle bottom side moves toward the top, instead of the opposite.

The behavior is corrected if I 
1) decrease `displayHeight`  instead of `height` (although in this case `y` and `height` remain constant to 200), or
2) call `setOrigin(0, 1)` after each decrease of `height`

If this is the intended behavior, I'd suggest at least a clarification in the documentation of `setOrigin()` to explain what the right way to update width or height are after setting  one of the parameters to 1

## Example Test Code

```import Phaser from './lib/phaser.js'

class Game extends Phaser.Scene {
  constructor () {
    super('game')
  }

  preload () {
  }

  create () {
    this.rect = this.add.rectangle(0, 200, 64, 200, 0xFF0000, 1)
    this.rect.setOrigin(0, 1)
  }

  update () {
    console.log(this.rect.y, this.rect.height)
    if (this.rect.height > 0)
      this.rect.height--
  }
}

export default new Phaser.Game({
  type: Phaser.AUTO,
  scale: {
    parent: 'mygame',
    mode: Phaser.Scale.FIT,
    autoCenter: Phaser.Scale.CENTER_BOTH,
    width: 800,
    height: 600
  },
  audio: {
    disableWebAudio: true
  },
  dom: {
    createContainer: true
  },
  scene: [Game]
})
```

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/unexpected-behavior-of-gameobject-rectangle/8709/6

**Comment by photonstorm** [comment]
Using `displayWidth` and `displayHeight` is the correct way to do it. Alternatively, if you need to resize the core geometry itself, you can call `Rectangle.updateData()` and then `updateOrigin()` _after_ you have changed the width or height. They're two different things, though. The first effectively keeps the geometry the same size but renders at the new size, the second resizes the core geometry and then readjusts the origin accordingly. Which you require is dependant on your game, really.
