### ISSUE TITLE
Tween is not starting until browser's tab is active

### ISSUE THREAD

**Issue by inmylo** [photonstorm/phaser#5529]
* Phaser Version: 3.51.0
* Operating system: Linux

## Description

If tween is started when browser's tab is hidden - it is waiting until tab is active again and only then starts from the beginning.

Steps to reproduce:
1. Run the code below in Labs
2. Immediately switch to some other browser's tab
3. Wait 5 seconds
4. Open previous tab again

Result - tween is being fired when it's not actual any more and it's time has expired. I guess the solution is to skip starting if it's already too late.

## Example Test Code for the Labs

```js
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('block', 'assets/sprites/block.png');
}

function create ()
{
    var marker = this.add.image(100, 300, 'block').setAlpha(0.3);
    var image = this.add.image(100, 300, 'block');

    var tw = this.tweens.add({
        targets: image,
        angle: 45,
        duration: 300,
        onComplete: onCompleteHandler,
        paused: true
    });

    setTimeout(() => {
        tw.resume();
    }, 3000);
}

//  The callback is always sent a reference to the Tween as the first argument and the targets as the second.
//  Whatever you provided in the onCompleteParams array follows.
function onCompleteHandler (tween, targets, myImage)
{
    console.log('onCompleteHandler');
}
```

**Comment by photonstorm** [comment]
This is the correct behavior. Phaser itself is not running when the tab has no focus, so nothing gets updated. The game effectively pauses until the tab comes back into focus again.

This is a result of the way browsers implement request animation frame throttling when a tab is not in view (or if you obscure the browser window with another app) and there is nothing you can do to prevent the browser from doing it I'm afraid. Phaser simply cannot run if it doesn't have focus, nor can anything that relies on request animation frame or setTimeout.
