### ISSUE TITLE
Phaser 3 TypeScript doesn't have game.sound.context reference

### ISSUE THREAD

**Issue by trynx** [photonstorm/phaser#5531]
## Version

* Phaser Version: 3.24.1

* Operating system: Windows 10

* Browser: Opera

## Description
When using Phaser 3 with TypeScript, the object `game.sound` doesn't contain any reference to 'context'.
Once doing the `game.sound as any`, it doesn't throw any error and can use it without problem, I needed that to to fix some audio contex `context === "suspended"` shenanigan :(

This is the base class of sound `BaseSoundManager` that I searched and didn't found the context, neither in `WebAudioSoundManager`.

**Comment by photonstorm** [comment]
You need to cast it as `Phaser.Sound.WebAudioSoundManager` if you want to access Web Audio Manager specific properties like `context`, not `any`.

**Comment by photonstorm** [comment]
Actually, thinking about it, `context` is private anyway, so even doing that won't provide access to it.

**Comment by trynx** [comment]
Yep, already tried to cast it as `Phaser.Sound.WebAudioSoundManager`, and as you said, won't work :P

**Comment by photonstorm** [comment]
There we go then, it's a private property, so it's doing exactly what it should do.

**Comment by trynx** [comment]
Then comes the question, is there a possibility to know the state of `game.sound.context` and resume it as needed?

Because the problem I face is, once the game is loading (boot scene), if I focus on the loading and then change the focus to another window, the AudioContext will stay in `suspended` when I'm back to the game, couldn't find any other way to do it except actually touching the AudioContext `resume()`

**Comment by photonstorm** [comment]
I can't see a reason why `context` is private, so now it's not.

**Comment by elivelton23021998** [comment]
I solved the problem... Only put in update()

const { context } = this.game.sound as Phaser.Sound.WebAudioSoundManager;
        if (context.state === "suspended") {
            context.resume();
        }
}
