### ISSUE TITLE
Game config - set resolution

### ISSUE THREAD

**Issue by williammanco** [photonstorm/phaser#5534]
Hello guys,
the resolution property in the game config is ignored, from version 3.16.1 and above.

It's a bug or a change?

this is a demo https://codepen.io/samme/pen/wyVKBG, if you downgrade to 3.15.1 it works as well.

Thanks

**Comment by samme** [comment]
<https://github.com/photonstorm/phaser/blob/master/CHANGELOG-v3.50.md#removal-of-resolution-property-from-across-the-api>
