### ISSUE TITLE
Can't move container from container to scene without resetting displayList.

### ISSUE THREAD

**Issue by malahaas** [photonstorm/phaser#5535]
## Version
* Phaser Version: 3.52.0
* Operating system: Windows 10
* Browser: any

## Description

I’d like to have one of my containers removed from its parent container and added to the scene directly. If I add the child container to the scene without adding it to the parent container, it renders. If I don’t remove the child from the parent it renders. I can even remove the child from the parent and add it to another new container and it renders. Also, as noted by samme in the [forums](https://phaser.discourse.group/t/container-wont-move-to-scene/8756) setting the child's displayList to null before adding the container to the scene allows it to render.

## Example Test Code

```
import Phaser from 'phaser';

const config = {
  type: Phaser.AUTO,
  width: 800,
  height: 500,
  physics: {
    default: 'arcade',
    arcade: {
      debug: true,
      debugShowBody: true
    }
  },
  scene: [LoadingScene]
}

class LoadingScene extends Phaser.Scene{
  create(){
    const p = this.add.container(100, 100);
    p.name='parent';
    const c = this.make.container({x: 100, y: 100}, false);
    c.name='child';
    const g = c.scene.make.graphics({}, false);
    g.fillStyle(0xFFFFFF);
    g.fillRect(0, 0, 50, 10 - 4);
    g.name = 'graphic'
    c.add(g);
    p.add(c);
    p.removeAll();
    // add this here and it works: c.displayList = null;
    this.add.existing(c);
  }
}

new Phaser.Game(config);
```

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/container-wont-move-to-scene/8756/3

**Comment by samme** [comment]
https://codepen.io/samme/pen/YzpzePg

See failed assertion in console.

Eye sprite should be visible but it isn't.

**Comment by samme** [comment]
Moving a sprite from container to scene also fails: https://codepen.io/samme/pen/NWbWygb

**Comment by tringcooler** [comment]
Moving a game object from container to layer also fails.

**Comment by photonstorm** [comment]
These are all now fixed in the master branch. Please see the test cases here: http://labs.phaser.io/index.html?dir=game%20objects/display%20list/&q= (be sure to test using the dev build)
