### ISSUE TITLE
BitmapText from atlas doesn't display properly with canvas renderer

### ISSUE THREAD

**Issue by vforsh** [photonstorm/phaser#5545]
## Version
Phaser 3.52 and newer

## Description
I use the technique when I combine bitmap font texture with atlas to reduce draw calls and improve performance. It stopped working since the commit https://github.com/photonstorm/phaser/commit/9116eddf99c40d236c6af628894b223ee3531ed6

## Example Test Code
https://codesandbox.io/s/laughing-framework-44p38?file=/index.ts

## Additional Information
This example also doesn't work if you will change renderer (line 37) to Canvas - http://labs.phaser.io/edit.html?src=src%5Cgame%20objects%5Cbitmaptext%5Cstatic%5Cbitmaptext-atlas.js

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
