### ISSUE TITLE
Spine on canvas does not display properly

### ISSUE THREAD

**Issue by pheXion** [photonstorm/phaser#5547]
Spine its working fine with WebGL, but changing rendering for canvas causes strange behavior.

Example:
Change 'type: Phaser.WEBGL' for 'type: Phaser.CANVAS' on:
https://phaser.io/examples/v3/view/spine/basic-spineboy

**Comment by FostUK** [comment]
I think this issue is caused by the Spine runtime not supporting meshes on Canvas so nothing much Phaser can do about it.

**Comment by photonstorm** [comment]
It's working: http://labs.phaser.io/view.html?src=src%5Cspine%5Ccanvas%20test%201.js&v=dev

But you have to make sure you're using a suitable atlas (with pre-multiplied alpha handled for you), such as in the example above. You can't use _any_ Spine animation with canvas.
