### ISSUE TITLE
Phaser render speed problem

### ISSUE THREAD

**Issue by roberthook823** [photonstorm/phaser#5549]
The latest version of phaser v3.52.0 is much slower than the old version of v3.24.1. What's the cause?
Not only this game, but also the previous games I wrote also showed a significant drop in fps when upgraded to v3.52.0.
The screenshot was tested on Android, and the same phenomenon also appeared in iOS.

![phaserIssue](https://user-images.githubusercontent.com/59207864/107336340-511ba080-6afc-11eb-8edb-de52e268a7b0.png)

This is a screenshot of the iPhone 7 Safari as an inspection on Mac Safari.
![screenshot1](https://user-images.githubusercontent.com/59207864/107343832-19652680-6b05-11eb-9207-71d986066599.png)

The part below is the code.

![code](https://user-images.githubusercontent.com/59207864/107336518-8aeca700-6afc-11eb-8a7f-b292f52bd435.png)
![console](https://user-images.githubusercontent.com/59207864/107341355-33513a00-6b02-11eb-9759-4b680fd946cd.png)
![code](https://user-images.githubusercontent.com/59207864/107340863-9ababa00-6b01-11eb-9e8e-5222e506c11b.png)

**Comment by photonstorm** [comment]
We can't debug screenshots. Try running the games through Spector GL and compare the draw calls and WebGL operations. There's a lot of changes in 3.50, a lot more rendering power, but it takes more control to use. Better use of atlases, configuring batch sizes, being careful about not mixing pipelines (Graphics vs. Multi, etc).

**Comment by roberthook823** [comment]
Phaser 3.52.0 was very attractive. However, the problem was that the render speed on mobile was rising. I'm sending you the source code below, so please solve it.

[phaserRenderTest.zip](https://github.com/photonstorm/phaser/files/5952670/phaserRenderTest.zip)

**Comment by roberthook823** [comment]
> We can't debug screenshots. Try running the games through Spector GL and compare the draw calls and WebGL operations. There's a lot of changes in 3.50, a lot more rendering power, but it takes more control to use. Better use of atlases, configuring batch sizes, being careful about not mixing pipelines (Graphics vs. Multi, etc).
