### ISSUE TITLE
Phaser render speed problem

### ISSUE THREAD

**Issue by roberthook823** [photonstorm/phaser#5553]
I am sending you the source code below.
This is the first request I raised.
The mobile browser is less fps at 3.52.0 than at phaser3.24.1 I really need to use the latest version, but the fps has dropped significantly, so I can't use it. Especially in the ios. I already uploaded the screenshot before. I uploaded the source code by requesting additional information. Please solve it.
This is not the only phenomenon that fps is falling, but also in all games that I developed with phaser.
Of course, these games don't need to be upgraded to the latest version, but the game's development significantly failed to reach 60 fps, so the test results showed that the 3.52.0 version was significantly lower than the 3.24.1 version.

[phaserRenderTest.zip](https://github.com/photonstorm/phaser/files/5953815/phaserRenderTest.zip)

![Untitled](https://user-images.githubusercontent.com/59207864/107475677-d6b05680-6bb7-11eb-968f-7e411e5c0b0e.png)

**Comment by roberthook823** [comment]
I'd really appreciate it if you could solve this problem as soon as possible. I really want to use the latest version this time.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release (3.55). If you get time to build and test it for yourself we would appreciate that.
