### ISSUE TITLE
Proper TypeScript types for SceneManager.keys

### ISSUE THREAD

**Issue by schontz** [photonstorm/phaser#5554]
The current TypeScript type for `SceneManager.keys` is `object`, which is not very useful. It should be:

```ts
keys: Record<string, Phaser.Scene>
```

**Comment by photonstorm** [comment]
I've made this change, however, please note that there are seldom any good reasons why you should be directly accessing the `SceneManager.keys` object from your game anyway.

**Comment by schontz** [comment]
Noted. I was doing that to stop the current active scene before starting another one. Something like:

```
function startScene(key) {
   // stop the current scene
  const scenes = game.scenes.keys;
  for (let key in scenes) if(game.scenes.isActive(key)) game.scenes.stop(key);

  game.scenes.start(key);
}
```

What is the preferred way to do that?

**Comment by photonstorm** [comment]
`this.scene.restart(key)` would do exactly this, but using the queue correctly.

**Comment by schontz** [comment]
Great, thanks.
