### ISSUE TITLE
The startFrame param of Actions.PlayAnimation() is not compatible with ignoreIfPlaying param of AnimationState.play()

### ISSUE THREAD

**Issue by xuxucode** [photonstorm/phaser#5555]
## Version
* Phaser Version: 3.52.0

## Description
`startFrame` is an optional number, but `ignoreIfPlaying` is an optional boolean:

https://github.com/photonstorm/phaser/blob/master/src/actions/PlayAnimation.js#L21
```js
/**
 * @function Phaser.Actions.PlayAnimation
 * @param {(string|number)} [startFrame] - The starting frame of the animation with the given key.
 */
var PlayAnimation = function (items, key, startFrame)
{
    for (var i = 0; i < items.length; i++)
    {
        items[i].anims.play(key, startFrame); // will eventually call AnimationState.play()
    }

    return items;
};
```

https://github.com/photonstorm/phaser/blob/master/src/animations/AnimationState.js#L826
```js
/** 
 * @method Phaser.Animations.AnimationState#play
 * @param {boolean} [ignoreIfPlaying=false] - If this animation is already playing then ignore this call.
 */
play: function (key, ignoreIfPlaying)
{
  // ...
}
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
