### ISSUE TITLE
Input events are sorted in wrong order when use container.

### ISSUE THREAD

**Issue by tringcooler** [photonstorm/phaser#5557]
## Version

* Phaser Version: 3.52.0

* Operating system: win7

* Browser: chrome

## Description

Sorry for my English.

Container objects can not be sorted in right way in function sortGameObjects.

## Example Test Code

``` js
scene.add(some_other_object_like_image);
let container = scene.add.container();
let bg = scene.make.image({key: bg_name});
container.add(bg);
container.setSize(bg.width, bg.height);
scene.add(container);

some_other_object_like_image.setInteractive();
some_other_object_like_image.on('pointerdown', (p) => {
    console.log('other');
});

container.setInteractive();
container.on('pointerdown', (p) => {
    console.log('container');
});
```
When the container bg image is over the some_other_object_like_image object, the container's event never be triggered.

## Additional Information

at source code:
``` js
sortGameObjects: function (gameObjects, pointer)
    {
        if (gameObjects.length < 2)
        {
            return gameObjects;
        }

        var list = pointer.camera.renderList;

        return gameObjects.sort(function (childA, childB)
        {
            return list.indexOf(childB) - list.indexOf(childA);
        });
    },
```

The pointer.camera.renderList does not contain any container object, so this function will not work for container objects.

**Comment by rexrainbow** [comment]
See this issue #5506

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
