### ISSUE TITLE
Error when destroying Text game object with headless renderer

### ISSUE THREAD

**Issue by mattjennings** [photonstorm/phaser#5558]
## Version

* Phaser Version: 3.52.0

* Operating system: macOS

## Description

The following error is thrown when destroying a Text GameObject while using Phaser.HEADLESS as the renderer

```
Uncaught TypeError: Cannot read property 'type' of null
```

which seems to be pointing to [this line](https://github.com/photonstorm/phaser/blob/master/src/textures/Texture.js#L512). Should be just a matter of adding a check for `renderer && renderer.type`. I can make a PR for this tomorrow, but there might be other places where a similar check is needed.

I remember a similar bug happening in #4976. Is there a way we can prevent similar regressions on this in the future? Perhaps a utility function that safely returns the renderer.type, eliminating the risk of accidentally forgetting to check it safely in the future?

## Example Test Code

[CodeSandbox repro](https://codesandbox.io/s/phaser-headless-bug-v1nzp?file=/src/index.js)

## Additional Information

Only started happening after upgrading from 3.24.1

**Comment by mattjennings** [comment]
Made a PR for it at #5559. It seemed like this was the only unsafe `renderer.type`, check so maybe it's fine just fixing it alone for now.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
