### ISSUE TITLE
Remove objects from cache by key

### ISSUE THREAD

**Issue by borkowsky** [photonstorm/phaser#5562]
Hi. I have 100 maps and load they as needed. I need to remove they from cache, when i switch to another location. I dont found any methods, which do something like that. Sorry for bad english.

**Comment by halilcakar** [comment]
Hello @borkowsky;

Here you can check for removing by name from [BaseCacheManager#remove](https://photonstorm.github.io/phaser3-docs/Phaser.Cache.BaseCache.html#remove__anchor)

And if you want to remove texture [Texture#remove](https://photonstorm.github.io/phaser3-docs/Phaser.Textures.Texture.html#remove__anchor)

Hope this will help :)

**Comment by borkowsky** [comment]
> Hello @borkowsky;
> 
> Here you can check for removing by name from [BaseCacheManager#remove](https://photonstorm.github.io/phaser3-docs/Phaser.Cache.BaseCache.html#remove__anchor)
> 
> And if you want to remove texture [Texture#remove](https://photonstorm.github.io/phaser3-docs/Phaser.Textures.Texture.html#remove__anchor)
> 
> Hope this will help :)

Thanks for the answer, but i need to remove tilemaps.

**Comment by samme** [comment]
[this.cache.tilemap](https://photonstorm.github.io/phaser3-docs/Phaser.Cache.CacheManager.html#tilemap).[remove()](https://photonstorm.github.io/phaser3-docs/Phaser.Cache.BaseCache.html#remove)

Try [Discord or the forum](http://phaser.io/community) first for questions like these.
