### ISSUE TITLE
Blend modes are not set on WebGL Graphics primitives drawn to a RenderTexture

### ISSUE THREAD

**Issue by danarcher** [photonstorm/phaser#5565]
## Version
* Phaser Version:  v3.52.0 
* Operating system: Windows 10 Version 1909 (OS Build 18363.1379)
* Browser: Firefox 85.0.2 (64-bit)

## Description

Under WebGL, calling setBlendMode() on a Graphics object has no effect when drawing that Graphics object to a RenderTexture.

The workaround is to add the Graphics object to a Container, and draw that Container to the RenderTexture.

This came up whilst drawing primitives to a Graphics object using additive blending, then drawing that RenderTexture to the scene using multiplicative blending, in order to implement a light/shadow effect.

## Example Test Code

See [https://codepen.io/danarcher/pen/OJbWYeW](https://codepen.io/danarcher/pen/OJbWYeW). The code is drawing concentric circles using additive blending.

Set `workaround` to `true` to see the workaround in effect, whereby concentric circles of increasing (additive) brightness are visible.

The workaround isn't necessary when using the canvas rather than WebGL renderer (change `Phaser.WEBGL` to `Phaser.CANVAS` in the example to demonstrate).

## Additional Information

There is no call to the renderer to set the blend mode from [GraphicsWebGLRenderer](https://github.com/photonstorm/phaser/blob/v3.52.0/src/gameobjects/graphics/GraphicsWebGLRenderer.js) or [RenderTextureWebGLRenderer](https://github.com/photonstorm/phaser/blob/v3.52.0/src/gameobjects/rendertexture/RenderTextureWebGLRenderer.js).

There is a call to the renderer to set the blend mode from [ContainerWebGLRenderer](https://github.com/photonstorm/phaser/blob/v3.52.0/src/gameobjects/container/ContainerWebGLRenderer.js#L99).

**Comment by sjb933** [comment]
I can confirm I'm experiencing the same issue. In my game I handle dynamic lighting and shadow casting with some shader tricks:

1. I draw each light source to a RenderTexture with, taking into account occlusion and shadow casting from game objects.
2. I apply a fragment shader to this for soft shadows and light fade
3. I draw each individual light source RenderTexture from step 1 to a composite lighting render texture with **additive** blending
4. I draw the composite lighting RenderTexture to my scene with **multiplicative** blending.

What I'm experiencing is very similar to the reported issue here - that the additive blending of my light maps isn't working when targeting my composite light map RenderTexture. Using WebGL

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
