### ISSUE TITLE
check for null after use

### ISSUE THREAD

**Issue by rattias** [photonstorm/phaser#5566]
## Version
* Phaser Version: 3.52.0
* Operating system: Linux
* Browser: Chrome

## Description
While attempting to address an issue in my code, I stumbled into this Phaser code:

```
var DOMElementCSSRenderer = function (renderer, src, camera, parentMatrix)
{
    var node = src.node;
    var style = node.style;
    var settings = src.scene.sys.settings;

    if (!node || !style || !settings.visible || GameObject.RENDER_MASK !== src.renderFlags || (src.cameraFilter !== 0 && (src.cameraFilter & camera.id)) || (src.parentContainer && !src.parentContainer.willRender()))
    {
```
Here `!node` is checked only after node is dereferenced in `node.style`. This seems incorrect. 

## Example Test Code
In my case, `src.node` was undefined, as I was calling `const element = this.add.dom(400, 600).createFromCache('')` (note the empty string) instead of specifying the key for the cached html. The surprising thing is that I copied that code from the example [here](http://phaser.io/examples/v3/view/game-objects/dom-element/form-input), which seems to work.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
