### ISSUE TITLE
Destroying a group causes an error

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5576]
## Version

* Phaser Version: 3.52.0

## Description

Create a group. Set its `runChildUpdate` to `true`. Destroy it. You'll see an error at Group#preUpdate() similar to

> TypeError: undefined is not an object (evaluating 'this.children.size')

## Example Test Code

```js
const group = this.add.group();

group.runChildUpdate = true;
group.destroy();
```

## Additional Information

The group isn't removed from the scene update list when destroyed. Group#removedFromScene() is never called.

Group#addedToScene() is never called either.

**Comment by photonstorm** [comment]
I cannot replicate this error. However, `destroy` doesn't remove the Group either, so I'll look at that.

```js
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#000000',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.spritesheet('invader2', 'assets/tests/invaders/invader2.png', { frameWidth: 44, frameHeight: 32 });
}

function create ()
{
    var invaders = this.add.group([
        { key: 'invader2', frame: 0, repeat: 10, setXY: { x: 32, y: 148, stepX: 52 } },
        { key: 'invader2', frame: 0, repeat: 10, setXY: { x: 32, y: 148 + 48, stepX: 52 } }
    ]);

    Phaser.Actions.IncX(invaders.getChildren(), 100);
    Phaser.Actions.SetTint(invaders.getChildren(), 0x00ff00);

    this.input.once('pointerdown', () => {

        console.log('nuke');

        invaders.destroy();

    });
}
```

**Comment by photonstorm** [comment]
Actually, my example shouldn't have done anything anyway, because I didn't do `destroy(true)` - adding that still doesn't cause this error, though.

**Comment by samme** [comment]
My mistake, you have to add

```js
group.runChildUpdate = true;
```

to get the error. I'll update the description.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
