### ISSUE TITLE
Some sound types are incorrect

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5578]
## Version

* Phaser Version: 3.52.0

## Description

You can get false TypeScript errors using Sounds because Phaser's types are incorrect.

## Example Test Code

```js
const sound = this.add.sound('key');

sound.setVolume(1);
// TypeScript error: setVolume does not exist on type 'BaseSound'
```

## Additional Information

The Sound Manager methods returning `BaseSound` should return `HTML5AudioSound | NoAudioSound | WebAudioSound` instead.

But `NoAudioSound` has a lot of undocumented members (e.g., `volume`, `setVolume()`) that need to be documented to allow that.

Credit pastaboss.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
