### ISSUE TITLE
Tween: Timeline: `progress` and `totalProgress` are incorrect if timeline has more than one tween

### ISSUE THREAD

**Issue by micsun-al** [photonstorm/phaser#5579]
## Version
* Phaser Version: 3.52.0
* Operating system: macOS Catalina
* Browser: Google Chrome 88.0.4324.182

## Description

Result:
`Timeline` has `progress` and `totalProgress` values that go from `0` to `progress / tweens.length`.

Expected result:
`Timeline` has `progress` and `totalProgress` values that go from `0` to `1`.

Example:
If a timeline has 3 tweens, the `progress` and `totalProgress` values will go from `0` to `0.333333`.

## Example Test Code

```javascript
this.tweens.timeline({
  targets: someObj,
  tweens: [
    {
      duration: 2000,
      props: { x: 69 },
    },
    {
      offset: 0,
      duration: 2000,
      props: { y: 1337 },
    },
    {
      offset: 0,
      duration: 2000,
      props: { alpha: 0.8008 },
    },
  ],
  onUpdate: timeline => {
    console.log(timeline.progress, timeline.totalProgress, timeline.elapsed, timeline.duration)
  },
})
```

**Comment by micsun-al** [comment]
Maybe this is working and I was spamming the console too much? The `progress` value seems to be working again for me inside of `onUpdate`.

**Comment by photonstorm** [comment]
Your example logs out correctly for me.
