### ISSUE TITLE
The obsolete method Phaser.Scenes.Systems#install() still exists in the code, and causes an error when used

### ISSUE THREAD

**Issue by Trissolo** [photonstorm/phaser#5580]
## Version

- Phaser Version: 3.52.0

## Description
The method:
https://github.com/photonstorm/phaser/blob/a3bcf4beb136b28bf1e19c1e05fbfb7d146cfc51/src/scene/Systems.js#L353-L361
 attempts to call `PluginManager.installLocal()`, which no longer exists, causing the following error:

> Uncaught TypeError: this.plugins.installLocal is not a function

## Example Test Code

```javascript
class BrokenScene extends Phaser.Scene {

  constructor ()
  {
      super( {plugins: []} );
  }

  init()
  {
      this.sys.install('TweenManager')
  }

}
```
## Additional Information

This method appears in the [Dev Log #119](https://phaser.io/phaser3/devlog/119), written in the time of Phaser v3.3, and is described as one of the many ways to install a Default Plugin in a specific Scene.
In any case, in the [docs](https://photonstorm.github.io/phaser3-docs/Phaser.Plugins.DefaultPlugins.html#.DefaultScene__anchor) it is well explained how, nowadays, you can select your favorite DefaultPlugins.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
