### ISSUE TITLE
Support devicePixelRatio>1 with RESIZE scaling

### ISSUE THREAD

**Issue by orjandh** [photonstorm/phaser#5581]
**The what**
The RESIZE scaling mode works by setting the display size and the game size to fill the available space of the parent. When devicePixelRatio is larger than 1, I would expect the game resolution to be that times larger than the display size. Currently, with a devicePixelRatio of say 3, the resolution will be very  low for a game on a modern device. The other scaling modes seems to work perfectly well with a higher devicePixelRatio.

**The why**
As the RESIZE scaling mode is very useful for more responsive games, I think this will be a good feature. If we do a Google search for "phaser scale resize devicepixelratio", we find that this seems to be a somewhat common issue. So I do believe it will be useful to more people than just me. :)

**Suggestion**
I forked the codebase and pushed a suggestion which works in my case. https://github.com/orjandh/phaser/tree/scale_resize_dpr I don't know what would be the best interface for this, but I made an optional dprResize flag in the config which sets the resolution to the correct values.

I don't know if this change breaks other components. I noticed the camera scroll seemed to work a bit different, but might have been something in my code.

Lastly, I was considering just changing the internals of the scaling manager on the resize event that it emits. But this will break other components like the camera, because it also depends on the resize event.

**Comment by photonstorm** [comment]
You're more than welcome to implement this in your own fork, but there are no plans to support DPRs above 1 in any v3 release of Phaser, as reported in the Change Log:

#### Removal of 'resolution' property from across the API

For legacy reasons, Phaser 3 has never properly supported HighDPI devices. It will render happily to them of course, but wouldn't let you set a 'resolution' for the Canvas beyond 1. Earlier versions of 3.x had a resolution property in the Game Config, but it was never fully implemented (for example, it would break zooming cameras). When the Scale Manager was introduced in v3.16 we forced the resolution to be 1 to avoid it breaking anything else internally.

For a long time, the 'resolution' property has been present - taunting developers and confusing new comers. In this release we have finally gone through and removed all references to it. The Game Config option is now gone, it's removed from the Scale Manager, Base Camera and everywhere else where it matters. As much as we would have liked to implement the feature, we've spent too long without it, and things have been built around the assumption it isn't present. The API just wouldn't cope with having it shoe-horned in at this stage. As frustrating as this is, it's even more annoying to just leave the property there confusing people and wasting CPU cycles. Phaser 4 has been built with HighDPI screens in mind from the very start, but it's too late for v3. The following changes are a result of this removal:
