### ISSUE TITLE
Missing Mobile Controls for Browser on Samsung Tablet

### ISSUE THREAD

**Issue by scotus-49** [photonstorm/phaser#5582]
I may be missing something, but in trying out several examples of Phaser games in various browsers (Firefox, Chrome, Opera etc)  on my Samsung tablet, not a single control was available. I was looking at a screen with nothing moving, and no control options whatsoever, only static sprites and background graphics. 

I could find no conclusive info in the forum/docs explaining how to remedy this. Have I overlooked something?

The often criticized "no coding" GDevelop has this ability built-in, and is relatively easy to implement. 

Are there any plans for making it possible to play Phaser games on mobile devices using only the standard browser? Phaser otherwise seems to me to be very interesting, and you do advertise "browser powered games - but how do they work with no controls?

Regards from Berlin

Francis Sim

**Comment by photonstorm** [comment]
Did you try any of the Input examples? http://labs.phaser.io/index.html?dir=input/pointer/&q=

Such as "Cards" or "Down Event" - which should all work fine on a mobile browser.

You will never _visually_ see any extra controls on mobile, unless the example has specifically been created to add those on-screen. Equally, lots of examples are coded to use the keyboard only. That doesn't mean they can't have mobile controls as well, it just means the example itself doesn't have them implemented - as this is something you have to do as part of your game.

If you can link us to _input examples_ that don't work on this particular tablet then there might be an issue with that actual device that we need to look at. I'm going to close this issue, but you can carry on posting to it. I'll reopen if it we can prove there is an issue in the code.

**Comment by scotus-49** [comment]
Thanks for your help and explanation. I think I've got it now. I've tried the input examples you linked to, and they worked like a charm on my Samsung Tab.

Thanks again.
