### ISSUE TITLE
WEBGL still falls back to CANVAS

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5583]
## Version

* Phaser Version: 3.52.0

## Description

Create a game with type `Phaser.WEBGL`. Run it on a device without WebGL. The game runs in CANVAS mode.

[The docs say](https://photonstorm.github.io/phaser3-docs/Phaser.html#.WEBGL "Phaser.WEBGL"):

> Forces Phaser to use the WebGL Renderer. If the browser does not support it, there is no fallback to Canvas with this setting, so you should trap it and display a suitable message to the user.

But this doesn't happen. In this case WEBGL seems to act just like AUTO.

![webgl disabled](https://user-images.githubusercontent.com/435681/109394729-51c67c00-78dd-11eb-89b7-ae58d7eec0e2.png)

## Example Test Code

In Firefox you can set `webGL.disabled` to `false` in `about:config` and then visit any WEBGL example, e.g., <http://phaser.io/examples/v3/view/display/alpha/single-alpha>. The game runs in CANVAS mode with no error.

Or you can do

```js
new Phaser.Game({
    type: Phaser.WEBGL,
    backgroundColor: 0x0074D9,
    callbacks: {
        preBoot: function (game) {
            game.device.features.webGL = false;
        }
    },
    scene: {
        create: function () {
            this.add.text(0, 0, 'Hello');
        }
    }
});
```

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
