### ISSUE TITLE
Still Missing Matter TypeScript type definitions

### ISSUE THREAD

**Issue by LukaszGrela** [photonstorm/phaser#5584]
## Version

* Phaser Version: 3.52.0

* Operating system: Linux Mint

* Browser: N/A

## Description

The attempt to access the `Phaser.Physics.Matter.Matter` ends up with an error and no intellisense, I know there were similar issues closed, but it was over a year ago, could you please help with this error?

![image](https://user-images.githubusercontent.com/7643591/109402579-38faac80-7957-11eb-95c8-eff586349ae1.png)

**Comment by photonstorm** [comment]
If you're using TypeScript, the correct namespace is `MatterJS` - that is the one bundled with Phaser:

index.ts:

```typescript
import Phaser from 'phaser';

class Demo extends Phaser.Scene
{
    constructor ()
    {
        super('demo');
    }

    create ()
    {
        const bodies = MatterJS.Bodies;

        const rect = bodies.rectangle(100, 100, 400, 64);

        this.matter.world.add(rect);

        //  Or this also provides intell-sense:

        this.matter.bodies.rectangle(100, 100, 400, 64);
    }
}

const game = new Phaser.Game({
    width: 800,
    height: 600,
    scene: Demo
});
```

**Comment by TheJare** [comment]
I'm currently stumped on this one - there's an import for Phaser from "phaser", but not one for matter, so where does `MatterJS` come from in that code excerpt?

I see that `node_modules/phaser/types/` contains a `matter.d.ts` file, but I don't know how to import it correctly - or how to bring the correct matter.js dist file into my build. I'm just importing "phaser" which brings the Phaser namespace fine during typechecking, and the phaser dist into the build.

**Comment by stracker-phil** [comment]
I could solve the problem by running the following to commands:

```bash
npm uninstall phaser
npm install phaser@latest
```

after this, the matter.d.ts file was at the correct location.
