### ISSUE TITLE
After 3.10.1  the"filecomplete_image_key" event becomes to  the "filecomplete-image-key" 

### ISSUE THREAD

**Issue by Nero0** [photonstorm/phaser#5585]
## Version

* Phaser Version: 3.52.0

* Operating system: macOS

* Browser: Chrome

## Description

I tested the example "File Complete with the key" on labs.phaser.io
the complete event handler seems not work after phaser@3.10.1
By changing the "_" into "-"，its working

**Comment by photonstorm** [comment]
This example has now been fixed.
