### ISSUE TITLE
Points and lines disappear when zooming out using WebGL and pixelart

### ISSUE THREAD

**Issue by prolight14** [photonstorm/phaser#5587]
## Version
* Phaser Version: 3.52.0
* Operating system: Windows 10

## Description
When lines/points are placed on the screen zooming out causes some of them to disappear when using `Phaser.WEBGL` and `pixelArt` in game config. Also If you move the camera while zoomed out points (and possibly lines) will glitter/twinkle/blink.
The expected behavior is that the points will stay there and not disappear when zooming out and moving around. Glittering/twinkling/blinking is not expected either.

## Example Test Code
```javascript

let config = {
    type: Phaser.WEBGL,
    width: 400,
    height: 400,
    pixelArt: true,
    scale: {
        mode: Phaser.Scale.FIT,
        autoCenter: Phaser.Scale.CENTER_BOTH,
    },
    scene: {
    		preload: preload,
				create: create,
        update: update
    },
}

var game = new Phaser.Game(config);

var stars, rng;

var worldWidth = 6000;
var worldHeight = 6000;


function preload()
{
    
}

function create()
{
  	stars = this.add.graphics();
  
    this.aKey = this.input.keyboard.addKey('a');       
    this.dKey = this.input.keyboard.addKey('d');       
    this.wKey = this.input.keyboard.addKey('w');        
    this.sKey = this.input.keyboard.addKey('s');
    
   	var cam = this.cameras.main;

    cam.scrollX = worldWidth / 2;   
    cam.scrollY = worldHeight / 2;
    
    this.input.on('wheel', (pointer, currentlyOver, dx, dy) =>
    { 
      	cam.setZoom(Math.min(Math.max(cam.zoom - dy * 0.001, 0.3), 1.5));
    });
}

function update()
{
		var cam = this.cameras.main;
    
    if(this.aKey.isDown)
    {
    		cam.scrollX -= 5;
    }
		
    if(this.dKey.isDown)
    {
    		cam.scrollX += 5;
    }
    
		if(this.wKey.isDown)
    {
    		cam.scrollY -= 5;
    }
		
    if(this.sKey.isDown)
    {
    		cam.scrollY += 5;
    }
		

    stars.clear();
    stars.fillStyle(0xFFFFFF);
    
    rng = new Phaser.Math.RandomDataGenerator("3232dfc0q7");
    
    for(i = 0; i < 10000; i++)
    {
    		stars.fillRect(rng.between(0, worldWidth), rng.between(0, worldHeight), 2, 2);
    }
}
```

## Additional Information
This only happens when using `Phaser.WEBGL`

**Comment by buzzjeux** [comment]
Try this code, dont know if the right way but seem a simple workaround with pixel perfect zoom in/out :

`this.input.on('wheel', (pointer, currentlyOver, dx, dy) => {
            cam.zoomTo(Phaser.Math.RoundTo(Math.min(Math.max(cam.zoom - dy * 0.0066, 1), 4), -1), 200)
        })`

**Comment by samme** [comment]
I think that may be expected, since antialiasing is off.

I see some twinkling with CANVAS renderer too.

**Comment by prolight14** [comment]
Is there anyway to turn antialiasing on? If so what are the performance penalties? Would that mean when pixel art images are zoomed out they would appear blurry?

**Comment by photonstorm** [comment]
The camera is being zoomed to the point where you can no longer fit a 'pixel' into a 'pixel' any longer, so it's gone into sub-pixel rendering and using `pixelArt` mode means it cannot anti-alias those sub-pixels, causing the effect you see here (which also happens in Canvas). You should lock the camera zoom steps to be integer only, in order to ensure you're still rendering whole pixels.

**Comment by prolight14** [comment]
Oh that makes perfect sense. Sorry for wasting your time. It works perfectly now. Also isn't sub-pixel rendering slow?

**Comment by prolight14** [comment]
This wasn't a problem in 3.24.0. Why does it have to be this way now? Can't you change it back somehow?

"You should lock the camera zoom steps to be integer only, in order to ensure you're still rendering whole pixels."
Yeah I tried that but it only led to very stiff camera zoom movement.

Also shouldn't `this.cameras.main.setRoundPixels(true);` fix it?
