### ISSUE TITLE
Phaser return 'Cannot read property 'target' of undefined“ when trag target is destroyed'

### ISSUE THREAD

**Issue by xuanzebin** [photonstorm/phaser#5590]
## Version
* Phaser Version:3.51.0
* Operating system: macOS Mojave 10.14.4
* Browser: Chrome 88.0.4324.182

## Description
I am eight years old from japan, last day, I use phaser to create a plane game, in this game, the plane can drag and will destroy when collision with the enemy plane.
and the problem will happened when i touch the screen and drag the plane to collide the enemy, the plane destroy normally, and then, when i keep touch in screen and move the finger, the console appear a error, said "Uncaught TypeError: Cannot read property 'target' of undefined"

![image](https://user-images.githubusercontent.com/38971117/109770080-0fcb6c00-7c36-11eb-8c08-5108653ee5d7.png)

## Example Test Code
```javascript
export default class Game extends Phaser.Scene {
  constructor () {
    super('playGame')
  }

  create () {
    // ...

    // I bind the input event in here
    this.tweens.add({
      targets: this.plane,
      y: Number(this.game.config.height) - this.plane.height,
      duration: 1000,
      onComplete: () => {
        this.dragFn = (pointer: Phaser.Input.Pointer, dragX: number, dragY: number) => {
          this.plane.setPosition(dragX, dragY)
        }
        this.plane.on('drag', this.dragFn)
        this.plane.body.setCollideWorldBounds(true)
      }
    })

    // ...

    // and i destroy the plane when the plane collision with enemy bullet
    this.physics.add.overlap(this.plane, this.enemyBullets, (plane: Phaser.Types.Physics.Arcade.SpriteWithDynamicBody, enemyBullet) => {
      enemyBullet.destroy()
      this.planeDestroy(plane)
    })
  }

  planeDestroy (plane: Phaser.Types.Physics.Arcade.SpriteWithDynamicBody) {
    plane.destroy()
    const planeFrame = this.add.sprite(plane.x, plane.y, `planeExplode`)
    planeFrame.anims.play('planeBoom')
    planeFrame.once('animationcomplete', () => {
      planeFrame.destroy()
    })

    this.gameOver = true

    this.scene.start('gameOver', {
      score: this.score
    })
  }

  update (time: number) {
    // ...
  }
}
```

## Additional Information
I try to log in the phaser.js

```javascript
processDragMoveEvent: function (pointer)
    {
        // ...
        for (var i = 0; i < list.length; i++)
        {
            var gameObject = list[i];

            var input = gameObject.input;
            console.log(input)
       // ...
       }
       // ...
}
```

and i found when the error appear, it will log "undefined", I doubt it need filter the input item when it is undefined

this is my first game, i hope I can get help from my brother and sister, I would like to express my most heartfelt thanks~

**Comment by arturomf** [comment]
I'm facing the some issue... any idea?

**Comment by photonstorm** [comment]
You've destroyed the plane but haven't removed the drag event for it. This needs removing as well:

```
plane.off('drag', this.dragFn)
plane.destroy()
...
```

Destroying an object doesn't clear your _local_ reference to it, it just clears it internally, so it was trying to drag a 'dead' sprite around, hence the error.
