### ISSUE TITLE
Arcade physics: collision detection bug since 3.50.0

### ISSUE THREAD

**Issue by supertorpe** [photonstorm/phaser#5591]
## Version

* Phaser Version: 3.50.0 to 3.52.0
* Operating system: Windows 10

## Description

When a sprite reaches a certain speed, it ends up overlapping another sprite even though it has set up a collider between the two.

<img src="https://i.imgur.com/8EPqVdM.gif" />

## Example Test Code

```js
create() {
...
let dude1 = this.physics.add.sprite(100, 100);
dude1.anims.play("dude-left");
dude1.setSize(32, 42, true);
dude1.setCollideWorldBounds(true);

this.dude2 = this.physics.add.sprite(40, 140);
this.dude2.anims.play("dude-stop");
this.dude2.setSize(32, 42, true);
this.dude2.setCollideWorldBounds(true);

let dude3 = this.physics.add.sprite(180, 180);
dude3.anims.play("dude-right");
dude3.setSize(32, 42, true);
dude3.setCollideWorldBounds(true);

this.physics.add.collider(this.dude2, dude1);
this.physics.add.collider(this.dude2, dude3);
this.physics.add.collider(dude1, dude3);
...
}
update() {
  if (this.cursors.right.isDown) {
    this.dude2.anims.play("dude-right", true);
    this.dude2.setVelocityX(100);
  } else if (this.cursors.left.isDown) {
    this.dude2.anims.play("dude-left", true);
    this.dude2.setVelocityX(-100);
  } else {
    this.dude2.anims.play("dude-stop");
    this.dude2.setVelocityX(0);
  }
...
}
```
[Complete source code](https://codesandbox.io/s/zealous-goldberg-2kd2o?file=/index.html)

## Additional Information

At speed 50 the problem is not reproduced.

Phaser 3.24.1 ~~does not reproduce the problem.~~ : the problem is not reproduced in the same way. At first it seems that the sprites do not overlap, but finally they do:

<img src="https://i.imgur.com/SJBgRSu.gif"/>

**Comment by supertorpe** [comment]
I read this in the docs: https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.World.html#collide

_Arcade Physics uses the Projection Method of collision resolution and separation. While it's fast and suitable for 'arcade' style games it lacks stability when multiple objects are in close proximity or resting upon each other. The separation that stops two objects penetrating may create a new penetration against a different object. If you require a high level of stability please consider using an alternative physics system, such as Matter.js._

Maybe this is not a bug, but a limitation of arcade physics?

**Comment by photonstorm** [comment]
Sorry, going to close this issue off as it's an unfortunate limitation of Arcade Physics (and will manifest in all versions of Phaser, to some degree or other). Thankfully there are alternatives available, such as Matter, Planck or Rapier.
