### ISSUE TITLE
Touch moving event still fires when moving outside of canvas at mobile device

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5592]
## Version

* Phaser Version: 3.52.0

* Operating system: ipad

* Browser: safari

## Description

Run this [test](https://codepen.io/rexrainbow/pen/oNYyKEZ) at 

A. Desktop chrome browser, with mouse moving
    1. pointer-down start from canvas
    2. dragging mouse cursor outside of canvas
Result: The 'pointermove' event will be fired started from dragging inside canvas, stopped when mouse cursor is outside of canvas. i.e. value of `eventCounter` won't be increasing

B. ipad safari browser, with touching and the same steps 
Result: The 'pointermove' event will be still fired when touching dragging outside of canvas. value of `eventCounter` is increasing all times.

The trigger logic of 'pointermove' event seem not the same between mouse input and touch input.

**Comment by photonstorm** [comment]
Looking into this further, it appears that the `touchover` and `touchout` events are no longer implemented in any browser, which is why this part of the Touch Manager fails.

**Comment by photonstorm** [comment]
Hmm.. and I can't use `event.target` because it stays as the canvas even when you're moving well outside of it 🤔

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
