### ISSUE TITLE
Can't click to focus an input dom element since 3.53

### ISSUE THREAD

**Issue by Kosmoon** [photonstorm/phaser#5594]
Testable in this official example: [dom input example](https://phaser.io/examples/v3/view/game-objects/dom-element/form-input)
works fine on 3.52

**Comment by samme** [comment]
https://github.com/photonstorm/phaser/issues/5470 https://github.com/photonstorm/phaser/pull/5504

**Comment by samme** [comment]
I think #5504 expects you will add CSS style `pointer-events: auto` or else

```js
domElement.node.style.pointerEvents = 'auto';
```

**Comment by pizkaz** [comment]
I believe they tried to just leave it at the default value, which would be `auto`. The problem is probably that the COM container sets the property to `none`:
https://github.com/photonstorm/phaser/blob/0d1d1b0038ecd3230ef2acf48188c72d246768f8/src/dom/CreateDOMContainer.js#L28

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
