### ISSUE TITLE
Can not add a layer to another layer.

### ISSUE THREAD

**Issue by tringcooler** [photonstorm/phaser#5595]
## Version

* Phaser Version: 3.53.1

* Operating system: win7

* Browser: chrome

## Description

Add a layer to another layer cause an error:
gameObject.removeFromDisplayList is not a function

This method is called at the start of Layer#addChildCallback for reset the displayList.
But, this method is not exist.

## Example Test Code

```js
let main_layer = this.scene.add.layer();
let sub_layer = this.scene.make.layer();
main_layer.add(sub_layer);   // <- Error Here
```

## Additional Information

This code is OK in v3.52.0

**Comment by photonstorm** [comment]
Hmm, I'm happy to fix this to make it work, however, Layers were never intended to be added to other Layers, so it's a bit of fluke it ever worked at all really.

**Comment by tringcooler** [comment]
> Hmm, I'm happy to fix this to make it work, however, Layers were never intended to be added to other Layers, so it's a bit of fluke it ever worked at all really.

All right. I've removed all code that nested layers

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
