### ISSUE TITLE
Type error: 'backgroundColor' does not exist in type 'GameConfig'

### ISSUE THREAD

**Issue by eli-s-r** [photonstorm/phaser#5597]
## Version

* Phaser Version: 3.53.1

* Operating system: Linux

* Browser: N/A

## Description

After upgrading to v3.53.1 from v3.52, the TypeScript code below results in an error that `'backgroundColor' does not exist in type 'GameConfig'`. Previously the `backgroundColor` property worked fine on `GameConfig`.

## Example Test Code

```
const defaultConfig: Phaser.Types.Core.GameConfig = {
  type:            Phaser.AUTO,
  width:           800,
  height:          600,
  backgroundColor: "#fff",
  scene:           [GameScene],
};
```

## Additional Information

The complete error message is:
```
TS2322: Type '{ type: number; width: number; height: number; backgroundColor: string; physics: { default: string; arcade: { gravity: { y: number; }; }; }; scene: (typeof GoSquishGameScene)[]; dom: { createContainer: true; }; }' is not assignable to type 'GameConfig'. Object literal may only specify known properties, and 'backgroundColor' does not exist in type 'GameConfig'.
```

Thanks so much!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
