### ISSUE TITLE
[3.53.1] Duplicate Objects when added to spineContainer

### ISSUE THREAD

**Issue by spayton** [photonstorm/phaser#5599]
Phaser: V3.53.1

## Description

Objects added to a spineContainer are also added to the base display list, so appear twice.

## Example

See example ["Spine Inside Container"](http://labs.phaser.io/view.html?src=src\spine\spine%20inside%20container.js), use cursor keys to move camera and you will see there are 2 spine boys (and 2 coins).  There should only by the 1 spineboy and 1 coin that are added to the container.

If the container is set visible = false, then it's contents disappear but the extra ones remain visible.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by spayton** [comment]
yup, that's fixed it.
