### ISSUE TITLE
Text in group to renderTextre snapshotArea got text stroke

### ISSUE THREAD

**Issue by Nero0** [photonstorm/phaser#5600]
## Version

* Phaser Version: 3.53.1

* Operating system: mac

* Browser: chrome

## Additional Information

![image](https://user-images.githubusercontent.com/2063594/111061861-58a9dd00-84e0-11eb-8d23-516f5ab0cc09.png)

![image](https://user-images.githubusercontent.com/2063594/111061913-aa526780-84e0-11eb-838c-cf466c1d11d6.png)

**Comment by photonstorm** [comment]
RenderTextures use a WebGL framebuffer internally, which does not support anti-aliasing I'm afraid.
