### ISSUE TITLE
[3.53.1] WebGL warning

### ISSUE THREAD

**Issue by DavidSegura** [photonstorm/phaser#5602]
Hi guys.

## Version
* Phaser Version: 3.53.1
* Operation System: Windows 10 Home Edition
* Browser: Firefox Developer Edition 87.0b9 (64-bits) 

## Description
I have generated a new project with Pasher. In it I have a JS class that extends from Phaser.Scene and where I load 3 png images. When I run it in the Firefox browser, it throws me a warning, with the following text: WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 

## Test Code
```
export class Bootloader extends Phaser.Scene{
    constructor(){
        super( { key: "bootloader" } );
    }
    preload(){
        this.load.image("cuerpo", "../assets/body.png");
        this.load.image("comida", "../assets/food.png");
        this.load.image("tablero", "../assets/tablero.png");

        this.load.on("complete", () =>{
           console.log("complete");
        });
    }
}
```

## Additional Information
This is my configuration for Phaser. 

```

const config = {
    type: Phaser.AUTO,
    title: "Snake",
    width: 320,
    height: 180,
    parent: 'container',
    backgroundColor: '#f9ca24',
    pixelArt: true,
    physics: {
        default: "arcade",
        /*arcade: {
            gravity: {y: 100}
        }*/
    },
    scene: [ Bootloader ]
};

var game = new Phaser.Game(config);
```
Thanks for your time.

**Comment by photonstorm** [comment]
Yes, this is annoying, but there's nothing we can do about it. We use the flag properly as per the spec (as do hundreds of other WebGL libs) and Mozilla said they won't change the message: https://bugzilla.mozilla.org/show_bug.cgi?id=1400077
