### ISSUE TITLE
Duplicate properties in RTree/Rbush

### ISSUE THREAD

**Issue by vforsh** [photonstorm/phaser#5605]
## Version
3.53.1

## Description
I have been bundling the latest Phaser with the esbuild and got warnings about duplicated keys in the [rbrush prototype](https://github.com/photonstorm/phaser/blob/master/src/structs/RTree.js). The following keys are being set twice but they have different values:

- toBBox
- compareMinX
- compareMinY

**Comment by photonstorm** [comment]
This is a 3rd party lib, I didn't write it, so I can't really modify it. You could have a look to see if it's been fixed upstream, but I'd be doubtful.
