### ISSUE TITLE
DOMElements broken in 3.53+

### ISSUE THREAD

**Issue by DPMakerQB** [photonstorm/phaser#5610]
## Version

* Phaser Version: 3.53.1

* Operating system: Windows

* Browser: Chrome

## Description
DOMElements are no longer clickable / useable in 3.53.1. Even text is unselectable, not just buttons.
Please view the form input example below. It doesn't work in 3.53+ but it works in 3.52.

## Example Test Code

https://phaser.io/examples/v3/view/game-objects/dom-element/form-input

**Comment by samme** [comment]
#5594

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
