### ISSUE TITLE
Shutdown does not disconnect event handles for keys created with this.input.keyboard.addKey

### ISSUE THREAD

**Issue by veleek** [photonstorm/phaser#5611]
## Version

* Phaser Version: 3.50.1

* Operating system:

* Browser:

## Example Test Code

Calling `Stop()` on a scene does not disconnect event handlers associated with Key objects created by `this.input.keyboard.add(...)`.

```
var MyGame = {};

MyGame.Boot = function ()
{
};

MyGame.Boot.prototype.constructor = MyGame.Boot;

MyGame.Boot.prototype = {

    preload: function ()
    {
        this.load.image('rick', 'assets/pics/rick-and-morty-by-sawuinhaff-da64e7y.png');
    },

    create: function ()
    {
        this.add.image(400, 300, 'rick').setScale(0.7);

        this.input.keyboard.on('keydown-T', function() {
            console.log("Key T - Registered using keyboard.on(...)")
        }, this);

        this.input.keyboard.addKey('Y').on('down', function() {
            console.log("Key Y - Registered using keyboard.addKey(...).on(...)")
        }, this);

        this.input.once('pointerdown', function () {
            console.log("Restarting scene...");
           this.scene.restart();
        }, this);
    }

};

var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600
};

var game = new Phaser.Game(config);

game.scene.add('Boot', MyGame.Boot, true);
```

## Additional Information

It appears that the `shutdown` function in `KeyboardPlugin` calls `this.resetKeys()` which resets the state of the key (but does not call `removeAllListeners()`), and then it calls `removeAllListeners` on itself.

So I think that keyboard events created using `this.input.keyboard.on(...)` will be disconnected during Shutdown, but not keys created by `this.input.keyboard.addKey(...)`.  

Does that seem like a correct assessment of the situation?  If so I can pull together a PR to fix it.

Just for reference, there's a bit of conversation on this thread: https://github.com/photonstorm/phaser/issues/5132#issuecomment-799967946.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
