### ISSUE TITLE
Pipelines don't work with the "render" config

### ISSUE THREAD

**Issue by williammanco** [photonstorm/phaser#5613]
Hi guys, great work with Phaser, it's a  beautiful game engine.
When you try to use the pipelines but when you set the "render" in game config the post processing don't work.

It's a bug or undocumented trick?

Thanks

**Test**
https://codesandbox.io/s/gallant-almeida-mmbm4?file=/src/index.js
https://labs.phaser.io/edit.html?src=src\renderer\hue%20rotation%20pipeline.js

**Version**
Phaser: 3.5x.x (currently 3.53.1)
OS: All
Browser: All

**Comment by samme** [comment]
I guess it's a config bug, but you can move `pipeline` into `render` as well.

**Comment by photonstorm** [comment]
Hi - I've tested this against 3.53.1 and `pipeline` works inside either the game config, or the `render` object in the game config. The property is in the typedefs as well, so I'm confident this is resolved.
