### ISSUE TITLE
Typescript definitions dont match with the setup tutorial.

### ISSUE THREAD

**Issue by OSG-Proj** [photonstorm/phaser#5615]
Hello, im trying to start to develop a game, but I need to use webpack, but when I import Phaser from 'phaser and I setup the config variable and use the preload, create and update functions, and I use game.load or game.add and certain functions, I dont get the definitions for it. I saw a third party version of a tutorial of how to set this up and its totally different then how it is done originally. Maybe the typescript definitions need to be updated for use just like how it is done including the built phaser into the global scope in the html file.

**Comment by gammafp** [comment]
Could you provide us with which settings you mean? Maybe your tutorial is for V2 and not for V3

**Comment by OSG-Proj** [comment]
I looked at the phaser 3 example and saw that the code was written in a way where each scene was separated into classes extended by Phaser.Scene, so I think I noticed it now, however the official tutorial needs to be updated for phaser 3 in that case because I need to learn a little before getting started with my game

**Comment by samme** [comment]
#4669

You can do

```typescript
function create() {
  const scene: Phaser.Scene = this;

  scene.add.image(400, 300, "sky");
}
```

**Comment by gammafp** [comment]
We are working to improvement the ecosystem of Phaser.
Please if you have more doubts, I invite you to join the discord group: [https://phaser.io/community](https://phaser.io/community)

**Comment by photonstorm** [comment]
Yes, this tutorial is woefully outdated and is for V2 only. Until we replace it, please use this one in the meantime: https://ourcade.co/books/infinite-runner-phaser3
