### ISSUE TITLE
Render Texture snapshot pixel y-coordinate is inverted

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5616]
## Version

* Phaser Version: 3.53.1

## Description

Call a Render Texture's `snapshotPixel()` and read the pixel color in the callback. The color is incorrect.

## Example Test Code

<https://codepen.io/samme/pen/gOgYpdB>

Click on the red area of the color wheel. The color swatch shows cyan.

Click on the cyan area of the color wheel. The color swatch shows red.

**Comment by photonstorm** [comment]
I can confirm this works properly in 3.60 now with a Dynamic Texture or a Render Texture.
