### ISSUE TITLE
Changing parent Container creates a visual copy of a GameObject

### ISSUE THREAD

**Issue by mariogarranz** [photonstorm/phaser#5618]
## Version

* Phaser Version:

Phaser 3.53.1 

* Operating system:

MacOs

* Browser:

Chrome 89.0.4389.90

## Description

When a GameObject is moved from one Container to another one, a copy of this GameObject appears rendered at a global position of (0,0).

The expected behaviour is the GameObject to just be rendered according to its own position relative to the parent Container.

## Example Test Code

https://codepen.io/mariogarranz/pen/VwPLzjG

## Additional Information

I can confirm this issue was not present in 3.50.0.

It could be that issue #5599 is related to this problem.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/phaser-3-53-1-objects-get-duplicated-when-move-from-a-container-to-another/9167/2

**Comment by mariogarranz** [comment]
Just built and tested the latest master version and I can confirm it's fixed.

Thanks a lot for the quick response.
