### ISSUE TITLE
Animation nextFrame: function (component) frame null

### ISSUE THREAD

**Issue by fenrir1990** [photonstorm/phaser#5620]
google translate :)

Phaser 3.53.1 Windows 10 Chrome  89.0.4389.90

/src/animations/Animation.js#L537

```
    nextFrame: function (component)
    {
        var frame = component.currentFrame;

        //  TODO: Add frame skip support

        if (frame.isLast)
```
console:
Uncaught TypeError: Cannot read property 'isLast' of null

because component.currentFrame is null

This happens when a large number of animated sprites are created and deleted. Several hundred sprites on the scene at the same time. An animation error occurs on deleted sprites.

**Comment by fenrir1990** [comment]
If write "if (frame == null) return;" the error no longer occurs, but it might not be the right approach.

**Comment by fenrir1990** [comment]
The hundreds of sprites that are constantly being created and removed in the scene are of course not the default engine mode. But I would like that, for example, with a large number of players in an online game, the fps only decreases, and the game does not crash with an error.

**Comment by photonstorm** [comment]
The quantity of sprites won't make any difference to this error. I need to know _how_ you are deleting them, as that is causing the error, not the number of them.

**Comment by fenrir1990** [comment]
remove:

```
cargo.setActive(false);
cargo.removeAll(true);
cargo.destroy();
```

the class to be removed:

```
var cargo = new Cargo(this, cargos[id]);

class Cargo extends Phaser.GameObjects.Container {
    constructor(scene, data) {
        super(scene, data.x, data.y);
...
        if (this.equipment.type == 'minerals') {
            var anim_config = {
                key: 'minerals_cargo_anim',
                frames: scene.anims.generateFrameNumbers('minerals_cargo', {
                    start: 0,
                    end: 50,
                    first: 0
                }),
                frameRate: 20,
                repeat: -1
            };
            scene.anims.create(anim_config);
            this.cargo = scene.add.sprite(0, 0, 'minerals_cargo');
            this.cargo.play('minerals_cargo_anim');
        }
...
```

**Comment by photonstorm** [comment]
_when_ is this being called? I suspect it's not part of the Phaser game loop, but outside of it.

**Comment by photonstorm** [comment]
Also, you should really, really be pooling and recycling these Game Objects and not destroying them all the time. Something should only really be destroyed when the Scene ends.

**Comment by fenrir1990** [comment]
```
        socket.on('capture', function (data) {
            if (this.cargos[data.capture_id] == null) {
                return;
            }
            var cargo = this.cargos[data.capture_id];
            var unit = this.units[data.unit_id];

            this.tweens.add({
                targets: cargo,
                duration: 1000,
                x: data.x,
                y: data.y,
                scaleX: 0.5,
                scaleY: 0.5,
                onComplete: get_cargo.bind(this)
            });

            function get_cargo() {
                cargo.setActive(false);
                cargo.removeAll(true);
                cargo.destroy();
                delete this.cargos[unit.capture_id];
            }

        }.bind(this));
```

**Comment by Aveyder** [comment]
@photonstorm I'm getting this error too, when doing something like this:

```
mySprite.on("animationcomplete", () => {
            mySprite.destroy();
});
```

Not sure I'm doing this right. But I guess my problem here is `skipMissedFrames` functionality. When this is the `frame.isLast === true`, an `"animationcomplete"` event is fired, as a callback the my sprite is destroyed. But then execution of `AnimationState#update` is continued and the logic for `skipMissedFrames` is invoked, that's where we get this: `Uncaught TypeError: Cannot read property 'isLast' of null`.

**Comment by fenrir1990** [comment]
No error occurs when skipMissedFrames: false

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
