### ISSUE TITLE
`add.text` renders with wrong y-coordinate

### ISSUE THREAD

**Issue by michaelmcleodnz** [photonstorm/phaser#5625]
## Version

* Phaser Version: 
3.53.1

* Operating system:
Windows 10

* Browser:
Firefox 86.0.1

## Description

`this.add.text(0, 0, 'Text')` renders the text about halfway down the canvas on Firefox.

## Example Test Code

e.g.,
https://labs.phaser.io/edit.html?src=src/scenes/ui%20scene.js&v=3.53.1
This issue happens each time the page is refreshed, but somehow fixes itself when the 'Run Code' button is pressed.

It also happens consistently with the code in the [Making your first game](http://phaser.io/tutorials/making-your-first-phaser-3-game/part1) tutorial.

## Additional Information

Happens in both WebGL mode and Canvas mode.

![image](https://user-images.githubusercontent.com/43872775/112620960-0bd5e700-8e8e-11eb-92da-03fd97cffc37.png)

**Comment by photonstorm** [comment]
Just updated Firefox to v84 on my Mac and cannot replicate this:

![image](https://user-images.githubusercontent.com/164476/112625596-11e4ad00-8e27-11eb-9d02-d05ebe6acc36.png)

Do you have any security plugins installed? Or settings that would prevent it from being able to scan a canvas? As that is what Phaser does internally - it writes the text to a canvas and then scans the pixels to get the font height from it. If this doesn't return sensible value, you'd likely see what you're seeing here.  However, this doesn't appear to be the _default_ case for Firefox, at least not on Mac OS (will test on Windows 10 later today)

**Comment by telinc1** [comment]
If it's any use, this was [brought up on the forums a few days ago](https://phaser.discourse.group/t/text-aligment-bug-on-linux/9145?u=telinc1), where it *worked* on Firefox 86.0.1 on Windows 10, but was broken elsewhere.

Considering it (supposedly) [breaks on Brave and Tor](https://phaser.discourse.group/t/text-aligment-bug-on-linux/9145/3?u=telinc1), I also suspect it's a security flag/plugin, but haven't been able to confirm anything.

**Comment by michaelmcleodnz** [comment]
Sorry about that, I can confirm that if I turn off the extension "DuckDuckGo Privacy Essentials", the text renders in the correct place.
I have also found that this issue actually happens on any browser where "DuckDuckGo Privacy Essentials" is enabled.
The extension doesn't report that it has blocked anything, but it is clearly the culprit because everything renders correctly when I disable it.
The site https://coli.prushka.fr/ mentioned on the forums is another example of this happening.

**Comment by telinc1** [comment]
I checked the extension. [It messes with the canvas API](https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/c2506e16cdfbdd9f0ea5401014922920e88f6524/shared/js/content-scope/fingerprint.js#L80), specifically `getImageData`. This is probably what breaks text rendering. Unless you whitelist the game's site, I don't think there's anything you can do about it.

**Comment by michaelmcleodnz** [comment]
Yeah, I'm personally fine with this issue now that I know how to fix it.

From the [blame](https://github.com/duckduckgo/duckduckgo-privacy-extension/blame/c2506e16cdfbdd9f0ea5401014922920e88f6524/shared/js/content-scope/fingerprint.js#L80) and their [comments on a recent issue](https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/574#issuecomment-802976104), it looks like they just added this in the last month as part of 'fingerprint protection', and they might even fix it so that this works correctly in the future. I would raise an issue there, but I'm not sure exactly how to describe it.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/text-positions-in-chrome-out-of-whack/9042/5

**Comment by photonstorm** [comment]
Thanks for updating me with your findings. Going to close this as I don't believe it's possible (or, indeed, or responsibility) to handle this Phaser-side, sorry. You could likely avoid it entirely by making use of the Text Metrics option in Phaser, so it skips the canvas image scan entirely.

**Comment by muzzwood** [comment]
I was getting the same issue. Can also confirm disabling DuckDuckGo Privacy Essentials extension fixed it.
Pop_OS! 20.10, Firefox 87.0

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/game-does-not-display-correctly-when-published/10039/6
