### ISSUE TITLE
DOM gameobject prevents input events on other gameobjects

### ISSUE THREAD

**Issue by sacharobarts** [photonstorm/phaser#5628]
## Version
* Phaser Version: 3.54.0
* Operating system: Win10

## Description

Creating a DOM gameobject prevents 'drag' or 'pointerover' events from firing on other gameobjects like they should. This can be seen in the example project here:
https://labs.phaser.io/view.html?src=src%5Cgame%20objects%5Cdom%20element%5Cinput%20test.js
...switching to an older phaser version (v3.52.0) shows the correct functionality (can both enter text and drag cards)

## Additional Information

It looks like 3.52.0 was the last version where both the DOM objects and other gameobjects responded to input correctly.
Thanks.

**Comment by FloodGames** [comment]
I hope it's posible to fix both the DOM object and dragging.

He probably just put .style.pointerEvents = "auto" and hence destroyed all dragging in phaser 3.54

if you want to add dragging to something:
```
setInteractive({
      draggable: true,
      cursor: "grab",
      hitArea: new Phaser.Geom.Rectangle( -100,-100,200,200),
      hitAreaCallback: Phaser.Geom.Rectangle.Contains,
    })
```

**Comment by photonstorm** [comment]
Yes, it appears that #5470 and the resulting PR #5504 has broken a lot, so it's time to revert it all back to how it was before when it worked fine.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
