### ISSUE TITLE
Setting a P2 body to static produces unexpected results.

### ISSUE THREAD

**Issue by abeisgoat** [photonstorm/phaser#563]
Hopefully this isn't my own inexperience with Phaser/P2, but I'm getting werid behavior with 2.0 when I set a P2 body to static.

Test it by opening the P2 > Collision Groups example and adding the line

`panda.body.static = true;`

on line 44. 

All my Pandas will display only in the top left and seem to have no physics properties.

**Comment by McFarts** [comment]
@photonstorm Where is 3?

**Comment by photonstorm** [comment]
It's a bitwise operator, so there is no 3.
