### ISSUE TITLE
How to get my custom Mesh Object Rendering in Phase 3.5

### ISSUE THREAD

**Issue by kestrelm** [photonstorm/phaser#5630]
## Version

3.5

Windows 10

## Description

I am the owner of the Creature Animation Tool ( https://creature.kestrelmoon.com/ ) I am trying to port my Creature Phaser plugin to the new Phase 3.5. I have managed ( as far as I can tell ) to fix all warnings/syntax errors. ( no warnings/errors in the browser console ) **However, I am getting a blank screen ( no warnings or errors at all ) and nothing seems to be rendering.**

***Previously before Phase 3.5, my plugin worked for Phaser 3.x. With the new 3.5 release, it is now broken so I am trying to fix it.***

## My Core Plugin Code
I have my code here:
https://github.com/kestrelm/Creature_WebGL/tree/Phase3_5_Alpha/Phaser3

In particular, my Phaser 3.5 rendering object is specified here:
https://github.com/kestrelm/Creature_WebGL/blob/Phase3_5_Alpha/Phaser3/CreaturePackPhaser3Obj.js

I have chosen to make **CreaturePackObj** inherit from **Phaser.Class** , and then calling the base class to initialize it like so:

```
        Phaser.GameObjects.Mesh.call(
            this,
            scene,
            x,
            y,
            texture_key,
            null,
            render_pts,
            render_uvs,
            indices,
            false,
            [],
            create_colors,
            create_alphas
        );    
```

Is this the correct way of doing it? I am passing the **frame** as a **null**. Is this OK?

For updating the mesh at each **tick**, I am doing the following:
```
    preUpdate: function (time, delta)
    {
        this.pack_renderer.stepTime(delta * this.speed);
        this.pack_renderer.syncRenderData();

        indices = this.pack_data.indices;
        render_pts = this.pack_renderer.render_points;
        render_uvs = this.pack_renderer.render_uvs;
        render_colors = this.pack_renderer.render_colors;
        
        var pLen = render_pts.length / 2;
        for(var i = 0; i < pLen; i++)
        {
            var cVertex = this.vertices[i];
            cVertex.x = render_pts[i * 2];
            cVertex.y = -render_pts[i * 2 + 1];

            cVertex.u = render_uvs[i * 2];
            cVertex.v = render_uvs[i * 2 + 1];
            
            var r = render_colors[i * 4];
            var g = render_colors[i * 4 + 1];
            var b = render_colors[i * 4 + 2];
            cVertex.color = this.getPackRGBA(r, g, b, 1);

            cVertex.alpha = render_colors[i * 4 + 3];
        }                     
    }
```
Again is this still valid? When I put a breakpoint for this function in debug it is triggered so I assume it should be doing something correct?

### Plugin registration

I tried to follow the pattern in the Mesh examples and wrote some registration code below:

```
Phaser.GameObjects.GameObjectCreator.register('CreaturePackObj', function (config, addToScene)
{
    if (config === undefined) { config = {}; }

    var x = Phaser.Utils.Objects.GetValue(config, 'x', 0);
    var y = Phaser.Utils.Objects.GetValue(config, 'y', 0);
    var texture_key = Phaser.Utils.Objects.GetAdvancedValue(config, 'texture_key', null);
    var byte_data_in = Phaser.Utils.Objects.GetAdvancedValue(config, 'byte_data_in', null);

    var creature_char = new CreaturePackObj(this.scene, x, y, byte_data_in, texture_key);

    if (addToScene !== undefined)
    {
        config.add = addToScene;
    }

    Phaser.GameObjects.BuildGameObject(this.scene, creature_char, config);

    if(!config.add)
    {
        this.updateList.add(creature_char);
    }

    return creature_char;
});

if (typeof WEBGL_RENDERER)
{
    Phaser.GameObjects.GameObjectFactory.register('CreaturePackObj', function (config)
    {
        if (config === undefined) { config = {}; }
        var x = Phaser.Utils.Objects.GetValue(config, 'x', 0);
        var y = Phaser.Utils.Objects.GetValue(config, 'y', 0);
        var texture_key = Phaser.Utils.Objects.GetAdvancedValue(config, 'texture_key', null);
        var byte_data_in = Phaser.Utils.Objects.GetAdvancedValue(config, 'byte_data_in', null);
    
        var new_obj = new CreaturePackObj(this.scene, x, y, byte_data_in, texture_key);
        return this.displayList.add(new_obj);
    });
}
```
Is this still  the correct way for registration?

## How I am using it
I am calling my new Creature object from here:
https://github.com/kestrelm/Creature_WebGL/blob/Phase3_5_Alpha/Phaser3/Phaser3BasicSample.html

In particular, I am instantiating the Creature meshes like so:
```
    function create ()
    {
        this.add.text(10, 0, 'CreaturePack Runtimes for Phaser 3', { fontFamily: '"Roboto Condensed"', fontSize: 32, color: '#FFFF00'  });
        this.cameras.main.backgroundColor.setTo(50,50,50);

        creature_char = this.add.CreaturePackObj({
            byte_data_in: this.cache.binary.get('char'),
//            texture_key: 'texture',
            texture_key: '__WHITE',
            x: 300,
            y: 300
        });
        creature_char.modelScale.x = 15;
        creature_char.modelScale.y = 15;
    }
```

I will appreciate any tips on how to get this working since I really want to get Creature support for Phaser 3.5. As I mentioned before, it was previously working before Phaser 3.5 ( Phase 3.x ) but now it's broken with the latest release.

Thanks!

**Comment by photonstorm** [comment]
I noticed you tweeted saying this was now ready for 3.50: https://twitter.com/KestrelmMoon/status/1376391922051248138 so have you resolved it?

**Comment by kestrelm** [comment]
Hello yes, I have resolved it with an alternate method. I suppose it should work for now. Closing this thanks.
