### ISSUE TITLE
Game swallowing input events from DOM inputs outside of a specified parent

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [photonstorm/phaser#5635]
## Version

* Phaser Version:
v3.22.0-FB
* Operating system:
n/a
* Browser:
n/a -- reproduced on Chrome and Firefox

## Description

The 404 error page on codecademy.com uses a Phaser game which adds keyboard shortcuts on letters such as `b` and `p`. That causes a bug in the header search:

1. Click the top-right magnifying glass icon in the header
2. Type in a shortcut letter such as `p` to that search -> it does not get added to the input, but is triggered on the game
3. Type in a non-shortcut letter such as `a` to that search -> the input behaves as expected

![Accidentally launching 40Phaser by typing 'p' into the header search](https://user-images.githubusercontent.com/3335181/113175703-b39a3e80-9219-11eb-996f-d2a3494f480f.gif)

## Example Test Code

Game source: https://github.com/Codecademy/40Phaser
Example usage: https://www.codecademy.com/errors/404

## Additional Information

I apologize if what I'm looking for here is actually doable and I've just missed the documentation on it. I tried searching around for event propagation, limiting to DOM events, etc. This _seems_ like a bug report but I'm not familiar enough with Phaser to be sure! 😅 

https://github.com/photonstorm/phaser/blob/v3.22.0/src/scale/ScaleManager.js#L607 -> https://github.com/photonstorm/phaser/blob/v3.22.0/src/dom/GetTarget.js#L26 seems to indicate that the parent should be allowed to be the string ID of the container, which is what the page uses now with the `<div id="phaser-container">`.

Edit: oh, and this is not a case of forgetting to set `preventDefault`: we still want it to be fired on events captured in the game's container. Just not events captured _outside_ the game's container.

**Comment by samme** [comment]
I think this is expected. One solution is to call `stopPropagation()` on `keydown` and `keyup` events from the search field; another is to [change Phaser's keyboard event target](https://codepen.io/samme/pen/zYNdeop).

**Comment by JoshuaKGoldberg** [comment]
> `stopPropagation()`

Well, this is embarrassing: I could have sworn I tried that out but had no luck. It does work. That makes sense. Thanks for the response, and sorry for the spam!
