### ISSUE TITLE
'scene.add.existing' TS definition does not allow adding a Layer

### ISSUE THREAD

**Issue by michal-bures** [photonstorm/phaser#5642]
## Version
* Phaser Version: 3.54

## Description
This code produces a typescript compiler error:
```typescript
export class MyScene extends Scene {
    create() {
        const myLayer = new Phaser.GameObjects.Layer()
        this.add.existing(myLayer)
    }
}
```

The error:
```
Argument of type 'Layer' is not assignable to parameter of type 'GameObject | Group'.
```

Makes sense, as `Layer` is not a `GameObject`, so I guess the `existing()` method on `GameObjectFactory` should now take `GameObject | Group | Layer`, right?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by michal-bures** [comment]
Finaly got around to test it on a build from master, it works :+1:, thanks.
