### ISSUE TITLE
How to get draw calls num from WebGLRenderer In Phaser

### ISSUE THREAD

**Issue by actionmoon** [photonstorm/phaser#5648]
I wanted to make a basic panel with FPS and Draw Calls, so I can quickly evaluate which scenes needs to be optimized.

**Comment by halilcakar** [comment]
Hi @actionmoon, 

Is this example usefull for you? https://labs.phaser.io/edit.html?src=src\renderer\webgl%20info.js :)

**Comment by samme** [comment]
https://spector.babylonjs.com

**Comment by actionmoon** [comment]
@halilcakar it's very cool, but it does not include real-time rendering data

**Comment by photonstorm** [comment]
SpectorGL is the correct way to do this. Please install it and get familiar with how it works, you can even inject extra data into it from your game code. This kind of functionality will never be built into Phaser directly, as tools like this are far more powerful.
