### ISSUE TITLE
[3.54] Typo on description of AnimationManager.addMix()

### ISSUE THREAD

**Issue by trynx** [photonstorm/phaser#5649]
## Version

* Phaser Version: 3.54

## Description

Small typo in the description of the method ` AnimationManager.addMix()`

![image](https://user-images.githubusercontent.com/25723003/113712098-5fe29600-96ee-11eb-9787-c392eec84fd2.png)

Should be `priority`.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
