### ISSUE TITLE
Wrong positioning of text label on Macbook (Catalina 10.15.7) Chrome (89)

### ISSUE THREAD

**Issue by neu5** [photonstorm/phaser#5650]
## Version

* Phaser Version: 3.54.0

* Operating system: macOS Catalina 10.15.7

* Browser: Chrome Version 89.0.4389.114 (Official Build) (x86_64)

## Description

Text should be positioned in the middle of the ball but it is positioned below the ball.

## Example Test Code

The bug is visible at phaser examples:
https://www.phaser.io/examples/v3/view/game-objects/container/text-and-sprite-test

## Additional Information

I noticed that the bug is present only on Chrome on macOS. It works fine on Firefox, Safari on macOS. Also it works fine on Android Chrome/Firefox.
![image](https://user-images.githubusercontent.com/980955/113997636-9f2cf600-9858-11eb-8dde-399ee3452e0c.png)

**Comment by telinc1** [comment]
Could be the same as #5625.

**Comment by neu5** [comment]
@telinc1 yes, I'm using DuckDuckGo and it's causing the problem! Thanks.
