### ISSUE TITLE
Problems with old and most recents version in this tutorial

### ISSUE THREAD

**Issue by AnimadrawFr** [photonstorm/phaser#5654]
Hi, i try to work with this tutorial : https://www.codeandweb.com/physicseditor/tutorials/how-to-create-physics-shapes-for-phaser-3-and-matterjs but that created with Phaser 3.10.

This tutorial doesn't work with old or most recent version of phaser. 
An idea ?

**Comment by photonstorm** [comment]
Although we didn't write this tutorial I can see nothing in it that will stop it from working in the most recent version of Phaser.

You can find it running in the Phaser 3 Examples here: http://labs.phaser.io/view.html?src=src%5Cphysics%5Cmatterjs%5Cadvanced%20shape%20creation.js

If you look at the source you'll find it's exactly the same other than a small change to use the new `alignBounds` method.
