### ISSUE TITLE
Scene getChildren TypeScript definition is not right

### ISSUE THREAD

**Issue by Vidminas** [photonstorm/phaser#5665]
## Version

* Phaser Version: 3.52.0

* Operating system: Irrelevant

* Browser: Irrelevant

## Description

The docs for `scene.getChildren()` say that one can specify optional arguments for a property and a value to filter children by. One of the examples is the property "visible" and the value "true". But the TypeScript types define the second parameter type as `Phaser.GameObjects.GameObject | undefined` which does not allow a boolean value. It should probably be defined as `any` to work with all the possible values that could be set on properties.

## Example Test Code

```ts
console.log(scene.children.getAll("visible", true));
```

## Additional Information

```
TypeScript error in C:/Users/Vidminas/GitHub/fitw-client/src/game/components/ModalDialog.ts(39,50):
Argument of type 'true' is not assignable to parameter of type 'GameObject | undefined'.  TS2345   

    37 |     dialog.getElement("background").setInteractive();
    38 |
  > 39 |     console.log(scene.children.getAll("visible", true));
       |                                                  ^
    40 |
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
