### ISSUE TITLE
Cannot resume game ?

### ISSUE THREAD

**Issue by GaelGuegan** [photonstorm/phaser#5668]
Hello,

I am making my first game using phaser, and I want to put a play/pause button. I am able to trigger the pause but unable to set the resume, it is like the event cannot be triggered when we are in pause. (I have already look in google without finding clear answer)

Here a extract of code:
 ```
    state = this.add.sprite(100, 100, 'state').setInteractive();
    state.on('pointerdown', function () {
        console.log("hello ");
        this.scene.scene.pause();
   }
```
The log is not call the second time.

Then I would like to add something like this.
```
if( this.scene.scene.isActive()) {
         this.scene.scene.pause();
         music.pause();
         state.setTexture('state', 1);
} else {
       this.scene.scene.resume();
       music.resume();
       state.setTexture('state', 0);
}
```

Can someone tell me how to make a play/oause button ?
Thanks.

PS: ihave only one scene.

**Comment by halilcakar** [comment]
Hello @GaelGuegan,

I believe you can create 2 scenes in this matter.

One is a UI Scene that can make the logic for resume, pause.

And the other one is your game scene.

You can check here for topic about this: https://phaser.discourse.group/search?q=multiple%20scene

**Comment by GaelGuegan** [comment]
Ok I will take a look. Too bad that we need to do multiple scenes for such a simple thing ...

I was expecting something nice, clear and simple.

Thank you for your precious help.
