### ISSUE TITLE
(TypeScript) Cannot find name 'GameConfig'

### ISSUE THREAD

**Issue by BlueStaggo** [photonstorm/phaser#5669]
## Version

* Phaser Version: 3.54.0

* Operating system: Windows 10 1909 x64

## Description

I was following a tutorial to set up a Phaser project from [this article](https://www.freecodecamp.org/news/how-to-build-a-simple-game-in-the-browser-with-phaser-3-and-typescript-bdc94719135/) and I found this piece of code:
```typescript
import "phaser";
const config: GameConfig = {
  title: "Starfall",
  width: 800,
  height: 600,
  parent: "game"
  backgroundColor: "#18216D"
};
export class StarfallGame extends Phaser.Game {
  constructor(config: GameConfig) {
    super(config);
  }
}
window.onload = () => {
  var game = new StarfallGame(config);
};
```
When I copied and pasted this code into VSCode (1.55.2) and hovered over the word `GameConfig`, this is what I saw:
![image](https://user-images.githubusercontent.com/71090710/115988205-7161e400-a5b0-11eb-82dd-c8d8eee49a09.png)
The only way to fix this issue is by replaceing `GameConfig` with `Phaser.Types.Core.GameConfig`
![image](https://user-images.githubusercontent.com/71090710/115988249-99e9de00-a5b0-11eb-9911-cffc6ad90692.png)
This is not just VSCode or ESLint messing up, it's an actual compiler error.
Is this intended? I doubt that it's a bug, as I haven't seen many other issues about this. For now, I'll just use Phaser.Types.Core.GameConfig.

## Example Test Code

```typescript
import "phaser";

const config: GameConfig = {
    title: "Phaser Game",
    width: 800,
    height: 600,
    backgroundColor: "#18216D"
};

export class MyGame extends Phaser.Game {
    constructor(config: GameConfig) {
        super(config);
    }
}

window.onload = () => {
    var game = new MyGame(config);
};
```

## Additional Information

None ¯\\\_(ツ)\_/¯

**Comment by photonstorm** [comment]
`Phaser.Types.Core.GameConfig` is the correct type to use. You can tell this by looking [at the docs](https://newdocs.phaser.io/docs/3.54.0/Phaser.Game) and seeing the data type of the Game constructor configuration object. 

The tutorial ought to be updated to use it, really, but that isn't something we have any control over.
