### ISSUE TITLE
Shader uniforms not updated when using an array of values

### ISSUE THREAD

**Issue by telinc1** [photonstorm/phaser#5670]
## Version
* Phaser Version: 3.54

## Description
When updating a shader's uniform using arrays of values (e.g. `set4fv` instead of `set4f`, or any of the matrix methods), the uniform will not actually be updated. This causes #5660 (and perhaps other issues?).

All uniform setters, both on `WebGLPipeline`s and `WebGLShader`s, call the lower-level [`setUniform2/3/4`](https://github.com/photonstorm/phaser/blob/6735f7e88e462ef6584f85dfba9f24310cc61f60/src/renderer/webgl/WebGLShader.js#L520) methods to update the values. These methods check for identity between the old and the new values, which is a good optimization when using scalar values. For arrays, however, if the same object is passed in, the uniform isn't updated even if the values in the array are the different.

This has been an issue since 3.50. I'd assumed this was intended, but I'm no longer sure considering Phaser gets confused by it, too. In the case of #5660, a [`setMatrix3fv` call](https://github.com/photonstorm/phaser/blob/6735f7e88e462ef6584f85dfba9f24310cc61f60/src/renderer/webgl/pipelines/LightPipeline.js#L256) gets ignored.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
