### ISSUE TITLE
Using WebP as tilemap causes misaligned tiles.

### ISSUE THREAD

**Issue by JasonHoku** [photonstorm/phaser#5671]
## Version
3.54.0

* Operating system:
Win 10 19042.928 x64

* Browser:
Chrome + Firefox tested

## Description

Webp tilemaps do not map individual tile locations correctly.

The second image on my map is pulling pixels from my first.

## Additional Information

WebP can reduce browser image sizes by drastic amounts. Most of my Phaser assets are in WebP and it would be ideal to continue using WebP, but PNG works fine too for now :)

Thank you Phaser Community!

**Comment by JasonHoku** [comment]
I think I can add on to this report by including that this might be potentially caused by a tile being indivisible by the screen dimensions, though somehow it does seem that WebP reacts differently to dimensions than png.

**Comment by JasonHoku** [comment]
Okay, I can confirm this is purely a webp issue:


The same graphic, tilemapped from PNG:
![image](https://user-images.githubusercontent.com/6715569/116939168-96d19c00-ac07-11eb-90f2-5769b6102c75.png)

as WebP:

![image](https://user-images.githubusercontent.com/6715569/116939101-77d30a00-ac07-11eb-8f99-7e808b0ce006.png)

**Comment by photonstorm** [comment]
Nothing inside of Phaser treats WebP files any differently from PNG files. It actually has no concept of them differing at all.

As you've not provided any code or map files I can't help but wonder if this isn't Tiled exporting different json based on the two formats? Failing that, try it in a different browser perhaps. There's nothing inside of Phaser I can actually change to capture this, and my gut tells me there's no way the tiles will have different resolutions based on format alone, so this is likely coming from somewhere external.

**Comment by JasonHoku** [comment]
> Nothing inside of Phaser treats WebP files any differently from PNG files. It actually has no concept of the file format at all.
> 
> As you've not provided any code or map files I can't help but wonder if this isn't Tiled exporting different json based on the two formats? Failing that, try it in a different browser perhaps. There's nothing inside of Phaser I can actually change to capture this, and my gut tells me there's no way the tiles will have different resolutions based on format alone, so this is likely coming from somewhere external.

Sorry for the late response, my tiles aren't generated from Tiled, but from an algo I scripted.  Also I did mention I confirmed this occurs in both Firefox and chrome.

I'll see if I can reproduce the experience in a codesandbox here for us shortly. Thanks for all the hard work here. 🙇🏼‍♂️
