### ISSUE TITLE
CanvasTexture doesn’t work in Safari

### ISSUE THREAD

**Issue by andrew-medvedev** [photonstorm/phaser#5672]
## Version
* Phaser Version: 3.54.0
* Operating system: mac os big sur 11.0.1 (20B29)
* Browser: Safari 14.0.1 (16610.2.11.51.8)

## Description
I need to modify texture so the only way I found is to generate CanvasTexture and move pixel by pixel from just Texture(with some mods it doesn't matter). So I faced the problem of rendering sprite with CanvasTexture in Safari (also I rechecked in Brave(chromium) and it works). It just doesn't appear.

## Example Test Code
```
'use strict';

var Scene = require('phaser').Scene;

class BootScene extends Scene{
    constructor(){
        super({ key: 'BootScene' });
    }
    preload(){
        
    }
    create(){
        var Sprite = require('phaser').GameObjects.Sprite;

        var __CT__ = this.textures.createCanvas('ct', 25, 25);
        for(let i = 0 ; i < 25 ; i++){
            for(let j = 0 ; j < 25 ; j++){
                console.log(` ~ SETTIN 255-128-64`);
                __CT__.setPixel(i, j, 255, 128, 64);
                let _pxl = __CT__.getPixel(i, j);
                console.log(` ~ GETTIN ${_pxl.r}-${_pxl.g}-${_pxl.b}`);
            }
        }
        __CT__.refresh();

        var s2 = new Sprite(this, 200, 200, 'ct');
        this.add.existing(s2);
        s2.setDisplaySize(200, 100);
    }
}

module.exports = BootScene;
```

## Additional Information
Here is what I see in Safari:
<img width="665" alt="fa8b60d7663a7b16852490065f894923" src="https://user-images.githubusercontent.com/7358595/115994531-d0dfe400-a5f0-11eb-8c77-604fb1346079.png">

And Brave:
<img width="936" alt="9be908c484b49bae75e0e242cdf0e2df" src="https://user-images.githubusercontent.com/7358595/115994534-d4736b00-a5f0-11eb-9e0b-fd17dd9d7995.png">

**Comment by photonstorm** [comment]
I know this is over a year old, but have just re-tested against 3.60 and 3.55 on macOS Safari, and the CanvasTexture examples in the Labs are working fine.
