### ISSUE TITLE
timeline onUpdate bug

### ISSUE THREAD

**Issue by helloyoucan** [photonstorm/phaser#5674]
## Version

* Phaser Version: v3.55.0-dev

* Operating system: window 10

* Browser:  Google Chrome 89.0.4389.128

## Description

I want to log tween progress in  onUpdate , but from the second tween log the progress is  only  1.

## Example Test Code

```javascript
const line = this.tweens.timeline({});
    line.add({
      targets: { a: 0 },
      a: 1,
      onUpdate(tween: Phaser.Tweens.Tween){
        console.log(tween.progress); // log 0-1
      },
    });
    line.add({
      targets: { b: 0 },
      b: 1,
      onUpdate(tween: Phaser.Tweens.Tween){
        console.log(tween.progress); // only log 1
      },
    });
    line.play()
```

**Comment by photonstorm** [comment]
Just to say that Timelines have been removed from Phaser 3.60 and replaced with the new Tween Chain system, which enables perfectly sequenced playback. Although this is a breaking change, I feel it was worth making for the benefits it brings (such as fixing issues like this!)
