### ISSUE TITLE
Fix GameObjects.Rectangle not being added to the scene

### ISSUE THREAD

**Issue by RichardJECooke** [photonstorm/phaser#5678]
## Version
3.53.1
* Phaser Version:
* Operating system:
WSL
* Browser:
* Chrome

## Description

The documentation for GameObjects.Rectangle says ` @param scene The Scene to which this Game Object belongs. A Game Object can only belong to one Scene at a time.`

but this code

```js
const blackRectangle = new Phaser.GameObjects.Rectangle(this, 0, 0, this.map.widthInPixels, this.map.heightInPixels, 0, 1); 
```

does *not* display the rectangle in the scene!

**Comment by photonstorm** [comment]
This is correct behaviour as the Scene isn't the display list, so just adding any Game Object to a Scene isn't enough on its own. It needs adding to the Display List too (and sometimes the Update List as well).

scene.add.existing(this) is one way to do it.
