### ISSUE TITLE
Fix RenderTexture origin not drawing at (0,0)

### ISSUE THREAD

**Issue by RichardJECooke** [photonstorm/phaser#5679]
## Version
3.53.1
* Phaser Version:
* Operating system:
WSL
* Browser:
* Chrome

## Description

The documentation for RenderTexture says `@param x The horizontal position of this Game Object in the world.
             * @param y The vertical position of this Game Object in the world.`

but the following code draws the texture at the origin of the scene (0,0). If I instead specify the actual coordinates (0,0) in the constructor then the texture is drawn in the middle of the scene!

```js
const blackRectangle = new Phaser.GameObjects.Rectangle(this, 0, 0, this.map.widthInPixels, this.map.heightInPixels, 0, 1);
const renderTexture = this.add.renderTexture(-this.map.widthInPixels/2, -this.map.heightInPixels/2, this.map.widthInPixels*2, this.map.heightInPixels*2); 
renderTexture.draw(blackRectangle, this.map.widthInPixels, this.map.heightInPixels);
```

**Comment by RichardJECooke** [comment]
I have the same error with `RenderTexture.erase` too, have to do stuff like this to get it to work:

```js
	updateFogOfWar()
	{
		const eraser = new Phaser.GameObjects.Rectangle(this, 0, 0, 100, 100, 65535, 1); //fillcolor, alpha
		this.fogOfWar.erase(eraser, this.player.body.x + this.map.widthInPixels/2, this.player.body.y + this.map.heightInPixels/2);
		eraser.destroy();
	};
```

**Comment by photonstorm** [comment]
This is working exactly as it should do.

The Rectangle Game Object has a default origin of 0.5 x 0.5 (as do nearly all Game Objects), so whatever coordinate you pass to `RenderTexture.draw` will denote the _center_ of where the Rectangle is drawn. If you want to change this to be the top-left, then call `setOrigin(0, 0)` on the Rectangle. Then the coordinate you draw it at will be the top-left instead.

The RenderTexture itself has a default origin of 0x0, so the top-left. This only impacts the placement of the Render Texture on-screen, not its drawable area.

Unrelated, but it's a really bad idea to create a Rectangle and then destroy it again in the same method like this. Just create it once and then re-use it every time the FoW updates. Creating Game Objects is expensive. Destroying them equally so. Do it sparingly.
