### ISSUE TITLE
Timeline calcDuration incorrect if tweens overlap in time

### ISSUE THREAD

**Issue by ghclark2** [photonstorm/phaser#5681]
## Version

* Phaser Version: 3.54

* Operating system: Windows

* Browser: All

## Description

The duration of a timeline as calculated by calcDuration seems to be wrong if tweens are not sequential. For example in the phaser 3 [absolute offset example](https://labs.phaser.io/edit.html?src=src/tweens/timelines/absolute%20offsets.js&v=3.54.0) the timeline duration should be 9000ms as each tween is 3000ms and the last one is started with an offset of 6000ms. However it is calculated to be 12000ms which is the sum of all the tween durations even though some of them overlap.

Many thanks for your time and effort!

## Example Test Code

`var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('block', 'assets/sprites/block.png');
}

function create ()
{
    var marker = this.add.image(100, 100, 'block').setAlpha(0.3);
    var image = this.add.image(100, 100, 'block');

    var timeline = this.tweens.timeline({

        targets: image,
        ease: 'Linear',
        duration: 3000,

        tweens: [{
            x: 600
        },
        {
            y: 500,
            offset: 2000
        },
        {
            x: 100,
            offset: 4000
        },
        {
            y: 100,
            offset: 6000
        }]

    });
    timeline.calcDuration()
    console.log(timeline.duration)
}`

**Comment by photonstorm** [comment]
Just to say that Timelines have been removed from Phaser 3.60 and replaced with the new Tween Chain system, which enables perfectly sequenced playback. Although this is a breaking change, I feel it was worth making for the benefits it brings (such as fixing issues like this!)
