### ISSUE TITLE
Web Audio does not work on iOS Safari

### ISSUE THREAD

**Issue by albert-gonzalez** [photonstorm/phaser#5685]
## Version

* 3.54.0

* iOs

* Safari

## Description

Using Safari in iOS, web audio does not work. When you run phaser it throws an error like this:

```
Error: Audio key "theKey" missing from cache
```

If you disable the audio with enabling the noAudio config, it works. You also can enable disableWebAudio, but this causes other issues.

## Example Test Code

```js
new Phaser.Game({
  type: Phaser.AUTO,
  physics: {
    default: "arcade",
  },
  audio: {
    noAudio: true // if this is true, it works, with audio enabled it fails
  },
  scene: titleSceneConfig,
});
```

## Additional Information

In this thread you can see other people having the same issue: https://phaser.discourse.group/t/audio-works-on-web-but-not-ios/3677

Thank you for this awesome project!

Best regards!

**Comment by photonstorm** [comment]
That error means you've tried to load an audio format that iOS doesn't support.

Load a correct one, like an m4a, and it definitely works.

**Comment by albert-gonzalez** [comment]
I am using ogg, which works in all other browsers. I'll try with m4a and let you know the result.

Thanks for the quick response!

**Comment by photonstorm** [comment]
iOS doesn't support ogg files.

**Comment by albert-gonzalez** [comment]
You will always learn something new 🙂. I'll convert my files to m4a and try again. I close the issue!

Thank you for your support!

**Comment by photonstorm** [comment]
You should provide your audio in 2, ideally 3 formats: m4a, ogg and mp3, then you provide an array of these 3 file types to the Phaser Audio Loader and it'll pick whichever is the first one it can play for that device.

**Comment by albert-gonzalez** [comment]
Great, I'll do that. Thank you for the tip!

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/audio-works-on-web-but-not-ios/3677/9

**Comment by Dercetech** [comment]
Hi,
I'm currently trying to write a proper "ios + capacitor" audio loader.

@photonstorm , I don't know why, but this is only when the mp3 are loaded from ios AND served by ios (using capacitor to build the package) that "my" issue happens. Using fetch instead of xhr solves this though. Maybe I can book 2h of your time via the support plan so we can work this out together?

**Comment by Dercetech** [comment]
> I used ogg and mp3 as fallback, and as you said, now works perfectly in all browsers, including iPhone. Thank you again!!!

Albert, do you package your game as an iOs game, or do you access the game via safari/chrome on the iphone?

**Comment by albert-gonzalez** [comment]
Hi @Dercetech 

I package the game using Parcel and access it via Safari and other browsers. I guess in your case is a problem with capacitor.

Best regards!

**Comment by Dercetech** [comment]
Hi @albert-gonzalez , ok thanks for the update. Can parcel create a native build?

I added my workaround in the forum thread, for the capacitor/ios users. I needs to be replaced by a proper MultiFile implementation to handle this properly. Not proud of my approach but I need to wrap up a demo. Code:

https://phaser.discourse.group/t/audio-works-on-web-but-not-ios/3677/11

**Comment by albert-gonzalez** [comment]
Hi again @Dercetech

I think Parcel is a bundler for the web only. I am developing a little game for my site, so I don't need a native build. I saw your post in the forum and I thought that they could be related, but now I see that is another issue, sorry for the inconvenience.

Best regards!

**Comment by Dercetech** [comment]
Hi @albert-gonzalez  good to know, I'll check it out. Parcel seems to be like a nice tool. No being sorry, it's me to thank you for sharing the possible link between our issues!

**Comment by Dercetech** [comment]
Hi @consolenaut , it's a blocking issue to me too, I've not really fixed it but found a way around this issue. Check my forum post ([link](https://phaser.discourse.group/t/audio-works-on-web-but-not-ios/3677/11)), I use the "fetch" (instead of the underlying XHR in the File / MultiFile loader base classes of Phaser). Then, before allowing the update() loop to run, you must listen to the scene.sound.on("decoded", ...) events (keeping track of what is already loaded. It's a bit tedious, but seems effective. I'll try to write a real Phaser loader but need more time and practice.

**Comment by consolenaut** [comment]
@photonstorm Should we raise a new issue for this? I think the original issue in this thread with the wrong format is resolved but more have been tagged on at the bottom.

**Comment by Dercetech** [comment]
sidenote: I haven't been able to create a proper loader for this. If anyone has a template that allows overriding the default hooks used by the XHR loader, please let me know.

**Comment by consolenaut** [comment]
I've tracked it down to the line giving us grief - looks like in the File class in the loader checks if its getting a local file by string matching on "file://" here - adding "capacitor://" in there too completely fixes the issue. 

https://github.com/photonstorm/phaser/blob/699e81e008456da0d0c7245b4a1d72cd5bb31d67/src/loader/File.js#L313

@photonstorm if I did a PR to extend `xhr.responseURL.indexOf('file://') === 0` to `xhr.responseURL.indexOf('file://') === 0 || xhr.responseURL.indexOf('capacitor://') === 0` would it be accepted, or is there a better way to handle this?

**Comment by Dercetech** [comment]
good job @consolenaut !

**Comment by consolenaut** [comment]
Raised another PR to address a related issue loading other file types, I think this'll be the last of the capacitor-related stuff @Dercetech @photonstorm
