### ISSUE TITLE
FPS is going down in peerjs + phaser3

### ISSUE THREAD

**Issue by smart0120** [photonstorm/phaser#5690]
## Version

* Phaser Version: 3.24.0

* Operating system: Windows 10

* Browser: Chrome 90.0

## Description

I used phaser3 in the live video stream website.
When the user connects the other, the fps is going down from 60 to 30.
But the user disconnects again, the fps is going up to 60.

I can't figure out what's the problem.

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.
