### ISSUE TITLE
Tilemaps Physics Optimization - New algorithms

### ISSUE THREAD

**Issue by Gurigraphics** [photonstorm/phaser#5691]
## Illustration
In the example below, rendering occurs normally.
![image](https://i.imgur.com/d7pKQkM.gif)

In this other example, lag occurs.
![image](https://i.imgur.com/m9UQLtz.gif)
The positioning of the sprite cannot follow the update positioning of the collision box.

***What is the difference between the two examples?***
The only difference is that in the second example, there are ***several tiles missing***. 
This means that the current algorithm tries to process all possible collisions.

## Optimization Performance

One way for Optimization Performance is to eliminate unnecessary or expendable processing.

## Necessary collisions
The necessary collisions are close to the actors.
For example: A "box activate" can activate collisions.
![image]( https://imgur.com/c23BZaI.png )

This "box activate" is nothing more than the distance between "actors" and "tiles".

Deactivated tiles work like normal sprites.
The array list physics updates remove this tiles to max performance.
Like Sorted Arrays
http://jsfiddle.net/cwgbxss5/1/

## New Algorithm Options

Phaser supports physics systems: Arcade Physics, P2, Ninja Physics, Box2D, Matter,  etc.

Phaser also could have native options for better tilemap update algorithms.
Like Sorted Arrays, Quad-tree, Octree, etc.

**Comment by photonstorm** [comment]
Your demo is for Phaser 2. This repo is for Phaser 3.

Phaser 3 does _not_ include 'empty' tiles for consideration when running collision checks against them. They are definitely skipped.

Even Phaser 2 has sorted-arrays and quadtree support built-in now, although not in the very, very old version you've used in your demo, which is v2.2.0. That version is over 7 years old. Phaser 2 is currently on v2.17.0.

**Comment by Gurigraphics** [comment]
The examples are Phaser 3.0

![image](https://imgur.com/fwIbMur.png)

The performance problem that I highlighted occurs in Phaser 3.0.
The sorted arrays that are Phaser 2.0, but just an example of the algorithm that can be used in any version.

The way I'm trying to get better performance is this:
```js
  var Xpos = playerCollision.x
  var Ypos = playerCollision.y
  var tile = blocks.getTileAtWorldXY(Xpos, Ypos, true)
    
  //Colision down
  if( tile && tile.index != -1 && tile.pixelY == Math.round(Ypos/32)*32){   
      playerCollision.y = Math.round(Ypos/32)*32
      playerCollision.setVelocityY(0)
      jump = true
  }
  ```
In my tests this already works better than the default system.
Now  missing the other sides of the collision.

**Comment by photonstorm** [comment]
You didn't show a reproducible issue, just a gif and then an example of something from a 7 year old version of Phaser. There is nothing here I can actually act upon. If you're already developing something that works better for _your use case_ then I suggest you stick with it and implement it in your own build.

**Comment by Gurigraphics** [comment]
To reproduce, just have a character that jump, and a "Chess" of tiles and holes under it. As in the images.

But, I realized that lag only occurs when resizing the screen multiple times. 
Then the update saturates and FPS stay 10, 20.

But, nobody resizes the browser, and nobody ever complained about it, so that's not a major problem.

Thnks.
