### ISSUE TITLE
The pointermove event handler does not work when game config dom createContainer is true.

### ISSUE THREAD

**Issue by izure1** [photonstorm/phaser#5692]
## Version

* Phaser Version: 3.54.0

* Operating system: Windows 10

* Browser: Chrome 90.0.4430.93

## Description

I apologize that my English is not my first language.

If set the createContainer property to true in game config, some pointer event handlers will not work.
In my case, 'pointermove', 'pointerwheel' events did not work.

## Example Test Code

```
const config = {
  type: Phaser.AUTO,
  parent: "game",
  autoCenter: true, 
  scale: {
    parent: 'game',
    width: '100%',
    height: '100%'
  },
  dom: {
    createContainer: true
  },
  scene: {
    create: create
  }
};
var game = new Phaser.Game(config);

function create() {
    this.input.on(Phaser.Input.Events.POINTER_MOVE, function(pointer){
        console.log('move')
    })
    this.input.on(Phaser.Input.Events.POINTER_WHEEL, function(pointer){
        console.log('wheel')
    })
}
```

**Comment by photonstorm** [comment]
Hi - Yes, this is a known issue in 3.54 and has been fixed already in the master branch. If you checkout this repo and do `npm run build` it will build you a version of 3.55 in which the fix is applied, which you can use until 3.55 is published fully.
