### ISSUE TITLE
`Tilemap.createFromObjects` unexpected behavior for large images, tile data

### ISSUE THREAD

**Issue by lackhand** [photonstorm/phaser#5697]
## Version

* Phaser Version: HEAD (v3.55.0-dev-FB)

* Operating system: n/a; Mac OSX

* Browser:

## Description

Expected: calling `someTilemap.createFromObjects('someLayer', {gid:someId})` creates approximately the same map as seen in Tiled: ![Screen Shot 2021-05-13 at 4 15 38 PM](https://user-images.githubusercontent.com/207026/118182029-80e18980-b406-11eb-9580-1fc9a836f160.png)
.
Actual: Because it doesn't automatically link tile offsets to texture frames, you get a bunch of missing images: 
![Screen Shot 2021-05-13 at 3 31 27 PM](https://user-images.githubusercontent.com/207026/118182098-99ea3a80-b406-11eb-849d-b93d476dc83e.png)

This can be repaired by the user by calling `setTexture` (or `setFrame`) on the returned objects which is cumbersome...
BUT THEN:
Expected: calling `setTexture` on the objects returned from `createFromObjects` will create approximately the same map as seen in Tiled.
Actual: Object has size ratio with 32 *squared* -- a 4px object is drawn at .5 px, an 8px object at 2 px, 16px @ 8px, 32px @ 1:1, 64px drawn at 128px: 
![Screen Shot 2021-05-13 at 3 36 59 PM](https://user-images.githubusercontent.com/207026/118182187-b1c1be80-b406-11eb-83de-b6fe920f20d9.png)

This is due to Tilemap internally setting the objects to the empty frame (@ 32 pixels), which sets the scale (via `setDisplayWidth` and `Height`; when the image is then later set, the scale is not cleared.

Also:
Expected: `type` of object will be visible to phaser and useful for creating instances (since `type` sounds a lot like `class` to me!)
Actual: `createFromObjects` doesn't support a `type` selector. Even if it did, because `type` can be set either on the `object` itself or on the tile to which the object `gid` refers, though Tiled treats those as equivalent (objects inherit the `type` of their tile in the UI!), since it's not inlined in the exported data, Phaser doesn't refer to it. (you can see this in the tiled UX screenshot where `64` is of type `huge`, contrast with the data in the included zip (see below)...

These are somewhat related; in order to use default image information from tiled, phaser would need to follow the object gid back to the tileset. It doesn't currently.

## Example Test Code

```js
class extends Phaser.Scene {
      constructor() {
        super({
          key: "Game",
          physics: { arcade: { debug: true } }
        });
      }
      preload() {
        for (let [size, url] of imgs) {
          this.load.image(`${size}px`, url);
        }
        this.load.image('scale', scale);
        this.load.tilemapTiledJSON('map', map);
      }
      create() {
        this.add.image(64, 0, 'scale').setOrigin(0, 0);

        let map = this.add.tilemap('map');
        for (let [size, _] of imgs) {
          const name = `${size}px`;
          for (let obj of map.createFromObjects('objects', {
           gid:map.addTilesetImage(name).firstgid, 
          })) {
            // If omitted, no texture used *even though there's potentially a known value from the tilemap*.
            obj.setTexture(name);
            console.log(name, 'at', obj.x, obj.y, obj.displayWidth, obj.displayWidth);
          }
        }
      }
    }
```
Note: also attached as a zip so that you can also use my beau~tiful images: [example.zip](https://github.com/photonstorm/phaser/files/6474877/example.zip)

## Additional Information

I have a solution in flight which will reference this bug.

**Comment by samme** [comment]
This is expected, though.

You get a missing image because there's no `key` given to the method or found on the tilemap object. And incorrect dimensions for the same reason.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
