### ISSUE TITLE
correctly handle redirected requests

### ISSUE THREAD

**Issue by jonnytest1** [photonstorm/phaser#5700]
at https://github.com/photonstorm/phaser/blob/5c8ecbcf999e6f328d21884e877c9e5935d2d350/src/loader/File.js#L468
and similar eventQueue emits 
the value of this.xhrLoader.responseURL should be added to the event data

not the keys though or it may break event listeners

**Comment by samme** [comment]
I think you can find it in [FILE_LOAD](https://newdocs.phaser.io/docs/3.55.0/Phaser.Loader.Events.FILE_LOAD).

**Comment by photonstorm** [comment]
The `data` parameter contains the xhr response. The `FILE_LOAD` should be used if you need to obtain the actual File instance itself, from which you can then get anything extra you need like this.
