### ISSUE TITLE
FPS Cap Bug - Reading from Monitor 1 Always

### ISSUE THREAD

**Issue by JasonHoku** [photonstorm/phaser#5705]
## Version
3.54

## Operating system:
Win 10.0.19042 x64

## Description
If using a secondary monitor with a greater FPS, the primary monitor Hz will be  inherited to Phaser.

## Example Test Code
This is hardware related.

## Additional Information
On 144hz Monitor, It was 144 before swapping primary/secondaries.

![image](https://user-images.githubusercontent.com/6715569/118576401-25740c00-b724-11eb-802e-353630e8735e.png)

**Comment by JasonHoku** [comment]
![image](https://user-images.githubusercontent.com/6715569/119594517-a613b780-bd77-11eb-8f7a-e0bd3747503c.png)


I think you might be right, perhaps we could turn this focus to a bug report to Chrome & FF or WebGL then?

**Comment by photonstorm** [comment]
Phaser has no concept of how fast your monitor is, all it can do is run at the rate the browser allows Request Animation Frame to run. If, for whatever reason, the browser throttles that rate (which it does, often) then sadly your game pays the price. I think you've likely found another browser edge case here.

I would _expect_ the browser to adjust to the frequency of the current monitor it is on. How it handles you tearing off a tab and moving just a tab to another monitor, who knows though - in that case, I assume it will retain the raf of the monitor the browser is running in. Either way, we have no actual control over this sadly.

If you do report this (I would say it's a raf issue, not a WebGL one) then please post a tracking link to this issue.
