### ISSUE TITLE
RenderTexture snapshotFramebuffer cannot exceed the size of the drawingBuffer

### ISSUE THREAD

**Issue by teng-z** [photonstorm/phaser#5707]
## Version

* Phaser Version: 3.23.0

* Operating system: macOS

* Browser: Google Chrome

## Description

I have a renderTexture whose size exceeds Canvas. The width and height of the snapshot cannot exceed the drawingBuffer.

I tried to remove Math.min from snapshotArea. Get the effect I want, is there any hidden danger?
Is there a better solution?

**Comment by photonstorm** [comment]
Agreed, this is fine to do here - I've moved the check to the snapshot function if the source is a frame buffer.
