### ISSUE TITLE
[Idea] Thoughts on using GitHub Actions for testing

### ISSUE THREAD

**Issue by karbassi** [photonstorm/phaser#5715]
Hello @photonstorm, based on the little issue on #5713, I was thinking it would be a good idea to have GitHub run `npm run ts` or other test automatically on all PRs and report back any issues. This may help with the burden of you manually having to check all PRs.

I've implemented many GitHub Actions on projects and could help with the process if you see fit.

Just a thought. Would love to hear what you think.

**Comment by photonstorm** [comment]
We already use Travis for automatic build tests. However `test-ts` is run as part of the local build process, it was just such an innocuous error that it didn't flag anything there at all, so even a GitHub Action / Travis wouldn't have picked up on it. Happy to look at GH Actions for v4, but will stick with Travis for v3.
