### ISSUE TITLE
Feature suggestion : add 'destroyFromScene' parameter back

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5716]
When restart, or shutdown a scene, `list.shutdown()` will be called, and destroy all game objects in [this loop](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/DisplayList.js#L236-L239)

1. It will pass a [`true`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/DisplayList.js#L238) value to destroy method.  It is a `destroyFromScene` parameter as I remembered, but no [destroy](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/GameObject.js#L825) method in each kind of game object has the parameter.
2. I would like to pass `destroyFromScene` value to [`DESTROY` event](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/GameObject.js#L838). Use case: sometime game objects will be destroyed together. It is fine in normal game object destroying, except destroying from scene, the [while loop](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/DisplayList.js#L236-L239) will be broken if removing item inside this loop. A `destroyFromScene` value can be used in this case.

I can add this 'destroyFromScene' parameter to GameObject.destroy method, if this request is accepted.

**Comment by photonstorm** [comment]
Sure, that makes sense to me.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
