### ISSUE TITLE
[TypeScript] Namespace 'Phaser.Types.Renderer.WebGL' has no exported member 'WebGLPipelineUniformsConfig'

### ISSUE THREAD

**Issue by PhaserEditor2D** [photonstorm/phaser#5718]
## Version

* Phaser Version: 3.55.0

* Operating system: Linux

* Browser: -

## Description

There is an error in the TypeScript definitions:

`Namespace 'Phaser.Types.Renderer.WebGL' has no exported member 'WebGLPipelineUniformsConfig'`

![image](https://user-images.githubusercontent.com/12187299/119677369-aa3de480-be0c-11eb-979a-45ea95e616d4.png)

I don't find any file with the `WebGLPipelineUniformsConfig` name in the Phaser code.

**Comment by PhaserEditor2D** [comment]
I think the problem is here: https://github.com/photonstorm/phaser/blob/5552079c9d23a883e10bef7318f6b924c9538c96/src/renderer/webgl/WebGLShader.js#L139

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by PhaserEditor2D** [comment]
Great! That's fixed. But I get another error now :(

```

../../../types/phaser.d.ts(10112,13): error TS2416: Property 'destroy' in type 'GameObject' is not assignable to the same property in base type 'EventEmitter'.
  Type '(fromScene: boolean) => void' is not assignable to type '() => void'.

```

**Comment by PhaserEditor2D** [comment]
I think if the `fromScene` parameter is set as optional then it fixes the error.
