### ISSUE TITLE
Using M4V extension instead of mp4 breaks loading

### ISSUE THREAD

**Issue by patrickkeenan** [photonstorm/phaser#5719]
## Version
* Phaser Version: 3.55.1
* Operating system: Windows
* Browser: Chrome

## Description

Exporting from a video tool (VLC/Handbrake) makes a m4v file extension. By adding the "mp4" extension, loading works, but with the original extension it does not.

## To Reproduce
* Use the video loader
* Use the m4v extension instead of mp4

## Result
* Does not load

**Comment by photonstorm** [comment]
Although `video/m4v` isn't a standard mime type, I have added support for `x-m4v` which is an Apple-specific edge-case. It will still only work if the server is configured to correctly deliver these files, though.
