### ISSUE TITLE
Arc fills are incorrect

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5720]
## Version

* Phaser Version: 3.55.1

## Description

Add to a scene a Text object and Arc with color fill.

The arcs appear filled with warped text.

## Example Test Code

https://codepen.io/samme/pen/YzZxGyM

**Comment by photonstorm** [comment]
I quite like that :)

But yeah, I know what that is. Will fix tomorrow.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
