### ISSUE TITLE
hover event Phaser.Input.Events.GAMEOBJECT_OVER is broken since 3.54.0

### ISSUE THREAD

**Issue by MrZakos** [photonstorm/phaser#5721]
Hi , 

I tried on 3.54.0 and on 3.55.2,
currently I'm using version 3.52.0 where it works fine,
tested on Chrome

![image](https://user-images.githubusercontent.com/999613/120107637-7f37f580-c16a-11eb-9fee-7c38e79764a9.png)

**Comment by photonstorm** [comment]
Show more code please, because it's clearly working here: https://labs.phaser.io/view.html?src=src\input\game%20object\over%20and%20out%20events.js

So there has to be something specific to how you're implementing it to cause it to break.

**Comment by MrZakos** [comment]
version 3.55.2
hmm it seems to work now  for weirdly unknown reason 
I changed from
`type: Phaser.AUTO,`
to
`  type: Phaser.CANVAS,`
then back to 
`type: Phaser.AUTO,`
and it works... so don't now what the problem was
