### ISSUE TITLE
Documentation filter WEBGL-CANVAS

### ISSUE THREAD

**Issue by monteiz** [photonstorm/phaser#5724]
Since some methods/members are exclusivity of WEBGL or CANVAS, it would be great to define a flag for each method/member, and create a filter in the documentation in order to hide features that are not available in the chosen context (WEBGL or CANVAS).

**Comment by photonstorm** [comment]
Hi - you cannot filter by it, but we already show in the docs if the function is WebGL only. For example: https://newdocs.phaser.io/docs/3.55.2/Phaser.GameObjects.Components.Tint#setTint (see the badge before the function name)

We use a JSDoc tag `@webgl` to control this, which you can see in the source code.
