### ISSUE TITLE
Pause and stop scene do not work during preload

### ISSUE THREAD

**Issue by prakol16** [photonstorm/phaser#5726]
## Version

* Phaser Version: 3.55.2

* Operating system: Ubuntu

* Browser: any

## Description

When calling `scene.pause` on a scene during its preload:

**Expected**: Either the loading pauses, or the loading continues but `create` is not called until the scene is resumed, or the loading continues and `create` is called, but after the `create` call, the scene goes back to being paused, and `update` is not called.

**Actual**: The pause is ignored.
<hr />

When calling `scene.stop` on a scene during its preload:

**Expected**: The scene stops, and even if the loading finishes, `create` should not be called.

**Actual**: `create` is called which usually results in an error. However, this can lead to unpredictable behavior. For example, if you add a timer in `create`, suddenly, if you ever restart the scene, there will be two timers, since the old timer was added after the scene was destroyed.

## Example Test Code

Example code: https://codepen.io/prakol16/pen/dyvmXJP

Note that this uses the `rexAwait` loader plugin, but that is just so that I can simulate a long-loading file. The bug is there even when loading ordinary files.

## Solutions
Probably something like checking if the scene has been destroyed/paused before calling `create` in `loadComplete` in `SceneManager.js`.

**Comment by samme** [comment]
Pausing or stopping a `LOADING` scene does actually stop it from **queueing** files. You can see this if you add `this.scene.pause()` to `preload()` in [loader/game load config](https://labs.phaser.io/view.html?src=src\loader\game%20load%20config.js).

**Comment by photonstorm** [comment]
I've been working on this today and although I'm not sure you'll like the conclusion, at least it now makes it consistent and throws a sensible warning at you. But I've made it that you cannot pause a Scene that isn't in an active running state, which includes a Scene that is currently loading. Once it is past that, you can pause and resume at will (you can also pause as part of `create`, that is fine). Trying to do it when a Scene is already paused, or destroyed, or loading, will throw a console warning. This is now implemented in 3.60 in the main branch.

**Comment by samme** [comment]
I think sleep should probably be changed in the same manner — meaning you can sleep only a creating, running, or paused scene.

**Comment by photonstorm** [comment]
Agreed, done.

**Comment by samme** [comment]
I reproduced the second problem with

    scene.start('demo').stop('demo6').start('demo');

(only when the 'demo' scene loads assets).

The events fired are

0. start 
0. ready 
0. shutdown 
0. start 
0. ready 
0. create 
0. create

Maybe Phaser should remove the `loadComplete` and `payloadComplete` event handlers when shutting down a scene.
