### ISSUE TITLE
Phaser 3 Geometry Mask Examples not working on Firefox

### ISSUE THREAD

**Issue by Overld** [photonstorm/phaser#5727]
* Phaser Version 3.2.0 to 3.55.2.  Tested a lot of versions and they don't work

* Operating system: Android

* Browser: Firefox.  Tested with version 88.1.4

## Description
Image Masks not working when using fillRect.  Examples using arc do appear to be working.

Running the Phaser 3 Examples from https://labs.phaser.io/.  I picked Home -> Display -> Masks -> Geometry Mask -> Image Mask.  Also Multiple Image Mask also doesn't work.  It just shows a black screen.  The mask is not working.  The examples Image Mask Arc, and Image Mask Multiple Circles do appear to be working.

This issue appears to only be affecting Android devices running Firefox.  Running Edge or Chrome works fine on the Android device.

The code to test the issue was provided on https://labs.phaser.io/.  It can be found under Home -> Display -> Masks -> Geometry Mask.  There are a few examples to test such as Image Mask, and Multiple Image Mask.

**Comment by gammafp** [comment]
Work for me, have you try to move the mouse over the canvas?

**Comment by Overld** [comment]
I am using a Lenovo Tablet, so there is no mouse.  I moved my finger all over the screen and nothing changed.  The examples with the circles did move.  In a game I wrote, I modified it to draw four lines and fill the rectangle it also works.  The fillRect doesn't appear to work.

**Comment by Ewanretor** [comment]
> I am using a Lenovo Tablet, so there is no mouse. I moved my finger all over the screen and nothing changed. The examples with the circles did move. In a game I wrote, I modified it to draw four lines and fill the rectangle it also works. The fillRect doesn't appear to work.

I used to use firefox before updating my chrome version. Your firefox might be outdated check for updates.

**Comment by photonstorm** [comment]
Works fine in Firefox 94.0.1 on Windows 10 and macOS, so going to close this off. Please ensure your version is up to date.
