### ISSUE TITLE
No camera postrender event with Phaser.CANVAS

### ISSUE THREAD

**Issue by ddanushkin** [photonstorm/phaser#5729]
## Version
* Phaser Version: tested on 3.54 and 3.55.2

## Description
No camera postrender event with Phaser.CANVAS.
If switch to Phaser.WEBGL than event fires.

## Example Test Code
[Example](https://codepen.io/ddanushkin/pen/poeLVMo)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
