### ISSUE TITLE
Group create method should return created gameobject

### ISSUE THREAD

**Issue by marcusx2** [photonstorm/phaser#5733]
There is a group.create method. When I create an object in the group, I can't get the created object. This is just common practice, that when you create something you return what was created. I am aware of the createCallback, but don't want to use it on this case. Or at least change this so that I can pass the callback as the last parameter of the create method, instead of having a global createCallback

Right now this is a global callback with just one parameter, it's horrible. So I have additional arguments that can't be passed to the callback.

Please just make the function return the created gameobject or allow me to pass the callback with any number of parameters I want as the last argument of the create method.

**Comment by halilcakar** [comment]
Hi @marcusx2, 

Can you please provide a code example to make it clear?

And If I understand it correctly [here](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/group/Group.js#L288) is the `create` method of Group.js. It's actually returning the children it's created.

Also see [`createMultiple`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/group/Group.js#L330) also returns the children array that created. Also same applies for [`createFromConfig`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/group/Group.js#L367) method.

If I understand the problem please try to explain so we can check togerher =)

**Comment by marcusx2** [comment]
Oh nevermind...you are correct it already does this...

**Comment by photonstorm** [comment]
I'm not a fan of the tone of the language used in this issue. Had you actually checked the documentation (or even tested it out) you would have seen it _does_ return the child that was created.

Please word future issues more carefully.

**Comment by marcusx2** [comment]
You are correct, I apologize. I checked the documentation before, but I couldn't see the return value until the other guys mentioned it. Guess I'm too tired. Thanks!
