### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by roberthook823** [photonstorm/phaser#5734]
Although Phaser 3.55.2 has been released, it is less than the previous version 3.24.1 in terms of rendering speed. It was previously submitted as a bug but has not been resolved.
Although it has been updated functionally, running many gameObjects reduces rendering speed compared to 3.24.1 and causes the mobile device to heat up when running. So I'm still using 3.24.1 for the most part. Please upgrade the rendering speed. In my case, rendering speed is the first in mobile webGL games.

**Comment by photonstorm** [comment]
The way in which 3.24 and 3.55.2 render is now exactly the same. It's literally the same pipeline, plus a few additions.

I'm closing this issue as there is no evidence given, no code sample, no metrics, no comparison of the two versions. In short, nothing of any actual use we can use.
