### ISSUE TITLE
Is there a way to customize the collider?

### ISSUE THREAD

**Issue by x-wk** [photonstorm/phaser#5738]
I want do this:
`
class MyCollider extends Collider{
    // ...
    update() {
        setTimeout(()=>{
            super.update();
        }, 30);
    }
    // ...
}
`

**Comment by photonstorm** [comment]
You can extend any Phaser Class, although putting a `setTimeout` in a Physics Collider is a very wrong way to achieve what I think you're trying to do. This question isn't an issue, so please continue it on the forum or Discord.

**Comment by x-wk** [comment]
Thank you for your suggestion, I did it like this(rxjs>asyncScheduler):
```ts
      const subject = new Subject();
      const oldUpdate = collider.update;
      collider.update = () => {
         subject.next(true);
      };

      subject.pipe(
         sampleTime(27 + idx * 2)
      ).subscribe(() => {
         oldUpdate.call(collider);
      });
```
The 'World#addCollider' cannot specify a subclass.
Is it necessary for phaser to implement its own scheduler?
