### ISSUE TITLE
Tweens don't affect object's properties if they starts with underscore

### ISSUE THREAD

**Issue by necrokot** [photonstorm/phaser#5747]
## Version

* Phaser Version: 3.55.2

* Operating system: Ubuntu 18.04, KUbuntu 20.04, Windows 10

* Browser: Chrome 91.0.4472.101 (Official Build) (64-bit), Version 91.0.4472.106 (Official Build) (64-bit)

## Description

Tweens don't affect object's properties if they start with underscore.

## Example Test Code

https://codepen.io/necrokot/pen/KKWbvBV

**Comment by photonstorm** [comment]
Yes, this is a design choice and has always been there. Underscore prefixed properties are skipped in the input object.

I'll add it to the documentation to make it explicit, but the feature won't be changing itself.

**Comment by necrokot** [comment]
Oh. Ok, I understand you. But could you please give some motivation for this decision?

**Comment by photonstorm** [comment]
Because since forever an underscore has denoted a private property, which are nearly always the last things you should be tweening.

**Comment by necrokot** [comment]
Such kind of code is common in our projects: class that encapsulate some animations and provide public interface for other parts. But property `speed` is not the part of public interface and must be denoted as private. Now we denote it via JSDoc or just comments, but it is a bit obstructs a code. Have you suggestions how to do it in a proper way?
This example is very simple but it showing the idea I hope.
```javascript
// for next code assume that PHASER is reference for active scene.
class Spinner{
  constructor () {
    this.speed = 0
    this._img = PHASER.add.image(...)
    ...
  }
  spin () {
    PHASER.add.tween({
      target: this,
      speed: 100,
      duration: 1000
    })
  }
  update(t, dt) {
    this._img.x += this._speed * dt
  }
}
```

**Comment by schoening** [comment]
@necrokot if you must denote them as private you could use a pattern of ending it with an underscore `speed_`.

Why don't you incrementally switch to TypeScript or use the new JavaScript feature of private fields? You can then transpile it using babel to  remove the modern syntax (even tho evergreen browsers seem to support it)
