### ISSUE TITLE
GameConfig dom behindCanvas setting true not working

### ISSUE THREAD

**Issue by iamallenchang** [photonstorm/phaser#5749]
## Version

- Phaser Version: 3.24.1

- Operating system: macos 11.2.1

- Browser: Chrome

## Description

config setting behindCanvas ture or false, but Chrome see Elements div always over canvas

## Example Test Code

gameConfig

  ```js export default {
	type: Phaser.AUTO,
	scale: {
		parent: 'phaser-game',
		mode: Phaser.Scale.FIT,
		autoCenter: Phaser.Scale.CENTER_BOTH,
		width: GameSetting.DEFAULT_WIDTH,
		height: GameSetting.DEFAULT_HEIGHT
	},
	dom: {
		createContainer: true,
		behindCanvas: true
	},
	antialias: true,
	plugins: {
		scene: [{
			key: 'rexUI',
			plugin: RexUI,
			mapping: 'rexUI'
		}, {
			key: 'SpinePlugin',
			plugin: window.SpinePlugin,
			mapping: 'spine'
		}]
	},
	audio: {
		disableWebAudio: false
	},
	disableContextMenu: true,
	version: process.env.VERSION,
	banner: {
		hidePhaser: true
	},
	scene: [
		MainScene
	]
} 
```

## Additional Information

<img width="672" alt="截圖 2021-06-17 下午3 20 17" src="https://user-images.githubusercontent.com/65879782/122350490-d66a0280-cf7f-11eb-8226-8745a736506d.png">

if anyone has any information I would be thankful!

**Comment by photonstorm** [comment]
Sorry, yes, this is a left-over property that shouldn't be in the config. I'll remove it.

**Comment by helians11** [comment]
Phaser: 3.60.0
behindCanvas in dom is not working.
Even after setting the behindCanvas to true it is always coming on top of canvas.
Please help on this @photonstorm 

const config = {
    type: Phaser.AUTO,
    parent: 'dummy',
    scale: {
      mode: Phaser.Scale.ScaleModes.RESIZE,
      width: document.getElementById(gameConfig.id).clientWidth * window.devicePixelRatio,
      height:
        document.getElementById(gameConfig.id).clientHeight * window.devicePixelRatio,
      autoCenter: Phaser.Scale.CENTER_BOTH,
    },
    pixelArt: false,
    backgroundColor: '#fff',
    fps: { target: 60 },
    physics: {
      default: 'arcade',
      arcade: {
        gravity: { y: 200 },
      },
    },
    dom: {
      createContainer: true,
      behindCanvas: true,
    },
    audio: {
      disableWebAudio: true,
    },
    scene: [GameScene],
  };
