### ISSUE TITLE
glsl precision mediump float 

### ISSUE THREAD

**Issue by actionmoon** [photonstorm/phaser#5751]
## Version
* Phaser Version: 3.52.0+
* Operating system: Android 10
* Browser: chrome 

## Description

'precision mediump float' in Multi-vert.js & Multi-frag.js 

causes strange spots when rendering on some Android devices. 

Hope to fix it as soon as possible, or provide an interface that overloads the fragShader in MultiPipeLine to help fix this issue. 

## Additional Information

[Blue Artifacts in WEBGL on Mobile #5659](https://github.com/photonstorm/phaser/issues/5659)
[spots appear when rendering #5655](https://github.com/photonstorm/phaser/issues/5655)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
