### ISSUE TITLE
Group Sorting doesn't work in Phaser v3

### ISSUE THREAD

**Issue by Ewanretor** [photonstorm/phaser#5754]
Please i have been trying to use sorting for Groups in Phaser v3 I think it's a capable feature because v2 had it. I really need it for my project, so I have been trying to implement it using v3 and v2 code to compare.
But since v2 runs on PIXI.js it kinda confuses me, I will be glad if you can help implement it into v3 or at least explain how I can sort groups or even similarities between v2 and v3 so I can implement it myself into Phaser and I will probably present it.
Thanks.

**Comment by halilcakar** [comment]
Hi @Ewanretor, I wondered what are you using groups for?

Can you give a small example?

**Comment by samme** [comment]
You can just do

```js
group.getChildren().sort((a, b) => {/*…*/});
```

But in Phaser 3 groups and containers are distinct. If you mean depth sorting then you need a container.

**Comment by Ewanretor** [comment]
> Hi @Ewanretor, I wondered what are you using groups for?
> 
> Can you give a small example?
> 
> Also please see https://phaser.discourse.group/t/best-situations-for-groups-and-containers/9833/2 @samme's answer here :)

I'm actually trying to do a group.sort("depth") function or sort groups in a topological order

**Comment by samme** [comment]
Phaser 3 groups are not displayable and the order of group members is unrelated to rendering.

You just need to loop through the group members and call their `setDepth()` methods.

**Comment by Ewanretor** [comment]
> Phaser 3 groups are not displayable and the order of group members is unrelated to rendering.
> 
> You just need to loop through the group members and call their `setDepth()` methods.

I am already sorting my sprites, so I think I just need to sort my every member of the group to sort themselves among each other.
I actually went through the main Phaser code for hours, I obviously tried `setDepth()` but this just put sorting my sprites depth inside out.

**Comment by photonstorm** [comment]
As samme has said, `depth` is not constrained to the contents of a Group (or a Container, for that matter), so whatever solution you come up with, it's going to need to be specific to your requirements.

**Comment by Ewanretor** [comment]
> As samme has said, `depth` is not constrained to the contents of a Group (or a Container, for that matter), so whatever solution you come up with, it's going to need to be specific to your requirements.

I only requested a sort function for the group class. Phaser CE and v2 had it and containers and list class has it. I have gone through the entire source code.
When I tried solving this in Phaser v3.52 source code groups aren't an array but the children are.
I don't exactly understand how you did the sort function for the v2|CE but I only want to either know how you added it or if you can just add it for a new version release .
Or alternatively is there any way to use the list class, I actually saw the similarities with groups and a little with containers. Thank you for your time.

**Comment by photonstorm** [comment]
You can't sort the Group contents because it uses a `Set` internally to store the children and Set's cannot be sorted, they always hold their contents in insertion order.

You can sort the contents of a Container, however, using the `Container#sort` method.

**Comment by Ewanretor** [comment]
> You can't sort the Group contents because it uses a `Set` internally to store the children and Set's cannot be sorted, they always hold their contents in insertion order.
> 
> You can sort the contents of a Container, however, using the `Container#sort` method.

I now understand why I couldn't sort the group class, but how do I use `lists` in Phaser 3.
There is a list class but I don't think it is useful as there is no tutorial or example on using lists.
Please at least is there a way to use the list function.
Due to positioning containers destroys the sorting of my game objects, so I just think I would like to use lists
