### ISSUE TITLE
Documentation of callbacks for tweens and timelines inconsistent, disagrees with implementation

### ISSUE THREAD

**Issue by prakol16** [photonstorm/phaser#5755]
## Version

* Phaser Version: 3.55.2

* Operating system: Ubuntu

* Browser:

## Description

When `tween.stop()` is called, or `timeline.stop()` is called, should `onComplete` run? The documentation is inconsistent. For `tween.stop()`: 
  -  The documentation on the `callbacks` object does not specify that `onComplete` should run (https://github.com/photonstorm/phaser/blob/v3.51.0/src/tweens/tween/Tween.js#L311)
  - Other documentation (e.g. the documentation on the `setCallback` function) claims that `onComplete` should run when `tween.stop()` is called (https://github.com/photonstorm/phaser/blob/v3.51.0/src/tweens/tween/Tween.js#L982 and also https://github.com/photonstorm/phaser/blob/v3.51.0/src/tweens/tween/Tween.js#L1578).
  - In fact, there is a separate callback `onStop` which is called when `tween.stop()` is called, and `onComplete` can  be called early using `tween.complete()`. This is nice, but it is currently undocumented.

On the other hand, for `timeline.stop()`
  - The documentation only says that `onComplete` should run when `timeline.stop()` is called (https://github.com/photonstorm/phaser/blob/v3.51.0/src/tweens/Timeline.js#L238).
  - In fact, if `timeline.stop()` is called, no callback fires. There is no `onStop()` callback, nor is there a `.complete()` method.
## Example Test Code

    const text = this.add.text(10, 10, "Hello");
    let timeline = this.tweens.createTimeline({
      onComplete: () => console.log("Finished!"),
    })
    .add({
      targets: text,
      x: "+=400",
      duration: 3000,
    })
    .add({
      targets: text,
      y: "+=400",
      duration: 3000,
    })
    timeline.play();
    setTimeout(() => timeline.stop(), 1000);
    // onComplete will not be called, contrary to the claims of the documentation

## Additional Information

This is part bug, part feature request. The bug is that the documentation is wrong (or the implementation). The feature request is that Timelines and Tweens should have essentially the same interface, and in particular, timelines should also have an `onStop` callback, as well as a `.complete()` method.

**Comment by photonstorm** [comment]
This has now been fully fixed in the 3.60 Beta 10 release and all events and callbacks are correctly documented and much more featured than before.
