### ISSUE TITLE
Group vs. self collisions cause double collision callbacks

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5758]
## Version

* Phaser Version: 3.55.2 and earlier

## Description

Create an Arcade Physics group with two overlapping members. Add an overlap collider with a collision callback. The callback is called twice per collider update or world step.

The same will happen if you use a collide collider with custom separation (no separation).

It will not happen with an ordinary group or array or when the physics world `useTree` is disabled.

## Example Test Code

<https://codepen.io/samme/pen/GRmKzPE>

See failed assertion in console.

## Additional Information

I think group vs. self checks mustn't search the body tree.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
