### ISSUE TITLE
Phaser.Types.Physics.Arcade.GameObjectWIthBody should contain Phaser.Tilemap.Tile

### ISSUE THREAD

**Issue by DeweyHur** [photonstorm/phaser#5759]
## Version
* Phaser Version: 3.55.2
* Operating system: Windows 10
* Browser: Chrome

## Description

```
  Phaser.Physics.Arcade.Factory.collider(object1: Phaser.GameObjects.GameObject | Phaser.GameObjects.GameObject[] | 
  Phaser.GameObjects.Group | Phaser.GameObjects.Group[], object2: Phaser.GameObjects.GameObject | 
  Phaser.GameObjects.GameObject[] | Phaser.GameObjects.Group | Phaser.GameObjects.Group[], collideCallback?: 
  ArcadePhysicsCallback, processCallback?: ArcadePhysicsCallback, callbackContext?: any): Phaser.Physics.Arcade.Collider;

  declare type ArcadePhysicsCallback = (object1: Phaser.Types.Physics.Arcade.GameObjectWithBody, object2: Phaser.Types.Physics.Arcade.GameObjectWithBody)=>void;

  type GameObjectWithBody = Phaser.GameObjects.GameObject & {
    body: Phaser.Physics.Arcade.Body | Phaser.Physics.Arcade.StaticBody;
  };
```

The type of third/forth parameters of collider doesn't expose Tilemap.Tile even it returns that type. I confirmed if Tile object is enclosed in the callback when I add a collider between a sprite and a tilemap.

## Example Test Code

```
    const map: Phaser.Tilemaps.Tilemap = scene.make.tilemap({ key: 'tilemap' });
    const tileset: Phaser.Tilemaps.Tileset = map.addTilesetImage('istanbul', 'base_tiles');
    const entrance = map.createLayer('entrance', tileset);
    scene.physics.add.collider(sprite, entrance, (lhs, rhs) => {
        console.error('The type of rhs is Tile.');
    });
```

**Comment by netrules** [comment]
Declare it as `any` for the time being? Also, perhaps use triple single quotes (`) (and also ```js ?) to wrap your code for better formatting.

**Comment by DeweyHur** [comment]
Oh yes, that's only a typescript thing. I am avoiding this by casting to any and to tile again.

**Comment by netrules** [comment]
I don't understand your example very well, I apologize. Could you please declare more instances of this issue happening to you with a clear_er_ / visual example?

**Comment by DeweyHur** [comment]
```
const tileset: Phaser.Tilemaps.Tileset = map.addTilesetImage('istanbul', 'base_tiles');
const entrance = map.createLayer('entrance', tileset);
scene.physics.add.collider(mySquad.group, entrance, (lhs, rhs) => {
        const tile = rhs as any as Phaser.Tilemaps.Tile;
        if( 'palace' in tile.properties ) lhs.body.reset(2152,107);
        else if ( 'palaceout' in tile.properties ) lhs.body.reset(500,300);
    });

```

This is how I avoid this issue. I think adding Tile as a return type would be good.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
