### ISSUE TITLE
Phaser.Events.off - Context not working

### ISSUE THREAD

**Issue by NickHatBoecker** [photonstorm/phaser#5761]
## Version
* Phaser Version:
3.52.0
* Operating system:
MacOS Catalina
* Browser:
Firefox

## Description

Hey there,

For keyboard inputs I'm listening to the same custom events in several classes. For example, I have a global `GridControls` class, listening to `EVENT_INTERACT` in order to start my custom event manager chain. On the other hand I have a class `Textbox`, listening to the same `EVENT_INTERACT` event, in order to skip to the next textbox.

In order to stop events from stacking, I wanted to remove the listeners, whenever no textbox is shown. So I found the [off function](https://photonstorm.github.io/phaser3-docs/Phaser.Events.EventEmitter.html#off__anchor) of Phaser's EventManager and the  `context` attribute. Unfortunately this does not work for me.

Everytime I want to off the listeners of the `Textbox` class, all other listeners are also removed. So whenever a textbox is hidden, my event manager chain cannot be started again, because the listener of `GridControls` was also removed.

## Example Test Code

```js
// GridControls
constructor () {
    this.scene.events.on('EVENT_INTERACT', () => this._doInteraction(), this)
}
```

```js
// Textbox

_initEvents () {
    this._shutdownEvents()
    this.scene.events.on('EVENT_INTERACT', () => this._onInteract(), this)
}

_shutdownEvents () {
    console.log('before', this.scene.events.listeners('EVENT_INTERACT'))

    this.scene.events.off('EVENT_INTERACT', undefined, this)

    console.log('after', this.scene.events.listeners('EVENT_INTERACT'))
}
```

I can reproduce that **ALL** listeners are removed,  instead of only the context ones, with the `console.log` statements above.

I also tried the following:

```js
this.scene.events.off('EVENT_INTERACT', () => null, this)
this.scene.events.off('EVENT_INTERACT', () => this._onInteract(), this)

// Maybe with a string as context:
this.scene.events.off('EVENT_INTERACT', () => this._onInteract(), 'TextBoxPlugin')
this.scene.events.on('EVENT_INTERACT', () => this._onInteract(), 'TextBoxPlugin')
```

But nothing seems to work. Is this a bug or am I getting the `off` function wrong?
Thank you so much!

Best regards
Nick

**Comment by samme** [comment]
I think is just how `off()` works. You must pass `(event, fn)` or `(event, fn, context)`. There's no matching by `context` alone.

You can do

```js
this.scene.events.on('EVENT_INTERACT', this._doInteraction, this)
// …
this.scene.events.off('EVENT_INTERACT', this._doInteraction, this)
```

**Comment by photonstorm** [comment]
Phaser uses EventEmitter3 internally: https://github.com/primus/eventemitter3 and in order to remove a single event, you need to ensure that the event name and the callback match exactly (and optionally the context). There's no ability to remove by context. More details here: https://nodejs.org/api/events.html#events_emitter_off_eventname_listener (although be aware that Node doesn't have any event context, that's an EE3 embellishment).
