### ISSUE TITLE
Spine Plugin Cannot create with multiple game instances.

### ISSUE THREAD

**Issue by xiamidaxia** [photonstorm/phaser#5765]
## Version

* Phaser Version:  V3.55.2

* Operating system: Mac
* Browser: Chrome 91.0.4472.114

## Description

I'm developing a game editor that requires just multiple instances of phaser

![spine](https://user-images.githubusercontent.com/4162271/123919499-92332500-d9b7-11eb-943a-5f29a4d85fbb.gif)

## Example Test Code

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phaser test</title>
    <script src="http://localhost:8000/build/3.55.2.js"></script>
    <script src="http://localhost:8000/plugins/3.50.x/SpinePluginDebug.js"></script>
</head>
<style>
    canvas {
        display: inline-block;
        margin-right: 20px;
    }
</style>
<body>

</body>
<script>
    const bootScene = {
        preload() {
            this.load.spine('set1', 'http://localhost:8000/assets/spine/3.8/demos/demos.json', [
                'http://localhost:8000/assets/spine/3.8/demos/atlas1.atlas',
                'http://localhost:8000/assets/spine/3.8/demos/atlas2.atlas',
                'http://localhost:8000/assets/spine/3.8/demos/heroes.atlas'
            ], true);
        },
        create() {
            this.add.spine(200, 200, 'set1.alien').setScale(0.5);
        }
    };
    var game1 = new Phaser.Game({
        width: 400,
        height: 400,
        parent: document.body,
        plugins: {
            scene: [
                {
                    key: 'SpinePlugin',
                    plugin: SpinePlugin,
                },
            ]
        },
        scene: [bootScene]
    });
    var game2 = new Phaser.Game({
        width: 400,
        height: 400,
        parent: document.body,
        plugins: {
            scene: [
                {
                    key: 'SpinePlugin',
                    plugin: SpinePlugin,
                },
            ]
        },
        scene: [bootScene]
    });
</script>
</html>


```

## Additional Information

![image](https://user-images.githubusercontent.com/4162271/123919067-1cc75480-d9b7-11eb-8f8a-60f22a7ffcac.png)

**Comment by xiamidaxia** [comment]
![image](https://user-images.githubusercontent.com/4162271/123939622-e398df80-d9ca-11eb-8fc4-355f22c26c1c.png)

I fixed the plug-in loading problem, but found a new one

**Comment by xiamidaxia** [comment]
Share the global scene renderer make this problem.

![image](https://user-images.githubusercontent.com/4162271/123951173-177a0200-d9d7-11eb-872a-64826a22bcec.png)

**Comment by phamconganh** [comment]
i hope it will soon merged. I have the same problem

**Comment by phamconganh** [comment]
@xiamidaxia I think the PluginCache also need to be edited. Because when you removeScenePlugin, the PluginCache will remove the plugin from any active scene that are already using it
```
  /**
   * Removes a scene plugin from the Plugin Manager and Plugin Cache.
   *
   * This will not remove the plugin from any active Scenes that are already using it.
   *
   * It is up to you to remove all references to this plugin that you may hold within your game code.
   *
   * @method Phaser.Plugins.PluginManager#removeScenePlugin
   * @since 3.8.0
   *
   * @param {string} key - The key of the plugin to remove.
   */
  removeScenePlugin: function (key) {
    Remove(this.scenePlugins, key);

    PluginCache.remove(key);
  },
```

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
