### ISSUE TITLE
If Chinese is used in BitmapFont, WorDwarp does not work 

### ISSUE THREAD

**Issue by Lziang** [photonstorm/phaser#5768]
the lines will be automatically wrapped  based on the specified character found in the line，there is no space character between the two characters in the Chinese statement like in the English statement，so I use Chinese in BitmapFont, WordWarp does not work

**Comment by Lziang** [comment]
Is there a solution for Chinese line wrapping in BitmapText

**Comment by photonstorm** [comment]
Use this: https://newdocs.phaser.io/docs/3.55.2/Phaser.GameObjects.BitmapText#wordWrapCharCode
