### ISSUE TITLE
Drop event not fired if mouse has not been moved

### ISSUE THREAD

**Issue by orjandh** [photonstorm/phaser#5769]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 10

* Browser: Chrome 91

## Description

When using the drag and drop system in Phaser with distance threshold at 0, I would expect the drop event to fire if you start dragging and drop the object at the same exact location. However this does not happen if you don't move the cursor at all while dragging. A possible fix for this is to perform some of the same logic that is used in the move processing function also in the dragdown processing function.

## Example Test Code

https://codepen.io/orjandh/pen/wvdMZQX

This is an example with a draggable button and the blue square is a drop zone. To reproduce the problem click and hold down on the button without moving the cursor, then release the mouse button. The text "Dropped!" should not appear.

This is in contrast to if you drag the button around and then drop it, the text will appear.

**Comment by rexrainbow** [comment]
Add this instruction `scene.input.setPollAlways()` to poll mouse event every tick. Default behavior is detect mouse event when mouse moving or clicking/releasing.

**Comment by samme** [comment]
IMHO that's expected, because there is no drag.

**Comment by orjandh** [comment]
If it is by design, then that's fair. However, I don't think it is the best design.

I would think a normal use case of the drag system is to place items in different predefined bins. And if you drop the item outside of those bins, it will either be deleted or reset to the original position. If you start dragging an item which is in one of these bins and then drop it again. The drag event is fired when you click and hold down on an item. If you now release it without moving, it will now not be counted as dropped in the dropzone, even though a dragstart and a dragend event has been fired. Which should amount to the concept of a drag?

But yeah, this can be solved with some additional logic and there may be reasons for why the system works like it does.

**Comment by photonstorm** [comment]
The issue is fundamentally: "Should there be a drop event even if there was never a starting drag event? and if so, how do you distinguish the difference between a 'non-dragged' drop and a pointer up event?"

**Comment by orjandh** [comment]
Actually, a _dragstart_ event is fired if you just _pointerdown_ on the object. This is illustrated in my pen by scaling the object up if you hold the mouse button down (without moving).

The problem is that with the current implementation, you can go from _dragstart_ -> _dragend_ without _drop_ being fired if you don't move the cursor, even though _dragend_ is fired while you are over a dropable zone.

**Comment by photonstorm** [comment]
As I said, there's no drag event, so the object is never considered as being in a state of actively being dragged. Once it reaches that state it is valid for being dropped. The drag time and distance thresholds also impact when this happens.

If it was a little earlier in Phaser 3s life I would consider changing this, but it's a substantially big breaking change (for those who use dragging), which I'm reluctant to force on devs at this point in time.
