### ISSUE TITLE
Images can be blurry with CANVAS renderer and roundPixels

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5774]
## Version

* Phaser Version: 3.55.2 and earlier

## Description

Create a game with roundPixels on and the CANVAS renderer. Create an image game object at non-integer coordinates, e.g. (0.5, 0.5). The image appears blurry.

## Example Test Code

https://codepen.io/samme/pen/dyWGzdO

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/sprite-distortion-with-camera-follow-using-bounds/11243/4
