### ISSUE TITLE
Phaser3 GUI mode

### ISSUE THREAD

**Issue by marcusx2** [photonstorm/phaser#5778]
I'd like it if there was a module to make GUI in Phaser3, that is independant from the scene itself. See the [`Babylon GUI`](https://doc.babylonjs.com/divingDeeper/gui/gui#introduction) module for example. So I could make a fullscreen GUI even if the scene is in FIT mode and doesn't cover everything for example.

**Comment by photonstorm** [comment]
This isn't easily possible in Phaser 3, and won't ever be, sorry. The canvas controls the scale of everything and you can't have different scaled canvases. You should really look at using the DOM for UI.
