### ISSUE TITLE
video.loadUrl support cross origin loads.

### ISSUE THREAD

**Issue by rmartell** [photonstorm/phaser#5779]
I'm trying to load a video from a remote server, and it needs to use CORS because I'm loading from a CDN.

I'm using video.loadURL to stream it, but it's failing because the video element that is created during loadUrl doesn't have cross origin attribute settable on it.:

From phaser/src/gameobjects/video/Video.js
```
    loadURL: function (url, loadEvent, noAudio)
    {
        if (loadEvent === undefined) { loadEvent = 'loadeddata'; }
        if (noAudio === undefined) { noAudio = false; }

        if (this.video)
        {
            this.stop();
        }

        if (this.videoTexture)
        {
            this.scene.sys.textures.remove(this._key);
        }

        var video = document.createElement('video');

        video.controls = false;

        if (noAudio)
        {
            video.muted = true;
            video.defaultMuted = true;

            video.setAttribute('autoplay', 'autoplay');
        }

        video.setAttribute('playsinline', 'playsinline');
        video.setAttribute('preload', 'auto');

        video.addEventListener('error', this._callbacks.error, true);

        video.src = url;

        video.load();

        this.video = video;

        return this;
    },
```
My suggestion would be to either add a 4th parameter to loadUrl or to look at the loaders crossOrigin loading setting.

I believe a workaround would be to load it with a asset loader and a key, but that would require loading the entire video in (AFAICT), vs. streaming it.

If this looks valid, and is something others could benefit from, let me know and I can implement and issue a pull request.

Thanks!

**Comment by photonstorm** [comment]
Feel free to submit a PR which either adds this as a 4th parameter, or is a setting on the Video Game Object via a property.

**Comment by rmartell** [comment]
The reason I was thinking 4th parameter values property is because if you use the loader, it has its own way of doing things.  

Having to know to set a property prior to calling this one function (and that property doesn’t communicate with the loader) would seem less clear.

I will submit a PR with 4th parameter once I implement and test it!

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
