### ISSUE TITLE
Looping sound stops playing on blur (despite using pauseOnBlur)

### ISSUE THREAD

**Issue by robinheidrich** [photonstorm/phaser#5782]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 10

* Browser: Google Chrome 91.0.4472.164

## Description

I have disabled that sounds pause on blur, but when the tab is switched the sound stops playing after some time. If you then go back to the tab it continues to play, with the next blur it stops again and then no longer plays.

## Example Test Code

```
// Disabling pause on blur (placed in the constructor of the Game)
this.sound.pauseOnBlur = false

// Play looping audio (placed in a Scene)
this.sound.play('background', { loop: true })
```

**Comment by photonstorm** [comment]
The browser will automatically stop running Request Animation Frame, which is what drives the ability for short sounds to repeat, as it detects if the sound is done and then plays it again, but if RAF has been stopped it cannot do this.

There is no known way to prevent a browser from sending your game to sleep when you switch tab. They all just do it by default now to conserve CPU / battery life.

**Comment by robinheidrich** [comment]
@photonstorm I also wanted to note that Phaser only restores the sound the first time after returning to the tab, the second time it's not restored.

Could you maybe take a look at that?
