### ISSUE TITLE
Game object events are executed when a DOM element is clicked

### ISSUE THREAD

**Issue by robinheidrich** [photonstorm/phaser#5784]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 10

* Browser: Google Chrome 91.0.4472.164

## Description

If you click on a DOM element and there is an interactive game object behind it, the `pointerdown` event will be executed for it as well.

Phaser should check if you have clicked on the DOM container and then not execute any events from the game.

## Example Test Code

```
gameObject.on('pointerdown', () => {
    // This should only be executed when clicked on the game object, but it is
    // also executed when the game object is behind a DOM element that was clicked on.
});
```

**Comment by photonstorm** [comment]
Call `event.preventDefault()` on the DOM element listener to stop this from happening.

**Comment by yanoyuki** [comment]
This works for me.

```
const CANVAS_ELEMENT_ID = "myCanvas"

const game = new Phaser.Game(config)
game.events.once('ready', () => {
  game.canvas.id = CANVAS_ELEMENT_ID
})

...

gameObject.on('pointerdown', (pointer: Phaser.Input.Pointer) => {
  if (pointer.downElement.id === CANVAS_ELEMENT_ID) {
     // <canvas /> is clicked.
   }
});
```
