### ISSUE TITLE
Some offsets are incorrect in createFromObjects()

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5789]
## Version

* Phaser Version: 3.55.2 and earlier

## Description

In Tiled, tile objects have origin (0, 1) and all others have origin (0, 0).

Phaser's `createFromObjects()` places tile objects correctly but other objects incorrectly, because it uses (0, 1) for all of them.

Here the coins are placed correctly but _exit_ and _sun_ are not:

![features test createFromObjects](https://user-images.githubusercontent.com/435681/126684527-728fbbf1-e87d-461a-b8c7-47a8d66f7a72.png)

## Example Test Code

<https://codepen.io/samme/pen/PomJVrL>

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
