### ISSUE TITLE
snapshotCanvas function bug in CanvasRenderer

### ISSUE THREAD

**Issue by rollinsafary-inomma** [photonstorm/phaser#5792]
## Version

* Phaser Version:  3.55.2

* Operating system: doesn't matter

* Browser: doesn't matter

## Description

Trying to get a snapshot from the container, when using Canvas Renderer. There seems a reference issue.

```
    snapshotCanvas: function (canvas, callback, getPixel, x, y, width, height, type, encoderOptions)
    {
        if (getPixel === undefined) { getPixel = false; }

        this.snapshotArea(x, y, width, height, callback, type, encoderOptions);

        var state = this.snapshotState;

        state.getPixel = getPixel;

        CanvasSnapshot(this.canvas, state);

        state.callback = null;

        return this;
    },
```

The function uses `CanvasSnapshot(this.canvas, state);` but there is no `this.canvas` property in there, there is `canvas` argument, that I think might be there or `this.gameCanvas` could be placed instead of `this.canvas`.
## Example Test Code

```
  protected async generateImage(): Promise<
    Phaser.Display.Color | HTMLImageElement
  > {
    return new Promise<Phaser.Display.Color | HTMLImageElement>((resolve) => {
      const texture = this.add.renderTexture(
        0,
        0,
        this.gameObject.width,
        this.gameObject.height,
      );
      texture.draw(this.gameObject);
      texture.snapshot(resolve, 'image/png', 1);
    });
  }
}
```

**Comment by rollinsafary-inomma** [comment]
@samme thanks for the fast fix. Is there any information on when this will be available?

**Comment by samme** [comment]
I don't know but you can use:

- [phaser-arcade-physics.js.zip](https://github.com/photonstorm/phaser/files/6909506/phaser-arcade-physics.js.zip)
- [phaser-arcade-physics.min.js.zip](https://github.com/photonstorm/phaser/files/6909508/phaser-arcade-physics.min.js.zip)
- [phaser-facebook-instant-games.js.zip](https://github.com/photonstorm/phaser/files/6909509/phaser-facebook-instant-games.js.zip)
- [phaser-facebook-instant-games.min.js.zip](https://github.com/photonstorm/phaser/files/6909511/phaser-facebook-instant-games.min.js.zip)
- [phaser-ie9.js.zip](https://github.com/photonstorm/phaser/files/6909512/phaser-ie9.js.zip)
- [phaser-ie9.min.js.zip](https://github.com/photonstorm/phaser/files/6909513/phaser-ie9.min.js.zip)
- [phaser.js.zip](https://github.com/photonstorm/phaser/files/6909515/phaser.js.zip)
- [phaser.min.js.zip](https://github.com/photonstorm/phaser/files/6909516/phaser.min.js.zip)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
