### ISSUE TITLE
GAMEOBJECT_OVER event - unexpected behavior

### ISSUE THREAD

**Issue by EsteFilipe** [photonstorm/phaser#5796]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 10, but this also reproduces in codesandbox so I think it's general

* Browser: Chrome 92.0.4515.107 (64 bits) and Firefox 89.0.2 (64-bit)

## Description

I have a game with bubbles made using Matter as the physics engine illustrated by the image below.

When the mouse is over a bubble I'm adding a tween to highlight it (and then another tween when the pointer goes out to remove that highlight). I'm using the events GAMEOBJECT_OVER and GAMEOBJECT_OUT to add those tweens.

Everything works fine except one thing: when, for instance, I have the pointer over bubble 1 in the image below and then move the pointer down directly to outside the game, and then move back the pointer again to bubble 1, the GAMEOBJECT_OVER event is not fired. On the other hand, if I move the pointer down from bubble 1 to outside the game, and then to the left always outside the game, and then back up to bubble 2, the GAMEOBJECT_OVER event is fired for bubble 2 (a GAMEOBJECT_OUT event is also fired before that). I've also checked and the GAME_OUT and GAME_OVER events are correctly fired when the pointer leaves and enters the game canvas, respectively.

Is this a bug or is it the expected behavior?

![image](https://user-images.githubusercontent.com/12476396/127462460-05e0839f-40db-4bbe-973f-1b41b2d07aff.png)

## Example Test Code

https://codesandbox.io/s/phaser-3-bug-j962z

I'm doing console.log when the GAMEOBJECT_OVER and GAMEOBJECT_OUT events are triggered to illustrate the behavior.

**Comment by photonstorm** [comment]
Thanks for opening the issuel. I agree it's a bit counter-intuitive, however it has always worked like this and I feel it's too late to change it now, so I have updated the event documentation to make it clear what happens.

**Comment by lehtikoskisofie** [comment]
Hi, is there a workaround to this, to make it so that you /can/ hover back over the same object after the pointer leaves the game canvas?
