### ISSUE TITLE
customCam.ignore(this.object) Does not filter new objects added on screen

### ISSUE THREAD

**Issue by RuyVictor** [photonstorm/phaser#5798]
## Technical information

**Phaser Version:**
v3.54.0
**Operating system:**
Windows 10
**Browser:**
Firefox 90.0.2 (32-bits)

## Description

The problem is that if new bullet sprites are created, it is possible to see them in the HUD camera, which was not supposed to happen. The possible solution would be, the "ignore" method that has the camera property should be updated as well as the update function, to identify new objects that will be rendered by the camera and thus ignore them too. Even though I try to ignore the group of objects, they keep appearing. He should be ignored entirely, even if I add new objects to them.

## Example Test Code

```
class Example extends Phaser.Scene
{
    constructor ()
    {
        super();
    }

    private myBulletsGroup!: Phaser.GameObjects.Group;

    preload () 
    {
        this.load.image('bullet', 'bullet.png');
    }

    create () 
    {
        const UICam = this.cameras.add(0, 0, this.cameras.main.width, this.cameras.main.height);

        //first, remove all current objects and filter only ui objects ---> after filter, new sprites that are added on screen,
        are not filtered.

        UICam.ignore(this.children.list.filter(
            value =>
            value != this.gameChat &&
            value != this.texfieldChat &&
            value != this.sendButton
        ))

        this.myBulletsGroup = this.physics.add.group({
            defaultKey: 'bullet',
            maxSize: 600,
        });
    }
    
    spawnBullet ()
    {
        const myBullet = this.myBulletsGroup.get(200, 200);
    
        if (myBullet) {
            this.physics.moveTo(myBullet, 340, 200, 1000);
        }
    update () 
    {
        const cursorPointer = this.input.activePointer;
        if (cursorPointer.leftButtonDown()) {
          this.spawnBullet()
        }
    }
}

const config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: [ Example ]
};

const game = new Phaser.Game(config);
```

**Comment by samme** [comment]
It's not possible to ignore game objects that haven't been created yet. But you could use two [Layers](https://newdocs.phaser.io/docs/3.55.2/Phaser.GameObjects.Layer) for this.

**Comment by photonstorm** [comment]
If you create a new object (such as a child of a Group) then you need to add that to the ignore list too. I would do as samme said and use a Layer instead, and set that to ignore.
