### ISSUE TITLE
Error adding Layer to Layer

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5799]
## Version

* Phaser Version: 3.53.0 to 3.55.2

## Description

Create two Layers. Add one Layer to the other.

> TypeError: gameObject.removeFromDisplayList is not a function.

## Example Test Code

<https://labs.phaser.io/view.html?src=src\game%20objects\layer\nested%20layers.js&v=3.55.2>

## Additional Information

Needs `Layer#removeFromDisplayList()`.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
