### ISSUE TITLE
Load image from external url

### ISSUE THREAD

**Issue by XOCODE-OP** [photonstorm/phaser#5801]
This example fails to load the external file from url.
[https://phaser.io/examples/v3/view/loader/loader-events/load-from-external-url](https://phaser.io/examples/v3/view/loader/loader-events/load-from-external-url)
The file seems to still exists at:
[http://labs.phaser.io/assets/pics/sukasuka-chtholly.png](http://labs.phaser.io/assets/pics/sukasuka-chtholly.png)
Has the code changed for this or why does this not work?

**Comment by samme** [comment]
It should be <https://labs.phaser.io/assets/pics/sukasuka-chtholly.png> (HTTPS).

**Comment by XOCODE-OP** [comment]
oh so just https, alright. well the example should be fixed but good to know nothing else is wrong
