### ISSUE TITLE
Geometry Mask does not work at the same time as PostFxPipeline

### ISSUE THREAD

**Issue by mijinc0** [photonstorm/phaser#5802]
## Version
* Phaser Version: 3.55.2
* Operating system: Ubuntu 20.04.2 LTS (WSL2)
* Browser: Google Chrome (version: 92.0.4515.131 Official Build 64 bit)

## Description
Geometry mask and PostFxPipeline work, but when they are used at the same time, geometry masks do not work.

## Example Test Code
code pen example

https://codepen.io/blue_arcade/pen/RwVYbKe

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
