### ISSUE TITLE
Pending items aren't removed from the update list

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5803]
## Version

* Phaser Version: 3.50.0 to 3.55.2

## Description

After either

```js
this.add.sprite(/*…*/).destroy();
```

or

```js
this.sys.updateList.remove(this.add.sprite(/*…*/));
```

the sprite will be on the active update list after the next update.

## Example Test Code

<https://codepen.io/samme/pen/LYyJOJw?editors=0010>

## Additional Information

It happens because items in the "destroy" list are removed only from "active" and not from "pending".

The fix is a bit complicated because e.g. `this.add.existing(sprite)` adds two (duplicate) items to the pending update list.

**Comment by photonstorm** [comment]
This is the same as #5818 #5817 (well, your issue was first, but the core problem is the same) so am linking these together so I can close them all when resolved.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
