### ISSUE TITLE
Phaser.Physics.Matter.Factory  bodies don't show fillColor or lineColor

### ISSUE THREAD

**Issue by steveja42** [photonstorm/phaser#5807]
## Version

* Phaser Version: 3.55

* Operating system: Windows 10

## Description

Bodies created by Phaser.Physics.Matter.Factory  don't show fillColor or lineColor and are thus invisible.  For example in the code below the rectangle created by this.matter.add.rectangle is invisible. If I set debug to true then the lineColor will show. So far I have noticed this in rectangle and circle.

## Example Test Code

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Making your first Phaser 3 Game - Part 1</title>
    <script src="//cdn.jsdelivr.net/npm/phaser@3.55.0/dist/phaser.js"></script>
    <style type="text/css">
        body {
            margin: 0;
        }
    </style>
</head>

<body>

    <script type="text/javascript">

        var config = {
            type: Phaser.AUTO,
            width: 800,
            height: 600,
            scene: {
                preload: preload,
                create: create,
                update: update
            },
            physics: {
                default: 'matter',
                matter: {
                    debug: false,
                    gravity: { x: 0, y: 0 }
                }
            }
        };

        var game = new Phaser.Game(config);

        function preload() {
        }

        function create() {
            this.matter.add.rectangle(10, 10, 30, 30, { render: { fillColor: 0x0000ff, lineColor: 0xff0000 } })
            //workaround
				let rect = this.add.rectangle(100, 100, 40, 40, 0x0000ff); 
            this.matter.add.gameObject(rect, { ignoreGravity: true })
        }

        function update() {
        }

    </script>

</body>

</html>

**Comment by photonstorm** [comment]
This is the correct behavior. The `Factory.rectangle` function (and similar) just create physics bodies. They have no rendering component to them. The fill and line colors are for debugging, hence why they only appear when debugging is enabled. If you wish to visualise the body you need to either attach it to a Sprite or a Game Object that renders, like one of the Shape objects.
