### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by rollinsafary-inomma** [photonstorm/phaser#5808]
## Description

I've just looked into `game.events` to check if all listeners have been removed after the scene stops. And found out that there are a lot of text objects, that are already destroyed but their listeners arent removed. So I've checked and it's a listener of Phaser.Core.Events.CONTEXT_RESOTRED event which is anonymous and that's why it can't be removed.

So this causes to not clear the text objects from the memory even after destroy or stopping the scene.

## Example Test Code

Path to the file: /src/gameobjects/text/Text.js lines 289-293
```
        scene.sys.game.events.on(GameEvents.CONTEXT_RESTORED, function ()
        {
            this.dirty = true;
        }, this);
```

## Additional Information

A possible fix for this is to change the listener function to a private one, but not anonymous, and then remove this listener before destroying the object.

**Comment by rexrainbow** [comment]
#5806

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
