### ISSUE TITLE
An error should be thrown when an undefined scene is started

### ISSUE THREAD

**Issue by ubershmekel** [photonstorm/phaser#5811]
## Version

* Phaser Version: v3.55.2

* Operating system: MacOS

* Browser: Chrome

## Description

When starting a scene with an invalid key, the command just kills the current scene with no error shown.

https://github.com/photonstorm/phaser/blob/5c8ecbcf999e6f328d21884e877c9e5935d2d350/src/scene/SceneManager.js#L1154

Seems there is no handling of the negative case of that `if`.

## Example Test Code

When no such scene was registered in the GameConfig:

`this.scene.start("game-over");`

## Additional Information

Would a PR to console log/warn be considered?

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
