### ISSUE TITLE
Shutdown shouldn't be repeated for stopped scenes

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser#5826]
If you do

```js
this.scene.stop().stop().stop();
```

then [SHUTDOWN](https://newdocs.phaser.io/docs/3.55.2/Phaser.Scenes.Events.SHUTDOWN) is emitted three times.

This seems a little incorrect to me and it can also make shutdown event handlers needlessly complex.

I would rather have [SceneManager#stop](https://newdocs.phaser.io/docs/3.55.2/Phaser.Scenes.SceneManager#stop) abort if the scene is already stopped.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
