### ISSUE TITLE
General Key mapping with event.code instead of event.key

### ISSUE THREAD

**Issue by DblK** [photonstorm/phaser#5829]
Hi,

On my game, I which to be able to let both `french` and `english` people to play with their keyboard.  
To do so, I had to match `WASD` and `ZQSD` to be able to move the player.

This is because of the `event.key` mapping instead of `event.code` ([You can see more information about it here](https://w3c.github.io/uievents-code/#key-alphanumeric-writing-system) and a [nice website to test it](https://keycode.info/)).

So if it is possible to use those it will ease the process to make game without adding complexity on code.  
Because it's the same for `digit`. Handling all keyboard language will be a pain...

**Comment by photonstorm** [comment]
As you said, Phaser 3 uses the _value_ of the key being pressed, not the physical representation of it. I cannot just change this over, it's far too late and there's too much code relying on it.

Plus, it would make things really difficult if, for example, you asked the player "Press Y to yell" - if I use the physical location, players with a US keyboard can press Y just fine, but those on a Dvorak keyboard would have to press F, or a German keyboard would have to press Z. It makes sense when using `isDown` style checks for movement (as in your example), but really complicates things for setting-style keys or menus, which means I'd have to have 2 forms of API available. It's just too late to wrench this in. Something to allow in Phaser 4 I think.
