### ISSUE TITLE
Text with RTL enable and padding left/right

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5830]
## Version
* Phaser Version: 3.55.2
* Operating system: Win10
* Browser: Chrome & firefox

## Description

Text with RTL enable and padding left/right does not render correctly.

## Example Test Code

[Test code](https://codepen.io/rexrainbow/pen/GREmmLy)
- Upper text is RTL enable, without any padding
- Bottom text is RTL enable, with left/right padding. The result of text rendering is outside of canvas.

![圖片](https://user-images.githubusercontent.com/817962/132934133-2435daa9-7840-4ba0-a3e5-360e21d459fa.png)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
