### ISSUE TITLE
[Spine Webgl] Spine plugin renders add 1 white pixel to the bound of the textures when game config has "transparent: true"

### ISSUE THREAD

**Issue by phamconganh** [photonstorm/phaser#5832]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 10

* Browser: Chrome

## Description

Spine plugin renders add 1 white pixel to the bound of the textures when game config has "transparent: true". When the game has backgroundColor, it doesn't have a bug. But in my case, I need the background to be transparent.
- Phaser
![image](https://user-images.githubusercontent.com/28704713/133188836-003e0547-ebaa-4255-8fb5-036be156a165.png)
- Pixijs
![image](https://user-images.githubusercontent.com/28704713/133188990-b7d1c5ac-3ad9-4f42-94b4-43f5c916eb23.png)

## Example Test Code

```
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    // backgroundColor: '#f5f5f5',
    transparent: true,
    scene: {
        preload: preload,
        create: create,
        update: update,
        pack: {
            files: [
                { type: 'scenePlugin', key: 'SpinePlugin', url: 'plugins/3.8.95/SpinePluginDebug.js', sceneKey: 'spine' }
            ]
        }
    }
};

var controls;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('logo', 'assets/sprites/phaser.png');

    this.load.setPath('https://s.sachmem.vn/public/images/v2/TA_mamnon/R4-L2/Book2_5_3');

    this.load.spine('raptor', 'Book2_5_3.json', 'Book2_5_3.atlas');
}

function create ()
{
    this.add.image(0, 0, 'logo').setOrigin(0);

    var raptor = this.add.spine(350, 600, 'raptor');


    var list = raptor.getAnimationList();

    raptor.play(Phaser.Utils.Array.GetRandom(list), true);

    var cursors = this.input.keyboard.createCursorKeys();

    var controlConfig = {
        camera: this.cameras.main,
        left: cursors.left,
        right: cursors.right,
        up: cursors.up,
        down: cursors.down,
        zoomIn: this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.Q),
        zoomOut: this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.E),
        acceleration: 0.5,
        drag: 0.01,
        maxSpeed: 1.2
    };

    controls = new Phaser.Cameras.Controls.SmoothedKeyControl(controlConfig);
}

function update (time, delta)
{
    controls.update(delta);
}

```

## Additional Information

When I use backgroundColor, it still has 1 pixel black error
![image](https://user-images.githubusercontent.com/28704713/133191792-be96e525-2f6f-497e-8656-a32ef4f957f6.png)

**Comment by photonstorm** [comment]
This looks like a pre-multiply alpha issue. Ensure you export from Spine with it enabled and set the corresponding parameter in Phaser when creating the Spine game objects. See the labs.phaser.io Spine folder for examples.

**Comment by phamconganh** [comment]
@photonstorm thank you for save my time!
