### ISSUE TITLE
Typescript optional / null arguments

### ISSUE THREAD

**Issue by Pythux** [photonstorm/phaser#5833]
## Description

Some functions handle null input but the typing does not reflect that.

## Example

[the documented function used](https://newdocs.phaser.io/docs/3.55.2/Phaser.Animations.Animation#calculateDuration)

function signature: `calculateDuration(target: Phaser.Animations.Animation, totalFrames: number, duration: number, frameRate: number): void`

inside this function, we have:
```js
if (duration === null && frameRate === null)
// ...
else if (duration && frameRate === null)
// ...
else
```

the documentation does not say that we choose duration or frameRate through typing `number | null`, with a default if none given.

### Example Test Code

```js
// let get a created animation named 'key'
const anim = scene.anims.get('key')

// to make the animation named 'key' last 2s:
anim.calculateDuration(anim, anim.getTotalFrames(), 2000, null)

// to make the animation named 'key' run at 8 frames per secondes:
anim.calculateDuration(anim, anim.getTotalFrames(), null, 8)
```

the correct function signature would be: `calculateDuration(target: Phaser.Animations.Animation, totalFrames: number, duration: number | null, frameRate: number | null): void`

## Additional Information

Moreover, we could make change in the code to allow undefined value too.

I don't know how to change the code to reflect typing change, it's look like typing is generated trough documentation, `@param {number | null}` would do ? Does these is something to run to generate then the typescript before sending a pull request ?

I would like to send one if it's ok, with the code change to allow `undefined`, and have the correct typing.

**Comment by Pythux** [comment]
Thank you samme,

The code right now only allow `number` or `null` values trough strict equals

A first fix to it is not `{?number}` that to my understanding allow `number` or `undefined`
But `{number|null}` that allow `number` or `null`


A change to double equals will allow `undefined` too, but, in the Code Style Guide, it is said:

- Always favor strict equals `===` unless you *need* to use type coercion.



So I think we could add `undefined` values to be valide and keep strict equals with: `value === null | value === undefined`

that would change the code to something like that:

```js
if ((duration === null | duration === undefined) && (frameRate === null | frameRate === undefined))
// ...
else if (duration && (frameRate === null | frameRate === undefined))
// ...
else
```

and change the documentation to `{?number | null}` or `{number | null | undefined}`, both are equivalent.

Maybe someone could propose better for the code ?


## ps

that typo you fixed too make me wonder where is the phaser documentation generated from ?

[the documentation link](https://newdocs.phaser.io/docs/3.55.2/Phaser.Animations.Animation#calculateDuration)

It is written `Calculates the duration, frame rate and msPerFrame values.`, no typo here

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
