### ISSUE TITLE
Document scale affects mouse input

### ISSUE THREAD

**Issue by hbiblia** [photonstorm/phaser#5843]
Hello there

I have a small code that scales the canvas-dom according to W / H, I use it a lot in my work because it allows to have a specific size like 1024 * 768.

When we use something with the mouse we must calculate it with a variable called "zoom = 1 (default)" if we are at 1024 * 768 but it changes according to the change of the window, but internally within the document it is 1024 * 768.

Well the phaser canvas should pass the same, the mouse should be zoomed.

Modify the Phaser 2.8.1 which is the one I use, but I imagine that they can do it in all versions here I leave the changes so that they can apply it if they see it necessary.

@class Phaser.Input
![image](https://user-images.githubusercontent.com/1939353/134713533-4a7228d8-8a0a-451f-9b3f-0bc1e7ad4385.png)

@method Phaser.Pointer#move
![image](https://user-images.githubusercontent.com/1939353/134713228-bdde5ff4-9595-49d6-a529-5bb1180b2f60.png)

Hope this helps improve more phaser, thanks.

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.
