### ISSUE TITLE
WebGL Tilemap Layer Rendering Broken

### ISSUE THREAD

**Issue by kainage** [photonstorm/phaser#5860]
## Version

* Phaser Version: Phaser v3.60.0-beta.1

## Description

TIlemap layers rendering is exploding and the x coord is not being calculated correctly

## Example Test Code

http://labs.phaser.io/view.html?src=src\tilemap\tileset%20collision%20shapes.js&v=dev

## Additional Information

PR to fix the issues: https://github.com/photonstorm/phaser/pull/5859

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
