### ISSUE TITLE
SetBackgroundColor sets inaccurate color

### ISSUE THREAD

**Issue by orjandh** [photonstorm/phaser#5866]
## Version

* Phaser Version: 3.55.2 and 3.17.0

* Operating system: Windows 10

* Browser: Chrome 94

## Description

Chrome's color input box let's you pick a color with an eye drop tool. I am trying to use this tool to select a background color in Phaser. But when setting the background color, the color will be slightly off compared to the selected color. The rgb value of the color object seems to be correct, but it doesn't seem like this is the color that is actually displayed. I also took a screenshot and compared the colors and it does indeed display the wrong rgb color.

## Example Test Code

https://stackblitz.com/edit/phaser3-typescript-9hvckf?file=index.ts

## Additional Information

To reproduce this. Open the stackblitz example in Chrome and select the green bar with the eye drop tool. The background will now change and you'll see that the colors does not align.

I suspect this has something to do with internal conversion to HSV.

**Comment by photonstorm** [comment]
There is no internal color conversion.

This is what I get when I pick the green platform with the eyedropper:

![image](https://user-images.githubusercontent.com/164476/137142759-1c4c87d0-1776-453f-9099-f06a7e31bfb0.png)

And double-checking with a color analyzer tool:

![image](https://user-images.githubusercontent.com/164476/137143025-d78c8ba1-5682-4f0f-ab20-ad77e024fd36.png)

This is on Windows 10 with Chrome 94.

I suspect you have either a browser setting, or extension, or GPU configuration causing this.
