### ISSUE TITLE
Missing type information for 'DynamicTilemapLayer'

### ISSUE THREAD

**Issue by steddyman** [photonstorm/phaser#5881]
## Version
* Phaser Version: 3.55..2
* Operating system: Mac OS,  ReactJS
* Browser: Chrome

## Description

I am trying to integrate the code from: https://github.com/mipearson/dungeondash.git into my ReactJS typescript application.  No matter how I integrate it, either manually or using @ion-phaser/react it always complains that DynamicTilemapLayer does not exist.  Here is the actual error:

/Users/username/path_to_file/FOVLayer.ts
TypeScript error in /Users/username/path_to_file/FOVLayer.ts(33,33):
Namespace 'Phaser.Tilemaps' has no exported member 'DynamicTilemapLayer'.  TS2694

    31 | 
    32 | export default class FOVLayer {
  > 33 |   public layer: Phaser.Tilemaps.DynamicTilemapLayer;
       |                                 ^
    34 |   private mrpas: Mrpas | undefined;
    35 |   private lastPos: Phaser.Math.Vector2;
    36 |   private map: Map;

## Example Test Code

Example code from: https://github.com/mipearson/dungeondash.git

## Additional Information

The code in the above repo for some reason will compile just fine in its own repo when it is not integrated with React.

**Comment by samme** [comment]
Since Phaser v3.50.0, there is no `Phaser.Tilemaps.DynamicTilemapLayer`, only `Phaser.Tilemaps.TilemapLayer`.

**Comment by steddyman** [comment]
Thank you, that was it!

**Comment by steddyman** [comment]
Resolved
