### ISSUE TITLE
Can't start the same timer when time-out

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5887]
## Version

* Phaser Version: 3.60.0

* Operating system: win11

* Browser: Chrome, firefox

## Example Test Code

See [this test](https://codepen.io/rexrainbow/pen/ExvmZEd)

1. Start a timer first time
2. Start the same timer under time-out callback (Case A)

This timer can't start at the same tick with time-out. In this case, timer is [added to 
`_pendingRemoval` and `_pendingInsertion` both](https://github.com/photonstorm/phaser/blob/master/src/time/Clock.js#L291-L292), and been [destroyed](https://github.com/photonstorm/phaser/blob/master/src/time/Clock.js#L316), clear callback. Therefore no callback available in next time-out. 

A workaround is start this timer at next tick (Case B), new callback is set after [destroyed](https://github.com/photonstorm/phaser/blob/master/src/time/Clock.js#L316)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
