### ISSUE TITLE
TS2339: Property 'normalize' does not exist on type 'Vector'.

### ISSUE THREAD

**Issue by tiago-prado-oliveira** [photonstorm/phaser#6109]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 10

## Description

Typescript error when trying to access the normalize (and other) function of Vector2 inside Arcade Body.

```
TS2339: Property 'normalize' does not exist on type 'Vector2 | Vector'. Property 'normalize' does not exist on type 'Vector'.
```
Phaser.Math.Vector2 has the property, but Vector (in MatterJS.BodyType) does not have. Apparently there is a conflict in here.

![image](https://user-images.githubusercontent.com/85585677/167706578-05507967-feb4-4583-9a12-6d581e0d8720.png)

VS Code and Webstorm can't autocomplete appropriately
![image](https://user-images.githubusercontent.com/85585677/167707437-9e8a37f8-cc28-4e3c-b563-01c3b15e108a.png)

## Example Test Code

```
this.player.body.velocity.normalize().scale(this.speed);
this.player.body.setCircle(10);
```
```
TS2339: Property 'normalize' does not exist on type 'Vector2 | Vector'. Property 'normalize' does not exist on type 'Vector'.
```
```
TS2339: Property 'setCircle' does not exist on type 'Body | StaticBody | BodyType'.
  Property 'setCircle' does not exist on type 'BodyType'.
```

**Comment by samme** [comment]
How did you create `this.player`?

**Comment by tiago-prado-oliveira** [comment]
Something like this
```
private player: Character;
...
create() {
    ...
    this.player = new Character(this);
    ...
}
```

```
export class Character extends Phaser.GameObjects.Sprite {
    constructor(phaserScene: Phaser.Scene) {
        super(phaserScene, 0, 0, 'player');
        this.scene.add.existing(this);
        this.scene.physics.add.existing(this);
    ...
```

I was following the template below, like he did with BlackSmith class (I changed Blacksmith to my Character class).
https://github.com/openforge/ionic-phaser-game-template/blob/master/libs/example-app/phaser/singleton/src/lib/scenes/forge.scene.ts

**Comment by samme** [comment]
Add

```typescript
export class Character extends Phaser.GameObjects.Sprite {
    body: Phaser.Physics.Arcade.Body;
    // …
}
```

**Comment by tiago-prado-oliveira** [comment]
Oh, I can override the field type.

Thank you for the help. Sorry for the stupid issue.

**Comment by AfonsoCFonseca** [comment]
@samme Thank you. That actually also solved my problem 👍🏻
