### ISSUE TITLE
TileSprite Scaling Smoothed With smoothed=false

### ISSUE THREAD

**Issue by jyapayne** [photonstorm/phaser#618]
Hi,

In the master branch and the latest dev branch, I am scaling a tilesprite up to 4x. It seems to get smoothed if I use game.stage.smoothed = false; and doubly smoothed if I set game.stage.smoothed = true;

![smoothed](https://f.cloud.github.com/assets/2645657/2478334/d5be98f6-b07d-11e3-94e3-ed468082afd0.png)

As you can see, these are both scaled by 4, but the cloud is nice and pixelly, whereas the road, which is a tilesprite, is slightly blurry and smoothed.

**Comment by devjv** [comment]
My tileSprites are smoothed even with canvas mode on and the above code snippet. I have also manually set tileSprite smoothed as false but nothing fixes the problem.

**Comment by Llorx** [comment]
Having this problem too. What I had to do is to create my own TileSprite class which involves drawing on a bitmap repeteadly.

**Comment by originals** [comment]
i also have this problem, only tilesprites are blurry with webgl

**Comment by Owumaro** [comment]
The explanation is in the documentation of [TileSprite](http://phaser.io/docs/2.6.1/Phaser.TileSprite.html):

> When running under Canvas a TileSprite can use any texture size without issue. When running under WebGL the texture should ideally be a power of two in size (i.e. 4, 8, 16, 32, 64, 128, 256, 512, etch pixels width by height). If the texture isn't a power of two it will be rendered to a blank canvas that is the correct size, which means you may have 'blank' areas appearing to the right and bottom of your frame. To avoid this ensure your textures are perfect powers of two.

I guess this blank canvas rendering step doesn't care if you have disabled smoothing or not.

**Comment by guatedude2** [comment]
Shouldn't this bug be reopened? There's no way to turn off smoothing on a TileSprite

**Comment by cjke** [comment]
Ensure your loaded sprites are indeed a power of two. If they are not, they will appear blurry
