### ISSUE TITLE
Snapshot with camera zoom

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#6180]
## Version

* Phaser Version: 3.55.2, 3.60.0-beta.10

* Operating system: win10

* Browser: chrome, firefox

## Description

[Here](https://codepen.io/rexrainbow/pen/PoRJOed) is the test code
- Disable line 15: No camera zoom. Snapshot area works well.
- Enable line 15: Set camera zoom to `0.75`. Snapshot area is shifted and scaled.

I guess that parameters `x, y, with, height` are based on screen coordinate, not  world coordinate of a camera.

**Comment by photonstorm** [comment]
Heya - testing this against master branch it appears to be working fine for me. Could you give my code a check to see if I'm doing anything wrong compared to yours please?

```js
class Example extends Phaser.Scene
{
    constructor ()
    {
        super();
    }

    preload ()
    {
        this.load.image('uv', 'assets/pics/uv-grid-4096-ian-maclachlan.png');
    }

    create ()
    {
        this.add.image(2048, 2048, 'uv');

        this.cameras.main.setZoom(0.75);
        this.cameras.main.setScroll(2000, 1024);

        this.renderer.snapshotArea(0, 0, 256, 256, image => {

            document.body.appendChild(image);

        });
    }
}

const config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d6d',
    scene: Example
};

const game = new Phaser.Game(config);
```

Above code also in Phaser 3 Examples repo in the bugs folder.

**Comment by photonstorm** [comment]
And yes, `snapshotArea` parameters are screen / canvas coordinates, not world.

**Comment by rexrainbow** [comment]
I see, the [comments](https://github.com/photonstorm/phaser/blob/master/src/renderer/webgl/WebGLRenderer.js#L2473-L2474) has been updated. Issue closed.
