### ISSUE TITLE
3.60.0-beta.19 - masking main camera makes GameObjects with postFX effects to disapear

### ISSUE THREAD

**Issue by drunkcat** [photonstorm/phaser#6407]
## Version

* Phaser Version: 3.60.0-beta.19
* Operating system: Windows 11
* Browser: Firefox and Chromium browsers

## Description

Adding effect to GameObject (ex. addBokeh() to Image) and masking the main camera, makes the object with effect to disappear. All other objects remain visible.

## Example Test Code
```
let _img = this.add.image(20, 20, 'testimage').setOrigin(0);
_img.postFX.addBokeh(0.5);// without adding the effect, masking a camera works fine

this.add.image(300, 20, 'testimage').setOrigin(0);//this image is always visible (properly masked)

this._mask_graphics = this.make.graphics();
this._mask_graphics.fillRectShape(new Phaser.Geom.Rectangle(0, 0, 700, 800));
this._mask = this._mask_graphics.createGeometryMask();
this.cameras.main.setMask(this._mask);// adding this line makes the image with postFX effects disappear
```

Thanks
Greg.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release (Beta 20). If you get time to build and test it for yourself we would appreciate that.
