### ISSUE TITLE
MatterJS types problem in TypeScript

### ISSUE THREAD

**Issue by ProgrammingLife** [photonstorm/phaser#6426]
## Version
* Phaser Version: 3.60 beta 19

## Description
Tried to remove and add a MatterJS body but it fails.

## Example Test Code
```js
const sprite = this.matter.add.image(
	500, 500, "box", undefined, { isStatic: true }
);
this.matter.world.remove( sprite.body );
this.matter.world.add( sprite.body );
```
It returns an error:
```
Argument of type 'BodyType | Body | StaticBody | null' is not assignable to parameter of type 'object | object[]'.
  Type 'null' is not assignable to type 'object | object[]'.ts(2345)
```

As a workaround we can use such form which works fine but not the best solution:
```js
this.matter.world.remove( sprite.body as any );
this.matter.world.add( sprite.body as any );
```

MatterJS needs to pass the exactly .body of the object, not the sprite object itself. So this:
```js
this.matter.world.remove( sprite );
this.matter.world.add( sprite );
```
compiles but doesn't work in runtime. It adds the sprite object only but not the physics body.

## Additional Information
n/a

**Comment by ProgrammingLife** [comment]
One more issue with MatterJS types is here:
```js
this.matter.body.setAngle( sprite.body, Math.PI );
```
The same problem.

**Comment by photonstorm** [comment]
Cast the body (doesn't have to be as `any`, you can explicitly cast it), because it's perfectly valid for `sprite.body` to be `null`, so we cannot remove that from the type defs for that property.
