### ISSUE TITLE
3.60 beta 21: Can't compile with ESM

### ISSUE THREAD

**Issue by ProgrammingLife** [photonstorm/phaser#6438]
Trying to compile the code:
```js
import { AUTO, Scene, Game } from "../libs/phaser.esm.min.js";
class Test extends Scene {
    constructor () {
        super();
    }
    public create () {
        this.add.text(10, 10, 'Welcome to Phaser ESM'); // <-- TS2339: Property 'add' does not exist on type 'Test'.
    }
}

const config = {
    type: AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: [ Test ]
};
const game = new Game(config);
```

Is this a known issue?

**Comment by ProgrammingLife** [comment]
Oh, this is my fault. Just missed a declaration file.
Fixed with: `$ npm i https://github.com/photonstorm/phaser.git`
and in ts: `import { AUTO, Scene, Game } from "phaser"`

**Comment by photonstorm** [comment]
7MB is the correct size for the unminified and uncompressed Phaser library. There is several MB worth of documentation in that bundle alone, never mind the code itself.

And no, it won't tree shake and shouldn't be expected to (that is what the V4 version is all about)
