### ISSUE TITLE
Static signals

### ISSUE THREAD

**Issue by merixstudio** [photonstorm/phaser#645]
All signals could be static and not as instance members. This would allow for greater modularity of game developer's code and doesn't require to pass everywhere a Game instance.

Instead of this:

```js
// Inside Phaser.Loader constructor
this.onFileComplete = new Phaser.Signal();
```

Could be this:

```js
Phaser.Loader.onFileComplete = new Phaser.Signal();
```

All loaders and other parts of the Phaser code should then use these global signals, eventually passing game instance as an argument to callbacks.

Then third-party additions to Phaser (e.g. custom loaders) would use these global signals instead of inventing their own ones.

Global signals are implemented in the [Django](https://docs.djangoproject.com/en/1.6/topics/signals/) web framework like this and it greatly helps to decouple modules. Note that Django is not game development tool, but contains very similar signals like in Phaser.

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)
