### ISSUE TITLE
When chaining tweens, onComplete fires after first tween

### ISSUE THREAD

**Issue by jyapayne** [photonstorm/phaser#646]
When I call this code:

``` javascript
var tween = this.add.tween(level_text_element).to({x:this.camera.width/2}, 500, Phaser.Easing.Exponential.Out)
.to({x:this.camera.width/2+50}, 1000, Phaser.Easing.Exponential.In)
.to({x:this.camera.width+100}, 500, Phaser.Easing.Exponential.Out).start();

tween.onComplete.add(function(){console.log('test');},this);
```

"test" is printed in the console after the first tween finishes (500 milliseconds). 

I would expect that the event should fire after the last tween, no?

This is on Phaser 2.0.1 from master.

**Comment by kenotron** [comment]
2.2.0 now has a tween onChildComplete signal. You look at the 2nd parameter in the callback (as the tween). You can check the chain number there as "current":

  tween
        .to({y: 250}, 750, Phaser.Easing.Cubic.In)
        .to({y: 250}, 350, Phaser.Easing.Linear.Out)
        .to({y: 0, alpha: 0}, 50, Phaser.Easing.Cubic.Out);

  tween.onChildComplete.add(function(target, theTween) {
        console.log(theTween.current);
  });
