### ISSUE TITLE
Strange behavior updating sprite position manually

### ISSUE THREAD

**Issue by Agnostic** [photonstorm/phaser#683]
Execute the next code here:
http://examples.phaser.io/_site/view_full.html?d=arcade%20physics&f=sprite+vs+group.js&t=sprite%20vs%20group

``` javascript
for(var i = 0; i < 200; i++){
  sprite.x = i;
  console.log(i, sprite.x);
}
```

**Comment by VengadoraVG** [comment]
your phaser.min.js file is old. You have to update it!!!!

**Comment by cirdec09** [comment]
left and right player move by arcade physics in phaser?
