### ISSUE TITLE
After scaling the layer of a tilemap camera seems to get buggy

### ISSUE THREAD

**Issue by eugenioclrc** [photonstorm/phaser#735]
I was working on a small map that i scale to make the player feels that its a big (and pixelated) world while its just a small and simple tilemap.

While doing this i've noticed that the camera its not working quite well. I have prepared a demo using one of the examples from http://examples.phaser.io

Demo using mario
http://jsbin.com/xicav/3/

Source;
http://jsbin.com/xicav/3/edit?js,output

**Comment by JRogaishio** [comment]
Is there any update to this? I'm trying to scale my tilemaps as well but everything is coming out wonky. Doing the below will re-scale the layers but the collisions are not fixed even if scaling is before the map.setCollisionsBetween.
```
var layer = map.createlayer('myLayer')
layer.scale.set(2,2); //Double the scale
```

**Comment by photonstorm** [comment]
This feature is now merged in the dev branch and will be part of the 2.3 release.
