### ISSUE TITLE
Generic pool class

### ISSUE THREAD

**Issue by gamedevsam** [photonstorm/phaser#747]
I feel that this would be a welcome addition to the engine, especially when allocating many Point / Line objects on each update loop as demonstrated by this example: http://gamemechanicexplorer.com/#raycasting-1

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)
