### ISSUE TITLE
Arcade collision fails to detect collision for rotated rectangular sprites.

### ISSUE THREAD

**Issue by sameergoyal** [photonstorm/phaser#752]
Hey,

I have a sprite of dimensions 50x20 say, tank. Now I rotate it using tank.angle += 90 or tank.angle -= 90. The anchor for this tank is set at 0.5, 0.5. 

Now after this rotation, tank.bottom & tank.right should have been updated, since my rectangular object has width > height and after a 90deg rotation, the distance from an object, say wall(wall.position.x = tank.position.x+100 & wall.position.y = tank.position.y) with which I can collide has reduced.

Since, the tank.bottom (& also tank.right) is not updated, the arcade collision detection also doesn't seem to include the effect of rotation in its collision computation.

Here is a screenshot of the issue: 
![screen shot 2014-04-23 at 3 47 16 am](https://cloud.githubusercontent.com/assets/1594391/2771504/eb9c2028-ca6b-11e3-815c-95310ee35beb.png)

The red rectangle is the rotated rectangular object and the black lines are part of a group and I call the collide method with both of these parameters. If I don't rotate the object, the collision detection works absolutely fine. Also, this effect seems more prominent for cases where the ratio of width to height (larger dimension to smaller dimension) is large.

**Comment by lafkpages** [comment]
What if we only rotate by 90 degrees and therefore maintain a rectangle bounding box? Can we manually update those bottom/right etc properties?

I just need to make a wall with a TileSprite and rotate the texture, so I made a horizontal rectangle and then rotated it with `.angle = 90` and it works fine except for the collisions.

**Comment by photonstorm** [comment]
> What if we only rotate by 90 degrees and therefore maintain a rectangle bounding box? Can we manually update those bottom/right etc properties?
> 
> I just need to make a wall with a TileSprite and rotate the texture, so I made a horizontal rectangle and then rotated it with `.angle = 90` and it works fine except for the collisions.

No, it still wont' work. You'll need to call `Body.setSize` to resize it as needed.
