### ISSUE TITLE
[Enchancement] Allow animations to be specified as flips

### ISSUE THREAD

**Issue by hilts-vaughan** [photonstorm/phaser#762]
For example, I have a sprite walking right and have defined the right walking frame as "walk_right". I'd like to define a flipped version of all these frames for "walk_left". This is currently not possible and I need to duplicate data.

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)
