### ISSUE TITLE
Stage.backgroundColor not working in CANVAS mode

### ISSUE THREAD

**Issue by ram64** [photonstorm/phaser#785]
If you try to set the stage color while in CANVAS mode it will not work but it works in WEBGL mode
http://codepen.io/ram64/pen/scgpH

**Comment by cscott5288** [comment]
I'm unable to set the background using Canvas 2d mode:
game.stage.backgroundColor = '0x000000';

**Comment by photonstorm** [comment]
You don't put hex values in quotes.

'#000000' or 0x000000


On Saturday, January 10, 2015, cscott5288 <notifications@github.com> wrote:

> I'm unable to set the background using Canvas 2d mode:
> game.stage.backgroundColor = '0x000000';
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/785#issuecomment-69438787>.
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27
