### ISSUE TITLE
Cannot read property 'shortcutLock' of undefined?

### ISSUE THREAD

**Issue by cattsmall** [photonstorm/phaser#804]
Hi, I created a practice game based on the Phaser tutorial. After I upgraded to the newest Phaser release (Apr 29), I started getting this error when I press keyboard keys in the game: 
`Error in event handler for (unknown): Cannot read property 'shortcutLock' of undefined
Stack trace: TypeError: Cannot read property 'shortcutLock' of undefined
    at chrome-extension://oknpjjbmpnndlpmnhmekjpocelpnlfdi/js/content.js:32:32
    at disconnectListener (extensions::messaging:335:9)
    at Function.target.(anonymous function) (extensions::SafeBuiltins:19:14)
    at EventImpl.dispatchToListener (extensions::event_bindings:395:22)
    at Function.target.(anonymous function) (extensions::SafeBuiltins:19:14)
    at publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:69:26)
    at EventImpl.dispatch_ (extensions::event_bindings:378:35)
    at EventImpl.dispatch (extensions::event_bindings:401:17)
    at Function.target.(anonymous function) (extensions::SafeBuiltins:19:14)
    at publicClass.(anonymous function) [as dispatch] (extensions::utils:69:26) extensions::event_bindings:383
EventImpl.dispatch_ extensions::event_bindings:383
EventImpl.dispatch extensions::event_bindings:401
publicClass.(anonymous function) extensions::utils:69
dispatchOnDisconnect`

Is this PEBCAK or is there an issue with the input recognition?

My code is here: [https://github.com/cattsmall/Phaser-game/blob/master/scripts/game.js](https://github.com/cattsmall/Phaser-game/blob/master/scripts/game.js)

You can try the game and see the console here: [http://cattsmall.github.io/Phaser-game/](http://cattsmall.github.io/Phaser-game/)

Thanks for making such a great framework! I'm really excited to share it with my class.

**Comment by crucialfelix** [comment]
which Chrome extension was doing it ? I've got the same interference

**Comment by randallb** [comment]
Me too!

**Comment by erikj** [comment]
for those asking about which extension, like @cattsmall, I had an exception pointing to `chrome-extension://oknpjjbmpnndlpmnhmekjpocelpnlfdi/js/content.js`

`oknpjjbmpnndlpmnhmekjpocelpnlfdi` seems to be the Chrome-store ID for the Readability extension, which I have installed

https://chrome.google.com/webstore/detail/readability/oknpjjbmpnndlpmnhmekjpocelpnlfdi?hl=en

**Comment by crucialfelix** [comment]
I can confirm that, I have readability installed. thanks @erikj

**Comment by philipforget** [comment]
Hey everyone, I'll take a look at why this is happening and fix the extension on our end as well. Sorry about that!

Philip (from Readability)

**Comment by crucialfelix** [comment]
Awesome @philipforget thanks !
I love readability

**Comment by alanguir** [comment]
I can confirm I'm getting this same error in chrome coming from readability while trying to read keypress events in Angular 1.5. Easiest fix for me was to set my node dev server to NOT be on port 3000 - I think that's where the overlap is occurring. For example, `localhost:3030` works just fine and doesn't show the console errors. 

@philipforget easy fix from your side could be just listening on an oddball port number instead of 3000.

**Comment by philipforget** [comment]
@alanguir Thanks for the update, I think this has to do with the way we do the "key chording" (allowing for an almost arbitrary number of concurrent keys for a given shortcut) and the listeners involved. I'm going to take a look at this as soon as I can, just a bit swamped right now.

**Comment by ajc308** [comment]
Have been getting this error recently and googled it, didn't expect it to lead me back to @philipforget :smile:

**Comment by philipforget** [comment]
All bugs lead back to me

**Comment by PawelDecowski** [comment]
@philipforget I’m still seeing this error. Is there a fix planned?

**Comment by skabbit** [comment]
Got the same error.
Got the same love to readability :)
REally annoying, while i'm developing somethiung.

**Comment by crucialfelix** [comment]
yep, every day all day long I'm seeing that error :)

**Comment by crucialfelix** [comment]
one trick actually is to create a separate chrome profile and only install dev stuff in it. it will run slightly faster too.

**Comment by sandstrom** [comment]
@philipforget friendly ping 😄

**Comment by ntodorov** [comment]
guys it is not issue for this repo!!! :) Just go and disable **Readability** extention and it will disapear!
Lets bug **readability** to fix it.
![image](https://cloud.githubusercontent.com/assets/4613148/17418855/d53d80e6-5a57-11e6-93b3-268b0e3ee3d5.png)

**Comment by drhayes** [comment]
@philipforget is the guy from readability. He's helping to fix it. 👍
