### ISSUE TITLE
Setting Group Scale Does Nothing

### ISSUE THREAD

**Issue by eldernos** [photonstorm/phaser#807]
I'm using 2.0.3 but nothing in the release notes seemed to mention group scaling so...

When I create a group and attempt to change its scale independently of another group (both are part of a state) it doesn't do anything.

The only way I can scale things is to do the whole camera for the state which scales everything (including UI) which is not what I want.   All the documentation seems to suggest that what I'm doing should work but it does nothing.  

Any ideas?

**Comment by olkinaYingele** [comment]
Hi!
I've just get the same problem - group scale doesn't work:


    window.onload = function() {

        var game = new Phaser.Game(800, 600, Phaser.AUTO, 'testDiv', { preload: preload, create: create });

        function preload () {

            game.load.image('logo', 'phaser.png');

        }

        function create () {

            var gr = game.add.group();
            gr.create(0, 0, 'logo');
            gr.scale.setTo(3,3);
 
            /*var logo = game.add.sprite(game.world.centerX, game.world.centerY, 'logo');
            logo.anchor.setTo(0.5, 0.5);
            logo.scale.setTo(3,3);*/

        }

    };

**Comment by pavle-goloskokovic** [comment]
Same problem here, this issue should be reopened...

**Comment by photonstorm** [comment]
No because it works fine:

```

var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create });

function preload() {

    game.load.spritesheet('coin', 'assets/sprites/coin.png', 32, 32);

}

var coins;

function create() {

    //  Here we create our coins group
    coins = game.add.group();

    //  Now let's add 50 coins into it
    for (var i = 0; i < 50; i++)
    {
        coins.create(game.world.randomX / 2, game.world.randomY / 2, 'coin', 0);
    }

    //  And now we scale it: x2 on the x and y axis
    coins.scale.set(2, 2);

}
```

**Comment by pavle-goloskokovic** [comment]
It is working. Sorry, my mistake :P
