### ISSUE TITLE
Adding the same animation set to a large(r) group of sprites take a long time 

### ISSUE THREAD

**Issue by LukaHorvat** [photonstorm/phaser#823]
I have a group of around 2400 sprites that all have the same texture. The call 

        group.callAll('animations.add', 'animations', tileName, [1], 1);

takes around 5 seconds and I need to make a few of these calls. This makes my game load for around 30 seconds and it will increase drastically when I add more content.
Is there a faster way to make a lot of basically identical sprites, but still be able to play animations on them separately?

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)
