### ISSUE TITLE
The amount of tilemap layers has a huge impact on performance

### ISSUE THREAD

**Issue by valueerrorx** [photonstorm/phaser#839]
http://test.xapient.net/phaser/ALL/layers.html  (AUTO)
http://test.xapient.net/phaser/ALL/layers-canvas.html  (CANVAS) 

as you can see in the given example 1 layer (no matter how many tiles are actually filled) does not affect the performance at all  (62fps)

canvas size 800x640
tilemap 200x20
tilesize 32x32

4 layers will result in 52 fps
6 layers in 42 fps
8 layers in 34 fps   
(on my workstation)

these test results will show if  you use a webbrowser without gpu rendering enabled (for example chromium on linux) or a low performance device like a tablet (tested with google nexus 7)

if you combine all the layers to one and place all tiles on the same layer you will again have 62 fps

so the amount of tiles is not responsible for any noticeable performance loss..
even 4 giant background images moved relative to the camera (parallax) will have no impact on the performance..  but even a complete empty layer will do !
![mariohills1](https://cloud.githubusercontent.com/assets/7266848/3031526/0e6d37f8-e04d-11e3-8150-ff3f87fe5a4e.jpg)

**Comment by photonstorm** [comment]
Closing this off as we've updated tilemap rendering lots recently to assist with this.
