### ISSUE TITLE
TileSprite seams visible when using atlases and WebGL

### ISSUE THREAD

**Issue by noidexe** [photonstorm/phaser#842]
If you load a tilesprite from an atlas and use WebGL for rendering, you can see a faint seam were the tilesprite loops. It doesn't happen with Canvas. 
- The texture has crisp borders and proper paddding
- It happens at least on Chrome 34.0.1847.137(win7-64) and Firefox 30.0(win7-64)
- It affects at least Phaser 2.0.4 and 2.0.5
- It might be hard to notice if the texture is too complex or noisy

I'm adding an image in case the description isn't clear enough.
![tilesprite-seams](https://cloud.githubusercontent.com/assets/526829/3049578/09cd8084-e162-11e3-9885-ab63646f692d.png)

**Comment by gfordinal** [comment]
See this alternative for a different approach:

[Render Layer as Texture](https://github.com/sporadic-labs/tile-extruder/issues/36)
