### ISSUE TITLE
Passing values into tween onStart/onComplete

### ISSUE THREAD

**Issue by clowerweb** [photonstorm/phaser#846]
There should be a way to pass arguments into the functions called in tween.onStart() and tween.onComplete(). For example, I'm chaining multiple tweens from paths returned from A*:

```
findPath: function(chara, tileX, tileY) {
  [...]
  var started = function(arg1, arg2) { console.log(arg1, arg2); };

  this.pathfinder.setCallbackFunction(function(path) {
    var speed = (32 / chara.speed) * 1000;

    path         = path || [];
    chara.tweens = [];

    for(var i = 0, plen = path.length - 1; i < plen; i++) {
      var pathX = path[i + 1].x * 32;
      var pathY = path[i + 1].y * 32;

      chara.tweens[i] = game.add.tween(chara.body).to({ x: pathX, y: pathY }, speed, null, false);
      chara.tweens[i].onStart.add(started, i); // This is where I'd like to pass the tween's array position

      if (i > 0) {
        chara.tweens[i - 1].chain(chara.tweens[i]);
      }
    }

    [...]
}
```

Logged values are: arg1 = the character.body object, arg2 = null (should be the value of "i" from the loop). This is needed so I can set a "currTween" property on the character object, and put a block of code in my update function to add custom collision detection and pause/resume chara.tweens[chara.currTween].

**Comment by ignaciohita** [comment]
I don't like lewster32 solution, it's OK in some situations, but if "i" changes before the tween ends you will get an error.

I prefer this way:

        var myTween = game.add.tween(tweenTarget);

        myTween.to({
            alpha: 0
        }, 1000, Phaser.Easing.Quadratic.easeOut);

        myTween.onComplete.add(function (currentTarget, currentTween) {
        // Here currentTarget is a reference to tweenTarget, and currentTween is a reference to myTween,
        // even if I assign other values to tweenTarget and myTween before tween ends.
            tweenEnd(currentTarget);
        });

        myTween.start();

If you need reference to a property that is not in your tween target you can assign it dynamically before tween start like this:

        tweenTarget.property = whatever;

**Comment by cryptonomicon** [comment]
Even though closed I often find myself using IIFE immediately-invoked function expression with phaser  in this situation.

lets say I have a loop that is firing off some tweens and I want onComplete to do something with the original object.

What you do is have an outer function that executes immediately returning another function. The inner function will contain a reference to object as it was at the time it was called.

```javascript
for(var i=0;i<some_array.length;i++){
 
 var some_item=some_array[i];// we want some_item but because of the loop this will keep changing
                            //and we have no idea what it will be when the tween completes

 //set up a tween or it could be a timer or an event or any thing else that will do something 
// at some point in the future 
 var myTween = game.add.tween(tweenTarget);
   myTween.to({
        alpha: some_data
    }, 1000, Phaser.Easing.Quadratic.easeOut);

  //here is the magic.  setup the callback as usual using an anonymous function   
myTween.onComplete.add(function(magic_var){

         //the scope of this outer anonymous function contains magic_var. 
         //We will force the outer function to invoke immediately
         // which will return another anonymous function

           return function(){
                //this inner anonymous function is where our actual callback lives. 
                //Because it is defined inside the scope of the outer function it can access 
               //magic_var
                var X=magic_var.some_data; 
                //magic_var contains the value passed to it when the outer function was invoked
                //and of course we will pass some_item in
           };

  }(some_item));  //the brackets () causes the outer anonymous function to be invoked immediately  
                      //which captures some_item inside magic_var - in fact it means magic_var will hold.
                      // a reference to the some_item object used when the function was called 

                     //onComplete now contains the inner function which contains the some_item object
                    // as it was at the time it was created accessible via magic_var
}
```
