### ISSUE TITLE
Keep flying when collide with tile (improve Phaser.Physics.Arcade#processTileSeparationY)

### ISSUE THREAD

**Issue by casensiom** [photonstorm/phaser#992]
I would like to have the option to keep flying when hit the bottom of a tile in the midle of a jump.
A lot of games dont cut your jump when collide vertically, they just adjust your position, but dont modify your velocity, so you can jump holes in a tunnel:
https://www.youtube.com/watch?v=bkki4f5eISA#t=104

So the function _Phaser.Physics.Arcade#processTileSeparationY_ should have some options to avoid the velocity modification when you have no bounce.

```
	if (body.bounce.y === 0)
	{
		body.velocity.y = 0;
	}
	else
	{
		body.velocity.y = -body.velocity.y * body.bounce.y;
	}
```

should become to something similar to:
```
	if (body.bounce.y === 0)
	{
		if(this.TILEMAP_ALLOW_COLLISION_Y)
		{
			// only reset the velocity when we are falling to gravity
			// (velocity has the same sign that gravity)
			if((this.gravity.y < 0 && body.velocity.y < 0) ||
			   (this.gravity.y > 0 && body.velocity.y > 0))
				body.velocity.y = 0;
		}
		else
		{
			body.velocity.y = 0;
		}
	}
	else
	{
		body.velocity.y = -body.velocity.y * body.bounce.y;
	}
```

You should initialice this variable (Phaser.Physics.Arcade.TILEMAP_ALLOW_COLLISION_Y) to take effect, otherwise the script will behavior the same.

Maybe the same can be applied horizontally for non conventional games.

**Comment by photonstorm** [comment]
This is now directly supported in the dev branch of 2.3 (only nearly a year late, sorry!)
